### ISSUE TITLE
TensorFlow Addons in Colab

### ISSUE THREAD

**Issue by seanpmorgan** [googlecolab/colabtools#1005]
Firstly I want to say thanks for including TFA in the TF2 environment! This is a great help for users transitioning from TF1.x and helps build our community. We've ran into some issues though since the installed TFA is quite behind the most recent versions. 

Users can pip install upgrade the package, but this can create confusion regarding restarting runtimes etc. Would it be possible for us to notify the colab team of new releases and upgrade the package in the environment?

cc @craigcitro

- Describe the current behavior:
```
%tensorflow_version 2.x
import tensorflow_addons as tfa
tfa.__version__
```
`0.6.0`

- Link to self-contained notebook that reproduces this issue
https://colab.research.google.com/drive/1Oe0h9KPZaQxROnwFDHD_frXr9bHpAp_P

**Comment by colaboratory-team** [comment]
b/149748775

**Comment by seanpmorgan** [comment]
It looks as though the installation may be coming from TF-Federated:
https://github.com/tensorflow/federated/issues/799

**Comment by colaboratory-team** [comment]
tensorflow_addons is now version 0.8.2 in external colab:
![addons](https://user-images.githubusercontent.com/38081706/75069282-b9194700-54a5-11ea-8d4a-84b5af0d373e.png)

**Comment by colaboratory-team** [comment]
Colab now comes with tensorflow_addons v0.8.2 in the tensorflow 2.x environment:
![addons](https://user-images.githubusercontent.com/38081706/75069282-b9194700-54a5-11ea-8d4a-84b5af0d373e.png)

**Comment by kelvinkoh0308** [comment]
can colab team upgrade tf_addons to 0.12.0?
