### ISSUE TITLE
In Markdown, Colab confused between $ as character and $ as LaTeX start/end symbol

### ISSUE THREAD

**Issue by RagingRoosevelt** [googlecolab/colabtools#1008]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- **Describe the current behavior**:

Colab tries to compile markdown between `$` characters as LaTeX even when they are on different lines.

As an example
```
| Col 1| Col 2 | Col 3 |
| :--- | ---: | :--- |
| Val 1,1 | $0 | Val 1,3 |
| Val 2,1 | $0 | Val 2,3 |
```
should render as 

| Col 1| Col 2 | Col 3 |
| :--- | ---: | :--- |
| Val 1,1 | $0 | Val 1,3 |
| Val 2,1 | $0 | Val 2,3 |

but instead renders as 

![image](https://user-images.githubusercontent.com/6985440/74987089-451c6780-53ef-11ea-9c5c-0e67fb07bfde.png)

- **Describe the expected behavior**:

Colab should realize that it's rendering two separate lines in a table and that the `$` character is a symbol and not a markup character.  I believe that `$` should only be used for single-line LaTeX.  `$$` is for designating multi-line LaTeX.

- **The web browser you are using (Chrome, Firefox, Safari, etc.)**:

Chrome 80.0.3987.106

- **Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*)**:

https://colab.research.google.com/drive/1mTosG6VtHYHVXlMpQexrk-NdcdSDam2I

**Comment by blois** [comment]
Can escape with `\$`:

```markdown
| Col 1| Col 2 | Col 3 |
| :--- | ---: | :--- |
| Val 1,1 | \$0 | Val 1,3 |
| Val 2,1 | \$0 | Val 2,3 |
```

https://colab.sandbox.google.com/gist/blois/bbd67cfe31b4e458c4a89a52a9a45f1e/issue-1008.ipynb

**Comment by RagingRoosevelt** [comment]
Maybe it's a subjective opinion, but I think that escaping the `$` is a band-aid fix rather than a proper solution.  I don't think I've encountered any other markdown renderers that are LaTeX-aware that would identify single `$` across multiple lines as LaTeX escaping.  

If you work only within the Collaboratory ecosystem, sure, escaping the `$` works.  But, for instance, if you download your notebook file and then save it to a github repository, you'll have errant `\` characters rendered into your table.  I think an argument could be made that the markdown renderer used in Collaboratory should use a more commonized interpretation of markdown syntax.  Certainly not the only valid position but perhaps worth considering.

**Comment by RagingRoosevelt** [comment]
Actually, it looks like this is present in Jupyter, too.  So if you assume that it's a bug, it's not a Collaboratory issue.

**Comment by blois** [comment]
We do aim to be consistent with JupyterLab's behavior here- if the rendering is changed in JupyterLab then we should change it in Colab as well.

Github's rendering is oddly unfortunate as well: https://gist.github.com/blois/bbd67cfe31b4e458c4a89a52a9a45f1e#file-issue-1008-ipynb
