### ISSUE TITLE
unzip file size limit?

### ISSUE THREAD

**Issue by qgh1223** [googlecolab/colabtools#1009]
I can unzip the SKU110K.tar gz one and half an hour ago.And after the link broken,unzip command met bug: Cannot read: Input/output error.What happened?The file is about 11G

**Comment by tnovikoff** [comment]
Can you provide a notebook to reproduce the issue?

**Comment by qgh1223** [comment]
This problem has been solved.Now I can unzip it normally.

**Comment by Santosh-Gupta** [comment]
How did you solve the issue? I'm getting the same issue.
