### ISSUE TITLE
Can't import the gurobipy library

### ISSUE THREAD

**Issue by Gonzalo-Perez** [googlecolab/colabtools#101]
I am not able to import and use the gurobipy library. I guess it is not that simple because in order to use GUROBI I use an educational license from my university. Is there a way to import this library or to run this code in mi PC locally (without having to download or copy and paste the script)?
Thanks in advance!

**Comment by craigcitro** [comment]
No, I don't think there's any reasonable way to install software like gurobi in a colab VM and use your school's site license.
