### ISSUE TITLE
Feature Request: Increase number of cores available for Colab Pro

### ISSUE THREAD

**Issue by Santosh-Gupta** [googlecolab/colabtools#1012]
I am working with a data pipeline which will have some on the fly data processing. Having more CPU cores would be helpful in this case. 

I saw the benefits of Colab Pro, but I didn't see anything about increasing the number of CPU cores.

**Comment by tnovikoff** [comment]
Information about Colab Pro can be found in the Colab Pro FAQ:
https://colab.research.google.com/signup

See in particular the section on Memory (even though your question is not actually about RAM).

**Comment by Damien78600** [comment]
wrong, there is nothing about number of cores

**Comment by jaroslawjanas** [comment]
To anyone reading this in the future.
It seems that no matter what tier you are on, you end up with 2 virtual CPU cores.

I did not verify it myself but all the data from other sites seems to indicate it.
I'd say 2 CPU cores is quite limiting, especially for paid users.

There are other services that allow up to 8 CPU cores, which also tend to be better value per hour.

**Comment by malintha** [comment]
@jaroslawjanas Do you know what other services offer more CPU cores? I am in the same boat as you apparently..

**Comment by jaroslawjanas** [comment]
@malintha 
I am sure there are a few alternatives, google is your friend.
The only one I know of is Deepnote but there are others.
