### ISSUE TITLE
TPU not working at all

### ISSUE THREAD

**Issue by Tylersuard** [googlecolab/colabtools#1013]
Bug report for Colab: http://colab.research.google.com/.

Running this notebook: https://colab.research.google.com/github/tensorflow/models/blob/master/research/nst_blogpost/4_Neural_Style_Transfer_with_Eager_Execution.ipynb#scrollTo=vSVMx4burydi

- Describe the current behavior:
Training does not work at all.  It usually takes 5 minutes with a GPU.  I'm in the TPU runtime, and I've been here for 5 minutes and it hasn't even gone through the first epoch.

- Describe the expected behavior:
Supposedly the TPU is much faster than a GPU?  Not seeing that at all here, it doesn't even work so far.

- The web browser you are using (Firefox)

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/github/tensorflow/models/blob/master/research/nst_blogpost/4_Neural_Style_Transfer_with_Eager_Execution.ipynb#scrollTo=vSVMx4burydi

**Comment by colaboratory-team** [comment]
See https://colab.research.google.com/notebooks/tpu.ipynb for information on how to use tensorflow with a TPU backend.

**Comment by rosefeller** [comment]
Hi,
my email:rosefellerart@gmail.com
LinkedIn:Rose Feller
