### ISSUE TITLE
GPU back-end is not allocated.

### ISSUE THREAD

**Issue by pky5776** [googlecolab/colabtools#1016]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
![image](https://user-images.githubusercontent.com/48509484/75123908-e99ff180-56ee-11ea-8095-55a48789da5f.png)
Repeated attempts will not allocate GPU back-end. How can I be allocated back-end?

**Comment by tnovikoff** [comment]
Information about resource limits in Colab can be found at https://research.google.com/colaboratory/faq.html

**Comment by qo4on** [comment]
@pky5776 Have you managed to run GPU?

**Comment by pky5776** [comment]
​
I bought a colab-pro. Now it's using it without a problem.

-----Original Message-----
