### ISSUE TITLE
The GPU runtime takes x2 duration of no hardware acceleration

### ISSUE THREAD

**Issue by rorycawley** [googlecolab/colabtools#102]
The GPU runtime takes x2 duration of no hardware acceleration for a Keras LSTM

**Comment by pointyointment** [comment]
Maybe share a notebook that demonstrates the problem

**Comment by colaboratory-team** [comment]
Sorry, we aren't able to troubleshoot issues in code written in Colab. My recommendation is to ask a question on a more general-purpose forum like StackOverflow and to include relevant tags like 'tensorflow' to solicit advice from experts from that community.
