### ISSUE TITLE
Failed to assign a backend

### ISSUE THREAD

**Issue by vaibhav198** [googlecolab/colabtools#1022]
Hi,

When I am connecting the google collab, I'm getting an popup message since last 12 hours.

No backend with GPU available. Would you like to use a runtime with no accelerator?

![Screenshot from 2020-02-27 09-24-47](https://user-images.githubusercontent.com/25102603/75411110-1dc02000-5944-11ea-96a4-1d8638bba173.png)

Please suggest me something.

thanks

**Comment by qo4on** [comment]
Have you managed to run GPU instance?

**Comment by tnovikoff** [comment]
Information about resource limits in Colab can be found at https://research.google.com/colaboratory/faq.html

**Comment by qo4on** [comment]
I never used it for mining or long term computation. And 12 hours later GPU and TPU are still not available.

**Comment by Sanqiang** [comment]
same issue with me. I just wait for several hours. 
BTW, how do you define "long term computation", is 12/24 hours means long (i think VM disconnect around 12 hours)?

**Comment by qo4on** [comment]
I think "long term computation" is when you run gpu calculation for hours, train model, for example.

**Comment by hayupadhyaya** [comment]
This happened to me. I've run the GPU instance for less than an hour.(it was my first time using Colab) and I was kicked out.
Any solutions?

**Comment by vaibhav198** [comment]
Try after some time, you will get the GPU instance. At the moment, when you
were using the collab, it might be possible that all the free GPU resources
are in use.

Thanks
