### ISSUE TITLE
Upload button doesn’t work on a IPad 7

### ISSUE THREAD

**Issue by Blaizzy** [googlecolab/colabtools#1023]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: I click the upload button and it doesn’t work at all

- Describe the expected behavior: I want to upload local files

- The web browser you are using (Chrome, Firefox, Safari, etc.): safari, chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*): Any Colab

**Comment by blois** [comment]
I can repro this using the file browser in iOS, but not desktop Safari.

**Comment by Blaizzy** [comment]
Safari is now full Desktop browsing on IOS 13.3.1 for Ipads.

Even if try chrome, the button doesn't work.

**Comment by purudpd** [comment]
Using  the following snippet seems to work for small files (~70kb), but **only** on the safari browser on IPad:
```
from google.colab import files
uploaded = files.upload()
```
Upload button however doesn’t seem to work on any browser on IPad.
