### ISSUE TITLE
Cartopy is crashing google codelab

### ISSUE THREAD

**Issue by WXslaughter** [googlecolab/colabtools#1029]
Hi I am new to using codelab. I am trying to create a map with Cartopy, whenever I try to set the bounds of my map using: 

ax.set_extent([-90,-72, 20, 55])

The notebook crashes. Does anyone have any advice on how to fix this issue?

Thank you for your time/help.

**Comment by WXslaughter** [comment]
ax = = fig.add_subplot(1, 1, 1, projection=ccrs.LambertConformal())

**Comment by tnovikoff** [comment]
Can you provide a full repro notebook? Also if this is a Cartopy issue rather than a bug in Colab, the place to get an answer would be on StackOverflow.

**Comment by WXslaughter** [comment]
I uploaded the code to my weather depository as Cartopy_Issue I am also sorry about any delays in responding I live in Guam. Please let me know if you have any other suggestions or need any more information from me. Thank you!

**Comment by WXslaughter** [comment]
I also submitted the question to StackOverflow.

**Comment by colaboratory-team** [comment]
See https://github.com/SciTools/cartopy/issues/1346#issuecomment-558397297

**Comment by WXslaughter** [comment]
That fixed the issue have a great day and thank you for the help!

**Comment by josuemtzmo** [comment]
This comment is to leave a possible solution if someone wants to add custom features using `cartopy` on google codelab. The only way I managed to do it was by changing the directory to the root of the google codelab project.

```
import cartopy 
cartopy.config['data_dir'] = '/content'
cartopy.config['repo_data_dir'] = '/content'
```


which will create the following tree structure on the codelab project:

![directory tree](https://user-images.githubusercontent.com/9144063/89246189-e752a380-d64d-11ea-93ac-f4defa944a27.png)
