### ISSUE TITLE
Keep ask for sign in

### ISSUE THREAD

**Issue by kuronekony4n** [googlecolab/colabtools#1033]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
It always ask for sign in even I have already signed in. I cant connect at all and cant access all my notebook on drive. I try to sign-in using different account but still cant.
![Opera Snapshot_2020-03-02_001806_colab research google com](https://user-images.githubusercontent.com/38156932/75630277-d8d60b00-5c1b-11ea-98fb-8f06c7ce64fb.png)

- Describe the expected behavior:
You know what it is. 

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Opera GX

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by katlyn-edwards** [comment]
Hey there! That's a pretty interesting bug! 

Can you verify that other Google services also treat you as logged in? Specifically sites like Google Drive, and Gmail?

Additionally, does your email show up if you put `window.colabUserEmail` in the Chrome dev console?

**Comment by aqibahmad** [comment]
Hi there. I'm also experiencing this issue.

**Comment by ikros98** [comment]
Hello, I have the same issue.
> Hey there! That's a pretty interesting bug!
> dashed
> Can you verify that other Google services also treat you as logged in? Specifically sites like Google Drive, and Gmail?
> 
> Additionally, does your email show up if you put `window.colabUserEmail` in the Chrome dev console?

Yes, I can. Everything works except colab.

In the console putting `window.colabUserEmail`, I got:
`"anonymous"`

I tried with Google Chrome, Firefox and Safari (also with incognito mode), but I had the same issue

**Comment by aqibahmad** [comment]
When a group member tried using colab, he logged in, but the main-page of colab (with that demo notebook) was not showing his google account picture/name in the circle on top-right corner of page. Also, when he clicked on "upload notebook", it showed "Google sign-in required", even though he was signed in! 

As of now, he cannot access any notebook saved in his drive.

I'm also having a similar issue. My colab main page shows my google account id on top-right. But it is not allowing me to upload/access my notebooks. It says "google sign-in required" even though i'm signed in.

Seems to be system-wide issue!

**Comment by kuronekony4n** [comment]
> Hello, I have the same issue.
> 
> > Hey there! That's a pretty interesting bug!
> > dashed
> > Can you verify that other Google services also treat you as logged in? Specifically sites like Google Drive, and Gmail?
> > Additionally, does your email show up if you put `window.colabUserEmail` in the Chrome dev console?
> 
> Yes, I can. Everything works except colab.
> 
> In the console putting `window.colabUserEmail`, I got:
> `"anonymous"`
> 
> I tried with Google Chrome, Firefox and Safari (also with incognito mode), but I had the same issue

I got the same result. Still can't access the collab.

**Comment by kuronekony4n** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/38156932/75647574-f1780c80-5c7f-11ea-823a-6b61e1f43f01.png)

I got this massage when trying to open notebook from drive.

**Comment by UsmanTariqAlvi** [comment]
Facing this issue since last evening.

**Comment by kuronekony4n** [comment]
![Opera Snapshot_2020-03-02_160956_colab research google com pngaa](https://user-images.githubusercontent.com/38156932/75661811-93a7ec80-5ca0-11ea-9b7b-9d00f477f9cc.png)

**Comment by katlyn-edwards** [comment]
Does it persist if you clear your cookies?

**Comment by aqibahmad** [comment]
It exists -> across browsers, across accounts, across laptops. No way cookies can come into play. Has been happening for 2,3 days now. I cannot do anything at all.

Could be country or IP specific but I doubt so.

**Comment by blois** [comment]
Do you happen to have third-party cookies disabled?

**Comment by blois** [comment]
Just noticed "across browsers, across accounts, across laptops". Looking more.

**Comment by katlyn-edwards** [comment]
Can you delete the SSID cookie (on colab.research.gooogle.com), and hard reload the page?

**Comment by blois** [comment]
Related is https://stackoverflow.com/questions/60323236/colab-notebook-crash-restart-cycle-followed-by-autosave-failures-and-invalid-c

**Comment by UsmanTariqAlvi** [comment]
Any success guys ?

**Comment by kuronekony4n** [comment]
![Opera Snapshot_2020-03-03_160305_settings](https://user-images.githubusercontent.com/38156932/75759812-bd2c4b00-5d68-11ea-9605-3097755b9eee.png)
Ok so I clear all my cookies and it works :D 
And got logged out from all websites :(
My mistake

**Comment by UsmanTariqAlvi** [comment]
not in my case.. Its not working after clearing everything.

**Comment by kuronekony4n** [comment]
> not in my case.. Its not working after clearing everything.

Try with different account

**Comment by aqibahmad** [comment]
The issue seems to be resolved for me now.

**Comment by blois** [comment]
Another item to try if this happens is to sign out then sign back in from your Google account.

**Comment by edercoelho** [comment]
I got the same message and found the solution here: https://github.com/googlecolab/colabtools/issues/1065#issuecomment-605486998
