### ISSUE TITLE
Colab cells both text or code doesn't take inputs from key board if I switch to the new editor. 

### ISSUE THREAD

**Issue by autonamaskar** [googlecolab/colabtools#1036]
Colab cells both text or code doesn't take inputs from the keyboard if I switch to the new editor. Now I don't even see the experiment button so I can switch to the old editor which seems to work fine.
Not sure why I am experiencing this issue.
New editor never seems to work for me - Not sure If I have to change some system settings.

I am using Windows 10 PC (HP ENVY)

I tested in another PC and there I don't see any issue using typing in code and data cell with the new editor. It seems some problem with my PC. It works everywhere like comments section but can't type anything code or text cell in collab.

Regards,
Suneet Sharma

Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by autonamaskar** [comment]
I am using Colab on Chrome

**Comment by blois** [comment]
Can you try an incognito window? It could be a chrome extension causing issues.

**Comment by autonamaskar** [comment]
Thanks for the feedback. Some of the chrome extensions were creating issues. all works now.
