### ISSUE TITLE
cv2_imshow fails to display rescaled images from ImageDataGenerator in Keras.

### ISSUE THREAD

**Issue by Sreerag-ibtl** [googlecolab/colabtools#1037]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I created a keras ImageDataGenerator with rescale=1/255.0. I tried displaying each image from the generator using cv2_imshow. The displayed image is full black. I tried imshow in matplotlib, the same image is displayed well.

- Describe the expected behavior:
A normalized image was expected

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
Since the my code as of now is little difficult run for others, I am not sharing a link. Instead this can be checked by giving a test image to data generator.

**Comment by purudpd** [comment]
When you use _rescale=1/255.0_ , it essentially normalizes your image to the range [0,1]. 

The image needs to be rescaled back to a range of [0,255] to display it using cv2.imshow( ). I was able to reproduce your issue using the following code:

Image in the range [0,1]
`image = np.random.uniform(size = [300,300], low = 0.0, high = 1.0)`

Rescale image to range [0,255]
`image = (image*255).astype(np.uint8)`

Display image
`cv2.imshow('Display',image)`
`cv2.waitKey(0)`

See if this works for you. Also, Stackoverflow would be a better forum for this type of questions.

**Comment by Sreerag-ibtl** [comment]
Thanks for your suggestions. I know rescaling back to the  range [0,255] can work. But my intention was to see how the images looks after the augmentations. As I already mentioned, matplotlib.pyplot.imshow is displaying rescaled images properly. Also I was not mentioning cv2.imshow but google.colab.patches.cv2_imshow.
