### ISSUE TITLE
python pillow is compiled with libraqm

### ISSUE THREAD

**Issue by muayyad-alsadi** [googlecolab/colabtools#1044]
- Describe the current behavior:

Python Pillow `draw.text()` is not compiled with libraqm, direction='rtl' is passed to it

```
KeyError: 'setting text direction, language or font features is not supported without libraqm'
```

RTL text is not rendered properly because this library is not compiled.

- Describe the expected behavior:

-- libraqm enabled
-- being able to pass `direction='rtl'`
-- RTL (like Arabic) is rendered correctly

here is a screenshot showing the correct behavior as seen on my fedora box

![Screenshot from 2020-03-04 15-30-21](https://user-images.githubusercontent.com/1312683/75884236-1f4e8400-5e2d-11ea-9d16-166fd390191d.png)

- Link to self-contained notebook that reproduces this issue

https://colab.research.google.com/drive/1VarbNFk0n5HyVQlD6cBInuqzQACXNqjM

**Comment by tnovikoff** [comment]
Tracking internally at b/151467662

**Comment by metrizable** [comment]
@muayyad-alsadi Thanks for filing the issue and providing a minimal repo notebook. I believe we are showing the correct behavior now.

![6TMUhk6vUZcYHCq](https://github.com/googlecolab/colabtools/assets/65414824/e590316d-e63b-4a20-a7b1-7722092842ca)

As an aside, modern versions of Pillow that Colab is now on links to [libraqm at runtime](https://github.com/python-pillow/Pillow/blob/8.4.0/docs/installation.rst#linux-installation), when available.
