### ISSUE TITLE
googlecolab 'mxnet' module missing error 

### ISSUE THREAD

**Issue by Army1996** [googlecolab/colabtools#1048]
from mxnet import np, npx
npx.set_np()
np.clip(0.5, 0.1,1.0)

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-38b452851014> in <module>()
----> 1 from mxnet import np, npx
      2 npx.set_np()
      3 np.clip(0.5, 0.1,1.0)

ModuleNotFoundError: No module named 'mxnet'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by colaboratory-team** [comment]
You can install mxnet using
```
!pip install mxnet
```
