### ISSUE TITLE
Would you mind to install custom widget called  nglview to molecular protein representation in colab notebooks

### ISSUE THREAD

**Issue by alvarosf** [googlecolab/colabtools#1049]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).
Would you mind to install custom widget called  nglview to molecular protein representation in colab notebooks
- Describe the current behavior:
after installing it with 
  pip install nglview
 and ended with
Building wheels for collected packages: nglview
  Building wheel for nglview (setup.py) ... done
  Created wheel for nglview: filename=nglview-2.7.4-cp36-none-any.whl size=5963883 sha256=eb71e8b122f7f548545877117a18314eb491f0bb8994d5f2a862f7a430e374a7
  Stored in directory: /root/.cache/pip/wheels/bc/32/29/783bb9fc3603d92796663d828e815fd41a1cd9fe9887beb8f1
Successfully built nglview
Installing collected packages: nglview
Successfully installed nglview-2.7.4

import nglview as nv
import ipywidgets
import notebook
print(nv.__version__)
print (ipywidgets.__version__)
print (notebook.__version__)

2.7.4
7.5.1
5.2.2

view = nv.show_pdbid("6vww")
view

Colab does not execute it and keep trying

- Describe the expected behavior:
To see the molecular structure of an interesting protein from covid-19 coronavirus

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Firefox
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1G0YSK4BjTGHLl0nGMt4qOf7wbQ7H_NsM#scrollTo=txtGBGuhuI5F

**Comment by tnovikoff** [comment]
Tracking internally at b/151467658

**Comment by colaboratory-team** [comment]
This would require support of custom ipywidgets, which is not yet available in Colab. See #60 and #498 for details.

**Comment by kiranchhetri1** [comment]
#1077

**Comment by AaronFeller** [comment]
Is this still being looked at? I'm _very_ interested in it working. Show some love for folks on the bio side.
