### ISSUE TITLE
not able to easily open .ipynb files without having to mount whole google drive

### ISSUE THREAD

**Issue by kirk86** [googlecolab/colabtools#1051]
This might sound like a naive question but I'm finding the missing feature of easily opening `.ipynb` notebooks very annoying.

- Describe the current behavior:
git clone projectA
projectA contains a bunch of files `{.py, .R, .ipynb}`
one can easily open `{.py, .R}` files from the file explorer on the left side of colab by double-clicking on each file.
The same behavior does not extend to `.ipynb`

- Describe the expected behavior:
Simply double-click on any `.ipynb` notebook and open it like jupyter does.

- The web browser you are using (Chrome):

- Link to self-contained notebook that reproduces this issue
any git repo that contains a .ipynb inside is enough to replicate the issue

**Comment by blois** [comment]
Colab separates the notebook from the execution environment and does not have the ability to edit notebooks from the VM that you are executing on. Our focus has been on loading from central repositories of persistent notebooks (Drive or GitHub) with execution on ephemeral VMs. Loading directly from the ephemeral VM brings in many issues (starting with persistent notebook URLs, then accessing notebooks when the VM has been recycled).
