### ISSUE TITLE
StarCraft 2 segfaults due to TCMalloc LD_PRELOAD

### ISSUE THREAD

**Issue by n0madsky** [googlecolab/colabtools#106]
Hello

I've been trying to get PySC2 working on Google Colab in order to run my StarCraft 2 machine learning models

In the current state, the following message is printed when trying to run StarCraft II
```
Segmentation fault (Core Dumped)
```

After a seriously painful debugging session. I've discovered that the problem was tcmalloc
Removing TCMalloc before running Starcraft 2 worked. So I am using this temporary workaround to run my Starcraft 2 machine learning models.

I've got a working colab notebook here to reproduce the situation.
https://colab.research.google.com/drive/1GLSGSaLesUly-Z5jqXTiq-8NTk4F2h0w

Suggestion:
Either give an option to disable TCMalloc, or an option to uninstall it.

**Comment by colaboratory-team** [comment]
We're going to stick with tcmalloc for now. Thanks for sharing the workaround. My recommendation is to follow up with the library maintainers regarding tcmalloc compatibility for the library.
