### ISSUE TITLE
block field of view

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#1064]
- Describe the current behavior:
after I ctrl+click, new file open, but after I close it, text behind that new file screen gets hidden
I attach example
[fov.zip](https://github.com/googlecolab/colabtools/files/4333849/fov.zip)

- Describe the expected behavior:
text behind new file open screen do not disappear

**Comment by blois** [comment]
Thanks- tracking in b/151553709

**Comment by blois** [comment]
The fix should be out in a few days.
