### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'placeholder'

### ISSUE THREAD

**Issue by mhlhr** [googlecolab/colabtools#1066]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I am using Tensorflow  2.1.0 with eager execution enabled. However, I am getting follwing error when I try to define a NN using Keras functional API.

AttributeError                            Traceback (most recent call last)
<ipython-input-27-aa800bcd222d> in <module>()
      1 
----> 2 encoder_input = Input(shape=(28, 28, 1), name='original_img')
      3 
      4 x = Conv2D(32, (3, 3), activation='relu', padding='same', name='CONV2D_1')(encoder_input)
      5 x = MaxPooling2D((2, 2), padding='same', name='MaxPooling2D_1')(x)

3 frames
/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py in placeholder(shape, ndim, dtype, sparse, name)
    539         x = tf.sparse_placeholder(dtype, shape=shape, name=name)
    540     else:
--> 541         x = tf.placeholder(dtype, shape=shape, name=name)
    542     x._keras_shape = shape
    543     x._uses_learning_phase = False

AttributeError: module 'tensorflow' has no attribute 'placeholder'

- Describe the expected behavior:

The same code works on my local machine using Tensorflow GPU.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by jsnydes** [comment]
could you provide a link to a publicly shared notebook that reproduces the problem? what is the output of tf.__version__?

**Comment by jsnydes** [comment]
closing as not reproducible. I suspect you need to add "%tensorflow_version 2.x" to the top of your notebook as I suspect you aren't using tensorflow 2 (colab is still tf1-by-default for the next week or so). feel free to re-open if you have a repro notebook.

**Comment by 123Pioneer** [comment]
![image](https://user-images.githubusercontent.com/24351632/87003218-d305bd00-c1ed-11ea-970c-d3203e95788f.png)
![image](https://user-images.githubusercontent.com/24351632/87003285-ef095e80-c1ed-11ea-8b53-53705737f35f.png)
I have the same error  and I dont know how to resolve it
