### ISSUE TITLE
GPU runtime dies when training Keras model

### ISSUE THREAD

**Issue by rohitchaudhri** [googlecolab/colabtools#107]
I'm trying to train a Keras CNN model on the CIFAR10 dataset on colab using a GPU runtime. When I call the model.fit method, I always get a message saying that the runtime died & it doesn't seem that training even starts. I have this issue only on GPU, works fine on CPU. My notebook is available here:
https://colab.research.google.com/drive/19jJJkLWY4Lqlmy16wHdIEcHd-pncVHgN

I followed these instructions to install Keras:
https://www.kdnuggets.com/2018/02/google-colab-free-gpu-tutorial-tensorflow-keras-pytorch.html 

I saw a similar issue reported here: https://github.com/googlecolab/colabtools/issues/28
seems that this issue couldn't be reproed so it was closed.

would appreciate any help with this.
thanks

**Comment by Thaumaturgy** [comment]
May I know where you keep the images? My notebook can't even find the images in my drive.

**Comment by rohitchaudhri** [comment]
the cifar10 dataset is included in keras. when i run my code, the dataset gets downloaded to the colab vm that is running my notebook. 
Using information from [this notebook](https://colab.research.google.com/notebooks/io.ipynb) i was able to download models to my google drive and local machine. i'm guessing that uploading/reading data might be similar.

**Comment by charlesverdad** [comment]
I just experienced this problem as well. I noticed it first when I made a copy of my notebook. The original still works, but the copy's runtime dies (and restarts) upon reaching the `model.fit` keras line.

**Comment by khaledbnmohamed** [comment]
> I just experienced this problem as well. I noticed it first when I ran "save and pin revision" and made a copy of my notebook. The original still works, but the copy's runtime dies (and restarts) upon reaching the `model.fit` keras line. No stack trace or any error messages.
> 
> I'm using Python 3 with GPU runtime.
> 
> Update: I tried copying a new notebook and got a stack trace. It seems my problem occurs when running a notebook immediately after copying it. #156

Did you find solution for this problem ?

**Comment by rohanchidrewar05** [comment]
I was able to solve the problem by following the article
[https://medium.com/@qiaozhang/i-got-an-error-message-that-the-colab-runtime-died-when-i-used-gpu-as-model-context-27dafb0d854e](url)
