### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'contrib'

### ISSUE THREAD

**Issue by Polarbeargo** [googlecolab/colabtools#1070]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
While run 
`
!apt-get install protobuf-compiler python-pil python-lxml python-tk  
!pip install Cython  
!git clone https://github.com/tensorflow/models.git  
%cd /content/models/research  
!protoc object_detection/protos/*.proto --python_out=.    
%set_env PYTHONPATH=/content/models/research:/content/models/research/slim  
!python object_detection/builders/model_builder_test.py`
Suddenly shows `AttributeError: module 'tensorflow' has no attribute 'contrib'`.  

![98](https://user-images.githubusercontent.com/8589224/76920337-38176900-6906-11ea-8883-d05ddb7ef849.png)

- Describe the expected behavior:
Yesterday working fine no error as above like following image:  
![88](https://user-images.githubusercontent.com/8589224/76920461-80368b80-6906-11ea-8520-1245123a035f.png)
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):  
https://colab.research.google.com/drive/1mak9Fa8b-ida-U3dW1ZW3h9HFnwyX001

**Comment by jsnydes** [comment]
sounds like an underlying image change means you're using tensorflow 2 instead of tensorflow 1. what happens if you add %tensorflow_version 1.x to the top of your notebook?

**Comment by jsnydes** [comment]
https://colab.research.google.com/drive/1FEJIseqjZLK9A-uFYIPNh9dqrcf0WKA5

**Comment by yev-d** [comment]
Hold on a sec, all of the solutions posted on the net point to using tensorflow 1.x. I don't get it. We are well into tensorflow 2.x, trying to migrate all the outdated modules over... going backwards seems counterproductive. Isn't there a solution (disregarding its complexity) to keep using tensorflow 2.x and fix this issue with contrib ?

**Comment by jsnydes** [comment]
I'm not sure what you mean. tf.contrib was dropped from 2.x: https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md

we as colab team don't control what tensorflow team does, and that decision was made in 2018

**Comment by yev-d** [comment]
@jsnydes, ah, got it. My bad. I didn't realize I was at the colab :).
I'm just trying to use object detection with tensorflow 2.x but run into the deprecated codes where the solution is to downgrade tensorflow. So I'm just hoping to find someone who can solve the issue of object detection with tensorflow2. 
Though I think I am in the wrong thread. Sorry.

**Comment by Polarbeargo** [comment]
Thank you @jsnydes :)!

**Comment by wassim-henia** [comment]
![image](https://user-images.githubusercontent.com/51765101/77260219-fd575d00-6c86-11ea-99d6-7f58a1d8f440.png)
I'm having the same problem and I did that but still doesn't work 
![image](https://user-images.githubusercontent.com/51765101/77260242-1bbd5880-6c87-11ea-8c23-375c42c1f8b6.png)

**Comment by jsnydes** [comment]
can you share a minimal notebook that reproduces your problem?

**Comment by wassim-henia** [comment]
well here is my full notebook where there is the problem 
https://colab.research.google.com/drive/1kWZCqIThUauxtxuorDyvlrs-o4XaX5nt#scrollTo=W1sucd7s_gR_

**Comment by jsnydes** [comment]
I can't use that notebook to reproduce the problem as it accesses data in your google Drive.

however, I believe the problem is you accidentally added a space to PYTHONPATH:
`os.environ['PYTHONPATH'] = ':../content/:../content/slim/: '+os.environ['PYTHONPATH']`
should be
`os.environ['PYTHONPATH'] = ':../content/:../content/slim/:'+os.environ['PYTHONPATH']`

**Comment by wassim-henia** [comment]
thank you so much it works now

**Comment by mszargoosh** [comment]
> 
> 
> https://colab.research.google.com/drive/1FEJIseqjZLK9A-uFYIPNh9dqrcf0WKA5





> 
> 
> https://colab.research.google.com/drive/1FEJIseqjZLK9A-uFYIPNh9dqrcf0WKA5

I'm having the same problem and I did that but still doesn't work.

  Traceback (most recent call last)
<ipython-input-2-8a58cc6d1998> in <module>()
    104 
    105 
--> 106 train()

7 frames

<ipython-input-2-8a58cc6d1998> in train()
     35     tra_image_batch, tra_label_batch = input_data.read_galaxy11(data_dir=train_dir,
     36                                                                 label_dir=train_label_dir,
---> 37                                                                 batch_size= BATCH_SIZE)
     38     val_image_batch, val_label_batch = input_data.read_galaxy11_test(data_dir=test_dir,
     39                                                                      label_dir=test_label_dir,

/content/input_data.py in read_galaxy11(data_dir, label_dir, batch_size)
    114 
    115 
--> 116     image,label=get_images(data_dir,label_dir)
    117 
    118     # data argumentation

/content/input_data.py in get_images(data_dir, label_dir)
     15     with tf.name_scope('input'):
     16 
---> 17         label=pd.read_csv(label_dir)
     18         index1=label['GalaxyID']
     19 

/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    674         )
    675 
--> 676         return _read(filepath_or_buffer, kwds)
    677 
    678     parser_f.__name__ = name

/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    446 
    447     # Create the parser.
--> 448     parser = TextFileReader(fp_or_buf, **kwds)
    449 
    450     if chunksize or iterator:

/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py in __init__(self, f, engine, **kwds)
    878             self.options["has_index_names"] = kwds["has_index_names"]
    879 
--> 880         self._make_engine(self.engine)
    881 
    882     def close(self):

/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py in _make_engine(self, engine)
   1112     def _make_engine(self, engine="c"):
   1113         if engine == "c":
-> 1114             self._engine = CParserWrapper(self.f, **self.options)
   1115         else:
   1116             if engine == "python":

/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   1889         kwds["usecols"] = self.usecols
   1890 
-> 1891         self._reader = parsers.TextReader(src, **kwds)
   1892         self.unnamed_cols = self._reader.unnamed_cols
   1893 

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] File My Drive/drive/train_label.csv does not exist: 'My Drive/drive/train_label.csv'

**Comment by pbanikk** [comment]
[https://www.tensorflow.org/api_docs/python/tf/compat/v1/nn/rnn_cell/BasicLSTMCell](url)
The only workaround if you want to use Basic LSTM Cell.
