### ISSUE TITLE
installing jupyter extentsion points to the EOL python 2.7 dist-packages

### ISSUE THREAD

**Issue by koyo-jakanees** [googlecolab/colabtools#1072]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I am trying to install a notebook extension but the shell ```jupyter nbextension enable --py --sys-prefix keplergl``` points to python2.7 dist-packages which is weird. the extension is to enable kepler gl visualization widgets
- Describe the expected behavior:
maanaged to install the keplergl module but enabling extensions can't be enabled
load keplergl widgets as described [here](https://github.com/keplergl/kepler.gl/blob/master/docs/keplergl-jupyter/user-guide.md)
step to reproduce ```!jupyter nbextension install --py --sys-prefix keplergl!jupyter nbextension enable --py --sys-prefix keplergl```
- The web browser you are using (Chrome, Firefox, Safari, etc.):
chrome
- Link to self-contained notebook that reproduces this issue
[link](https://colab.research.google.com/drive/1b7By6NULVUZPaJ4Nh6RpQbsz2fTblSBj#scrollTo=0aHDZz-qpihc&line=1&uniqifier=1)
  (click the *Share* button, then *Get Shareable Link*):

**Comment by koyo-jakanees** [comment]
if i do ```!pip2 install keplergl``` and  after ```!jupyter nbextension install --py --sys-prefix keplergl!jupyter nbextension enable --py --sys-prefix keplergl```  the extension is enabled. just thought it a bit weird

**Comment by merrcury** [comment]
I have also faced the same issue when I am trying to use `fileupload` & This pip2 method didn't help.

**Comment by blois** [comment]
Jupyter notebook extensions (nbextensions) do not work in Colab- they are extensions for classic Jupyter notebook.

Installing the nbextension will make the resources available from the kernel though, so you can do:

```python
from IPython.display import HTML

HTML('''
<script src="/nbextensions/keplergl-jupyter/index.js"></script>
''')
```

@merrcury If you are looking to upload files then take a look at https://colab.research.google.com/notebooks/io.ipynb#scrollTo=BaCkyg5CV5jF.
