### ISSUE TITLE
Google Colab: playground mode vs “normal mode”

### ISSUE THREAD

**Issue by AdityaGovardhan** [googlecolab/colabtools#1075]
When a person shares a Google Colab notebook with me, it is opened in playground mode and it shows a button for "Copy to Drive", on clicking this it opens another window with same code which I call the "normal mode".

Playground mode has Tesla P4 GPUs while "normal mode" has Tesla T4 GPUs (leading to CUDA out of memory in playground mode while running properly in "normal mode"), which I found after hours of debugging and there is no mention of this in the references I came across. Why is there a difference between these two modes/environments?

**Comment by colaboratory-team** [comment]
See https://research.google.com/colaboratory/faq.html#gpu-availability:

> The types of GPUs that are available in Colab vary over time. This is necessary for Colab to be able to provide access to these resources for free. The GPUs available in Colab often include Nvidia K80s, T4s, P4s and P100s. There is no way to choose what type of GPU you can connect to in Colab at any given time.
