### ISSUE TITLE
Some scripts are not executing in colab, running fine in terminal 

### ISSUE THREAD

**Issue by ejri** [googlecolab/colabtools#1079]
- Describe the current behavior:
Importing a dataset from the gdc.cancer.gov website

steps to reproduce:

 this is repo that helps import datasets from gdc.cancer.gov, cloning repo, installations, etc... 

````
!git clone https://github.com/NCI-GDC/gdc-client.git
!pip install -r gdc-client/requirements.txt
!python setup.py install
!pip install -r gdc-client/dev-requirements.txt
````

However, downloading the datasets into colab doesn't work. There's no output (no files downloaded, no progress bars, etc..). Tried different variations of making sure that all the files and subfiles are added to the path. 

`!sh gdc-client download -m gdc_manifest_20200323_185845.txt`

The code runs in terminal, there are files being downloaded, progress bars, etc..

All other shell scripts I tried appear to be working and executing just fine. 
example:
````
%%writefile simple_shell_script.sh
echo "This is a shell script"
!ls
!bash simple_shell_script.sh
````

Any suggestions?

**Comment by craigcitro** [comment]
I'd try asking on the repo for the project you're trying to use.

**Comment by jakevdp** [comment]
It looks like you're trying to run the setup script outside the source directory. This works for me:
```
!git clone https://github.com/NCI-GDC/gdc-client.git
!cd gdc-client && pip install -r requirements && pip install .
!gdc-client --help
```
