### ISSUE TITLE
Plotting some graphs larger than designated figsize

### ISSUE THREAD

**Issue by hobediente** [googlecolab/colabtools#1083]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior: Plotting some graphs larger than designated figsize

- Describe the expected behavior: Plot graphs the correct figsize 

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/18x1-YqJ-F1L4XszOH1wGPe9-BDC-on4z

**Comment by hobediente** [comment]
<img width="1630" alt="Screen Shot 2020-03-24 at 3 52 25 PM" src="https://user-images.githubusercontent.com/57720623/77471258-538fe180-6de8-11ea-858e-9d8af0796327.png">

<img width="1680" alt="Screen Shot 2020-03-24 at 3 52 32 PM" src="https://user-images.githubusercontent.com/57720623/77471270-5985c280-6de8-11ea-8db8-9f09e8c40f2a.png">

The above images are screenshots of plots from the linked notebook. Notice how both plots are supposed to print as figsize(10,5) but one is huge.

**Comment by blois** [comment]
Note that JupyterLab renders images with a max-width of 100%.

**Comment by blois** [comment]
`plt.figure` does not constrain the text being displayed to the area.

An example of this is a cell of just:
```python
plt.figure(figsize=(10,5))
plt.text(0, 3, 'something',
             color='red',
             fontdict={'weight': 'bold', 'size': 50},
        )
```

In the meantime we're also looking at improving the default rendering of larger images.
