### ISSUE TITLE
Colab seems like cannot import tensorflow 1.4

### ISSUE THREAD

**Issue by Sanqiang** [googlecolab/colabtools#1089]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

Once I install tensorflow 1.4, the "import tensorflow" directly raise an error:
ImportError: cannot import name 'export_saved_model'

- Describe the expected behavior: should import correctly. and the same code works before.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1Jr0j_I_npKQxcQ1ggJQFHTqoJHmt9Bqk

**Comment by jsnydes** [comment]
sorry, problem is that installing tensorflow-gpu does not uninstall tensorflow and tensorflow 2.2.0 has introduced some changes that are incompatible with tensorflow 1.14.0.

if you do 

```%tensorflow_version 2.x
!pip uninstall -y tensorflow
!pip install tensorflow-gpu==1.14.0```

it will work
