### ISSUE TITLE
NumPy UltraQuick Tutorial

### ISSUE THREAD

**Issue by Readysoon** [googlecolab/colabtools#1092]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

When doing Task 2 and even inserting the solution I get a huge table with numbers like 
[-1.03799777  1.18692501 -0.21298688  0.28180928  1.27637995  1.2276173
 -0.96114212 -1.7133726   1.34400002  0.68396425  0.59283102  0.73580741
 -1.37387939 -1.6859322   1.25733414]
[[[[ 76.86854417 106.72959721 103.61529121 ... 149.79836909
    140.16796323 143.92824245]
   [ 76.22029493 106.19863018 104.08008184 ... 149.5580585
    140.70905955 144.60182011]
   [ 76.38262883 106.4768985  104.08553818 ... 149.68325416
    140.01284173 144.40540324]
   ...

- Describe the expected behavior:

I expect to get an output like the solution tells me:
 
[ 1.24674723 -1.61229857  0.35459573  0.74910582 -0.32050834 -0.58922991
  1.48855156 -0.49079274 -1.58361229 -1.59558797  1.29648719  1.38813291
  0.36295871  1.08857235  0.9782751 ]
[23.24674723 23.38770143 28.35459573 31.74910582 33.67949166 36.41077009
 41.48855156 42.50920726 44.41638771 47.40441203 53.29648719 56.38813291
 58.36295871 62.08857235 64.9782751 ]

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Firefox

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/github/google/eng-edu/blob/master/ml/cc/exercises/numpy_ultraquick_tutorial.ipynb

**Comment by sandersk** [comment]
This goes to Barry, @jugglerix.

**Comment by metrizable** [comment]
@Readysoon Thanks for filing the issue. There have been several package and ecosystem upgrades since it has been filed, including `numpy`. I tried your example notebook and the issue looks to be resolved.

![7hRxRYWG4Ry5e96](https://user-images.githubusercontent.com/65414824/224066310-d0f88b62-1915-4d01-9b61-2b5030f17a66.png)
