### ISSUE TITLE
Module not found tensorflow.contrib

### ISSUE THREAD

**Issue by LolMenn** [googlecolab/colabtools#1093]
Bug report for Colab: http://colab.research.google.com/.
- Describe the current behavior:
      ~Google Colab says that the tensorflow.contrib module doesn't exist.

- Describe the expected behavior:
      ~ Run all the code without problems

- The web browser you are using (Chrome, Firefox, Safari, etc.):
     ~ Chrome

![image](https://user-images.githubusercontent.com/61662858/77813083-35421400-707c-11ea-9605-00636799f535.png)

**Comment by jsnydes** [comment]
we recently switched the default version of tensorflow from 1.15.2 to 2.2.0rc1. TensorFlow 2 does not have the contrib module. To use TensorFlow 1, add `%tensorflow_version 1.x` before your imports.
