### ISSUE TITLE
CD command not working

### ISSUE THREAD

**Issue by Monster-Gaming-Studios** [googlecolab/colabtools#1094]
### `cd` not working
 - Describe the current behavior:
        When using `!cd` command, the directory does not change

 - Describe the expected behavior:
    The directory should have changed

- The web browser you are using (Chrome, Firefox, Safari, etc.):
    Chrome

- How to Reproduce:
`!git clone https://github.com/matterport/Mask_RCNN.git`
` !cd Mask_RCNN`
 `!python setup.py install`

**Comment by colaboratory-team** [comment]
See #40
