### ISSUE TITLE
Inappropriate starting index in ordered list

### ISSUE THREAD

**Issue by qbx2** [googlecolab/colabtools#11]
![image](https://user-images.githubusercontent.com/5977817/34364003-aedddc26-eac4-11e7-9164-b6faf16a1a74.png)

Related specification: [start number](http://spec.commonmark.org/0.27/#start-number). Minimal example:

2. second item

Rendered as:

1. second item

**Comment by craigcitro** [comment]
We use marked.js, not commonmark, so this is (unfortunately) working as intended.

More info on markdown in colab is in [this sample notebook](https://colab.research.google.com/notebook#fileId=/v2/external/notebooks/markdown_guide.ipynb). It's possible that the [smartLists](https://github.com/chjj/marked#smartlists) option could make this work, but we'd have to set that in the UI (you couldn't do it yourself).

**Comment by craigcitro** [comment]
Ah, I take back my comment about `smartLists`: this doesn't seem to help, unfortunately.

**Comment by blois** [comment]
This is a limitation of marked.js, see: https://github.com/chjj/marked/issues/665.

A workaround is to use an HTML ordered list in the markdown:

```html
<ol start="2">
  <li> test </li>
</ol>
```
