### ISSUE TITLE
Slow to load images from my google drive

### ISSUE THREAD

**Issue by dhavalmj007** [googlecolab/colabtools#110]
I've recently tried using Colab for CNNs. I'm trying to use the files that I've saved in my google drive. But the loading time of the files are very high and at the end the notebook crashes. 

Any help on this?

Thanks

**Comment by pointyointment** [comment]
How are you connecting to Google Drive?

**Comment by dhavalmj007** [comment]
I'm using this first to authenticate 
`!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}`

then this to mount drive
`
!mkdir -p drive
!google-drive-ocamlfuse drive
`

**Comment by colaboratory-team** [comment]
I'd recommend trying the bundled Drive client like so:

```
from google.colab import drive
drive.mount('/content/gdrive')
```

If you encounter issues working with Drive files, please open a new issue describing what you tried and the precise error message you observed.

**Comment by LeonardoLed** [comment]
Hi There, I am trying to load my database via Google drive. I have 8,000 images but when I try to load my database in order to use like a entry data to CNNs. It is too slow, given an example, the same code in Laptop this function runs 1 minute aprox. but in colab more than  one hour. 
Do you know what is the problem about that?

The drive cliente is:

from google.colab import drive
drive.mount('/content/drive')

and the code is

`def create_training_data():
    count = 0
    
    for category in CATEGORIES:
        print(category)
        path = os.path.join(DATADIR, category)
        class_num = CATEGORIES.index(category)
        flag = 0
        for img in os.listdir(path):
            try:
                
                img_array = cv2.imread(os.path.join(path,img))
                
                """
                #training_data.append(img_array)
                if flag == 0:
                  flag = 1
                  training_data = np.array(img_array)
                #label_data.append(class_num)
                else:
                  training_data = np.concatenate([[training_data],[img_array]])
                 """
                count +=1
                if count == 100:
                  count=0
                  print("cargue 100 imagenes")
            except Exception as e:
                pass
          
          

    xTrain, xTest, yTrain, yTest = train_test_split(training_data, label_data, test_size = 0.25, random_state = 0)
    xTrain = np.array(xTrain)
    xTest = np.array(xTest)
    yTrain = np.array(yTrain)
    yTest = np.array(yTest)
    return (xTrain, yTrain), (xTest, yTest)
`

**Comment by NeonGod314** [comment]
Hi,
I'm having the save issue.
To load the data, Im doing 
```
from google.colab import drive
drive.mount("/content/drive/")
```
and then iterating over the images in folder using glob and loading them using OpenCV. This is quite fast in my local system which has 7 years old i7 and 16gb ram. But on colab, the data loading is ridiculously slow.

Any suggestions around it?

**Comment by FarazNadeem22** [comment]
Colab is taking a long time to load my data from google drive. 

This is how I am mounting my drive 

from google.colab import drive
drive.mount("/content/drive/")


It just started being slow today.  Way too slow.

**Comment by bratyslav** [comment]
I have the same problem when a dataset of several thousand images 100x200px is loaded from Google Drive for hours.

**Comment by nash981** [comment]
same scenes here. Sadly my task requires a data set 0f around 16k images. Im waiting for an hour at least to just load the data.

**Comment by hugorodro** [comment]
For those iterating over the drive files and individually loading each image, combining the images into a singular np.array and uploading this into drive, and loading the array once into memory. Afterwards iterate in colab.

ie. given 1000 colored images of size 200 X 200

Locally:
- Image becomes 'img' np.array, (img.shape = 200, 200, 3)), (PIL library can convert)
- Combine into 'images' np.array, (images.shape = 1000, 200, 200, 3)
- Save and upload images.npy

Colab:
- images = np.load('path/images.npy')
- Iterate over images.npy

**Comment by yxoos** [comment]
For those who are still struggling with this, zipping and then unzipping resolved my problem (done in seconds compared to 20 minutes)

https://stackoverflow.com/questions/59120853/google-colab-is-so-slow-while-reading-images-from-google-drive

**Comment by josuerocha** [comment]
Has this issue been resolved?

I have a 300 GB dataset, which I uploaded to Google drive after paying the 2 TB space subscription. I am mounting my Drive to Colab Pro and reading the images directly from Google Drive since the dataset is too big the fit the disk space provided by Colab Pro.

Loading the dataset in batches that fit memory takes about 40 minutes, which is nearly 15 times slower than with my laptop...

**Comment by jzagame** [comment]
> For those who are still struggling with this, zipping and then unzipping resolved my problem (done in seconds compared to 20 minutes)
> 
> https://stackoverflow.com/questions/59120853/google-colab-is-so-slow-while-reading-images-from-google-drive

its work for me !
