### ISSUE TITLE
GPU unusable

### ISSUE THREAD

**Issue by mtchibozo** [googlecolab/colabtools#1101]
Hello, 
For the past few days the GPU associated to my Colab account (mt3390@columbia.edu) has been inconsistent if not unusable. Would it be possible to have a fix for this problem? I am a student in Data Science, and am using Colab solely for educational purposes. 
Thank you.
Best,
Maxime

**Comment by sakshamjn** [comment]
I am facing the same problem

**Comment by mtchibozo** [comment]
Best course of action is still just waiting...
