### ISSUE TITLE
Cannot open shared Python3 notebook within Edge browser

### ISSUE THREAD

**Issue by Mercurrent** [googlecolab/colabtools#1102]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
On opening the shared notebook, I get an error:

'There was an error loading this notebook. Ensure that the file is accessible and try again.
'TextDecoder' is not defined'

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Microsoft Edge 44.17763
This problem is specific to browser type.

- Link to self-contained notebook that reproduces this issue
any, but the one I started with: https://colab.research.google.com/drive/1nmIOOm1f1zf2mGJGrigRctItj5Nj59eQ

**Comment by blois** [comment]
You'll want to upgrade to the latest version of Edge, which is 80.0.361. We recommend Chrome or FireFox.

**Comment by JATINLALITMANDAL** [comment]
I have the latest update which is Microsoft Edge
Version 92.0.902.62 (Official build) (64-bit) but still I am unable to type the code. When I am typing I am able to see only a green dit in that box.

**Comment by cperry-goog** [comment]
Have you tried opening in an incognito window? I just tried in Edge and can't reproduce.
