### ISSUE TITLE
change tensorflow2 to tensorflow1,but tensorflow gpu didn't work

### ISSUE THREAD

**Issue by Pacerzhujiang0112** [googlecolab/colabtools#1103]
hi,I'm doing some NLP experiments on colab.I used tensorflow1.41. But the tensorflow updated to tensorflow2.2，now I can't train my code with tensorflow2. I tried to change tensorflow to 1.41 version,I used the command"pip install tensorflow-gpu==1.41" ,Then I installed succeefully,but when I use "import tensorflow as tf" there was a error.I can't use tensorflow-gpu. What should I do? thanks!

**Comment by jakevdp** [comment]
See https://github.com/googlecolab/colabtools/issues/1089

tensorflow 2 is now the default in Colab. To install tensorflow 1 you'll need to install old versions of both tensorflow and tensorflow-gpu:
```
!pip install tensorflow==1.14.0 tensorflow-gpu==1.14.0
```

**Comment by Pacerzhujiang0112** [comment]
thanks!It's worked!
