### ISSUE TITLE
Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.

### ISSUE THREAD

**Issue by Kenji-Tanaka** [googlecolab/colabtools#1105]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
After training and saving a model (file extension: `.h5`), loading it with `tensorflow.keras.models.load_model` doesn't load the optimizer's state:
`WARNING:tensorflow:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.` In fact, these are missing and `loaded_model.optimizer.get_weights()` is empty.

- Describe the expected behavior:
Saving a trained model with its optimizer's weights to a .h5-file and then loading it should also load the optimizer's trained state. 

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome 80.0.3987.149 and Firefox 74.0

- Link to self-contained notebook that reproduces this issue
https://colab.research.google.com/drive/1Uvlk-K4TTtF6AroXMtxfjvu_nC_AoI4u

Thank you very much!

**Comment by colaboratory-team** [comment]
Seems like a TF/keras issue: tensorflow/tensorflow#37968

**Comment by abdulsam** [comment]
> Bug report for Colab: http://colab.research.google.com/.
> 
> * Describe the current behavior:
>   After training and saving a model (file extension: `.h5`), loading it with `tensorflow.keras.models.load_model` doesn't load the optimizer's state:
>   `WARNING:tensorflow:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.` In fact, these are missing and `loaded_model.optimizer.get_weights()` is empty.
> * Describe the expected behavior:
>   Saving a trained model with its optimizer's weights to a .h5-file and then loading it should also load the optimizer's trained state.
> * The web browser you are using (Chrome, Firefox, Safari, etc.):
>   Chrome 80.0.3987.149 and Firefox 74.0
> * Link to self-contained notebook that reproduces this issue
>   https://colab.research.google.com/drive/1Uvlk-K4TTtF6AroXMtxfjvu_nC_AoI4u
> 
> Thank you very much!

Still, the error is not resolved. Facing the same error.

**Comment by harshilishere** [comment]
trying to run the code attached in the link but facing the same issue.

[https://github.com/Tony607/Keras-Trigger-Word](url)
