### ISSUE TITLE
APEX Support for PyTorch

### ISSUE THREAD

**Issue by trisongz** [googlecolab/colabtools#1106]
Hi Colab Team! - Colab Pro user here. I absolutely love Colab and it's an essential part of my daily workflow, I don't know what I would do without it, honestly. Nothing else is as so straight forward to use and _just works._ (including GCPAI Platform notebooks - If AI Notebooks came in a Colab flavor, I'd be all over it)

Small request - would it be possible to include NVIDIA APEX precompiled and installed within the VM for GPUs? I'm finding myself having to install it almost every time working with a new PyTorch project since most leverage Transformer based projects use it to allow for training of large models on a single GPU. It takes roughly 10 mins each time to compile, and there's also a symlink to CUDA 10.0 as the default CUDA version (rather than 10.1 as nvidia-smi shows), which causes APEX to not properly compile. New users trying to use APEX on Colab may run into these issues as well.

Thanks!

**Comment by colaboratory-team** [comment]
How are you building apex? 

Using the first snippet from https://github.com/NVIDIA/apex#linux:
```bash
$ git clone https://github.com/NVIDIA/apex
$ cd apex
$ pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```
claims to complete successfully, and `import apex` doesn't show any errors, so not clear what you mean by "not properly compile".

Looks like installing apex takes ~47MiB of disk.

**Comment by trisongz** [comment]
This is my current code snippet whenever I install apex

```
## Check Cuda Location
!ls -al /usr/local/cuda
#This will occasionally show CUDA 10.0 as the syslinked CUDA version

## Syslinks proper CUDA
!sudo unlink /usr/local/cuda
!sudo ln -s /usr/local/cuda-10.1 /usr/local/cuda

## Install APEX
%cd /content
!git clone https://github.com/NVIDIA/apex
%cd /content/apex

!pip install -v --no-cache-dir --global-option="--pyprof" --global-option="--cpp_ext" --global-option="--cuda_ext" .
```

Here's a Colab notebook running both as a test to reproduce results:

https://colab.research.google.com/drive/1k0VaP04sCexpEuEQiq8-KO4sW2Kva0Tx

**Comment by colaboratory-team** [comment]
The inconsistency of /usr/local/cuda's target is a bug (thanks for reporting it!); internally tracked as b/151005954.
Ironically non-GPU VMs have a correct symlink target which is why apex appeared to build correctly above.

**Comment by trisongz** [comment]
Glad to help - if your team ever decides to release a Colab container for AI notebooks, _pleaseee_ let me know. It's always such a pain trying to get rid of py3.5 for 3.6 with the default TF container.

**Comment by colaboratory-team** [comment]
/usr/local/cuda symlink now correctly points to 10.1 on all variants.
(if you're still seeing a 10.0 symlink please use `Factory reset runtime` from the Runtime menu).

Leaving this bug open to track potential future inclusion of apex in the base image. Right now usage is too low to warrant it.
