### ISSUE TITLE
Couldn't install a package of latest version

### ISSUE THREAD

**Issue by FreelyReceivedFreelyGive** [googlecolab/colabtools#1107]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: There is a package whose name is "DCinsideRead" on PyPI.
For using it, I wrote a command "!pip install DCinsideRead", and it seemed working right at first.
But despite version update in PyPI, colab still installs 1.0.0 version which is the first release.
I tried upgrade option and version designating option, but couldn't solve the problem.

- Describe the expected behavior: It's expected that colab install the latest version of package on PyPI.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Firefox, Brave, Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1fzBWaJaqN7kvWYqwkndyKGiSpsyTSX_G

package on PyPI url: https://pypi.org/project/DCinsideRead/

**Comment by jakevdp** [comment]
Hello,
If you look to the bottom-left of the screen on https://pypi.org/project/DCinsideRead/, you'll see that the most recent release of the package requires Python 3.7.4. Colab has Python 3.6. The newest release of this package that is not marked as requiring Python 3.7.4 is version 1.0.0. When you pip install the package, pip selects the newest version that is compatible with the current Python version.

If you want pip to ignore this requirement and install the latest version no matter what, you can run
```
!pip install DCinsideRead --ignore-requires-python
```
but if the package uses code that is invalid in Python 3.6, the result may not work correctly.
