### ISSUE TITLE
Dark theme prompt if already notebook in dark theme

### ISSUE THREAD

**Issue by manas11** [googlecolab/colabtools#1109]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
While laying out the notebook, if notebook already in dark theme, it prompts for Check out the new dark theme.

- Describe the expected behavior:
If notebook already in dark theme, it should not prompt to check out the new dark theme.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome Version 80.0.3987.149 (Official Build) (64-bit)

- Screenshot of the issue:
![Screenshot from 2020-04-01 20-18-30](https://user-images.githubusercontent.com/32369710/78151655-73fa1480-7456-11ea-80ac-2df57310fdc3.png)

**Comment by katlyn-edwards** [comment]
Tracking internally with b/152755263

We've fixed this upstream, it should be live tomorrow - thanks for the note!
