### ISSUE TITLE
not able to execute code after doing Runtime->Restart

### ISSUE THREAD

**Issue by kalpa-subbaiah** [googlecolab/colabtools#1110]
As per the tensorflow guide https://www.tensorflow.org/tfx/tutorials/tfx/components_keras

After executing the code
 !pip install -q "tfx>=0.21.1,<0.22" "tensorflow>=2.1,<2.2" "tensorboard>=2.1,<2.2"

After doing Restart->Runtime as in the document and executing any chunk of code gives below error.This was working fine until yesterday.

![image](https://user-images.githubusercontent.com/30182218/78256811-a8cda080-7516-11ea-8dc2-1cc5f4f09891.png)

This issue is only observed when restarting the collab runtime after  executing below code
!pip install -q "tfx>=0.21.1,<0.22" "tensorflow>=2.1,<2.2" "tensorboard>=2.1,<2.2"

**Comment by jakevdp** [comment]
If you remove ``-q`` from your pip install, you will see the following warning, which indicates the issue:
```
WARNING: Upgrading ipython, ipykernel, tornado, prompt-toolkit or pyzmq can
cause your runtime to repeatedly crash or behave in unexpected ways and is not
recommended. If your runtime won't connect or execute code, you can reset it
with "Factory reset runtime" from the "Runtime" menu.
```
Your installations update the ``pyzmq`` package to a version that is incompatible with the Jupyter kernel manager. You can reproduce this with
```
!pip install pyzmq==19.0.0
```
 If you pin ``pyzmq`` to the current version in your installation command, Colab should still work properly after restart:
```
!pip install -q "tfx>=0.21.1,<0.22" "tensorflow>=2.1,<2.2" "tensorboard>=2.1,<2.2" "pyzmq==17.0.0"
```

**Comment by kalpa-subbaiah** [comment]
Thank you so much it worked.
