### ISSUE TITLE
Files invisible in browser?

### ISSUE THREAD

**Issue by Tylersuard** [googlecolab/colabtools#1112]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
Can see files using linux commands in the notebook, but cannot see those same files in the left in the file browser.  Scripts cannot access the files either.

(content/music-translation/checkpoints/pretrained_musicnet/)

The directory appears empty in the file browser, but it has multiple checkpoint files and a zip file in it.  This same thing happens when I mount a google drive and download that same content to a folder there: the file browser will not show them.

- Describe the expected behavior:
Files should be visible in both browser and command line

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Firefox

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1XqC2zeEkogtx8uGbXAmpFlt3FohnoQAs

**Comment by metrizable** [comment]
Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem including Torch since then, if you are still experiencing the issue, please re-open and provide an updated, minimal reproducible notebook.
