### ISSUE TITLE
Connect without GPU dialog action buttons are backwards

### ISSUE THREAD

**Issue by MattJeanes** [googlecolab/colabtools#1113]
- Describe the current behavior:
When you get the popup about usage limits, pressing 'Connect without GPU' results in an popup saying 'Unable to connect to runtime'. This is the same behaviour as clicking outside the box. Pressing the Close button successfully connects to an instance.

- Describe the expected behavior:
The buttons appear to be backwards. 'Connect without GPU' should connect to the instance while pressing 'Close' should result in the 'Unable to connect to runtime' popup.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome 80

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
Any

**Comment by colaboratory-team** [comment]
Thank you for the report. Internal tracking: b/153170043

**Comment by colaboratory-team** [comment]
This should be fixed now. Thanks again for the report!

**Comment by MattJeanes** [comment]
You're welcome! Glad to see I wasn't going crazy ☺️
