### ISSUE TITLE
Unable to Undo/Redo 

### ISSUE THREAD

**Issue by liamlindy** [googlecolab/colabtools#1115]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: in my colab notebook, I am unable to use either the buttons or keyboard shortcuts to undo. This is clearly no buneo

- Describe the expected behavior: pressing the undo button should undo 

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome (most recent version) on Mac Catalina 

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/drive/1THcfK0gNvW-YE64ZwnR_P5oVe7N15cYF

**Comment by blois** [comment]
What keyboard layout are you using?

And to undo there are actually 2 undo stacks- add/remove cells and undo of text edits in the editor. Which one are you trying to perform?

**Comment by liamlindy** [comment]
The one under the edit menu. Not even trying a short cut 
![Screen Shot 2020-04-03 at 6 04 12 PM](https://user-images.githubusercontent.com/38886660/78408565-877fb980-75d5-11ea-80b4-201954262bb3.png)

see how they're grayed out even though I just typed

**Comment by liamlindy** [comment]
Okay I got it to work, but its not straight forward. It only works via a short cut, which I think is how a typical google drive works.
