### ISSUE TITLE
The default installation of keras is not compatible with tensorflow 

### ISSUE THREAD

**Issue by sciann** [googlecolab/colabtools#1117]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
Default sessions starts with tf==2.2.0rc and Keras==2.2.5. However, this version of keras is not compatible with TF2.

**Comment by colaboratory-team** [comment]
Thank you for the report. Internal tracking: b/153219046

**Comment by colaboratory-team** [comment]
Keras 2.3 is now the default in new runtimes. Thank you for the report!
