### ISSUE TITLE
Stuck in "Allocating" state

### ISSUE THREAD

**Issue by hanshengchiu** [googlecolab/colabtools#1118]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
After training with TPU for 45 minutes, Colab stuck in "Allocating" state for very long. Many errors also appeared in Chrome's console, as shown on the right of attached screenshot. Those 404 errors are the same as reported in #1111 

When in such state, clicking reload in Chrome can't really refresh the tab. If I open another tab and try to open colab.research.google.com, it will timeout and show the following error
```
This site can’t be reached
The webpage at https://colab.research.google.com/ might be temporarily down or it may have moved permanently to a new web address.
ERR_HTTP2_PROTOCOL_ERROR
```
However if I open another browser (i.e. Edge) or relaunch Chrome, connecting to colab.research.google.com will be ok. 

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome stable version 80.0.3987.163 (Official Build) (64-bit)

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
![Untitled](https://user-images.githubusercontent.com/17819084/78421250-c4f14f00-7688-11ea-8669-a49baf29c6a3.png)

**Comment by hanshengchiu** [comment]
This happens when I keep showing plots for certain amount of epochs (<100). Doesn't feel like memory issue because I tried high mem instance too.

**Comment by Abishek-rk** [comment]
Solves for me by signing out from google chrome and disabling the specific 3rd party chrome extension.

**Comment by cperry-goog** [comment]
Yeah, this seems like an extensions issue: if it repos in incognito for someone then re-open.
