### ISSUE TITLE
Hi Colab team, any progress on this issue? I ran into it today using Edge browser.

### ISSUE THREAD

**Issue by Tagbo-Aroh** [googlecolab/colabtools#1119]
Hi Colab team, any progress on this issue? I ran into it today using Edge browser.

_Originally posted by @Mercurrent in https://github.com/googlecolab/colabtools/issues/710#issuecomment-605825771_

Hi Mercurrent, any luck?

**Comment by hanshengchiu** [comment]
Colab doesn't support Edge...
