### ISSUE TITLE
GPU runtimes cannot find directory

### ISSUE THREAD

**Issue by deweysia** [googlecolab/colabtools#112]
The notebook is unable to find directories in the Drive when using a GPU. Using the regular python 3 or 2, this problem does not seem to be there. Any idea why this is happening? 

I'm testing with this notebook
https://colab.research.google.com/notebook#fileId=1srw_HFWQ2SMgmWIawucXfusGzrj1_U0q

**Comment by pointyointment** [comment]
The outputs I see in that notebook look successful.  I didn't run it myself, but I can navigate my Drive's directories using `google-drive-ocamlfuse` from a GPU notebook of my own, that uses pretty much the same code, just fine. Where is the problem occurring?

**Comment by colaboratory-team** [comment]
We'll need more context to diagnose issues of this sort, e.g., the precise error you observed. Please open a new issue if this issue recurs.
