### ISSUE TITLE
wrong args in function 'hist' in matplotlib.pyplot

### ISSUE THREAD

**Issue by esselesse** [googlecolab/colabtools#1120]
- Describe the current behavior:
```
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as sps
sns.set()
sample = sps.norm.rvs(size=200)
grid = np.linspace(-3, 3, 100)
plt.hist(sample, range=(-3, 3), bins=20, normed=True)
plt.hist()
plt.plot(grid, sps.norm.pdf(grid), color='red', label='density')
plt.show()
```

throws error 

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-136-e552c6ada10a> in <module>()
>       1 plt.figure()
> ----> 2 plt.hist(sample, range=(-3, 3), bins=20, normed=True)
>       3 plt.plot(grid, sps.norm.pdf(grid), color='red', label='density')
>       4 plt.show()
> 
> 5 frames
> /usr/local/lib/python3.6/dist-packages/matplotlib/artist.py in _update_property(self, k, v)
>    1000                 if not callable(func):
>    1001                     raise AttributeError('{!r} object has no property {!r}'
> -> 1002                                          .format(type(self).__name__, k))
>    1003                 return func(v)
>    1004 
> 
> AttributeError: 'Rectangle' object has no property 'normed'

in a listing of a function "hist" on colab we have 

> matplotlib.pyplot.hist(x, bins=None, range=None, density=None, weights=None, cumulative=False, bottom=None, histtype='bar', align='mid', orientation='vertical', rwidth=None, log=False, color=None, label=None, stacked=False, *, data=None, **kwargs)

but on [Official documentation cite](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.hist.html) there is 

> matplotlib.pyplot.hist(x, bins=None, range=None, density=None, weights=None, cumulative=False, bottom=None, histtype='bar', align='mid', orientation='vertical', rwidth=None, log=False, color=None, label=None, stacked=False, **_normed=None_**, *, data=None, **kwargs)

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Opera.

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1D_y9K9huLNHkihrUANjT3BHbzsj2U6uE

**Comment by jakevdp** [comment]
According to the documentation site you linked to:
```
normed : bool, optional
    Deprecated; use the density keyword argument instead.
```
I suspect that after deprecating this option, matplotlib removed it from test coverage, and a subsequent change broke the behavior. You might consider raising this bug in the [matplotlib project](https://github.com/matplotlib/matplotlib)
