### ISSUE TITLE
ImportError: cannot import name 'sequence_generator_bundle'

### ISSUE THREAD

**Issue by jvalansi** [googlecolab/colabtools#1122]
Bug report for Colab: http://colab.research.google.com/.
- Describe the current behavior:
When Initializing the model in the Melody RNN section, this error pops up.

- Describe the expected behavior:
Shouldn't be an error.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Tried both Chrome and Safari

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/notebooks/magenta/hello_magenta/hello_magenta.ipynb#scrollTo=_Pm3kdH0-DaH

**Comment by craigcitro** [comment]
You should report this over at https://github.com/tensorflow/magenta.
