### ISSUE TITLE
OUT OF THE RAM????? your session had crashed after using all the available RAM

### ISSUE THREAD

**Issue by sumayaaliso** [googlecolab/colabtools#1123]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I paid for Colab pro to solve the problem of  being out of ram!! But it seems it does not solve!!
just to know I used to run my code normally whiteout using the pro version but three days ago, there were an issue regrading to the ram!! Like suddenly!! Same program same files.. I have no idea what happened !!

 

If there is any problem in the service's  pleas let us now to find another source !
- Describe the expected behavior:
Want my program to run as before without using all the available RAM 
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by sumayaaliso** [comment]
pleas waiting the solution :))))))))))))

**Comment by jakevdp** [comment]
Have you selected a high-memory runtime? See https://colab.research.google.com/notebooks/pro.ipynb#scrollTo=65MSuHKqNeBZ

**Comment by sumayaaliso** [comment]
yes i did but still it is not working
it crashed before the epoch ends, like in the middle of the training process
i notice that in the training, the batch size is not implemented as i set..
 i set it equal to 1024, but in the training it was 88 !!
so slow and the model is not training very well
all was good i do not know what happens

**Comment by jakevdp** [comment]
Please share a complete notebook that reproduces the issue you are seeing.

**Comment by sumayaaliso** [comment]
it is already in the first comment...
please,  see the training process and how the bach_size were set to 88
automatically !

**Comment by jakevdp** [comment]
I'm sorry, I don't see any link to your notebook in this thread.

**Comment by sumayaaliso** [comment]
https://colab.research.google.com/drive/1tCDaeUDzXy13rvzFxELmud-aaVgOPMqZ


please, look at the training process and how the batch size set to 88 .. even though i choose it to be 1024

**Comment by sumayaaliso** [comment]
> I'm sorry, I don't see any link to your notebook in this thread.

please provide me any information to help get over this problem :)

**Comment by jakevdp** [comment]
It's not obvious to me from from reading through your notebook why it would be using too much memory, and your data is not accessible to me because it is hosted on your private drive. You might try asking a more pointed question on StackOverflow.

**Comment by sumayaaliso** [comment]
> It's not obvious to me from from reading through your notebook why it would be using too much memory, and your data is not accessible to me because it is hosted on your private drive. You might try asking questions about tensorflow usage on StackOverflow.

thank you for ur time, I'll try to solve it

**Comment by KaleabTessera** [comment]
@jakevdp  How much RAM is available in the high-memory runtime? I get about 27.4 gb. Can this be made extended?
