### ISSUE TITLE
why number of samples per epoch sets automatically (88) during the training ??

### ISSUE THREAD

**Issue by sumayaaliso** [googlecolab/colabtools#1124]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
why number of samples per epoch sets automatically (88) during the training ??
- Describe the expected behavior:
all samples must train in one epoch which bach zise = 1024
- The web browser you are using (Chrome, Firefox, Safari, etc.):
chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1tCDaeUDzXy13rvzFxELmud-aaVgOPMqZ

**Comment by kamilbakierzynski** [comment]
If you mean this:
`Epoch 1/10
88/88`
it doesn't mean that it's 88 samples. It's 88 * batch_size so in your case it will be > 90k so it covers your whole data set.

Please close.
