### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'log' error

### ISSUE THREAD

**Issue by Laksmi1940** [googlecolab/colabtools#1126]
I want to implement the CNN in mnist dataset in Keras.

https://github.com/keras-team/keras/blob/master/examples/mnist_cnn.py

When I ran the code:

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))

it shows the error :  AttributeError: module 'TensorFlow' has no attribute 'log'

Could you help me with this resolving this issue?

**Comment by jsnydes** [comment]
keras needs updated I believe: same issue as https://github.com/googlecolab/colabtools/issues/1117
