### ISSUE TITLE
iPad external keyboard doesn't work well

### ISSUE THREAD

**Issue by korakot** [googlecolab/colabtools#113]
Currently, Colab almost works on my iPad pro. A few problems remain

- Backspace moves the active cell up to the previous cell
- When select a cell, sometime it won’t become the active cell (you can’t Shif-Enter to run).
- The output area overlap with the next input area if the result becomes long.

Colab is the perfect tool to work anywhere. Please help make it also usable on iPad pro with keyboard.

**Comment by lizhicq** [comment]
Is there any fix so far? Also stuck with it here.
