### ISSUE TITLE
Feature request: Google colab to host latest stable TensorFlow versions at all times.

### ISSUE THREAD

**Issue by ymodak** [googlecolab/colabtools#1132]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
This is more of a feature request.
Google Colab currently hosts unstable TensorFlow version 2.2.0-rc2
The adverse effect of this version has caused many colab tutorials to throw unexpected error messages which can be avoided by switching to latest stable TF version.
For example https://github.com/tensorflow/tensorflow/issues/38232

- Describe the expected behavior:
Can we please have google colab to host latest stable TensorFlow versions at all times?
Since TF 2.2 final is yet to be released, it can be a good idea to host latest available stable version like TF 2.1.0

- The web browser you are using (Chrome, Firefox, Safari, etc.): 
Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
```python
%tensorflow_version 2.x
import tensorflow as tf
print(tf.__version__)
```
```
2.2.0-rc2
```

**Comment by korakot** [comment]
I suggest allowing many tensorflow installations.

Now it's already possible to use 2 versions.

    %tensorflow_version 1.x

and 

    %tensorflow_version 2.x

I suggest Colab has 3 versions: 1.x, 2.1, 2.2 (and 2.3, 2.4, ... etc in the future).

**Comment by bhack** [comment]
We are still not in sync with the new `2.3.0` release

**Comment by bhack** [comment]
We are at 2.8.x now but the last stable TF release is 2.10.0

**Comment by cperry-goog** [comment]
We can't guarantee always being up to date, you can always `!pip install` upgrades as needed. Follow our backend updates at https://github.com/googlecolab/backend-info
