### ISSUE TITLE
None is only supported in the 1st dimension. Tensor 'input_1' has invalid shape '[None, None, None, None]'.

### ISSUE THREAD

**Issue by asj100** [googlecolab/colabtools#1133]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
On running the Optimization for TFLite cell, I get the following error message:

ValueError                                Traceback (most recent call last)
<ipython-input-13-7c2afc44c7fa> in <module>()
     15   if representative_dataset:  # This is optional, see above.
     16     converter.representative_dataset = representative_dataset
---> 17 lite_model_content = converter.convert()
     18 
     19 with open("/tmp/lite_flowers_model", "wb") as f:

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py in convert(self)
    481               "None is only supported in the 1st dimension. Tensor '{0}' has "
    482               "invalid shape '{1}'.".format(
--> 483                   _get_tensor_name(tensor), shape_list))
    484         elif shape_list and shape_list[0] is None:
    485           # Set the batch size to 1 if undefined.

ValueError: None is only supported in the 1st dimension. Tensor 'input_1' has invalid shape '[None, None, None, None]'.

Web browser: Chrome

Notebook Link:
TF Hub for TF2: Retraining an image classifier

https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/tf2_image_retraining.ipynb

**Comment by craigcitro** [comment]
You should report this to the repo the notebook came from (tensorflow/hub).
