### ISSUE TITLE
Regarding non notebook style files

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#1135]
- Describe the current behavior:
A lot of github repositories have ‘.py’ style files, and not notebook, so, when we search for files within a repository using github search provided in colab, it does not show any ‘.py’ file.

- Describe the expected behavior:
It show ‘.py’ files and give an option to add entire file in first cell

**Comment by blois** [comment]
There is also some convention for cell separators within Python files which could allow opening it as more of a notebook.

Spyder uses:
```python
#%%
... the first cell ...
#%%
... the second cel l...
#%%
```
