### ISSUE TITLE
Sorry, no backends available. Please try again later.

### ISSUE THREAD

**Issue by YucelPeynirci** [googlecolab/colabtools#1138]
My instance have been running less than 2 hours have shut down without a warning and I can not allocate any type of instances. 
"Sorry, no backends available. Please try again later."
I am sure not being blacklisted as an honest Colab Pro user.

**Comment by aciupan** [comment]
I have had the same issue in the last hour. It hasn't happened before. Any help would be appreciated!

**Comment by YucelPeynirci** [comment]
A session have been allocated, but my 2 hour session is fully down. This is still an issue for future.

**Comment by Debkanya1998** [comment]
I am also facing the same issue

**Comment by aciupan** [comment]
Solved for me. Thanks!

**Comment by Debkanya1998** [comment]
> Solved for me. Thanks!

how?

**Comment by aciupan** [comment]
Just restarted and it worked.

**Comment by YucelPeynirci** [comment]
@aciupan have you lost your instance and data?

**Comment by aciupan** [comment]
Yes I did but I had just restarted my computer so there was no significant loss

**Comment by colaboratory-team** [comment]
Colab was briefly unavailable this morning due to elevated error rates for Google Cloud infrastructure components. This issue has been resolved. Sorry for the trouble, all. 

Details: https://status.cloud.google.com/incident/zall/20005
