### ISSUE TITLE
It‘s too slow to read images when I use GPU

### ISSUE THREAD

**Issue by DreamsofGg** [googlecolab/colabtools#1139]
I have 16k images to read, when I select  **None** hardware accelerator, it approximately performs **80it/s**, but when I choose **GPU**, it's just about **2it/s**.

I have mounted my google drive, and the code is
```python
def readfiles_(path):
    # img_dir = sorted(os.listdir(path))
    img_dir = random.sample(os.listdir(path), 1000)

    x = np.zeros((len(img_dir), 128, 128, 3), dtype=np.uint8) # N H W C
    y = np.zeros(len(img_dir), dtype=np.uint8)

    for i, file in tqdm(enumerate(img_dir)):
        img = cv2.imread(os.path.join(path, file))
        x[i, :, :] = cv2.resize(img, (128,128)) 
        if label:
            y[i] = file[0]
    
    return x, y
```
Any method to solve it?

**Comment by VSumanth99** [comment]
I have the same issue. One workaround I found was to save the dataset as a zip file and extract it in the notebook before reading it. This seems to work fine for me and is significantly faster than individually loading the image files
