### ISSUE TITLE
Local runtime error in colored text display

### ISSUE THREAD

**Issue by korakot** [googlecolab/colabtools#114]
First, thank you for a great new feature.

Here's a minor bug in the display when I call `!ls` as followed. It seems any colored text will have an additional `m` attached at the end.

![screen shot 2561-04-05 at 13 51 55](https://user-images.githubusercontent.com/3155646/38351246-daddbb5e-38d8-11e8-9000-4ee2f02fc80a.png)

**Comment by colaboratory-team** [comment]
What version of ipykernel and ipython are you using?
