### ISSUE TITLE
Widget multiple selection dropdown behavior

### ISSUE THREAD

**Issue by caupolicandiaz** [googlecolab/colabtools#1140]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
A multiple selection dropdown works as expected when selecting a continuous range, but if you attempt to select a range that isn't continuous the output is often just the first element selected
- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by blois** [comment]
The fix for this should now be live.
