### ISSUE TITLE
Can't get back to default tensorflow version

### ISSUE THREAD

**Issue by vinzeebreak** [googlecolab/colabtools#115]
I did not know that `tensorflow` and `keras` were installed by default on the machine. And I installed my own versions. But it was buggy. So I decided to go back to the previous versions. I did:

    !pip install tensorflow==1.6.0
and

    !pip install keras==2.1.5
But now, when I do `import keras`, I get the following error:

    AttributeError: module 'tensorflow' has no attribute 'name_scope'

So I suspect, my installations were wrong somehow.

Is there a clean way to get back to the default settings and versions ?

**Comment by craigcitro** [comment]
If you install the desired versions and restart your kernel (`Runtime` -> `Restart kernel`), you should be back in working order.

If you really want a completely new VM, you have a few choices -- the easiest is to just `kill -9 -1`, wait 30 seconds, and reconnect. 😁 

(Closing, but feel free to reopen if you're still stuck.)

**Comment by vinzeebreak** [comment]
The `kill -9 -1` was what I needed. Thanks.

But wouldn't it be better to have a button in the menu for that kind of command ?

**Comment by craigcitro** [comment]
Yes and no -- it's still pretty rarely needed, and has side-effects that are harder to explain (eg any installed packages need reinstalled). So worth surfacing, but still TBD where.
