### ISSUE TITLE
use of wrong indexing in method predict_house_values( )

### ISSUE THREAD

**Issue by SundarML** [googlecolab/colabtools#1150]
Bug report for Colab: 
https://colab.research.google.com/github/google/eng-edu/blob/master/ml/cc/exercises/linear_regression_with_a_real_dataset.ipynb?utm_source=mlcc&utm_campaign=colab-external&utm_medium=referral&utm_content=linear_regression_real_tf2-colab&hl=en#scrollTo=H0ab6HD4ZO75
For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
under the heading "use the model to make predictions",
the batch to be predicted contains index values starting from 10000 to 10000+n, but index of the feature in the output table is from 0 to 9, it is misleading. 

- Describe the expected behavior:
the correct code follows,
def predict_house_values(n,feature,label):
  batch = training_df[feature][10000:10000+n]
  predicted_values = my_model.predict_on_batch(x=batch)
  indx = (batch.index).to_list()
  print('feature      label        predicted')
  print('---------------------------------------------')
  for i,j in zip(indx,range(n)):
    print('%5.0f %9.0f %15.0f'%(training_df[feature][i],training_df[label][i],predicted_values[j]))
the output follows, 
feature      label        predicted
---------------------------------------------
 1960        53             170
 3400        92             203
 3677        69             210
 2202        62             176
 2403        80             180
 5652       295             256
 3318       500             202
 2552       342             184
 1364       118             156
 3468       128             205

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1fnBLMZ2pwF5vPifhM99q_I0IC8NafIpN

**Comment by craigcitro** [comment]
You should report this on the repo you're reading the notebook from (https://github.com/google/eng-edu).
