### ISSUE TITLE
Doc string not opening

### ISSUE THREAD

**Issue by rishik-00** [googlecolab/colabtools#1151]
Bug report for Colab: http://colab.research.google.com/.

I am not able to open doc string in google colab, neither is it is opening automatically 

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: using `shift` + `tab`  or `ctrl`+  `shift` + `space` is not opening doc string

- Describe the expected behavior: doc string should open

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1OUDQ25xa-eHKmsVwChg8MbY9oY3uS-mt

**Comment by blois** [comment]
Is this for all methods or specific ones?

Can you try it with the print statement near the top of your notebook?
```
print('TF version', tf.__version__|)
```
Where the cursor position is indicated by the `|` character.

**Comment by rishik-00** [comment]
Tried it with both shift + tab and ctrl+shift+space,  not working

**Comment by blois** [comment]
What OS and keyboard layout are you using?

**Comment by rishik-00** [comment]
Windows 10, and keyboard layout means key bindings? it's default, though i m able to use ctrl+space for auto complete suggestions

**Comment by blois** [comment]
The keyboard layout is your OS preference for keyboard layout (EN-US, Dvorak, etc). We do see some differences between the keyboard shortcuts on non-EN-US keyboard layouts.

Can you also try in an incognito browser window?

**Comment by rishik-00** [comment]
Keyboard layout is EN-US for Input language and windows display language, EN-India for app language

It worked in incognito, automatically showing doc strings, did i unintentionally changed something in my notebook

**Comment by blois** [comment]
If it works in incognito but not in a normal window (even after reloading) then the most likely culprit it going to be a browser extension.

For example, see https://github.com/googlecolab/colabtools/issues/858#issuecomment-553943188.

**Comment by rishik-00** [comment]
I have not been closing my browser(but reloaded it quite sometimes) because of loss of variables, but when I did it, it starta showing docstrings again with ctrl+shift+space, not automatically though

Thanks for assist
