### ISSUE TITLE
Some questions regarding TPU

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#1159]
Could you inform the power consumption of TPU, and its performance in terms of FLOPS, does TPU follow von Neumann architecture, or do it modify von Neumann architecture to reduce power consumption, do it follow same neuromorphic architecture as TrueNorth?

Plus could a command be added to show specs of TPU, just like we do nvidia-smi to see specs of GPU, this includes FLOPS, or TOPS, architecture details, power consumption details and so on.

thanks

**Comment by tnovikoff** [comment]
These do not appear to be issues for the Colab team

**Comment by vainaijr** [comment]
Ok, closing the issue.
