### ISSUE TITLE
Colab freezing when lemmatizing one line

### ISSUE THREAD

**Issue by 4hseproject** [googlecolab/colabtools#1160]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe current behavior:
Colab is stuck lemmatizing one string for more than 10 minutes, with gpu boost which it is not using

- Describe the expected behavior:
Even on my laptop in jupyter it takes seconds to run the code
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1yGuE15WuF9xHVSQz-AOMQjAZYJ7mnteE#scrollTo=mGvNHfVsDfhq&line=4&uniqifier=1

**Comment by tnovikoff** [comment]
Please make the repro notebook publicly visible
