### ISSUE TITLE
All of the "seedbank" links on the welcome page are broken

### ISSUE THREAD

**Issue by sdierauf** [googlecolab/colabtools#1161]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
1. Open the Colab default welcome.ipynb
2. Scroll to bottom Seedbank examples
3. Click on an example
4. Redirected to generic aihub search results page

- Describe the expected behavior:
1. Open the Colab default welcome.ipynb
2. Scroll to bottom Seedbank examples
3. Click on an example
4. Goes to that example

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/notebooks/welcome.ipynb

**Comment by katlyn-edwards** [comment]
Tracking internally with b/154508008

**Comment by katlyn-edwards** [comment]
This should be fixed; thanks for the report!

**Comment by samkohli** [comment]
Still broken https://research.google.com/seedbank

**Comment by EvanWiederspan** [comment]
I'm not sure if that specific link was ever valid. This question originally referred to the links at the bottom of the welcome notebook, https://colab.research.google.com/#scrollTo=-Rh3-Vt9Nev9. They all seem to work for me

**Comment by parjun585** [comment]
Still its not opening, it hadn't been recovered or the googlers are responding to this? 
[https://research.google.com/seedbank] https://research.google.com/seedbank

**Comment by katlyn-edwards** [comment]
https://research.google.com/seedbank isn't a valid URL, and doesn't have anything to do with Colab -- are you seeing that URL somewhere in Colab?

**Comment by parjun585** [comment]
No , I am not seeing anything in the Collab

**Comment by ChaosCom** [comment]
@EvanWiederspan @katlyn-edwards It was, please see the announcement at [https://blog.tensorflow.org/2018/07/seedbank-discover-machine-learning.html](https://blog.tensorflow.org/2018/07/seedbank-discover-machine-learning.html ) where it was being advertised. Some books and websites also mentioned that link in the past, for example the book "Foundational Python for Data Science". Not sure if this is the right place to report this, just wanted to let you know.
