### ISSUE TITLE
Plotly from local runtime does not work

### ISSUE THREAD

**Issue by lzlarryli** [googlecolab/colabtools#1165]
- Describe the current behavior: I have a local kernel with plotly installed as described in the [official repo](https://github.com/plotly/plotly.py). Locally I can confirm that the [minimal example](https://plotly.com/python/plotly-express/) renders without problem. I can confirm that the same minimal example works if I use the public kernel. But if I switch to my local runtime in colab and run the same minimal example, then it renders an empty space without any error message. 

    I don't know if this is going to be helpful or not, but below is a screenshot of the result along with the errors in the developer console.

<img width="1599" alt="example" src="https://user-images.githubusercontent.com/8211938/79960553-62df6a80-843a-11ea-839f-34d61a2374c2.png">

- Describe the expected behavior: Plotly installed in the local runtime should run the same way as the one in the public runtime.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome Version 80.0.3987.163 (Official Build) (64-bit)

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/drive/1dppekpyJ8vonoNhxxTlwdK9RaIvGqbjD

**Comment by jakevdp** [comment]
What version of plotly do you have installed locally? Automatic rendering of plotly charts in Colab requires [plotly version 4.0](https://community.plotly.com/t/introducing-plotly-py-4-0-0/25639) or newer.

**Comment by blois** [comment]
You may also try to set the default renderer in Python:
https://plotly.com/python/renderers/#setting-the-default-renderer

**Comment by lzlarryli** [comment]
Thank you both very much~ I confirm that both methods work. 

BTW, my plotly version is 4.6.0.

For future reference, to use plotly with a local runtime, either run this on the server side when start the kernel
```
PLOTLY_RENDERER=colab jupyter notebook 
    --NotebookApp.allow_origin='https://colab.research.google.com' 
    --port=8888 
    --NotebookApp.port_retries=0 
    --no-browser
```
or run this in the client colabs
```
import plotly.io
plotly.io.renderers.default = "colab"
```

**Comment by parmarjigar** [comment]
Hello, I have a program run on colab with plotly version 4.11.0. I prepare the graphs and when I download that colab notebook and try to run in my local, instead of graphs I am getting blank space. I tried setting the renderers to notebook_connected, notebook but still it wont work. Please help.

**Comment by blois** [comment]
@parmarjigar Not sure I'm following- the notebook worked in Colab but what do you mean by "run in my local"?
