### ISSUE TITLE
font size is small I cannot see contents.Where can I change the size?

### ISSUE THREAD

**Issue by rashmihattalli** [googlecolab/colabtools#1168]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by katlyn-edwards** [comment]
![font_size](https://user-images.githubusercontent.com/2673487/80122716-c48afc00-8542-11ea-9c70-d82f1745f946.png)
You can change the font size of the editor in Tools -> Settings -> Editor
