### ISSUE TITLE
gdrive mount failed due to unzipping in main directory

### ISSUE THREAD

**Issue by Nabagata** [googlecolab/colabtools#1170]
I had a dataset of 90k images and I had unzipped it in one of the subdirectories. However, after disconnecting from the notebook, I noticed it was moved to the main drive directory.
I haven't been able to connect to colab ever since and always getting mount failed error as there are too many files in the main directory.

I want to delete all the image files from the main directory but for that I'll need to connect to colab at least once and write a script to delete or reorder all the jpeg/png files from main directory.
Deleting manually isn't possible and is taking a lot of time and sometimes the drive webpage gets stuck if I try to select more than 500 files for deleting. I want to reorder the directory structure as mentioned in the instructions

Please suggest some way out of this issue.

**Comment by colaboratory-team** [comment]
Sorry to hear about your troubles.
A potential way out: don't mount your drive in colab, but instead use [PyDrive](https://colab.research.google.com/notebooks/io.ipynb#scrollTo=7taylj9wpsA2) to page through listing your files and delete them using PyDrive incrementally. It'll be slow/tedious, but it should get you unblocked. 

*Caution*: restrict the listing/deleting to just the files you explicitly want to delete to avoid deleting everything in your drive.

**Comment by Nabagata** [comment]
Thanks for the suggestion.
Do I need to explicitly delete all the unwanted files from the main directory as well as trash or just shifting them to trash will be enough to mount gdrive again?

**Comment by colaboratory-team** [comment]
Removing from Trash is the only way to be sure.
