### ISSUE TITLE
Sympy / matplotlib problem

### ISSUE THREAD

**Issue by agodon** [googlecolab/colabtools#1174]
simple example script :
```python
%matplotlib inline
from sympy import *
plot(x**2)
```
result :
/usr/local/lib/python3.6/dist-packages/sympy/plotting/plot.py:890: MatplotlibDeprecationWarning: 
The set_smart_bounds function was deprecated in Matplotlib 3.2 and will be removed two minor releases later.
  self.ax.spines['left'].set_smart_bounds(True)
/usr/local/lib/python3.6/dist-packages/sympy/plotting/plot.py:891: MatplotlibDeprecationWarning: 
The set_smart_bounds function was deprecated in Matplotlib 3.2 and will be removed two minor releases later.
  self.ax.spines['bottom'].set_smart_bounds(False)

**Comment by jakevdp** [comment]
For questions about Python library usage, we suggest asking on http://stackoverflow.com
