### ISSUE TITLE
shell command # can't be carry out when it not used for comments

### ISSUE THREAD

**Issue by jianmosier** [googlecolab/colabtools#1176]
I'm confused about this code! Why # cant't play a role that takes the length of a string?

```
> string="abcd"
> 
> !echo ${#string}
> 
```
In fact, the code behind # has become commented and cannot be executed!

Any advice?

**Comment by jakevdp** [comment]
This works correctly, but you cannot mix python and bash variables in this way. Try this instead:
```
!string="abcd" && echo ${#string}
```
The two statements have to be on the same line because each ``!`` statement opens a temporary subshell. If you want to use multiline bash programs, you can use the ``%%bash`` cell magic instead:
```
%%bash
string="abcd"
echo  ${#string}
```
