### ISSUE TITLE
Code Editor Box One-line Confusion

### ISSUE THREAD

**Issue by luciengaitskell** [googlecolab/colabtools#118]
While using Colab, I noticed an issue with one line Python statements, such as:
`if True: print("Hello Word")`

These seem to confuse the editor, as it likes to indent the next line, as an attempt to start a new block. It's a very minor issue, but can be annoying while writing code.

**Comment by colaboratory-team** [comment]
b/124760387

**Comment by blois** [comment]
We're updating the editor engine Colab uses, details are at https://colab.research.google.com/notebooks/editor_details.ipynb.

This bug is fixed in the new engine.
