### ISSUE TITLE
Problem with google-auth

### ISSUE THREAD

**Issue by thomas-blachier** [googlecolab/colabtools#1181]
Bug report for Colab: http://colab.research.google.com/.

Colab says :
ERROR: google-colab 1.0.0 has requirement google-auth~=1.7.2, but you'll have google-auth 1.14.1 which is incompatible.
Installing collected packages: google-auth
Successfully installed google-auth-1.14.1
WARNING: The following packages were previously imported in this runtime:
  [google]
You must restart the runtime in order to use newly installed versions.
 but I install google-auth-1.14.1 first.
I tried :
!pip uninstall 'google-auth==1.7.2'
!pip install 'google-auth==1.14.1'
 and 
!pip install --upgrade google-auth
but I have the same issue.
I am using Opera
Of course I type y to the uninstalling of google-auth 1.7.2

https://drive.google.com/open?id=19SiaJop-wdxhp8vUOs2JRh4rXWrNXwIY

**Comment by craigcitro** [comment]
You need to restart the runtime after updating google-auth.

**Comment by devineeharika** [comment]
I too have the same issue with the  google auth  please let me know how to solve it
