### ISSUE TITLE
The file import option is not functioning

### ISSUE THREAD

**Issue by AnoopCA** [googlecolab/colabtools#1182]
I used the below code to upload a csv file. An option shown to upload the file. But after selecting the file, it is not uploading anyway. No options are available on colab like buttons to upload the fie in this way.

from google.colab import files
uploaded = files.upload()

**Comment by blois** [comment]
What browser are you using? Can you upload files with the file browser?

**Comment by AnoopCA** [comment]
Hi,

Thank you for your response.
I'm using google chrome version 81.0.4044.122 (64-bit).
