### ISSUE TITLE
r topicmodel package

### ISSUE THREAD

**Issue by acikalinbuse** [googlecolab/colabtools#1184]
When i tried to install topicmodel package in r kernel i got an below error.

**install.packages("topicmodels")**

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Warning message in install.packages("topicmodels"):
“installation of package ‘topicmodels’ had non-zero exit status”

**library(topicmodels)**

Error in library(topicmodels): there is no package called ‘topicmodels’
Traceback:

1. library(topicmodels)

**Comment by jakevdp** [comment]
[This StackOverflow answer](https://stackoverflow.com/a/24245311/2937831) indicates that in order to install topicmodels, you first have to install [gsl](https://www.gnu.org/software/gsl/doc/html/) on your system.

Try running
```
system("apt install libgsl-dev", intern=TRUE)
```
before installing ``topicmodels``, and it should work.

**Comment by acikalinbuse** [comment]
it worked. thank you.
