### ISSUE TITLE
mesh_segmentation_demo.ipynb not working

### ISSUE THREAD

**Issue by alexiworld** [googlecolab/colabtools#1187]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Load and visualize test data fails with:
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_graphics/notebooks/mesh_segmentation_dataio.py:173: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-0049de5dbd79> in <module>()
     10 with input_graph.as_default():
     11   mesh_load_op = dataio.create_input_from_dataset(
---> 12       dataio.create_dataset_from_tfrecords, test_tfrecords, test_io_params)
     13   with tf.Session() as sess:
     14     test_mesh_data, test_labels = sess.run(mesh_load_op)

/usr/local/lib/python3.6/dist-packages/tensorflow_graphics/notebooks/mesh_segmentation_dataio.py in create_input_from_dataset(dataset_fn, files, io_params)
    325 
    326   dataset = dataset_fn(files, io_params)
--> 327   mesh_data = dataset.make_one_shot_iterator().get_next()
    328   mesh_data['neighbors'] = adjacency_from_edges(mesh_data['edges'],
    329                                                 mesh_data['edge_weights'],

AttributeError: 'PaddedBatchDataset' object has no attribute 'make_one_shot_iterator'

- Describe the expected behavior:
Successfully execute Colab notebook
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/github/tensorflow/graphics/blob/master/tensorflow_graphics/notebooks/mesh_segmentation_demo.ipynb

**Comment by craigcitro** [comment]
You should report this on the repo that contains the notebook (tensorflow/graphics).
