### ISSUE TITLE
Shared and added folders are not displayed when mounting the drive after opening a notebook from drive

### ISSUE THREAD

**Issue by theendlessriver13** [googlecolab/colabtools#1188]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
When openening an `.ipynb` file from your drive by doubleclicking it a new tab opens with google colab. When you mount your drive by clicking `Mount Drive` it asks for permission and succeeds.
Now it shows all drive folders, but no shared folders that were added to your drive. 
When using this snipppet:
>```python
>from google.colab import drive
>drive.mount('/content/drive')
>```
it works and you also get the shared folders that were added to your drive.

- Describe the expected behavior:
When clicking the `Mount Drive` button and after agreeing to use your drive also the shared folders that were added to your drive should appear.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome/Firefox

- Link to self-contained notebook that reproduces this issue
Not a notebook specific issue

**Comment by colaboratory-team** [comment]
Closing as dup of #1205 (sorry for missing this earlier report).
