### ISSUE TITLE
No way to manage uploaded files in google.colab.files library

### ISSUE THREAD

**Issue by andrewfwalters** [googlecolab/colabtools#119]
The only functions are upload and download. There is now way to associate a set of files to a particular notebook, remove files once they've been uploaded, or many other basic filesystem actions. Considering that the use case for colaboratory is primarily data science, I would expect a more mature capability

**Comment by blois** [comment]
The google.colab.files package is only to upload/download files between your local computer and the VM. Once on the VM standard Python I/O should be used to manipulate any files.
