### ISSUE TITLE
cannot preview vars.env file created in gdrive, confused how .env works in google colab

### ISSUE THREAD

**Issue by deepankeromn** [googlecolab/colabtools#1191]
used the following code to create a vars.env file in google drive

```
!pip install colab-env -qU
import colab_env
```

then I used this to add variables

```
colab_env.envvar_handler.add_env("TEST", "HELLO WORLD!", overwrite=True)
!more gdrive/My\ Drive/vars.env
```

I see that the vars.env file was created in my drive, and I tested to check that it was saved in the colab environment but, I cannot open this file in colab or my drive and directly edit its contents like I can do with an .env file in visual studio? I am running a github repository program that needs a GPU on colab, and it came with a length env.example. I wanted to copy this into vars.env but I can't open it. Is there a better way?

**Comment by craigcitro** [comment]
colab-team doesn't have anything to do with the `colab-env` package; I'd try talking to the package author.

**Comment by deepankeromn** [comment]
do you know how I can reach out to them?

**Comment by craigcitro** [comment]
I'd start at the PyPI page: https://pypi.org/project/colab-env/
