### ISSUE TITLE
Pytorch Lightning 0.7.5

### ISSUE THREAD

**Issue by williamFalcon** [googlecolab/colabtools#1193]
Hi team,

Here is the wheel for Lightning 0.7.5

https://files.pythonhosted.org/packages/75/ac/ac03f1f3fa950d96ca52f07d33fdbf5add05f164c1ac4eae179231dfa93d/pytorch_lightning-0.7.5-py3-none-any.whl

Our wheel is compatible with PyTorch 1.1-1.5 on any cuda, TPU or cpu device.

We're looking to having it updated in Colab.

Thank you again for all the help!

cc'ing @colaboratory-team

**Comment by craigcitro** [comment]
Thanks, we'll start the ball rolling!

internal tracking: b/155424112

**Comment by craigcitro** [comment]
Oh -- I'm sorry, I had mistakenly believed that this was already bundled in colab.

It looks like we don't currently install pytorch_lightning, and it's a fast `!pip install`; I'm going to close this for now, and we can revisit if we get reports of users hitting trouble installing.

**Comment by williamFalcon** [comment]
@craigcitro mind checking in with @CSEMike and Timothy Novikoff first? we discussed last week.

Thanks! :)

**Comment by craigcitro** [comment]
Left hand, right hand ... 🤦
