### ISSUE TITLE
 File viewer tabs will mess up when open files are deleted via file browser

### ISSUE THREAD

**Issue by riccardoangius** [googlecolab/colabtools#1194]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behaviour: file viewer tabs will mess up when a file is opened and then deleted (via file browser).

- Describe the expected behavior: the tabs for deleted files should disappear (or be appropriately marked), and the contents of newly opened files should open in their actual tab, not in one for a deleted file.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Brave

![Screen Recording 2020-04-30 at 16 43 48](https://user-images.githubusercontent.com/694840/80725418-54144a00-8b03-11ea-84b2-65c6737dfb65.gif)

**Comment by craigcitro** [comment]
internal tracking: b/155431037

**Comment by katlyn-edwards** [comment]
I can't seem to reproduce this anymore, going to close it. Feel free to comment/reopen if you're still able to repro.
