### ISSUE TITLE
New files on Drive won't appear in Colab (Until factory reset)

### ISSUE THREAD

**Issue by lucasavila00** [googlecolab/colabtools#1195]
- Describe the current behavior:

You have Colab running for a while.

You upload a file to Google Drive.

You try to download it to Colab and it says file "not found". (I can run !ls on the folder, no permission issues. I can download another file that was uploaded before I opened colab.)

You do a factory reset on colab and it founds the new file.

- Describe the expected behavior:

It should be able to see files in Google Drive that were added after Colab was started.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome Version 81.0.4044.129 (Official Build) (64-bit), macOS Catalina (10.15.4).

- Link to self-contained notebook that reproduces this issue:

https://colab.research.google.com/drive/1kkqVcbbJufg9zrpgSJiTW5tVCGarSVYS

I also tried to mount Google Drive with the new UI button and it didn't work either on the left panel.
I also tried to mount Google Drive at another pathname (like "gdrive2/") and it didn't work either.

**Comment by blois** [comment]
Unfortunately I've seen a bit of flakiness around the mounted drive detecting changes to your drive folder. One thing to try is remounting with the [force_remount](https://github.com/googlecolab/colabtools/blob/513aa807cdd34adfdf4d3d6bd6998b45845dc737/google/colab/drive.py#L93) flag set to true.

**Comment by lucasavila00** [comment]
Ok. Great. 👍 

I guess I can close this?
