### ISSUE TITLE
OSError: [Errno 5] Input/output error // Download quota exceeded for this file

### ISSUE THREAD

**Issue by rachelsterneck** [googlecolab/colabtools#1196]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
I'm unable to load any of my colab files with `torch.load`. I get an error message `OSError: [Errno 5] Input/output error`. Similarly, I cannot download .pth dataset files on my drive that have been made through colab; when I try to download manually by right clicking on the file, I get a "Download quota exceed for this file." Both of these issues are happening for files I haven't used in weeks, as well as files I use regularly. I haven't shared these files with anyone. I'm able to download Google docs/slides/sheets files normally. 

- Describe the expected behavior:
I should be able to load my datasets and work as usual.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

**Comment by YashGupta1997** [comment]
Hey! I'm getting the same error. The code seemed to be working fine and stopped suddenly. My data set size is 34 GB. Were you able to solve this problem?
![image](https://user-images.githubusercontent.com/57323800/81951613-ac6c4100-9605-11ea-99c6-133aecb2e2c9.png)

**Comment by Santosh-Gupta** [comment]
I am getting this issue as well. It first happened with a 24 gb numpy memmap, but not it's happening with all files greater than 400 mbs. I am still able to open 13 mb files just fine though. 

When I try to access the numpy memmap, the enviroment crashes.
