### ISSUE TITLE
Output for running '.*?' in re.search not returning the character output

### ISSUE THREAD

**Issue by nilotpalc** [googlecolab/colabtools#1197]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
The output while running `re.search('.*?',<phrase>) ` is not showing any characters in the generated list. It is only showing empty strings.
- Describe the expected behavior:
The actual output should be a list which includes empty strings and characters
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  https://colab.research.google.com/drive/1POUWG2H94UTZBXnElfledf2t4z270z6D
 JupyterNotebook Image
![image](https://user-images.githubusercontent.com/63115134/80738096-1d095d00-8b32-11ea-9fac-e7730394e2da.png)

**Comment by colaboratory-team** [comment]
This isn't a jupyter-vs-colab difference but rather a difference among python versions:
```
$ for v in 3.6 3.7 3.8; do echo $v ; docker run -it python:$v python3 -c "import re ; print(re.findall('.*?', 'This is an example sentence.'))"; done
3.6
['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
3.7
['', 'T', '', 'h', '', 'i', '', 's', '', ' ', '', 'i', '', 's', '', ' ', '', 'a', '', 'n', '', ' ', '', 'e', '', 'x', '', 'a', '', 'm', '', 'p', '', 'l', '', 'e', '', ' ', '', 's', '', 'e', '', 'n', '', 't', '', 'e', '', 'n', '', 'c', '', 'e', '', '.', '']
3.8
['', 'T', '', 'h', '', 'i', '', 's', '', ' ', '', 'i', '', 's', '', ' ', '', 'a', '', 'n', '', ' ', '', 'e', '', 'x', '', 'a', '', 'm', '', 'p', '', 'l', '', 'e', '', ' ', '', 's', '', 'e', '', 'n', '', 't', '', 'e', '', 'n', '', 'c', '', 'e', '', '.', '']
```
