### ISSUE TITLE
GAN Tutorial does not work

### ISSUE THREAD

**Issue by hbono2019** [googlecolab/colabtools#1199]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
It has multiple problems:
First This code Segment makes a call to multiple libraries and functions
---- Original code in the notebook
import matplotlib.pyplot as plt
import tensorflow_datasets as tfds
import tensorflow_gan as tfgan
import numpy as np

params = {'batch_size': 100, 'noise_dims':64}
with tf.Graph().as_default():
  ds = input_fn(tf.estimator.ModeKeys.TRAIN, params)
  numpy_imgs = next(tfds.as_numpy(ds))[1]
img_grid = tfgan.eval.python_image_grid(numpy_imgs, grid_shape=(10, 10))
plt.axis('off')
plt.imshow(np.squeeze(img_grid))
plt.show()
--------------------- Error that arises ---
AttributeError                            Traceback (most recent call last)
<ipython-input-20-70878da6d9e2> in <lambda>(_)
     12 
     13   noise_ds = (tf.data.Dataset.from_tensors(0).repeat()
---> 14               .map(lambda _: tf.random_normal([bs, nd])))
     15 
     16   if just_noise:

AttributeError: module 'tensorflow' has no attribute 'random_normal'

Second error:
-- Original Code -------------------
train_batch_size = 32 #@param
noise_dimensions = 64 #@param
generator_lr = 0.001 #@param
discriminator_lr = 0.0002 #@param

def gen_opt():
  gstep = tf.train.get_or_create_global_step()
  base_lr = generator_lr
  # Halve the learning rate at 1000 steps.
  lr = tf.cond(gstep < 1000, lambda: base_lr, lambda: base_lr / 2.0)
  return tf.train.AdamOptimizer(lr, 0.5)

gan_estimator = tfgan.estimator.GANEstimator(
    generator_fn=unconditional_generator,
    discriminator_fn=unconditional_discriminator,
    generator_loss_fn=tfgan.losses.wasserstein_generator_loss,
    discriminator_loss_fn=tfgan.losses.wasserstein_discriminator_loss,
    params={'batch_size': train_batch_size, 'noise_dims': noise_dimensions},
    generator_optimizer=gen_opt,
    discriminator_optimizer=tf.train.AdamOptimizer(discriminator_lr, 0.5),
    get_eval_metric_ops_fn=get_eval_metric_ops_fn)
-----------------------------------------------------
------------Code Error---------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-1e10a3d25898> in <module>()
     18     params={'batch_size': train_batch_size, 'noise_dims': noise_dimensions},
     19     generator_optimizer=gen_opt,
---> 20     discriminator_optimizer=tf.train.AdamOptimizer(discriminator_lr, 0.5),
     21     get_eval_metric_ops_fn=get_eval_metric_ops_fn)

AttributeError: module 'tensorflow._api.v2.train' has no attribute 'AdamOptimizer'
--------------------------------------------------
- Describe the expected behavior:
It seems this notebook was designed as of Tensorflow 1.X
but never upgraded to version 2.X
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/github/tensorflow/gan/blob/master/tensorflow_gan/examples/colab_notebooks/tfgan_tutorial.ipynb

**Comment by craigcitro** [comment]
You should report this on the repo that contains that notebook (tensorflow/gan).

**Comment by hbono2019** [comment]
This is what I call customer service, you get rid of the issue instead of passing it onto the correspondent team.

Totally professional approach, not on my bucket and close the issue.

**Comment by hbono2019** [comment]
I will open the issue to the team then

**Comment by Miguelme** [comment]
+1
