### ISSUE TITLE
Not able to install pocketsphinx

### ISSUE THREAD

**Issue by msd495** [googlecolab/colabtools#12]
```
Failed building wheel for pocketsphinx
?25h  Running setup.py clean for pocketsphinx
Failed to build pocketsphinx
Installing collected packages: pocketsphinx
  Running setup.py install for pocketsphinx ... ?25l- error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ng194sfh/pocketsphinx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-iw5epd6l-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build_ext
    building 'sphinxbase._ad' extension
    swigging swig/sphinxbase/ad.i to swig/sphinxbase/ad_wrap.c
    swig -python -modern -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/android -Ideps/sphinxbase/swig -outdir sphinxbase -o swig/sphinxbase/ad_wrap.c swig/sphinxbase/ad.i
    unable to execute 'swig': No such file or directory
    error: command 'swig' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ng194sfh/pocketsphinx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-iw5epd6l-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ng194sfh/pocketsphinx/
```

**Comment by craigcitro** [comment]
The issue here is that two of the [non-python dependencies for `pocketsphinx`](https://github.com/bambocher/pocketsphinx-python#install-requirements) are missing in Colab by default; installing them first should have you up and running.

    !apt-get install -y swig libpulse-dev
    !pip install pocketsphinx

worked for me.

**Comment by JigarJoshi04** [comment]
Pocketsphinx was not able to install. 
So I had to install:

!apt-get install -y swig libpulse-dev
!pip install pocketsphinx
And PocketSphinx was up and running.

**Comment by giantest** [comment]
this solution used to work but now I suddenly get an error when running 

`!apt-get install -y swig libpulse-dev`

error:
`Err:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpulse-mainloop-glib0 amd64 1:11.1-1ubuntu7.9
  404  Not Found [IP: 91.189.88.142 80]
Err:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpulse-dev amd64 1:11.1-1ubuntu7.9
  404  Not Found [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/p/pulseaudio/libpulse-mainloop-glib0_11.1-1ubuntu7.9_amd64.deb  404  Not Found [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/p/pulseaudio/libpulse-dev_11.1-1ubuntu7.9_amd64.deb  404  Not Found [IP: 91.189.88.142 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

using --fix-missing did not help either...

Does anyone experience the same problem? I realize this is probably the wrong place to post this issue so any redirection is appreciated as well.

**Comment by giantest** [comment]
this solution used to work fine in colab but since a few days you might also need to run
`!apt-get update`
before you can successfully run
`!apt-get install -y swig libpulse-dev`

hope this is helpful for someone:)

**Comment by sri497111** [comment]
how do you do this in vs code?

**Comment by sri497111** [comment]
how do you do this in vs code?

**Comment by sri497111** [comment]
how do you do this in vs code?
