### ISSUE TITLE
IPython and Shell Commands - "!!" should throw error

### ISSUE THREAD

**Issue by vishwr7** [googlecolab/colabtools#1200]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
!!ls -ltr
['total 4', 'drwxr-xr-x 1 root root 4096 Apr  3 16:24 sample_data']

- Describe the expected behavior:
Using "!!" for shell commands in GoogleColab should throw error - ['/bin/bash: !ls: command not found'].
As per documentation, we should use only single "!" for passing shell commands.

- The web browser you are using (Chrome, Firefox, Safari, etc.): 
Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1Ginp6DA30iE_yrC1HtcvoXUPydxPr1ZH?usp=sharing

**Comment by craigcitro** [comment]
This is a longstanding IPython behavior: [docs](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-sx)
