### ISSUE TITLE
Elements on screen resizing during code execution

### ISSUE THREAD

**Issue by groer99** [googlecolab/colabtools#1201]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

I have two screens on my PC, one of them set to 125% scaling, the other to 100%. Even when the Colab window is only on the screen with 100% scaling, during execution of code cells, some output cells suddenly resize to larger text and then switch back to normal scaling. All output on the screen is moving. When I set both screens to 100% scaling, nothing like this is observed.

- Describe the expected behavior:

No rescaling.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Edge 83 (Windows 10)

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by blois** [comment]
Is that using OS display scaling? Do you know if it’s only Edge which does
this?

**Comment by groer99** [comment]
Yes, this is Windows 10 display scaling. Could confirm the same with Chrome 81.

Please see example screenshots attached:
![Bild1](https://user-images.githubusercontent.com/20140359/80867609-53132200-8c95-11ea-886a-45543afaeade.png)

In this example: Screen 1 set to 150% scaling, Screen set to 100%. Browser window on screen 2.

Left part: Normal view
Right part: When I add a new code cell or execute code, some text suddenly changes size for a short moment.

**Comment by blois** [comment]
Do you know if this is only happening to cells with error tracebacks, or all types of outputs?

**Comment by blois** [comment]
Tracking  internally with b/147382246.

**Comment by groer99** [comment]
Yes, also happens with text output and plots (matplotlib).

Only seems to happen on the secondary screen, when it is using a different
scaling than the primary screen.

Am Mo., 4. Mai 2020 um 18:12 Uhr schrieb blois <notifications@github.com>:
