### ISSUE TITLE
"Mount drive" button in web-interface works with bug - does not allow to access  "Add shortcut to Drive" files, while "old" command-line mount is okay 

### ISSUE THREAD

**Issue by chervov** [googlecolab/colabtools#1205]
The problem is described here:
https://stackoverflow.com/a/61560765/625396

"Mount drive" button in web-interface works with bug -
does not work the same as command line mount drive instructions,
in respect of accessing files "shared with me"+"Add shortcut to Drive" .

**Comment by colaboratory-team** [comment]
Thanks for the bug report. Tracking internally as b/155539909

**Comment by theendlessriver13** [comment]
This seems to be the same problem I described in #1188

**Comment by colaboratory-team** [comment]
Thanks again for the bug report. The issue should now be fixed on our end.
