### ISSUE TITLE
Unable to connect to google drive

### ISSUE THREAD

**Issue by shrenik007** [googlecolab/colabtools#1208]
I am trying to connect to my google but it is not connecting to the desired google drive but if I choose another google drive account then it connects properly. 

I am attaching a screenshot for the reference

![Screenshot from 2020-05-03 21-28-41](https://user-images.githubusercontent.com/16061768/80925124-42da7000-8d85-11ea-8f0f-1ccec0f5e3eb.png)

**Comment by blois** [comment]
Did the steps linked in the error message help resolve the issue?
https://research.google.com/colaboratory/faq.html#drive-timeout
