### ISSUE TITLE
Proper Google Drive integration?

### ISSUE THREAD

**Issue by pointyointment** [googlecolab/colabtools#121]
Why not just have a checkbox in the runtime settings to enable native filesystem-level access to the Google Drive of the Google Account that owns the notebook?

Currently we have to install and set up `google-drive-ocamlfuse`—which requires clicking through the OAuth approval screens and copying and pasting an API key (sometimes twice)—every time we reopen a notebook/restart the runtime. The only other options I know of, the REST API and PyDrive, don't look to provide filesystem-level access, and I expect they would have the same annoying requirement of copying and pasting an API key to effectively connect my account to itself, every time.

**Comment by CSEMike** [comment]
b/68936165

**Comment by madhurkashyap** [comment]
All the more at least the google-drive-ocamlfuse was working till last few days. It has started to now fail with below error. Are colab servers using older version of Linux distro which results in this failure ?

!apt-get install --fix-missing -y -qq software-properties-common python-software-properties module-init-tools

Unable to correct missing packages.
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/d/distro-info-data/distro-info-data_0.36ubuntu0.1_all.deb  404  Not Found [IP: 91.189.88.149 80]
E: Aborting install

**Comment by colaboratory-team** [comment]
A work-around for the 404 is to add an `!apt-get update` before the install. For example:

```
!apt-get update -qq 2>&1 > /dev/null
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
```

**Comment by colaboratory-team** [comment]
Good news: we now bundle the support needed to mount your Drive in the filesystem. In short:

```
from google.colab import drive
drive.mount('/content/drive')
```

This snippet mounts your Drive files at `/content/drive`. [I/O notebook example](https://colab.research.google.com/notebooks/io.ipynb#scrollTo=7-JR7WQ5O70X).

**Comment by lastephanieee** [comment]
Hello @colaboratory-team , I tried to authenticate myself to google drive with this code 
`!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse

auth.authenticate_user()
creds = GoogleCredentials.get_application_default()
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}


!mkdir -p drive
!google-drive-ocamlfuse drive`

and still google kicks me out with this message:

Error 400: invalid_scope
Some requested scopes cannot be shown: [https://www.googleapis.com/auth/drive, https://www.googleapis.com/auth/compute, https://www.googleapis.com/auth/appengine.admin, https://www.googleapis.com/auth/cloud-platform]
Request Details
redirect_uri=urn:ietf:wg:oauth:2.0:oob
prompt=select_account
response_type=code
client_id=32555940559.apps.googleusercontent.com
access_type=offline
display=page
scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/appengine.admin https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/accounts.reauth https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/plus.me

How should I fix my problem?

**Comment by colaboratory-team** [comment]
Sorry for the trouble. There's an ongoing issue with a downstream dependency that we're working on correcting with the relevant teams.

An immediately applicable work-around is to use the built-in Drive FUSE client by running the snippet below to mount your Drive files:

```
from google.colab import drive
drive.mount('/content/drive')

```

> Hello @colaboratory-team , I tried to authenticate myself to google drive with this code
...
> Error 400: invalid_scope

**Comment by dmitriyC300** [comment]
no longer seeing an issue of invalid_scope w/ suggested workaround.  thanks for adding built-in drive mount support.

**Comment by lastephanieee** [comment]
@colaboratory-team I have issue again, every time I try to mount my drive to colab, the timeout exceeds and I can't mount it. How can I solve my issue?

**Comment by pointyointment** [comment]
The integration of `google-drive-ocamlfuse` is a bit more convenient, so thanks for that, but I don't think it'll solve the problem I was having with it (which might be related to @lastephanieee's problem too). It's been a while, but I think I figured out it was using the API key incorrectly, or the way it's used in Colab results in improper usage. According to an article I remember reading back in April (**so this is all from memory and therefore probably somewhat inaccurate**), when you click the link that `google-drive-ocamlfuse` gives you, and you get a key, that key is only supposed to be used once to request a new key (of a different kind), which you can then use to access your files long-term. The first key only works once, and if you repeatedly request new keys of that type, the API gets mad at you.

That's why I wanted to download my google-drive-ocamlfuse config, which I think stores the second key, and reupload it in later sessions (difficulty with which was the subject of #122), so that I didn't have to keep requesting that first kind of key. But that would still be inconvenient compared to a checkbox (in which case I imagine it would be the whole Colab app, not the notebook or its host, that the user authorizes to connect to Drive.)

**Comment by cahau1222** [comment]
Hi Colab team,

I have been having issue with mounting the google drive in colab using the command. I managed to do it with colab cpu, however it failed whenever i switched it to GPU, is there any solution to it? (FYI there is less than ten files in my drive)

from google.colab import drive
drive.mount('/content/drive')

Thanks!
