### ISSUE TITLE
Why is Tensorboard showing rarely?

### ISSUE THREAD

**Issue by jandevries123** [googlecolab/colabtools#1226]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I just run my keras model and i call:
%load_ext tensorboard
%tensorboard --logdir tensorboard/
to load tensorboard, this launches tensorboard, though when i leave the browser idle for sometime it out doesn't update anymore of is replaced by a white block. When reloading the page it stays blank. Restarting the runtime also gives me a blank block. It says it is reusing the tensorboard on port xyz. The only way i can have it show up is by eliminating the session and creating a new one.
I am assuming this actually an intended behaviour regarding RAM maybe? Therefor i am rather looking for an explaination about how Tensorboard works on Google Colab/Notebooks? than a solution, since i am not that firmiliar with them and confused what is causing this nor how to resolve this. 
- Describe the expected behavior:
To just load and update the tensorboard event after left idle.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Google Chrome
- Link to self-contained notebook that reproduces this issue
Can't share my code, but nothing special then the descriped context.

Thank you for helping in advance.

**Comment by blois** [comment]
When you get the white block, can you try moving the cell up/down within the notebook using the up/down arrows in the cell toolbar?

**Comment by jandevries123** [comment]
> When you get the white block, can you try moving the cell up/down within the notebook using the up/down arrows in the cell toolbar?

No, the white block is non interactable and scrolling up or down is not even an option.

**Comment by jandevries123** [comment]
Please delete issue.
