### ISSUE TITLE
Session crashes on `tfa.image.rotate`

### ISSUE THREAD

**Issue by jraman** [googlecolab/colabtools#1229]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Session crashes repeatedly (like six or seven times, consecutively) on this line:
``` py
img1 = tfa.image.rotate(img, angles=0.0873, interpolation='BILINEAR')
```
where, as usual, `tfa` is `tensorflow_addons`.

Error message: _"Your session crashed for an unknown reason."_

After repeated attempts, I have not been able to get past this line.

My code runs fine if this one line is commented out.

- Describe the expected behavior:
I did not expect it to crash the session.

If there was a bug in my code, I expected an error message, but not a crash.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/drive/1_Qs6hDK9m1MOQLH-KJ830UkGBSCJYuua?usp=sharing

**Comment by colaboratory-team** [comment]
This is tensorflow/addons#1298 unfortunately.
You can work around this by `pip install tfa-nightly` but that will be brittle in future (and likely buggier than non-nightly once this is fixed) since it's a nightly release.
