### ISSUE TITLE
Files Downloading Issue over 90MB

### ISSUE THREAD

**Issue by nageshwaghmare** [googlecolab/colabtools#123]
After training the CNN model in google Colab, every time I get the error as 
Error: Failed to download:
the file size is around 90MB
![screenshot 121](https://user-images.githubusercontent.com/26818148/38677275-671d73fa-3e7b-11e8-8017-a36ec5533a9e.png)

**Comment by blois** [comment]
When it does succeed, I'm seeing that Chrome's time-to-first-byte is quite long (approaching 2 minutes), which implies that the responses are not being streamed. Investigating.

**Comment by fischman** [comment]
Should be fixed now.
