### ISSUE TITLE
cv2 imread function is not working properly

### ISSUE THREAD

**Issue by vikalpjain91** [googlecolab/colabtools#1230]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
cv2.imread function is returning none while reading a file.

- Describe the expected behavior:
It should read the file.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1o1A9WpENxEtY6CxlHBQrga9QJvj-JExX?usp=sharing
(search with #### block)

here colab is able to find the image but it is unable to read it using cv2 function. and it is returning None.
Kindly check the screenshot below:
Colab:
![image](https://user-images.githubusercontent.com/16263750/81488708-ff529b00-9289-11ea-84f7-dab91e02aec9.png)

Local Jupyter:
![image](https://user-images.githubusercontent.com/16263750/81488661-4be9a680-9289-11ea-9000-7d6077154fab.png)

File location in Drive:
![image](https://user-images.githubusercontent.com/16263750/81488689-c1557700-9289-11ea-84f7-172491371bff.png)

**Comment by vikalpjain91** [comment]
While I was working imwrite got broke so i made a workaround to store pickle file. afterwards imread also got broke. both are cv2 functions which are not working. Can you please have a look!

**Comment by vikalpjain91** [comment]
@colaboratory-team any update?

**Comment by ojiwon-kenobi** [comment]
I know this is pretty old, but I figured out a workaround on this issue just now. I was also getting NONE returned from my cv2.imread calls- I was adding the path string and the files found in the directory to use as the parameter for `cv2.imread`

Putting the full path (`content/drive/MyDrive/yourPathToTheFile/xyz.png') as the parameter for `cv2.imread` corrected my issue.

**Comment by cperry-goog** [comment]
Thanks!
