### ISSUE TITLE
Mount drive taking forever to connect after passing the code

### ISSUE THREAD

**Issue by umairjavaid** [googlecolab/colabtools#1233]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Mount drive taking forever to connect after passing the code
- Describe the expected behavior:
To get connected instantly
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1juVjDz2bKLm7W12rNu8o8pG8V1AcRzaC

**Comment by blois** [comment]
See https://research.google.com/colaboratory/faq.html#drive-timeout
