### ISSUE TITLE
iam unable to connect local runtime 

### ISSUE THREAD

**Issue by saikirannarayana** [googlecolab/colabtools#1234]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by saikirannarayana** [comment]
![Screenshot (543)](https://user-images.githubusercontent.com/33194364/81506694-ded02280-9315-11ea-8f37-0823221576e2.png)

**Comment by craigcitro** [comment]
Did you try clicking "Troubleshoot"? Did any of those suggestions help?
