### ISSUE TITLE
When I run the google colab file this is what I get.

### ISSUE THREAD

**Issue by Rowanihab** [googlecolab/colabtools#1237]
Could not load the JavaScript files needed to display output. This is probably because your Google Account login access has expired or because third-party cookies are not allowed by your browser.
I tried all solutions concerning cookies and allowing cookies but in vain.

**Comment by AndreeaMusat** [comment]
I think I've been having the same problem and it worked when I tried in a new incognito tab, maybe it also works for you.

**Comment by Rowanihab** [comment]
Thanks. I’ve solved it by uninstalling google chrome and re-installing it
