### ISSUE TITLE
Insert form from the top menu not working

### ISSUE THREAD

**Issue by EmanuelDri** [googlecolab/colabtools#1238]
I'm inserting interactive forms into a colab notebook. If they are introduced using the top menu Insert->Add form, the resulting form never appears. Instead, if it is added using the options side panel of the code cell it actually works.

I'm using Brave Browser 1.8.95 on Windows 10 Pro x64 Build 1909

Link to the notebook on which I experienced this issue:
https://colab.research.google.com/drive/1qTCpHn0VMhsFUyRoqsV2WdU4sNTzWwjA#scrollTo=rGAEl0AivG52

**Comment by corrieann** [comment]
Thanks for the bug report.  This should now be fixed.
