### ISSUE TITLE
Unable to save notebook to private Github repo

### ISSUE THREAD

**Issue by alexanderwhatley** [googlecolab/colabtools#124]
Also posted on StackOverflow: https://stackoverflow.com/questions/49805960/google-colab-cannot-access-github-private-repositories

I'm trying to save my colab notebook to a private Github repository, but it, and all of my other private repositories, do not appear in the dropdown list when I click "Save a copy to Github."

**Comment by corrieann** [comment]
Sorry, we only request the public_repo and gist scopes currently (https://developer.github.com/apps/building-oauth-apps/scopes-for-oauth-apps/).  We may add support for this in the future, but currently you'll need to either use a public repo or download the ipynb (File -> Download .ipynb) and manually upload your file to GitHub.

**Comment by jakevdp** [comment]
Update: private repos are supported (look for the "include private repos" check-box in Colab's github pane).

**Comment by fqassemi** [comment]
@jakevdp I am not sure why I can not find this "include private repos". Where exactly is this located?

**Comment by 7ruth** [comment]
The Colab's github pane referred above, is not the pane you get when you are trying to save to github, its the pane you see when you go to File => Open Notebook => click on 'Github' tab and checkbox should be on the top right.

**Comment by mirfan899** [comment]
It's buggy. Some times it shows repositories and some times not. Also what to do next when we select the repository after authentication? No `OK` button or any guide go next. I can't clone even after authentication from GitHub.

**Comment by KaleabTessera** [comment]
For me, I had to go to Tools->Preferences->Request GitHub access to view and edit private repositories and organizations.

**Comment by eafpres** [comment]
> This menu option doesn't exist for me.

It is now Tools, Settings and the option is there and worked for me

**Comment by WittmannF** [comment]
For me it did not work for organizations, just for private repos. Any hint what could be the problem?

**Comment by anujgupta82** [comment]
@WittmannF : any solutions?

**Comment by WittmannF** [comment]
@anujgupta82 I forked the repository into my own Username account. After making the changes and saving from colab I sent a pull request to the organization. Still waiting for a solution where I can directly save into the organization.

**Comment by eyalho** [comment]
@WittmannF Also for me it did not work for organizations, just for private repo.
Did you found any solution?

**Comment by 134130U** [comment]
I got the same issue to work for organization with public repository. 
Please can someone help me

**Comment by rruggi** [comment]
Also with the same problem Here, very cumbersome fork process described above.

**Comment by Bennyhwanggggg** [comment]
Hi, currently getting the same issue with personal private repo, could this be looked at?

**Comment by josealvarez97** [comment]
Why isn't it possible to save to a private organization?

**Comment by josealvarez97** [comment]
Well, as it turns out, it seems you can overwrite it. This still works well with organizations. Just click save a copy to GitHub -- it won't really save a "copy" in the broadest sense. 

I guess that's a functional workaround.

(It will keep comitting "Created using Colaboratory" though)
![image](https://user-images.githubusercontent.com/21250471/102857511-2cedee00-43ee-11eb-97a7-9a013c9325d4.png)

**Comment by WittmannF** [comment]
Not sure if I understood. How did you do it @josealvarez97?

**Comment by josealvarez97** [comment]
> Not sure if I understood. How did you do it @josealvarez97? 

Go to file a save a copy to Github. This is assuming to at least accomplished to do it a fisrt time (I was just speaking of overwriting it).

If you can't see private repos, then you may need to try opening one first. Im that process you'll be able to click a checkmark for allowing access to peivate repos. Then you'll be able to save them too.

Hope that helps.

**Comment by josealvarez97** [comment]
Because it's the first time that I connect my colab notebook to GitHub, I made the big mistake of recharging the page after some work. The changes were lost. I wonder if there's a way to include automatic saving to notebooks that are loaded from GitHub. At the end, it's what we're used to when working within this environment...

**Comment by WittmannF** [comment]
Saving a copy on github doesn't work for organizations

**Comment by yerbby** [comment]
I have activated the option to access private repos and gists. I can open private colab notebooks and gists. I can save a colab notebook to github gist (a new commit is automatically created). But I CAN NOT save a colab notebook to a repository on github, y says I have no authorization. 

Any hints???

**Comment by thucnc** [comment]
I got the same issue of loading notebooks from private organization. Anyone knows workaround ?

**Comment by sohan656** [comment]
Well I guess whenever the popup comes by collab to allow it to link with Github just allow it

**Comment by tejuafonja** [comment]
I was able to toggle on private repositories via `Tools > Settings > GitHub > Access private repositories and organizations`

**Comment by dwheale-equi** [comment]
If anyone continues to have this problem, I found that although my personal github account has access to my organization, you have to specifically enable colab's access to the org.

**Comment by IgnatiusEzeani** [comment]
> If anyone continues to have this problem, I found that although my personal github account has access to my organization, you have to specifically enable colab's access to the org.

How does one enable access to their org's repo?

**Comment by JavierAsprillaG** [comment]
> > If anyone continues to have this problem, I found that although my personal github account has access to my organization, you have to specifically enable colab's access to the org.
> 
> How does one enable access to their org's repo?

If you're an owner, in your organization repo, go to Settings, scrolls down, see at the left menu the Third party Access section, clic on OAuth applications policy (https://github.com/organizations/YOUR_ORG_NAME/settings/oauth_application_policy), and clic the button revoke restrictions. Now when you save a copy to github from colab it will also show your organization repos.

Set up again the restrictions once all members finish their contributions.

**Comment by sandrovw64** [comment]
> For me, I had to go to Tools->Preferences->Request GitHub access to view and edit private repositories and organizations.

Thanks @KaleabTessera 
It works for me

**Comment by hyperkai** [comment]
Putting a username always works to show private repositories as shown below:

> hyperkai

![Screenshot 2024-10-18 042321](https://github.com/user-attachments/assets/28e7aa91-9410-4075-a5dc-d5fd69017765)

But putting a url always or sometimes doesn't work to show private repositories as shown below:

> https://github.com/hyperkai

![Screenshot 2024-10-18 042435](https://github.com/user-attachments/assets/fe5cb890-7304-4937-840a-964c989e0062)
