### ISSUE TITLE
Unable to upgrade from 12 gb ram to 25gb after using all of 12gb and crashing

### ISSUE THREAD

**Issue by mashdas** [googlecolab/colabtools#1246]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:When the ram gets used up to the limit(about 12gb),an option for a ram upgrade(about 25gb) should automatically appear.All i get is an option to view the runtime logs.

- Describe the expected behavior:
RAM upgrade option should be available

- The web browser you are using (Chrome, Firefox, Safari, etc.):
chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by colaboratory-team** [comment]
Resources are not guaranteed may vary over time. For more context, see: https://research.google.com/colaboratory/faq.html#resource-limits

**Comment by Jangab-water** [comment]
I cannot increase the ram over 13.88GB! when I use ram 13.88GB over, they shutdown my kernel, and don't show any other message without 'show runtime log'! I need your help, bros.
