### ISSUE TITLE
Can we continue cell after reconnect?

### ISSUE THREAD

**Issue by jianmosier** [googlecolab/colabtools#1248]
I am cleared about notebook may be disconnected due to some limited factor. But, is there any way to continue my cell running after reconnect based last running . I mean, google drive + colab,when i training network with GPU on colab get some interrupt, how can we continue training after reconnect.

**Comment by jianmosier** [comment]
Can pydrive do this work?

**Comment by Dovermore** [comment]
I am not a dev but consider adding checkpoints (each batch or each epoch) in your code so you can resume training? I'm sure this will be much simpler than requiring devs to add a complex functionality like what you have described.

**Comment by Dovermore** [comment]
You can also use the following code to prevent your notebook from disconnecting
```
function KeepClicking(){
   console.log("Clicking");
   document.querySelector("colab-connect-button").click()
}
clicking = setInterval(KeepClicking,60000)
```

**Comment by jianmosier** [comment]
Ckpt may be the only simply way to continue train , tks for your advice.
