### ISSUE TITLE
colab ram is not increasing 

### ISSUE THREAD

**Issue by tanay5678** [googlecolab/colabtools#1251]
after using all ram which 12 GB ..it should increase to 25 GB but it is not, the ram crashes.
as per colab said when we use whole 12 GB ram it can extend to 25 GB but it is not extending.

**Comment by akash-yadagouda** [comment]
Some issue I am also getting. Please, google work on it. I think it is a bug in the system.

**Comment by ambuje** [comment]
Same issue please fix it asap.

**Comment by rishabkr** [comment]
same issue,12.7 gb is too less for my notebook, i am not able to expand it after using all 12.7 gb.Please fix it.
