### ISSUE TITLE
ColabPro: Reading files from mounted Google drive results in OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by Santosh-Gupta** [googlecolab/colabtools#1254]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:

I am trying to read a file from my mounted google drive, but I get this error

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-9-ed63b6fdd88d> in <module>()
      1 with open('/content/drive/My Drive/AbstractNet/JustMedicinePapers/RowNumToIndexID.json', 'r') as fh:
----> 2     indexIDtoRowNum = json.load(fh)

/usr/lib/python3.6/json/__init__.py in load(fp, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    294 
    295     """
--> 296     return loads(fp.read(),
    297         cls=cls, object_hook=object_hook,
    298         parse_float=parse_float, parse_int=parse_int,

OSError: [Errno 5] Input/output error
```

- Describe the expected behavior:

It should read the file without a problem. 

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome 

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/drive/1oDvadEOSVy9gepurMyI9QSA5tdggtbXP?usp=sharing

If it makes a difference, I also have a paid google drive account, 200 gb. 

I tried contacting Google One/Google Drive support, and they weren't able to help me.

**Comment by Santosh-Gupta** [comment]
It seemed like the google drive integration was somewhat back to normal now, at least for smaller files, but occasionally even now I am getting I/O errors with smaller 13 mb files


```
['Error opening ', '/content/drive/My Drive/AbstractNet/JustMedicinePapers/ListsOfCitations/citListsSplitOrient-055.json']
['Error', OSError(5, 'Input/output error')]
```

Link to notebook

https://colab.research.google.com/drive/1HSB6ZkP6_PvVygk16AkjzdWQpwQPvPaf?usp=sharing

**Comment by Santosh-Gupta** [comment]
It's been three days since I starting encouraging this issue and I am still not able to read 13 mb json files from my drive.

https://colab.research.google.com/drive/11cVqQPZNBUtTHmukm-uDf2Z8otQD93Fo?usp=sharing

**Comment by coryroyce** [comment]
I'm having the same issue "OSError: [Errno 5]" trying to load a 2MB .pickle file from my mounted drive.
Are there any work arounds or ways to refresh so that this error stops?

**Comment by EByrdS** [comment]
I am having this same error right now. Any fix that prevents this from happening? I worked fine some days ago, but now it is not working.

**Comment by davidshumway** [comment]
Any solution?

**Comment by cperry-goog** [comment]
Pretty confident this is a reflection of too many files: https://research.google.com/colaboratory/faq.html#drive-timeout
