### ISSUE TITLE
ArcGIS API for Python. Map is not displayed in colab.

### ISSUE THREAD

**Issue by zaharyonok** [googlecolab/colabtools#1255]
Hello!
I am using ArcGIS API for displaying satellite data in Colab notebook.'
The piece of code is very basic:
`gis = GIS()`
`map1 = gis.map()`
`map1`
It should display the map but it doesn't.
Any help appreciated!
Thanks!

**Comment by blois** [comment]
ArcGIS requires third-party widget support, specifically arcgis-map-ipywidget.

This is covered by https://github.com/googlecolab/colabtools/issues/498.

**Comment by salmagro** [comment]
@zaharyonok did you find a way to run the API on colab?
