### ISSUE TITLE
Issue with reading large file

### ISSUE THREAD

**Issue by vsanz** [googlecolab/colabtools#1258]
I am using Google Colab, and cannot read a h5f file (22GB).  The error message contains:

error message = 'Input/output error'

I see in other posts this is a well-known problem with Google services, but no solution is provided. 

Some people mention with Google Pro or with GSuite one can avoid this "bug". But I have paid for the Google Colab Pro AND the 100 GB upgrade of GDrive AND upgraded RAM, so it's not an issue that will be solved by paying more. 

This is supposed to be a Machine Learning platform. Files of tenths of GB are not unusual in this kind of work. I really don't understand how this problem isn't solved or properly documented.

**Comment by AlainMindana** [comment]
Hi have you resolved this?

**Comment by colaboratory-team** [comment]
This is likely a dup of #1607.
