### ISSUE TITLE
Disk Mount is not working properly!

### ISSUE THREAD

**Issue by vikalpjain91** [googlecolab/colabtools#1267]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Files stored by python is not visible in google drive.

- Describe the expected behavior:
Google drive should show the files.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1pNI-TR07bBaXM32OJJcMf3ZiBhEgbcuW?usp=sharing

Issue:
I AM USING GOOGLE COLAB PRO
I am using standard environment and created four files in drive to store:
![image](https://user-images.githubusercontent.com/16263750/82525697-a1f2ff80-9b4f-11ea-864b-b41a77843ae5.png)

After creation I am unable to see those files:
![image](https://user-images.githubusercontent.com/16263750/82525726-bafbb080-9b4f-11ea-9bd9-490fc3333308.png)

I am checking atleast after giving 1 hour of time to colab.
Main issue is files are also not accessible via colab with GPU runtime.
![image](https://user-images.githubusercontent.com/16263750/82525820-057d2d00-9b50-11ea-8d04-a7834c142a70.png)

**Comment by gryfi** [comment]
I also have some problem
but, I just use free account

for simple mount

> from google.colab import drive
> drive.mount('/content/drive')

for today, it is doesn't work
when get request code for google drive also got error

also for server keep busy all the time
i cannot do simple task anymore, even for one line code

i think there is problem with server
because of, I saw thread many Google Colab pro account have many problem recently

**Comment by vikalpjain91** [comment]
it needs to shutdown the vm to make it sync to drive. Very problematic. Even I am paying but there is no response from colab team. what is the use of subscription. Though colab is very helpful but still this needs to be fixed otherwise it is not useful when data is not available for GPU.

**Comment by gryfi** [comment]
I already try "factory reset runtime"
but, doesn't work till now

yeah, you already paid for Google Colab Pro, but they still not respond it

**Comment by vikalpjain91** [comment]
Can We have a method call which will sync up the drive with colab? Because most of the time it is taking so much time but still it is unable to discover files from VM inside google drive.
once we will execute that function it can show which files it is discovering so we can have patience!
@colaboratory-team @blois ?

**Comment by colaboratory-team** [comment]
The `google.colab.drive` module has a `flush_and_unmount()` function that you can use to sync data written to the local VM's disk cache of your Drive-mounted folder back to Google Drive.
