### ISSUE TITLE
Header Tags Using Markdown Removes Underlines from Forms

### ISSUE THREAD

**Issue by Danc2050** [googlecolab/colabtools#1275]
- Describe the current behavior:
  When using markdown syntax in a code cell and any header tags (e.g., `<h1>`) inside of that 
  syntax, some underlines below a forms input/selection section disappears.
- Describe the expected behavior:
  Valid markdown syntax should not affect a form's underline.
- The web browser you are using (Chrome, Firefox, Safari, etc.):
  Brave
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
  https://colab.research.google.com/drive/1W9wAGf9uASXwYearrr1I3Vifd8Z15RAk?usp=sharing

**Comment by blois** [comment]
I'm not sure what difference in underlines you're referring to. This is what I'm seeing using Brave browser:
![image](https://user-images.githubusercontent.com/2152569/83169390-d45ca980-a0c7-11ea-87e9-5be8d6efb8e1.png)

**Comment by Danc2050** [comment]
Odd. This is what I am seeing:
![myscreen](https://user-images.githubusercontent.com/32185616/83169930-9b710480-a0c8-11ea-8df0-dc3f99f5ebc4.png)

I am running Linux Ubuntu 18.04 if that matters.

**Comment by Danc2050** [comment]
@blois Ah... try unzooming in your screen. The issue is present when that happens.

**Comment by blois** [comment]
Ok, yes- when my zoom is <100% then I'm seeing that the 1px lines occasionally disappear. The fix should be available shortly.

**Comment by Danc2050** [comment]
Sounds great -- thanks!

**Comment by blois** [comment]
This should be fixed now.

**Comment by Danc2050** [comment]
`>=80%` works without a hiccup, while `<80%` is where an underline(s) are lost (on Brave at least), but it is much improved. Thank you.
