### ISSUE TITLE
 Universal Sentence Encoder - Questions Classifier Example

### ISSUE THREAD

**Issue by loretoparisi** [googlecolab/colabtools#128]
The docs about the module **google/universal-sentence-encoder/1** [here](https://www.tensorflow.org/hub/modules/google/universal-sentence-encoder/1) refers to, among the other tasks this module can address, Classification tasks like *Question Classifier*, but there is no evidence of this in the provided Colab examples, that is a DNNClassifier for Sentiment Classification Task, and it is not using the mentioned sentence encoder example of course.
Could you please provide an example of Question Classifier, using the **google/universal-sentence-encoder/1** module?

In my understanding this is the implementation that is behind the AI Experiments tool "Talk2Books", that was recently announced _https://research.googleblog.com/2018/04/introducing-semantic-experiences-with.html_.

That would help a lot to better understand this powerful model.
Thanks a lot.

**Comment by colaboratory-team** [comment]
I'd recommend following up with the TensorFlow docs maintainers for improvements to the TF docs. Their issues template is here:

https://github.com/tensorflow/tensorflow/issues/new?template=20-documentation-issue.md
