### ISSUE TITLE
colab compute engine automatically disconnected frequently

### ISSUE THREAD

**Issue by me-my-aloha** [googlecolab/colabtools#1282]
The colab compute engine will automatically disconnect after connecting for a few seconds, and then it will automatically reconnect, but it will disconnect again after a few seconds. Even when I bought collab pro, it didn't improve

**Comment by colaboratory-team** [comment]
Likely this means either the runtime has been broken by an incompatible pip/apt install or else a very large output is clogging the pipes. Factory reset from the Runtime menu might unblock you. If not, please include a minimal standalone repro notebook.
