### ISSUE TITLE
docstring pop-up hides my code

### ISSUE THREAD

**Issue by dndgml913** [googlecolab/colabtools#1283]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by blois** [comment]
Automatic completions can be disabled in the Settings:
https://colab.research.google.com/notebooks/editor_details.ipynb#scrollTo=ev2VBsdN3psP

After doing this they can still be opened with either `Tab` or `Ctrl-Space`. Docstrings can be opened with `Ctrl-Shift-Space`.
