### ISSUE TITLE
scrolling bugged

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#1286]
[scroll_.zip](https://github.com/googlecolab/colabtools/files/4705529/scroll_.zip)

**Comment by blois** [comment]
This is not something we've seen before. Does is repro in incognito mode? What browser & version, and OS?

**Comment by vainaijr** [comment]
hello, it happen once, so I capture and share it, I no see it happen again, if it happen again then I inform, I use Chrome, Version 83.0.4103.61 (Official Build) (64-bit), I on Windows 10.

**Comment by metrizable** [comment]
Since this issue was filed a while ago, if you are still experiencing the issue, please file a new issue with steps to reproduce/screencast or file in-product feedback.
