### ISSUE TITLE
Unable to use Colab - Getting error: "Sorry, o backends available. Please try again later."

### ISSUE THREAD

**Issue by manichaw** [googlecolab/colabtools#1287]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: Getting error: "Sorry, o backends available. Please try again later."

- Describe the expected behavior: Reconnect + Run the code normally.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/drive/1a_cMrh16dBmVaMD71VxXEZPRPJbYVgjC#scrollTo=SvveDt2cWRJ2

**Comment by colaboratory-team** [comment]
Thanks for reporting the problem.

Typically, this message corresponds to usage limits described here:
https://research.google.com/colaboratory/faq.html#resource-limits

A recent service issue resulted in this message appearing for more users and more frequently than intended. 

The issue has been corrected. Sorry for the trouble.
