### ISSUE TITLE
Unable to use Colab - Getting error: "Sorry, no backends available. Please try again later."

### ISSUE THREAD

**Issue by akash1309** [googlecolab/colabtools#1288]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by colaboratory-team** [comment]
Duplicate of #1287
