### ISSUE TITLE
%%bigquery not working

### ISSUE THREAD

**Issue by andrenmo** [googlecolab/colabtools#129]
The bigquery magic (%%bigquery) is not working from colab.
The error appears when runing the bigquery demo notebook.
Even when reimporting the bigquery library the error appears.

![image](https://user-images.githubusercontent.com/23079130/38815023-55e83340-4169-11e8-991a-ec3e5ac031b6.png)

How to reproduce:
- Go to bigquery demo notebook:
https://colab.research.google.com/notebooks/bigquery.ipynb
- Try to run.

**Comment by craigcitro** [comment]
Whoops -- that one's my fault; the doc update got ahead of the container update.

If you use `pip install --upgrade` to update the two packages in https://github.com/googlecolab/backend-container/commit/4e249ce88a8b6d7b8dc3ad200ce6f57ad435ec8a, and then `%load_ext google.cloud.bigquery`, you should be up and running.

**Comment by andrenmo** [comment]
Hi, when i did:
```
!pip install --upgrade google-cloud-bigquery pandas-gbq
%load_ext google.cloud.bigquery
```
It worked, thanks.
