### ISSUE TITLE
GPU Memory Usage Not Corresponding To The Status Bar

### ISSUE THREAD

**Issue by sinclairjang** [googlecolab/colabtools#1292]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
<img width="1274" alt="Screen Shot 2020-05-30 at 9 40 57 PM" src="https://user-images.githubusercontent.com/58962488/83328628-519e3f00-a2bf-11ea-99d7-42eda2a6a7e6.png">
When I check the GPU memory usage, it's shown way less than that shown on the status bar on the right top.
- Describe the expected behavior:
Is status bar supposed to correspond to the actual memory usage?
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by colaboratory-team** [comment]
Status indicator is showing system/main RAM, while nvidia-smi is showing GPU RAM (two distinct types/sources of memory).
