### ISSUE TITLE
Sorry, no backends available. Please try again later.

### ISSUE THREAD

**Issue by YoavRaytz** [googlecolab/colabtools#1294]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: I'm trying to run my notebook and for like an hour it's pop up and 
say:" Sorry, no backends available. Please try again later."

- Describe the expected behavior: be able to run cells

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1ZlKAJLC-gICfAoVzD3z99hqg_YKE9E-4?usp=sharing

**Comment by colaboratory-team** [comment]
Duplicate of #1287
