### ISSUE TITLE
Page header is not shown in Colab

### ISSUE THREAD

**Issue by bikcrum** [googlecolab/colabtools#1297]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
The header is not shown in colab. I tried clearing site data but the problem seems to persist. However there is not issue with other google account. When I dug into the inspector found this. 
`<div id="header" class="horizontal layout" style="display: none;">`

- Describe the expected behavior:
The header is supposed to be shown. It was okay before. When I tried **display** to be **block** here it works. 
`<div id="header" class="horizontal layout" style="display: block;"> `

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
Every notebook has this issue on account bikcrum@gmail.com. Here is one example https://colab.research.google.com/notebooks/intro.ipynb

**Comment by katlyn-edwards** [comment]
There's a toggle on the right side to expand and collapse the header. It's saved as a preference per-account. I suspect your account has likely toggled the collapse header button accidentally.

Here's a screenshot:
![header_collapse_colab](https://user-images.githubusercontent.com/2673487/83335620-ea52a180-a262-11ea-8d69-67dea11c353c.png)

**Comment by bikcrum** [comment]
> There's a toggle on the right side to expand and collapse the header. It's saved as a preference per-account. I suspect your account has likely toggled the collapse header button accidentally.
> 
> Here's a screenshot:
> ![header_collapse_colab](https://user-images.githubusercontent.com/2673487/83335620-ea52a180-a262-11ea-8d69-67dea11c353c.png)

Thank you. I didn't know that.
