### ISSUE TITLE
Unable to type/paste anything into a google colab cell

### ISSUE THREAD

**Issue by aishwarya2905** [googlecolab/colabtools#1299]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: I was unable to paste a code snippet from another notebook into a cell. And when I tried to type into the cell, I couldn't type anything either.

- Describe the expected behavior: I should have been able to type into the cell

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by ocdex** [comment]
Unable to type into the code or text cells at all.
Not sure what is the problem.

Tried to see if it is keyboard issue. But it is not.
I used soft keyboard to type in and seeing the same problem.
But surprisingly the using the suggested keywords on the top of soft keyboard is getting typed in. Nothing else. Not even space.

**Comment by cperry-goog** [comment]
Can you attempt this in an incognito window?

And what device are you attempting this on?
