### ISSUE TITLE
Kitties and dogs are stuck at one place. It is making me nervous.

### ISSUE THREAD

**Issue by ayushman1024** [googlecolab/colabtools#1301]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Kitties and dogs are stuck at one place. It is making me nervous.

![image](https://user-images.githubusercontent.com/31370112/83405815-fdb06900-a42a-11ea-88d6-1f0270201021.png)

- Describe the expected behavior:
It should not be stuck at one place. Kitties and dogs moves around ,one or two at a time.
- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by katlyn-edwards** [comment]
Oops, will take a look - thanks for the bug report.

**Comment by katlyn-edwards** [comment]
Sorry about this! Should be fixed tomorrow around noon pacific

**Comment by katlyn-edwards** [comment]
Just an update - the fix is indeed now live.

**Comment by ayushman1024** [comment]
Thanks looks good, having nice company with kitties n doggo ☺
