### ISSUE TITLE
Is it possible to get a 20.04 Colab

### ISSUE THREAD

**Issue by cjds** [googlecolab/colabtools#1304]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Currently I cannot use some tools because they are only released for 20.04 and the list of changes is significant

- Describe the expected behavior:
I'd like to use Colab in an Ubuntu 20.04 environment. Specifically to use ROS Noetic
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

**Comment by craigcitro** [comment]
No, there's currently no way to do this.

**Comment by cjds** [comment]
Is there a timeline to add this as a feature?

**Comment by craigcitro** [comment]
Not currently.

**Comment by colaboratory-team** [comment]
#1880 now tracks the ubuntu 20.04 update.
