### ISSUE TITLE
Can't get high-RAM anymore

### ISSUE THREAD

**Issue by cathey-synex** [googlecolab/colabtools#1311]
Hi, I just opened a new notebook, and 12GB RAM is not enough. Previously I could crash the session and request a larger RAM, but now I couldn't. And in Notebook settings there's no option for a larger RAM either. I have Colab Pro, so I thought I'd have access to better settings. What should I do? Thanks

**Comment by craigcitro** [comment]
See https://github.com/googlecolab/colabtools/issues/1246#issuecomment-629341243
