### ISSUE TITLE
Is it possible to increase the ram in google colab? I am getting 12GB RAM but i need more RAM to train my model. Please help us.

### ISSUE THREAD

**Issue by nitishkmr005** [googlecolab/colabtools#1314]
Is it possible to increase the ram in google colab? I am getting 12GB RAM but i need more RAM to train my model. Please help us.

**Comment by dayfine** [comment]
Try [Colab Pro](https://colab.research.google.com/signup)? Or use a GCP instance with required amount of memory as your runtime: https://medium.com/@senthilnathangautham/colab-gcp-compute-how-to-link-them-together-98747e8d940e
