### ISSUE TITLE
Change LD_LIBRARY_PATH in Colab environment

### ISSUE THREAD

**Issue by cjds** [googlecolab/colabtools#1317]
Bug report for Colab: http://colab.research.google.com/.

I'm trying to change LD_LIBRARY_PATH environment variable before the `ipython` gets loaded but it doesn't seem to change even after updating kernelspec

- I changed the kernelspec to contain this:
```
    "kernelspec": {
      "name": "python2",
      "display_name": "Python 2",
      	"env": {
		"LD_LIBRARY_PATH": "/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/opt/ros/melodic/lib",
    "HELLO": "GOODBYE"
	    }
    }
```
However, when I do`!echo $HELLO` I see no changes

- I should see the word GOODBYE

**Comment by craigcitro** [comment]
Can you explain what you're trying to accomplish?

Note also that python2 is on its way out: https://research.google.com/colaboratory/faq.html#python-2-deprecation

**Comment by cjds** [comment]
This would still apply on Python 3. When calling C++ libraries within my Python you require `LD_LIBRARY_PATH` to be set correctly before the interpreter is started. i.e. as part of the interpreter process. If you change it at runtime of the intepreter it only applies to child shells and not the interpreter itself. This prevents you from using `LD_LIBRARY_PATH`s from outside the places they are searched for even if you can find them via `ldd`

**Comment by craigcitro** [comment]
If you want to tweak `LD_LIBRARY_PATH` for the current session, you should modify `os.environ`.

If you want this to persist across kernel restarts, you could modify the `exec_lines` in `/etc/ipython/ipython_config.py` and restart the kernel.

**Comment by vinaygcode** [comment]
> If you want to tweak `LD_LIBRARY_PATH` for the current session, you should modify `os.environ`.
> 
> If you want this to persist across kernel restarts, you could modify the `exec_lines` in `/etc/ipython/ipython_config.py` and restart the kernel.

Hi craigcitro,

Thank you for your reply.  I am trying to set LD_LIBRARY_PATH in google code colab by following statements:

```
import os
os.environ['LD_LIBRARY_PATH']='/path/to/library/used/by/my/software'
 
```
I can see the environment variable added in the environment variables list, checked by (!printenv), but when my exe tries to access the library stored at LD_LIBRARY_PATH, it is not able to find it.

`NotFoundError: library_name.so: cannot open shared object file: No such file or directory`

I also tried configuring the environment variables through colab-env package (https://pypi.org/project/colab-env/), but I am facing same issue with this approach also.

Can someone give pointers? Thank you.

**Comment by KelSolaar** [comment]
Alternatively, you could also copy your library to `/usr/lib`.

**Comment by jaimergp** [comment]
I managed to get it working with `execve`. Not perfect (spinner keeps spinning), but it works! Note this will restart the kernel.

``` 
os.environ["LD_LIBRARY_PATH"] = f"/usr/local/lib:{os.environ.get('LD_LIBRARY_PATH', '')}"
os.execve(sys.executable, [sys.executable] + sys.argv, os.environ)

# The spinner will keep running forever, but the cell did run! 
# It's a side effect of replacing the python process with execve... 😬
# You can keep going!
```
