### ISSUE TITLE
Output assignment option

### ISSUE THREAD

**Issue by AngelClaudio** [googlecolab/colabtools#1319]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Using %config InteractiveShell.ast_node_interactivity='last_expr' for example, I can not set the value to 'last_expr_or_assign' like in Jupyter Notebook. Can we get that option?

- Describe the expected behavior:
Would like to be able to use value 'last_expr_or_assign' for %config InteractiveShell.ast_node_interactivity setting, so that I can see assignment values.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
[Link of REPREX](https://colab.research.google.com/drive/19Sp07Jezv2GWHNJ8CBlyuJt8AgYQC0pB?usp=sharing)

**Comment by blois** [comment]
This is because Colab has not yet been upgraded to the latest IPython version- if you explicitly upgrade with `!pip install -U ipython` then `last_expr_or_assign` will work.
