### ISSUE TITLE
Error loading when I try to install gspread library

### ISSUE THREAD

**Issue by mcastilhosampaio** [googlecolab/colabtools#1320]
When I use the comand **!pip install --upgrade --quiet gspread** I receive the message **ERROR: google-colab 1.0.0 has requirement google-auth~=1.7.2, but you'll have google-auth 1.16.1 which is incompatible.**. Could you help me to solve this problem?

Thanks in advance

Best regards

**Comment by craigcitro** [comment]
Thanks for the report -- this should be fixed.
