### ISSUE TITLE
"Runtime type" does not show

### ISSUE THREAD

**Issue by brbisheng** [googlecolab/colabtools#1322]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
clicking "Notebook settings", I do not see the "change runtime type" option.
- Describe the expected behavior:
There should be an option "change runtime type“
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1XyVBfMJ3m23IsDVjPER7G-UZ0vd4gT2c?usp=sharing

**Comment by craigcitro** [comment]
This is WAI: python2 is being deprecated (https://research.google.com/colaboratory/faq.html#python-2-deprecation), so we don't show the dialog for python3 notebooks (since there's nothing else to select).
