### ISSUE TITLE
Google colab keeps on crashing while using pyyolo.

### ISSUE THREAD

**Issue by ramgarg102** [googlecolab/colabtools#1325]
Bug report for Colab: http://colab.research.google.com/.

Timestamp | Level | Message
-- | -- | --
Jun 11, 2020, 6:39:29 PM | WARNING | WARNING:root:kernel 1c954a2c-3ad4-449e-b204-44f85e85de9a restarted
Jun 11, 2020, 6:39:29 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Jun 11, 2020, 6:39:16 PM | WARNING | Done! Loaded 162 layers from weights-file
Jun 11, 2020, 6:39:15 PM | WARNING | Try to load weights: /mydrive/backup/yolov4_custom2_final.weights
Jun 11, 2020, 6:39:15 PM | WARNING | nms_kind: greedynms (1), beta = 0.600000
Jun 11, 2020, 6:39:15 PM | WARNING | nms_kind: greedynms (1), beta = 0.600000
Jun 11, 2020, 6:39:15 PM | WARNING | nms_kind: greedynms (1), beta = 0.600000
Jun 11, 2020, 6:39:15 PM | WARNING | mini_batch = 1, batch = 1, time_steps = 1, train = 0
Jun 11, 2020, 6:39:15 PM | WARNING | net.optimized_memory = 0
Jun 11, 2020, 6:39:15 PM | WARNING | Try to load cfg: /content/darknet/cfg/yolov4_custom2.cfg, weights: /mydrive/backup/yolov4_custom2_final.weights, clear = 0
Jun 11, 2020, 6:39:15 PM | WARNING | Loading weights from /mydrive/backup/yolov4_custom2_final.weights...
Jun 11, 2020, 6:39:15 PM | WARNING | Allocate additional workspace_size = 52.43 MB
Jun 11, 2020, 6:39:15 PM | WARNING | avg_outputs = 489778
Jun 11, 2020, 6:39:15 PM | WARNING | Total BFLOPS 59.563
Jun 11, 2020, 6:39:15 PM | WARNING | [yolo] params: iou loss: ciou (4), iou_norm: 0.07, cls_norm: 1.00, scale_x_y: 1.05

- Describe the current behavior:
The modal keeps on crashing. I am using the python library 'pyyolo' to detect objects in a video. But every time after two detections, the kernel crashes and restarts.

- Describe the expected behavior:
The modal is supposed to output detections from a video

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
![Screenshot (38)](https://user-images.githubusercontent.com/47526387/84389956-7d50eb80-ac14-11ea-883b-6a378b4730fa.png)

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment]
I'd try asking the pyyolo folks.

**Comment by ramgarg102** [comment]
Thanks a lot man, that would be a huge help.

**Comment by craigcitro** [comment]
Sorry -- I was suggesting that you should try asking the pyyolo folks.
