### ISSUE TITLE
Google Child account cannot sign into Colab

### ISSUE THREAD

**Issue by optidatascience** [googlecolab/colabtools#1328]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: 
Google kids account managed by Familylink cannot sign into colab

- Describe the expected behavior: 
Wonder if Child can sign in and use Colab?

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by raydanaguru** [comment]
I am also facing the same issue.

![image](https://user-images.githubusercontent.com/68515570/87883300-04d80a00-c9cc-11ea-8cce-f6a83e5b6f0d.png)

Here are the steps i am doing:
1.  Login to gmail using my child account
2.  open  https://colab.research.google.com/notebooks/intro.ipynb in new tab
3.  create "new notebook" from file menu
4. "google singin required" popup.

**Comment by Divyosmi** [comment]
I am also facing the same issue
