### ISSUE TITLE
error from open python 2/3 notebook

### ISSUE THREAD

**Issue by majedghambari** [googlecolab/colabtools#133]
hi , when i open new python 2/3 notebook this error is accurate 
Notebook loading error
There was an error loading this notebook. Ensure that the file is accessible and try again.
https://drive.google.com/drive/?action=locate&id=1m28DuzBKXZ1oI695PTcI_8I_hfkCm0Us&authuser=0

**Comment by colaboratory-team** [comment]
If you encounter this issue again, please open a new issue that includes any errors present on the Javascript console. (Often, this error indicates transient unavailability in Drive.)
