### ISSUE TITLE
[UI] Comment boxes disappeared not shown for *some* unresolved comments

### ISSUE THREAD

**Issue by jdemonasterio** [googlecolab/colabtools#1330]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
As the title states, some unresolved comments do not have the comment boxes to the side of the ipynb.  The comments are not solved or deleted, they are still open comments.

New comments' boxes do appear though.

- Describe the expected behavior:
Comments should be shown.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Both Chrome Version 83.0.4103.97 (Official Build) (64-bit) and Brave Version 1.9.80 Chromium: 81.0.4044.138 (Official Build) (64-bit)

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

Given that this is a UI issue, replicating the bug doesn't seem an easy task.
Here is a .gif showing the issue in a private colab notebook.
![google colab - missing unresolved comments](https://user-images.githubusercontent.com/12395592/84517337-8938be00-aca5-11ea-8963-4393d0f54377.gif)

Here is a public (very similar) notebook on which i've added new comments to try and see if they fail to render.
https://colab.research.google.com/drive/1IeiZ0wAXTk9pyl1F4-R5puGCw7A7ve8S

**Comment by etheleon** [comment]
Yes experiencing this issue

**Comment by peguerosdc** [comment]
I am experiencing the same issue

**Comment by cperry-goog** [comment]
Thanks for flagging. Filed b/235513780 internally.
