### ISSUE TITLE
Record audio in Firefox need <iframe> permission attribute

### ISSUE THREAD

**Issue by korakot** [googlecolab/colabtools#1331]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:

Code that can record audio works in Chrome, but not Firefox. 

The cause is different html codes for Chrome and Firefox. Chrome has iframe html with "allow" and "sandbox" attributes. Firefox iframe html is bare.

- Describe the expected behavior:

Recording audio works in Firefox as well. (by adding sandbox and allow attributes in Firefox iframe)

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Firefox

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/drive/1VPV-KiPpJZ0mNf6A3rScP7lUXsHF-U5o?usp=sharing

**Comment by korakot** [comment]
This is similar to issues #240 . 

But this time, there's no allow or sandbox in Firefox HTML at all. It's just

```html
<iframe name="output-iframe" style="height: 34px;" 
 src="https://vxfdm1q3b6-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20200610-085601-RC00_315688042" 
 class=""></iframe>
```

Compare it with Chrome's iframe.

```html
<iframe allow="autoplay; camera; microphone; xr-spatial-tracking" 
 sandbox="allow-downloads allow-forms allow-pointer-lock allow-popups 
          allow-same-origin allow-scripts allow-popups-to-escape-sandbox" 
 src="https://4bocfm58pcn-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20200610-085601-RC00_315688042"
 class="" style="height: 35px;"
></iframe>
```

**Comment by eyaler** [comment]
i am seeing the same error when trying to take a photo with the official snippet:
https://colab.research.google.com/notebooks/snippets/advanced_outputs.ipynb

the error happens on firefox 77, although the camera is permitted. it did work in the past. works fine on chrome. is there a work around?

**Comment by blois** [comment]
The fix for this should now be available.
