### ISSUE TITLE
cursor is missing and not showing inright place

### ISSUE THREAD

**Issue by AbhishekKaushikCV** [googlecolab/colabtools#1332]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by blois** [comment]
A couple questions:
 - What browser & OS?
 - What browser zoom level?
 - Are you using an external monitor?
 - Does it reproduce in an incognito window?

**Comment by AbhishekKaushikCV** [comment]
The browser is Google chrome and the operating system is Ubuntu linux.
No external monitor in use.
I didn't check in incognito mode.

**Comment by AbhishekKaushikCV** [comment]
I am sharing the link to my colab notebook which you can try.
https://colab.research.google.com/drive/1JdSUiElGXsMinFpq0EegCraaE-SnqMX5#scrollTo=xdJ1lfuph0h3

I am not still unable to move to my desired location on colab notebook and it is very frustrating. It is showing somewhere and writing at some other location.
