### ISSUE TITLE
[Feature Request] Tracking GPU memory usage

### ISSUE THREAD

**Issue by wishforgood** [googlecolab/colabtools#1334]
Because colab is built based on IPython, it seems like users are not able to run multiple cells at the same time. Thus, I can't run `nvidia-smi` when running my machine learning program. However, the right top icon simply shows the usage of disk and RAM.
![ram](https://user-images.githubusercontent.com/9963412/84566881-4a8b2c80-ada7-11ea-9ec2-ecee48720ea0.png)
So I think it would be better to show GPU memory usage at that place for GPU instances.

**Comment by blois** [comment]
Here's a quick workaround which serves up the results of `nvidia-smi` in an iframe which is refreshed every 30s-
https://colab.research.google.com/gist/blois/cee2f422779782ffe187254c6028c13d/nvidia-smi-server.ipynb

**Comment by wishforgood** [comment]
> Here's a quick workaround which serves up the results of `nvidia-smi` in an iframe which is refreshed every 30s-
> https://colab.research.google.com/gist/blois/cee2f422779782ffe187254c6028c13d/nvidia-smi-server.ipynb

It works. Thanks for your advice. It seems like I can also use a similar method to run other programs, right?

**Comment by blois** [comment]
Yes, this is based on the same underlying technique that Tensorboard uses.
