### ISSUE TITLE
cursor location is not accurate

### ISSUE THREAD

**Issue by AbhishekKaushikCV** [googlecolab/colabtools#1336]
Bug report for Colab:

- Describe the current behavior: the cursor behavior in a notebook is not correct showing at a different place and editing at a different location.

- The web browser you are using (Chrome, Firefox, Safari, etc.): google chrome

I am sharing the link to my colab notebook which you can try.

https://colab.research.google.com/drive/1JdSUiElGXsMinFpq0EegCraaE-SnqMX5#scrollTo=xdJ1lfuph0h3

I am  unable to move to my desired location on colab notebook and it is very frustrating. It is showing somewhere and writing at some other location.

**Comment by AbhishekKaushikCV** [comment]
Bug report for Colab:

Describe the current behavior: the cursor behavior in a notebook is not correct showing at a different place and editing at a different location.

The web browser you are using (Chrome, Firefox, Safari, etc.): google chrome

I am sharing the link to my colab notebook which you can try.

https://colab.research.google.com/drive/1vZxTbq1D_EBNKGXfbz1PKMwVE1Ilb9Kw

I am unable to move to my desired location on colab notebook and it is very frustrating. It is showing somewhere and writing at some other location.

**Comment by Rigved19** [comment]
Check your zoom level, reset it to 100

**Comment by engozdil** [comment]
Same problem. how can i solve this problem?

**Comment by Ishaan-10** [comment]
Facing the same issue as of Feb 2023

**Comment by NiLLabbasi** [comment]
same :|

**Comment by MathewLipman** [comment]
They never fixed this its a joke how slow their UI is too. Why the hell would i pay for your paid product when your free product is such shit.

**Comment by ArrafMelon** [comment]
Has a solution been found yet? Experiencing the same problem.

**Comment by kxwhiowo** [comment]
Still waiting for a solution :(
