### ISSUE TITLE
cannot paste anything into the notebook...using windows system. it could work at the begeinning. do not know what happened

### ISSUE THREAD

**Issue by YangZhao1996** [googlecolab/colabtools#1342]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by Bonecrusher707** [comment]
Same here! I’m on ipad, I cannot cut or paste anything within a cell. Makes it completely unusable!
