### ISSUE TITLE
Google Colab Pro disconnecting after 1-2 hrs

### ISSUE THREAD

**Issue by anavmehta** [googlecolab/colabtools#1344]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Google Colab Pro disconnects after 1-2 hrs

- Describe the expected behavior:
Google Colab Pro should atleast run for 24hrs
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome, on Mac

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by PaulB86UK** [comment]
I have the same problem :S

Describe the current behavior:
Google Colab Pro disconnects after 1-2 hrs

Describe the expected behavior:
Google Colab Pro should atleast run for 24hrs

The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome, on Mac

I

**Comment by vladbarrow** [comment]
I am experiencing the exact same issue. I start code execution, the model runs for about 1-2 hours and then I get the following error: "OSError: [Errno 5] Input/output error". Can someone please help?
