### ISSUE TITLE
I have no access to GPU

### ISSUE THREAD

**Issue by HildaSamame** [googlecolab/colabtools#1346]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: **no backend with gpu available**
- Describe the expected behavior: **able to connect with hosted runtime**

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/drive/1rkCBZ5yRKLmLVUp_Ew34Q2S5IxGlSzWB?usp=sharing

In the part of training a StyleGan, how would you recommend to training? each N hours and then stopped?
It's for academic use.

**Comment by BritneyMuller** [comment]
+1 

I'm experiencing this same problem.

**Comment by manyone** [comment]
i'm trying to run face depixelizer but with no success - i connect to hosted runtime and if i set the runtime to GPU, i get "google guota exceeded" when i set the runtime to none, i get "no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:47
![image](https://user-images.githubusercontent.com/7508243/85537208-9e2c2000-b5c8-11ea-9307-219abecbbfbd.png)
