### ISSUE TITLE
https://colab.research.google.com/notebook#create=true&language=swift 

### ISSUE THREAD

**Issue by conwyn-flavell** [googlecolab/colabtools#1351]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: This is using Swift version 5.3-dev which causes 
%install ‘.package(url: “https://github.com/IBM-Swift/Swift-JWT.git”, from: “3.0.0”)’ SwiftJWT to fail in CryptoECC  with
SIL verification failed: return with stack allocs that haven't been deallocated: state.Stack.empty()

- Describe the expected behavior: I would expect it to use Swift 5.2 until 5.3 becomes stable.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by blois** [comment]
This is better reported at https://github.com/tensorflow/swift/issues.
