### ISSUE TITLE
[Feature Request] Allow Viewing of plaintext files with no file extension

### ISSUE THREAD

**Issue by Kreijstal** [googlecolab/colabtools#1352]
I was playing with google colab, and I checked that you could open python files because I hovered over a toolbox, where it says "view source" there was a href link with a URLEncoded that reads something like this 
`<a href="#" data-href="command:viewSource?%5B%22%2Fusr%2Flocal%2Flib%2Fpython3.6%2Fdist-packages%2Ftensorflow%2Fpython%2Feager%2Fwrap_function.py%22%2C%7B%22startLineNumber%22%3A232%2C%22startColumn%22%3A1%2C%22endLineNumber%22%3A232%2C%22endColumn%22%3A1%7D%5D" title="command:viewSource?%5B%22%2Fusr%2Flocal%2Flib%2Fpython3.6%2Fdist-packages%2Ftensorflow%2Fpython%2Feager%2Fwrap_function.py%22%2C%7B%22startLineNumber%22%3A232%2C%22startColumn%22%3A1%2C%22endLineNumber%22%3A232%2C%22endColumn%22%3A1%7D%5D">View source</a>`

Couldn't you use the same technique to preview plain textfiles?

**Comment by blois** [comment]
Plaintext files can be viewed from the file browser, see button on the left side of the window.

Or do you have an example of some code that you would expect the hover action would apply to?

**Comment by Kreijstal** [comment]
Oh, yeah, I think it was that I wanted to edit a file that didn't have an extension from colab's editor, and the only thing I could do was download it 
For example something like:

![image](https://user-images.githubusercontent.com/2415206/85321217-a00cbb00-b4c4-11ea-85d2-6dcb642bbb8e.png)

A solution would be to rename it temporarily into a .txt and then rename it back, but I find that a bit inconvenient
