### ISSUE TITLE
colab is now using keras 2.3.1 which is silently broken

### ISSUE THREAD

**Issue by eyaler** [googlecolab/colabtools#1357]
colab has recently updated keras from 2.2.5 to 2.3.1. however 2.3.1 has a silently broken evaluate_generator (which is also used in the fit_generator). see here:
https://github.com/keras-team/keras/issues/13469

**Comment by metrizable** [comment]
Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem including Keras 2.12.0 since then, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
