### ISSUE TITLE
OOM Runtime

### ISSUE THREAD

**Issue by donmahallem** [googlecolab/colabtools#136]
I am currently facing a problem "reguarly" with Python 3 GPU Runtime.

I do have setup a keras( with tensorflow) experiment and it does run fine most of the time. But once in a while it suddenly Tensorflow will throw OOM Errors for the specified tensor sizes without changing anything. From my experiments it seems to be account/runtime bound. 

Restart runtime doesn't help. Waiting until the runtime gets "fully recycled" or switching Google accounts in the mean time is required for the code to execute again.

It does look to me that the gpu memory doesn't get cleared fully and I can't find a solution to this problem on my own right now

**Comment by youssefElPrns** [comment]
try using 
! kill -9 -1
to kill current VM which will allocate you a new clean VM after a reconnect

**Comment by colaboratory-team** [comment]
You can reset a VM using the menu item 'Reset all runtimes...' from the Runtime menu.
![image](https://user-images.githubusercontent.com/38081706/54174445-c0d20e00-4443-11e9-9d70-86c5306a2277.png)
