### ISSUE TITLE
Feature request: hidden cell

### ISSUE THREAD

**Issue by idhamari** [googlecolab/colabtools#1360]
I am working with a group on a private GitLab project. The notebook should clone the project repository. Everone share the notebook must use his own credentials e.g. password or access token to do the cloning. THis makes everyone sharing the notebook can see other passwords or access token which is not desirable. It would be nice if there is a sharing option that hides a cell so one can execute this cell only privately while others can not see the hidden cell.

**Comment by blois** [comment]
Can you use getpass?

```python
import getpass
getpass.getpass('Password? ')
```
