### ISSUE TITLE
windows.performance.mark is not a function on older browsers

### ISSUE THREAD

**Issue by gamecraftCZ** [googlecolab/colabtools#1362]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
window.perfomance.mark is not a function on IOS 10 or older
![IMG_4918](https://user-images.githubusercontent.com/11137519/85781474-02b0c180-b726-11ea-9f69-614d5fd1034d.PNG)

- Describe the expected behavior:
It should be present using polyfill if not supported by browser
This polyfill worked for me when I injected it using remote web inspector: https://gist.github.com/RubaXa/8662836

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Safari on IOS 10.3.3

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
Just create any notebook you like.

**Comment by blois** [comment]
iOS 11 was released in 2017, iOS 10 has not received security updates since then.

**Comment by katlyn-edwards** [comment]
https://research.google.com/colaboratory/faq.html#browsers

The FAQ page mentions that Colab doesn't support older browser variants.

**Comment by gamecraftCZ** [comment]
I think it is just a minimal change to include polyfill. My old iPad is still working just fine so why not to use it.
