### ISSUE TITLE
haiku import throws AttributeError

### ISSUE THREAD

**Issue by lgoetz** [googlecolab/colabtools#1364]
Bug report for Colab: http://colab.research.google.com/.

Current behavior: after installing haiku (pip install git+https://github.com/deepmind/dm-haiku) trying to import haiku (import haiku as hk) throws following error:
AttributeError: module 'jax.core' has no attribute 'CallPrimitive'

Expected behavior: errorless haiku import

I'm using Firefox. Here's a link to a minimal notebook that reproduces this issue: https://gist.github.com/lgoetz/54fff3ab729c4e18039841dd65258813

**Comment by craigcitro** [comment]
Thanks for the report!

Workaround: `!pip install --upgrade jax jaxlib` first and you can import haiku.

It looks like haiku requires a newer version of jax, but it's not included by default in the deps (instead being in an extras section). I'd ask on the haiku repo; the commit was also 6 hours ago, so it could be that they're still working on it. ;)

**Comment by lgoetz** [comment]
Great, thanks, that works for now ;)
