### ISSUE TITLE
Cell numbers disappear after execution and scrolling

### ISSUE THREAD

**Issue by fonnesbeck** [googlecolab/colabtools#1367]
As shown in the screen shot below, the numbers associated with cells executed in Colab quickly disappear soon after exectution:

![Screenshot 2020-06-27 at 12 23 07 PM](https://user-images.githubusercontent.com/81476/85928654-431e5580-b874-11ea-8136-e6c474b206ea.png)

This happens regularly after scrolling through the notebook. They persist as long as cells remain visible on the screen, but after scrolling up or down then returning, the numbers disappear despite the cell output still being visible and runtime still being active and in the proper state. This makes it incredibly confusing to use Colab for development.

I'm running Colab Pro on Chrome 84 with ad blockers disabled.

**Comment by blois** [comment]
Cell numbers will disappear if the connection is lost then re-established, I'm wondering if that is what you're seeing here?

**Comment by fonnesbeck** [comment]
It would have had to happen really quickly, and without the usual visual cues when a connection is lost. This was all within a few minutes of working with the notebook.

**Comment by blois** [comment]
Is it possible that the file was modified in a separate tab and updated while you were viewing it?

**Comment by blois** [comment]
The cell numbers should now be getting restored when the kernel connection is reset. I believe this can still repro if the notebook is modified though.

**Comment by issa-garcia** [comment]
Hello, I am also unable to see the index of a cell in Google Collab. The numbers that appear next to the cell are the number of cell executions in the notebook.

It would be useful for collaboration and teaching purposes to be able to have a display of cell index, particularly for very long collab notebooks. I tried implementing this with javascript, but console.log() and alert() are not displaying variables' content on the output and browser popup messages of Google Collab notebook, respectively.

I am using Google Collab 2024-06-18 on Firefox 127.0.1 (64-bit)
