### ISSUE TITLE
Inconsistent file extraction

### ISSUE THREAD

**Issue by Grinjero** [googlecolab/colabtools#1369]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
A 14 GB zip file is stored in my Google Drive. When extracting that file in colab to the content folder using the unzip command one of seemingly random things occurs:
1) That file extracts successfuly
2) unzip can't recognise it as an archive
3) unzip claims it is corrupted
4) unzip recognizes it as an archive but claims the file offset are corrupted
5) unzip starts unzipping the file but fails due to an unexpected error

I checked the hash sum of the local file on my computer and the file that is stored in Google Drive and they are the same. That archive unzips properly localy.

- Describe the expected behavior:
Extraction should work in every situation, not fail randomly.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by Michael-J98** [comment]
I have the same problem too.
I asked the Google One Support for help.
But they don't think it's the problem with gdrive and advice me turning to colab instead.
