### ISSUE TITLE
Error in example feature_crosses.ipynb

### ISSUE THREAD

**Issue by AMGValue** [googlecolab/colabtools#137]
The text about one-hot says:

> For each possible categorical value, we make a new **binary** feature of **real values** that can take one of just two possible values: 1.0 if the example has that value, and 0.0 if not. In the example above, the categorical feature would be converted into three features, and the training points now look like:
> 
> # | feature_value_0 | feature_value_1 | feature_value_2

> 0 | 0.0 | 0.0 | 1.0
> 1 | 1.0 | 0.0 | 0.0
> 2 | 0.0 | 1.0 | 0.0
> 
There are some errors in the example

**Comment by sandersk** [comment]
Hi @AMGValue,

Could you please provide more details on the errors you've encountered?

Thanks,
Sanders

**Comment by AMGValue** [comment]
The 1 should be in other places (diagonal), corresponding to each value (0, 1, 2).

Doesn't it?

**Comment by sandersk** [comment]
Hi @AMGValue,

The values shown in this table:

| #  | feature_value_0 | feature_value_1 | feature_value_2 |
| -- | --------------- | --------------- | --------------- |
| 0| 0.0 | 0.0 | 1.0 |
| 1 | 1.0 | 0.0 | 0.0 |
| 2 | 0.0 | 1.0 | 0.0 |

Illustrate a one-hot encoding of the feature data in this table (also shown in the Colab):

| #  | feature_value |
| -- | ------------- |
| 0| 2 |
| 1 | 0 |
| 2 | 1 |

So, directly above, the first row says that example 0 has a value of 2, which is encoded as:

| #  | feature_value_0 | feature_value_1 | feature_value_2 |
| -- | --------------- | --------------- | --------------- |
| 0| 0.0 | 0.0 | 1.0 |

And so on for the next two rows.

Does that clarify? Let me know if you have further questions.

Sanders
