### ISSUE TITLE
%matplotlib notebook not working 

### ISSUE THREAD

**Issue by iheathers** [googlecolab/colabtools#1372]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by Joe-Sin7h** [comment]
yes it's not working
