### ISSUE TITLE
Disk half full after resetting 

### ISSUE THREAD

**Issue by ghsama** [googlecolab/colabtools#1377]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
Colab didn't clear the disk after runtime reset : Using GPU , i reset the instance but it keep allocating 38GB of the available 76GB
- Describe the expected behavior:
Normal, it should clear all the cached files after reset, and have all the 76GB available
PS : I'm using the GPU instance
- The web browser you are using (Chrome, Firefox, Safari, etc.):
![image](https://user-images.githubusercontent.com/20842504/86222370-6e5fb800-bb86-11ea-872b-6138951bb637.png)

- running !df -h :
Filesystem      Size  Used Avail Use% Mounted on
overlay          69G   32G   34G  49% /
tmpfs            64M     0   64M   0% /dev
tmpfs           6.4G     0  6.4G   0% /sys/fs/cgroup
shm             5.8G     0  5.8G   0% /dev/shm
/dev/sda1        75G   33G   42G  44% /opt/bin
tmpfs           6.4G   16K  6.4G   1% /var/colab
tmpfs           6.4G     0  6.4G   0% /proc/acpi
tmpfs           6.4G     0  6.4G   0% /proc/scsi
tmpfs           6.4G     0  6.4G   0% /sys/firmware

**Comment by craigcitro** [comment]
This is working as intended -- the space is being used by the OS, python, libraries, etc. 😀
