### ISSUE TITLE
Error when running code in Colab

### ISSUE THREAD

**Issue by christianchadwick** [googlecolab/colabtools#1379]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: When i try to run any code, i get the error message 
_Error
Could not load the JavaScript files needed to display output.
This is probably because your Google Account login access has expired or because third-party cookies are not allowed by your browser.

Please reload this page._

However, I have cookies enabled and have tried clearing them, refreshing the browser, etc. Not sure what else to do.

- Describe the expected behavior: It should run my code, but it won't even run a basic print command right now.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment]
We've recently started seeing this when a chrome render process is stuck at 100%; if you open the Chrome task manager, do you see a process eating 100% CPU? Does killing it and re-executing fix the problem?

**Comment by christianchadwick** [comment]
> We've recently started seeing this when a chrome render process is stuck at 100%; if you open the Chrome task manager, do you see a process eating 100% CPU? Does killing it and re-executing fix the problem?

I tried re-executing and that didn't work. I'm not sure what happened, but it's working now. I just left the tab up while I went out and it seems to have fixed itself!

**Comment by christianchadwick** [comment]
Thanks for the help though!

**Comment by craigcitro** [comment]
Closing, but feel free to reopen if you come up with a repro.
