### ISSUE TITLE
not download ipynb file instread of that download text file

### ISSUE THREAD

**Issue by kunal9665** [googlecolab/colabtools#1381]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment]
It's not clear to me what bug you're reporting?

If you'd like to download your notebook as something other than an .ipynb file, `File` -> `Download .py`.
If you'd like to download a file stored on your runtime, use the file browser on the left-hand side.

**Comment by kunal9665** [comment]
But whenever you click on .py file instead of.py colab download text
document file. please check

**Comment by craigcitro** [comment]
I believe you're saying that downloading a .py file from the file browser, you end up with a different extension locally?

This isn't anything Colab is doing, but your browser or OS may be adding the .txt extension, which you can remove once it's downloaded.
