### ISSUE TITLE
Consider line wrapping errors message by default for consistency with Jupyter

### ISSUE THREAD

**Issue by shoyer** [googlecolab/colabtools#1384]
- Describe the current behavior:

Unlike Jupyter, Colab doesn't line wrap output, either from `print` or raising exceptions in Python.

Most of the time, this is fine. But it presents a poor UX experience for long error messages from third party packages, which in my experience rarely explicitly add line breaks -- likely because they were designed to work well with Jupyter.

This has come up for JAX, as we try to figure out how whether we should wrap explicitly long error messages or not.

Example:

![image](https://user-images.githubusercontent.com/1217238/86518154-e840ad00-bde3-11ea-9755-db8ed0616b4f.png)

- Describe the expected behavior:

From Jupyter:
![image](https://user-images.githubusercontent.com/1217238/86518156-ed9df780-bde3-11ea-9c79-11692b53a811.png)

**Comment by blois** [comment]
This will be fixed in the next few days.

**Comment by shoyer** [comment]
Awesome, thanks @blois !

**Comment by blois** [comment]
Fix should be live.
