### ISSUE TITLE
Input/output error when reading file from Google Drive

### ISSUE THREAD

**Issue by JianyueZ** [googlecolab/colabtools#1386]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: I am reading files stored on my Google Drive. However, it prompts input/output error 'rasterio.errors.RasterioIOError: '/content/drive/My Drive/*.TIF' not recognized as a supported file format.' The tif file I am reading is about 700MB. In the meantime, if the tif file on Google Drive is small (2MB for example), it will be success. Besides, if I copy files from Google Drive to Colab /content, big files encounter I/O error while small files succeed.

- Describe the expected behavior: I expect Colab work with files on Google Drive of any size, at least 1000MB for my instance.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Edge(chromium).

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/drive/1lMJsSPCpbJ48wwjTO-YgKfOBDPOQMA0B?usp=sharing

**Comment by chhokarpardeep** [comment]
@colaboratory-team 

Please provide any solution for this error.



thanks

**Comment by muxgt** [comment]
I have the same problem and it appears only on CPU runtime. On GPU it works fine.

**Comment by nyroro** [comment]
Same problem on gpu. Please fix it
