### ISSUE TITLE
File upload tool doesn't work twice with the same file.

### ISSUE THREAD

**Issue by neonbjb** [googlecolab/colabtools#1392]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
When you upload a file with the same name twice, it doesn't work the second time. You have to reload the webpage to allow it to work again.

- Describe the expected behavior:
You should be able to repeatedly upload the same file over and over. This worked until recently.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome. Reproducible on Windows and Linux.

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
Reproducible in any notebook:
1) Upload any file.
2) Wait till upload finishes.
3) Upload the file again
4) Notice that you don't see the upload marker (and if you made any changes to the file, they are not reflected)

**Comment by blois** [comment]
Fix will be incoming shortly. For what it's worth uploading a different file between uploads can be used as a workaround as well.

**Comment by blois** [comment]
The fix should now be live, thanks for reporting.
