### ISSUE TITLE
Colab window keeps scrolling back to the top.

### ISSUE THREAD

**Issue by Ritesh313** [googlecolab/colabtools#1394]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: I am experiencing a new issue, I am working in one of the tabs and withing 2-3 seconds it automatically scrolls back to the top.

- Describe the expected behavior: It should stay where I am typing, I guess.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Firefox

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://photos.app.goo.gl/hYdfn9unEPcH4bVn7

**Comment by Ritesh313** [comment]
https://photos.app.goo.gl/hYdfn9unEPcH4bVn7
This is the link the the video in which I have reproduced the issue.

**Comment by blois** [comment]
Can you try private browsing mode? I'm curious if this is caused by an extension possibly? I cannot reproduce and have not heard of other people hitting this yet (it looks pretty unusable from your video)

**Comment by Ritesh313** [comment]
It didn't happen in a private window. The, I tried in my actual notebook (the one in the video), it didn't happen there too. The only difference is that there is another node running at this time.

**Comment by Ritesh313** [comment]
I figured out what was happening, in case someone else experiences it. It can be either because there is a cell running with continuous outputs and you have the scroll with the output toggle on (you can turn it off in settings) or it can be because the notebook is open in another window or another system for that matter and your notebook keeps scrolling to another cell.
