### ISSUE TITLE
prompt to opt for higher RAM environment no longer appears!!!!

### ISSUE THREAD

**Issue by naveen-marthala** [googlecolab/colabtools#1397]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
I have filled up the available 12.7GB RAM when I was trying to make a numpy array of shape (95476, 128, 64, 1) and the session crashed mid way. This happened with TPU and GPU and plain run-times.

- Describe the expected behavior:
That the colab to show the prompt to connect to higher RAM runtime as it previously used to. But, nothing shows up. (I am in India.)

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Google Chrome of "Version 83.0.4103.116 (Official Build) (64-bit)" on a Windows 10 64-bit laptop.

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
link to cell: https://colab.research.google.com/drive/1WcyiSfYgEoanATlGZ7DcR7aLYQZVZ8gN#scrollTo=fZoClKISHR8J&line=2&uniqifier=1
link to the notebook:
https://drive.google.com/file/d/1WcyiSfYgEoanATlGZ7DcR7aLYQZVZ8gN/view?usp=sharing

**Comment by kdmsit** [comment]
Yup same happening with me
