### ISSUE TITLE
Variable sharing between kernels (support for SoS in Colab notebooks)

### ISSUE THREAD

**Issue by rchurt** [googlecolab/colabtools#1399]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
As far as I know, there's no way to share variables between kernels in the same notebook. So if I wanted to create a Pandas DataFrame, then run some functions from an R package on the data in it, then plot it with Bokeh, I would have to write the DataFrame to a csv, import it with R, write it to a csv again, and import it with Pandas so I can plot it with Bokeh.

- Describe the expected behavior:
There is a workflow engine called SoS (https://vatlab.github.io/sos-docs/) that has been implemented in a Jupyter-style notebook (https://github.com/vatlab/sos-notebook) that allows users to pass variables between kernels using a `%get` magic function.

**Comment by craigcitro** [comment]
Correct, there is no way to share data between kernels beyond what you describe (write to disk and shell out to another binary), and there's no current or future work in that direction.

**Comment by rchurt** [comment]
For anyone finding this later, I did find a workaround for this specific case:
```
# Pandas dataframe to R data frame
!pip3 install rpy2
%load_ext rpy2.ipython
%R -i df
```
```
# R data frame to Pandas dataframe
%R seq.data <- read.delim('sequence.index', header=TRUE, stringsAsFactors=FALSE)
seq_data = %R seq.data
```
