### ISSUE TITLE
Support for CLI colors?

### ISSUE THREAD

**Issue by megamindbrian** [googlecolab/colabtools#14]
This might belong to upstream jupyter, please let me know if I should re-file.  I thought it might be cool if colab supported the CLI coloring.  Looks like it just prints the color characters directly to the console, ie when running npm:

```
?25h
> zeromq@4.6.0 install /content/node_modules/zeromq
>
```

I think the ```?25h``` is a color command.

**Comment by blois** [comment]
The specific JSON in the notebook is:

```json
"\u001b[K\u001b[?25h/tools/node/bin/ijs"
```

Which translates to CSI-K (clear line), followed by CSI-?25h, which is a VT320 command indicating that the cursor should be displayed. Colab is already ignoring the unsupported CSI-K command, we should probably ignore the private commands as well.

In general coloring is supported, but the outputs do not support more of the cursor manipulation commands.

**Comment by blois** [comment]
CSI-?25h and other private commands will be skipped in the next release of Colab (later this week).

**Comment by megamindbrian** [comment]
@blois  Excellent!
