### ISSUE TITLE
No backend available and registration required

### ISSUE THREAD

**Issue by thegreennapalm** [googlecolab/colabtools#140]
![image](https://user-images.githubusercontent.com/37814113/39164210-13c4064a-4733-11e8-9518-0ed4d7a3c782.png)

![image](https://user-images.githubusercontent.com/37814113/39164213-1e85e31e-4733-11e8-86ef-5bac0d297f82.png)

Why does this happen?

**Comment by blois** [comment]
There have been some changes, can try again.
