### ISSUE TITLE
Cannot Copy ANY Skillshare course with colab at the moment - don't know why.

### ISSUE THREAD

**Issue by besscella** [googlecolab/colabtools#1400]
Hi

I'm having a problem with copying ANY Skillshare course using Colab at the moment.  Something's wrong but I don't know what or how to fix it.

Here's my problem:
When I start the process I attempt to connect to hosted runtime - sometimes I get a message saying cannot connect to runtime. then it will connect (I think).
Then I click on runtime to change runtime type - when the Notebook window opens, I can only see Hardware accelerator where I have the option to change it from none to GPU or TPU, but the window does not show Runtime Type: Python3.  I don't know if this is causing the problem or just part of the problem.
Then the next 2 steps appear to work fine.
When I get to step 3 where I'm asked to input the skillshare website info and press run, I do that but then I get the following error message:

Traceback (most recent call last):
  File "/root/.skillshare-1hack/dl.py", line 50, in <module>
    main()
  File "/root/.skillshare-1hack/dl.py", line 11, in main
    dl.download_course_by_url(course_url)
  File "/root/.skillshare-1hack/skillshare.py", line 28, in download_course_by_url
    assert m, 'Failed to parse class ID from URL'
AssertionError: Failed to parse class ID from URL

I don't know what any of this means or if I caused it or if colab is malfunctioning - I have no idea what's going on.

Where the above error appears, what normally happens is that the course should begin to download but instead i get the error message and everything comes to a stop.

You ask for a link:
https://colab.research.google.com/github/beast1hack/skillshare-1hack/blob/master/Skillshare_DL_%5B1hack%5D.ipynb?pli=1#scrollTo=IPSBl3OUzsw7

Any help you can offer would be much appreciated.  
Thanks.

Kind Regards,
Sharon

Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment]
I'd recommend filing an issue in the repo where you found the notebook.
