### ISSUE TITLE
Not able to get tensorboard to load properly in colab (using chrome) using official Tensorflow example 

### ISSUE THREAD

**Issue by Santosh-Gupta** [googlecolab/colabtools#1401]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

I am running the official tensorboard colab notebook example from here

https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks

[direct link https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_in_notebooks.ipynb ]

But it doesn't seem to be loading properly. 

This is what it looked like 

https://snipboard.io/KIfMVO.jpg

I thought it would due to some sort of extension, so I opened it incognito mode which disables all of my extensions, but the tensorboard doesn't even register

https://snipboard.io/UdTFlr.jpg

I tried again using a different account in incognito and still got the 403 error. 

I also tried saving my own copy into my drive, and running it, and also got the save error. 

- Describe the expected behavior:

Tensorboard should load properly 

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome, up to date 

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

Both the official link and my copy had the issues. 

Official link 

https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_in_notebooks.ipynb

My copy

https://colab.research.google.com/drive/1X9Dt_OBMs_5cqXmCbWKYmt0OcaXns62W?usp=sharing

**Comment by blois** [comment]
Do you know if you happen to have third-party cookies disabled? That could possibly cause it.

**Comment by Santosh-Gupta** [comment]
third-party cookies were blocked in incognito mode, when I enabled them, the Tensorboard is working, so must be some extension that's interfering with it
