### ISSUE TITLE
Objects not freed after failure of block execution

### ISSUE THREAD

**Issue by lhubbard01** [googlecolab/colabtools#1402]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
  Ram is being used from a failed runtime, i.e. either no memory being freed, or the python runtime equivalent
- Describe the expected behavior:
   Expect memory being used in ram to clear out of the associated execution fails.
- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by metrizable** [comment]
Since this issue was filed a while ago, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
