### ISSUE TITLE
 Cannot connect to GPU backend.

### ISSUE THREAD

**Issue by haonguyen1107** [googlecolab/colabtools#1404]
Hi sir. I am a student in computer science. I am using Google colab free, but I met an error: Cannot connect to GPU backend.
Looking forward to your help.Thank you!

**Comment by hxtruong** [comment]
Did you change type runtime:  click Runtime -> Change runtime type -> choose "GPU" in Hardware accelerator -> Save
Then test again.

**Comment by metrizable** [comment]
Since this issue was filed a while ago, if you are still experiencing the issue, please file a new issue with steps to reproduce/screencast or file in-product feedback.
