### ISSUE TITLE
package tmap not installing in colab R notebook due to old R version

### ISSUE THREAD

**Issue by mputs** [googlecolab/colabtools#1408]
I tried to install the TMAP package in R. It does not work. The first problem i faced was that i could not install the XML package, which requires at least R 4.0 (see also https://github.com/mtennekes/tmap/issues/472).  

Could you upgrade R, so we can continue installing the TMAP package?

notebook which shows the problem: https://colab.research.google.com/drive/1N_DZROB00k3NfuC3v2t8B5616u2ABemc?usp=sharing

**Comment by craigcitro** [comment]
R is now updated.
