### ISSUE TITLE
How can I change directory?

### ISSUE THREAD

**Issue by miky12993** [googlecolab/colabtools#1409]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: cannot change directory

- Describe the expected behavior: change directory

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
I want to change my directory to gdrive/My drive.
However below coding does not work at all.
Could you tell me what should I do?

<img width="565" alt="Screen Shot 2020-07-14 at 10 34 13 PM" src="https://user-images.githubusercontent.com/68284557/87431849-2a5ac180-c622-11ea-8e0d-7bd03f773fa0.png">

**Comment by katlyn-edwards** [comment]
https://stackoverflow.com/questions/48298146/changing-directory-in-google-colab-breaking-out-of-the-python-interpreter

Specifically, see Bob Smith's answer.
