### ISSUE TITLE
Error in code sparsity_and_l1_regularization.ipynb

### ISSUE THREAD

**Issue by xgcastano** [googlecolab/colabtools#141]
Hi 

In the exercise code sparsity_and_l1_regularization.ipynb, in the first cell, the line california_housing_dataframe = pd.read_csv("https://storage.googleapis.com/mledu-datasets/.googleapis.com/ml_universities/california_housing_train.csv", sep=",") is bad the url data.

The correct url is california_housing_dataframe = pd.read_csv("https://storage.googleapis.com/mledu-datasets/california_housing_train.csv", sep=",")

thanks.

**Comment by craigcitro** [comment]
Thanks for the bug report! I'm fixing this upstream, but just to confirm: did you see this in the spanish version of the exercise? (That's the only place I see the typo, so just wanted to confirm.)

**Comment by xgcastano** [comment]
Hi.

Yes, I see this exercise in spanish.

regards.
