### ISSUE TITLE
Getting "bad zipfile offset (lseek)" for previously successfully unzipped archives

### ISSUE THREAD

**Issue by pevogam** [googlecolab/colabtools#1410]
- Describe the current behavior:
```
Archive:  drive/My Drive/data/test.zip
file #1:  bad zipfile offset (lseek):  0
file #2:  bad zipfile offset (local header sig):  67
file #3:  bad zipfile offset (local header sig):  149
error:  zipfile read error
file #4:  bad zipfile offset (EOF):  3805
```
- Describe the expected behavior:
```
Archive:  drive/My Drive/data/test.zip
...file-list-here...
```
While extracting the two zip archives "test.zip" and "train.zip" used to work the first time I tried it, my runtime crashed and afterwards I keep getting errors during zipfile extraction and warnings that the zip was corrupted. However, the zip is located in the Google drive and extracting it shouldn't modify it in any manner. I have tried resetting and factory-resetting the runtime but to no avail.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Firefox

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1BUojT_vFirth4vjgGv355CcG5p1AA6PW?usp=sharing

**Comment by Michael-J98** [comment]
Hi,
I met the same question too.
Did you solve it?

**Comment by Michael-J98** [comment]
I don't know why but I solved my problem by re-downloading the data after clearing the previous folder.

**Comment by pevogam** [comment]
Somewhat but not quite - this seems to only appear at certain times and not at others. I suspect possible race conditions on the colab cloud side but I cannot be sure. My recommendation in this issue is mostly that if any such problems appear due to quota of resources then it is best if the error is explicit like "You have reached your quota and number of files or storage space" or anything more specific. In this way we know what the problem is and are not mislead with looking for unzipping bugs.

**Comment by Michael-J98** [comment]
That sounds reasonable. For me, it happens only when I interact with gdrive. If I download the dataset directly to the vm, it can be unzipped without any error just costing a lot of time(which is really annoying).

**Comment by pevogam** [comment]
Yes, my trouble with this is also with GDrive and for very similar reasons. So for now we have at least +2 about this issue.
