### ISSUE TITLE
After the purchase of Colab pro, I cannot  neither create a new notebook nor open an existing one

### ISSUE THREAD

**Issue by ataftaf** [googlecolab/colabtools#1412]
I used Chrome
![colabBug1](https://user-images.githubusercontent.com/57816866/87578328-90a01c80-c6d4-11ea-9cce-dcc4c2f1d1b2.png)

**Comment by craigcitro** [comment]
Can I ask you to go to `Help` -> `Send Feedback` and reference this github issue?

**Comment by ataftaf** [comment]
The problem has been solved. Thanks.
