### ISSUE TITLE
bug notebooks Names change to "Untitled" on Firefox

### ISSUE THREAD

**Issue by BraiGold** [googlecolab/colabtools#1414]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

notebooks names change back to  "Untitled". 
to reproduce the error (doesn't happen every time):
1. open a notebook and change the name
2. with the tab still open turn off the computer
3. before shutting down Firefox will ask if you really want to close all windows, say yes.
4. turn it on again, open firefox, will say something about being closed unexpectedly, click on restore tabs.
5. notebook tab comes back but named "Untitled"

- Describe the expected behavior:

Names should stay the same

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Firefox from ubuntu 18.10

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/drive/1vcAF6gRQCNtp1319AiZP-kKZXgS0_it0?usp=sharing

**Comment by blois** [comment]
It sounds like the file was not saved before exiting Firefox- if you do an explicit save (ctrl-s) or wait 30s then the title should be persisted.
