### ISSUE TITLE
GPU disconnects after a small time of inactivity. 

### ISSUE THREAD

**Issue by AmalPrakash** [googlecolab/colabtools#1416]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: I had been trying to train some images on MobileNets and I'm new to colab. And I had given some 30 epochs and upon the 29th epoch it goes off.. 

- Describe the expected behavior: There should be no timeout

- The web browser you are using (Chrome, Firefox, Safari, etc.):Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):https://colab.research.google.com/drive/1LuIdC-KWHp52ooEwCwfT5YUycpM8RpAw?usp=sharing

**Comment by deveshSingh06** [comment]
The provided link denies access. Make sure it is public.

**Comment by AmalPrakash** [comment]
Seems I was just complaining about colab's session timeout.
