### ISSUE TITLE
Corgis running around?

### ISSUE THREAD

**Issue by kathrinkajderowicz** [googlecolab/colabtools#1417]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by katlyn-edwards** [comment]
This is a setting. If you want to enable or disable it, open tools > settings > misc > corgi mode
