### ISSUE TITLE
google colab crashing whenever i reconnect

### ISSUE THREAD

**Issue by mobassir94** [googlecolab/colabtools#1418]
my kernel works fine,model training has no issue at all but whenever i face internet issue even for 1 minute or colab gets disconnected for 1 minute then whenever i try to reconnect after 1 minute i see browse hangs,crashes and i need to quickly stop notebook from running, this problem doesn't occur if i never face colab disconnect issue or lose internet for even 1 minute. is it because of tqdm or something? where it is requesting more memory whenever i reconnect notebook? please check the attached notebook and let me know where my notebook is causing problem

https://colab.research.google.com/drive/169ScdD6AGs5c98CynFtyhpOgAd1NTIud?usp=sharing

thank you

**Comment by aebeljs** [comment]
Running into the same issue repeatedly. Regardless of which browser I tried, it hangs and crashes when this happens. Any solutions yet?

**Comment by mobassir94** [comment]
for me, tqdm was the culprit,i just stopped using tgdm and it solved my issue

**Comment by aebeljs** [comment]
Yeah it turned out to be the same for me too. After removing tqdm, it works fine even after disconnection. Thanks!
