### ISSUE TITLE
Timeout Error for drive.mount('/content/drive')

### ISSUE THREAD

**Issue by bghadge** [googlecolab/colabtools#1419]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
```
from google.colab import drive
drive.mount('/content/drive')
```
Timeout error for `drive.mount('/content/drive')`
I do not have any files my drive only folders and Empty trash. Even after using "Restart runtime", "Restart and run all" and "Factory reset runtime" it doesn't change. 
After running `!cat /var/colab/hostname` I get `gpu-p4-s-2fsig4ovhmzti`
- Describe the expected behavior:
Drive should be mounted.
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome ubuntu 18.04
- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/17EkkgJRYRekS1QzlLdk0vapKRukHbzzz?usp=sharing

**Comment by red-mikan** [comment]
Same here.
Cleaning root directory, restart runtime, try again, these do not work.

!cat /var/colab/hostname
gpu-t4-s-bdvjjeisypch

**Comment by rouninnomi** [comment]
I also cannot mount my Google Drive folders with the error shown below. 

!cat /var/colab/hostname
gpu-t4-s-ngusageosqze




---------------------------------------------------------------------------
TIMEOUT                                   Traceback (most recent call last)
<ipython-input-1-d5df0069828e> in <module>()
      1 from google.colab import drive
----> 2 drive.mount('/content/drive')

4 frames
/usr/local/lib/python3.6/dist-packages/pexpect/expect.py in timeout(self, err)
    142             exc = TIMEOUT(msg)
    143             exc.__cause__ = None    # in Python 3.x we can use "raise exc from None"
--> 144             raise exc
    145 
    146     def errored(self):

TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7fd25f00bc88>
searcher: searcher_re:
    0: re.compile('google.colab.drive MOUNTED')
    1: re.compile('root@a76e32efbfd5-3361c88dbda14c4d94fd84ee0fc3fadf: ')
    2: re.compile('(Go to this URL in a browser: https://.*)$')
    3: re.compile('Drive File Stream encountered a problem and has stopped')
    4: re.compile('drive EXITED')
<pexpect.popen_spawn.PopenSpawn object at 0x7fd25f00bc88>
searcher: searcher_re:
    0: re.compile('google.colab.drive MOUNTED')
    1: re.compile('root@a76e32efbfd5-3361c88dbda14c4d94fd84ee0fc3fadf: ')
    2: re.compile('(Go to this URL in a browser: https://.*)$')
    3: re.compile('Drive File Stream encountered a problem and has stopped')
    4: re.compile('drive EXITED')

**Comment by Niklas5** [comment]
I have the same issue. Any solution yet?

`!cat /var/colab/hostname`
tpu-s-215hpry3j9mwq

**Comment by rouninnomi** [comment]
Success report. 

I used newest version of Microsoft Edge browser, and it worked. 
Timeout error may be caused by a browser problem.

**Comment by Niklas5** [comment]
In my case, the "copy-link-button" did not work properly. So copying the string manually solves this issue.

**Comment by Akila-Ayanthi** [comment]
Hi, 
I'm having the same issue. I tried with different browsers but it still doesn't work. 
Copying the string manually also doesn't work.
Tried on an incognito window as well. But nothing works.
Any solution?

**Comment by cperry-goog** [comment]
https://research.google.com/colaboratory/faq.html#drive-timeout
