### ISSUE TITLE
Sympy LaTeX-formatting is not working. 

### ISSUE THREAD

**Issue by mattbellis** [googlecolab/colabtools#142]
The Sympy pretty-printing function is not working. It looks like it's spitting out the raw LaTeX without rendering it. 

Here's an example. 

https://drive.google.com/file/d/12ammy7wJmUfkD7M0smoYx0ZLvzEYFBC-/view?usp=sharing

Sympy's documentation for this feature is here. 

http://docs.sympy.org/latest/tutorial/printing.html

This would be great for educational purposes!

**Comment by afqueiruga** [comment]
The unicode-based pprint(expression) works for me, but I would also like to see LaTeX rendering work as it does in native Jupyter.

**Comment by blois** [comment]
The issue is that MathJax is not installed for outputs by default, it's not a small module.

Here's an example showing how to manually enable it, we should probably expose a simple wrapper for it.
https://gist.github.com/blois/cea02123a82a4dd40500b31c39dfcb23#file-mathjaxoutputs-ipynb

**Comment by mattbellis** [comment]
Ah, cool. I added that to the Colab example I linked to in my first post. That's a relatively easy workaround...just a question of always making sure you call the setup_typeset() in the same cell.

**Comment by blois** [comment]
With direct Colab link:
https://colab.sandbox.google.com/gist/blois/cea02123a82a4dd40500b31c39dfcb23/mathjaxoutputs.ipynb

**Comment by ebrunach** [comment]
It means that each time we need nice typesetting , we need to call the function. It's weird. Moreover mathjax is loaded to render latex formula in all text cells. Is that possible to make it more simple?

**Comment by blois** [comment]
The `pre_run_cell` hook can be used to automatically configure every cell:

```python
get_ipython().events.register('pre_run_cell', setup_typeset)
```

**Comment by ebrunach** [comment]
Great!! thanks.

**Comment by larssp** [comment]
It may be reasonable to restrict it to the colab environment, if you want to share the .ipynb
for example
```
#@title Activate MathJax for this Notebook on Colab

import os
if "COLAB_GPU" in os.environ:     
    import IPython
    def setup_typeset():
        # see above
    get_ipython().events.register('pre_run_cell', setup_typeset)
```
