### ISSUE TITLE
ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

### ISSUE THREAD

**Issue by raghada** [googlecolab/colabtools#1425]
`ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.`

I'm getting these while trying to read a CSV file ( a really small one). It's important to mention that it was working! I haven't change anything so it stopped out all of a sudden, so it isn't and will never be a pandas problem, it's colab's.

I'm a colab pro user as well.. that's super frustrating.

**Comment by alvaro-martin** [comment]
Same error here, It was working fine, then I go for lunch, come back, and this error appears.

**Comment by majesticio** [comment]
My colab has been hung all day. Same thing, I didn't change any code.

**Comment by zzy99** [comment]
Same error

**Comment by jbrinkhoff** [comment]
Here too:

```
----> 1 with open('/content/gdrive/My Drive/foo.txt', 'w') as f:
      2   f.write('Hello Google Drive!')
      3 with open('gdrive/My Dr/foo.txt', 'r') as f:
      4   print(f.read())

OSError: [Errno 5] Input/output error: '/content/gdrive/My Drive/foo.txt'
```

**Comment by craigcitro** [comment]
See #1428.
