### ISSUE TITLE
Can not move file from drive to colab

### ISSUE THREAD

**Issue by bobyba2000** [googlecolab/colabtools#1427]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by lovethatcat** [comment]
I got that issue.

**Comment by craigcitro** [comment]
See #1428.
