### ISSUE TITLE
Cannot connect colab to drive!!

### ISSUE THREAD

**Issue by kathrinkajderowicz** [googlecolab/colabtools#1431]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by kathrinkajderowicz** [comment]
HUGE inconvenience that has been occurring since 8 PM (5 hours!). Colab isn't connecting with Google drive properly. Cannot load datasets that were working fine before.

**Comment by craigcitro** [comment]
See #1428. (tl;dr: we're actively working on it.)
