### ISSUE TITLE
colab is experiencing issue connecting to drive

### ISSUE THREAD

**Issue by dhaval-zala** [googlecolab/colabtools#1434]
colab is experiencing issue connecting to drive. how can i solve this?

**Comment by Smankusors** [comment]
you can't solve this. Please track on #1428 and wait for Google to fix it.

(in the meantime, don't close this issue so another people don't recreate same issue again and again until this solved)

**Comment by craigcitro** [comment]
Dupe of #1428. (Should now be fixed.)
