### ISSUE TITLE
Run Yolov4 in Colab with Tesla P100(Work!) and K80(Failed!)

### ISSUE THREAD

**Issue by er778899789** [googlecolab/colabtools#1437]
Hi , I have a study in yolov4 to run a computer vision project on Colab.
First time, I check !nvidia-smi and the GPU is Tesla P100. When I finished the first notebook, I want to try another method and I create the second notebook to use. The second notebook's GPU is Tesla K80, and I use the same config to run the code but get the error below.

CUDA Error: no kernel image is available for execution on the device
CUDA Error: no kernel image is available for execution on the device: File exists
darknet: ./src/utils.c:325: error: Assertion `0' failed.

Is Tesla K80 GPU compute capability too weak to handle this project? 
How can I solved this problem?

**Comment by ingrid717-py** [comment]
Hi! I am getting the same error, did you solve the problem (also Yolo4, but with Testa P100)
