### ISSUE TITLE
Cannot connect to GPU backend due to usage limits

### ISSUE THREAD

**Issue by gizemtanriver** [googlecolab/colabtools#1438]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior: Receiving this message "Cannot connect to GPU backend
You cannot currently connect to a GPU due to usage limits in Colab."

- Describe the expected behavior: Reset of usage limits

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome 

In the last two days - not sure if it is somehow related but I think it started after this bugfix https://github.com/googlecolab/colabtools/issues/1432, i have been experiencing issues with connecting to GPU backend. Last night I started training and after about 4 hrs Colab disconnected from GPU. Now when I try to reconnect, I am receiving the message "Cannot connect to GPU backend. You cannot currently connect to a GPU due to usage limits in Colab.". It has been more than 12 hrs but the issue remains.  Unfortunately, I am not living in the US and can't use Colab Pro.

**Comment by shahla-ai** [comment]
I had the same issue apparently we exceeded the free limit this link provides further explanations.

https://research.google.com/colaboratory/faq.html#usage-limits

**Comment by aravind-ramanan** [comment]
@shahla-ai When will this banning be lifted normally after I have exceeded the GPU usage limits in Colab
