### ISSUE TITLE
can't create or save colab notebooks

### ISSUE THREAD

**Issue by yon606** [googlecolab/colabtools#1439]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
I can't save my Colab Notebooks.
Also I can't create new notebooks.

- Describe the expected behavior:
I want to save my Notebooks and create a new one.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome Version 84.0.4147.89

![image](https://user-images.githubusercontent.com/15139934/88402508-7e586980-cdcb-11ea-81e4-96ce33f3700f.png)

**Comment by blois** [comment]
The error mentions that the user quota has been exhausted, see https://github.com/googlecolab/colabtools/issues/1020 for common causes of this. This should resolve itself shortly.
