### ISSUE TITLE
Runtime died. Automatically Restarting

### ISSUE THREAD

**Issue by anoopkumarg2** [googlecolab/colabtools#144]
Can somebody let me know why am getting 'Runtime died.Automatically restarting' error on google colab, everytime i am trying to run a convnet using Tensorflow or Keras.  For exampe a simple convnet like the one below (link below to my code on google drive) also results in this error once it starts training the convnet.

https://drive.google.com/open?id=1ntNsPuKko1uyd5dYaxH92wUg_CUsavEB

I am using Python 3 GPU accelerator,

**Comment by mohanrajmit** [comment]
same error am also getting.

Did u got any solution?

**Comment by Patil-Sahil** [comment]
Same here, Every time I try to fit my deep learning model the notebook gets restarted.
Do you guys get any solution?

**Comment by anoopkumarg2** [comment]
No i didn't get any solution to this. But curiously the issue seems to have got solved somehow. I am no longer facing it with my deep learning models i am running.  I have only updated the code to install Google Drive Fuse wrapper (though that may not be the solution to the problem!)

**Comment by colaboratory-team** [comment]
For users experiencing backend crashes, please open a distinct issue that includes a self-contained notebook that reproduces the issue and we'll take a closer look.
