### ISSUE TITLE
HUGE issues with Google Colab. Can't connect Drive data to notebook. Same code working perfectly all week until major issues began Wednesday and still occurring. 

### ISSUE THREAD

**Issue by kathrinkajderowicz** [googlecolab/colabtools#1440]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by FarazNadeem22** [comment]
Hi Kat, 
I was just turning to github for help it seems you beat me to it. Faraz

**Comment by craigcitro** [comment]
It's impossible for us to help without a description of what's going wrong (link to minimal, public, self-contained notebook demonstrating the problem).
