### ISSUE TITLE
Issues with Collab (Loading files from gDrive)

### ISSUE THREAD

**Issue by yejiadong** [googlecolab/colabtools#1443]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: Am not able to intermittently load/read files from gDrive, and was not able to access a notebook for a short period of time earlier, throws OSError: [Errno 5] Input/output error when attempting to read any file of any size from gDrive, seems like Drive API errors still persist

- Describe the expected behavior: Read file normally with random access from gDrive

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/drive/1hBBHoMbcF2MjR8gl5lGoo3J5jzfDaSd-?usp=sharing

**Comment by craigcitro** [comment]
The drivefs logs are quite helpful, thanks!

In particular, if you look at the logs, you'll see you're hitting quota issues (`Failed to download content (QUOTA_EXCEEDED)`), which is out of our control. See #1020 for some possible workarounds.

**Comment by perlman-izzy** [comment]
Hi all,

I'm trying to train a GAN but it times out every time, sometimes less than an hour.  I'm a Pro member so not sure why.  Also when I reconnect I almost never see my sampled files from that session.  The 2 problems together make it impossible.  Any ideas?
