### ISSUE TITLE
Cannot COPY and PASTE any content from Colab cell

### ISSUE THREAD

**Issue by pym1024** [googlecolab/colabtools#1444]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

Cannot copy and paste contents from Colab cell which makes Colab almost unusable on mobile platform.
Noticed this problem for almost **ONE** year and saw bunch of people complain about it, but seems no Googler care about it. 

- Describe the expected behavior:

Copy selected contents from Colab cell and paste it to other place.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Any browser on iPadOS and iOS

**Comment by bragarods** [comment]
I’m also struggling with this. Colas is a great platform for all of us, but it really need to be addressed

**Comment by Ryan-Haines** [comment]
This is still an issue! Three years and a broken TEXT COPY function.

**Comment by cperry-goog** [comment]
What platform/browser did you see this in? Repo steps? I've never seen this.

Please also try in incognito mode; could be a conflicting browser extension.
