### ISSUE TITLE
[Feature Request] Tracking updates of new libraries

### ISSUE THREAD

**Issue by korakot** [googlecolab/colabtools#1445]
- Describe the current behavior:

Now I can track only the dependencies of `google-colab` by reading [history of setup.py](https://github.com/googlecolab/colabtools/commits/master/setup.py). For example, today I know it has updated `tornado` to 5.1 which resolve problems with many other libraries.

For other libraries, I can manually call `!pip freeze` to get the current state. But I want to track diffs and history as well.

For example, someone mentions that `holoviews` is now supported in Colab. I want to be able to track that or any other libraries. Then, I can write an article to promote a new library just available in Colab.

- Describe the expected behavior:

`requirements.txt` or equivalent information is provided through github as well.

**Comment by mayankmalik-colab** [comment]
We have created a new repo - [backend-info](https://github.com/googlecolab/backend-info). This repository would contain the latest apt-list.txt and pip-freeze.txt files. You would be able to track diffs and history easily starting today onwards.
