### ISSUE TITLE
Output is Not visible 

### ISSUE THREAD

**Issue by sravanatmoon** [googlecolab/colabtools#1449]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: The Output for any cell is not visible. 

- Describe the expected behavior: the output is generally visible 

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome, Edge both

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://drive.google.com/file/d/1VAuxJ9sLU-mknXS1IoxfZeXKllubh5JJ/view?usp=sharing

**Comment by craigcitro** [comment]
Notebook isn't public.
