### ISSUE TITLE
Colab is not terminating session when switching between different type of Runtypes

### ISSUE THREAD

**Issue by amarsinghen** [googlecolab/colabtools#1450]
Bug report for Colab: http://colab.research.google.com/.
None.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Was using colab session with Runtype: Hardware - None and Runtype Shape - Standard.
Switched to Runtype: Hardware - None and Runtype Shape - HIGH RAM
Expected previous session with Standard RAM to terminate automatically, but when I checked Active Sessions, the previous session was still running along with new one with HIGH RAM
![image](https://user-images.githubusercontent.com/32318822/88485747-3ea99300-cf2d-11ea-9322-0f875b767786.png)

- Describe the expected behavior:
Will expect the previous session to terminate since I am not using it, and do not want to count it towards my usage history.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
Should be reproducible by any notebook given the steps above

**Comment by craigcitro** [comment]
Thanks for the report!

b/162271754
