### ISSUE TITLE
Part of filepath displayed as url

### ISSUE THREAD

**Issue by ziatdinovmax** [googlecolab/colabtools#1452]
This is a minor issue but I recently noticed that sometimes parts of a file path are (mis-)identified by Colab as URL (see screenshot below). This happens when the path starts with e.g. ```"/content/..."``` although I haven't investigated this in detail.
![image](https://user-images.githubusercontent.com/34245227/88591657-adb8e180-d02a-11ea-8711-190565256207.png)

**Comment by katlyn-edwards** [comment]
This should now be fixed
