### ISSUE TITLE
Plotly plots not showing in Jupyter output widgets in Colab

### ISSUE THREAD

**Issue by liocoa** [googlecolab/colabtools#1458]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
I am trying to show a Plotly plot in a Jupyter Output widget. I am able to see print statements show up in the output widget, but Plotly plots do not.
![Capture](https://user-images.githubusercontent.com/62915202/88820636-90515800-d18f-11ea-9dcf-e2855b3290b8.JPG)

- Describe the expected behavior:
I would expect Plotly plots to appear in output widgets just like they do in Jupyter notebooks.
![Capture1](https://user-images.githubusercontent.com/62915202/88821378-98f65e00-d190-11ea-85b7-298828b1ab7f.JPG)

- The web browser you are using (Chrome, Firefox, Safari, etc.):
I am using Chrome.

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/12n92Ez3KRtkBhEOtKORnCY4qz6h2bS65?usp=sharing

**Comment by blois** [comment]
Thank you for the report! This should now be working.

**Comment by Yuri-Nassar** [comment]
I'm facing this issue. If I try to use some plotly graph it does not work, but with matplotlib it is ok.

**Comment by alexci26** [comment]
idem it doesn't work on Google Colab , I don't see any graph
