### ISSUE TITLE
PyTorch 1.6.0 does not work in GPU environment.

### ISSUE THREAD

**Issue by tmabraham** [googlecolab/colabtools#1460]
Please see the below image:
![image](https://user-images.githubusercontent.com/37097934/88860906-a5d77980-d1b1-11ea-9ba8-32282b351821.png)

Torch 1.6.0 is unable to find the GPU. It seems this is likely a Colab environment-specific issue.

**Comment by colaboratory-team** [comment]
CUDA libs need to match between the wheel and the host.
Updating colab VMs to PyTorch 1.6.0 is tracked in #1454.
