### ISSUE TITLE
Regarding search notebook content also

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#1465]
- Describe the current behavior:
when I do a search for a notebook, it searches for the name of the notebook.
but sometimes, I do not remember what name did I give to the notebook, or I do not give it any name, that is its name is
set to 'Untitled'.
so, searching for work that I did before becomes difficult.

- Describe the expected behavior:
notebook search looks for keyword within notebook also.
so, if I have a notebook, if which I wrote the word 'XYZ', and its named as 'Untitled', then if I search for 'XYZ', then this notebook
is displayed in the search results.

**Comment by blois** [comment]
You can use Drive's search functionality to locate notebooks based on the text contents.

**Comment by vainaijr** [comment]
thanks for your reply, I check the drive's search functionality, it appear to search based on text content, I close this issue.
