### ISSUE TITLE
Problem with "Files" navigation bar and tree structure

### ISSUE THREAD

**Issue by qraleq** [googlecolab/colabtools#1468]
- Describe the current behavior:

Let's say I have a directory tree structure similar to this one:
.
|---   `content`
------ |---   `first_folder`
--------------|---   `second_folder`
---------------------|---   `file_1.txt`
---------------------|---   `file_2.txt`
---------------------|---   `file_3.txt`

Opening `first_folder` that only contains a single folder (`second_folder`) without any files using the "Files" navigation bar doesn't show any content, and it's not possible to navigate to `file_1.txt` using it.

The tree shown in the "Files" navigation bar looks like this:
.
|---   `content`
------ |---   `first_folder`

- Describe the expected behavior:

Expected behavior is to see a tree like this:
.
|---   `content`
------ |---   `first_folder`
--------------|---   `second_folder`
---------------------|---   `file_1.txt`
---------------------|---   `file_2.txt`
---------------------|---   `file_3.txt`

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

**Comment by blois** [comment]
The file tree does not automatically refresh when directory contents change- does the refresh button at the top make `second_folder` appear?

**Comment by qraleq** [comment]
> The file tree does not automatically refresh when directory contents change- does the refresh button at the top make `second_folder` appear?

Unfortunately, it doesn't.

**Comment by blois** [comment]
I'm unable to repro this- I'm trying using this- https://colab.research.google.com/gist/blois/204227f801dcb74499d247c2c1f162d0/untitled565.ipynb. Does it reproduce with that notebook for you?

What browser are you using? If Chrome, does it happen in incognito window?

**Comment by qraleq** [comment]
Using your notebook it doesn't happen. It happens when I clone this repo: https://github.com/qraleq/models and when I try to navigate to `research/object_detection/models/checkpoints/detection`.

I'm using Chrome and it does happen in incognito mode too.

**Comment by blois** [comment]
Thanks for the report- I can also repro with:
```
!mkdir -p models/research/object_detection/models/checkpoints/detection
```

**Comment by blois** [comment]
This appears to be https://github.com/googlecolab/colabtools/issues/621
