### ISSUE TITLE
Failed to upload file through google.colab.files.upload()

### ISSUE THREAD

**Issue by zfukuoka** [googlecolab/colabtools#1469]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
  - File upload is failed through google.colab.files.upload() .
    - When above API is executed, widget for upload files isn't appeared and message "Upload widget is only available when the cell has been executed in the current browser session. Please rerun this cell to enable." is appeared. 
    - It can reproduce colab's sample program in https://colab.research.google.com/notebooks/io.ipynb

- Describe the expected behavior:
  - File upload is available through google.colab.files.upload() . 

- The web browser you are using (Chrome, Firefox, Safari, etc.):
  - Chrome 84.0.4147.105 on Windows 10(64bit)
  - Firefox 79.0 on Windows 10(64bit)

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
  - https://colab.research.google.com/notebooks/io.ipynb

**Comment by blois** [comment]
I'm unable to reproduce this with Firefox 79.0 or Chrome 84.0.4147.105. Does this happen for every file? Does it happen in an incognito window as well?

**Comment by zfukuoka** [comment]
Thank you for trying to reproduce.

As you point, this happen for every file and it happen in an incognito window on Chrome.

Just now, I found this issue is related to third party cookie from your old post.
It doesn't happen when enabled to third party cookie on Chrome.
I'm sorry for stealing your time.
