### ISSUE TITLE
Installing custom repository packages using pip

### ISSUE THREAD

**Issue by zafarali** [googlecolab/colabtools#147]
I try to execute this command in the notebook
```
!git clone https://github.com/zafarali/emdp.git
!pip install -e ./emdp
```

However, sometimes once it's done I try to import things from the library: `from emdp.examples import build_SB_example35` it fails. The way I currently fix the problem is that i restart the runtime and re-execute the command it then it works. Any ideas as to what I might be doing wrong?

Zaf

**Comment by colaboratory-team** [comment]
Sorry, we're not able to diagnose issues with code written in Colab.
