### ISSUE TITLE
[Feature Request] Editable code cell execution queue 

### ISSUE THREAD

**Issue by Santosh-Gupta** [googlecolab/colabtools#1471]
Say that I select 'run all' but then I realize there's a few cells that I don't want to be included in the queue run. It would be great to just remove them from the queue. 

This might be tricky with short/fast code blocks, but would be useful for code blocks that take a while to execute.

**Comment by blois** [comment]
Agree that this would be super useful- I'd also love to be able to amend the code after it's enqueued. The executions are queued up on the kernel and there is no mechanism right now to modify that queue while it is processing code- this would probably be a substantial change.
