### ISSUE TITLE
노트북 실행 결과 셀에서 정렬문제 발생

### ISSUE THREAD

**Issue by y0918y** [googlecolab/colabtools#1476]
> df_test.isnull().sum()

> 
PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

- 출력결과 셀을 보면 테이블의 첫번째 컬럼은 왼쪽정렬, 두번째 컬름은 오른쪽 정렬이 되어야 가독성이 좋은데 ~
- 이상하게 제 colab에서면 결과 컬럼이 들쭉날쭉합니다. 원인을 모르겠어요

**Comment by blois** [comment]
This is what I see for the titanic training set:
https://colab.research.google.com/gist/blois/e8a61b54e250a416e987b3f9075bf0e9/untitled581.ipynb

![image](https://user-images.githubusercontent.com/2152569/89597443-09dfea80-d80f-11ea-9332-216bd5b96aa5.png)

**Comment by y0918y** [comment]
[image: image.png]

??????

2020년 8월 7일 (금) 오전 10:03, blois <notifications@github.com>님이 작성:

**Comment by y0918y** [comment]
< img src = "https://mail.google.com/mail/u/0?ui=2&ik=b308247f5c&attid=0.1&permmsgid=msg-a:r467260782479358582&th=173c67370c184552&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ8ffhFcyo-rS8iSStQf32fh5dRCUoMyVIcU3m3J1-bIAQAHR9U23SKeS9ZYsaZQUqAYqfRoEHPLCdBnncnicwz-FOYeKTNEndBTcwP86U_2y6HgYIpERllehz8&disp=emb&realattid=ii_kdjj1toi0">

**Comment by blois** [comment]
The text is rendered using the browser's default fixed-width font- it looks like yours is set to a proportional font. You can change the font in your browser settings. 

![image](https://user-images.githubusercontent.com/2152569/89610408-43285280-d82f-11ea-9311-e0748c7d3491.png)
