### ISSUE TITLE
selection + paste error

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#1479]
https://www.twitch.tv/videos/703519842?t=00h14m58s

it go from 5 rows selected, to 3 rows selected.

also it paste incorrectly

https://www.twitch.tv/videos/703519842?t=00h25m00s

**Comment by blois** [comment]
If you arrow up/down to the top/bottom of the cell then the selection will narrow- it looks like you're hitting that.

Most of this functionality is going to be in the https://github.com/microsoft/monaco-editor/issues component, you can experiment in https://microsoft.github.io/monaco-editor/playground.html.
