### ISSUE TITLE
Large Keras Models Taking Forever to Compile

### ISSUE THREAD

**Issue by meethariprasad** [googlecolab/colabtools#148]
Consider following model.

`model2 = Sequential()
model2.add(LSTM(LSTM_Unitsize, input_shape=(n_timesteps_in, input_features), return_sequences=True,activation='relu'))
model2.add(AttentionDecoder(LSTM_Unitsize, n_features))
model2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])
`
It is a fairly large model with following parameters.

Total params: 114,965,400
Trainable params: 114,965,400
Non-trainable params: 0

Model is taking forever to compile! Is anyone facing the same issue in large model compilation?

**Comment by colaboratory-team** [comment]
Sorry, we're not able to diagnose issues with libraries used within Colab. I'd recommend asking a question on a more general-purpose forum like StackOverflow to attract the attention of domain experts.
