### ISSUE TITLE
ModuleNotFoundError for many pre-installed modules. Possibly name-dependent.

### ISSUE THREAD

**Issue by danzimmerman** [googlecolab/colabtools#1481]
**_Bug report for Colab: http://colab.research.google.com/._**

**_- Describe the current behavior:_**

Many apparently installed modules listed as available with `!pip list` or `!pip3 list` cannot be imported. 

There appear to be 379 pre-installed modules. Of these:

- 49 with all-lowercase names, hyphens replaced with underscores as necessary in the name, fail with a `ModuleNotFoundError`. Of these, only 10 are names without underscores. 
- Only one module fails for a reason other than `ModuleNotFoundError`. `kaggle` throws an `OSError`.
- Only one module with a capital letter in the name succeeds, `Cython`
- 28 mixed-case modules fail.
- 300 all-lowercase modules, some with underscores, some without, are successfully loaded.

These tests were conducted using `importlib.import_module()` but spot-checks with regular import syntax, for example, `import PyYAML` or `import scikit_learn`, also fail.

I ran these tests because I was unable to import [PyNEC](https://pypi.org/project/PyNEC/) after successfully installing with `!pip install PyNEC`, and noticed that other pre-installed mixed-case module names could not be imported.
 
**_- Describe the expected behavior:_**

I expect to be able to import any module listed with `!pip list` or `!pip3 list`, provided that I replace hyphens with underscores as necessary.

I also expect to be able to import newly-installed modules installed with `!pip install ModuleName`.

**_- The web browser you are using (Chrome, Firefox, Safari, etc.):_**

Microsoft Edge Version 84.0.522.52
Google Chrome Version 84.0.4147.105

**_- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):_**

Full tests checking all modules listed with `!pip list`:

https://colab.research.google.com/drive/1TP3xbKliMcNFC9WgEYjrLvKALRsBXphD?usp=sharing

Minimal selected manual imports:

https://colab.research.google.com/drive/1jbpy2pF4c1wKjYklBwvJi5GWdEyVWZ00?usp=sharing

**Comment by craigcitro** [comment]
This isn't a colab issue and is WAI: python package names need not have anything to do with how they're imported (which is admittedly wacky, but so it goes).

For example, PyYAML imports as `import yaml`. Usually the right answer is to check the library docs.

**Comment by danzimmerman** [comment]
Sorry, of course, this is what I get for working late at night. 

I guess my inability to import PyNEC is unrelated. Thanks.
