### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by rajans** [googlecolab/colabtools#1483]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
There is a type in the error message:

**`Truncation was not @ explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to @explicitely truncate examples to max length.`**

- Describe the expected behavior:

The message should read as below and the entire message lookup must be spell checked
Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment]
This isn't an error message controlled by colab.

**Comment by rajans** [comment]
Right, my bad. It should go to huggingface
