### ISSUE TITLE
Cannot change the font in the code cell

### ISSUE THREAD

**Issue by sml105012013** [googlecolab/colabtools#1486]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

 Although I have followed the instruction in Frequently Asked Questions in Colab, it doesn't make any change in the code cell.

- Describe the expected behavior:

Find` out the solution why the fonts in the code cell cannot be changed.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by blois** [comment]
Can you verify that you are changing the fixed-width font in the browser settings? Perhaps try an incognito window to ensure that no extensions are getting in the way?

**Comment by comicat-hu** [comment]
I got same problem in chrome (build 84.0.4147.125), windows 10 (build 19041)
I try incognito window and set fixed-width font = 'consolas' but fonts in the code cell still not change.

**Comment by blois** [comment]
@comicat-hu The font in the screenshot is a serifed font which I've never seen in use before, and it also does not match the font in the output. Other than an extension I'm not sure what else could be changing the font here. Perhaps using Chrome's devtools could narrow it down.

**Comment by comicat-hu** [comment]
> @comicat-hu The font in the screenshot is a serifed font which I've never seen in use before, and it also does not match the font in the output. Other than an extension I'm not sure what else could be changing the font here. Perhaps using Chrome's devtools could narrow it down.

I find the error in DevTools-Network, I'm not sure if it affects this issue.

<https://colab.research.google.com/generate-authorship-tag?authuser=0> (400 Bad Request)

<img width="846" alt="colab_font_issue_devtool_network" src="https://user-images.githubusercontent.com/19973124/91126269-2f596900-e6d6-11ea-964d-7fe6914d0d29.png">

---

DevTools-Console
<img width="838" alt="colab_font_issue_devtool_console" src="https://user-images.githubusercontent.com/19973124/91126454-98d97780-e6d6-11ea-82a4-81e59a52a780.PNG">

---

I try to use Edge (chromium based) and Firefox got the same issue.
Could it be related to the font of the OS ?

**Comment by blois** [comment]
It could be related to the OS font- I'd be curious if changing the fixed-width font preference to a different one has a different result.

**Comment by comicat-hu** [comment]
> It could be related to the OS font- I'd be curious if changing the fixed-width font preference to a different one has a different result.

It only affects the output cell but the code cell still not change.

**Comment by FranklinYu** [comment]
I come across the same issue. After some research I think it has to do with the fact that Chrome font-setting is per-script (“script” in the sense of [writing systems](https://en.wikipedia.org/wiki/Writing_system)): the OS-level configuration only maps to the “default” script, but when Chrome encounters an HTML node with [`lang` attribute](https://en.wikipedia.org/wiki/Writing_system) the script-specific default font takes precedence. In my case, the language is Chinese, so Chrome would use the default monospace font for Chinese, which is not the one I configured.

Chrome doesn’t seem to provide a native way to configure per-script fonts. In contrast, Firefox has [built-in UI to configure per-script font](https://support.mozilla.org/en-US/kb/change-fonts-and-colors-websites-use):

https://user-media-prod-cdn.itsre-sumo.mozilla.net/uploads/gallery/images/2022-06-12-08-43-50-9b0880.png

The screenshot shows “fonts for Latin”; with the dropdown I can also configure “fonts for Chinese”.

**Comment by FranklinYu** [comment]
Update: I found [the source code for the second extension](https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/mv2-archive/api/fontSettings)! I’ll try debugging that and see whether it fixes the issue.

**Comment by ragman-google** [comment]
Great sleuthing FranklinYu, I think you're right!

We may have a built-in solution here though: We've recently added a feature to allow you to change the Code Font from the Colab settings menu.

If you go to "Settings -> Editor", you should see a "Font family used when rendering code" input, which allows you to type your desired editor font:

![Screen Shot 2022-10-20 at 3 07 30 PM](https://user-images.githubusercontent.com/114030602/197068190-529dd791-ca0e-469b-8c7b-b564b254b0bb.png)

Please let us know if that works for you!

**Comment by FranklinYu** [comment]
I’m aware of that setting, but it is unfortunately sub-optimal, because it is not cross-platform. For example, on macOS I can use fonts native on that platform. Hard-coding the font in settings means that choices are limited to *cross-platform fonts*. According to [w3school](https://www.w3schools.com/cssref/css_websafe_fonts.php) this means we are stuck with “Courier” or “Courier New”; the latter is known to look bad, so we essentially have to use “Courier”.

Shall we reopen this issue?

**Comment by Raysekiro** [comment]
I wanted to share that I have successfully resolved the issue by changing the preferred language to English in the Chrome settings. If anyone else is experiencing a similar problem, try adjusting your language settings as it might help.
