### ISSUE TITLE
The Kernel is Disconnected during Long Training in GPU

### ISSUE THREAD

**Issue by meethariprasad** [googlecolab/colabtools#149]
I am trying to run my research code on Language Translation over GPU, but it is getting disconnected after 500 iterations, which I when reconnect will not restores running epochs. How can we run for long iterations without such interruptions in Collab? Can we fix it? Hint: It would have been wonderful, if we had feature like notebook schedule allowing researchers to spend more productive time on research. Great platform by the way! Kudos team.

**Comment by colaboratory-team** [comment]
We'll need more information to diagnose. Please share a self-contained notebook that reproduces the problem and we'll take a closer look.
