### ISSUE TITLE
Compilation failure: Dynamic shape is not supported for non trivial window

### ISSUE THREAD

**Issue by brand17** [googlecolab/colabtools#1491]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: 
I am trying to train Huggingface transformer on TPU. 
Input shape (sequence length) is determined in the start of every epoch and is the same for the whole dataset. 
It works well for 2-3 epochs. Then the program generates an error "Compilation failure: Dynamic shape is not supported for non-trivial window".
If I don't change input shape - it works fine.
If I train under GPU/CPU - it works fine.
The program works fine on TPU in Kaggle.
And it worked fine in Colab on TPU a week ago.
I tried a simple model instead of transformer (embedding layer and dense layer) - it works fine.

- Describe the expected behavior:
The program should not generate this error.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1p0BZEdxn6hQGmK5HR0AJIFBzJaYQKuDY?usp=sharing

**Comment by craigcitro** [comment]
Can you confirm whether the TF version is the root cause? (https://github.com/googlecolab/colabtools/issues/1470#issuecomment-668897876 has a recipe for changing the TF version on TPU.)

If so, I'd recommend reporting the issue upstream to tensorflow.
If not, I'd try asking on the huggingface repo.

**Comment by brand17** [comment]
I confirm - TF version is a root case. Thanks

**Comment by MrRobot2211** [comment]
Iam having a similar issue on a kaggle kernel when usaing keras tuner. The code runs normally on gpu though https://www.kaggle.com/felipebihaiek/tuner-baseline-implementation-resnet34
