### ISSUE TITLE
OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by danzeeeman** [googlecolab/colabtools#1492]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Receive OSError: [Errno 5] Input/output error when access a medium sized file (<400mb).

- Describe the expected behavior:
Open the file with python

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Safari

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by danzeeeman** [comment]
seeing this with a simple 

%cp /content/drive/My\ Drive/Datasets/network-snapshot-011421.pkl .

when trying to access anything from a mounted drive

**Comment by essamgoda** [comment]
sam issue with me
it shows with me with a large file (65GB) all time 
and the smaller files were worked fine then suddenly shows the same error

**Comment by Oz-art** [comment]
Same here. is there any suggested solution?
