### ISSUE TITLE
after updating windows i can not open my colab files

### ISSUE THREAD

**Issue by umairjavaid** [googlecolab/colabtools#1499]
getting error 400.
https://colab.research.google.com/drive/1MjBqwKkCGDdmY0UAwb5oG3h8C-CKGHWY?ouid=116469667804339088430
https://colab.research.google.com/drive/1sDGNxxWk5YpWRXu6LMNMELZ8NgTYrxcq?ouid=116469667804339088430
https://colab.research.google.com/drive/1dEV3SSofyYVppDAsy1ICgoOiXpnyHu0X?ouid=116469667804339088430
GETTING THE SAME ERROR 400 on all my files

**Comment by dczechowski** [comment]
I have students with this same error.

A work around is to remove the ?ouid=_____________________ from the URL

**Comment by cperry-goog** [comment]
Closing due to staleness. File a new bug with reproducible steps if this is an issue.
