### ISSUE TITLE
Feature request: Allow setting custom tab size

### ISSUE THREAD

**Issue by danjjl** [googlecolab/colabtools#15]
Currently Google Colaboratory uses 2 spaces for 1 tab.

I personally prefer using 4 spaces for 1 tab. This quickly leads to tabulation errors when copy-pasting code from a local text editor to an already partially filed notebook cell.

Could we add a setting allowing the user to specify the number of spaces corresponding to 1 tab.

---

PS

I tried to change it using the browser's js console:

```js
var cell = colab.Notebook.get_selected_cell();
var config = cell.config;
var patch = {
      CodeCell:{
        cm_config:{indentUnit:4}
      }
    }
config.update(patch)
```

`get_selected_cell` is not defined, I will still need to play a bit to get it working

**Comment by kennylawww** [comment]
It seems that now you have been already allowed to switch to 4 spaces per tab.
"Tools" -> "References"
![qq 20180607121334](https://user-images.githubusercontent.com/25930225/41078002-b16db742-6a4c-11e8-9637-e5a3ed69c0d3.jpg)
-> "Indent with spaces"
![qq 20180607121441](https://user-images.githubusercontent.com/25930225/41078007-b5ba8a14-6a4c-11e8-80f4-01745591f8b5.jpg)

**Comment by akira-okumura** [comment]
Two spaces should be the default behavior.
