### ISSUE TITLE
Saved Models are Not visible in directory

### ISSUE THREAD

**Issue by meethariprasad** [googlecolab/colabtools#150]
I have saved my model successfully using checkpoint,and made it to run for long. But it got disconnected in collab after 500 epoch's on GPU. When I reconnected, I tried to load my model but found a message saying it doesn't exist. Then I tried to find it in file system. It was not there. This made me wonder, what happened to my model?

`import os
os.path.isfile("main_model_weights_attn_new.h5")
os.listdir()`

My Notebook: GPU Translation Code.ipynb

Please fix this serious issue.

**Comment by colaboratory-team** [comment]
Backends are discarded once idle. You'll want to arrange to save model checkpoints periodically during training. A typical pattern is to save these checkpoints to persistent storage, e.g., in [Drive](https://colab.research.google.com/notebooks/io.ipynb#scrollTo=RWSJpsyKqHjH).
