### ISSUE TITLE
Colab keeps adding code cells automatically 

### ISSUE THREAD

**Issue by Rupam07** [googlecolab/colabtools#1504]
My google colab jupyter notebook keeps adding code cells automatically even when I am using or not using it 

I keep the notebook open on my browser to use/code after sometime and there are empty code cells added where the cursor was left last 

Please help me with the same.

**Comment by blois** [comment]
Possibly an extension? If you open in an incognito window does it happen? Could it be inadvertent clicks on the add cell buttons between cells? Alternatively the 'a' or 'b' single-key shortcuts adding cells when no editor is focused?

**Comment by Rupam07** [comment]
<img width="323" alt="Screen Shot 2020-08-13 at 2 35 22 PM" src="https://user-images.githubusercontent.com/48689684/90189540-3ac1a180-dd72-11ea-86c2-471931fdc3fb.png">

I believe it is this piece of code I found in inspection view that is creating this bug

**Comment by blois** [comment]
I believe that code is from an extension.

**Comment by Rupam07** [comment]
How do I remove this extension? I haven’t added it so I am not sure how to solve this

**Comment by blois** [comment]
You should be able to find it in `chrome://extensions/` then uninstall it.
