### ISSUE TITLE
Unable to run linux commands on colab notebooks

### ISSUE THREAD

**Issue by mithil-sri-sai** [googlecolab/colabtools#1506]
Bug report for Colab: http://colab.research.google.com/.

I am unable to run any linux commands (such as !ls, !w , !who ) when I was connected to local runtime on google colab notebooks, whereas I am able to run the commands when I am connected to the hosted runtime. I tried solving the issue from the website https://research.google.com/colaboratory/local-runtimes.html but I failed to do so. When I have connected to local runtime and run those linux commands, it says command is not recognized as internal or external comand, operable program or batch file.
![image](https://user-images.githubusercontent.com/60311405/90310776-6a0f1480-df12-11ea-9467-cb7007c89283.png)

**Comment by craigcitro** [comment]
This is WAI. The `!` magic isn't attempting to emulate linux: it's just going to run the string you give it as a command.
