### ISSUE TITLE
Unable to upload huge datasets

### ISSUE THREAD

**Issue by csrajath** [googlecolab/colabtools#1508]
I am uploading a TSV file for processing on GColab, the file is 4GB and the upload process is not getting completed from a very long time (hours). Any pointers here are of great help.
![DataSet_Uploading)](https://user-images.githubusercontent.com/23517359/90333161-115a7d00-dfe1-11ea-8e2b-04ec592fdf2e.png)

**Comment by antocommi** [comment]
We have similar problem with a 150K video dataset. It's a zip file in our drive account and we can't extract properly from bash script (unzip command) or with some python script.
