### ISSUE TITLE
How to switch code to md or reversely?

### ISSUE THREAD

**Issue by StevenJokes** [googlecolab/colabtools#1509]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by katlyn-edwards** [comment]
![yONfOFPzDj3](https://user-images.githubusercontent.com/2673487/90419697-cb96c680-e06b-11ea-8f38-4f6f9720929d.png)
 
These are available as keyboard shortcuts.

**Comment by StevenJokes** [comment]
Thanks. maybe make it more obvious.
