### ISSUE TITLE
can't upload files from local drive

### ISSUE THREAD

**Issue by naoualberbiche** [googlecolab/colabtools#1513]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
 I can't  upload files from my local drive
- Describe the expected behavior:
 Upload widget is only available when the cell has been executed in the current browser session. Please rerun this cell to enable.
---------------------------------------------------------------------------
MessageError                              Traceback (most recent call last)
<ipython-input-5-bc72f1aee996> in <module>()
      2 from google.colab import files
      3 
----> 4 uploaded = files.upload()
      5 
      6 for fn in uploaded.keys():

2 frames
/usr/local/lib/python3.6/dist-packages/google/colab/_message.py in read_reply_from_input(message_id, timeout_sec)
    104         reply.get('colab_msg_id') == message_id):
    105       if 'error' in reply:
--> 106         raise MessageError(reply['error'])
    107       return reply.get('data', None)
    108 

MessageError: TypeError: Cannot read property '_uploadFiles' of undefined

- The web browser you are using (Chrome, Firefox, Safari, etc.): chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment]
You need to follow the instructions at the beginning of the error messsage (`Please rerun this cell to enable`).

If that doesn't work, please attach a minimal, self-contained, public notebook that reproduces the issue.
