### ISSUE TITLE
Tensorboard do not work on firefox, error 403

### ISSUE THREAD

**Issue by hadaev8** [googlecolab/colabtools#1517]
Tried this demo
https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_in_notebooks.ipynb#scrollTo=E6QhA_dp3eRq

Chrome is fine.

**Comment by voltum** [comment]
Are third-party cookies blocked in Firefox and allowed in Chrome?

**Comment by hadaev8** [comment]
Not sure why, but now this is fine

**Comment by metrizable** [comment]
Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem including TensorFlow since then, if you are still experiencing the issue, please file a new issue with steps to reproduce/screencast or file in-product feedback.
