### ISSUE TITLE
Pip network connection broken

### ISSUE THREAD

**Issue by ricardobarroslourenco** [googlecolab/colabtools#152]
While trying to `!pip3 install lucid`:

> Collecting Lucid
>   Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6fc9a04160>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /packages/12/51/b6f9088712945a2d2b7407b45dfc4456d55247415c77ad5eddf792892510/lucid-0.0.8.tar.gz

I think that it should be a network connectivity problem with the container. Any hints?

**Comment by craigcitro** [comment]
This was almost surely https://status.python.org/incidents/zjxwp5lpyn8s; if you're still seeing this, feel free to reopen.
