### ISSUE TITLE
Plotly 3D-Plot is not visible in any of the programmes from a month, but it was good till a month back. 

### ISSUE THREAD

**Issue by sravanatmoon** [googlecolab/colabtools#1522]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: The files runs and produces output. but the 3D-Graph is invisible. 

- Describe the expected behavior: The 3D-Graph should be visible and even interactive 3D-manipulation by mouse is to be done. 

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome, Edge, Firefox

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*): https://drive.google.com/file/d/1zJ58GTX-IhG3Dy8zA_N3U7FfKnTKkGzJ/view?usp=sharing

**Comment by blois** [comment]
It looks like

```python
import plotly.offline as offline
offline.init_notebook_mode()
```

Changes the default renderer from `colab` to `plotly_mimetype+notebook`.

It looks like it works if you just omit that line, or perhaps reset the default renderer to `colab` after calling it.  See the documentation at https://plotly.com/python/renderers/#setting-the-default-renderer.
