### ISSUE TITLE
Cannot connect to GPU backend

### ISSUE THREAD

**Issue by 3rk3** [googlecolab/colabtools#1523]
You cannot currently connect to a GPU due to usage limits in Colab. What's happened?

**Comment by craigcitro** [comment]
https://research.google.com/colaboratory/faq.html#usage-limits

**Comment by hoangphuc1998** [comment]
I ran a notebook with GPU 2 weeks ago and now I can't connect to GPU anymore (I have tried many times in many days). I think the GPU reset time is 24 hours. Please help

**Comment by RaghavPrabhakar66** [comment]
I am also having same issue. I am pretty sure that I did not exhaust GPU resources as I ran notebook for just 1 hr. But for past two weeks I am getting `Cannot connect to GPU Backend`. Also I have two google accounts (personal + college (.edu)) and both cannot to GPU. Even if I used all my resources, I think cool down period is around 2-3 days not 2 weeks.

**Comment by Aisharjaa** [comment]
Any solution?

**Comment by GianniGi** [comment]
Limits for the paid version are too low, I keep gettin "Cannot connect to GPU backend". That's crazy.
