### ISSUE TITLE
Ctrl + M M and Ctrl + M D commands are not working

### ISSUE THREAD

**Issue by lbaiao** [googlecolab/colabtools#1526]
Bug report for Colab: http://colab.research.google.com/.

Ctrl + M M and Ctrl + M D commands are not working

When I try the Ctrl+M D, the browser actually adds the page to my bookmark.

Browser: Chrome Versão 85.0.4183.83 64 bits

**Comment by lbaiao** [comment]
I tried the commands with the Edge browser, and it worked. After that, I went back to Chrome and it worked again. I don't know why it is working again, or if it is related with the browser change.

**Comment by craigcitro** [comment]
If you come up with consistent repro steps, in particular that work in an incognito window, we're happy to take a look.

(Why incognito? Situations like this are often due to extensions.)

I'm going to close since the problem is gone, but feel free to reopen if you manage to repro.
