### ISSUE TITLE
Mounted google drive stop showing *.csv files after run pandas read_csv function once.

### ISSUE THREAD

**Issue by billchenxi** [googlecolab/colabtools#1529]
- Describe the current behavior:
This just happened this morning 8:42 Pacific time, I first mount the google drive, and using pandas to read a few CSV files from a shared folder. They are large files, after running the first one, the mounted drive stopped showing any CSV files.
- Describe the expected behavior:
Yesterday I run the code, there's nothing wrong.
- Browser using are: Chrome, Edge (I don't think it's browser related)
- Here is the problem, you can see from the below replication, the code read one csv, then when it read the second one, it stop working, I double check the folder using `ls`, all the csv files are gone.
```
Enter your authorization code:
··········
Mounted at /content/drive
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-d5e364018267> in <module>()
      6 from sklearn.preprocessing import MinMaxScaler
      7 data_flt = pd.read_csv('/content/drive/Shared drives/Fake_path/data_flt.csv', dtype='float32')
----> 8 data_int = pd.read_csv('/content/drive/Shared drives/Fake_path/data_int.csv', dtype='int32')
      9 uniprot  = pd.read_csv('/content/drive/Shared drives/Fake_path/final_uniprot.csv')
     10 

4 frames
/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   1889         kwds["usecols"] = self.usecols
   1890 
-> 1891         self._reader = parsers.TextReader(src, **kwds)
   1892         self.unnamed_cols = self._reader.unnamed_cols
   1893 

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] File /content/drive/Shared drives/Fake_path/data_int.csv does not exist: '/content/drive/Shared drives/Fake_path/data_int.csv'
```
Does anyone have the same problem

**Comment by billchenxi** [comment]
I cannot even copy the file from the google drive to the colab local, even touch the file it will stop the drive mount to show CSV file.

**Comment by ValentinMoullet** [comment]
Hi! We have a similar problem where after having mounted Google Drive with our G Suite account, we cannot see all the files that are supposed to be in our Shared Drives. Everyone in our company is seeing different folders/files when looking at the same folder in the same Shared Drive. This started between yesterday and today.

**Comment by YeisonCardona** [comment]
Just after mounting the files are accessible, but a moment later "disappear", very annoying.

**Comment by ValentinMoullet** [comment]
@YeisonCardona Exactly, same behaviour on our side. Does this happen in a Shared Drive as well? Or is it in "My Drive"?

**Comment by YeisonCardona** [comment]
@ValentinMoullet in my case, the problems are related to the "Shared drives", but is occasional, right now is working perfectly.

**Comment by ValentinMoullet** [comment]
I think this is the same issue as #1494.

**Comment by colaboratory-team** [comment]
Closing as dup of #1494. Anyone still seeing this issue please answer the question there.

**Comment by billchenJT** [comment]
@ValentinMoullet  this is not same issue. The #1494 1494 doesn't show certain file. This one is the file will not present AFTER run function on them, aka reading files will trigger a disappearing. Please make sure you are the one experience @1494 or #1529, then comment. Thank you!
