### ISSUE TITLE
Files not downloading using mozilla firefox

### ISSUE THREAD

**Issue by vikashkr117** [googlecolab/colabtools#153]
I was using python 3 with GPU enabled in mozilla firefox browser. My browser pop-ups were not blocked.

My NN worked fine and I could see the weights file created at /content directory. But download was not getting initiated. There were no errors and the print statement below the download statement was also executing successfully.

``from google.colab import files``
``files.download('weights.h5')``
``print('complete')``

I had to use PyDrive to upload it to google drive and later download manually.

**Comment by blois** [comment]
This could be related to https://github.com/googlecolab/colabtools/issues/123, which we are actively working on.

**Comment by blois** [comment]
Scratch that last comment.
