### ISSUE TITLE
Attribute error 'NoneType' object has no attribute 'clip'

### ISSUE THREAD

**Issue by sathvikng** [googlecolab/colabtools#1530]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:AttributeError                            Traceback (most recent call last)
<ipython-input-9-4639c10487c4> in <module>()
      1 from google.colab.patches import cv2_imshow
----> 2 cv2_imshow(img)

/usr/local/lib/python3.6/dist-packages/google/colab/patches/__init__.py in cv2_imshow(a)
     20       image.
     21   """
---> 22   a = a.clip(0, 255).astype('uint8')
     23   # cv2 stores colors as BGR; convert to RGB
     24   if a.ndim == 3:

AttributeError: 'NoneType' object has no attribute 'clip'

- Describe the expected behavior:print the image

- The web browser you are using (Chrome, Firefox, Safari, etc.):Brave

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):https://drive.google.com/file/d/1TByqy21D6E4tZ_DrrfgfvkdKiIHXbiGx/view?usp=sharing

**Comment by craigcitro** [comment]
The error here means you're calling `imshow` with `None` instead of an image.

**Comment by himhan34** [comment]
i have the same problem as same as the people who questioned to you sir. 
can you explain more? for me? i tried that at my two account each in colab. 
but one did properly and i saw showed picture, but another didn't the error message is the same like the picture above your answer. can you explain how to solve the problem?

**Comment by ArchieAlexArkhipov** [comment]
I guess its the solution
img = cv2.imread(img_path)
cv2_imshow(img)
