### ISSUE TITLE
intro_to_fairness.ipynb Test data should retrieve "adult.test"

### ISSUE THREAD

**Issue by brccabral** [googlecolab/colabtools#1531]
Bug report for Colab: https://colab.research.google.com/github/google/eng-edu/blob/master/ml/cc/exercises/intro_to_ml_fairness.ipynb?utm_source=mlcc&utm_campaign=colab-external&utm_medium=referral&utm_content=fairness_tf2-colab&hl=en#scrollTo=-xgIRapb5LaQ 

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Test data is retrieving "adult.data"

- Describe the expected behavior:
Test data should retrieve "adult.test"

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/github/google/eng-edu/blob/master/ml/cc/exercises/intro_to_ml_fairness.ipynb#scrollTo=-xgIRapb5LaQ

**Comment by craigcitro** [comment]
You should report this on the repo the notebook comes from (colab doesn't own that notebook).
