### ISSUE TITLE
Error reading file from Google Drive

### ISSUE THREAD

**Issue by NicholasLaur** [googlecolab/colabtools#1532]
Hi, since this morning I have this problem when reading _.npz_ files from Google Drive:

```
`OSError  Traceback (most recent call last)
<ipython-input-4-1db54172dab4> in <module>()
----> 1 data = np.load(path, allow_pickle=True)
      2 data = data['arr_0']
      3 data1 = np.load(path_1, allow_pickle=True)
      4 data1 = data1['arr_0']
      5 data2 = np.load(path_2, allow_pickle=True)

/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    434         _ZIP_SUFFIX = b'PK\x05\x06' # empty zip files start with this
    435         N = len(format.MAGIC_PREFIX)
--> 436         magic = fid.read(N)
    437         # If the file size is less than N, we need to make sure not
    438         # to seek past the beginning of the file

OSError: [Errno 5] Input/output error`
```
When I reading _hdf5_ files I have this other problem:
```
`OSError                                   Traceback (most recent call last)
<ipython-input-20-a8bed9c8b8c9> in <module>()
     44 
---> 45   model = keras.models.load_model(filepathWeights)
     46

1 frames
/usr/local/lib/python3.6/dist-packages/h5py/_hl/base.py in is_hdf5(fname)
     42 
     43         if os.path.isfile(fname):
---> 44             return h5f.is_hdf5(filename_encode(fname))
     45         return False
     46 

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.is_hdf5()

OSError: Unable open file (file read failed: time = Sat Aug 29 16:17:29 2020
, filename = pathModel, file descriptor = 61, errno = 5, error message = 'Input/output error', buf = 0x7ffec729b4e0, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0)`
```

How I can fix these two problems?

**Comment by rustequal** [comment]
I have the same problem. When I try to copy a 26GB file from Google Drive it copied only 9GB, then this error appears:

```
!cp "/drive/My Drive/Colab Notebooks/db/diplom/ms1m_bin.tfrecord" "train_data/"
cp: error reading 'drive/My Drive/Colab Notebooks/db/diplom/ms1m_bin.tfrecord': Input/output error
```

If I try to copy again, then exactly 9Gb is copied again, then the same error appears.
Also, error "**A Google Drive quote has been exceeded**" is displayed below.

I have a paid subscription to Google One, as well as Colab Pro. I contacted Google One support, they investigated and said the problem was with Colab and my Google Drive quota is fine. They recommended referring here to resolve this error. That is, I cannot download a file over 10GB into the Colab session. The problem has been going on for over 2 weeks and is not related to Google Drive quotas according to the support "Google One".

**Comment by NicholasLaur** [comment]
I fixed this problem by migrating all files into Mega.nz and then downloading them every time. Hope it's useful for you too

**Comment by ch406769249** [comment]
> I have the same problem. When I try to copy a 26GB file from Google Drive it copied only 9GB, then this error appears:
> 
> ```
> !cp "/drive/My Drive/Colab Notebooks/db/diplom/ms1m_bin.tfrecord" "train_data/"
> cp: error reading 'drive/My Drive/Colab Notebooks/db/diplom/ms1m_bin.tfrecord': Input/output error
> ```
> 
> If I try to copy again, then exactly 9Gb is copied again, then the same error appears.
> Also, error "**A Google Drive quote has been exceeded**" is displayed below.
> 
> I have a paid subscription to Google One, as well as Colab Pro. I contacted Google One support, they investigated and said the problem was with Colab and my Google Drive quota is fine. They recommended referring here to resolve this error. That is, I cannot download a file over 10GB into the Colab session. The problem has been going on for over 2 weeks and is not related to Google Drive quotas according to the support "Google One".

I got the same issue. did you fix it?

**Comment by rustequal** [comment]
> I got the same issue. did you fix it?

Unfortunately no

**Comment by colaboratory-team** [comment]
#1607 tracks fixing the bug that causes I/O Error & "quota has been exceeded".
