### ISSUE TITLE
ColabPro and GPU

### ISSUE THREAD

**Issue by ramani41** [googlecolab/colabtools#1533]
I have subscription to ColabPro. When I run some notebooks I select GPU and High RAM. Recently it seems that it does not use GPU. In fact, it comes up with a warning that you are connected to GPU but not using GPU. I have tried with and without
!pip install tensorflow-gpu 

My ML training jobs and image processing with CV2 take for ever. Anyone knows why this happens and how to solve the issue.

<img width="1889" alt="ColabPro GPU warning 2020-08-29 at 2 19 49 PM" src="https://user-images.githubusercontent.com/51888338/91643703-90997900-ea03-11ea-9b05-e69c1834c552.png">

**Comment by drajsel** [comment]
Maybe it's related to [#1574](https://github.com/googlecolab/colabtools/issues/1574)? Check the output of 
```
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
```
and `!nvidia-smi`.
