### ISSUE TITLE
TIMEOUT when mounting Google Drive

### ISSUE THREAD

**Issue by ValentinMoullet** [googlecolab/colabtools#1538]
- Describe the current behavior:

I can't mount my drive using the usual `drive.mount('/content/drive')`. The following error appears:

    TIMEOUT                                   Traceback (most recent call last)
    <ipython-input-2-d5df0069828e> in <module>()
      1 from google.colab import drive
    ----> 2 drive.mount('/content/drive')

    4 frames
    /usr/local/lib/python3.6/dist-packages/pexpect/expect.py in timeout(self, err)
    142             exc = TIMEOUT(msg)
    143             exc.__cause__ = None    # in Python 3.x we can use "raise exc from None"
    --> 144             raise exc
    145 
    146     def errored(self):

    TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7f39c621acf8>
    searcher: searcher_re:
    0: re.compile('google.colab.drive MOUNTED')
    1: re.compile('root@352e6fca76e0-72631056df6b4467a181cdbbe437cfeb: ')
    2: re.compile('(Go to this URL in a browser: https://.*)$')
    3: re.compile('Drive File Stream encountered a problem and has stopped')
    4: re.compile('drive EXITED')
    <pexpect.popen_spawn.PopenSpawn object at 0x7f39c621acf8>
    searcher: searcher_re:
    0: re.compile('google.colab.drive MOUNTED')
    1: re.compile('root@352e6fca76e0-72631056df6b4467a181cdbbe437cfeb: ')
    2: re.compile('(Go to this URL in a browser: https://.*)$')
    3: re.compile('Drive File Stream encountered a problem and has stopped')
    4: re.compile('drive EXITED')

- Describe the expected behavior:

I expected it to mount correctly as always. I've tried with my business account (G Suite) and my personal account, both have the same issue since today. I'm aware of the [drive timeout issues](https://research.google.com/colaboratory/faq.html#drive-timeout) which can happen if there are too many files/folders in the Drive, but it doesn't seem to be the case as I tried to mount in 2 different Google Colab notebooks with 2 different accounts that don't share any drives/folders. The same issue also appears for all our collaborators in our business.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Google Chrome

----------

The research in our business is based on Google Colab, and we are now stuck because of this issue. It would be great to have some response to this.

Thanks in advance for your help!

**Comment by shangguan9191** [comment]
Same problem!!!!!!

**Comment by nick-jhlee** [comment]
Same here! It worked (if I recall correctly) last week, but suddenly I'm seeing the timeout error.

The web browser you are using (Chrome, Firefox, Safari, etc.): Safari

**Comment by nbeili** [comment]
Same here. It was working yesterday fine, but today when I wanted to mount my drive to run the same code as yesterday , I had this error
<img width="988" alt="Screen Shot 2020-09-02 at 11 17 48" src="https://user-images.githubusercontent.com/49637264/91963295-f93b6b00-ed0d-11ea-821d-328e35f0d821.png">

**Comment by ArtemKarablinov** [comment]
Same problem!
https://github.com/googlecolab/colabtools/issues/382 - here is an answer that huge amount of files in drive cause this problem.  I don't have a lot of files in drive, but i am using google photos and is it causes problems?

**Comment by ValentinMoullet** [comment]
@ArtemKarablinov I doubt that the issue is coming from a big number of files as mentioned in #382 , as this problem just started to happen today for multiple people. Also, I don't have a lot of files in the root of the My Drive of my personal account (less than 10).

**Comment by itan-git** [comment]
Same here
1 folder in Drive root, no changes since yesterday (was working)

**Comment by bamps53** [comment]
I have a same issue from about 10~12 hours ago.

**Comment by nbeili** [comment]
@ArtemKarablinov  yes, I have around 40000 file, but it was working well without problem. The problem occurs only today.

**Comment by skaltro-nn** [comment]
Same problem here. Never had troubles with mounting Drive untill today. Google scheduled an update maybe?

**Comment by condoy** [comment]
I was able to mount it with a direct string copy. The copy button doesn't seem to be working right.

**Comment by nbeili** [comment]
@condoy thanks, it is working now

**Comment by bamps53** [comment]
@condoy Thanks, you are genius!!

**Comment by skaltro-nn** [comment]
@condoy there's a big LoL here. Thank you very much!

**Comment by itan-git** [comment]
![https___i pinimg com_originals_59_c9_12_59c912db216ac16ba61c31fb3bd95325](https://user-images.githubusercontent.com/70638361/92000616-623ed500-ed46-11ea-9622-cd9379ec578a.gif)

**Comment by ValentinMoullet** [comment]
Damn, big facepalm ahah. Thanks for pointing this out @condoy! I will close the issue, I opened another one specifically about the button (#1540).

**Comment by Machine-Learning-Moron** [comment]
Use ('/content/drive/') and it will work. 🤓

**Comment by AYb442** [comment]
@sukanyabag 
thank you very much

**Comment by Subhan460** [comment]
Thanks very much darling @sukanyabag ...Really appreciate your efforts

**Comment by avadhnaresh** [comment]
yes bro its work
