### ISSUE TITLE
train_dataset not iterable

### ISSUE THREAD

**Issue by bowen0603** [googlecolab/colabtools#154]
I am running the code at section "Create the training tf.data.Dataset", but see the following error below. It sometimes works, but sometimes doesn't. Don't have a clue why it happens..

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-e4356c5eb59b> in <module>()
      6 
      7 # View a single example entry from a batch
----> 8 features, label = iter(train_dataset).next()
      9 print("example features:", features[0])
     10 print("example label:", label[0])

TypeError: 'BatchDataset' object is not iterable

**Comment by colaboratory-team** [comment]
Sorry, we're not able to diagnose issues with libraries used within Colab. I'd recommend asking a question on a more general-purpose forum like StackOverflow to attract the attention of domain experts.
