### ISSUE TITLE
"Copy" button on page when mounting doesn't work

### ISSUE THREAD

**Issue by ValentinMoullet** [googlecolab/colabtools#1540]
Hi,

When running `drive.mount('/content/drive')` and clicking on the link generated by it, we arrive on a page that contains a code which we can copy using a button (or manually copy/pasting). This "copy" button doesn't work and leads to a lot of people thinking Colab has a timeout issue (see #1538). In order to copy correctly, one needs to manually copy and paste.

It would be great to see it fixed! Thanks in advance!

**Comment by blois** [comment]
I'm unable to repro the 'copy' button not working, but I do see that when an incorrect authorization code is entered that drive.mount never completes.

**Comment by ValentinMoullet** [comment]
For me the button definitely still doesn't work.

![Screenshot 2020-09-02 at 17 57 13](https://user-images.githubusercontent.com/11041357/92007218-f197b880-ed45-11ea-990a-be8b4c35b9ff.png)

**Comment by craigcitro** [comment]
@ValentinMoullet thanks for the report! You're definitely not the only one hitting this, as per the dupes.

To confirm: can you repro this in an incognito window?

**Comment by ValentinMoullet** [comment]
@craigcitro No problem. Yes, I have the exact same problem in an incognito window.

**Comment by craigcitro** [comment]
OK, we believe the fix on the oauth2 page is now live everywhere, so this should be working again.

Thanks again everyone for the reports!

**Comment by eyildiz-ugoe** [comment]
It's not about the button per se. No matter how I would copy, authentication always fails.
