### ISSUE TITLE
colab not connecting in drive this is error appear 

### ISSUE THREAD

**Issue by Ahmed-Alghliz** [googlecolab/colabtools#1541]
![error](https://user-images.githubusercontent.com/69500120/92007431-a03ff700-ed4e-11ea-9fe0-7338ac8c0269.png)
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by blois** [comment]
This is tracked in https://github.com/googlecolab/colabtools/issues/1540.
