### ISSUE TITLE
Google Colab Pro drive.mount() Timeout all the time

### ISSUE THREAD

**Issue by vovastrilets** [googlecolab/colabtools#1542]
Bug report for Colab: http://colab.research.google.com/.

The same second as I bought google Colab Pro I started getting timeout errors for
drive.mount('/content/drive')
Error code:
TIMEOUT                                   Traceback (most recent call last)
<ipython-input-1-d5df0069828e> in <module>()
      1 from google.colab import drive
----> 2 drive.mount('/content/drive')

4 frames
/usr/local/lib/python3.6/dist-packages/pexpect/expect.py in timeout(self, err)
    142             exc = TIMEOUT(msg)
    143             exc.__cause__ = None    # in Python 3.x we can use "raise exc from None"
--> 144             raise exc
    145 
    146     def errored(self):

TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7f4dac506ac8>

Did not have any issues with mounting same google drive with free version.
Please help.

**Comment by blois** [comment]
See https://github.com/googlecolab/colabtools/issues/1540
