### ISSUE TITLE
Mounting Google Drive - Timeout 

### ISSUE THREAD

**Issue by GeoKafkias** [googlecolab/colabtools#1543]
When I am trying to mount my Google Drive with the colab using the command:

 from google.colab import drive
 drive.mount("/content/drive/")

after entering the authorization code and waiting some time, it produces the message that says out of time (TIMEOUT). I tried the solutions that you suggested to the similar issues: 
1.  Factory reset runtime
2.  !cmd/ctrl-shift-p -> /bin/bash: cmd/ctrl-shift-p: No such file or directory
3.  !cat /var/colab/hostname -> m-s-3bpws6hr5ibeb
4.  I have only three folders with 31 files

This is the message:

TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7f3a83b53d30>
searcher: searcher_re:
    0: re.compile('google.colab.drive MOUNTED')
    1: re.compile('root@68687e1197a2-2c40a0d8523746ea8aa4c374a37a2f85: ')
    2: re.compile('(Go to this URL in a browser: https://.*)$')
    3: re.compile('Drive File Stream encountered a problem and has stopped')
    4: re.compile('drive EXITED')
<pexpect.popen_spawn.PopenSpawn object at 0x7f3a83b53d30>
searcher: searcher_re:
    0: re.compile('google.colab.drive MOUNTED')
    1: re.compile('root@68687e1197a2-2c40a0d8523746ea8aa4c374a37a2f85: ')
    2: re.compile('(Go to this URL in a browser: https://.*)$')
    3: re.compile('Drive File Stream encountered a problem and has stopped')
    4: re.compile('drive EXITED')

Any recommendation?

Thanks,
Georgios

**Comment by blois** [comment]
See https://github.com/googlecolab/colabtools/issues/1540

**Comment by GeoKafkias** [comment]
> See #1540

Thank you very much! You are the best!
