### ISSUE TITLE
Mounting google drive timeout in colab

### ISSUE THREAD

**Issue by jielu0728** [googlecolab/colabtools#1544]
TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7fbdb7653b38>
searcher: searcher_re:
    0: re.compile('google.colab.drive MOUNTED')
    1: re.compile('root@a6381556aa3b-bc7cff5f6eef4c84b591bf0676e22814: ')
    2: re.compile('(Go to this URL in a browser: https://.*)$')
    3: re.compile('Drive File Stream encountered a problem and has stopped')
    4: re.compile('drive EXITED')
<pexpect.popen_spawn.PopenSpawn object at 0x7fbdb7653b38>
searcher: searcher_re:
    0: re.compile('google.colab.drive MOUNTED')
    1: re.compile('root@a6381556aa3b-bc7cff5f6eef4c84b591bf0676e22814: ')
    2: re.compile('(Go to this URL in a browser: https://.*)$')
    3: re.compile('Drive File Stream encountered a problem and has stopped')
    4: re.compile('drive EXITED')

I've retried many times, including reinitializing runtime, nothing has worked so far.
Yet I managed to run one notebook this morning, but I still encounter the same issues when I run others.

**Comment by burakozturan** [comment]
I have the same problem

**Comment by colaboratory-team** [comment]
See #1540.
