### ISSUE TITLE
Mounting Google drive timeout

### ISSUE THREAD

**Issue by naruto5406** [googlecolab/colabtools#1545]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I cannot mount Google drive anymore due to timeout error.
Here are the things I have tried:

  1. I have made sure there are only few direct childs in the folder the colab notebook resides.(Only 3 files and 3 directories)
  2. I have tried the colab notebook in several different folders and sub folders with few files in them.
  3. I have done this in new notebooks and have reset and restarted runtime.
  4. I have tried to mount gdrive of the other google account, still failed
  5. I have made sure there is no trash in trash folder

- Describe the expected behavior:
I should and used-to be able to mount google drive in a few seconds

- The web browser you are using (Chrome, Firefox, Safari, etc.):
chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1GEkvNBQyQ4y_Ne1tczF3QY0e5WkNO0I-?usp=sharing

**Comment by burakozturan** [comment]
same here , i did the same steps and could not connect to colab

**Comment by colaboratory-team** [comment]
See #1540.
