### ISSUE TITLE
After mounting google drive in colab, file format changed to .gdoc

### ISSUE THREAD

**Issue by yashkhandelwal2006** [googlecolab/colabtools#1548]
Bug report for Colab: http://colab.research.google.com/.

When I mount the google drive in colab, formats of all the .py files as well as .txt files have been changed. I can see .py file as .py.gdoc file and I am no more able to use those files now.
I tried this on both 'chrome' and 'firefox'. Same issue in both.

**Comment by Vignesh2999** [comment]
> Bug report for Colab: http://colab.research.google.com/.
> 
> When I mount the google drive in colab, formats of all the .py files as well as .txt files have been changed. I can see .py file as .py.gdoc file and I am no more able to use those files now.
> I tried this on both 'chrome' and 'firefox'. Same issue in both.

i too have the same error. how to rectify it?
