### ISSUE TITLE
How to use turtle module in colab on Windows10, always how error: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by laibird** [googlecolab/colabtools#1549]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
import turtle
T = turtle.Turtle()

TclError                                  Traceback (most recent call last)
<ipython-input-10-5bdf1a39e6ef> in <module>()
----> 1 T = turtle.Turtle()

4 frames
/usr/lib/python3.6/tkinter/__init__.py in __init__(self, screenName, baseName, className, useTk, sync, use)
   2021                 baseName = baseName + ext
   2022         interactive = 0
-> 2023         self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
   2024         if useTk:
   2025             self._loadtk()

TclError: no display name and no $DISPLAY environment variable
- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):
chrome
- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment]
This isn't supported in colab (as there's no way to load a graphics display).

**Comment by laibird** [comment]
> This isn't supported in colab (as there's no way to load a graphics display).
But it can still use 
matplotlib.pyplot 
to draw graph, why do not support turtle drawing
