### ISSUE TITLE
files.upload() ONLY returns the original filename but the function increments the filename if the file already exists without returning new filename

### ISSUE THREAD

**Issue by rengler33** [googlecolab/colabtools#1550]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

`from google.colab.files import upload`

This function creates a convenient way to upload files. When a user runs the function and uploads a file, it returns an object with {"filename": "data"}. However, built into this function is the ability to increment the filename, if needed, should there be a file that already exists with the same name. The function does NOT return the incremented filename (it only prints it). 

- Describe the expected behavior:
When the user runs the cell again and uploads a file of the same name, the function is currently designed to add a counter to the filename. This is helpful to not overwrite the original file; however, the function prints the new name, but only returns the original name. It is difficult to access the LATEST file upload since the return value does not include the modified filename.

I would argue this is misleading. If a user makes a change to their file and re-uploads it with the same filename, this function is going to return the ORIGINAL filename and not the modified filename. 

Thus, it may go unnoticed to the user that the return value from this function is still referring only to the unmodified filename from the original upload. Since that file exists, it is likely that this error will not be noticed and the remainder of the notebook will not be using the intended file.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/14S48J4Y-y3PthhDibPV7ajy5FMleJfid?usp=sharing

**Comment by producercoder** [comment]
Wondering if there is any update on this? Still an annoyance.

**Comment by cperry-goog** [comment]
tracked internally b/290217619

**Comment by mayankmalik-colab** [comment]
We have made the changes. Closing it now.
