### ISSUE TITLE
Top level await

### ISSUE THREAD

**Issue by FredrikNoren** [googlecolab/colabtools#1553]
- Describe the current behavior:
I'm having some trouble running [pyppeteer](https://github.com/pyppeteer/pyppeteer) in colab (which I'm using to communicate with a reinforcement learning environment called [Derk's Gym](http://gym.derkgame.com/)). It's using async/away, and from what I understand the ["normal"](https://stackoverflow.com/questions/46827007/runtimeerror-this-event-loop-is-already-running-in-python) way to make that work is to use nest_asyncio. But pyppeteer unfortunately has a [bug](https://github.com/pyppeteer/pyppeteer/issues/99) which prevents it being used with nest_asyncio. 
From what I gather ipython/jupyter supports top level awaits, which would solve this problem. Is that something colab has on the roadmap? Or are there other solutions to running async code in colab that I'm not aware of?

- Describe the expected behavior:
Would be great if pyppeteer worked :)

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

```
!pip install pyppeteer

import asyncio
from pyppeteer import launch

async def main():
    browser = await launch()
    page = await browser.newPage()
    await page.goto('https://example.com')
    await page.screenshot({'path': 'example.png'})
    await browser.close()

asyncio.get_event_loop().run_until_complete(main())
```

**Comment by blois** [comment]
We need to get an ipython upgrade to allow pyppeteer working, this will take a bit of time. In the meantime I've been downgrading tornado to allow the asyncio to work.

```python
from google.colab import output
with output.temporary():
  !pip install pyppeteer tornado==4.5.3 
  !apt update
  !apt install chromium-chromedriver

import os
import signal

# Kill the process to restart with the older tornado version.
os.kill(os.getpid(), signal.SIGTERM)
```

**Comment by FredrikNoren** [comment]
@blois Thanks! That worked

**Comment by paaksing** [comment]
For those who need TOP LEVEL AWAIT LITERALLY. Upgrade your ipython and ipykernel, because it's of the old version that does not support this feature.
```
!pip install ipython ipykernel --upgrade
```
After this restart runtime and you're good to go.

**Comment by craigcitro** [comment]
Internal tracking: b/207773817

**Comment by metrizable** [comment]
The Colab runtime has been upgraded to `ipython==7.34` and, although YMMV, `asyncio` machinery appears to be working:

![4uwubyeRdAvbtwK](https://user-images.githubusercontent.com/65414824/229948096-db7184ab-e6f0-4c28-807c-9e376c621417.png)
