### ISSUE TITLE
Mounting Google Drive timeout

### ISSUE THREAD

**Issue by colab-user** [googlecolab/colabtools#1559]
I used the code

from google.colab import drive
drive.mount('content/drive')

to mount my Google Drive but after entering my credentials it just times out. I've tried resetting my runtimes but it didn't help. I have used this in the past and it used to work but now it doesn't.

I run !cat /var/colab/hostname and the output is:
m-s-1rjpt685tkzo0

what is the problem?

**Comment by colaboratory-team** [comment]
See #1540.
