### ISSUE TITLE
[OR-FGBFDL-25] I cannot register myself to google colab pro

### ISSUE THREAD

**Issue by miracle6719** [googlecolab/colabtools#1562]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: When I try to pay for it, I got this error message: [OR-FGBFDL-25] 

- Describe the expected behavior: 

- The web browser you are using (Chrome, Firefox, Safari, etc.):Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by sebbov** [comment]
This not a Colab error. You would need to contact [GPay customer support](https://support.google.com/pay) for help with this issue.
