### ISSUE TITLE
got <type 'str'> ('Authorization failed') as pattern 

### ISSUE THREAD

**Issue by JulianneLee** [googlecolab/colabtools#1565]
I was unable to mount the google drive (while for others is working fine). I already restart the runtime and run again it doesn't work.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://i.imgur.com/YbzTQf4.png

error message that can't be seen
`[1] 99101
root@b8d21a613da2-7e8549ce73194f22a57d99db3952b04a: cat /tmp/tmp0e1n_A/drive.fifo | head -1 | ( /opt/google/drive/drive --features=max_parallel_push_task_instances:10,shortcut_support:true,max_operation_batch_size:15,opendir_timeout_ms:60000,use_unique_user_id:true,enforce_single_parent:true --inet_family=IPV4_ONLY --preferences=trusted_root_certs_file_path:/opt/google/drive/roots.pem,mount_point_path:/content/drive --console_auth 2>&1 | grep --line-buffered -E "(Go to this URL in a browser: https://.*)$|Drive File Stream encountered a problem and has stopped|Authorization failed"; echo "drive EXITED"; ) &
[2] 99105`

**Comment by colaboratory-team** [comment]
Sorry for the breakage. 
If you use a python 3 runtime instead of python 2 this issue should go away.
Will keep this issue open until py2 fix is out.

**Comment by JulianneLee** [comment]
> Sorry for the breakage.
> If you use a python 3 runtime instead of python 2 this issue should go away.
> Will keep this issue open until py2 fix is out.

yeah but i have this problem next if i use python 3 instead of 2
https://i.imgur.com/Y8R6Pyh.png

**Comment by colaboratory-team** [comment]
That's https://github.com/keras-team/keras/issues/7440. There's a potential workaround in a [couple](https://github.com/keras-team/keras/issues/7440#issuecomment-321098478) of [comments](https://github.com/keras-team/keras/issues/7440#issuecomment-476554877) on that issue.

**Comment by shadowshot-x** [comment]
> Sorry for the breakage.
> If you use a python 3 runtime instead of python 2 this issue should go away.
> Will keep this issue open until py2 fix is out.

How to resolve this in Python2 ?

**Comment by MuaazZakria** [comment]
Hi !

I was also unable to mount my google drive while working on a py2 notebook. I was getting the following error:

TypeError: got <type 'str'> ('Authorization failed') as pattern, must be one of: <type 'unicode'>, pexpect.EOF, pexpect.TIMEOUT

**Comment by colaboratory-team** [comment]
py2 should be fixed in new VMs. If you're still seeing this problem please use the "Factory reset runtime" entry from the Runtimes menu.
