### ISSUE TITLE
Validation programming exercise shows error

### ISSUE THREAD

**Issue by koshygeoji** [googlecolab/colabtools#157]
while running train model function it shows:

ImportErrorTraceback (most recent call last)
<ipython-input-39-bed573cfb279> in <module>()
      6     training_targets=training_targets,
      7     validation_examples=validation_examples,
----> 8     validation_targets=validation_targets)

<ipython-input-38-df5551bf3284> in train_model(learning_rate, steps, batch_size, training_examples, training_targets, validation_examples, validation_targets)
     35   # Create a linear regressor object.
     36   my_optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
---> 37   my_optimizer = tf.contrib.estimator.clip_gradients_by_norm(my_optimizer, 5.0)
     38   linear_regressor = tf.estimator.LinearRegressor(
     39       feature_columns=construct_feature_columns(training_examples),

/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/lazy_loader.pyc in __getattr__(self, item)
     51 
     52   def __getattr__(self, item):
---> 53     module = self._load()
     54     return getattr(module, item)
     55 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/lazy_loader.pyc in _load(self)
     40   def _load(self):
     41     # Import the target module and insert it into the parent's namespace
---> 42     module = importlib.import_module(self.__name__)
     43     self._parent_module_globals[self._local_name] = module
     44 

/usr/lib/python2.7/importlib/__init__.pyc in import_module(name, package)
     35             level += 1
     36         name = _resolve_name(name[level:], package, level)
---> 37     __import__(name)
     38     return sys.modules[name]

/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py in <module>()
     22 
     23 # Add projects here, they will show up under tf.contrib.
---> 24 from tensorflow.contrib import batching
     25 from tensorflow.contrib import bayesflow
     26 from tensorflow.contrib import cloud

ImportError: cannot import name batching

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by blateyang** [comment]
I run into the same problem when I do the exercises in feature_crosses.ipynb. The  ImportError happened in the 7th code block as follows:
```
_ = train_model(
    learning_rate=1.0,
    steps=500,
    batch_size=100,
    feature_columns=construct_feature_columns(training_examples),
    training_examples=training_examples,
    training_targets=training_targets,
    validation_examples=validation_examples,
    validation_targets=validation_targets)

ImportErrorTraceback (most recent call last)
<ipython-input-32-551bfb6541f6> in <module>()
      7     training_targets=training_targets,
      8     validation_examples=validation_examples,
----> 9     validation_targets=validation_targets)

<ipython-input-31-29885d35152f> in train_model(learning_rate, steps, batch_size, feature_columns, training_examples, training_targets, validation_examples, validation_targets)
     36   # Create a linear regressor object.
     37   my_optimizer = tf.train.FtrlOptimizer(learning_rate=learning_rate)
---> 38   my_optimizer = tf.contrib.estimator.clip_gradients_by_norm(my_optimizer, 5.0)
     39   linear_regressor = tf.estimator.LinearRegressor(
     40       feature_columns=feature_columns,

/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/lazy_loader.pyc in __getattr__(self, item)
     51 
     52   def __getattr__(self, item):
---> 53     module = self._load()
     54     return getattr(module, item)
     55 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/lazy_loader.pyc in _load(self)
     40   def _load(self):
     41     # Import the target module and insert it into the parent's namespace
---> 42     module = importlib.import_module(self.__name__)
     43     self._parent_module_globals[self._local_name] = module
     44 

/usr/lib/python2.7/importlib/__init__.pyc in import_module(name, package)
     35             level += 1
     36         name = _resolve_name(name[level:], package, level)
---> 37     __import__(name)
     38     return sys.modules[name]

/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py in <module>()
     23 
     24 # Add projects here, they will show up under tf.contrib.
---> 25 from tensorflow.contrib import batching
     26 from tensorflow.contrib import bayesflow
     27 from tensorflow.contrib import cloud

ImportError: cannot import name batching
```
I don't know how to solve it. Should I install or upgrade some dependencies through !pip or !apt command? @craigcitro

**Comment by craigcitro** [comment]
@blateyang what else have you run in your current session? (I can run that cell with no errors in a fresh session.)

**Comment by blateyang** [comment]
Thanks for your reply.  @craigcitro  I have solved this problem by resetting the default settings and tensorflow versions through the command```!kill -9 -1```  in issues [#115 ](https://github.com/googlecolab/colabtools/issues/115).
