### ISSUE TITLE
Relative path to current notebook stored in Google Drive

### ISSUE THREAD

**Issue by rchurt** [googlecolab/colabtools#1570]
Bug report for Colab: http://colab.research.google.com/.

Let's say that the notebook I'm currently running in Colab is stored in my Google Drive (which is mounted in Colab as `gdrive`) here: `/gdrive/My Drive/my_project/notebook.ipynb`. And let's say that in the `my_project` directory, I have several other files and folders that are important for the code I'm running in the notebook, like `/gdrive/My Drive/my_project/data.csv` among others. When I want to access those files through the notebook, I have to enter the absolute path, e.g.:
```
path_to_csv = '/gdrive/My Drive/my_project/data.csv'
pd.read_csv(path_to_csv)
```

However, if I want to publish the entire project and share the code and data with someone else, if I share the file and they put it in a different location in their Google Drive, all of the absolute paths will break. It would be great if there were a feature to avoid this.

What I'm imagining is that you would introduce a function, let's call it `find_current_notebook_dir`, such that I could do the following:
```
current_notebook_dir = find_current_notebook_dir() # this evaluates to '/gdrive/My Drive/my_project/'
path_to_csv = current_notebook_dir + 'data.csv'
pd.read_csv(path_to_csv)
```

Google Colab already has a method for doing something similar to this via the browser interface ("File" -> "Locate in Drive")--perhaps that functionality could be adapted into a function like the above.

**Comment by craigcitro** [comment]
There are a lot of hiccups here, unfortunately -- for instance, if the notebook was loaded from github, it's not clear what the right behavior would be.

My advice would be to just have two variables (possibly `@param`s), one for `current_notebook_dir` and another for `relative_dir`.

**Comment by freenrg** [comment]
Why was this closed?
That answer dit not complete anything.

**Comment by rchurt** [comment]
Yes, I agree, I still think it would be helpful to have a function like this, and it doesn't seem like it would be terribly hard, since the functionality is already present in Colab. It doesn't need to work for all notebook locations (e.g., github)--it can give an error if the notebook isn't stored in Google Drive.

**Comment by IyadKhuder** [comment]
I'm facing the same issue and wondering the same. This is what has brought me here.
Let me add another question: Wouldn't be optimal if Google Colab allows _relative_ file path? i.e., when I put my CSV file in the same location as my .ipynb file (or in a subfolder relatively to its location), wouldn't be optimal that Google Colab accepts that relative file path? I obviously tried that and it failed to read it and returned a "file not found" error.  Correct me if I'm wrong.
