### ISSUE TITLE
VMs need CUDA 11 for tf-nightly releases >= 2.4.0-dev20200819 to see the GPU

### ISSUE THREAD

**Issue by drajsel** [googlecolab/colabtools#1574]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior: As of `tf-nightly` release `2.4.0-dev20200819` the GPU devices are not detected when connected to GPU. As mentioned [here](https://github.com/tensorflow/tensorflow/issues/42957), that release is the first one to use CUDA 11 instead of CUDA 10.1.

- Describe the expected behavior: The GPU devices should be detected when the accelerator is set to 'GPU'. 

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome 

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/gist/amahendrakar/25b8598fea215239f22d406a387c1735/42957.ipynb

**Comment by colaboratory-team** [comment]
[Indeed](https://colab.research.google.com/gist/colaboratory-team/74bde5d86c61dadf6da3eeb61b5ad209/tf-nightly-breaking-on-colab-gpu-vms-after-requiring-cuda-11.ipynb), tf-nightly-gpu==2.4.0-dev20200819 tries and fails to load libcudart.so.11.0 (and a handful of other CUDA 11 libs), so cannot use the GPU on colab VMs, since they only have CUDA runtimes up to 10.1.

**Comment by colaboratory-team** [comment]
Tracked internally as b/168211450.

**Comment by quickgrid** [comment]
Not getting GPU with tf-nightly `2.4.0-dev20201005` on colab.

**Comment by jvahl** [comment]
All tf-nightly builds on PyPi are now using CUDA 11 - August builds have been removed. Would be great the upgrade could be tackled soon... thanks!

**Comment by dbouchabou** [comment]
Is it possible to install a tf-nightly version that use CUDA 10.1 as August builds have been removed in pip ?

**Comment by dbouchabou** [comment]
Is it possible to install a tf-nightly version that use CUDA 10.1 as August builds have been removed in pip ?

**Comment by tjdurant** [comment]
I am running into this issue because there is a data augmentation [bug](https://github.com/tensorflow/tensorflow/issues/44501) in TF versions <2.4

But, versions >2.4 (where the bug is fixed) appear to need CUDA>=11.0

**Comment by Ruomei** [comment]
> Is it possible to install a tf-nightly version that use CUDA 10.1 as August builds have been removed in pip?
Same question.

**Comment by RicCu** [comment]
Are there any updates on this?

**Comment by colaboratory-team** [comment]
CUDA 11 is now available in Colab VMs, and tf-nightly (tf-nightly-2.5.0.dev20210302) can see the GPU:
![](https://user-images.githubusercontent.com/38081706/109763411-e31c4380-7ba6-11eb-8f92-f5bb8d5c39b3.png)

**Comment by sigeisler** [comment]
There seems to be a similar issue now with cuda 11.2. If one wants to install `tf-nightly` then `nvidia-smi` will not show any GPU anymore.

Investigating a little I found some inconsistencies in the current environment w.r.t. the installed versions (a mix of cuda 11.0 and 11.2):

```
!ls /usr/local | grep cuda
cuda
cuda-10.0
cuda-10.1
cuda-11.0
```

```
!nvidia-smi

Tue Jun 29 17:47:44 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P0    26W / 250W |      2MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
 
```
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
```

**Comment by bhack** [comment]
Yes this will be a reccurent issue. We Need to find a more general solution.

**Comment by sigeisler** [comment]
I see. Hmm but currently the Cuda 11.2 installation on Colab seems to be incomplete as well (a mix of cuda 11.0 and 11.2) or am I missing sth?
