### ISSUE TITLE
'Active Sessions' window keep popping up

### ISSUE THREAD

**Issue by hxrnedserpent** [googlecolab/colabtools#1576]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: The 'active sessions' window keep popping up every 2 minutes or so, it's annoying

- Describe the expected behavior: It never pop up randomly before, so... I dont know what happen

- The web browser you are using (Chrome, Firefox, Safari, etc.): chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):  https://colab.research.google.com/drive/1zapXd4V5LAFkE2_9RXejiJ-cf3s_lsCb?usp=sharing

![image](https://user-images.githubusercontent.com/60341870/92856956-3eeae880-f41e-11ea-949c-2b968bef63ce.png)

**Comment by kristalization** [comment]
This issue still persists!! I suffer from it. unable to use Collab at all.

**Comment by colaboratory-team** [comment]
The most common cause of this issue is third-party browser extensions. Try disabling extensions, or using Colab in an incognito window with extensions disabled, to resolve the problem.
