### ISSUE TITLE
while launching tensorboard, I get a google 403 error

### ISSUE THREAD

**Issue by kunal9665** [googlecolab/colabtools#1577]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

![image](https://user-images.githubusercontent.com/54747785/92896680-37393d00-f43a-11ea-8e3e-ea83803fe2ec.png)
![google error](https://user-images.githubusercontent.com/54747785/92896808-51731b00-f43a-11ea-8d94-d66ae44bf7d3.JPG)

**Comment by blois** [comment]
This can be due to third-party cookies being disabled in the browser settings, as the viewing code uses browser Service Workers which are disabled if third-party cookies are disabled.

**Comment by HowardHonig** [comment]
Enabled third party cookies in Windows chrome.  Didn't help.
