### ISSUE TITLE
File Not Found Error when loading large numpy arrays into notebook

### ISSUE THREAD

**Issue by cjstorfer** [googlecolab/colabtools#1579]
When trying to load in a numpy arrays for training I keep getting a File Not Found Error despite mounting on the drive. Before loading the files I ensure the file exists by using !ls in the file directory. The files are relatively large, ~7GB in total but thats still below whats allocated in the notebook. The order in which I load the files seems to matter, e.g. when I load smaller files first I get the error on the largest and when I load the largest first I get the error on the subsequent file. Following the error, when I try to load a file by re-running a cell which had successfully loaded without trouble previously, I get the error. Also after I get the error, when I !ls the same directory it appears as empty, as in the files are no visible. 

To try to fix this I factory reset the runtime and remount each time. I have this issue at least 50% of the time I try to run the notebook. It seems like some kind of internal runtime error (?) or something, I have no clue its pretty inexplicable to me. Has anyone experienced this or know a potential solution? Thank you!

Also this is my first ever post please let me know if you need any other information or anything. Thanks!

**Comment by colaboratory-team** [comment]
If the files are in "Shared drives" then you're likely running into #1494. 
Can you share a minimal reproduction notebook, ideally starting from "Factory reset runtime" and then doing as little as possible in the notebook to reproduce the issue. If you can minimize away library calls (e.g. by replacing numpy reads with `!cat file > /dev/null` and so on) that's helpful.
