### ISSUE TITLE
Google Colab uses outdated IPython version (5.5.0) from 2017

### ISSUE THREAD

**Issue by Nufflee** [googlecolab/colabtools#1582]
- Describe the current behavior:
Google Colab currently uses IPython 5.5.0 from 2017 while 7.18.x is the current version. [This](https://github.com/ipython/ipython/pull/11650) is the feature I was looking for in particular but it was not implemented until IPython 7. 
I also tried upgrading IPython through `%pip` but received an error message about `google-colab` depending on `ipython` 5.5.0.

IPython version can be checked as follows:
```py
import IPython

IPython.version_info
```

- Describe the expected behavior:
Google Colab should be using a more up to date version of IPython.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1kxegd8OUd8CcbxgIU1qfBeb_lCTkmixp?usp=sharing

**Comment by jamesthurley** [comment]
I also require IPython 7 (for asyncio async/await). I've made do with having the first cell of the notebook being:
```
!pip install "ipython>=7"
```
Then I run that cell first, ignore the errors and warnings, click the "Restart Runtime" button which appears, and so far that has worked fine for me. It would be great if the base version was upgraded though.

**Comment by craigcitro** [comment]
Duping against #1553

**Comment by EasyArray** [comment]
Just checking in to see if there is any possible movement on this (and later python versions)?
