### ISSUE TITLE
nvidia-smi ERR V100

### ISSUE THREAD

**Issue by ijpq** [googlecolab/colabtools#1587]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
show ERR when running !nvidia-smi

- Describe the expected behavior:
no ERR

- The web browser you are using (Chrome, Firefox, Safari, etc.):
chrome
- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1sB4gNswAEE404XV7LZxO-VwvWyjZZ_rj?usp=sharing

**Comment by OURLEDS** [comment]
Having Colab Pro + and only getting a P100, never a V100 or a G100, and definetely not a A100. What is the point of Paying Coolab Pro if you dont get a V100 ... BUT WHAT IS THE POINT OF PAYING COLAB PRO+ IF YOU NEVER GET A100  and not even a V100?

Seems like google has an algorithm that never lets you get a V100 neither A100 ...seems like lootboxes with GPU.

They dont give any information on what you can expect.  This is an horrible service with very clear scam attempt

**Comment by cperry-goog** [comment]
Thanks for the report, but looks like the file referenced by the URL doesn't exist. !nvidia-smi should work as long as you have a GPU runtime; please make sure you've selected GPU in runtime settings.
