### ISSUE TITLE
Cannot open colab

### ISSUE THREAD

**Issue by JUNGYO** [googlecolab/colabtools#1588]
Error loading https://apis.google.com/js/client.js
Error: Error loading https://apis.google.com/js/client.js
    at HTMLScriptElement.k.onerror (https://colab.research.google.com/v2/external/gapi_loader.js:14:415)

Using chrome and open colab file from my Gdrive, but cannot opening the file with those error.

**Comment by blois** [comment]
See https://github.com/googlecolab/colabtools/issues/981
