### ISSUE TITLE
Working Jupyter Notebook has issue training in Colab

### ISSUE THREAD

**Issue by contractorwolf** [googlecolab/colabtools#159]
I have a  working Jupyter Notebook that I wrote that is taken from several online examples that I wanted to use for a lunch-n-learn to teach some developers at the office to use TensorFlow.  I am trying to move it to Colab to make it easier for them to play around without having to install a bunch of things but I am having an issue getting it to trouble getting my working Jupyter Notebook train in Colab.  When it tries to train the classifier I hit this issue and I can not figure out what the problem is:

```---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-57-5c962f10a4d9> in <module>()
----> 1 classifier.train(input_fn=train_input_fn)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py in train(self, input_fn, hooks, steps, max_steps, saving_listeners)
    353 
    354     saving_listeners = _check_listeners_type(saving_listeners)
--> 355     loss = self._train_model(input_fn, hooks, saving_listeners)
    356     logging.info('Loss for final step: %s.', loss)
    357     return self

/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py in _train_model(self, input_fn, hooks, saving_listeners)
    819       features, labels, input_hooks = (
    820           self._get_features_and_labels_from_input_fn(
--> 821               input_fn, model_fn_lib.ModeKeys.TRAIN))
    822       worker_hooks.extend(input_hooks)
    823       estimator_spec = self._call_model_fn(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py in _get_features_and_labels_from_input_fn(self, input_fn, mode)
    678   def _get_features_and_labels_from_input_fn(self, input_fn, mode):
    679     """Extracts the `features` and labels from return values of `input_fn`."""
--> 680     result = self._call_input_fn(input_fn, mode)
    681     input_hooks = []
    682     if isinstance(result, dataset_ops.Dataset):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py in _call_input_fn(self, input_fn, mode)
    770       kwargs['config'] = self.config
    771     with ops.device('/cpu:0'):
--> 772       return input_fn(**kwargs)
    773 
    774   def _call_model_fn(self, features, labels, mode, config):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/inputs/pandas_io.py in input_fn()
    118     features = dict(zip(list(x.columns), features))
    119     if y is not None:
--> 120       target = features.pop(target_column)
    121       return features, target
    122     return features

KeyError: 'target'
``` 

My code is taken from here:
https://github.com/contractorwolf/tensorflow-irisdataset/blob/master/Iris-Estimator-Tensorflow-Basics.ipynb

The only difference is that I used the Colab "upload" module to move the file up and changed the file path to reference the new file location.  The other difference is that my code was running TensorFlow 1.41 in Jupyter Notebook, but I am new to TensorFlow so I cant tell if that is an issue or not.  Can someone give me some advice? Thanks in advance.  I am loving TensorFlow and would prefer to use Colab.

**Comment by contractorwolf** [comment]
here is the actual Colab notebook:
https://drive.google.com/file/d/1v04vdZ8H5xCyBG3ALIoAl9sw8MczG6Cb/view?usp=sharing

**Comment by colaboratory-team** [comment]
Sorry, we're not able to diagnose issues with libraries used within Colab. I'd recommend asking a question on a more general-purpose forum like StackOverflow to attract the attention of domain experts.
