### ISSUE TITLE
Pasting code in Firefox creates extra indentations

### ISSUE THREAD

**Issue by androbaza** [googlecolab/colabtools#1591]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:

`def perceptron(data, num_iter):
      features = data[:, :-1]
          labels = data[:, -1]
              
                  # set weights to zero
                      w = np.zeros(shape=(1, features.shape[1]+1))
                          
                              misclassified_ = [] 
                                
                                    for epoch in range(num_iter):'

- Describe the expected behavior:

`def perceptron(data, num_iter):
    features = data[:, :-1]
    labels = data[:, -1]
    
    # set weights to zero
    w = np.zeros(shape=(1, features.shape[1]+1))
    
    misclassified_ = [] 
  
    for epoch in range(num_iter):'

- The web browser you are using (Chrome, Firefox, Safari, etc.): Firefox

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*): 

https://colab.research.google.com/drive/1H1liNq-db0hypu28pZ3_S192Su8gnnkK?usp=sharing

**Comment by WolfByttner** [comment]
I second this. There is no obvious workaround in the IPython kernel.

`get_ipython().autoindent` can be set to both False and True - the bug remains. The magic `%autoindent` is disabled in Colab.

There was no obvious way to set indentation to 0 spaces, so it is unclear whether that is a valid workaround.

Setting the user agent string to Chrome did not fix the bug.

It should be noted that pasting content with zero indentation works just fine. It is only when the first indented line comes along that Colab starts double-indenting everything.
