### ISSUE TITLE
Migrate Colab to python3.8

### ISSUE THREAD

**Issue by johnnync13** [googlecolab/colabtools#1592]
- Describe the current behavior:
It is impossible to migrate to python 3.8

- Describe the expected behavior:
Researchers and anaconda software have updated to python 3.8, for all the best it brings. When will you migrate to python 3.8.5 by default in Colab? Is very useful...

Scipy >1.4.1 the packages like sklearn, statsmodel etc break down!

**Comment by craigcitro** [comment]
duplicate of #1422
