### ISSUE TITLE
New Seaborn version

### ISSUE THREAD

**Issue by lfalin** [googlecolab/colabtools#1593]
I use Google Colab for teaching data science and visualization. We often have students use Seaborn to create quick visualizations. Seaborn recently released version 11.0 of their library. (https://seaborn.pydata.org/whatsnew.html) 

This introduced a major change in their API, and they also updated all of their tutorial pages to correspond to this new API. Unfortunately, by default, these API changes aren't available on Colab. So when students attempt to follow the Seaborn tutorials, they just get a bunch of method not found errors. 

For example, this function from their [tutorial page](https://seaborn.pydata.org/tutorial/distributions.html#plotting-univariate-histograms):

    import seaborn as sns
    penguins = sns.load_dataset("penguins")
    sns.displot(penguins, x="flipper_length_mm")

Results in an error:

    AttributeError: module 'seaborn' has no attribute 'displot'

After forcing Seaborn to upgrade to the latest version, this works as expected.

I know that it's fairly easy to force a library upgrade in the notebook, but one of the reasons we use Colab is to try to keep this as easy as possible for students.  Forcing a library upgrade can be a bit confusing for new students because the exact procedure varies a bit depending on whether or not you've already loaded Seaborn into memory.

It can also cause quite a bit of confusion if they put the upgrade command in the same cell as the import statement, and keep getting stuck in this import/upgrade/restart loop.

So I was wondering if there's a timeline for when library upgrades typically happen and take effect for new instances, and if there's a procedure for requesting a specific upgrade. 

Thanks.

**Comment by craigcitro** [comment]
There's no strict timeline for updates; it's largely "when someone has time, and as long as it doesn't create other conflicts." A seaborn update should land next week.

In general, though, if you have notebooks that are for consumption by others, I'd encourage you to include a cell that installs the versions you're looking for at the top of your notebook, as that's the best bet for future-proofing them.

**Comment by lfalin** [comment]
Just wanted to confirm that default Seaborn is now 11.0 at the time I wrote this comment.
