### ISSUE TITLE
Colab Notebook doesn't work

### ISSUE THREAD

**Issue by DmitryVil** [googlecolab/colabtools#1596]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

It refuses to do anything. Even operation like: 4 + 5

I  got the message:
Error
Could not load the JavaScript files needed to display output.
This is probably because your Google Account login access has expired or because third-party cookies are not allowed by your browser.

- Describe the expected behavior:

- I tried to do this on Chrome and FireFox

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1FcSveJAQn_FBtoCTT3IMIr_4XgfuBdhX?usp=sharing

**Comment by Alex478** [comment]
Такая же проблема. Началось 4-7 дней назад . До этого работало около года нормально, без претензий. Прошу пояснить.

**Comment by Alex478** [comment]
Проблема исчезла.

**Comment by metrizable** [comment]
Since this issue was filed a while ago, if you are still experiencing the issue, please file a new issue with steps to reproduce/screencast or file in-product feedback.
