### ISSUE TITLE
files.upload() could accept a destination directory instead of implicitly using current directory

### ISSUE THREAD

**Issue by coatless** [googlecolab/colabtools#1598]
- Describe the current behavior:

File mounting is done using: 

```py
from google.colab import drive
drive.mount('/content/drive')
```

However, once the drive is mounted, there is no way to obtain what path the drive was mounted at as there lacks any accessor. We can only see a printed output:

https://github.com/googlecolab/colabtools/blob/993b687cd8cb1d71f590b55af510c4b3b7228765/google/colab/drive.py#L273

Moreover, the `files.upload()` option does not allow for data to be directly uploaded into the Drive. All files are written into a temporary directory. In order to store the files where the mount is, the user has to either: 1. drag files into the directory or 2. write move commands.

```py
!mv img.png content/drive/img.png
```

- Describe the expected behavior:

Ideally, there would be a way to access the mount path with: 

```py
drive.mountpath()
```

Also, during the file upload, there could be an option to specify a directory:

```py
files.upload(dir = drive.mountpath())
```

Per the readme, I'm not sure if it would be worth submitting a reference patch that could be incorporated.

**Comment by colaboratory-team** [comment]
The path printed during mount is simply the argument passed to mount passed through `os.path.expanduser()`, so an accessor is not needed for it.

You can use `files.upload()` to upload to an arbitrary directory by first `%cd <dir>`'ing into it: 
![Screen Shot 2020-09-22 at 11 42 27 AM](https://user-images.githubusercontent.com/38081706/93923819-be9f6f80-fcc8-11ea-8a78-18f7f8525c08.png)

**Comment by colaboratory-team** [comment]
Leaving this issue open and repurposed to track the feature request for `files.upload()`.
Thanks for the report!

**Comment by coatless** [comment]
@colaboratory-team, I suppose I'm trying to avoid having to define a variable holding the mount path: 

```py
from google.colab import drive

mountpath = '/content/drive'
drive.mount(mountpath)

!pwd
!echo $mountpath
!cd $mountpath
!ls $mountpath
```

RE: `files.upload()`: I didn't realize it was setup to upload to the working directory. Thanks!
