### ISSUE TITLE
Google drive mounts but the csv file is not available to be read by pd.read_csv

### ISSUE THREAD

**Issue by vcbarros** [googlecolab/colabtools#1599]
Bug report for Colab: http://colab.research.google.com/.

[stackoverflow](https://stackoverflow.com/questions/48967757/cant-read-a-file-in-google-colaboratory).

- Describe the current behavior:

Google colab notebook used to read the csv file from google drive. Now it does not read anymore.
The notebook has the same code:

from google.colab import drive
drive.mount('/content/drive')
.
.
.
raw_dataset = pd.read_csv(r'//content//drive//My Drive//XXXX XXXX//XXXXXX//XX XXX XX//dataset-completo.csv', sep=';')

Then I get the following error message:

FileNotFoundError: [Errno 2] File //content//drive//My Drive//XXXX XXXX//XXXXXX//XX XXX XX//dataset-completo.csv  does not exist: '//content//drive//My Drive//XXXX XXXX//XXXXXX//XX XXX XX//dataset-completo.csv'

- Describe the expected behavior:

Expected behavior was to get raw_dataset set up with the dataset-completo.csv content.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Google Chrome

**Comment by colaboratory-team** [comment]
The doubled slashes (`//`) are probably unintentional and would be better to drop.

Does `!ls '/content/drive/My Drive/.../dataset-completo.csv'` see the file before the read_csv method? Does it see after?
Does the file browser in the left-hand section of the colab UI show the file?

**Comment by vcbarros** [comment]
No, it does not see the file before the read_csv method. Here is the error message:

ls: cannot access '/content/drive/My': No such file or directory
ls: cannot access 'Drive/ICAP': No such file or directory

**Comment by colaboratory-team** [comment]
That looks like you've not escaped the space between `My` and `Drive`; either enclose the entire file path in quotes or use a `\` to escape the space.

**Comment by vcbarros** [comment]
Well, it improved, but the issue remains:

 !ls /content/drive/My\Drive/ICAP\2020/Listas/28\ago\20/dataset-completo.csv

Error message:

ls: cannot access '/content/drive/MyDrive/ICAP2020/Listas/28ago20/dataset-completo.csv': No such file or directory

File browser is still showing the file.

**Comment by colaboratory-team** [comment]
You've included the backslash but forgotten the space between `My` and `Drive` in the ls command.

**Comment by vcbarros** [comment]
Thanks. I have fixed it but still don't get it right:

  !ls /content/drive/My\ \Drive/ICAP\ \2020/Listas/28\ \ago\ \20/dataset-completo.csv
  ls: cannot access '/content/drive/My Drive/ICAP 2020/Listas/28 ago 20/dataset-completo.csv': No such file or directory

I had done the whole path between the cotes and the result was the same:

 !ls '/content/drive/My Drive/ICAP 2020/Listas/28 ago 20/dataset-completo.csv'
ls: cannot access '/content/drive/My Drive/ICAP 2020/Listas/28 ago 20/dataset-completo.csv': No such file or directory

**Comment by colaboratory-team** [comment]
Using the file browser find the file, click its 3-dot menu to the right of the filename, and select "Copy path". Then paste the result inside single quotes (`'`).

**Comment by vcbarros** [comment]
I have done it and it worked (pd.read_csv as well). I have noticed that the folder ICAP 2020 now has one undescore in between. 
Another comment, it worked with the 28 ago 20 with no underscore.

 !ls '/content/drive/My Drive/ICAP_2020/Listas/28 ago 20/dataset-completo.csv'
'/content/drive/My Drive/ICAP_2020/Listas/28 ago 20/dataset-completo.csv'
