### ISSUE TITLE
Can't use dollar $ symbol inside indented markdown snippet

### ISSUE THREAD

**Issue by johnkershaw** [googlecolab/colabtools#16]
I want to write this:

Your output should be formatted like this:

    Lasagne: $4
    Pizza: $5
    Total: $9

But the $ signs are being interpreted as inline LaTex markers.

I tried escaping them using \$, \\$, $$, $$$ etc but nothing works. Any ideas, other than using USD5 ?

**Comment by blois** [comment]
Would it be possible to share a notebook of what you are trying to do?

This appears to work correctly for me:
https://colab.research.google.com/notebook#fileId=1k3V7ySJDe-WK5TW7dDR5HZAbK5yChHm6&scrollTo=SDH_qgMOfjuY

**Comment by blois** [comment]
I'm unable to repro this- please re-open if you have an example of the markdown you're using.

**Comment by johnkershaw** [comment]
Paste this into a markdown cell. The data should all line up in the same column.

I'd rather not use a library and format it as a proper table, cos these students are just getting their heads around Python and Colab and those heads are already very full :/

Interestingly, the markdown parser on Git is rendering the text as intended, but the screenshot at the bottom from Colab is wonky.

## 10c Spending Tracker
The text file “spending.txt” contains the following data:

    spending.txt
    2015-09-19 L $11.77 Lunch
    2015-09-17 B $5.00 Phone top-up
    2015-09-16 S $48.42 Supermarket
    2015-09-15 B $15.00 Water
    2015-09-15 S $34.99 Shoes
    2015-09-15 L $9.00 Cinema
    2015-09-14 L $34.99 Coffee/cake
    2015-09-13 B $125.50 Electricity

Read the file and output the total amount of money spent in each category, in alphabetical order: (B)ills, (L)eisure, (S)hopping, eg:

    B: $145.5
    L: $55.76
    S: $83.41

![image](https://user-images.githubusercontent.com/5265410/35918534-bb0b53c4-0c44-11e8-969f-cd46bce63625.png)

**Comment by johnkershaw** [comment]
Don't know how to re-open the issue :(

**Comment by craigcitro** [comment]
Yep, I can repro this; will file a bug internally and update here as a fix rolls out.

In the interim, there's an easy workaround on your side: instead of using four-space indents, you can do triple-backquote blocks to make things work, eg
```
B: $145.50
L: $55.76
S: $83.41
```
and everything should work.

**Comment by craigcitro** [comment]
For Colab reference, this is b/73140877.

**Comment by johnkershaw** [comment]
Is this fixed? I've just pasted this text from a GCSE task and the $ signs are still causing colab to switch into Latex mode:

![image](https://user-images.githubusercontent.com/5265410/40699408-48e46260-63fe-11e8-80cd-1ec89e1440c8.png)

I can work around it using the kludge outlined by craigcitro (thank you!) but I had to come here to remember how to do it!

    ### TASK 3 – Calculate the price for a customer’s consignment of parcels
    Extend TASK 2 to also calculate the price for each parcel, using the following rules:

    * 1 kg to 5 kg inclusive costs ```$```10
    * Each 100 grams over 5 kg, up to 10 kg, costs an extra ```$```0.10

**Comment by colaboratory-team** [comment]
b/73140877

**Comment by corrieann** [comment]
This should now be resolved.  Please let us know if you still see issues.
