### ISSUE TITLE
Shortcuts with special character not working correctly with non-English keyboards

### ISSUE THREAD

**Issue by wltjr1007** [googlecolab/colabtools#160]
Images below are screenshots of shortcut settings in Colaboratory (i.e. Ctrl+ M H).

As you can see, "å" is added to the shortcuts when I type in a special character.
This happens not only in the settings panel, but also in the Colab cells. (Meaning preset shortcuts like Ctrl+/ does not work)

I suspect this is a problem with non-English keyboards (Korean keyboard for me), since I have not experienced this problem with an English Keyboard.

This problem comes and goes, and I could not find a regular pattern to this problem yet.
A workaround I found was to refresh the Colab Notebook every time this problem comes back.

BTW
I use Surface Book 2, Windows 10 Enterprise Korean Ver 1803, Chrome Ver 66.0.3359.170

![1](https://user-images.githubusercontent.com/5194237/39969826-ea5fba34-571c-11e8-8609-cca854c8315c.PNG)
![2](https://user-images.githubusercontent.com/5194237/39969827-ec679248-571c-11e8-90be-0a223401aa06.PNG)
![4](https://user-images.githubusercontent.com/5194237/39969828-ee128882-571c-11e8-8550-19055566fb1c.PNG)
![5](https://user-images.githubusercontent.com/5194237/39969829-ef11d490-571c-11e8-8d4c-570fb7284d02.PNG)

**Comment by colaboratory-team** [comment]
Please reopen if you discover a reliable set of steps to reproduce the issue, and we'll take a closer look.
