### ISSUE TITLE
Super-slow parquet reading with pyarrow

### ISSUE THREAD

**Issue by alippai** [googlecolab/colabtools#1600]
- Describe the current behavior:
Reading a medium size dataset (3GB) is slow compared to my local machine. It takes 3+ minutes instead of few seconds. I tried to copy the files to the local drive, creating tmpfs but it didn't work. %time says it's "user", so it's CPU bound. Used up to date bumpy, pandas, pyarrow (installed via pip install --upgrade). I wouldn't assume 30-50x slowdown (even if I have an i7). 
- Describe the expected behavior:
Fast parquet dataset loading

Maybe it's about some compile/CPU flags. @xhochy @kszucs, you are familiar with building/installing pyarrow, is there something I can check/validate?

**Comment by colaboratory-team** [comment]
Can you share a minimal notebook reproducing the issue?
(with whatever data is required to observe the issue)

**Comment by metrizable** [comment]
Since this issue was filed a while ago, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
