### ISSUE TITLE
Multi-line output only giving a single output

### ISSUE THREAD

**Issue by samantha-olinsky** [googlecolab/colabtools#1601]
Bug report for Colab: http://colab.research.google.com/.

_Describe the current behavior:_ 
When I have more than one line to be output within a single code block, only the last line is actually output.

_Describe the expected behavior:_
Each output from the code block should be returned on a separate line, within the same output "block".

_The web browser you are using (Chrome, Firefox, Safari, etc.):_ 
Chrome (with same issue on Safari)
Chrome Version 85.0.4183.121

_Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):_
https://colab.research.google.com/drive/1epbedRgubAIDX6sMc4bxf0oj8zn9Ih5v?usp=sharing

**Comment by craigcitro** [comment]
This is how notebook environments work: only the *last* value in a cell is displayed. If you want to see multiple values, you'll need to call `print` or `display`.
