### ISSUE TITLE
Output is not visible

### ISSUE THREAD

**Issue by malhartakle** [googlecolab/colabtools#1606]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
![image](https://user-images.githubusercontent.com/44829096/94349361-a23e6280-003b-11eb-9382-8b73fdeca8ac.png)
I'm not able to view the output after running a code cell.

**Comment by Avinash1a** [comment]
I have faced the same issue. Switching from chrome to firefox solved the problem.

**Comment by metrizable** [comment]
Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem including `nltk` since then, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
