### ISSUE TITLE
Synchronization issue in google colab and google colab

### ISSUE THREAD

**Issue by ruchikalalit** [googlecolab/colabtools#1608]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I am facing a issue while using colab with google drive. I mount the drive with 2tb of storage space, but the program execution takes only disk storage available with colab and when it get filled it, message popups that you have exceeded the  drive limit. My program need around 400gb or may be more space for complete execution, but am not able to do it as every time program generates error due to storage.
Thanks

- Describe the expected behavior:
proper data transfer should be there between colab and google drive whether its a read operation or write operation to the drive.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
chrome, firefox both
- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by colaboratory-team** [comment]
Sorry, colab's Drive integration is limited to the amount of disk available on the VM.
