### ISSUE TITLE
GPUs are not working in Colab Pro

### ISSUE THREAD

**Issue by vikalpjain91** [googlecolab/colabtools#1609]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
While training tensorflow network Unet in segmentation_model. gpu is not working for a single epoch it is taking 1.5 hr.

- Describe the expected behavior:
Each epoch should get trained within minutes

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1FsyH0mQlA_AScMZagy4cuPwxOAOrnZkY?usp=sharing

**Comment by vikalpjain91** [comment]
My runtime enviornment is GPU still cpu and gpu both environments are taking same time.

**Comment by vikalpjain91** [comment]
@colaboratory-team can you please have a look.?

**Comment by vikalpjain91** [comment]
and when the training is going on it is giving the error we are not using gpu:
![Uploading image.png…]()

**Comment by vikalpjain91** [comment]
![image](https://user-images.githubusercontent.com/16263750/94355688-d6e60480-00a3-11eb-8231-05cafac0b1e5.png)

**Comment by colaboratory-team** [comment]
You are overriding the version of TensorFlow that is preinstalled on the VM with `!pip install tensorflow==2.0.0` which lacks GPU support, so it's unsurprising that TF then doesn't use the GPU. 
Compare 
![image](https://user-images.githubusercontent.com/38081706/94948151-b77c1c80-0493-11eb-802c-732a1f4986c5.png)

to using `tensorflow-gpu==2.0.0`:

![image](https://user-images.githubusercontent.com/38081706/94948203-cebb0a00-0493-11eb-971f-eb3597f6adb1.png)

Note that the former never even tries to load CUDA libs while latter does and successfully finds the GPU.
