### ISSUE TITLE
Matplotlib plot style unexpected behavior

### ISSUE THREAD

**Issue by bpisaacoff** [googlecolab/colabtools#1610]
- Describe the current behavior: 
I'm getting some unexpected behavior when setting the matplotlib style in Google Colab. Whether or not ```plt.style.use``` is called in the first cell (which also has the ```import matplotlib.pyplot as plt``` import) or if it's called in a subsequent cell determines whether or not all of the style settings are correctly set.

NOTE: I'm referring to a fresh kernel, so in order to reproduce this behavior restart the kernel for each condition. Also, this behavior is not occurring in JupyterLab on my local machine (the style is set correctly regardless of where ```plt.style.use``` is called).

If the ```plt.style.use``` is called in a cell after the imports then everything is set correctly:
![image](https://user-images.githubusercontent.com/15311264/94453421-a3c47380-017e-11eb-8c5f-780c8e1193a5.png)

However, if ```plt.style.use``` is called in the first cell with the imports then only some of the style settings are set and others are not: 
![image](https://user-images.githubusercontent.com/15311264/94453491-bb036100-017e-11eb-8984-e86e5c495001.png)

- Describe the expected behavior: I expect the plot style to be fully set regardless of whether or not the style is set in the first cell or not.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/drive/1G3lvGPTfyYOvLbAjpjim4vfYnVAyJC0m?usp=sharing

**Comment by craigcitro** [comment]
I can repro, and it is indeed confusing. 😕 

Looks like this is https://github.com/jupyter/notebook/issues/3691; unfortunately, that probably means you're stuck waiting on us to upgrade IPython (which should happen, but is a nontrivial amount of work away).

**Comment by bpisaacoff** [comment]
No worries, it's not like this is a critical or pressing issue. Just wanted to flag it for your attention. Thank you
