### ISSUE TITLE
Failed to assign a backend -- Colab Pro

### ISSUE THREAD

**Issue by raghada** [googlecolab/colabtools#1611]
For some reason, I can't get a backend for long time now, even though I'm a Pro user and I haven't used Colab for the past two days.

Error message:

Failed to assign a backend
No backend with GPU available. Would you like to use a runtime with no accelerator?
More info

**Comment by JustinSty** [comment]
Same problem encountered here. I'm also a Pro user, and I'm not even using GPUs, just normal backend. Seems there isn't any available at this moment.

**Comment by craigcitro** [comment]
Thanks for the report! Yes, we're currently having an issue, and the fix is already being deployed; should be completed in less than 5 minutes.

Just to check: do you happen to be using multilogin? (We suspect the issue is related.)

Using a fresh incognito window for the next few minutes should get you unblocked.

**Comment by raghada** [comment]
> Thanks for the report! Yes, we're currently having an issue, and the fix is already being deployed; should be completed in less than 5 minutes.
> 
> Just to check: do you happen to be using multilogin? (We suspect the issue is related.)
> 
> Using a fresh incognito window for the next few minutes should get you unblocked.

Thanks for your prompt response, 

What do you mean by multilogin?

**Comment by craigcitro** [comment]
By "multilogin" I mean having multiple google accounts logged in as part of a single browser profile.

**Comment by raghada** [comment]
> By "multilogin" I mean having multiple google accounts logged in as part of a single browser profile.

Yes, this is the case actually.

**Comment by craigcitro** [comment]
Awesome, thanks for confirming.

Fix should be completely deployed, so assignments should be working again in all cases. (I'm going to close for now, but reopen if you're still getting failures.)
