### ISSUE TITLE
Cannot install onnxruntime 1.5.1

### ISSUE THREAD

**Issue by RicCu** [googlecolab/colabtools#1614]
- Describe the current behavior:
Installing and importing the latest onnxruntime-gpu release (1.5.1) fails. Apparently due to missing cudnn 8 in colab env.
Importing version 1.4.0 works as expected.

- Describe the expected behavior:
Successfully import onnxruntime 1.5.1 with gpu support

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1fGbc97A1WlnHhfrcccbXrHVYH7txYyOD?usp=sharing

**Comment by colaboratory-team** [comment]
cudnn 8 will come with cuda 11, tracked by #1574.
