### ISSUE TITLE
Doctest style examples in Numpy docstrings are poorly formatted

### ISSUE THREAD

**Issue by Mr0grog** [googlecolab/colabtools#1616]
Bug report for Colab: http://colab.research.google.com/.

I like to use [Numpy-style docstrings](https://numpydoc.readthedocs.io/en/latest/format.html) both because Numpy is so broadly used and because the format does a pretty good job being both human and machine readable in a variety of environments (e.g. both the REPL’s `help()` and in generated HTML documentation). However, I discovered today that the style used for code samples (the [doctest](https://docs.python.org/3/library/doctest.html) style) renders *really* poorly in Colab’s popovers.

In particular:
- line breaks aren’t preserved,
- the text is not monospaced,
- the `>>>` causes the text to be *very* deeply indented, and
- there’s no syntax highlighting (it’s clearly possible since GitHub-style fenced code blocks in docstrings *do* get syntax highlighting).

When examples include sample output, they become nearly unreadable because the code a reader should type and the sample output both run together.

Here’s an actual example from Numpy:

<img width="758" alt="numpy-docstring-example-formatting" src="https://user-images.githubusercontent.com/74178/94776136-016ee080-0376-11eb-9840-71358fda3c07.png">

And a more stripped-down example:

<img width="821" alt="numpy-docstring-example-formatting-2" src="https://user-images.githubusercontent.com/74178/94776166-0f246600-0376-11eb-955d-49e889c09117.png">

Or you can view the above examples live in this notebook:

https://colab.research.google.com/drive/1tb2YD1McF5g6qaP5Xvft0iLVsNJEvtN7

Anyway, it’d be lovely to get some additional formatting love for docstrings. Colab provides a really nice, approachable, no-setup environment for introducing people to programming techniques and sharing research code, and the docstring popups really help elucidate what’s going on!

**Comment by blois** [comment]
I just recently landed some improvements in this area- the formatting above should be better. I noticed one missing change which is missing from the hover tooltip but is in the completion tooltip- the wrapping of the param names in hover is incorrect but the fix should arrive shortly.

**Comment by blois** [comment]
From the simplified example above, this is what it should look like today:
![image](https://user-images.githubusercontent.com/2152569/95240741-b7488d80-07c1-11eb-9402-4148ffa6b74f.png)

**Comment by Mr0grog** [comment]
Oh, I didn’t even notice the parameter wrapping. Good to hear there’s a fix on the way for that soon. Regardless, this is fantastic! Thanks you. 😁 🙇

**Comment by param-rp** [comment]
> I just recently landed some improvements in this area- the formatting above should be better. I noticed one missing change which is missing from the hover tooltip but is in the completion tooltip- the wrapping of the param names in hover is incorrect but the fix should arrive shortly.

Wrapping of text is still not proper when using (ctrl + space), and the function prototype is not completely visible because there is a limit to the horizontal elongation of the pop-up.

![Screenshot from 2024-10-16 22-47-25](https://github.com/user-attachments/assets/e731c1b5-fcb5-4257-8b4e-9a31bdc5861a)
![Screenshot from 2024-10-16 22-46-48](https://github.com/user-attachments/assets/bbf8aac7-4836-48e4-898e-0e706dee5a4a)

As you see in the images, even if the pop up is enlarged downwards, then no wrapping happens and that causes trouble. Correct text wrapping would be highly anticipated rectification.
