### ISSUE TITLE
from google.cloud.vision import types ImportError: cannot import name 'types'

### ISSUE THREAD

**Issue by abehzad** [googlecolab/colabtools#1618]
Hello, I am trying to run the following:

import os, io
from google.cloud import vision
from google.cloud.vision import types

os.environ['GOOGLE_APPLICATION_CREDENTIALS']=r'/content/My-First-Project-fcdd4c0cc920.json' 

I am getting the following error: 

ImportError: cannot import name 'types'

I have tried:
!pip install google.cloud
!pip install google-cloud-vision

But I am still getting the same error. I have also uninstalled them both and upgraded them, still nothing. 

I have tried it in both chrome and firefox. 

Any help would be greatly appreciated.

**Comment by craigcitro** [comment]
After running `!pip install ...`, you'll need to restart your runtime (`Runtime` -> `Restart` or ctrl-m .), as imports are idempotent in python.
