### ISSUE TITLE
IPython payload is not working

### ISSUE THREAD

**Issue by arnabghose997** [googlecolab/colabtools#1619]
The IPython payload functionality is not working on Colab, as the code is not able to generate a new cell.

Attaching the following public colab notebook for reference:
https://colab.research.google.com/drive/17V_Hz8GwdQmwbfVxLGJRUn_4hnthiFWg?usp=sharing

Does Colab supports IPython Payload? If not, is there any workaround for it?

**Comment by craigcitro** [comment]
No, this isn't currently supported; this is actually the same root cause as #42.

(closing as duplicate of #42)
