### ISSUE TITLE
Colab output disappears once executed.

### ISSUE THREAD

**Issue by PoojithaV** [googlecolab/colabtools#1623]
`Bug` report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
![colab_issue](https://user-images.githubusercontent.com/19277533/95068856-c108bd00-06fd-11eb-9d8c-869c9b437385.JPG)

**Comment by PoojithaV** [comment]
![image](https://user-images.githubusercontent.com/19277533/95068927-e5fd3000-06fd-11eb-8bcc-2cc7cecb87dc.png)

**Comment by Avinash1a** [comment]
I have faced the same issue. Switching from chrome to firefox solved the problem.

**Comment by ZsoltSafrany** [comment]
I have the same issue on chrome

**Comment by blois** [comment]
We're seeing what appears to be a recent regression in rendering in Chrome- some reports say that clicking on the output will cause it to render again.

**Comment by ArunGaonkar** [comment]
I am still facing the same issue. 
don't know whether it's due to chrome settings or what?

**Comment by jchelquer** [comment]
Having the same issue. Cannot believe it is still happening!
