### ISSUE TITLE
google colab error while mounting google drive

### ISSUE THREAD

**Issue by Avinash1a** [googlecolab/colabtools#1625]
I'm trying to mount my google drive in google colab but it's not working. It worked absolutely fine till yesterday. From today onwards I'm facing error. When i paste the auth code, it keeps on running the cell but never get mounted. this is the code i have been using and i generelly copy and paste auth code manually (without clicking copy button) 

from google.colab import drive drive.mount('/content/drive') 

when i try debug code 
from google.colab import drive drive.mount._DEBUG = True drive.mount('/content/drive') 
It returned this error "bash: cannot set terminal process group (-1): Inappropriate ioctl for device bash: no job control in this shell." I dont have any idea about this .. please help

https://extraimage.com/images/2020/10/07/colab-error.png

**Comment by kenan-joot** [comment]
I'm having the same issue.

**Comment by voloddia** [comment]
Same here.

**Comment by colaboratory-team** [comment]
The "bash: cannot set terminal process group (-1): Inappropriate ioctl for device bash: no job control in this shell." message is expected and is emitted even on successful mounts.

The mount() call shouldn't take more than 3m; it should succeed or fail, likely with some sort of message in a popup/toast.
If you're still seeing this issue please describe what's happening: does the cell keep executing for longer than that? Does it ever terminate? Is any output emitted after the token is entered?

**Comment by voloddia** [comment]
It keeps running without any output.

**Comment by colaboratory-team** [comment]
We'll need some logs to debug further. Please "Factory reset runtime" (from the Runtime menu), then 
```
from google.colab import drive
drive.mount('/content/drive')
```
and let that run for 3m. Assuming it doesn't terminate, interrupt the cell using cmd/ctrl-m-i (or "Interrupt execution" from the Runtime menu), and in another cell run:
```
!tar cvzf /tmp/b1625.tar.gz /root/.config/Google/DriveFS/Logs
from google.colab import files
files.download('/tmp/b1625.tar.gz')
```
That will download logs to your local computer; from there please upload to https://drive.google.com and share with colaboratory-team@google.com so we can investigate.

**Comment by colaboratory-team** [comment]
@voloddia (assuming the tarball shared was yours): logs show an authorization failure. Are you perhaps trying to use a GSuite account that has Drive disabled domain-wide? Does it work with a vanilla @gmail.com email address?

**Comment by voloddia** [comment]
@colaboratory-team That was my teammate sharing. 
The problem persists with a gmail.com account.

**Comment by Dobby233Liu** [comment]
Also got this problem last night and now.

> Is any output emitted after the token is entered?

For me, neither just emit a new line nor ask for a token again whatsoever, even after repeated tries of pressing the Return key on my IME, like [#1628](https://github.com/googlecolab/colabtools/issues/1628#issuecomment-705287316).
My browser is Chrome on Android, version 86.0.4221.0; IME is Google Pinyin Inputmethod, version 4.5.2-193126728-armeabi-v7a.
Here's the notebook I'm using: https://colab.research.google.com/drive/1vUC7jZxSgwEjWAXebFaB4hdqCZvTY6zg

**Comment by colaboratory-team** [comment]
@voloddia / @kenan-joot / @Avinash1a: what browser/platform are you using? Does the issue reproduce on desktop Chrome in an incognito window?

@Dobby233Liu let's track the enter key issue in #1628 .

**Comment by Avinash1a** [comment]
> 
> 
> @voloddia / @kenan-joot / @Avinash1a: what browser/platform are you using? Does the issue reproduce on desktop Chrome in an incognito window?
> 
> @Dobby233Liu let's track the enter key issue in #1628 .

I tried in chrome and chrome incognito, firefox and firefox incognito .. same issue. And i'm using normal google account. There is no output except running the cell forever. And mine is a new notebook.

**Comment by colaboratory-team** [comment]
@Avinash1a what platform (linux/mac/windows/android/ios) and what version of chrome?

What does running `input()` in a cell on its own, then typing "hello", and hitting the enter/return key, produce?

**Comment by Avinash1a** [comment]
I'm using windows 10.
![image](https://user-images.githubusercontent.com/72508711/95412439-98bfcf00-0946-11eb-99c4-171a83f7d4f5.png)
it is producing nothing

**Comment by colaboratory-team** [comment]
@Avinash1a can you check chrome://version for the specific version of chrome?  Also what sort of keyboard are you using and how is it connected?

**Comment by Avinash1a** [comment]
> 
> 
> We'll need some logs to debug further. Please "Factory reset runtime" (from the Runtime menu), then
> 
> ```
> from google.colab import drive
> drive.mount('/content/drive')
> ```
> 
> and let that run for 3m. Assuming it doesn't terminate, interrupt the cell using cmd/ctrl-m-i (or "Interrupt execution" from the Runtime menu), and in another cell run:
> 
> ```
> !tar cvzf /tmp/b1625.tar.gz /root/.config/Google/DriveFS/Logs
> from google.colab import files
> files.download('/tmp/b1625.tar.gz')
> ```
> 
> That will download logs to your local computer; from there please upload to https://drive.google.com and share with [colaboratory-team@google.com](mailto:colaboratory-team@google.com) so we can investigate.

i tried doing this. https://drive.google.com/file/d/1LCbM15DEs0gGveygtNIrroPPU-logGyi/view?usp=sharing

**Comment by Avinash1a** [comment]
> 
> 
> @Avinash1a can you check chrome://version for the specific version of chrome? Also what sort of keyboard are you using and how is it connected?

this is my chrome version 86.0.4240.75 (Official Build) (64-bit) (cohort: 86_Win_75)
And I'm using lenovo laptop keyboard.

**Comment by voloddia** [comment]
> @voloddia / @kenan-joot / @Avinash1a: what browser/platform are you using? Does the issue reproduce on desktop Chrome in an incognito window?
> 
OS: Windows 7 x64, Browser: Firefox 81.0.1
The problem persists with Chrome incognito mode. 
However, unlike Avinash1a, running `input` does produce output. 

//FWIW, the token input box does appear to be smaller than usual.

**Comment by Avinash1a** [comment]
> 
> 
> > @voloddia / @kenan-joot / @Avinash1a: what browser/platform are you using? Does the issue reproduce on desktop Chrome in an incognito window?
> 
> OS: Windows 7 x64, Browser: Firefox 81.0.1
> The problem persists with Chrome incognito mode.
> However, unlike Avinash1a, running `input` does produce output (in both Firefox and Chrome).
> 
> //FWIW, the token input box does appear to be smaller than usual.

please share screenshot of output of running input() sir.

**Comment by colaboratory-team** [comment]
Enter key issue should be fixed on tab reload.
Please confirm whether issue still reproduces.

**Comment by voloddia** [comment]
It works now. 
Thanks for quick response.

**Comment by Avinash1a** [comment]
Thank You. Problem is solved.

> 
> 
> Enter key issue should be fixed on tab reload.
> Please confirm whether issue still reproduces.
