### ISSUE TITLE
Python 3 GPU backend stuck at "Initializing"

### ISSUE THREAD

**Issue by mancoast** [googlecolab/colabtools#163]
Greetings,

I have been conducting research utilizing colab for a few days now.
Today I am unable to connect to the GPU backend.  
After clicking the connect button, the system hangs and displays "initializing".

When switching to the CPU backend, the system connects as usual.

Please see attached screenshot:
![image](https://user-images.githubusercontent.com/7040493/40195146-a78309bc-59da-11e8-8811-b580c6499f2f.png)

Do you have any suggestions to resume research?

Thanks,
coast

**Comment by blois** [comment]
This can occur if there is a long-running operation happening in the background. Can you try 'Restart runtime...' from within the Runtime menu?

**Comment by mancoast** [comment]
Wow, thanks for the quick response!  I selected "restart runtime" while the system was initializing and then it instantly connected.  @blois thanks!
