### ISSUE TITLE
how to check tpu version  2 or 3 or 4  in colab?

### ISSUE THREAD

**Issue by world2vec** [googlecolab/colabtools#1630]
how to check tpu version  2 or 3 or 4  in colab?

**Comment by colaboratory-team** [comment]
Colab only exposes Cloud TPU v2 hardware, so dynamic detection is not necessary.

**Comment by world2vec** [comment]
Thanks for your quick response.
Hope coab will add v3, since I found v2 is too slow compare to modern hardware.
