### ISSUE TITLE
Repeated crashing after `pip install tensorflowjs==1.2.6`

### ISSUE THREAD

**Issue by josephrocca** [googlecolab/colabtools#1632]
### Describe the current behavior:
If I open a new notebook and then run:
```
!pip install tensorflowjs==1.2.6
```
These errors are displayed amongst the install logs:
```
ERROR: umap-learn 0.4.6 has requirement numpy>=1.17, but you'll have numpy 1.16.4 which is incompatible.
ERROR: nbclient 0.5.0 has requirement jupyter-client>=6.1.5, but you'll have jupyter-client 5.3.5 which is incompatible.
ERROR: google-colab 1.0.0 has requirement six~=1.15.0, but you'll have six 1.11.0 which is incompatible.
ERROR: dm-tree 0.1.5 has requirement six>=1.12.0, but you'll have six 1.11.0 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
```
But then it does seem to successfully finish installing the package and ends with this message:

```
...
Successfully installed h5py-2.8.0 keras-2.2.4 keras-applications-1.0.8 numpy-1.16.4 six-1.11.0 tensorboard-1.14.0 tensorflow-1.14.0 tensorflow-estimator-1.14.0 tensorflow-hub-0.5.0 tensorflowjs-1.2.6
WARNING: The following packages were previously imported in this runtime:
  [numpy,six]
You must restart the runtime in order to use newly installed versions.
```
And so I click the "restart runtime" button, and then the notebook enters a crash loop. It repeatedly says "Your session crashed. Automatically restarting".

Below is a screenshot of the runtime logs from an earlier notebook where I was also installing some other packages. I can't seem to get another snapshot because the crash loop happens too quickly with the new minimal code, and the runtime logs are cleared each time.

![image](https://user-images.githubusercontent.com/1167575/95668431-c4012300-0bbf-11eb-8b46-64feb3ec47ec.png)

### Browser:

Chrome 86

### Link:

https://colab.research.google.com/drive/1dgruKKTjNEqZL2dvFYyV-zylYD20ViQF

Thanks!

**Comment by craigcitro** [comment]
The error you're hitting is because you've installed a version of six that's incompatible with some of the code we package with colab.

* The immediate fix would be to also run `!pip install --upgrade six` after the pip command you ran, but before restarting.
* Another option would be to figure out which package(s) you're installing that request an older version of six, and fix those.
* When py2 support eventually disappears, we'll also remove the `six` dep, which will eliminate this particular issue.

**Comment by josephrocca** [comment]
@craigcitro Thanks! That does solve it. I wonder if a warning could be added to help future newbie users (like me) avoid this sort of problem, and prevent the crash loop?

**Comment by craigcitro** [comment]
In fairness, `pip` is already trying to warn you 😁 :

```
ERROR: google-colab 1.0.0 has requirement six~=1.15.0, but you'll have six 1.11.0 which is incompatible.
```

That said, IWBN to be a little more forceful about situations we know will lead to a crash loop, which I'll mull over.
