### ISSUE TITLE
Python Colab Usage

### ISSUE THREAD

**Issue by YoGrandma** [googlecolab/colabtools#1633]
Bug report for Colab: http://colab.research.google.com/.

I wrote the same code in my Command Prompt and Google Colab...but got the different output...is it joke or something????

In python - 
 `a = "hello\rwoe"`
`print(a)`

The expected output is - `woelo`
But the Google Colab Output is  - `woe`

Is this is joke...or what?

Link of the notebook - https://colab.research.google.com/drive/1JBpPGW1bYBM1T7KJb6O5ZCvSi823d9v_?usp=sharing

**Comment by Jimatwork** [comment]
Why I just started run code, system report exceed quota? Wait for another, same thing happened, I thought was due to disk space, I bought another 100G, didn't help, How to solve this issue?

**Comment by YoGrandma** [comment]
LMAO, tbh...I have migrated to Jupyter...but few of my friends got the same issue - 

for the code -

   `print("Hello\rWor")` 

**Expected output is Worlo; but my friend got Hello Wor in his IDE, I got Wor in Collab, but in CMD and Jupyter the output is Worlo**. I don't understand what's wrong.
