### ISSUE TITLE
Not able to Cancel Colab Pro

### ISSUE THREAD

**Issue by halidziya** [googlecolab/colabtools#1636]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Once I go to settings and Pro tab it shows new subscription button for colab pro. However, I have already subscribed and it is charging monthly. 

- Describe the expected behavior:
It should show cancel button for me instead. 

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
It is not a notebook issue, the overall system could be affected in some time frame due to some update.

**Comment by aakarsh** [comment]
This is amazing, How does one cancel or suspend colab subscription ?

**Comment by halidziya** [comment]
I realized that I used different account for pro. Switching to right account , it was easy

**Comment by aakarsh** [comment]
Hmm, Doesn't seem to work for me am pretty sure I am on the right account, thanks for the quick reply either way.
