### ISSUE TITLE
Google colab: Fail to mount the drive

### ISSUE THREAD

**Issue by EmilyZ233** [googlecolab/colabtools#1638]
After I mount the drive and enter the authorization code, an error jumped out: keyboardinterrupt. 

I don't know how to solve this problem. 

I tried to sign in with different accounts or use different browsers like chrome and firefox, but I have the same error.

<img width="1167" alt="colab error" src="https://user-images.githubusercontent.com/55302565/95940229-6b749480-0e10-11eb-9f86-e0a0e13698d0.png">
(https://colab.research.google.com/drive/1knoix0L5Pbc4HyGsvkXXsl-czBjj_hAt?usp=sharing[](url))

**Comment by colaboratory-team** [comment]
That is consistent with accidentally clicking the "Play" button twice (the first triggers cell execution, the second interrupts it).
Does the problem go away if you don't click the play button and instead use cmd/ctrl-enter to run the cell (when keyboard focus is in it)?

**Comment by EmilyZ233** [comment]
Yes, the error disappeared!
Thank you so much!
