### ISSUE TITLE
Javascript files needed to display output error on google colab

### ISSUE THREAD

**Issue by Kunalzeromile** [googlecolab/colabtools#1639]
[Bug](url
![photo_2020-10-14_10-00-40](https://user-images.githubusercontent.com/72848699/95944472-e71d1400-0e05-11eb-8942-9a3d28fa41e9.jpg)
) report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by cperry-goog** [comment]
Consolidating javascript errors to #4427
