### ISSUE TITLE
Feature request: run cells by index

### ISSUE THREAD

**Issue by amundv** [googlecolab/colabtools#164]
The following does not seem to work in Colab at the moment, but works in Jupyter:
```
%%javascript
Jupyter.notebook.execute_cells([0]) # 0 to run first cell in notebook etc.
```
It would be amazing to run a selection of cells, for example for importing dependencies, running checks and loading utilities whenever a cell is run.

**Comment by blois** [comment]
For security reasons the Javascript in outputs only has limited capabilities and is executed in a fairly controlled iframe.

Examples of what can be done can be found at https://colab.research.google.com/notebooks/snippets/advanced_outputs.ipynb.

**Comment by amundv** [comment]
I'm not familiar enough with javascript to see if any of these will do the job of running one cell from another cell.

I was thinking of this functionality as an alternative to importing an external utils.py -file from the notebook. 

The reason I'd like this is as a workaround to not having an IDE or commandline with vim on the colab VM. Is it possible to log in to the VM from my local machine to have this functionality instead? Any other way of solving this impracticality? I find it hard workflow-wise to do _everything_ in the notebook

**Comment by timeNotTime** [comment]
is this feature came?
