### ISSUE TITLE
All my scripts cancel and I get a red arrow.

### ISSUE THREAD

**Issue by olav3d** [googlecolab/colabtools#1644]
No matter what script I run on the GPU it just stops and turns the run button red with no explanation after just a few minutes. It has been like that for two days now and it does not say anything about running out of GPU quotas or anything. My Google Colab just seems to be completely broken now.

**Comment by Rainboom-Dash** [comment]
Mine runs somewhere between 5 seconds to 75 minutes and then just stops.. a lot of times can be started right back up
But it disconnects the GPU.. not just stops the script
Tabs are staying open and internet shouldn't be an issue
I have colab pro
Just started happening a few days ago

**Comment by olav3d** [comment]
Same, I have a Colab Pro subscription too, has not worked for 3 days now...

**Comment by chandangm** [comment]
Same, i get disconnected from the instance exactly after 2 hours, and i don't see any error message or anything useful in the runtime logs.

**Comment by selvaganesh-M** [comment]
I have the same issue too. For the past few days, all GPU requiring scripts stop within 5 mins, and I have a colab pro subscription.

**Comment by olav3d** [comment]
Still no fix, canceled my pro subscription now.

**Comment by selvaganesh-M** [comment]
the same issue happened on another account where I used colab pro. thats 2 accounts that have become useless for me now

**Comment by waxb** [comment]
Same issue, Pro subscription
