### ISSUE TITLE
colab session doesn't start

### ISSUE THREAD

**Issue by AHMEDHAMID123** [googlecolab/colabtools#1645]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I have been trying to start a notebook using google colab but the session never connect and it's stuck at the allocation phase. I tried to use different browsers and different google accounts,  but the problem still the same and it's is stuck at the allocation phase. 
- Describe the expected behavior:
it suppose to start and the cells should run but it's stuck at the allocating phase and can't run any code
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome and Firefox
- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by olav3d** [comment]
Same problem for me, Google Colab is useless for GPU usage at this point, have not been able to use it for 5 days and I have a pro subscription. Had to cancel it today.
