### ISSUE TITLE
Unzip bad zipfile offset

### ISSUE THREAD

**Issue by quinnbee** [googlecolab/colabtools#1647]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: Can unzip file only once in a day. It gives a bad zipfile offset when I try unzipping another folder or same folder in the same day(another session).

- Describe the expected behavior: Should unzip files always

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/drive/17G7orqwECmZd-xsusLAz3Y71m8WXrbXO?usp=sharing

**Comment by colaboratory-team** [comment]
Assuming the zip file is the >22G dataset from Kaggle, this is likely a dup of #1607, which see for workarounds.
