### ISSUE TITLE
Unable to access all the files after mounting drive in Google Colab Pro.

### ISSUE THREAD

**Issue by gm039** [googlecolab/colabtools#1650]
I am trying to mount shared google drive in my colab pro environment and its mounting correctly. I can also see all the files. unfortunately, when I try to again access them, most become unavailable. I am able to see only limited files on the mounted folder using %ls command. See attached image.

It used to work well before. Not sure what's the reason. I am using google chrome (Version 86.0.4240.75). Can you please help?

![drive_issue](https://user-images.githubusercontent.com/50217085/96596039-48d3f700-12ba-11eb-8cd5-4b1c0347cd5d.PNG)

**Comment by colaboratory-team** [comment]
This is #1494, whose cause is still mysterious. If possible, can you share the drive with colaboratory-team@google.com and brian@demodemo.org? 
Can you describe the sharing situation: i.e. are you the owner or a manager or a viewer, how many people are in each category, and do people in all categories observe the disappearances, or only some (if some, which?)?
Please reply in #1494 and not here to centralize data collection.
