### ISSUE TITLE
Runtime always disconnects after just a few minutes on a pro subscription

### ISSUE THREAD

**Issue by olav3d** [googlecolab/colabtools#1651]
I has now been 5 days where all my scripts in colab pro that used to run fine disconnects after just a few minutes running on a GPU, still no answers from customer service. Is this what I pay for? When will this be fixed?

**Comment by mrkdian** [comment]
same. I usually only use it a few times in a month, but I still triggered the restriction

**Comment by vothaiduong14** [comment]
I also encounter the same problem. Keep disconnected within 1 hour even though I am on Pro subscription. This is such a rip off.
