### ISSUE TITLE
cannot copy and paste, or use keyboard shortcuts such as cmd+a, cmd+c, cmd+v in an iPad pro

### ISSUE THREAD

**Issue by atmosinf** [googlecolab/colabtools#1665]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- I cannot copy and paste or use keyboard shortcuts such as cmd+a, cmd+c or cmd+v. When i try to paste something, what was copied from some other application is pasted

- Describe the expected behavior:

- Tried on Chrome and Safari

**Comment by A-pixel101** [comment]
I cant copy and pate the authorization code from google drive 


I do not know what should I do

 please help

**Comment by jmbenedetto** [comment]
Same here.

**Comment by tolgadiz** [comment]
Same
