### ISSUE TITLE
We all Gsuite/Domain user can not log-in Colab

### ISSUE THREAD

**Issue by ghostjoy** [googlecolab/colabtools#1666]
1. Our user (senior high school student and teacher )in Gsuite education Domain (@rwm.ks.edu.tw) can't login colab, its always occur a login -loop.
2. I (Gsuite Admin) checked permission setting is all right and granted (by google support team)

3. please check maybe our user account is  a kid account ? so we can't use  colab.

**Comment by colaboratory-team** [comment]
Please see https://github.com/googlecolab/colabtools/issues/1065#issuecomment-605486998.
