### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by nairouz** [googlecolab/colabtools#1669]
I have a notebook file and several .py files which I can import to my notebook.
Every time I restart my notebook it does not take into consideration the latest update of my .py files.

**Comment by abnormalstudent** [comment]
I got almost the same issue, - when I modify some .py file, Colab doesn't recognize any changes in this file (even after saving it, for sure), and from my experience the only way to fix this issue is to restart the hosted runtime, which is probably not a proper way to do it.

**Comment by abnormalstudent** [comment]
> I have a notebook file and several .py files which I can import to my notebook.
> Every time I restart my notebook it does not take into consideration the latest update of my .py files.

Think I figured this out, - just use 

`import importlib`
 `importlib.reload(module_name)`

By doing so, colab will figure out changes in module_name.py file w/o restart of environment. 
Hope it helps.
