### ISSUE TITLE
changes in the python file have not effect ...

### ISSUE THREAD

**Issue by markub3327** [googlecolab/colabtools#1677]
Hello,
&nbsp;  my changes in the python file have not effect. Please see the screenshot, that I change the error in the source file, but the change did not affect the runtime.

<img width="1552" alt="Snímka obrazovky 2020-10-30 o 22 05 35" src="https://user-images.githubusercontent.com/16693449/97757628-69dbe980-1afd-11eb-86ed-a0a669fd8261.png">

Thanks.

**Comment by stephengmatthews** [comment]
The runtime would need to be restarted to reload the changes, or use [`importlib.reload()`](https://docs.python.org/3/library/importlib.html#importlib.reload) without restarting the runtime.

**Comment by markub3327** [comment]
Thanks, 'Restart runtime' is working and 'importlib.reload()' works too.
