### ISSUE TITLE
authenticate_user() Error code 500

### ISSUE THREAD

**Issue by jaidmin** [googlecolab/colabtools#168]
Hi, I cannot authenticate using the authenticate_user method anymore. It used to work, but now if I click the link I get a 500 error on a google site.

These people seem to have the same issue:
https://github.com/gsuitedevs/PyDrive/issues/132

Any ideas?

EDIT:

I could pin it down to `gcloud auth login` returning a link which leads to a 500 Error code. I tried updating, that didnt help.

Cheers, 
Johannes

**Comment by craigcitro** [comment]
Can you provide any more details about the failure? (This isn't a widespread problem AFAICT.)

* does it repro in an incognito window?
* are there any errors in the chrome JS console?
* is there any more information in the error message?

**Comment by jaidmin** [comment]
Hi, 

the issue is resolved when using another browser (where I am not logged in) or using incognito mode. This also seems to help other users experiencing the same issue. 

https://github.com/gsuitedevs/PyDrive/issues/132#issuecomment-392031235

I can only assume that it must be some problem with cookies or something, thanks anyways.

Cheers, Johannes

**Comment by craigcitro** [comment]
Yes, that sounds like something to do with cookie settings in your browser (either need to clear cookies or cookies are disabled).
