### ISSUE TITLE
Cannot connect to GPU backend

### ISSUE THREAD

**Issue by lethanh26061998** [googlecolab/colabtools#1681]
- I was running gpu google colab then this message: "Cannot connect to GPU backend" appeared.
I tried to reconnect but failed.
What do I need to do now to be able to use gpu colab?
- Describe: "You cannot currently connect to a GPU due to usage limits in Colab"
- The web browser I am using: Chrome

**Comment by matheus176** [comment]
same for me, but the problem is persisting for me and my friends for days now, we even tried with different g-mail accounts but after 20-30 minutes of use i´m disconnected and i cant use gpu´s
