### ISSUE TITLE
using DataFrame.style loses all default table styling

### ISSUE THREAD

**Issue by wideglide** [googlecolab/colabtools#1687]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

Using the [DataFrame.style](https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html) in anyway completely removes all default table styling for dataframes.

See also this [stackoverflow question](https://stackoverflow.com/questions/62255818/pandas-style-doesnt-work-with-google-colab)

- Describe the expected behavior:

Using `dataframe.style.apply` and/or `dataframe.style.applymap` should add to the existing style, not remove all existing style.  This is the default behavior in Jupyter.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1iKoBlatiVWDV8qlYVwawh4W5apfv8DX-?usp=sharing

**Comment by mrkobk** [comment]
Id love this to be resolved as well

**Comment by miiguelkf** [comment]
Up

**Comment by blois** [comment]
Colab only applies the 'dataframe' styling to HTML table elements with the `dataframe` classname. The regular dataframe [adds the dataframe class](https://github.com/pandas-dev/pandas/blob/059c8bac51e47d6eaaa3e36d6a293a22312925e6/pandas/io/formats/html.py#L225) but the styler one [does not](https://github.com/pandas-dev/pandas/blob/83278721b5bc548c3c614242a828ca73e2530cc9/pandas/io/formats/templates/html.tpl#L28).

The best approach is probably to explicitly add the `dataframe` class:

```python
df.style.highlight_max().set_table_attributes('class="dataframe"')
```

This may possibly be addressed as part of https://github.com/pandas-dev/pandas/issues/41693?

**Comment by attack68** [comment]
Is this still relevant? I ran pandas styler in colab recently and it no longer seems to lose the formatting?

**Comment by craigcitro** [comment]
Indeed, this is now fixed, and we forgot to close this issue. :)
