### ISSUE TITLE
Runtime dies everytime Keras code is run

### ISSUE THREAD

**Issue by mks2103** [googlecolab/colabtools#169]
Came through an issue when trying to train my deep learning model using keras. There were no issues till yesterday. Now whenever the code is run and before it reaches to train model line of code (model.fit()), always the message "Runtime Dies" is shown.
 i. Previously I tried with 4 GB of dataset, it was working perfect
ii. Tried with 8 GB of dataset and runtime kept on restaring.
iii. Tried with 4 GB and 5 GB dataset and the error 'runtime dies' keep on prompting.

ipynb link: https://drive.google.com/open?id=15pPdngd8Eeq-dwpK0LVfZNNOyyG75lk2

**Comment by mks2103** [comment]
When tried to run the following code, it's shown that only 532 MB of GPU-RAM is free to process further.

#How much GPU is allocated

!ln -sf /opt/bin/nvidia-smi /usr/bin/nvidia-smi
!pip install gputil
!pip install psutil
!pip install humanize
import psutil
import humanize
import os
import GPUtil as GPU
GPUs = GPU.getGPUs()

gpu = GPUs[0]
def printm():
 process = psutil.Process(os.getpid())
 print("Gen RAM Free: " + humanize.naturalsize( psutil.virtual_memory().available ), " I Proc size: " + humanize.naturalsize( process.memory_info().rss))
 print("GPU RAM Free: {0:.0f}MB | Used: {1:.0f}MB | Util {2:3.0f}% | Total {3:.0f}MB".format(gpu.memoryFree, gpu.memoryUsed, gpu.memoryUtil*100, gpu.memoryTotal))
printm()


![image](https://user-images.githubusercontent.com/39581733/40470828-4a23a7cc-5f52-11e8-8113-62b7784501ce.png)

Can this be the reason behind the issue?

**Comment by abeyn** [comment]
I have the same problem.
I have used my notebook for a few months to lern neural networks with memory 8Gb. But now I can use only 5Gb. May be this problem connected with tensorflow update to version 1.8.0. I can't downgrade to 1.7.0

**Comment by youssefElPrns** [comment]
Have anyone solved this problem yet.
or at least managed to downgrade tensorflow

**Comment by colaboratory-team** [comment]
The notebook in the first comment isn't shared, unfortunately.

For folks experiencing issues of this type, I'd recommend asking a question on a more general-purpose forum like StackOverflow to attract the attention of domain experts. Please do include a self-contained notebook that reproduces the problem.
