### ISSUE TITLE
Insanely slow data reading from google drive

### ISSUE THREAD

**Issue by dazzle-me** [googlecolab/colabtools#1691]
- Describe the current behavior: 

![image](https://user-images.githubusercontent.com/57013219/98342578-a9389780-2021-11eb-884b-746546f328eb.png)

I'm trying to read data as pairs of .png/.pkl files

The problem is that sometimes speed of reading data is around 300 samples per second (it's the expected one, I almost always have this speed in colab and even on local machine with HDD as well), but sometimes it falls down to 1 sample per second, which leads to 300x slowdown, which is of course not an expected behaviour.

To further readers - I think it is about caching, I found a little trick how I can prevent such slow loading. I just had to delete whole unpacked dataset, and then just apply `!unzip dataset.zip`, after that it has been cached and it started to load pretty fast!

Browser : Chrome, ver. 86.0.4240.183, 64-bit

No notebook, though, because it uses a lot of in-disk dependicies, so you won't be able to replicate same mistake.

But if you really want to improve this part of your service, here is how you can try to replicate it:

First of all, suppose notebook localted at "content/drive/My Drive/some_folder_name", 
and dataset located at "content/drive/My Drive/some_folder_name/dataset"

Then for all images pathes and pkl pathes we read image via `cv2.imread` and read pickle via 

`with open(pickle_path, 'rb') as file:`
`____pickle_data = pickle.load(file)` 

Dataset architecture : 
![image](https://user-images.githubusercontent.com/57013219/98346648-5530b180-2027-11eb-8a16-5e29657633d8.png)

Torch dataset class :
![image](https://user-images.githubusercontent.com/57013219/98347342-59a99a00-2028-11eb-98c2-8b08c8f866f5.png)

Create loader function : 
![image](https://user-images.githubusercontent.com/57013219/98347479-7f36a380-2028-11eb-91f3-9eaab404389f.png)

**Comment by stephengmatthews** [comment]
Have you tried copying the data to local storage instead of reading the data from google drive? If not, it's worth trying this by copying your data to /tmp at the start of every session before running your models. Something like this:
```
! cp -r /content/drive/My Drive/some_folder_name/dataset /tmp/dataset
```

**Comment by abnormalstudent** [comment]
> Have you tried copying the data to local storage instead of reading the data from google drive? If not, it's worth trying this by copying your data to /tmp at the start of every session before running your models. Something like this:
> 
> ```
> ! cp -r /content/drive/My Drive/some_folder_name/dataset /tmp/dataset
> ```

I tried that, but no luck : it is still a lot slower than the hack described above.

**Comment by dazzle-me** [comment]
Stopped using Colab service.

**Comment by jrl-se** [comment]
Has this issue been resolved?

I have a 300 GB dataset, which I uploaded to Google drive after paying the 2 TB space subscription. I am mounting my Drive to Colab Pro and reading the images directly from Google Drive since the dataset is too big the fit the disk space provided by Colab Pro.

Loading the dataset in batches that fit memory takes about 40 minutes, which is nearly 15 times slower than with my laptop...

**Comment by dazzle-me** [comment]
I think that you have to copy files from google drive to a VM you're assigned when using Colab, but I'm not sure if it's fast to copy 300Gb of data to VM in each new session (though, Colab internet is very fast, if VM has appropriate amount of disk space maybe you can do it)

This way, VM won't have to read files from the google drive (somewhere from the internet), but instead it'll read data from it's local storage, it'll be much faster.

Haven't tried it though

**Comment by josuerocha** [comment]
Thanks for your answer.

Yes, I have considered copying the dataset to Colab's VM. However, as I mentioned in my answer, the dataset does not fit the disk storage space provided by Colab Pro (around 150 GB).

**Comment by josuerocha** [comment]
I have a 300 GB dataset, which I uploaded to Google drive after paying the 2 TB space subscription. I am mounting my Drive to Colab Pro and reading the images directly from Google Drive since the dataset is too big the fit the disk space provided by Colab Pro.

Loading the dataset in batches that fit memory takes about 40 minutes, which is nearly 15 times slower than with my laptop...
