### ISSUE TITLE
Error Unable to load Colaboratory.

### ISSUE THREAD

**Issue by sumit1o** [googlecolab/colabtools#1693]
- Describe the current behavior:
getting following error: 
---------------------------------------------------------------------------------
Error
Unable to load Colaboratory.

The object already contains the key "4KKw5onT5ZwRn"
Oc@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20201105-085602-RC00_340833107:96:139
h.addChildAt@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20201105-085602-RC00_340833107:365:391
h.addChild@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20201105-085602-RC00_340833107:364:31
i6@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20201105-085602-RC00_340833107:4494:157
$5.prototype.enterDocument@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20201105-085602-RC00_340833107:4440:138
h.enterDocument@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20201105-085602-RC00_340833107:4964:163
Nn@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20201105-085602-RC00_340833107:360:374
h.render@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20201105-085602-RC00_340833107:360:93
qla/<@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20201105-085602-RC00_340833107:2188:174
Fa@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20201105-085602-RC00_340833107:19:336
Da.prototype.next_@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20201105-085602-RC00_340833107:17:474
Ha/this.next@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20201105-085602-RC00_340833107:20:206
b@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20201105-085602-RC00_340833107:20:465
---------------------------------------------------------------------------------

- Describe the expected behavior:
co-laboratory should load properly. 

- The web browser you are using (Chrome, Firefox, Safari, etc.):
firefox81.0 (64bit)

**Comment by ChristianRLynn** [comment]
I am having the same problem uploading a GitHub file

**Comment by colaboratory-team** [comment]
Sorry for the trouble, and thanks for the reports. Can you share a notebook that reproduces the issue you observe?

**Comment by blois** [comment]
I have a repro

**Comment by ChristianRLynn** [comment]
Do you want me to send the file as an attachment. Mine is coming from a GitHub repo.
If you search, it is public:
ChristianRLynn/DataSets

The notebook is Notebooks_V5.ipynb 

I have been working in Git to try and revert my way around this issue (it wasn’t happening before).

~Christian R. Lynn

**Comment by sumit1o** [comment]
I've resolved the issue in my Jupyter file. 

It's code block id issue on Google colab. While same file running on local pc's Jupyter Notebook.

If your local Jupyter file have duplicate I'd, and you upload it on your colab then your colab will do unexpected behaviour and you can't do anything with that file. 

Google colab should be resolve it.

**Comment by blois** [comment]
Yes, a fix is in the works.

**Comment by blois** [comment]
Also a workaround in the meantime- if you see an error along the lines of `The object already contains the key "4KKw5onT5ZwRn"`, then you should be able to download your notebook and look for something like:

```json
      "metadata": {
        "id": "4KKw5onT5ZwRn"
      },
```

Removing the `id` key and value should be sufficient.

**Comment by sumit1o** [comment]
No need to remove id, you can change id value only and save it local then upload on colab .
