### ISSUE TITLE
Value Regarding Mathematics(Cos90degree value)

### ISSUE THREAD

**Issue by adi122190** [googlecolab/colabtools#1697]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by adi122190** [comment]
The value Of cos90 is coming 6.123233995736766e-17 which is wrong and the correct value is 0

**Comment by Kreijstal** [comment]
that has absolutely nothing to do with google colab, it's python itself. and that's because you're using floating point arithmetic.

**Comment by adi122190** [comment]
Plss Give Solution then

**Comment by Kreijstal** [comment]
There's no solution.

**Comment by adi122190** [comment]
😑😶😶😑
