### ISSUE TITLE
Feature request: hidden cells don't open when down-arrowing over them

### ISSUE THREAD

**Issue by amundv** [googlecolab/colabtools#171]
Collapsed sections currently expand when down-arrowing over them. I would love for them to remain closed, to avoid having to use the mouse to skip them. This is currently the behavior of cells with a "form", where its possible to "hide" the code and only show the form.

Perhaps an alternative behavior could be opening the section with right-arrow?

**Comment by colaboratory-team** [comment]
b/128367640

**Comment by blois** [comment]
This has been fixed.
