### ISSUE TITLE
Access to Docs API through default Credentials.

### ISSUE THREAD

**Issue by kindly** [googlecolab/colabtools#1711]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

Not able to to access [Google Docs API v1](https://developers.google.com/docs/api) through default colab credentials.

- Describe the expected behavior:
Would expect it to behave the same as [Drive API](https://colab.research.google.com/notebooks/io.ipynb#scrollTo=jRQ5_yMcqJiV)

i.e would expect the following to work
```python
from google.colab import auth
auth.authenticate_user()

from googleapiclient.discovery import build

docs_service = build('docs', 'v1')
documents=docs_service.documents()
documents.create(body={"title":'test'}).execute()
```
I think this should as easy as enabling the Docs API to the Google Cloud SDK project.  I do not think this is giving away anymore permissions than currently as the Drive API is already enabled.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Does not work in any.

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/drive/1mxi8FTLnIw1UxYZp57uAwM0dOUH_8KiW#scrollTo=v_vKXwsrgJ4s

**Comment by craigcitro** [comment]
Fixed!
