### ISSUE TITLE
Missing tf summary files

### ISSUE THREAD

**Issue by RenHao116** [googlecolab/colabtools#1713]
tf version: 1.x

I'm using colab pro to run a code in my google drive. The code writes tf summary and model checkpoints to my google drive. 

If the code finishes executing or gets terminated by hand, the tf summary files are stored correctly. However, if the session is killed by the server, sometimes I would lose my tf summary files. But all the saved model are stored correctly.  If I download the summary file during training, it doesn't contain the log information either. 

Sometimes, even this happens, my tensorboard magic, however, can still display expected information.

My guess is that since I'm writing tf summary at every iteration, all my summary is actually in cache. When the session gets killed by the server, the cache doesn't get propagated to my drive. 

Sorry for can't really share my code at the moment and it would be a mess to set it up anyway. Would be really appreciated if anyone else with the same problem can help out.

**Comment by metrizable** [comment]
Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem including deprecation of TensorFlow 1.x and upgrade to TensorFlow 2.12.0 since then, if you are still experiencing the issue, please file a new issue and provide a minimal reproducible notebook.
