### ISSUE TITLE
Feature Request: keep files open when disconnecting

### ISSUE THREAD

**Issue by bycn** [googlecolab/colabtools#1716]
- Describe the current behavior:
When the runtime disconnects, all files that are open in the editor (i.e. editing a python file in the file system) are closed. 
- Describe the expected behavior:
Keep the files open in the editor, only invalidating it if path has changed. 
- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

**Comment by corrieann** [comment]
Thanks for the report!  This took us a while to fix, but has now been fixed.
