### ISSUE TITLE
Feature request: allow editing of non python files as text

### ISSUE THREAD

**Issue by bycn** [googlecolab/colabtools#1717]
- Describe the current behavior:
Cannot open a cpp file in the local filesystem in the editor for editing.
- Describe the expected behavior:
If a file is not recognized (ie not a .py file), allow for opening as text to edit the file. 
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

**Comment by blois** [comment]
Thanks for the request! .cpp files should now be editable.

**Comment by bycn** [comment]
Can this be done also for related files? .h etc

**Comment by blois** [comment]
Header files should be editable as well, though the syntax highlighting right now is not correct. I'll get that tweaked.
