### ISSUE TITLE
Can't change tcmalloc llimit 

### ISSUE THREAD

**Issue by vkorf** [googlecolab/colabtools#1718]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: 
I switched to colab pro.
Notebook runtime had 27.4 gigabytes of available RAM.(high-RAM runtime!)
Got tcmalloc error, which refers to 12gb limit.

- Describe the expected behavior:
Change limit and train model(stylegan)

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

Nov 16, 2020, 10:20:09 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
-- | -- | --
Nov 16, 2020, 10:20:04 PM | WARNING | tcmalloc: large alloc 12884901888 bytes == 0x7f8880000000 @ 0x7f94b4551001 0x7f94aba49765 0x7f94abaadbb0 0x7f94abaafa4f 0x7f94abb46048 0x50a4a5 0x50cc96 0x507be4 0x509900 0x50a2fd 0x50beb4 0x507be4 0x509900 0x50a2fd 0x50cc96 0x507be4 0x588e5c 0x59fd0e 0x50d256 0x5095c8 0x50a2fd 0x50beb4 0x5095c8 0x50a2fd 0x50beb4 0x507be4 0x588e5c 0x59fd0e 0x50d256 0x507be4 0x509900

**Comment by craigcitro** [comment]
The log message includes the amount of memory allocated in a single step, not the total RAM. You're still hitting an OOM with the larger RAM limit.

**Comment by vasilykorf-wk** [comment]
Is there any way to change this limit for a single step? looks like known issue: https://github.com/googlecolab/colabtools/issues?q=is%3Aissue+is%3Aopen+tcmalloc

**Comment by vkorf** [comment]
@craigcitro 
is there any way to change this limit for a single step? looks like a known issue: https://github.com/googlecolab/colabtools/issues?q=tcmalloc+
