### ISSUE TITLE
Why Colab Pro is using all my local RAM memory and processors?

### ISSUE THREAD

**Issue by Ceceu** [googlecolab/colabtools#1719]
When opening Google Colab Pro, the use of my local processors and RAM jump to 100% due to the chrome render process.

**Comment by craigcitro** [comment]
* Can you confirm whether this happens in an incognito window?
* Does this happen on all notebooks, or just some? In particular, does it happen on https://colab.research.google.com/notebooks/intro.ipynb in an incognito window?

**Comment by Ceceu** [comment]
This started to happen with all the notebooks I have, which I had no problem with before.
However, it doesn't seem to happen when I'm in the incognito window.

**Comment by craigcitro** [comment]
If it doesn't happen in incognito, it almost surely means an extension is causing trouble. I'd try disabling extensions to see if you can find the one causing trouble.

I'm going to close for now, but please do add a comment with the extension causing the trouble once you find it.
