### ISSUE TITLE
Showing no error when i am using undeclared variable @ variable name tbl in below code

### ISSUE THREAD

**Issue by ghost** [googlecolab/colabtools#172]
generate_data()
num_epochs=100
state_size=4
truncated_backpropogate_length=15
total_series_length=50000
batch_size=5
num_of_batches=total_series_length//batch_size//tbl
num_classes=1

**Comment by colaboratory-team** [comment]
Sorry, we're not able to diagnose issues with libraries used within Colab. I'd recommend asking a question on a more general-purpose forum like StackOverflow to attract the attention of domain experts.
