### ISSUE TITLE
R Stan no longer works; requires V8

### ISSUE THREAD

**Issue by JSenta** [googlecolab/colabtools#1723]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
When running an R notebook on Colab, the package 'rstan' can no longer be installed because of its new mandatory dependence on 'V8'. Colab doesn't allow the package V8 to install.

**Comment by craigcitro** [comment]
Can you include a minimal repro notebook with what you tried any error(s) you encountered?

**Comment by JSenta** [comment]
Hi, thanks for the response. I followed the steps outlined in this guide to using RStan on Google Colab:
https://colab.research.google.com/drive/1BYnnbqeyZAlYnxR9IHC8tpW07EpDeyKR

When I try to install rstan in my notebook, I receive the following error:
![image](https://user-images.githubusercontent.com/41653809/99597892-8c02b200-29ad-11eb-9ecc-92517d7dd55c.png)

I see there may have been other instances of this since rstan made V8 a required dependency; (E.g., https://github.com/stan-dev/rstan/issues/790)

Thanks for any insight you can provide!

(Also, for reference, the original source for the notebook I started with is here):
https://discourse.mc-stan.org/t/r-jupyter-notebook-rstan-on-google-colab/6101 (links to next notebook shown below)
https://colab.research.google.com/drive/1xj_aYLBBPX2oSQ1I4xp5_YZiVhhpC1Ke (links to the updated starting notebook I used)

**Comment by craigcitro** [comment]
If I'm reading https://packages.ubuntu.com/search?keywords=libnode64 correctly, it looks like this requires a newer version of ubuntu, which means there's no easy fix right now. 😞

**Comment by JSenta** [comment]
Ah, I see! Ok, thanks for looking into that. Is there any estimated timeline on that new ubuntu version being incorporated into Colab?

**Comment by craigcitro** [comment]
"hopefully soon" 🤞

**Comment by JSenta** [comment]
Ok, thanks!

**Comment by andrjohns** [comment]
The V8 installation issue is caused by the package needing the V8 library installed on the system, you can either install this via R using:
```
system("apt-get install -y libv8-dev")
install.packages("V8")
```

Or the V8 package has the option to download a static version of the library to use when installing, you can do this via:
```
Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1)
install.packages("V8")
```

**Comment by craigcitro** [comment]
Thanks @andrjohns!

@JSenta does that get you unblocked?

**Comment by JSenta** [comment]
@andrjohns @craigcitro Thanks so much, the static version install did the trick!!
