### ISSUE TITLE
Colab pro and Google Drive storage volume inconsistency

### ISSUE THREAD

**Issue by vkorf** [googlecolab/colabtools#1724]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior: Different colab pro and g drive storage volume.

- Describe the expected behavior: Align volumes
![colab pro](https://user-images.githubusercontent.com/10270346/99601279-55806380-29bc-11eb-9049-ee1e244d33d2.png)
![google drive](https://user-images.githubusercontent.com/10270346/99601280-5618fa00-29bc-11eb-8b90-54f9214552b1.png)

**Comment by Smankusors** [comment]
no, this is correct. They are different storage volume. Your gdrive volume is not same as your Colab Pro environment.

Furthermore, when you factory reset runtime, you will lost all files except one that saved on your gdrive mounted folder.

**Comment by vkorf** [comment]
@Smankusors true, but if I mount gdrive to colab notebook, the gdrive memory will be totally consumed by colab while saving some models' snapshot. is this an expected behavior?

**Comment by Smankusors** [comment]
> @Smankusors true, but if I mount gdrive to colab notebook, the gdrive memory will be totally consumed by colab while saving some models' snapshot. is this an expected behavior?

if you save the model snapshots in your gdrive folder, then yes it will consume your gdrive space instead
