### ISSUE TITLE
ENH: Colaboratory icon in my Google Apps Tab

### ISSUE THREAD

**Issue by westurner** [googlecolab/colabtools#1725]
How can I add a Colaboratory icon in my Google Apps Tab; such as here:

<img width="398" alt="Screen Shot 2020-11-18 at 9 22 16 PM" src="https://user-images.githubusercontent.com/50891/99613474-9e004700-29e5-11eb-8a0e-2c4e6d073492.png">

**Comment by blois** [comment]
I believe this is governed by Google Cloud's Google Workspace Marketplace SDK, looks like we need to generate 48x48 & 96x96 icons as well.
