### ISSUE TITLE
[Feature Request] Custom docker containers for colab environment

### ISSUE THREAD

**Issue by TheTrueCoder** [googlecolab/colabtools#1727]
Feature request for Colab: http://colab.research.google.com/.

Problem
-
When doing work on projects with a lot of special dependencies, it can take a long time to install/build everything every time I want to do work on it.

Solution
-
Give us the ability to use a custom docker container as the google colab environment, so that all the dependencies are preinstalled and you can get to working on your software straight away without worrying about the default packages becoming incompatible.

**Comment by forkbabu** [comment]
@TheTrueCoder bro same

**Comment by adRn-s** [comment]
Apparently this (great) idea won't bloom. See #299
