### ISSUE TITLE
Missing Code: Plot Is Not Displayed -- Add `plt.show()`

### ISSUE THREAD

**Issue by Th3-M3nt0r** [googlecolab/colabtools#1728]
Bug report for Colab: http://colab.research.google.com/.
For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- **Current Behavior**: There is a missing statement due to which, the plot is not being displayed, when code is copied and run on user system. This is current code snippet:
```
import matplotlib.pyplot as plt
plt.xlabel('Epoch Number')
plt.ylabel("Loss Magnitude")
plt.plot(history.history['loss'])
```

- **Solution (expected behavior)**: To show the plot, add `plt.show()` in the end of the above code snippet as follows:
```
import matplotlib.pyplot as plt
plt.xlabel('Epoch Number')
plt.ylabel("Loss Magnitude")
plt.plot(history.history['loss'])
plt.show()
```

- Web Browser: _Chrome_
- Operating System: _Windows_
- Link: [https://colab.research.google.com/github/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l02c01_celsius_to_fahrenheit.ipynb#scrollTo=0-QsNCLD4MJZ](https://colab.research.google.com/github/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l02c01_celsius_to_fahrenheit.ipynb#scrollTo=0-QsNCLD4MJZ)

**Comment by craigcitro** [comment]
You should report this on the repo where you found that notebook (tensorflow/examples).
