### ISSUE TITLE
Can't cd into a directory

### ISSUE THREAD

**Issue by BitYog** [googlecolab/colabtools#173]
Google Colab is a really useful tool and most of my work is done there.
But I regularly face a problem with using the terminal.
I can't cd into a directory, and this really gets in the way of my work. 

For example:
``
!cd data\
``
But when I try to ls or pwd I get:
``
!pwd  
/content [Output]
``

This is really quite infuriating. Hope you can resolve this.

**Comment by PatinaHo** [comment]
Google Colab inherits from jupyter command, in jypyter if you want to change the current working directory you use the built-in magic command `%cd`.
You can refer to the document here: http://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-cd

**Comment by BitYog** [comment]
I didn't know that. Thanks! This is super helpful!

**Comment by craigcitro** [comment]
The thing to understand here is that each command of the form `!cmd arg1 ...` creates a **new** subshell to execute in. So if you do

    !cd /foo
    !ls

those are each in a *separate* subshell, leading to confusion. As @PatinaHo mentioned, you can use `%cd`, or you can also just use [`os.chdir`](https://docs.python.org/3/library/os.html#os.chdir).

**Comment by KANYIMATRIX** [comment]
very helpful

**Comment by KJYong666** [comment]
it says [Errno 2] No such file or directory: how?
