### ISSUE TITLE
[TPU] Your session crashed for an unknown reason

### ISSUE THREAD

**Issue by Smankusors** [googlecolab/colabtools#1730]
### Intro

So I got these short code below :

```
import tensorflow as tf
import numpy as np
try:
  tpu = tf.distribute.cluster_resolver.TPUClusterResolver()  # TPU detection
  print('Running on TPU ', tpu.cluster_spec().as_dict()['worker'])
  tf.config.experimental_connect_to_cluster(tpu)
  tf.tpu.experimental.initialize_tpu_system(tpu)
  strategy = tf.distribute.TPUStrategy(tpu)
except ValueError:
  print('WARNING: TPU not available!')
  strategy = tf.distribute.get_strategy()
data = np.random.randint(low=0, high=255, size=(11000, 170, 400, 3), dtype="uint8")
data = tf.convert_to_tensor(data, dtype="uint8")
```

It's just small code to generate small random dataset and convert it to tensor. This dataset I think consumed max 6GB of RAM. I tested on the CPU runtime and it's only consumed 3GB of RAM.

### Current behavior:

The session crashed for an unknown reason. The runtime logs suggest that maybe it is run out of memory :

```
Nov 22, 2020, 12:57:44 PM | WARNING | E1122 05:57:44.886857853 2071 proto_buffer_writer.h:83] assertion failed: byte_count_ < total_size_
Nov 22, 2020, 12:57:43 PM | WARNING | tcmalloc: large alloc 2244001792 bytes == 0x8f3e2000 @ 0x7f329d95c887 0x7f329c252c29 0x7f329c252ff2 0x7f329c25365e 0x7f325f275e2c 0x7f3263a5a0fb 0x7f3263a5e303 0x7f3263a850d6 0x7f3263a8562d 0x7f3263a44ee3 0x7f3263a3ec24 0x7f3263697044 0x7f3263609fb6 0x7f326360ab2e 0x5515c1 0x5a9dac 0x50a433 0x50beb4 0x507be4 0x509900 0x50a2fd 0x50beb4 0x5095c8 0x50a2fd 0x50beb4 0x507be4 0x509900 0x50a2fd 0x50cc96 0x507be4 0x509900
Nov 22, 2020, 12:57:35 PM | WARNING | tcmalloc: large alloc 2244001792 bytes == 0x9680000 @ 0x7f329d95a1e7 0x7f3294e545e1 0x7f3294eb8c78 0x7f3294eb8f37 0x7f3294f50f28 0x566f73 0x7f328f14c2e8 0x7f328f82cb42 0x50a4a5 0x50cc96 0x507be4 0x5161c5 0x50a12f 0x50beb4 0x507be4 0x509900 0x50a2fd 0x50beb4 0x507be4 0x509900 0x50a2fd 0x50cc96 0x507be4 0x508ec2 0x594a01 0x59fd0e 0x50d256 0x507be4 0x509900 0x50a2fd 0x50cc96
```

However, if I selected CPU or GPU runtime, the code works fine.

### Expected behavior

If it's really run out of memory, should not it show "Your session crashed after using all available RAM"? But it should not run out of memory because it's not that big. Unless on the background, somehow the `uint8` converted to `float32`....

~Heck, I think at least before around Nov 17, 2020 13:29 UTC , this code still works fine on TPU runtime. Last time I think this code works around Nov 17, 2020 4:21 UTC.~ EDIT: I forgot to account there's additional dataset at that time, so this is irrelevant now

### More information

If you change the size of data to (10500, 170, 400, 3), it works fine, the RAM usage are 4.9 GB of 12.72 GB. It doesn't make sense if I change it to 11000 and the RAM usage just whooping to over 12 GB... right?

Futhermore, I don't think this is problem with the version of TensorFlow library I used. It's the same 2.3.0 version.

[Here is the colab notebook link in case you need it.](https://colab.research.google.com/drive/1__Zdp2TSJr98n8akXZd2SItP__SL_WUj?usp=sharing)

Thanks,

EDIT : Further investigation, I also tried Kaggle with more RAM and it's also crashed. It's seems not just run out of memory. This seems to related with protobuf hard limit...

EDIT : This seems rather a feature request, to tell the users that they hit the protobuf hard limit when the session crashed

**Comment by colaboratory-team** [comment]
The `tcmalloc` lines are just warnings. The real problem here is the assertion failure in the quoted error message: protobufs can't be larger than 2GiB. This is tensorflow/tensorflow#24459.
