### ISSUE TITLE
Colab Stuck on "busy" or "restarting" when connecting to local runtime

### ISSUE THREAD

**Issue by audreyberquand** [googlecolab/colabtools#1731]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- **Describe the current behavior:** Colab Notebook does not connect anymore to local runtime, it just displays "busy". Worked like a charm yesterday and works fine if I try to connect to a hosted runtime. I have tried to interrupt the execution / restart the runtime / Factory reset runtime without success... In the "best" cases, the notebook moves on to being frozen in a "reinitialization" mode. I have also tried a different port for my VM. The issue is not with the VM according to the Google Cloud Platform support. So @GoogleColab help!

- **Describe the expected behavior:** Connected to local runtime

- **The web browser you are using (Chrome, Firefox, Safari, etc.):** Chrome

**Comment by whoafridi** [comment]
You got the answer? I've also facing same issues in colab

**Comment by audreyberquand** [comment]
Hi, unfortunately, I did not get any answer from @colaboratory-team
GCP support confirmed that the issue was on colab side, not theirs, in my case.
In the end, I am going to run my script directly with the gcp cloud shell...

**Comment by israrhussainrao** [comment]
stuck in the same issue for 2 days. its keep on executing the code.

**Comment by lmy86263** [comment]
> stuck in the same issue for 2 days. its keep on executing the code.

+1

**Comment by fitnesswanderer** [comment]
stuck in the same issue for 2 days. its keep on executing the code.
What should I do?

**Comment by OracleToes** [comment]
I'm getting this same issue as well, has there really been no fix?

**Comment by as1078** [comment]
Also getting this issue. Is there a fix?

**Comment by cperry-goog** [comment]
Can you confirm your jupyter server is running per the instructions at https://research.google.com/colaboratory/local-runtimes.html ? This sounds like the local jupyter instance breaking and Colab cannot connect to it.
