### ISSUE TITLE
Failed to initialize NCCL

### ISSUE THREAD

**Issue by supersonic118** [googlecolab/colabtools#1735]
Caught error during NCCL init (attempt 0 of 5): trying to initialize the default process group twice!
Caught error during NCCL init (attempt 1 of 5): trying to initialize the default process group twice!
Caught error during NCCL init (attempt 2 of 5): trying to initialize the default process group twice!
Caught error during NCCL init (attempt 3 of 5): trying to initialize the default process group twice!
Caught error during NCCL init (attempt 4 of 5): trying to initialize the default process group twice!

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-38-659c07b23285> in <module>()
      9 from jukebox.utils.dist_utils import setup_dist_from_mpi
     10 from jukebox.utils.torch_utils import empty_cache
---> 11 rank, local_rank, device = setup_dist_from_mpi()

1 frames

/usr/local/lib/python3.6/dist-packages/jukebox/utils/dist_utils.py in _setup_dist_from_mpi(master_addr, backend, port, n_attempts, verbose)
     99             pass
    100 
--> 101     raise RuntimeError("Failed to initialize NCCL")

RuntimeError: Failed to initialize NCCL

I have no idea what any of this means I am not a very experienced programmer.

**Comment by metrizable** [comment]
Since this issue was filed a while ago, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
