### ISSUE TITLE
Support Multiline Form Input

### ISSUE THREAD

**Issue by githubpsyche** [googlecolab/colabtools#174]
So, you recently added a Form feature for the notebooks. It's neat, I like it, etc. But despite all the many different sorts of forms that are possible, one I'm really missing is multiline input. If I want to accept from the user, say, the string: 
"""Bobby
Janice
Lana"""

I'm stuck, especially given Python's limitations with respect to accepting multiline input generally. So can you please add that? Or in the meantime tell me how I can go on without it?

**Comment by githubpsyche** [comment]
I found that I could get the control I wanted over form display by relying on HTML/Javascript Forms and transmitting submissions to Python variables the amazing output module for google.colab. Thank you for all the cool work you guys do - and making it free to use!

**Comment by eyaler** [comment]
@githubpsyche care to share your solution?

**Comment by githubpsyche** [comment]
Uh, it's been a few years, but I think this notebook demos an approach I ended up abandoning: https://drive.google.com/file/d/1roBC2t-k7-fjoWg_-cAZoKHqWTe9OLR3/view?usp=sharing

Forgive the, uh, extra stuff. I just don't really feel like cleaning up the example right now.

**Comment by eyaler** [comment]
Thanks. I ended up doing it using ipywidgets areabox. example: https://j.mp/vid2green

**Comment by githubpsyche** [comment]
Awesome, that seems pretty smooth!
