### ISSUE TITLE
it occure when i unzip a large folder

### ISSUE THREAD

**Issue by frallisland** [googlecolab/colabtools#1741]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
it occure when i unzip a large folder by commend "!jar xvf CH-SIMS.zip".Can you tell me the solution?
- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by whoafridi** [comment]
Check the unzip command when try to use zip file in colab

**Comment by frallisland** [comment]
my command is "!jar xvf CH-SIMS.zip"

**Comment by whoafridi** [comment]
https://stackoverflow.com/questions/50590747/how-can-i-unzip-very-large-zip-file-6gb-in-google-colab-notebook

I got this .

**Comment by frallisland** [comment]
thanks.
