### ISSUE TITLE
Lost code from 2 days of work.

### ISSUE THREAD

**Issue by GauharM** [googlecolab/colabtools#1747]
I have lost all change in my Colab notbook made during 26 and 27th November in this Colab: https://colab.research.google.com/drive/1y_2ZwvifBy31A986KllGpLWWuJik-iYJ#scrollTo=fzi_gM8GUdQj
Could you, please, restore it.

Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by blois** [comment]
Using File -> Revision History, are you able to see any data from previous revisions?

**Comment by GauharM** [comment]
Yes, those days have disappeared from the History - I have 24 and 25th and then 30th right away

**Comment by PratyushPareek26** [comment]
A similar thing happened with me... were you able to find a solution? @GauharM

**Comment by Galsor** [comment]
Same thing happened to me. 
I can see changes in the file activity but all revisions for the last two days disappeared.
The weirdest part is the current file revision is prior to the revision I worked from yesterday.

Loosing days of work is the worst experience one can encounter.
You have an issue with the auto-save and revision system. Please handle it...

**Comment by imSarfaroz** [comment]
Same happened here! That's annoying to lose all the work!

**Comment by jdmogollonp** [comment]
I was trying to save an image output from the notebook, but instead, I downloaded the full page. When I opened it up, it suddenly crashed my Colab notebook, lost its state, and restored an old version of the file. Now I have a useless HTML and two days of work lost.

**Comment by CY-dev** [comment]
I experienced the same just today, lost 2 days of work. Will open a new issue.

**Comment by ILIAISHCHENKO** [comment]
Still a problem
