### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_86'

### ISSUE THREAD

**Issue by gbharti379** [googlecolab/colabtools#1748]
![compute_86](https://user-images.githubusercontent.com/26971298/100746047-31824080-3406-11eb-9444-159a4914f1bd.PNG)
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

nvcc fatal   : Unsupported gpu architecture 'compute_86'
Makefile:183: recipe for target 'obj/convolutional_kernels.o' failed
make: *** [obj/convolutional_kernels.o] Error 1

**Comment by ZhaoChongren** [comment]
I have this problem too. Have you solved it?

**Comment by gbharti379** [comment]
@ZhaoChongren remove the computer_86 architecture from make file it's work for me
