### ISSUE TITLE
Cell has not been executed in this session

### ISSUE THREAD

**Issue by hermesribeiro** [googlecolab/colabtools#175]
Dear all,
Whenever I try to make a long network training or hyperparameter tuning using either pure TensorFlow or Keras, the session disconnects on about 30 minutes. The background keeps running, but the notebook stops printing the output results with the message on mouse over:
"Run cell
cell has not been executed in this session
executed at unknown time" 
Is there any way to solve this issue via som settings?

**Comment by colaboratory-team** [comment]
Please reopen if you are able to share a self-contained notebook that reproduces the problem.
