### ISSUE TITLE
Keras flow_from_directory function not working

### ISSUE THREAD

**Issue by KeeshanW** [googlecolab/colabtools#1754]
Greetings, 
After using the following import: 
from tensorflow.keras.preprocessing.image import ImageDataGenerator

My code was running as expected with the the following:
ImageDataGenerator().flow_from_directory()
where it loaded the image files from my Google drive needed for the rest of my code to run. However now, this function is not working, that is it's not loading the files and reports that 0 files were found. 

I don't know it just stop loading the files, when it was running perfectly several minutes prior. I've tried restarting the notebook, remounting the google drive, different browsers, even starting a new notebook, all with the same outcome. I'm not sure what else i can do at this point to get it to work. Please advise. 

see here for a file that can recreate the issue:
https://github.com/KeeshanW/Classification_of_Dogs.git

Best, Keeshan  
 
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by metrizable** [comment]
Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem including Keras since then, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
