### ISSUE TITLE
Bob.blitz package installation error

### ISSUE THREAD

**Issue by Sergey-Github** [googlecolab/colabtools#176]
Hello, I am installing the Bob package:

!pip install bob.blitz

and get error:

Collecting bob.blitz
  Using cached https://files.pythonhosted.org/packages/8c/42/c72dc24fcd7454e4b4a4e4d5cbbc237e3b3e5e7d6e281d44479e1890c39a/bob.blitz-2.0.15.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8eqovvmj/bob.blitz/setup.py", line 70, in <module>
        system_include_dirs=system_include_dirs,
      File "/usr/local/lib/python3.6/dist-packages/bob/extension/__init__.py", line 419, in __init__
        boost_pkg = boost(boost_req.replace('boost', '').strip())
      File "/usr/local/lib/python3.6/dist-packages/bob/extension/boost.py", line 69, in __init__
        raise RuntimeError("could not find boost's `version.hpp' - have you installed Boost on this machine?")
    RuntimeError: could not find boost's `version.hpp' - have you installed Boost on this machine?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-8eqovvmj/bob.blitz/

How to fix this error and install bob.blitz?

P.S. If I understood correctly, I also installed boost (successfully):
!pip install boost

**Comment by blois** [comment]
The error is looking for Boost, so:
```
!apt-get install libboost-all-dev
!pip install bob.extension
```

Then you'll need to install Blitz, but I'm not seeing up-to-date instructions for that- `!apt-get install libblitz0-dev` doesn't work on recent releases.

I'd recommend following up on blitz or bob.blitz forums.
