### ISSUE TITLE
Not able to log into colab with my google drive account, even though I am logged into google drive. 

### ISSUE THREAD

**Issue by SantoshGuptaML** [googlecolab/colabtools#1763]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

I am not able to log into colab. I open a colab notebook from my google drive, but I am not able to save or create copies of those notebooks, because I am logged out. What is interesting is that there is still the colab pro symbol on the left, even though that needs a login. 

When I try to log back in, I get redirected to the "You need access" page. At the bottom, it says I am signed into the same account as the owner of the notebook. 

- Describe the expected behavior:

The colab account management should work as previously. 

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome 

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

I open the notebook from my google drive account
https://snipboard.io/LpMqbU.jpg

It says I am not logged in, even though I have the colab pro symbol 
https://snipboard.io/xq4y8n.jpg

When I try to sign in, I need to get access, even though at the bottom it shows the same account which is the owner of the notebook
https://snipboard.io/Tz1yik.jpg

**Comment by colaboratory-team** [comment]
The (anonymous) avatar included with the email address at the bottom of the third screenshot is different to the (non-anonymous) avatar included in the first screenshot's right-hand status pane (extremely dimmed).
Are you sure that the owner of the notebook is indeed the account you're signed in as?

Does the problem reproduce in an incognito window?

**Comment by SantoshGuptaML** [comment]
Yeah, it's the same account. I guess the avatar is not retrieved for the 3rd page, but it's the same account, sangupta.ml@gmail.com. I only have colab pro on that account. Also, the colab pro is symbol is on the notebook as well, so it looks like it's partially recognizing that I am logged in. 

https://snipboard.io/GmAjsa.jpg

I haven't had a chance to try in the incognito window, I'll be able to try in about 5 hours (3pm PST)

**Comment by SantoshGuptaML** [comment]
It seems like the issue is fixed now; my colab notebooks are logged in now.

**Comment by colaboratory-team** [comment]
Thanks for confirming you're unblocked.
FYI this is likely a dup of #1766 which we've been able to reproduce, so a fix will be tracked there.
