### ISSUE TITLE
Can't save (or log in) when logged out of a google account

### ISSUE THREAD

**Issue by b-chu** [googlecolab/colabtools#1766]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
3 google accounts available when clicking icon in top right
Logged into account 1, session expired for account 2, logged into account 3
Switch to account 3
Open notebook belonging to account through (through drive or colab)
No longer signed into any google account (top right says "Sign In")
Can't save notebook but can still edit

- Describe the expected behavior:
Signed into account 3
Can save notebook

- Fix
Fixable by signing into account 2 (which previously said session expired)
Account 3 notebooks now work

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
N/A

**Comment by colaboratory-team** [comment]
Thanks for the detailed report!
Repro'd & tracked internally in b/173005239. Will close this issue when the fix rolls out.
