### ISSUE TITLE
pydot import problem

### ISSUE THREAD

**Issue by angshusuri** [googlecolab/colabtools#177]
When I try to run my program after installing pydot it is showing :
+1: /usr/local/lib/python3.6/dist-packages/keras/utils/vis_utils.py in _check_pydot()
     18     if pydot is None:
     19         raise ImportError(
---> 20             'Failed to import `pydot`. '
     21             'Please install `pydot`. '
     22             'For example with `pip install pydot`.')

ImportError: Failed to import `pydot`. Please install `pydot`. For example with `pip install pydot`.

The installation command are :  
!apt-get -qq install -y graphviz && pip install -q pydot.
Please help me . Thanks in advance.

**Comment by blois** [comment]
You'll need to restart your runtime after installing pydot as the result is cached from first load:
https://github.com/keras-team/keras/blob/master/keras/utils/vis_utils.py#L11

**Comment by blois** [comment]
Restart the runtime under the Runtime menu.

You'll also need to install graphvis: `!apt-get install -y graphviz`
