### ISSUE TITLE
After starting the runtime on GPU, the first time I run any code that requires that GPU, it launches and runs extremely slowly. After that, it gets to normal, but the problem reappears every time I restart the runtime.

### ISSUE THREAD

**Issue by hungrynagini** [googlecolab/colabtools#1772]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by colaboratory-team** [comment]
This symptomology sounds like you've installed software that is targeting the wrong NVIDIA compute capability for the GPU you're being assigned, resulting in a slow JITting of the GPU-targeting code once per runtime lifetime.

**Comment by colaboratory-team** [comment]
(if this is reproducible with preinstalled software on the VM, a publicly-readable, minimal reproduction notebook link would be great)
