### ISSUE TITLE
torch.cuda.is_available () returning false in google coolab

### ISSUE THREAD

**Issue by cybertron97** [googlecolab/colabtools#1773]
I am experiencing issues with running the cuda version on google colab 
I have been following this website to help myself 

(https://colab.research.google.com/drive/1B5KQvPySqYEa6XicRHdOwgv8fN1BrCgQ#scrollTo=335xvR6acayB)

But when i try to run the same file in google colab, I expereience these issues: 
 Code 
`import torch
torch.cuda.is_available()`

Output : 
/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
False

Any help would be really helpful

**Comment by colaboratory-team** [comment]
The way CUDA works requires software to be linked against the correct runtime libraries. Installing arbitrary software builds isn't expected to work. The torch bundled with colab VMs shows cuda_is_available() returns true.

(Runtime -> Factory reset runtime to get a fresh VM)
