### ISSUE TITLE
print function returning tuple error - Clip inside

### ISSUE THREAD

**Issue by cmaguire13** [googlecolab/colabtools#1776]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
- Returning an error for the print function

- Describe the expected behavior:
- Please see - https://drive.google.com/file/d/1rhNLw7mg9kBY7NDdJl_JLWGadjlACYS7/view?usp=sharing

- The web browser you are using (Chrome, Firefox, Safari, etc.):
- Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
- Not reproducible when accessed with a different account.
- https://colab.research.google.com/drive/1iMY1ekFeqjqG0AnusZ1n4mDAZU4tvV4n?usp=sharing

**Comment by craigcitro** [comment]
You've almost surely accidentally reassigned `print` (eg via `print = ...`).

Restarting your kernel (ctrl-m .) should get you up and running.

**Comment by cmaguire13** [comment]
Cheers Craig!
