### ISSUE TITLE
Colab disconnecting too frequently; not idling, no GPU, Pro user

### ISSUE THREAD

**Issue by kevinroccapriore** [googlecolab/colabtools#1777]
Bug report for Colab: http://colab.research.google.com/.

Hello-

Since yesterday, Colab has been disconnecting about every 10-15 minutes. I am on a home network, no VPN, nothing fancy there. I'm using the latest Chrome browser. I have Pro, and I have a *single* instance open with standard runtime CPU and basic memory - literally the most minimalistic runtime I can run. I can't imagine Google dropping me down the priority list given I'm using the most basic runtime and am a Pro subscriber. As I am on CPU, I am not doing any sort of deep learning training. These issues are occurring with ordinary codes and data files in the tens of MBs. 

All uploaded files to the workspace are lost, like a factory reset runtime. So I have to reinitialize all modules and upload all files again each time, only to have about 10 minutes of working time before I am booted again. Clearly not enough time to get much done.

I have not changed anything as far as I can tell. 
I've never had this issue of being booted in this manner. That is to say, I have been disconnected due to idling, my network dropping, or using a GPU runtime when I don't need it. This however is different, and I see no reason why it is occurring.

Also, this is happening to any of my notebooks, and is not isolated to any one in specific.

I could not find any similar report. Most disconnects seem to be due to idling for too long, or training a network for a long time, essentially over-taxing the servers or not utilizing them - that's to be expected. This however is not. 

Is there any change that has recently occurred? Or, is there anything I can check on my end? What other possible reasons are there for such behavior?

Thanks,
-K

**Comment by yuriyzuev** [comment]
the same problem

**Comment by kevinroccapriore** [comment]
No change here. 
I resorted to local runtimes for simpler tasks but when I need GPU, I cannot keep the notebook active for more than a few minutes.

What's going on guys?

**Comment by kevinroccapriore** [comment]
Another update.

I was incorrect in saying this issue is tied to my account. 
Since then, I have switched computers, changed from chrome to firefox (to ensure no nasty extensions that might be carried over), changed to an entirely new google account, and - here's the kicker - I am testing the issue with the "Welcome to Colaboratory" notebook! I am still disconnected randomly, with all variables and files cleared (total fresh instance).

How is this even possible? This is driving me nuts

**Comment by OPHoperHPO** [comment]
The same issue

**Comment by mrmonsif** [comment]
The same issue, Pro user

**Comment by vothaiduong14** [comment]
Same issue even as a Pro user. I wouldn't mind paying more but paying for something that doesn't work is really disappointing.

**Comment by rubeea** [comment]
Same issue. Today my runtime got disconnected and all the data was wiped out immediately though I am a pro user!

**Comment by cperry-goog** [comment]
Duplicating into #2032

**Comment by apprenticemanxxx** [comment]
me too, pro user as well, and it's disconnected even in the training process.
