### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by Smokemachine** [googlecolab/colabtools#178]
Hello, Google!
Today I installed you colaboratory service and discovered a bug. After upgrading tensorflow-gpu I can't backup default environment to start it again. Please, tell me how to do it or add this function in colab.

**Comment by colaboratory-team** [comment]
You can always reset your environment to its original state by selecting 'Reset all runtimes' from the Runtime menu.
![image](https://user-images.githubusercontent.com/38081706/54174540-376f0b80-4444-11e9-92d7-4b6ff0c6ed1a.png)
