### ISSUE TITLE
Colab functionality breaks after trying to mount drive with shortcut

### ISSUE THREAD

**Issue by jalgalvis** [googlecolab/colabtools#1781]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
In some notebooks when I try to mount drive with shortcut or the button in the Files section, it requests to add a drive mount code:

```
from google.colab import drive
drive.mount('/content/drive')
```
then some functionality stop working, most of the shortcuts do not work and actually cells options reduce only to link to cell, settings and ... as follows

![Screen Shot 2020-12-17 at 10 56 16 AM](https://user-images.githubusercontent.com/38927544/102511338-aa180c80-4056-11eb-8592-69466a034756.png)

- Describe the expected behavior:
Drive mount button and shortcut should just do that mount the drive, and if for some reason code needs to be added the notebook should keep behaving as before.
 
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

https://drive.google.com/file/d/1bGGfAnO_iEogJv-CclRJb0VmxJFF4Ttm/view?usp=sharing

**Comment by colaboratory-team** [comment]
Does the problem reproduce if you "Runtime -> Factory reset runtime"?
How about in an incognito window?

**Comment by jalgalvis** [comment]
Thank you very much,
I just have a doubt, why sometimes I just cannot use the function to mount the drive and Colab ask me to include the mentioned code?
