### ISSUE TITLE
Runtime dies when I use gpu/cpu

### ISSUE THREAD

**Issue by ArthDh** [googlecolab/colabtools#179]
Link to notebook: 
https://drive.google.com/file/d/1ZfLcjEQu6LxmxPF5sfk8RaxKQ4X8p7jN/view?usp=sharing

**Comment by colaboratory-team** [comment]
For issues of this type, please share a self-contained notebook that reproduces the issue. (We aren't able to execute this notebook since it relies on private files in Drive.)
