### ISSUE TITLE
Colab terminate too frequently

### ISSUE THREAD

**Issue by imrankhan441** [googlecolab/colabtools#1793]
What is going on with colab. it's terminate without any reason. I think colab will be unusable in the feature. please don't terminate I train my model for about 3 hours and remaining only 5 more epoch to complete and it's terminate automatically. that was a really horrible experience. please fix this issue as soon as possible. 
thank you

**Comment by skullymqc5** [comment]
[]()

**Comment by skullymqc5** [comment]
What the he'll exactly is y'all doing

**Comment by skullymqc5** [comment]
Sounds like it's broken
