### ISSUE TITLE
Terminal doesn't scroll

### ISSUE THREAD

**Issue by dorukkarinca** [googlecolab/colabtools#1795]
- Describe the current behavior: There's a new Terminal tab on Colab which is pretty nice. However, there is no scroll bar. Using the mouse wheel on the terminal causes it to either print "scroll characters" to the console or navigate the command history (just like up/down arrow keys).

- Describe the expected behavior: It should scroll. That way, console output larger than one screen should be navigable.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*): n/a

**Comment by colaboratory-team** [comment]
Thanks for the report. This is internally tracked as b/176440596.

Workaround: use tmux's copy-mode commands / keyboard shortcuts: `ctrl-b [` to enter copy-mode, then pgup/pgdn to scroll by pages or up/down arrows to move by single line, etc.

**Comment by dorukkarinca** [comment]
I gave it a go today and the scrollbar looks good! Thanks!
