### ISSUE TITLE
%Tensorboard shows no output

### ISSUE THREAD

**Issue by jaideepheer** [googlecolab/colabtools#1797]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
On running `%tensorboard --logdir tensorboardlogs`, I get the message `Reusing TensorBoard on port 6007 (pid 97), started 0:45:03 ago. (Use '!kill 97' to kill it.)` but tensorboard iframe is not shown.

![image](https://i.postimg.cc/CKLk6ND8/Screenshot-2020-12-31-203331.png)

Chrome console looks like this whenever I run the cell,
![image](https://i.postimg.cc/R0yhQQT4/Screenshot-2020-12-31-203331.png)
![image](https://i.postimg.cc/J0ch8wCz/Screenshot-2020-12-31-203331.png)

- Describe the expected behavior:
Tensorboard should show up.
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Google chrome v87.0.4280.88 (Official Build) (64-bit)
- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks

**Comment by blois** [comment]
This looks like it's within Tensorboard's Javascript, should probably be filed in https://github.com/tensorflow/tensorboard/issues.
