### ISSUE TITLE
Docstrings do not appear while writing code even though I have turned off automatic code completion from the settings

### ISSUE THREAD

**Issue by Monisha-20** [googlecolab/colabtools#1799]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
-  I tried everything, pressing tab and ctrl+space, but the docstrings never appear whenever I code in google colab. I have turned off automatic code completion from the settings but still, every time I try it says no suggestions. 

- Describe the expected behavior:
Quick docstrings should appear whenever I press tab or ctrl+space. 
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
[https://colab.research.google.com/drive/1-oRijAoUwpp2Qlz-Kl3k6hNlodWQyf87?usp=sharing](url)

**Comment by craigcitro** [comment]
Just to clarify: do you mean `Automatically trigger code completions` is *off* or *on*?

* If it's on, does refreshing the page fix things?
* If it's off, what happens when you turn it on?

Does this happen across all notebooks, or just sometimes?
