### ISSUE TITLE
cannot reauthenticate

### ISSUE THREAD

**Issue by ay1011** [googlecolab/colabtools#180]
after running 

!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

**Comment by colaboratory-team** [comment]
Sorry, we're not able to diagnose issues with libraries used within Colab. I'd recommend asking a question on a more general-purpose forum like StackOverflow to attract the attention of domain experts.

An alternative to this library is to use the built-in Drive FUSE client; see:
https://colab.research.google.com/notebooks/io.ipynb#scrollTo=u22w3BFiOveA
