### ISSUE TITLE
a url ending with a underscore is truncated 

### ISSUE THREAD

**Issue by eyaler** [googlecolab/colabtools#1803]
if you paste e.g. `https://colab.research.google.com/drive/1bwUnj-9NnJA2EMr7eWO4I45UuBtKudg_` into a text cell, it becomes a hyperlink but the underscore in the end gets truncated

**Comment by blois** [comment]
Colab (and most other notebook renderers) use marked.js for markdown rendering, it looks like the linkifying there is not treating trailing underscores as part of the link.

Here's [an example](https://marked.js.org/demo/?text=%20-%20Bad%3A%20http%3A%2F%2Fexample.com%2Ffoo_%0A%20-%20Workaround%3A%20%5Bhttp%3A%2F%2Fexample.com%2Ffoo_%5D(http%3A%2F%2Fexample.com%2Ffoo_)&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) with a workaround.

**Comment by blois** [comment]
See also https://github.com/markedjs/marked/issues/1758#issuecomment-691268825
