### ISSUE TITLE
Sudden file handling error- OSError: [Errno 22] Invalid argument:

### ISSUE THREAD

**Issue by DomMcKean** [googlecolab/colabtools#1807]
Bug report for Colab: http://colab.research.google.com/.

-I have been working with the same scripts on Colab for over a year. I have used these scripts yesterday and this morning with no problems. All of a sudden this afternoon, I have been getting this error: "OSError: [Errno 22] Invalid argument:" when attempting to access files.

-Nothing in the script has been changed. Older scripts that are known to work are also failing with the same error. 
I am using the same browser - Chrome.
I have noticed in the file explorer window that there was always a gap in the directory name "My Drive"; however, this gap now seems to be gone- "MyDrive", but closing this gap in my file path had no effect on the error. 

I was recently greeted with a message from Google Drive telling me that Drive was out of date and needed reloading. Could this Drive update be related?

Link to my workbook:
https://colab.research.google.com/gist/DomMcKean/c19b8f8a3b2f77cfd6fb8d836b8a19db/trainer.ipynb

Traceback:

/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_pdf.py in __init__(self, filename, keep_empty, metadata)
    2433 
    2434         """
-> 2435         self._file = PdfFile(filename, metadata=metadata)
    2436         self.keep_empty = keep_empty
    2437 

/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_pdf.py in __init__(self, filename, metadata)
     457         self.original_file_like = None
     458         self.tell_base = 0
--> 459         fh, opened = cbook.to_filehandle(filename, "wb", return_opened=True)
     460         if not opened:
     461             try:

/usr/local/lib/python3.6/dist-packages/matplotlib/cbook/__init__.py in to_filehandle(fname, flag, return_opened, encoding)
     401             fh = bz2.BZ2File(fname, flag)
     402         else:
--> 403             fh = open(fname, flag, encoding=encoding)
     404         opened = True
     405     elif hasattr(fname, 'seek'):

OSError: [Errno 22] Invalid argument: '/content/drive/My Drive/PhD/PhD/lstm3/model44/model44_v0/gauss_pic_RMSE.pdf'

**Comment by colaboratory-team** [comment]
The OSError might have been fallout from a service-side issue. Does the error persist through if you "Factory reset runtime" and try with a fresh VM?

The removal of the space in `My Drive` is an [intentional change](https://twitter.com/GoogleColab/status/1328757129046413312), and things should work both with and without the space.
