### ISSUE TITLE
Python package `rpy2` available by default is outdated.

### ISSUE THREAD

**Issue by lgautier** [googlecolab/colabtools#1808]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

By default the R magic is using an outdated version of `rpy2`, no longer compatible with the default version of `pandas` (or R packages coming with R-4.0, also the version of R available by default on colab).

- Describe the expected behavior:

The version of the package rpy2 available by default on colab should be the latest (3.4.2 at the time of writing).

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Not relevant, but Firefox.

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/drive/1QU1cHf6gbkpcSGgcjcrtiyLhDtordW2k?usp=sharing

**Comment by Timmate** [comment]
@lgautier Is this the only outdated package you came across? I got a whole bunch of such packages when running `!pip list --outdated` which makes me wonder why this actually happens.

**Comment by lgautier** [comment]
I have not checked all packages. I just happen to be the maintainer of `rpy2` and I noticed that the version installed by default will not work well with version of other packages installed by default.

Given the number of installed packages, each following their own release schedule, I believe that there can always be outdated packages.

**Comment by craigcitro** [comment]
OK, rpy2 should be updated!
