### ISSUE TITLE
pip install colabtools?

### ISSUE THREAD

**Issue by MeTaNoV** [googlecolab/colabtools#181]
Hi,
we are using Colaboratory via local runtime and therefore need to install the python libraries on our server.
Especially in the context of using PyDrive, I would need access to the colabtools package, but I was not able to find it...
Therefore is the package available somewhere? Or do I need to clone this repo and do the configuration myself?
Thanks in advance!
Cheers,
Pascal

**Comment by craigcitro** [comment]
What part(s) of colabtools are you looking to use?

In particular, the `auth` libraries are really only designed for use inside colab (since they assume a lot about how things are arranged in a colab container).

**Comment by MeTaNoV** [comment]
I would like indeed `auth`, and yes, looking at the `backend-container` repo, there is a lot...

Still trying to see how I can handle the Auth from a local runtime forwarded to our Jupyter server...

**Comment by MeTaNoV** [comment]
Even without considering using `PyDrive`, it would be nice to be able to use `files` from `google.colab`.

File upload is working properly, but not the download part.
There is no problem creating a file, and since the working directory on our instance is /home/ubuntu/jupyter/, one can find the newly created file `exemple.txt` there.
But when trying to download the file, I get a `MessageError: Error: Failed to download: Not Found` and looking at the jupyter log on the instance, it receive a GET with the following path: `/_proxy/15462/home/ubuntu/jupyter/example.txt` which is incorrect in our case.

**Comment by ricardodeazambuja** [comment]
> What part(s) of colabtools are you looking to use?

I just developed [a way to read sounds directly from a local microphone using Javascript](https://ricardodeazambuja.com/deep_learning/2019/03/09/audio_and_video_google_colab/), but currently it only works inside google.colab's served notebooks because of eval_js. I really would like to use your asynchronous version of eval_js in other projects :cry:. 
I could just [dig through the code](https://github.com/googlecolab/colabtools/blob/d4f218c51d8a18c003ef3c0fceb40fe427a2bac7/google/colab/output/_js.py#L23) to extract what I need, but it would be much nicer to simply pip install it :smile:

**Comment by colaboratory-team** [comment]
We aren't planning to offer colabtools as a standalone package for the foreseeable future.

**Comment by blois** [comment]
eval_js requires support on both the Python side and the client side. It's theoretically possible to get something similar using an IPython 7.0+ kernel with async/await but I have not had much luck with it yet. It would be a great JupyterLab sample if you can get it working well!

**Comment by ratulray** [comment]
+1 for being able to pip install colabtools

**Comment by amutz** [comment]
+1 for colabtools being usable outside colab. 

In particular, I want to be able to share colab-hosted notebooks in my organization that work even if you are using a local runtime (for extra horsepower).  There are small differences between local runtimes and colab.

Just one example: colabtools allows shell commands to accept user input.  This is great!  I currently get this functionality by doing `google.colab._system_commands._shell_line_magic(command)`, but this is ugly and it would be nice to just get this functionality by loading the colab extension

**Comment by dayfine** [comment]
Yeh I think it would be nice to use `interactive_table` in a local runtime. (This works at Google and I wonder where the difference comes in). Otherwise my option is `ipywidgets`..?
