### ISSUE TITLE
Consider updating default sympy version to 1.7.1

### ISSUE THREAD

**Issue by nlchar** [googlecolab/colabtools#1810]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

The current default sympy version is 1.1.1 which is quite old and have a lot of bugs. Please, consider updating to sympy 1.7.1 which is the latest stable release. 
- Describe the current behavior:
import sympy
sympy.__version__
OUT: '1.1.1'
- Describe the expected behavior:
import sympy
sympy.__version__
OUT: '1.7.1' (or the latest stable release from pip)
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/19CFroaEWsiYlUOA-21JooGkU2yA4EmWL?usp=sharing

**Comment by craigcitro** [comment]
New version should be live.
