### ISSUE TITLE
Allocating takes forever in Colab

### ISSUE THREAD

**Issue by shakhyar** [googlecolab/colabtools#1812]
I am unable to connect to google colab. When I click on connect, it takes forever to connect. I have used different browsers, different accounts, but nothing worked out. I cannot even run previous notebooks.

A few days ago, I ran a large program, it made the System RAM crash of colab several times: It was a neural network notebook, [ASR WITH NEMO](https://colab.research.google.com/github/NVIDIA/NeMo/blob/r1.0.0b3/tutorials/asr/01_ASR_with_NeMo.ipynb) 

I don't know if this the issue, like maybe google blocked me from using colab, like a cooldown period?

I tried to grab console logs of Google Colab by inspecting it, then I got this: 
![Screenshot (523)](https://user-images.githubusercontent.com/68093713/104454062-505e2000-55cb-11eb-829d-ae36c7ff88f3.png)

Or maybe my country is not authorized to load Google's scripts? I am from India though. Even after using VPN or a Proxy, I am not able to connect. NOTE: **This is really strange, I could not use some google services like editing google forms, making changes to my google calendar. I can only use those after I connect to a VPN or Proxy. (But not with popular apps like youtube, gmail, etc.**

The things I have tried:

- used VPN [not worked]
- used different account[not worked]
- used different browsers[not worked]
- cleared browser cache[not worked]

Any solutions?

**Comment by trbella** [comment]
Hi, @shakhyar 
It was happening the same with me, but I don't think that it is about your code.
I simply went to google's page, logged off all my accounts and logged on again.
Then I just refreshed the colab's page and everything was running normally again.

**Comment by Abishek-rk** [comment]
Solves for me by signing out from google chrome and disabling the specific 3rd party chrome extension.

**Comment by cperry-goog** [comment]
+1, probably extensions

**Comment by Leo-Aqua** [comment]
Yep disabling all extensions worked! just go to [chrome://extensions/](chrome://extensions/) and disable all

**Comment by oubellasaber** [comment]
worked for me by disabling the captcha solving extention
