### ISSUE TITLE
Stuck on allocating

### ISSUE THREAD

**Issue by JoshKou** [googlecolab/colabtools#1820]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by schwers** [comment]
I also have this issue. I only get stuck allocating when running on Safari. 

The notebook I'm trying to run was: https://colab.research.google.com/github/fastai/fastbook/blob/master/01_intro.ipynb

My Safari version (gets stuck allocating and never connects / initializes):  14.0.2 (15610.3.7.1.10, 15610)

My  Chrome version (works within seconds): 88.0.4324.96
