### ISSUE TITLE
Wrong parsing for the dollar sign "$" in shell code-blocks

### ISSUE THREAD

**Issue by ModarTensai** [googlecolab/colabtools#1821]
When there is a dollar sign in two consecutive shell code-blocks, the displayed preview gets messed up:
![image](https://user-images.githubusercontent.com/7101743/105110690-2e373700-5ad0-11eb-9a9f-62516103ede4.png)

The expected output should look something like this:

-----------------------------------
```shell
echo $A
```

What is going on here?

```shell
echo $A
```
-----------------------------------

I am using Google Chrome and didn't test other browsers. To reproduce the bug, copy the following in a new text cell:
~~~
```shell
echo $A
```

What is going on here?

```shell
echo $A
```
~~~

**Comment by craigcitro** [comment]
We can't seem to repro this -- can you confirm it happens in an incognito window (in particular where no extensions are present)?

**Comment by ModarTensai** [comment]
Yes, I just tried it also on Edge:
![image](https://user-images.githubusercontent.com/7101743/105254262-322b8d80-5b92-11eb-8687-52176e904730.png)

**Comment by blois** [comment]
Do you also see that behavior with https://colab.research.google.com/gist/blois/c17b4e70b9368927706d2138a9065d73/untitled.ipynb?

**Comment by ModarTensai** [comment]
Interesting, your cell is fine if you copy it as is. However, when I try to copy its content in a new cell it fails again.
![image](https://user-images.githubusercontent.com/7101743/105256256-74ef6480-5b96-11eb-90c1-15b86c0dde7b.png)

**Comment by ModarTensai** [comment]
I cloned your gist notebook and made the edits. On gist, the preview is fine but in colab, the last cell is just wrong. Can you confirm this link: https://colab.research.google.com/gist/ModarTensai/fdb264b4970fc31bb69e9ac1e1a1dd24/untitled.ipynb

**Comment by blois** [comment]
Interesting! I now see it in your notebook. Will look further.

**Comment by blois** [comment]
It seems to be an issue with carriage returns + newlines in that markdown cell, as opposed to just newlines.

**Comment by ModarTensai** [comment]
Hmm... I was working on my Windows machine to create homework for the new semester. I checked and it seems that there is no option to force LF instead of CRLF. This will definitely add some overhead as I would need to download the notebooks convert line endings and upload them back again (didn't test this yet). Hopefully, this gets fixed soon as I only have remote access to my Linux workstation. Thanks, @blois for confirming this.

**Comment by corrieann** [comment]
Thanks for the report!  This should now be fixed.
