### ISSUE TITLE
tf.keras.preprocessing.image_dataset_from_directory includes hidden dirs as classes

### ISSUE THREAD

**Issue by jhihn** [googlecolab/colabtools#1824]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
When passing class names it produces the error:
`ValueError: The `class_names` passed did not match the names of the subdirectories of the target directory. Expected: ['.ipynb_checkpoints', 'no_skip', 'skip'], but received: ['no_skip', 'skip']`
 When not passing class names it picks up 3 classes, not two.

- Describe the expected behavior:
tf.keras.preprocessing.image_dataset_from_directory(...) should not include hidden `.directories`.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Not relevant

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1sI2Zk7-YjIOg3nRDyHtUtczwjevQfdPF?usp=sharing

**Comment by craigcitro** [comment]
I'd recommend filing this in the keras repo.
