### ISSUE TITLE
Inconsistent behaviour for bq magic

### ISSUE THREAD

**Issue by darrenchiu** [googlecolab/colabtools#1827]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: If i put any code in front of the %%bigquery line, it would return with "Syntax Error" for the %%bigquery line. Making the BQ magic not usable at all.

- Describe the expected behavior: I should be able to put code in front of the %%bigquery line.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1wmyIJUE6WOHojCp7ODhF3ZLyJAlxYj84?resourcekey=0-NgCVXO_pe9wEB_tyw09azw&usp=sharing

**Comment by craigcitro** [comment]
This is WAI: cell magics (anything starting with `%%`) need to be in a cell by themselves.

See https://colab.sandbox.google.com/notebooks/basic_features_overview.ipynb#scrollTo=qM4myQGfQboQ and the link there for more info about magics.
