### ISSUE TITLE
Connected to GPU, but not utilizing GPU.

### ISSUE THREAD

**Issue by impetusengine** [googlecolab/colabtools#1829]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: Experiencing the warning: "Warning: you are connected to a GPU runtime, but not utilizing the GPU."
- Describe the expected behavior: GPU is accelerating runtime.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by MartinCastellano** [comment]
current behavio:You cannot currently connect to a GPU due to usage limits in Colab
Describe the expected behavior: GPU is accelerating runtime
The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

**Comment by cperry-goog** [comment]
I don't see any specific bug reports in here; your code will need to be modified to take advantage of the GPU. Closing this, if you have specific issues please report them separately.
