### ISSUE TITLE
Can't enable new editor with vim support, no experimental button

### ISSUE THREAD

**Issue by 205g0** [googlecolab/colabtools#1831]
There's no experimental button to turn on the new editor.

- Describe the current behavior: No experimental button

- Describe the expected behavior: Experimental button shown

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

**Comment by craigcitro** [comment]
What was once the "new editor" is now the only editor -- `Tools` -> `Settings` -> `Editor` should be what you're looking for.
