### ISSUE TITLE
Colab is no more available to connect in GDrive

### ISSUE THREAD

**Issue by Espanta** [googlecolab/colabtools#1833]
Colab seems to be excluded in the new "Google Workplace Marketplace" as an app to connect and hence new users cannot connect. It used to be available to connect until very recently in Nov/Dec 2020 and once connected, we could create new notebook from there. 

I am a teacher using Colab heavily and I am not sure if it is simply a miss or it is a plan to exclude it from Individual Google  accounts. 

I found that colab is now available https://colab.research.google.com/, but not sure this is permanent change or a bug to be fixed. Pls advise so we can update materials and communicate with students.

Thanks

**Comment by colaboratory-team** [comment]
Please see https://github.com/googlecolab/colabtools/issues/1065#issuecomment-605486998
