### ISSUE TITLE
Errors when connecting to Colab KataGo via Lizzie

### ISSUE THREAD

**Issue by foolai** [googlecolab/colabtools#1836]
KataGo and SSH server on Colab server run fine.
However, when connecting Colab KataGo via Lizzie, I get an error.
I searched the internet and couldn't find a solution. Please help me.

(1)  Lizzie Engine 0 -> C:/katagocolab/colab-katago.exe testuser 87651234

(2) Two error messages appearing in the gtp console window

case 1

> 1 name  
> 2 version  
> 3 boardsize 19  
> 4 komi 6.5  
2021/01/30 10:11:37 INFO using user name: testuser password: 87651234 
2021/01/30 10:11:38 ssh options 
{"host": "0.tcp.ngrok.io", "port": 16308, "user": "root"} 
2021/01/30 10:11:38 failed to create ssh clientssh: handshake failed: read tcp 122.147.186.214:49253->3.17.7.232:16308: wsarecv: An existing connection was forcibly closed by the remote host.

case 2

> 1 name  
> 2 version  
> 3 boardsize 19  
> 4 komi 6.5  
2021/01/30 10:28:08 INFO using user name: testuser password: 87651234 
2021/01/30 10:28:09 ssh options 
{"host": "0.tcp.ngrok.io", "port": 16308, "user": "root"} 
2021/01/30 10:28:09 failed to create ssh clientssh: handshake failed: EOF

**Comment by foolai** [comment]
I used it for 4 months without any problems. However, an error occurs from yesterday.

**Comment by eyaler** [comment]
there was an ngrok issue due to ngrok bug that was fixed in the last days
