### ISSUE TITLE
Cannot install pysine into google colab

### ISSUE THREAD

**Issue by dev-lang** [googlecolab/colabtools#1838]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: 

I am trying to get working pysine module inside google colab but a required module cannot be installed via pip

`Collecting pysine
  Using cached https://files.pythonhosted.org/packages/c4/01/32bc126eef61060eb2cf6f7c6247a376d1bd5f2cb986f90df0c98ee01544/pysine-0.9.2-py2.py3-none-any.whl
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from pysine) (1.19.5)
Collecting mock
  Using cached https://files.pythonhosted.org/packages/5c/03/b7e605db4a57c0f6fba744b11ef3ddf4ddebcada35022927a2b5fc623fdf/mock-4.0.3-py3-none-any.whl
Collecting pyaudio
  Using cached https://files.pythonhosted.org/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz
Collecting nose>=1.0
  Using cached https://files.pythonhosted.org/packages/15/d8/dd071918c040f50fa1cf80da16423af51ff8ce4a0f2399b7bf8de45ac3d9/nose-1.3.7-py3-none-any.whl
Building wheels for collected packages: pyaudio
  Building wheel for pyaudio (setup.py) ... error
  ERROR: Failed building wheel for pyaudio
  Running setup.py clean for pyaudio
Failed to build pyaudio
Installing collected packages: mock, pyaudio, nose, pysine
    Running setup.py install for pyaudio ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-edc6dkkl/pyaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-edc6dkkl/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-584e_ufu/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.`

- Describe the expected behavior:

I need to use pysine module but got an error

- The web browser you are using (Chrome, Firefox, Safari, etc.): Microsoft Edge (Chromium) 88.0.705.53

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
  https://colab.research.google.com/drive/1A_MKggNs4wJvNufcmdo7JG8Iv0PcUDCl?usp=sharing

**Comment by craigcitro** [comment]
This isn't a colab issue: pyaudio needs additional deps installed. [This answer on SO](https://stackoverflow.com/a/54396790) gives the list of libraries you need; this will work:

```
!apt-get install -q portaudio19-dev python3-pyaudio
!pip install pysine
```

**Comment by dev-lang** [comment]
ok. thank you.
that was because i followed the template while editing.

**Comment by dev-lang** [comment]
thank you again for the support
