### ISSUE TITLE
Colab bug

### ISSUE THREAD

**Issue by wilkyway69** [googlecolab/colabtools#1841]
Bug report for Colab: http://colab.research.google.com/.

I don't know if i pressed something that i shouldn't or someone else somehow got in my colab, but i see this dogs up walking, sparks flying across the entire screen, you can see it in hte picture down and while i am writing screen is shaking and combo caunt is rising :D

https://snipboard.io/HrCAwX.jpg

**Comment by blois** [comment]
You've discovered Power Mode!

https://github.com/googlecolab/colabtools/issues/803
