### ISSUE TITLE
Colab changes and versioning

### ISSUE THREAD

**Issue by eyaler** [googlecolab/colabtools#1842]
Colab is a really amazing environment, and I rely on it more and more for making tutorials and accessible tools. However from time to time things change in the environment and my notebooks break without warning or a quick way to restore functionality, or even unerstand what changed. It would be really useful to have:
1. public announcement of potentially breaking changes.
2. option to subscribe to said announcements.
3. publicly exposed versioning with an option to check the current version.
4. an elaborate changes diff between versions (namely the python libraries).
5. magic %colab_version 1.x to revert to a previous version.
6. if different versions can coexist in the wild - would be nice to have some visibility on their distribution.

**Comment by craigcitro** [comment]
Agreed that this would be nice -- but unfortunately it's not really something we can take on at the moment.

**Comment by eyaler** [comment]
@craigcitro I have just experience massive breakage of tens of colabs due to recent breaking updates. most notably: 
1. The removal or support for tensorflow 1 (which i guess will became an even harder issue if the day comes when colab updates from python 3.7)
2. Updating IPython having this side effect: https://github.com/googlecolab/colabtools/issues/3017
This is not viable/scalable. We need a better way to prevent unannounced breaking changes as well as minimize breaking changes in general. I think the easiest solution would be to have a way to pin the colab version. if the environment has updated, the pinning will downgrade it.
Please consider opening this issue, or suggesting an appropriate venue for this important discussion

**Comment by fedorov** [comment]
This is now possible https://research.google.com/colaboratory/runtime-version-faq.html. 

My coding agent could not find an official, documented mechanism for accessing the runtime information programmatically, and came up with this workaround that I am going to use. Maybe this can help someone else.

As of right now, this returns `runtime release-colab-external_20260213-060047_RC00`.

```python
# Detect Colab environment and runtime version
try:
    import google.colab  # noqa: F401
    colab_env = "Google Colab"
    # Try to get the Colab runtime version (e.g., "2026.01")
    colab_release = os.environ.get("COLAB_RELEASE_TAG")
    if colab_release:
        colab_env += f" (runtime {colab_release})"
    else:
        # Fall back to google-colab package version as a proxy
        try:
            colab_env += f" (google-colab {version('google-colab')})"
        except PackageNotFoundError:
            pass
    print(f"Runtime:  {colab_env}")
except ImportError:
    print("Runtime:  Local")
```
