### ISSUE TITLE
h5py IO and Signature Error

### ISSUE THREAD

**Issue by wgabrielong** [googlecolab/colabtools#1843]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

**Describe the current behavior:**
- Unable to open h5 files in Google Colab. 
- System throws IO error when trying to load directly from Google Drive. 
- System throws file signature error when file is loaded directly onto the virtual machine. 
- Code has previously worked on multiple instances. 

**Describe the expected behavior:**
- I would expect the file to open with no issues. 

The web browser you are using (Chrome, Firefox, Safari, etc.):
- Google Chrome Version 88.0.4324.104

**Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):**
[Notebook](https://colab.research.google.com/drive/1r4yDerWDEVC5JD0DM_esDW0NM07I3MYN?usp=sharing)

**Comment by jasonwun** [comment]
Similar issue for Google Drive IO. Was attempting to read a file but IO Error threw. The path is correct but when you are trying to read it, it throws.

**Comment by wgabrielong** [comment]
> Similar issue for Google Drive IO. Was attempting to read a file but IO Error threw. The path is correct but when you are trying to read it, it throws.

@jasonwun Is this an on and off problem? I have two notebooks open now, one where it is working and another where it gives this IO error.

**Comment by jasonwun** [comment]
Don't know. I've tried terminate and create new runtime so many times but problem persists
