### ISSUE TITLE
Colab Pro subscription does not give T4 or P100 GPU

### ISSUE THREAD

**Issue by Geethi2020** [googlecolab/colabtools#1849]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I have been paying for Colab Pro subscription since 11/3/2020. But I never got an improvement in the performance compared to my colleague who does not have a Pro subscription. Sometimes his code runs faster than mine. I reported it to the Colab customer care multiple times and did not receive a satisfactory response. After much follow up they suggested me to open a bug here. So trying my luck here !!!!! 

- Describe the expected behavior:
I expect T4 or P100 GPU to be available at least once in a while. 

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Safari (mostly) and Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/16zUW9PaIo6WDNCHG9FV2p679re_P6OUV?usp=sharing

**Comment by Geethi2020** [comment]
Always NVIDIA GPU is on and "Tesla V100-SXM2...  Off"

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   32C    P0    22W / 300W |      0MiB / 16130MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by wrhwrhwrhsf** [comment]
V100 is the best bro

**Comment by Geethi2020** [comment]
I never got V100 .. it's always set to Off 

Tesla V100-SXM2... Off

For me, even with or without paying for Pro, it's NVIDIA ..

**Comment by Geethi2020** [comment]
Any help is greatly appreciated..

**Comment by eduardo4jesus** [comment]
Same thing for me. This is upsetting.

- Before getting PRO, I always got T4, and somethings K80 after using for long periods.
- After getting PRO, I didn't get T4 yet, only P100. And I haven't used as much GPU recently.

```
Sun Apr 18 01:39:13 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.67       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P0    25W / 250W |      2MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by lopho** [comment]
> I never got V100 .. it's always set to Off
> 
> Tesla V100-SXM2... Off
> 
> For me, even with or without paying for Pro, it's NVIDIA ..

The "Off" means that Persistence-Mode is off. When it says V100, you got a V100.

**Comment by eduardo4jesus** [comment]
I am Colab PRO user and I just got allocated K80. A bit upsetting given that it has  about a week I don't use Colab GPUs.

**Comment by mmoghadam11** [comment]
> I am Colab PRO user and I just got allocated K80. A bit upsetting given that it has about a week I don't use Colab GPUs.

me too ):

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback

**Comment by jacquesg** [comment]
I'm cancelling my Colab Pro+ account after just a few hours. The most frustrating part of this is that Google is obstructive in providing a refund.

**Comment by jacquesg** [comment]
![image](https://user-images.githubusercontent.com/3534453/150632902-83c0bdf9-7d45-404c-929c-7261035278da.png)

**Comment by jacquesg** [comment]
Super clever and what I've now become accustomed to, bait-and-switch tactics. I got reasonable GPU's with the free version, moving to the Pro+ version, still got the same and sometimes worse. This is at 1AM in the morning...
