### ISSUE TITLE
Markdown preview line in code cell

### ISSUE THREAD

**Issue by LeData** [googlecolab/colabtools#185]
Some code cells have a dotted line in the middle, which should be appearing in text cells only.

EDIT: windows 8.1, Chrome 67.0.3396.79

**Comment by blois** [comment]
Is that the line-length indicator which appears when the cell has longer lines?

**Comment by LeData** [comment]
Indeed. I understand now that it is the 80 character line. It is not obvious from the design, as it reuses the graphic code of the markdown preview.
