### ISSUE TITLE
"Shared Drives" mounted as "Shareddrives"

### ISSUE THREAD

**Issue by kubaraczkowski** [googlecolab/colabtools#1850]
Bug report for Colab: http://colab.research.google.com/.

We use Colab for collaborating on Notebooks developed in two places - on a Mac and on Colab.
Previously it was possible to mount the drive as "/Volumes/GoogleDrive" in colab, which then matched the Mac GoogleDriveFileStream location.
Currently, however, the "/Volumes/GoogleDrive/Shared Drives" on mac is visible in colab as "/Volumes/GoogleDrive/Shareddrives" (no space). That breaks all file links :/

- Describe the current behavior:
"Shared Drives" is mounted as "Shareddrives" (no space). While logical, this breaks file path compatibility, at least between a Mac and Colab

- Describe the expected behavior:
Either mount as "Shared Drives", or - add an optional flag to do so to .mount()

**Comment by colaboratory-team** [comment]
Colab has an invisible "Shared drives" redirect in place, so including or omitting the space should work equivalently.
