### ISSUE TITLE
PWD and pwd

### ISSUE THREAD

**Issue by Zalake** [googlecolab/colabtools#1853]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
$PWD has ".../My Drive/..." pwd is ".../MyDrive/..."
- Describe the expected behavior:
both PWD and pwd should be same, the space between "My Drive" causes a lot of bugs
- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by colaboratory-team** [comment]
The space is optional; both including and excluding it should work for file/directory access.
Of course if you have a e.g. string comparisons in play, things might get confusing.
If you still think you're seeing a bug, please share a minimal self-contained notebook demonstrating it.
