### ISSUE TITLE
Plotly blank graph

### ISSUE THREAD

**Issue by hemnathmouli** [googlecolab/colabtools#186]
Colab doesn't support offline plotly iplot. Just an example code:

```
plotly.offline.iplot(choromap)
```

or
```
iplot(choromap)
```

Just gives an empty or blank output with some height. That works fine on jupyter notebook.

**Comment by craigcitro** [comment]
Yes, colab iframes each output, which means that some code will require modification.

A sample of using plotly is [in the docs](https://colab.research.google.com/notebooks/charts.ipynb#scrollTo=mlPjkAty7kcK).
