### ISSUE TITLE
Colab file tray not working

### ISSUE THREAD

**Issue by SamanthaHassal** [googlecolab/colabtools#1860]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: File upload not working (corrupting large non-code files in upload, failed upload tabs not closing when I hit the "close" icon) even after factory reset of runtime

- Describe the expected behavior: my code should read the file instead of spitting out "
TypeError: '>=' not supported between instances of 'NoneType' and 'int'" (this code has worked before, which makes me think that it's an issue with how colab is handling the file), failed uploads should close after clicking the icon

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/drive/19wAuXCFBhIE2ApozvwIIe3N1PeoYifXL?usp=sharing

**Comment by blois** [comment]
Does this reproduce for all files being uploaded or just specific files?

I'm curious if the issue also repros with:
```
from google.colab import files
files.upload()
```

Or IPyWidgets' File Upload widget: https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#File-Upload

**Comment by SamanthaHassal** [comment]
OK, @blois , I tried the issue with a different file. I have the same problem. 

I definitely suspect this is an issue with colab's file tray. 

Have no idea where it came from. Ran this code ~2 weeks ago, no issues.
