### ISSUE TITLE
When printing colab file to pdf, all output sees to go to the first page only, so when the first page is full, the rest of the input is cut off, and not continued on the second page

### ISSUE THREAD

**Issue by loomdawg** [googlecolab/colabtools#1866]
code is cut off on first page, nothing on second page or anything after.  I expect there to be a page break.

I'm on firefox with ubuntu

**Comment by JOOZOO20** [comment]
Hello, I am experiencing the same issue with printing to PDF in Colab using Chrome on Windows. 
Could you please suggest a solution or workaround?
