### ISSUE TITLE
Cell magic `%%bigquery` not found

### ISSUE THREAD

**Issue by stewart-r** [googlecolab/colabtools#187]
Encountering the above error message when trying to use the `%%bigquery` cell magic.

Reproduced in a new notebook following exactly the [example in the docs](https://colab.research.google.com/notebooks/bigquery.ipynb#scrollTo=nFF9Wz1CAyVI):

![image](https://user-images.githubusercontent.com/5658894/41358650-bb551f42-6f20-11e8-8a53-11ca41dd772a.png)

**Comment by craigcitro** [comment]
I can't repro this; is there a chance you'd done a `pip install` of something in another notebook before opening this one?

**Comment by stewart-r** [comment]
hi, Yes, I'd tried to install some packages. Having returned to the notebook several hours later, it is now working as normal. Happy to close this off. Thanks for coming back so swiftly
