### ISSUE TITLE
provide a transition period for python3.6

### ISSUE THREAD

**Issue by RussTedrake** [googlecolab/colabtools#1874]
Today's switch from python3.6 to python3.7 came as a complete surprise to me.  Was it announced anywhere? 

Request: Can you provide a transition grace period with continued support for runtime types with python3.6 ?  

FTR -- This took down all of the software for my graduate course the night before the first colab assignment was due (and spoiled today's interactive lecture).  I've been trying everything I can to either upgrade all of our dependencies to 3.7 or downgrade a particular runtime.

**Comment by craigcitro** [comment]
Sorry about the breakage and its poor timing. 😞 

Unfortunately, there's no way to support multiple python versions at once right now, so when updates happen (for python *or* library versions), they happen all at once. We'd like to make this more flexible one day, but there's nothing in place at the moment.

**Comment by truboxl** [comment]
Ubuntu 18.04 doesn't even have python3.7 as the default... This breaks a lot of things... especially PPA handling...
```
!dpkg -l python3

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  python3        3.6.7-1~18.0 amd64        interactive high-level object-ori
```
```
!add-apt-repository

Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 12, in <module>
    from softwareproperties.SoftwareProperties import SoftwareProperties, shortcut_handler
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 67, in <module>
    from gi.repository import Gio
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from 'gi' (/usr/lib/python3/dist-packages/gi/__init__.py)
```
Band-aid for most problems:
```
!update-alternatives --set python3 /usr/bin/python3.6
```

**Comment by jamiesnape** [comment]
> Sorry about the breakage and its poor timing. 😞

@craigcitro How much notice did you give and where did you publicize this change in advance? Changes happen, but Google is usually good at publicizing breaking changes to its users and developers in advance.

**Comment by craigcitro** [comment]
@truboxl thanks for the report! `add-apt-repository` should be up and running again.
