### ISSUE TITLE
Colab Problem import repositories (new -- started today)

### ISSUE THREAD

**Issue by davetew** [googlecolab/colabtools#1875]
A new problem developed today when importing a repository in a Colab notebook that I have used many times over the past ~month.
 
When attempting to import the repository using `!apt-add-repository -y ppa:speth/cantera`, I get an error message stating that there is an issue related to `gi`--a python module that seems to be employed by `apt-add-repository`.
 
> `ImportError: cannot import name '_gi' from 'gi' (/usr/lib/python3/dist-packages/gi/__init__.py)`
 
A link to a workbook that contains an example of the problem is below. 
 
[Example Notebook](https://colab.research.google.com/drive/1NCga2pWSGfs0Ix-sS-Axvn4jJnhMEMQL?usp=sharing)
 
Thank you for any help that you might be able to offer.
 
Regards,
Dave
PS:  The problem occurs in both Safari & Chrome.

**Comment by craigcitro** [comment]
Thanks for the report -- this was related to the python 3.7 update, and we're working on rolling out a fix already. It should land shortly, but I'll update this issue when it does.

**Comment by craigcitro** [comment]
Also, as a short-term workaround until the fix is live, you can do

```
!python3.6 /usr/bin/add-apt-repository ...
```

and it'll work just as before.

**Comment by drew-parsons** [comment]
The most appropriate and simplest fix is to upgrade the Colab host environment from Ubuntu bionic 18.04 to Ubuntu groovy 20.04.

**Comment by craigcitro** [comment]
This should be fixed -- if you either reconnect or (if you've got a session running) `Factory reset runtime`, you should once again have a working `add-apt-repository`.

**Comment by davetew** [comment]
Thank you very much.  The fix did seem to resolve the issue with add-apt-repository.  However, when I try to import the module that is installed from the repository, it fails with a somewhat similar error.

> `(ModuleNotFoundError: No module named 'cantera._cantera')`

`_cantera.pxd` does indeed seem to be where is should be in  `/usr/lib/python3/dist-packages/cantera`; however, the import fails.  This import also worked yesterday (2/23).

A link to an updated workbook with the additional import statement is below
[Cantera Notebook](https://colab.research.google.com/drive/1NCga2pWSGfs0Ix-sS-Axvn4jJnhMEMQL)

Thanks again for any additional help that you might be able to offer!

Regards,
Dave

**Comment by craigcitro** [comment]
It looks like the ubuntu installation you're following only works with 3.6, unfortunately.

I don't know anything about cantera; I'd try asking upstream.

**Comment by francesco-ballarin** [comment]
> The most appropriate and simplest fix is to upgrade the Colab host environment from Ubuntu bionic 18.04 to Ubuntu groovy 20.04.

@drew-parsons @craigcitro I agree with that. Are there any plans to upgrade to 20.04?

**Comment by colaboratory-team** [comment]
#1880 tracks the 20.04 update.

**Comment by davetew** [comment]
Thank you very much for the very quick responses!  Regards, Dave

On Feb 24, 2021, at 2:05 PM, Craig Citro ***@***.******@***.***>> wrote:



Also, as a short-term workaround until the fix is live, you can do

!python3.6 /usr/bin/add-apt-repository ...


and it'll work just as before.
