### ISSUE TITLE
Install libtorrent and Initialize Session

### ISSUE THREAD

**Issue by iangabre** [googlecolab/colabtools#1877]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-393135217c75> in <module>()
      1 get_ipython().system('apt install python3-libtorrent')
      2 
----> 3 import libtorrent as lt
      4 
      5 ses = lt.session()

ModuleNotFoundError: No module named 'libtorrent'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

COMO RESOLVE ISSO? 
NÃO ESTOU CONSEGUINDO MANDAR MEUS ARQUIVOS TORRENT PARA O DRIVE DEVIDO A ESSE ERRO
POR FAVOR ME AJUDEM!!!!!!!!!!!!!!!!!!

**Comment by iangabre** [comment]
USEI O GOOGLE

**Comment by MrSalehSalem** [comment]
put the next two lines before the first line. 

!python -m pip install --upgrade pip setuptools wheel
!python -m pip install lbry-libtorrent

**Comment by teck45** [comment]
As I understand peer to peer sharing (torrent) is forbidden on colab. I can recommend to follow google terms of service. For downloading something upload it to google drive from computer or use wget command from colab.
