### ISSUE TITLE
Error installing cartopy in google colab

### ISSUE THREAD

**Issue by st12343** [googlecolab/colabtools#1884]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
the cartopy library installation proposed in "Snippets: Importing libraries" notebook doesn't work anymore :
**!apt-get -qq install python-cartopy python3-cartopy
import cartopy**

I have the follonwing error for the import of cartopy._crs module import :
**---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-b779dcb0167b> in <module>()
      1 get_ipython().system('apt-get -qq install python-cartopy python3-cartopy')
----> 2 import cartopy

1 frames
/usr/lib/python3/dist-packages/cartopy/crs.py in <module>()
     34 import six
     35 
---> 36 from cartopy._crs import CRS, Geocentric, Geodetic, Globe, PROJ4_VERSION
     37 import cartopy.trace
     38 

ModuleNotFoundError: No module named 'cartopy._crs'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------**

- Describe the expected behavior:

until today the cartopy library installation proposed in "Snippets: Importing libraries" notebook works fine
!apt-get -qq install python-cartopy python3-cartopy
import cartopy

- The web browser you are using (Chrome, Firefox, Safari, etc.):
under chrome.

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/notebooks/snippets/importing_libraries.ipynb#scrollTo=Zq68DSY2rP2W

**Comment by craigcitro** [comment]
Thanks for the report! We'll get that snippet updated.

In the interim, you can `!pip install cartopy` and you should be up and running. Let us know if that doesn't work.

**Comment by nekot22** [comment]
I also experienced it.
I'm trying to use xraylib and I was able to install it until last week.
But I couldn't import today.
It seems that the one installed by ( !apt-get ) cannot be imported.

**Comment by st12343** [comment]
Hello,
Thank you for the quick answer. The `!pip install cartopy` and then import cartopy work well for geospatial data manipulation.

**Comment by craigcitro** [comment]
`cartopy` snippet should also be updated now.
