### ISSUE TITLE
Timeout issue while mounting Google Drive to Google Colab

### ISSUE THREAD

**Issue by varundhingra004** [googlecolab/colabtools#1885]
Bug report for Colab: http://colab.research.google.com/.

- Current Behavior:
 I am getting a timeout error when I try to mount my Drive to Colab. I copy. and paste the auto generated code and then the system hangs until timeout.

- Expected behavior:
  The mount should be successful after pasting the auto generated code.

- The web browser used: Chrome and Firefox

- Link : https://colab.research.google.com/drive/1ZiMpVDI7BORzbHLkX96WbF-RBd0FePEC?usp=sharing

- Extra Information:

Whenever I try to mount my drive onto colab I get this error. Earlier things were smooth but since the past week I have been consistently getting this error.

All discussion posts have given 2 solutions

It is due to issue in the file structure because there are many files on drive.
The copy function for the auto generated token does not work so type manually.

I do not think case 1 is the issue for me because even though the drive has many folders and files, my team members do not encounter any issues while mounting the same drive that is shared with them. I am the. Only person with the issue. Also, the mounting for the same drive worked before.

For case 2,  I tried ti manually type the auto generated token but it makes no difference.

Any help or advice will be appreciated.

**Comment by colaboratory-team** [comment]
You can try passing e.g. `timeout_ms=3600000` to the `drive.mount()` function and see if that avoids the `TIMEOUT`.

I don't think it's possible to share your top-level "My Drive", so my guess is that your teammates' ability to mount shared drives does not mean you don't have too many files/folders in the root of your Drive.

**Comment by varundhingra004** [comment]
Hello,

Thanks for your response.

I passed the parameter but Timeout is not avoided.

I do not have any other files on my Drive except for the drive that my team and I share. Out of 15 Gb, 5 Gb is still free in the drive.

Thanks,
Varun.

**Comment by colaboratory-team** [comment]
There's nothing in https://drive.google.com/drive/my-drive ?  That's very surprising then.

**Comment by varundhingra004** [comment]
The only content of My Drive is the folder that is shared by the entire team.

**Comment by colaboratory-team** [comment]
The notebook linked in the original report now shows a successful mount. Did the problem go away on its own?

If not, you might also try in an incognito browser window.

**Comment by varundhingra004** [comment]
I made a new gmail account. It worked then.
