### ISSUE TITLE
Can't connect for hours

### ISSUE THREAD

**Issue by smadarlom** [googlecolab/colabtools#1887]
Hello
I'm getting errors for hours
Hope to be able to work with your machine soon.
I want to pay, but there is no option for Israeli.
Would like to find a way to pay you.
Thank you.

RuntimeError                              Traceback (most recent call last)
<ipython-input-3-9e8cf0629a39> in <module>()
     59     print(' translated to:', text)
     60   tx = clip.tokenize(text)
---> 61   txt_enc = model_vit.encode_text(tx.cuda()).detach().clone()
     62   if dual_model is True:
     63     txt_enc = torch.cat((txt_enc, model_rn.encode_text(tx.cuda()).detach().clone()), 1)

/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py in _lazy_init()
    170         # This function throws if there's a driver initialization error, no GPUs
    171         # are found or any other error occurs
--> 172         torch._C._cuda_init()
    173         # Some of the queued calls may reentrantly call _lazy_init();
    174         # we need to just return without initializing in that case.

RuntimeError: No CUDA GPUs are available

**Comment by dimkiriakos** [comment]
I'm waiting for hours and still allocating even without gpu.

**Comment by smadarlom** [comment]
**Now there are errors. I don't know how to deal with them... anyone?**





/content/aphantasia/clip_fft.py in <module>()
     14 import clip
     15 os.environ['KMP_DUPLICATE_LIB_OK']='True'
---> 16 import pytorch_ssim as ssim
     17 
     18 from utils import pad_up_to, basename, img_list, img_read

ModuleNotFoundError: No module named 'pytorch_ssim'


---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
