### ISSUE TITLE
Unable to download weights

### ISSUE THREAD

**Issue by ayush1999** [googlecolab/colabtools#189]
I trained a Keras model in Google Colab. However, now I want to download the model weight file to my local system.
```
from google.colab import files
files.download("model-weights.h5")
```

The cell runs for a few seconds, but after running successfully, it doesn't download the weight file anywhere. What should I do to download the file? I am using Firefox browser.

**Comment by blois** [comment]
Browser info/version?

Can you download any other files? What is the file size of this file?

**Comment by ayush1999** [comment]
I'm using Mozilla Firefox v60.0 (64 bit), on Ubuntu 16.04. The size of the file is around 16.5 MBs. No, I'm not able to download any other files.

**Comment by colaboratory-team** [comment]
Please reopen if you're still observing this problem, and please do note any error messages on the Javascript console. 

Browser extensions are also a common cause of these issues, so it may be helpful to see if the problem persists when extensions are disabled.
