### ISSUE TITLE
Upgrading torchtext to v0.9.0

### ISSUE THREAD

**Issue by zhangguanheng66** [googlecolab/colabtools#1892]
Hi folks,

We released a new torchtext v0.9.0.

The wheel link is:

https://download.pytorch.org/whl/torchtext-0.9.0-cp36-cp36m-linux_x86_64.whl

If you require wheels for Python 3.7 / 3.8, you can find the links here: [download.pytorch.org/whl/torch_stable.html](download.pytorch.org/whl/torch_stable.html)

We're looking to having it updated in Colab.

Thanks very much.

cc'ing @colaboratory-team

Similar to #1891

**Comment by craigcitro** [comment]
torchtext should be updated.
