### ISSUE TITLE
Error en la conexion entre Colab y Drive

### ISSUE THREAD

**Issue by DanielEstebanGalindo** [googlecolab/colabtools#1893]
Intento conectar mi script de Colb con Drive de las dos formas mas conocidas (mediante la interfaz y mediante el siguiente código) pero me redirige la conexión a Drive File Stream. La segunda forma y el erro es la siguiente: 

from google.colab import drive
drive.mount('/content/drive')

Enter your authorization code:
######################
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-d5df0069828e> in <module>()
      1 from google.colab import drive
----> 2 drive.mount('/content/drive')

/usr/local/lib/python3.7/dist-packages/google/colab/drive.py in mount(mountpoint, force_remount, timeout_ms, use_metadata_server)
    266       raise ValueError(
    267           str(domain_disabled_drivefs) +
--> 268           ': https://support.google.com/a/answer/7496409')
    269   if not wrote_to_fifo:
    270     with open(fifo, 'w') as fifo_file:

ValueError: The domain policy has disabled Drive File Stream: https://support.google.com/a/answer/7496409

**Comment by colaboratory-team** [comment]
Last line of the error message is saying what's wrong and link to how to fix it (must be done by your domain's administrator).
