### ISSUE TITLE
diff older revision and other notebook shoes latest revision

### ISSUE THREAD

**Issue by eyaler** [googlecolab/colabtools#1894]
1. file->revision history
2. open revision in colab
3. tools->diff notebooks

you get a diff using the lastet revision instead of the chosen one. you need to manually change to colab url in the diff to the one of the revision.

**Comment by craigcitro** [comment]
Thanks for the report! Indeed, unfortunately you'll need to manually tweak the URI for now, as you've discovered.

Tracked internally as b/181992333.

**Comment by craigcitro** [comment]
OK, this should be fixed.

Thanks again fro the report!
