### ISSUE TITLE
I can not use [!apt install]

### ISSUE THREAD

**Issue by nekot22** [googlecolab/colabtools#1896]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

I tried 
 !apt install python-cartopy python3-cartopy
 import cartopy

I need to use [!apt install].

This is for illustration purposes.
 https://colab.research.google.com/drive/1mMgHZZbvObSknByhr3PMro12wO83NnJC?usp=sharing

**Comment by craigcitro** [comment]
For cartopy, you don't need apt -- you can just `!pip install cartopy`.
