### ISSUE TITLE
Colab not installing latest version of Pandoc package

### ISSUE THREAD

**Issue by FowadIjaz** [googlecolab/colabtools#1897]
- Describe the current behavior:
When installing pandoc on google colab, version 1.19.2.4 is installed, which is a release from 2017. 

- Describe the expected behavior:
The latest Release, which is 2.11, should have been installed. Specifying the version number gives: 

`ERROR: Could not find a version that satisfies the requirement pandoc==2.11 ( from versions: listOfVersions)
`

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1_9D0MyqRQx1VOgp7YEK9ZviNzbThRkBF?usp=sharing

**Comment by craigcitro** [comment]
The core issue you're hitting is that the version of `pandoc` in the version of ubuntu we use is old; that's out of our hands. https://pandoc.org/installing.html#linux has instructions for how to install a newer version.

The `pip` error is because `pip` (which is the *python* package manager) doesn't know anything about upstream pandoc versions; the fact that it works at all is a little surprising, but is because there is a python package that wraps pandoc (https://pypi.org/project/pandoc/).

**Comment by FowadIjaz** [comment]
> The core issue you're hitting is that the version of `pandoc` in the version of ubuntu we use is old; that's out of our hands. https://pandoc.org/installing.html#linux has instructions for how to install a newer version.
> 
> The `pip` error is because `pip` (which is the _python_ package manager) doesn't know anything about upstream pandoc versions; the fact that it works at all is a little surprising, but is because there is a python package that wraps pandoc (https://pypi.org/project/pandoc/).

Thanks, I was wondering why Pandoc's version numbers weren't lining up. So that means the version number for the python package that wraps pandoc is different from the Pandoc version... that makes sense.

I'm still not quite following the procedure for installing what steps I need to do to install the latest version however. Will the linux commands work in Colab? Or were you referring to how to install the latest version locally?

**Comment by craigcitro** [comment]
Yes, you can run any linux command by adding a `!` in front of it; this did the trick for me:

```
!curl -OL https://github.com/jgm/pandoc/releases/download/2.11.4/pandoc-2.11.4-linux-amd64.tar.gz
!tar xvzf pandoc-2.11.4-linux-amd64.tar.gz --strip-components 1 -C /usr/local
```
