### ISSUE TITLE
Stuck on allocating and after some time I get this. Is colab pro gonna fix this?

### ISSUE THREAD

**Issue by cmesa121** [googlecolab/colabtools#1898]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

![image](https://user-images.githubusercontent.com/69813510/110510662-55d37480-80fb-11eb-8699-f6a8f8c68a50.png)

**Comment by nehelmalhotra** [comment]
Having the same issue as well.

**Comment by craigcitro** [comment]
We believe any service issues are now mitigated, so I'm going to mark this as fixed. Sorry about the interruption!
