### ISSUE TITLE
GPU hardware accelerator is selected but absolutely no performance boost observed

### ISSUE THREAD

**Issue by tejasa97** [googlecolab/colabtools#191]
I'm running the MNIST program on Colab. I've run it in the past on Colab using the GPU and it trained pretty fast. Now if I try doing the same it runs rather slow, very slow, like it was actually running on the CPU only. Tried this several times with restarting the runtime etc, but to no avail. Why?

**Comment by colaboratory-team** [comment]
Sorry, we're not able to diagnose issues with libraries used within Colab. I'd recommend asking a question on a more general-purpose forum like StackOverflow to attract the attention of domain experts.
