### ISSUE TITLE
PRO - NO GPU

### ISSUE THREAD

**Issue by Fearless1989** [googlecolab/colabtools#1912]
Today I paid for the pro version but I can't use the GPU ! 
![fsdfsdfsdfsdfsdfs](https://user-images.githubusercontent.com/59699635/111620652-ad569c00-87ef-11eb-8165-f9d774fc314f.png)
This is a mockery of people. Where can I get my money back. Everything about this company is confused and they don't have a simple support.

**Comment by tiger-jie** [comment]
I have the same question.
