### ISSUE TITLE
Output in cell disappears immediately after executing in google colab notebook

### ISSUE THREAD

**Issue by SaurabhThakre** [googlecolab/colabtools#1914]
`from matplotlib import pyplot as plt `

`x = [5, 2, 9, 4, 7] `
`y = [10, 5, 8, 4, 2]` 
`plt.plot(x,y)` 
`plt.show()`

When I try to execute the above code in google colab notebook, its output appears for milliseconds and disappears immediately and does not remains. This behaviour only occurs when trying to plot the graph using matplotlib. But this does not happen when I use a print statement, the output does not disappear like the graph for the above plot.

![colab_matplotlib](https://user-images.githubusercontent.com/46682857/111735120-7b9e0d80-88a1-11eb-89a0-8cc62161db53.gif)

I have recorded and added this gif, which shows the above-described problem in my colab.

**Comment by SaurabhThakre** [comment]
[https://i.stack.imgur.com/onVPn.gif](url)

Link for :
I have recorded and added this gif, which shows the above-described problem in my colab.

**Comment by craigcitro** [comment]
Thanks for the report!

I can't seem to reproduce this, which makes me think one of two things may be in play:
* previous code you've run in this notebook causing trouble; can you repro if you run just that code in a fresh notebook?
* a chrome extension causing trouble; can you repro in an incognito window?

**Comment by SaurabhThakre** [comment]
As you told I have tried this in a fresh notebook as well as in an incognito window, it still gives the same problem.

**Comment by SaurabhThakre** [comment]
I have removed all my extensions from chrome and now it shows the output properly.
Some extension was causing this problem.
Thanks @craigcitro

**Comment by blois** [comment]
If you are able to narrow down which extension caused the issue please let us know in case others run into this later. Thanks!

**Comment by SaurabhThakre** [comment]
It was Urban VPN extension.

**Comment by Mouaadoussous** [comment]
@SaurabhThakre  Thank you so much , i tried lot of solutions nothing worked ... until i removed urban VPN extension !!!
