### ISSUE TITLE
IOPub data rate exceeded.  Where can I change the configuration to read a cvs file on GoogleDocs?

### ISSUE THREAD

**Issue by johngage** [googlecolab/colabtools#192]
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)  is too low, apparently, for my notebook to read a small cvs vile.
Want to set it to: 
--NotebookApp.iopub_data_rate_limit=10000000.0

How to do this?

**Comment by blois** [comment]
This data rate applies to the amount of data which is being sent from the kernel to the browser for display. Generally if you're hitting this limit you are printing large amounts of data to the console which will then be saved and displayed in the notebook file.
