### ISSUE TITLE
Improvement Suggestion - Form Dropdown list from Pandas Columns

### ISSUE THREAD

**Issue by gaciap** [googlecolab/colabtools#1924]
It would be perfect to import a list of Dropdown options from the list variable.
e.g.

> var = df.columns
> dropdown = var[0] #@param var {type:"raw"}

or

> dropdown = df.columns[0] #@param df.columns {type:"raw"}

Sergio Lucero suggested the following form on [stackoverflow.com](https://stackoverflow.com/questions/49165220/the-new-form-feature-in-google-colaboratory)
> dropdown = df['col1'][0] #@param df.col1.unique()

**Comment by blois** [comment]
[IPyWidgets](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#Select) are great for this-
https://colab.research.google.com/gist/blois/71aa984fdab9a0b2ef6c9438dc06382e/altair-stock-comparison.ipynb
