### ISSUE TITLE
Downgrade python version in google colab 3.7 to 3.6

### ISSUE THREAD

**Issue by Thushar-marvel** [googlecolab/colabtools#1926]
I  am working on tensorflow api object detection Faster R CNN model.I had trained it in 2 months earlier (jan).All worked well.But now while I train it ,it shows fatal python error.,so wanted to downgrade python version from 3.7 to 3.6.How to proceed for this ?

**Comment by craigcitro** [comment]
This isn't possible, unfortunately.
