### ISSUE TITLE
Sorry, no backend available. Try later. ColabPro

### ISSUE THREAD

**Issue by killamah** [googlecolab/colabtools#1928]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by killamah** [comment]
Hi , i bought ColabPro for my account , but when i run a script i get : Sorry, no backend available. Try later.

**Comment by thanhlt998** [comment]
I have Colab Pro subcription but now i also faced with "Failed to assign a backend! No backend with GPU available. Would you like to use a runtime with no accelerator?" error. I cannot connect to backend with GPU and without GPU.
