### ISSUE TITLE
Adding a GPU/TPU timer on Colab

### ISSUE THREAD

**Issue by gchhablani** [googlecolab/colabtools#1930]
Hi :)

This is a feature request. I apologize if this isn't the right place for this.

It would be nice to have a timer for GPU/TPU time on Free as well as Pro version. Usually when we train models, we have a time estimate for model training. Often it happens that the GPU session ends and all the training/time spent (unless save using checkpoints) goes in vain. If there was a timer, the user will be able to prepare for it in advance.

Thanks

**Comment by Tikquuss** [comment]
It would be better to know when the session is going to end so that we know how to better preserve our data.
