### ISSUE TITLE
my google collab screen expanded. It is very hard to view the output of the screen. The resolution is too big. And yet it was not like this before.

### ISSUE THREAD

**Issue by matovu-farid** [googlecolab/colabtools#1933]
The current behavior:
- The whole screen was magnified. 

The expected behavior:
-The screen was smaller before

- The web browser Chrome

- Link- https://colab.research.google.com/drive/1nLBI0Dpiv27bfRsx_0mb3LdbXRPaW3Rs?usp=sharing

**Comment by blois** [comment]
Perhaps browser zoom level changed on the page? We are not aware of any Colab changes which would lead to this.
