### ISSUE TITLE
mount my drive to google colab

### ISSUE THREAD

**Issue by Habdo89** [googlecolab/colabtools#1935]
Hi,
I am trying to unzip a file in my drive using google colab 
I already mounted it but when !unzip, it can not see the folder
Is there anything I can do to make it recognise the folder, unzip and load it to my note book??
Thanks

**Comment by teck45** [comment]
try to upload you file to your google drive, then mount google drive to colab and you will unzip it without problems. You can also upload file directly to colab, just clikc on file button to open this window look in left top quadrant. 3rd or 4th button.
