### ISSUE TITLE
Disconnects while running code.

### ISSUE THREAD

**Issue by FatSandwich** [googlecolab/colabtools#1936]
I was running code and it gets disconnected, which never happened before. It's happening with all of my ipynb files. Is there a server issue?

**Comment by FatSandwich** [comment]
It's still happening. I can't run anything for over 30 - 1 min.

**Comment by jshriver** [comment]
Its been like this for 2 weeks for me.  Ended up cancelling my pro account and trying 1-2x a week to see if its fixed, nothing yet.

**Comment by FatSandwich** [comment]
It's annoying and never happened to me, except for yesterday and today. Hope it gets fixed!

**Comment by Appolo-11** [comment]
I have the same problem!!!! I didn't use Colab that much to restrict me. But minute - is my limit to stable 
Colab connection. It happens also on the account, where I've never used Colab before!!!!

**Comment by FatSandwich** [comment]
I'm going to try using another platform like Docker which is free and maybe easier.

**Comment by FatSandwich** [comment]
Seems like it's fixed, but I don't think it's reliable.
