### ISSUE TITLE
Auto copy error due to mouse click

### ISSUE THREAD

**Issue by src-by-hannah** [googlecolab/colabtools#1940]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: 
When I click the mouse on the code block, the code of the cell is automatically copied and pasted. This has been going on for weeks. I'm having a hard time getting tangled in my code due to auto copy paste. We hope that this error will be resolved as soon as possible.

- Describe the expected behavior:
When I click the mouse within the code block, it would be nice if the code was not automatically copied and pasted.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by angelkamt-eat** [comment]
I'm having the exact same issue here.

Device: Android Lenovo Tablet P12
Browser: Brave
