### ISSUE TITLE
I can not connect to CPU after upgrading to Colab Pro.

### ISSUE THREAD

**Issue by druckservice** [googlecolab/colabtools#1941]
I can not connect to CPU after upgrading to Colab Pro.
Anything work if I use other google account and connect to colab (not colab Pro)from the same Laptop.

![colab](https://user-images.githubusercontent.com/13498965/113343765-87251600-9330-11eb-85ab-e854090440c3.png)

**Comment by miguelalejo** [comment]
Same issue using Colab pro

**Comment by sander2825** [comment]
same issue
