### ISSUE TITLE
Where did File->Update Drive preview go?

### ISSUE THREAD

**Issue by DevinShanahan** [googlecolab/colabtools#1943]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
I used to be able to use `File->Update Drive preview` to update the preview shown in Google Drive. This option is no longer available and my previews are very out of date. It is especially confusing because I changed the file name and the name shown at the top of the preview does not match the name of the file. I have looked within Drive for an option to update but not seeing anything there either. I am already sharing these files so I do not want to make a copy (if that is a possible solution).

![image](https://user-images.githubusercontent.com/17952172/113429040-1a903280-9395-11eb-912d-c1deb2904b0b.png)

- Describe the expected behavior:
I would expect either: 
 a) this option is made available again 
 b) the preview is updated automatically upon saving

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

**Comment by blois** [comment]
You should still be able to use the command palette (ctrl-shift-p) -> Update Drive preview

**Comment by blois** [comment]
Also curious what you'd think about using the last image output as the Drive preview, if there is an image output in any of the cell outputs.

**Comment by DevinShanahan** [comment]
Thanks! I wasn't aware of the command palette, looks very useful.

As far as the image, it's not something I would make use of currently. Similar to the command palette, it's also something I would likely not be aware of. I'm imagining someone also might want, for example, the first image to be the preview and placing it again at the end could look strange. 

Would it be possible to add a section in Settings for the Drive instead? Maybe has the option to upload an image for the preview, a button to update the preview, etc.
