### ISSUE TITLE
I can't delete my empty folders

### ISSUE THREAD

**Issue by jerrel-theos** [googlecolab/colabtools#1945]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: It is saying that the folder must be empty to delete even though it is empty already.

- Describe the expected behavior: It should be able to delete the folder well.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not a screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):  https://colab.research.google.com/drive/13CAbTBjQGiaswMU79yi7sf_dVUxFfQjX?usp=sharing

**Comment by teck45** [comment]
you can try command, just copy path of folder in file manager and
!rm -rf path/to/folderyouwant/todelete
