### ISSUE TITLE
Cannot connect to GPU backend. How long it will be working normally again? You cannot currently connect to a GPU due to usage limits in Colab. looking for more information As a Colab Pro subscriber, you get a higher limit of usage compared to non-subscribers. However, the usage is not limitless.  To get the most out of Colab Pro, don't use the GPU when it's not needed for your work.

### ISSUE THREAD

**Issue by quangjimmynguyen** [googlecolab/colabtools#1951]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by SunHaoOne** [comment]
I have been limited for almost a week, and I am also a colab pro user. I have only use this lab for four days.
