### ISSUE TITLE
Create new account, have just paid subscription for Colab Pro. But no GPU available???

### ISSUE THREAD

**Issue by giaabaoo** [googlecolab/colabtools#1953]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by cperry-goog** [comment]
Closing due to staleness. File a new bug with reproducible steps if this is an issue.
