### ISSUE TITLE
Can't install conda

### ISSUE THREAD

**Issue by EByrdS** [googlecolab/colabtools#1956]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I installed conda using: 
`!wget https://repo.anaconda.com/archive/Anaconda3-5.2.0-Linux-x86_64.sh`
`!bash Anaconda3-5.2.0-Linux-x86_64.sh -bfp /usr/local`
I used to be able to create an environment using `!conda install -n root _license -y` and then `!conda create --name my_env python=3.7 -y`. But now it throws an error: 
`InvalidVersionSpec: Invalid version '4.19.112+': empty version component`

- Describe the expected behavior:
The environment should be created seamlessly, and should be available to use with 
```bash
%%bash
source activate my_env
```

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Microsoft Edge.

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/11FfvouepU9JFXKyILfnt1jzFH9JjHLx3#scrollTo=2luBZlLX2GEa

The problem was asked in StackOverflow and I provided a possible answer, but it does not work anymore, another similar error is raised with `Invalid version '=2.7'`. [StackOverflow question and answer](https://stackoverflow.com/questions/66956203/conda-colab-error-collecting-package-metadata-current-repodata-json-failed-in/66993094#66993094)

**Comment by korakot** [comment]
5.2.0 is for python 3.6

To update to python 3.7, you can use miniconda 4.6.14

```python
# Newer colab need py37, download 67 MB
!wget -O mini.sh https://repo.anaconda.com/miniconda/Miniconda3-4.6.14-Linux-x86_64.sh 
!bash ./mini.sh -b -f -p /usr/local
!conda install -q -y --prefix /usr/local python=3.7.3 # add your_library
import sys
sys.path.append('/usr/local/lib/python3.7/site-packages/')
# import your_library 
```
