### ISSUE TITLE
Mathjax throws Math processing error at correct bmatrix expression.

### ISSUE THREAD

**Issue by IlIlIlIl** [googlecolab/colabtools#196]
I encounted `Math processing error` at correct bmatrix expression in Colaboratory text cells.

**Screenshot**

![screenshot from 2018-06-28 02-19-49](https://user-images.githubusercontent.com/11178403/41989297-c52c99fa-7a79-11e8-8bf0-04362e32af83.png)

**bmatrix expression**

```
$\Delta {\bf E} = \nabla^2 {\bf E} = (\nabla \cdot \nabla) \begin{bmatrix} E_x \\ E_y \\ E_z \end{bmatrix} = \begin{bmatrix} {\bf div}({\bf grad}(E_x)) \\ {\bf div}({\bf grad}(E_y)) \\ {\bf div}({\bf grad}(E_z)) \end{bmatrix}$

$\begin{bmatrix} a & b \\ c & d \end{bmatrix}$
```

I checked correctness of the above code in [here](https://www.mathjax.org/#demo) .

**Comment by colaboratory-team** [comment]
This should be working again now.
