### ISSUE TITLE
Stopped after 12 hours working

### ISSUE THREAD

**Issue by santiftw59** [googlecolab/colabtools#1961]
I was running a script and it takes a long time, suddenly Colab disconnected and deleted the information it had after 12 hours

**Comment by rmdhnreza** [comment]
[https://research.google.com/colaboratory/faq.html#resource-limits](https://research.google.com/colaboratory/faq.html#resource-limits)

**How long can notebooks run in Colab?**

Notebooks run by connecting to virtual machines that have maximum lifetimes that can be as much as 12 hours. Notebooks will also disconnect from VMs when left idle for too long. Maximum VM lifetime and idle timeout behavior may vary over time, or based on your usage. This is necessary for Colab to be able to offer computational resources for free. Users interested in longer VM lifetimes and more lenient idle timeout behaviors that don’t vary as much over time may be interested in [Colab Pro](http://colab.research.google.com/signup?utm_source=faq&utm_medium=link&utm_campaign=how_long_can_nbs_run).

**Comment by santiftw59** [comment]
But I have Colab pro...

**Comment by miguelalejo** [comment]
Same issue using Colab Pro

**Comment by LuongQuocThien** [comment]
Have you use GPU VM?

**Comment by AlexandreBourrieau** [comment]
Same issue with ecolab pro I am always disconnected after 10H

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits
