### ISSUE TITLE
additional packages for R kernel

### ISSUE THREAD

**Issue by poldrack** [googlecolab/colabtools#1963]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

there are several packages that are commonly used for data analytics in R that are not included in the base R package.  Installing them can take a substantial amount of time, since R on Linux automatically installs from source rather than binary.  The packages of interest are:

- lme4
- lmerTest
- optimx
- lavaan

- Describe the expected behavior:

It would be great to be able to simply load these using the `library()` function without the need to install them.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment]
We're not planning on adding any new R packages right now.

FWIW you can install binary R packages in linux; use `!apt install r-cran-<pkgname>` (eg `!apt install r-cran-lme4`). All the packages you're interested in here are available as binary packages.

**Comment by poldrack** [comment]
Cool, thanks!
