### ISSUE TITLE
The domain policy has disabled drive file stream. Colab Pro

### ISSUE THREAD

**Issue by duyendh** [googlecolab/colabtools#1968]
It is really difficult to mount drive using drive.mount('/content/gdrive'). I'm using Chrome. 
Colab gives the error "the domain policy has disabled drive file stream". 
Successfully mount after trying for multiple times. 
This has happened for several days. The error only occurs when I'm using colab pro. Other accounts without colab pro still work as expected. 
https://colab.research.google.com/drive/19mcMGXStms3aAcuwKxab2TjgxrBuVZ3c?usp=sharing

**Comment by Hadrien-Cornier** [comment]
I am having the same issue

**Comment by cperry-goog** [comment]
Nothing Colab can do if domain has disabled Drive.
