### ISSUE TITLE
Hovering over a function shows its function call prefixed by `def def`

### ISSUE THREAD

**Issue by jameshfisher** [googlecolab/colabtools#1972]
<img width="677" alt="Screen Shot 2021-04-21 at 17 15 29" src="https://user-images.githubusercontent.com/166966/115587142-39fbea80-a2c5-11eb-9a01-05835dfbf4f9.png">

Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior: Hovering over a function shows its function call prefixed by `def def`

- Describe the expected behavior: Hovering over a function shows its function call prefixed by `def`

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/drive/1kV0HnEQMbAHuS05b9xomM1QWRB01-OhG?usp=sharing

**Comment by blois** [comment]
Thanks for the report! The fix should roll out in a few days.
