### ISSUE TITLE
colab pro cant connect to runtime 

### ISSUE THREAD

**Issue by abdoelsayed2016** [googlecolab/colabtools#1973]
Dear sir,
I am using colab pro but it is useless in a day 3 time can not connect to runtime cuz limit GPU.
limit GPU without using it for 2 hours how it becomes like that ??
I subscribe to colab pro to use it for a long time but it being bad and cant do my research well.
please who can fix this problem?
account: abdoelsayed2016@gmail.com

**Comment by cuongnguyengit** [comment]
I also have a similar situation. I cant connect to runtime GPU  during last 5 days.
I subscribed to colab pro on 2021/04/14 to use it for one or two months but I feel really disappointed because of your problem.
You need fix this problem soon?

Account: 20164980@hust.student.edu.vn

**Comment by cperry-goog** [comment]
We'll need reports from within the product to properly debug; please submit a report via Help > Submit feedback in Colab next time you encounter a resource issue with Pro!
