### ISSUE TITLE
!pip install not working

### ISSUE THREAD

**Issue by rchicola** [googlecolab/colabtools#1974]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: !pip install xlsxwriter not installing "module not found" in a new notebook, but it does work in an older web scrape notebook for clark county, makes zero sense

- Describe the expected behavior: I expect pip instal to well, install...never should have switched from jupyter

- The web browser you are using (Chrome, Firefox, Safari, etc.): chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/drive/1x1W5cynnPqHnuNGjtD5C48NMm2xOG06E#scrollTo=lbn62atGO1y0&line=1&uniqifier=1

**Comment by craigcitro** [comment]
Seems to work fine for me in a fresh runtime; impossible to say more without knowing what error you hit. (The notebook you linked isn't public.)
