### ISSUE TITLE
Error installing cartopy 

### ISSUE THREAD

**Issue by st12343** [googlecolab/colabtools#1976]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
**!pip install cartopy**

I have the following error message
Collecting cartopy
  Using cached https://files.pythonhosted.org/packages/b7/15/c466caf7aeff118c02aedefbe80caf77effda86bcb43ccb6c5e0655c4238/Cartopy-0.19.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.7/dist-packages (from cartopy) (1.19.5)
Requirement already satisfied: shapely>=1.5.6 in /usr/local/lib/python3.7/dist-packages (from cartopy) (1.7.1)
Processing /root/.cache/pip/wheels/76/2b/d4/53e6b9a0fb0a9f9f29664cf82605af8bc81d5ab44d987896dd/pyshp-2.1.3-cp37-none-any.whl
Building wheels for collected packages: cartopy
  Building wheel for cartopy (PEP 517) ... error
  ERROR: Failed building wheel for cartopy
  Running setup.py clean for cartopy
Failed to build cartopy
ERROR: Could not build wheels for cartopy which use PEP 517 and cannot be installed directly

- Describe the expected behavior:
Up to now the cartopy installation through !pip install cartopy was working well and didn't show any trouble since the closure of issue https://github.com/googlecolab/colabtools/issues/1884

I do think its is linked to the new version Cartopy-0.19.0.tar.gz  since up to now the import was made on version 0.18.0.tar.gz from older installations message 
"Collecting cartopy
  Downloading https://files.pythonhosted.org/packages/46/c1/04e50c9986842f00f7db0e7a65caa896840050d7328f74e5b7437aa01179/Cartopy-0.18.0.tar.gz (14.4MB)..."

If I enforce the cartopy version with 
!pip install cartopy==0.18.0
it works fine

- The web browser you are using (Chrome, Firefox, Safari, etc.):
under chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
this can be reproduce in the snippets for installation/import libraries examples  :
https://colab.research.google.com/notebooks/snippets/importing_libraries.ipynb#scrollTo=Zq68DSY2rP2W

regards

**Comment by craigcitro** [comment]
This looks to be an upstream issue: https://github.com/SciTools/cartopy/issues/1767

Workaround (from that issue): `!FORCE_CYTHON=1 pip install cartopy`

**Comment by st12343** [comment]
Sorry, I've missed it!
thanks !
