### ISSUE TITLE
Code executing continuously even after getting disconnected from runtime environment.

### ISSUE THREAD

**Issue by GourishettySairam** [googlecolab/colabtools#1977]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- observed behaviour: code continuing to run even after run time is disconnected

- Expected behaviour: As soon as the run time is disconnected. code execution should stop

- I am using Chrome browser
- 
![Screenshot (1639)](https://user-images.githubusercontent.com/58263874/115955584-07e0c780-a515-11eb-9ae3-ada2118f01a9.png)

**Comment by cperry-goog** [comment]
We haven't been able to repro, closing for now.
