### ISSUE TITLE
Genism Installation

### ISSUE THREAD

**Issue by BradleyMerrillT** [googlecolab/colabtools#1983]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
- I try  "from gensim.models.nmf import Nmf"

- Describe the expected behavior:
- It should import, but it doesn't.  I get this error: ModuleNotFoundError: No module named 'gensim.models.nmf'
- I have investigated, and it works fine in, for example, jupyter notebook once I install genism
-  Other genism libraries import just fine into colab
- genism I gather is preinstalled, as when I tried to install it, I got the message it was already there
- I wonder if it needs to be reinstalled somehow.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
- Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment]
The submodule you're looking for requires a newer version of `gensim`; you can upgrade with `!pip install --upgrade gensim` (and then restart your kernel if you've already imported gensim).

**Comment by BradleyMerrillT** [comment]
Thanks!
