### ISSUE TITLE
CRASH from fewer Records of Big Datasets

### ISSUE THREAD

**Issue by JayeMineM** [googlecolab/colabtools#1985]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
 My codes keeps on crashing even from a very little amount of datas: less than 1% of  https://github.com/NVlabs/ffhq-dataset and https://www.kaggle.com/puneet6060/intel-image-classification ...Whereas 50% (at least) is needed to train my Machine Learning (ML) model.

- Describe the expected behavior:
my codes snippets to run smoothly...giving that I have turned Pro with ROM(~25GB) and ROM(225GB)

- The web browser you are using (Chrome, Firefox, Safari, etc.): CHROME

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

Regards,

Pls URGENTLY Advise on the Remedy....or...alternatively... Provide more RAM !!!
![Screenshot 2021-04-30 002135](https://user-images.githubusercontent.com/72269561/116630603-62ca5280-a94b-11eb-8103-b0a991d04a27.png)
![Screenshot 2021-04-30 002108](https://user-images.githubusercontent.com/72269561/116630622-6bbb2400-a94b-11eb-80ae-255b4926a96d.png)
![Screenshot 2021-04-30 001725](https://user-images.githubusercontent.com/72269561/116630628-6d84e780-a94b-11eb-87ca-a953d237cb9e.png)

![Screenshot 2021-04-30 001915](https://user-images.githubusercontent.com/72269561/116630555-4af2ce80-a94b-11eb-947a-8a4f8fe20242.png)

**Comment by cperry-goog** [comment]
This is hard to debug without a well defined example. If it's still a problem, try getting a contained example and share the Colab here.
