### ISSUE TITLE
Keep Colab Compatible with Latest Package Releases

### ISSUE THREAD

**Issue by sirinath** [googlecolab/colabtools#1986]
Many of the packages on Colab are not the latest. Can Colab be regularly kept updated with the latest of the packages.

**Comment by craigcitro** [comment]
We try to keep packages up to date, but it's impossible to keep everything in sync with PyPI.

I'd recommend explicitly using `!pip install` to install any package versions you're looking for, or `!pip install --upgrade` if you prefer to stick with whatever is most recent.
