### ISSUE TITLE
Colas can‘t connect to backend, up to now. Email: fanwenjie1969@gmail.com

### ISSUE THREAD

**Issue by fanyiyang** [googlecolab/colabtools#1994]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by cperry-goog** [comment]
If you encounter this again, please send feedback in product (Help -> Send feedback)
