### ISSUE TITLE
Image(open(file.gif,'rb').read()) dosn't work from .py script

### ISSUE THREAD

**Issue by pmikola** [googlecolab/colabtools#1995]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by cperry-goog** [comment]
Known issue

**Comment by blois** [comment]
The version of IPython which is installed by default doesn't support .gif files. We're working on an upgrade but in the meantime a manual upgrade should fix it-
https://colab.research.google.com/gist/blois/a6466b39ed0aab492640c0d324b50d7c/untitled44.ipynb
