### ISSUE TITLE
colab gpu with pro version disconnects due to unkown error.

### ISSUE THREAD

**Issue by matteo-ticli** [googlecolab/colabtools#1996]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by cperry-goog** [comment]
If you encounter this again, please submit feedback in Colab via "Send Feedback" in the Help menu so our team can investigate further.
