### ISSUE TITLE
Colab Pro keeps saying Page is Unresponsive and crashes. Computer becomes extremely slow too

### ISSUE THREAD

**Issue by AshWiji** [googlecolab/colabtools#1997]
Bug report for Colab: http://colab.research.google.com/.

**Problem:** 
As you can see in the image below when I train my GAN model this is what happens. It will start training but it won't show an output and then it starts to crash. It was working fine prior to this. The only change I did was use the JaveScript thing in the console to make sure it keeps connecting every hour. Could that be the cause? Googling answers, it says to clear the cache which I have tried and the problem still persists.

If the problem is due to the JavaScript, I have tried to open Colab in Incognito and the problem still happens.

![image](https://user-images.githubusercontent.com/83708334/117148636-52343500-adae-11eb-9601-26f7cae15997.png)

**What I want to happen:**
- May model to run without the page becoming unresponsive and slowing my computer

**Web Browser**: Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/drive/1XZi2LuS10M15h2xI0rQOpz8RmlN6Ermf?usp=sharing

**Comment by blois** [comment]
Typically crashes of the browser will be related to the amount or type of output being displayed by the kernel. My recommendation is to try to limit how much data is being displayed.
