### ISSUE TITLE
I can't log into a google colab. Google says my business account is removed and I need to contact my administrator s

### ISSUE THREAD

**Issue by DXC-sgg** [googlecolab/colabtools#1999]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
when trying to log to google colab with my business account it says that is has been recently removed and that I need to contact administrator. 

- Describe the expected behavior:
I expect to connect with my business account to the colab website

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome 

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1TLOslWax7Q52-TvdT0XY2qIJ6s6I3p3D?usp=sharing#scrollTo=4tbAi4NqRD3I

**Comment by cperry-goog** [comment]
If you're encountering Colab access issues with a business account, you should contact your administrator to confirm that they haven't revoked access to Colab for the organization. Steps to revoke or grant access are here: https://support.google.com/a/answer/7646040

The Colab team has no ability to circumvent administrator access controls at the organization level.
