### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by blois** [googlecolab/colabtools#2]
Python 2 is deprecated, users should be able to execute Python 3 notebooks.

**Comment by craigcitro** [comment]
Python3 support is now live! 

* When creating a new notebook, there's now an option for Python2 or Python3.
* For an existing notebook, `Runtime` -> `Change runtime type` will let you switch.

We write the language info into the `kernelspec` in the notebook metadata, so switching runtime type isn't just per-session.

**Comment by willingc** [comment]
@craigcitro Congrats!!! Awesome that Python 3 is now supported. Thank you 🥇
