### ISSUE TITLE
Unable to save .h5 when using Keras

### ISSUE THREAD

**Issue by Jinkeycode** [googlecolab/colabtools#20]
I have import h5py in colab like this
```
!pip install h5py
import h5py
```
but when I save model use `model.save()`, the error of missing h5py still occur：
```
ImportErrorTraceback (most recent call last)
<ipython-input-33-14c760cfc8c2> in <module>()
     20 print("训练耗时：%f 秒" %(finish-start))
     21 # 保存模型
---> 22 model.save("health_and_tech_design.h5")
     23 
     24 # 加载预训练的模型

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in save(self, filepath, overwrite, include_optimizer)
   2554         """
   2555         from ..models import save_model
-> 2556         save_model(self, filepath, overwrite, include_optimizer)
   2557 
   2558     def save_weights(self, filepath, overwrite=True):

/usr/local/lib/python2.7/dist-packages/keras/models.pyc in save_model(model, filepath, overwrite, include_optimizer)
     55 
     56     if h5py is None:
---> 57         raise ImportError('`save_model` requires h5py.')
     58 
     59     def get_json_type(obj):

ImportError: `save_model` requires h5py.

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by craigcitro** [comment]
I *think* what's going on here is that you imported `keras` before you'd installed `h5py`, and keras [decides if h5py is available at import time](https://github.com/keras-team/keras/blob/eac78b859beb31cafa65a3edb4eaa888d3b6c2e6/keras/models.py#L29-L32).

A quick check would be to just restart your kernel (ctrl-m .) and re-run your code.

**Comment by Jinkeycode** [comment]
@craigcitro I imported h5py before keras, but it wasn't work.
```
!pip install keras
!pip install jieba
!pip install h5py

import h5py
import jieba as jb
import numpy as np
import keras as krs
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
```

**Comment by craigcitro** [comment]
do you have a repro notebook? (or just code snippet?)

**Comment by Jinkeycode** [comment]
@craigcitro My data and code and notebook is all in here，but I remove model.save() because it fail, you can try to add it after model.fit()
https://github.com/Jinkeycode/keras_lstm_chinese_document_classification

**Comment by craigcitro** [comment]
I can't seem to repro: https://colab.research.google.com/notebook#fileId=1EqImxY9mv6UOC9vbznNZeisWtz9ggNhE&scrollTo=wldO2oVKvggr

**Comment by JaveriaAkbar** [comment]
I ran into the same problem. Installing libhdf5 fixed it.
!apt-get install -y libhdf5-dev

**Comment by craigcitro** [comment]
We've also added `h5py` (and `libhdf5-dev`) to the container by default, so you shouldn't hit this one again. 😁
