### ISSUE TITLE
Issue with function on feature_sets.ipynb - variable definition

### ISSUE THREAD

**Issue by creatureII** [googlecolab/colabtools#200]
Hello,

I am new to coding and working through the tensorflow tutorial.

On the last solution for the feature_sets.ipynb tutorial page, I ran into an issue where "select_and_transform" would only work one time, as LATITUDE_RANGES was defined outside of the function itself.  ie, select_and_transform would work correctly the first time, but fail to transform the dataframe the second time. By moving the definition of LATITUDE_RANGES inside of the function, it would work again for me.

My apologies if this is not the right place to post about this. 

Python 3.6.5
```
LATITUDE_RANGES = zip(range(32, 44), range(33, 45))

def select_and_transform_features(source_df):
  selected_examples = pd.DataFrame()
  selected_examples["median_income"] = source_df["median_income"]
  for r in LATITUDE_RANGES:
    selected_examples["latitude_%d_to_%d" % r] = source_df["latitude"].apply(
      lambda l: 1.0 if l >= r[0] and l < r[1] else 0.0)
  return selected_examples

selected_training_examples = select_and_transform_features(training_examples)
selected_validation_examples = select_and_transform_features(validation_examples)
```
Changed to work below:
```


def select_and_transform_features(source_df):
  selected_examples = pd.DataFrame()
  selected_examples["median_income"] = source_df["median_income"]
  LATITUDE_RANGES = zip(range(32, 44), range(33, 45))
  for r in LATITUDE_RANGES:
    selected_examples["latitude_%d_to_%d" % r] = source_df["latitude"].apply(
      lambda l: 1.0 if l >= r[0] and l < r[1] else 0.0)
  return selected_examples

selected_training_examples = select_and_transform_features(training_examples)
selected_validation_examples = select_and_transform_features(validation_examples)
```

**Comment by colaboratory-team** [comment]
Sorry, we aren't able to offer help with individual Colab examples. I'd recommend following up on a general-purpose forum like StackOverflow or with the authors of the notebook.
