### ISSUE TITLE
download button about folder 😡

### ISSUE THREAD

**Issue by epsilon-deltta** [googlecolab/colabtools#2000]
File downloading is possible 
but there is not Folder downlaod button in colab 
Could you make this?😡
![image](https://user-images.githubusercontent.com/45354219/117387274-8b41e600-af23-11eb-808f-a6ed937956ab.png)

**Comment by blois** [comment]
Easiest approach is going to be to zip the directory on the VM and download that:

```
!zip -r files.zip sample_data
```

It'll probably be faster overall as well.
