### ISSUE TITLE
CUDA out of memory error

### ISSUE THREAD

**Issue by vish1200** [googlecolab/colabtools#2001]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: When executing my code, I keep getting the error message "CUDA out of memory. Tried to allocate 3.35 GiB (GPU 0; 15.78 GiB total capacity; 14.23 GiB already allocated; 210.75 MiB free; 14.28 GiB reserved in total by PyTorch)". The code was working previously and nothing has been changed. 

- Describe the expected behavior: Code should compile without error

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/drive/1aHcZAgKBAQBZhN8xZ5SAxm4zzzCBc-H5?usp=sharing

**Comment by cperry-goog** [comment]
Try restarting runtime, or include a much smaller colab with the exact repro steps so we can check.
