### ISSUE TITLE
Colab Pro signup link in settings page returns 404

### ISSUE THREAD

**Issue by shaunakg** [googlecolab/colabtools#2011]
**Describe the current behavior**
The 'settings' dialog (accessed from tools -> settings) has a pane called 'Colab Pro' with a signup button. When clicked, this button takes you to [https://colab.research.google.com/signup/pricing](https://colab.research.google.com/signup/pricing) which is a 404 error page.

**Describe the expected behavior**
You might want to change the link to lead to [https://colab.research.google.com/signup](https://colab.research.google.com/signup/pricing) (without a trailing slash as it will cause a **403** instead for some reason).

**What web browser you are using**
Chrome 92.0.4503.5 on Windows.

**Comment by blois** [comment]
We're unable to repro this using the default configuration.
