### ISSUE TITLE
Your  Gaussian Regression isn't working

### ISSUE THREAD

**Issue by snakuch1** [googlecolab/colabtools#2018]
So I just opened the tutorial in Google Colab and I just tried running the code and this is the error that comes up:
ValueError                                Traceback (most recent call last)
<ipython-input-25-0b42fdbef836> in <module>()
     10                             observation_noise_variance_var)
     11   grads = tape.gradient(loss, trainable_variables)
---> 12   optimizer.apply_gradients(zip(grads, trainable_variables))
     13   lls_[i] = loss
     14 

1 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/utils.py in filter_empty_gradients(grads_and_vars)
     77   if not filtered:
     78     raise ValueError("No gradients provided for any variable: %s." %
---> 79                      ([v.name for _, v in grads_and_vars],))
     80   if vars_with_empty_grads:
     81     logging.warning(

ValueError: No gradients provided for any variable: ['amplitude:0', 'length_scale:0', 'observation_noise_variance_var:0'].

**Comment by craigcitro** [comment]
I'm not sure what you mean by "the tutorial", but it doesn't look like one owned by colab.

I'd recommend filing the issue with the owners of the tutorial.

**Comment by snakuch1** [comment]
https://www.tensorflow.org/probability/examples/Gaussian_Process_Regression_In_TFP this was the link that I used

**Comment by MarkDaoust** [comment]
Thanks Craig, I'll send a bug to the team that owns this.
