### ISSUE TITLE
Slow display of IPython HTML image

### ISSUE THREAD

**Issue by hhoppe** [googlecolab/colabtools#2019]
Please see the notebook https://colab.research.google.com/drive/1nYgLqq5rBDhG3UztlMKKJ6dfzFrawZCZ?usp=sharing

The Colab notebook takes a long time to display a generated HTML image.
Profiling (%prun) shows that the image is encoded and processed by IPython in 0.5 s,
yet the Colab cell takes ~9.5 s to show the output image.

(Using Chrome.)

**Comment by blois** [comment]
The cell execution time includes the full time it took to receive and render the resulting output. In this case the vast majority of that time appears to be in transferring the data from the kernel to the browser. Looking at the network requests in the browser devtools I can see the request for the image data take ~8.5s to download.
