### ISSUE TITLE
Can not get Colab to work with Google Cloud Compute Instances

### ISSUE THREAD

**Issue by CliffordDonovan** [googlecolab/colabtools#202]
Continue to get error:
"ImportError: No module named colab"

It seems colab is not injecting the appropriate, necessary, package - and, as far as I know, there is no way to have the notebook install this package.

To Pre-empt a few questions:
I have tried this on Google compute instances using a couple different Ubuntu and Debian versions. I have ensured I am using python 3.6. I have followed the instructions 100% as outlined here: https://research.google.com/colaboratory/local-runtimes.html

I am not very familiar with linux and do not know my way around. But, I SSH into the instance, ensure the correct version of python, pip and jupyter are all installed, I install jupyter_http_over_ws and run the `jupyter serverextension enable --py jupyter_http_over_ws` command. 

I then run:
`jupyter notebook \
  --NotebookApp.allow_origin='https://colab.research.google.com' \
  --port=8888` - I have tried it with the `--no-browser` flag and without.

Then, on my local PC:
I run `gcloud compute ssh --zone YOUR_ZONE YOUR_INSTANCE_NAME -- -L 8888:localhost:8888` from my local PC (with my zone and instance name inserted of course).

I then open chrome (I have uninstalled adblock - as I found someone had a similar issue with adblock open) and open the jupyter notebook via the link/token generated from the vm instance. I then open the colab notebook and connect to the local runtime on port 8888. This all works fine.

However, I then try to import the google.colab package, with no success. 
This is of course a major issue as it is necessary to authenticate in order to manage data in and our of the colab instance. So because of this, it's basically unusable.

I have now tried this using multiple different compute instances with no success.

**Comment by craigcitro** [comment]
You're not doing anything wrong: there's currently no mechanism for installing the `google.colab` module for local runtimes.

Specifically for auth, the usual approach is to use the VM's service account, which any libraries you want to use should be able to find themselves. (In particular, `google.auth.default()` should return you a usable credential, just as `google.colab.auth.authenticate_user()` does in a managed runtime.)
