### ISSUE TITLE
update_display() renders a new display instead of updating an existing one

### ISSUE THREAD

**Issue by ender-wieczorek** [googlecolab/colabtools#2020]
**Describe the current behavior**
The following code renders 6 plots:
```
import plotly.graph_objects as plotly

out = display(plotly.Figure(), display_id=True)
for i in range(6):
  out.display(plotly.Figure())
```

**Describe the expected behavior**
This should render a single plot.

**What web browser you are using**
Chrome

**Additional context**
See the code snippet above.

**Comment by blois** [comment]
This appears to be a Plotly issue- the display data resulting from plotting the figure does not have a `display_id` field set on it. I added some further details to the Plotly bug.

**Comment by ender-wieczorek** [comment]
Thanks for looking into this. I also found a workaround: wrapping the figure in `HTML()`:
instead of: `display(f)`
do: `display(IPython.display.HTML(f.to_html()))`
