### ISSUE TITLE
saves failed after fixing errors in cell 

### ISSUE THREAD

**Issue by pleabargain** [googlecolab/colabtools#2021]
**Describe the current behavior**
run the colab notebook
errors
fix errors
save
saves failed after fixing errors in cell and then colab complains the notebook is open in another cell!
save fails because there is a conflict with another open tab?! I'm running a private single use colab with no sharing 

here's the onscreen error:
https://i.imgur.com/ypBbWIS.png

**Describe the expected behavior**
save should work 

**What web browser you are using**

Google Chrome | 90.0.4430.212&nbsp;(Official Build)&nbsp;(64-bit)

![colab error on save 2021-05-17_16-15](https://user-images.githubusercontent.com/640846/118625437-b0abdb00-b7d2-11eb-8bad-e2a4ae3f10a5.png)
![colab error save2021-05-17_17-03](https://user-images.githubusercontent.com/640846/118625442-b1447180-b7d2-11eb-851f-fc34543c50aa.png)
![error colab 2021-05-17_17-06](https://user-images.githubusercontent.com/640846/118625445-b1dd0800-b7d2-11eb-80de-b0e091b6b7ff.png)
![error colab asdf 2021-05-17_17-08](https://user-images.githubusercontent.com/640846/118625446-b1dd0800-b7d2-11eb-85a4-ca2acdce2582.png)
![anothererror 2021-05-18_12-06](https://user-images.githubusercontent.com/640846/118625448-b2759e80-b7d2-11eb-9bc0-0d24bdfc38e8.png)
![save-error-2021-05-18_15-09](https://user-images.githubusercontent.com/640846/118648498-2459e200-b7eb-11eb-81a1-52ceeae116aa.png)

**Comment by blois** [comment]
There are some rare cases where we're seeing Drive file saves generate conflicts with themselves. In these cases a manual 'Save' will prompt to overwrite which you can use to force save the file.

**Comment by nikshingadiya** [comment]
Hello blois,  It's not rare case I am facing every day this issue.
I don't how to solve this issue!!
![Screenshot (81)](https://user-images.githubusercontent.com/46846887/122212693-c5f55180-cec5-11eb-95bb-09adefc6f13f.png)

**Comment by pleabargain** [comment]
Try turning off 'saving output'. I have had luck with that option.

**Comment by nikshingadiya** [comment]
Thanks Dennis it's working good
