### ISSUE TITLE
This garbade does not work

### ISSUE THREAD

**Issue by ljluisjimenez12** [googlecolab/colabtools#2022]
https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/tf2_object_detection.ipynb

THis garbade fails on step 19

fix it

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by craigcitro** [comment]
You should report the bug on https://github.com/tensorflow/hub/issues (which is the repo that owns that notebook).
