### ISSUE TITLE
google colab pro for free

### ISSUE THREAD

**Issue by MrZethaz** [googlecolab/colabtools#2025]
Vulnerability that allows me to use a google colab terminal for free, and can bring some problems

**Comment by AhmadManzoor** [comment]
@MrZethaz  can you please share more details?

**Comment by blois** [comment]
Security vulnerabilities should be reported through https://www.google.com/about/appsecurity/

You can also use Help -> Send Feedback to report details via a private channel.

**Comment by MrZethaz** [comment]
> Vulnerabilidades de segurança devem ser relatadas em https://www.google.com/about/appsecurity/
> 
> Você também pode usar Ajuda -> Enviar feedback para relatar detalhes por meio de um canal privado.

thankkkssssssssssssssssssssssss, for a long time trying to find where I can report the vulnerability, honestly I even got excited
