### ISSUE TITLE
Invalid anchor.href value returned by serve_kernel_port_as_window

### ISSUE THREAD

**Issue by ohtaman** [googlecolab/colabtools#2026]
**Describe the current behavior**
When I call `colab.google.serve_kernel_port_as_window`  with default path option (or '/'),
I get the link url with doubled slash.

ex)
expects: https://ycxfoqhtd0p-496ff2e9c6d22116-8000-colab.googleusercontent.com/
results: https://ycxfoqhtd0p-496ff2e9c6d22116-8000-colab.googleusercontent.com//

**Describe the expected behavior**

With default path option, the link url should be ended with single slash.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

Chrome

**Additional context**

- the version of colab.google: 0.0.1a2
- link to a minimal notebook: https://colab.research.google.com/drive/1Y_WbVqipnoSc5YkTC1lliKbFbzHdCPsj?usp=sharing

**Comment by ohtaman** [comment]
This line seems to be the cause of this problem.  `path` is `"/"` in default but `url` already contains `"/"`

https://github.com/googlecolab/colabtools/blob/eb61c58715be10b0334af0e6f756105f0263cac7/google/colab/output/_util.py#L110

**Comment by craigcitro** [comment]
Thanks for the report! Sending a fix, should be live next week.

**Comment by craigcitro** [comment]
Fix should be live.
