### ISSUE TITLE
Stuck at Allocating

### ISSUE THREAD

**Issue by Yunussurty** [googlecolab/colabtools#2027]
**Describe the current behavior**
Google colab is stuck on Allocating and is not executing any code. I am using this for the 1st time and has been struggling to use it.

**Describe the expected behavior**
I should be allocated Ram and Space for my code to be executed.

**What web browser you are using**
Chrome and FireFox. It is happening on both'
Version for chrome - Version 90.0.4430.212 (Official Build) (64-bit).
Firefox version - 87.0 (64-bit)
![Colab issue](https://user-images.githubusercontent.com/83905803/118942493-66606080-b970-11eb-9d42-fd8bd2cd3bd7.jpg)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by blois** [comment]
Possibly try an incognito browser window? It could be an issue with some browser extension.
