### ISSUE TITLE
Colab Pro : Access to GPU

### ISSUE THREAD

**Issue by sander2825** [googlecolab/colabtools#2028]
**Describe the current behavior**
II subscribed to Colab Pro a month and a half ago and I was sometimes disconnected or had no access to GPU. It's fine as explained in the FAQ.
But it now has been 6 days I can't have access to a GPU via Colab Pro, and when I am able to have one I am disconnected after less than an hour?
I subscribed to Colab Pro for my studies and need it for my Deep Learning Courses. 
The other students do not seem to have the same issue, and I don't think that I use Colab differently.
Can you help?

**Describe the expected behavior**
Access to GPU via Colab Pro

**What web browser you are using**
Tried with Chrome, Edge

**Additional context**
I already sent feedbacks via colab, mails to Colab Customer Support... But no answer and no help given.

**Comment by cperry-goog** [comment]
We're following up on the in-Colab feedback report, thanks.

**Comment by sander2825** [comment]
When and how I will receive an answer is unclear...

**Comment by mastercho** [comment]
@sander2825 i got same case here, did they solve your issue?

**Comment by sander2825** [comment]
I waited a few more days. Now it works
