### ISSUE TITLE
colab crashing after ".to(device)'

### ISSUE THREAD

**Issue by MoranReznik** [googlecolab/colabtools#2029]
**Describe the current behavior**
I am using google colab pro. I am running on GPU mode:

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
print(torch.cuda.get_device_name())
returns:

cuda
Tesla P100-PCIE-16GB
I am able to create a model and run it perfectly fine, and then save it. when I try to load it without to(device), it works.

but when I run:

notes_model = LSTM_notes(em_dim).to(device)
the session crashes:

Your session crashed for an unknown reason. View runtime logs

**Describe the expected behavior**
it should run without crashing the session.

**What web browser you are using**
Chrome.

I have tried looking at the logs, but they don't seem to provide meaningful info:

May 20, 2021, 2:37:08 PM    WARNING WARNING:root:kernel 53812acc-3a19-48e2-a41b-1acaab9dfe61 restarted
May 20, 2021, 2:37:08 PM    INFO    KernelRestarter: restarting kernel (1/5), keep random ports
May 20, 2021, 2:36:44 PM    WARNING WARNING:root:kernel 53812acc-3a19-48e2-a41b-1acaab9dfe61 restarted
May 20, 2021, 2:36:44 PM    INFO    KernelRestarter: restarting kernel (1/5), keep random ports
any ideas on why is this happening and what can I do to solve it?

it doesn't, I think, an out-of-ram issue.

**Comment by cperry-goog** [comment]
We're not sure how to debug a Torch issue; is it possible to ask on their tracker or on StackOverflow to get more logs here? Otherwise this is not possible for us to take action on.
