### ISSUE TITLE
Youtube videos are not saved as MP3 or MP4

### ISSUE THREAD

**Issue by dgrl** [googlecolab/colabtools#2031]
**Describe the current behavior**
When change url from https://github.com/deezer/spleeter/raw/master/audio_example.mp3 to an youtube mp4 or mp3 download link it will download the file and save it but cant be used because its not ending on MP3....

**Describe the expected behavior**
Be able to use video from youtube 

**What web browser you are using**
Chrome, Firefox, Safari, Edge

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
Colab downloads with whatever file extension is provided by the download url. If you provide reproducible steps in a notebook we could look into this to see if there are any bugs on our end.

**Comment by dgrl** [comment]
Please do not close a ticket that is not solved 

Check this url
https://www.soundboard.com/handler/DownLoadTrack.ashx?cliptitle=Bag+Raiders+-+Shooting+Stars&filename=24/246940-8f538f7a-f032-4738-9b62-32cec5a0093a.mp3

Ends with .mp3 url in browser saves file fine 

Your app;

!wget https://www.soundboard.com/handler/DownLoadTrack.ashx?cliptitle=Bag+Raiders+-+Shooting+Stars&filename=24/246940-8f538f7a-f032-4738-9b62-32cec5a0093a.mp3

Does not saves it as .mp3

Saving to: ‘DownLoadTrack.ashx?cliptitle=Bag+Raiders+-+Shooting+Stars.2’

Does not play song in next step....
