### ISSUE TITLE
The whitespace in editor displayed strangely on Google Chrome

### ISSUE THREAD

**Issue by tibitTW** [googlecolab/colabtools#2034]
The width of whitespace is different from other characters. The image below highlights **a whitespace character**, and it causes code looks messy.

![image](https://user-images.githubusercontent.com/39118448/119332357-0db7fd00-bcbb-11eb-9dd9-94746d6a3a5c.png)

Firefox don't have this problem, it works good. And on MS Edge the width is exactly twice of other characters so code still looks neat.

I just found that in Google Chrome and Edge it's not a `" "` character but a `"&nbsp"` character. Is it the reason cause the display problem?

> Chrome Version : 90.0.4430.212 (64 bit) (stable)

**Comment by katlyn-edwards** [comment]
Hey there -- in Chrome, can you navigate to 
`chrome://settings/fonts`

Can you respond with the font that's selected for the "Fixed-width font" setting?

**Comment by tibitTW** [comment]
I use `Cascadia Code PL` as my Fixed-width font.

Btw, the `font-family` of code blocks in colab is `monospace` but not `monospaced` also confused me (same in firefox and edge)

**Comment by katlyn-edwards** [comment]
Hmm I'm not able to reproduce the issue:
![image](https://user-images.githubusercontent.com/2673487/119589276-53da9280-bd87-11eb-9e8f-6cb19b89bbe9.png)

Interestingly, your screenshot doesn't seem to be using Cascadia Code PL, which is odd, if it's set in Chrome as the fixed width font. In your screenshot, the bottom of the `g` is a circle, whereas in Cascadia Code, it seems it's open: https://coding-fonts.css-tricks.com/fonts/cascadia-code/?language=charmap Your screenshot of what monospace is matches your original screenshot quite closely. I'm not sure why it's falling back to the default monospace.

Also `monospace` is correct: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#syntax
`monospace` simply asks the computer/browser/etc for a preferred fixed width font, and has a generic setting as a fallback. Colab in Chrome reads from the "fixed-width font" setting, so in theory it should be using Cascadia Code PL. 

Is it possible that the original font files for Cascadia Code PL were deleted or removed somehow? Does Cascadia Code PL work in other applications?

**Comment by tibitTW** [comment]
Yes, it works perfectly on my VS Code.
And another mysterious thing is, I open a notebook on Colab I wrote before, and a part of content displays in Cascadia Code PL, and other parts are not.

![image](https://user-images.githubusercontent.com/39118448/119609566-635ee780-be2a-11eb-81dc-1e9db1550b15.png)

I also try write a simple html file, change the font-family to Cascadia Code PL, and it still works.

**Comment by katlyn-edwards** [comment]
Is it possible that you have a Chrome extension installed that is causing the change in space character? You mentioned earlier that it looked OK in Firefox and Edge. 

You can test it by disabling all chrome extensions, reloading the page to see if it looks any different. If it fixes it, you can isolate which extension is problemmatic by re-enabling them one at a time, and reloading Colab after each extension is enabled.

**Comment by tibitTW** [comment]
I change the UI language of Chrome from **Chinese (Tranditional)** to **English** and fix this problem now.

And the problem actually is, the custom setting of fixed-width text will not work if users use Chinese as their language. 

So this error is from chromium, not google colab.

And here is older same issue of chromium I found :

https://bugs.chromium.org/p/chromium/issues/detail?id=1017123&q=font-family&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by cperry-goog** [comment]
Marking fixed based on comment.
