### ISSUE TITLE
more info link on no allocation goes to a dead page 

### ISSUE THREAD

**Issue by pleabargain** [googlecolab/colabtools#2035]
no backend error
clicked to find out why
screen shot:
https://i.imgur.com/UzJM6UZ.png

link in error message
https://colab.research.google.com/drive/%7B$moreInfoUrl%7D

page doesn't exist error is here
https://i.imgur.com/qOZwY40.png

**Comment by craigcitro** [comment]
Thanks for the report, we'll take a look.

b/189115135

**Comment by corrieann** [comment]
Thanks for the report. This has been fixed.
