### ISSUE TITLE
phantom find text on page.

### ISSUE THREAD

**Issue by ilan** [googlecolab/colabtools#2037]
In Ubuntu (have no Windows installation to check) in both Firefox and Chromium, find text on page finds fake text (like fake news...). I think this is connected to copy-paste operations which I used to change the relative location of pieces of code. The problem exists in colab notebooks.
In my case I wanted to see the occurrences of a variable to see if I had missed something. Find text reported 9 instances of the text. The first 5 I agreed with the finding, but 6 to 9 were phantom. It is possible that my operation of copy-paste followed by a delete of the original text leaves a phantom behind.
To check if perhaps the text might be in a cache, I powered down the computer and started again. The phantom text was still alive, but invisible.
I had been using Firefox, so I switched to Chromium. The problem was exactly the same so it isn't browser connected. I can't prove it is connected to the copy-paste, but this is my best guess. In any case it is annoying since the precise question I wanted to answer was "are there other occurrences of this variable?". Find text claimed that there were 4 more but wouldn't show them.
If I can help, I would be glad to do so.
Thanks,
Ilan

**Comment by katlyn-edwards** [comment]
Hi there!

It sounds like you're using native browser find, which indeed isn't really supported well. 

Instead please use Colab's Find pane, from the magnifying glass on the left side of the screen. There's also a global keyboard shortcut, which I think is Apple/Ctrl + G

**Comment by ilan** [comment]
Thanks.
Yes, I used what I already knew, the browser's find.
Now I just tried the colab's find, which does the job.

I ran across something else which is more disturbing.
It is quite easy to mistakenly erase part of my code. Most IDE's have
multiple undo.
If I'm not mistaken, there is only a single undo in colab, which is scary.
As a workaround, I started to keep a copy of my code off line and then I
can use Meld to review changes if I have doubts that I inadvertently
changed something.

In any case, it is a very nice tool. In my case I have an "old computer"
which does not have a GPU. That was a show stopper where colab saved the
day.

**Comment by blois** [comment]
Multiple undo operations are available though with some nuances:

- Inside of the cells there is an undo stack per cell- you'll need to be editing the specific cell to perform the undo.
- Some operations such as integrating remote edits of a notebook may clear the undo stack.
