### ISSUE TITLE
%%sql syntax highlighting.

### ISSUE THREAD

**Issue by kindly** [googlecolab/colabtools#2039]
**Is your feature request related to a problem? Please describe.**
When writing SQL with the `%%sql` or `%sql` magics from ipython-SQL the sql is not syntax-highlighted 

**Describe the solution you'd like**
For the `%%sql` sql to be highligted

**Describe alternatives you've considered**
Currently on the the `%%bigquery` magic is highlighted along with if you do `syntax.sql('`.   I think it should be simple to add `%%sql` to the `googlesql` highlighting in the javascript.  I managed to do this even with the minified javascript.  The javascript does not live in this repo and would be happy to do the pull request if directed to where it does live.

**Additional context**
I have hacked my sql library to trample on the %%bigquery magic to get its sytax highlighting but thought it might be better to just ask.

**Comment by craigcitro** [comment]
Thanks for the FR! I sent a change, which should go live by next week. (I'll update this issue when it's live.)

**Comment by kindly** [comment]
@craigcitro Amazing! Thanks.

**Comment by craigcitro** [comment]
Should be live now.
