### ISSUE TITLE
Files windows blank. Connecting a runtime to browse,

### ISSUE THREAD

**Issue by flydragon2018** [googlecolab/colabtools#2040]
**Describe the current behavior**
the file windows becomes blank.
**Describe the expected behavior**
File Explorer should show the directories and files

**What web browser you are using**
 Chrome

**Additional context**
 
notebook status is "busy"

**Comment by craigcitro** [comment]
Can you provide repro steps? We have at least two reports, but I can't manage to repro the failure here, even when a long-running command is executing.
