### ISSUE TITLE
'from keras.engine import InputSpec' stopped working all of sudden

### ISSUE THREAD

**Issue by RoshanSalian** [googlecolab/colabtools#2042]
When I try to import InputSpec from keras.engine, I get error
`ImportError: cannot import name 'InputSpec' from 'keras.engine' (/usr/local/lib/python3.7/dist-packages/keras/engine/__init__.py)
`
This never happened before yesterday and I have made no changes to my code.

I have been using InputSpec from keras.engine for a year now and never faced any issue.

Browser - FireFox

I was trying to add Reflection Padding which required InputSpec as given in this repository - https://github.com/RaphaelMeudec/deblur-gan/blob/master/deblurgan/layer_utils.py

**Comment by colaboratory-team** [comment]
Recently colab was upgraded to TF 2.5.0, forcing an upgrade to keras-nightly 2.5.0.dev2021032900.
Looks like `keras.engine.InputSpec` has moved to `keras.engine.input_spec.InputSpec` in keras.

(note that colab trades off stability vs staying up to date by default so when upstreams choose to break backwards-compatibilty some user-visible breakage is inevitable)
