### ISSUE TITLE
WARNING | Config option `delete_to_trash` not recognized by `ColabFileContentsManager`.

### ISSUE THREAD

**Issue by evawyf** [googlecolab/colabtools#2043]
Session crash for unknown reason.. 

**Describe the current behavior**

May 26, 2021, 12:22:11 AM | INFO | google.colab serverextension initialized.
-- | -- | --
May 26, 2021, 12:22:11 AM | INFO | google.colab serverextension initialized.
May 26, 2021, 12:22:11 AM | INFO | Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
May 26, 2021, 12:22:11 AM | INFO | Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
May 26, 2021, 12:22:11 AM | WARNING | Config option `delete_to_trash` not recognized by `ColabFileContentsManager`.
May 26, 2021, 12:22:11 AM | WARNING | Config option `delete_to_trash` not recognized by `ColabFileContentsManager`.

**Describe the expected behavior**

**What web browser you are using**
Chrome

**Comment by craigcitro** [comment]
That warning is harmless, though this is a good reminder to remove it.

It's impossible to say anything else without more info about the code that led to your crash.

**Comment by craigcitro** [comment]
For posterity, the `delete_to_trash` warning should go away in a few days.

**Comment by evawyf** [comment]
Thank you
