### ISSUE TITLE
UX: "Edit form attributes" dialog is well hidden

### ISSUE THREAD

**Issue by Aivean** [googlecolab/colabtools#2046]
**Describe the current behavior**

This tiny button, that appears only when form has a title, seems to be the only way to access "Edit form attributes" dialog:
<img width="497" alt="Screen Shot 2021-05-26 at 3 29 18 PM" src="https://user-images.githubusercontent.com/2865203/119739573-4a106800-be37-11eb-81d6-6391d0f65ded.png">

For the reference, here is the aforementioned dialog:
<img width=300 src="https://user-images.githubusercontent.com/2865203/119739740-8b087c80-be37-11eb-9f7a-22f12f60c73d.png"/>

**Describe the expected behavior**

There should be a more obvious way to access this dialog. For example, a good place for it would be "⋮ → Form" cell submenu:

<img width=500 src="https://user-images.githubusercontent.com/2865203/119739908-d1f67200-be37-11eb-8602-0fb3e70689d8.png" />

**Comment by corrieann** [comment]
Thanks for the suggestion.  You can now find it in the form cell submenu or the command palette.
