### ISSUE TITLE
text at bottom of cell is being cut off

### ISSUE THREAD

**Issue by pleabargain** [googlecolab/colabtools#2048]
I've noticed that text is getting off at the bottom of code cells
![cut off text 2021-05-27_13-17](https://user-images.githubusercontent.com/640846/119809903-383dcc00-beee-11eb-8587-427614e73555.png)

browser
Version 91.0.4472.77 (Official Build) (64-bit)

**Comment by cperry-goog** [comment]
Can you try again in an incognito window? This might be caused by extensions.

**Comment by pleabargain** [comment]
cut off again
https://i.imgur.com/VSJIWV4.png

extensions are not cut off
This behavior is only in Colab.

**Comment by blois** [comment]
Were you able to try in an incognito window? Also when this happens does it persist across a page reload? In the past there have been some similar issues after changing monitor resolutions.

**Comment by pleabargain** [comment]
The bug happens intermittently. I will try to run incognito from time to time and try to catch the bug again. Should I check the browser console for a specific error type?

**Comment by pleabargain** [comment]
![cutoff](https://user-images.githubusercontent.com/640846/121199572-b9487c00-c87b-11eb-9e35-833f68cc056c.png)

**Comment by craigcitro** [comment]
If this goes away in an incognito window, it's almost surely an extension causing trouble; I'd try disabling extensions until you find the culprit.

(If you do find it, please do report back -- it'd be useful to know for other users who may hit this.)

**Comment by pleabargain** [comment]
![image](https://user-images.githubusercontent.com/640846/122683016-5ead0980-d205-11eb-9eb9-80ddd7a2263f.png)
FWIW, the same problem is happening in Brave
Upgraded Chromium to 91.0.4472.106. (#16314)

and the only extension I'm using in Brave is google translate
