### ISSUE TITLE
 GPU:InternalError

### ISSUE THREAD

**Issue by omrylcn** [googlecolab/colabtools#205]
Hi , my Gpu is not work . When ı write code 

`from tensorflow.python.client import device_lib
device_lib.list_local_devices()`

I get this error 

---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
<ipython-input-1-161a99cea532> in <module>()
      1 from tensorflow.python.client import device_lib
----> 2 device_lib.list_local_devices()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/device_lib.py in list_local_devices(session_config)
     39   return [
     40       _convert(s)
---> 41       for s in pywrap_tensorflow.list_devices(session_config=session_config)
     42   ]

/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py in list_devices(session_config)
   1684                                           status)
   1685     else:
-> 1686       return ListDevices(status)
   1687 
   1688 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    517             None, None,
    518             compat.as_text(c_api.TF_Message(self.status.status)),
--> 519             c_api.TF_GetCode(self.status.status))
    520     # Delete the underlying status object from memory otherwise it stays alive
    521     # as there is a reference to status from this from the traceback due to

InternalError: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 11995578368

**Comment by colaboratory-team** [comment]
I wasn't able to reproduce this when running the snippet. If you're able to reproduce this issue, please do let us know. 

It's likely that other notebooks you are running are consuming available GPU memory. You can use the session manager to terminate background sessions by choose 'Manage sessions' from the Runtime menu.

![image](https://user-images.githubusercontent.com/38081706/55016053-40ff8400-4fab-11e9-9254-36d225627f31.png)
