### ISSUE TITLE
cannot read can't read oso from CSV file which is on google drive

### ISSUE THREAD

**Issue by arifsoul** [googlecolab/colabtools#2051]
**Describe the current behavior**
I use tensorflow object detection api on google colab which integrates gdrive and github. when going to make a TF record with CSV showing "emptydataerror" even though the file has contents.

**Describe the expected behavior**
want to know the cause colab can't read the contents of the csv file from the gdrive directory.

**What web browser you are using**
(Edge.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - https://colab.research.google.com/drive/138-021pmNb1rg90n1l4JYpV7Qo7kPdWa?usp=sharing

**Comment by cperry-goog** [comment]
We upgraded TensorFlow this week, we suspect this is related to that upgrade.

**Comment by arifsoul** [comment]
@cperry-goog thank you the problem has been resolved
