### ISSUE TITLE
python 3.8

### ISSUE THREAD

**Issue by pankajkumar9797** [googlecolab/colabtools#2054]
I am trying to run d2go but it requires python 3.8, when it is going to be available on Google Colab.
Error: Import Error, from typing import final (feature of python 3.8).

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, screenshots or notebooks about the feature request here.

**Comment by craigcitro** [comment]
dupe of #1880
