### ISSUE TITLE
Closing the menu and reopening it when upload is failed causes glitches

### ISSUE THREAD

**Issue by UnforeseenOcean** [googlecolab/colabtools#2056]
**Describe the current behavior**
Closing the left menu when the upload fails causes each file list to multiply (and the X button does not work)

**Describe the expected behavior**
When the X button is clicked, the failed upload is cleared. When the file menu is closed and reopened, the file list does not duplicate.

**What web browser you are using**
Firefox 88.0.1

**Additional context**
Making a self-contained Notebook cannot be done because the Notebook does not include uploaded files. Instead, here's the screenshot of the issue.
![IMG1622290573](https://user-images.githubusercontent.com/11834016/120069978-a2f43080-c0c3-11eb-891b-0745abafefde.png)
![GIF 5-29-2021 9-33-42 PM](https://user-images.githubusercontent.com/11834016/120070466-a25c9980-c0c5-11eb-827e-8c7c010d6af2.gif)

**Comment by colaboratory-team** [comment]
Thanks for the report. We'll take a look.
b/189633482

**Comment by cperry-goog** [comment]
We rolled out a fix for this, please re-open if you encounter the issue again. Thanks!
