### ISSUE TITLE
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.

### ISSUE THREAD

**Issue by chillaxkrish** [googlecolab/colabtools#2057]
Hi Team,

I was running the mentioned screenshot code for past three months. I have not faced any error for this. I didnt change anything in my project(all the code). last week also i run this code, its run goods without no issue. Yesterday onwards started getting this issue. Please help me. I was using this project in both chrome and Firefox

![image](https://user-images.githubusercontent.com/61927056/120079952-169e3980-c0d4-11eb-82d9-0c9e567e56d5.png)

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
We recently installed a new version of TensorFlow (2.5); consider installing an older version or updating your code for any incompatibilities.
