### ISSUE TITLE
JS in Colab returns null

### ISSUE THREAD

**Issue by qo4on** [googlecolab/colabtools#2058]
I tried to stop the `Colab` runtime without restarting it from a code cell. Manually I usually do this by clicking `Runtime` -> `Factory reset runtime` (it helps to reduce GPU usage time). The same thing I tried with `JS` but got `null` in the console:
```
import IPython

display(IPython.display.Javascript('''
xPathResult = document.evaluate(
    "//*[@class='goog-menu-button goog-inline-block']//*[contains(text(),'Runtime')]", document);
if(xPathResult){
     element = xPathResult.iterateNext();
}
console.log(element);
'''))
```
Why doesn't `IPython.display.Javascript` work as expected? Do you know another way to do this?

**Comment by blois** [comment]
Outputs are displayed in a sandboxed iframe with guarded access to the top-level window.

**Comment by qo4on** [comment]
@blois thank you for your answer. Is there an official way to stop the runtime from a code cell?

**Comment by blois** [comment]
The run button to the left of the cell should interrupt the runtime, or the Runtime -> Interrupt execution menu item should do the same.

Or are you looking for a way from the output to interrupt the execution? There are some techniques in https://colab.research.google.com/notebooks/snippets/advanced_outputs.ipynb for communicating back to the kernel from outputs.

**Comment by qo4on** [comment]
@blois 
No, I'm talking about terminating the whole VM session using code written inside a code cell. For example, this code kills current session (does factory reset: all files will be removed) and starts a new session:
```
!pkill --oldest
```
I'd like to do the same but do not start a new session after the previous one was terminated. This will help to reduce `Colab` usage time.
