### ISSUE TITLE
InvalidArgumentError:  logits and labels must be broadcastable: logits_size=[20,8] labels_size=[20,10]

### ISSUE THREAD

**Issue by chintanhvparmar** [googlecolab/colabtools#2059]
**Describe the current behavior**
Everytime i upload images manually from my laptop to google colab i get the below error. I am trying to use ImageDataGenerator for getting training and validation data and labels. It seems some hidden folders like .ipynb_checkpoints are causing the issue. This happens every time. IF i zip the folder and load it to cloud and then download it to colab using python and unzip using python then this issue is not seen. Please look into this issue. 

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:1940: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '
Epoch 1/30
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-71-c999c2d767df> in <module>()
      4       epochs=30,
      5       validation_data=val_generator,
----> 6       validation_steps=66)  

7 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError:  logits and labels must be broadcastable: logits_size=[20,8] labels_size=[20,10]
	 [[node categorical_crossentropy/softmax_cross_entropy_with_logits (defined at <ipython-input-59-c999c2d767df>:6) ]] [Op:__inference_train_function_5294]

Function call stack:
train_function
 
**Describe the expected behavior**
As described this error should not happen

**What web browser you are using**
Chrome
**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
Can you share a notebook with reproducible steps? I'm not sure how you're uploading images to Colab.
