### ISSUE TITLE
Feature request: hinterland support

### ISSUE THREAD

**Issue by simon-ritchie** [googlecolab/colabtools#206]
Maybe It would be useful if colab support [hinterland](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/hinterland), or  any other code autocompletion feature to avoid tab pressing.

**Comment by colaboratory-team** [comment]
b/72399263

**Comment by metrizable** [comment]
An auto-completion feature is currently supported. Closing.
