### ISSUE TITLE
the removed file is not removed

### ISSUE THREAD

**Issue by aydinmirzaeei** [googlecolab/colabtools#2061]
**Describe the current behavior**
I uploaded a file and now I really want to delete it, but every time I do this, it will be deleted, but when 1 day has passed, the file will be seen again..

**Describe the expected behavior**
Well, I want this file to be deleted and free space

**What web browser you are using**
Chrome

**Additional context**

**Comment by cperry-goog** [comment]
Do you have a repro notebook?

**Comment by aydinmirzaeei** [comment]
yes I had a repo notebook but I don't have it right now.
