### ISSUE TITLE
chrome Version 91.0.4472.77 spikes 100% on opening find and replace then chrome freezes

### ISSUE THREAD

**Issue by pleabargain** [googlecolab/colabtools#2062]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
open colab notebook
use crtl + h
chrome spikes 100% 
UI freezes   :(

**Describe the expected behavior**
chrome shouldn't freeze on opening a search function!

**What web browser you are using**
chrome Version 91.0.4472.77

Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
dgd@ubuntu20:~$

**Comment by corrieann** [comment]
Thanks for the report!  To help us pin down what's going on, please share a notebook that repros the issue.
