### ISSUE TITLE
google mount drive 

### ISSUE THREAD

**Issue by Dongximing** [googlecolab/colabtools#2063]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

![Screen Shot 2021-06-01 at 2 59 08 PM](https://user-images.githubusercontent.com/35741613/120501248-15e0fe00-c387-11eb-9b40-970a86e86f24.png)
when I run code , sometimes it will appear "Aw snap", how can I avoid it? thanks

**Comment by cperry-goog** [comment]
Can you reproduce this in an incognito window?

**Comment by Dongximing** [comment]
> Can you reproduce this in an incognito window?

sorry, I can not understand. what do you mean?

**Comment by cperry-goog** [comment]
Open Colab in a chrome incognito window and attempt the same steps.
