### ISSUE TITLE
keras functional API doesn not create layer

### ISSUE THREAD

**Issue by dongdori** [googlecolab/colabtools#2064]
**Describe the current behavior**
When I define deep learning model with functional keras api, model is defined without error but there are not any layer in the created model.
ex) 
input = Input(shape = (10,))
x = Dense(20)(input)
output = Dense(1)(x)
model = keras.models.Model(input, output)

model.layers  ======> [ ] (empty!)

Something weird is that when I excuted model.summary(), the number of parameters are correct but only layers are empty.
**Same code works well without any error in Kaggle Kernel**

**Describe the expected behavior**
model.layers shouldn't be empty list.

**What web browser you are using**
Chrome

**Additional context**
![image01](https://user-images.githubusercontent.com/70640345/120506984-6432e300-c401-11eb-888a-a6fa41f05790.png)

You might check this code that  I wrote. there are not any layers in model summary.

**Comment by cperry-goog** [comment]
We don't have any ability to troubleshoot Keras issues, suggest you ask in a Keras support channel, sorry!
