### ISSUE TITLE
When using sklearn module the autocomplete feature does not work

### ISSUE THREAD

**Issue by decodingcausality** [googlecolab/colabtools#2066]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by craigcitro** [comment]
Can you say more about what did/didn't work for you?

(Naively, importing sklearn or a submodule and autocompleting is working fine for me.)
