### ISSUE TITLE
Cannot change keras version on colab

### ISSUE THREAD

**Issue by Radhika-Keni** [googlecolab/colabtools#2068]
When I try to change the version of keras on colab(simple pip install) and simply run a keras_version command to follow , it fails.
Looks to me like the keras version is not getting installed correctly
![image](https://user-images.githubusercontent.com/68383273/120708111-c90d3c80-c4d8-11eb-8a72-5c5427f4c331.png)
![image](https://user-images.githubusercontent.com/68383273/120708147-db877600-c4d8-11eb-9968-fa4b08912d09.png)

Please advice

**Comment by craigcitro** [comment]
The issue here is that as part of the TF 2.5 update, we're currently installing `keras-nightly`; doing a `!pip uninstall keras-nightly` should get you unblocked.

**Comment by Radhika-Keni** [comment]
Thanks worked

**Comment by nataliameira** [comment]
@Radhika-Keni 
Hey
I trained my model.
My training was held on June 3, 2021.
I used:

pip uninstall keras-nightly
pip uninstall -y tensorflow
h5py==2.10.0
tensorflow==1.15
tensorflow-gpu==1.15.0
keras==2.1.6
