### ISSUE TITLE
Recently started getting FailedPreconditionError with keras optimizers

### ISSUE THREAD

**Issue by Sajal-1** [googlecolab/colabtools#2069]
**Describe the current behavior**
Getting FailedPreconditionError. The output says "could not find variable training/RMSprop/rho" or  "training/RMSprop/conv2d_8/bias/rms" or something else, basically different things in different runs.

**Describe the expected behavior**
This code was working fine till 29th April, but is giving errors now. Another thing which could maybe help in resolving the issue is that "from keras.utils import plot_model" was also working earlier but not now, so maybe there is some keras version issue.

**What web browser you are using**
Chrome

**Additional context**
https://colab.research.google.com/drive/1ylu1BV7IfZIbcQqz2DvSkxSeXdYF1rkR?usp=sharing

**Comment by craigcitro** [comment]
We updated TF to 2.5 recently, which led to keras-nightly being installed as well. You can update your code for the new versions, or downgrade TF and `!pip uninstall -y keras-nightly`.

**Comment by Sajal-1** [comment]
Thanks

And for anyone else facing the same issue, replacing keras by tensorflow.keras also solves the issue( for TF version 2.5.0).
