### ISSUE TITLE
sparsity_and_l1_regularization.ipynb Task 1 solution doesn't fulfill criteria in challenge.

### ISSUE THREAD

**Issue by scottleedavis** [googlecolab/colabtools#207]
The challenge:
**Find an L1 regularization strength parameter which satisfies both constraints — model size is less than 600 and log-loss is less than 0.35 on validation set.**

The provided solution says aregularization_strength=0.1, is a solution however the final results:
logloss: 0.25
modelsize: 747
...does not meet the challenge.

Instead regularization_strength=0.75 produces:
logloss: 0.25
modelsize: 593

thank you!

**Comment by sandacn** [comment]
need set regularization_strength>=0.7 , the model size will reduce to below 600
while set regularization_strength = 0.7, the model size is  599.

**Comment by sandacn** [comment]
But may be here is not just right for the issue. 
The repo is for colabtools not for notebook content. 
I think there should be another repo for the mlcc notebook

**Comment by craigcitro** [comment]
@sandacn yep, exactly right.

I've forwarded this report along, and I'm closing this issue.

**Comment by scottleedavis** [comment]
You are both right.  I have no idea what I am taking about.
