### ISSUE TITLE
Can't upload files larger than 1 MB

### ISSUE THREAD

**Issue by FekinML** [googlecolab/colabtools#2070]
**Describe the current behavior**
For the last 3 days, uploading of local files larger that 1 MB to the notebook's explorer fails every time (red ring). Restarting the runtime doesn't solve this, neither disconnecting and reconnecting. There is plenty of space left on the disk (28.53 GB) and the crash is not affected by whether the files are being uploaded in batch or one by one. File type doesn't affect the outcome either, just file size.

**Describe the expected behavior**
Everything was working fine until 4 days ago.

**What web browser you are using**
Firefox 89.0 64-bit

**Additional context**
![εικόνα](https://user-images.githubusercontent.com/85400780/120893549-26f26f00-c614-11eb-9411-97d597ce9141.png)

**Comment by cperry-goog** [comment]
We are unable to reproduce this, can you post repro steps? If possible, linking a problematic file would be beneficial as well.

**Comment by alexsanabria** [comment]
Hi for all,

I have the same problem in firefox 90.0.2 linux and windows versions
