### ISSUE TITLE
DISCONNECT TOO FREQUENTLY 

### ISSUE THREAD

**Issue by ifiscoder** [googlecolab/colabtools#2073]
my colab notebook disconnect immediately after connecting ,
this issue prevail 
I don't know what is causing this
I am unable to run a single code due to it 
please look into the matter

**Comment by srisri12** [comment]
Same Issue, I have mounted my google drive and suddenly it disconnects , doesn't matter what command I will use, It just disconnects within seconds, I think this issue is for both pro and free member, please solve this as soon as possible.

**Comment by ifiscoder** [comment]
> Same Issue, I have mounted my google drive and suddenly it disconnects , doesn't matter what command I will use, It just disconnects within seconds, I think this issue is for both pro and free member, please solve this as soon as possible.
My assumption is, it is temporary ban,
When you exhaust limit or when you do something that is not to be done you kind of are banned to server temporary for few days Or week

**Comment by ifiscoder** [comment]
If true colab should not impose ban longer, 
It it takes week or two then it is big issue

**Comment by cperry-goog** [comment]
We'll need more information to follow up on this bug report. Please submit feedback within Colab at Help > Send feedback.
