### ISSUE TITLE
Tensorflow version changing issue

### ISSUE THREAD

**Issue by chillaxkrish** [googlecolab/colabtools#2074]
![image](https://user-images.githubusercontent.com/61927056/120931904-34415380-c711-11eb-9dc1-f31143c96471.png)

**Describe the current behavior**
After changing tensorflow version to 2.2.0 . I cannot import other packages getting errors. Please check the issue

**Describe the expected behavior**
Dependencies problem should not come

**What web browser you are using**
Chrome, Firefox

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by craigcitro** [comment]
We recently upgraded to TF 2.5, which picked up a dependency on keras-nightly. If you `!pip uninstall -y keras-nightly` you should be unblocked.
