### ISSUE TITLE
Inline equation after a link not correctly rendered

### ISSUE THREAD

**Issue by tueda** [googlecolab/colabtools#2075]
**Describe the current behavior**

In text cells on Google Colaboratory, if an inline LaTeX math equation (`$...$`) is put just after an inline link without any spaces between them, then rendering this math expression is not triggered.

Example which does not work (without space):
```markdown
[Google](https://www.google.com/)$x^2+y^2=a^2$.
```

![image](https://user-images.githubusercontent.com/1481665/120983109-593ad280-c7b4-11eb-8ba8-1d3d70344f8c.png)

If I put a tiny space, then it works as expected.

Example which does work (note the space between the link and the equation):
```markdown
[Google](https://www.google.com/) $x^2+y^2=a^2$.
```

![image](https://user-images.githubusercontent.com/1481665/120983380-9acb7d80-c7b4-11eb-9284-7c6634f6e1bf.png)

Note that, in some languages, spaces between words are not needed and actually some style guides or text linters may strictly forbid any additional spaces (ideally, typesetting or text display systems should handle spacing adjustment in this case if needed, rather than by users).

**Describe the expected behavior**

Equations should be rendered correctly even without any spaces.

**What web browser you are using**

Chrome (91.0.4472.77, 64bits, Windows 10)

**Additional context**

Workaround with no additional visible spaces: putting `<!-- $ $ -->` triggers the equation rendering:
```markdown
[Google](https://www.google.com/)$x^2+y^2=a^2$.<!-- $ $ -->
```
![image](https://user-images.githubusercontent.com/1481665/120985219-5e991c80-c7b6-11eb-9fdf-1c5988e6d68d.png)

**Edit**: unfortunately, this workaround does not work for the following case and worsens the output:
```markdown
[Google](https://www.google.com/)$x \ge 0$.<!-- $ $ -->
```
![image](https://user-images.githubusercontent.com/1481665/121052239-2533d180-c7f5-11eb-906f-1e3e7d1645fd.png)

**Comment by cperry-goog** [comment]
Thank you for your report! This is super helpful for us, we'll take a look.

**Comment by cperry-goog** [comment]
Internally tracked at b/190753449

**Comment by blois** [comment]
This should now be fixed.
