### ISSUE TITLE
Colab pro does not give more than 16 gb of ram

### ISSUE THREAD

**Issue by helloworld123-lab** [googlecolab/colabtools#2076]
Today i upgraded my account to Colab pro. Although it prints the ram as:

```
Your runtime has 27.3 gigabytes of available RAM
    
    You are using a high-RAM runtime!
```
when I start training my model, it gives the error below.

`RuntimeError: CUDA out of memory. Tried to allocate 88.00 MiB (GPU 0; 15.90 GiB total capacity; 14.75 GiB already allocated; 75.75 MiB free; 14.95 GiB reserved in total by PyTorch)
`
Hyperparameters of my model:

```
args_dict = dict(
    #data_dir="", # path for data files
    output_dir="", # path to save the checkpoints
    model_name_or_path='t5-large',
    tokenizer_name_or_path='t5-large',
    max_seq_length=600,
    learning_rate=3e-4,
    weight_decay=0.0,
    adam_epsilon=1e-8,
    warmup_steps=0,
    train_batch_size=4,
    eval_batch_size=4,
    num_train_epochs=2,
    gradient_accumulation_steps=16,
    n_gpu=1,
    early_stop_callback=False,
    fp_16=True, # if you want to enable 16-bit training then install apex and set this to true
    opt_level='O1', # you can find out more on optimisation levels here https://nvidia.github.io/apex/amp.html#opt-levels-and-properties
    max_grad_norm=1.0, # if you enable 16-bit training then set this to a sensible value, 0.5 is a good default
    seed=42,
)
```
Colab pro not providing all ram. My code only works if train_batch_size = 1. What causes this? am I doing something wrong? Any ideas?

My complete code is in [https://colab.research.google.com/drive/1_gc-MT589474mo2ZiBlmAhdBX_-h445a?usp=sharing](url)

**Comment by colaboratory-team** [comment]
You're confusing system RAM (what there is 26GiB of) with GPU RAM (what there is different amounts of depending on which GPU is present on your  assigned VM, but 16GiB is a typical value).
