### ISSUE TITLE
 Runtime disconnected Your runtime has been disconnected due to inactivity or reaching its maximum duration. To connect to a new runtime, click the connect button below.

### ISSUE THREAD

**Issue by fatajima** [googlecolab/colabtools#2077]
Runtime disconnected
Your runtime has been disconnected due to inactivity or reaching its maximum duration.
To connect to a new runtime, click the connect button below.

 in every 10 minute and not fixed yet

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
We'll need more information to follow up on this bug report. Please submit feedback within Colab at Help > Send feedback.
