### ISSUE TITLE
error dialog box close button is not visible: put the close button at the top!

### ISSUE THREAD

**Issue by pleabargain** [googlecolab/colabtools#2078]
**Describe the current behavior**
error
error dialog shows
to close the error dialog user has to FIND the OK button at the bottom of the UI.
The error can be so BIG that the OK button is NOT visible until you ZOOM way out
see attachment

**Describe the expected behavior**
error
close error button is immediately visible at the TOP of the error

**What web browser you are using**
Chrome
Version 91.0.4472.77 (Official Build) (64-bit)
![no close 2021-06-09_09-02](https://user-images.githubusercontent.com/640846/121314549-20177500-c910-11eb-9767-b698fa756b4d.png)

**Comment by craigcitro** [comment]
Two questions:

* is the close button visible if you hit the button to collapse the error details?
* were the error details collapsed when the error appeared?

**Comment by craigcitro** [comment]
This should be fixed! Let us know if you're still seeing issues.
