### ISSUE TITLE
custom snippets not loading

### ISSUE THREAD

**Issue by pleabargain** [googlecolab/colabtools#2079]
here is the colab snippet
https://colab.research.google.com/drive/1OdSBJVh6BwTZrWm8SowD3O_QxLNYKZkk?usp=sharing

**Describe the current behavior**
snippet URL is loaded in settings
but
snippet is not loading in results

**Describe the expected behavior**
custom snippet should show up

**What web browser you are using**
(Chrome
Version 91.0.4472.77 (Official Build) (64-bit)

see gif
![custom snippets not loading Peek 2021-06-09 13-27](https://user-images.githubusercontent.com/640846/121339358-12b9b500-c927-11eb-9c35-a04fd1f45f7d.gif)

**Comment by pleabargain** [comment]
the snippet did show up later... I don't know how long to expect to wait but the snippet is there and works.

https://i.imgur.com/H8hZn1z.png

**Comment by nielsbom** [comment]
How long did you have to wait?
I first added URL A to the snippets setting, then URL B, but the snippets from A have kept showing up for about 15 minutes.

**Comment by richy1996** [comment]
stills happens for me regularly
