### ISSUE TITLE
Disconnecting internet browser (notebook) from the Colab server when cell runs for a long time

### ISSUE THREAD

**Issue by rustequal** [googlecolab/colabtools#2082]
A few days ago, the bug of disconnecting the browser from the Colab server began to appear during the long execution of the cell. If the notebook cell runs for a long time - several hours, then the notebook loses communication with the Colab server.
An error appears in the developer console of the Google Chrome browser:

_DevTools failed to load source map: Could not load content for https://colab.research.google.com/v2/external/js/min-maps/vs/base/worker/workerMain.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE_

**I will show you how it looks in the screenshots**

This screenshot shows the launch of the cell. Everything looks fine.

![01](https://user-images.githubusercontent.com/28533532/121782091-9b975180-cbb0-11eb-9e54-a9e0a132c79c.png)

After about 2.5 hours, the browser with the notebook loses connection with the Colab server. Note that the cell status has changed to stopped.

![02](https://user-images.githubusercontent.com/28533532/121782116-b669c600-cbb0-11eb-8d66-7fb9ac8f4b5e.png)

After the notebook has lost communication with the server, you can click refresh in browser. After that, the notebook is hooked up to the Colab server again

![03](https://user-images.githubusercontent.com/28533532/121782136-cbdef000-cbb0-11eb-8ff7-9f4e0fff7f66.png)

Below is a simple code that can be used to repeat this bug:

```
import time

print('Hello\n')
minute = 0

while True:
  time.sleep(60)
  minute += 1
  if minute % 120 == 0:
    print(minute)
```

I tried many options:
- Changing PCs to make sure that the problems are not in them
- Changing the Internet provider 3 times, used a VPN in order to make sure that the problem is not related to the network
- Changing internet browsers (Google Chrome , FireFox).

The version of Google Chrome browser is 91.0.4472.101 (Windows 10 Pro (build 2004)).
I want to note that the bug appeared just a few days ago. Before that, everything worked perfectly.

**Comment by topliftarm** [comment]
i have similar problem! disconnected after about 2.5 hours and ...

**Comment by aygul0790** [comment]
The exact same issue for my notebook!

**Comment by ckaarle** [comment]
I have the exact same problem as well.

**Comment by cperry-goog** [comment]
Thank you for the report and straightforward repro steps! We just rolled out a fix for this today, please re-open if you continue to observe this.

**Comment by shankhiremath** [comment]
The runtime is getting disconnected within 20 seconds of running a cell on Chrome. Here are the error messages in the console. Can you please fix this problem?
<img width="460" alt="colab error 3" src="https://user-images.githubusercontent.com/45012110/170011949-a9add0d1-f828-455f-8269-757a1a18b2e0.png">
<img width="465" alt="colab error" src="https://user-images.githubusercontent.com/45012110/170011991-32e09c50-6a61-477b-8eff-dd0946c0bec1.png">
<img width="463" alt="colab error 2" src="https://user-images.githubusercontent.com/45012110/170012004-e386b1ff-d3f0-4c43-bbd7-05ac5a5a0c8b.png">
