### ISSUE TITLE
ISSUE IN CONNECTION TO GOOGLE DRIVE

### ISSUE THREAD

**Issue by python-hunglyreha** [googlecolab/colabtools#2085]
Madam/Sir:

I received the following error while mounting google drive. Kindly guide.

from google.colab import drive
drive.mount('/content/drive')

Yours truly,

Python-Hungry
[Screenshot1.xlsx](https://github.com/googlecolab/colabtools/files/6644411/Screenshot1.xlsx)

**Comment by cperry-goog** [comment]
Can you paste the error message text here, or attach as an image?

**Comment by python-hunglyreha** [comment]
Sir:

Every time I mount the drive, I receive the following message.

[image: image.png]


When I run the cell as described above, it looks for some kind of
authentication interims of system generated password. and then mount to
drive.The respective screenshots are attached herewith.

[image: image.png]

[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
Kindly guide me.

Yours sincerely,

Sheikh Rehan Aslam

**Comment by craigcitro** [comment]
Attaching the files to the email won't work; you can add them directly in the github UI.
