### ISSUE TITLE
Security bug

### ISSUE THREAD

**Issue by Marimuthu0403** [googlecolab/colabtools#2086]
**Describe the current behavior**
when Run time warning occurs , it shows warning with file location details

**Describe the expected behavior**
I expected run time error

**What web browser you are using**
Chrome

**Additional context**
Security bug :
 I found a bug, when I run a math calculations .
I intensionally created this code just to test it . But it shows error with your file location details . you may missed to catch this exception .However I don't know what's fully wrong here . But i know ,it may cause some security issues . Please fix it . Thanks !

photo of bug attached **
![error_google](https://user-images.githubusercontent.com/85847696/121821059-07aeae00-ccb4-11eb-8566-5f591c3074fb.png)

**Comment by craigcitro** [comment]
There's no bug here: the warning is expected, and the file path isn't secret, so there's no security issue.
