### ISSUE TITLE
cell output has too much trailing newlines when running Keras code

### ISSUE THREAD

**Issue by sohnryang** [googlecolab/colabtools#209]
When I run this code from [tensorflow.org tutorial](https://www.tensorflow.org/tutorials/).

```python
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)
```

The output cell looks like this:

![3](https://user-images.githubusercontent.com/15506585/42721429-c9c042c4-8775-11e8-9e22-fd94594b850c.png)

It seems that there's too much trailing newlines.

**Comment by colaboratory-team** [comment]
I wasn't able to reproduce this behavior when executing the referenced snippet. Please reopen if this issue is still occurring for you.
