### ISSUE TITLE
Can't `cat` gdoc, gslides, etc.

### ISSUE THREAD

**Issue by DUOLabs333** [googlecolab/colabtools#2090]
_Note:_ Most of this can be found here: https://stackoverflow.com/questions/68042477/oserror-when-using-shutil-with-strings-with-double-quotes-in-them

I'm using Google Colab to back up my drive, and I'm using the `shutil` library to back it up. All goes well, until it comes upon a file like this: '/drive1/MyDrive/"Foo" bar.gdoc'. Then it returns: `OSError: [Errno 95] Operation not supported: '/drive1/MyDrive/"Foo" bar.gdoc'`. 

After a bit of tracking down, I believe I found the culprit: you can't `open` `gdoc` files in Colab, so they can't write. `cp` doesn't work either.

To reproduce, mount a drive with a google doc and try to `cat` a Google doc or try:
```
with open('/drive1/MyDrive/foobar.gdoc','rb') as f:
  print(f.read())
```

**Comment by craigcitro** [comment]
This is WAI: contents of google-hosted types (docs, sheets, slides, etc) aren't accessible via mounting Drive in Colab.
