### ISSUE TITLE
OSError when importing torch_geometric

### ISSUE THREAD

**Issue by vtsiouri** [googlecolab/colabtools#2091]
Hi,

When importing torch_geometric in my Colab notebook I get the following error:

> OSError                                   Traceback (most recent call last)
<ipython-input-7-c4b5cfe24cae> in <module>()
     36 from sklearn.model_selection import RandomizedSearchCV
     37 import torch
---> 38 from torch_geometric.data import Data
     39 from torch_geometric.nn import GCNConv, GATConv, GatedGraphConv
     40 from sklearn.ensemble import RandomForestClassifier
5 frames
/usr/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle
OSError: /usr/local/lib/python3.7/dist-packages/torch_sparse/_convert_cuda.so: undefined symbol: _ZNK2at6Tensor6deviceEv

This started happening yesterday evening. Before that time, I could import the libraries and run my code without any problems. 

I have installed pytorch version 1.8.0 and CUDA 10.1:
`!pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html`
`!pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html`
`!pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html`
`!pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html`
`!pip install torch-geometric`

**Comment by vtsiouri** [comment]
Hi,
When importing torch_geometric in my Colab notebook I get the following error:
`OSError                                   Traceback (most recent call last)
<ipython-input-7-c4b5cfe24cae> in <module>()
     36 from sklearn.model_selection import RandomizedSearchCV
     37 import torch
---> 38 from torch_geometric.data import Data
     39 from torch_geometric.nn import GCNConv, GATConv, GatedGraphConv
     40 from sklearn.ensemble import RandomForestClassifier

5 frames
/usr/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: /usr/local/lib/python3.7/dist-packages/torch_sparse/_convert_cuda.so: undefined symbol: _ZNK2at6Tensor6deviceEv`

This started happening yesterday evening. Before that time, I could import the libraries and run my code without any problems. 

I have installed pytorch version 1.8.0 and CUDA 10.1:
`!pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html
!pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html
!pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html
!pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html
!pip install torch-geometric
![error when importing torch_geometric](https://user-images.githubusercontent.com/79109135/122636102-b05f7200-d0e7-11eb-9a05-150585c555d4.PNG)
`

**Comment by craigcitro** [comment]
We updated pytorch to 1.9.0 last week, which is almost surely the root cause for your issue.

Note that your install stanza isn't actually changing the *torch* version; I suspect that's the thing to fix.

**Comment by tungts1101** [comment]
I have tried version 1.9.0 and still got this error in colab. Here is my script to install based on https://gist.github.com/ameya98/b193856171d11d37ada46458f60e73e7

```
# Add this in a Google Colab cell to install the correct version of Pytorch Geometric.
import torch

def format_pytorch_version(version):
  return version.split('+')[0]

TORCH_version = torch.__version__
TORCH = format_pytorch_version(TORCH_version)

def format_cuda_version(version):
  return 'cu' + version.replace('.', '')

CUDA_version = torch.version.cuda
CUDA = format_cuda_version(CUDA_version)

!pip install torch-scatter     -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-sparse      -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-cluster     -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-geometric 
```
