### ISSUE TITLE
Collab crashes intermittently without any specific error

### ISSUE THREAD

**Issue by aritraghosh** [googlecolab/colabtools#2093]
**Describe the current behavior**
When I try to run a code snippet, it crashes and resstarts

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
[Chrome]

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
Will you share a minimal repro notebook with the snippet you ran that crashed? Thanks.
