### ISSUE TITLE
The file browser randomly disappears

### ISSUE THREAD

**Issue by Orchoidizer** [googlecolab/colabtools#2095]
This issue with the file browser randomly disappearing has been happening a few weeks now.

Has anybody discovered any ways to stop this happening or at least a workaround for when it does.

The only way to bring it back is to terminate whichever process your working in and restart it which is an absolute pain if it disappears when your in the middle of merging especially!

![123174884-c28b3880-d478-11eb-87c2-4a0de806e24b](https://user-images.githubusercontent.com/54647922/123431492-389ab700-d5c1-11eb-95c2-a5e1b9dda63d.JPG)

**Comment by cperry-goog** [comment]
Can you try this in an incognito window and see if it reproduces?
