### ISSUE TITLE
File Path copying is getting failed when working on scratch cell

### ISSUE THREAD

**Issue by hariappliedai** [googlecolab/colabtools#2096]
**Describe the current behavior**
When working with scratch cell copying the file path from file explorer is not copying the path but it is copying the content of the scratch sell itself 

**Describe the expected behavior**
Expected behavior is to copy the  path of the file

https://user-images.githubusercontent.com/83105811/123505555-6d6c4400-d67d-11eb-86db-27027b83388a.mp4

**What web browser you are using**
chrome

**Comment by corrieann** [comment]
Thanks for the report!  This has been fixed.
