### ISSUE TITLE
Colab becomes stuck on "connecting"

### ISSUE THREAD

**Issue by neel04** [googlecolab/colabtools#2097]
### Describe the current behavior

I am trying to run a script to spawn model processes on all TPU cores, and train the model via data parellism. However, it seems after running the script for a couple of minutes, I get the colab "Connecting" status, where it stays unless I scrap the runtime.

### Describe the expected behavior

Colab to remain connected and not disconnect

### What web browser you are using

Latest `Firefox`

### Additional context
- _**I am using Colab Pro**_ 

With the 35Gb RAM, and available Disk space, I don't think resources can be a problem; however it might be that some part of the instance is taken up when deploying the script causing it to fail. Will investigate more on this line of thinking.

Does anyone have some clue as to what part I can investigate to troubleshoot this issue?

**Comment by cperry-goog** [comment]
If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback and mention this GitHub issue.

**Comment by sar-m** [comment]
I had the same problem. Colab disconnected while running and it was giving me the "Connecting" status since. I was able to connect again only after I terminated that session and started a new one.
