### ISSUE TITLE
Change in behaviour of ctrl+c, ctrl+x for cells opened in tab (side pane)

### ISSUE THREAD

**Issue by tumble-weed** [googlecolab/colabtools#2099]
**Describe the current behavior**
There is a change in behavior while using ctrl+c, ctrl+x etc. on cells opened in tab (side pane) ( scratch cell and mirrored cells), where now this key combination is copying/cutting the entire cell instead of selections within it. Have noticed it on 2 computers

**Describe the expected behavior**
ctrl+c should be copying selected text, and ctrl+m,c should be copying the cell. similarly for cutting and pasting

**What web browser you are using**
Firefox on ubuntu, chrome on ubuntu

**Comment by corrieann** [comment]
Thanks for the report!  This has been fixed.

**Comment by tumble-weed** [comment]
nope. still not fixed for me.
