### ISSUE TITLE
IOPub data rate exceeded

### ISSUE THREAD

**Issue by gaceladri** [googlecolab/colabtools#21]
I am having the next issue when try to load a file from drive that is bigger than 10mb.

the code:

`file_id = ...` 

`import io`
`from googleapiclient.http import MediaIoBaseDownload`

`request = drive_service.files().get_media(fileId=file_id)`
`downloaded = io.BytesIO()`
`downloader = MediaIoBaseDownload(downloaded, request)`
`done = False`
`while done is False:`
`  _, done = downloader.next_chunk()`

`downloaded.seek(0)`
`print('Downloaded file contents are: {}'.format(downloaded.read()))`

The issue:

`IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
--NotebookApp.iopub_data_rate_limit.`

`Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)`

**Comment by blois** [comment]
The issue is with the final line:

```python
print('Downloaded file contents are: {}'.format(downloaded.read()))
```

The large file cannot be displayed at once. I would recommend either only display a portion of the file. You could try displaying in multiple chunks, but this will also run into a 10MB limit on the amount of data allowed in the notebook display.
