### ISSUE TITLE
Cant downlod file by google.colab.files TypeError: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by hadaev8** [googlecolab/colabtools#210]
---> 28   files.download(name)

/usr/local/lib/python3.6/dist-packages/google/colab/files.py in download(filename)
    174       'port': port,
    175       'path': os.path.abspath(filename),
--> 176       'name': os.path.basename(filename),
    177   })

/usr/local/lib/python3.6/dist-packages/google/colab/output/_js.py in eval_js(script, ignore_result)
     37   if ignore_result:
     38     return
---> 39   return _message.read_reply_from_input(request_id)
     40 
     41 

/usr/local/lib/python3.6/dist-packages/google/colab/_message.py in read_reply_from_input(message_id, timeout_sec)
     84         reply.get('colab_msg_id') == message_id):
     85       if 'error' in reply:
---> 86         raise MessageError(reply['error'])
     87       return reply.get('data', None)

**Comment by hadaev8** [comment]
Firefox browser.

**Comment by blois** [comment]
There is a new file download UI in the notebook sidebar, alongside the table of contents.
