### ISSUE TITLE
Colab's frequent runtime disconnection and crash

### ISSUE THREAD

**Issue by SShuchitaS** [googlecolab/colabtools#2104]
Colab's runtime disconnects minutes after executing a cell despite the continuous interaction and a strong network connection. It also gets hang while displaying the output from google drive. I have copied the dataset into colab's VM using the zip and unzip method but it wasn't of any help and the colab hanged while displaying the output and also the runtime got disconnected early. Also, we can't change the data rate limit in colab.

**Comment by azidanit** [comment]
same with me.. just using colab pro today.. Runtime disconnected after a few second, although not using GPU and higher RAM.

**Comment by JoelGarcia99** [comment]
Same problem. I thought it was my internet connection, but it seems to be a Google problem

**Comment by cperry-goog** [comment]
Please follow #2032
