### ISSUE TITLE
Disconnected execution environment in seconds.

### ISSUE THREAD

**Issue by thiob92** [googlecolab/colabtools#2106]
I've been using Colab for 15 days and with the paid version COLAB PRO. I can't even sign in to my google account without disconnecting from the Google Compute Engine backend. Since I started the subscription only 1 time I managed to spend more than 50 gb. Now not even 1 gb passes even after 3 days without accessing the platform. I use High RAM at most and I don't use GPU or TPU. I just want to transfer my data from MEGA to Google. Disconnection takes place without the slightest program error, it simply disconnects in seconds. Please help me! And I've already sent the information through feedback, but so far nothing! What can I do?

**Comment by azidanit** [comment]
same with me.. just using pro today.. Runtime disconnected randomly after a few second, although not using GPU and higher RAM.

**Comment by cperry-goog** [comment]
Please follow #2032
