### ISSUE TITLE
Session keep disconnect when my laptop is lock or sleep

### ISSUE THREAD

**Issue by chethan-avyay** [googlecolab/colabtools#2107]
I'm a google co-lab pro user I'm running hyperparameter tuning for a large dataset with a lot of parameters it will take more than a day to run. but co-lab session gets disconnect if leave the running notebook for a night and in the morning there is no output even I connect to the session again
I'm using google-chrome
Please can you add a persistent session if the cell is running

**Comment by cperry-goog** [comment]
Colab generally prioritizes interactive compute sessions, and cannot at this time guarantee non-interactive long-running jobs will complete. We're working on features to permit this in the future. You might try modifying your job to occasionally output a result.

**Comment by chethan-avyay** [comment]
> Colab generally prioritizes interactive compute sessions, and cannot at this time guarantee non-interactive long-running jobs will complete. We're working on features to permit this in the future. You might try modifying your job to occasionally output a result.

Thanks for the response, I found out that if I avoid sleeping mode in my machine then works like charm. quick fix
