### ISSUE TITLE
Checkpoints are reported as Corrupted

### ISSUE THREAD

**Issue by saakshi077** [googlecolab/colabtools#2111]
**Current behavior**
I uploaded the checkpoints file on drive and then mounted drive to Colab. But the Colab is giving runtime error and says that the files are corrupted.

**Expected behavior**
I want to execute loho.py and make sure that weights are loaded and checkpoints and it generates the output.
**What web browser you are using**
I am using Google Colab Pro version (running code on GPU) on Chrome

**Error Msg :**
This is the error msg :
Setting up Perceptual loss... Loading model from: /content/LOHO/networks/lpips/weights/v0.1/vgg.pth ...[net-lin [vgg]] initialized ...Done Setting up Perceptual loss... Loading model from: /content/LOHO/networks/lpips/weights/v0.1/vgg.pth ...[net-lin [vgg]] initialized ...Done Constructing DeepLabv3+ model... Number of classes: 20 Output stride: 16 Number of Input Channels: 3 /content/drive/MyDrive/inference.pth Traceback (most recent call last): File "/content/LOHO/loho.py", line 180, in <module> state_dict = torch.load(graphonomy_model_path) File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 595, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 781, in _legacy_load deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly) RuntimeError: unexpected EOF, expected 1362420 more bytes. The file might be corrupted.
`
**Files**
Link to the Repo(that I am trying to run) : https://github.com/saakshi077/LOHO
Link to the colab file (open ) : https://colab.research.google.com/drive/1ykZK0v81l20UnbFDhr1P6PH54gFGhBqV?usp=sharing

**Comment by cperry-goog** [comment]
I don't see this error in your linked Colab, did you manage to fix it?

**Comment by saakshi077** [comment]
Yes, fixed it .Thank you
