### ISSUE TITLE
Execution of cells is queued

### ISSUE THREAD

**Issue by gilbertbadaro** [googlecolab/colabtools#2112]
Hi,
Since today morning July 1st 2021, the execution of cells is queued and not being completed. I am subscribed to colab pro.
![image](https://user-images.githubusercontent.com/58029672/124126121-9e33eb00-da7a-11eb-93fd-9f637a76083b.png)

**Comment by ahazeemi** [comment]
I'm having the same issue. Cells are getting queued and aren't being executed.

**Comment by gilbertbadaro** [comment]
The issue is still not resolved and I have a Colab Pro account.

**Comment by Pantalaymon** [comment]
Same problem for me. I upgraded to Pro but to no avail, it doesn't fix anything.

**Comment by sainttttt** [comment]
I'm having the same issue as well.

**Comment by blois** [comment]
A few questions-
 - Does this repro in an incognito window?
 - Does this repro after running Runtime -> Factory reset runtime (for a notebook such as https://colab.research.google.com/notebooks/intro.ipynb)?

**Comment by sainttttt** [comment]
I'll check it out in a bit with an incognito window, but it does work when I factory reset, however the issue comes  up again. It's not that no cells ever run. They run in the beginning and then at some point they just get queued, and only a factory reset will get it to start executing again. It seems randomly as to how long it lasts before it starts queuing. This issue does seem to be recent.

**Comment by zhangyidavidfan** [comment]
Someone please fix this :(

**Comment by Pantalaymon** [comment]
> A few questions-
> 
> * Does this repro in an incognito window?
> * Does this repro after running Runtime -> Factory reset runtime (for a notebook such as https://colab.research.google.com/notebooks/intro.ipynb)?

I have the same answers as @sainttttt .
It also happens in incognito windows for me.

I'll add that it always happens whenever there is an error when a cell is ran (which forces me to factory reset to fix every little exception while debugging)

**Comment by blois** [comment]
> I'll add that it always happens whenever there is an error when a cell is ran

Do you have a consistent repro which can be shared?

Does Runtime -> Restart runtime fix the issue, as opposed to Runtime -> Factory reset runtime?

Does reloading the page while the cell is queued do anything?

The next time that this happens, can you use Help -> Send feedback to send feedback? This may give us a bit more info.

**Comment by gilbertbadaro** [comment]
> Do you have a consistent repro which can be shared?
I have sent the notebook to a colleague and he didn't face any issue. It seems it is account related?

> Does Runtime -> Restart runtime fix the issue, as opposed to Runtime -> Factory reset runtime?
The factory reset fixes the issue to be able to run one more cell and then the queueing issue is back again.

> The next time that this happens, can you use Help -> Send feedback to send feedback? This may give us a bit more info.
I did this when I created the issue.

**Comment by blois** [comment]
To clarify- it seems that restart runtime should be sufficient as opposed to the full factory reset? (Restart runtime restarts the Python process, factory reset assigns a new VM).

Does reloading the page make any difference? We still have not been able to repro and are trying to understand the issue more.

**Comment by sainttttt** [comment]
Here is a link to what happens: https://streamable.com/upxg1y

As of right now it seems that if I refresh it helps and it gets it unstuck, but it doesn't save changes during this time. I have to refresh several times. Other times refreshing wouldn't help and I would have to do a reset

**Comment by blois** [comment]
Thanks @sainttttt - you appear to be installing `simpletransformers` then restarting the runtime to pick up a new ipykernel verison. Does this repro on notebooks which do not upgrade ipykernel? We have not done extensive validation of that version which was just [released June 30th](https://pypi.org/project/ipykernel/#history).

**Comment by Pantalaymon** [comment]
> > I'll add that it always happens whenever there is an error when a cell is ran
> 
> Do you have a consistent repro which can be shared?
> 



> Does Runtime -> Restart runtime fix the issue, as opposed to Runtime -> Factory reset runtime?
> 
It depends. Sometimes a single Runtime -> Restart runtime fixes it but sometimes two or three are needed.

> Does reloading the page while the cell is queued do anything?

Sometimes yes, sometimes no.


> Here is a link to what happens: https://streamable.com/upxg1y
> 
> As of right now it seems that if I refresh it helps and it gets it unstuck, but it doesn't save changes during this time. I have to refresh several times. Other times refreshing wouldn't help and I would have to do a reset

By watching your stream I think I may have found the origin of the issue. You install the library simpletransformers at the beginning of the notebook and so do I. 
I then started running some of the cells of my notebook without the `!pip install simpletransformers` one (and all the related code) and I didn't run into the issue.

It is strange because I have used this library before but never had this problem.

**Comment by blois** [comment]
After installing `simpletransformers` can you downgrade `ipykernel` with `!pip install "ipykernel<6"` (and restart kernel with that version) to see if that makes a difference?

This can be used to check the ipykernel version:
```
import ipykernel
ipykernel.version_info
```

Colab's default is 4.10.1 but from the timeline anything <6 may be sufficient.

**Comment by sainttttt** [comment]
Here is another example, where it seems to break if I run any sort of function https://streamable.com/xg0n7e
Refreshing doesn't seem to work in this case. Even when I  reset the notebook it doesn't work https://streamable.com/l7qvlq.

I tried testing this without doing pip install and I don't seem to have the problem. So yeah I think it's related to that.

**Comment by sainttttt** [comment]
> After installing `simpletransformers` can you downgrade `ipykernel` with `!pip install "ipykernel<6"` (and restart kernel with that version) to see if that makes a difference?
> 
> This can be used to check the ipykernel version:
> 
> ```
> import ipykernel
> ipykernel.version_info
> ```
> 
> Colab's default is 4.10.1 but from the timeline anything <6 may be sufficient.

I did this and it seems to work fine. It installs ipykernel-5.5.5 and I don't seem to have any stuck cells anymore!

**Comment by craigcitro** [comment]
This should be fixed! Let us know if you're still seeing trouble.
