### ISSUE TITLE
(Still Not Working) Change in behaviour of ctrl+c, ctrl+x for cells opened in tab (side pane) 

### ISSUE THREAD

**Issue by tumble-weed** [googlecolab/colabtools#2115]
(Note: the fix mentioned in https://github.com/googlecolab/colabtools/issues/2099  does not work)

**Describe the current behavior**
There is a change in behavior while using ctrl+c, ctrl+x etc. on cells opened in tab (side pane) ( scratch cell and mirrored cells), where now this key combination is copying/cutting the entire cell instead of selections within it. Have noticed it on 2 computers

**Describe the expected behavior**
ctrl+c should be copying selected text, and ctrl+m,c should be copying the cell. similarly for cutting and pasting

**What web browser you are using**
Firefox on ubuntu, chrome on ubuntu

**Colab Pro**

**Comment by corrieann** [comment]
I can't reproduce the issue you describe.
Is it possible you're using a tab that was opened before the fix or loading cached resources?  Try clearing your cache and reloading.  If that doesn't work, more info about any custom keybindings that you have set up would be helpful.

**Comment by tumble-weed** [comment]
Hi, thanks for the response. In the past few days, its mostly been working, but here and there i've seen the copy scratch cell behaviour. 
I dont have any custom keybindings.
At this point i think it might be related to the cache like you said, I shall be able to clear it later. I will close this issue.
thanks
