### ISSUE TITLE
Pip version is too old

### ISSUE THREAD

**Issue by st-pasha** [googlecolab/colabtools#2116]
By default, Google Colab runs in an environment with pip 19.3.1:
```
>>> !pip --version
pip 19.3.1 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
```
However, pip 19.3.1 is too old to properly support Linux environment: [PEP-600](https://www.python.org/dev/peps/pep-0600/) has introduced new platform tags of the form `manylinux_${GLIBCMAJOR}_${GLIBCMINOR}_${ARCH}`, which are only recognized by pip 20.3+. Moreover, these new platform tags are now (since May 5th 2021) emitted by default by the auditwheel tool, which means that any new manylinux wheels created after May cannot be easily installed on Google Colab.

In order to remedy this situation, please consider upgrading the default version of `pip` in your environment to preferably latest, but at the very least to version `20.3.0`, which is the earliest version of pip that supports new manylinux tag names.

**Comment by colaboratory-team** [comment]
Thanks for the report. We've updated `pip` to version 21.1.3.
