### ISSUE TITLE
Colab unable to load/mount My Drive

### ISSUE THREAD

**Issue by jjsammii** [googlecolab/colabtools#2118]
https://github.com/googlecolab/colabtools/wiki/Bug-Reports

**Describe the current behavior**
Im unable to mount my google drive in colab
![Capture](https://user-images.githubusercontent.com/85793576/124545567-e5a9d680-ddee-11eb-9b18-422edc2c00ce.PNG)
. The error I get is . I tried to manually copy and paste the auth code but I still get the same error. I suspect it has to do with the total number of images in my directory, but I have over 50K images and I dont think I can manually delete them all. Using Shift and control A still doesn't select all the images for me to delete. What is the work around?

**Describe the expected behavior**
Unable to Load/Mount Google Drive within colab

**What web browser you are using**
(Chrome)

**Comment by CurtisASmith** [comment]
If the problem is that your Drive has too many individual files, and you can't delete files on your Drive in-browser, [maybe the API will help](https://developers.google.com/drive/api/v3/reference/files/delete).

**Comment by cperry-goog** [comment]
See https://research.google.com/colaboratory/faq.html

Why does drive.mount() sometimes fail saying "timed out", and why do I/O operations in drive.mount()-mounted folders sometimes fail?
