### ISSUE TITLE
Cant upgrade tensorflow

### ISSUE THREAD

**Issue by hadaev8** [googlecolab/colabtools#212]
Then running this command
!pip install --upgrade tensorflow-gpu
Get error
error tcmalloc: large alloc 1073750016 bytes == 0x4d3ce000 @
And tensorflow installation corrupted.

**Comment by colaboratory-team** [comment]
Unfortunately, adjusting the TensorFlow GPU version requires many adjustments to system libraries and the environment. There isn't a simple way to accomplish a GPU self-install right now.
