### ISSUE TITLE
Cell stuck after running and not giving any response

### ISSUE THREAD

**Issue by Patrickbro13** [googlecolab/colabtools#2123]
I am using autogluon library in my google colab where I loaded my dataset and tried to reset the index with data.reset_index() method but colab cell remain stucked  and on hovering it says cell has not been executed even when I ran the cell.
code :
 ```
 import autogluon.core as ag
from autogluon.tabular import TabularPrediction as task
data = task.Dataset(file_path='/content/csv_nfl_data.csv')
data.reset_index()
 ```
This how it looks : 
![image](https://user-images.githubusercontent.com/55437218/125097680-00809180-e0f4-11eb-86fe-d7c590cf17d2.png)

But when I tried running the same before 4-5 hrs. it was working fine but now I am facing this problem
I am currently using Chrome browser and I also tried restarting kernel but its not working.

Notebook link : https://colab.research.google.com/drive/1JeK6zFR78fgYklaoyJbsE04mEjrPnWVC?usp=sharing

**Comment by blois** [comment]
Similar to https://github.com/googlecolab/colabtools/issues/2112?

**Comment by Patrickbro13** [comment]
So in short I need to downgrade the version of ipykernel right ?

**Comment by blois** [comment]
Yes-

```
!pip install "ipykernel<6"
```

Then restart your runtime to pick up the new version.

**Comment by Patrickbro13** [comment]
yes it works !
Thank you @blois
