### ISSUE TITLE
Collab Pro not using GPU memory to full extend compared to similar configuration GPU

### ISSUE THREAD

**Issue by Shaurya026** [googlecolab/colabtools#2126]
**Collab pro** provides me with approximately 15.9 GB of GPU RAM which is similar to the one provided by kaggle notebooks.   
But while training networks on Collab pro, the GPU RAM utilization is not upto the mark:   
<p align="center">
  <img  src="https://user-images.githubusercontent.com/43774789/125161744-a1795600-e1a1-11eb-8bd3-c39cc3c9ffa9.png" alt="Sublime's custom image"/>
</p>
whereas running the same network on kaggle(with same GPU configuration) provides much better speed and utilization of GPU RAM:  
<p align="center">
  <img width="200" height="300" src="https://user-images.githubusercontent.com/43774789/125161985-20bb5980-e1a3-11eb-8691-cdb1c71ac9d5.png" alt="Sublime's custom image"/>
</p>  

I also applied various methods in hope to get more GPU RAM utilization using the following code but found no luck: 
```
physical_devices = tf.config.list_physical_devices('GPU')  
try:  
    tf.config.experimental.set_per_process_memory_fraction(0.75)  
except:  
    pass
```
  
Is there someway to get proper utilization in COLLAB PRO ? Please provide a solution to this, Thank You

**Comment by cperry-goog** [comment]
If you have a self-contained repro notebook that displays different data on Kaggle and Colab, that would be helpful. Please ensure the GPU chips are identical.

**Comment by Shaurya026** [comment]
Thank You for replying. 
Sorry but i can't share the files for its privately-held project.   
After a few days i noticed that GPU RAM consumption varied from session to session, with better performance sometimes after each pertaining epoch. Don't know what triggers it but below is a picture for reference on my current model training after 10hrs: 

<p align="center">
  <img  src="https://user-images.githubusercontent.com/43774789/125872455-dfe8b696-59d7-4bdf-943c-765672540e79.png" alt="Sublime's custom image"/>
</p>    
Even the system RAM consumption grows with time. and yes the GPU chips are identical, both kaggle and collab pro uses P100 with same configurations. Eventually collab picks up the speed and provides similar performance, For longer runtimes that's sufficient for me. So, i'll be closing my issue.
