### ISSUE TITLE
Every cell retains its cursor after execution.

### ISSUE THREAD

**Issue by farhan-naqvi** [googlecolab/colabtools#2129]
After execution of one cell, the cursor retains its position as well as appears in the next cell. Also when I click on any other cell the cursor appears in previous and present both.

Link to the image: https://github.com/farhan-naqvi/bugs/blob/main/multiple%20issues.PNG

**Comment by cperry-goog** [comment]
Can you reproduce this in an incognito window?

**Comment by farhan-naqvi** [comment]
> Can you reproduce this in an incognito window?

The issue was resolved after i reset my browser's factory settings. I don't think this issue would occur in incognito window.
