### ISSUE TITLE
Provide "Run Current Line" option

### ISSUE THREAD

**Issue by arteagac** [googlecolab/colabtools#2132]
**Is your feature request related to a problem? Please describe.**
Some developers run their Python code line by line and in Colab it's inconvenient and time consuming having to select the entire code in the current line every time. In JupyterLab and Rstudio there is an option called "Run current line", which is much more convenient.

**Describe the solution you'd like**
Provide a "Run current line" option. This option can be mixed with "Run selection" and have a single "Run selection or current line" option, which is the way JupyterLab works. After running the current line, the cursor should automatically move to the next line.

**Describe alternatives you've considered**
I tried shortcuts to select the entire code in the current line but this is still inconvenient. 

**Additional context**
I attach an image of how it is displayed in Jupy
![B3LTS](https://user-images.githubusercontent.com/13966395/125508263-cce0bf6d-2d06-4b94-9868-e35eea719aad.png)
terLab.

**Comment by blois** [comment]
Thanks for the suggestion! The "Run selection" command should now run the current line if nothing is selected.

**Comment by arteagac** [comment]
This is so great! I checked it and it works like a charm. Thank you so much for implementing it so fast.
