### ISSUE TITLE
Opening Cuda Files with Code Editor.

### ISSUE THREAD

**Issue by eduardo4jesus** [googlecolab/colabtools#2138]
**Is your feature request related to a problem? Please describe.**
*I'm always frustrated when* I try to open a file to edit it and the file gets downloaded. In particular, recently I've working with `.cu` files.

**Describe the solution you'd like**
The text-based files, such as source code, could simply open on the text editor. Hence, having the same behaviours such as for the `.c` and `.py` files. 
1. I wish to be able to open `.cu` files in the colab code editor;
2. If possible, allow users to configure which files they want to open in the code editor. Today is cuda files, tomorrow could be another extension. After all, the download option is always available on the `right-click menu`; or
3. Add the option to open with code editor to the `right-click menu`.

**Describe alternatives you've considered**
Currently, the work around is to save the file as `.c` in order to edit it. Then when I need to use it I rename it to `.cu`. This process is time consuming.

**Comment by blois** [comment]
This should be fixed now.

**Comment by eduardo4jesus** [comment]
Thank you so much!

**Comment by eduardo4jesus** [comment]
Hello @blois. 

How quickly would it be to add the syntax highlight for the `.cu` files?

**Comment by blois** [comment]
Looks like we should be able to just use the C syntax highlighting for that?

**Comment by blois** [comment]
Fix should arrive in a few days.

**Comment by eduardo4jesus** [comment]
Wow. Once again, thank you so much for the fast work.
