### ISSUE TITLE
Julia runtime is not recognised and defaults to python

### ISSUE THREAD

**Issue by pjgoodall** [googlecolab/colabtools#2139]
**Current behavior**
A colab template which installed and ran Julia code no-longer functions.

If I search for `Julia Colab` using google this is very highly ranked - so needs fixing some-way or another please. 

**Describe the expected behavior**
I had an expectation that the following notebook would execute: [Julia for Pythonistas](https://colab.research.google.com/github/ageron/julia_notebooks/blob/master/Julia_for_Pythonistas.ipynb)

**What web browser you are using**
Chrome

**Additional context**
[Julia for Pythonistas(https://colab.research.google.com/github/ageron/julia_notebooks/blob/master/Julia_for_Pythonistas.ipynb)
I have reported a bug against the notebook as well. [Unrecognized runtime "Julia"](https://github.com/ageron/julia_notebooks/issues/3#issue-946930997)

**Comment by craigcitro** [comment]
That notebook starts with a step to install Julia, which is required to make this work.
