### ISSUE TITLE
Blank Screen when opening ipynb through colab 

### ISSUE THREAD

**Issue by chain-veerender** [googlecolab/colabtools#214]
i tried to open 'first_steps_with_tensor_flow.ipynb' through colab. But, it is displaying blank screen which you can find in screen shot attached
![screenshot_error](https://user-images.githubusercontent.com/30558259/42799645-1ed3135e-8988-11e8-96e1-2423fc6b79d9.png)

**Comment by colaboratory-team** [comment]
Do you observe any errors in the Javascript console? (A common cause of this sort of issue is browser extensions interfering with the page.)

**Comment by veerenderreddy** [comment]
No...I was opening colab through Machine Learning Crash Course Exercises. I
didn't get any errors in console....

**Comment by colaboratory-team** [comment]
What browser and browser version are you using?
