### ISSUE TITLE
chmod -R 777 / executes

### ISSUE THREAD

**Issue by WilfredAlmeida** [googlecolab/colabtools#2140]
`chmod -R 777 /` executes when executed from cell.

I didn't let run completely and terminated the cell in 5 seconds as soon as I didn't get any error or any other output.

I don't know if it runs to the end but if it does, it can be problematic as it might break the OS

**Comment by craigcitro** [comment]
Colab VMs are ephemeral, so this sort of thing is quickly fixed with a factory reset.

**Comment by WilfredAlmeida** [comment]
As long as there aren't any bigger problems it doesn't matter, although I think is should be patched rather than doing a tedious factory reset.
