### ISSUE TITLE
Disconnects randomly without reaching usage limit or any other valid reason.

### ISSUE THREAD

**Issue by shubhamscifi** [googlecolab/colabtools#2141]
**Describe the current behavior**
Colab notebook disconnects randomly without any reason. (Neither my usage limit is reached nor my RAM has crashed and nor is the notebook inactive) and still it disconnects randomly many times. eg: I am training my model. It runs for one hour and then disconnects. Now I have to again reconnect do everything again from start. Wastes the whole effort and time.

**Describe the expected behavior**
The colab notebook should not disconnect until code is being written or being run and usage limit is not reached.

**What web browser you are using**
Chrome

**Comment by cperry-goog** [comment]
See #2032
