### ISSUE TITLE
Google Colab keeps logging me out when I try to create new notebook

### ISSUE THREAD

**Issue by ShavaRobert** [googlecolab/colabtools#2148]
When I try to create a new notebook in Colab, I get an error message " Your Google Account was signed out on a different tab. Sign in to continue". I get this error message although I am signed in. I try to sign in and keeps logging me out and I cannot then sign in again unless I delete cookies in Chrome

**Comment by cperry-goog** [comment]
Can you try to create a new notebook in incognito mode and see if it works?

**Comment by katlyn-edwards** [comment]
It appears you are using an account that is a Google Workspace, or Google Domain account. Drive is disabled for that domain - you should talk to your domain administrator to enable it: https://support.google.com/a/answer/6115117
