### ISSUE TITLE
1 week of work lost in Colab (bug)

### ISSUE THREAD

**Issue by Shughen** [googlecolab/colabtools#2149]
Hello,

I have the colab pro version.
I have lost my work in Colab and I don't know why.
In the version historic, nothing has been saved.
Moreover, I can see the file (from last week), and I can't save : 
![image](https://user-images.githubusercontent.com/75950671/126750857-3df9ba0f-b969-4185-950a-e4c1bf63ad5f.png)

Colab says to me that I can't save the file (probably because it considers that I am not the owner). 
However, I am the owner of the file :
![image](https://user-images.githubusercontent.com/75950671/126751105-1b715a81-ad40-4d30-b217-0780a4225612.png)

So do you know why I can't save this file if I am the owner ?
Can I retrieve somewhere my work ?!

Many thanks,
Rémi

**Comment by cperry-goog** [comment]
Thanks for reporting. We haven't seen this issue before, could you submit feedback in product when you encounter this issue, and mention this Github issue in your submission?
