### ISSUE TITLE
Import Files won't refresh

### ISSUE THREAD

**Issue by lakarbatti** [googlecolab/colabtools#215]
Once I have uploaded local files using `files.upload()`, if I change the content of the file and then reload, the updates to the file aren't getting reflected in the program. Still see the old file. Nothing worked including resetting the runtime or clearing the output. Finally, I went to Notebook settings, changed some options and then reran and this time saw the changes reflected. This is not good. The changes have to reflect immediately.

**Comment by colaboratory-team** [comment]
`files.upload` doesn't overwrite existing files by default, so you'll need to check for a new file containing a suffix that uniquifies it. Using the file browser on the left hand side may help.

![image](https://user-images.githubusercontent.com/38081706/55016863-d94a3880-4fac-11e9-8a50-e13489403988.png)
