### ISSUE TITLE
how to disable show code hyperlink below hidden code cells

### ISSUE THREAD

**Issue by mdhabeebvulla** [googlecolab/colabtools#2154]
how to disable show code hyperlink below hidden code cells in colab notebook

**Comment by corrieann** [comment]
Thanks for the question!  To ensure that the person viewing the notebook knows that there is hidden code and gets a chance to verify that they indeed are intending to run that code, we now unconditionally display the "Show code" button when a cell is in form view.  There is currently no way to disable it.
