### ISSUE TITLE
No active session but colab still complains "You have too many active sessions. Terminate an existing session to continue."

### ISSUE THREAD

**Issue by Abhishek-Prajapat** [googlecolab/colabtools#2159]
I was trying to train a model and I just did a factory reset of the kernel but now I just can't connect to any VM. Colab is complaining that I have too many active session but I don't have a single active session.

**What web browser you are using**
I was using FireFox when the issue occured. As of now I have also tried Chrome but the issue persists.

**[here](https://drive.google.com/file/d/1ybDwf9QS_2xbSatV1QaW6RdiWc1djG2c/view?usp=sharing) is a link of a screen recording showing what is happening**

**Note**: This is happening in TPU runtime and I am subscribed to colab pro.

**Comment by brunobastosg** [comment]
I have a similar problem. I was using two sessions simultaneously until yesterday.

Today, I can only start one session. If I try to start another session in another tab, it complains about "too many active sessions", even though there is only one session.

I'm also subscribed to Colab Pro.

**Comment by tuananh0305** [comment]
I have a similar problem. Please let me know if you solved this problem. Thank you so much!

**Comment by cperry-goog** [comment]
Thanks for reporting this. We're working on a fix, but for now you can work around by opening an incognito window and logging into Colab with a single account. Let us know if that doesn't work.
