### ISSUE TITLE
Colab Pro: "Too many active sessions" with only one session active

### ISSUE THREAD

**Issue by demiantill** [googlecolab/colabtools#2163]
I believe Colab Pro normally allows up to 3 active sessions. As of July 31st it is only allowing me to have one active session. If I try to run another notebook it tells me I have too many active sessions and that I need to terminate one to continue.

The browser I'm using is Google Chrome.

**Comment by josesydor** [comment]
Same problem here! I've always used two simultaneous sessions (tabs) for my work with no hiccups. Is there any chat/phone support for the Pro version of this product, anyway?

**Comment by king398** [comment]
Same problem. Can we actually get a good costumer service for colab Pro user ?

**Comment by PebriSinaga** [comment]
Got same problem here! I've always used three simultaneous sessions...

**Comment by atmaranto** [comment]
I usually use two sessions, but for the last week or so, I've been unable to use more than a single GPU session. I'm not sure if this is a bug or a change to the service, but it would be nice to know if it was one or the other.

**Comment by cawandmilk** [comment]
It seems to support multiple sessions when using a hardware accelerator as GPU, and changing Runtime Shape to **Standard** rather than **High-RAM**.

**Comment by king398** [comment]
@cawandmilk that worked for me. Thank you

**Comment by hyolee1999** [comment]
@king398  how long can you run on Standard ? Because when using High Ram , it lasts about 2 hours and terminates

**Comment by king398** [comment]
> @king398 how long can you run on Standard ? Because when using High Ram , it lasts about 2 hours and terminates

Mine is working from 4 hours rn and still did not terminate

**Comment by Kevin-Chen0** [comment]
Same problem here, and I'm using Google Pro. Before, I can do as many as 5 sessions but now can only do 1.

^ This is if I set the type to High-RAM. Once I set the Standard, however, I can do more than 1 session. Nevertheless, this had not been a problem for me before. I don't know why recently I'm getting this problem, however.

**Comment by radovleugel** [comment]
I was always able to run three simultaneous sessions. Since a couple of days this is down to two (I'm using Colab Pro)

**Comment by chenhao1umbc** [comment]
The same problem happened to me today...

**Comment by josesydor** [comment]
I believe that from Google's perspective it's not a bug, it's a new policy! The Colab Pro contract is vague enough to allow  this kind of throttling. I blame these goddamn bitc*nt miners!
Keep tweeting Elon, make them loose all their money! LOL

**Comment by atmaranto** [comment]
@josesydor You're probably correct, but it would be nice to have a semi-official confirmation to this change in policy, like "You can no longer run multiple simultaneous GPU sessions with High RAM."
That being said, Colab's usage _does_ change unpredictably, so it's possible this isn't even a policy change wrought by human hands.

**Comment by king398** [comment]
@josesydor doesn't colab have an algorithm to detect miners

**Comment by josesydor** [comment]
@king398 They certainly have ways to, but that'd imply a privacy issue, no? I mean, checking what every and which notebook is doing... Anyways, I guess I'm just venting my fury since it's because of them miners I cannot afford the GPUs I need, hence me here ranting...

**Comment by king398** [comment]
> @king398 They certainly have ways to, but that'd imply a privacy issue, no? I mean, checking what every and which notebook is doing... Anyways, I guess I'm just venting my fury since it's because of them miners I cannot afford the GPUs I need, hence me here ranting...

Personally I would sacrifice my privacy for those miners to get banned

**Comment by cperry-goog** [comment]
In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

I've seen some bugs for users not being able to get any active sessions, please do continue to highlight those.

**Comment by cperry-goog** [comment]
I should add: for users not getting any active sessions, you should be able to work around that for now by opening an incognito window and logging into Colab with a single user account. That may also address some of the other active sessions reports here, but hard to make a broad generalization.

**Comment by adhamStudy** [comment]
I have a very heavy task and I need to run 3 models at same time , any one have an idea can I run them on colab pro + or colab pro
