### ISSUE TITLE
breakpoint() causes cell to hang indefinitely

### ISSUE THREAD

**Issue by stbennet** [googlecolab/colabtools#2164]
**Describe the current behavior**
If I run a cell containing a line with `breakpoint()`, the cell will either ignore the breakpoint and never prompt me with the option to debug, or otherwise will hang indefinitely. Either behavior may be exhibited when I run the same cell.

**Describe the expected behavior**
When running a cell, upon reaching the line containing `breakpoint()`, the output will prompt me with debugging options akin to those of pdb.set_trace()

**What web browser you are using**
Firefox 90.0.2 64-bt

**Additional context**

[Minimal working example on google colab](https://colab.research.google.com/drive/1zQ1uhUZckBED9AloSVCpqlVBOpJ71Wpm?usp=sharing)

**Comment by cperry-goog** [comment]
Tracked internally at b/195687832

**Comment by craigcitro** [comment]
Thanks for the report! This is fixed (for a while now -- I forgot to update this issue 😕 ).
