### ISSUE TITLE
Update Python version to latest

### ISSUE THREAD

**Issue by orome** [googlecolab/colabtools#2165]
Currently it is impossible to use a Python version other than the one currently offered, making it impossible to share anything written for later versions of Python (e.g., currently 3.8 and 3.9).

It should be possible to select from several Python version, up through the latest stable release, at least; or to be able to install an arbitrary Python.

**Comment by jasonkhadka** [comment]
any update on this issue? Is there any plan/work going on to update to python 3.8 or 3.9?
This issue mentioned there were work going on for further updates from the one in Feb to Python 3.7?
https://github.com/googlecolab/colabtools/issues/1422

**Comment by craigcitro** [comment]
It's still on our radar; #1880 tracks an ubuntu update (which would bump python along the way).

**Comment by jasonkhadka** [comment]
Do you know what is the expected date for this update? Is it Dec 26 as mentioned in the comment in the other issue?

> It's still on our radar; #1880 tracks an ubuntu update (which would bump python along the way).

**Comment by craigcitro** [comment]
No, it won't be on Dec 26.

**Comment by jasonkhadka** [comment]
Is there any estimate for this? When can we roughly expect this?
> No, it won't be on Dec 26.

**Comment by craigcitro** [comment]
@jasonkhadka No specific date.

**Comment by KelSolaar** [comment]
Hello,

I was wondering if it would make sense to follow the Scientific Python SPEC-0000: https://scientific-python.org/specs/spec-0000/

Cheers,

Thomas

**Comment by EwoutH** [comment]
This issue is becoming really important, with many packages dropping Python 3.7 support, following the Numpy depreciation policy ([NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html)). Python 3.7 support was dropped on December 26th, 2021 for NumPy.

Aside from NumPy 1.22+, Pandas 1.4+ and NetworkX 2.7+ also only support Python 3.8+.

I would suggest adopting either Python 3.8 and 3.9 as soon as possible, to be able to use the latest versions of those packages.

**Comment by EwoutH** [comment]
@colaboratory-team @blois @craigcitro @yilei and @katlyn-edwards,

This issue becomes more and more pressing each week that passes. So much packages now require Python 3.8 support. It sucks being limited by the environment, it harms compatibility. Colab really needs an Python 3.8+ update, preferably directly to 3.9.

**Comment by craigcitro** [comment]
As noted above, this is on our radar. I don't have a specific date to offer, unfortunately.

**Comment by janosh** [comment]
> Python 3.11 is going to have some [improvements in error messages](https://docs.python.org/3.11/whatsnew/3.11.html#enhanced-error-locations-in-tracebacks) too.

[Not to mention it's noticeably faster](https://docs.python.org/3.11/whatsnew/3.11.html#summary-release-highlights)! 🎉

**Comment by EwoutH** [comment]
Another month has passed, without any update...

At this point maybe we should regard Colab as unmaintained.

**Comment by orome** [comment]
@EwoutH That's what I've assumed for some time now.

**Comment by janosh** [comment]
@orome Same. That's why I stopped using it.

Google pays their engineers several 100k a year because they're competent. And it doesn't take a competent engineer more than a week or two to update an OS, even on a large distributed system like Colab. Since nothing's happened for years, seems no one is working on Colab.

**Comment by hayk-skydio** [comment]
+1 for at least Python 3.8

**Comment by lisphilar** [comment]
Thank you for providing Google Colab.
Absolutely + 1 for using Python (3.8 or) 3.9+ as @orome and @EwoutH mentioned.

I'm developing a library which uses pandas and so on as dependencies. I think many users try the library with Google Colab because we can set up environment easily and quickly.

To use the latest versions of major packages, which dropped 3.7 support, my library will need to take away chances to be used on Google Colab.

**Comment by lisphilar** [comment]
I found that we can useOptuna version 3.0.0 with the followng settings.

- python = "^3.7.13,<3.11"
- optuna = "^3.0.0"
- scipy = "^1.7.3"

Dropping Python 3.7 will be discussed with #1146 later.

**Comment by lisphilar** [comment]
Does anyone know why it is difficult to update Python version...?

**Comment by EwoutH** [comment]
I just cancelled my Colab subscription. It doesn't provide enough value to me any more, almost fully due to the outdated Python version.

It's just sad.

**Comment by orome** [comment]
> I just cancelled my Colab subscription. 

Same here, long ago, for the same reason.

**Comment by lisphilar** [comment]
Hmm... I have to do the same...and I will replace "Open in Colab" with a new one in documentation, changing minimum Python support of my library.

**Comment by GianniGi** [comment]
Why does colab still feature python 3.7? Is it possible to update it, or any update must be "redone" after each time a notebook connects?

**Comment by liamdugan** [comment]
+1 to updating to at least 3.8. The latest version of fairseq now fails to build because it requires numpy 1.23.3 (and thus python 3.8). This is incredibly inconvenient for ML dev

**Comment by MrAshRhodes** [comment]
Guessing this will never be updated...
Even if there was just a way to manually update the version... just anything to get to a higher python version.

**Comment by lisphilar** [comment]
I suppose that and I changed Jupyter Notebook environment. I have no idea to help and encourage the maintainers so that they can update Python version.

**Comment by ilia3101** [comment]
This really needs attention. Important packages are dropping support for 3.7 now.

**Comment by RyuuOujiXS** [comment]
Pandas pickles in current versions are no longer compatible with the latest available Pandas for Python 3.7

**Comment by jakirkham** [comment]
What is the ETA for updating Python?

Several libraries have dropped Python 3.7 like NumPy ( https://github.com/numpy/numpy/pull/21558 ), Pandas ( https://github.com/pandas-dev/pandas/pull/41989 ), and other projects following [NEP 29]( https://numpy.org/neps/nep-0029-deprecation_policy.html ).

In conda-forge, we plan to drop Python 3.7 when adding Python 3.11 ( https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/2623 ), which is [coming out Monday]( https://peps.python.org/pep-0664/#schedule ).

**Comment by betaBison** [comment]
Can @colaboratory-team @craigcitro @cperry-goog please provide an update on Python/Ubuntu upgrades?

Last update regarding Python was 6 months ago from @craigcitro on Apr 24, 2022

> As noted above, this is on our radar. I don't have a specific date to offer, unfortunately.

And the last update on the related #1880 to upgrade Ubuntu was from @cperry-goog on Oct 14, 2021

> Thanks, no updates, this is on our radar.

**Comment by JoaoPaes-at-Dynamox** [comment]
Oh, come on. Google is one of the largest companies in the world, they are that child winning at Monopoly, so they started not caring about their users community.

They compiled the 3.7.15 version on 2022-10-12. About a month ago. This issue started more than a year ago.

What is the problem? Lack of money? Lack of skillful engineers to handle the problem?

...

**Comment by unnir** [comment]
Please update python to at least 3.9 :)

**Comment by leofang** [comment]
It seems the update to Python 3.8 is done recently: https://github.com/googlecolab/colabtools/issues/3246

**Comment by unnir** [comment]
how long will it take for 3.9 🙃

**Comment by PavelGorbanj** [comment]
Just in case, here it goes how I've installed 3.10. It survives Runtime restarts, but it's not persistent Runtime deletion

`#The code below installs 3.10 (assuming you now have 3.8) and restarts environment, so you can run your cells.

import sys #for version checker
import os #for restart routine

if '3.10' in sys.version:
  print('You already have 3.10, nothing to install')
else:
  #install python 3.10 and dev utils
  #you may not need all the dev libraries, but I haven't tested which aren't necessary.
  !sudo apt-get update -y
  !sudo apt-get install python3.10 python3.10-dev python3.10-distutils libpython3.10-dev 
  !sudo apt-get install python3.10-venv binfmt-support #recommended in install logs of the command above

  #change alternatives
  !sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
  !sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 2

  # install pip
  !curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
  !python3 get-pip.py --force-reinstall

  #install colab's dependencies
  !python3 -m pip install setuptools ipython ipython_genutils ipykernel jupyter_console prompt_toolkit httplib2 astor

  #minor cleanup
  !sudo apt autoremove

  #link to the old google package
  !ln -s /usr/local/lib/python3.8/dist-packages/google /usr/local/lib/python3.10/dist-packages/google
  #this is just to verify if 3.10 folder was indeed created
  !ls /usr/local/lib/python3.10/

  #restart environment so you don't have to do it manually
  os.kill(os.getpid(), 9)`

**Comment by metrizable** [comment]
Colab is now on Python 3.8 (#3246) with plans to upgrade to Python 3.9+ in the future!

**Comment by jakirkham** [comment]
Thanks Eric! 🙏 Christmas came early 🎁

**Comment by KelSolaar** [comment]
> Colab is now on Python 3.8 (#3246) with plans to upgrade to Python 3.9+ in the future!

This is great news, thank you!

**Comment by KelSolaar** [comment]
> Just in case, here it goes how I've installed 3.10. It survives Runtime restarts (but not the deletion). All the searchable "solutions" were either irrelevant or incomplete/outdated as of today (so mine may become like that later on))) so I've updated the one that was the closest. I haven't tested it heavily, but basic 3.10 items work.
> 
> ```
> #The code below installs 3.10 (assuming you now have 3.8) and restarts environment, so you can run your cells.
> 
> import sys #for version checker
> import os #for restart routine
> 
> if '3.10' in sys.version:
>   print('You already have 3.10, nothing to install')
> else:
>   #install python 3.10 and dev utils
>   #you may not need all the dev libraries, but I haven't tested which aren't necessary.
>   !sudo apt-get update -y
>   !sudo apt-get install python3.10 python3.10-dev python3.10-distutils libpython3.10-dev 
>   !sudo apt-get install python3.10-venv binfmt-support #recommended in install logs of the command above
> 
>   #change alternatives
>   !sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
>   !sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 2
> 
>   # install pip
>   !curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
>   !python3 get-pip.py --force-reinstall
> 
>   #install colab's dependencies
>   !python3 -m pip install setuptools ipython ipython_genutils ipykernel jupyter_console prompt_toolkit httplib2 astor
> 
>   #minor cleanup
>   !sudo apt autoremove
> 
>   #link to the old google package
>   !ln -s /usr/local/lib/python3.8/dist-packages/google /usr/local/lib/python3.10/dist-packages/google
>   #this is just to verify if 3.10 folder was indeed created
>   !ls /usr/local/lib/python3.10/
> 
>   #restart environment so you don't have to do it manually
>   os.kill(os.getpid(), 9)
> ```

@PavelGorbanj : This just stalls here for me:

```
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  libnvidia-common-460
0 upgraded, 0 newly installed, 1 to remove and 20 not upgraded.
After this operation, 35.8 kB disk space will be freed.
(Reading database ... 125030 files and directories currently installed.)
Removing libnvidia-common-460 (460.106.00-0ubuntu1) ...
```

**Comment by unnir** [comment]
just checked, have the same issue as @KelSolaar

**Comment by wenkesj** [comment]
This worked well enough for me:

```python
!sudo apt-get update -y
!sudo apt-get install python3.9 python3.9-dev python3.9-distutils libpython3.9-dev 
!sudo apt-get install python3.9-venv binfmt-support #recommended in install logs of the command above

#change alternatives
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2

# install pip
!curl -sS https://bootstrap.pypa.io/get-pip.py | python3.9
!python3 -m pip install jupyter psutil setuptools ipython==7.9.0 traitlets==5.7.1 ipython_genutils ipykernel jupyter_console prompt_toolkit httplib2 astor

# link to the old google package
!ln -s /usr/local/lib/python3.8/dist-packages/google \
       /usr/local/lib/python3.9/dist-packages/google

!rm -r ~/.jupyter
!jupyter serverextension list
!jupyter notebook --config=/usr/local/etc/jupyter/jupyter_notebook_config.json
```

Then restart the runtime.

**Comment by wenkesj** [comment]
This worked for me to install 3.9 on a 3.8 instance:

```python
!sudo apt-get update -y && sudo apt-get install python3.9 python3.9-dev python3.9-distutils libpython3.9-dev python3.9-venv

# Link python3 to 3.9.
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2

# Install pip.
!curl -sS https://bootstrap.pypa.io/get-pip.py | python3.9

# Install your dependencies. Pin IPython and traitlets versions, as traitlets version 5.8 contains a breaking change that prevents google-colab server extension from working properly.
!python3 -m pip install ipython==7.9.0 traitlets==5.7.1 jupyter psutil setuptools ipython_genutils ipykernel jupyter_console prompt_toolkit httplib2 astor

# Copy the already installed `google-colab` package over. It depends on an _old version_ of pandas, so building the wheel won't work.
!ln -s /usr/local/lib/python3.8/dist-packages/google \
       /usr/local/lib/python3.9/dist-packages/google

# Reinstall jupyter server extension.
!jupyter serverextension list
!jupyter notebook --config=/usr/local/etc/jupyter/jupyter_notebook_config.json
```

Restart your runtime, then run:

```python
import sys
print(sys.version)
```

It should output something like:
```bash
3.9.16 ...
```

**Comment by metrizable** [comment]
@orome Thanks for filing the request. We have upgraded Colab's runtime to Python 3.9 (#3450) with plans to upgrade to modern versions in the future.

**Comment by orome** [comment]
@metrizable Good to know. We're on 3.11 now so — will have to keep waiting.

**Comment by metrizable** [comment]
@orome  One more version closer :). We've upgraded Colab's runtime to Python 3.10 (https://github.com/googlecolab/colabtools/issues/3572) and we'll keep [cadence](https://devguide.python.org/versions/) with final regular bug fix releases with binary installers for Python versions (like [3.11](https://peps.python.org/pep-0664/#bugfix-releases)) in the future.
