### ISSUE TITLE
Clicking on "Switch to Prod" is resulting in Error

### ISSUE THREAD

**Issue by rmothukuru** [googlecolab/colabtools#2167]
**Describe the current behavior**
From the past 3-4 days, clicking on **`Switch to Prod`** link,

![image](https://user-images.githubusercontent.com/48206667/127808702-d22fde3e-92fc-49b5-a302-aa1a63a5cc9a.png)

is resulting in 404 Error. Screenshot of the error is shown below:

![image](https://user-images.githubusercontent.com/48206667/127808490-ba3b7d30-b396-4f66-9e1d-d8331f88dbd8.png)

Production Environment (clicking on "Switch to Prod")  is very important for us because we have to Save our **`Colab Notebooks`** as **`Github Gist`**.

**Describe the expected behavior**
There should be no error.

**What web browser you are using**
Chrome

**Additional context**
https://colab.research.google.com/no-dogfood/drive/10BUyAhorLP1mQjVyrh9wNPooScWdaItD?resourcekey=0-HUPqogpFp5hJpQJb_YL_Ig

**Comment by craigcitro** [comment]
Filed b/195311462, let's follow up there.
