### ISSUE TITLE
Pandas related output disappears immediately after running the cell

### ISSUE THREAD

**Issue by arashag** [googlecolab/colabtools#2168]
**Describe the current behavior**
I tried to run a cell which contain loading a csv file using pandas. When I run the cell, the output disappears suddenly, and I can see a blank output. If I right click on the blank space and click on "view output fullscreen", I can see the output in full screen 

**Describe the expected behavior**
I expect that I can see the output below the cell just it has always been.

**What web browser you are using**
Chrome

**Comment by craigcitro** [comment]
Can you share a minimal repro notebook as a gist?

**Comment by arashag** [comment]
I found that had a similar problem which he recorded a short video of the problem. Here is the link:
[https://gitmemory.com/issue/googlecolab/colabtools/1914/802959541](https://gitmemory.com/issue/googlecolab/colabtools/1914/802959541)

**Comment by blois** [comment]
Can you try in an incognito browser window?

**Comment by arashag** [comment]
I've just tried and It works correctly in incognito Chrome.

**Comment by craigcitro** [comment]
The gitmemory link has a comment suggesting the "Urban VPN" extension could have been causing trouble, which matches with things working in incognito. I'm going to close for now, but if it turns out to be a different extension for your case, that would also be interesting to know.
