### ISSUE TITLE
Bokeh push_notebook doesn't work (Comms issue)

### ISSUE THREAD

**Issue by bernspe** [googlecolab/colabtools#217]
At what stage will Colab support Comms? I am still struggling to get my bokeh plot updated, which works in Jupyter but not in Colab. It seems to be due to the fact, that Comms is still not supported. Any help possible?

**Comment by blois** [comment]
Can you provide an example notebook with how you are looking to use comms?

Colab does have some plumbing in place for comms but currently they are only used for widgets.

**Comment by bernspe** [comment]
[Copy of Bokeh_Test3.ipynb.zip](https://github.com/googlecolab/colabtools/files/3459900/Copy.of.Bokeh_Test3.ipynb.zip)

Thanks for answering. Please make sure to provide your own oanda key in this case, as it is confidential.
The bokeh graph is not updating, however - the pricing stream still provides data...

**Comment by bryevdv** [comment]
There are complete public example notebooks in the Bokeh repo:

https://github.com/bokeh/bokeh/tree/master/examples/howto/notebook_comms

**Comment by jakirkham** [comment]
Any updates on this? 🙂

**Comment by odadoun** [comment]
Yes any updates please ? interact seems not working inside Colab environnement ... can you confirm the issue ?
