### ISSUE TITLE
An option to suppress(hide) cell output while looking for version diff in  version history

### ISSUE THREAD

**Issue by wanburana** [googlecolab/colabtools#2172]
**Is your feature request related to a problem? Please describe.**
While there is a built in version history. The cell output is included which is not desirable in many cases. Sometimes I just want to see the *code* diff, not the output diff, this is especially annoying when experiment with ML hyperparameters when you want to track what you did in the last version. At the moment it's not possible to distinguish the diff from code and the diff from output.
![image](https://user-images.githubusercontent.com/66191669/128498952-c2e36d43-edcf-44e8-a869-7e8a0ee734d6.png)

**Describe the solution you'd like**
A toggle option to turn on and off the output of the notebook cell in the version history

**Comment by cperry-goog** [comment]
tracked internally at b/198165096

**Comment by corrieann** [comment]
Thanks!  There's now a checkbox to hide cell output

**Comment by wanburana** [comment]
> Thanks! There's now a checkbox to hide cell output

Amazing! Thank for the team's promptly work!
