### ISSUE TITLE
Questions about problems of ingest, numba only happened in colab platform

### ISSUE THREAD

**Issue by ChineseBest** [googlecolab/colabtools#2173]
For this code, I will face this error only in the colab platform:
![image](https://user-images.githubusercontent.com/43333475/128514807-b7fc04bc-5f35-489f-9d34-d5175e53bde6.png)

I have tried the method in this part.
https://github.com/lmcinnes/pynndescent/issues/133

**Comment by cperry-goog** [comment]
We suspect the problem lies in different versions of libraries you're interacting with; it'd be worth force installing the same versions you are using elsewhere.
