### ISSUE TITLE
ValueError: module functions cannot set METH_CLASS or METH_STATIC

### ISSUE THREAD

**Issue by susisam** [googlecolab/colabtools#2174]
**Describe the current behavior**
Trying to import:
from simpletransformers.classification import ClassificationModel, ClassificationArgs
I receive the following error:
ValueError: module functions cannot set METH_CLASS or METH_STATIC
**Describe the expected behavior**
It was working fine until yesterday.
**What web browser you are using**
Chrome
**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
You'd need to ask the library author.
