### ISSUE TITLE
almost 2 hours to fit 274 batchs (LSTM model, 10k rows dataset)

### ISSUE THREAD

**Issue by sylzys** [googlecolab/colabtools#2175]
**Describe the current behavior**
The time for my model to fit a small dataset is really slow, almost 2 hours

**Describe the expected behavior**
It is always way quicker to fit, it was like 1min on Colab free

**What web browser you are using**
Firefox 91.0 Windows

**Additional context**
LSTM model running on a base of 1min/epochs on Colab free

![Screenshot_7](https://user-images.githubusercontent.com/1545358/128609619-fcbae5a9-12ed-467f-99ea-9e47c703eb6c.png)

**Comment by cperry-goog** [comment]
We'd need a reproducible notebook to investigate

**Comment by sylzys** [comment]
I think it was quota, I used GPU a lot and I guess it was limited
