### ISSUE TITLE
isdirectory error caught

### ISSUE THREAD

**Issue by phil-fw60** [googlecolab/colabtools#2176]
After much formatting I finally got my private lsjspeech-pattern data to work. Mels were generated and my filelists seemed to work -though flagged up missing punctuation at end of texts.
When I start training it goes through 69 /69 steps of first iteration and writes some data to log files in MyFile and Colab - but then the process immediately crashes out with this error report.  Looks like something to do with file paths.

I was wondering why we have to add 'wavs/'xxxx.wav| text xxxxxxxxxxxxxxxx
To the filelist entries when the datapath is specified as 'wavs' - doesnt this make the 'wavs/' at the start of the entry redundant?

Confused here.

---------------------------------------------------------------------------

IsADirectoryError                         Traceback (most recent call last)

<ipython-input-40-e8a871a0e98d> in <module>()
      5 print('cuDNN Benchmark:', hparams.cudnn_benchmark)
      6 train(output_directory, log_directory, checkpoint_path,
----> 7       warm_start, n_gpus, rank, group_name, hparams, log_directory2)

5 frames

/usr/local/lib/python3.7/dist-packages/torch/_utils.py in reraise(self)
    423             # have message field
    424             raise self.exc_type(message=msg)
--> 425         raise self.exc_type(msg)
    426 
    427 

IsADirectoryError: Caught IsADirectoryError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/tacotron2/data_utils.py", line 61, in __getitem__
    return self.get_mel_text_pair(self.audiopaths_and_text[index])
  File "/content/tacotron2/data_utils.py", line 34, in get_mel_text_pair
    mel = self.get_mel(audiopath)
  File "/content/tacotron2/data_utils.py", line 49, in get_mel
    melspec = torch.from_numpy(np.load(filename))
  File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
IsADirectoryError: [Errno 21] Is a directory: 'wavs/'

**Comment by cperry-goog** [comment]
I'd try asking on Stackoverflow, this doesn't appear to be a Colab issue, sorry.
