### ISSUE TITLE
Can not load weight : "You are trying to load a weight file containing 189 layers into a model with 188 layers"

### ISSUE THREAD

**Issue by tuandv2021** [googlecolab/colabtools#2182]
I have tried load Inception v3 weights into model with this code :

from tensorflow.keras.applications.inception_v3 import InceptionV3
pre_trained_model = InceptionV3(
    input_shape=(150, 150, 3), include_top=False, weights=None)

local_weights_file = 'inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5'
pre_trained_model.load_weights(local_weights_file)

And its return:
ValueError: You are trying to load a weight file containing 189 layers into a model with 188 layers.

How can I fix this Issue?
Thanks!

**Comment by cperry-goog** [comment]
Try reporting this at https://github.com/tensorflow it doesn't appear Colab is the main cause.
