### ISSUE TITLE
Runtime getting disconnected in less than a minute

### ISSUE THREAD

**Issue by DayakarMalgari** [googlecolab/colabtools#2183]
I'm training a Neural Network model and while executing, it's getting disconnected sometime in less than a minute and sometimes in 5 minutes.

I'm getting below error message. 

Your runtime has been disconnected due to inactivity or reaching its maximum duration.
For longer running notebooks, consider upgrading to Colab Pro.
To connect to a new runtime, click the connect button below.

Thanks.

**Comment by Daviljoe193** [comment]
Similar situation, haven't used Colab in days, and yet just using it today, I'm getting the same issue after less than 40 minutes. Can't even use CPU only without the session getting terminated.

**Comment by cperry-goog** [comment]
see #2032
