### ISSUE TITLE
'_EagerConst' is neither a type of a primitive operation nor a name of a function registered in binary running on n-c128b5ca-w-0. Make sure the operation or function is registered in the binary running in this process. [Op:VarHandleOp] name: Variable/replica_1/

### ISSUE THREAD

**Issue by triper1022** [googlecolab/colabtools#2185]
**Describe the current behavior**
Yesterday I can run the same code on TPU, this issue didn't happen.
Besides, I can run the same code normally on CPU or GPU runtime.

**Describe the expected behavior**
Please tell me how to fix it. Thanks

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.

[notebook](https://colab.research.google.com/gist/triper1022/1147c993e2a50d97cfd625d0e644f628/hw4_with_tpu-keras.ipynb?hl=en)

**Comment by craigcitro** [comment]
TF is just cutting a new release, leading to many packages being updated. I suspect you're picking up a new version of [`tensorflow_io`](https://pypi.org/project/tensorflow-io/#history) that leads to the error; I'd try installing a specific version.
