### ISSUE TITLE
Access to root of machine filesystem

### ISSUE THREAD

**Issue by ptsypyshev** [googlecolab/colabtools#2186]
**Describe the current behavior**
I can get access to / folder of machine via internal filemanager. Is it a feature or misconfiguration?

**Describe the expected behavior**
I expect that an user should not have access to root of filesystem.

**What web browser you are using**
Opera v:77.0.4054.277

**Additional context**
[Screenshot](https://drive.google.com/file/d/1F2issXZhYW-3t_ep6l1zaXmIRo-BBdSW/view?usp=sharing)
machine-id is 1601c427d7c84dea8a09c9ef8e82a8e6

**Comment by craigcitro** [comment]
This is WAI.
