### ISSUE TITLE
Parallelism error with Ray

### ISSUE THREAD

**Issue by Thomas-M-H-Hope** [googlecolab/colabtools#2188]
Hello,

I saw some output that specifically asked me to inform you of the 'bug'. Here it is: I can't understand it!

(pid=28750) 2021-08-12 12:55:39.152181: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
(pid=28749) 2021-08-12 12:55:39.221103: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
(pid=28751) 2021-08-12 12:55:39.325041: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
(pid=28748) 2021-08-12 12:55:39.374474: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
(pid=28823) 2021-08-12 12:55:43.097926: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
(pid=28827) 2021-08-12 12:55:43.333143: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
(pid=28824) 2021-08-12 12:55:43.437021: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
(pid=28822) 2021-08-12 12:55:43.474860: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
(pid=28750) 2021-08-12 12:55:45.492610: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
(pid=28750) 2021-08-12 12:55:45.503396: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
(pid=28750) 2021-08-12 12:55:45.503534: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: 777d0b035ca2
(pid=28750) 2021-08-12 12:55:45.503565: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: 777d0b035ca2
(pid=28750) 2021-08-12 12:55:45.503703: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 460.32.3
(pid=28750) 2021-08-12 12:55:45.503751: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 460.32.3
(pid=28750) 2021-08-12 12:55:45.503772: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 460.32.3
(pid=28751) 2021-08-12 12:55:45.808591: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
(pid=28751) 2021-08-12 12:55:45.834912: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
(pid=28751) 2021-08-12 12:55:45.834989: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: 777d0b035ca2
(pid=28751) 2021-08-12 12:55:45.835018: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: 777d0b035ca2
(pid=28751) 2021-08-12 12:55:45.835218: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 460.32.3
(pid=28751) 2021-08-12 12:55:45.835288: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 460.32.3
(pid=28751) 2021-08-12 12:55:45.835312: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 460.32.3
(pid=28749) 2021-08-12 12:55:46.139381: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
(pid=28749) 2021-08-12 12:55:46.168550: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
(pid=28749) 2021-08-12 12:55:46.168698: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: 777d0b035ca2
(pid=28749) 2021-08-12 12:55:46.168737: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: 777d0b035ca2
(pid=28749) 2021-08-12 12:55:46.168980: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 460.32.3
(pid=28749) 2021-08-12 12:55:46.169081: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 460.32.3
(pid=28749) 2021-08-12 12:55:46.169107: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 460.32.3
(pid=28748) 2021-08-12 12:55:46.460048: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
(pid=28748) 2021-08-12 12:55:46.468837: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
(pid=28748) 2021-08-12 12:55:46.468925: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: 777d0b035ca2
(pid=28748) 2021-08-12 12:55:46.468953: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: 777d0b035ca2
(pid=28748) 2021-08-12 12:55:46.469131: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 460.32.3
(pid=28748) 2021-08-12 12:55:46.469190: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 460.32.3
(pid=28748) 2021-08-12 12:55:46.469218: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 460.32.3
(pid=28751) 2021-08-12 12:56:33.500564: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
(pid=28751) 2021-08-12 12:56:33.506235: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2299995000 Hz
(pid=28748) 2021-08-12 12:56:33.974303: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
(pid=28748) 2021-08-12 12:56:33.974960: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2299995000 Hz
(pid=28751) WARNING:tensorflow:AutoGraph could not transform <function cc at 0x7f80efb69440> and will run it as-is.
(pid=28751) Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
(pid=28751) Cause: Unable to locate the source code of <function cc at 0x7f80efb69440>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
(pid=28751) To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
(pid=28749) 2021-08-12 12:56:34.657733: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
(pid=28749) 2021-08-12 12:56:34.658991: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2299995000 Hz
(pid=28748) WARNING:tensorflow:AutoGraph could not transform <function cc at 0x7f6504ee9440> and will run it as-is.
(pid=28748) Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
(pid=28748) Cause: Unable to locate the source code of <function cc at 0x7f6504ee9440>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
(pid=28748) To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
(pid=28750) 2021-08-12 12:56:35.004568: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
(pid=28750) 2021-08-12 12:56:35.005381: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2299995000 Hz
(pid=28749) WARNING:tensorflow:AutoGraph could not transform <function cc at 0x7fbcf9729440> and will run it as-is.
(pid=28749) Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
(pid=28749) Cause: Unable to locate the source code of <function cc at 0x7fbcf9729440>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
(pid=28749) To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
(pid=28751) tcmalloc: large alloc 1073741824 bytes == 0x55e0bc31e000 @  0x7f8121633b6b 0x7f8121653379 0x7f7e92ac8e97 0x7f7e81a1c6ef 0x7f7e81aad28b 0x7f7e818dc2e7 0x7f7e818dc96f 0x7f7e818dcb28 0x7f7e8c4421fb 0x7f7e81be4723 0x7f7e8709d441 0x7f7e8709a133 0x7f7e8231cd75 0x7f81214066db 0x7f812053b71f
(pid=28750) WARNING:tensorflow:AutoGraph could not transform <function cc at 0x7fd8531294d0> and will run it as-is.
(pid=28750) Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
(pid=28750) Cause: Unable to locate the source code of <function cc at 0x7fd8531294d0>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
(pid=28750) To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
(pid=28748) tcmalloc: large alloc 1073741824 bytes == 0x560005aea000 @  0x7f6536993b6b 0x7f65369b3379 0x7f62a7e48e97 0x7f6296d9c6ef 0x7f6296e2d28b 0x7f6296c5c2e7 0x7f6296c5c96f 0x7f6296c5cb28 0x7f62a17c21fb 0x7f6296f64723 0x7f629c41d441 0x7f629c41a133 0x7f629769cd75 0x7f65367666db 0x7f653589b71f
(pid=28749) tcmalloc: large alloc 1073741824 bytes == 0x5632cc91e000 @  0x7fbd2b1dfb6b 0x7fbd2b1ff379 0x7fba9c688e97 0x7fba8b5dc6ef 0x7fba8b66d28b 0x7fba8b49c2e7 0x7fba8b49c96f 0x7fba8b49cb28 0x7fba960021fb 0x7fba8b7a4723 0x7fba90c5d441 0x7fba90c5a133 0x7fba8bedcd75 0x7fbd2afb26db 0x7fbd2a0e771f
(pid=28750) tcmalloc: large alloc 1073741824 bytes == 0x555e2ea44000 @  0x7fd884bd4b6b 0x7fd884bf4379 0x7fd5f6088e97 0x7fd5e4fdc6ef 0x7fd5e506d28b 0x7fd5e4e9c2e7 0x7fd5e4e9c96f 0x7fd5e4e9cb28 0x7fd5efa021fb 0x7fd5e51a4723 0x7fd5ea65d441 0x7fd5ea65a133 0x7fd5e58dcd75 0x7fd8849a76db 0x7fd883adc71f
(pid=28751) tcmalloc: large alloc 2416443392 bytes == 0x55e1ac31e000 @  0x7f81216511e7 0x7f7e8855ffd5 0x7f7e88f52d45 0x7f7e8c09934a 0x7f7e8c3e9334 0x7f7e8c4398d0 0x7f7e8c43abf7 0x7f7e8c43bbe9 0x7f7e8c43d31e 0x7f7e8c441df2 0x7f7e8c4422ef 0x7f7e81be4723 0x7f7e8709d441 0x7f7e8709a133 0x7f7e8231cd75 0x7f81214066db 0x7f812053b71f
(pid=28748) tcmalloc: large alloc 2416443392 bytes == 0x5600f5aea000 @  0x7f65369b11e7 0x7f629d8dffd5 0x7f629e2d2d45 0x7f62a141934a 0x7f62a1769334 0x7f62a17b98d0 0x7f62a17babf7 0x7f62a17bbbe9 0x7f62a17bd31e 0x7f62a17c1df2 0x7f62a17c22ef 0x7f6296f64723 0x7f629c41d441 0x7f629c41a133 0x7f629769cd75 0x7f65367666db 0x7f653589b71f
(pid=28749) tcmalloc: large alloc 2416443392 bytes == 0x5633bc91e000 @  0x7fbd2b1fd1e7 0x7fba9211ffd5 0x7fba92b12d45 0x7fba95c5934a 0x7fba95fa9334 0x7fba95ff98d0 0x7fba95ffabf7 0x7fba95ffbbe9 0x7fba95ffd31e 0x7fba96001df2 0x7fba960022ef 0x7fba8b7a4723 0x7fba90c5d441 0x7fba90c5a133 0x7fba8bedcd75 0x7fbd2afb26db 0x7fbd2a0e771f
(pid=28750) tcmalloc: large alloc 2416443392 bytes == 0x555f1ea44000 @  0x7fd884bf21e7 0x7fd5ebb1ffd5 0x7fd5ec512d45 0x7fd5ef65934a 0x7fd5ef9a9334 0x7fd5ef9f98d0 0x7fd5ef9fabf7 0x7fd5ef9fbbe9 0x7fd5ef9fd31e 0x7fd5efa01df2 0x7fd5efa022ef 0x7fd5e51a4723 0x7fd5ea65d441 0x7fd5ea65a133 0x7fd5e58dcd75 0x7fd8849a76db 0x7fd883adc71f
2021-08-12 12:56:52,292	WARNING worker.py:1779 -- A worker died or was killed while executing task 7c3ddc20ab82ffffffff01000000.
(pid=28824) 2021-08-12 12:56:52.845696: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
(pid=28824) 2021-08-12 12:56:52.907893: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
(pid=28824) 2021-08-12 12:56:52.908015: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: 777d0b035ca2
(pid=28824) 2021-08-12 12:56:52.908045: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: 777d0b035ca2
(pid=28824) 2021-08-12 12:56:52.910606: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 460.32.3
(pid=28824) 2021-08-12 12:56:52.910741: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 460.32.3
(pid=28824) 2021-08-12 12:56:52.910782: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 460.32.3
---------------------------------------------------------------------------
RayWorkerError                            Traceback (most recent call last)
<ipython-input-15-9288cbcde8b3> in <module>()
      1 ray.init(ignore_reinit_error=True)
----> 2 [preds_baseline,preds_dl,preds_dl_multi] = run_cv_with_baseline_par(old_style,x_train2,x_train1,y_train)
      3 

1 frames
/usr/local/lib/python3.7/dist-packages/ray/worker.py in get(object_ids)
   2347                 if isinstance(value, ray.exceptions.UnreconstructableError):
   2348                     worker.dump_object_store_memory_usage()
-> 2349                 raise value
   2350 
   2351         # Run post processors.

RayWorkerError: The worker died unexpectedly while executing this task

**Comment by cperry-goog** [comment]
I'd report this upstream to tensorflow at https://github.com/tensorflow
