### ISSUE TITLE
Error in search against genetic databases

### ISSUE THREAD

**Issue by mtopolska** [googlecolab/colabtools#2189]
error code: 

NotFoundError                             Traceback (most recent call last)

<ipython-input-4-1640ae7ce3a3> in <module>()
     24 import py3Dmol
     25 
---> 26 from alphafold.model import model
     27 from alphafold.model import config
     28 from alphafold.model import data

6 frames

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/load_library.py in load_library(library_location)
    152 
    153     for lib in kernel_libraries:
--> 154       py_tf.TF_LoadLibrary(lib)
    155 
    156   else:

NotFoundError: /opt/conda/lib/python3.7/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl12lts_2021032411string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS9_EE

**Comment by cperry-goog** [comment]
We suspect this is a module load order bug, you could try restarting the process and trying again. You should report this upstream to https://github.com/deepmind/alphafold They'll be more equipped to troubleshoot.
