### ISSUE TITLE
Could not fetch branches

### ISSUE THREAD

**Issue by jonbaer** [googlecolab/colabtools#219]
When opening a notebook via a GitHub search some public repos will report "Could not fetch branches" even though they do publicly exist.

**Comment by craigcitro** [comment]
Do you have any repro steps? In particular, does this consistently happen for certain repos?

(One might say I'm interested in repro repos. 😁 )

**Comment by jonbaer** [comment]
Sorry, https://github.com/jvns/pandas-cookbook

<img width="837" alt="screen shot 2018-07-24 at 6 57 37 pm" src="https://user-images.githubusercontent.com/13155/43170621-05399ec6-8f74-11e8-9117-7735fc301c63.png">

**Comment by craigcitro** [comment]
I can't seem to repro -- that repo loads fine for me.

Are there any errors in the Chrome JS console?

**Comment by jonbaer** [comment]
<img width="1098" alt="screen shot 2018-07-25 at 12 42 55 pm" src="https://user-images.githubusercontent.com/13155/43215027-07297efa-9009-11e8-87fa-cde9bd098dcc.png">

**Comment by colaboratory-team** [comment]
b/133228440

**Comment by marcNY** [comment]
I am getting the same error, has this been solved?
![image](https://user-images.githubusercontent.com/8562443/78424072-49cd7000-766b-11ea-9338-b73a33c85c17.png)

**Comment by darkhorse1998** [comment]
> I am getting the same error, has this been solved?
> ![image](https://user-images.githubusercontent.com/8562443/78424072-49cd7000-766b-11ea-9338-b73a33c85c17.png)

I think if you initialize your repo as public and with a README, it should work fine. It did in my case. I didn't have any commit or a README file in my repo that I made. After I created a readme file, the problem was solved.

**Comment by araghav1** [comment]
Still facing same issue
![image](https://user-images.githubusercontent.com/28639672/80309090-a0c4f180-87a0-11ea-86da-d538c28ad3b5.png)

**Comment by araghav1** [comment]
Workdaround solution above my post works perfect for me: I think if you initialize your repo as public and with a README, it should work fine. It did in my case. I didn't have any commit or a README file in my repo that I made. After I created a readme file, the problem was solved.

**Comment by JonathanNdambaPro** [comment]
Hi I've resolved this type of issues, you have to create any types of file on your folder github, for my self i've created .gitkeep without any line and commit, with this your git going to create a branch (master) and normaly this will work.

Best.

**Comment by arsalanyaghoobi** [comment]
I faced the same trouble;you can come along with this ,very easily ,by creating a Read Me file for your Repository;thus changing your Branch into a Master.
the best

**Comment by tiachoptinhdu** [comment]
I deal with problem when copy a file to git from colab.google. In my case just add README file and we can save that copy to github

**Comment by cicada-code** [comment]
In my case, adding a README file solves the problem.

**Comment by cperry-goog** [comment]
tracking internally at b/198164710

**Comment by cperry-goog** [comment]
This has been fixed, please re-open if you encounter issues again. Thank all.
