### ISSUE TITLE
Colab Crashed when loading a pickle file

### ISSUE THREAD

**Issue by niyuzheno1** [googlecolab/colabtools#2191]
**Describe the current behavior**

The current behavior is that when I tried to run the cell on google colab then it immediately crash for no reason. The same problem did not happen in Kaggle.

**Describe the expected behavior**

I want the pickle file to be loaded without crashing. 

**What web browser you are using**
Chrome

**Additional context**

https://colab.research.google.com/gist/niyuzheno1/e20452beb3b98cefc089be032072178c/lgbmmodel0.ipynb

The pickle file "LGBMmodel0.bin" is widely available, specially it is located under this kaggle dataset:
[lgdm](https://www.kaggle.com/chumajin/lgbm02104)

**Comment by craigcitro** [comment]
Isn't `train.pkl` (https://www.kaggle.com/chumajin/lgbm02104?select=train.pkl) the pickle file?

**Comment by niyuzheno1** [comment]
No, it is LGBMmodel0.bin.
