### ISSUE TITLE
Cannot plot any images or show any bug details in output item

### ISSUE THREAD

**Issue by Yuebing-zhou** [googlecolab/colabtools#2194]
**Describe the current behavior**
<img width="1205" alt="截屏2021-08-17 上午6 06 01" src="https://user-images.githubusercontent.com/76542963/129666677-b7a71539-37a2-4289-9077-d52bcc74e28c.png">
Hello, as the above picture shows, I cannot plot any images and even if I have some mistake on code, the output item still did not show anythings 

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
It should plot some images
**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome
**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
could you share a minimal notebook that reproduces this so we can test?

you also might try executing in an incognito window.
