### ISSUE TITLE
Function range doesn't work as it should

### ISSUE THREAD

**Issue by sergioomoya** [googlecolab/colabtools#2195]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

The range function doesn't work properly (works differrent in Colab than in other IDE).

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

Usually, if we use the range function like this: range(1,5)
We get: 1, 2, 3, 4, 5
But in colab we get: 1, 2, 3, 4

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

I executed this function in Chrome and OperaGX

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
I don't know how to use github very well, it is just: print(range(1,5))
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by craigcitro** [comment]
Colab's got the right behavior here -- `list(range(1, 5))` returns `[1, 2, 3, 4]` -- see the docs: https://docs.python.org/3/library/stdtypes.html#typesseq-range
