### ISSUE TITLE
.py files deleted after re-opening notebook

### ISSUE THREAD

**Issue by samuela** [googlecolab/colabtools#2197]
**Describe the current behavior**
I wrote a bunch of .py files and saved them to the colab file system in /content. After saving, closing, and re-opening the notebook all of my files have disappeared. I just lost a week's worth of work. How do I recover these files?

**Describe the expected behavior**
The saving functionality to actually save.

**What web browser you are using**
Firefox 91.0.1

**Additional context**
https://colab.research.google.com/drive/1-NTypnd4htt5pqk_RDjcrGtWTvKDSS-e?usp=sharing

**Comment by cperry-goog** [comment]
You'll want to write files to Drive in order to have persistent storage. The VMs Colab provides are ephemeral, and are recycled after each usage, and no data is recoverable on the VM after a session. I think we have some warnings on this, but we should do a better job of flagging, sorry.

**Comment by samuela** [comment]
Yeah, this is quite confusing for the end-user, esp. considering you provide a nice code editor experience within the UI. I didn't see any warnings along the way. Working with script files felt like it was a "blessed" mode of using the tool.

**Comment by cperry-goog** [comment]
Yup, you're right it's confusing. Tracking extra warnings internally at b/197257377
