### ISSUE TITLE
Shift + Tab doesn't do docstring lookup

### ISSUE THREAD

**Issue by ajinkyakolhe112** [googlecolab/colabtools#22]
To see docstring lookup, need to execute with ? instead of easier Shift + Tab as it can be done in Jupyter

**Comment by craigcitro** [comment]
In colab, shift+tab does outdent.

We support tab completion, too, in two ways:

* if you're in a parenthesis or between arguments (eg after a comma), tab will show you the docstring -- so if you are typing something like `print('hello', sep='')`, then tab after the paren or between the comma and the next arg will show you the docstring.

* alt+/ will always show (or hide) the docstring.

I'm going to close, but do reopen if either of those aren't working for you at all!

**Comment by ajinkyakolhe112** [comment]
Shouldn't shortcut to access the docstring be uniform?

**Comment by AlcoholV** [comment]
> In colab, shift+tab does outdent.
> 
> We support tab completion, too, in two ways:
> 
> * if you're in a parenthesis or between arguments (eg after a comma), tab will show you the docstring -- so if you are typing something like `print('hello', sep='')`, then tab after the paren or between the comma and the next arg will show you the docstring.
> * alt+/ will always show (or hide) the docstring.
> 
> I'm going to close, but do reopen if either of those aren't working for you at all!

alt+/ isn't working.

**Comment by blois** [comment]
We're in the process of rolling out a new engine for the code editor, details can be found at https://colab.research.google.com/notebooks/editor_details.ipynb.

In this editor ctrl-shift-space can be used to show the docstring.

Additionally in preferences you can disable automatic completions which will behave more like the previous editor- tab will complete, tab after an open paren will open the docstring. In addition shift-tab will open the docstring, similar to Jupyter Lab.

**Comment by MauroCE** [comment]
2020 and:

- alt + / doesn't work for me
- shift + tab doesn't work for me

**Comment by Emprors** [comment]
Same for me
2020 and:

alt + / doesn't work for me
shift + tab doesn't work for me

**Comment by blois** [comment]
Shift-tab will only work if the 'automatic completions' option is set to 'off' in the settings.

**Comment by Programmer1-1** [comment]
How do I show the docstring? I am used to using shit+tab in jupyter notebooks. I tried turning off "Automatically trigger code completions" in Settings and shift+tab still doesn't work.

**Comment by blois** [comment]
ctrl-shift-space is the default for opening the parameter hints, if you are within the brackets of a method invocation.

**Comment by Programmer1-1** [comment]
It would be good to make it work consistently with Jupyter Notebooks. I don't know how this github thing works, but maybe this can be added to a future update.

**Comment by vibhuk16** [comment]
> ctrl-shift-space is the default for opening the parameter hints, if you are within the brackets of a method invocation.

This doesn't work. Could you please verify this again?

**Comment by sunnyyadav13** [comment]
use ctrl+shift+space it works

**Comment by DigNeurosurgeon** [comment]
trying on ipad pro... none of the options mentioned seem to work

**Comment by RinRoya** [comment]
Use Ctrl+Shift+Space
Ex: use Ctrl+Shift+Space after "e" in `np.linspace`

**Comment by divyanx** [comment]
> trying on iPad pro... none of the options mentioned seem to work

use command instead of control, if you are using a windows keyboard use the windows button instead of control, probably should work

**Comment by herdward** [comment]
none of these work

**Comment by sascharo** [comment]
> Use Ctrl+Shift+Space Ex: use Ctrl+Shift+Space after "e" in `np.linspace`

Works, though it's slow compared to a locally running IDE.
