### ISSUE TITLE
[discuss]ModuleNotFoundError: No module named 'termios'

### ISSUE THREAD

**Issue by KishaniKandasamy** [googlecolab/colabtools#2200]
Hi,  I try to connect  google.colab using the command  _from google.colab import drive_ and 
I get this error message.
Can anyone please help me to resolve this?
I have already installed the package using conda _install -c conda-forge google-colab_

![x](https://user-images.githubusercontent.com/53715187/129948789-d7064355-3d43-4fdc-86e0-ab0d3350cc2b.jpg)

**OS: Windows 10**

**Comment by craigcitro** [comment]
The google-colab package isn't supported for local use.
