### ISSUE TITLE
Progressive web app for Google Colab

### ISSUE THREAD

**Issue by StarlightScribe** [googlecolab/colabtools#2204]
**Is your feature request related to a problem? Please describe.**
The current Chrome Web Store app hasn't been updated in two years, and Chrome Apps will be completely discontinued next year. Right now they are only available for ChromeOS. 

**Describe the solution you'd like**
I hope that Google is planning to transition the Chrome App to a progressive web app. This will allow for integration with the ChromeOS system and other operating systems. 

**Describe alternatives you've considered**
An alternative solution would be a standalone app, or a native Android app. This would limit the compatibility across different operating systems. Here is Google's own guidance for transitioning:

https://developer.chrome.com/docs/apps/migration/

**Comment by jhilto** [comment]
Yes, that is one benefit, but it should be possible to add more offline functionality with an installable web app.
