### ISSUE TITLE
Typing in Markdown

### ISSUE THREAD

**Issue by ASaboorSyed25** [googlecolab/colabtools#2211]
**Describe the current behavior**
When I try to edit a markdown box, each character of the markdown code is written on individual lines making it unreadable and impossible to see what you are typing as you are typing it. For example "Hello" would be written as 
H
e
l
l
o
The text still runs fine and is formatted correctly in the output, but it is impossible to read you input if its longer than 2-3 words

**Describe the expected behavior**
Each line of text should wrap once it hits the middle divider, not at each character

**What web browser you are using**
Issue is present on Chrome and Safari

**Comment by blois** [comment]
This sounds like the editor is wrapping the text to 0 width. Does it continue to happen after you resize the browser window?

**Comment by ASaboorSyed25** [comment]
Resizing the window didn't change it. Though, I did figure out how to fix it. For whatever reason the divider column was set to -1. I fixed it by pressing the settings icon in the markdown box -> Editor -> Vertical Ruler Column and I set it to 100. Thank you four your help though!
