### ISSUE TITLE
Slow Mo error 

### ISSUE THREAD

**Issue by akos111** [googlecolab/colabtools#2217]
getting this here when i play with  "Making Slowmo: RIFE_Simplified(youtube).ipynb"   :

NameError                                 Traceback (most recent call last)
<ipython-input-1-3ceae8f68c51> in <module>()
     72 get_ipython().system("ffmpeg   -i myoutput_slow.mp4   -i myvideo_slow.mp4   -filter_complex '[0:v]pad=iw*2:ih[int];[int][1:v]overlay=W/2:0[vid]'   -map [vid]   -c:v libx264   -crf 23   -preset veryfast   -y myoutput_4_display.mp4")
     73 clear_output()
---> 74 show_local_mp4_video('myoutput_4_display.mp4', width=900, height=253, slowmoFactor = 1)
     75 
     76 

NameError: name 'show_local_mp4_video' is not defined

What can be done to fix this ?

Thanks ;)

**Comment by cperry-goog** [comment]
You'd need to contact the author of the notebook, it's not immediately clear.
