### ISSUE TITLE
Cannot run more than one standard instance even as a pro+ user

### ISSUE THREAD

**Issue by mlzxy** [googlecolab/colabtools#2221]
**Describe the current behavior**: Whenever I create a second standard GPU instance, it tells me I have too many sessions. 

**Describe the expected behavior**: Able to run two concurrent standard GPU instances

**What web browser you are using**: Chrome

I have read that the resource is distributed dynamically for colab to better handle the scalable workload, but is this the expected behavior? I subscribe for the pro+ mostly for a stable set of two connections. 

Thanks for your help.

**Comment by mlzxy** [comment]
Now the only instance disconnects and I cannot connect to any. Really sad because I only run it for five hours. And the executing without browser features is also not working properly. 

It happens many times that my program almost finishes the training and is ready to upload checkpoints to google drive, it just resets everything.

**Comment by cperry-goog** [comment]
Consolidating to #2232
