### ISSUE TITLE
Tensorflow 1.12 cannot installed on google colab

### ISSUE THREAD

**Issue by bushra-tayyaba** [googlecolab/colabtools#2223]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I want to install TensorFlow 1.12 on google colab. I always say the 1.12 version does not exist. Secondly, Colab only offers one version of python but I think that is not a problem. the main problem is different versions of TensorFlow provide different functionalities and that are not included in latest versions available on colab.  

**Describe the solution you'd like**
Users should be able to install any version of their required packages. 

**Describe alternatives you've considered**
in my case, I did not find any alternative for TensorFlow 1.12 on colab

**Additional context**
The output  for (!pip install tensorflow-gpu==1.12.0) is always as follows:
 ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.12.0 (from versions: 1.13.1, 1.13.2, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0rc0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0) ERROR: No matching distribution found for tensorflow-gpu==1.12.0

**Comment by craigcitro** [comment]
tensorflow-gpu 1.12 is far enough back that it didn't support Python 3.7, which Colab currently uses.
