### ISSUE TITLE
bug report in 2. Node Classification.ipyb  googlecolab file

### ISSUE THREAD

**Issue by SuleymanSuleymanzade** [googlecolab/colabtools#2224]
In the second google collab file please change the next lines (in the second code part, where graph parameters are printed)
 
`data.has_self_loops() `  **to**  `data.contains_self_loops()`
`data.has_isolated_nodes() ` **to** ` data.contains_isolated_nodes()`

Thank you.

**Comment by craigcitro** [comment]
I'd try reporting this to whoever owns the notebook you're referring to.
