### ISSUE TITLE
Cant do factory reset and gets t4 on pro+

### ISSUE THREAD

**Issue by Uemuet** [googlecolab/colabtools#2225]
hi my colab pro+ account under the mail umutbildiz@gmail.com has issues, 

I cant use Factory Runtime, the extra window doesnt appear and i only get the T4 on colab Pro+.

Can someone help me?

**Comment by PuckWong** [comment]
This has happend to me. Can't change Runtime.

**Comment by mmoghadam11** [comment]
> This has happend to me. Can't change Runtime.

what happend to t4 it doesnt giv me too

**Comment by Uemuet** [comment]
still cant do the factory reset at the normal way...and gets always a t4

**Comment by stas-sl** [comment]
Same here, this is really frustrating. Also unable to get High Memory instances anymore - it just gives only 12 GB of RAM and 2 CPU cores.

**Comment by cperry-goog** [comment]
Consolidating to #2232
