### ISSUE TITLE
always Backend, Low Memory for Collab Pro and Pro Plus

### ISSUE THREAD

**Issue by CoinFreakz** [googlecolab/colabtools#2227]
hi my colab pro and Pro + account 

I can t use Factory Runtime, the extra window doesnt appear and i only get the T4 on colab Pro and Pro +

Can someone help me?

and everytime im reconnect always get backend WHAT THE FUK FOR Pro ACCOUNT?

**Comment by cperry-goog** [comment]
Consolidating to #2232
