### ISSUE TITLE
Unable to get full ram allocation (51 gb) when connected to GPU. No problem when not connected to GPU.

### ISSUE THREAD

**Issue by daripp** [googlecolab/colabtools#2228]
I am only allocated ~12 gb of ram when connected to a gpu even when I select a high ram run time shape. When I am not connected to a gpu, I have no problem getting ~51 gb of ram. I am a colab pro plus subscriber, any help would be greatly appreciated. 
![image](https://user-images.githubusercontent.com/60364676/132281475-be72f454-6e33-4e69-8831-3eed762b1b85.png)
![image](https://user-images.githubusercontent.com/60364676/132281343-1bc806d3-04c9-4fbd-bfe8-ec021c1221b0.png)

**Comment by stas-sl** [comment]
> Hi,
 
> In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. GPU runtimes are prioritized by subscription tier, with Pro+ receiving highest priority, then Pro. During periods of heavy usage, we may not be able to allocate our most powerful GPUs to all subscribers. You can read more about Pro allocations here[1].
 
> [1] https://colab.sandbox.google.com/notebooks/pro.ipynb#scrollTo=QMMqmdiYMkvi
 
> Thanks, Colab Pro Customer Support

**Comment by daripp** [comment]
Weird, that response has nothing to do with the complaint.

**Comment by stas-sl** [comment]
Looks like they don't even bother to understand the issue and respond with the same boilerplate text to anyone complaining about insufficient resources, no matter if you are on Pro/Pro+ or Free. Though definitely this is wrong behavior, because even on plain Pro plan I had more RAM and CPUs which I used for months and never had this issue.

**Comment by cperry-goog** [comment]
Consolidating to #2232

**Comment by Alifalisda** [comment]
hallo guys, my google collab is actually using GPU RAM 0.6 /40, do you have answer for the happening?
