### ISSUE TITLE
Challenge feature request:  Auto-complete for Python and Tensorflow or some libraries

### ISSUE THREAD

**Issue by XinyueZ** [googlecolab/colabtools#223]
While developing with codes it is easy to improve productivity when the auto-complete feature has been plugged.

**Comment by metrizable** [comment]
@XinyueZ Thanks for filing the request. Auto-complete functionality is supported in Colab (for example, by pressing Ctrl+Space after a dot:

![Screenshot 2023-08-31 16 51 54](https://github.com/googlecolab/colabtools/assets/65414824/6bcf3a3e-b834-4977-897c-01a4a474546d)
).

**Comment by XinyueZ** [comment]
why dont you guys integrate Bard or GPT-4 ? @metrizable
