### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by nw96** [googlecolab/colabtools#2235]
when i submit my sequence to ColabFold: AlphaFold2 w/ MMseqs2, i came across an error at step : Gather input features, predict structure. it tells ma that my run was stopped due to out of memory. I had already upgraded to colab pro, but the problem didn't go away.

**Comment by cperry-goog** [comment]
Could you give a pointer to the notebook you were looking at?

**Comment by George0793** [comment]
@cperry-goog why finish GPU  backend in 2 hour for colab pro?
