### ISSUE TITLE
Only one active session with Pro+ (GPU and TPU both unavailable runtimes for multiple sessions)

### ISSUE THREAD

**Issue by hazid1** [googlecolab/colabtools#2236]
**Describe the current behavior**
Only one active session with GPU and high-RAM usage possible. despite my recent upgrade to Google Colab Pro+
Neither GPU nor TPU runtime is available for multiple session

**Describe the expected behavior**
Multiple active sessions possible with High-RAM usage and GPU or TPU runtime.

**What web browser you are using**
Chrome

**Comment by DKB0512** [comment]
Either Colab is having a major bug issue or they are just being greedy here. Many people bought Pro and Pro+ package but they are still either getting K80s or no GPUs at all. And many people are still getting that same "Your limit reached" error despite using colab on pro+ for few hours. The worst is for those who are using Free accounts (Students like us) who are now only getting K80s and can't get our work done using those old GPUs.

**Comment by soulspark666** [comment]
@DKB0512 here I was thinking that I am getting only K80s for every session I tried. Do we have any news regarding this anywhere?

**Comment by cperry-goog** [comment]
Consolidating to #2232
