### ISSUE TITLE
Bokeh not working

### ISSUE THREAD

**Issue by ahuang11** [googlecolab/colabtools#224]
Chrome
bokeh==0.13.0

A simple bokeh plot isn't showing; seems like bokehJS is missing on Google Colaboratory

```
from bokeh.io import output_notebook, show
from bokeh.plotting import figure
output_notebook()

# create a new plot with default tools, using figure# creat 
p = figure(plot_width=400, plot_height=400)

# add a circle renderer with a size, color, and alpha
p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=15, line_color="navy", fill_color="orange", fill_alpha=0.5)

show(p) # show the results
```

https://github.com/bokeh/bokeh/issues/8116

**Comment by blois** [comment]
This should be working, example:
https://colab.research.google.com/gist/blois/cee3062d91274f63cceddbe507011219/bokeh.ipynb

From the errors displayed in https://github.com/bokeh/bokeh/issues/8116 it looks like there may be something else blocking the network requests.

What Chrome version?
Perhaps try an incognito browser window?

**Comment by ahuang11** [comment]
Okay, I disabled my popup blocker and adblocker and worked.

My next question is if HoloViews is supported?

```
!pip install holoviews
import holoviews as hv
hv.extension('bokeh')
hv.Curve([1, 2, 3])
```

**Comment by blois** [comment]
An example of HoloViews:
https://colab.research.google.com/gist/blois/3eff3af6da6406baf84edd0c9ed962cd/holoviews.ipynb

Need to call bokeh.output_notebook() in the cell which is displaying the holoviews output.
