### ISSUE TITLE
Colab Pro + limit issue

### ISSUE THREAD

**Issue by ehzawad** [googlecolab/colabtools#2242]
**Can't able to use it for two days straight**
I don't think I have crossed the limits. In fact, I have colab pro subscription in my another google account, and it is working just fine, and get access more memory than Colab Pro +

**It should have given access to faster ram**
I'm only getting 12 GB ram

**What web browser you are using**
Chrome

![image](https://user-images.githubusercontent.com/12381692/133229606-8a976d2f-5896-4511-9e5c-20a022d84c99.png)

**Comment by stas-sl** [comment]
Welcome to the club, a week + 2 days here 😕

**Comment by rajat-tech-002** [comment]
Same here. Why even Colab Pro+ Users are not getting GPUs even after 5-6 days of non-usage. 
![Screenshot from 2021-09-14 22-48-46](https://user-images.githubusercontent.com/46721220/133304231-87affd89-986c-4b02-bdaa-681305993260.png)
https://github.com/googlecolab/colabtools/issues/2244

**Comment by akshaybankapure** [comment]
Same here @google @colaboratory-team @colab-team

**Comment by akshaybankapure** [comment]
<img width="768" alt="Screenshot 2021-09-15 at 10 10 19 pm" src="https://user-images.githubusercontent.com/17162733/133510255-ad76894c-143c-4fb6-8327-fc6b6814d6a4.png">
I am getting this  error even though I am on Pro+, even with high-RAM setting in the runtime-type @colaboratory-team  please address this sooner. I have my project demonstration tomorrow.

**Comment by cperry-goog** [comment]
Consolidating to #2232

**Comment by renatodigiorgio** [comment]
same here =(
