### ISSUE TITLE
Pro Plus Pro+ RAM not available

### ISSUE THREAD

**Issue by akshaybankapure** [googlecolab/colabtools#2245]
**For some reason I am not able to access full RAM, restricted to only 13GB RAM!(12.69GB) and even though I have tried all the types Runtime but not able to fix this problem by any means.** 
I have tried high-RAM, Standard, none, GPU, TPU everything I have tried but all of them are showing me only 12.69GB of RAM.

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by akshaybankapure** [comment]
<img width="768" alt="Screenshot 2021-09-15 at 10 10 19 pm" src="https://user-images.githubusercontent.com/17162733/133510880-d162e720-d397-4cb2-b625-36566aeeb973.png">

**Comment by akshaybankapure** [comment]
@colaboratory-team

**Comment by cperry-goog** [comment]
Consolidating to #2232

**Comment by material-math-UIdaho** [comment]
> Consolidating to #2232

I have the same issue. With pro plus but only 12.69G ram available. and I don't think this should be consolidated to #2232
