### ISSUE TITLE
Even without using Colab pro+ account for few days usage limit error.

### ISSUE THREAD

**Issue by hrishikeshps94** [googlecolab/colabtools#2246]
Even without using **colab pro plus** account for **5 or 6 days**. Everytime when I try to **connect to a GPU** the error below appears.

''Cannot connect to GPU backend
You cannot currently connect to a GPU due to usage limits in Colab. Learn more
As a Colab Pro+ subscriber, you have higher usage limits than both non-subscribers and Colab Pro users, but availability is not unlimited. To get the most out of Colab Pro+, avoid using GPUs when they are not necessary for your work."

**Comment by rinabuoy** [comment]
It has been more than a week for me.

**Comment by cperry-goog** [comment]
Consolidating to #2232
