### ISSUE TITLE
Unable to open colab notebook-stuck on loading

### ISSUE THREAD

**Issue by shivani21998** [googlecolab/colabtools#2251]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
While trying to open any colab notebook from chrome browser it does not load. Gives a blank page with message "Loading"
I have attached the error from console. I don't face with same issue on edge browser and the notebook loads without any issue. 

On chrome, I face the same issue while creating a new notebook and I have tried with incognito as well but the notebooks don't load. 

**What web browser you are using**
Chrome
![Capture](https://user-images.githubusercontent.com/29472727/133737380-1837cbba-116c-4fd0-9f1f-2db6f16ead67.JPG)
![Capture2](https://user-images.githubusercontent.com/29472727/133737387-2ae1da16-ed37-40a5-934d-1ec2ef42843a.jpg)

**Comment by mrtechnoo** [comment]
Same issue with me as well but some of my friends in different area can open it @colaboratory-team

**Comment by raghav-menon** [comment]
Facing the same issue. My notebook is not loading. I have a Pro account

**Comment by kupmurugib** [comment]
Facing same issue since this morning.

**Comment by mrtechnoo** [comment]
I do have the Pro version of colab @colaboratory-team

**Comment by colaboratory-team** [comment]
Thanks for the report. This is tracked internally at b/200267435.

To help us diagnose: when reproducing in an incognito window, does this issue persist with all extensions disabled? Does this error reproduce in other browsers, e.g., Firefox/Safari?

**Comment by kupmurugib** [comment]
Yes, it did! I did disabled all extensions and tried out. Also, with
different browsers.

Thanks
Kuppuraj M

**Comment by blois** [comment]
Are you using Windows? and if so, is there a particular OS language you are using?

**Comment by saru-d2** [comment]
I'm experiencing the issue on mac

**Comment by Sreerag-ibtl** [comment]
Having the same issue with Ubuntu 16.04. Tried incognito as well.

**Comment by kupmurugib** [comment]
Yes Windows

**Comment by colaboratory-team** [comment]
The root cause for this is likely similar to https://github.com/googlecolab/colabtools/issues/2250. We're working on mitigations now. We'll post further updates on https://github.com/googlecolab/colabtools/issues/2250.

**Comment by Daoguang-Polimi** [comment]
@colaboratory-team Hello, I still can't load the Colab notebook successfully on Chrome. But I can load the notebook on another brower.

**Comment by Daoguang-Polimi** [comment]
I suggest you update your chrome. But I can't remember the solution clearly.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by shazia1971** [comment]
Thanks

**Comment by shazia1971** [comment]
chrome updated

still colab not opening any python notebook

**Comment by Daoguang-Polimi** [comment]
Do you restart your computer?

**Comment by Maria2244** [comment]
i have this issue please some one help me

**Comment by Maria2244** [comment]
i have same problem please some guide me.@colaboratory-team

**Comment by Maria2244** [comment]
please some one help me i tried with all my account but is same

**Comment by shahrzad-setayesh** [comment]
Hi 
should 
1.uninstall chrom 
2.then install chrom 
3.connect with vpn Colab

**Comment by abbakark2** [comment]
I had a similar issue. What I did was delete all the browsing data from the date I started using Google Colab. I don't know why, but this actually worked. I hope this helps.

**Comment by RezuwanHassan262** [comment]
@colaboratory-team I am currently facing the same issue for both firefox and chrome!

**Comment by hassaanhameed786** [comment]
@colaboratory-team I am currently facing the same issue on safri

**Comment by ShahidulHaqueShaheeen** [comment]
I am facing the same problem. what should i do to solve this problem? Please help

**Comment by alien054** [comment]
I am facing the same problem on my mac.
