### ISSUE TITLE
US 49.99$ for nothing ( can NOT use pro+)

### ISSUE THREAD

**Issue by js-lan** [googlecolab/colabtools#2252]
paid at 2021.09.11
![1](https://user-images.githubusercontent.com/15121274/133744901-a33b32fa-6f7c-4b71-8d25-5ed421b1a8d1.png)

but still can not use pro+
![2](https://user-images.githubusercontent.com/15121274/133744916-671b1406-a084-430c-b6c5-81f99a9b43e2.png)

email  ：  xumeilan.scut@gmail.com
BILL ID：  COLSUB.0215-6274-8764-12157.14

**Comment by sebbov** [comment]
Email colab-billing@google.com for billing questions.
