### ISSUE TITLE
Inconsistent Output in Google Colab

### ISSUE THREAD

**Issue by inancarin** [googlecolab/colabtools#226]
I have the following basic code in Google Colab:

```
from random import *
number = randint(1, 100)

guess = int(input("Enter a guess: "))

while guess != number:
  if guess > number:
    print("Enter a smaller value")
  else:
    print("Enter a greater value")
  guess = int(input("Enter a guess: "))

print("You guessed the number")
```
This loop continues until we guess the number correctly. And after each guess, program directs us for the next guess (like enter smaller/greater number).

Sometimes, I get some inconsistency in the outputs. After I enter a wrong number as input, it should direct me with an output.

![2018-08-02_00-13-49](https://user-images.githubusercontent.com/19675020/43551047-3ad0b59e-95ee-11e8-9e23-574648bf5823.png)

After I enter 40 as input, it does not show me the output as shown above. But after I enter the next input (42), it fixes the output screen and shows the missing output as below.

![2018-08-02_00-14-42](https://user-images.githubusercontent.com/19675020/43551060-4a472fc6-95ee-11e8-9690-148e81c74b84.png)

What might be the problem? It is happening all the time.

**Comment by colaboratory-team** [comment]
Thanks for reporting the issue!

This could be due to out-of-order message delivery where the input request is received before the output from the previous print() statement. We'll look into a fix on our end.

**Comment by inancarin** [comment]
Thanks, I am looking forward to hearing good news from you soon.

**Comment by eikonomega** [comment]
@colaboratory-team Any update on this?

**Comment by colaboratory-team** [comment]
The underlying issue is https://github.com/jupyter/notebook/issues/3159.

An immediate work-around is to combine the feedback with the prompt, e.g.,

```
from random import *
number = randint(1, 100)
guess = int(input("Enter a guess: "))

while guess != number:
  if guess > number:
    prompt = 'Enter a smaller value\n'
  else:
    prompt = 'Enter a greater value\n'
  guess = int(input(prompt + "Enter a guess: "))

print ("You guessed the number")
```
