### ISSUE TITLE
Page becomes unresposive after opening a notebook 

### ISSUE THREAD

**Issue by sireesha-vakada** [googlecolab/colabtools#2261]
**Describe the current behavior**
After opening the notebook and I try to connect, the status changes from "Connect" to "Allocating", and the page becomes unresponsive. When I try to refresh the page, the page becomes blank

**Describe the expected behavior**
The page to become responsive and function normally

**What web browser you are using**
Chrome

**Comment by blois** [comment]
Does the issue continue in an incognito window? Does it occur for all notebooks or just a specific notebook?
