### ISSUE TITLE
Students unable to access Colab in Google Workspace for Education

### ISSUE THREAD

**Issue by seantibor** [googlecolab/colabtools#2264]
**Describe the current behavior**
Approximately 50% of our students are receiving an error stating that they do not have access to the service. This occurs when they attempt to open any Google Colab file in their Drive account. They do not experience this issue when opening a colab file in a non-Education Google Account (i.e. an @gmail.com).

<img width="1431" alt="Screen Shot 2021-09-19 at 2 40 57 PM" src="https://user-images.githubusercontent.com/40579452/134033717-ec5e11b9-f94d-4c9d-a6dc-ba21328a2ca8.png">

At the individual and organizational unit level we have confirmed that the users have access to Google Colab. Per issue https://github.com/googlecolab/colabtools/issues/1065, we have also verified that "Access to additional services without individual control" is turned ON for all students.

**Describe the expected behavior**
Student should be able to open the notebook and perform normal actions, e.g. run in playground, save a copy, etc.

**What web browser you are using**
Chrome on Mac OS Big Sur.

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
https://colab.research.google.com/drive/17BJkwnwD-OKttdSvrpUmxJNoaDDaRn7B?usp=sharing

**Comment by juusoFIN** [comment]
Same problem, approx. 10 - 20% of students get the same message. Last year Google Colab worked perfectly with all students. Now the rest of the students need to use repl.it.

**Comment by battis** [comment]
Also running into this at our school. New 9th graders can't get in, but older students can.

**Comment by deaconw** [comment]
I'm betting this is related to Google's new Under-18 policy.  They specifically state that "Services without On or Off controls" will be unavailable to "users in primary and secondary institutions who administrators indicate as under 18".
https://support.google.com/a/answer/10651918?hl=en#zippy=%2Cservices-not-available-to-users-under

**Comment by deaconw** [comment]
> Possibly, though Colab shows up as an On/Off service in our Google Admin console. It could be that some of the permissions logic is buggy even with that status.

That's interesting.  We're having the same issue here, and I can't find Google Colab under the list of "Additional Google Apps" to be able to manage it directly.  I'm looking at Google Admin Console > Apps > Additional Google Apps.  I do see Google Colab available as a Google Workspace Marketplace App, but installing the app domain-wide also seems to not grant permission to students (OUs containing users marked as Under-18).

**Comment by battis** [comment]
> I'm betting this is related to Google's new Under-18 policy. They specifically state that "Services without On or Off controls" will be unavailable to "users in primary and secondary institutions who administrators indicate as under 18".
> https://support.google.com/a/answer/10651918?hl=en#zippy=%2Cservices-not-available-to-users-under

That seems to be the case. Our system admin writes:

> I contacted google tech support about the Colab issue. They are aware of the issue and currently investigating. Google Colab is a service that does not have an On or Off control using Google Workspace for Education and might be affected by the Age-based access settings for under 18. They asked me to create a temporary workaround (I created a new Organizational Unit and marked them as over 18 and moved xxx@yyy.tld and zzz@yyy.tld.) and see if it fixed the issue. I emailed the students and copied Seth and Mike. Our case remains open and google will keep us posted.

**Comment by pbeeken** [comment]
We are having much the same problem although it is intermittent. Not all students are affected. Our administrator is following up with Google. Looking at the above post I can kind of see why those services are not relevant to Workspace for Education but why CoLab is suddenly excluded is not at all clear.

**Comment by bfsjmoore** [comment]
Same argghhh! About 10% of students in the same class.

**Comment by michael714** [comment]
I'm having the same problem with students in my high school Statistics classes.   Most are able to access Google Colab, but 5 to 10 in each class are unable to access Google Colab.   One student tried to access Google Colab via her personal gmail account and came up with the same "administrator" error message- but she was using a district issued Chromebook at the time.

**Comment by michael714** [comment]
> Same problem, approx. 10 - 20% of students get the same message. Last year Google Colab worked perfectly with all students. Now the rest of the students need to use repl.it.

In my district, we can no longer use repl.it because the site can serve as a proxy and so our internet filter is blocking it.  :(

**Comment by michael714** [comment]
I submitted a Google Colab feedback to Google today about this.  Hopefully, all of you have as well.   You just go to the help menu and then Send Feedback.

**Comment by cperry-goog** [comment]
Hey folks, thanks for reporting. I'm checking in on the Under-18 policy and seeing how that impacts. I will state that Colab does not currently support Child accounts (under 13).

**Comment by michael714** [comment]
> Hey folks, thanks for reporting. I'm checking in on the Under-18 policy and seeing how that impacts. I will state that Colab does not currently support Child accounts (under 13).

Technically, that shouldn't be an issue for most high school students.  Certainly, my Statistics students are all juniors and seniors (16 to 18 years in age).   Most students graduate high school by age 17 or 18, so that should put only a small percentage of high school students at an age under 13.    Aside from that, the age 13 seems an arbitrary limit for access to Colab.  I get the fact that this could be used to throttle processor and memory usage, but we live in an age where students are building and programming robots when they're in elementary school.  Do we really think that their won't be any kids under 13 trying their hand at data science?

**Comment by mrspacepotato** [comment]
I began the school year with only two or three students affected of my 100+.  The numbers keep going up though, and I can't stall any longer.

I was teaching Python and basic data science to sixth grade students that only use chromebooks, but I've since had write a whole new curriculum overnight due to this issue.  I can't reasonably continue working on coding with students when ~10% of my students cannot access Colab.  It is not realistic to try and get people on board with setting up a jupyter notebook server on the school network right now either.

**Comment by michael714** [comment]
I was told by another teacher in my district that we can use CodingRooms.com.   As a Statistics teacher, I'm mainly interested in Python and R- which CodingRooms supports, but they also support Javascript and other languages.   CodingRooms.com is a bit pricey for the premium account, but I'm going to try to use the free account so students at least have a place to try to write code.   I really wish that Google would help fix this problem so we can just use Colab.

**Comment by battis** [comment]
> > Hey folks, thanks for reporting. I'm checking in on the Under-18 policy and seeing how that impacts. I will state that Colab does not currently support Child accounts (under 13).
> 
> Technically, that shouldn't be an issue for most high school students. Certainly, my Statistics students are all juniors and seniors (16 to 18 years in age). Most students graduate high school by age 17 or 18, so that should put only a small percentage of high school students at an age under 13. Aside from that, the age 13 seems an arbitrary limit for access to Colab. I get the fact that this could be used to throttle processor and memory usage, but we live in an age where students are building and programming robots when they're in elementary school. Do we really think that there won't be any kids under 13 trying their hand at data science?

Age 13 is about COPPA and data collection on minors — and not wanting to get involved in all the approvals from guardians and whatnot. [Under 18 is a bit more of a political move.](https://techcrunch.com/2021/08/10/google-to-introduce-increased-protections-for-minors-on-its-platform-including-search-youtube-and-more/)

**Comment by michael714** [comment]
> > > Hey folks, thanks for reporting. I'm checking in on the Under-18 policy and seeing how that impacts. I will state that Colab does not currently support Child accounts (under 13).
> > 
> > 
> > Technically, that shouldn't be an issue for most high school students. Certainly, my Statistics students are all juniors and seniors (16 to 18 years in age). Most students graduate high school by age 17 or 18, so that should put only a small percentage of high school students at an age under 13. Aside from that, the age 13 seems an arbitrary limit for access to Colab. I get the fact that this could be used to throttle processor and memory usage, but we live in an age where students are building and programming robots when they're in elementary school. Do we really think that there won't be any kids under 13 trying their hand at data science?
> 
> Age 13 is about COPPA and data collection on minors — and not wanting to get involved in all the approvals from guardians and whatnot. [Under 18 is a bit more of a political move.](https://techcrunch.com/2021/08/10/google-to-introduce-increased-protections-for-minors-on-its-platform-including-search-youtube-and-more/)

Of course it's difficult to please everyone and that is understandable.  However, I think it would be nice to let high school students explore data science with Google Colab.   As for protecting kids from themselves, the road to hell is paved with good intentions...

**Comment by pbeeken** [comment]
For me it's AP/C physics.  I teach all seniors who are aiming at phys. sci. and eng. majors.  It seems to me it's a no brainer to make a tool like Jupyter available to them.  My exit surveys last year revealed that my students really liked using this tool for homework and lab write-ups.

I could go on but I am pleasantly surprised at how many HS have adopted this tool.  I hope it's just a matter of short time before this gets fixed.

**Comment by nambarn** [comment]
i got this problem too.
yesterday it's worked fine but now it's doesn't work anymore

**Comment by mdsnkm** [comment]
Same here. The issue arose today out and affected all new to Google Colab students.

**Comment by ekawamoto1** [comment]
I started seeing this issue last evening (Wed 09/24) with (high school) students running Colab Notebooks using the Java runtime. I thought it might have something to do with document ownership transferring between student and teacher when the notebook was submitted through Google Classroom, but one student had experienced this problem without submitting his notebook. This morning, the same problem occurred with other students whose Colab Notebooks use the native Python runtime. I myself have not (yet) experienced this access issue, except when I tried to open the notebooks that were submitted through Google Classroom, which students could not unsubmit or open in order to see comments I left on their code. Last night, I had also found that "fresh" notebooks (links to notebooks on my own Google Drive, of which students could make their own copies) would run the Python and Java runtimes.

**Comment by danbrady143** [comment]
Same issue...hoping it is resolved soon

**Comment by sdoro** [comment]
Mee too ... hoping it is resolved soon

**Comment by ProChore** [comment]
idem for us.
waiting for a solution

**Comment by ProChore** [comment]
I just got a response from Google: use of the service is limited to users over 18 !!

**Comment by pbeeken** [comment]
Yes, that is the current status. But the question is why? And why isn't it in the list of selectable apps in the Enterprise control panel like the others?  The implication of this situation implies CoLab's current status isn't because of a conscious choice to exclude but a default action because nobody thought about it.

The rules changed from "we allow any web app by default unless explicitly forbidden" to "we forbid any web app by default unless explicitly allowed." Fair enough, what is that decision tree and how does it get changed?  

Currently my students are using their personal accounts which sidesteps district management which I have permission to allow.  What makes CoLab different than Google Sheets with it's collaborative messaging?

**Comment by battis** [comment]
> > I'm betting this is related to Google's new Under-18 policy. They specifically state that "Services without On or Off controls" will be unavailable to "users in primary and secondary institutions who administrators indicate as under 18".
> > https://support.google.com/a/answer/10651918?hl=en#zippy=%2Cservices-not-available-to-users-under
> 
> That seems to be the case. Our system admin writes:
> 
> > I contacted google tech support about the Colab issue. They are aware of the issue and currently investigating. Google Colab is a service that does not have an On or Off control using Google Workspace for Education and might be affected by the Age-based access settings for under 18. They asked me to create a temporary workaround (I created a new Organizational Unit and marked them as over 18 and moved [xxx@yyy.tld](mailto:xxx@yyy.tld) and [zzz@yyy.tld](mailto:zzz@yyy.tld).) and see if it fixed the issue. I emailed the students and copied Seth and Mike. Our case remains open and google will keep us posted.

Our local Google admin reports that he's been notified by Google that there _will_ be an on/off option for Colab coming to the Google Admin panel. However, he also says that he was not promised a specific timeline for this.

**Comment by cperry-goog** [comment]
Hi folks, I know this is frustrating, and I'm super sorry for the access issues with Colab.

We were impacted by the recent change which prohibits access for Education users under 18 to services without an on/off control in Workspace: https://support.google.com/a/answer/10651918?hl=en

We are working to improve access to Colab for Education users in the long run, though I cannot give solid timelines at this time, I am prioritizing this work. For the time being, note that the access policy does not apply to accounts not administered by institutions. As a workaround to allow students to access notebooks, you could also consider using one of our related products, Kaggle Notebooks: https://www.kaggle.com/code

Kaggle does not have the same access restrictions as Colab, but do please note any age restrictions in their terms of service: https://www.kaggle.com/terms

Again, my apologies to the many teachers and students who rely on Colab. It may be helpful if you were to mention your desire to access Colab and how it helps your institution to your organization's contacts at Google for Education.

**Comment by deaconw** [comment]
Thank you for your communication and your work on this issue.  I look forward to our students being able to use this amazing educational tool again!

**Comment by michael714** [comment]
It's not realistic for us to have our district Google contacts advocate for
Colab.   That's like us asking you to ask your VP to advocate for some
issue you care about.   Everybody has their own agenda.  Colab is only
important to those of us on the front line.   Why isn't it sufficient for
us, educators, to send feedback via Colab to let you know we want access to
this for our students?

**Comment by awchisholm** [comment]
Colab is a great resource for teaching and we have created a lot of resources that make use of it. It will be time consuming to move to a different delivery method and the end result is likely to be less compelling. Kaggle is a possibility but I could not find a way to enable Internet access or linking to Google Drive.

**Comment by pbeeken** [comment]
One can even load jupyter notebook on local machines which is what we were doing before CoLab came along. We were just starting to investigate deploying a jupyter server in the cloud. Today all of our lesson plans, lab writeups and instructional material is developed and deployed using CoLab.  It would take an inordinate amount of time to convert.  I look forward to being able to turn access back on.

**Comment by michael714** [comment]
In my district, we do not have the option of loading software onto
machines.  Also, our school is mostly Chromebooks.   Colab should work for
high school students.

**Comment by pmimranek** [comment]
My suggestion is to go to the workspace community board and submit a feature request to add it to the Admin console.  It is a path to move things in the Google system.  Since this age thing started, they have quickly moved several things into the admin console based on the feedback.  There is already a post regarding the issue, so all you need to do is up vote the post and leave a comment.  I have already done this to work it from this angle.  Here is a link to the current post:

https://www.googlecloudcommunity.com/gc/Feature-Ideas/Enable-Colab-Research-Google-com-for-individual-enablement/idi-p/171439

All the pontificating about the whys and whos is irrelevant.  Advocating for the platform is exactly what you should do if you want to use it.  We have all made good use of it to this point and lending your voice to help continue the use does not seem like a tough ask.  At this point the only other option is to designate some student accounts as over 18, but I don't think any Workspace admin in K12 is making that leap without understanding the consequences.

**Comment by cperry-goog** [comment]
Hi folks, I have another update here. We've started rolling out visibility of the Workspace Control to enable or disable Colab for an entire Workspace organization. This is a staged rollout across all organizations over the coming days, so you may not see that today, but will very soon. More information on this control is here: https://support.google.com/a/answer/11254550

A Workspace admin for your organization MUST enable that control in order to preserve access to Colab for all users regardless of age. In the coming weeks we will begin to restrict access to all users in organizations who have not enabled that control.

It is critical you enable that control because Colab will be default off for all users in Workspace for Education organizations.

At the time we begin enforcing access based on the Workspace control (I will update this thread), all users in an organization that has enabled Colab will be able to access Colab. At that time the <18 access issues will be resolved. Until we begin enforcement, <18 users are still expected to not have access, regardless of the control setting.

I appreciate the complexity of this message, but I wanted to flag this early for you all to ease your transition. Please do comment if the content isn't clear, and I'll reply as I am able.

**Comment by SF65** [comment]
> 

Since a few days, most users see the warning below when entering Colab (they still can work  as usual) . 

**"Ask your admin to enable Colab for your education account
All Google Workspace for Education accounts will soon be denied access to Colab unless the administrator enables Colab."**

Colab is already enabled for everyone in Google Workspace Marketplace apps - Apps list (it does not figure in Additional Google services as stated in https://support.google.com/a/answer/11254550).

Anything we should do or is it just a cosmetic message ?

**Comment by pbeeken** [comment]
It is not cosmetic. My students still do not have access as of 11:27am EST.  It is my understanding that the administration console is a different beast and needs to be activated by the assigned, in-school, admin. Our admin, when they asked Google, were also told to 'toggle' the switch a few times (I think that means 'save' and refresh the screen) to make sure the request stuck.

**Comment by SF65** [comment]
I do confirm, it is not cosmetic ! 
We just lose access a few minutes ago

Now, we have this message : 

_"What is happening?
Access to Colab is changing for Google Workspace for Education accounts. Starting Nov 29, Google will begin rolling out an individual ON/OFF control to enable administrators to manage access to Colab. As this new control becomes available to administrators over several days, users may lose access to Colab during this time. When the control is available, service administrators can enable Colab access. Learn more about turning on or off Google Colab."_

**Comment by cperry-goog** [comment]
Enforcement will begin soon, and visibility of the control will gradually roll out over the next few days, barring any issues. I expect many users to lose access while they wait for visibility of the control to be exposed; unfortunately I could not find a way around that.

**Comment by qkzk** [comment]
> Enforcement will begin soon, and visibility of the control will gradually roll out over the next few days, barring any issues. I expect many users to lose access while they wait for visibility of the control to be exposed; unfortunately I could not find a way around that.

Hello,
Our whole organisation has lost access to colab.

How can we know the control is visible ? Is there a specific space to watch ?

**Comment by pbeeken** [comment]
The enterprise admin just has to check in periodically in the same control space they authorize/deauthorize other apps for your school.  My admin has even called support services to verify that this coming down the pipe. Support keeps telling them that it is in the works and should appear soon.  My admin is checking every few hours (that's how much we are invested, across many different classes, in this service.)  I am hoping by the end of the week but then it wouldn't be the first time I was diagnosed with pollyannaism.

**Comment by cperry-goog** [comment]
Coming down the pipeline, I'm trying to get it as fast as we can, though we rely on many other services so Colab cannot enable this on our own.

I'll broadcast on this thread when visibility is at 100%.

**Comment by SF65** [comment]
Since this morning, the control for Colab is visible in our console (in Apps - Additional Google services)
We have regain access to Colab and everything seems fine.

Thank you for you work and your help.

**Comment by pbeeken** [comment]
The controls appeared earlier this week. It did take abut 24-36 hours to propagate through to all the students but it looks like it is good to go.  There are some really minor things that have changed in terms how the connection to each students cloud storage (Drive) is handled but it is completely unimportant.  Thanks for the effort in this.

**Comment by educate-remix** [comment]
Still not visible to us

**Comment by cperry-goog** [comment]
Thanks for the updates! Very glad to hear it's showing up, it's been a stressful week.

@educate-remix I checked this morning, and almost all organizations should have the control visible (there were a few errors we're chasing but it impacts vanishingly few orgs) can you check again, and if still not visible, possible to share a screenshot with colab-billing@google.com along with your domain and flag for me here? That's probably the easiest way to share your data without broadcasting it to this forum.

**Comment by qkzk** [comment]
It's working for us too now. Thanks for the regular updates  @cperry-goog , it was quite stressfull for us too :)

**Comment by educate-remix** [comment]
My Bad ....It indeed is showing up now.  Thanks for the efforts and updates !!!

**Comment by cperry-goog** [comment]
Hi folks, I'm closing this issue off given we believe we've restored access for all >13 year old K12 students. See our broad announcement here: https://twitter.com/GoogleColab/status/1467961695813337091 and the support article here: https://support.google.com/a/answer/11254550

We do not intend to support <13 year old students at this time, though we would be of course interested to hear requests.

Thanks for your patience during this semester/term/quarter. Open new bugs with any issues you may encounter.

**Comment by ProChore** [comment]
It still doesn't work for our domain. The organizational units are configured correctly, and I created an access group, but everything is blocked.
Can anyone help us?

**Comment by cperry-goog** [comment]
@ProChore do you have a Workspace support contact for your organization? I would try contacting them first.

Alternatively, send in a report to colab-billing@google.com and reference this GitHub issue and we can connect to troubleshoot.

**Comment by tiggerntatie** [comment]
I'm hearing from our admin that in order to enable Colab now we need to certify that all affected students (<18) have written parental permission to use it. Is that right?

**Comment by cperry-goog** [comment]
@tiggerntatie yes, there's a modal to that extent, which as I understand follows the same wording/warning for some (many?) other Workspace services, though questions involving the Workspace agreement are probably better handled by Workspace support.

**Comment by ProChore** [comment]
Hello, since the Colab update is unusable and no one bother to help us! We are very disappointed.
Our teachers and students can no longer work with Colab.

**Comment by cperry-goog** [comment]
@ProChore how is Colab unusable? Have you enabled Colab for your organization? https://support.google.com/a/answer/11254550

**Comment by ProChore** [comment]
Hello,
Here are some screenshots that will say more than a long text.
We've been using Colab for over a year, and everything was working fine
before the update.
Thanks

Pierre Collet ***@***.***)

*Administrateur Google Workspace Sévigné*
*Etablissement Privé sous contrat Sévigné*
*1 avenue Saint Jérôme*
*13013 MARSEILLE*


Le mer. 15 déc. 2021 à 18:43, cperry-goog ***@***.***> a
écrit :

**Comment by cperry-goog** [comment]
@ProChore this looks like a Workspace issue, I'm trying to escalate to the right team internally. If you have someone your organization works with in Workspace it'd be worth flagging for them.

**Comment by cperry-goog** [comment]
@ProChore I think you're trying to enable the Workspace Marketplace Colab app, which is totally separate (confusing) from Colab Workplace control. You'll need to navigate to the Workspace admin control center.

**Comment by ProChore** [comment]
Hello @cperry-goog,
I do not understand your answer.
I have put screenshots of the workspace to show you that, on the one hand,
the users were correctly configured (age limit), and that on the other
hand, Colab is indeed active with different rights following the
organizational units.
What else needs to be done?

ProCore

Le ven. 17 déc. 2021 à 02:03, cperry-goog ***@***.***> a
écrit :

**Comment by cperry-goog** [comment]
@ProChore You need to navigate to the Workspace admin control center: https://support.google.com/a/answer/182076?hl=en

You've been configuring the Workspace Marketplace, which will have no impact on access.

**Comment by ProChore** [comment]
Thank you very much ! I hadn't seen that Colab was now a complementary
Google service.
*ProChore*


Le mar. 28 déc. 2021 à 19:18, cperry-goog ***@***.***> a
écrit :

**Comment by cperry-goog** [comment]
Let me know if you get it to work!

**Comment by ProChore** [comment]
Yes it works!
Thanks for your help
*ProChore*


Le mar. 28 déc. 2021 à 19:30, cperry-goog ***@***.***> a
écrit :

**Comment by sdoro** [comment]
Yes it works!
Thanks!!

**Comment by thanksfortheride136** [comment]
As of 2023 is this still limited to 18+. Your wording has completely given my K-12 IT team exact reasons to completely disallow this service. I wish Google would think of the impact when randomly making a service like this 18+, IT now bans it completely. I am confused in the usage agreements, do students ages need to be 18+ to turn on?

**Comment by thanksfortheride136** [comment]
> @thanksfortheride136 Due to Workspace policies, the service is default off for a k12 organization - an admin needs to enable the service: https://knowledge.workspace.google.com/kb/how-to-enable-an-additional-google-service-in-the-admin-console-000007968

Thank you. But my IT is now hung up on the age because they now see it as something they cant do because its "over 18".

is there any documentation saying its NOT over 18 any longer? Or any way you can confirm.

**Comment by seantibor** [comment]
> > @thanksfortheride136 Due to Workspace policies, the service is default off for a k12 organization - an admin needs to enable the service: https://knowledge.workspace.google.com/kb/how-to-enable-an-additional-google-service-in-the-admin-console-000007968
> 
> Thank you. But my IT is now hung up on the age because they now see it as something they cant do because its "over 18".
> 
> is there any documentation saying its NOT over 18 any longer? Or any way you can confirm.

Disclaimer: I am not a lawyer, nor do I work for Google. This is just my advice based on my own experience. 

We asked our school's legal/compliance officer for her perspective based on the other Google Workspace tools we were using. In our case, the wording of our existing parental consent form and acceptable use policy was inclusive enough to cover adding Google Colab. We did not need any additional release from parents.

Other schools are different. Here's a [release form from Newton Public Schools](https://sdpc.a4l.org/agreements/2022-09-14_636_11229_signed_agreement_file.pdf) as an example.

Suggest that you pose this question to the same person/group that set your policies for Google Workspaces to see if that policy also includes other tools like Colab without additional releases. See what they say.

**Comment by cperry-goog** [comment]
Thanks @seantibor 

@thanksfortheride136 where are you seeing 18+? In terms of documentation, we just fall under the normal additional services controls: we announced the change via twitter: https://twitter.com/GoogleColab/status/1467961695813337091

https://support.google.com/a/answer/11254550 is official help center documentation and doesn't mention 18.
