### ISSUE TITLE
Cannot open files from google drive for editing in colab

### ISSUE THREAD

**Issue by ramtob** [googlecolab/colabtools#2266]
**Describe the current behavior**
![image](https://user-images.githubusercontent.com/11027714/134138726-4bdc7fa7-f411-4d64-9195-9eae0c735a1d.png)

After mounting google drive in colab (by using code from  course), I am trying to open a file for editing.
(See above image for the numbering)
(1) from the files tree 
=> fails silently
2) from a link to a file, a link that I extracted from  the files tree
=> fails. And in the browserr console I get the errors seen in (3)

**Describe the expected behavior**
1. Clilcking on the file name in the files tree will open the file for editing in colab.
Worked until now.
2. Clicking on the file path that I extracted from the file tree will open the file for editing in colab.
Worked until now.

**What web browser you are using**
Google Chrome 93.0.4577.82

**Comment by blois** [comment]
Thank you for the report.

I cannot repro 1), but I do see 2) and a fix will be arriving shortly.

Do files still not open from the file tree?

**Comment by ramtob** [comment]
> Thank you for the report.
> 
> I cannot repro 1), but I do see 2) and a fix will be arriving shortly.
> 
> Do files still not open from the file tree?

Hi @blois thanks for responding!

Yes, (1) does work from the file tree, when I double click. (I might have forgotten that it required a double click :)

If you can, let me know when (2) is fixed. Or whether there is a PR about it. Do you have an idea what causes this problem?

**Comment by blois** [comment]
This was a change on our side- the fix should be available early next week.
