### ISSUE TITLE
Colab not opening in safari (Mac OS Catalina)

### ISSUE THREAD

**Issue by working12** [googlecolab/colabtools#2269]
**Describe the current behavior**
Colab Not opening in safari (incognito + normal)

**Describe the expected behavior**
It should open. 
**What web browser you are using**
Safari
**Additional context**
![image](https://user-images.githubusercontent.com/12879472/134399137-51a28530-7915-4df8-80a5-7bb7fbe2ea2e.png)
![image](https://user-images.githubusercontent.com/12879472/134405413-b1c3e31c-7996-408a-b21e-2203fc7f00da.png)

**Comment by blois** [comment]
The latest update requires Safari >= 13.1 Firefox >= 72 or Chrome >=80.

**Comment by hassaanhameed786** [comment]
sad life :(
