### ISSUE TITLE
Runtime Automatically ending while using imshow(cv2)

### ISSUE THREAD

**Issue by dhruvchamania** [googlecolab/colabtools#227]
![screenshot from 2018-08-03 13-37-32](https://user-images.githubusercontent.com/24455149/43631991-6e7b1b66-9722-11e8-989b-6c6ce6fb2d5c.png)

AS you can see running the imshow causes a restart. Is there something that I am doing wrong or disregarding some colab restrictions.

**Comment by craigcitro** [comment]
duping against #458
