### ISSUE TITLE
Colab font in Mac OS Catalina

### ISSUE THREAD

**Issue by working12** [googlecolab/colabtools#2271]
**Describe the current behavior**
Why don't I see the fonts in Monaco or Menlo? (Which is the standard font for coding editors in my browser in safari in mac)

**Describe the expected behavior**
Expected the font of the system to be Monaco or Menlo.

**What web browser you are using**
Safari (13.1.1)

**Additional context**
![image](https://user-images.githubusercontent.com/12879472/134467753-af1ecf66-f56b-41a7-809c-a51ddc924420.png)
I have shown 4 sections. What are these fonts? How can I change it to Monaco or Menlo? 

Specifically I want (3) and (1) to be Monaco.

**Comment by blois** [comment]
Colab uses the default 'monospace' browser font. It looks like Safari has removed the ability to customize this?
https://apple.stackexchange.com/questions/106083/is-there-a-way-to-set-the-default-monospace-font-in-safari

**Comment by working12** [comment]
@blois Thanks but I have provision of applying stylesheets. And that works. But then everything in the browser changes to Monaco. Is it possible that I just apply the font rule to area (3) and (1) and nothing else? (I am wondering the css rules for that).

**Comment by blois** [comment]
If you are able to apply stylesheets during page load then you may be able to use:

```css
html { 
  --colab-code-font-family: Monaco;
}
```

The important thing is going to be that the font needs to be specified during page load.

**Comment by mainakmanna** [comment]
@blois I have this but when I tried your code it didnt work.

![image](https://user-images.githubusercontent.com/28564860/134729968-017fe522-ad35-4e05-8739-ed1f421bd5d6.png)

**Comment by working12** [comment]
@blois Sorry somebody deleted a comment earlier but I have a similar situation like him/her. Because I tried the stylesheets but it didn't change. I have created a `.css` file with this snippet and uploaded it in safari but it didn't work.

**Comment by blois** [comment]
Looks like it needs to be:
```css
html { 
    --colab-code-font-family: Monaco !important;
}
```

**Comment by working12** [comment]
@blois  Awesome. it worked.
