### ISSUE TITLE
Google Colab need to improve claims

### ISSUE THREAD

**Issue by YosmelyBermudez** [googlecolab/colabtools#2273]
Google charged me more than once for the cost of Google Colab Pro, and I need to get that money back because the first card I used was from Colombia and it didn't give me that address, but I never gave the option to buy. I had to use an American card, who do I have to talk to to reverse that money that they charged me too much?Google needs a claims section with payments, I need someone to give me an answer for this

**Comment by cperry-goog** [comment]
Please contact customer support at colab-billing@google.com
