### ISSUE TITLE
Sending feedback in Colab doesn't work

### ISSUE THREAD

**Issue by olaviinha** [googlecolab/colabtools#2274]
**Describe the current behavior**
Sending feedback in Colab doesn't work.

**Describe the expected behavior**
As it is suggested in the closing comments of bugs, in the issue filling guidelines, etc., sending feedback in Colab should definitely work.

**What web browser you are using**
Chrome.

**Additional context**
![image](https://user-images.githubusercontent.com/50331907/134587274-9863dfad-fe43-466f-bd17-64cd680c9954.png)

Clicking *Retry* will result this same box again.
Tried multiple times, refreshing page etc., always the same "Can't send feedback" error.

**Comment by craigcitro** [comment]
Thanks for the report! I'm seeing the same behavior; we're looking into it.

**Comment by craigcitro** [comment]
Thanks for the report; should be fixed.
