### ISSUE TITLE
Suspected bug in maintenance of flexibility to adjust usage dynamically for Pro+ users

### ISSUE THREAD

**Issue by olaviinha** [googlecolab/colabtools#2275]
**Describe the current behavior**
Unable to use any GPU at all for 10 days and counting, on Pro+ plan. I check multiple times a day every day if any GPU at all is available, and it never is.

**Describe the expected behavior**
Limitations should lighten and lift sooner. In the unlikely case that this scenario is NOT caused by a bug, then the new crazy-limitations should also be applied sooner, i.e. more evenly distributed and scattered throughout the billing period, i.e. count the continuous durations in hours, not in days or in weeks.

**What web browser you are using**
Chrome.

**Additional context**

Naturally it's a little difficult to tell if it's a bug or not due to the infamous "restrictions apply" disclaimer, but my developer instinct is definitely telling me that there must be some kind of a bug in whatever and however is maintaining the flexibility to adjust usage dynamically and applying the limitations as seen fit. I base this suspicion on two reasons:

1. I got Pro+ plan at the beginning of this month, after being on Pro plan for a year. As a heavy GPU user, I experienced many limitations many times also on Pro plan, but never ever anywhere near this drastic as I am now experiencing with the Pro+ plan.

2. Unrelated to above point, unless the end game is scamming people, which I find hard to believe in this case, it simply feels nonsensical to provide a service that is rendered useless by the service itself more than it is kept useful, as in what user is paying for, even with the expected limitations included. Particularly for the plan that is supposed to have the least restrictions. I have a equally hard time believing it has been designed that way intentionally, because I expect somewhat reliable and stable services by default from Google. This is not critique, this is one of my reasons to believe there may be a bug.

We all know about the flexibility and limitations, nothing new there. I would simply appreciate if you were able to check if there could possibly be an actual bug somewhere in the applying and lifting of limitations, even if affecting only a relatively small number of users upgrading from Pro to Pro+. As you can surely understand, it's a major issue, if it's a bug. Or alternatively confirm that it is not a bug, if you have already checked and confirmed this.

**Comment by rinabuoy** [comment]
With colab pro+, I am unable to connect to gpu 2/3 of the times.

**Comment by olaviinha** [comment]
Many Pro+ users are also reporting that after 2 weeks they no longer have access to GPUs above the "Free plan" GPUs, and that situation continues indefinitely.

**Comment by jadsonlourenco** [comment]
# Google Colab is a SCAM! 

Simple like that.

**Comment by cperry-goog** [comment]
Thanks for the feedback, we've investigated dozens of reports from users, and have not yet found any issues with assignments. By and large, users are getting good value for their Pro/Pro+ subscriptions, and we are working towards helping address some of the feedback in the community around transparency and control.
