### ISSUE TITLE
Cannot connect to GPU backend. Runtime Disconnect. COLAB PRO!

### ISSUE THREAD

**Issue by srositad** [googlecolab/colabtools#2278]
**Describe the current behavior**
I using GOOGLE Colab PRO right now, but it says Runtime Disconnect and I cant connect to GPU also I cant connect to TPU. Detect me as free user but currently I subscribe on colab PRO 1 week ago. Why I be detected as free user? And my friend that using free can running on GPU smoothly, and I always got reminder to disconnect also to change to connect without GPU/TPU. Please fix it. I need to train my model right now :((((((

**Describe the expected behavior**
Collab Pro or Plus can treated as special user so dont disconnect our runtime while training. what differences free and paid????????????

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
