### ISSUE TITLE
Demande high RAM but Dont get it

### ISSUE THREAD

**Issue by BttMA** [googlecolab/colabtools#2279]
**Describe the current behavior**
Hello,
I am working with the **Colab PRO **+**** and it has been a couple of hours since I can’t get the access of the high RAM. Yesterday, I was working with it just fine but today I can’t have it. When I demand it from the menu and save it don’t show me any restriction or error but when I check the resources I find that I stil have the 12GB not the 60GB. I really need it for my work. I don’t see where is the problem. Can you please tell me if there is something That I miss?
Thank you,

**Describe the expected behavior**
I need The 60BG that I payed for when I subscribed to PRO+.

**What web browser you are using**
Chrome

**Additional context**
![Screenshot 2021-09-24 at 11 13 53 AM](https://user-images.githubusercontent.com/90634663/134650193-6533239a-ee08-4464-bf1a-08bc0a661897.png)
![Screenshot 2021-09-24 at 11 15 16 AM](https://user-images.githubusercontent.com/90634663/134650314-9b75a0b2-e7a8-456c-bd6f-452fb265a1b3.png)

**Comment by Theivaprakasham** [comment]
Same issue here with me also for the past 2 days with Google Pro+ Subscription. I am not getting a HIGH RAM or a Better GPU than Tesla K80. The session gets disconnected sooner like the basic plan. After a couple of tries, I get a message like NO BACKENDS AVAILABLE. PLEASE TRY AGAIN LATER. I am sure that I have not exhausted my usage Quota as I have not used COLAB for more than 10 minutes in the last few weeks.


![image](https://user-images.githubusercontent.com/44334254/134704427-9b723943-0c50-4e23-a635-409533690093.png)


![image](https://user-images.githubusercontent.com/44334254/134704697-86e46028-7967-4295-bb87-e7d15c20cf57.png)

I mailed Google Colab Support and their reply was the same template message that does not help me. Attaching their reply below.

_```
Hi, 
 
In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Resources are prioritized by subscription tier, with Pro+ receiving highest priority, then Pro. During periods of heavy usage, we may not be able to allocate our most powerful hardware to all subscribers. You can read more about Pro allocations here[1]. We are actively working on features to give more control to users.
 
[1] https://colab.sandbox.google.com/notebooks/pro.ipynb#scrollTo=QMMqmdiYMkvi
 
Thanks,
--Colab Pro Customer Support
```_

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
