### ISSUE TITLE
Only 12GB RAM is allocated to Colab Pro+

### ISSUE THREAD

**Issue by Sanzid-Priam** [googlecolab/colabtools#2282]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by guiantunes12** [comment]
same problem, heeeelp.

**Comment by ijhan21c** [comment]
same problem.
I cant use anything. ha......

**Comment by wrhwrhwrhsf** [comment]
same

**Comment by Sanzid-Priam** [comment]
Problem is persisting more than one day.

**Comment by ginward** [comment]
Same here. I am a Colab Pro Plus member, and I am only allocated 12GB RAM.

**Comment by Benshan-WANG** [comment]
Pro+ user too, I have encountered this bug several days ago and it didn't be solved now.

**Comment by jadsonlourenco** [comment]
# Google Colab is a SCAM! 

Simple like that.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing, please submit feedback in product within Colab at Help > Send feedback

**Comment by Snnzhao** [comment]
I have similar problem.
My colab pro+ can access only less than 13g ram and p100 gpu.
This happens after I purchase a second colab pro+ account. Now both accounts meet this problem.
I have no idea how this happens. If google does not allow this, I can stop using the second account.
I want to know how long will this situation exists.
My accounts are 15827510651zs@gmail.com and senzhao950823@gmail.com.
