### ISSUE TITLE
Even after google colab pro + ram is limited to 12GB

### ISSUE THREAD

**Issue by kotran88** [googlecolab/colabtools#2285]
Hello 
I'm training quite well now with struggle , but from yesterday, it crash for ram after starting training. 
I checked and found out ram is allocated only 12GB even subscribing google colab pro + 
can you tell me how to get more ram to training?

**Comment by Sanzid-Priam** [comment]
Same problem. Big waste of time and money.

**Comment by kotran88** [comment]
I ' don't know why, but after restart run time now I can use more ram...
.... it should be notified by google if I am restricted ram or not... I paying money but for some times, I couldn't use it. 
what is it????

**Comment by Sanzid-Priam** [comment]
I have not got it yet. 52 GB RAM is available without GPU. With GPU, they are giving 12 GB.

**Comment by ginward** [comment]
Same issue here. My RAM is limited to 12GB only for GPU, and I am a Colab Pro Plus subscriber.

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro and Pro+ subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback and mention this GitHub issue.

For paid subscribers, if you have billing questions you can contact colab-billing@google.com

**Comment by Snnzhao** [comment]
I have similar problem.
My colab pro+ can access only less than 13g ram and p100 gpu.
This happens after I purchase a second colab pro+ account. Now both accounts meet this problem.
I have no idea how this happens. If google does not allow this, I can stop using the second account.
I want to know how long will this situation exists.
My accounts are 15827510651zs@gmail.com and senzhao950823@gmail.com.

**Comment by ayushi1212** [comment]
I also have similar problem, I have three accounts with colab pro plus and problems are same in all the accounts. Even issue is with the GPU as well, I'm very rarely assigned Tesla V100. Recently I was training a model and it stopped it between saying my GPU limit is exhausted.

**Comment by kechan** [comment]
This is happened to me today. I only have colab pro but i used to get 24-25gb on a high ram instance. What's happening? Is this related to recent price change?

**Comment by KishorD-04** [comment]
Google collab pro will allocate you high ram resource of 25gb when you select the high ram feature in the the >view resources >change running type > ram> high ram. 
This will solve the problem.

**Comment by Ture-Dukale** [comment]
it sucks!

**Comment by SuZeAI** [comment]
the same, colab  of mail machinelearning2028@gmail.com , ram < 13G, what colab pro

**Comment by hyphaestion** [comment]
Hello, what you need to do is within the settings click _Change Runtime Type_ and then select _High RAM_. Colab changes its UI from time to time but currently (as of September 2025) you need to select the down arrow in the top right corner, but only the arrow next to the RAM and Disk graphs.
