### ISSUE TITLE
LaTeX packages

### ISSUE THREAD

**Issue by akshay-seetharam** [googlecolab/colabtools#2286]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that I can't use LaTeX packages in Colab Markdown.

**Describe the solution you'd like**
I'd like to be able to import LaTeX packages in some way like $\usepackage{hyperref}$ or something like that.

**Describe alternatives you've considered**
You could somehow have an API to overleaf to render LaTeX and then just redirect that output back into Colab as an image in Markdown.
**Additional context**
Not necessary

**Comment by craigcitro** [comment]
The rendering for LaTex in markdown cells is actually handled client-side (by mathjax); making that capable of handling LaTeX packages would be exceedingly complex.

I don't think we're likely to handle this (via overleaf or locally running LaTeX); my only advice would be trying to render to an image yourself and insert that into your markdown. :/

**Comment by kzhk75** [comment]
> The rendering for LaTex in markdown cells is actually handled client-side (by mathjax); making that capable of handling LaTeX packages would be exceedingly complex.

Dose Google have any plan to update mathjax from v2 to v3 in Colaboratory?
I'd like to use [physics extension](http://docs.mathjax.org/en/latest/input/tex/extensions/physics.html) of [mathjax v3](https://www.mathjax.org/).
I can use this extension on blogspot with adding some \<script\> in \<meta\>

**Comment by blois** [comment]
LaTeX in markdown cells is rendered in Colab's top-level frame and there is no way to enable additional extensions within that context. For security reasons we have to limit what can be done in this scope.

It should be possible to enable MathJax running in the output of a specific cell by emitting HTML with the MathJax script tags & configuration.

**Comment by kzhk75** [comment]
Thanks, @blois 

> It should be possible to enable MathJax running in the output of a specific cell by emitting HTML with the MathJax script tags & configuration.

I've tried the following HTML source in the cell of Google colaboratory, but \dv{x}{t} is not rendered.
The source is correctly rendered in https://jsbin.com/ .
Is it a proper way to emit HTML?

```
%%html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>MathJax example</title>
  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script id="MathJax-script" async
          src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
  </script>
  <script>
    window.MathJax = {
    loader: {load: ['[tex]/physics']},
    tex: {packages: {'[+]': ['physics']}}
    };
  </script>
</head>
<body>
<p>
  When \(a \ne 0\), there are two solutions to \(ax^2 + bx + c = 0\) and they are
  \[x = {-b \pm \sqrt{b^2-4ac} \over 2a}. \]
</p>
<p>
Here is a sample of physics pacakges:
$$\dfrac{{\rm d} x}{{\rm d}t} = \dv{x}{t}$$
</p>
</body>
</html>
```
