### ISSUE TITLE
Unable to download a file

### ISSUE THREAD

**Issue by geoffrey4444** [googlecolab/colabtools#229]
I am unable to download files with Safari, though it works in Chrome.

I put this text into a cell of a new collab notebook saved to my Google drive:

```
file = open('Hello.txt', 'w')
file.write("Hello world\n")
file.close()
from google.colab import files
```

This works fine in Safari and Chrome. But then I try to run a cell with this

```
files.download('Hello.txt')
```

This works correctly in Chrome. But in Safari, the cell hangs, and the file never downloads.

I'm running macOS 10.13.6, Safari 11.1.2, and Chrome 68.0.3440.84.

Any help would be greatly appreciated!

**Comment by blois** [comment]
There is a new file download UI in the notebook sidebar, alongside the table of contents.
