### ISSUE TITLE
register google colab pro but only get gpu tesla k80 ?

### ISSUE THREAD

**Issue by bacgiangtramnam** [googlecolab/colabtools#2294]
i bought pro plan and i only get tesla k80 gpu

**Comment by nyansing** [comment]
The same bug to me

**Comment by renilo** [comment]
### **GOOGLE COLAB IS SCAM!!!**

Simple like that.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing, please submit feedback in product within Colab at Help > Send feedback
