### ISSUE TITLE
GPU no backend problem / only get 2 hour in 24 hour. RAM issue. COLAB PRO

### ISSUE THREAD

**Issue by George0793** [googlecolab/colabtools#2295]
![20210926_200153](https://user-images.githubusercontent.com/89333452/134811630-c42d5cf1-0e80-4120-9e6d-2f56a861e7dd.jpg)
<img width="959" alt="Capture1" src="https://user-images.githubusercontent.com/89333452/134811634-b8033efc-a022-4a39-a310-1d94d29ccdbd.PNG">

where is my extra RAM? Why k80 on Colab pro? why I get only 2 hour runtime in GPU? 
Expecting answerer from google colab.

**Comment by bacgiangtramnam** [comment]
I'm also having the same problem as my bro

**Comment by George0793** [comment]
@colaboratory-team @cperry-goog please answerer.

**Comment by nyansing** [comment]
I have the same problem

**Comment by arifaghafur** [comment]
same shit happen to pro+

**Comment by renilo** [comment]
### **GOOGLE COLAB IS SCAM!!!**

Simple like that.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing, please submit feedback in product within Colab at Help > Send feedback
