### ISSUE TITLE
Google Colab isn't working on Google Chrome

### ISSUE THREAD

**Issue by benedictflorance** [googlecolab/colabtools#2296]
**Describe the current behavior**
![image](https://user-images.githubusercontent.com/22187553/134823700-79fa67f6-fbc1-434a-9c99-05ada7abdaef.png)

It show the loading box in the left bottom, and never loads the notebook. There's just a white screen! On clicking Inspect Element, there are a couple of errors
![image](https://user-images.githubusercontent.com/22187553/134823686-f4bd83ad-71bf-48aa-b009-e52ffe82a034.png)

The notebook is not corrupted as it loads correctly on other browsers like Mozilla. I have also tried clearing cookies and opening the notebook on Chrome incognito, but doesn't help!

**Describe the expected behavior**
Should load the notebook

**What web browser you are using**
Chrome

**Comment by blois** [comment]
See https://github.com/googlecolab/colabtools/issues/2269 - you'll need Chrome >=80.

**Comment by jedesai** [comment]
i have still same issue. i am not able to open colab notebook, which i was working. i have tried relaunching of chrome after updating. 
my long hours of work is missing there on notebook. terrible!
