### ISSUE TITLE
 I've been using pro + for 2 days. I can only use it now. I can only use k80. How can I work? I'm almost done.

### ISSUE THREAD

**Issue by tuntun100** [googlecolab/colabtools#2298]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by renilo** [comment]
### **GOOGLE COLAB IS SCAM!!!**

Simple like that.

**Comment by cperry-goog** [comment]
https://colab.research.google.com/pro/terms
