### ISSUE TITLE
Can't use Bokeh inside Google Colab

### ISSUE THREAD

**Issue by abdelwahed** [googlecolab/colabtools#23]
I installed the library (from the notebook itself) and it showed the installation is successful

`!pip install bokeh`

but when I use it. It doesn't show anything (not even an error). Just blank output. When I check chrome's Javascript console, I see the follwoing

> Bokeh: ERROR: Unable to run BokehJS code because BokehJS library is missing

**Comment by craigcitro** [comment]
There's a [bokeh sample](https://colab.research.google.com/notebook#fileId=/v2/external/notebooks/charts.ipynb&scrollTo=JGnotb1n73Yk) in the docs, which works for me. In particular, note the comment there about needing to call `output_notebook()` in the cell where you're producing your chart.

I'm going to close, but do reopen if that isn't working for you.

**Comment by juanpac96** [comment]
Has anybody successfully embedded a bokeh server in a google colab notebook? I'm trying to run a copy of bokeh/notebook_embed.ipynb in google colab. All cells execute fine but show(modify_doc) produces no output. What value should I pass as notebook_url?
