### ISSUE TITLE
Error message: Runtime died. Automatically restarting

### ISSUE THREAD

**Issue by hilltopblv** [googlecolab/colabtools#230]
To reproduce, try this:
> import tensorflow as tf
> help(tf)

**Comment by craigcitro** [comment]
This does seem to be a bug -- I'm taking a look.

**Comment by craigcitro** [comment]
Ah, sadly, this is google/protobuf#2974, which is apparently blocked on another protobuf release. (At which point we need TF to pick up that release.)

I'll nose around to see if there's another fix for this, but I'm wary of trying to patch in a new version of proto (given that TF is compiled against it).

**Comment by colaboratory-team** [comment]
Tracked in b/126895080
