### ISSUE TITLE
Why k80 pro+

### ISSUE THREAD

**Issue by yelin10** [googlecolab/colabtools#2303]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
![Screenshot_20210927-062452](https://user-images.githubusercontent.com/91223853/134828686-203fe373-3b75-45fa-abc3-42890b4155e8.png)

**Comment by yelin10** [comment]
why k80 only?

**Comment by yelin10** [comment]
Why k80 only pro+

**Comment by Sanzid-Priam** [comment]
How much RAM?

**Comment by yelin10** [comment]
hight ram

**Comment by yelin10** [comment]
Pro+ k80 giving only pro+
high ram

**Comment by yelin10** [comment]
Why k80 only pro+

**Comment by BLACKGSGO** [comment]
same here, pro+ 2 days and i cant connect any other gpu, just K80 wtf?????????????

**Comment by renilo** [comment]
### **GOOGLE COLAB IS SCAM!!!**

Simple like that.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing, please submit feedback in product within Colab at Help > Send feedback
