### ISSUE TITLE
JUST K80 ON PRO+ MORE THAN TWO DAYS, IS A FREE GPU IN A PRO+ WTF GOOGLE COLAB????????

### ISSUE THREAD

**Issue by BLACKGSGO** [googlecolab/colabtools#2304]
i start my plan since 3 days, and after 1 day just have k80, wtf??????????????

**Comment by BLACKGSGO** [comment]
only 12.69gb of RAM, when were changes made?

**Comment by renilo** [comment]
### **GOOGLE COLAB IS SCAM!!!**

Simple like that.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing, please submit feedback in product within Colab at Help > Send feedback
