### ISSUE TITLE
Selecting a GPU or TPU on Colab Pro+ Account Prevents High RAM Runtimes from being allocated

### ISSUE THREAD

**Issue by NeverNude** [googlecolab/colabtools#2305]
**Describe the current behavior**
When selecting Hardware Accelerator = GPU, or Hardware Accelerator = TPU, and High-RAM on my Colab Pro+ , will consistently allocate a runtime that has 13.6 GB of CPU RAM rather than 20+.

**Describe the expected behavior**
When selecting Hardware Accelerator = GPU, or Hardware Accelerator = TPU, and High-RAM that 20+ GB of CPU RAM is available in the allocated runtime.

**What web browser you are using**
Chrome

**Additional context**
Selecting no hardware accelerator and high RAM runtime successfully results in a high RAM runtime being allocated.
Tested both TPU and GPU options with high RAM, and neither will work.

Was working successfully up until the morning of 9/26/2021.

Have been a Colab Pro+ subscriber for several weeks, so likely not related to recent account changes.

**Comment by leminhyen2** [comment]
I also have the same issue! I used to be able to train my research model with pro + but recently it's limited to 12GB RAM and my model crashed EVERYTIME.

**Comment by osmanmerdan** [comment]
I am dealing with the same issue! I am glad, I have found some people having similar problems. I am a new Pro+ member, also.  Selecting high RAM runtime does not do anything.

**Comment by ceenamathews** [comment]
I also have the same issue. How long should I wait to use GPU and high RAM runtime?

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro and Pro+ subscribers have greater limits than the free version of Colab.

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback and mention this GitHub issue.

**Comment by NeverNude** [comment]
What additional information or telemetry would be useful for the future reports@cperry-goog?  This has resolved itself as of yesterday, so I assume it was some amount of usage/rate limiting.  It would be valuable as a user to have insight into when resources are being limited, and when limits are removed (e.g. it will be 24 hours until you can use a high RAM runtime with GPU)

**Comment by NeverNude** [comment]
@cperry-goog ^
