### ISSUE TITLE
Colab Pro+

### ISSUE THREAD

**Issue by jalukasjagykuntilisasi** [googlecolab/colabtools#2307]
Please Fix Colab Pro+,

**Comment by BLACKGSGO** [comment]
Yes, please fix, only K80, her is avaible in free plan, WTF

.....

**Comment by paragnar9** [comment]
yes please fix , training is on hold since few days , Pls help

**Comment by jalukasjagykuntilisasi** [comment]
colab pro+ only k80

**Comment by renilo** [comment]
### **GOOGLE COLAB IS SCAM!!!**

Simple like that.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing, please submit feedback in product within Colab at Help > Send feedback
