### ISSUE TITLE
no backend available on cpu , tpu , and gpu on colab pro+

### ISSUE THREAD

**Issue by doninod** [googlecolab/colabtools#2308]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by renilo** [comment]
### **GOOGLE COLAB IS SCAM!!!**

Simple like that.

**Comment by doninod** [comment]
why do you say scam , colab is not a money game .

I'm just asking why there is no backend available and asking if this is a bug

**Comment by soulspark666** [comment]
@doninod as you can see from last two weeks there has been some issues with the service and someone did reach out clarifying it
https://github.com/googlecolab/colabtools/issues/2232#issuecomment-922160127

**Comment by doninod** [comment]
@soulspark666 

clarification as described.

where can i find the clarification

**Comment by paragnar9** [comment]
Same issue 
Cannot access GPU on Colab Pro +

**Comment by doninod** [comment]
> Same issue
> Cannot access GPU on Colab Pro +

can you connect with cpu , i can't connect with cpu and i can't continue my work

**Comment by soulspark666** [comment]
@doninod for a normal session like not pro, pro + the service seems to work, just that only k80s are there in GPU and it will be of limited runtime, so if there is something that you can do in the 6-8 hr one runtime with the browser open then I think you can give it a try, till google officially comes out and says something, or till you find alternatives to move your work to other platforms

**Comment by soulspark666** [comment]
Edited the link for the message

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing, please submit feedback in product within Colab at Help > Send feedback
