### ISSUE TITLE
Authentication taking lot of time 

### ISSUE THREAD

**Issue by avinashsai** [googlecolab/colabtools#231]
I am trying to authenticate google drive using colab. But when the authentication token is entered, it takes more than an hour to authenticate.I have restarted kernel couple of times but still authentication is not successful. Is there any possible way to reduce the delay in this authentication process.

**Comment by craigcitro** [comment]
In particular, `auth.authenticate_user` pops up a link you have to click -- did you click that? Where are things getting stuck?

**Comment by avinashsai** [comment]
Yes,I clicked that link and entered the string in the  box in colab notebooks. After that it is taking lot of time to authenticate. Iam not getting any error in the browser.

**Comment by craigcitro** [comment]
It shouldn't take more than a few seconds once you paste the link; two things to check:

1. If you open up the JS console, are there any errors?
1. Can you consistently reproduce this?

**Comment by avinashsai** [comment]
No there are no errors in the JS console.

**Comment by soylisK** [comment]
I am facing a similar problem, I copy and paste the key from the url but execution never ends.
Error Msg on js console:"Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”)."

**Comment by soylisK** [comment]
I've tried in an incognito window, at start of google colab I see the same msg on js console..
But still execution doesn't end..
Check this
![selection_032](https://user-images.githubusercontent.com/22836483/43993703-7c167288-9d9a-11e8-9253-be740e1b9162.png)

**Comment by colaboratory-team** [comment]
Thanks, the screenshot is useful.

What version of Chrome are you using?

**Comment by avinashsai** [comment]
Even I have tried authenticating in an incognito window. But I am not able to authenticate.I am attaching the screenshot below for the error that I got.
![selection_002](https://user-images.githubusercontent.com/22453634/43994177-2aa916fa-9db6-11e8-8ed3-6d923083934f.png)

**Comment by soylisK** [comment]
I use firefox quantum 61.0.1 (64-bit) 
and chromium Version 68.0.3440.84 (Official Build) (64-bit) on ubuntu 16.04
screenshot is from firefox in private mode

**Comment by soylisK** [comment]
I've tried on Chrome for linux  too, but still not authentication (without any errors from console this time).
Notice that I tried on a Windows10 pc, using Chrome, yesterday and  authentication was succesfull a couple of times, and it was very fast.
Have you found what is causing this problem?

**Comment by avinashsai** [comment]
Did the colab team find the solution to this problem??

**Comment by soylisK** [comment]
No. I'm trying everyday to connect at different hours of the day  but still nothing happens.

**Comment by colaboratory-team** [comment]
I just repeated the auth snippet in Chrome 68.0.3440.106 successfully.

```
from google.colab import auth
auth.authenticate_user()
```

A few things to try to diagnose this issue:

1. Try restarting your browser and repeating the execution in an incognito tab. (Make sure all extensions are disabled for incognito.)
1. Try a distinct browser. (This is basically another way to check if your browser settings are interfering with matters.)

**Comment by avinashsai** [comment]
I have tried with Firefox and Chrome in an incognito window with all extensions disabled. But authentication is not successful. We can access files in google drive through PyDrive only when the authentication is successful. Is there any other way to directly access files in drive without authentication??

**Comment by soylisK** [comment]
I've also (fresh)install (no extensions installed) Chrome (68.0.3440.106 ) 64-bit on Ubuntu 16.04, I've tried so many times (2-3 times per day on different hours ) and there is not any progress. Executing the snippet you mentioned never ends. All the other commands (like installing packages) run with no problem.

**Comment by colaboratory-team** [comment]
Do you by chance have [advanced account protection](https://landing.google.com/advancedprotection/) enabled for your account?

**Comment by soylisK** [comment]
No.

**Comment by SamarEA** [comment]
I have the same problem. Any solutions?

**Comment by soylisK** [comment]
> I have the same problem. Any solutions?

Personally I didn't find the cause of the problem.. so I saved money and build a pc with a decent gpu to do my work!!

**Comment by konemshad** [comment]
This problem seems to occur whenever you share your notebooks with someone else.

**Comment by tassosblackg** [comment]
Recently I've found this 
from google.colab import drive
drive.mount('/content/gdrive')

which does the job of mounting the drive to the colab-notebook
