### ISSUE TITLE
colab pro+ always allocates 12.69GB RAM memory

### ISSUE THREAD

**Issue by panafamily** [googlecolab/colabtools#2311]
although I set runtime type as GPU and High-RAM, the RAM memory of colab pro+ is always 12.69GB, the same memory of free version...

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing, please submit feedback in product within Colab at Help > Send feedback

**Comment by panafamily** [comment]
colab pro+ always allocates 12.69GB RAM memory
although I set runtime type as GPU and High-RAM, the RAM memory of colab
pro+ is always 12.69GB, the same memory of free version...

my account e-mail is ***@***.***"

thanks

>

**Comment by Snnzhao** [comment]
I have similar problem.
My colab pro+ can access only less than 13g ram and p100 gpu.
This happens after I purchase a second colab pro+ account. Now both accounts meet this problem.
I have no idea how this happens. If google does not allow this, I can stop using the second account.
I want to know how long will this situation exists.
My accounts are 15827510651zs@gmail.com and senzhao950823@gmail.com.
