### ISSUE TITLE
Can't use GPU and High RAM together in Colab Pro+ for more than half an hour. Please help

### ISSUE THREAD

**Issue by eliacs** [googlecolab/colabtools#2313]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by matpy1** [comment]
Same here. GPU only works with 12 GB of RAM

**Comment by George0793** [comment]
only for 2 hour with k80

**Comment by BLACKGSGO** [comment]
Same....

**Comment by kenan82** [comment]
Same but has been weeks

**Comment by jadsonlourenco** [comment]
more victims of the **Google Colab SCAM**...

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing, please submit feedback in product within Colab at Help > Send feedback
