### ISSUE TITLE
deleted folder gets recreated

### ISSUE THREAD

**Issue by GianniGi** [googlecolab/colabtools#2315]
**Describe the current behavior**
Every time that I start a colab instance, I find a folder called "sample_data" inside the root /content folder.
The "sample data" was probably donwloaded from a python script or from a github command. 
OR is it a github folder connected to my drive, so it gets recreated at each startup? 

**Describe the expected behavior**
I erase the folder and all the files, so it disappears, but it gets recreated at each new instance startup.
Then I reset the runtime, I delete it again, and at each startup the folder with the files is still there.
I mount the drive with 
from google.colab import drive
drive.mount('/content/drive')
and I've also tried to mount it "authorizing" a new colab file.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
I've tried to erase in chrome and in firefox

**Comment by craigcitro** [comment]
Yes, the `sample_data` folder is part of the base image, so it will always be present and can't be deleted.

(Even if you delete the files, the space is never actually recovered.)

**Comment by GianniGi** [comment]
Ok but why do I need a dataset?
