### ISSUE TITLE
import pygrib fails

### ISSUE THREAD

**Issue by janmandel** [googlecolab/colabtools#2316]
**Describe the current behavior**
`! pip install pygrib` goes through, but  `import pygrib` fails

**Describe the expected behavior**
The import should return without error at least

**What web browser you are using**
Tested on Chrome and Safari.

**Additional context**

See [pygrib-test.ipynb](https://colab.research.google.com/drive/1zLir45VsFF73shCOtOpHIbmouJ4Nu3YO?usp=sharing)

It seems to be a Colab-specific issue; locally, `pip install pygrib` followed by import goes through fine:
```
$ pip install pygrib
Collecting pygrib
  Using cached pygrib-2.1.4-cp39-cp39-macosx_10_9_x86_64.whl (16.5 MB)
Collecting pyproj
  Using cached pyproj-3.2.1-cp39-cp39-macosx_10_9_x86_64.whl (7.5 MB)
Collecting numpy
  Using cached numpy-1.21.2-cp39-cp39-macosx_10_9_x86_64.whl (17.0 MB)
Requirement already satisfied: certifi in /Users/jmandel/opt/anaconda3/envs/pygrib-test/lib/python3.9/site-packages (from pyproj->pygrib) (2021.5.30)
Installing collected packages: pyproj, numpy, pygrib
Successfully installed numpy-1.21.2 pygrib-2.1.4 pyproj-3.2.1
$ python
Python 3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygrib
>>> 
```

Also jswhit/pygrib#192

**Comment by craigcitro** [comment]
It looks like the upstream answer should get you unblocked: pygrib requires a newer numpy version.

I'm going to close this, but I'll also comment on the upstream issue you filed.
