### ISSUE TITLE
can't connect to mysql with mysql connector

### ISSUE THREAD

**Issue by ALexSamotuga** [googlecolab/colabtools#2319]
Have a nice day.

I get the "1698 (28000): Access denied for user 'root'@'localhost'" when try to connect to mysql server using the code below:

`from getpass import getpass
from mysql.connector import connect, Error

try:
  with connect(
    host="localhost",
    user="root",
    password=""  
  ) as connection:
      create_db_students = "CREATE DATABASE OmSTU"
      with connection.cursor() as cursor:
        cursor.execute(create_db_students)
except Error as e:
    print(e)`

Could somebody tell me, how i can fix it?

I use Opera ver. 79.0.4143.50
Here is a link to google drive on colab notebook:
[https://colab.research.google.com/drive/1OOOEIwmDHXAe7x2ajaEzDzGapSUsix5v?usp=sharing](url)

Thanks to all for answers!

**Comment by cperry-goog** [comment]
I think you'll have more luck asking on StackOverflow, we're not quite sure what's going on.
