### ISSUE TITLE
Colab Pro + does not let me use more than 12 Gb GPU

### ISSUE THREAD

**Issue by bennu99** [googlecolab/colabtools#2325]
**Colab Pro + does not let me connect to a second 12 GB GPU but instead only letting me use use one 12GB GPU**
A clear and concise explanation of what is currently happening.

**As a Colab Pro + user it is expected to be able to use more than 12 GB GPU (which is anyway freely available)**
A clear and concise explanation of what you expected to happen.

**Safari**
(Chrome, Firefox, Safari, etc.)

**A week ago I signed for Colab Pro + but I have been using only 12 Gb GPU till yesterday because I did not need more. When I finally tried to switch to a high ram GPU it was impossible no matter what and since then I can only use one 12 GB GPU. Very disappointed and regretting  for signing for a service that does not hold true*
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
<img width="898" alt="Screen Shot 2021-10-03 at 8 54 28 AM" src="https://user-images.githubusercontent.com/91794495/135742065-a471ceff-b848-4a8b-9ef0-d8107bffe6a9.png">
 - or Share Drive notebooks using the Share button then 'Get Shareable Link
<img width="1396" alt="Screen Shot 2021-10-03 at 9 15 54 AM" src="https://user-images.githubusercontent.com/91794495/135742431-3d45dd0e-156e-44be-9ce5-246531f8918e.png">
'.

**Comment by RicardoCorreiaMuniz** [comment]
same here

**Comment by p-dileep** [comment]
Same Issue here and none have any clue...

**Comment by Uemuet** [comment]
I have the same issue too and colab customer service doesn't exist....

**Comment by bennu99** [comment]
Closing this now as I got refunded. Hopefully they will fix this issue for everybody.

**Comment by Snnzhao** [comment]
I have similar problem.
My colab pro+ can access only less than 13g ram and p100 gpu.
This happens after I purchase a second colab pro+ account. Now both accounts meet this problem.
I have no idea how this happens. If google does not allow this, I can stop using the second account.
I want to know how long will this situation exists.
My accounts are 15827510651zs@gmail.com and senzhao950823@gmail.com.
