### ISSUE TITLE
Can not connect to GPU in Colab Pro + 

### ISSUE THREAD

**Issue by bennu99** [googlecolab/colabtools#2328]
**After 10 hours of waiting I can still not connect to any GPU at all**

** I am a Colab Pro + user since September 27 and I have been using only 12gb GPUs so far( two instances at a time till yesterday). Before I was using Colab Pro and the cool off period was never more than 6 hours for the same set up. What is the privilege of being a Colab Pro + user when one can not use more than 12 gb ram GPU and even after 10 hours of waiting time  it is still not possible to use any GPU at all?**

**Safari, Chrome**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by BLACKGSGO** [comment]
more than 1 week with the same shit problem...

**Comment by BLACKGSGO** [comment]
i pay for what? and we have all time the same 
answer wtffffffff

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
