### ISSUE TITLE
Is there a BUG in the "Send Feedback" option regarding Colab Pro + 

### ISSUE THREAD

**Issue by bennu99** [googlecolab/colabtools#2331]
In the past 3 days I sent 3 emails(to colab-billing@google.com) and 3 feedbacks asking the same questions as seen from the screenshot bellow and still no answer....
@cperry-goog I just followed your advice "We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback"
but, as you can see NO ONE cares.

<img width="1361" alt="colab" src="https://user-images.githubusercontent.com/91794495/136035145-26635dfe-e66b-444d-8b20-d4eaeb84032e.png">
![1](https://user-images.githubusercontent.com/91794495/136035248-79f1e7db-1e20-41f1-9f5a-0135a7edcfc6.jpg)

**Comment by RicardoCorreiaMuniz** [comment]
same here /:

**Comment by pillorygem** [comment]
Dude, we're having the exact same problem!
I didn't even get to train yet because as soon as I upgraded, I was hit "Usage Limits".  
I have no idea what's going on and there's no way to efficiently contact support or get a refund.
Very ridiculous!

**Comment by bennu99** [comment]
I am going to close this ticket since the problem was resolved for me (I got refund after this ticket). There is a problem regarding Colab Pro + and hopefully they will address it soon.
