### ISSUE TITLE
Only slow GPU as Pro+ user since a week

### ISSUE THREAD

**Issue by matpy1** [googlecolab/colabtools#2339]
Hello.

I am a Pro+ subscriber and since more than a week I only get access to slow GPU's (P100 PCIE) with 12 GB of RAM.
They are 7-8 times slower than previous GPU's I had access to and make it impossible to train my models (since it takes around 60 hours instead of 10 hours and there are regular crashes after more than 15 hours of running).

Its really not acceptable, considering that I pay 50 Dollars per month for this service and I get the same GPU's that I had access to as a normal Pro or free subscriber.

**Comment by mavillan** [comment]
Same problem here. Very disappointed with the pro+ service

**Comment by Snnzhao** [comment]
I have similar problem.
My colab pro+ can access only less than 13g ram and p100 gpu.
This happens after I purchase a second colab pro+ account. Now both accounts meet this problem.
I have no idea how this happens. If google does not allow this, I can stop using the second account.
I want to know how long will this situation exists.
My accounts are 15827510651zs@gmail.com and senzhao950823@gmail.com.
