### ISSUE TITLE
Colab runtime died when running pyreclab library

### ISSUE THREAD

**Issue by gasevi** [googlecolab/colabtools#234]
Hi,

   I am trying to run a recommendation library called pyreclab, but when the training step begins, the runtime dies immediately, no matter the runtime type ( GPU or None ) nor python version ( 2 or 3 ).
   Here is my source code:

!pip install pyreclab
!wget https://github.com/gasevi/pyreclab/blob/master/examples/dataset/u1.base
!wget https://github.com/gasevi/pyreclab/blob/master/examples/dataset/u1.test
from pyreclab import SVD
mysvd = SVD( dataset = 'u1.base', dlmchar = b'\t', header = False, usercol = 0,itemcol = 1,ratingcol = 2 )
mysvd.train( factors = 1000, maxiter = 100, lr = 0.01, lamb = 0.1 )

**Comment by craigcitro** [comment]
This seems to be fixed by the `pyreclab` 0.1.12 release (0.1.11 still exhibits the crash).
