### ISSUE TITLE
Pro+ no access to any GPU runtimes. [Usage Restriction]

### ISSUE THREAD

**Issue by pillorygem** [googlecolab/colabtools#2343]
I have not been able to even use a GPU runtime since I've subscribed to the Pro+ plan.

I've tested again on a free tier account, which **was** able to utilize a GPU.

There are others with the same issue on Reddit, GitHub, Discord, and Twitter, echoing the same issue. 

When emailing Colab, they just send a link to Usage Rules on their FAQ.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
