### ISSUE TITLE
Pro+ 

### ISSUE THREAD

**Issue by Kulinark** [googlecolab/colabtools#2344]
After subscribing to pro + I come across ONLY slow gpu and ALWAYS with 12gb ram. On another account with a $ 10 tariff, I always come across gpu with at least 25gb ram. This is clearly a mistake, or Google is simply bestial towards its customers.

**Comment by Zagsss** [comment]
Yes, I am on the same boat
This vague specs need to be stopped, just make it pay per minute already

**Comment by sobhan1398** [comment]
I Have the same problem too. With Colab pro plus, I don't have a much more ram, that is just 12 gb with gpu mode

**Comment by pillorygem** [comment]
Ever since I subscribed I haven't been able to even have a GPU runtime.
Keep in mind, that I haven't seriously used Colab's GPU resources in almost a year, and when I had a Pro, I never encountered ANY issues similar to these.

**Comment by Zagsss** [comment]
I don't know law, but is it allowed to sell random undertermined service time? with no minimum per day?

**Comment by CBassani94** [comment]
I have the same problem too.

**Comment by Zagsss** [comment]
@cperry-goog
