### ISSUE TITLE
No connection to the GPU for over a week (I'm a Pro Plus user).

### ISSUE THREAD

**Issue by takuto-suetsugu** [googlecolab/colabtools#2345]
I'm signed up for Google Colab Pro Plus, but I haven't been able to connect to my GPU for over a week. Probably because it has not been available since I cancelled my Pro Plus contract. (My contract is still active until the 19th, so according to the terms and conditions it should work.

Please let me know if there is a refund procedure as it has been unusable for over a week.

**Comment by yearofthewhopper** [comment]
Same. I signed up and not only have not gotten access to any GPU but also not given access to additional High-RAM. The output in the colab says I have 59gb but I am only able to use 16gb.

**Comment by Zagsss** [comment]
only getting P100, should be better but OK
the 12gb RAM that should be 16

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
