### ISSUE TITLE
DEOLDIFY VIDEO COLORIZER

### ISSUE THREAD

**Issue by ltommasini76** [googlecolab/colabtools#2355]
**Describe the current behavior**
Im experience an issue with Deolidy VideoColorizerColab (i'm using Mac ). It's now happening a lot of time. as you see in the screenshot, after all the process is finished, the player does nto show the video colorized. Moreover..it says that i can fin the video in "video/result/video.mp4"..and i cannot understand where this folder is located. I tried to reset chrome, use safari but i'm always ending here stucked without understand what is the problem. The video is comeing from  youtube, 2 minutes long, as source is an mp4. And lso it stop giving me a window saying that the runtime is expired or ended and it basically stop the process. any suggestions?

**Describe the expected behavior**
I made other test with 30 sec video at the beginning and it worked. Moreover...after i tried many times with other 2 video and get stucked, i used the firt link and it actually worked!..so i don't get where it could be the problem with this new link i'm using. And...just to make make the thing more funny, when i run "See how well render_factor values perform on a frame here"...it gives me the frames acutally colorized!

**What web browser you are using**
Chrome,Safari, 

**Additional context**
<img width="806" alt="Schermata 2021-10-14 alle 11 47 20" src="https://user-images.githubusercontent.com/92517467/137298497-9013224f-8860-48e6-9a66-7ce3368ba13b.png">
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by craigcitro** [comment]
The file is being created on your runtime (not your local computer); you can open the file browser on the left, find the file, and right-click to download.
