### ISSUE TITLE
Javascript issue - started 2 days ago, everyone I work with is having constantly

### ISSUE THREAD

**Issue by JohnGriffiths** [googlecolab/colabtools#2357]
**Describe the current behavior**

Box appears saying 

>"Could not load the JavaScript files needed to display output.
This is probably because your Google Account login access has expired or because third-party cookies are not allowed by your browser.Please reload this page."

**Describe the expected behavior**
Not having this error box. 

**What web browser you are using**
Chrome

**Additional context**

Everyone I know is experiencing this issue constantly for the past 2-3 days. Causing MAJOR problems. 

Also described here   https://github.com/googlecolab/colabtools/issues/1639

**Comment by JohnGriffiths** [comment]
Made a screenshot. 

Github won't let me upload it. 

You can see it here

https://drive.google.com/file/d/1vFtdQKIBV8S6eSJ9fqB32DaEl0ksECg6/view?usp=sharing

**Comment by cperry-goog** [comment]
If you encounter this again, please submit feedback in product and reference this github issue.
