### ISSUE TITLE
%load magic does not work for *.py scripts

### ISSUE THREAD

**Issue by VytautasV** [googlecolab/colabtools#2360]
**Describe the current behavior**
Nothing happens after running 
%load script.py
or 
load script.py

**Describe the expected behavior**
Load should show the contents of script.py

**What web browser you are using**
Chromium
Version 87.0.4280.66 (Official Build) Built on Ubuntu , running on LinuxMint 19.2 (64-bit)

**Comment by craigcitro** [comment]
Duplicate of #42
