### ISSUE TITLE
Colab Pro+ low RAM with High-RAM enabled

### ISSUE THREAD

**Issue by lukebor** [googlecolab/colabtools#2366]
It happens to me today and i don't know if there is quota to use RAM, but when i switch off GPU and hit High-RAM i will get it but with GPU i got only 13GB. What is the problem because i switched to pro+ to have more flexibility to preprocess data and now i cant even start my model becuase it crashes on StandardScaler() with 13 GB Ram. Switching to High-RAM i though but then still 13 GB.

**Comment by SamanthaZH** [comment]
got same problem. I need high RAM or I got SIGKILL error because out of RAM. Can anyone help me?
