### ISSUE TITLE
ValueError: mount failed: invalid oauth code

### ISSUE THREAD

**Issue by sunnydaystar** [googlecolab/colabtools#2369]
Started having the issue of mounting the google drive to colab since yesterday. Tried manually copying the auth code, which did not work. Any thought for how to resolve this?

**Comment by HumasLin** [comment]
Same here, I tried copying to other apps or restart the computer to make sure the copy is working normally but it still won't help. It keeps failing to ValueError: mount failed: invalid oauth code.

**Comment by aakashsinghbais** [comment]
Google Drive mount on a Colab notebook worked fine till yesterday...today it started giving `invalid oauth code error`!

My code:
```python
import os
import sys
from google.colab import drive
drive._mount('/content/mnt', force_remount=False) # To install any module, just upload it to My Drive/Colab Notebooks, and then use force_reload=True to remount the Drive
```

The Error:
![image](https://user-images.githubusercontent.com/56718090/150420729-f2540491-4f14-405b-a968-0848f751066e.png)

**Comment by craigcitro** [comment]
We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution. Let us know if you have any issues mounting Google Drive and executing code from the same account.

**Comment by aakashsinghbais** [comment]
I have an issue. I have two accounts, one has a PRO subscription to Colab but 15 GB drive space, the other doesn't have Colab PRO subscription, but is a G-Suite account. This is the reason why I wanted to mount the drive from a different account.

Will it not be possible now @craigcitro ?

**Comment by craigcitro** [comment]
Correct, it is unfrotunately no longer possible to mount drive for an account other than the one used for Colab.
