### ISSUE TITLE
google colab( jupyter ) , it is slowly to unzip, why, and how to make unzip quickly?

### ISSUE THREAD

**Issue by jinpengchina** [googlecolab/colabtools#237]
import zipfile
with zipfile.ZipFile("drive/app1/train.zip","r") as zip_ref:
    zip_ref.extractall("drive/app1/targetdir")

**Comment by craigcitro** [comment]
Based solely on the file path, I'm guessing the file is mounted via something like googledrive-ocaml-fuse?

If so, I'd try copying it to the local disk first, and see if that fixes the issue. If so, we know where to start.
