### ISSUE TITLE
Upgrading PyTorch to v1.10.0 and torchvision to v0.11.1 and torchaudio to v0.10.0

### ISSUE THREAD

**Issue by seemethere** [googlecolab/colabtools#2372]
Hi folks,

We released
* pytorch v1.10.0
* torchvision v0.11.1
* torchaudio v0.10.0

The wheel links are:

### CUDA 11.3

[download.pytorch.org/whl/cu113/torch-1.10.0%2Bcu113-cp36-cp36m-linux_x86_64.whl](https://download.pytorch.org/whl/cu113/torch-1.10.0%2Bcu113-cp36-cp36m-linux_x86_64.whl)

### CUDA 11.3

[download.pytorch.org/whl/cu113/torchvision-0.11.1%2Bcu113-cp36-cp36m-linux_x86_64.whl](https://download.pytorch.org/whl/cu113/torchvision-0.11.1%2Bcu113-cp36-cp36m-linux_x86_64.whl)

### CUDA 11.3

[download.pytorch.org/whl/cu113/torchaudio-0.10.0%2Bcu113-cp36-cp36m-linux_x86_64.whl](https://download.pytorch.org/whl/cu113/torchaudio-0.10.0%2Bcu113-cp36-cp36m-linux_x86_64.whl)

## Other notes
If you require wheels for Python 3.7 / 3.8, you can find the links here: [download.pytorch.org/whl/torch_stable.html](https://download.pytorch.org/whl/torch_stable.html)

We're looking to having it updated in Colab.

Thanks very much.

cc'ing @colaboratory-team

Similar to https://github.com/googlecolab/colabtools/issues/1891

**Comment by malfet** [comment]
@seemethere they should be cuda-11.3

**Comment by colaboratory-team** [comment]
Done.
