### ISSUE TITLE
Google Colab Pro+ RAM not available

### ISSUE THREAD

**Issue by danielvasic** [googlecolab/colabtools#2374]
Hello I've used Colab Pro before in HighRAM mode, and on many occasions I have available 25GB of RAM, after upgrading to Google Colab Pro+ I cannot get more than 12GB of RAM. Before that I was using Google Colab for training BERT model (1 eopch ETA 24h). I'm wondering if I hit some limit or something?

Best regards,
Daniel

**Comment by Snnzhao** [comment]
I have similar problem.
My colab pro+ can access only less than 13g ram and p100 gpu.
This happens after I purchase a second colab pro+ account. Now both accounts meet this problem.
I have no idea how this happens. If google does not allow this, I can stop using the second account.
I want to know how long will this situation exists.
My accounts are 15827510651zs@gmail.com and senzhao950823@gmail.com.
