### ISSUE TITLE
unable to execute the block of code it continuously loading in google colab

### ISSUE THREAD

**Issue by Ritesh796** [googlecolab/colabtools#2386]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
![Screenshot (25)](https://user-images.githubusercontent.com/83160726/138865766-8996de83-2549-4c46-95f5-c330e07ac7f0.png)

**Comment by cperry-goog** [comment]
@deniltonV I'd ask about your issue on stackoverflow, as it seems unrelated to the original issue.
