### ISSUE TITLE
RAM at 12GB at High-RAM runtime shape

### ISSUE THREAD

**Issue by pn12** [googlecolab/colabtools#2389]
My colab pro+ account's RAM is still at 12GB after selecting High RAM runtime multiple times.

Can anyone look into this ?

Thanks

**Comment by Snnzhao** [comment]
I have similar problem.
My colab pro+ can access only less than 13g ram and p100 gpu.
This happens after I purchase a second colab pro+ account. Now both accounts meet this problem.
I have no idea how this happens. If google does not allow this, I can stop using the second account.
I want to know how long will this situation exists.
My accounts are 15827510651zs@gmail.com and senzhao950823@gmail.com.

**Comment by Snnzhao** [comment]
I also have feedback. No reply currently.
