### ISSUE TITLE
Runtime disconnected immediately after captcha (with Pro)

### ISSUE THREAD

**Issue by dodger** [googlecolab/colabtools#2393]
**Describe the current behavior**
My runtime disconnected immediately after the captcha. I am a Pro user.

**Describe the expected behavior**
Not doing that. I am not paying for pro access to have to reinitalise everything out of the blue just because your crap is screwed up.

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
Can you send feedback in app? We can't diagnose runtime disconnections from GitHub.
