### ISSUE TITLE
Colab Pro+ can not connect to a GPU for more than 8 days

### ISSUE THREAD

**Issue by rs3dtouch** [googlecolab/colabtools#2394]
I can not connect to a GPU on my Colab Pro+ for more than 36 hours. I suppose this must be a bug.

I understand that GPUs are allocated dynamically, but if someone pays Pro+ it would be essential to get a smaller GPU at least. I can not even develop anything atm, because I can't run specific code without a GPU.

As said in my other post an indicator would be helpful. It's better to know how long one has to wait and maybe even manage the GPU > Developing with a small GPU, running the result with the best GPU.

**Comment by rs3dtouch** [comment]
Now it's been more than 3 days in total, please fix this. It's supposed to be Pro+...

**Comment by rs3dtouch** [comment]
Now it's been more than 4 days that I can not use my Pro+ account.

**Comment by rs3dtouch** [comment]
I just got a very general email from Colab support with no solution. 

Anyone had this experience before? It's now almost 5 days using Pro+ with the error message "Cannot connect to GPU backend"...

**Comment by syskn** [comment]
FYI I can't use any GPUs with my brand new subscription on personal account with Colab Pro+ for 10 days after being able to use it for the first 48 hours. This does not happen with my work account where at some point I was able to use two A100's for weeks.

I think there is a GPU quota that adds up over time, and if your account go below a certain threshold, you are either de facto banned for a month or your quota will only recover very slowly until you are "unbanned".

I understand the motivation behind this, but I think the current rule for Pro+ is too extreme given that in a Pro account you can still use GPU for hours even when your account is low on quota.

**Comment by rs3dtouch** [comment]
Thanks for you feedback @syskn! 

The strange thing is, that I was on Holidays for 10 days not using Pro+ and now it's 5 days I can not use it after my return.

I wasn't even using the A100 because of a bug, so I'm paying for 15 days not using my Pro+ so far. I think it is ridiculous that there is no quota/indicator that allows planning. 

Pro+ is not worth it at all. Especially if you have a monthly subscription and then you can not use it when needed. And there is no official channel for feedback on these issues :-(

**Comment by adamadatasci** [comment]
I am experiencing the same issu. Got also a meaningless general email. I cancelled my subscription and looking for others providers.

**Comment by rs3dtouch** [comment]
That's very sad to read, such a promising product and no support if there is an obvious bug...

Any recommendations for another platform?

**Comment by adamadatasci** [comment]
Consider using preamtible VM with V100 or A100  with colab for training and free colab for data processing.

**Comment by rs3dtouch** [comment]
Thanks Adam, will consider it. Have to rethink my pipeline indeed... I'm just disappointed, that I was happy with the service and was fine with paying 50€ and then the support is simply a ghost town...

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
