### ISSUE TITLE
GCloud init crashed under Colab Pro notebook

### ISSUE THREAD

**Issue by raymond-dms** [googlecolab/colabtools#2395]
**Describe the current behavior**
when executing command in my Colab notebook for initializing gcloud access, error/crash occurred today:
!gcloud init
------------------------------------------------------------------------------
Settings from your current configuration [default] are:
component_manager:
  disable_update_check: 'True'
compute:
  gce_metadata_read_timeout_sec: '0'
core:
  account: user@company

ERROR: gcloud crashed (ValueError): invalid width 0 (must be > 0)
------------------------------------------------------------------------------

**Describe the expected behavior**
I ran this command daily, along with/after "auth.authenticate_user()". never have issue. It would step-by-step prompt me to choose configuration, project, etc.

**What web browser you are using**
Chrome

**Additional context**
https://colab.research.google.com/drive/1QpFuFHXi6f8pUhqfx74jGMZRvr_Q95iS?usp=sharing

**Comment by craigcitro** [comment]
You're not doing anything wrong -- this was an upstream bug that was new and then fixed (https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/257); I'll work on getting it updated from our side. (In principle, you could `!gcloud components update`, but that fails with the same error you're hitting.)

**Comment by raymond-dms** [comment]
Thanks. Appreciate the update.

**Comment by craigcitro** [comment]
OK, this should be fixed! (You may need to `Factory reset runtime` to pick it up.)
