### ISSUE TITLE
Can't mount another drive in Colab Pro+

### ISSUE THREAD

**Issue by BraveSugar** [googlecolab/colabtools#2399]
I can't mount another google drive different from the one I am using in Colab Pro+ because of the credential error.
I can login another account and give a permission. However, the tab close automatically and I can't mount.
I can mount the same drive I am using in Colab Pro+.
1st picture is to give permission and 2nd picture is the tab that closed automatically and 3rd picture is the error.
Environment: Windows 10 Pro 64bit, Google Chrome 95.0.4638.69
What is the solution?
![s1](https://user-images.githubusercontent.com/78690779/140247682-1e41b3e6-643f-47ad-87b7-01f2c2589337.png)
![s2](https://user-images.githubusercontent.com/78690779/140247698-448f6833-f999-44be-852a-2eef51359d4a.png)
![s3](https://user-images.githubusercontent.com/78690779/140247701-990ed982-d456-48d0-8738-fc8b5dcb7121.png)

**Comment by BraveSugar** [comment]
I tried another account that uses free Colab plan, and I can mount another drive.
So, I think this bug is caused by Colab Pro+.

**Comment by yaryaryar** [comment]
i solved this problem.when i see the code in colab,i find two different functions.

One is the

def mount(mountpoint,
force_remount=False,
timeout_ms=120000,
use_metadata_server=None):

The other one is

def _mount(mountpoint,

force_remount=False,

timeout_ms=120000,

use_metadata_server=None):

if you use the _mount you can get the link.So i think this is a update for colab.

finally,try running this code:

from google.colab import drive

drive._mount('/content/drive')

**Comment by spike-h** [comment]
@yaryaryar When using drive._mount('/content/drive') I get an 'invalid oauth code' error when trying to mount a drive account that's different from the one that I'm running the notebook on.

![image](https://user-images.githubusercontent.com/53828342/141352675-f1098cc1-84a9-4f94-85a9-795502243528.png)

**Comment by spike-h** [comment]
> @yaryaryar When using drive._mount('/content/drive') I get an 'invalid oauth code' error when trying to mount a drive account that's different from the one that I'm running the notebook on.
> 
> ![image](https://user-images.githubusercontent.com/53828342/141352675-f1098cc1-84a9-4f94-85a9-795502243528.png)

Oop nvm I used drive._mount('/content/drive', force_remount=True) which breaks it for some reason.

**Comment by yaryaryar** [comment]
@spike-h **invalid oauth code** means you input a false authorization code.Check your code,then try running it again.
![N TDR0YIF_Y881@6}}($PKO](https://user-images.githubusercontent.com/72912402/141385273-6fa95328-d254-4e26-91ce-5fbd6c21b5df.png)

**Comment by BraveSugar** [comment]
@spike-h 
Thank you for solving this problem.
I could mount another drive
![s4](https://user-images.githubusercontent.com/78690779/141445885-e8ee3533-4856-4f9b-ab58-33ce9797cd4f.png)
.

**Comment by mohammadnajeeb** [comment]
Working sol:

#Connect Google Drive
from google.colab import drive
drive._mount('/content/drive')

**Comment by FrankLinxzx** [comment]
now _mount   cant use        why google always do something evil?

**Comment by hz424** [comment]
> 

_mount not working now..

from google.colab import drive  
drive._mount('/content/drive', force_remount=True)
ValueError: mount failed: invalid oauth code

**Comment by xjdeng** [comment]
drive._mount('/content/drive') isn't even opening the window to get the oauth code and it immediately returns invalid oauth code

**Comment by yaryaryar** [comment]
@FrankLinxzx @xjdeng @hz424 I just woke up, checked the code and found a solution. Someone has proposed a method.I've tried to run. Now I'll share it with you here：
```
from google.colab import drive, auth, output
auth.authenticate_user()
drive._mount('/content/drive')
```

**Comment by Rhitabrat** [comment]
@yaryaryar Not working. 😢

**Comment by FrankLinxzx** [comment]
> from google.colab import drive, auth, output
> auth.authenticate_user()
> drive._mount('/content/drive')

ok i'll try later

**Comment by zechenli03** [comment]
> > from google.colab import drive, auth, output
> > auth.authenticate_user()
> > drive._mount('/content/drive')
> 
> ok i'll try later

I tried it and now it could open the window to get the oauth code, but still get errors when you input the code.

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/23718939/150467672-a35db129-263d-48fb-9963-039f40c157ab.png">

**Comment by zechenli03** [comment]
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}
%cd /content
!mkdir drive
%cd drive
!mkdir MyDrive
%cd ..
%cd ..
!google-drive-ocamlfuse /content/drive/MyDrive

This code works for me. https://stackoverflow.com/a/69881106/15576628
But looking forward to an easier way.

**Comment by RajdeepBorgohain** [comment]
> !apt-get install -y -qq software-properties-common python-software-properties module-init-tools !add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null !apt-get update -qq 2>&1 > /dev/null !apt-get -y install -qq google-drive-ocamlfuse fuse from google.colab import auth auth.authenticate_user() from oauth2client.client import GoogleCredentials creds = GoogleCredentials.get_application_default() import getpass !google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL vcode = getpass.getpass() !echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} %cd /content !mkdir drive %cd drive !mkdir MyDrive %cd .. %cd .. !google-drive-ocamlfuse /content/drive/MyDrive
> 
> This code works for me. https://stackoverflow.com/a/69881106/15576628 But looking forward to an easier way.

This works! Thanks for saving time mate :)

**Comment by xjdeng** [comment]
> > !apt-get install -y -qq software-properties-common python-software-properties module-init-tools !add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null !apt-get update -qq 2>&1 > /dev/null !apt-get -y install -qq google-drive-ocamlfuse fuse from google.colab import auth auth.authenticate_user() from oauth2client.client import GoogleCredentials creds = GoogleCredentials.get_application_default() import getpass !google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL vcode = getpass.getpass() !echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} %cd /content !mkdir drive %cd drive !mkdir MyDrive %cd .. %cd .. !google-drive-ocamlfuse /content/drive/MyDrive
> > This code works for me. https://stackoverflow.com/a/69881106/15576628 But looking forward to an easier way.
> 
> This works! Thanks for saving time mate :)

This one works but the transfer speed is extremely slow.

**Comment by seven320** [comment]
> !apt-get install -y -qq software-properties-common python-software-properties module-init-tools
> !add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
> !apt-get update -qq 2>&1 > /dev/null
> !apt-get -y install -qq google-drive-ocamlfuse fuse
> from google.colab import auth
> auth.authenticate_user()
> from oauth2client.client import GoogleCredentials
> creds = GoogleCredentials.get_application_default()
> import getpass
> !google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
> vcode = getpass.getpass()
> !echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}
> %cd /content
> !mkdir drive
> %cd drive
> !mkdir MyDrive
> %cd ..
> %cd ..
> !google-drive-ocamlfuse /content/drive/MyDrive

This code works for me!! thx!! but it is not best way, actually.

**Comment by cperry-goog** [comment]
duping into #2563

**Comment by huylgia** [comment]
> from google.colab import drive
> drive._mount('/content/drive', force_remount=True)

At present, this way bankrupted

**Comment by huylgia** [comment]
> 

At present, this way bankrupted

**Comment by huylgia** [comment]
> !apt-get install -y -qq software-properties-common python-software-properties module-init-tools !add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null !apt-get update -qq 2>&1 > /dev/null !apt-get -y install -qq google-drive-ocamlfuse fuse from google.colab import auth auth.authenticate_user() from oauth2client.client import GoogleCredentials creds = GoogleCredentials.get_application_default() import getpass !google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL vcode = getpass.getpass() !echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} %cd /content !mkdir drive %cd drive !mkdir MyDrive %cd .. %cd .. !google-drive-ocamlfuse /content/drive/MyDrive
> 
> This code (https://stackoverflow.com/a/69881106/15576628) works for me. But looking forward to an easier way.

At present, this way bankrupted

**Comment by fernando-zalles** [comment]
I've been using this solution for a while but today is not working anymore

**Comment by Mazochi** [comment]
See this:
https://stackoverflow.com/a/69881106/8961642

**Comment by fernando-zalles** [comment]
> See this: https://stackoverflow.com/a/69881106/8961642

Yes, this solution is working, thank you! I wonder why is this happening so often and we need workarounds each time.

**Comment by jinyal** [comment]
> > !apt-get install -y -qq software-properties-common python-software-properties module-init-tools
> > !add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
> > !apt-get update -qq 2>&1 > /dev/null
> > !apt-get -y install -qq google-drive-ocamlfuse fuse
> > from google.colab import auth
> > auth.authenticate_user()
> > from oauth2client.client import GoogleCredentials
> > creds = GoogleCredentials.get_application_default()
> > import getpass
> > !google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
> > vcode = getpass.getpass()
> > !echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}
> > %cd /content
> > !mkdir drive
> > %cd drive
> > !mkdir MyDrive
> > %cd ..
> > %cd ..
> > !google-drive-ocamlfuse /content/drive/MyDrive
> 
> This code works for me too!! thx!! but it is not best way, actually.

This doesn't work for April neither...
