### ISSUE TITLE
ipywidget not supported ?

### ISSUE THREAD

**Issue by abdelwahed** [googlecolab/colabtools#24]
The following doesn't work in Google Colab

```
from ipywidgets import interact

def f(x):
  return x

interact(f, x=10)
```

**Comment by aquintanar** [comment]
I tried this fix with !jupyter nbextension enable --py --sys-prefix widgetsnbextension, after install widgetsnbextension and I always get this error "ImportError: No module named widgetsnbextension"

**Comment by blois** [comment]
Consolidating into https://github.com/googlecolab/colabtools/issues/60
