### ISSUE TITLE
Colab Pro + never getting V100

### ISSUE THREAD

**Issue by smithee77** [googlecolab/colabtools#2400]
Hi, I updated to Colab Pro + a week ago and I've been using it on a daily basis. Never get a V100, only P100s. 
And today I can't even get a second P100 session...

is this normal?

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
