### ISSUE TITLE
Google drive mount in Colab Pro failing with invalid oauth code 

### ISSUE THREAD

**Issue by techsachinkr** [googlecolab/colabtools#2403]
While i am trying to mount my google drive into any of my colab pro notebooks within that same google account, i am getting an oauth error even with correctly copying and pasting the authorization code  both manually and from copy button, also ensured no leading and training spaces, but still after so many tries not been able to mount google drive into any of my colab pro notebooks
Facing the issue since past 2 days, also emailed to colab-help@google.com and via Send feedback option in help, but didn't heard anything back.
Will appreciate any help in this regard.
![image](https://user-images.githubusercontent.com/32604730/140589212-d1439f19-5926-4595-8757-807ff3e9e0de.png)

**Comment by techsachinkr** [comment]
Found out it was in internal IT policy blocking drive access, found out the solution and its working fine now

**Comment by GHBTM** [comment]
@techsachinkr could you go into more detail with what exactly happened and what was your solution?  I am receiving the same errors, trying all varieties of using the _mount() function with mixed arguments, calling auth.authenticate_user() as well to prompt the "Enter your authorization code:" line with link and entrypoint.  This is on a Colab Pro + account connecting to a gdrive on the same google account.

**Comment by techsachinkr** [comment]
> @techsachinkr could you go into more detail with what exactly happened and what was your solution? I am receiving the same errors, trying all varieties of using the _mount() function with mixed arguments, calling auth.authenticate_user() as well to prompt the "Enter your authorization code:" line with link and entrypoint. This is on a Colab Pro + account connecting to a gdrive on the same google account.

I tried mounting using google-drive-ocamalfuse driver with the instructions as outlined at: https://medium.com/@uditsaini/access-google-drive-and-mount-google-drive-to-colab-notebook-google-ccbca1691d31 , and that worked out fine for mounting drive into colab.
Note: For the link above in step 5, either you can create new drive folder as mentioned there or access current directory structure  instead,by running the following in step5: 
!mkdir -p /content/drive/MyDrive
!google-drive-ocamlfuse /content/drive/MyDrive

**Comment by cperry-goog** [comment]
duping with #2563
