### ISSUE TITLE
GPU is not available on Colab Pro+ for a few days

### ISSUE THREAD

**Issue by ryletko** [googlecolab/colabtools#2404]
I can't start my colab notebook with GPU on Colab Pro+. It happened a couple days ago, and then I tried again today, but it is still not possible due to the limits.

**Comment by syskn** [comment]
On Colab Pro+, once you are banned from GPU (with a brand new account, you can run into this after using two GPUs simultaneously for 36-48 hours) you need to wait for the next billing period before you can use any GPU again.

This is unlike Colab Pro where you can use GPU again (though in a limited mode - which limits consecutive GPU instance use to 4-6 hours) after waiting for 16-24 hours.

**Comment by ryletko** [comment]
> In Colab Pro+, once you are banned from GPU (with a brand new account, you can run into this after using two GPUs simultaneously for 36-48 hours) you need to wait for the next billing period before you can use any GPU again.
> 
> This is unlike Colab Pro where you can use GPU again (though in a limited mode - which limits consecutive GPU instance use to 4-6 hours) after waiting for 16-24 hours.
> 
> In Colab Pro+, however, you can still use TPUs with a different quota from GPU whereas Colab Pro can give you a temp. 16-24h ban from both GPU/TPU when quota is out.
> 
> This apparently is not a bug, but nonetheless it is not exactly a good state of affair given that the most expensive tier has the most unforgiving policy when there is no visible quota.
> 
> Although there is no visible quota, you can tell how many quotas left on your account by GPU assignment. When quota is plenty you get A100. A bit less V100, much less P100. If you continue to use after P100-mode, you can get aforementioned 30-day ban. While you are not banned, quota recovers over time.

The thing is that I didn't use two GPU simultaneously. The last GPU was A100. That day when this happened I canceled my subscription, but it should be active until 11/28. Looks like it can be related to the issue.

**Comment by syskn** [comment]
From what I understand, there is a bug in Colab Pro+ where your instance can continue to run in background even though you can't see in the running instances list. This drains quota as well. I don't know what exactly can cause this, but possibly:
1. Killing an instance from the running instances list (most likely)
2. Killing an instance by resetting the runtime while a script is still running

Right now, the safest way to kill the instance in Colab Pro+ is unfortunately to let it expire.

**Comment by suminmin** [comment]
I currently have the same issue, too.

I ran the following code in Colab Pro+ with GPU 2 days ago.
https://colab.research.google.com/github/MichaelBosello/carla-colab/blob/master/carla-simulator.ipynb

I have never activated Colab with GPU since this issue happened despite no active sessions in Colab.

**Comment by wzrd** [comment]
I have the same issue on relatively new account, I have subscribed to Colab Pro+ 3 days ago and I can't use GPU with extended memory, when I run it, just 12 GB for GPU are available even if you choose extended. How can I solve this? It's quite annoying because GPU with good RAM is the main reason why I bought this subscription. Thank you in advance.

**Comment by antibodylover** [comment]
Same issue here. I am new to colab and paid $50 for pro+. It is very frustrating because my project muse use GPU. I actually have to create another pro account and paid $10 to use GPU. 
The whole shadow ban thing doesn't make any sense!

**Comment by bassaniokum** [comment]
> > In Colab Pro+, once you are banned from GPU (with a brand new account, you can run into this after using two GPUs simultaneously for 36-48 hours) you need to wait for the next billing period before you can use any GPU again.
> > This is unlike Colab Pro where you can use GPU again (though in a limited mode - which limits consecutive GPU instance use to 4-6 hours) after waiting for 16-24 hours.
> > In Colab Pro+, however, you can still use TPUs with a different quota from GPU whereas Colab Pro can give you a temp. 16-24h ban from both GPU/TPU when quota is out.
> > This apparently is not a bug, but nonetheless it is not exactly a good state of affair given that the most expensive tier has the most unforgiving policy when there is no visible quota.
> > Although there is no visible quota, you can tell how many quotas left on your account by GPU assignment. When quota is plenty you get A100. A bit less V100, much less P100. If you continue to use after P100-mode, you can get aforementioned 30-day ban. While you are not banned, quota recovers over time.
> 
> The thing is that I didn't use two GPU simultaneously. The last GPU was A100. That day when this happened I canceled my subscription, but it should be active until 11/28. Looks like it can be related to the issue.

My next billing day is 26/11 and I had canceled the subscription around 5 days ago. You know what? I have NO GPU since cancelling.

**Comment by antibodylover** [comment]
> > > In Colab Pro+, once you are banned from GPU (with a brand new account, you can run into this after using two GPUs simultaneously for 36-48 hours) you need to wait for the next billing period before you can use any GPU again.
> > > This is unlike Colab Pro where you can use GPU again (though in a limited mode - which limits consecutive GPU instance use to 4-6 hours) after waiting for 16-24 hours.
> > > In Colab Pro+, however, you can still use TPUs with a different quota from GPU whereas Colab Pro can give you a temp. 16-24h ban from both GPU/TPU when quota is out.
> > > This apparently is not a bug, but nonetheless it is not exactly a good state of affair given that the most expensive tier has the most unforgiving policy when there is no visible quota.
> > > Although there is no visible quota, you can tell how many quotas left on your account by GPU assignment. When quota is plenty you get A100. A bit less V100, much less P100. If you continue to use after P100-mode, you can get aforementioned 30-day ban. While you are not banned, quota recovers over time.
> > 
> > 
> > The thing is that I didn't use two GPU simultaneously. The last GPU was A100. That day when this happened I canceled my subscription, but it should be active until 11/28. Looks like it can be related to the issue.
> 
> My next billing day is 26/11 and I had canceled the subscription around 5 days ago. You know what? I have NO GPU since cancelling.

I also cancelled before GPU was banned.  looks like we find the reason. Can google legally do that? we paid for the whole month.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback

**Comment by Snnzhao** [comment]
I have similar problem
My colab pro+ can access only less than 13g ram and p100 gpu.
This happens after I purchase a second colab pro+ account. Now both accounts meet this problem.
I have no idea how this happens. If google does not allow this, I can stop using the second account.
I want to know how long will this situation exists.
My accounts are 15827510651zs@gmail.com and senzhao950823@gmail.com.

**Comment by Snnzhao** [comment]
It is really disappointing. With colab pro, I can have 25gb ram with gpu. But with colab pro+, I can only have 12gb. I can not even train my model with this. I hope get refund if google can not change this situation.

**Comment by bigstrawberrywakaka** [comment]
> It is really disappointing. With colab pro, I can have 25gb ram with gpu. But with colab pro+, I can only have 12gb. I can not even train my model with this. I hope get refund if google can not change this situation.

same as you. My colab pro+ also can access only less than 13g ram and p100 gpu. Do you get v100 or a100 gpu now? :)

**Comment by NeuronIQ** [comment]
The message box that pops up and lets you know that GPU's are not available should really mention that you can still use Colab Pro+ during the timeout in some instances, if you uncheck the background execution option in the runtime settings. I thought I was blocked for hours when it occurred to me that the restriction might be only for background tasks.
