### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib.metadata' while import wandb

### ISSUE THREAD

**Issue by hannaliavoshka** [googlecolab/colabtools#2406]
**Describe the current behavior**
Get ModuleNotFoundError: No module named 'importlib.metadata' while wandb library import, although this code was working a day before.

**Describe the expected behavior**
Expect that install and import wandb will be done without errors.

!pip install wandb -qqq
import wandb

**What web browser you are using**
Chrome

**Additional context**
https://gist.github.com/hannaliavoshka/9538bd3045761adbb4e56d4ea9a245d3

**Comment by craigcitro** [comment]
`importlib.metadata` is new in Python 3.8, but Colab is still on Python 3.7. This is most likely to be fixed as part of #1880; closing this as a dupe.

The only easy route I see is trying to use an older version of `wandb` if that works for you. 😞

**Comment by hannaliavoshka** [comment]
The temporal solution from wandb support is to use the following command before installing and importing wandb:
!pip install shortuuid==1.0.1
