### ISSUE TITLE
Google colab change form parameters

### ISSUE THREAD

**Issue by krishyadav007** [googlecolab/colabtools#2407]
I had a question which I asked here: https://stackoverflow.com/questions/68957902/google-colab-change-form-parameters, and it was not answered, therefore I guess this feature is not present in colab till now.

Therefore I would really like if making this feature would be possible, as it is needed.

Pasting the question from Stackoverflow
----
Google colab form has a powerful feature called Forms, https://colab.research.google.com/notebooks/forms.ipynb.

In that there is a dropdown option too, I want to modify the options of the drop-down list via code. 

Is it possible to do so colab?

Example it should work in this manner:

```
n = input('Give a number : ')
arr = list(range(n))
dropdown = arr[0] #@param arr
```

I have tried the above code but it won't work simply because the param list is after `#`, hence it commented as python cant reach till there.

If not should I use Jupyter Widgets? Would they be efficient, fast, and most importantly **re-run cells on change?**
----

**Comment by CrDevUno** [comment]
I'm looking also for an answer for use a dropdown in Google Colab.

Meanwhile, I'm using the code described in the [source:](https://stackoverflow.com/a/63117410/12511801)

```
# Import: 
import ipywidgets as widgets

# Set data source: 
fruit_list = ['pomegranate', 'watermelon', 'lychee']
fruit_picker = widgets.Dropdown(options=fruit_list, value='watermelon')

# This line draw the dropdown with the data source on it: 
fruit_picker
```

**Comment by cperry-goog** [comment]
We'd recommend using widgets at this time, keeping the general feature request open.

**Comment by blois** [comment]
For parameters which are dynamic (determined at runtime) the widgets approach used above is the recommended approach.

After the dropdown is displayed you can use `fruit_picker.value` to get the selected value.

**Comment by CrDevUno** [comment]
> For parameters which are dynamic (determined at runtime) the widgets approach used above is the recommended approach.
> 
> After the dropdown is displayed you can use `fruit_picker.value` to get the selected value.

For future references, can this issue stay open or mark it as feature request, please? - other users might be interested in this feature, too.

I'm searching about how to use `ipywidgets` in Google Colab, because, I have this scenario: 

> I created a dropdown with dynamic data *(from a JSON object I bring using requests)*, once an item is selected, it will show the results in a graph, however, I want to achieve that each time the dropdown changes its selected value, the graph is regenerated; in this case, I'm cleaning the output, but, cleaning the output also deletes the dropdown and so far, I'm unable to redraw the dropdown OR print the results in another code cell.

What would be the correct approach in Google Colab for the described scenario?

**Comment by blois** [comment]
A simple example is something like:
https://colab.research.google.com/gist/blois/71aa984fdab9a0b2ef6c9438dc06382e/altair-stock-comparison.ipynb

This is using `@interact`, but you can also use the Output widget to scope what is being cleared-
https://ipywidgets.readthedocs.io/en/latest/examples/Output%20Widget.html
