### ISSUE TITLE
The GPU instance in colab pro+ is allocated with only 12.69 GB of RAM against 52GB

### ISSUE THREAD

**Issue by dileep-kott** [googlecolab/colabtools#2408]
I have upgraded to colab pro+ for having more RAM GPU instances.  But now Colab only allocate high memory to CPU instance only. The GPU instance is always allowed 12.69GB but in colab pro, I was always getting 25GB for high RAM GPU instances. Please rectify this issue.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback

**Comment by Snnzhao** [comment]
I have similar problem
My colab pro+ can access only less than 13g ram and p100 gpu.
This happens after I purchase a second colab pro+ account. Now both accounts meet this problem.
I have no idea how this happens. If google does not allow this, I can stop using the second account.
I want to know how long will this situation exists.
My accounts are 15827510651zs@gmail.com and senzhao950823@gmail.com.

**Comment by Snnzhao** [comment]
@cperry-goog please help me solve the problem. I have submit feedback in product but receive no reply. My ddl is reaching,
I really need high ram to do experiments.
