### ISSUE TITLE
Unable to use GPU even if updating to pro

### ISSUE THREAD

**Issue by louis-ng1127** [googlecolab/colabtools#2409]
I have updated to Google Collab Pro, and when I use Google Collab I have ENABLED GPU acceleration, but a normal code takes 45 minutes to run, and then my local laptop only takes 10 minutes to run. When I look at the GPU usage, it is 0, which means there is no GPU acceleration, only CPU. This problem has been bothering me for a week and has had a serious impact on my project schedule. May I ask how I can solve this problem?

**Comment by louis-ng1127** [comment]
I have updated to Google Collab Pro, and when I use Google Collab I have ENABLED GPU acceleration, but a normal code takes 45 minutes to run, and then my local laptop only takes 10 minutes to run. When I look at the GPU usage, it is 0, which means there is no GPU acceleration, only CPU. This problem has been bothering me for a week and has had a serious impact on my project schedule. May I ask how I can solve this problem?

**Comment by cperry-goog** [comment]
We'll need a minimally reproducible notebook shared with us, but we'll note that enabling a GPU will occasionally require updates to your code in order to improve speed.

**Comment by Snnzhao** [comment]
I have similar problem.
My colab pro+ can access only less than 13g ram and p100 gpu.
This happens after I purchase a second colab pro+ account. Now both accounts meet this problem.
I have no idea how this happens. If google does not allow this, I can stop using the second account.
I want to know how long will this situation exists.
My accounts are 15827510651zs@gmail.com and senzhao950823@gmail.com.

**Comment by Snnzhao** [comment]
I have similar problem.
My colab pro+ can access only less than 13g ram and p100 gpu.
This happens after I purchase a second colab pro+ account. Now both accounts meet this problem.
I have no idea how this happens. If google does not allow this, I can stop using the second account.
I want to know how long will this situation exists.
My accounts are 15827510651zs@gmail.com and senzhao950823@gmail.com.

**Comment by Snnzhao** [comment]
It is really disappointing. With colab pro, I can have 25gb ram with gpu. But with colab pro+, I can only have 12gb. I can not even train my model with this. I hope get refund if google can not change this situation.
