### ISSUE TITLE
Unable to mount other google accounts drive.

### ISSUE THREAD

**Issue by AnirbanML** [googlecolab/colabtools#2414]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by AnirbanML** [comment]
I am unable to mount other drive account apart from my default colab pro google account.

**Comment by yaryaryar** [comment]
i solved this problem.when i see the code in colab,i find two different functions.

One is the

def mount(mountpoint,
force_remount=False,
timeout_ms=120000,
use_metadata_server=None):

The other one is

def _mount(mountpoint,

force_remount=False,

timeout_ms=120000,

use_metadata_server=None):

if you use the _mount you can get the link.So i think this is a update for colab.

finally,try running this code:

```
from google.colab import drive

drive._mount('/content/drive')
```

**Comment by yaryaryar** [comment]
i solved this problem.when i see the code in colab,i find two different functions.

One is the

```
def mount(mountpoint,
force_remount=False,
timeout_ms=120000,
use_metadata_server=None):
```

The other one is

```
def _mount(mountpoint,

force_remount=False,

timeout_ms=120000,

use_metadata_server=None):

```
if you use the _mount you can get the link.So i think this is a update for colab.

finally,try running this code:

```
from google.colab import drive

drive._mount('/content/drive')
```

**Comment by AnirbanML** [comment]
@yaryaryar Awsm Bro it worked..

**Comment by yaryaryar** [comment]
@AnirbanML 😜
