### ISSUE TITLE
Issues related with Google Colab pro plus and Enable GPU

### ISSUE THREAD

**Issue by mfceballosc** [googlecolab/colabtools#2416]
Today I have bought to Google Colab Pro+, and when I use Google Colab I could  not ENABLED GPU acceleration. When I tried select **runtime>change runtime type>GPU**, it doesn't work and appear next message: ** "Cannot connect to GPU backend You cannot currently connect to a GPU due to usage limits in Colab. Learn more As a Colab Pro+ subscriber you have higher usage limits than both non-subscribers and Colab Pro users, but availability is not unlimited. To get the most out of Colab Pro+, avoid using GPUs when they are not necessary for your work."**
This problem has been bothering me all day and has had a serious impact on my project schedule. May I ask you how can I to solve this problem?

![img1](https://user-images.githubusercontent.com/64441789/141384709-867dd106-0cd5-41ea-a61c-9c347e5a2e34.PNG)

![img2](https://user-images.githubusercontent.com/64441789/141384754-8903841a-5d15-4bd5-8a8e-27b7830b806f.PNG)

**Comment by rs3dtouch** [comment]
I struggle with this problem all the time on my Pro+. And there is no way to find out how long it can be used until this happens.

I canceled my Pro+ it because it is basically not predictable how many days it does (not) work :-(

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback

**Comment by Burera** [comment]
Hello, I am facing a problem.
I have subscribed to GOOGLE COLAB PLUS and I used GPUs yesterday only. Now it shows you have zero compute units and GPUS also disabled
