### ISSUE TITLE
torchaudio does not work

### ISSUE THREAD

**Issue by mthrok** [googlecolab/colabtools#2417]
**Describe the current behavior**
The following code was working earlier with PyTorch 1.9,

```python
!pip install torchaudio
import torchaudio
```

but after https://github.com/googlecolab/colabtools/issues/2372, it no longer works with the following error;

```
Collecting torchaudio
  Downloading torchaudio-0.10.0-cp37-cp37m-manylinux1_x86_64.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 9.3 MB/s 
Requirement already satisfied: torch==1.10.0 in /usr/local/lib/python3.7/dist-packages (from torchaudio) (1.10.0+cu111)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from torch==1.10.0->torchaudio) (3.10.0.2)
Installing collected packages: torchaudio
Successfully installed torchaudio-0.10.0
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-90af107c3418> in <module>()
      4 get_ipython().system('pip install torchaudio')
      5 
----> 6 import torchaudio
      7 print(torchaudio.__version__)

4 frames
/usr/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: libcudart.so.10.2: cannot open shared object file: No such file or directory
```

**Describe the expected behavior**

a version of `torchaudio` 0.10 that matches with the pre-installed PyTorch should be installed and works.

**What web browser you are using**

I tried with Chrome and Safari
- Safari (Version 15.1 (17612.3.2.1.1))
- Chrome (Version 95.0.4638.69 (Official Build) (arm64))

**Comment by malfet** [comment]
This is sort of expected, as you are trying to mix-n-match torch+cu113 and torchaudio+cu102
Testing if `pip install torchaudio -f https://download.pytorch.org/whl/cu113/torch_stable.html` will work

**Comment by mthrok** [comment]
Yeah, but the concern is that all the Colab notebooks with torchaudio from the past has stopped working.

**Comment by colaboratory-team** [comment]
Being worked on with internal bug: b/206623828

**Comment by aheba** [comment]
Hello @colaboratory-team,
we do a tutorial (20 students) this morning with torchaudio on collab and we got stuck too...

One of the solution is to use: 
```
!pip install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html 
```

are you working on that problem ?

**Comment by zpapakipos** [comment]
Hi, this issue has also broken 50% of our example colabs for the AugLy library (https://github.com/facebookresearch/AugLy/tree/main/examples). Do you have an ETA on when this issue will be fixed, or should we implement workarounds?

**Comment by mravanelli** [comment]
Right,
for us it is a kind of an emergency and many users are complaining about
it. I agree It could be important if you can share with us an estimate on
when the issue will be fixed.

**Comment by pierrebedu** [comment]
aheba gave a (temporary) solution 23 hours ago

**Comment by mravanelli** [comment]
Right, but this is quite annoying on our side because we have to basically
change something like 30 tutorials (and then modify them again when the
issue will be fixed).

**Comment by colaboratory-team** [comment]
Fixed.

**Comment by mravanelli** [comment]
Thank you very much!

**Comment by mthrok** [comment]
Thank you @colaboratory-team !

**Comment by loretoparisi** [comment]
This is amazing!
In my case I had to do the following:

```
%pip install torch==1.10.0+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```



Then it worked

```
import torchaudio
print(torchaudio.__version__)
0.10.0+cu113
time: 699 ms (started: 2021-11-15 12:51:46 +00:00)
```
