### ISSUE TITLE
Colab cannot mount the Google Drive of the account I need

### ISSUE THREAD

**Issue by SZ-STEPHEN** [googlecolab/colabtools#2418]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

I am a Colab Pro user, and I need to mount Google Drive to process my data. Today, when I use the code

"From google.colab import drive
drive.mount('/content/drive')"

To mount the Google Drive where I store data, it no longer asks me to fill in the verification code as usual, but goes to another page to log in to the account. When I log in to the Google Drive of my other account (not the account using the Colab), an error has occurred and it cannot be mounted. The specific situation is shown in the figures below

![11](https://user-images.githubusercontent.com/67080133/141400487-150700d6-1ae8-4e6a-a506-39613768ea0d.JPG)

![22](https://user-images.githubusercontent.com/67080133/141400503-73331fb7-6bc8-4619-b1d5-44115f7b4210.JPG)

![333](https://user-images.githubusercontent.com/67080133/141400529-80402919-8684-4348-bb8b-2c399932aeb3.JPG)

**Describe the expected behavior**

I hope to solve the problem as soon as possible, so that everyone can successfully mount the Google Drive of other accounts, thank you very much

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by SawanKumar28** [comment]
I am facing the same issue. I hope this is resolved as soon as possible.

**Comment by morg1649** [comment]
similar problem

**Comment by morg1649** [comment]
Google, please, return the disk connection to notepad as it was before (with code input)

**Comment by morg1649** [comment]
My temporary solution:
`!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}
%cd /content
!mkdir drive
%cd drive
!mkdir MyDrive
%cd ..
%cd ..
!google-drive-ocamlfuse /content/drive/MyDrive`

**Comment by ShamimAlMahmud** [comment]
I'm also fcing the same problem from this morning

**Comment by yaryaryar** [comment]
i solved this problem.when i see the code in colab,i find two different functions.

One is the

```
def mount(mountpoint,
force_remount=False,
timeout_ms=120000,
use_metadata_server=None):
```

The other one is

```
def _mount(mountpoint,

force_remount=False,

timeout_ms=120000,

use_metadata_server=None):
```

if you use the _mount you can get the link.So i think this is a update for colab.

finally,try running this code:

```
from google.colab import drive

drive._mount('/content/drive')
```

**Comment by SZ-STEPHEN** [comment]
> i solved this problem.when i see the code in colab,i find two different functions.
> 
> One is the
> 
> ```
> def mount(mountpoint,
> force_remount=False,
> timeout_ms=120000,
> use_metadata_server=None):
> ```
> 
> The other one is
> 
> ```
> def _mount(mountpoint,
> 
> force_remount=False,
> 
> timeout_ms=120000,
> 
> use_metadata_server=None):
> ```
> 
> if you use the _mount you can get the link.So i think this is a update for colab.
> 
> finally,try running this code:
> 
> ```
> from google.colab import drive
> 
> drive._mount('/content/drive')
> ```

Thanks a lot! It works!

**Comment by Rajarshi07** [comment]
> i solved this problem.when i see the code in colab,i find two different functions.
> 
> One is the
> 
> ```
> def mount(mountpoint,
> force_remount=False,
> timeout_ms=120000,
> use_metadata_server=None):
> ```
> 
> The other one is
> 
> ```
> def _mount(mountpoint,
> 
> force_remount=False,
> 
> timeout_ms=120000,
> 
> use_metadata_server=None):
> ```
> 
> if you use the _mount you can get the link.So i think this is a update for colab.
> 
> finally,try running this code:
> 
> ```
> from google.colab import drive
> 
> drive._mount('/content/drive')
> ```

THANK YOU

**Comment by cperry-goog** [comment]
We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution. Let us know if you have any issues mounting Google Drive and executing code from the same account.

Any workarounds for connecting other accounts will eventually cease to succeed, so know that you will need to migrate at some point in the near future.

**Comment by Huy-LichHoang** [comment]
it no longer run well

**Comment by ananda1996ai** [comment]
> We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution. Let us know if you have any issues mounting Google Drive and executing code from the same account.
> 
> Any workarounds for connecting other accounts will eventually cease to succeed, so know that you will need to migrate at some point in the near future.

Why on earth would you do this! This makes sharing code so much harder which is supposed to be the very purpose of "Colab"!! The functionalityy to mount different drives should have been kept as is. This is just stupid.

**Comment by tian1327** [comment]
> > We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution. Let us know if you have any issues mounting Google Drive and executing code from the same account.
> > Any workarounds for connecting other accounts will eventually cease to succeed, so know that you will need to migrate at some point in the near future.
> 
> Why on earth would you do this! This makes sharing code so much harder which is supposed to be the very purpose of "Colab"!! The functionality to mount different drives should have been kept as is. This is just stupid.

I believe they are trying to prevent people from combining resources under different gmail account. For example, I used to mount my personal colab with my university google drive since student account has unlimited storage for google drive. Now they found this bug and fixed it.

Also, I believe they announced that student account can no longer mount their drive to colab.

**Comment by PratikStar** [comment]
@tian1327 This is exactly how I was using this mounting function. Sadly not possible now :(

**Comment by bryastring** [comment]
It is frustrating that they won't let people do this any more. All they're going to do is force people to look into using different platforms that are better and more user friendly.
