### ISSUE TITLE
I can not mount my colab account to a different drive account

### ISSUE THREAD

**Issue by amro-kamal** [googlecolab/colabtools#2419]
**The current behavior**
Colab doesn't mount to a google drive account with a different email. It can be mounted only to the drive account associated with the Colab email.
When you try to mount the account and after entering the email and the password, it gives a white screen with the text "Close this tab/window" without any details.
**Describe the expected behavior**
Till a few days ago, it was to mount Colab to any drive account I have.

**Comment by syskn** [comment]
It looks like a bug.

From other posts and stackoverflow: you can still use the old procedure with (with underline before **mount**)
`drive._mount('/content/drive')`

**Comment by Randy1435** [comment]
It does look indeed like a bug but syskn is right,

Instead of using:
"from google.colab import drive
drive.mount('/content/drive')"

Use:
"from google.colab import drive
drive._mount('/content/drive')"

**Comment by jhonmaker-gonsu** [comment]
> It does look indeed like a bug but syskn is right,
> 
> Instead of using: "from google.colab import drive drive.mount('/content/drive')"
> 
> Use: "from google.colab import drive drive._mount('/content/drive')"

thanks! now It works!!

**Comment by rs3dtouch** [comment]
Thanks, I was wondering what was broken there...

**Comment by craigcitro** [comment]
We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution. Let us know if you have any issues mounting Google Drive and executing code from the same account.

**Comment by ananda1996ai** [comment]
> We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution. Let us know if you have any issues mounting Google Drive and executing code from the same account.

Why would you do this! This makes code sharing so much harder which was suppossed to be the very purpose of "Colab!" The functionality to mount different drives should have been kept as is. This is just stupid!
I'm guessing this just to force more people into a Google One subscription!? Good luck on that 👍

**Comment by tin2123** [comment]
Hi everyone Colab doesn't mount to a google drive account with a different email. It can be mounted only to the drive account associated with the Colab email.
When you try to mount the account and after entering the email and the password, it gives a white screen with the text "Close this tab/window" without any details. I tried the code by adding underscore before mount still does not work. please help. thanks and godbless

**Comment by roshkins** [comment]
Hi @craigcitro I use Advanced Account Protection, and I bought the Google Colab upgrade. I cannot authenticate my account, I get a 400 rejected message. I want to use a different account's google drive as a work around, but I see here that is not possible. Any suggestions for either connecting to the same account's Google Drive or some other way? Otherwise I have a subscription that I can't use or get a refund on that I didn't know was broken.

**Comment by achyu2003** [comment]
> 

Please fix the bug. Colab should allow mounting of any other Google Account too

**Comment by phenggeler** [comment]
> Hi @craigcitro I use Advanced Account Protection, and I bought the Google Colab upgrade. I cannot authenticate my account, I get a 400 rejected message. I want to use a different account's google drive as a work around, but I see here that is not possible. Any suggestions for either connecting to the same account's Google Drive or some other way? Otherwise I have a subscription that I can't use or get a refund on that I didn't know was broken.

Has there been any update on looking at ensuring Advanced Protection can work with Google Colab?

**Comment by teengineer** [comment]
> We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution. Let us know if you have any issues mounting Google Drive and executing code from the same account.

it's not make sense and is not about secure. you should not have done this

**Comment by akmaldika** [comment]
> We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution. Let us know if you have any issues mounting Google Drive and executing code from the same account.

rollback this, i need the file in my other gmail, it is not simple to move around the file

**Comment by cuongptnk** [comment]
> Hi @craigcitro I use Advanced Account Protection, and I bought the Google Colab upgrade. I cannot authenticate my account, I get a 400 rejected message. I want to use a different account's google drive as a work around, but I see here that is not possible. Any suggestions for either connecting to the same account's Google Drive or some other way? Otherwise I have a subscription that I can't use or get a refund on that I didn't know was broken.

I am in same situation

**Comment by lai-tran-exelab** [comment]
Google always finds a way to cash in on us!!
