### ISSUE TITLE
Mounting Google Drive Not Working Authorization Error Error 403: rate_limit_exceeded  This app has reached its sign-in rate limit for now.

### ISSUE THREAD

**Issue by andrewcchan** [googlecolab/colabtools#2422]
**Describe the current behavior**

Google Colab seems to have changed the way it authorizes mounting of Google Drive. When I run the following:
```
from google.colab import drive
drive.mount('/content/drive')
```
There is a new popup that now signs me in automatically to mount the drive. However, I am now facing this rate limit error:
![Screenshot 2021-11-12 203458](https://user-images.githubusercontent.com/40149441/141605780-31d4c854-abc1-4a81-9510-e0fe1061785a.png)

**Describe the expected behavior**
It should automatically mount Google Drive without error.

**What web browser you are using**
Chrome

**Additional context**
Previously the authorization method required cutting and pasting a UUID that allowed authorization. Despite multiple sign ins I never encountered this error. Now with the new oauth method it seems we have reached a rate limit.

**Comment by IzzyKohout** [comment]
I have exactly the same issue on my Colab Pro account

**Comment by tanbh0009** [comment]
I have the same issue.

**Comment by tanbh0009** [comment]
I found a work around from a comment by https://github.com/syskn

From other posts and stackoverflow: you can still use the old procedure with (with underline before mount)
drive._mount('/content/drive')

**Comment by usergenic** [comment]
@tanbh0009 thank you for that workaround ❤️

**Comment by steffng** [comment]
@tanbh0009 thank you so much!

**Comment by andrewcchan** [comment]
@tanbh0009 thank you for that.

I am still leaving this issue open so that Google knows that the default behavior does not work.

**Comment by Randy1435** [comment]
Yeah, google needs to fix their new system, it's everything but improved. The old system works fine!

**Comment by anuragkanwar** [comment]
> I found a work around from a comment by https://github.com/syskn
> 
> From other posts and stackoverflow: you can still use the old procedure with (with underline before mount) drive._mount('/content/drive')

thanks it works for me, you saved my day

**Comment by MaxwellHogan** [comment]
> I found a work around from a comment by https://github.com/syskn
> 
> From other posts and stackoverflow: you can still use the old procedure with (with underline before mount) drive._mount('/content/drive')

life saver

**Comment by srk-dev** [comment]
> I found a work around from a comment by https://github.com/syskn
> 
> From other posts and stackoverflow: you can still use the old procedure with (with underline before mount) drive._mount('/content/drive')

Thank you for this work around!

**Comment by blois** [comment]
The rollback for this has been in for a few days, issue appears to be resolved.
