### ISSUE TITLE
Sorry, no backends available. Please try again later. 

### ISSUE THREAD

**Issue by Tehqy** [googlecolab/colabtools#2423]
**Describe the current behavior**
Every time I try to connect it tells me "_Sorry, no backends available. Please try again later._"

**Describe the expected behavior**
It should just connect....

**What web browser you are using**
Chrome

**Additional context**
![image](https://user-images.githubusercontent.com/90979039/141621980-eff33cf5-e4ce-477a-9854-5ec196aa1350.png)

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
