### ISSUE TITLE
Issues with Collab Pro+ Requesting TPU and High RAM

### ISSUE THREAD

**Issue by ek631768** [googlecolab/colabtools#2425]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
I have Collab Pro+ and am not able to get an instance with High RAM and TPU (when request High RAM and TPU  I do so I am getting less than 13 GB of RAM). However, when I request and instance without the TPU or GPU and High RAM (I get 51.01 GB of RAM).  I am unable to get an instance with both TPU and High RAM.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
I expect to get a Collab Notebook instance with High RAM and TPU when I make changes to the notebook settings to have the hardware accelerator TPU and  run time shape High RAM ('runtime type'). 
**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by Snnzhao** [comment]
I have similar problem
My colab pro+ can access only less than 13g ram and p100 gpu.
This happens after I purchase a second colab pro+ account. Now both accounts meet this problem.
I have no idea how this happens. If google does not allow this, I can stop using the second account.
I want to know how long will this situation exists.
My accounts are 15827510651zs@gmail.com and senzhao950823@gmail.com.

**Comment by Snnzhao** [comment]
It is really disappointing. With colab pro, I can have 25gb ram with gpu. But with colab pro+, I can only have 12gb. I can not even train my model with this. I hope get refund if google can not change this situation.

**Comment by ChaozhongLiu** [comment]
Same here, getting only 12GB with colab pro+. Really fooled by Google when they ask me whether to upgrade to get more RAM...

**Comment by snowmint** [comment]
Same here... I'm also getting only 12GB RAM with colab pro, it's not worth for $49.9... And also Google didn't provide customer service in Taiwan, it's very disappointing. I have been send email to colab-help@google.com but after 2 days also didn't get any single word of reply, well done.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback

**Comment by hinaqasim30** [comment]
I got the same issue but what is the solution?? anybody know??
