### ISSUE TITLE
Issue about using GPU in R kernel

### ISSUE THREAD

**Issue by skypc785308** [googlecolab/colabtools#2426]
**Describe the current behavior**
I set the hardware accelerator to GPU and runtime type is R in colab. I install keras package and work well, but there is an error about not found any CUDA in system when I call `keras_model_sequential()`.

```
Timestamp | Level | Message
-- | -- | --
Nov 15, 2021, 1:04:32 PM | WARNING | WARNING:root:kernel 4a06743c-433e-4a9c-a12b-b86f5a4adfb3 restarted
Nov 15, 2021, 1:04:32 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Nov 15, 2021, 1:04:31 PM | WARNING | 2021-11-15 05:04:31.881321: F tensorflow/core/platform/statusor.cc:33] Attempting to fetch value instead of handling error INTERNAL: failed initializing StreamExecutor for CUDA device ordinal 0: INTERNAL: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_UNKNOWN: unknown error
Nov 15, 2021, 1:04:31 PM | WARNING | 2021-11-15 05:04:31.880232: W tensorflow/stream_executor/cuda/cuda_driver.cc:374] A non-primary context 0x559a2596e000 for device 0 exists before initializing the StreamExecutor. The primary context is now 0x559a1f161ba0. We haven't verified StreamExecutor works with that.
```

![](https://i.imgur.com/A1jTmOa.png)

**Describe the expected behavior**
I should be able to  use GPU and run keras in R.

**What web browser you are using**
Chrome 95.0.4638.69

**Additional context**
https://colab.research.google.com/drive/1Ave4qyr-mO66Fo5j4UjMh62lXk2NAchd?usp=sharing

**Comment by cperry-goog** [comment]
We're not familiar with the R Keras interface, you may have more luck asking on StackOverflow.
