### ISSUE TITLE
My colab pro+ can access only less than 13g ram and p100 gpu.

### ISSUE THREAD

**Issue by Snnzhao** [googlecolab/colabtools#2428]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
My colab pro+ can access only less than 13g ram and p100 gpu.
This happens after I purchase a second colab pro+ account. Now both accounts meet this problem.
I have no idea how this happens. If google does not allow this, I can stop using the second account.
I want to know how long will this situation exists.
My accounts are 15827510651zs@gmail.com and senzhao950823@gmail.com.
**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
I hope at leat my first account 15827510651zs@gmail.com can be normal.
I can stop using the second one.
**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by Snnzhao** [comment]
I also feed back in colab, but no reply exists currently.

**Comment by Snnzhao** [comment]
It is really disappointing. With colab pro, I can have 25gb ram with gpu. But with colab pro+, I can only have 12gb. I can not even train my model with this. I hope get refund if google can not change this situation.

**Comment by eefaan** [comment]
I also have similar problem. I am new to colab pro+. Since the time I registered, I can only access 12gb ram, even lesser than pro. Hoping google to solve this problem or let me get refund. My account is baka999.nine@gmail.com.

**Comment by Kobe1997** [comment]
The same thing happens to me!!!

**Comment by ady-yu** [comment]
I also have the same problem!!!!

**Comment by eefaan** [comment]
> I also have similar problem. I am new to colab pro+. Since the time I registered, I can only access 12gb ram, even lesser than pro. Hoping google to solve this problem or let me get refund. My account is [baka999.nine@gmail.com](mailto:baka999.nine@gmail.com).

![image](https://user-images.githubusercontent.com/26412699/141779947-5e44f6d7-8975-4c3b-b8cf-f847a41b68a7.png)
Here's the details of my resources.

**Comment by eefaan** [comment]
> **Describe the current behavior** A clear and concise explanation of what is currently happening. My colab pro+ can access only less than 13g ram and p100 gpu. This happens after I purchase a second colab pro+ account. Now both accounts meet this problem. I have no idea how this happens. If google does not allow this, I can stop using the second account. I want to know how long will this situation exists. My accounts are [15827510651zs@gmail.com](mailto:15827510651zs@gmail.com) and [senzhao950823@gmail.com](mailto:senzhao950823@gmail.com). **Describe the expected behavior** A clear and concise explanation of what you expected to happen. I hope at leat my first account [15827510651zs@gmail.com](mailto:15827510651zs@gmail.com) can be normal. I can stop using the second one. **What web browser you are using** (Chrome, Firefox, Safari, etc.)
> 
> **Additional context** Link to a minimal, public, self-contained notebook that reproduces this issue.
> 
> * Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
> * or Share Drive notebooks using the Share button then 'Get Shareable Link'.

This situation seams to have no relationship with two accounts. I am new to colab pro+ and also meet this problem. And even I got 24GB RAM when I contribute the colab pro only.

**Comment by Snnzhao** [comment]
@eefaan 
How can this happens? if so, why we upgrade from pro to pro+?

**Comment by eefaan** [comment]
@Snnzhao  I check the policy published by google, they promise to give more ram than pro.

**Comment by Snnzhao** [comment]
I hope google can give explanation.

**Comment by eefaan** [comment]
> I hope google can give explanation.

Yeah I also hope get some explanations from google about their false advertising

**Comment by Snnzhao** [comment]
I have use colab pro for over two years. When pro and pro+ released, I registered as soon as possible.
I have never disappointed like this before.

**Comment by Snnzhao** [comment]
My ddl is coming. I really need colab to do experiment. Please help me with this problem as soon as possible

**Comment by Snnzhao** [comment]
I find the high ram option not work yet.

**Comment by Snnzhao** [comment]
At  this   time, the   problem is  still  not  solved   and   no feedback.

**Comment by TAEYOUKIM** [comment]
I've been suffering from this issue all day

**Comment by Snnzhao** [comment]
I continue wondering when will this problem been solved

**Comment by Snnzhao** [comment]
Still waiting to be solved.

**Comment by Snnzhao** [comment]
My problem is currently solved, thanks

**Comment by ChungNPH** [comment]
@Snnzhao i have the same issue. Did Colab's supporter solve your problem and how did they solve it? :(

**Comment by bigstrawberrywakaka** [comment]
> i have the same issue...Do you solve it now? ㄒoㄒ
