### ISSUE TITLE
Just got pro+ and notebook keeps timing out during training

### ISSUE THREAD

**Issue by yogeshriyat** [googlecolab/colabtools#2429]
I am using a Chrome browser. 

I am training Xception, and the training keeps getting interrupted and the notebook disconnects. I actually terminate the notebook and restart before running training. I assume that resets the 24 hour clock. But, the notebook disconnects nowhere close to the 24 hour mark. Probably doesn't run for more than a few hours. Training models for longer numbers of epochs is the entire reason that I upgraded. 

If I reconnect the notebook during this 24 hour period, will it resume training? This isn't really specified anywhere as far as I know. If it is, can you point me to the docs that explain how it works in detail? I've read some very general FAQ type answers. But, it would be helpful for me to know how to get long runs to work.

**Comment by cperry-goog** [comment]
This is hard to debug over GitHub, submitting feedback in product will allow us to explore further.

If you reconnect the notebook, you will not resume any previous activity, as you're connecting to a fresh runtime. If you require consistency in runtimes, you might want to explore purchasing our Marketplace image: https://research.google.com/colaboratory/marketplace.html
