### ISSUE TITLE
Code folding issue -- code won't stay folded

### ISSUE THREAD

**Issue by thestephencasper** [googlecolab/colabtools#2430]
**Describe the current behavior**

I fold code, scroll away to another cell, scroll back, and the code is unfolded. This is a new issue. I have only experienced it starting recently. It was not an issue for me when I was last using colab intensively a couple months ago. 

**Describe the expected behavior**

Code should stay folded. 

**What web browser you are using**

Chrome

**Additional context**

--

**Comment by blois** [comment]
This is probably a regression from a recent performance optimization. Thanks for reporting.

**Comment by blois** [comment]
The fix should be rolling out shortly.
