### ISSUE TITLE
BUG: Potential Problem of the Subscription Handling - Pro+ is not working for almost 3 weeks 

### ISSUE THREAD

**Issue by rs3dtouch** [googlecolab/colabtools#2433]
I can not get any GPU access for my Pro+ account for almost 3 weeks within the month. Even a simple "!nvidia-smi" fails.

That feels like a massive bug. 

But the support team only sends out general messages or deletes my request from this Github forum.

I believe it could be happening because I cancelled my subscription in the beginning of the month (because I wanted to finish one project and not forget). So maybe the system thinks my Pro+ subscription is finished from that day (I lost access some days later), even when it should still work, since it is paid/active for the remaining time.

It is more than sad that there is not a single way to get a solution since the dev team simply ignores this fundamental problem.

My Pro+ runs out tomorrow and I'm very disappointed because it started out great in the first weeks of usage. 
(subscription total 2 months: 5 weeks working, 3 weeks broken)

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
