### ISSUE TITLE
Pro+ and T4 GPU

### ISSUE THREAD

**Issue by VladPedro** [googlecolab/colabtools#2434]
I bought a Pro+ subscription and got 12GB of RAM and a T4 graphics card.

I was expecting a more powerful graphics card, like the V100.

I use the Chrome browser.

I don't know where else to go for Google to hear about my problem. Can anyone help? Please.

**Comment by cperry-goog** [comment]
Pro+ users have higher priority GPU assignments, but do not have guaranteed chip types as we provide the service at scale. You can purchase a specific chip type via GCP Marketplace if you have chip type requirements: https://research.google.com/colaboratory/marketplace.html
