### ISSUE TITLE
GPU limit on Pro + 

### ISSUE THREAD

**Issue by soundobsessed** [googlecolab/colabtools#2435]
Hello,

On Google Colab Pro + recently have started to run out of GPU.  After 3 weeks of not using anything, after 1 day of usage yesterday, been unable to use any notebook.

Please help, all the notebooks require GPU.

Thank you

**Comment by rs3dtouch** [comment]
Same problem here with Pro+ and no feedback from the support in the last 3 weeks... 

I guess it must be a bug, but nobody takes care of it so far :-(

**Comment by VladPedro** [comment]
I have the same problem. google support is silent. they do not care about our problems.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
