### ISSUE TITLE
Enabled GPU usage but not using code isnt using GPU

### ISSUE THREAD

**Issue by replacementAI** [googlecolab/colabtools#2436]
**Describe the current behavior**
I have a notebook with XGBoost, and I set tree method to gpu hist and gpu id to 0, but its not using the GPU.

**Describe the expected behavior**
It should be using the GPU.

**What web browser you are using**
Chrome

**Additional context**
```XGBRegressor(tree_method='gpu_hist', gpu_id=0)```

**Comment by cperry-goog** [comment]
Please ensure you have a GPU runtime by running:
!nvidia-smi

If the code is not using the GPU provided, I'd ask the library authors.
