### ISSUE TITLE
My colab pro+ can access only less than 13g ram and p100 gpu.

### ISSUE THREAD

**Issue by eefaan** [googlecolab/colabtools#2437]
**Describe the current behavior**
> A clear and concise explanation of what is currently happening.

I have Colab Pro+ and am not able to get an instance with High RAM and GPU for three days.
![image](https://user-images.githubusercontent.com/26412699/142342732-ee346088-f88b-4272-bb0a-c3a876f4b047.png)

**Describe the expected behavior**
> A clear and concise explanation of what you expected to happen.

Plz check my account baka999.nine@gmail.com and let me work with Colab Pro+.

**What web browser you are using**
Chrome

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
