### ISSUE TITLE
I pay for two pro+ account, only one can get high ram and v100

### ISSUE THREAD

**Issue by Snnzhao** [googlecolab/colabtools#2438]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
I pay for two Pro+ account, but the second one senzhao950823@gmail.com is limited to 12g ram and p100.
If two account is not allowed, please let me known and I will never use that again.
Otherwise, please let my second account get the right resource.
Best Wishes.
**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
