### ISSUE TITLE
Notebook loading error

### ISSUE THREAD

**Issue by gaurtvin** [googlecolab/colabtools#2439]
**Describe the current behavior**
Every time when I link my GitHub to Colab it's successfully linked but when I tried to open my existing GitHub repository It always shows this error.

<img width="1332" alt="Screenshot 2021-11-20 at 8 44 45 AM" src="https://user-images.githubusercontent.com/78334545/142712672-5c3fc10e-f0a3-40d3-ab7f-17a674d06e65.png">

**Describe the expected behavior**
I wanted to open any existing GitHub repository in Colab without any error.

**What web browser you are using**
Chrome, Brave

**Comment by craigcitro** [comment]
That isn't a valid JSON file: https://github.com/gaurtvin/colab-notebooks/blob/main/test.ipynb

**Comment by gaurtvin** [comment]
Thanks for you're Instant help, Craig! Appreciated 🤩
