### ISSUE TITLE
Eye symbol/Input line

### ISSUE THREAD

**Issue by joh10891** [googlecolab/colabtools#244]
Starting today, I've started having issues with code and google drive FUSE (see "malformed auth code" issue). Also, peculiarly, I've noticed this eye/input prompt after running virtually every line of code. Very odd, don't know if it's at all related to the FUSE issues. 

<img width="305" alt="eye_symbol" src="https://user-images.githubusercontent.com/29440741/44360569-dcae9c00-a480-11e8-8f52-dd2f8e4d2bba.png">

**Comment by colaboratory-team** [comment]
These are indeed related. We're rolling back this change due to the FUSE authentication issues you describe.

The main issue tracking this is
https://github.com/googlecolab/colabtools/issues/244
