### ISSUE TITLE
Google colab pro plus only offering 1 session of 12Gb RAM

### ISSUE THREAD

**Issue by smithee77** [googlecolab/colabtools#2441]
I don't know how many times have reported this. The service offered is not good: never got an A100, very few 50Gb RAM sessions, and today I just can get 1 NOTEBOOK SESSION OF 12Gb RAM. Please solved this because I'm not the only one with this issues.

**Comment by cbologa** [comment]
Same here. Upgraded from Pro to Pro+ only to be able to access more than 27 GB RAM. After paying $50 now I get only 12 GB. It is really frustrating.

**Comment by Dolzodmaa** [comment]
Same here.

**Comment by optiprime8** [comment]
Yes, me too. On pro+ I only have 12.69GB RAM.

**Comment by JonahR1** [comment]
Same here.

**Comment by hannesfelix** [comment]
I have 50 GB on paper (top right corner resources) but when opening a file of 17 GB it always crashes at 12 GB. So this is actually something that is done systematically and not resolved? Is there even anyone working on this?

**Comment by smithee77** [comment]
I surrender. Just cancelled my Pro + . Leave this open hoping to be helpful

**Comment by CharonWangg** [comment]
Same, really disppointing

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback

**Comment by optiprime8** [comment]
> We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback

Wow! I did submit feedback, was as much help as your reply.

**Comment by CharonWangg** [comment]
My account is charonwangg@gmail.com

**Comment by CharonWangg** [comment]
> We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback

My account is charonwangg@gmail.com

**Comment by hannesfelix** [comment]
Way to go! Just close the issue! That will help for sure!!! What a crazy attitude. 

My email feedback had the same effect. Basically, I am told they never promised anything when I paid them 50 USD.

Terrible service. I will definitely not recommend this to my students.
