### ISSUE TITLE
Colab Pro Plus much Slower than Pro

### ISSUE THREAD

**Issue by mantisnft** [googlecolab/colabtools#2443]
I upgraded from Colab Pro to Pro + yesterday, and so far the only change is everything is much slower. What once took 10 minutes now takes an hour. This means I also get disconnected more. Is there a reason for this? Do I just need to downgrade back to Pro? 

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
