### ISSUE TITLE
GPU driver version mismatch on R runtime

### ISSUE THREAD

**Issue by skypc785308** [googlecolab/colabtools#2445]
**Describe the current behavior**
I found the problem that can not use GPU accelerator on R runtime. I try `system2("nvidia-smi", stdout = TRUE)` on colab, and it show that `'Failed to initialize NVML: Driver/library version mismatch'`. Maybe someone set the GPU driver version of R runtime to a workable version, thanks. 

**Describe the expected behavior**
I can use GPU on R runtime

**What web browser you are using**
Chrome 96.0.4664.55 

**Additional context**
https://colab.research.google.com/drive/1GqbdBaMpcEXmo2IN52bPOadKJiTOYszC?usp=sharing

**Comment by craigcitro** [comment]
R is fiddling with `LD_LIBRARY_PATH` at startup, which is confusing `nvidia-smi`.

You can fix this with `Sys.setenv(LD_LIBRARY_PATH='/usr/lib64-nvidia:/usr/lib/R/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server')`, but I'm not sure why R is fiddling with the path in the first place, or if there's a better way to fix it.
