### ISSUE TITLE
Colab Pro Plus(+) only providing 12 GB RAM

### ISSUE THREAD

**Issue by upasaNITP** [googlecolab/colabtools#2446]
I upgraded from Colab Pro to Pro +. But seems like both are use less for me.  Ram size is same for non-pro, pro and pro+(12.69 GB). What's the point of upgrading and wasting our money.

**Comment by smithee77** [comment]
same here :(

**Comment by JonahR1** [comment]
Same here :/

**Comment by hannesfelix** [comment]
Same here... in fact I thought something was wrong on my side and I first signed up to Colab Pro and then switched to Colab Pro +. Can I get back to Colab Pro if you resolve this?

**Comment by Dolzodmaa** [comment]
Same here

**Comment by smithee77** [comment]
I surrender. Just cancelled my Pro +

**Comment by brueyq** [comment]
Same here

**Comment by hannesfelix** [comment]
I also cancelled my subscription now. I get completely generic emails at the helpdesk as well. Seems like fixing this is very low priority.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
