### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

### ISSUE THREAD

**Issue by SUPERSHOPxyz** [googlecolab/colabtools#2449]
I have Colab Pro+ and have been running some ML Training. I have been resuming the same code for a couple weeks now, and all of a sudden am getting this error like there are no GPUs allcated. Please advise, thanks

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
