### ISSUE TITLE
Providing Non-GPU Notebook with RAM 52 GB and GPU Notebook with RAM size 12 GB.

### ISSUE THREAD

**Issue by upasaNITP** [googlecolab/colabtools#2454]
I am a Colab pro+ member and I am getting  non-GPU notebook with RAM 52 GB and GPU Notebook with RAM size 12 GB. Because of the low RAM my session getting crushed repeatedly. I need a notebook with GPU accessibility and RAM size more than 25 GB.

**Comment by JonahR1** [comment]
Same.

**Comment by CharonWangg** [comment]
Same

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
