### ISSUE TITLE
Can't use High-Ram on Colan Pro

### ISSUE THREAD

**Issue by asafcloud-romarketinggroup** [googlecolab/colabtools#2456]
**Describe the current behavior**
I upgraded to Colab Pro+
Changed runtime type to High Ram
But still it doesn't seem to increase the machine RAM
```
from psutil import virtual_memory
ram_gb = virtual_memory().total / 1e9
print('Your runtime has {:.1f} gigabytes of available RAM\n'.format(ram_gb))

if ram_gb < 20:
  print('Not using a high-RAM runtime')
else:
  print('You are using a high-RAM runtime!')
```

**Describe the expected behavior**
High-Ram activated

**What web browser you are using**
Chrome

My colab-
https://colab.research.google.com/drive/1AFy5uQFOj0treM1uJzA_p3el3NeR_jId#scrollTo=aamGsstrtoWS

**Comment by JonahR1** [comment]
Same here.

**Comment by teeppiphat** [comment]
Same for me.

**Comment by khaling** [comment]
Same here.

**Comment by CharonWangg** [comment]
Same

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
