### ISSUE TITLE
The Colab disconnects once per minute

### ISSUE THREAD

**Issue by saintthor** [googlecolab/colabtools#2458]
I have to click the Reconnect button frequently.  Otherwise the env will reset in teen minutes.

The network is fine.

**Comment by saintthor** [comment]
messages from the browser console:


kernel connection error: CustomError: 代码执行程序崩溃在：(crush at)
 C7.prototype.resume/e<@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:5027:484
C7.prototype.resume@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:5026:320
k.connect/</<@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:5156:239
external_polymer_binary_l10n__zh_cn.js:5113:166

无法连接到代码执行程序。( can not connect to the executor )
POSThttps://colab.research.google.com/analytics?authuser=0

Recording uncaught error: CustomError CustomError: SocketIO error: /session: xhr poll error: 0 - TransportError external_polymer_binary_l10n__zh_cn.js:1566:200

Uncaught 
Object { stack: "bb@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:64:498\ntJ@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:2101:772\nk.connect/</<@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:5423:172\nc.prototype.emit@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62:84\nc.prototype.emit@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:148:506\nc.prototype.emitAll@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:68:365\nc.prototype.onerror@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:74:141\nn.exports/<@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:155:120\nc.prototype.emit@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62:84\nd.prototype.onError@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:96:333\nd.prototype.setTransport/<@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:87:121\nc.prototype.emit@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62:84\nc.prototype.onError@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:113:416\nf.prototype.doPoll/<@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103:198\nc.prototype.emit@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62:84\nh.prototype.onError@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:106:353\nh.prototype.create/b.onreadystatechange/<@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105:497\nsetTimeout handler*h.prototype.create/b.onreadystatechange@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105:483\nEventHandlerNonNull*h.prototype.create@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105:164\nh@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:101:196\nf.prototype.request@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:102:337\nf.prototype.doPoll@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103:116\nc.prototype.poll@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:110:9\nc.prototype.onData@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:110:361\nf.prototype.doPoll/<@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103:159\nc.prototype.emit@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62:84\nh.prototype.onData@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:106:283\nh.prototype.onLoad@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:107:365\nh.prototype.create/b.onreadystatechange@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105:459\nEventHandlerNonNull*h.prototype.create@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105:164\nh@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:101:196\nf.prototype.request@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:102:337\nf.prototype.doPoll@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103:116\nc.prototype.poll@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:110:9\nc.prototype.onData@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:110:361\nf.prototype.doPoll/<@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103:159\nc.prototype.emit@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62:84\nh.prototype.onData@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:106:283\nh.prototype.onLoad@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:107:365\nh.prototype.create/b.onreadystatechange@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105:459\nEventHandlerNonNull*h.prototype.create@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105:164\nh@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:101:196\nf.prototype.request@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:102:337\nf.prototype.doPoll@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103:116\nc.prototype.poll@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:110:9\nc.prototype.onData@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:110:361\nf.prototype.doPoll/<@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103:159\nc.prototype.emit@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62:84\n", message: "SocketIO error: /session: xhr poll error: 0 - TransportError" }
external_polymer_binary_l10n__zh_cn.js:177:526
    Pe https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:177
    (异步：setTimeout handler)
    Pe https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:177
    receivedError https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:4047
    connect https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:5423
    emit https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62
    emit https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:148
    emitAll https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:68
    onerror https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:74
    exports https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:155
    emit https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62
    onError https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:96
    setTransport https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:87
    emit https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62
    onError https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:113
    doPoll https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103
    emit https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62
    onError https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:106
    onreadystatechange https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105
    (异步：setTimeout handler)
    onreadystatechange https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105
    (异步：EventHandlerNonNull)
    create https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105
    h https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:101
    request https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:102
    doPoll https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103
    poll https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:110
    onData https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:110
    doPoll https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103
    emit https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62
    onData https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:106
    onLoad https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:107
    onreadystatechange https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105
    (异步：EventHandlerNonNull)
    create https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105
    h https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:101
    request https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:102
    doPoll https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103
    poll https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:110
    onData https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:110
    doPoll https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103
    emit https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62
    onData https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:106
    onLoad https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:107
    onreadystatechange https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105
    (异步：EventHandlerNonNull)
    create https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105
    h https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:101
    request https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:102
    doPoll https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103
    poll https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:110
    onData https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:110
    doPoll https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103
    emit https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62

Uncaught (in promise) 
Object { stack: "bb@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:64:498\nB7@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:5025:1932\nC7.prototype.resume/e</<@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:5028:23\nyi@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:240:374\nk.dispatchEvent@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:238:483\nk.stop@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:5156:462\nn8/<@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:5145:255\nyi@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:240:374\nk.dispatchEvent@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:238:483\nj8/<@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:5136:42\nyi@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:240:374\nk.dispatchEvent@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:238:483\nb2.prototype.closed@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:4047:561\nl@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:5421:444\nk.connect/</<@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:5422:185\nc.prototype.emit@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62:84\nc.prototype.emit@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:148:506\nc.prototype.onclose@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:150:324\nn.exports/<@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:155:120\nc.prototype.emit@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62:84\nc.prototype.onclose@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:76:495\nn.exports/<@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:155:120\nc.prototype.emit@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62:84\nd.prototype.onClose@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:97:222\nd.prototype.onError@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:96:354\nd.prototype.setTransport/<@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:87:121\nc.prototype.emit@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62:84\nc.prototype.onError@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:113:416\nf.prototype.doPoll/<@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103:198\nc.prototype.emit@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62:84\nh.prototype.onError@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:106:353\nh.prototype.create/b.onreadystatechange/<@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105:497\nsetTimeout handler*h.prototype.create/b.onreadystatechange@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105:483\nEventHandlerNonNull*h.prototype.create@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105:164\nh@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:101:196\nf.prototype.request@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:102:337\nf.prototype.doPoll@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103:116\nc.prototype.poll@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:110:9\nc.prototype.onData@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:110:361\nf.prototype.doPoll/<@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103:159\nc.prototype.emit@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62:84\nh.prototype.onData@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:106:283\nh.prototype.onLoad@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:107:365\nh.prototype.create/b.onreadystatechange@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105:459\nEventHandlerNonNull*h.prototype.create@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105:164\nh@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:101:196\nf.prototype.request@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:102:337\nf.prototype.doPoll@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103:116\nc.prototype.poll@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:110:9\nc.prototype.onData@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:110:361\nf.prototype.doPoll/<@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103:159\nc.prototype.emit@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62:84\nh.prototype.onData@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:106:283\nh.prototype.onLoad@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:107:365\nh.prototype.create/b.onreadystatechange@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105:459\nEventHandlerNonNull*h.prototype.create@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:105:164\nh@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:101:196\nf.prototype.request@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:102:337\nf.prototype.doPoll@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103:116\nc.prototype.poll@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:110:9\nc.prototype.onData@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:110:361\nf.prototype.doPoll/<@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:103:159\nc.prototype.emit@https://colab.research.google.com/v2/external/external.js?vrz=colab-20211122-060049-RC00_411523091:62:84\n", message: "代码执行程序崩溃在：\n C7.prototype.resume/e<@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:5027:484\nC7.prototype.resume@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:5026:320\nk.connect/</<@https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20211122-060049-RC00_411523091:5156:239\n" }

**Comment by cperry-goog** [comment]
It'll be easier for us to troubleshoot if you can submit feedback within Colab at Help > Send feedback and mention this GitHub issue.
