### ISSUE TITLE
Runtime disconnects if you are not constantly on your PC. Useless tool for data science, as most of the time you're just waiting for training to finish, and then because you stepped out for lunch, 4 hours of training are lost. No point to use the tool that's not designed for the purpose it claims it serves.

### ISSUE THREAD

**Issue by Juliana-Yakimchuk** [googlecolab/colabtools#2460]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
Please submit feedback within Colab at Help > Send feedback and mention this GitHub issue. Colab should maintain connection as long as training runs.
