### ISSUE TITLE
Colab freezes when left unatended for minutes.

### ISSUE THREAD

**Issue by Ilias-Paralikas** [googlecolab/colabtools#2461]
I am training using optuna to train a model. 
As you can see by the output times every trial so far takes less than 30 seconds, but it has been like this for 10 minutes. 
This only happens  when I leave it untended for minutes . If I stay on the page and just scroll up and down it trains no problem.
Even when I come back the issue is not fixed, so I have to restart runtime all over again.
Obviously this makes the whole thing useless as I cant stay there for one or two hours to watch over it. 

[I 2021-11-27  09:05:47,272] A new study created in memory with name: no-name-d14e3d8d-0b44-4e67-b290-a9fd866fee26
[I 2021-11-27 09:05:48,132] Trial 0 finished with values: ...
[I 2021-11-27 09:06:12,839] Trial 1 finished with values: ...
[I 2021-11-27 09:06:13,933] Trial 2 finished with values: ...
[I 2021-11-27 09:06:29,855] Trial 3 finished with values: ...
[I 2021-11-27 09:06:29,917] Trial 4 finished with values:...

**Comment by cperry-goog** [comment]
Could you try sharing a minimal reproducible notebook?

**Comment by jasonwun** [comment]
I have the same issue. While training unattended, the cell seems freeze is not even running internally. I setup backup every hour onto Google Drive but it doesn't trigger as well.
