### ISSUE TITLE
DownloadError when loading 'glue/sst2' with tfds

### ISSUE THREAD

**Issue by sacpis** [googlecolab/colabtools#2464]
**Current behavior**
I am trying to load dataset 'glue/sst2' usig tfds load function. On running the following cell
https://colab.research.google.com/github/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l10c02_nlp_multiple_models_for_predicting_sentiment.ipynb#scrollTo=nCOtiRJZbxCH&line=6&uniqifier=1

I get the following error

DownloadError                             Traceback (most recent call last)
<ipython-input-24-8e5e19d9a773> in <module>()
      1 # Get the dataset.
      2 # It has 70000 items, so might take a while to download
----> 3 dataset, info = tfds.load('glue/sst2', with_info=True)
      4 print(info.features)
      5 print(info.features["label"].num_classes)

21 frames
/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/download/downloader.py in _assert_status(response)
    257   if response.status_code != 200:
    258     raise DownloadError('Failed to get url {}. HTTP code: {}.'.format(
--> 259         response.url, response.status_code))

DownloadError: Failed to get url https://firebasestorage.googleapis.com/v0/b/mtl-sentence-representations.appspot.com/o/data%2FSST-2.zip?alt=media&token=aabc5f6b-e466-44a2-b9b4-cf6337f84ac8. HTTP code: 403.

**Expected behavior**
Expected behavior is that the dataset 'glue/sst2' gets loaded

**Web browser**
Chrome

**Comment by craigcitro** [comment]
I'd try asking upstream (or just retrying).
