### ISSUE TITLE
Colab Scrolling issue

### ISSUE THREAD

**Issue by VasudevTA** [googlecolab/colabtools#2465]
**Describe the current behavior**
While scrolling  through a colab sheet, the focus jumps to the previous or next code block. 

**Describe the expected behavior**
Smooth scrolling, as it was before

**What web browser you are using**
Chrome

**Additional context**
Facing this issue across accounts, so I think this is a universal issue

**Comment by Germandev55** [comment]
same problem here: https://github.com/googlecolab/colabtools/issues/2455
