### ISSUE TITLE
Colab Pro+

### ISSUE THREAD

**Issue by masawdah** [googlecolab/colabtools#2466]
I have subscribed to colab pro+ to get access to higher GPU, but unfortunately I don't have access to GPU/TPU for almost 1 week. I don't know if this is normal.

**Comment by rs3dtouch** [comment]
I did not get access for more than 14 day with Pro+. I tried to get support, but no answers... I also believe it is a bug, but in the end my post was deleted instead of getting an answer...

**Comment by masawdah** [comment]
It's really annoying and no support at all from google side, the funniest thing that I'm asking my friends with free account to run codes for me.

**Comment by CharonWangg** [comment]
Same, and recently my high ram runtime only gave me 12.69gb ram^

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
