### ISSUE TITLE
Failure to autosave document

### ISSUE THREAD

**Issue by laraconda** [googlecolab/colabtools#2469]
Autosave fails allegedly because another window has the same document open, yet I have no other windows running it.
Once this happens it continues to happen and last time the bug manifested, I lost a week of work. What I have to do is restart my browser (maybe closing my window would work but I have not tried that).
This happens constantly.
Firefox 94.0.2 (64-bit)

**Comment by craigcitro** [comment]
If you see that warning, another option is to download the file (`File` -> `Download .ipynb`), refresh the page, and then upload. (This is awkward, but better than losing work.)

The next time this happens, can you file feedback (`Help` -> `Send feedback`) and reference this github issue?
