### ISSUE TITLE
Error loading the application...

### ISSUE THREAD

**Issue by Vifray** [googlecolab/colabtools#2471]
When opening a new notebook, everything works, but I can't open an existing one on disk

Error loading https://apis.google.com/js/client.js
Error: Error loading https://apis.google.com/js/client.js
    at HTMLScriptElement.h.onerror (https://colab.research.google.com/v2/external/gapi_loader.js:20:280)

Help me!)

**Comment by blois** [comment]
This sounds like https://github.com/googlecolab/colabtools/issues/981#issuecomment-660342615
