### ISSUE TITLE
COLAB PRO + got almost a week of least ram, now it even doesn't provide GPU^

### ISSUE THREAD

**Issue by CharonWangg** [googlecolab/colabtools#2474]
**Describe the current behavior**
More than a week, my high-ram runtime only gave me 12.69GB and P100 GPU. Now it even didn't provide GPU runtime^^ and my another free account works pretty well!
account: charonwangg@Gmail.com 
DISAPPOINTING

**Describe the expected behavior**

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by CharonWangg** [comment]
it still only provide non-GPU runtime till now^

**Comment by CharonWangg** [comment]
still no GPU runtime^

**Comment by CharonWangg** [comment]
As a pro + user, I can not use GPU in more than half a week

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
