### ISSUE TITLE
seanborn version update

### ISSUE THREAD

**Issue by YenYuHsuan** [googlecolab/colabtools#248]
here is the error i got:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-6-d39716b26dc1> in <module>()
      3 planets = sns.load_dataset('planets')
      4 cmap = sns.cubehelix_palette(rot = -.2, as_cmap = True)
----> 5 ax = sns.scatterplot(x = 'distance', y = 'orbital_period', hue = 'year',size ='mass',palette = cmap,sizes = (10,200),data = planets)

AttributeError: module 'seaborn' has no attribute 'scatterplot'
```
i know the error is because of the seaborn version (i read from [here](https://stackoverflow.com/questions/51402579/module-seaborn-has-no-attribute-any-graph))
but i can't update seaborn on CoLab, even i tried `!pip install -U seaborn` 😭

**Comment by craigcitro** [comment]
The fastest route here is to `!pip install -U seaborn` -- the reason your attempt didn't work is because you'd already loaded the library, and python imports are idempotent.

If you `!pip install` and restart the runtime, you'll pick up the new version.

**Comment by sadakosa** [comment]
I tried it! just add `!pip install -U seaborn` in a code cell and `restart and run all...` your model :) atb!

**Comment by YenYuHsuan** [comment]
@craigcitro Thanks! that works for me ^__^

**Comment by Kishan-Sahu** [comment]
pip install -U seaborn

**Comment by Constantino-Carreto-Romero** [comment]
I was really helpful, thanks!
