### ISSUE TITLE
With Runtime shape set to "Max-Ram" i'm only getting 12.69gb of ram.

### ISSUE THREAD

**Issue by stanakanats** [googlecolab/colabtools#2480]
With Runtime shape set to "Max-Ram" I'm only getting 12.69GB of ram.

I've done the "factory reset runtime" tons of times. I've tried connecting to a different runtime host several times. I keep getting the "Tesla P100" but with only 12.69GB. I bought the Pro+ membership yesterday.

**Comment by aygong** [comment]
Same here. :(

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
