### ISSUE TITLE
Is there a way to detect the Colab theme using python?

### ISSUE THREAD

**Issue by kaushikb11** [googlecolab/colabtools#2485]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

We wish to detect the theme of Colab and based on that, we want to update the colors of custom progress bar using Rich.
I came across https://github.com/googlecolab/colabtools/issues/1214, but I only wish to detect the theme, not run anything on the html side.

Would appreciate your help with this! Thank you

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by blois** [comment]
You should be able to use:

```python
from google.colab import output
is_dark = output.eval_js('document.documentElement.matches("[theme=dark]")')
```
