### ISSUE TITLE
Upload stuck

### ISSUE THREAD

**Issue by piyush4669** [googlecolab/colabtools#249]
Cant upload files.

**Comment by blois** [comment]
Is this from the new file upload UI in the sidebar?

Browser details? Any error messages in the browser developer tools?

**Comment by piyush4669** [comment]
Yes its in the new UI

Tried in both chrome and Firefox
Latest versions


Error code is
[Image]
________________________________

**Comment by blois** [comment]
Screenshot did not come through.

**Comment by fulldecent** [comment]
Here's my screenshot...

![untitled5 copy 2](https://user-images.githubusercontent.com/382183/50494648-9353f780-09f2-11e9-9601-ffb2240c656b.gif)

**Comment by buttercookie42** [comment]
Same problem here, using the sidebar file upload UI in Firefox Nightly. The upload just gets stuck and the progress spinner rotates endlessly.
In the console, I see the following error message appear:
> TypeError: c.progressElement_.setValue is not a function
> external_polymer_binary.js:3041:179

**Comment by colaboratory-team** [comment]
We aren't able to reproduce this issue with the current version of Firefox. (65.0)
If this issue persists, please share your precise Firefox version. Keep in mind that extensions are a common cause of errors like this, so please do verify that the issue persists when extensions are disabled.
