### ISSUE TITLE
Only connected to GPU with 12.69GB after subscribing to Colab Pro+

### ISSUE THREAD

**Issue by aygong** [googlecolab/colabtools#2491]
Hi, I subscribed to Colab Pro+ yesterday. Now, I only have access to GPU with 12.69GB today. The Colab plan says that “Significantly more memory than ever before.” However, the actual memory of Colab Pro+ is just the same as that of Colab Free.

Hope this bug can be fixed.

**Comment by aygong** [comment]
My account: gongaoyu@gmail.com

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
