### ISSUE TITLE
My colab pro+ can access only less than 13g ram and p100 gpu. 

### ISSUE THREAD

**Issue by 1one5ome** [googlecolab/colabtools#2494]
**Describe the current behavior**
I am having the exact same problem described in #2428. My colab pro+ can access only less than 13g ram and p100 GPU. My account is gaotianzheng97@gmail.com.

**Describe the expected behavior**
My subscription can work normally.

**What web browser you are using**
Chrome

**Comment by inzombakura** [comment]
I currently have the same issue while working on a class project, my account is groupprojectgan@gmail.com

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback

**Comment by bigstrawberrywakaka** [comment]
I also have the same issue, after updating from pro to pro plus, it always gives me a p100 as pro, I feel cheated by Google...my account is straberrywakaka@gmail.com
