### ISSUE TITLE
Scrolling bug

### ISSUE THREAD

**Issue by dserero** [googlecolab/colabtools#2495]
https://user-images.githubusercontent.com/26485777/145613019-502cec7e-a55b-4d24-8218-8a503f97adfb.mp4

As you can see I cannot access the top of my code because the display keeps jumping around.  I am on windows 10. 
Seems related to https://github.com/googlecolab/colabtools/issues/2455 but unsure. 

Please help

**Comment by blois** [comment]
This should be resolved now.
