### ISSUE TITLE
ImportError: cannot import name 'PROTOCOL_TLS' from 'urllib3.util.ssl_' 

### ISSUE THREAD

**Issue by EchoFei333** [googlecolab/colabtools#2499]
When my code was not modified, it failed when it was run again today, and the error was displayed as:ImportError: cannot import name 'PROTOCOL_TLS' from 'urllib3.util.ssl_' (/usr/local/lib/python3.7/dist-packages/urllib3/util/ssl_.py), I can't find any reason, I look forward to your answer as soon as possible！

**Comment by craigcitro** [comment]
It's hard to say more without a minimal, public repro notebook.

**Comment by TheEliteAnalyst** [comment]
@EchoFei333 Had the same issue and was solver by upgrading SageMaker
`pip install --upgrade sagemaker`
Hope that helps!

**Comment by EchoFei333** [comment]
> @EchoFei333有同样的问题，通过升级 SageMaker 解决了 `pip install --upgrade sagemaker` 希望有帮助！

In fact, I didn't make any changes. After refreshing or logging in again, my code returned to normal again. You can try this method.

**Comment by EchoFei333** [comment]
> 如果没有一个最小的公共复制笔记本，很难说更多。

Thank you for your reply. In fact, after refreshing or logging in again, my code is back to normal again.

**Comment by wangshuo999** [comment]
pip install --upgrade sagemaker
+1 Solve the problem！
