### ISSUE TITLE
changing language

### ISSUE THREAD

**Issue by johnnytorres** [googlecolab/colabtools#25]
Currently, i have to change language to english everytime I open a new notebook

**Comment by eggie5** [comment]
How do you change the language? Mine is stuck in korean...

**Comment by blois** [comment]
The default language should be configured in your Chrome settings under chrome://settings/?search=language.

Alternatively to specify English: https://colab.research.google.com/notebook?hl=en

**Comment by johnnytorres** [comment]
thanks that did work! , @eggie5 it should be in the help menu, but after the step recommended by @blois I couldn't find it.
