### ISSUE TITLE
saving the current notebook and missing documentation for _message request_type

### ISSUE THREAD

**Issue by eyaler** [googlecolab/colabtools#2501]
i am using:
```
import google.colab
import json
notebook = colab._message.blocking_request('get_ipynb')
if notebook:
    with open('notebook.ipynb', 'w', encoding='utf8') as f:
        json.dump(notebook, f)
```
to save a copy of the current notebook programmatically. would be useful to get a documentation of the possible request types.

**Comment by craigcitro** [comment]
The `_message` API is private, so not intended for general use; we aren't planning to document it, but even if we did, I'd strongly discourage you from depending on it (since it's subject to change without notice).

**Comment by ivanbelenky** [comment]
Mane, come on, make it public, remove that trailing `_`. It would not be the first time engineers make use of unreliable stuff for hacky one time scripts, or volatile architectures.

**Comment by mklilley** [comment]
Hello. From what I can tell, this is the only way of getting access to the current notebook's underlying metadata. It seems like a sensible thing to expose as a public API. Are there any reasons why this would be problematic? Thanks.
