### ISSUE TITLE
Open File Types Supported by Google Drive in from Colab UI

### ISSUE THREAD

**Issue by sirinath** [googlecolab/colabtools#2503]
When exploring data files it is helpful if they can be quickly previewed or open online. So please add a view / open option. Currently there the option is to download and then view locally, which is cumbersome.

**Comment by Btibert3** [comment]
You can double-click on files in File browser and it should open up in a new tab.  For example, you can view CSV files in a grid, or open markdown files.  For the latter (markdown, text), you can also edit and save those files.

**Comment by blois** [comment]
You can also use:

```python
from google.colab import files
files.view('<path to file>')
```
