### ISSUE TITLE
Restart maintaining state

### ISSUE THREAD

**Issue by sirinath** [googlecolab/colabtools#2507]
If any of the package backing stateful objects did not get updated in downloading the notebook can maintain state.

Say I have a Pandas DF in a cell. I say upgrade Pandas but the requires are satisfied hence there is no upgrade. So:
1. I don't need to restart the kernel but
2. if I do, previous state can be reloaded.

Restart with state also would be an additional option.

If the restart is required due to internally used packages make the restart automatic and transparent to the user.

**Comment by craigcitro** [comment]
This is beyond the scope of something colab can really do: modifying the way python works is out of scope for us.
