### ISSUE TITLE
#!pip install tensorrec crashing run time

### ISSUE THREAD

**Issue by pragyanaischool** [googlecolab/colabtools#2512]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by craigcitro** [comment]
The root cause here is an incompatibility between tensorrec's `six` version requirement and TensorFlow's.

Looking at the repo, it looks like `tensorrec` only support TF 1.x; if you first run `%tensorflow_version 1.x` and then install, you should have no trouble.
