### ISSUE TITLE
Can't use GPU Runtime while "backend running" is on

### ISSUE THREAD

**Issue by CharonWangg** [googlecolab/colabtools#2513]
**Describe the current behavior**
Every time when I turn the "backend running", I can not use GPU runtime. It said that my GPU runtime reaches limitation. Even if I turn off "backend running", I can only use GPU runtime for one night and it reaches limitation.
And I am a Pro + user.

My account is charonwangg@Gmail.com

**Describe the expected behavior**
Fix this

**What web browser you are using**
Chrome

**Comment by boscoybarra** [comment]
i'm experimenting the same issue. Also with Chrome. With TPU seems to work but takes much more time to run.

**Comment by cperry-goog** [comment]
Enabling "background execution" requires you to have enough quota upfront to access a long-running runtime. This looks WAI.

**Comment by boscoybarra** [comment]
> 

can you please share with us how this can be activated? thanks
