### ISSUE TITLE
IndexError: list index out of range when using ColabFold: AlphaFold2 with MMseqs2

### ISSUE THREAD

**Issue by Neel6164** [googlecolab/colabtools#2514]
When I try to use the structure prediction tool for a 12_mer protein, I get the list index error in the Display 3D structure section of the notebook. I was expecting the notebook to run just fine, just like it did when I tried the same for smaller oligomers (dimers/trimers etc.). I am using Google Chrome. Screenshot of error message is attached.
![Screenshot 2021-12-16 at 10 22 31 AM](https://user-images.githubusercontent.com/79642195/146355896-39f2ed84-8614-4cd7-9271-f6746ffb7945.png)

**Comment by craigcitro** [comment]
I'd try asking on the AlphaFold repo (https://github.com/deepmind/alphafold), or wherever you ran into the notebook you're using.
