### ISSUE TITLE
Colab does not take into account changes in modified py files

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [googlecolab/colabtools#2517]
**Describe the current behavior**
I git cloned a repo. I ran a cell and its output pointed to an error in source code. So I made changes to this source code directly in Colab by double clinking on a py file on the left pane. I saved (ctrl s) the changes on the py file. 

When I launched the cell again, the same error occured at the same line (which I commented to see if it was behaving as expected) : 
```/content/Voice-Cloning-App/training/utils.py in validate_dataset(filepaths_and_text, dataset_directory, symbols)
    107             invalid_characters.update(invalid_characters_for_row)
    108 
--> 109     #assert not missing_files, f"Missing files: {(',').join(missing_files)}"
    110     assert (
    111         not invalid_characters
```

As you can see the error is still shown on the same line although it has been commented.
Consequently it looks like Colab is showing some code but executing another version of it (ie the original).

**Describe the expected behavior**
When I make changes to code through the integrated editor, Colab should run this new code.

**What web browser you are using**
Firefox 94.0.1 64 bits

**Additional context**
Run this [notebook](https://colab.research.google.com/drive/1YbB_gA2_Rspmm1TDyEDueNXittmtWu1c?usp=sharing), make changes to source code via the internal editor, run the last cell again, the error will still point to the same line.

**Comment by craigcitro** [comment]
This isn't a colab-specific thing, this is how python works: changes to the python source on disk aren't reflected until you either (1) restart the python process or (2) reload the module. The latter is delicate (eg you may need to reload many modules, or recreate objects, or a number of other gotchas).

If you restart your kernel process (ctrl-m . or `Runtime` -> `Restart runtime`) after making your changes, you should be good to go.

**Comment by Ca-ressemble-a-du-fake** [comment]
Thanks a lot @craigcitro , what a headache you stopped for me! I was thinking I was launching bash commands (because I used to do it) but it as actually Python! Wow it took me some time to understand! Anyway thank you!
