### ISSUE TITLE
Colab can't save changes to GitHub public and private reports

### ISSUE THREAD

**Issue by atkuzmanov** [googlecolab/colabtools#2518]
**Describe the current behavior**
# Colab can't save changes to GitHub public and private reports

Hi Folks,

A bit of a mystery here. I need this to work urgently, so any help I will greatly appreciate.

Nothing has worked so far... I am at a loss and I am desperately looking for help.

*Colab cannot save to any of my GitHub repos regardless whether they are `public` or private.*

The error I get:
**"You do not have permission to save this notebook. To keep your changes, make a copy of the notebook."**

State:

- Both my Google and GitHub accounts are standard accounts.

- I have approved and authorized Colab with GitHub access.

- I have "Access private repositories and organisations" ticked.

- I have Adblock Plus disabled for the Colab site.

- I have all permissions to the site set to either `Ask(default)` or `Allow(default)` and I even changed `Pop-ups and redirects` to `Allow`.

- The browser I use is Chrome, but I have also tried it in Firefox and on a different computer - I still get the same error.

- I have tried deleting all cookies and site data for both Colab and GitHub.

- I have tried revoking GitHub access from Colab and requesting it again.

Workflows to reproduce bug:

- `File` -> `Open notebook` -> `GitHub tab` -> `select a PUBLIC repository` -> `Try to save` -> `Get error: "You do not have permission to save this notebook. To keep your changes, make a copy of the notebook."`

- `File` -> `Open notebook` -> `GitHub tab` -> `select a PRIVATE repository` -> `Try to save` -> `Get error: "You do not have permission to save this notebook. To keep your changes, make a copy of the notebook."`

I tried creating a new notebook in Colab and saving it to GitHub - this works, it commits it to the repo, however when I open the newly notebook created book in Colab I get the same error "You do not have permission to save this notebook. To keep your changes, make a copy of the notebook.".

Here are more details and things I have tried to troubleshoot:

- I was a member of an `organization` in GitHub, of which I do not have rights to modify the organization's settings. I thought this might cause problems, so despite me not wanting to do it, I left the organisation and it got removed my account. I gave it more than 24h in case it needs to converge but this did not fix the issue, I still get the same error.

- I had applied and received approval for `GitHub sponsorship`, but had not set it up, so I thought it might be causing issues. I revoked it and my GitHub sponsorship account got closed. 

- I used `Chrome Developer Tools` to try and get some more info:

    - The only request, when I save, which gets made in the `Network` tab is this one:
    ```sh
    curl 'https://colab.research.google.com/analytics?authuser=0' \
  -H 'authority: colab.research.google.com' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"' \
  -H 'dnt: 1' \
  -H 'content-type: application/x-www-form-urlencoded;charset=UTF-8' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36' \
  -H 'x-colab-experiment: 20730102,20730120' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'accept: */*' \
  -H 'origin: https://colab.research.google.com' \
  -H 'x-client-data: CIm2yQEIprbJAQjEtskBCKmdygEIhIbLAQjq8ssBCJ75ywEI1vzLAQjnhMwBCLWFzAEIy4nMAQitjswBCNuOzAEIm4/MAQjSj8wBCNmQzAEYjp7LAQ==' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://colab.research.google.com/' \
  -H 'accept-language: en-GB,en;q=0.9,bg-BG;q=0.8,bg;q=0.7,en-US;q=0.6' \
  -H 'cookie: [XXX-SANITIZED-XXX]' \
  --data-raw '{"notebook_name":"Untitled1.ipynb","notebook_id":"https://github.com/atkuzmanov/googcol-test-1/blob/main/Untitled1.ipynb","colab_version_tag":"colab-20211215-060053-RC00_416524343","session_id":1625868743325649,"user_action":{"action":"save","source":1}}' \
  --compressed
    ```
    And this request gets:

    ```sh
    Request URL: https://colab.research.google.com/analytics?authuser=0
    Request Method: POST
    Status Code: 204 
    ```

Please do not hesitate to let me know if you need any more info.    

I need this to work rather urgently, so any help I will greatly appreciate.

Thanks you so much,
atkuzmanov

**Describe the expected behavior**
Colab should be able to save to any of my GitHub repos regardless whether they are public or private.
At this point I am desperate and even only being able to save to public repos would be great!

**What web browser you are using**
`Chrome (Macintosh; Intel Mac OS X 10_14_6)`

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
- https://github.com/atkuzmanov/googcol-test-1

**Comment by corrieann** [comment]
Unfortunately, I suspect you're just running into an issue of bad UX on our side.  In order to save back to GitHub you always have to use "Save a copy in GitHub".  Colab doesn't yet support auto-save or Ctrl+S saving back to GitHub because it requires making a commit back to the repo but it's a bit misleading that the intended save flow looks like it's making another copy.  So, work-around is "Save a copy in GitHub" -- hopefully that works for you for now.

**Comment by atkuzmanov** [comment]
@corrieann, thank you so much for the quick reply, I greatly appreciate it! ( :

I see, that sort of makes sense.

Do you know if this is already a feature request, to be able to save with `Save` or `Ctrl/Cmd+S` and if not, can we please change this issue to a feature request?

**Comment by corrieann** [comment]
I filed an internal feature request for this issue.  Thanks!

**Comment by coder563** [comment]
I just started having this problem too for each and every notebook on Github. But this wasn't the case until now.

**Comment by atkuzmanov** [comment]
> I filed an internal feature request for this issue. Thanks!

Thank you so much for this, I appreciate it! ( :

Let me know if you need any additional support, for example for me to do anything like also raise a feature request here or something. I obviously won't do it for now as you've already raised an internal one.

**Comment by atkuzmanov** [comment]
> I just started having this problem too for each and every notebook on Github. But this wasn't the case until now.. When you click on "Open in Colab" icon on GitHub it opens every notebook as "Untitled<number".ipynb in Colab

Hi, I am not sure I understand what you are saying correctly, or if it is related to this issue. 
I have, on purpose, manually and explicitly named the files in the dummy/test repo linked above - `Untitled1`, `Untitled2` ... etc.

**Comment by coder563** [comment]
So if I create a file on Github "Sorting.ipynb" it opens as "Unitled1.ipynb" on colab. If I create another file on Github "Index.ipynb" it opens as "Untitled2.ipynb" and so on.

**Comment by atkuzmanov** [comment]
> So if I create a file on Github "Sorting.ipynb" it opens as "Unitled1.ipynb" on colab. If I create another file on Github "Index.ipynb" it opens as "Untitled2.ipynb" and so on.

That sounds to me like a completely different issue than the one I have described in this ticket.
This ticket is now closed anyway so it will not get the necessary attention, I suggest you open a new ticket with your issue and describe it like you have in here. :)

**Comment by anishjohnson** [comment]
I am working on a project and when I save a copy in the repository using colab and try to view it later it keeps on showing An error occurred,  I tried creating new repo as well as creating new notebook using colab and still can view my notebook. Any help would be appriciated.

**Comment by atkuzmanov** [comment]
Hi @corrieann, Happy new 2022, wishing you all the best!
Can we please have a link for tracking the issue you opened, just to keep track of progress etc?

**Comment by imhilla** [comment]
I was stuck for a while but this [comment ](https://github.com/googlecolab/colabtools/issues/2518#issuecomment-997020696)helped

**Comment by sandhya-suman-ux** [comment]
i am not able  to save colab notebooks in github resiprotary

**Comment by imhilla** [comment]
Did you hover on File and select `save copy on github`?

**Comment by rzeta0** [comment]
Today, 19th Dec 2023, and the last few days I have found the "save copy on GitHub" randomly fails.

The strange thing is, that it initially shows on GitHub as a new update "now" or "2 minutes" ago .. but then later it seems to revert to an old copy days ago.

**Comment by angelaaaateng** [comment]
Hi! I'm also running into this issue; the weird thing is, save on Github was working a few hours ago, but I think I clicked out of the Google Colab tab while it was about to save to Github. Now, I'm getting the following error: 

`Failed to save notebook to https://github.com/xxxx/xxx.ipynb`

I've tried logging in and logging out, closing my tabs and restarting Chrome. I would really appreciate any advice! Thank you so much!

**Comment by prodonjs** [comment]
I am not able to reproduce this behavior this morning. Is this something that you can reproduce consistently for the same GitHub notebook? What about different notebooks from the same repository? If you are able to record a screencast and/or record a [HAR dump](https://support.google.com/admanager/answer/10358597?hl=en) from your browser that would also help.

We will be releasing some improvements to the UX surrounding GitHub saving in the coming weeks so we're definitely interested in reducing any friction that may exist.

**Comment by tracydo99** [comment]
i had this problem as well and what fixed it was switching out my api key with a secret key.
