### ISSUE TITLE
Failed to assign a backend No backend with GPU available. Would you like to use a runtime with no accelerator?

### ISSUE THREAD

**Issue by ihsanulada** [googlecolab/colabtools#2519]
Im using Google Colab PRO+ and cannot connect GPU Backend for 7 days. How to fix it?

**Comment by Nefousi** [comment]
I have the same problem, I paid for Google Colab PRO + for a month and cannot connect the GPU Backend for 8 days. How to fix it and recover the lost days?

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
