### ISSUE TITLE
Add ipytree support (Jupyter widget for tree-structured data)

### ISSUE THREAD

**Issue by tylere** [googlecolab/colabtools#2522]
Add support for the [ipytree](https://github.com/QuantStack/ipytree) within Colab.

![Screen Shot 2021-12-20 at 11 50 14 AM](https://user-images.githubusercontent.com/92862/146824369-7ad9c637-451f-437e-9010-84d9b7efe1dc.png)

**Is your feature request related to a problem? Please describe.**
When working with geospatial data, there is often a need to inspect layers of information (often nested) for a region of interest. With the addition of [Colab support for ipyleaflet](https://github.com/googlecolab/colabtools/issues/498#issuecomment-910755873), there is a way to display and interact with spatial data, but there is a related need to display layer data.

**Describe the solution you'd like**
Provide a way to install and use the third-oarty jupyter widget [ipytree](https://github.com/QuantStack/ipytree). A good test case would be the ability to run the [ipytree_ileaflet example](https://github.com/QuantStack/ipytree/blob/master/examples/ipytree_ipyleaflet.ipynb).

**Describe alternatives you've considered**
I have considered manually building simple trees using the standard [jupyter widgets](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html), but that seems like reinventing the wheel...

**Additional context**
When trying to display an ipytree widget in Colab, Chrome developer tools reports a 404 error accessing the following:
> manager.min.js:1654` GET https://cdn.jsdelivr.net/npm/ipytree@0.2.1/dist/index.js 404

I confirmed that the file is not accessible from the CDN, however, there are other related CDN files for ipytree@0.2.1
https://www.jsdelivr.com/package/npm/ipytree

**Comment by giswqs** [comment]
I second the support for ipytree @martinRenou. I have a Python package for geospatial analysis called [whiteboxgui](https://github.com/giswqs/whiteboxgui), which is used by [geemap](https://github.com/giswqs/geemap) and [leafmap](https://github.com/giswqs/leafmap). I implemented it using both ipywidgets and ipytree. Currently, only the ipywdigets version works in Google Colab. Here is a notebook example  [![image](https://colab.research.google.com/assets/colab-badge.svg)](https://githubtocolab.com/giswqs/whiteboxgui/blob/master/examples/examples.ipynb) [![image](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/giswqs/whiteboxgui/master)

Implemented using ipywidgets
![image](https://user-images.githubusercontent.com/5016453/146825675-8f1907ea-db2b-42ab-90f4-22f990d22dbf.png)

Implemented using ipytree
![image](https://user-images.githubusercontent.com/5016453/146825706-62d14214-cb41-461a-bab9-55a4207cc115.png)

Demo
![tutorial](https://i.imgur.com/girs2dr.gif)

**Comment by blois** [comment]
The ipytree_ipyleaflet.ipynb example appears to work using `ipytree==0.2.0`:

https://colab.research.google.com/gist/blois/1af162473872445cbece540ffe6830c4/untitled1200.ipynb

The dist/ folder does not appear in the `0.2.1` release.

**Comment by tylere** [comment]
Closing since Colab support is working as intended... just need to get the CDN copy corrected.
