### ISSUE TITLE
Multiple Cursor in each cell

### ISSUE THREAD

**Issue by Aditya-gam** [googlecolab/colabtools#2528]
**Describe the current behavior**
There is a cursor in each of my cells and even running the cell does not put the cursor in the next cell. I am not able to type in a different cell unless I reload the page.

**Describe the expected behavior**
There should be only 1 cursor in the current cell which should move to the next cell upon execution or when I click on another cell. I should be able to type in any cell where I click.

**What web browser you are using**
Google Chrome

**Comment by cperry-goog** [comment]
@Aditya-gam occasionally browser extensions will cause issues, can you try to reproduce this in an incognito window?

**Comment by craigcitro** [comment]
Note that our text editor does support multiple cursors, which can be activated with alt-click or ctrl+alt+up/down (or cmd+alt on a Mac). Are you potentially enabling multiple cursors? (Escape should get rid of the extra cursors.)

**Comment by RDmaverick** [comment]
I was getting same error it was because of one of my chrome extensions which I used to disable Action Log, so you can check for the same and disable it and try refreshing it. It should work
