### ISSUE TITLE
gdown option not working even after setting the permission to "anyone in this group with this link can view"

### ISSUE THREAD

**Issue by NobinPegasus** [googlecolab/colabtools#2531]
**Describe the current behavior**
I am sharing my google drive file with anyone in this group with this link can view.

![Screenshot 2021-12-30 234234](https://user-images.githubusercontent.com/56520367/147776712-b77ec932-a50d-475a-98a3-e071d78e36e4.png)

But when I login using my institutional email id and try to download this file using the following code
! gdown --id File_id

It gives the following error:
Permission denied: https://drive.google.com/uc?id=File_id
Maybe you need to change permission over 'Anyone with the link'?
unzip:  cannot find or open Results.zip, Results.zip.zip or Results.zip.ZIP.

![Screenshot 2021-12-30 234924](https://user-images.githubusercontent.com/56520367/147776832-018dda22-106a-4f18-9261-afe5a8552ff5.png)

**Describe the expected behavior**
Since I am giving permission to anyone of my institution to view the file.
Using ! gdown --id File_id 
anyone using my organization email should be able to download the file.

**What web browser you are using**
Microsoft Edge

**Additional context**
(https://colab.research.google.com/gist/NobinPegasus/278523b0f8ef3f6a9a045a998a827414/untitled9.ipynb?authuser=2)

**Comment by craigcitro** [comment]
This is a gdown question, not a colab question.
