### ISSUE TITLE
Payment for Colab Pro is not working

### ISSUE THREAD

**Issue by deanhopes** [googlecolab/colabtools#2532]
The payment authorizes, then it repeats this screen, never completing the transaction.
![Untitled-1](https://user-images.githubusercontent.com/56652777/147834572-78c63609-2556-4961-8e70-92f47dedda1f.jpg)

**Comment by cperry-goog** [comment]
Thanks for the report. Can you provide more information on your setup? Browser, OS, Device type, Country?
