### ISSUE TITLE
Vim mode search via forward slash not working

### ISSUE THREAD

**Issue by MatteoGaetzner** [googlecolab/colabtools#2537]
**Current Behavior**
When using the vim text editor mode, the search function, which can be used by pressing '/' and then typing the keyword that should be found, does not work. Instead, the keypresses, following the forward slash get registered as keypresses in normal mode.

**Expected Behavior**
The keypresses after hitting forward slash should be registered as search mode keypresses instead of normal mode keypresses.

**Web Browser**
Firefox, Safari

**Additional Context**
Any notebook I tested produced this error, for example this one:
https://colab.research.google.com/drive/1aEKu3r09QM-iZ5i5qdaEgkiODsbUQPkd?usp=sharing

**Comment by cperry-goog** [comment]
tracked internally at b/213342793

**Comment by nss-ysasaki** [comment]
Seems to be fixed. (hooray!)
Any official comments, or closure of the issue, @cperry-goog?

**Comment by katlyn-edwards** [comment]
Sorry for the lack of updates - this is indeed now fixed. Thanks for noticing!
