### ISSUE TITLE
Security Error when initializing GPU accelerated runtime

### ISSUE THREAD

**Issue by Vichoko** [googlecolab/colabtools#254]
SO: Windows 10
Browser: Firefox Quantum 61.0.2
Python version: 3

This error has been happening to my colaboratory notebook in the last couple of days, when i select GPU accelerated runtime enviroment. When i select None hardware accelerator (CPU), this error won't show and it'll work correctly.

When the runtime is initializing in GPU mode, it pops the following error:

> SecurityError: The operation is insecure.
This message is preceeded with this other error message:

> Could not access the resources needed to display output.
   This is probably because third-party cookies are not allowed by your browser.

I have third-party cookies are allowed in my browser, also i have all extensions disabled.

When i check the JS console, this error message is shown, when the error modal pops-up:
`
Failed to register / update a ServiceWorker for scope 'https://s01qiu2uyui-colab.googleusercontent.com/v2/usercontent/8b5e8f2bbe60490e/': Access to storage is restricted in this context due to user settings or mode Private browsing
`

As i said, when using None accelerator or CPU, this error won't show up.

Something weird to note, is that this error sometimes doesn't pop, and the runtime initialize correctly in GPU mode with the same exactly browser i'm using now. So this runtime enviroment works intermittently under the same local conditions, in my case.

**Comment by blois** [comment]
I can't think of any relation between GPU and the error, I'm curious if it repro's in a FireFox private window as well.

https://bugzilla.mozilla.org/show_bug.cgi?id=1429714 discusses some potential causes, but I cannot repro the issue just by enabling GPU.

**Comment by Vichoko** [comment]
Thanks for the attempt.

I tried now after some hours and the GPU runtime is initializing without errors.

**Comment by metrizable** [comment]
Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem since then, if you are still experiencing the issue, please re-open and provide steps to reproduce.
