### ISSUE TITLE
My colab pro+ can access only less than 13g ram and p100 gpu.

### ISSUE THREAD

**Issue by bigstrawberrywakaka** [googlecolab/colabtools#2540]
Describe the current behavior
I am having the exact same problem described in #2428 #2494. My colab pro+ can access only less than 13g ram and p100 GPU. My account is straberrywakaka@gmail.com. 
If I have been assigned 13g ram and p100 all the time, just like a pro user, then why should I buy pro+? I feel cheated by Google... = =

Describe the expected behavior
My subscription can work normally.

What web browser you are using
Chrome

**Comment by bigstrawberrywakaka** [comment]
still always give me p100... ?= =

**Comment by bigstrawberrywakaka** [comment]
still p100. Anyone I know who buys colab pro+ can be assigned to V100 or A100. Why only give me p100? So disappointed...

**Comment by CharonWangg** [comment]
nope, mine is same P100, which has been a month

**Comment by cperry-goog** [comment]
You'll need to ensure you're requesting high mem runtimes in notebook settings when you're connecting to a GPU runtime. As for P100 vs. another GPU type, that's subject to resource availability.

**Comment by cperry-goog** [comment]
If you're interested in a deterministic GPU type, you'll want to explore our Marketplace offering: https://research.google.com/colaboratory/marketplace.html

**Comment by bigstrawberrywakaka** [comment]
today still P100...

**Comment by bigstrawberrywakaka** [comment]
still P100. sh*t  google!!!

**Comment by colaboratory-team** [comment]
Fix is being worked on with internal tracking bug b/212640241.

**Comment by bigstrawberrywakaka** [comment]
still P100, always P100... I hope others will not be deceived by you google... 👎

**Comment by panchocodes** [comment]
Any solution? :,(

**Comment by panchocodes** [comment]
Any known fix for this?

**Comment by bigstrawberrywakaka** [comment]
No solution. I have given up using the service of colab pro+




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "googlecolab/colabtools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月22日(星期五) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [googlecolab/colabtools] My colab pro+ can access only less than 13g ram and p100 gpu. (Issue #2540)





 
Any known fix for this?

**Comment by panchocodes** [comment]
Ok, thanks anyway!
