### ISSUE TITLE
Google Colab pro disconnect even before 24 hours

### ISSUE THREAD

**Issue by mz3220** [googlecolab/colabtools#2544]
I subscribed to pro service expecting a connectivity period of 24 hours. However, it disconnected after 12 hours, although I am using a script on the browser that keeps clicking the reconnect every 1 minute.

**What web browser you are using**
(Chrome)

**Comment by cperry-goog** [comment]
Runtime length is individualized and subject to quota remaining. We're working on better ways to surface that to users. On the surface, this appears to be a resource quota exhaustion issue.

Pro+ users have access to background execution which gives much more reliability and runtimes which execute up to 24 hours. But again, that's subject to quota remaining.
