### ISSUE TITLE
Can't pip install in my colab

### ISSUE THREAD

**Issue by ahinazar** [googlecolab/colabtools#2545]
Hi,
I'm trying to do the following:
`!pip install git+https://github.com/statsmodels/statsmodels.git`

but all i get (and stuck with) is:
`Collecting git+https://github.com/statsmodels/statsmodels.git
  Cloning https://github.com/statsmodels/statsmodels.git to /tmp/pip-req-build-x5en6kda
  Running command git clone -q https://github.com/statsmodels/statsmodels.git /tmp/pip-req-build-x5en6kda`

it's not issue with the link, i tried it locally and it went well...

any help?

thanks

**Comment by blois** [comment]
The `!pip install` error is:

```
ERROR: Package 'statsmodels' requires a different Python: 3.7.12 not in '>=3.8'
```

So it's requiring Python 3.8+ where Colab is still on 3.7. Can you use the version you get with `!pip install statsmodels`?

**Comment by cperry-goog** [comment]
Dupe with #2165
