### ISSUE TITLE
Auto-turnoff

### ISSUE THREAD

**Issue by Rise166** [googlecolab/colabtools#2549]
i've been using this thing for past 1 day. i used it and its pretty **Great!**. But i have an issue where the chrome remote profile turn off automatically and i have to literally create new one every 40 minutes. it's really annoying. Please help me fix this issue!!!
![Screenshot_4](https://user-images.githubusercontent.com/83956457/148656471-3cca7626-0f8c-4c9b-9fbe-0027b5dec802.png)

**Comment by rmdhnreza** [comment]
I think this is not a bug, basically colab is for interactive users.
From [faq.html#resource-limits](https://research.google.com/colaboratory/faq.html#resource-limits)

### How long can notebooks run in Colab?

Notebooks run by connecting to virtual machines that have maximum lifetimes that can be as much as 12 hours. **_Notebooks will also disconnect from VMs when left idle for too long._** Maximum VM lifetime and idle timeout behavior may vary over time, or based on your usage. This is necessary for Colab to be able to offer computational resources for free. Users interested in longer VM lifetimes and more lenient idle timeout behaviors that don’t vary as much over time may be interested in Colab Pro and Pro+.

So, solution for this issue, upgrade to Colab Pro+ for background execution

<details>
  <summary>Image</summary>
![Colab Pro+](https://i.imgur.com/wpO1rtv.png)
</details>

**Comment by Rise166** [comment]
No, when i was using it also turned off that time aswell. it doesnt even last 12 hours.

**Comment by cperry-goog** [comment]
Colab prioritizes use for interactive or exploratory computing work in the Colab UI. Using Colab runtimes for other purposes is unsupported.
