### ISSUE TITLE
Persistent failure to connect to a backend

### ISSUE THREAD

**Issue by vibss2397** [googlecolab/colabtools#255]
Hey, i have been trying to run a generative network on my colab for a while now. Initially it worked fine, but it now it wont assign me a gpu backend. I tried to open the file in another account and it connects but it has been 2 days and i cant connect to my colab notebook from my account. Does google lock one out if they use colab continously or is it some other error?

**Comment by metrizable** [comment]
Since this issue was filed a while ago, if you are still experiencing the issue, please file a new issue with steps to reproduce/screen cast or file in-product feedback.
