### ISSUE TITLE
Attaching larger disk to GSE Custom Colab VM isn't reflected in Colab disk space available

### ISSUE THREAD

**Issue by jroakes** [googlecolab/colabtools#2553]
**Describe the current behavior**
I am running a process on a fairly large file (80GB) on Colab connected to a Custom Colab GCE VM.  The VM has 64 CPUs and 512GB of memory.  When launching the VM, I allocate 500GB of disk space as I was running into disk issues with the default 200GB.  The attached disk is of type SSD.  Despite upgrading the volume to 500GB, Colab reports that the diskspace available is ~185GB.  

**Describe the expected behavior**
When I upgraded the drive space in the VM, I expected the drive space available to Colab to reflect the additional space.

**What web browser you are using**
Chrome

**Additional context**
Cannot link a working example due to cost of VM.

VM: is n2-highmem-64 (us-east1-b)

Here is the output of DF from Colab
```
Filesystem     1K-blocks      Used Available Use% Mounted on
overlay        195578532 170304448  25257700  88% /
tmpfs              65536         0     65536   0% /dev
shm              5696512         0   5696512   0% /dev/shm
tmpfs          264188800        44 264188756   1% /var/colab
/dev/sda1      511741492 239756576 271968532  47% /etc/hosts
tmpfs          264188800         0 264188800   0% /proc/acpi
tmpfs          264188800         0 264188800   0% /proc/scsi
tmpfs          264188800         0 264188800   0% /sys/firmware
```

**Comment by jroakes** [comment]
For anyone else with this issue in colab, you can use the following command to resize `/var/colab`

```
!sudo umount /dev/shm/ && sudo mount -t tmpfs -o rw,nosuid,nodev,noexec,relatime,size=200G shm /dev/shm
```

where you can point, for example, ray to use as _temp_dir
`ray.init(num_cpus=30, _temp_dir="/var/colab", include_dashboard=False, _enable_object_reconstruction=True)`

**Comment by colaboratory-team** [comment]
Hi JR,

Thank you for reporting this problem. It has been fixed for the initial configuration of Colab-VM. Said another way, if you configure Colab VM with 500G disk, you will see the same in the Colab notebook.

The ability to resize the disk, post creation, has been added as a feature request, tracked internally as b/214286660.

Until the above feature is released, you can resize the disk post creation by using SSH to login to the VM and executing these commands, with the caveat that you are using an unsupported feature and the risk that goes with it:

`sudo truncate -s <NEWSIZE> /var/lib/docker/colab-vmdisk`
`sudo docker exec -it tunnelbevm /bin/losetup -c /dev/loop0`
`sudo resize2fs /dev/loop0`

Where **<NEWSIZE**> is a string like 500G minus 10G for overhead (IOW, 490G for a 500G new disk size). 

Here is a worked example:

`andrekhan@colab-4-vm ~ $ sudo truncate -s 490G /var/lib/docker/colab-vmdisk`
`andrekhan@colab-4-vm ~ $ sudo docker exec -it tunnelbevm /bin/losetup -c /dev/loop0`
`andrekhan@colab-4-vm ~ $ sudo resize2fs /dev/loop0`
`resize2fs 1.46.2 (28-Feb-2021)`
`Filesystem at /dev/loop0 is mounted on /var/lib/docker/overlay2; on-line resizing required`
`old_desc_blocks = 24, new_desc_blocks = 62`
`The filesystem on /dev/loop0 is now 128450560 (4k) blocks long.`
`andrekhan@colab-4-vm ~ $ `

**Comment by jroakes** [comment]
Thanks for the follow up @colaboratory-team!
