### ISSUE TITLE
Googlecolab plot are dipicted cut off

### ISSUE THREAD

**Issue by Driver160** [googlecolab/colabtools#2554]
In googlecolab when I plot my picture it doesn't show the first row of pixels.
Here is a copied version from the browser.
![abc4e296-5a2b-42ed-9913-66404bcb7fd7](https://user-images.githubusercontent.com/97529235/148953403-8ec3d9cf-e44f-48e6-8dad-055b3fb037f6.jpg)

Browser: Chrome
Code used inside a for loop:
    fig,ax = plt.subplots()
    plt.title('croped topside')
    ax.imshow(crop_semi2[i],'gray')
    plt.plot(np.shape(crop_semi2[i])[1]/2, np.shape(crop_semi2[i])[0],'go') # plot  the dot that indicate the middle
    # img_array= np.array(crop_semi2[i],dtype='uint16')
    # img_save = Image.fromarray(img_array)
    # img_save.save('missingpixel_found.tif')
    plt.show()

Here we see the saved TIF file from the previous plot which is showing correctly the picture I would have expected. 
![29734e15-68f3-43d1-b023-152235c7885c](https://user-images.githubusercontent.com/97529235/148953410-e8db81a7-b14e-44a3-bb9c-dc9eabc73449.jpg)

If I would add an extra row of zeros at the top it shows the following in the screenshot: 
![image](https://user-images.githubusercontent.com/97529235/148955517-bcc82f52-cd1c-413d-ae98-dd3e752a9462.png)

This in my opinion how it should have looked previously.

For completeness this is the saved TIF of the picture with the added row of zeros:
![image](https://user-images.githubusercontent.com/97529235/148955880-4da1d385-6bee-4148-bc55-fb025ca20673.png)

**Comment by blois** [comment]
Do you have a complete repro for this? Does this behavior differ from how it behaves in Jupyter?

**Comment by Driver160** [comment]
I have no experience in Jupyter so I could not easily check this! 
And do you want my entire code? There is a lot that is not only for plotting.

Thank you for your reply!

**Comment by cperry-goog** [comment]
Yes, can you share a notebook with the section that is plotting? We'll need a minimal reproducible notebook.
