### ISSUE TITLE
Colab : Unable to render color using matplotlib.pyplot.pcolormesh and colorbar

### ISSUE THREAD

**Issue by FriendOfFatBeagle** [googlecolab/colabtools#256]
Here are my code fragments:
import numpy as np
from scipy import signal, fftpack
from scipy.signal import chirp, sweep_poly
import matplotlib.pyplot as plt
from matplotlib.colors import BoundaryNorm

##----------- Generate signal   ----------------------------------
fs = 10e3                          #Hz  
ts = 1/fs                           # sampling interval
N = 1024                        ## total Samples 
freq_of_signal = fs/10       # 1K Hz  
phi = 0  
time = np.arange(N) / float(fs)                      # N time samples
x = np.sin(2*np.pi*freq_of_signal*time + phi)

##-----------Do spectrogram -----------------------
f, t, Sxx = signal.spectrogram(x, fs)
print( "type(Sxx) : " + str(type(Sxx)) + " Sxx.shape: " + str(Sxx.shape))
print( "Min Sxx: " + str(np.amin(Sxx)) + ", " + "Max Sxx" + str(np.amax(Sxx)) )
im = plt.pcolormesh(t, f, Sxx)
plt.ylabel('Frequency [Hz]')
plt.xlabel('Time [sec]')
plt.title("Signal Spectrum")
plt.colorbar(im)
plt.show()

I ran same code on desktop system with nvidia GPU, 
and was able to render color chart for 
matplotlib.pyplot.pcolormesh() & colorbar().  
But when I ran the same code as shown above in colab, 
but the output is only gray scale as shown below. 
What did I missed? 
Thank you for assisting.

![image](https://user-images.githubusercontent.com/4752711/44950687-bfc48200-ae0b-11e8-93a7-18bd116a8e67.png)

**Comment by metrizable** [comment]
I executed the example code and it renders with a color scale now:

![Screenshot from 2023-02-09 15-07-53](https://user-images.githubusercontent.com/65414824/217959265-34e644e5-626f-4bae-9c32-279ed25a5cf6.png)
