### ISSUE TITLE
Can't mount another drive in Colab Pro using drive._mount

### ISSUE THREAD

**Issue by machinelearninggo** [googlecolab/colabtools#2562]
I am trying to mount drive via drive._mount, however it shows "ValueError: mount failed: invalid oauth code". 

It never shows "Go to this URL in a browser ..." but just get failed immediately. 

I try to restart the pc but it doesn't work. Does anyone know how to solve it? Thanks very much!!!!

![1642707136(1)](https://user-images.githubusercontent.com/75209437/150409249-abf926ae-cb78-4211-882c-4460bb1bf530.png)

**Comment by craigcitro** [comment]
You should use `drive.mount`, not `drive._mount`.

**Comment by machinelearninggo** [comment]
> 
drive.mount cannot mount the drive from another account, which is what I need. See https://github.com/googlecolab/colabtools/issues/2419


> You should use `drive.mount`, not `drive._mount`.

**Comment by craigcitro** [comment]
We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution. Let us know if you have any issues mounting Google Drive and executing code from the same account.

**Comment by JaneMercer** [comment]
So we are now simply unable to mount the drive from another account?

**Comment by craigcitro** [comment]
@JaneMercer Yes.

**Comment by GHBTM** [comment]
I only am logged into one account across chrome, and still had to use drive._mount() yesterday.  Today both are broken.  Same issue here as Issue 2563, for me.

**Comment by cperry-goog** [comment]
dupe with #2563

**Comment by masc-it** [comment]
> > 
> 
> drive.mount cannot mount the drive from another account, which is what I need. See #2419
> 
> > You should use `drive.mount`, not `drive._mount`.

Same situation here, this is unacceptable. In my particular scenario I have a Colab Pro account on email 1 and my university Google Drive (unlimited) on email 2. Yeah I could use shared folders, but writings will still count on email 1. Please, do something.

**Comment by n1CkS4x0** [comment]
Same for me

**Comment by justinjohn0306** [comment]
Ya man, this really sucks that you can't mount drive from other accounts
anymore

**Comment by Randy1435** [comment]
> @JaneMercer Yes.

In the most polite way...


why?

**Comment by qkum** [comment]
> > > 
> > 
> > 
> > drive.mount cannot mount the drive from another account, which is what I need. See #2419
> > > You should use `drive.mount`, not `drive._mount`.
> 
> Same situation here, this is unacceptable. In my particular scenario I have a Colab Pro account on email 1 and my university Google Drive (unlimited) on email 2. Yeah I could use shared folders, but writings will still count on email 1. Please, do something.

I totally agree.

Same situation here.

Pro+ and can't connect to my gdrive from the same account as my Colab account.

48 hours now and they have not even rolled back the update yet. Morons.

**Comment by qkum** [comment]
> We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution. Let us know if you have any issues mounting Google Drive and executing code from the same account.

Lies, I can't even connect to my own gdrive.

Stop making shit up.

What about you guys start informing your Paying customers before you do such changes in general?

My patience has been used up.

It should have been fixed within 24 hours maximum. (you are google ffs)

Just Roll back the epic fail update and stop slacking. 

Sorry for the tone, but do you guys not give a flying F about your customers?.....

**Comment by chervonij** [comment]
> We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution. Let us know if you have any issues mounting Google Drive and executing code from the same account.

I have been watching this situation for two days now.
Colab team broken most of workflows. I just don't get it. 
What is the "more secure method to mount Google Drive"? 
What was wrong with OAuth before that?

**Comment by masc-it** [comment]
> > We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution. Let us know if you have any issues mounting Google Drive and executing code from the same account.
> 
> @craigcitro
> 
> Lies, I can't even connect to my own gdrive. (I use drive.mount)
> 
> Stop making shit up.
> 
> What about you guys start informing your Paying customers before you do such changes in general?
> 
> My patience has been used up.
> 
> It should have been fixed within 24 hours maximum. (you are google ffs)
> 
> Just Roll back the epic fail update and stop slacking.
> 
> Sorry for the tone, but do you guys not give a flying F about your customers?.....

Guys, I am as much pissed as you, but please don't push it that way. Stay calm, we will figure this out.

They already know how many workflows have been broken with this push and how many Pro and Pro+ clients they are going to lose (me included), let's just stick together and show our honest disappointment.

A more secure way to mount Google Drive? Let it be. But allow us to use whatever account we want. 

Or is there anything else behind those commits? Whoever pushed in that direction already knew the disservice that would have been caused and it is not something we can't even remotely accept. Most of all, for customers paying monthly for your service.

**Comment by primeart** [comment]
This can't have a better timing for me. Students was constantly complaining about loosing work on random colab (free) runtime disconnects, and I finally decided to ask for colab pro been paid for entrie faculty. After this your move, guess who will pay nothing to google + won't learn on google products/accounts?

**Comment by Randy1435** [comment]
I have found a way to connect your drive to a different account, I won't show it here since this is Google and they will get rid of it probably so if you can DM me (idk if GitHub has DMS) on discord if you have that, I will send you the code. It's slow and not recommended but it works. Pikachu ✓#5870 is my discord

**Comment by Randy1435** [comment]
Eh, Frick it.

!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}
%cd /content
!mkdir gdrive
%cd gdrive
!mkdir MyDrive
%cd ..
%cd ..
!google-drive-ocamlfuse /content/gdrive/MyDrive
%cd /content

this piece of bigger, takes longer to run, unconventional but working piece of code should do the trick

**Comment by ARUNSRINIVASAN12** [comment]
> We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution. Let us know if you have any issues mounting Google Drive and executing code from the same account.

Sir, I am a UG student in India, and Colab played a major part in my research internships. For hyperparameter tuning (using WandB) using multiple accounts, makes my job easier and more productive, whereas when done using a single account increases my time exponentially and is unproductive. Also mounting across different multiple google accounts is a unique feature of Colab and please don't remove that.

**Comment by blrk** [comment]
> > > 
> > 
> > 
> > drive.mount cannot mount the drive from another account, which is what I need. See #2419
> > > You should use `drive.mount`, not `drive._mount`.
> 
> Same situation here, this is unacceptable. In my particular scenario I have a Colab Pro account on email 1 and my university Google Drive (unlimited) on email 2. Yeah I could use shared folders, but writings will still count on email 1. Please, do something.

I am also facing the same issue. Colab pro in one account. data in the official gdrive. Pathetic situation. Worst case, I have to think about the alternatives.

**Comment by zavinono** [comment]
> We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution. Let us know if you have any issues mounting Google Drive and executing code from the same account.

This is unacceptable- working from a university as a student we have drives with full storage capabilities but not the ability to add cards to them to pay for things like colab pro- if this is the case we will have to look at other options and recommending stopping all paid google services- as it is unusable.

**Comment by blrk** [comment]
> > We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution. Let us know if you have any issues mounting Google Drive and executing code from the same account.
> 
> Sir, I am a UG student in India, and Colab played a major part in my research internships. For hyperparameter tuning (using WandB) using multiple accounts, makes my job easier and more productive, whereas when done using a single account increases my time exponentially and is unproductive. Also mounting across different multiple google accounts is a unique feature of Colab and please don't remove that.

I found a workaround share the data folder of your official drive to your personal account (if write access is needed add it). 
Then move to the shared with me of your drive. Right-click on the folder a popup menu will appear. In that click, the option add a shortcut to drive. Now, Drive menu appear, in that click the My drive option and choose a folder where you want to create the short cut. Use that path for data access. In my refer the following code

`drive.mount('/content/drive')
os.chdir('/content/drive/MyDrive/research_data/xyz/)`

**Comment by cperry-goog** [comment]
Thanks @blrk I've been meaning to propose that as an option for folks on the various threads here, just haven't had a chance. I believe you can still get your work done by explicitly sharing Drive content with the intended account.

**Comment by masc-it** [comment]
> > > We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution. Let us know if you have any issues mounting Google Drive and executing code from the same account.
> > 
> > 
> > Sir, I am a UG student in India, and Colab played a major part in my research internships. For hyperparameter tuning (using WandB) using multiple accounts, makes my job easier and more productive, whereas when done using a single account increases my time exponentially and is unproductive. Also mounting across different multiple google accounts is a unique feature of Colab and please don't remove that.
> 
> I found a workaround share the data folder of your official drive to your personal account (if write access is needed add it). Then move to the shared with me of your drive. Right-click on the folder a popup menu will appear. In that click, the option add a shortcut to drive. Now, the Drive menu appears, in that click the My drive option and choose a folder where you want to create the shortcut. Use that path for data access. In my refer the following code
> 
> `drive.mount('/content/drive') os.chdir('/content/drive/MyDrive/research_data/xyz/)`
> 
> Also, refer this link [https://stackoverflow.com/questions/54351852/accessing-shared-with-me-with-colab](url)

Shared folders works fine unless you have massive writes from your colab (ie: model checkpoints). 
In such case, remember that writes will still count on the Colab account, not the shared folder owner. Be careful.

**Comment by prismspecs** [comment]
> > > 
> > 
> > 
> > drive.mount cannot mount the drive from another account, which is what I need. See #2419
> > > You should use `drive.mount`, not `drive._mount`.
> 
> Same situation here, this is unacceptable. In my particular scenario I have a Colab Pro account on email 1 and my university Google Drive (unlimited) on email 2. Yeah I could use shared folders, but writings will still count on email 1. Please, do something.

I have exactly this situation and now I simply cannot use Colab for my research. This is a huge issue, please fix it.

**Comment by Tiagoeem** [comment]
This is a huge issue, please fix it. [2]

**Comment by Donegas** [comment]
Any updates on this issue? I can't afford having shared folders with tons of GB reading/writing between accounts.

**Comment by Kossi-Francois** [comment]
frankly the disappointment is immeasurable, in my opinion it looks more like a finance oriented  decision by more than by security. I really hope this will be fixed in the next few days.

**Comment by vu-huynh-huy** [comment]
This is very frustrating issue for one who has only 15 GB limited in 1 google drive account, please fix it.

**Comment by cperry-goog** [comment]
Thanks for voicing your frustration. Would you please describe your use cases in more detail so we can find ways to solve the root problem? What causes you to have one account with large amounts of data, and a separate account you need to compute with?

The one use case we've seen so far is a student with large amounts of data on their student account, but unable to purchase Colab Pro on a student account due to Google Pay being blocked by their administrator.

We'd like to understand if there are other use cases we're missing.

**Comment by faruknane** [comment]
@cperry-goog we have two google drives with 5TB and one of them is full. I have to access the data from the first one which is already full and train on the second drive. It is extremely annoying for us to find alternative solutions. Why do I find myself in a situation where I have to solve extra another problem which google wants it to be impossible? I am already paying 2 google drive + 1 colab plus pro!!!!!!!!!

**Comment by Kossi-Francois** [comment]
@cperry-goog for me it is exactly this case, I have an account with unlimited storage provided by an organization (the school), for which I cannot even use colab anymore because you have deactivated colab by default on the accounts administered since a few months, and so I was using colab with my personal account plus the drive with unlimited storage.

At the moment as workaround, i am  sharing a folder from the drive with unlimited storage with my personal account.
But this solution is not perfect, for example when I save files through the shared folder, they are stored in the current drive (personal account) and not on the drive of the shared folder (drive with unlimited storage)

**Comment by Donegas** [comment]
@cperry-goog for me it is the exactly the case as well. I'm a PhD candidate and a researcher. I have unlimited storage in my school account, but I can't purchase google colab pro there and I have also a problem with data sensitivity, the data was shared/collected in my school account but it cannot be shared with anyone else outside organisation. I also use colab pro for minor stuff in my reasearcher job, wich also has sensitive data that cannot be shared outside organisation as well. The smart way was purchase colab pro on my personal account and make it connect in both organisational accounts as needed.

**Comment by Randy1435** [comment]
> Thanks for voicing your frustration. Would you please describe your use cases in more detail so we can find ways to solve the root problem? What causes you to have one account with large amounts of data, and a separate account you need to compute with?
> 
> The one use case we've seen so far is a student with large amounts of data on their student account, but unable to purchase Colab Pro on a student account due to Google Pay being blocked by their administrator.
> 
> We'd like to understand if there are other use cases we're missing.

We don't mind which system we use, as long as we are easily able to hook up account 1 (colab) to account 2 (drive) using colab gdrive mounting

**Comment by minor** [comment]
Also going to hop in on this thread – have Colab Pro on my personal account but not on my school account as it is blocked. The shared with me trick works, but it stores everything, as @masc-it mentioned, on the Colab user's drive, which is preventing some of my files from being saved. I'd really love to see a fix!

**Comment by vu-huynh-huy** [comment]
@cperry-goog 
> We've rolled out a new, more secure method to mount Google Drive

 What is more secure method here? Honestly we dont get it, Could you please revert as the past version

**Comment by prismspecs** [comment]
Has this been fixed yet?

**Comment by khan1792** [comment]
@prismspecs Not yet, unfortunately. It is quite annoying.

**Comment by BlkPingu** [comment]
Fix this ffs there was nothing wrong with the being able to mount external drives

**Comment by Kossi-Francois** [comment]
when will the problem finally be solved ?
Does anyone have any work around  ?

**Comment by Digital-XxX** [comment]
Still no remedy for this? Hoping someone will figure it out.

**Comment by Digital-XxX** [comment]
I think I'm just gonna cry 😭😭😭

**Comment by lilianli17** [comment]
any update for the mounting problem

**Comment by OEMunlag** [comment]
Been a year already, no fix.

**Comment by Azutoz** [comment]
Is this issue fixed?

**Comment by EpsiRho** [comment]
If I can't mount an alt drive and you download speeds are so slow I time out before you can give me my file, what's the point? Why use your service at all?
