### ISSUE TITLE
_mount not working

### ISSUE THREAD

**Issue by RajdeepBorgohain** [googlecolab/colabtools#2564]
_mount is not working, below is a temporary solution posted by @zechenli03
Need better short solutions:

!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}
%cd /content
!mkdir drive
%cd drive
!mkdir MyDrive
%cd ..
%cd ..
!google-drive-ocamlfuse /content/drive/MyDrive

This code works for me. https://stackoverflow.com/a/69881106/15576628
But looking forward to an easier way.

_Originally posted by @zechenli03 in https://github.com/googlecolab/colabtools/issues/2399#issuecomment-1018178585_

**Comment by cperry-goog** [comment]
duping with #2563
