### ISSUE TITLE
[FR] Add a way to programmatically end the current session 

### ISSUE THREAD

**Issue by NightMachinery** [googlecolab/colabtools#2568]
**Is your feature request related to a problem? Please describe.**
Having an API to end the current session can save resources. There is interest in doing this as well; I found 3 Stackoveflow questions about doing exactly this, one of which had a bounty set on it.

- https://stackoverflow.com/questions/68640984/how-to-stop-google-colab-runtime-without-it-automaticly-restarting?noredirect=1&lq=1
- https://stackoverflow.com/questions/50541851/is-there-a-function-in-google-colab-module-to-close-the-runtime
- https://stackoverflow.com/questions/62331439/how-to-terminate-current-colab-session-from-notebook-cell

**Describe the solution you'd like**
```
from google.colab import terminate_session
terminate_session()
```

**Describe alternatives you've considered**
We can just let it run, until the AI overlords stop the sessions, wasting resources.

**Comment by qkum** [comment]
Basic 101 feature.

I assumed it existed and I had just not found it yet. 

I had too high expectations I assume.

Just like I assumed paying customers could use their services without getting treated like a GPU abuser. Nope.

**Comment by cperry-goog** [comment]
This is a good feature. I thought we already had it somewhere, but since I can't find it, leaving this open.

**Comment by lucids-git-goods** [comment]
please.  the current assumption that users are just going to stare at the colab screens until training is complete is unrealistic and would just be unhealthy.

**Comment by KaranKhoslaDianthus** [comment]
Hi, I'm just checking if there has been any progress on this requested feature

**Comment by BrockFletcher** [comment]
Any solutions? I've seen to run
!kill $(ps aux | awk '{print $2}')
or 
!kill -9 -1 
but these seem inelegant?

**Comment by happycube** [comment]
The !kill commands don't seem to work, at least with pro+ backgrounding.  I set up a time-delayed !kill -9 -1 and when I reconnected a few minutes later it listed the session as "unknown notebook" and I had to terminate it manually.

**Comment by carriemorrison** [comment]
Following...would really like to be able to stop notebook after execution. rather than being punished for it lol

**Comment by LordLean** [comment]
Just a friendly comment to help push this request up - it would be great if I could programmatically terminate a long session that's running whilst I nap!

**Comment by LuciferSam86** [comment]
Yeah, it would be nice, especially now we're switching to the compute credits.

**Comment by peap** [comment]
Thanks for your patience here, everyone. Starting next week you'll be able to programmatically end sessions from code cells like so:

```
from google.colab import runtime
runtime.unassign()
```

The new `unassign()` function marks the currently connected runtime for deletion and disconnects any notebook sessions.  I expect it to be available for any runtimes started next Monday morning (Sep 12, PDT) or later.
