### ISSUE TITLE
Problem when trying to mount gdrive from different account

### ISSUE THREAD

**Issue by lkautzsch** [googlecolab/colabtools#2569]
Google colab is returning an error when trying to mount a gdrive from a different account. This worked fine before until this morning.

`from google.colab import drive`
`drive._mount('/drive_folder')`

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-2da5ed700d5d> in <module>()
----> 1 drive._mount('/drive_folder')

/usr/local/lib/python3.7/dist-packages/google/colab/drive.py in _mount(mountpoint, force_remount, timeout_ms, use_metadata_server, ephemeral)
    294       wrote_to_fifo = True
    295     elif case == 5 and not use_metadata_server:
--> 296       raise ValueError('mount failed: invalid oauth code')
    297     elif case == 6:
    298       # Terminate the DriveFS binary before killing bash.

ValueError: mount failed: invalid oauth code`

**Comment by Randy1435** [comment]
I'm having the same issue, so is probably everyone. I'm gonna try looking for a solution

**Comment by masc-it** [comment]
See [here](https://github.com/googlecolab/colabtools/issues/2562#issuecomment-1017869732).

**Comment by cperry-goog** [comment]
We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution.

If you require data from another account, you can share that data between accounts and add a shortcut to view that file or folder in your Drive when mounted in Colab [1]

Report any issues accessing shared content. If you experience issues mounting Drive from the same account, please do the following:

Runtime -> Factory Reset Runtime
drive.mount() using the account with which you are logged in to Colab

And then send feedback in product: Help > Send feedback.

[1] https://support.google.com/drive/answer/9700156
