### ISSUE TITLE
Code for forms isn't available

### ISSUE THREAD

**Issue by taliesinb** [googlecolab/colabtools#257]
Perhaps I'm missing something, but the forms functionality (https://colab.research.google.com/notebooks/forms.ipynb) doesn't seem to be implemented in any of the colab repos. It doesn't seem to be a Jupyter feature either. Where can I find the implementation? Is it not open source?

**Comment by craigcitro** [comment]
You're correct, the code implementing forms isn't open-sourced anywhere.

(I'm going to interpret this as a sign that our docs didn't answer a question you have, so feel free to reopen or file a new issue with forms questions.)
