### ISSUE TITLE
unable to see ploted graphs in google colab pro +

### ISSUE THREAD

**Issue by akhil9010** [googlecolab/colabtools#2570]
**Describe the current behavior**
when i try to plot graph, I am unable to see graphs, but the code is executed perfectly.

**Describe the expected behavior**
when i try to plot graph, I used to see graphs, but I am unable to see graphs

**What web browser you are using**
(Firefox)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
 - https://colab.research.google.com/gist/akhil9010/62597bd5f0cafe56ab642ef66033f9a0/ass_16.ipynb

**Comment by cperry-goog** [comment]
Can you produce a subsection of that notebook which reproduces your error? We'll need a minimal reproducible notebook.

**Comment by PetrusPS** [comment]
Google Colab always fail to show graph after Run Cell. Not efficient when I always refresh using the Reload Current Page (Ctrl+R) if you want to display the graph

**Comment by cperry-goog** [comment]
@PetrusPS does this reproduce for you in an incognito window?
