### ISSUE TITLE
Google colab drive mounting.

### ISSUE THREAD

**Issue by Randy1435** [googlecolab/colabtools#2573]
**Is your feature request related to a problem? Please describe.**
Google drive mounting was always easy and fast, no hassle and it supported being able to hook up Google account 1 to a colab session with a different account, which was always nice and handy. Now Google deleted that feature for some odd "security" reason and it frustrates me that for example; you have important files on google drive account 1, You get access to a T4 in a colab session with Google account 2, you decide to do some math figuring out the T4 is better than a K80 that google likes to throw at you and boom, you figure out you can't connect the drive ya colab session because you're using 2 different accounts.

**Describe the solution you'd like**
Bringing back the old system or just allowing you to mount your drive to a different google accounts' colab session.

**Describe alternatives you've considered**
**drive._mount()** Before Google got rid of it...

**Additional context**
People buy google drive storage and some people buy (the not-worth-it (trust me, having 4 accounts with pro instead of 1 account with pro+ is way better)) colab pro+ subscription and they have them on different accounts, see where I'm going? Connecting your big drive to your colab pro+ session is now impossible, yay. Even in the new crappy window it says you can add a different account while you cannot...

**Comment by cperry-goog** [comment]
We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution.

If you require data from another account, you can share that data between accounts and add a shortcut to view that file or folder in your Drive when mounted in Colab [1]

Report any issues accessing shared content. If you experience issues mounting Drive from the same account, please do the following:

Runtime -> Factory Reset Runtime
drive.mount() using the account with which you are logged in to Colab

And then send feedback in product: Help > Send feedback.

[1] https://support.google.com/drive/answer/9700156

**Comment by Randy1435** [comment]
> 

I don't think you've read my issue correctly, Unacceptable.
