### ISSUE TITLE
Update the version of plotly installed by default

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [googlecolab/colabtools#2575]
**Describe the current behavior**
plotly.express, in Google Colab, ignores `color_map_sequence`

**Describe the expected behavior**
Graphs should show with the defined color map, chosen by the user, not the default color map

**What web browser you are using**
Chrome

**Additional context**

**Google Colab Behaviour**

<img width="1476" alt="Google Colab Behaviour" src="https://user-images.githubusercontent.com/34355337/150676493-98e97214-88fe-4d3b-a2c1-f845956496af.png">

**Expected Behaviour**

<img width="1785" alt="Expected Behaviour" src="https://user-images.githubusercontent.com/34355337/150676547-4ec57bf6-1501-43d6-bb27-af3fbf218ca5.png">

**Comment by craigcitro** [comment]
Can you include a minimal, public repro notebook demonstrating the problem?

(Note that your screenshot doesn't include the argument you mentioned.)

**Comment by JorgeMiguelGomes** [comment]
@craigcitro hi! Here is the [**link**](https://colab.research.google.com/drive/1bgieW5SK-nNu1bcvEI4WVabCYcgKL_PN?usp=sharing) to the notebook 

## Code running locally (that shows the chosen colors)

```
import plotly.express as px

"""## CREATE COLOR DISCRETE MAP"""

party_colors={
                "PCTP/MRPP": "#E00E02",
                "PSD": "#FF6400",
                "CDS-PP":"#0B6AB1",
                "Ergue-te": "#BF311E",
                "MAS": "#2B2C2C",
                "PS": "#E7A098",
                "LIVRE": "#00CE8C",
                "ADN": "#204E84",
                "BE": "#C90635",
                "PCP": "#025298",
                "R.I.R.": "#00939D",
                "Volt Portugal": "#502376",
                "CH": "#202056",
                "JPP": "#03AB83",
                "IL": "#00AEEF",
                "PAN": "#00798E",
                "MPT": "#66BB69",
                "PTP": "#00659B",
                "Nós, Cidadãos!": "#00659B",
                "ALIANÇA": "#0451CB",
                "PPD/PSD-CDS-PP - MADEIRA PRIMEIRO": "#F36D24",
                "PPM" : "#19476C",
                "PPD/PSD - CDS-PP - PPM – AD/Aliança Democrática": "#0031A"
							}

"""### PROJECTS PRESENTED BY PARTY"""

fig = px.pie(df_party,names='partido',values='projetos',hole =0.6, color='partido',color_discrete_map=party_colors)
fig.show()
```

**Comment by craigcitro** [comment]
Internal tracking: b/216114208

**Comment by craigcitro** [comment]
This should be fixed (possibly after a factory reset if you've got an existing runtime).
