### ISSUE TITLE
Install/updtate colab gdown package from 3.6.4 to 4.2.0 (File Sharing) 

### ISSUE THREAD

**Issue by fdsig** [googlecolab/colabtools#2579]
**Request: Install/updtate colab gdown package  from 3.6.4 to 4.2.0** 
<div align="left">
  <a href="https://pypi.python.org/pypi/gdown"><img src="https://img.shields.io/pypi/v/gdown.svg"></a>
</div>

[gdown](https://github.com/wkentaro/gdown) is a very useful package for file sharing/workflows that use google drive file/directory sharing urls. While there are other methods such as wget/curl, these are less well adapted to where use cases are for google drive sharing urls for larger files/urls and for urls that are for directories. 

currently, version install on defautl Colab runtime is runing on python 2.7:
```python
!gdown -V
>>> gdown 3.6.4 at /usr/local/lib/python2.7/dist-packages
```
This does not allow the use of `--path` handle:

```python
!gdown --folder https://drive.google.com/drive/some/folder/url -O test_dir/test.pth
```

Further present default install does obviously, not enable importing gdown and using within python scripts. 

**Current practice required to use gdown 4.2.0:**

```python
!pip uninstall gdown -y && pip install gdown
!gdown -V
>>> gdown 4.2.0 at /usr/local/lib/python3.7/dist-packages
```
**What this would resolve:**

Installing gdown 4.2.0 on python 3.7 as default may assist many researchers/those who wish to used Colab more easily and without time-consuming troubleshooting and manually uninstalling/reinstalling. 

**Request:**

Install gdown 4.2.0 on python 3.7 as default for Colab runtimes. 

**Use Case:**

Using down 4.2.0 is extremely useful for research where google drive where: 

> * sharing datasets where notebooks are used to share reproducible research;
> * sharing model weights/ state dictionarys;
> * sharing whole directories.

**Comment by craigcitro** [comment]
Thanks for the report! This should all be cleaned up; let us know if you're still hitting trouble.

**Comment by fdsig** [comment]
amazing!! thanks @craigcitro  
gdown is on python3.7 now 

```python
!gdown -V && python -c '[print("🤗") for i in range(5)]'
>>>gdown 4.2.0 at /usr/local/lib/python3.7/dist-packages
🤗
🤗
🤗
🤗
🤗
```
