### ISSUE TITLE
uninstall pymssql

### ISSUE THREAD

**Issue by powerbi1** [googlecolab/colabtools#258]
while uninstalling
-> !pip uninstall pymssql

Proceed (y/n)?

how can I press y????

**Comment by colaboratory-team** [comment]
Give it another try. We've just rolled out support for input prompts. You should now see something like this:
![prompt](https://user-images.githubusercontent.com/38081706/45189737-448a1400-b1ef-11e8-9b19-435203d8d97c.png)
