### ISSUE TITLE
Allow pre approved/ educational accounts to be linked under another account for the purpose of drive mounting

### ISSUE THREAD

**Issue by zavinono** [googlecolab/colabtools#2580]
Many university students have a drive account with storage that can hold data for experiments etc, however we don't have the ability to add card details to these accounts as we don't technically own them. This leaves us to using other accounts to buy and use colab pro and pro+. With the recent changes forcing the drive to be the same account as the colab account, it makes the service unusable. 

The feature I am suggesting is to be able to link educational accounts with normal accounts to bypass this restriction.

**Comment by masc-it** [comment]
This would be great.

**Comment by cperry-goog** [comment]
We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution.

If you require data from another account, you can share that data between accounts and add a shortcut to view that file or folder in your Drive when mounted in Colab [1]

Report any issues accessing shared content. If you experience issues mounting Drive from the same account, please do the following:

Runtime -> Factory Reset Runtime
drive.mount() using the account with which you are logged in to Colab

And then send feedback in product: Help > Send feedback.

[1] https://support.google.com/drive/answer/9700156


Closing this as it's not a feature we'll be pursuing.

**Comment by zavinono** [comment]
> We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution.
> 
> If you require data from another account, you can share that data between accounts and add a shortcut to view that file or folder in your Drive when mounted in Colab [1]
> 
> Report any issues accessing shared content. If you experience issues mounting Drive from the same account, please do the following:
> 
> Runtime -> Factory Reset Runtime drive.mount() using the account with which you are logged in to Colab
> 
> And then send feedback in product: Help > Send feedback.
> 
> [1] https://support.google.com/drive/answer/9700156
> 
> Closing this as it's not a feature we'll be pursuing.

This is not a solution to the problem- when training for academic purposes the models and checkpoints can quickly fill up the non-university drive- and creates files relevant spread across multiple drives. This more secure method makes it colab unusable for academic purposes when using things like transformers models. The solution I am proposing is allowing a link froma verified university account to be made with a personal account for the purpose of being able to purchase a pro account while using the space the university google drive accounts allow. This also stops any data protection issues with potentially sensitive data that need to be kept on university drives.
