### ISSUE TITLE
Colab Pro - cannot connect to GPU Backend

### ISSUE THREAD

**Issue by jacklfreedman** [googlecolab/colabtools#2581]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
![Screenshot 2022-01-25 091301](https://user-images.githubusercontent.com/98422234/151042726-6190e12a-f877-4aff-aa81-988017cc40e4.png)
Hi there - I have been using Colab for one day, and was enjoying the program for free - but i needed more space and ram, so i added 100gb of storage to my google account and got Colab Pro, but as soon as that went through in the system, i got an error message saying i was unable to access the gpu due to data limits. this is very confusing and I'd love to have my access to the servers restored as I've only been using the program for a few hours and couldn't have blown thru any data limits. 

Best,

Jack 
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback

**Comment by jacklfreedman** [comment]
The issue has seemingly been resolved, as my pro subscription has been reset.. 

Best,

Jack

**Comment by UltimateAmitieKaiNiC** [comment]
GPU has a permanent limit

**Comment by BenisonSam** [comment]
@jacklfreedman What did you do? How was the pro subscription reset?
