### ISSUE TITLE
Getting This Error: Error Could not load the JavaScript files needed to display output. This is probably because your Google Account login access has expired or because third-party cookies are not allowed by your browser.  Please reload this page.

### ISSUE THREAD

**Issue by beniyuu** [googlecolab/colabtools#2582]
**Describe the current behavior**

Notebook throws this error:

```
Error
Could not load the JavaScript files needed to display output.
This is probably because your Google Account login access has expired or because third-party cookies are not allowed by your browser.

Please reload this page.
```

For a few days now. Two days ago, it just pops up whenever I run a JavaScript-based cell, but now it also shows up whenever I start Colab.

![GIF to show](https://user-images.githubusercontent.com/31402170/151179204-f9e0bada-d59a-4013-a8a6-a4a489dd0f69.gif)

The issue vanishes when I use incognito or VirtualBox. I could do this work around, but I believe everyone could agree that if we can work where we regularly do without the added effort, we would prefer that, right?

**Describe the expected behavior**
To be able use JS-based integrations without error and not have the error pop up, I guess?

**What web browser you are using**
Browser: Brave - Version 1.34.81 Chromium: 97.0.4692.99 (Official Build) (64-bit)
Machine: Windows 10.0.19044 Build 19044

**Additional context**

[Minimal notebook code to reproduce the issue: ]()
https://colab.research.google.com/drive/1b86gMDh45b5uoe3fdu0CEokUvyH5awH-?usp=sharing

[Steps taken to address:]()
- Reset and factory reset runtime
- Cleared cache, history, cookies
- Allowed third-party cookies, and added [*.]googleusercontent.com
- Disabled all extensions
- Reset browser profile
- Turned off ad blocker
- Turned off Brave browser-specific features
- Logged out and back in of my Google account
- Restarted browser
- Restarted PC
- Tried with Explorer, Firefox, Chrome
- Whitelisted browser in Windows Firewall
- Tried a VPN

Looking forward to your responses. Thanks!

**Comment by cperry-goog** [comment]
Our best guess because this works in incognito you've got a conflicting extension breaking things.

**Comment by beniyuu** [comment]
> Our best guess because this works in incognito you've got a conflicting extension breaking things.

But why didn't the issue get resolved when I removed all the extensions? Literally deleted everything and it still does that.

**Comment by zahramahani** [comment]
i have the same problem

**Comment by razafD** [comment]
Have you fix it? I have this issue too. For me, sometimes, it works well and sometimes it's not working. Sometimes in one browser with two different notebooks, one works and the others not. I do not understand what the problem is

**Comment by Nayrouzzz** [comment]
Disconnect and Delete runtime. It worked for me.

**Comment by richy1996** [comment]
still having this error

**Comment by lopshopedun** [comment]
I had the same problem so I disabled Anti-Banner in Kaspersky Standard Anitvirus, and then the problem disappeared

**Comment by ingenarel** [comment]
i'm using tor and i'm having this issue too

**Comment by JF11579** [comment]
did anyone figure out a solution.  It is May 2024, a year later , and now I am getting that same error. I am trying to run some python code that uses Plotly.  A few days ago all was fine but now ruination! On a linux mint machine i got the error running in colab as well as aws and as well as on a mac.  Any ideas what is happening?  I tried every solution stated above

**Comment by g-i-o-r-g-i-o** [comment]
Same, incredible. No interfering plugin, same problem in Private Windows.

**Comment by Pesolo** [comment]
> Disconnect and Delete runtime. It worked for me.

worked pretty well for me

**Comment by itsmuhammad001** [comment]
> did anyone figure out a solution. It is May 2024, a year later , and now I am getting that same error. I am trying to run some python code that uses Plotly. A few days ago all was fine but now ruination! On a linux mint machine i got the error running in colab as well as aws and as well as on a mac. Any ideas what is happening? I tried every solution stated above

I'm getting the problem were you able to solve it?

**Comment by itsmuhammad001** [comment]
> > Disconnect and Delete runtime. It worked for me.
> 
> worked pretty well for me

Can you please explain how you did it?

**Comment by xeroxism** [comment]
**FOR BRAVE BROWSER:**
In the [browser settings][1] (URL: **brave://settings/content/javascript?search=permission**)

Under **Customized behaviors** > **Allowed to use JavaScript** > click on the **ADD** button and input the following URL:

"***drive.google.com***"

Then reload the Google Colab web page. It worked for my Brave Browser.


  [1]: https://brave://settings/content/javascript?search=permission

**Comment by xeroxism** [comment]
**FOR BRAVE BROWSER:**
In the [browser settings][1] (URL: **brave://settings/content/javascript?search=permission**)

Under **Customized behaviors** > **Allowed to use JavaScript** > click on the **ADD** button and input the following URL:

"***drive.google.com***"

Then reload the Google Colab web page. It worked for my Brave Browser.


  [1]: https://brave://settings/content/javascript?search=permission

**Comment by g-i-o-r-g-i-o** [comment]
why is this closed, I have been getting it for years on firefox, it's driving me mad
