### ISSUE TITLE
Upgrade pandas pinned version from 1.1

### ISSUE THREAD

**Issue by aebrahim** [googlecolab/colabtools#2583]
**Describe the current behavior**
`import pandas; print(pandas.__version__)` gives `1.1.5`
`pip install pandas --upgrade` now gives the following error
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas~=1.1.0; python_version >= "3.0", but you have pandas 1.3.5 which is incompatible.
```

**Describe the expected behavior**
I would like to be able to use a more recent pandas build, such as 1.3.5 or 1.4 to work around some bugs.

**What web browser you are using**
Chrome

**Comment by aebrahim** [comment]
I believe the simplest fix would be changing `'pandas~=1.1.0; python_version >= "3.0"',` in `setup.py` to use `>=` instead of `~=`

**Comment by cperry-goog** [comment]
tracked internally at b/216670100

**Comment by craigcitro** [comment]
Thanks for the bug -- this should be fixed!
