### ISSUE TITLE
Colab: wrong delimiter in csv file previewer

### ISSUE THREAD

**Issue by qkzk** [googlecolab/colabtools#2584]
When you open a CSV file with other delimiter than comma, the previewer is wrongly formatted.

Please execute the sample below.

[Colab wrong delimiter in csv file](https://gist.github.com/qkzk/c019c93136ac54312e98243a88bb0eb3)

Then execute the code cell, it will download the file on colab,
Open it with the previewer, the columns aren't displayed correctly.

Why not allow to change the delimiter from a simple menu above the previewer ?

**Comment by blois** [comment]
Thanks for the feedback, in the meantime the delimiter can be converted with something like:

```python
pd.read_csv('rando.csv', delimiter=';').to_csv('rando2.csv', index=False)
```

**Comment by qkzk** [comment]
Thank you very much I didn't knew and my students will love it :)
