### ISSUE TITLE
[ColabPro] " ValueError: pyarrow.lib.Codec size changed, may indicate binary incompatibility. "

### ISSUE THREAD

**Issue by Halegua** [googlecolab/colabtools#2592]
I've been using ColabPro to run some Machine Learning models for a few weeks now, and suddenly, today I've come across an error that has persisted, even without having changed the code in any instance. I have been researching what could have been the reason for this problem but I have not been successful, and this has effectively made it impossible for me to use ColabPro, and to continue my work.
Here is the error I have received:

`/usr/local/lib/python3.7/site-packages/cudf/_lib/__init__.py in <module>()
      2 import numpy as np
      3 
----> 4 from . import (
      5     avro,
      6     binaryop,

cudf/_lib/avro.pyx in init cudf._lib.avro()

cudf/_lib/column.pyx in init cudf._lib.column()

cudf/_lib/scalar.pyx in init cudf._lib.scalar()

cudf/_lib/interop.pyx in init cudf._lib.interop()

ValueError: pyarrow.lib.Codec size changed, may indicate binary incompatibility. Expected 48 from C header, got 40 from PyObject`

[In this link](https://drive.google.com/file/d/1Zi-w5OZZ2wV8rd656EcU_SXkRnVArHNp/view?usp=sharing) can be found a copy of my notebook in which the error appears, regardless of the variables I have tried. I need to receive some kind of support ASAP.

**Comment by craigcitro** [comment]
This looks like an upstream issue, tracked here: https://github.com/rapidsai/cudf/issues/10187
