### ISSUE TITLE
google colab error

### ISSUE THREAD

**Issue by bargac** [googlecolab/colabtools#2593]
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**

Using chrome  98.0.4758.82

using google colab to run:

num = int(input("Type a number... "))
print(1*num)

and inputting a number, like 5 gives me error

TypeError                                 Traceback (most recent call last)
[<ipython-input-69-14bdb03263fa>](https://localhost:8080/#) in <module>()
----> 1 num = int(input("Type a number... "))
      2 print(1*num)

TypeError: 'int' object is not callable

**Additional context**
https://colab.research.google.com/drive/1GEnIt5WTgRqYx1zEl56z6ksT-45CdmYK?usp=sharing

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
I expect to get 1* the inputted number. 

-----

**Comment by bargac** [comment]
https://colab.research.google.com/drive/1GEnIt5WTgRqYx1zEl56z6ksT-45CdmYK?usp=sharing

**Comment by craigcitro** [comment]
I suspect you've redefined `int` at some point in your session; `Runtime` -> `Restart runtime` will get you back up and running.
