### ISSUE TITLE
NSE(National Stock Exchange) API not working on Google colab

### ISSUE THREAD

**Issue by Radhika-Keni** [googlecolab/colabtools#2596]
Hi Google Colab Team , 
                                          The **nsepy** API is not working correctly on colab. The  " get_history" function **runs indefinitely**.It does not throw any errors.
Please take note that the same code works on a local Jupyter environment.

I have attached  a screenshot for the same 
![Collab_Issue_With_nsepy](https://user-images.githubusercontent.com/68383273/152485784-6449b16d-2069-4154-aa8a-afb8c94235da.png)

**Comment by craigcitro** [comment]
I'd try asking upstream on the nsepy repo.

**Comment by Radhika-Keni** [comment]
Thanks , that worked
