### ISSUE TITLE
Installation of pytorch 

### ISSUE THREAD

**Issue by prajjwal1** [googlecolab/colabtools#26]
I've tried using 
`!pip install -q http://download.pytorch.org/whl/cu75/torch-0.2.0.post3-cp27-cp27mu-manylinux1_x86_64.whl torchvision
import torch
`
Output:
`torch-0.2.0.post4-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform.
`
I've also tried building from the source but conda is not well supported.
I've tried installing with torch 0.3 as well, it shows the same output. Can you update the snippet for installation of Pytorch for manylinux for colab.

**Comment by tfriedel** [comment]
https://jovianlin.io/pytorch-with-gpu-in-google-colab/

**Comment by CSEMike** [comment]
Thanks for the report. We've updated the pytorch snippet to be robust to new configurations.

**Comment by pointyointment** [comment]
You can now just do `!pip install torch` or `!pip3 install torch`.
