### ISSUE TITLE
cannot import pip updated scipy package

### ISSUE THREAD

**Issue by mmilosav** [googlecolab/colabtools#260]
Notebook is failing to import the pip updated version:
```
!pip install --upgrade scipy
import scipy
print(scipy.__version__)
```
prints:
```
Collecting scipy
  Downloading https://files.pythonhosted.org/packages/a8/0b/f163da98d3a01b3e0ef1cab8dd2123c34aee2bafbb1c5bffa354cc8a1730/scipy-1.1.0-cp36-cp36m-manylinux1_x86_64.whl (31.2MB)
    100% |████████████████████████████████| 31.2MB 1.4MB/s 
Requirement already satisfied, skipping upgrade: numpy>=1.8.2 in /usr/local/lib/python3.6/dist-packages (from scipy) (1.14.5)
Installing collected packages: scipy
  Found existing installation: scipy 0.19.1
    Uninstalling scipy-0.19.1:
      Successfully uninstalled scipy-0.19.1
Successfully installed scipy-1.1.0
0.19.1
```
Note that the imported version == 0.19.1 is not the installed version == 1.1.0.  Restarting the runtime, etc., does not help.  Thanks.

**Comment by craigcitro** [comment]
The problem here is just python module caching -- you have to restart your runtime *after* upgrading `scipy`. (I just confirmed this worked in a fresh runtime.)

If you're restarting after install and it's not working, please share a notebook demonstrating the problem and we'll take a look.

**Comment by mmilosav** [comment]
Thank you. The restart between the pip install and the import works but is problematic when sharing.  I am teaching an introductory undergraduate class and would like to share a notebook demo requiring scipy-1.1 with the students. It substantially complicates student experience to be required the restart after the pip install workaround.

**Comment by craigcitro** [comment]
Agreed that it's not stellar. 

You can also do it programmatically: 

    import os
    import signal
    os.kill(os.getpid(), signal.SIGTERM)

When you execute that cell, the next attempt to execute (eg ctrl-enter or run button) will automatically reconnect to the just-restarted kernel.
