### ISSUE TITLE
from object_detection.builders import model_builder  error

### ISSUE THREAD

**Issue by nguaki** [googlecolab/colabtools#2605]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
Getting this error:

from object_detection.builders import model_builder
ImportError                               Traceback (most recent call last)
[<ipython-input-51-a71a6c59c4ac>](https://localhost:8080/#) in <module>()
      4 from object_detection.utils import visualization_utils as viz_utils
      5 
----> 6 from object_detection.builders import model_builder
      7 from object_detection.utils import config_util

9 frames
[/usr/local/lib/python3.7/dist-packages/keras/api/_v1/keras/backend/__init__.py](https://localhost:8080/#) in <module>()
     21 from keras.backend import bias_add
     22 from keras.backend import binary_crossentropy
---> 23 from keras.backend import binary_focal_crossentropy
     24 from keras.backend import binary_weighted_focal_crossentropy
     25 from keras.backend import cast

ImportError: cannot import name 'binary_focal_crossentropy' from 'keras.backend' (/usr/local/lib/python3.7/dist-packages/keras/backend.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
**Describe the expected behavior**

Where did this error come from?
This was stable for a couple of months.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by AlexBlackNn** [comment]
pip install keras==2.7.0 works for me

**Comment by cperry-goog** [comment]
We'll need a minimal public repro notebook to investigate.

**Comment by blois** [comment]
See https://github.com/googlecolab/colabtools/issues/2600
