### ISSUE TITLE
sync delay on colab google drive mount

### ISSUE THREAD

**Issue by yhgon** [googlecolab/colabtools#2607]
**Describe the current behavior**
I mount google drive in colab api. 
and I write scratch file and checkpoint file on mounted directory for each iteration. 
(write log text file in each iter, save checkpoint file in 100M iter, appended output in singlefile in 1M iter ) 

```
total 3.2G
-rw------- 1 root root 3.2M Feb  9 01:19 file_A  <-- initial data
-rw------- 1 root root 3.2M Feb  9 00:42 file_B  <-- final data
-rw------- 1 root root 3.1G Feb  9 01:19 file_C  <--large scratch  ( appended data  in every 1M iter )
-rw------- 1 root root 5.0M Feb  9 01:19 file_D <-- log text
-rw------- 1 root root  40M Feb  9 01:19 file_E  <-- last_checkpoint(overwrite)
```

to download these files from google drive, 
I connect google drive on other browser tab. 
when I check the file in google drive page in web browser, 
small log file(5MB) and checkpoints files(40MB) is synced correctly. 

However, large appended scratch file(3GB) is not synced in google drive from colab result.  
the file is appeared but size is 0byte in google drive web browser.
when I wait, it is synced after 30 minutes.  (sync log in google drive web page : Feb  9 01:43)

**Describe the expected behavior**
check synced file on google drive and download it from web browser. 
I want to know force sync option

**What web browser you are using**
Chrome

**Additional context**

**Comment by craigcitro** [comment]
The only hook we have here is `drive.flush_and_unmount()` -- as the name implies, it will wait for all pending writes to complete, unmount drive, and return. (You can then re-mount drive if needed.)
