### ISSUE TITLE
Colab Freezes at step Collecting statsmodels>=0.11   Using cached statsmodels-0.13.2.tar.gz (17.9 MB)

### ISSUE THREAD

**Issue by tomwilson41986** [googlecolab/colabtools#2609]
**Describe the current behavior**
Myself and other users are experiencing an issue with Colab this morning. 

When installing dependencies, Colab is crashing on the step

Collecting statsmodels>=0.11
  Using cached statsmodels-0.13.2.tar.gz (17.9 MB)

We are trying to install:
!pip install deeplabcut
!pip install opencv-python-headless==4.5.1.48
!pip install --upgrade tables
!pip install tensorflow==2.7

**Describe the expected behavior**
Dependencies usually install within 2-3 mins. Now it is freezing for over 1 hour.

**What web browser you are using**
Chrome

https://colab.research.google.com/drive/1YbTE3snFNIjQ3l2J1NQ2C4O8ER7tWxf-?usp=sharing

**Comment by skanda-trmb** [comment]
Facing the same issue. Any solution?

**Comment by craigcitro** [comment]
I just tried this in a fresh VM and can't reproduce this -- are you still having trouble?

**Comment by tomwilson41986** [comment]
Thanks this is now resolved
