### ISSUE TITLE
ValueError: tf.enable_eager_execution must be called at program startup.

### ISSUE THREAD

**Issue by mymusise** [googlecolab/colabtools#261]
Met this error when I running the example of **Neural Machine Translation with Attention** in [Colab](https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/contrib/eager/python/examples/nmt_with_attention/nmt_with_attention.ipynb)
I found a similar issue. [https://github.com/tensorflow/tensorflow/issues/18304](https://github.com/tensorflow/tensorflow/issues/18304) But it does not work if I reset the environment，What should I do?

**Comment by 824zzy** [comment]
me too!!!! Please help!!!

**Comment by nexolute** [comment]
This happens whenever I am using a GPU instance, but never on CPU instance.

Here is a minimal code snippet to reproduce the error:

```
import tensorflow as tf
tf.enable_eager_execution()
```

**Comment by craigcitro** [comment]
This was a bug on our side, fix is live. If you restart any runtimes that weren't working (or Runtime -> Restart all runtimes), you should be all set. Please open a new issue if you're still seeing trouble, and sorry about the trouble!
