### ISSUE TITLE
tensorflow_federated not importing

### ISSUE THREAD

**Issue by amiranees88** [googlecolab/colabtools#2616]
Hi.. I am trying to use tensorfloe_federated in Google Colab.. but its giving me an error "No module named 'tensorflow_federated"

Can anyone please help me in this?

**Comment by cperry-goog** [comment]
`!pip install tensorflow-federated`

You'll need to run that command before you attempt to import.

**Comment by hussain939** [comment]
No module named 'tensorflow_federated' how to fix ?
