### ISSUE TITLE
Python version is not updating [BUG]

### ISSUE THREAD

**Issue by jainam1997** [googlecolab/colabtools#2618]
Steps to reproduce:

1. Install conda
%%bash
MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh
MINICONDA_PREFIX=/usr/local
wget https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT
chmod +x $MINICONDA_INSTALLER_SCRIPT
./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX

2.!conda create --name env_new0
3.!source activate env_new0
4.
!python --version
!python --version
import sys
print(sys.version)

**Output**
Python 3.6.5 :: Anaconda, Inc.                              --> Here it is showing the python version -> 3.6.5
3.7.12 (default, Jan 15 2022, 18:48:18)                --> Here it is showing the python version -> 3.7.5
[GCC 7.5.0]

5.
!pip install -q torch==0.4.1 torchvision==0.2.2 -f https://download.pytorch.org/whl/torch_stable.html
!python --version
import platform
import torch
print(torch.__version__, " - ", platform.python_version())

**Output**
Python 3.6.5 :: Anaconda, Inc.    --> Here it is showing python 3.6.5
1.10.0+cu111  -  3.7.12          --> Here it is showing torch version latest, python latest version

Even though we have installed torch 0.4.1, torchvision 0.2.2 , we are getting torch version of latest version.

**Comment by cperry-goog** [comment]
We don't support Conda at this time, closing this issue.
