### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python.keras.preprocessing'

### ISSUE THREAD

**Issue by arupkrdas2008** [googlecolab/colabtools#2623]
My code was running fine in Colab+ and then suddenly started to have problem.

ModuleNotFoundError: No module named 'tensorflow.python.keras.preprocessing'

And it can not find any of the module even though they were working just fine till yesterday

from tensorflow.python.keras.preprocessing.image import ImageDataGenerator

from tensorflow.keras.models import Sequential
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras import optimizers

**Comment by craigcitro** [comment]
You're right that this changed underneath you: we've just upgraded to TensorFlow 2.8, which deprecated the keras imports you were using. ([original commit](https://github.com/tensorflow/tensorflow/commit/91e853c47c1cc280af1d8ed1b6b3ca16179c71fc))

Options:
* update your code (I believe `from tensorflow.keras.preprocessing.image import ImageDataGenerator` is what you're looking for)
* install an older TF version
