### ISSUE TITLE
cuDNN failed to initialize

### ISSUE THREAD

**Issue by tomwilson41986** [googlecolab/colabtools#2624]
Colab is crashing due to a cuDNN error.

UnknownError: 2 root error(s) found.
  (0) UNKNOWN: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node resnet_v1_50/conv1/Conv2D}}]]
	 [[Sigmoid/_545]]
  (1) UNKNOWN: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node resnet_v1_50/conv1/Conv2D}}]]
0 successful operations.
0 derived errors ignored.
![image](https://user-images.githubusercontent.com/95654146/154229690-e86e556b-2c56-4f21-9af4-a3b39c1c9de2.png)

**What web browser you are using**
Chrome

**Additional context**
https://colab.research.google.com/drive/1YbTE3snFNIjQ3l2J1NQ2C4O8ER7tWxf-?usp=sharing.

**Comment by SauBuen** [comment]
This is related to [#10505](https://github.com/tensorflow/models/issues/10505) and  [#2626](https://github.com/googlecolab/colabtools/issues/2626)

**Comment by cperry-goog** [comment]
Duping with #2600
