### ISSUE TITLE
loaded wrong runtime CuDNN version

### ISSUE THREAD

**Issue by mingweichua** [googlecolab/colabtools#2626]
Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version.

**Comment by SauBuen** [comment]
I have the same issue [#10505](https://github.com/tensorflow/models/issues/10505)

**Comment by cperry-goog** [comment]
Can you link a minimal repro notebook?

**Comment by cperry-goog** [comment]
On second thought, duping with #2600
