### ISSUE TITLE
constantly running into a loop of requirements

### ISSUE THREAD

**Issue by KakoozaJerry** [googlecolab/colabtools#2627]
When I run 
`!pip install TTS`

Previously , 2 days back , I would be able to run
`!tts --list_models` 

Without an error.

Right now, I am running into a numpy error since your update. There has been no update at all on the TTS library and also it sets a predefined numpy version of 1.19.5 as a requirement to run that library .

I think am running into a constant loop of requirement errors from your update

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
[view more detailed explanation of it on GitHub](https://github.com/coqui-ai/TTS/discussions/1247#discussioncomment-2189596)

**Comment by craigcitro** [comment]
AFAICT the problem is that `tts` is requesting `numpy==1.19.5`, but only works in practice with `numpy==1.21.5`. If you reinstall the correct numpy version after you should be up and running (as per the linked issue).
