### ISSUE TITLE
error cannot log in multiple drive accounts

### ISSUE THREAD

**Issue by lythatda1997** [googlecolab/colabtools#2632]
I don't know if it's okay to ask this here. I can't use a drive other than the one I'm logged into colab with.
![Screenshot_20220219-103253_Chrome](https://user-images.githubusercontent.com/81241248/154785119-0795f3fa-1502-489d-a9d8-b4de3f980146.jpg)
![Screenshot_20220219-103502_Chrome](https://user-images.githubusercontent.com/81241248/154785123-b252dd1e-273e-48cb-b495-a80c1024c9ed.jpg)

**Comment by cperry-goog** [comment]
We've rolled out a new, more secure method to mount Google Drive. This requires using the same account to mount Google Drive as you use for notebook code execution.

If you require data from another account, you can share that data between accounts and add a shortcut to view that file or folder in your Drive when mounted in Colab [1]

Report any issues accessing shared content. If you experience issues mounting Drive from the same account, please do the following:

Runtime -> Factory Reset Runtime
drive.mount() using the account with which you are logged in to Colab

And then send feedback in product: Help > Send feedback.

[1] https://support.google.com/drive/answer/9700156
