### ISSUE TITLE
Import from tensorflow.keras import layers      could not be resolved

### ISSUE THREAD

**Issue by YustasDev** [googlecolab/colabtools#2637]

**Comment by YustasDev** [comment]
![error1](https://user-images.githubusercontent.com/65298804/155132351-aa569525-32cb-42a7-8b9c-f9f971e5fa6e.jpg)

**Comment by blois** [comment]
This is a diagnostic error which is from static analysis, it's getting tripped up on https://github.com/tensorflow/tensorflow/blob/57a903a9ea32f02731a1e89b8067b20206633ae7/tensorflow/api_template.__init__.py#L91.

My understanding is that this should be equivalent to `from keras import layers`
