### ISSUE TITLE
get doc in code manner

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#2638]
I get something like this -
![Screenshot (1038)](https://user-images.githubusercontent.com/43755000/155278213-07eb34dd-378b-4ee6-93b2-c812d00835e9.png)
![Screenshot (1039)](https://user-images.githubusercontent.com/43755000/155278217-3aebe0de-a9cb-4924-9484-32f647dba0f7.png)

desired -
![Screenshot (1041)](https://user-images.githubusercontent.com/43755000/155278318-4ef178bc-0693-40b1-8e5c-bbdadb561448.png)

**Comment by blois** [comment]
Would this be something like:

```python
import csv
csv.writer?
```
