### ISSUE TITLE
Error on Pip install

### ISSUE THREAD

**Issue by mihirjoshi21** [googlecolab/colabtools#264]
Everything was working fine till yesterday but suddenly I am experiencing problem.

`!pip install -U gensim`

And this is the error log.
```
get_ipython().system('pip install -U gensim')
MessageError: Error: Unknown request type: cell_update_stdin
```

**Comment by craigcitro** [comment]
Just to check -- does the problem go away if you refresh the tab you're viewing the notebook in?

**Comment by mihirjoshi21** [comment]
@craigcitro Thank you, sir. It didn't occur to me I was just restarting runtime and terminating sessions which obviously didn't help.
