### ISSUE TITLE
Dont run EXE file on Google Colab

### ISSUE THREAD

**Issue by ivanoffskiy** [googlecolab/colabtools#2640]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by ivanoffskiy** [comment]
please> help me, 
dont open EXE file on google colab

**Comment by cperry-goog** [comment]
We don't support running Windows binaries (.exe) in Colab.
