### ISSUE TITLE
i cant download skill share Courses on  google colab

### ISSUE THREAD

**Issue by senuthsathviru** [googlecolab/colabtools#2641]
hello,
 im using microsoft edge browser. i use your code to download skill share Courses to google drive but now it's not work. the problem is when i click (_**Run this Cell to Download Skillshare Course**_) it will download first video only. after i get this error 

### Traceback (most recent call last):
File "/root/.skillshare/dl.py", line 33, in <module>
    main()
  File "/root/.skillshare/dl.py", line 11, in main
    dl.download_course_by_url(course_url)
  File "/root/.skillshare/skillshare.py", line 29, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/root/.skillshare/skillshare.py", line 32, in download_course_by_class_id
    data = self.fetch_course_data_by_class_id(class_id=class_id)
  File "/root/.skillshare/skillshare.py", line 69, in fetch_course_data_by_class_id
    assert res.status_code == 200, 'Fetch error, code == {}'.format(res.status_code)
AssertionError: Fetch error, code == 403

 .i try to download so many Courses but it happen again and again.so i try in chrome but it never fix.
please fix this Bug. 
Thank you...

**Comment by cperry-goog** [comment]
Can you point us to a notebook where this occurs?

**Comment by SEREPie** [comment]
same issue

**Comment by senuthsathviru** [comment]
> Can you point us to a notebook where this occurs?
what you meen

**Comment by senuthsathviru** [comment]
> same issue

have any idea to Fix this??

**Comment by senuthsathviru** [comment]
![image](https://user-images.githubusercontent.com/90859537/156894835-c663c6b9-35fd-4d1b-9f8d-0e09b8087ac8.png)

**Comment by SEREPie** [comment]
no 

> > same issue
> 
> have any idea to Fix this??

no, I'm just saying I'm having the same issue

**Comment by cperry-goog** [comment]
I looked around in the notebook, I think you should ask upstream to the Skillshare folks.

**Comment by senuthsathviru** [comment]
I think they changed the way the link in the course is generated. i mean the old site will generated one line to the full course but now the link will change form video to video

**Comment by senuthsathviru** [comment]
> no
> 
> > > same issue
> > 
> > 
> > have any idea to Fix this??
> 
> no, I'm just saying I'm having the same issue

oh ok

**Comment by Sachiii4** [comment]
Dose anyone have a solution for this?

**Comment by mco-gh** [comment]
Please refer this issue to the provider of the software you're trying to use for help debugging this issue. Also, if this software violates Skillshare's terms of service, please don't use it.
