### ISSUE TITLE
''Too many sessions'' message when I don't even have an open session.

### ISSUE THREAD

**Issue by DLCs2001** [googlecolab/colabtools#2643]
Hello, right now I'm trying to start a session in Google Colab, but I can't because I always get a message saying that ''I have too many sessions'' open, which is incorrect and illogical, since I don't even have a single session open.
Anyone else experiencing the same problem as me?
![Screenshot 2022-02-28 22 29 46](https://user-images.githubusercontent.com/100662407/156105622-2d84ba8a-57b8-45be-a12e-6812a32ff441.png)
![Screenshot 2022-02-28 22 30 16](https://user-images.githubusercontent.com/100662407/156105638-b45cffa6-a718-4f19-abaa-38ec9bc021bc.png)

**Comment by al-sarraj** [comment]
Me 2 :(  ,,, is there any solving for the problem ???!!

**Comment by olivethrush** [comment]
Yes, same issue; same notification. Grateful for solution

**Comment by Alesiosaruri** [comment]
Same problem, I have no active sessions.
The real problem is that I have the same error in all the google accounts I tried, even in the ones I created today

**Comment by vanz1938** [comment]
Same here...

**Comment by vtsgarbee** [comment]
same.

**Comment by Kaiten10** [comment]
Glad to know I'm not the only one. It only started happening today, with all my accounts.

**Comment by craigcitro** [comment]
For anyone who's encountering this: can you click `Help` -> `Send feedback` in Colab and include a link to this github issue?

**Comment by vanz1938** [comment]
> For anyone who's encountering this: can you click `Help` -> `Send feedback` in Colab and include a link to this github issue?

Just did it ;)

**Comment by vanz1938** [comment]
> Thanks for submitting feedback (feel free to continue). Looks to be related to highmemory GPU requests, a possible workaround right now would be to create a new notebook and copy all the cells into it (Edit->Select all cells, copy/paste). Continuing investigation.

It worked! Thanks a lot! :)

**Comment by algarde** [comment]
Same problem here and the workaround doesn't solve it. When starting the runtime I have immediately this error: "NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running."

**Comment by blois** [comment]
@algarde You'll need to specify GPU in Edit -> Notebook Settings.

**Comment by algarde** [comment]
@blois you're right, sorry!

**Comment by sebbov** [comment]
The problem should be fixed and your original notebooks should now work again.  Let us know (`Help` -> `Send feedback`) if you still see the issue.
