### ISSUE TITLE
pip install doesn't correctly install in "High Runtime" mode 

### ISSUE THREAD

**Issue by mzamek** [googlecolab/colabtools#2647]
**Describe the current behavior**
This notebook works fine in "standard" runtime. If I switch to "High Runtime" it gives me error: ModuleNotFoundError: No module named 'mlrose_hiive'

**Describe the expected behavior**
I expect that pip install correctly installs library

**What web browser you are using**
Chrome

**Additional context**
[https://colab.research.google.com/drive/1R0ljJF5SumcJ0K_q-isMqB6tnoM_fhun?usp=sharing](url)
here you can see issue with importing library in "High Runtime" mode
![image](https://user-images.githubusercontent.com/1072315/156530118-adc2b866-77f8-490e-8488-176632e4d037.png)
Here you can see it works correctly in "standard" mode:
![image](https://user-images.githubusercontent.com/1072315/156530246-668ba2f9-5784-43f2-b538-6fbae27535ba.png)

**Comment by cperry-goog** [comment]
After switching to a Highmem runtime, did you re-run the cell with the pip install command?

**Comment by mzamek** [comment]
> After switching to a Highmem runtime, did you re-run the cell with the pip install command?

yes

**Comment by mzamek** [comment]
this didn't work today at around 1am PST. It works now as intended.

**Comment by mzamek** [comment]
This is resolved now
