### ISSUE TITLE
Getting --[no-]launch-browser flags are deprecated Warning on Google Colab

### ISSUE THREAD

**Issue by neuralpicorp** [googlecolab/colabtools#2650]
**Describe the current behaviour**
Upon using the `auth` module from `google.colab`, the following warning pops up:
_

> WARNING: The --[no-]launch-browser flags are deprecated and will be removed in future updates. Use --no-browser to replace --no-launch-browser.

_

**Describe the expected behaviour**
No warning should pop up (please add the new flags as suggested in [Google Cloud CLI - Release Notes](https://cloud.google.com/sdk/docs/release-notes))

**Code:**
```
from google.colab import auth
auth.authenticate_user()
```

**Comment by colaboratory-team** [comment]
b/222692238 for internal tracking

**Comment by colaboratory-team** [comment]
Warning no longer appears, closing
