### ISSUE TITLE
'! gdown --id file_id_on _drive' in colab is giving access error.

### ISSUE THREAD

**Issue by krharish05** [googlecolab/colabtools#2655]
'! gdown --id file_id_on _drive' is giving an access error even when the access level for the file in Google Drive is set as 'Anyone with the link'.
A month ago I used to load files and datasets from Drive using !gdown and it worked fine but now it is not working and giving errors.
![colab_error](https://user-images.githubusercontent.com/99948695/156894276-a80c2139-b7b3-4b2d-a2c5-d375e9a1140a.JPG)

**Comment by craigcitro** [comment]
This is a large upstream change on the Drive side [docs](https://developers.google.com/drive/api/v3/resource-keys): files need a resource key or to have their sharing settings changed.
