### ISSUE TITLE
PATH export command does not work in Google colab

### ISSUE THREAD

**Issue by AliZebardastinik** [googlecolab/colabtools#2659]
Hello
I'm going to install the fire simulator software code with the link 
(https://github.com/firemodels/fds/releases/download/FDS6.7.7/FDS6.7.7_SMV6.7.18_rls_lnx.sh) on the google colab Linux operating system To. But the installation does not work because the export PATH command does not work.
Like code
!export PATH=$PATH:/.../bin
please guide me

**Comment by yeounoh** [comment]
This worked for me,
```
import os
os.environ['PATH'] += '/.../bin'
```

**Comment by AliZebardastinik** [comment]
thank you very much

**Comment by AliZebardastinik** [comment]
Thanks
