### ISSUE TITLE
Can't mount another google drive in Colab Pro+

### ISSUE THREAD

**Issue by mohammadnajeeb** [googlecolab/colabtools#2660]
**Problem**
Can't mount another google drive different from the one I am using in Colab Pro+ because of the credential error.
I can log in to another account and give permission. However, the tab close automatically and I can't mount it.

Earlier this problem can be fixed by using "drive._mount('/content/drive')" instead of "drive.mount('/content/drive')".

**Environment:**
Google Chrome Version 99.0.4844.51 (Official Build) (64-bit), Windows 11 Home 64bit

**What is the solution?

"drive._mount('/content/drive')" method not working:
![pic 1](https://user-images.githubusercontent.com/30042087/157282913-e17c7eb4-6555-453e-aeff-970a407f0574.jpg)

2nd way: normal mounting-
![pic 2](https://user-images.githubusercontent.com/30042087/157282921-44154d64-0d07-4de4-87d2-9352c3428d8e.jpg)

Not working
![pic 3](https://user-images.githubusercontent.com/30042087/157282925-81a2dfa1-5413-4b05-8f13-94e2cfba4cae.jpg)
**

**Comment by zavinono** [comment]
This is still an ongoing problem- I hope the team notes that there are many use cases- such as educational use where a google account cannot be used to purchase colab pro or colab pro+ however that is where data needs to be stored for monetary reasons and for data security reasons. This is making this service unusable to academics

**Comment by cperry-goog** [comment]
dupe with #2563
