### ISSUE TITLE
Getting OSError: [Errno 5] Input/output error when using MS COCO 2014 dataset to train a model using Google Collab Pro

### ISSUE THREAD

**Issue by maitreeedu92** [googlecolab/colabtools#2663]
**Describe the current behavior**
I am trying to train the official "Tensorflow Image Captioning" tutorial (https://www.tensorflow.org/tutorials/text/image_captioning) using the MS COCO 2014 dataset.

But it is giving "Getting OSError: [Errno 5] Input/output error" even though I am using Collab Pro and 2TB of Google Drive space.

**Describe the expected behavior**
The tutorial example should run on the MS COCO dataset. Google Drive time-out error should not appear while running Collab Pro.

**What web browser you are using**
Chrome, Collab Pro, Google Drive 2TB
Tensorflow official example
MS COCO dataset

**Additional context**

**Comment by cperry-goog** [comment]
I ran the Colab on just a normal runtime and couldn't repro the error, I think you might ask upstream to the Tensorflow authors.
