### ISSUE TITLE
wont work ckpt = torch.load(model_path, map_location='cpu'

### ISSUE THREAD

**Issue by mrfishydishy** [googlecolab/colabtools#2664]
**Describe the current behavior**
i run e4e completion and i get in EOFError on ckpt = torch.load(model_path, map_location='cpu')

**Describe the expected behavior**
i  expected  e4e completion and get a face 

i am using
Chrome

**Additional context**
https://colab.research.google.com/drive/10vHwVo1bjwCksA_BHPr5YncSRco32VjO?usp=sharing

**Comment by cperry-goog** [comment]
You'll need to talk to the author of the notebook

**Comment by mrfishydishy** [comment]
> You'll need to talk to the author of the notebook

how?
