### ISSUE TITLE
Account Google Colab Pro + was reset when running over than 24 Hours

### ISSUE THREAD

**Issue by Anantasak** [googlecolab/colabtools#2667]
I was running **long time process of Google Colab Pro +** for training model with very long time with process sequence2sequence machine translation per attach picture.
![0DSE95Z](https://user-images.githubusercontent.com/22325698/157737871-38e84006-8a6a-45ff-b4e4-304eae2d3eb9.png)

And all process was running as normally no code breakdown or crash but system was have limited function which reset all system running and make system can't running over 23 hour 30 minutes.  So I'm very sadly for that. Per about this issue we need Google Colab team address about this problem and **kindly fix this issue for prevent future case** that impact to our expect on using quality premium support from Google Colab Pro + which capable to running as background process but it's useless on this issue.

PS. I attach log file for further more investigation,Thanks. @fischman @craigcitro @jfsny @corrieann @blois 

- [ ] Fix on long time process running.
- [ ] Refund on any occurrence that not meet with SLA (Service Level Agreement)

![vk58VOt](https://user-images.githubusercontent.com/22325698/157739111-57de54ea-d9fa-4355-a6ed-f8e15349e36a.png)

[log for running processing MT.txt](https://github.com/googlecolab/colabtools/files/8226395/log.for.running.processing.MT.txt)

**Comment by cperry-goog** [comment]
If you require runtimes that last longer than 24 hours, you'll want to use our GCP Marketplace instance: https://research.google.com/colaboratory/marketplace.html

**Comment by Anantasak** [comment]
> If you require runtimes that last longer than 24 hours, you'll want to use our GCP Marketplace instance: https://research.google.com/colaboratory/marketplace.html

Thanks for your recommendation. We already done it on some private cloud server. It's seem to us that Price & Performance on GCP+ should better than GCP,right?

How ever, Seem to this is limitation of GCP+ which need to improve,Thanks.


![6vd6o2Q](https://user-images.githubusercontent.com/22325698/157774407-5cb4b999-0438-4b9c-98ad-0dc93ae174b7.png)
