### ISSUE TITLE
Couldnt import Pygame module

### ISSUE THREAD

**Issue by algaeginger** [googlecolab/colabtools#2671]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by algaeginger** [comment]
import pygame
import time

pygame.font.init()
screen = pygame.display.set_mode((800,600))
background = (0, 0, 0)
screen.fill((background))
myfont = pygame.font.Font(None, 90)
f = open("/Users/bgr/Desktop/Advice.txt","r")
for line in f:
    for word in line.split():
        text = myfont.render(word,1,(0,255,0))
        screen.blit(text, (300,300))
        pygame.display.update()
        time.sleep(0.2)
        screen.fill((background))
        pygame.display.update()
pygame.display.quit()

**Comment by cperry-goog** [comment]
You need to install first:

`!pip install pygame`
