### ISSUE TITLE
UnknownError: Graph execution error:  Fail to find the dnn implementation.  [[{{node CudnnRNN}}]]

### ISSUE THREAD

**Issue by Mennaruuk** [googlecolab/colabtools#2673]
**Describe the current behavior**
GPU cannot be used on the notebook below to train RNN. I get the following error:

```
30 texts collected.
Training new model w/ 3-layer, 128-cell LSTMs
Training on 5,296 character sequences.
Epoch 1/20
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
[<ipython-input-5-766a9f967633>](https://localhost:8080/#) in <module>()
     18     max_length=model_cfg['max_length'],
     19     dim_embeddings=100,
---> 20     word_level=model_cfg['word_level'])

4 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

UnknownError: Graph execution error:

Fail to find the dnn implementation.
	 [[{{node CudnnRNN}}]]
	 [[model_1/rnn_1/PartitionedCall]] [Op:__inference_train_function_9347]
```

**Describe the expected behavior**
GPU can be used without an error being raised by Colab.

**What web browser you are using**
Brave

**Additional context**
**Notebook**: https://drive.google.com/file/d/1mMKGnVxirJnqDViH7BDJxFqWrsXlPSoK/view
Crash occurs at the third step.

Others have reproduced this error, all in 2022:
https://github.com/minimaxir/textgenrnn/issues/254#issue-1159788194
https://github.com/INVESTAR/StockAnalysisInPython/issues/131#issue-1121592822
https://github.com/Dobiasd/frugally-deep/issues/317

**Comment by SanjibSarkarU** [comment]
I faced the same error when running my code on google chrome

UnknownError                              Traceback (most recent call last)
[<ipython-input-171-65cf2dcccab3>](https://localhost:8080/#) in <module>()
      3 epochs = 50
      4 
----> 5 model.fit(train_coor, epochs=epochs, verbose=1)

1 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

UnknownError: Graph execution error:

Fail to find the dnn implementation.
	 [[{{node CudnnRNN}}]]
	 [[sequential/lstm/PartitionedCall]] [Op:__inference_train_function_29932]

**Comment by DenSmugg** [comment]
Any updates? Faced same error

**Comment by WZHOU007-0912** [comment]
This might be the worst solution, but it worked for me that I just uninstalled the tensorflow and keras and then re-installed them in my google colab.

**Comment by cperry-goog** [comment]
Duping with #2656

**Comment by varunponda** [comment]
Does anyone have any other work around?

**Comment by idrisdemir** [comment]
I downgraded tensorflow version. it works for me.

**Comment by varunponda** [comment]
@idrisdemir Thanks for the solution. This version solved my problem ```!pip install -U tensorflow==2.8.2```

**Comment by aaadddiiii** [comment]
> !pip install -U tensorflow==2.8.2

@varunponda such a saviour!! From morning it was giving me this error and I had nothing changed in my file and busted my balls whole day searching solution

**Comment by idrisdemir** [comment]
@varunponda i had searched it very much. i had not found solution but as far as see solution at a web site i wrote the solution
