### ISSUE TITLE
403 error when accessing training images for https://colab.research.google.com/github/tinyMLx/colabs/blob/master/2-4-11-AssignmentQuestion.ipynb#scrollTo=njf4YhwFb6hW

### ISSUE THREAD

**Issue by r-christie** [googlecolab/colabtools#2674]
Trying out the assignment at:

https://colab.research.google.com/github/tinyMLx/colabs/blob/master/2-4-11-AssignmentQuestion.ipynb#scrollTo=njf4YhwFb6hW

When running the standard code for fetching training images (which we don't need to change for the assignment)

!wget --no-check-certificate \
    https://storage.googleapis.com/ibeans/train.zip \
    -O /tmp/train.zip

!wget --no-check-certificate \
    https://storage.googleapis.com/ibeans/validation.zip \
    -O /tmp/validation.zip

!wget --no-check-certificate \
    https://storage.googleapis.com/ibeans/test.zip \
    -O /tmp/test.zip

We get the following 403 errors.

--2022-03-13 13:10:29--  https://storage.googleapis.com/ibeans/train.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 209.85.147.128, 142.250.125.128, 142.250.136.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|209.85.147.128|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-03-13 13:10:30 ERROR 403: Forbidden.

--2022-03-13 13:10:30--  https://storage.googleapis.com/ibeans/validation.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.128.128, 142.251.6.128, 142.250.159.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.128.128|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-03-13 13:10:30 ERROR 403: Forbidden.

--2022-03-13 13:10:30--  https://storage.googleapis.com/ibeans/test.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 64.233.183.128, 173.194.194.128, 142.250.152.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|64.233.183.128|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-03-13 13:10:30 ERROR 403: Forbidden.

**Comment by cperry-goog** [comment]
You'll need to check with the individuals hosting the file.
