### ISSUE TITLE
cant give an input

### ISSUE THREAD

**Issue by Bhushbox** [googlecolab/colabtools#2679]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by Bhushbox** [comment]
DevTools failed to load source map: Could not load content for https://colab.research.google.com/v2/external/js/min-maps/vs/base/worker/workerMain.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by cperry-goog** [comment]
Can you reproduce this in an incognito window?
