### ISSUE TITLE
Exception: Java gateway process exited before sending its port number

### ISSUE THREAD

**Issue by mahbubk9** [googlecolab/colabtools#268]
Hi,
I am getting this error while trying to run pyspark on colab,
codes i ran;
!pip install pyspark
import pyspark
from pyspark import SparkContext
sc =SparkContext()
strangely, it worked at first instance , but giving this error everytime i try now.

**Comment by metrizable** [comment]
@mahbubk9 I just gave your code a try, and extended it include the canonical Pi calculation and it worked without issue. If you are still experiencing the issue, please feel free to re-open this issue and provide a minimal reproducible notebook.

![AQCRYvVaEYVBqE8](https://user-images.githubusercontent.com/65414824/221366715-133abad1-157d-473a-b5e0-8ee5e2db0299.png)
