### ISSUE TITLE
Files created in Colab not showing up in Drive

### ISSUE THREAD

**Issue by yohenthounaojam** [googlecolab/colabtools#2683]
**Describe the current behavior**

I am extracting 1000 `.tar` files in Drive. After successful extraction, `os.listdir()` shows me that the files are in Drive. But the problem is that it doesn't show up on Drive or any other Colab notebook when Drive is mounted. 

I have also tried `drive.flush_and_unmount` but it runs for over 2 hours. 

**Describe the expected behavior**
Once files are extracted, they automatically start showing up in Drive. This happens up to a certain number of files and stops. 

**What web browser you are using**
Firefox 98.0.1 (64-bit)

**Additional context**

_Unable to share_

**Comment by cperry-goog** [comment]
Unfortunately, Drive does not support large collections of files very well: this is a flavor of https://research.google.com/colaboratory/faq.html#drive-timeout

Someday we may consider ways to improve this, but currently out of scope for the team.
