### ISSUE TITLE
Variable inspector does not work ?

### ISSUE THREAD

**Issue by mint1234abc** [googlecolab/colabtools#2684]
**Describe the current behavior**
Variable Inspector "{x}" may not work in my environment.
"{x}" is clicked, and then {x} GUI is shown. But variables are not shown.
For example, "a = 1" is performed; however, "a" is not shown.

**Describe the expected behavior**
I hope the detail of "a" is displayed on the Variable Inspector window.

**What web browser you are using**
Chrome 99.0.4844.74（Official Build）64 bit

**Additional context**
- Python is 3.7.12
- Colab Pro subscription
- "While inspector is open" mode
- I tried "Factory Reset Runtime."
- I tried "Scratch Cell."
a = 1
print(a)
1

When the mouse pointer is on the variable "a," then "int: a 1" is shown shortly near the mouse pointer.
- I tried "playground mode."

Thank you

**Comment by blois** [comment]
Does this repro on a new empty notebook as well?

**Comment by mint1234abc** [comment]
Thank you very much for your response.
Yes.

When several cells are written, the Variable Inspector becomes empty unnoticeably.

Thank you.

**Comment by AlexaGri** [comment]
same story, no variables or imported data is shown in {x}
new notebook

**Comment by blois** [comment]
It sounds like it's most likely related to the code being executed, we'd really need a repro (ideally minimal) or the issue.

**Comment by mint1234abc** [comment]
Thank you very much for your comment.
