### ISSUE TITLE
Android/chrome: backspace key not working

### ISSUE THREAD

**Issue by francoijs** [googlecolab/colabtools#269]
Tested from chrome 68.0 / android 6.0.1:
The backspace key from the android keyboard has no effect.
Observed while editing code or text in a colab notebook.

**Comment by maggot99999** [comment]
Same issue.
Tested on Chrome 71.0 on Android 9.0 with Gboard 7.9.7
The backspace barely works at first symbols then it becomes uncontrollable.

**Comment by swd543** [comment]
Any solution to this issue? Affects me too.
