### ISSUE TITLE
.gdoc not copying, also notice the same issue when copying google doc files, google excel files etc.

### ISSUE THREAD

**Issue by harialencherry** [googlecolab/colabtools#2692]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by harialencherry** [comment]
Nil

**Comment by cperry-goog** [comment]
Google docs and sheets files are pointers to files stored in the cloud, and are not directly modifiable in Colab via mount drive. If you'd like to access those contents or write files, open snippets in Colab and look for gspread or pydrive as starters.
