### ISSUE TITLE
No backend Available for account edutacional college

### ISSUE THREAD

**Issue by Riztya** [googlecolab/colabtools#2696]
**Describe the current behavior**
Hi i'm student indonesia college, my major on this college is information technology, i'm and all my friends on classroom have project from my teacher to learning machine learning and data science, but we only can use account education from my college but all account on my classroom can't to run all type 
 of runtime. always show sorry no backend available, it's been 1 month trying

**Describe the expected behavior**
The lecturer at my campus explained that previously it was possible to use a college education account to learn machine learning on this, but starting one month earlier, I couldn't use that account. I hope the college education account can be used again. my college domain @radenfatah.ac.id

**What web browser you are using**
Chrome

**Comment by cperry-goog** [comment]
We saw your in-product submission and have replied directly to that.
