### ISSUE TITLE
Colab Pro "manage subscription" link results in 403

### ISSUE THREAD

**Issue by jdagdelen** [googlecolab/colabtools#2702]
I recently canceled my Colab Pro subscription, but then wanted to add it back to my account. Clicking the "manage subscription" link in the "Colab Pro" tab in Colab settings results in a redirect to https://colab.research.google.com/%7B$signupUrl%7D, which gives a 403. Mac OS Monterrey 12.2.1 running Chrome Version 99.0.4844.74 (Official Build) (x86_64)

**Comment by cperry-goog** [comment]
Thanks for the report! This was a bug, the fix is live today.
