### ISSUE TITLE
Something not right during prediction run

### ISSUE THREAD

**Issue by hussiai1** [googlecolab/colabtools#2704]
**RUN PREDICTION ERROR**

WARNING: found GPU Tesla K80: limited to total length < 1000
2022-03-28 06:32:16,384 Running colabfold 1.2.0 (06347d692849531babcf6b196734ae3f0eec68e3)
2022-03-28 06:32:16,387 Found 5 citations for tools or databases
2022-03-28 06:32:22,283 Query 1/1: TripartateproteinamrB_23797 (length 3141)
COMPLETE: 100%|██████████| 150/150 [elapsed: 00:00 remaining: 00:00]
2022-03-28 06:32:46,272 Running model_1
2022-03-28 06:34:20,955 Could not predict TripartateproteinamrB_23797. Not Enough GPU memory? RESOURCE_EXHAUSTED: Out of memory while trying to allocate 2542442752 bytes.
2022-03-28 06:34:20,979 Done

****DISPLAY 3D STRUCTURE ERROR**

IndexError                                Traceback (most recent call last)
[<ipython-input-12-a785035f92e3>](https://localhost:8080/#) in <module>()
     46 
     47 
---> 48 show_pdb(rank_num,show_sidechains, show_mainchains, color).show()
     49 
     50 

[<ipython-input-12-a785035f92e3>](https://localhost:8080/#) in show_pdb(rank_num, show_sidechains, show_mainchains, color)
     19   model_name = f"rank_{rank_num}"
     20   view = py3Dmol.view(js='https://3dmol.org/build/3Dmol.js',)
---> 21   view.addModel(open(pdb_file[0],'r').read(),'pdb')
     22 
     23   if color == "lDDT":

IndexError: list index out of range

This is the real cause of this error?

**Comment by craigcitro** [comment]
This is unfortunately expected -- the error suggests you were trying to allocate 25GB of GPU RAM, but the GPUs available in Colab all top out at 13GB of RAM.

Note a high RAM assignment refers to *system* memory (as returned by `!grep MemTotal /proc/meminfo`), not *GPU* memory (as returned by `!nvidia-smi --query-gpu=memory.total --format=csv`). All GPU chips have the same memory profile.

**Comment by hussiai1** [comment]
Hi Mr Citro,

So what should I do to prevent this problem occurred again in future?

Regards,

Ainulkhir Hussin
