### ISSUE TITLE
Google Colab runtimes resets after just a few seconds.

### ISSUE THREAD

**Issue by MedicDoesStuff** [googlecolab/colabtools#2706]
**Describe the current behavior**
The runtime disconnects and resets quickly after a few seconds.

**Describe the expected behavior**
Usually, my runtimes expire after 15 minutes of losing internet but now. Just 40 seconds of internet disconnection and reconnection to the runtime resets the runtime.

**What web browser you are using**
Chrome

**Comment by cperry-goog** [comment]
We'll need more information to follow up on this bug report. Please submit feedback within Colab at Help > Send feedback.
