### ISSUE TITLE
What does this error means? 

### ISSUE THREAD

**Issue by hussiai1** [googlecolab/colabtools#2708]
Hi,

Hope you guys can help me out. 

Was the problem happened because of wrong sequence uploaded? Homology modelled of my protein sequence showed that my protein is a tripartate protein, so what I did was copying the sequence like this PIxxxxxxSK:PIxxxxxSK:PIxxxxxxSK. Is this method of correct? or I just need to insert only one sequence instead of three? --- something like this PIxxxxxxSK. I really don't know what is the real problem whether it was because of less RAM that I need to upgrade to the ColabPro+ or I need to fix my sequence?

IndexError                                Traceback (most recent call last)
[<ipython-input-6-a785035f92e3>](https://rc6wfos6yjl-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220328-060046-RC02_437851183#) in <module>()
     46 
     47 
---> 48 show_pdb(rank_num,show_sidechains, show_mainchains, color).show()
     49 
     50 

[<ipython-input-6-a785035f92e3>](https://rc6wfos6yjl-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220328-060046-RC02_437851183#) in show_pdb(rank_num, show_sidechains, show_mainchains, color)
     19   model_name = f"rank_{rank_num}"
     20   view = py3Dmol.view(js='https://3dmol.org/build/3Dmol.js',)
---> 21   view.addModel(open(pdb_file[0],'r').read(),'pdb')
     22 
     23   if color == "lDDT":

IndexError: list index out of range

**Comment by cperry-goog** [comment]
This is a question for the AlphaFold folks, I'd go chase them.
