### ISSUE TITLE
Bring back the old Drive mounting system

### ISSUE THREAD

**Issue by MedicDoesStuff** [googlecolab/colabtools#2709]
**Is your feature request related to a problem? Please describe.**
Google Colab has been getting worse recently with drive mounting for "privacy" reasons

**Describe the solution you'd like**
Rollback the drive mounting to the old authcode-based version

**Describe alternatives you've considered**
I've tried google-drive-ocamlfuse which had worked for the last month but started to act the same as the new Colab mounting this morning.

**Additional context**
This is a pain in the butt for people like me who store large files in other drives which i've specifically paid for larger storage and having a Colab Pro account with small drive space, please atleast make other accounts mountable.

**Comment by cperry-goog** [comment]
Sorry, this is infeasible.
