### ISSUE TITLE
Could not load the JavaScript files needed to display output. This is probably because your Google Account login access has expired or because third-party cookies are not allowed by your browser.  Please reload this page.

### ISSUE THREAD

**Issue by suonbo** [googlecolab/colabtools#2711]
"Could not load the JavaScript files needed to display output.
This is probably because your Google Account login access has expired or because third-party cookies are not allowed by your browser.

Please reload this page."

This is the bug that I received recently when using colab on my project. This causes the notebook unable to log anything. I dont know how to solve this because I tried all the methos, clear recent cookies, change web browser, reload notebook, restart my laptop, change Colab account,...

Web browser: I tried both Chrome and Safari, it doesnt work at all

**Comment by blois** [comment]
See also https://github.com/googlecolab/colabtools/issues/2209 for some explanations

**Comment by mlgitter** [comment]
> See also #2209 for some explanations

This doesn't help. In my case, little outputs can be printed, but diagrams, datasets, etc - just not, which makes the tool useless for me((
