### ISSUE TITLE
Can't mount another google drive in Colab Pro

### ISSUE THREAD

**Issue by yangfanliang** [googlecolab/colabtools#2714]
**Problem**

Can't mount another google drive different from the one I am using in Colab Pro+. Previously workaround [here](https://stackoverflow.com/questions/69822304/google-colab-google-drive-can%C2%B4t-be-mounted-anymore-browser-popup-google-dri/69881106#69881106) no longer works starting today (03-30-2022). 

**Describe the expected behavior**
Should be able to connect to Google Drive from Colab.

**Comment by eddyliao-30** [comment]
I have same issue here. I was using the same code as you did before but I couldn't give me the authentication if I try to mount another google account drive. 

When I try to get the authentication of my other google account, it reflects:
MessageError: Error: credential propagation was unsuccessful

**Comment by yangfanliang** [comment]
> I have same issue here. I was using the same code as you did before but I couldn't give me the authentication if I try to mount another google account drive.
> 
> When I try to get the authentication of my other google account, it reflects: MessageError: Error: credential propagation was unsuccessful

Same error for me!

**Comment by TigerPeng2** [comment]
I don't have Pro but I have the same error as well. I have tried every workaround that was on the internet previously, I've tried creating a new notebook with the same code. Nothing has worked.

**Comment by TheLastLovemark** [comment]
Slightly different issue with the same error message.

I am not trying to mount the drive of a different account. Colab account = drive account that I want to mount.

This started today March 30, 2022. The last time I know there was a successful mount was Saturday, March 26, 2022

**Comment by mosmos6** [comment]
Same issue here.

I run this code in order to mount google drive onto colab.

`from google.colab import auth
auth.authenticate_user()`

Then a new window pops up to authenticate my other google account. I follow the instructions and click "Allow". This new window closes itself but colab returns "MessageError: Error: credential propagation was unsuccessful".
Actually popping up a new window is a new behavior. Until about 12 hours ago, colab showed a URL to authenticate my other google account, and it lead to a code to copy and paste onto colab. It's different now and the new system doesn't seem to work.
I went back to my other google account to check the security setting. I found Colaboratory Runtimes on security related activity. I checked "Trust" but still this error persists.

**Comment by hussiai1** [comment]
I'm currently using Colab Pro to predict 3129 amino acid sequence. Is that sufficient? Because it came out with an error doing so. In contrast, it was ok running 1100 amino acid sequence yesterday. If needed I want to upgrade to Colab Pro+...someone please help me out...

**Comment by Stoneberger** [comment]
Same error for me! 
Please fix it.

**Comment by zavinono** [comment]
This has closed the work around that university students could use to link to data on their university accounts (where it is safe and legal to store data), but accounts that are locked from upgrading to google colab pro as they cannoy have a credit card entered to them. Please either put in a word around for academic accounts or remove this as it is clear a lot of people would like to mount drives from different accounts for a multitude of reasons

**Comment by zavinono** [comment]
Unfortunately this leads me to cancel my pro account as it is now unusable, and will have to look for a different source

**Comment by hieunguyen1053** [comment]
I found a solution here, hope it helps.
https://stackoverflow.com/questions/71695387/connecting-to-a-different-google-drive-than-the-one-logged-into-google-colab.
It works for me.

**Comment by mosmos6** [comment]
> I found a solution here, hope it helps. https://stackoverflow.com/questions/71695387/connecting-to-a-different-google-drive-than-the-one-logged-into-google-colab. It works for me.

@hieunguyen1053 Thank you, it worked for me too. and now I cannot mount gcs that I had no problem to mount until 2 days ago..

**Comment by Stoneberger** [comment]
The connection to Google Cloud Storage no longer works for me either. Even with the account with which I am logged into Colab.

When setting the project, I am permanently asked for permission to access to project. 
While loading the TPU, the "Google Application Credentials" don't seem to be found anymore. 
Please urgently analyze this problem and fix it. It is currently no longer possible to work with the TPUs, GPUs or files in GCS.

**Comment by mosmos6** [comment]
@Stoneberger Same here. I can barely do anything but keep paying for Pro+ and GCS.

**Comment by lorenzo-park** [comment]
Hello,

I am in the same situation to login for accessing GCS on Colab. Following error is occurred:

```
from google.colab import auth
auth.authenticate_user()

output:
---------------------------------------------------------------------------
MessageError                              Traceback (most recent call last)
[<ipython-input-3-aca706909015>](https://localhost:8080/#) in <module>()
      1 from google.colab import auth
----> 2 auth.authenticate_user()
      3 project_id = 'strategic-grove-343714'
      4 get_ipython().system('gcloud config set project {project_id}')

2 frames
[/usr/local/lib/python3.7/dist-packages/google/colab/_message.py](https://localhost:8080/#) in read_reply_from_input(message_id, timeout_sec)
    104         reply.get('colab_msg_id') == message_id):
    105       if 'error' in reply:
--> 106         raise MessageError(reply['error'])
    107       return reply.get('data', None)
    108 

MessageError: Error: credential propagation was unsuccessful
```

It was working about 3 days ago. When I run following commands, the cell provides link to google login page, and when I proceed by clicking "allow" button, the window shows the auth key to copy and paste it to input field in the cell output.
Now, when I click "allow" button, there are no redirections to the auth key copying page and face the error I attached above.

**Comment by cperry-goog** [comment]
@Stoneberger could you file a separate issue describing your problem? We believe that's a distinct issue from the rest of this thread.

**Comment by cperry-goog** [comment]
We have been making more changes to improve our security and authentication, and the previous statement applies here:

We've rolled out a new, more secure method to authenticate in Colab. This requires using the same account to mount Google Drive as you use for notebook code execution.

If you require data from another account, you can share that data between accounts and add a shortcut to view that file or folder in your Drive when mounted in Colab [1]

Report any issues accessing shared content. If you experience issues mounting Drive from the same account, please do the following:

Runtime -> Factory Reset Runtime
drive.mount() using the account with which you are logged in to Colab

And then send feedback in product: Help > Send feedback.

[1] https://support.google.com/drive/answer/9700156

**Comment by Stoneberger** [comment]
@cperry-goog I have created a new issue for the problem #2732

**Comment by TheLastLovemark** [comment]
@cperry-goog I am using the same account to mount Google Drive as I use for notebook code execution. I get the same login propogation error.

**Comment by cperry-goog** [comment]
@TheLastLovemark are you using a TPU? #2732 is now known, and we're working on a fix.

**Comment by mosmos6** [comment]
@cperry-goog Thank you for your attention. I understand you are working on #2732 now but even if it's fixed, according to your manifest on this thread, does this mean we can't mount GCS of other account onto Google drive anymore? That would cause us a huge amount of restructuring of data location, etc..

**Comment by zavinono** [comment]
> We have been making more changes to improve our security and authentication, and the previous statement applies here:
> 
> We've rolled out a new, more secure method to authenticate in Colab. This requires using the same account to mount Google Drive as you use for notebook code execution.
> 
> If you require data from another account, you can share that data between accounts and add a shortcut to view that file or folder in your Drive when mounted in Colab [1]
> 
> Report any issues accessing shared content. If you experience issues mounting Drive from the same account, please do the following:
> 
> Runtime -> Factory Reset Runtime drive.mount() using the account with which you are logged in to Colab
> 
> And then send feedback in product: Help > Send feedback.
> 
> [1] https://support.google.com/drive/answer/9700156

I think you are miss understanding the issue- for academic purpose we are given drives that are both large and allowed by ethics approval to store both data and models onto them. Sharing data is fine but unless I am mistaken I cannot then use another account to train a model and save it to the university drive.

**Comment by TheLastLovemark** [comment]
@cperry-goog Not using TPU

**Comment by TheLastLovemark** [comment]
I've identified part of the problem. GDrive is mounting in Chrome, but not in Firefox. I upgraded to FF 99.0 today.

**Comment by varunponda** [comment]
This solution solved my problem: 
```!sudo echo -ne '\n' | sudo add-apt-repository ppa:alessandro-strada/ppa >/dev/null 2>&1 # note: >/dev/null 2>&1 is used to supress printing
!sudo apt update >/dev/null 2>&1```
Go to next cell and run this:
```!sudo apt install google-drive-ocamlfuse >/dev/null 2>&1```
And finally run this block of code
```!google-drive-ocamlfuse
!sudo apt-get install w3m >/dev/null 2>&1 # to act as web browser 
!xdg-settings set default-web-browser w3m.desktop >/dev/null 2>&1 # to set default browser 
%cd /content
!mkdir gdrive
%cd gdrive
!mkdir "My Drive"
!google-drive-ocamlfuse "/content/gdrive/My Drive"```
you will get a line stating:
Failure("error opening URL: click this url and select the account

**Comment by BrunoArsioli** [comment]
I had the same issue here. Sharing the target folders and linking to them has solved the problem for me. 

> We have been making more changes to improve our security and authentication, and the previous statement applies here:
> 
> We've rolled out a new, more secure method to authenticate in Colab. This requires using the same account to mount Google Drive as you use for notebook code execution.
> 
> If you require data from another account, you can share that data between accounts and add a shortcut to view that file or folder in your Drive when mounted in Colab [1]
> 
> Report any issues accessing shared content. If you experience issues mounting Drive from the same account, please do the following:
> 
> Runtime -> Factory Reset Runtime drive.mount() using the account with which you are logged in to Colab
> 
> And then send feedback in product: Help > Send feedback.
> 
> [1] https://support.google.com/drive/answer/9700156
