### ISSUE TITLE
Google Cloud Storage can no longer be connected

### ISSUE THREAD

**Issue by Stoneberger** [googlecolab/colabtools#2732]
**Describe the current behavior**
The error has existed since 30/03/2022. Since this date, it is no longer possible to correctly link Google Colab with Google Cloud Storage.
As a result, it is also no longer possible to use the TPUs correctly (see below).

**Describe the expected behavior**
I try to link colab with the following code to GCS:
```python
from google.colab import auth
auth.authenticate_user()
```

Since 30.03.2022 appears the new window where now the confirmation must be made by clicking on the "Allow" button (previously you had to copy a code). The account currently used is the one with which Google Colab is also used.

If you try to set the project, you will be asked to confirm the following request each time you start the code.
(google_project_id is a variable)

```python
!gcloud config set project {google_project_id}
```

This message appears:
![image](https://user-images.githubusercontent.com/88782026/161346655-a506cb71-3967-42ab-b6f9-e68b217469cd.png)

Afterwards, if you try to initialize the TPU, the credentials cannot be retrieved correctly.

```python
#Set the tf-hub cache directory
os.environ['TFHUB_CACHE_DIR'] = os.path.join(f'{google_bucket_model_path}/_tfhub_cache')

#Initialization of the TPU instance
resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)
strategy = tf.distribute.TPUStrategy(resolver)

#If there is a problem with the connection wie print a error message, else we print the ip address of the tpu instance
assert 'COLAB_TPU_ADDR' in os.environ, 'ERROR: Not connected to a TPU runtime; please see the first cell in this notebook for instructions!'
TPU_ADDRESS = 'grpc://' + os.environ['COLAB_TPU_ADDR']
print('TPU address is', TPU_ADDRESS)

with tf.compat.v1.Session(TPU_ADDRESS) as session:
  print('TPU devices:')
  pprint.pprint(session.list_devices())

  #Upload credentials to TPU.
  with open('/content/adc.json', 'r') as f:
    auth_info = json.load(f)

  #Set up GCS access with the TPU
  tensorflow_gcs_config.configure_gcs_from_colab_auth()
```

The following error message appears:

![image](https://user-images.githubusercontent.com/88782026/161345777-3d75233b-a803-43d8-b043-5a497dd8f064.png)

I have already tested the following step: Runtime -> Factory Reset Runtime

**What web browser you are using**
Chrome

**Comment by cperry-goog** [comment]
Thanks! Tracked internally at b/227809850

Hope to have you an alternative soon.

**Comment by TheLastLovemark** [comment]
I am using the same account to mount Google Drive as I use for notebook code execution.

I have a similar problem as @Stoneberger, but I am trying to mount the drive a different way. I'm using the code snippet provided by Colab

![colab_mount_error](https://user-images.githubusercontent.com/5613063/161355731-91a0a92b-b3d3-48d0-95fc-021d72f2b2c7.png)

**Comment by yokomotod** [comment]
I faced the same problem and maybe found a workaround.

If I set `%env USE_AUTH_EPHEM=0`, it seems to return to the previous behavior and solve the problem.  
I found this variable [here](https://github.com/googlecolab/colabtools/blob/9fba8e85d205b1a5342d0bbeace86d2f5a08046c/google/colab/auth.py#L235)

Perhaps colab started setting `USE_AUTH_EPHEM=1` by default since 30/03/2022?

**Comment by Stoneberger** [comment]
@yokomotod I can confirm. It is a workaround that solves the problem for the moment. Thanks for your help.

**Comment by TheLastLovemark** [comment]
@yokomotod where do I make this change? I am not as well versed as you and @Stoneberger

**Comment by mosmos6** [comment]
@yokomotod Thank you. That worked for me too. Mr. Anderson, welcome back.

**Comment by TheLastLovemark** [comment]
I do not know how to make this change. can someone please point me in the right direction?

**Comment by Stoneberger** [comment]
@TheLastLovemark I think your problem is related to the ticket #2714.
You are not trying to connect to Google Cloud Storage you are trying to connect to Google Drive. 
I think the workaroud of @yokomotod does not solve your problem, but you can still try it. 
Just try it with the following code:
```python
%env USE_AUTH_EPHEM=0

from google.colab import drive
drive.mount('/content/gdrive')
```

**Comment by bobglobe** [comment]
Works for us too

**Comment by paplorinc** [comment]
The 
```
%env USE_AUTH_EPHEM=0
```
trick doesn't seem to be working anymore. Any other fixes or workarounds?

**Comment by cperry-goog** [comment]
on TPUs you should be using `auth.authenticate_service_account()`

I think everything has been fixed there for awhile, sorry for dropping this bug.

**Comment by paplorinc** [comment]
@cperry-goog, so what's the workaround exactly for using `drive.mount('/content/drive')` with a different Google account? Nothing seems to be working for me?
