### ISSUE TITLE
The JavaScript file required to display the output could not be loaded. This may be because your Google Account login access has expired or your browser does not allow third-party cookies.

### ISSUE THREAD

**Issue by WuYue688** [googlecolab/colabtools#2734]
**Describe the current behavior**
always gives the following error ：The JavaScript file required to display the output could not be loaded. This may be because your Google Account login access has expired or your browser does not allow third-party cookies.Hope to get help and advice, thank you very much!

**What web browser you are using**
Chrome and Safari.

**Comment by cperry-goog** [comment]
We think this is the standard third-party cookies required warning: you'll need to enable those in your browser.
