### ISSUE TITLE
error in google colab pro => URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)>

### ISSUE THREAD

**Issue by jeanckempf** [googlecolab/colabtools#2735]
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)>
![ssl error](https://user-images.githubusercontent.com/102886131/161407753-ec523c01-9d41-401d-80b0-6453ed43d59e.png)

**Comment by oowhyoo** [comment]
me too

**Comment by Ainigma0** [comment]
same

**Comment by kenny29800** [comment]
same here on colab pro...

**Comment by amkmpro** [comment]
Check it again, solved.

**Comment by oowhyoo** [comment]
> Check it again, solved.

Where did you fix it please?

**Comment by amkmpro** [comment]
> > Check it again, solved.
> 
> Where did you fix it please?

just restart runtime.

**Comment by craigcitro** [comment]
This was an upstream issue (https://github.com/pytorch/vision/issues/5727#issuecomment-1086804901), should be fixed.

**Comment by hcps-pressleaf** [comment]
Was struggling to load vgg19 using pytorch. I ran this code and it bypassed the error: 
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
