### ISSUE TITLE
Unable to use Google Drive API to download file 

### ISSUE THREAD

**Issue by kechan** [googlecolab/colabtools#274]
This has worked until today. I have been using this snippet:

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

When I clicked the link shown and choose my Account, I got an authorization error:

Authorization Error
Error 400: invalid_scope
Some requested scopes cannot be shown: [https://www.googleapis.com/auth/drive, https://www.googleapis.com/auth/compute, https://www.googleapis.com/auth/appengine.admin, https://www.googleapis.com/auth/cloud-platform]

**Comment by colaboratory-team** [comment]
Sorry for the trouble. There's an ongoing issue with a downstream dependency that we're working on correcting with the relevant teams.

An immediately applicable work-around is to use the built-in Drive FUSE client by running the snippet below to mount your Drive files:

```
from google.colab import drive
drive.mount('/content/drive')
```

**Comment by kechan** [comment]
I didnt know there's a mount option. I am going to try this and see if it works. This may turns out to be a better solution for me.

**Comment by blois** [comment]
The downstream issue should now be resolved.
