### ISSUE TITLE
Problem when uploading files.

### ISSUE THREAD

**Issue by zer0Percent** [googlecolab/colabtools#2740]
Current behavior
Files won't upload when they are dragged and dropped from the file system. The files are stored in /content/
The files are related to CSV files that consume 150MB approximately.

Expected behaviour
Files are uploaded.

**What web browser you are using**
Firefox

**Comment by cperry-goog** [comment]
Just tested this on Firefox on Windows: dragging files into the file system upload fine for me. Please provide clearer repro steps and I can test it.
