### ISSUE TITLE
ENH: split cell at cursor

### ISSUE THREAD

**Issue by westurner** [googlecolab/colabtools#2741]
**Is your feature request related to a problem? Please describe.**

STORY: Users can split the current cell at the current cursor position, in order to refactor into more notebook cells.

**Describe the solution you'd like**

- [ ] ENH: Create a keyboard shortcut for splitting the current cell at the cursor
  - [ ] ENH: cell IDs change upon copying, pasting, splitting
    - [ ] DOC: JEP #
  - [ ] UBY: decide on a keyboard shortcut
    - [ ] e.g. JupyterLab has 'Ctrl-Shift-Minus',
      which is going to be muscle memory for people coming from that tool,
      so maybe `Ctrl-Shfit-Minus` for jlab compatibility, and, though:
    - [ ] 'Ctrl-Shift-Minus' collides with (is it Global or Local) font size decrease on Chromebooks, so there needs to be another keyboard shortcut to split cell
      - [ ] ENH,UBY: jlab: that should/could be added back to jlab, too

**Describe alternatives you've considered**
Copy and paste to a new cell, instead of splitting at cursor:
- `Shift + PageDown`  # PageDown = Fn + Down arrow  # Select all
- `Ctrl-X`  # Cut the rest of the cell
- [ ] Create a new cell in colab
- `Ctrl-V`  # Paste the rest of the previous cell

**Additional context**
- https://jupyter.org/enhancement-proposals/62-cell-id/cell-id.html#questions :: 
  > - How is splitting cells handled?
  >   - One cell (second part of the split) gets a new cell ID.
- https://github.com/jupyter/nbdime/issues/553

**Comment by craigcitro** [comment]
Note that this already works: ctrl-m - (ctrl-m followed by -) will split the current cell.

**Comment by westurner** [comment]
- [ ] Colab: Add to command palette

**Comment by 8gent** [comment]
ctrl m - doesn't work for me.  makes my screen smaller or it turn the cell into text to which I can't reverse.   I had to turn off windows short cut to make it work.
