### ISSUE TITLE
pushed results of while(TRUE) loop when using colab for R language

### ISSUE THREAD

**Issue by rokq** [googlecolab/colabtools#2744]
**Describe the current behavior**
I am making a while(TRUE)loop for R language in colab. I am not making complicated scripts.  And different outcomes are coming out with when I am using the R studio and when I am using google colab. 

**Describe the expected behavior**

I made a simple example of the situation .

If my script is 

"

f<- function(x){
  x <- as.double(x)
  value <- x^2-4*x
  return(value)                
}

x1 <- readline(prompt = "value of x : ")

while(TRUE){
  if(f(x1)>0){
    print("Invalid - try again")
    x1 <- readline(prompt = "value of x : ")
    readline(prompt = "Press Enter key to continue : ")
  }
  else{
    break;
    
  }
}

print(paste("f(x) is ", f(x1)))

"

If i input the invalid case, in R studio the message invalid-try again appears at every trial
But in google colab, it does not appear at every trial, and appears all at once after I get the right case of inputs. 

**What web browser you are using**
Google chrome

**Additional context**

**Comment by craigcitro** [comment]
There are two issues here:

1. You want to call `flush.console()` after your print; this fixes the "output only appears at the end" problem.
2. You probably want to wrap `readline()` in `as.integer()`.
