### ISSUE TITLE
inconsistent output

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#2746]
run this in one cell,
```
import functools, operator as op
class List(list):  
  def flatten(self): 
    return functools.reduce(op.iconcat, self)
a = List([['x', 'y', 'z'], ['l', 'm']])
b = List([[1, 2, 3], [4, 5]])
print(dict(zip(*map(List.flatten, [a, b]))))
```
then in another cell,
```
print(a)
```
gives,
```
[['x', 'y', 'z', 'l', 'm'], ['l', 'm']]
```
which is not expected.
this problem gets solved if I define the class in another cell, do the assignment to `a` in another cell.

**Comment by craigcitro** [comment]
I believe this is WAI: you're using *i*concat, which is the op corresponding to `a += ...`. If you don't want to side-effect `a`, use `op.concat`.
