### ISSUE TITLE
pandas/_libs/innumpy.ufunc size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by dpredie** [googlecolab/colabtools#2749]
**Describe the current behavior**
after reporting #2601 and the conflicting default pandas version/install in colab are fixed ( thanks again), it seems now the pandas numpy version is conflicting 

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
.............
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

**Describe the expected behavior**
able to run code section 4, import tensorflow after installing tensorflow 1.11.0 like in january 2022

**What web browser you are using**
Edge

**Additional context**
https://github.com/dpredie/SingleHDR/blob/master/SingleHDR.ipynb

**Comment by craigcitro** [comment]
The problem here is that `tensorlayer 1.11.0` and `tensorflow 1.15.2` have conflicting requirements for numpy: the former wants `numpy < 1.16` and the latter wants `numpy >= 1.16`. This is in the error stanza at the end of the initial `pip install tensorlayer` in your notebook.
