### ISSUE TITLE
 Getting error: "Sorry, no backends available. Please try again later."

### ISSUE THREAD

**Issue by Alan-LZhang** [googlecolab/colabtools#2750]
**Describe the current behavior**
 Getting error: "Sorry, no backends available. Please try again later."

**Describe the expected behavior**
Get connected and run the code

**What web browser you are using**
Chrome

**Additional context**
Some posts suggest it could be due to limited resources. But I have a pro subscription and have not used Colab for more than a month.

**Comment by zehuicao** [comment]
I meet the same questions

**Comment by craigcitro** [comment]
We had an availability issue on our side, which led to failed GPU assignments; we believe we've found the root cause and the issue should resolve shortly.
