### ISSUE TITLE
"No backend with GPU available. Would you like to use a runtime with no accelerator?" even with other accounts.

### ISSUE THREAD

**Issue by MedicDoesStuff** [googlecolab/colabtools#2751]
**Describe the current behavior**
I have Colab Pro but i can't connect to GPU runtimes, even CPU runtimes won't connect.

**Describe the expected behavior**
Runtimes normally should connect just flawlessly and have no problems.

**What web browser you are using**
Brave and Chrome.

**Comment by Francis-Un** [comment]
I meet the same problem.

**Comment by craigcitro** [comment]
We had an availability issue on our side, which led to failed GPU assignments; we believe we've found the root cause and the issue should resolve shortly.
