### ISSUE TITLE
Unresponsive Colab

### ISSUE THREAD

**Issue by Rana-Javed** [googlecolab/colabtools#2752]
Respected Sir,

My Professional Colab account unresponsive during running. I set 120 Epoch for my experiment, but the Colab shows unresponsive behavior such as its stop working (unresponsive some times 35 epoch, some times on 6 epochs). I did not complete experiment which is almost 3 to 4 hours long. Please resolve the issue on an urgent basis.
![Colab unresponsive](https://user-images.githubusercontent.com/58065773/162916428-5d13cd31-7951-41d6-93cc-9fc4fd897792.png)
[app.log](https://github.com/googlecolab/colabtools/files/8471132/app.log)

**Comment by cperry-goog** [comment]
Looks like your session restarted a few times; it may be you're running out of memory? Can you share a minimal repro notebook that triggers this?
