### ISSUE TITLE
NVIDIA driver issue

### ISSUE THREAD

**Issue by HosseinRZ95** [googlecolab/colabtools#2756]
** current behavior**
I use ray RLlib for my reinforcement learning. I'm getting Nvidia driver issue today as follows:
''invalid literal for int() with base 10: "NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.''
I checked ray and it had an update but it doesnt seem to be related to this issue.
**Describe the expected behavior**
just init ray actor as always
**What web browser you are using**
edge
**Additional context**
most of rllib examples can be tested:
https://github.com/ray-project/ray/tree/master/rllib/examples

**Comment by craigcitro** [comment]
I suspect that you were executing in a non-GPU runtime; you can select a GPU by going to `Edit` -> `Notebook settings` and selecting `GPU` as the accelerator.
