### ISSUE TITLE
Upgraded to Colab pro plus and still ram limited to 25gb

### ISSUE THREAD

**Issue by Jackgihl** [googlecolab/colabtools#2759]
Hi
I recently upgraded to colab pro plus because i have been running some pretty RAM intensive networks. I was under the impression google colab plus gave you up to 52 gb of ram with the high ram option. Is there a delay between when you upgrade accounts and when you gain access to more ram? Any thoughts?

**Comment by cperry-goog** [comment]
Can you check again? There was an issue that was resolved earlier this week and you shouldn't encounter problems.
