### ISSUE TITLE
Not able to install google-drive-ocamlfuse

### ISSUE THREAD

**Issue by hidasri** [googlecolab/colabtools#276]
When I run the following code

!apt-get update -qq 2>&1 > /dev/null
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse

I get this error
Warning: apt-key output should not be parsed (stdout is not a terminal)
E: Unable to locate package google-drive-ocamlfuse

The above code used to work for me previously.

**Comment by craigcitro** [comment]
This seems to be astrada/google-drive-ocamlfuse#492

**Comment by craigcitro** [comment]
An immediately applicable work-around is to use the built-in Drive FUSE client by running the snippet below to mount your Drive files:

    from google.colab import drive
    drive.mount('/content/drive')

**Comment by hidasri** [comment]
Thank you. When I try doing this, there is a 'My Drive' folder created inside 'drive'. Is there any way to avoid this additional folder. I just want to mount everything on '/content/drive'

**Comment by fischman** [comment]
It's not possible to avoid the 'My Drive' intermediate layer, but you can mount elsewhere and symlink just the contents you want back to /content/gdrive:

```
import os
from google.colab import drive
drive.mount('/gdrive')
os.symlink('/gdrive/My Drive', '/content/gdrive')
!ls -l /content/gdrive/
```

**Comment by Jmaihuire** [comment]
> An immediately applicable work-around is to use the built-in Drive FUSE client by running the snippet below to mount your Drive files:
> 
> ```
> from google.colab import drive
> drive.mount('/content/drive')
> ```

What if I just want to mount a folder from My Drive(not all of it-- too heavy)?

**Comment by jadevaibhav** [comment]
You provide the path to the directory inside the drive to drive.mount().

**Comment by jadevaibhav** [comment]
I just checked, providing path to drive.mount() does not work.
