### ISSUE TITLE
the newest version amongst all new and all old versions of python

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#2761]
the version of python on colab is,
```
Python 3.7.13
```
whereas on the official cpython repositoy, the version of python is,
```
Python 3.11.0a7+
```
due to this, certain features cannot be run on colab, such as,
```
def func(a, b, /, c=2, *, d=3, e=4):
    pass
```
```
x = 1
match x:
    case 1:
        print(True)
    case 2:
        print(False)
```
I would like to compare the `match-case` against `if-else`, but it is not possible due to the Python version problem.

the newer version of Python also introduces more detailed errors, but those dont appear with Python 3.7.

How do I install newer version of Python on colab, and I would like to keep it to the most recent version released on cpython, that is in case the next day Python 3.12 is released, then colab uses Python 3.12.

or give an option in settings, to add a custom python version, which would get downloaded and setup.

one way around is by doing something like this,
```
!sudo apt-get update -y
!sudo apt-get install python3.11
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 2
```
and then use `%%python3` in each block, but one would not want to do this for every notebook, so there should be a setting option.
plus `pip` does not appear to be working after using trick to update to `Python 3.11`

**Comment by cperry-goog** [comment]
#2165 tracks the Python update. We are not intending to support multiple Python versions in the near future.
