### ISSUE TITLE
Auth Window Click-off grace time

### ISSUE THREAD

**Issue by minerharry** [googlecolab/colabtools#2763]
When the auth window for mounting google drive or authenticating google cloud pops up in colab, there should be a grace time of a second or two where clicking off won't cancel the auth request. Usually those are the first two cells in all of my notebooks, and if I'm clicking on other things in the notebook while they're running it happens fairly frequently that I go to click a button, the auth window pops up for a split second, and the click cancels the auth and stops execution.

**Comment by cperry-goog** [comment]
Can you document how you encounter this, step by step?

**Comment by minerharry** [comment]
Sorry I missed this, typically I work in very long google colab notebooks where the first step is to mount google drive and authenticate with google cloud. These cells take some time to run (I'm mounting a lot of stuff from drive), so while they're running I like to queue up later cells or change parameters (input the particular files I will be using for that session into various fields) later in the notebook. As I am clicking around, sometimes the pop-up for drive mounting / authentication will come up just as I'm queuing up another cell or clicking a field:
![image](https://user-images.githubusercontent.com/35383543/168498278-e913921c-e819-4c8a-bcef-7e0b76dfe74f.png)
when this happens, unless I happen to be clicking within the box, the program will see me clicking outside the box and cancel the cell. When that happens, not only does the authentication get canceled, but all of the cells I've queued up get unqueued as well. This happens solely because of the time disconnect between me noticing the popup and me stopping myself from clicking, so if the popup simply wouldn't close from clicking off for even a fraction of a second after opening the problem would go away completely
