### ISSUE TITLE
"UnknownError:  Failed to get convolution algorithm" cuDNN error TF 2.6.3

### ISSUE THREAD

**Issue by vk1996** [googlecolab/colabtools#2765]
**Describe the current behavior**
"UnknownError:  Failed to get convolution algorithm" cuDNN error when running a simple tf.keras.applications.resnet50.ResNet50 model in the Tensorflow version 2.6.3. Works well for TF versions 2.4.0 & 2.8.0

Mostly linked to mismatch in cuDNN version for  TF 2.6.3

**Describe the expected behavior**

The model should predict the input tensor as resnet50 is a standard model from tf.keras applications 

**What web browser you are using**
Chrome

**Additional context**
https://colab.research.google.com/drive/1xftvBvjMnN_HtcShovldYDMcWKOT1GeT?usp=sharing

**Comment by cperry-goog** [comment]
Duping with #2656
