### ISSUE TITLE
Issue with Megadetector_Colab_test

### ISSUE THREAD

**Issue by cca8uk** [googlecolab/colabtools#2768]
Hi,

I've been using Megadetector_Colab_test available on Colab to classify camera trap images into the broad groups (animal, person, empty).  It's has worked flawlessly every time until today when I get the same error when running the batch process 

`!python run_tf_detector_batch.py megadetector_v4_1_0.pb "$images_dir" "$output_file_path" --recursive`

Traceback (most recent call last):
  File "run_tf_detector_batch.py", line 66, in <module>
    from detection.run_detector import ImagePathUtils, TFDetector
ImportError: cannot import name 'TFDetector' from 'detection.run_detector' (/content/CameraTraps/detection/run_detector.py)

I'm not intrinsically great a coding which is why this available colab was so useful.   Sadly I haven't been able to debug this. I checked back in the revision history to the last working version, and there doesn't appear to be any changes (other than the filepath to the source images, but have treble checked this is correct). Any ideas why a stable code has suddenly stopped working from yesterday to today without any obvious changes.

Cheerio

Chris

**Comment by cperry-goog** [comment]
We suspect this is a dependency problem: if you share a minimal repro notebook we can take a look.

**Comment by cca8uk** [comment]
I don't know how to minimise it any more than to say try running the public [Megadetecor Colab](https://colab.research.google.com/github/microsoft/CameraTraps/blob/master/detection/megadetector_colab.ipynb).  It produces the same error.  

I note that the run_tf_detector_batch.py which seems to be the point of failure was edited Yesterday on the [CameraTraps](https://github.com/microsoft/CameraTraps) repository, so I suspect one of the changes is the culprit as it worked perfectly on Wednesday.

**Comment by cperry-goog** [comment]
Just ran through the notebook and it works fine, got some sweet images output. Closing this, re-open if you have consistent steps.
