### ISSUE TITLE
Variable inspector stops working due to multibyte chars

### ISSUE THREAD

**Issue by beiz23** [googlecolab/colabtools#2769]
**Variable Inspector hangs-up when it runs a cell that contains multibyte characters**

For example, 

[1] a = 1
-> works.

[2] #Ａ
-> stop working.

[3] b = 2
-> does not updated.

This will occurs wherever multibyte chars are in the executed cell, regardless of quotes or comments. The inspector is so useful that I would be very happy if this bug was dealt with.

**What web browser you are using**
- Chrome : 100.0.4896.127 (Official Build) (x86_64)

**Comment by craigcitro** [comment]
Thanks for the report, that's a great bug! Tracked internally at b/230138968.

(We'll update again once a fix is rolled out.)

**Comment by blois** [comment]
This should be fixed now, thanks again for the great bug!

**Comment by beiz23** [comment]
Thank you very much for the quick fix!
