### ISSUE TITLE
Cannot click on authentication link when using google.colab.drive

### ISSUE THREAD

**Issue by fonnesbeck** [googlecolab/colabtools#277]
When trying to mount my Google Drive using the code from the snippet in Colab, I am presented with an output cell that includes a link to retrieve an authentication code for my account:

![image](https://user-images.githubusercontent.com/81476/45657181-d8d95e00-baae-11e8-9b8b-4fc7f5479c8a.png)

However, the link does not respond to clicks, nor does it allow the link to be selected, leaving me with no way to retrieve the code.

Running on Google Chrome on a PixelBook

**Comment by colaboratory-team** [comment]
Thanks for the report. We're looking into this. Does this issue recur if you interrupt the cell and try again?

**Comment by craigcitro** [comment]
Brainstorming: any chance you're running afoul of a popup blocker?

**Comment by craigcitro** [comment]
Brainstorming: any chance you're running afoul of a popup blocker?
