### ISSUE TITLE
TypeError: test() got an unexpected keyword argument 'test_dataloaders'

### ISSUE THREAD

**Issue by eshokr** [googlecolab/colabtools#2772]
I am trying to run the example named "# Tutorial 7: Graph Neural Networks"

It works well until this part
========================================
node_mlp_model, node_mlp_result = train_node_classifier(model_name="MLP",
                                                        dataset=cora_dataset,
                                                        c_hidden=16,
                                                        num_layers=2,
                                                        dp_rate=0.1)
========================================

it shows this error "TypeError: test() got an unexpected keyword argument 'test_dataloaders'"

I have tried it on google colab and on my local notebook but the same error appear

**Comment by craigcitro** [comment]
I'd try reporting the bug to whoever wrote the notebook.
