### ISSUE TITLE
When I execute my code, I have the following error: tcmalloc: large alloc 140423497228288 bytes

### ISSUE THREAD

**Issue by Mosaeidi** [googlecolab/colabtools#2775]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by craigcitro** [comment]
There's no repro info here, so it's hard to say, but I suspect you're hitting https://github.com/pyg-team/pytorch_geometric/issues/4539.
