### ISSUE TITLE
Apt-get dependencies in colab broken by NVIDIA signing key updates

### ISSUE THREAD

**Issue by samquinan** [googlecolab/colabtools#2779]
**Describe the current behavior**
Dependency installs with calls to `apt-get update` are broken (e.g., see step 0 of the [HelloMagenta tutorial]()). That call now results in the following errors:

```
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is no longer signed.
```

This appears to be a more general issue tied to NVIDIA updating and rotating the signing keys used by apt-get (see [developer blog](https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/) announcement and directions for updating the keys).

[Similar errors](https://github.com/NVIDIA/cuda-repo-management/issues/1?fbclid=IwAR3bczeu2yyqwTG1SgJqpu1BaxRdBLFB49VepYSj--3GpTvRLLmPV3KMrF4#issuecomment-1111435035) can be seen reported in NVIDIA repo with the solution from the developer blog provided as the response.

**Describe the expected behavior**
The expected behavior is for `apt-get update` to not throw signing errors.

**What web browser you are using**
Chrome

**Additional context**
[This link](https://gist.github.com/samquinan/5efb3515d44b51d2209945973bb7333b) should be a minimal, public, self-contained notebook that reproduces the issue, saved as a Github Gist.

**Comment by craigcitro** [comment]
Thanks for the (excellent) report -- this is indeed going to be nasty friction. I'm working on a fix, which can hopefully roll out tomorrow.

**Comment by craigcitro** [comment]
For anyone hitting this issue, an immediate workaround -- run this code in a cell by itself:

```
!wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.0-1_all.deb && dpkg -i cuda-keyring_1.0-1_all.deb && rm -f cuda-keyring_1.0-1_all.deb && rm -f /etc/apt/sources.list.d/cuda.list
```

**Comment by craigcitro** [comment]
internal tracking: b/230797939

**Comment by craigcitro** [comment]
Fix is live!
