### ISSUE TITLE
module 'pandas' has no attribute 'core'

### ISSUE THREAD

**Issue by ZoeBerling** [googlecolab/colabtools#2781]
Trying to import pandas:
import pandas as pd

but I get this error:
[/usr/local/lib/python3.7/dist-packages/pandas/_testing/__init__.py](https://localhost:8080/#) in <module>()
    946 
    947 
--> 948 cython_table = pd.core.common._cython_table.items()
    949 
    950 

AttributeError: module 'pandas' has no attribute 'core'

I tried upgrading and downgrading pandas but keep getting the same error.

**Comment by cperry-goog** [comment]
Can you provide a minimal repro notebook that demonstrates this problem? I can't reproduce this error.
