### ISSUE TITLE
MessageError: Error: credential propagation was unsuccessful

### ISSUE THREAD

**Issue by ZeliangSu** [googlecolab/colabtools#2782]
**Describe the current behavior**
I ran into this error suddenly today, while doing `from google.colab import drive` then `drive.mount('/content/drive/')`. I tried all the solutions in this [post](https://stackoverflow.com/a/69881106/9217178), but nothing works.

**Describe the expected behavior**
Drive mounted

**What web browser you are using**
Tried both Chrome and Safari

**Additional context**
I'm using a Google Pro account

**Comment by cenktaskin** [comment]
Have the same problem. Before I was somehow mounting the drive from the button and worked. Now I'm prompted to run the aforementioned cell and it prompt a pop-up window. Which always end up with "Something went wrong".

**Comment by cperry-goog** [comment]
Are you trying to mount Drive on the same account you're signed into?

**Comment by ZeliangSu** [comment]
@cperry-goog I do think that's a mistake of mine having two same notebooks running not properly closed, I will close this
