### ISSUE TITLE
Session getting crashed every time

### ISSUE THREAD

**Issue by shivam-vaish** [googlecolab/colabtools#2783]
**Describe the current behavior**

from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog, DatasetCatalog

I am trying to import these libraries but when I import these libraries my session got crashed this is happening when i am training my data to SSD resnet and SSD centernet model with both GPU and TPU. This is happening for 3-4 days now.

**Describe the expected behavior**

1st I expected to import these libraries as it was previously able to do and run and train my model perfectly.

**What web browser you are using**

Chrome

**Additional context**

(https://colab.research.google.com/drive/1t7VICSzyDQ2cJHfZ64xOV_6TdT0jBmmk?usp=sharing)

**Comment by cperry-goog** [comment]
We took a look through the notebook and it appears you've got it working? Can you provide a minimal repro notebook if you can narrow down to a specific step?

**Comment by IceCream-cca** [comment]
I'm also facing the same problem. whenever I imported detectron2 packages, it is showing that " the session crush for unknow reason". Please help
