### ISSUE TITLE
After updating python version to 3.9 this error rise ModuleNotFoundError: No module named 'pip'

### ISSUE THREAD

**Issue by t-alanazi** [googlecolab/colabtools#2784]
After upgrading python version in Colab to 3.9 using these commands:

!sudo apt-get update -y
!sudo apt-get install python3.9
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2
!python --version

It became Python 3.9.12. 

But when I tried to run this code :
!pip install --quiet --upgrade tensorflow-federated
I got this error:
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'

Then, I tried to check, install or upgrade pip in different ways with no luck!
I used these ways: 

python -m ensurepip --default-pip
got this error: 
    python -m ensurepip --default-pip
                      ^
SyntaxError: invalid syntax

curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py --force-reinstall
got this error:
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
             ^
SyntaxError: invalid syntax

sudo python3 -m pip install --upgrade pip
got this error:
sudo python3 -m pip install --upgrade pip
               ^
SyntaxError: invalid syntax

python3 -m pip install --upgrade pip
got this:
python3 -m pip install --upgrade pip
                 ^
SyntaxError: invalid syntax

wget https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py
got this:
wget https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py
             ^
SyntaxError: invalid syntax

Does my updating for python to 3.9 wrong? And when I open new colab notebook, and check the version of python, it returned 3.7 again! 

Can you give me the right way to update python version with pip ?

Appreciate any help!

**Comment by cperry-goog** [comment]
We don't support upgrading Python version in Colab at this time. You could run your own VM in Marketplace and upgrade there, and you may have better luck: https://research.google.com/colaboratory/marketplace.html

Separately, we're looking into the Python upgrade generally.
