### ISSUE TITLE
RuntimeError: CUDA error: misaligned address CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

### ISSUE THREAD

**Issue by ppdayz888** [googlecolab/colabtools#2788]
I searched all over for a fix to this & nothing I found helped... 
Cleared ALL sessions restarted everything & still get this error? 

RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

How do I fix this? 

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by Kelier** [comment]
Yes, I had it too, it was very bad, it ruined my project, even the paid experience couldn't avoid it

**Comment by craigcitro** [comment]
It's impossible for us to provide any help or pointers without knowing what code you're running. 

Please include a minimal, self-contained, public repro notebook (as suggested in the issue template).

**Comment by Kelier** [comment]
> It's impossible for us to provide any help or pointers without knowing what code you're running.
> 
> Please include a minimal, self-contained, public repro notebook (as suggested in the issue template).


I classify it as unstable for colab, because the same configuration sometimes works and sometimes goes wrong, all I can do is recreate a copy from scratch

**Comment by tampicokid** [comment]
I was producing images happily all last week and this just started happening to me. Same CUDA error. No matter how many times I try it fails. This is my first post on GitHub XD

**Comment by craigcitro** [comment]
Does the workaround from https://github.com/pyg-team/pytorch_geometric/issues/4539#issuecomment-1109465921 get you unblocked?

**Comment by kvkamal** [comment]
I'm starting to see this now.  Trying to run ultralytics YOLOV8 training from.  Has there been any updates to Cuda/Ultralytics?

[/usr/local/lib/python3.10/dist-packages/ultralytics/utils/tal.py](https://localhost:8080/#) in get_box_metrics(self, pd_scores, pd_bboxes, gt_labels, gt_bboxes, mask_gt)
    111         ind[1] = gt_labels.squeeze(-1)  # b, max_num_obj
    112         # Get the scores of each grid for each gt cls
--> 113         bbox_scores[mask_gt] = pd_scores[ind[0], :, ind[1]][mask_gt]  # b, max_num_obj, h*w
    114 
    115         # (b, max_num_obj, 1, 4), (b, 1, h*w, 4)

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
