### ISSUE TITLE
bug with cv2 library

### ISSUE THREAD

**Issue by niket709** [googlecolab/colabtools#279]
whenever i try to run 

**### cv2.imshow('IM',image)**

the colab notebook shows error and get restarted.

**Comment by vahidajalluian** [comment]
Also the same issue.

**Comment by rodrigosilvafe** [comment]
I am working on colab and also have the same issue, any solution?

**Comment by craigcitro** [comment]
duping against #458 -- there's a potential workaround mentioned there.
