### ISSUE TITLE
running encode text in googe colab notebook

### ISSUE THREAD

**Issue by REXX-dev** [googlecolab/colabtools#2790]
how their run encode text in Google Colab?

**Comment by REXX-dev** [comment]
![Untitled](https://user-images.githubusercontent.com/79816772/166225915-2d1af3ef-7df0-4bc3-a2d8-db1e2edbf846.jpg)
this for example

**Comment by REXX-dev** [comment]
![caem](https://user-images.githubusercontent.com/79816772/166226003-b86be597-ad5f-4209-9467-487ed0ecabc4.PNG)
this for example

**Comment by craigcitro** [comment]
https://research.google.com/colaboratory/faq.html#:~:text=using%20a%20remote%20desktop%20or%20ssh
