### ISSUE TITLE
Session crashed when import torch_geometric

### ISSUE THREAD

**Issue by charloe2000** [googlecolab/colabtools#2792]
**Describe the current behavior**
I did nothing except importing torch_geometric after pip install it, but session crashed for unknown reason.

**What web browser you are using**
Chrome

**Additional context**
https://colab.research.google.com/drive/1Iz46Tg9t2dBEKBHH74Xzlqp9MdF0nj42?usp=sharing

**Comment by craigcitro** [comment]
See https://github.com/pyg-team/pytorch_geometric/issues/4539
