### ISSUE TITLE
Updated ESRGAN.ipynb

### ISSUE THREAD

**Issue by 2022lena** [googlecolab/colabtools#2795]
**Describe the current behavior**
After the upload, the following error always comes up. Tested with different images, always the same problem. and with the Pro version, there should be no resource problems. also tested on different days and times. "inference_realesrgan.py: error: unrecognized arguments: --half
/content"

**Describe the expected behavior**
A few weeks ago everything was still working

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'. https://colab.research.google.com/drive/1O8kr-iyRll5eQsaOH-vQIc3ImEKWsvF-?usp=sharing

**Comment by cperry-goog** [comment]
This looks like an issue with the code in the notebook; you'll want to contact the notebook author.

**Comment by blois** [comment]
The `--half` argument was removed in https://github.com/xinntao/Real-ESRGAN/commit/cddc2ff658082ac15ed8492731a827ba640bdc83.
