### ISSUE TITLE
Simple transformers training issue

### ISSUE THREAD

**Issue by rahulponnusamyofficial** [googlecolab/colabtools#2796]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
Currently, I am training a transformer model using simple transformer package. Every this is going we till the model setup part but when it comes to training. Training is not happening at all. I tried it in other environment it works well. 
**What web browser you are using**
Opera

**Comment by cperry-goog** [comment]
Can you share a minimal repro notebook?

**Comment by rahulponnusamyofficial** [comment]
Colab link: https://drive.google.com/file/d/1LP4fc5Pik0i4nTjl8Kyrs18Vb-CrcRKd/view?usp=sharing

In this notebook, you can find the "model.train_model(train)". It is not even training, it is staying at this step for the time i let it run (it had run for 5 hours at that step without training). At one point, the model is trained, but I can't able to predict the model.

**Comment by cperry-goog** [comment]
We looked it over, not clear if Colab is the issue: you'll want to connect w/ simpletransformers folks.
