### ISSUE TITLE
Runtime dies whenever Keras is called for execution

### ISSUE THREAD

**Issue by rajatthepagal** [googlecolab/colabtools#28]
I am using this tool for first time and I set up the tool for using GPU . I installed tensorflow with GPU and tensorflow in itself is working fin. But when keras is called which uses tf as backend the session dies and restarts.

**Comment by fischman** [comment]
Thanks for the report. Do you have a repro notebook you can share publicly demonstrating this, or at least one you can share with colaboratory-team@google.com ?

**Comment by rajatthepagal** [comment]
https://colab.research.google.com/notebook#fileId=1ra-c-wjfp9n9s-OPq17ifI6N6wqvRQYh

Ya, this is my notebook. And surprisingly today it is working. Since the problem was for only GPU environment I think maybe it was not allocated GPU VMs , that is why the issue crept up.

**Comment by fischman** [comment]
Glad to hear it's working now.  You can see whether you're connected to a GPU runtime by hovering the CONNECTED at the top-right of the UI.
The notebook is not shared so I can't see its contents.

**Comment by craigcitro** [comment]
Marking closed, but @rajatthepagal please do reopen if you can repro.

**Comment by rajatthepagal** [comment]
@craigcitro ya sure. @fischman ya i was new to it so did not exactly realised how the sharing worked. I am sharing a new link for it that is globally shared. Now its working though. Will reopen if any issue creeps up again. 
Link: https://colab.research.google.com/notebook#fileId=1ra-c-wjfp9n9s-OPq17ifI6N6wqvRQYh

Hope you can see it i have shared it publicly. It was just a test notebook for my peers and juniors in college to know and get started with collab.

**Comment by fischman** [comment]
Thanks. Note that you shouldn't need to uninstall and reinstall
tensorflow-gpu. The VM has  it preinstalled, and the build that is
preinstalled is compiled with more aggressive optimization than the
pip-installable version is built with, so reinstalling will actually slow
things down.

**Comment by rajatthepagal** [comment]
Ya i read about it later. I thought the one installed is not by default tensorflow-gpu :-D thanks for the info.

**Comment by sourcecode369** [comment]
Same happens with me. No matter whichever runtime type I use, AutoKeras kills the runtime and then automatically restarts the notebook. I'm kind of fed up now.

**Comment by 13beehiqbal** [comment]
@sourcecode369  @vaibhavgarg1982 Did you find any solution to this?
