### ISSUE TITLE
An external source of truth for google colab runtime environment definition.

### ISSUE THREAD

**Issue by startakovsky** [googlecolab/colabtools#2800]
**Is your feature request related to a problem? Please describe.**
I want an easy way to understand what is installed with google colab.

**Describe the solution you'd like**
I would like to have a github link to this repo or somewhere else where I can just see exactly what to expect with the default Google Colab settings.

**Describe alternatives you've considered**
The thing people on the internet recommend is to just "pip freeze" but that doesn't give a full picture, and just seems hacky and unreliable and no visibility into how things evolved (version control) over the months / years past. Imagine trying to understand why a notebook ran without errors last month and this month is broken. Maybe it was a new Python version, for example.

**Additional context**
Yes, I have a stackoverflow question on this topic that is not getting any love: https://stackoverflow.com/questions/72148172/where-is-the-official-manifest-definition-of-google-colabs-environment

**Comment by cperry-goog** [comment]
This is a good idea and something we aspire to do someday. Duping with #1445
