### ISSUE TITLE
Run tensorflow sample code occurred OSError: PortAudio library not found

### ISSUE THREAD

**Issue by dh20156** [googlecolab/colabtools#2801]
Tensorflow sample code: https://codelabs.developers.google.com/tensorflow-retraining-comment-spam-detection#3

import numpy as np
import os

from tflite_model_maker import configs
from tflite_model_maker import ExportFormat
from tflite_model_maker import model_spec
from tflite_model_maker import text_classifier
from tflite_model_maker.text_classifier import DataLoader

import tensorflow as tf
assert tf.__version__.startswith('2')
tf.get_logger().setLevel('ERROR')

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[<ipython-input-18-a2ebdbf2eeb3>](https://localhost:8080/#) in <module>()
      2 import os
      3 
----> 4 from tflite_model_maker import configs
      5 from tflite_model_maker import ExportFormat
      6 from tflite_model_maker import model_spec

11 frames
[/usr/local/lib/python3.7/dist-packages/sounddevice.py](https://localhost:8080/#) in <module>()
     69             break
     70     else:
---> 71         raise OSError('PortAudio library not found')
     72     _lib = _ffi.dlopen(_libname)
     73 except OSError:

OSError: PortAudio library not found

How to fix it?

**Comment by cperry-goog** [comment]
Thanks for flagging, we'll route to the team who wrote the code.

**Comment by blois** [comment]
Workaround is to add:

```
!apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
```

**Comment by dh20156** [comment]
It works, thanks ;-)

**Comment by jasonmayes** [comment]
Thanks for flagging this. I will update the TensorFlow.js codelab with the new change needed.
