### ISSUE TITLE
Trying To Add Slow Slow Mo For Smoothing in VQGAN+Clip (With Animations)

### ISSUE THREAD

**Issue by AFreelanceAnimator** [googlecolab/colabtools#2804]
Hello, Ive been trying my hand at some AI Artwork using VQGAN+Clip with Animations.  Everything works perfectly and can even download the video but soon as i try do the last step for smoothing it errors with this:

Screenshot: https://ibb.co/fDMVFgC

**Describe the expected behavior**
Smooth the video and allow me to download the final render.

**What web browser you are using**
Chrome 

The Colab I'm Using:
https://colab.research.google.com/github/chigozienri/VQGAN-CLIP-animations/blob/main/VQGAN-CLIP-animations.ipynb#scrollTo=2hT5Lhgs0gwe

Thanks for anyhelp with this, im using Colab Pro so i don't think its a GPU issue or anything :)

- Chris

**Comment by cperry-goog** [comment]
You'll need to contact the notebook author.
