### ISSUE TITLE
Colab crahses when we try to use `tf-nightly` version

### ISSUE THREAD

**Issue by chunduriv** [googlecolab/colabtools#2805]
**Describe the current behavior**
Colab crahses when we try to use `tf-nightly` version for `2.10.0.dev20220514`, `2.10.0.dev20220515`,`2.10.0.dev20220516` and `2.10.0.dev20220517`.

Your session crashed for unknown reason.

**Describe the expected behavior**
It should successfully import tf-nightly version

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 https://colab.research.google.com/gist/chunduriv/1050c12f55b953e157466ea4b4c06ded/colab-crash.ipynb

**Comment by cperry-goog** [comment]
Unfortunately, we don't support all tf-nightly releases. We resolve these sorts of issues when we upgrade TensorFlow on the Colab runtime image, but we don't keep up with nightly builds.

I'd love to hear your use case though, to see if there are other things we can do to help.

**Comment by chunduriv** [comment]
This issue is fixed now.Thank you.
