### ISSUE TITLE
'EasyEnsembleClassifier' object has no attribute 'n_features_in_'

### ISSUE THREAD

**Issue by AdelAbbas2022** [googlecolab/colabtools#2811]
I had an error when I tried to apply "EasyEnsembleClassifier." I tried many solutions that I found online, but with no success.

Error:
'EasyEnsembleClassifier' object has no attribute 'n_features_in_'

I need help fixing this issue and making the code works for this method.

**Comment by cperry-goog** [comment]
Could you please share a minimal repro notebook?
