### ISSUE TITLE
Stuck with t4's and p100's on Pro+ after payment failed (card expired) and new payment card added

### ISSUE THREAD

**Issue by delphium226** [googlecolab/colabtools#2813]
**Describe the current behavior**
For at least a week, only T4's and p!00's have been assigned to my sessions. Have tried terminating the sessions and requesting new ones many times.
This behavour seemed to occur after a monthly payment failed because the card expired. A new card was added and a payment for pro+ was put through. The Settings feature tells me I'm a Pro+ subscriber.

**Describe the expected behavior**
To at least be assigned a v100 or better occasionally.

**What web browser you are using**
Chrome

**Additional context**
https://colab.research.google.com/drive/124-O1cJlBGXBztECsj5rxvTf0b1-9n2Y?usp=sharing

**Comment by sebbov** [comment]
Internally tracked at b/233350535.  This should be fixed by early next week.  If you still see issues, reach out to our payments support at colab-help@google.com and reference this github issue.
