### ISSUE TITLE
Session Crashing: exhausted RAM in 1.5GB for Colab pro+

### ISSUE THREAD

**Issue by thilaragunath** [googlecolab/colabtools#2817]
Session keep crashing while executing TfidfVectorizer mentioning exhausted the RAM. But when I check the session only 1.5GB is used. 
I could not move further with my coding. Please help

Console:
Undo option in the Edit menu
DevTools failed to load source map: Could not load content for https://colab.research.google.com/v2/common/webcomponentsjs/v2/webcomponents-lite.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://colab.research.google.com/v2/common/webanimationsjs/web-animations-next-lite.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://colab.research.google.com/v2/external/js/min-maps/vs/editor/editor.main.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://colab.research.google.com/v2/external/js/min-maps/vs/loader.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://colab.research.google.com/v2/external/js/min-maps/vs/base/worker/workerMain.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
external_polymer_binary.js?vrz=colab-20220518-060055-RC00_449411064:1972 Your session crashed. Automatically restarting.
external_polymer_binary.js?vrz=colab-20220518-060055-RC00_449411064:5210 Ignoring benign restart error: CustomError: Runtime restarted at: 
 Error
    at K7 (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20220518-060055-RC00_449411064:5108:279) ....
.......
external_polymer_binary.js?vrz=colab-20220518-060055-RC00_449411064:1972 Your session restarted after a crash. Diagnosing...
external_polymer_binary.js?vrz=colab-20220518-060055-RC00_449411064:1972 Your session crashed after using all available RAM.

**Comment by ylchang** [comment]
I have the same issue. I am trying to read a csv file of less than 5Gbit, and I have Colab Pro+, but my code kept crashing due to Session Crashing: exhausted RAM. Need urgent help!!!

**Comment by cperry-goog** [comment]
We can't troubleshoot much without a minimal repro notebook.
