### ISSUE TITLE
while running run prediction, appears: RuntimeError: Error loading imports from extension module

### ISSUE THREAD

**Issue by miaolegemi1000** [googlecolab/colabtools#2821]
RuntimeError: Error loading imports from extension module appear while i was running file i run before without pro

**Comment by miaolegemi1000** [comment]
the error immediately happened when I up grade my version from nonpayment to colabpro. my friend account without pro version work smoothly.

**Comment by cperry-goog** [comment]
Can you share a minimal reproducible notebook?
