### ISSUE TITLE
Colab Runtime disconnecting within 30 seconds of running a cell

### ISSUE THREAD

**Issue by shankhiremath** [googlecolab/colabtools#2824]
**Describe the current behavior**
The runtime is getting disconnected within 30 seconds of running a cell despite good internet connection.

**Describe the expected behavior**
No disconnection.

**What web browser you are using**
I observed this in Chrome and Firefox.

**Additional context**
Pictures of the errors in the console:
<img width="465" alt="colab error" src="https://user-images.githubusercontent.com/45012110/170020832-dbd010a0-2f93-4b4f-9b5b-2d6bc3adcbb0.png">
<img width="463" alt="colab error 2" src="https://user-images.githubusercontent.com/45012110/170020841-6c51ca5e-7f46-492d-8848-37b0471de6a2.png">
<img width="460" alt="colab error 3" src="https://user-images.githubusercontent.com/45012110/170020846-0311fb1d-0a46-42f5-bd33-709007fa3aa9.png">

**Comment by craigcitro** [comment]
Could you provide a public, minimal repro notebook?

**Comment by shankhiremath** [comment]
I solved the issue. Thanks.
