### ISSUE TITLE
I paid for the Colab Pro but I'm in the forbidden country

### ISSUE THREAD

**Issue by Nickdog222** [googlecolab/colabtools#2826]
I paid for the Colab Pro but I'm in the forbidden country.

If Colab Pro can't be used in some countries, it shouldn't be booked and charged. 
Else if it can be booked and charged, it's not in a forbidden country.

**Comment by cperry-goog** [comment]
Not sure what you mean by forbidden country; Colab uses Google Pay rails for billing restricted to billing country per an allowlist. If you're making it through you should be in an approved country.

**Comment by Nickdog222** [comment]
I'm in Taiwan, which is not in the allowlist and I still got the bill pay for it. How can I check if the Colab Pro works or not?
