### ISSUE TITLE
https://colab.research.google.com/ cannot find a **public** GitHub repository

### ISSUE THREAD

**Issue by TomasVaskevicius** [googlecolab/colabtools#2844]
There appears to be a potential bug in listing the public GitHub repositories through https://colab.research.google.com/.

1) The repository in question is https://github.com/alan-turing-institute/mathematics-of-ml-course/.

2) When trying to search for the above repository through the colab.research.google.com web interface, the "mathematics-of-ml-course" repository does not appear in the list of alan-turing-institute repositories. See the image below.
![mathematics-of-ml-course](https://user-images.githubusercontent.com/8312273/172042257-1490910d-0378-46ea-a30a-3aff37fb4dc5.png)

3) Approximately one year ago, this bug did not exist -- it was possible to load the notebooks located in the "mathematics-of-ml-course" repository through the https://colab.research.google.com/ web interface. 

4) Note that it is still possible to load the notebooks from the "mathematics-of-ml-course" via direct links. For example, clicking on the following link works: https://colab.research.google.com/github/alan-turing-institute/mathematics-of-ml-course/blob/master/practicals/compressed_sensing.ipynb.

**Comment by cperry-goog** [comment]
We suspect we're dropping it as the list of repos is very long. Tracking this internally at b/235514809
