### ISSUE TITLE
I can't connect to colab anymore for a few days

### ISSUE THREAD

**Issue by dariodellamura** [googlecolab/colabtools#2845]
For a few days I have not been able to connect to Colab with my personal accounts (even with my university google account). I get this error message: "Sorry, no backend available. Please try again later", even when I don't connect with runtime gpu but try to connect with runtime none. I need google colab at all costs, in July I have to graduate and I still have some experiments to complete.
What can I do? I don't know what it can be. It is not the usage limit because I have not been able to connect with any account in my possession for days.

thanks all.

**Comment by sebbov** [comment]
If this is still a problem, please submit feedback in product within Colab at Help > Send feedback.
