### ISSUE TITLE
wrong outcome for package function

### ISSUE THREAD

**Issue by mahmoud-alsahlee** [googlecolab/colabtools#2847]
**Describe the current behavior**
The outcome of the bleu score calculation for the b3 and b4 is not correct. where the outcome on google colab is not correct while running it locally on my hardware (Jupyter notebook) is giving the right answer. as can be seen in the following example:

# cumulative BLEU scores
from nltk.translate.bleu_score import sentence_bleu
reference = [['this', 'is', 'small', 'test']]
candidate = ['this', 'is', 'a', 'test']
print('Cumulative 1-gram: %f' % sentence_bleu(reference, candidate, weights=(1, 0, 0, 0)))
print('Cumulative 2-gram: %f' % sentence_bleu(reference, candidate, weights=(0.5, 0.5, 0, 0)))
print('Cumulative 3-gram: %f' % sentence_bleu(reference, candidate, weights=(0.33, 0.33, 0.33, 0)))
print('Cumulative 4-gram: %f' % sentence_bleu(reference, candidate, weights=(0.25, 0.25, 0.25, 0.25)))

**Describe the expected behavior**
the local hardware gives the answer:

Cumulative 1-gram: 0.750000
Cumulative 2-gram: 0.500000
Cumulative 3-gram: 0.000000
Cumulative 4-gram: 0.000000

while the colab gives:
Cumulative 1-gram: 0.750000 
Cumulative 2-gram: 0.500000 
Cumulative 3-gram: 0.632878 
Cumulative 4-gram: 0.707107​

and the correct answer is:
Cumulative 1-gram: 0.750000
Cumulative 2-gram: 0.500000
Cumulative 3-gram: 0.000000
Cumulative 4-gram: 0.000000

**What web browser you are using**
Using Google Chrome

**Comment by cperry-goog** [comment]
This is a great bug report, thanks. Our version of nltk is out of date, we'll upgrade it. Tracking here: b/235514201

To fix this, run `!pip install --upgrade nltk`  then restart your runtime, and you'll get the correct results.

**Comment by colaboratory-team** [comment]
nltk upgrade is now live in prod, confirmed that the above code snippet now returns the expected values. Thanks for the report!
