### ISSUE TITLE
_batch_encode_plus() got an unexpected keyword argument 'is_pretokenized' using BertTokenizerFast

### ISSUE THREAD

**Issue by MariRazno** [googlecolab/colabtools#2849]
**Describe the current behavior**
Versions conflict

**Describe the expected behavior**
Output as in the example

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
I think you'll want to flag this issue with the BertTokenizerFast authors.
