### ISSUE TITLE
error with Super-Enhance the Generated Image

### ISSUE THREAD

**Issue by DivePADI** [googlecolab/colabtools#2850]
/content/Real-ESRGAN
usage: inference_realesrgan.py [-h] [-i INPUT] [-n MODEL_NAME] [-o OUTPUT]
                               [-s OUTSCALE] [--suffix SUFFIX] [-t TILE]
                               [--tile_pad TILE_PAD] [--pre_pad PRE_PAD]
                               [--face_enhance] [--fp32]
                               [--alpha_upsampler ALPHA_UPSAMPLER] [--ext EXT]
                               [-g GPU_ID]
inference_realesrgan.py: error: unrecognized arguments: --half
/content

**Comment by cperry-goog** [comment]
This looks like a dupe of https://github.com/xinntao/Real-ESRGAN/issues/324
