### ISSUE TITLE
Google colab Runtime error: Failed to initialize SDL

### ISSUE THREAD

**Issue by Shivam310** [googlecolab/colabtools#2852]
I have been recently getting this colab error. Whenever I run a certain cell the colab notebook throws this error:
`    RuntimeError                              Traceback (most recent call last)
<ipython-input-7-feca46536a5c> in <module>()
----> 1 env = gym.make('ALE/Breakout-v5', render_mode='human')
      2 env = Recorder(env, './video')

2 frames
/usr/local/lib/python3.7/dist-packages/gym/envs/atari/environment.py in seed(self, seed)
    194                 "https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management"
    195             )
--> 196         self.ale.loadROM(getattr(roms, self._game))
    197 
    198         if self._game_mode is not None:

RuntimeError: Failed to initialize SDL`
I have all the necessary libs installed and I have also tried restarting the colab multiple times. Please help. Thx

**Comment by cperry-goog** [comment]
I'll need a minimal repro notebook to check this out.
