### ISSUE TITLE
wordwrap

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#2854]
current scenario -
1) if the output goes beyond the screen width, then it would display a horizontal scroll bar
![Screenshot (1089)](https://user-images.githubusercontent.com/43755000/173211149-d79149d1-c43f-43c3-8561-d764e3f4790f.png)

expected scenario -
1) give an option in settings to enable wordwrap, so if output goes beyond the screen width, and wordwrap is on, then instead of horizontal scroll bar, the output moves to the next line.

**Comment by cperry-goog** [comment]
tracked internally at b/236299760

**Comment by blois** [comment]
This should be fixed now.
