### ISSUE TITLE
Running out of memory as free user and Pro user?

### ISSUE THREAD

**Issue by cbmtrx** [googlecolab/colabtools#2855]
I had been using a public Colab **successfully** for a couple days as a free Colab user. Then last night I suddenly started getting Out Of Memory errors. I actually tried a second Google account to double-check whether it was an account-related issue but I got the same behavior.

So this morning I paid for Colab Pro, expecting that any memory issues would be covered. Not so, I get exactly the same failure (as others here have asked: what am I paying for?).

This is the error I get—typically 2-3 minutes after starting it:

_"RuntimeError: CUDA out of memory. Tried to allocate 232.00 MiB (GPU 0; 14.76 GiB total capacity; 12.97 GiB already allocated; 29.75 MiB free; 13.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"_

**UPDATE: Now I'm getting this error: "ConnectionResetError: [Errno 104] Connection reset by peer" In Colab Pro?

**Describe the expected behavior**
As a Pro user I expected to get the Colab to run better and more reliably than I had done as a free user (ie: no memory/disconnect problems).

**What web browser you are using**
Chrome

**Additional context**
This is the Colab I was using:
https://colab.research.google.com/github/chigozienri/VQGAN-CLIP-animations/blob/main/VQGAN-CLIP-animations.ipynb

I'm not sure if any other info would be helpful. I've been rendering at 720x480 (these dimensions were *working* as a free user).

Cheers.

**Comment by cperry-goog** [comment]
Looks like you're running out of GPU memory; all of our chips have the same memory profile so I have no ideas beyond reducing the memory footprint of what you're trying to fit into the GPU.
