### ISSUE TITLE
02.06-Visualization-and-PyMOL-Mover.PyRosetta-ColabPyMOL-integration.ipynb does not complete

### ISSUE THREAD

**Issue by ascusf** [googlecolab/colabtools#2856]
**Describe the current behavior**
https://colab.research.google.com/github/RosettaCommons/PyRosetta.notebooks/blob/master/notebooks/02.06-Visualization-and-PyMOL-Mover.PyRosetta-ColabPyMOL-integration.ipynb#scrollTo=jna_I3lJJ7EK

This code below keeps running.

import time as time_module

import pyrosetta
import pyrosetta.rosetta as rosetta

pose = pyrosetta.pose_from_sequence('SERGEY'*2)
rosetta.protocols.moves.AddPyMOLObserver(pose, keep_history=False)

scorefxn = pyrosetta.get_fa_scorefxn() #  rosetta.create_score_function('standard')

psi = 0.0
phi = 0.0
i = 1
while True:
    pose.set_psi(i, pose.psi(i) + 87)
    pose.set_phi(i, pose.phi(i) + 19)
    scorefxn(pose)

    time_module.sleep(.05)
    i += 1
    if i >pose.size(): i=1

**Describe the expected behavior**
How long should it run?

**What web browser you are using**
Firefox

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
I'd ask the notebook author. Offhand that looks like an interminable while loop.
