### ISSUE TITLE
Cannot change location on Payment details (Not in the US)

### ISSUE THREAD

**Issue by Voxolis** [googlecolab/colabtools#2857]
Hi, 
I use Firefox 101.0.1
I try to purchase a subscription at Colab Pro but cannot change the location/Zip Code from reselected "US". I cannot go past that. 

Many thanks for your assistance.

![Screenshot 2022-06-13 at 18 29 51 (2)](https://user-images.githubusercontent.com/107424864/173401165-8fc16b71-6d1a-4328-950f-2db188ddfc0c.png)

**Comment by cperry-goog** [comment]
https://support.google.com/pay/answer/7644076#changecountry should be the right path here.

**Comment by AnandNimaiDas** [comment]
facing same issue

**Comment by Sarah-Kamoun** [comment]
same problem here

**Comment by sedlund** [comment]
same - oh well no money for you google!

**Comment by cperry-goog** [comment]
As shown above, https://support.google.com/pay/answer/7644076#changecountry  should get you in the right place.

**Comment by sedlund** [comment]
> As shown above, https://support.google.com/pay/answer/7644076#changecountry should get you in the right place.

No it does not.

**Comment by sedlund** [comment]
Colab does not seem to see my Google Pay settings where I have 5 saved credit cards with my US address.  Colab wants to chage me 11.75 EUR.  It wants me to enter a NEW credit or debit card.

![image](https://github.com/googlecolab/colabtools/assets/8109138/cb3b7ebb-953d-4ced-ade4-1466616979d1)
![image](https://github.com/googlecolab/colabtools/assets/8109138/097aefeb-2759-468f-b003-51f0044e0bff)


Cannot change country.

**Comment by cperry-goog** [comment]
I'm guessing you have two payments profiles - one for the US and one for Hungary (in screenshot). If you navigate to payments.google.com can you switch profiles to the US profile? That will be the one used for Google Pay transactions like Colab.

**Comment by sedlund** [comment]
> I'm guessing you have two payments profiles - one for the US and one for Hungary (in screenshot). If you navigate to payments.google.com can you switch profiles to the US profile? That will be the one used for Google Pay transactions like Colab.

No, you'd be wrong. I have one profile only in the USA.

**Comment by daniellm19** [comment]
I have the same issue. I'm in Iceland and in the settings it says my country/region is Iceland, and my payment method is also in Iceland, and my addresses as well. Yet it asks for a new credit or debit card which is exclusively in the United States (US)?

**Comment by daniellm19** [comment]
Interesting, what about compute units? It still defaults to United States there. I'm surprised since universities in Iceland have used Collab and have given their students compute units.

**Comment by katlyn-edwards** [comment]
Compute units purchases have the same country restrictions unfortunately

**Comment by johanneskopton** [comment]
> Hey there! We're only launched in the following countries:
> 
> United States of America, Canada, Brazil, France, Germany, India, Japan, Thailand, United Kingdom, Ireland, Israel, Italy, Morocco, Netherlands, Poland, Spain, Switzerland, Turkey, United Arab Emirates, Australia, Bangladesh, Colombia, Hong Kong, Indonesia, Mexico, New Zealand, Pakistan, Philippines, Singapore, Taiwan, Vietnam, Austria, Belgium, Bulgaria, Czech Republic, Denmark, Finland, Greece, Hungary, Portugal, Sweden, Cyprus, Estonia, Croatia, Lithuania, Latvia, Norway, Romania, Slovenia, Slovakia, Algeria, Egypt, Ghana, Kenya, Nigeria, Rwanda, South Africa, Tunisia, Malaysia, Nepal, Saudi Arabia, Sri Lanka, Ukraine, Argentina, Chile, Ecuador, and Peru
> 
> If you're not in one of these countries, the payment flow will default/fallback to the US.

Sorry, but I think this problem has nothing to do with this. I have the same problem with a billing address in Germany and currently being in the Netherlands. Both are in the list, still I cant use my German credit card.

**Comment by SuperElectron** [comment]
same issue

**Comment by senku-kz** [comment]
same problem on Ubuntu 22.04 Firefox

**Comment by alexsuakim** [comment]
I'm having the same problem in Hong Kong although it is in the available countries list. I am physically in Hong Kong with only one payment profile which is based in Hong Kong. When I try to subscribe to Colab Pro I can't change the country from the US to Hong Kong. The provided link doesn't help.

**Comment by mina-naseh** [comment]
Same problem. I am in Luxembourg and can not change my region from US to Luxembourg.

**Comment by lucgrefte** [comment]
Same issue.

In account settings my payment method has a Dutch address. My account address is also Dutch. I can only pay from the US.

**Comment by rz1027** [comment]
Reopen this issue, it is not fixed.

**Comment by evasahlholdt** [comment]
Also facing the same issue (Denmark)

Typing in a random US postal code fixes the problem, but not sure that's entirely legal.

**Comment by samuel23taku** [comment]
> Also facing the same issue (Denmark)
> 
> Typing in a random US postal code fixes the problem, but not sure that's entirely legal.

Worked for me(Zimbabwe). I'll deal with the consequences later

**Comment by derspotter** [comment]
Yes, the issue persists. German payment profile, but can only type in US credit cards. REOPEN!!!

**Comment by ansemin** [comment]
I still have the same issue -- does not let me change the country despite following the preceeding guide

**Comment by robertoshea** [comment]
same issue on 13-Jun-2025

**Comment by research-yassin** [comment]
It is you where your current IP address. You need a VPN work around.
