### ISSUE TITLE
Syntax checker assumes Python code in %%writefile cells

### ISSUE THREAD

**Issue by tueda** [googlecolab/colabtools#2859]
**Describe the current behavior**
It seems that the syntax checker tries to parse `%%writefile` cells as Python code. If the file contents are text data, then it gives many red/yellow lines:

![image](https://user-images.githubusercontent.com/1481665/173417199-bcf8b00a-bdaa-4e25-bef0-7a3ab6f6b1bc.png)

**Describe the expected behavior**
The syntax checker should ignore `%%writefile` cells, at least for cells that do not look like Python files (maybe recognized by the file extension).

**What web browser you are using**
Chrome 102.0.5005.63

**Additional context**
None

**Comment by craigcitro** [comment]
This should all be fixed. Thanks for the report!

**Comment by tueda** [comment]
I have confirmed that `%%writefile` disables the syntax checker. Thank you!

**Comment by TheW27** [comment]
Hello, Sir If you are there 
i need a help
