### ISSUE TITLE
statsmodels error - ImportError: cannot import name 'PytestTester'

### ISSUE THREAD

**Issue by sriramkraju** [googlecolab/colabtools#286]
After:
!pip install statsmodels==0.9.0rc1

from statsmodels.tsa.api import PytestTester

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-64-723a92bf7870> in <module>()
----> 1 from statsmodels.tsa.api import PytestTester

/usr/local/lib/python3.6/dist-packages/statsmodels/tsa/__init__.py in <module>()
----> 1 from statsmodels import PytestTester
      2 test = PytestTester()
      3 

ImportError: cannot import name 'PytestTester'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by craigcitro** [comment]
I believe you're running afoul of python's caching of imports: if you've imported statsmodels, you won't see a newly installed version until you restart the python process.

Runtime -> Restart runtime should do the trick.

**Comment by sriramkraju** [comment]
### Restarting runtime didn't help. I even tried closing and opening the collab notebook

from statsmodels import PytestTester

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-d293e314317f> in <module>()
      1 import statsmodels.api as sm
----> 2 from statsmodels import PytestTester

ImportError: cannot import name 'PytestTester'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by sriramkraju** [comment]
Thanks for checking. For some reason, my collab notebook had v 0.8.0 of
statmodels that gave an error.
I uninstalled and reinstalled 0.9.0 and didn't forget to restart runtime
for the error to disappear!

By the way, how long a google collab runtime session is persistent, Can I
run a script that runs for 20+hours?


--


*Thanks and Regards, Sriram*


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/26/18,
1:14:41 PM

**Comment by downlz** [comment]
> !pip install statsmodels

It works after restarting runtime. The Issue is session is not persistent and you have to perform this activity once again when you return to this notebook again.
