### ISSUE TITLE
Upgrade spaCy to version 3

### ISSUE THREAD

**Issue by koaning** [googlecolab/colabtools#2861]
**Is your feature request related to a problem? Please describe.**

At the moment, the Colab notebook comes with spaCy v2.

```python
import spacy

print(spacy.__version__) # 2.2.4
```

This is a dated version by now. Since Feb 2021 we've upgraded to a new version with breaking changes. It unfortunately means that many of the new guides aren't compatible with Colab unless users manually upgrade. One of the main reasons to upgrade is to allow for more languages, we've recently added more supported languages, and it'd be nice if people could immediately use it. I also think some of our newer pipelines are lighter to download. 

**Describe the solution you'd like**

I'd like to upgrade the spaCy version to version 3.3.0. This version supports our new floret embeddings, which should also support many new languages. 

**Describe alternatives you've considered**

We could also do nothing and ask all users to install manually but that'd be an extra effort to many users. 

**Additional context**

I work at Explosion, the company behind spaCy. I'll gladly help out if that's appreciated.

**Comment by colaboratory-team** [comment]
Tracking internally as b/236142392

**Comment by colaboratory-team** [comment]
We're now using spacy 3.3.1, thanks for the request!
