### ISSUE TITLE
Upgrade fastai to 2.6.3 

### ISSUE THREAD

**Issue by muellerzr** [googlecolab/colabtools#2862]
**Is your feature request related to a problem? Please describe.**
At the moment fastai comes preinstalled in Google Colab with version 1.0.61, which is from May of **2020**. It would be great if we could please get the (currently as of now) latest version of it installed by default please? 🙏 😺 

**Describe the solution you'd like**
I'd like to have the preinstalled fastai version to 2.6.3. This solves a number of headaches we've had with installing fastai in colab each time, and the fastai v1 of the library is at this point dead and has been for some time. The two latest versions of the fastai course follow fastai 2.x.x as well. 

**Describe alternatives you've considered**

Manually installing it every single time I'd like to use the library, but this is asking (and has been asking) a lot out of each of our users. 

**Additional context**
Add any other context, screenshots or notebooks about the feature request here.

I'm a senior member and one of the main contributors to fastai, and I'll help how I can to get us there. Thank you so much!

**Comment by colaboratory-team** [comment]
Tracking internally as b/236159301

**Comment by colaboratory-team** [comment]
We're now using fastai 2.6.3, thanks for the request!
