### ISSUE TITLE
Problem with generating data and saving to google drive.

### ISSUE THREAD

**Issue by FlyingYanglu** [googlecolab/colabtools#2865]
Problem: I use colab to generate large amount of images and save them to a folder inside my google drive. I don't know is this the problem with google colab or google drive, but after I generate 500000 images, the folder will overflow and all remaining images are saved to root directory of google drive. That couldn't be a mistake with my code as I've stupidly reproduce this bug twice using different block of codes. I wonder that is this some sort of limitation of colab or google drive and even so, could you fix it so that the remaining images are saved under a folder rather than the root directory? If they are saved under root directory, the only way to remove them is using the google drive desktop because the web version does not allow you to select and delete everything.

**Comment by cperry-goog** [comment]
This is an instance of https://research.google.com/colaboratory/faq.html#drive-timeout
