### ISSUE TITLE
Uploading file not working

### ISSUE THREAD

**Issue by w12l3-c** [googlecolab/colabtools#2873]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
Try to import some downloaded datasets into the files in TensorFlow and it is not uploading, it also doesn't show the preview of my computer and does nothing when I press the upload file after right-click or the import file button. When I try to drag the files into the area, it also doesn't work(respond). Right now I cannot work on anything.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
I expected to be able to upload files

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
 It happens on every single file

**Comment by cperry-goog** [comment]
Thanks, if you are able to provide consistent repro steps that would be helpful.

**Comment by w12l3-c** [comment]
There is not much to be shown though, it is just opening the tensorflow notebook, then the file section on the left hand navigation bar, then drag the csvs onto the area or right click and click on import file

**Comment by haltosan** [comment]
I'm using Firefox without the tracker protection on and without an ad-block on for the website and I'm still unable to upload a single image. I can upload a small yaml file (1KB), but I can't get the image (7,250KB). Is it an issue with file size? Other people have claimed it was issues with cookies but I ruled that out. Is it on my end or on your end?

**Comment by youdontneedtoknow22** [comment]
I can't upload files on Firefox 111, but uploading works on microsoft edge

**Comment by gvmii** [comment]
Doesn't work on Firefox, works on Chrome.

**Comment by w12l3-c** [comment]
I tried on some other browsers like firefox and operaGX with the drag and drop or import button. Sometimes it works but most of the time it doesn't. The way I am solving it now is by using 
`
from google.colab import files
files.upload()
`
 in one of the blocks and the file window will show up most of the time.

**Comment by Huhuzai** [comment]
chrome not working, tried to use `from google.colab import files files.upload()`, not working neither

**Comment by w12l3-c** [comment]
maybe clearing cache and cookies might help?

**Comment by InfHorus** [comment]
Getting same issue, tried every browsers, clearing cache & cookies. This is very not professional from Google Colab.
