### ISSUE TITLE
Google Colab error while running `GLIBC_2.29' not found, how can I fix?

### ISSUE THREAD

**Issue by ibrahimali123** [googlecolab/colabtools#2877]
tensorflow.python.framework.errors_impl.NotFoundError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/python3.7/dist-packages/tensorflow_compression/python/ops/../../cc/libtensorflow_compression.so)

how can I fix?
Note the same code is running on my local machine but can't run it on colab

**Comment by colaboratory-team** [comment]
Can you share the notebook where you're seeing this error?

**Comment by lyndond** [comment]
I also am running into this issue and found this issues page after google searching. Here's a minimal notebook where I'm seeing the error: https://colab.research.google.com/drive/11JZg5o25IKCTK0VenfxJ2tEjpOzDUQMT?usp=sharing .

**Comment by colaboratory-team** [comment]
It looks like this comes from installing a version of tensorflow-compression that's too new for our build. Would you be able to install a slightly older version until we can update?

!pip install tensorflow-compression==2.8.1

**Comment by lyndond** [comment]
Sure that works. Thanks!
