### ISSUE TITLE
R Tensorflow/Keras CUDA drivers

### ISSUE THREAD

**Issue by numberinho** [googlecolab/colabtools#2879]
Using R in google-colab with GPU Support:
It seems like the CUDA drivers are misconfigured for use in the R interface for Tensorflow.
https://github.com/rstudio/keras/issues/1217#issuecomment-1153893755

Do you have any thoughts on this?

**Comment by craigcitro** [comment]
Does the workaround from https://github.com/googlecolab/colabtools/issues/2486 get you unblocked?
