### ISSUE TITLE
Is there a timeline for upgrading version of IPython?

### ISSUE THREAD

**Issue by eikonomega** [googlecolab/colabtools#288]
I've noticed that the version of IPython used in the service is 5.5.0 which is about a year old now. Do you have any timeline on upgrading to 7.X?

Thanks for everything you are doing with this platform. It is awesome.

**Comment by craigcitro** [comment]
Not at the moment -- is there a feature you're interested in that's blocked on a newer IPython?

**Comment by eikonomega** [comment]
Hi @craigcitro! 

I was hoping to be able to use the enhanced timing information from the %timeit magic command that came long in 6.something, I forget exactly where.

**Comment by colaboratory-team** [comment]
b/124535699
