### ISSUE TITLE
l=[1,2,4,1,4] l=set(l) print(l,type(l)) its showing error for this program

### ISSUE THREAD

**Issue by fuvcck** [googlecolab/colabtools#2885]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by colaboratory-team** [comment]
This code by itself works fine,

```
l=[1,2,4,1,4]
l=set(l)
print(l,type(l))

> {1, 2, 4} <class 'set'>
```

Could you share the notebook where you were seeing the error? And also what was the error?
