### ISSUE TITLE
Colab Pro+ Bug - Codes don't work when High RAM is selected

### ISSUE THREAD

**Issue by zerrintt** [googlecolab/colabtools#2886]
When high ram is activated in google colab pro+, the codes do not work(even adding a library), they stay in executing. 
However, the same codes work when normal ram is selected.

For example; the code below run successfully when standart ram is selected, when high ram selected doesn't work.

%%R
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

![Problem_screenshot](https://user-images.githubusercontent.com/102037936/176012372-28b1cc28-d469-4434-8365-5d3513e9ab57.png)

 I've tried both chrome and edge, but the result is same. When high ram is selected codes doesn't work, when standart working is selected codes are running. I need high ram so I've bought pro+, but I can't use because of this problem.

drive notebook link: https://colab.research.google.com/drive/1regpRAK3qaY9h3Py-IU4kzvRHqlh3_z-?usp=sharing

**Comment by craigcitro** [comment]
Can you still repro this with a fresh runtime?

(There's nothing we configure differently about high-ram runtimes, so I suspect there was some bad/confusing kernel state.)

**Comment by zerrintt** [comment]
Thanks for reply,

Yes, unfortunately I have same problem. I cann’t use high ram option.

I’ve tried creating new code file, finishing sessions. I don’t know what
can I do?

29 Haz 2022 Çar, saat 09:41 tarihinde Craig Citro ***@***.***>
şunu yazdı:

**Comment by craigcitro** [comment]
Sorry about the trouble -- sure enough, this is a bug on our side.

Here's a quick workaround: before using R, execute:

```
import os
os.environ['OPENBLAS_NUM_THREADS'] = '1'
```

and then you should be unblocked.

**Comment by zerrintt** [comment]
The solution worked, the R codes are working. Thank you so much.
