### ISSUE TITLE
Can't connect to Colab on GCE VM after !pip install google-cloud-texttospeech and restart runtime

### ISSUE THREAD

**Issue by tomchify** [googlecolab/colabtools#2887]
**Describe the current behavior**
I created a custom GCE VM named "colab-3" (my 3rd one, not sure if that matters). I pressed "Connect to Colab with VM". I opened a notebook and ran it.

After running the code:
!pip install google-cloud-texttospeech
The output prompts me to "RESTART RUNTIME". After I press that button, the instance hangs. 
<img width="1791" alt="Screen Shot 2022-06-27 at 6 58 28 PM" src="https://user-images.githubusercontent.com/1762208/176074957-fb01addf-551a-4ba9-ad50-2236353debda.png">

Pressing view runtime logs reveals:
<img width="551" alt="Screen Shot 2022-06-27 at 6 58 47 PM" src="https://user-images.githubusercontent.com/1762208/176075087-a8eac30c-eb98-40bb-8f05-77aee64c1646.png">

This is the 3rd time I've created a custom GCE VM and tried to get this going but it consistently hangs. Oddly, the same colab notebook code doesn't hang on the first two "colab-1" and "colab-2" VMs I created.

**Describe the expected behavior**
I would expect to be able to reconnect to the runtime and run the colab notebook again.

**What web browser you are using**
Chrome

**Comment by tomchify** [comment]
Update: 

If I move:
!pip install google-cloud-texttospeech

above:
!pip install google-cloud-firestore --upgrade
!pip install google-api-core==1.31.6 (the only other two lines in the notebook that cause a "RESTART RUNTIME" prompt)

... then the notebook runs as expected. 🤷‍♂️ Weird, but that unblocks the problem.

**Comment by colaboratory-team** [comment]
Glad you found a way to get unblocked. Could you share the notebook you used to reproduce the issue?
