### ISSUE TITLE
Files are disappearing

### ISSUE THREAD

**Issue by Uwanggood** [googlecolab/colabtools#2888]
Why do files that I have mounted and saved on Google Drive keep disappearing?

It's not a small company, and when files keep disappearing, are  people say nothing abount this ? ???????????????

I have been using it for several months and the file keeps disappearing. Please please please  tell me the cause of this

--
1. Mount Google Drive

2. Save the learning work progress result in Google Drive

3. Delete the file result after a few hours
(wt;;zzzzzzzzzzzzzz)

**Comment by colaboratory-team** [comment]
Can you share the notebook you are running?

**Comment by Uwanggood** [comment]
how to share with colab-team  account ?

**Comment by colaboratory-team** [comment]
You can either share it with colaboratory-team@google.com, or make the notebook publicly visible and put the link here if it doesn't contain sensitive information
