### ISSUE TITLE
Localtunnel not working ( XML Error)

### ISSUE THREAD

**Issue by SPKChaosPhoenix** [googlecolab/colabtools#2891]
**Describe the current behavior**
Running localtunnel doesnt print out the localtunnel link, but inseatd gives an XmlKeyManager Error and then stops printing out anything until stopping the execution.

**Describe the expected behavior**
Running the Code should print out a localtunnel link and then Microsoft.Hosting.Lifetime information witout the need to stop code exectuion.

**What web browser you are using**
Firefox
Chrome

**Additional context**
The Code did work just a few days ago without any errors like it is intended.

Notebook to reproduce the Proplem:
https://colab.research.google.com/drive/1T8tfhupaw0pEI2-x4qn0E0sjw-55xYTb?usp=sharing

**Comment by colaboratory-team** [comment]
Could not reproduce, I ran your notebook on a hosted runtime and the server started up fine. I did see your XMLKeyManager warning, but the localhost links appeared as well

===warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {4c9ee724-d4f3-4bd5-9059-73dc6308efdc} may be persisted to storage in unencrypted form.
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to https://localhost:5001/ on the IPv6 loopback interface: 'Cannot assign requested address'.
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to http://localhost:5000/ on the IPv6 loopback interface: 'Cannot assign requested address'.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001/
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000/
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /content/LevelImposter-Web/LevelImposter-Web

**Comment by SPKChaosPhoenix** [comment]
Ist missing the Localtunnel link which should follow after: ==your URL is:
