### ISSUE TITLE
Upgrading PyTorch to v1.12.0 and torchvision to v0.13.0 and torchaudio to v0.12.0

### ISSUE THREAD

**Issue by seemethere** [googlecolab/colabtools#2893]
Hello,

We released pytorch v1.12.0 torchvision v0.13.0 torchaudio v0.12.0 

# Wheel links:

## **pytorch**
**CUDA 11.3**

[download.pytorch.org/whl/cu113/torch-1.12.0%2Bcu113-cp37-cp37m-linux_x86_64.whl](https://download.pytorch.org/whl/cu113/torch-1.12.0%2Bcu113-cp37-cp37m-linux_x86_64.whl)

## **torchvision**
**CUDA 11.3** 

[download.pytorch.org/whl/cu113/torchvision-0.13.0%2Bcu113-cp37-cp37m-linux_x86_64.whl](https://download.pytorch.org/whl/cu113/torchvision-0.13.0%2Bcu113-cp37-cp37m-linux_x86_64.whl)

## **torchaudio**
**CUDA 11.3** 

[download.pytorch.org/whl/cu115/torchaudio-0.12.0%2Bcu115-cp37-cp37m-linux_x86_64.whl](https://download.pytorch.org/whl/cu115/torchaudio-0.12.0%2Bcu115-cp37-cp37m-linux_x86_64.whl)

-----

Other notes If you require wheels for Python 3.8 / 3.9 or 3.10, you can find the links here: [download.pytorch.org/whl/torch_stable.html](https://download.pytorch.org/whl/torch_stable.html)

We're looking to having it updated in Colab.

Thanks very much.

cc'ing @colaboratory-team

Similar to [#2372](https://github.com/googlecolab/colabtools/issues/2668)

**Comment by craigcitro** [comment]
Thanks for the note! We're moving a little slow with the holiday in the US. :)

We've got a conflict with another package; filed https://github.com/fastai/fastai/issues/3730 to see if we can get it sorted.

**Comment by craigcitro** [comment]
This should be fixed!
