### ISSUE TITLE
ValueError: Minimization failed after 100 attempts.

### ISSUE THREAD

**Issue by Belfield** [googlecolab/colabtools#2894]
Hi,

Can anyone help with running AlphaFold Colab. We have run it many times before but recent;ly, and with the same protein sequences, the script returns the following error: ValueError: Minimization failed after 100 attempts.

Any help would be appreciated.

Thanks,

**More details below:**

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-5-f89616eedc2d>](https://localhost:8080/) in <module>()
     88         max_outer_iterations=3,
     89         use_gpu=True)
---> 90     relaxed_pdb, _, _ = amber_relaxer.process(prot=unrelaxed_proteins[best_model_name])
     91   else:
     92     print('Warning: Running without the relaxation stage.')

________________________________________
2 frames
________________________________________
[/opt/conda/lib/python3.7/site-packages/alphafold/relax/amber_minimize.py](https://localhost:8080/) in _run_one_iteration(pdb_string, max_iterations, tolerance, stiffness, restraint_set, max_attempts, use_gpu, exclude_residues)
    417       logging.info(e)
    418   if not minimized:
--> 419     raise ValueError(f"Minimization failed after {max_attempts} attempts.")
    420   ret["opt_time"] = time.time() - start
    421   ret["min_attempts"] = attempts

ValueError: Minimization failed after 100 attempts.

**And when we try and submit the same job, we get this error message:**

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
[<ipython-input-12-97d4183e8ad4>](https://localhost:8080/#) in <module>()
     19     with io.capture_output() as captured:
     20       # Uninstall default Colab version of TF.
---> 21       get_ipython().magic('shell pip uninstall -y tensorflow')
     22 
     23       get_ipython().magic('shell sudo apt install --quiet --yes hmmer')

3 frames
[/usr/local/lib/python3.7/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in _run_command(cmd, clear_streamed_output)
    166   if locale_encoding != _ENCODING:
    167     raise NotImplementedError(
--> 168         'A UTF-8 locale is required. Got {}'.format(locale_encoding))
    169 
    170   parent_pty, child_pty = pty.openpty()

NotImplementedError: A UTF-8 locale is required. Got ANSI_X3.4-1968

**Comment by colaboratory-team** [comment]
Colab does not maintain the Alphafold notebooks, I would recommend reaching out to the Alphafold team via their [github issue list](https://github.com/deepmind/alphafold/issues). Your issue might be similar to [this one](https://github.com/deepmind/alphafold/issues/483)
