### ISSUE TITLE
Cannot unpack non-iterable Msa object

### ISSUE THREAD

**Issue by limarch** [googlecolab/colabtools#2899]
**Describe the current behavior**
When it runs the step that call MMseqs2 to get MSA for each gene, it sounds a warning that cannot unpack non-iterable Msa object, with the wrong code is msa, deletion_matrix = pipeline.parsers.parse_a3m(a3m_lines[0]).

**Describe the expected behavior**
I hope it can run smoothly.

**What web browser you are using**
Chrome.

**Comment by colaboratory-team** [comment]
This sounds like an issue with the code in the notebook you are running. I would talk to either the notebook author or the MMseqs2 library maintainers

**Comment by Virtue-123** [comment]
How should we solve this problem when we encounter it？
