### ISSUE TITLE
Request: Ability to connect to vpn/local server

### ISSUE THREAD

**Issue by JoyChopra1298** [googlecolab/colabtools#29]
Hi
For my research I am using a simulator that runs on my machine on some port and I want to train neural network on google colab. Please add a way to make connection between colab and other vpns. I even created a vpn and tried to connect colab to vpn but it didn't work.
I get the following error when I run !openvpn --config client.ovpn 
 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
 Exiting due to fatal error

Edit: I tried this after looking at his [page]( https://groups.google.com/forum/#!topic/docker-user/2jFeDGJj36E)
1.mkdir -p /dev/net
2.mknod /dev/net/tun c 10 200
3.chmod 600 /dev/net/tun
and then when I run !openvpn --config client.ovpn, I am getting the following error
 ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)
 2018 Exiting due to fatal error

**Comment by CSEMike** [comment]
Thanks for the note. As you point out, this isn't supported just yet. We'll keep this issue up-to-date with progress on supporting local execution.

**Comment by MeTaNoV** [comment]
Seems like local execution is now a thing, but it would be nice to have the same for remote execution without having to do port forwarding via ssh.

**Comment by colaboratory-team** [comment]
Local runtimes reference: http://research.google.com/colaboratory/local-runtimes.html

**Comment by ratulray** [comment]
Is there a way to run "import google.colab.XX" while being on local runtime?

**Comment by tlkahn** [comment]
Is OpenVPN now supported?

**Comment by kalinin-sanja** [comment]
Why the issue is closed? I want to power of Google's machines but my database is stored on different server. And I have to use VPN to connect. Using local runtime is not solution because my laptop is slow.
