### ISSUE TITLE
Are you still there? 

### ISSUE THREAD

**Issue by Tezas-6174** [googlecolab/colabtools#2915]
**Current behaviour**
- Receiving this inactivity prompt quite often, even when I am working in the notebook.

**Expected behaviour**
- Ideally, it should prompt only when there is actual inactivity. 

**What web browser you are using**
- Chrome

**Comment by cperry-goog** [comment]
Thanks for reporting, Colab prioritizes interactive compute and these prompts help ensure resources are being delivered to folks who need them.

**Comment by Tezas-6174** [comment]
But one must receive this prompt only when there is actual inactivity. It isn't the case as of now.
