### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by juzi-dj** [googlecolab/colabtools#2919]
I get an error no matter what command I run

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected
The folder you are executing pip from can no longer be found.

**Comment by cperry-goog** [comment]
Can you share a minimal repro notebook?
