### ISSUE TITLE
Colab won’t allow me to place “strings” while I use my Ipad to type

### ISSUE THREAD

**Issue by Foulgaz3** [googlecolab/colabtools#292]
I use several different devices, but I often use my Ipad as it is much more compact than my computer. At first I thought it was the fact that I am using a Bluetooth Keyboard, but I tried using the normal keyboard and had the same issue. I am using google chrome on an IPad Air 2

I apologize if the details are not necessary, but I felt I should provide them in case.

**Comment by blois** [comment]
I see that it's inserting `“”` chars rather than `"`.
