### ISSUE TITLE
side scrolling issue

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#2920]
the scroll bar ends even though there is text to be scrolled to the right
![Screenshot (1103)](https://user-images.githubusercontent.com/43755000/178953010-781788dd-4938-46cb-9513-56e5a96ca4ce.png)
had to manually take the cursor to the text and hit the right arrow key
![Screenshot (1101)](https://user-images.githubusercontent.com/43755000/178953023-5212a5ef-71f1-4c1b-b65c-00858027a6b2.png)
.

**Comment by cperry-goog** [comment]
Can you share a minimal repro notebook and tell us which browser you're observing this on?

**Comment by cperry-goog** [comment]
Gotcha, thanks, closing this, feel free to re-open if there's a clear AI for us
