### ISSUE TITLE
Multitab ipywidget tool being flagged as 3rd party widget

### ISSUE THREAD

**Issue by gutow** [googlecolab/colabtools#2921]
**Describe the current behavior**
Part one of the three ipywidget based GUIs in the latest release candidates for [jupyter-Pandas-GUI](https://pypi.org/project/jupyter-Pandas-GUI/0.7.0rc0/#history) is being flagged as a third party widget. This leads to the tabbed part of the tool not being rendered. As there is no third-party widget to be downloaded following the instructions for using third-party widgets does not solve the problem. The two other ipywidget based GUIs in the package, built the same way, are rendered. The one that does not render has more tabs and embeds a plotly graph in one of the tabs. Removing the plotly graph does not solve the problem (0.7.0rc1).

This works in Jupyter Lab and even more elegantly in classic Jupyter, where the code is built directly in the cell below the GUI.

I have not been able to do any more diagnosis as nothing appears in the logs. I am hoping that someone with more complete access to Colab can find the issue. I am assuming it is something in the jupyter-Pandas-GUI code.

**Describe the expected behavior**
The expected behavior is that after importing the jupyter-pandas-gui package: `from pandas_GUI import *`. The commands `new_pandas_column_GUI()`, `plot_pandas_GUI()` and `fit_pandas_GUI()` should all generate a tabbed ipywidget display followed by the codearea box. Only the first two work in Colab.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Tested in Firefox and Chrome.

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
Behavior can be seen in [this](https://colab.research.google.com/drive/15ojkP83sckftJcZBqmvNNpfo1-2-A8IR?usp=sharing) Colab notebook.

**Comment by blois** [comment]
The error is originating from https://github.com/jupyter-widgets/ipywidgets/blob/056f1d12669e643bce221843abcd5dcd9540716a/packages/controls/src/widget_selectioncontainer.ts#L338

Where this.model.get('titles') is returning undefined. This looks similar to https://github.com/jupyter-widgets/ipywidgets/issues/2789#issuecomment-956501407 which was rooted in an ipywidgets 7 vs 8 change- the sample is using V8 widgets.

**Comment by gutow** [comment]
Thanks. That gives me a lead. So the issue may be with ipywidgets 8+. I will see if I can find a workaround that doesn't break my use of the widgets in the ipywidgets 7 (current release) or a patch for ipywidgets 8+. If I can reproduce the issue outside of colab, I will close this issue.

**Comment by gutow** [comment]
> The error is originating from https://github.com/jupyter-widgets/ipywidgets/blob/056f1d12669e643bce221843abcd5dcd9540716a/packages/controls/src/widget_selectioncontainer.ts#L338
> 
> Where this.model.get('titles') is returning undefined. This looks similar to [jupyter-widgets/ipywidgets#2789 (comment)](https://github.com/jupyter-widgets/ipywidgets/issues/2789#issuecomment-956501407) which was rooted in an ipywidgets 7 vs 8 change- the sample is using V8 widgets.
Yep. Fundamentally, the python syntax for defining tabbed widgets has changed and the code in v8.0 breaks v7 compatible code. I will file an issue with ipywidgets.

Thanks. Closing.

**Comment by gutow** [comment]
There is something deeper going on. Changing the syntax in my code to be more compliant with v8 and forcing the use of v7 produces a new error `RC00_460676560:15:429\nb@https://colab.research.google.com/v2/external/output_binary.js?vrz=colab-20220713-060046-RC00_460676560:16:165\n", message: "Widget jupyterlab-plotly FigureModel is not supported"` When the widget is embedded in a selectioncontainer. However, the plotly widget works when called in a cell. Will try removing the plotly widget from the selectioncontainer.
