### ISSUE TITLE
Can't connect to custom GCE VM instance after executing cell while restarting runtime.

### ISSUE THREAD

**Issue by tomchify** [googlecolab/colabtools#2922]
**Describe the current behavior**
I started a custom GCE VM "colab-3". It for some reason was failing to run any GPU commands (just hung - an issue unrelated to this bug, but I'm guessing hardware failure or something behind the scenes?), while "colab-1" and "colab-2" ran the same code correctly.

I pressed "Restart runtime" inside the notebook (since it was hanging on a GPU related function execution). Then, before the restart had completed, I pressed the play button to execute the top cell in the notebook, containing simple python like:

instance_name = "colab-3" 

The instance then became completely unusable. I was unable to reconnect to it.

A crash came up like this:
<img width="620" alt="Screen Shot 2022-07-14 at 10 29 46 AM" src="https://user-images.githubusercontent.com/1762208/179046176-cff313fc-a00e-4925-8d9f-bab1b03b4bc7.png">

After a refresh, when I attempted to reconnect to this same custom GCE vm ("colab-3-vm"), it just showed this sometimes:

<img width="726" alt="Screen Shot 2022-07-14 at 10 07 35 AM" src="https://user-images.githubusercontent.com/1762208/179042780-460a8871-c95f-4d37-b803-06ee810a9ae7.png">

Pressing the "Connect to VM with Colab" in the Deployments Manager (https://console.cloud.google.com/dm/deployments) doesn't fix the problem.

Using the "Connect to a custom GCE VM" button from the notebook's triangle dropdown doesn't get it reconnected. 

Restarting the VM from the VM Instance manager (https://console.cloud.google.com/compute/instances ...) doesn't fix the problem, nor does "Resetting" the instance from that page.

Deleting the deployment and all related assets and creating a new deployment (using https://console.cloud.google.com/marketplace/product/colab-marketplace-image-public/colab ) is the only way I was able to connect again to a third GCE vm.

Now, after connecting to the new instance, I found that after executing:

!pip install google-api-core==1.31.6 
!pip install google-cloud-texttospeech

The output showed:
...
Collecting google-cloud-texttospeech
  Downloading google_cloud_texttospeech-2.11.1-py2.py3-none-any.whl (69 kB)
...

Then is shows a prompt to "RESTART RUNTIME" but the instance crashes and fails to connect any time after that.

I then deleted the deployment, started over again, and discovered that if I put:

!pip install google-cloud-texttospeech
1/0
 at the top of the notebook, before any other commands that prompt a "RESTART RUNTIME", then I'm able to get an instance running again.

So, long story short, I've encountered what feels like multiple bugs: an instance stopped executing gpu commands, hung forever after executing a block during a restart runtime, no way to reconnect except for deleting the entire deployment and restarting all over, and notebook crashes consistently with the install of google-cloud-texttospeech (when not first in the notebook).

I've encountered these weird stumbling blocks more than a handful of times now, so figured worth filing the bug with the real-world scenario I'm experiencing. Thanks for taking a look. Things feel... brittle, but like they could be wonderful with just a tiny bit of these edge cases fixed (or possibly with me doing things better, let me know if there are resources to best practices or something...).

**What web browser you are using**
Chrome

**Comment by blois** [comment]
The error in the screenshot implies that the kernel has been upgraded or one of the packages has been removed from the VM.  Executing the code:

```
!pip install google-api-core==1.31.6
!pip install google-cloud-texttospeech
```

Does not repro this for me, I'm guessing there was some additional configuration change on the VM?
