### ISSUE TITLE
Upgraded library version, but desired features are still not available

### ISSUE THREAD

**Issue by frigeriomtt** [googlecolab/colabtools#2929]
**Describe the current behavior**
After successfully updating tensorflow's version with 
`!pip3 install tensorflow==2.9.1 tf-models-official==2.9.2  tensorflow-io==0.26.0`
keras features developed in a more recent version than the one present by default in colab are still not available 
**Describe the expected behavior**
* [split_dataset](https://www.tensorflow.org/api_docs/python/tf/keras/utils/split_dataset) should be available;
* [image_dataset_from_directory](https://www.tensorflow.org/api_docs/python/tf/keras/utils/image_dataset_from_directory) should accept "both" as validation_split parameter's value

**What web browser you are using**
Chrome

**Comment by craigcitro** [comment]
Both of the features you're describing are only available in tf-nightly; for instance, the first has a note at the top of the page saying `Note: This API is new and only available via pip install tf-nightly.`.
