### ISSUE TITLE
Is this the right way ?

### ISSUE THREAD

**Issue by paulgureghian** [googlecolab/colabtools#293]
it seems to be working. is it all I need ? are there more commands I need to add ? if it is correct, how to add two or more files in the same cell ? or do i need separate cells for each file ?
![capture3](https://user-images.githubusercontent.com/8146561/46499874-315e6a00-c7d6-11e8-8e8d-eb271767cce6.PNG)

**Comment by craigcitro** [comment]
Programming questions are better asked on StackOverflow; issues in this repo are for bug reports and feature requests in Colab itself.
