### ISSUE TITLE
NameError: name 'set_seed' is not defined

### ISSUE THREAD

**Issue by alcomane** [googlecolab/colabtools#2931]
Hi,

I cannot find anything related to this error, reason to open this bug.

After I successfully completed all previous steps, when I run the step - 4. Diffuse I receive the following error: 

80 if set_seed == 'random_seed':
     81     random.seed()
     82     seed = random.randint(0, 2**32)

NameError: name 'set_seed' is not defined

No sure what parameters have to have, but the process doesn't run.

[Archive.zip](https://github.com/googlecolab/colabtools/files/9127638/Archive.zip)

**Comment by cperry-goog** [comment]
Can you share a minimal repro notebook?
