### ISSUE TITLE
Alphafold does not work

### ISSUE THREAD

**Issue by Alleko** [googlecolab/colabtools#2933]
Last 6 days alhphafold kept giving the same error message despite whatever protein sequence I ran. As a control I ran simple protein sequences that alphafold was able to predict before. Now it cannot do even these controls. Could you please help? Below is the error. 

0%|          | 0/7 [elapsed: 00:00 remaining: ?]
/usr/local/lib/python3.7/dist-packages/jax/_src/tree_util.py:201: FutureWarning: jax.tree_util.tree_multimap() is deprecated. Please use jax.tree_util.tree_map() instead as a drop-in replacement.
  'instead as a drop-in replacement.', FutureWarning)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-5-f89616eedc2d>](https://localhost:8080/#) in <module>()
     88         max_outer_iterations=3,
     89         use_gpu=True)
---> 90     relaxed_pdb, _, _ = amber_relaxer.process(prot=unrelaxed_proteins[best_model_name])
     91   else:
     92     print('Warning: Running without the relaxation stage.')

**Comment by cperry-goog** [comment]
I'd ask upstream at the AlphaFold repo: https://github.com/deepmind/alphafold/issues
