### ISSUE TITLE
During final execusion of the dicom diffusion a got followin error. Could You advice what is wrong with the configuration?

### ISSUE THREAD

**Issue by Zawrot** [googlecolab/colabtools#2936]
Hello,

Could You help me to solve this issue?  I got this error during the execution of the simple, static image dicom diffusion script:

[/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py](https://localhost:8080/#) in _in_projection_packed(q, k, v, w, b)
   4743         if q is k:
   4744             # self-attention
-> 4745             return linear(q, w, b).chunk(3, dim=-1)
   4746         else:
   4747             # encoder-decoder attention

RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

**Comment by cperry-goog** [comment]
You may have better luck asking upstream with the notebook author or StackOverflow; this doesn't appear to be a Colab issue.
