### ISSUE TITLE
Installing rapids in Google Colab sample code not working for 403 error

### ISSUE THREAD

**Issue by shunseki** [googlecolab/colabtools#2938]
**Describe the current behavior**
Critical module not imported with codes that supposed to be installing them. Error code:
`CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/rapidsai/linux-64/rapids-xgboost-21.12.00-cuda11.2_py37_gc46440c_94.tar.bz2>`
and more urls invalid

**Describe the expected behavior**
Critical module should be imported with the codes: 

`!python rapidsai-csp-utils/colab/install_rapids.py stable
import os
os.environ['NUMBAPRO_NVVM'] = '/usr/local/cuda/nvvm/lib64/libnvvm.so'
os.environ['NUMBAPRO_LIBDEVICE'] = '/usr/local/cuda/nvvm/libdevice/'
os.environ['CONDA_PREFIX'] = '/usr/local'`

**What web browser you are using**
Chrome 103.0.5060.134 (Official Build) (x86_64）

**Additional context**
Google colaboratory official notebook for installing rapids by nvidia: https://colab.research.google.com/drive/1rY7Ln6rEE1pOlfSHCYOVaqt8OvDO35J0?usp=sharing

**Comment by cperry-goog** [comment]
This looks to be an upstream issue: https://github.com/rapidsai-community/rapidsai-csp-utils/issues/63
