### ISSUE TITLE
Not able to download dataset from kaggle

### ISSUE THREAD

**Issue by samik-saha** [googlecolab/colabtools#294]
Downloading competition dataset from kaggle using kaggle-api stopped working this morning. It throws an '404-Not Found' error. In fact all the kaggle commands are throwing the same error.

**Comment by colaboratory-team** [comment]
Looks like the Kaggle-side discussion is here: https://www.kaggle.com/general/65737

Internally: b/117300640

**Comment by mrisdal** [comment]
Hi @samik-saha, I'm sorry to hear you're having problems using Kaggle's API in Colab. Unfortunately I'm not able to reproduce this behavior. If it's helpful to compare with your notebook, here's an example of working code: https://colab.research.google.com/gist/corrieann/3abf2e79f833200d72b58ff10b1df39e/kaggle-api.ipynb

Let me know if you continue to have problems. In which case it would be helpful for me to see the code you are using.

**Comment by samik-saha** [comment]
@mrisdal It is working now for me as well. Maybe it was some temporary network issue? Thanks for looking  into it though.

**Comment by arunjose696** [comment]
I am having this same issue

**Comment by dagnelies** [comment]
I got this too. In my case it was a freshly created dataset. Resulted in 404. After a while, it worked again. I guess it is just a temporary effect.
