### ISSUE TITLE
google.colab.auth is unsupported in this environment.

### ISSUE THREAD

**Issue by ThdsilvaBedu** [googlecolab/colabtools#2941]
**Describe the current behavior**
I'm using Google Colab with GCE VM instance connected and when i try to mount Mounting Google Drive locally with the command below:
from google.colab import drive
drive.mount('/content/drive')

But i receive the following error:

NotImplementedError                       Traceback (most recent call last)
[<ipython-input-4-d5df0069828e>](https://localhost:8080/#) in <module>()
      1 from google.colab import drive
----> 2 drive.mount('/content/drive')

1 frames
[/usr/local/lib/python3.7/dist-packages/google/colab/drive.py](https://localhost:8080/#) in _mount(mountpoint, force_remount, timeout_ms, use_metadata_server, ephemeral)
    124   """Internal helper to mount Google Drive."""
    125   if _os.path.exists('/var/colab/mp'):
--> 126     raise NotImplementedError(__name__ + ' is unsupported in this environment.')
    127 
    128   if ' ' in mountpoint:

NotImplementedError: google.colab.drive is unsupported in this environment.

**Describe the expected behavior**
Mount your Google Drive on your runtime using an authorization code, and how to write and read files there.

**What web browser you are using**
Chrome

**Additional context**
I'm using Google Colab with GCE VM instance connected and when i try to Mounting Google Drive locally but does not work.

**Comment by cperry-goog** [comment]
So sorry, drive.mount doesn't work with GCE VMs; the best alternative is to use PyDrive or the Drive REST API documented here:

https://colab.research.google.com/notebooks/io.ipynb#scrollTo=7taylj9wpsA2

**Comment by ThdsilvaBedu** [comment]
> So sorry, drive.mount doesn't work with GCE VMs; the best alternative is to use PyDrive or the Drive REST API documented here:
> 
> https://colab.research.google.com/notebooks/io.ipynb#scrollTo=7taylj9wpsA2

When i use the PyDrive i get the same error:

NotImplementedError                       Traceback (most recent call last)
[<ipython-input-4-3254a9bed9fd>](https://localhost:8080/#) in <module>()
----> 1 auth.authenticate_user()
      2 gauth = GoogleAuth()
      3 gauth.credentials = GoogleCredentials.get_application_default()
      4 drive = GoogleDrive(gauth)

[/usr/local/lib/python3.7/dist-packages/google/colab/auth.py](https://localhost:8080/#) in authenticate_user(clear_output)
    144   """
    145   if _os.path.exists('/var/colab/mp'):
--> 146     raise NotImplementedError(__name__ + ' is unsupported in this environment.')
    147   if _check_adc():
    148     return

NotImplementedError: google.colab.auth is unsupported in this environment.

**Comment by corngk** [comment]
@cperry-goog, like mentioned by @ThdsilvaBedu, I also experience the same. 

I use Colab on a GCE VM. The auth.authenticate_user() command produce the same error.
