### ISSUE TITLE
pyyaml issue

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#2942]
1) I get this error,
```
TypeError: load() missing 1 required positional argument: 'Loader'
```
2) more details are in this stackoverflow question,
```
https://stackoverflow.com/questions/69564817/typeerror-load-missing-1-required-positional-argument-loader-in-google-col
```

I think this is a colab issue, which is because of some issue with pyyaml

**Comment by craigcitro** [comment]
Do you have a minimal repro notebook?

**Comment by vainaixr** [comment]
I got this error when I did,
```
!pip install darts
from darts import TimeSeries
```
then I had to,
```
!pip install pyyaml==5.4.1
```
to fix the error

**Comment by mayankmalik-colab** [comment]
It seems `!pip install darts` also updated pyyaml to version 6.0. Our other packages are consistent with the older pyyaml version. That being said, we are in the process of updating pyyaml to 6.0 (with other necessary package upgrades to support pyyaml 6.0 ). This should fix the issue going forward.

**Comment by cperry-goog** [comment]
This should be fixed now in prod, please re-open if you have problems.
