### ISSUE TITLE
[Colab Pro] Cannot connect to GPU backend and no option for High-RAM in Runtime menu

### ISSUE THREAD

**Issue by FateAudax** [googlecolab/colabtools#2943]
Have been having issue connecting to a GPU even after subscribing to Colab Pro which shouldn't be the case since when I was a free user, they advertise that by subscribing to Colab Pro, GPU wouldn't be an issue.

![image](https://user-images.githubusercontent.com/23497000/180344790-ce24071c-f462-4229-ad4f-af3c5e915e6e.png)

Also, after subscribing to Colab Pro, there's an introductory page that tells me the availability to select "High-RAM" as a runtime option but I couldn't find it at all.

![image](https://user-images.githubusercontent.com/23497000/180343413-438e4c0c-f322-45b6-b751-121f3f58e094.png)

![image](https://user-images.githubusercontent.com/23497000/180343375-760d1af7-70ff-4ab5-a3aa-bfe4ba957c83.png)

**Comment by corrieann** [comment]
Thanks for the report! 

Please file feedback via Help > Send feedback from the tab that you're having trouble accessing the Notebook Setting's "Runtime shape" menu from.

**Comment by BenisonSam** [comment]
I am facing the exact same problem. No solutions are available after googling for a while! **Send feedback** doesn't give any guarantees of getting a solution in a timely manner!

**Comment by drorhunvural** [comment]
Any solution ?
