### ISSUE TITLE
I cannot uncheck the checkboxes in share setting options in googlecolab.

### ISSUE THREAD

**Issue by reza-ghazi** [googlecolab/colabtools#2945]
I cannot change any options in share settings in my Collaboratory or Slide or Docs, etc.
 
The options are always enabled, but I want to prevent my students from copying, printing, and downloading the files I shared with them.

The process of what I do:
1. Create a file.
2. Try to share the file with a person as a viewer,
3. Click on `Settings` wheel
4. In the opened box, I cannot uncheck any of the following options:
    - Editors can change permissions and share
    - Viewers and commenters can see the option to download, print, and copy

That's it.

Thank you,

**Comment by cperry-goog** [comment]
What browser are you using? For my own notebooks I own I'm able to uncheck those settings in the share dialog.

**Comment by reza-ghazi** [comment]
@cperry-goog : I am using Chrome.

**Comment by cperry-goog** [comment]
@reza-ghazi does this repo for you in an incognito window? Sometimes we see extensions messing with the UI in weird ways.

**Comment by reza-ghazi** [comment]
@cperry-goog No, I am using a regular browsing state. I also checked with Firefox and Edge, but I have the same issue. The unique part is that when I contact support services, they refer me to the community and this GitHub page. They said they only support paid versions. It's understandable, but it is not a personal issue, it is a bug in Colab, or maybe they did by intention to force people to buy. I have a lot of students, and Honestly, I am thinking about alternatives; of course, it will affect all my students' desires and future decisions.

**Comment by craigcitro** [comment]
You said you're seeing this across several products (eg Slides), which makes me think that this is likely an org policy, not anything Colab-related.

To confirm: are you using an account that's part of another organization (eg university or company)? Do you see the same behavior with a consumer gmail account?

**Comment by reza-ghazi** [comment]
@craigcitro No, I am using my personal Gmail account.

**Comment by cperry-goog** [comment]
We looked into this and can't reproduce and have no ideas what might be causing your issue: this component is built by the Drive team, so I think you'll need to submit feedback via Drive, especially since you're seeing this across filetypes, not just notebooks. Sorry!
