### ISSUE TITLE
Paid for Pro, not upgraded

### ISSUE THREAD

**Issue by sheilaaliens** [googlecolab/colabtools#2946]
**Describe the current behavior**
I paid for Colab Pro, it was debited from my account, yet it does not say I have Pro nor is it giving me Pro features. 
**Describe the expected behavior**
Expected behavior is obviously to be upgraded to Pro as I have paid for it.
**What web browser you are using**
(Chrome,
**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by corrieann** [comment]
Thanks for the report!
We are not able to address billing and account issues from GitHub. 
Please contact [colab-billing@google.com](mailto:colab-billing@google.com) for any billing issues.
For issues having to do with your account, please submit feedback in product within Colab at Help > Send feedback
