### ISSUE TITLE
Can't export instrument to DDSP - VST

### ISSUE THREAD

**Issue by denoumestick** [googlecolab/colabtools#2947]
Hello guys,
I bought the procolab+ the other day and used the function to train my instrument to use in DDSP-VST and I do everything as instructed but after half an hour of wait it gives me an error saying that it can't export my instrument. Iam using Google Chrome and Iam uploading a 12 minute clip of an arabic instrument and it has no other instruments with it in the recording. So what am I doing wrong?
Please help.
With best regards.

**Comment by cperry-goog** [comment]
I'd ask upstream with the notebook author.

**Comment by denoumestick** [comment]
What do you mean sir? Who is the notebook author and how do you ask
upstream?
Please help.
