### ISSUE TITLE
SPAM MILION OF LINKS WITH MOVIES AND HACKS AND OTHER THINGS

### ISSUE THREAD

**Issue by dsadasdasd54** [googlecolab/colabtools#2948]
In google is milion links with spam and scams with colabtool

https://colab.research.google.com/drive/1BCeFF0gj7em-54Im9yRYmu5qvbntl_Q7
https://colab.research.google.com/drive/1qLPUrbN_mQAnfWIyTouRCG2E7wTHQy6O
https://colab.research.google.com/drive/16hPnHJvn8dy6oyhW5Ih8HUIHLj1jK4n9
https://colab.research.google.com/drive/1LHRVqTE9guZf0riRmFTyk42MXJyubi8F
https://colab.research.google.com/drive/1cGEeY7rItbFSB_BdWx23gK9uc1U64AsP?usp=sharing
https://colab.research.google.com/drive/1gegqgoeStmOSgP536pXlmoO5uc54mkDY
https://colab.research.google.com/drive/1w3lEB9BjCQh6NUlOk2cTfUajOEkTgpBl
https://colab.research.google.com/drive/1Mtg6tJiCWl6Zu0ymyDXHyJyWMnHDqmLi
https://colab.research.google.com/drive/1nCkM3qMrg8RwWzs4LI0zYpI9sP_gK-p7
https://colab.research.google.com/drive/1euY1eg7f50Pa5znRi_MBcpyF8oNBNu4d
https://drive.google.com/file/d/1Deluer8MIB-lvWYUww_LywCwI_mp9Y_J/edit
https://colab.research.google.com/drive/15K_jpZU0VPQhv0ZunIo8BrXbNnqEzdtG?usp=sharing
https://colab.research.google.com/drive/1qCdVTe-GTlexPvZssgkzPrr9m73rY231?usp=sharing
https://colab.research.google.com/drive/1dULup53wDxd5u2E3LNWE3U1Qs_HdAY97?usp=sharing
https://colab.research.google.com/drive/1ajYGwUBls_GqlZtQBByqdSmZAHBmFjQu
https://colab.research.google.com/drive/1J7bjq77OOMDNmm35ShG3pFj6_1DI292-?usp=sharing
https://colab.research.google.com/drive/1Y8ir_ETEZoDWCco5SlxiakFVFyZfRUU9
https://colab.research.google.com/drive/1eo4G8H4FGlRW2ttpItm_pYt_iffWk7nF?usp=sharing
https://colab.research.google.com/drive/1ktD1xxdyL74eE5Ikm36bA41_9i8YjaON?usp=sharing
https://colab.research.google.com/drive/1-5vIHYL-1ebS_UseQxaOpAzfbsKVsspC?usp=sharing

Why nobody no delete this and allow to scam other poeple? this platform is used to scam others or what?

i check google and is 100kk + links with scam like this

**Comment by cperry-goog** [comment]
You can report spam in Help > Report Drive abuse.
