### ISSUE TITLE
ModuleNotFoundError: No module named 'win32api'

### ISSUE THREAD

**Issue by seq2193** [googlecolab/colabtools#2953]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome
**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

!pip install pypiwin32    error no install
ModuleNotFoundError: No module named 'win32api'
https://colab.research.google.com/drive/1iqg9OroA5JFJ2xQPAAOM07G3enfDGfJo?usp=sharing

**Comment by f1refa11** [comment]
Google Colab uses Linux, which doesn't support win32api

**Comment by seq2193** [comment]
Ok maybe I should give up, thanks.
