### ISSUE TITLE
paste option not available

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#2955]
current scenario -
1) after copying text on notes app, there is no option to paste it in colab

expected scenario -
1) there is a paste option in colab for text copied in different apps on a mobile phone

**Comment by cperry-goog** [comment]
I can't repro this - on my iPhone 11 I get a paste option if I long select in the box. It's a little janky but it works -- please re-open with repro steps if you can get this.

**Comment by vainaixr** [comment]
yes it works with long press.
I was attempting with a short press as that works when pasting in notes.
