### ISSUE TITLE
Google Colab Session Crashes in GPU Mode automatically when try to use face recognition algorithm. Can anyone please help

### ISSUE THREAD

**Issue by AIIP-Clevered** [googlecolab/colabtools#2956]
<img width="796" alt="image" src="https://user-images.githubusercontent.com/91605125/181581742-8389d827-fd93-4cfb-8804-fefa2522f53e.png">

**Comment by cperry-goog** [comment]
I'd try asking upstream with the library authors; unclear that this is a Colab issue.

**Comment by AIIP-Clevered** [comment]
I am sharing google colab notebook for your reference.

Turn on GPU and execute code line by line. You will find the error.

Thank you!!!

**Comment by shivanisriup** [comment]
Notebook link:-

https://drive.google.com/file/d/187SR6biv-_dhI2x-lTzB5xnhvQyUPMy_/view?usp=sharing
