### ISSUE TITLE
Background execution feature not working in Colab Pro+

### ISSUE THREAD

**Issue by nmanuvenugopal** [googlecolab/colabtools#2958]
I have subscribed Colab Pro+ for background execution even if the my laptop is locked. However, the pattern shows that when the screen automatically locks, the execution fails. As you are aware, training a model requires a lot of time and is challenging to repeat. Please let me know if there is anything I need to do on my end.

**Comment by craigcitro** [comment]
We'll need more information to follow up on this bug report. Please submit feedback within Colab at `Help` > `Send feedback` and reference this github issue.
