### ISSUE TITLE
copy in vim drops last character when right to left selection is used

### ISSUE THREAD

**Issue by lvwarren** [googlecolab/colabtools#2961]
**Current behavior:**
When I select and cut text from right to left in Jupyter in Chrome on MacOS, the last character is always dropped.
When I select and cut text from left to right it works fine.

**Expected behavior**
When I select and cut text from right to left in Jupyter in Chrome on MacOS, the last character should be retained.

**What web browser you are using**
Chrome

**Additional context**
Works with any Google Colab Jupyter Notebook whose cell editing options are set to vim.

**Comment by cperry-goog** [comment]
https://github.com/brijeshb42/monaco-vim/issues/100 is the origin here
