### ISSUE TITLE
colab suddenly restart and stop run when (face_recognition.face_encodings)

### ISSUE THREAD

**Issue by AhmedQusay** [googlecolab/colabtools#2962]
**Describe the current behavior**
i am using colab for face recognition, it was working properly, but today when I reach the following line the colab stop and restart the session suddenly: **(colab stops on encoding code line)**

messi = face_recognition.load_image_file('the path of the image ')
messi_face_encodings = face_recognition.face_encodings(messi)[0]

**Describe the expected behavior**
it was working correctly in the past

**What web browser you are using**
(Chrome)

**Additional context**
below in the app.log 
<html>
<body>

WARNING | WARNING:root:kernel 65c933ab-594b-4985-825c-3114847718fa restarted
-- | --
Jul 30, 2022, 10:21:40 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Jul 30, 2022, 10:19:07 PM | WARNING | WARNING:root:kernel 65c933ab-594b-4985-825c-3114847718fa restarted
Jul 30, 2022, 10:19:07 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Jul 30, 2022, 10:17:24 PM | INFO | Adapting to protocol v5.1 for kernel 65c933ab-594b-4985-825c-3114847718fa
Jul 30, 2022, 10:17:22 PM | INFO | Kernel started: 65c933ab-594b-4985-825c-3114847718fa
Jul 30, 2022, 10:16:24 PM | INFO | Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Jul 30, 2022, 10:16:24 PM | INFO | http://172.28.0.2:9000/

</body>
</html>

**Comment by cperry-goog** [comment]
Can you share a minimal reproducible notebook?

**Comment by kristianyosi** [comment]
Just happened to me, too. I even upgraded to Colab Pro but still crashes.

**Comment by cwreynolds** [comment]
I suspect this may be related to issue https://github.com/googlecolab/colabtools/issues/2965 — _Frequent disconnects while busy running in Google Colab_.

**Comment by kristianyosi** [comment]
My Face Recognition Colab is pretty short and only takes about 2 min to run. 
https://colab.research.google.com/drive/1fKZL--zQzQLxFc3-5Q8LPliaLjx7uQw7
My solution was to move my code to Kaggle.
https://www.kaggle.com/code/yosikristian/face-recognition

**Comment by RamishRasool14** [comment]
> Can you share a minimal reproducible notebook?

Below is the minimal possible code that results in the crash.

```
!pip install face-recognition
!wget https://upload.wikimedia.org/wikipedia/commons/6/68/Joe_Biden_presidential_portrait.jpg -O /content/biden.jpg
import face_recognition
known_image = face_recognition.load_image_file("/content/biden.jpg")
biden_encoding = face_recognition.face_encodings(known_image)[0]
```

**Comment by cperry-goog** [comment]
Thanks for the code! We can reproduce this. b/245796152 tracks internally

**Comment by colaboratory-team** [comment]
Installing an older version of `dlib` works for me on a GPU runtime:

```
!pip install dlib==19.18
!pip install face-recognition
!wget https://upload.wikimedia.org/wikipedia/commons/6/68/Joe_Biden_presidential_portrait.jpg -O /content/biden.jpg
import face_recognition
known_image = face_recognition.load_image_file("/content/biden.jpg")
biden_encoding = face_recognition.face_encodings(known_image)[0]
```
It seems like the face-recognition library breaks on newer versions of dlib (Colab currently uses 19.24), I would reach out to the library maintainer about this issue (although the library has not been updated since 2020)
