### ISSUE TITLE
[Feature Request] support 8-bit color sequence generated by Pygments

### ISSUE THREAD

**Issue by ganler** [googlecolab/colabtools#2963]
**Is your feature request related to a problem? Please describe.**
While Jupyter notebook, the notebook plugin from VSCode, and many other terminals support rendering [24-bit](https://en.wikipedia.org/wiki/ANSI_escape_code#24-bit) color sequences, Google Colab seems not render the 24-bit colors correctly for now that such highlighted texts are displayed in black and white. 

For example:

```python
print('\x1b[38;5;28;01mimport\x1b[39;00m \x1b[38;5;21;01mos\x1b[39;00m\n')
```

**iTerm**

<img width="670" alt="image" src="https://user-images.githubusercontent.com/38074777/182040800-b37474d0-f301-4975-80bc-ca7b00465fed.png">

**Jupyter Notebook**

<img width="582" alt="image" src="https://user-images.githubusercontent.com/38074777/182040827-0e6a2c12-9361-4571-8daf-e15fb05acb89.png">

**Colab** ❌

<img width="549" alt="image" src="https://user-images.githubusercontent.com/38074777/182040845-da4cc451-4ab8-4992-bfdb-f5179ef825d4.png">

**Describe the solution you'd like**
Given a [24-bit](https://en.wikipedia.org/wiki/ANSI_escape_code#24-bit) color sequence, render it to correpsonding RGB colors in HTML display correctly (not pure black).

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by blois** [comment]
Clarification-
24-bit colors do work, for example:
`print('\x1b[38;2;0;127;0;01mimport\x1b[39;00m \x1b[38;2;0;0;255;01mos\x1b[39;00m\n')`

It's the 8-bit color sequence which is broken.

**Comment by ganler** [comment]
Thanks @blois for the clarification. After a closer check, Colab indeed supports 24-bit color. Sorry for pointing out the wrong issue. The example color sequence is a 8-bit one. However, I am still curious why other renders can display this sequence expectedly?

**Comment by blois** [comment]
There was a missing multiplier, the fix should be out on Monday.
