### ISSUE TITLE
Colab notebook not using GPU despite having selected GPU in runtime panel

### ISSUE THREAD

**Issue by frigeriomtt** [googlecolab/colabtools#2964]
**Describe the current behavior**
The notebook does not seem to use the gpu at all (as reported from occasional popups and showed by the resources panel) despite having selected GPU as runtime; at some point, the script eventually run of RAM (which is probably not related and I could resolve by upgrading, but resources panel shows that GPU ram is not being used).

**Describe the expected behavior**
 The script should use GPU resources

**What web browser you are using**
Chrome

**Comment by craigcitro** [comment]
Using a GPU requires reworking your code to take advantage of it; see https://research.google.com/colaboratory/faq.html#gpu-utilization
