### ISSUE TITLE
stuck at python's input function.

### ISSUE THREAD

**Issue by improvisor40** [googlecolab/colabtools#2969]
please, do you know how to get passed python's input function?.
i cant seem to get passed it, i wrote a small program that takes input and prints how many letters are there but after writing the letters i cant tap enter, if you can please help.

_Originally posted by @improvisor40 in https://github.com/googlecolab/colabtools/issues/2908#issuecomment-1203088184_

**Comment by craigcitro** [comment]
Can you provide a minimal, public repro notebook demonstrating the problem?

**Comment by improvisor40** [comment]
Thanks, but I found a fix, it's probably obvious, I just couldn't find it on time, it's the Linux yes command I use to fix the input problems. With the python input function.
I was having problems answering (y/n) to a python module, so it was frustrating, but thank "God" its fixed.
I will close it now.
