### ISSUE TITLE
Python dict is sorted by keys in worksheet result

### ISSUE THREAD

**Issue by m-f-h** [googlecolab/colabtools#2972]
**Describe the current behavior**
Python dicts are sorted by keys inworksheet results:
e..g., in function test(), define ` c={'2':2, '1':1} ; `
if you print it, it's correct, 
if you return it, the result is displayed (and stored in variables  _ and _xx ) as {'1':1, '2':2} 
(see link below) which is INCORRECT, because
` import sys ; sys.version ` says it's Python 3.7

**Describe the expected behavior**
Since Python 3.6 a dict MUST remain in the order it is created.
So the result of the above function should be displayed  returned as is (since Python 3.6 a dict is supposed to respect insertion order).

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue:
https://colab.research.google.com/drive/1dwercctjDsw4bLN1U5ZSasqj6Z7ndJDM?usp=sharing

**Comment by craigcitro** [comment]
Colab doesn't own any logic here, we get this from IPython, which fixed it in https://github.com/ipython/ipython/pull/10958. We'll pick that up as part of our next IPython upgrade (which is hopefully soon).
