### ISSUE TITLE
import geemap error

### ISSUE THREAD

**Issue by sook296** [googlecolab/colabtools#2977]
![github_문의사항1](https://user-images.githubusercontent.com/103712130/183328382-a8afdee5-9f95-4864-bfb9-8f1edbdc14d3.png)
 
not import geemap

Please help me   

thank you

**Comment by craigcitro** [comment]
The `!pip install geemap` requires you to restart your kernel; you should have seen a prompt after the install.

You can restart with ctrl-m . or `Runtime` -> `Restart runtime`.
