### ISSUE TITLE
Getting latest pandas require restart

### ISSUE THREAD

**Issue by aprbw** [googlecolab/colabtools#298]
Running this

`!pip install pandas==0.23.4
import pandas as pd
pd.__version__`

will give

> '0.22.0'

I have to click "Runtime" > "Restart runtime..." and run the codes again to get

> '0.23.4'

**Comment by craigcitro** [comment]
The problem here is that pandas is loaded when initializing a colab runtime, and imports in python are a noop for already-loaded modules.

The fastest approach here is just to restart the runtime once you `pip install`.
