### ISSUE TITLE
cell stuck after model training(not runbning but showing keep running), can't able to stop or run the code.

### ISSUE THREAD

**Issue by Pratik-Kapadiya** [googlecolab/colabtools#2983]
cell stuck after model training(not running but showing keep running), can't able to stop or run the code for the same line and after.

I can run code lines before that stuck line.
but can't be able to run that or after code lines.

**Comment by alexklwong** [comment]
I am also having this problem. My tqdm for my training loop is stuck at 0%.

```
Begin Epoch:    1/17
Epoch:    1/17  Batch:   0% 0/18559 [00:00<?, ?it/s]
```

**Comment by cperry-goog** [comment]
Do you have a minimal repro notebook?

> not running but showing keep running

Do you have a screenshot of what you're seeing?
