### ISSUE TITLE
Cell keeps running but not executing anything. 

### ISSUE THREAD

**Issue by pandugorthi** [googlecolab/colabtools#2986]
**Describe the current behavior**
Hi I am unable to execute even. a simple cell in the notebook. The cell keeps running but below we can see it is not executing anything. the issue did not resolve even after restarting and running multiple times. I tried to run it in different browsers but the issue persists. I disconnected and reconnected the wifi multiple times also to resolve the issue. But the issue was not resolved.

The code is just assigning value to a column For example df["Country"]=US. 

**Describe the expected behavior**

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
 I have tried it in both chrome and safari.

**Comment by cperry-goog** [comment]
Are you able to consistently reproduce this? If so, can you share the notebook that reproduces it?
