### ISSUE TITLE
Payment for Colab Pro doesn't seem to work (Firefox 99.0, Ubuntu 20.04.4 LTS, from France)

### ISSUE THREAD

**Issue by Valkea** [googlecolab/colabtools#2989]
The payment authorizes, and then it repeats this screen, never completing the transaction.

![147834572-78c63609-2556-4961-8e70-92f47dedda1f](https://user-images.githubusercontent.com/3459527/184409691-d0262a22-73ef-4b2a-a5d2-47e8eeefdccd.jpg)
(this screenshot is not mine, but I had exactly the same behaviour)

I already have 2 pending subscriptions...

---
![Screenshot from 2022-08-12 19-13-55](https://user-images.githubusercontent.com/3459527/184409884-4bb0c456-dec9-4d65-8768-0fdca364ea9c.png)
---

I validated one payment with my bank application and it confirmed the payment.
But both are still pending and yet not access to the colab pro service.

I used Firefox 99.0 on Ubuntu 20.04.4 LTS and I'm in France.

**Comment by cperry-goog** [comment]
We use Google Pay for billing; you'll want to explore their help center or contact their agents: https://support.google.com/googlepay/#topic=11450859
