### ISSUE TITLE
Background execution not functioning with Colab Pro+

### ISSUE THREAD

**Issue by epetersen-sci** [googlecolab/colabtools#2991]
I am attempting to run a Alphafold project using the template [publicly available](https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb). Due to the long runtimes I purchased Colab Pro+ so that I could execute in the background.

In the runtime setup I do have "Background execution" checked, but after the runtime starts a message pops up at the bottom informing me that background execution is not enabled. The link in the message doesn't work.  

I am not sure if background execution is enabled or not and I'm not sure how to check without potentially canceling the long run I have started. 

I am using Chrome 104.0.5112.81.

**Comment by colaboratory-team** [comment]
Thanks for reporting this issue. We are tracking and investigating this issue internally, and provide an update soon.
