### ISSUE TITLE
range() overfflows

### ISSUE THREAD

**Issue by maks1798** [googlecolab/colabtools#2992]
**Describe the current behavior**
code:
```
x = list(range(100))
y = x

for n in x:
  print(n)
  s = {*range(int(n))}
  # res = %timeit -r2 -n2 -q -o list(s)
  y.append(res.best)
```
output:
```
  ...
  5.360000159271294e-07
  5.360000159271294e-07
  5.360000159271294e-07
  5.360000159271294e-07
  ...
```
and it goes on untill keyboard interupt

**Describe the expected behavior**
code:
```
x = list(range(100))
y = x

for n in x:
  print(n)
  s = {*range(int(n))}
  # res = %timeit -r2 -n2 -q -o list(s)
  y.append(res.best)
```
output:
```
 "res" is not defined
```

**What web browser you are using**
Firefox Developer Edition 104.0b9

**Additional context**
[link to notebook](https://colab.research.google.com/drive/16ZetZbUExs3RZjpFGKBsfc1QsgeAPOdH?usp=sharing)

**Comment by mayankmalik-colab** [comment]
I tried running the attached notebook and getting the error as expected - `NameError: name 'res' is not defined` . Can you restart the runtime and try again. The 'res' value can also come from previous run ( if the cell was previously run without 'res' being commented).

**Comment by maks1798** [comment]
Restarted cell, works as expected.
The issue was with range going over the upper limit, but I have no idea,
how to replicate it now.
