### ISSUE TITLE
Undo deleted scratch or normal cell feature

### ISSUE THREAD

**Issue by pedr0sorio** [googlecolab/colabtools#2994]
**Is your feature request related to a problem? Please describe.**
Google Colab offers the very useful feature of scratch cells, which are perfect for testing code without disrupting the flow of the notebook. However, I am always frustrated that when I close the scratch for some reason there is no way to retrieve what was there written. I have faced this issue mainly with scratch cells but i think it also happens with normal cells.

**Describe the solution you'd like**
The same way one can undo a deleted cell by using the command esc + z in Jupyter notebooks, colab could adopt a similar solution.
It would be beneficial for all if history of deleted cells was kept for both normal cells as also scratch cells.

Thanks for reading,
Pedro

**Comment by cperry-goog** [comment]
Tracked internally at b/243058895

Thanks!

**Comment by katlyn-edwards** [comment]
Hey there! Thanks for the note - this should be now be live. Please feel free to re-open if you notice anything wrong.
