### ISSUE TITLE
Colab Pro+ constant disconnection

### ISSUE THREAD

**Issue by fastrocket** [googlecolab/colabtools#2996]
**Describe the current behavior**
I'm running a single Colab Pro+ background process which I leave open in my browser. But after a time, the session is disconnected for no apparent reason. I have another notebook open with another provider and I don't get disconnected there. This seems to be happening recently as I didn't have this problem last week.

The background process still seems to run (I can see output in Google Drive), but I am also unable to reconnect to the session. It hangs trying to reconnect.

**Describe the expected behavior**
Not to lose my session connection.

**What web browser you are using**
Chrome

**Additional context**

**Comment by colaboratory-team** [comment]
Thanks for reporting this issue. We are tracking and investigating this issue internally, and provide an update soon.

**Comment by colaboratory-team** [comment]
This issue should be fixed by now, for newly connected runtimes with background execution enabled. Otherwise, please reopen this issue, and also consider sending a feedback from Colab UI (Help - Send feedback) so that we may have more information to investigate your issue with.
