### ISSUE TITLE
Python logging module: content streamed to the log file also shows in cell output

### ISSUE THREAD

**Issue by johanmonard** [googlecolab/colabtools#2998]
I use the python logging module to write a log file, but a few days ago all the content that is written to the file started to appear in the cell output. Any idea why?
Browser: Chrome
Colab Pro +

**Comment by cperry-goog** [comment]
Could you share a minimal repro notebook?

**Comment by johanmonard** [comment]
I finally got rid of the issue by setting `logger.propagate=False` for each running logger, but I had been using the loggers without that setting for months and the logs suddenly started appearing in the cell outputs a few weeks ago.

**Comment by NguyenThaiHoc1** [comment]
I'm trying to use logging module to write log but not work 
This is my code
```
import logging
logging.basicConfig(filename='rb-log.log', 
                    format='%(process)d-%(asctime)s-%(levelname)s-%(message)s',
                    force=True,
                    propagate=False,
                    level=logging.info)
# logger.
# logger = logging.getLogger(__name__)
logging.debug('This is a debug message')
logging.info('This is an info message')
```
I use it in google colab pro. But not working. Pls Help
