### ISSUE TITLE
Test Upgrading PyTorch and torchvision  torchaudio with CUDA 11.6

### ISSUE THREAD

**Issue by atalman** [googlecolab/colabtools#2999]
Hello,

We are planning on releasing

pytorch v1.13.0
torchvision v0.14.0
torchaudio v0.13.0

With CUDA 11.6 support, deprecating CUDA 11.3. We want to try CUDA 11.6 wheels on Google Collab and make sure it works.

The wheel installation script:

pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cu116

Other notes
If you require wheels for Python 3.8 / 3.9 or 3.10 you can find the links here: [download.pytorch.org/whl/nightly/](https://download.pytorch.org/whl/nightly/)

We're looking to having it updated in Colab for next release

Thanks very much.

cc'ing @colaboratory-team @craigcitro @malfet 

Similar to #2372

**Comment by malfet** [comment]
Creating a collab to check that it works with 1.12.1, will update this comment with the findings and URL to the notebook

**Comment by craigcitro** [comment]
That looks promising!

I'm fine saying that we can try the CUDA 11.6 wheels for the next torch release; if something goes sideways, we can fall back to the current version and reconsider. (If there are CUDA 11.6 wheels for the current pytorch release, we could also try those first.)

**Comment by robotwhispering** [comment]
You do realize that CUDA is the issue that needs to be resolved first, right? You can have all the compatible libraries/frameworks in the world fully supported, but we're sitting here ONLY able to connect to environments with CUDA 11.2 or 11.1. I upgraded to the Colab Pro + plan, and I ended up wasting 2 complete days installing, reinstalling, uninstalling, on an environment that you arbitrarily either make me restart anyway or you do it yourself. It's a joke. For proper Pytorch integration as of today, we need either 11.3 or 11.6 on these virtuals, available like YESTERDAY! I'll be going back to Microsoft Azure until this is resolved. At least if I spend a day getting the environment set up, I can actually use it...not have it vanish seconds later.

**Comment by robotwhispering** [comment]
Actually, I'll give you a free business plan. Provide us with the option of putting the notebook in a "Environment Setup" state, that comes with some persistence, just enough to cover setting up environments that require a reboot. I would pay for that today.
