### ISSUE TITLE
Enable easier file loading

### ISSUE THREAD

**Issue by rgerkin** [googlecolab/colabtools#30]
Currently, if I have a .csv file (output from some instrument, for example), all options for getting that loaded into the notebook and read into e.g. a Pandas dataframe are pretty awkward.  I wouldn't mind so much, but I'm teaching a class of 35 undergrads with minimal programming experience and I'd like to make it easy for them.  I feel like this:  
<img width="267" alt="screen shot 2018-01-22 at 4 35 43 pm" src="https://user-images.githubusercontent.com/549787/35250142-5ba71968-ff92-11e7-91f5-e0ad8412f453.png">
with the associated file upload dialog clicking is way more awkward that the equivalent scenario in Azure notebooks where I load the `dice.csv` file into the workspace before class, and then cells 2-4 just become the usual one line `df = pd.read_csv('dice.csv')`.  In Colab, the students have to point and click and find the data somewhere and execute a few more cells.  I could put in on Drive or Sheets or the web, but then there are a bunch of nuisance Google API commands that distract from the Data Science lesson as it would be taught on a stand-alone local Jupyter notebook server with real local file storage.  For example, doesn't this seem a bit excessive for a student trying to load one file?  
<img width="320" alt="screen shot 2018-01-22 at 4 48 20 pm" src="https://user-images.githubusercontent.com/549787/35250603-a59d8280-ff94-11e7-8223-05b313918ea6.png">
Maybe there is some security concern preventing the "easy" solution of, say, letting a user mark an entire Drive folder containing a Colab notebook as public, and then allowing local file reads within that folder (through a transparent-to-the-user set of background calls to `googleapiclient`).  It's also not clear why the user has to authenticate to download one file.  From my end it would be easier to use the API docs to compose the raw file download URL, and then use `urllib` and `io.StringIO` to read it back in.  But again, couldn't this be even easier?  

If there isn't a simpler auxiliary file handling solution already in the works, and since you aren't considering PRs right now, would you welcome a rapidly installable package on PyPI for one-line loading of public GDrive files into Colab?  Something as simple (or simpler) than the implementation for Google Cloud Storage file loading?  

I only write this because Colab is *so awesome* and I really love it, but right now for teaching a class, Azure Notebooks is still better because of this one major issue.

**Comment by colaboratory-team** [comment]
A typical pattern is to use `!wget <url>` to retrieve files in the course of executing the cell.

Here's a simple example:

```
!wget -q https://raw.githubusercontent.com/oncletom/coursera-ml/master/week-1/people-example.csv -O people-example.csv
import pandas as pd
df = pd.read_csv('people-example.csv')
df
```

**Comment by rgerkin** [comment]
@colaboratory-team This is useful, thank you.  For medium-sized binary files that are inappropriate for GitHub, I'd like to load them from Drive.  I know how to do this, but a documented URL pattern for a publicly-shared Drive file would be helpful for the documentation, e.g.:
```
# Download a Google Drive file with a shareable link by extracting 
# the FILE_ID from that link and using it as follows:
!wget -q https://drive.google.com/uc?export=download&id=FILE_ID
```
