### ISSUE TITLE
runtime crashes

### ISSUE THREAD

**Issue by arshamkhodajoo** [googlecolab/colabtools#3001]
**Describe the current behavior**
I tried to train simple CNN network using `pytorch_lightning` on gpu, it works fine on my machine but colab runtime crashes every time I run `trainer.fit(..)`

![image](https://user-images.githubusercontent.com/105818828/185058223-7aa16435-71d8-41b3-93eb-2987f9a1920d.png)

**Describe the expected behavior**
Train on GPU, as it works on my machine
no RAM overload, no VRAM allocation limit. just sudden runtime restart !

**What web browser you are using**
Chrome

**Comment by arshamkhodajoo** [comment]
the part which trigger this problem:

![image](https://user-images.githubusercontent.com/105818828/185059614-d16f1aa7-f964-4bdc-8b31-3c38b93fb58d.png)

**Comment by colaboratory-team** [comment]
Can you provide a link to a minimal repro notebook? Make sure its publicly visible so we can see it

**Comment by arshamkhodajoo** [comment]
sorry I totally forgot to share notebook !

notebook:
https://colab.research.google.com/drive/1lp6oEVMbfbBczgHjuGrsp9Q9O6xAvXBa?usp=sharing

all imports are from here:
https://github.com/arshamkhodajoo/callme

this notebook works fine on my machine using CPU, it runs a few backward iteration before crash runtime both on CPU and GPU

**Comment by metrizable** [comment]
Thanks for the reply and the repro notebook!

From looking at the notebook, the first cell installs an unpinned version of `pytorch_lightning`, whose latest versions (1.7.2, 1.7.3) pull in the dependency `tensorboard==2.10.0`, conflicting with the already installed version of `tensorflow==2.8.2`:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.8.2+zzzcolab20220719082949 requires tensorboard<2.9,>=2.8, but you have tensorboard 2.10.0 which is incompatible.****
```
On execution of the notebook, I am able to replicate that it eventually leads to a kernel crash. The runtime logs contain this exception:
```
[libprotobuf FATAL google/protobuf/stubs/common.cc:87] This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.17.3). Contact the program author for an update. If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/[tensor_shape.pb.cc](http://tensor_shape.pb.cc/)".)
```

One work-around that you can try that worked for me would be to install a slightly older, but compatible, version of `pytorch_lightning`:
```
!pip install pytorch_lightning==1.6.5 torch_optimizer
```
On a side note, the last cells in your example notebook under the "vanila run" section refer to a `device` variable that does not exist, which raises `NameError: name 'device' is not defined`.

**Comment by arshamkhodajoo** [comment]
Hi @metrizable
after few days, my solution to fix this problem was getting rid `pytorch-lightning` for sake of getting project done and I ended up adding section "vanila run" to demonstrate classic Pytorch train pipeline works without problem.

so pytorch-lightning use tensoboard under the hood which cause this cnflict crash ..that little case took me really long time with no luck.

Thank for your help, now I think it's time to close this issue.
