### ISSUE TITLE
Unable to cancel Colab Pro when google account has been disabled

### ISSUE THREAD

**Issue by JohYis** [googlecolab/colabtools#3003]
My file size in Google drive has exceeded the storage limits.
So the organization has disabled my google account.

I have a Colab Pro subscription.
Now I want to cancel it.
But since I can't log in with the disabled account, I can't cancel it.

**Describe the current behavior**
I can't cancel the Colab Pro subscription if my account has been disabled.

**Describe the expected behavior**
There should be another way to cancel Colab Pro.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
 -

**Comment by cperry-goog** [comment]
Please contact colab-billing@google.com for subscription issues, thanks.
