### ISSUE TITLE
Deep Convolutional Generative Adversarial Network does not run on google Colab

### ISSUE THREAD

**Issue by aebtehaj** [googlecolab/colabtools#3005]
Hi, I am just trying to run an example provided https://www.tensorflow.org/tutorials/generative/dcgan on my google Colab and it runs into the following error. I did not make any change in the code. 

When I try to run the following cell:

generator = make_generator_model()

noise = tf.random.normal([1, 100])
generated_image = generator(noise, training=False)

plt.imshow(generated_image[0, :, :, 0], cmap='gray')

I get the following error message:

UnimplementedError                        Traceback (most recent call last)
[<ipython-input-33-e8aca7e79c6e>](https://localhost:8080/#) in <module>
      2 
      3 noise = tf.random.normal([1, 100])
----> 4 generated_image = generator(noise, training=False)
      5 
      6 plt.imshow(generated_image[0, :, :, 0], cmap='gray')

1 frames
[/usr/local/lib/python3.7/dist-packages/keras/backend.py](https://localhost:8080/#) in conv2d_transpose(x, kernel, output_shape, strides, padding, data_format, dilation_rate)
   5756     x = tf.compat.v1.nn.conv2d_transpose(x, kernel, output_shape, strides,
   5757                                          padding=padding,
-> 5758                                          data_format=tf_data_format)
   5759   else:
   5760     if dilation_rate[0] != dilation_rate[1]:

UnimplementedError: Exception encountered when calling layer "conv2d_transpose_15" (type Conv2DTranspose).

DNN library is not found. [Op:Conv2DBackpropInput]

Call arguments received by layer "conv2d_transpose_15" (type Conv2DTranspose):
  • inputs=tf.Tensor(shape=(1, 7, 7, 256), dtype=float32)

**Comment by colaboratory-team** [comment]
We are rolling out a fix soon. Two potential workarounds for you in the meantime:

1) !pip install -U tensorflow==2.8.2 (this one is safer)

or

2) !apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2

Make sure you Runtime -> Restart Runtime after running either of these, and the notebook should start working again

**Comment by aebtehaj** [comment]
I appreciate your feedback. I will follow the instruction and will keep you posted. 
Cheers, Ardeshir

**Comment by colaboratory-team** [comment]
The fix for this should now be fully rolled out, closing
