### ISSUE TITLE
Fail to find the dnn implementation.

### ISSUE THREAD

**Issue by 2076959577** [googlecolab/colabtools#3011]
why?  This has never happened before. 

---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
[<ipython-input-33-20150c770223>](https://localhost:8080/#) in <module>
      1 # 使用Adoboost集成各个模型
      2 Adaboost_all = Adaboost_integrate()
----> 3 Adaboost_all.Ada_fit(X_train, y_train, X_val, y_val, model , scaler )
      4 pre_Ada_all = Adaboost_all.Ada_predict(X_train, y_train, X_val, y_val, model, scaler)

2 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

UnknownError: Graph execution error:

Fail to find the dnn implementation.
	 [[{{node CudnnRNN}}]]
	 [[sequential_1/lstm_3/PartitionedCall]] [Op:__inference_predict_function_5730]

**Comment by colaboratory-team** [comment]
We are rolling out a fix soon. Two potential workarounds for you in the meantime:

1) !pip install -U tensorflow==2.8.2 (this one is safer)

or

2) !apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2

Make sure you Runtime -> Restart Runtime after running either of these, and your notebook should start working again

**Comment by colaboratory-team** [comment]
The fix for this should now be fully rolled out, closing
