### ISSUE TITLE
DNN library is not found 

### ISSUE THREAD

**Issue by Nikhil-IITI** [googlecolab/colabtools#3012]
**Describe the current behavior**
DNN library is not found for Convolution operation

**Describe the expected behavior**
Just 12 hr ago Everything was working fine(Conv2D layers were not showing any problem) 

**What web browser you are using**
Google Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by metrizable** [comment]
There are two work-arounds that may resolve your issue until we can roll out a fix

```
!pip install -U tensorflow==2.8.2
```
or

```
!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2
```

Either work-around requires a restart of your runtime.

**Comment by colaboratory-team** [comment]
The fix for this should now be fully rolled out, closing
