### ISSUE TITLE
Fail to find the dnn implementation.

### ISSUE THREAD

**Issue by JayPBhatia** [googlecolab/colabtools#3014]
**Describe the current behavior**
[usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py](https://localhost:8080/#) in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

UnknownError: Graph execution error:

Fail to find the dnn implementation.
	 [[{{node CudnnRNN}}]]
	 [[sequential_1/bidirectional/forward_lstm/PartitionedCall]] [Op:__inference_train_function_547451]

**Describe the expected behavior**
No Exception. 

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by metrizable** [comment]
There are two work-arounds that may resolve your issue until we can roll out a fix

```
!pip install -U tensorflow==2.8.2
```
or

```
!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2
```

Either work-around requires a restart of your runtime.

**Comment by colaboratory-team** [comment]
The fix for this should now be fully rolled out, closing
