### ISSUE TITLE
Exclamation commands behavior changed for single quoted variables

### ISSUE THREAD

**Issue by eyaler** [googlecolab/colabtools#3017]
I am using single quotes around cli variables which may contain spaces. this does not work anymore unless i change all single quotes to double quotes. This is breaking tens of my colabs
```
folder = '/content'
!ls '$folder'
```
used to work the same as:
```
folder = '/content'
!ls "$folder"
```
but now no longer works and gives:
```
ls: cannot access '$folder': No such file or directory
```

**Comment by blois** [comment]
This is most likely due to https://github.com/ipython/ipython/pull/10545 which arrived in a recent IPython upgrade.

```python
folder = '/content'
!ls "$folder"
```

**Comment by eyaler** [comment]
yes. please stop changing the environment.
