### ISSUE TITLE
Please use informative descriptions for commits

### ISSUE THREAD

**Issue by eyaler** [googlecolab/colabtools#3018]
most commits seems to read "internal change" which is not useful for debugging breaking changes.

**Comment by craigcitro** [comment]
Agreed that it would be nice to have better descriptions.

That said, the commits here only affect a small slice of the user-visible surface (namely the code in the `google.colab` package), and are unlikely to help in the situation I suspect you were in. We're working on that -- I'm going to dupe this against #1445, which tracks that work.
