### ISSUE TITLE
Incorrect "cell" activated when using `input()`

### ISSUE THREAD

**Issue by eikonomega** [googlecolab/colabtools#302]
I've noticed that when you have an `input()` function within a cell and then run that function a couple of problems occur:

1. The cursor either stays in the code cell when you where (ctrl + enter) or moves to the cell AFTER the input dialog (ctrl + return). You have to manually click on the input box to have control go to the right place.

2. The input box is improperly positioned in the cell output window (see image).

These two things together make for 💩 experience using `input()`.

Any fixes or workarounds?

Thanks!

<img width="714" alt="image" src="https://user-images.githubusercontent.com/415939/46908814-66656d80-cef6-11e8-8c48-20ca40b74a35.png">

**Comment by colaboratory-team** [comment]
Thanks for the feedback and sorry for the trouble!

We've looked into this and believe the root issue should be fixed. This should be available in the next few days.

**Comment by eikonomega** [comment]
@colaboratory-team AWESOME!!!! Thanks!
