### ISSUE TITLE
Auto complete

### ISSUE THREAD

**Issue by gatorwatt** [googlecolab/colabtools#3021]
**Is your feature request related to a problem? Please describe.**

This is a small thing and is more as an fyi than any pressing need for a fix. Colaboratory's autocomplete feature to view available commands associated with a module (as could be used for exploring commands available in the cirq library) appears to max out at 100 displayed commands. It would be cool for exploratory purposes if colab could add support to navigate beyond this limit.

**Describe the solution you'd like**

after pressing command space to view available completions, if this list runs into this constraint, a simple “show more” button would be helpful. 

**Describe alternatives you've considered**

Or if you could roll out a large language model code complete tool that would be cool as well.

**Comment by craigcitro** [comment]
Our autocomplete mechanism is designed to only return 100 entries; if you start typing, we'll filter the results (fetching more results if needed).

If you want the full list, `dir(myobj)` will work.
