### ISSUE TITLE
tqdm.notebook does not work on colab

### ISSUE THREAD

**Issue by khslsahan** [googlecolab/colabtools#3023]
from tqdm.notebook import trange, tqdm
from time import sleep

for i in trange(3, desc='1st loop'):
    for j in tqdm(range(100), desc='2nd loop'):
        sleep(0.1)

Does not shows progress bar 

when run the code enable_custom_widget_manager snippets comes out

**Comment by aksinha4** [comment]
Experienced the same issue. My Language Model training code uses Huggingface library which in turn uses tqdm extensively. Till yesterday, the code was working perfectly ok and suddenly it stopped working from today morning. As soon as tqdm code is encountered, code-snippet "enable_custom_widget_manager" pops up and asks to insert code to enable third party widgets display. And even when I insert code to enable third party widget display, tqdm does not display at all.

Needs to be fixed very urgently.

**Comment by osanseviero** [comment]
Also reported in social media
* https://twitter.com/_nateraw/status/1560759694016352257
* https://twitter.com/charles_irl/status/1561170712030679042

And notice that the suggested fix to enable the widgets doesn't fix the issue (I guess related to #3020). This is probably breaking hundreds of notebooks out there without any previous notice nor mention in the [release notes](https://colab.research.google.com/notebooks/relnotes.ipynb)

**Comment by colaboratory-team** [comment]
Thanks for the report; we're aware of the breakage and will roll out a fix in the next few days. In the meantime, downgrading ipywidgets should fix your issue:

`!pip install ipywidgets==7.7.1`

You may need to restart your runtime after running this

**Comment by khslsahan** [comment]
downgrading ipywidgets solve the problem
                              !pip install ipywidgets==7.7.1
Thanks!!!

**Comment by colaboratory-team** [comment]
The fix for this should now be rolled out. If you are still seeing the issue, try deleting your runtime and connecting to a new one
