### ISSUE TITLE
Scrolling not working sometimes

### ISSUE THREAD

**Issue by DrFelder** [googlecolab/colabtools#303]
When using the colab tool for the [machine learning crash course](https://colab.research.google.com/notebooks/mlcc/synthetic_features_and_outliers.ipynb), I have trouble scrolling through the page.

##### Expected behaviour
I can scroll normally, every "click" of my mousewheel moves the page down/up the same amount of lines.

##### Experienced behaviour
My pointer gets "stuck" on code blocks: When I scroll up or down and start from a code cell, the scrolling only seems to move the code inside the code cell up/down. The code is moved only about a fifth of a line, and scrolling is stuck for another few ticks.
It does not matter whether or not I selected a cell or text.

##### User agent
Mozilla/5.0 (X11; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0

I haven't looked into it and can't tell what exactly is going wrong, I hope the description is clear enough for you to understand the issue.

**Comment by Melanol** [comment]
Same thing here. Chrome/Windows 7. Works 50% of the time when trying to scroll a cell containing this [code](https://gist.github.com/karpathy/a4166c7fe253700972fcbc77e4ea32c5) in one cell (the cell probably has to be long). The cell has to be selected. Moving your cursor out of the cell fixes it (example: the whole vertical line below the Run Cell button. It feels like the system sometimes thinks that the cell has it's own scrolling and moves up/down 2 pixels. Try moving the cursor out of the cell and back to increase chances of reproduction.

**Comment by galdezanni** [comment]
Hey guys,

@blois , @DrFelder 

This is also happening to me, Google Colab (browser screen) crashes when I scroll the screen with the mouse scroll.

I've already tested it with Chrome, Edge and Safari, and the problem is always repeated, when I use the notebook trackpad I don't get an error, the error only occurs with the mouse scroll

Mouse: Logitech M720
PC: Macbook Pro - mid 2012
OS: macOS Catalina 10.15.7
Chrome: 91.0.4472.106

I hope you can help me

Thanks

**Comment by blois** [comment]
Is there a cell with a particularly large output? The outputs don't get rendered until they will be visible on the page, could be one of them being too large and causing the scrolling/crash issue.

Edit -> Clear all outputs may resolve it

**Comment by galdezanni** [comment]
@blois 

Great!!!

It worked, thank you very much!
