### ISSUE TITLE
Google colab is not displaying real time output while executing a cell

### ISSUE THREAD

**Issue by avinashkarkada** [googlecolab/colabtools#3030]
Normally when we run long execution commands (for eg. gmx) in a local linux command prompt, it displays the real time output during the execution. The output consists of number of steps, time remaining etc. Like this ----> https://i.stack.imgur.com/S7Cf2.png
Here, the command is run on a linux cp where there is a realtime display of what is happening during the execution.

`gmx mdrun -deffnm md_out -v`
Above is the command itself that can take a lot of time to execute and I need to know when execution will get completed. So....
It would be great if the output is displayed throughout the execution rather than show it in the end only. This is how it is on the notebook --------> https://i.stack.imgur.com/lhTZl.png

This is the nb ----------> https://colab.research.google.com/drive/1wYbTzE8kFedFjBPNr37D2ou782l3K9P0

**Comment by cperry-goog** [comment]
We don't stream output from bash today, but this is a fine feature request to keep around.

Thanks for the report!

**Comment by cperry-goog** [comment]
I think these are dupes no? #3029

**Comment by avinashkarkada** [comment]
Ahhh. Okay. Thanks
