### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by wons20k** [googlecolab/colabtools#3032]
Hi,

I'm using Chrome and Colab Pro+.
Whenever, I move from my home to school or vice versa, I use the background mode to continue my training.
After I moved my place from the other, I turned on my laptop then the Colab session was connected.
I could so "busy" with green color.

However, from 25-08-2022, when I did the same thing(set the background mode > turned on laptop when I arrived the other place), I only can see "connecting" with orange color. The status was not changed back so I had to disconnect the session. 

Whenever I need to move, I need to disconnect, reconnect, and redownload my dataset because of this bug.
Could you solve this problem?
Thank you.

**Comment by cperry-goog** [comment]
Could you submit feedback in product and reference this issue so we can investigate further? I can't know your account details from a GitHub bug. Thanks!
