### ISSUE TITLE
unable to unmount drive in Google Colab

### ISSUE THREAD

**Issue by shu793** [googlecolab/colabtools#3043]
**Describe the current behavior**
I mounted my google drive to Google Colab but could not unmount it.
The icon to unmount my drive is not shown anywhere but one to mount it still exists.

**Describe the expected behavior**
I need the icon to unmount my drive or want to know the command.

**What web browser you are using**
Chrome

**Comment by mayankmalik-colab** [comment]
I don't think there is any icon to unmount. However, you can unmount by - 
```
from google.colab import drive
drive.flush_and_unmount()
```
For more information and other ways to load/save data from external sources, you can also checkout [io.ipynb](https://colab.research.google.com/notebooks/io.ipynb) .
