### ISSUE TITLE
cannot select different country on Colab Pro purchase

### ISSUE THREAD

**Issue by Csumber** [googlecolab/colabtools#3049]
Upon trying to sing up for [Colab Pro](https://colab.research.google.com/signup), I can not select my country (Denmark), as the address defaults to United States. 

I did check the [terms of service](https://research.google.com/colaboratory/tos_v3.html) and it is never mentioned that the product would only be available in given country (US), in fact, there is a lookup table for all the different countries of the world and associated Google entities.

![Screenshot 2022-09-04 110353](https://user-images.githubusercontent.com/31830274/188305962-e7664c81-fa47-48ee-8e7d-7c59e59d8203.png)

Expected behavior would be for example a dropdown, where I could select my country and enter my address.

**Comment by cperry-goog** [comment]
I think this is a Google Pay issue: you need to set up a pay profile in Denmark: https://support.google.com/googlepay/answer/7644076?hl=en

That said, Pro isn't available in Denmark but it will be very soon (shhhh)
