### ISSUE TITLE
Cannot select code with mouse pointer

### ISSUE THREAD

**Issue by LiuJiLan** [googlecolab/colabtools#3052]
**Describe the current behavior**
Cannot select code with mouse pointer

**Describe the expected behavior**
JUST LIKE COMMON EDITER

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by colaboratory-team** [comment]
Could you provide more details on the behavior that you're expecting? It sounds like you want to double-click or drag the mouse pointer to select code in order to copy/paste, and that already works in Colab

**Comment by LiuJiLan** [comment]
It will be more intuitive to watch the video:
https://drive.google.com/file/d/1btSx4giX2kbku8ph51l1_FECV38s3aZj/view?usp=sharing

Double-click is fine in both text and code cell.
Dragging the mouse pointer is working fine in text cell, but is malfunctioning in code cell.
In the video I additionally test selecting with keyboard shortcuts.

The Chrome version is `104.0.5112.101`  (x86_64)

**Comment by blois** [comment]
Does the issue repro in an incognito browser session?

**Comment by LiuJiLan** [comment]
No, this rendition was recorded under the nighttime look of the browser's normal mode.
But I just went to incognito as an extra to try it out, and when I first tried dragging to select in incognito mode, it worked, but right after that it didn't work again.
This is so weird.

**Comment by cperry-goog** [comment]
If it works in incognito mode it's almost surely a conflicting browser extension modifying the UI state.
