### ISSUE TITLE
Colab has buggy `fsspec==2022.8.1` which has been YANKED on PyPI

### ISSUE THREAD

**Issue by lhoestq** [googlecolab/colabtools#3055]
**Describe the current behavior**

`fsspec==2022.8.1` is currently installed by default.
However this version is buggy and has been YANKED on PyPI.

For example running this code fails:
```python
import fsspec
f = fsspec.open("https://huggingface.co/datasets/lhoestq/test/resolve/main/some_text.txt").open()
f.read()
```

**Describe the expected behavior**

Colab should use the fixed version `fsspec==2022.8.2` to make `fsspec` work again.

**Additional context**

Link to a notebook that reproduces this issue:
https://colab.research.google.com/drive/19pieUj4-yw4jl278lxfoEqVMK8TyP5qZ?usp=sharing

cc @mariosasko

**Comment by cperry-goog** [comment]
Thanks for reporting! Tracked internally at b/245753804

Looks like we're going to miss tomorrow, so fix will be live Monday.

Workaround for now: `!pip install fsspec==2022.8.2`

**Comment by mayankmalik-colab** [comment]
`fsspec` is upgraded to `2022.8.2` and is live now.
