### ISSUE TITLE
ERROR: Package 'vsketch' requires a different Python: 3.7.13 not in '<3.11,>=3.8'

### ISSUE THREAD

**Issue by HaraldBerlin** [googlecolab/colabtools#3057]
I'm running it in Google Colab.

**Comment by mayankmalik-colab** [comment]
It seems like you are manually installing `vsketch` as this is not one of the preinstalled packages. We are on Python 3.7, but we will upgrade it soon. Hopefully, it should work once we are on Python `>=3.8`.

**Comment by HaraldBerlin** [comment]
Hello googlecolab/colabtools,

thanks for your reply! It seems to be not only me. Obviously no one can 
use this:

https://colab.research.google.com/github/marceloprates/prettymaps/blob/master/notebooks/examples.ipynb

I updated to Python 3.8 using the following 3 lines:

|!wget -O mini.sh 
https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.2-Linux-x86_64.sh 
!chmod +x mini.sh !bash ./mini.sh -b -f -p /usr/local |

Installation section runs then without errors. I restart the runtime. 
Unfortunately then the "Imports" section throws:

|ModuleNotFoundError: No module named 'prettymaps |

If I now click this link again
https://colab.research.google.com/github/marceloprates/prettymaps/blob/master/notebooks/examples.ipynb
suddenly all example maps run as expected without starting them 
manually. Unfortunately I always get errors: Running an own code 
section, changing the existing examples and I cannot even run them anew. 
Always errors like

|NameError: name 'plt' is not defined |

This is no fun.

Best regards / Mit freundlichen Grüßen / Meilleures salutations / 
Distinti saluti


      Harald Friedrich

Dipl.-Wirtsch.-Ing. (TU) / Industrial Engineer
CEO / Owner

Ing.-Büro FRIEDRICH




	+49 (0) 6659 919 444 <tel:+496659919444>, Fax: +49 (0) 6659 919 445 
<tel:+496659919445>

	Fuldaer Straße 20, DE-36124 Eichenzell

	***@***.*** ***@***.***>

	www.ibfriedrich.com <https://www.ibfriedrich.com>




Am 13.09.2022 um 01:37 schrieb mayankmalik-colab:

**Comment by cperry-goog** [comment]
Users upgrading Python in Colab is not supported; we're working on a 3.8 upgrade.

**Comment by HaraldBerlin** [comment]
Thank you for the information!

Best regards / Mit freundlichen Grüßen / Meilleures salutations / 
Distinti saluti


      Harald Friedrich

Dipl.-Wirtsch.-Ing. (TU) / Industrial Engineer
CEO / Owner

Ing.-Büro FRIEDRICH




	+49 (0) 6659 919 444 <tel:+496659919444>, Fax: +49 (0) 6659 919 445 
<tel:+496659919445>

	Fuldaer Straße 20, DE-36124 Eichenzell

	***@***.*** ***@***.***>

	www.ibfriedrich.com <https://www.ibfriedrich.com>




Am 15.09.2022 um 23:11 schrieb cperry-goog:

**Comment by metrizable** [comment]
Colab is now on Python 3.8 with #3246.

**Comment by HaraldBerlin** [comment]
Thanks a lot metrizable, it works! (Y)
