### ISSUE TITLE
simple_audio.ipynb is broken.  Says DNN library not found. 

### ISSUE THREAD

**Issue by RossMelbourne** [googlecolab/colabtools#3058]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mayankmalik-colab** [comment]
I am assuming you are referring to [simple_audio.ipynb](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/audio/simple_audio.ipynb) . I can see that it upgrades tensorflow in the initial `Setup` cell to the  newest available version. It may make our cudnn version incompatible.

Can you try the following: 
`!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2` . 

Note: It would require restarting your runtime.

The notebook ran just fine after the above change. Hopefully, it should work for you too.

**Comment by RossMelbourne** [comment]
Yes I was referring to simple_audio.ipynb: (https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/audio/simple_audio.ipynb) .
And yes, your suggestion worked! 
Thank you!

**Comment by markmcd** [comment]
Fixed in https://github.com/tensorflow/docs/commit/993919c737bd6a707cecb5e94c661d938b416a4a
