### ISSUE TITLE
error on initial install

### ISSUE THREAD

**Issue by CrazyBob48** [googlecolab/colabtools#3059]
New to this notebook install effort...
Got these error codes at the tail end of my install on MSI 17" laptop w/ i7 proc., RTX360 vid, 64GB ram and 2TB disk.

recent call last)
<ipython-input-8-3ded0168da05> in <module>
    416     render_interpolation(args, anim_args)
    417 else:
--> 418     render_image_batch(args)

Thanks in advance for help and thanks for the amazing software.

<ipython-input-4-9f5c14873646> in generate(args, return_latent, return_sample, return_c)
    399         sampler = PLMSSampler(model)
    400     else:
--> 401         sampler = DDIMSampler(model)
    402 
    403     model_wrap = CompVisDenoiser(model)

**Comment by mayankmalik-colab** [comment]
Can you elaborate on that and provide a minimal repro notebook?

**Comment by CrazyBob48** [comment]
Tracked it down to an error I made in selecting paths to save and find the files. Google Drive was misaddressed for file saving and model data access. Thanks for your response.
