### ISSUE TITLE
colabtools/google/colab/drive.py - is it possible to add readonly option

### ISSUE THREAD

**Issue by gaitskell** [googlecolab/colabtools#306]
For the colabtools/google/colab/drive.py - is it possible to add a readonly option when mounting the Google Drive? This would make it difficult for any "accidents" in the Python code to delete significant parts of the mounted Google Drive.

**Comment by fischman** [comment]
Thanks for the suggestion. We'll consider including an option for this in the future.

For now you can do this for yourself in notebook code e.g.:
`!mount -o ro,remount /<path>`
(substituting the path param you passed to `drive.mount()`)

If you did it right, then
`!mount|grep <path>`
should look like
`drive on <path> type fuse.drive (ro,nosuid,nodev,relatime,user_id=0,group_id=0)`
where the `ro` means "read-only".

**Comment by Telofy** [comment]
I have the same problem. First mount can’t find the drive executable, so I link it in `/bin`. But then I get this error:

```
!ln -s /opt/google/drive/drive /bin/drive
!mount -o ro,remount /content/drive
ERROR: Unknown command line flag 'o'
```
