### ISSUE TITLE
Unable to stop running cell after scrolling down into output

### ISSUE THREAD

**Issue by jobicarter** [googlecolab/colabtools#3068]
**Describe the current behavior**

The stop button that appears to the left of a running cell does not function when you've scrolled down into the cell output. 
Specifically, as you scroll down, after the stop button moves to float over the darker output area and is no longer on the ligher area next to the cell code, it stops functioning.

**Describe the expected behavior**

When you've scrolled down into the output zone you should be able to click the stop button to halt the cell execution without scrolling back up to the cell code. 

**What web browser you are using**

Chrome Version 105.0.5195.102 (Official Build) (arm64)

**Additional context**

Saved as a gist here:
https://colab.research.google.com/gist/jobicarter/accf6cef0f4610e6eb9fcd8e3bd74ecd/long-scroll-cant-stop-active-cell.ipynb

Or, reproducible in a single cell fresh notebook via:
```
# Run this cell
# Scroll down until the stop button leaves the lighter zone, and passes into/floats over the darker output zone
# Try to hit the stop button and it will not work
# Scroll back up till the stop button is in the light zone again
# Try to hit the stop button and it now works again
import time
print("-\n" * 500)
time.sleep(60)
```

**Comment by ragman-google** [comment]
Thanks for reporting! We're investigating this now.

Tracked internally at b/247858193.
