### ISSUE TITLE
New message followed by vram low error

### ISSUE THREAD

**Issue by lhucklen** [googlecolab/colabtools#3072]
Got this error

Input type (torch.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
An exception has occurred, use %tb to see the full traceback.

SystemExit: Using too much VRAM, lower your settings.

Also got this 
'trained_betas'} was not found in config. Values will be initialized to default values.
{'norm_num_groups'} was not found in config. Values will be initialized to default values.

This is using in painting mode

**What web browser you are using**
Safari

**Comment by cperry-goog** [comment]
You might want to contact the notebook or library author, doesn't look Colab specific.
