### ISSUE TITLE
!pip install is not working

### ISSUE THREAD

**Issue by Joshep1229** [googlecolab/colabtools#3075]
**Describe the current behavior**
Python Installer is not working (the output is '/bin/bash: pip: command not found')

**Describe the expected behavior**
It should install the pip packages

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 https://github.com/jsebastianquiroga/Big_Data_Derby_2022_SI/blob/main/Notebooks/Sistemas_Inteligentes.ipynb

Or simply you can execute the following code. 
from oauth2client.client import GoogleCredential

**Comment by colaboratory-team** [comment]
That notebook doesn't contain any pip commands, so I don't know where you saw the pip error. If you get into that state, deleting and getting a new runtime will restore pip to working order.

As for `from oauth2client.client import GoogleCredential`, the import is misspelled. It should be `from oauth2client.client import GoogleCredentials`, with an s at the end.
