### ISSUE TITLE
Colab terminate frequently “Your session crashed after using all available RAM” when it has NOT used all the RAM

### ISSUE THREAD

**Issue by pacificoceanmist** [googlecolab/colabtools#3076]
I was running the same code on GPU but Colab keeps terminating when it has NOT used all the RAM. I even hovered the mouse over the "RAM/Disc" bar to monitor how much RAM it uses through out the process but after 4/5GB it terminates my program. It was working smoothly a week ago (same code , same file size) but the past week it kept shutting off.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback and reference this issue.
