### ISSUE TITLE
Training freezes and do not end

### ISSUE THREAD

**Issue by maralthesage** [googlecolab/colabtools#3077]
This started happening last week on Friday. I tried to train my model and it stopped progressing in the middle of the first epoch.I thought it was a temporary bug so I left things for the weekend and now I am back trying to run my code, the same thing happened again but after 3 epochs it froze and did not proceed. I am using Colab Pro btw.

Also, I was able to choose my GPU with a code at the beginning of my notebook here is the code:
`gpu = !nvidia-smi -L
print(gpu[0])
assert any(x in gpu[0] for x in ['P100', 'V100'])`

Now, that doesn't work either and Tesla T4 is the only GPU I can use, which is fine, as long as it works.

Here is a link to the notebook:
https://colab.research.google.com/drive/124QcxRHBtEODHSDTcxBzp4tfcjqqqJZ4?usp=sharing

**Comment by maralthesage** [comment]
bug report

**Comment by cperry-goog** [comment]
The next time this happens can you file feedback in product and reference this issue? We can take more of a look on the backend, but without that info it's hard to troubleshoot what's going on.

**Comment by maralthesage** [comment]
Sure. is it enough to reference to this issue by using the issue number -> #3077 ?
