### ISSUE TITLE
localhost refused to connect

### ISSUE THREAD

**Issue by GH-Pablo** [googlecolab/colabtools#3079]
Hi! 

I'm trying to use a "folium.Map" on a Google Colab notebook but I'm getting the following error: **"localhost refused to connect"**.
I'd have expected to run a simple map on the Chrome browser, but this issue is holding me back.  

Can somebody help me, please? 

Thanks in advanced!
Best regards

![1](https://user-images.githubusercontent.com/104099279/191103903-a9e48854-005a-47f1-9a2c-d347965d4069.JPG)
![2](https://user-images.githubusercontent.com/104099279/191103911-a0c93d0e-a8f2-4ab8-89dc-1fe146a9f335.JPG)
![3](https://user-images.githubusercontent.com/104099279/191103918-060402c9-6ca7-4ec2-8397-a222245558c8.JPG)

**Comment by cperry-goog** [comment]
can you share a minimal repro notebook and share it broadly? we can take a look.
