### ISSUE TITLE
Input/Output Error - Colab

### ISSUE THREAD

**Issue by mnarasim** [googlecolab/colabtools#3084]
Trying to load images from a folder in google drive that has 150k plus images. Getting an Input/Output error, have 100GB storage capacity and have Colab Pro account. How do I fix. Read about quota limits, where would I go to increase my quota limit.

**Comment by cperry-goog** [comment]
https://research.google.com/colaboratory/faq.html#drive-timeout

You could try putting those in zip file in Drive, then unzipping directly onto the local storage in the runtime session.
