### ISSUE TITLE
Google drive is not mounting

### ISSUE THREAD

**Issue by bilalsoomro** [googlecolab/colabtools#309]
I have had no issues mounting my google drive but for some reason now it won't show up in the files tab on the left of the notebook. I am able to successfully mount my drive after entering my authorization code but nothing happens after that.

I also can't run the sample code of writing the text file to my drive. I've attached a screenshot. I tried to terminate the session and start a new one however the issue persists. Any help would be appreciated. Thanks!

![colab_issue](https://user-images.githubusercontent.com/8417115/47086927-69789a80-d223-11e8-8ca9-a153a9906fca.png)

**Comment by colaboratory-team** [comment]
If you've mounted at `/drive`, it's likely that the path to a file like `foo.txt` would be `/gdrive/My\ Drive/foo.txt`. 

Try confirming the contents of the `/drive` by running a cell with the code `!ls /gdrive`.

**Comment by bilalsoomro** [comment]
> If you've mounted at `/drive`, it's likely that the path to a file like `foo.txt` would be `/gdrive/My\ Drive/foo.txt`.
> 
> Try confirming the contents of the `/drive` by running a cell with the code `!ls /gdrive`.

Hi, I can read the contents of /gdrive. I also have added "My Drive" in the path now and that has worked too. Although, the drive folder is still now showing up in the files tab.

**Comment by colaboratory-team** [comment]
Try changing your mount path to `/content/drive` instead, and you should see the directory in the files tab.

**Comment by bilalsoomro** [comment]
> Try changing your mount path to `/content/drive` instead, and you should see the directory in the files tab.

That worked. Thanks for the help! :)
