### ISSUE TITLE
Google Drive error has occurred.

### ISSUE THREAD

**Issue by SynapticHorizons** [googlecolab/colabtools#3094]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
Everytime a Use Google Colab soon after running a model, I'll get a "Google Drive error has occurred." at the bottom of the screen. see attached jpg. Why do I keep getting this and how do I get the situation fixed?

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
I should always be able to use my Colab to run the various models without ever seeing "Google Drive error has occurred."

**What web browser you are using**
I'm using Google Chrome
![Google_Drive_Error_Has_Occured](https://user-images.githubusercontent.com/51413001/191968936-c614abc0-e05f-4d6c-9bd1-b27bf73814f1.jpg)

I saved a copy at GitHub Gist.
**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
Could you send feedback in product next time this happens and reference this issue? Thanks.
