### ISSUE TITLE
Cannot download datasets from tfds

### ISSUE THREAD

**Issue by markub3327** [googlecolab/colabtools#3095]
**Describe the current behavior**
Hi,

   I cannot download the dataset from TensorFlow Dataset. After ran the `dataset = tfds.load('celeb_a', shuffle_files=True)`, I got an error:

> Downloading and preparing dataset 1.38 GiB (download: 1.38 GiB, generated: 1.62 GiB, total: 3.00 GiB) to ~/tensorflow_datasets/celeb_a/2.0.1...
> Dl Completed...: 75%
> 3/4 [00:00<00:00, 7.22 url/s]
> Dl Size...: 100%
> 41713467/41713467 [00:00<00:00, 107426615.93 MiB/s]
> ---------------------------------------------------------------------------
> DownloadError                             Traceback (most recent call last)
> [<ipython-input-20-fccc868c06ea>](https://hfr6ufwutrd-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220921-060051-RC00_475785192#) in <module>
> ----> 1 dataset = tfds.load('celeb_a', shuffle_files=True, try_gcs=True)
>       2 dataset_train = dataset['train'].map(lambda data: (tf.cast(data['image'], tf.float32) - 127.5) / 127.5, num_parallel_calls=tf.data.AUTOTUNE)  # Normalize the images to [-1, 1]
>       3 dataset_test = dataset['test'].map(lambda data: (tf.cast(data['image'], tf.float32) - 127.5) / 127.5, num_parallel_calls=tf.data.AUTOTUNE)  # Normalize the images to [-1, 1]
>       4 dataset_val = dataset['validation'].map(lambda data: (tf.cast(data['image'], tf.float32) - 127.5) / 127.5, num_parallel_calls=tf.data.AUTOTUNE)  # Normalize the images to [-1, 1]
>       5 
> 
> 20 frames
> [/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/download/downloader.py](https://hfr6ufwutrd-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220921-060051-RC00_475785192#) in _assert_status(response)
>     305   if response.status_code != 200:
>     306     raise DownloadError('Failed to get url {}. HTTP code: {}.'.format(
> --> 307         response.url, response.status_code))
> 
> DownloadError: Failed to get url https://doc-0s-84-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/0gqpl0pqaskdpmmo5thjlpd7f4mc4hn9/1663954725000/13182073909007362810/*/0B7EVK8r0v71pZjFTYXZWM3FlRnM?e=download&uuid=d97d500c-3eaa-4754-a2cc-7c9b5600cb8d. HTTP code: 429.

**Describe the expected behavior**
I want to download the dataset successfully because I have Colab Pro.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Safari and Firefox, too

**Additional context**
```python
dataset = tfds.load('celeb_a', shuffle_files=True)
```

**Comment by mayankmalik-colab** [comment]
If possible, can you please share a minimal repro notebook?

**Comment by mayankmalik-colab** [comment]
It seems like `celeb_a` dataset not being accessible from tfds is a common issue and is not Colab specific. I think you'll have more luck searching on Stackoverflow or tensorflow github issues section.

**Comment by markub3327** [comment]
Thanks.
