### ISSUE TITLE
file not reading using pandas

### ISSUE THREAD

**Issue by Divyanshua1** [googlecolab/colabtools#3097]
mydata= pd.read_csv('C:\\Users\\User\\Downloads\\Module2AssignmentDataScience')
No such directory error but file exists in my laptop

**Comment by mco-gh** [comment]
Assuming you're using the default configuration of Colab, any file operations are carried out on the backend server supporting the notebook environment, which means they can't directly see or access anything on your laptop. One option would be store the file of interest in a publicly accessible place (assuming it doesn't contain any proprietary content) like Google Drive, Google Cloud Storage, S3, Dropbox, etc. and then pass the publicly readable URL to pd.read_csv(), which accepts a file path or a URL.

I'll close this now but feel free to re-open if I've missed the point.
