### ISSUE TITLE
Images not showing in Google Chrome

### ISSUE THREAD

**Issue by tyler-knowles** [googlecolab/colabtools#310]
I am not able to see images included (using sharable link from Drive) in my Colaboratory notebook in either of Safari or Chrome.  I can only see the images when I use Firefox.

**Comment by tyler-knowles** [comment]
I can see the images on the link you sent; the images that are not appear
for me and my collaborators are images in markdown.

**Comment by tyler-knowles** [comment]
It turns out that there was an issue with permissions/privacy settings.  I
and my collaborators are now able to see the diagrams in both Firefox and
Chrome; they are still not appearing in Safari.

**Comment by anmolter** [comment]
Has this been fixed? One of my colleagues can see images in the text when using Chrome, but not when using Safari.

**Comment by blois** [comment]
This should be fixed. Is there a specific notebook which is not working in Safari?

**Comment by tyler-knowles** [comment]
The issue has been resolved.  Thank you!

K

This message was composed on a mobile device.  Please pardon any typos and my brevity.
