### ISSUE TITLE
Not able to do copy paste 

### ISSUE THREAD

**Issue by sowmiyadharmalingam86** [googlecolab/colabtools#3103]
Not able to perform copy and paste operation

**Comment by colaboratory-team** [comment]
Does the issue still happen for you in incognito mode? If so, it may be due to a browser extension interfering. If you still see the issue, please share a video showing it, and share which browser version you are using

**Comment by jgwill** [comment]
I got that issue on Chrome on iOS, unable to paste.  
I have an older version of iOS (old iPhone, hopefully one day a more advanced one ;) )
I am pretty sure it's not the latest Chrome app because of the OS.  Still, would be nice if  that can be fixed :)
