### ISSUE TITLE
Unexpected behaviour while uploading file with the same name

### ISSUE THREAD

**Issue by abhijitdeepa** [googlecolab/colabtools#3107]
**Describe the current behavior**

When I try to upload a file having the same name, the object gets renamed and added to the collab's memory, but when I am accessing the object the old object is the one that is getting accessed. See the reproducing steps for more information.

**Describe the expected behavior**
I think The code in the _get_unique_filename()  function could be updated to fix the bug, by simply removing the spaces before the braces of the new file name. I believe its just a linux issue due to spaces.

**What web browser you are using**
Issue with google collab - happens on all browsers.

**Additional context**
Steps to Reproduce:
https://colab.research.google.com/notebooks/io.ipynb#scrollTo=vz-jH8T_Uk2c&line=3&uniqifier=1

In the above link try uploading a file with name whatever. Then try uploading another file with the same name whatever. Then  perform some operations on the image to see the bug. The new image is not being affected by the operations.

**Comment by cperry-goog** [comment]
We can't reproduce this, if you have consistent reproducible steps please re-open with a minimal notebook.
