### ISSUE TITLE
Proxies don't work in requests

### ISSUE THREAD

**Issue by KanamiHub** [googlecolab/colabtools#3111]
Hello colab community I have had a constant problem I need colab using requests to access a web page from my country but it is blocked for other countries, that's why I thought about using a proxy which is what I normally do, but the page gives this error :

/usr/local/lib/python3.7/dist-packages/socks.py in connect(self, dest_pair, catch_errors)
    785         try:
    786             # Initial connection to proxy server.
--> 787             super(socksocket, self).connect(proxy_addr)
    788 
    789         except socket.error as error:

KeyboardInterrupt:

This is my code:

import requests
proxy = "socks5://obisoftdevproxy.ydns.eu:8080"
web = requests.get("http://www.revpediatria.sld.cu/", proxies={"http":proxy,"https":proxy})

**Comment by cperry-goog** [comment]
We don't have any good ideas here, you may try asking on StackOverflow. Sorry.
