### ISSUE TITLE
please update chess library

### ISSUE THREAD

**Issue by m-f-h** [googlecolab/colabtools#3113]
**current behavior**
The  provided version of the `chess` package is obsolete -- IDK from what year but it is v1.4 or earlier while the current version is v1.9.3. In particular it lacks the very useful method `Board.outcome()` introduced in v1.5:
```>>> import chess
>>> chess.Board.outcome()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-25-c30b73f34a33>](https://localhost:8080/#) in <module>
----> 1 chess.Board.outcome()
AttributeError: type object 'Board' has no attribute 'outcome'
```

**Describe the expected behavior**
[According to the online documentation](https://python-chess.readthedocs.io/en/latest/core.html?highlight=pieces#chess.Board.outcome), `class Board` has method `outcome()` that yields the `Outcome` if the game has ended:
```>>> b=chess.Board()
>>> [b.push_san(m)for m in"f4 e5 g4 Qh4".split()]
>>> b.outcome()
Outcome(termination=<Termination.CHECKMATE: 1>, winner=False)
```

**What web browser you are using**
Chrome (but that'ss irrelevant),

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue:
https://colab.research.google.com/drive/14k2FHAZy4Kl1Lu8IvQW-T73pF-_kL6ga?usp=sharing

**Comment by mayankmalik-colab** [comment]
We will try to make an update soon. However, a workaround for now would be :

`
!pip uninstall python-chess
`
`
!pip install chess
`

**Comment by cperry-goog** [comment]
I didn't even know we had a chess library; we'll probably drop this from the base image soon, anyone can pip install whatever chess library they want!
