### ISSUE TITLE
IndexError 

### ISSUE THREAD

**Issue by YiMECP2** [googlecolab/colabtools#3114]
IndexError                                Traceback (most recent call last)
[<ipython-input-7-4f3f55b1da52>](https://localhost:8080/#) in <module>
     47 
     48 
---> 49 show_pdb(rank_num,show_sidechains, show_mainchains, color).show()
     50 if color == "lDDT":
     51   plot_plddt_legend().show()

[<ipython-input-7-4f3f55b1da52>](https://localhost:8080/#) in show_pdb(rank_num, show_sidechains, show_mainchains, color)
     20   model_name = f"rank_{rank_num}"
     21   view = py3Dmol.view(js='https://3dmol.org/build/3Dmol.js',)
---> 22   view.addModel(open(pdb_file[0],'r').read(),'pdb')
     23 
     24   if color == "lDDT":

IndexError: list index out of range

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
I think this is an AlphaFold problem, I'm flagging for them internally, but closing this here.
