### ISSUE TITLE
https://colab.research.google.com website fails to load

### ISSUE THREAD

**Issue by davidshumway** [googlecolab/colabtools#3115]
**Describe the current behavior**
About half of the time when booting the computer, the https://colab.research.google.com website fails to load. It usually loads again properly after restarting the machine. Other websites and google.com websites load as expected.

**Describe the expected behavior**

**What web browser you are using**
Firefox and Chrome

**Additional context**
Fedora Linux 33

**Comment by mco-gh** [comment]
Can you open Chrome Devtools and share the contents of the browser's JS console (and any errors in the network tab) when the page fails to load? That might give us a hint.

**Comment by RyuuOujiXS** [comment]
This git is not responsible for troubleshooting your access TO Colab, only your access WITHIN Colab. Call GeekSquad or something for general computer support.

**Comment by davidshumway** [comment]
> This git is not responsible for troubleshooting your access TO Colab, only your access WITHIN Colab. Call GeekSquad or something for general computer support.

From the readme:

> For any product issues, you can either [submit an issue](https://github.com/googlecolab/colabtools/issues) or "Help" -> "Send Feedback" in Colab.

The problem is intermittent and appears to go away after a few minutes. The website also doesn't load from the terminal (`$wget "https://colab.research.google.com"`). Every other google website loads fine.

**Comment by davidshumway** [comment]
> This git is not responsible for troubleshooting your access TO Colab, only your access WITHIN Colab. Call GeekSquad or something for general computer support.

Perhaps someone could clarify "product issue"?

**Comment by cperry-goog** [comment]
We'll need any errors you're seeing in the JS console; if you get those please reopen.
