### ISSUE TITLE
Incorrect rendering of display math environments in block quotes.

### ISSUE THREAD

**Issue by pazner** [googlecolab/colabtools#3118]
**Describe the current behavior**

The following example of a LaTeX display environment in a block quote does not render properly:
```
> This is a block quote
> $$
>     y = m x + b
> $$
> with an equation.
```

![image](https://user-images.githubusercontent.com/11493037/193874420-f91854b8-bacc-45af-8a60-704d689f6aa0.png)

**Describe the expected behavior**

It should render like this (this is how it is rendered with `jupyter nbconvert --to html`, in GitHub, VSCode, etc.):

![image](https://user-images.githubusercontent.com/11493037/193874225-ef1878f7-5d45-4993-b90f-69931c4faed9.png)

**What web browser you are using**

Tested in Safari and Chrome

**Additional context**

<details>
<summary>Notebook to reproduce</summary>

```
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "> This is a block quote\n",
    "> $$\n",
    ">     y = m x + b\n",
    "> $$\n",
    "> with an equation."
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

</details>

**Comment by cperry-goog** [comment]
Thanks for the report, fixing LaTeX rendering is always a struggle. Tracking internally at b/251566630

**Comment by corrieann** [comment]
This has been fixed.  Thanks!
