### ISSUE TITLE
standard use of the python `logging` module appears to be broken ... 

### ISSUE THREAD

**Issue by rayvoelker** [googlecolab/colabtools#3119]
**Describe the current behavior**
It appears as though the standard use of the logging module is broken, except for when invoking the `%%python` magic in the cell, before running the contents of the cell

**Describe the expected behavior**
It's expected that the logging module should write to a file when it's configured properly and as intended. 

It appears as though that this use of the the logging module (to create and save data to a file) had worked in the past but no longer does.

**What web browser you are using**
Firefox 

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
https://gist.github.com/rayvoelker/dd706c572b122b2ea58bddc35d5e5e4a

**Comment by mayankmalik-colab** [comment]
`basicConfig` configures the root logger and it doesn't work properly if there is already any handler present. So, can you try using your own logger like below. It should write to a file.
```
import logging
logger = logging.getLogger('my_logger')
formatter = logging.Formatter('%(name)s - %(levelname)s - %(message)s')
file_handler = logging.FileHandler('temp.log')
file_handler.setFormatter(formatter)
logger.addHandler(file_handler)

logger.warning('This will get logged to a file')
```
