### ISSUE TITLE
I have 95 compute units available (Colab Pro+ and canceled renewal), but cannot get a GPU

### ISSUE THREAD

**Issue by 2massive** [googlecolab/colabtools#3120]
**Describe the current behavior**
I am not allowed a GPU even though I paid for compute units. (I've since canceled because your Pro+ is just not valuable anymore, but I'm trying to use up my compute units.)

**Describe the expected behavior**
Able to start a Colab with a GPU using my compute units.

**What web browser you are using**
Brave

**Additional context**
Here's a screenshot showing I have compute units, but can't use a GPU.

![image](https://user-images.githubusercontent.com/115067300/194004461-9af94db8-0396-4038-aea2-2824b692af74.png)

 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by sonaterai** [comment]
Same here... :(

**Comment by sundog777** [comment]
same problem, with no real help or helpful ways to remedy. Looking into alternate services because this hasbeen ongoing from the beginning of the week. I have just susbsribed to the colab+ and for the money i'd expect some very fundamental things to be working for it to be worth it but not even the simplest of things are possible....

**Comment by sonaterai** [comment]
@sundog777  I am very interested if you find an interesting alternative solution, thank you

**Comment by cperry-goog** [comment]
Thanks for the report - we're rolling out a fix to this shortly

**Comment by cperry-goog** [comment]
The primary bug is resolved in prod now; do submit in-product feedback if you encounter other problems.
