### ISSUE TITLE
I have a PRO+ account+ drive, But I can't connect with GPU

### ISSUE THREAD

**Issue by masterinfo** [googlecolab/colabtools#3121]
I have a PRO+ account+ drive,
But I can't connect with GPU
since yesterday and cannot work !!!!

**Comment by sonaterai** [comment]
Same !! Can someone help us ?

**Comment by sundog777** [comment]
I posted this in another thread and they fixed the problem, but its come back! All i had was half a day, its a shame I expected more from a subscription like pro+

**Comment by cperry-goog** [comment]
If you're having trouble accessing a runtime, check your quota by opening a notebook, clicking on the arrow dropdown next to connect, and clicking on View resources.

If no compute units are listed, you've run out of quota. We recently made a change that gives you more visibility into your quota and allows you to utilize more Colab quickly as announced [here](https://blog.tensorflow.org/2022/09/colabs-pay-as-you-go-offers-more-access-to-powerful-nvidia-compute-for-machine-learning.html)

Your option is wait until your next recurrence or [purchase more compute units](https://colab.research.google.com/signup). Closing this: if you are not able to access a runtime and you have a compute unit balance, please submit feedback in product.
