### ISSUE TITLE
slow GPU for Pro account

### ISSUE THREAD

**Issue by leminhhuy132** [googlecolab/colabtools#3123]
i use pro account but you show me to use tesla T4 card? on par with a free account, it's unacceptable...
this has been going on all week along with blocking me from using GPU, time limit....

**Comment by cperry-goog** [comment]
Are you requesting premium GPU in runtime settings?

**Comment by leminhhuy132** [comment]
> Are you requesting premium GPU in runtime settings?

No. Compute unit too little. After the recent update, I almost stopped using colab pro. Not worth the money at all

**Comment by buoyrina** [comment]
True ! Sadly, i also stopped colab subscription.
