### ISSUE TITLE
import pandas fail:AttributeError: module 'pandas' has no attribute 'core'

### ISSUE THREAD

**Issue by ezhu17** [googlecolab/colabtools#3124]
import pandas fail:AttributeError: module 'pandas' has no attribute 'core'
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mco-gh** [comment]
Can you share a notebook, please, so we can try to reproduce this? A simple import pandas works fine for me so I must be missing some context.

**Comment by ezhu17** [comment]
Marc,

It works right now.
Thank you

Emily
