### ISSUE TITLE
Kernel keeps crashing in a specific line 

### ISSUE THREAD

**Issue by djgarayb** [googlecolab/colabtools#3125]
Hi,
My Colab session keeps crashing when I run the following line from the package scripy 
ir.tl.clonotype_network(adata, min_cells=2) 

Previously running just fine and now it crashes every time I run it with exactly the same data and tutorial data too. I made a copy of the notebook in a new folder and it ran correctly once after that kept getting the same issue. Session crashing.  

Error:
<html>
<body>

Oct 6, 2022, 10:42:41 AM | WARNING | WARNING:root:kernel ba0c94bc-3e56-4676-b49d-83aa5b1a375b restarted
-- | -- | --
Oct 6, 2022, 10:42:41 AM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Oct 6, 2022, 10:42:40 AM | WARNING | src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7f82050
Oct 6, 2022, 10:42:02 AM | INFO | Kernel restarted: ba0c94bc-3e56-4676-b49d-83aa5b1a375b

</body>
</html>

Using Google Chrome

**Comment by cperry-goog** [comment]
We'd need a minimal repro notebook to investigate; my suspicion is this is an issue with the library.

**Comment by djgarayb** [comment]
Hi,
I was trying to reproduce this notebook https://scverse.org/scirpy/latest/tutorials/tutorial_3k_tcr.html and it was working perfectly fine. However, it has been crashing for the last few days every time I run the line 
21: ir.tl.clonotype_network(adata, min_cells=2) 
This happens with my data too. 
Greatly appreciate any advice

**Comment by djgarayb** [comment]
I already tried different version of scirpy and didn't help. I have run the tutorial data using my laptop and it worked with no problem at all, however when I try in Colab it keeps crashing, exactly the same error, the session crashes and the kernel is restarted. So that makes me think it is a problem with Colab.
