### ISSUE TITLE
Stable Baselines 3 Import Gym Issue -- 'Entrypoint'

### ISSUE THREAD

**Issue by Nyquistro** [googlecolab/colabtools#3127]
I'm currently running Stable baselines 3 (SB3) on Colab. Everything was going well until today. I has to reset the runtime for Colab. Once I installed SB3, Colab failed to import gym. I receive the error "AttributeError: 'EntryPoints' object has no attribute 'get'"

Not sure what is going on here

- I install this with no problem:

pip install stable_baselines3

- Then proceed to install gym

import gym

Error Log:

AttributeError                            Traceback (most recent call last)
[<ipython-input-9-299cce7fe7d2>](https://localhost:8080/#) in <module>
      2 import os
      3 import json
----> 4 import gym
      5 from gym import Env, spaces
      6 from gym.spaces import Dict, Discrete, Box

2 frames
[/usr/local/lib/python3.7/dist-packages/gym/__init__.py](https://localhost:8080/#) in <module>
     11 )
     12 from gym.spaces import Space
---> 13 from gym.envs import make, spec, register
     14 from gym import logger
     15 from gym import vector

[/usr/local/lib/python3.7/dist-packages/gym/envs/__init__.py](https://localhost:8080/#) in <module>
      8 
      9 # Hook to load plugins from entry points
---> 10 _load_env_plugins()
     11 
     12 

[/usr/local/lib/python3.7/dist-packages/gym/envs/registration.py](https://localhost:8080/#) in load_env_plugins(entry_point)
    248 def load_env_plugins(entry_point="gym.envs"):
    249     # Load third-party environments
--> 250     for plugin in metadata.entry_points().get(entry_point, []):
    251         # Python 3.8 doesn't support plugin.module, plugin.attr
    252         # So we'll have to try and parse this ourselves

AttributeError: 'EntryPoints' object has no attribute 'get'

**Comment by colaboratory-team** [comment]
Your issue repros for me. Installing stable_baselines3 downgrades gym to from 0.25.* to 0.21, which is indeed what stable_baselines3 pins it to in their [setup.py](https://github.com/DLR-RM/stable-baselines3/blob/master/setup.py). This seems to be the version that is throwing the error you see.

If you run `!pip installl stable_baselines3 gym==0.25.2`, it will keep gym at the current pre-installed version. You get a package incompatibility warning, but it also allows gym to import properly. Hopefully doing that will unblock you for now, but this might be worth filing an issue with the stable_baselines3 project

**Comment by Nyquistro** [comment]
Thank you for getting back so quickly, that solved the issue. I'll be sure to let SB3 know about this issue.
