### ISSUE TITLE
I bought 100 compute units to have more RAM. Nevertheless, my session crashes "After using all available RAM" and offers me to buy PRO subscription with the same amount of compute units. What is going on?

### ISSUE THREAD

**Issue by nighstaggerer** [googlecolab/colabtools#3129]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
Looks like you're hitting a standard promo when a non-Pro/Pro+ user hits an OOM error. You'll want to adjust your approach to use less memory, or upgrade to Pro/Pro+ for highmem runtimes.
