### ISSUE TITLE
Error. Keras load_model

### ISSUE THREAD

**Issue by vithmel** [googlecolab/colabtools#313]
I trained model and saved it to google drive with the ModelCheckpoint callback
After that I ran the`load_model(path)` and got an error:

	`TypeError: '<' not supported between instances of 'dict' and 'float'`

I tried to save with  `model.save()`. The result was the same.

I repeated these actions several times assuming that an error might have occurred while writing to the Google disk, but the result was the same.

I also saved directly to disk in colab
`model.save ('./model.h5')` - result the same.

Then I downloaded the model to my computer and ran `load_model(path)`, the error was different:
	`Unknown initializer: GlorotUniform`

My tensorflow version is 1.11.0
Keras version is 2.1.6-tf

Colab tensorflow version:  1.12.0-rc1
Colab  Keras version: 2.1.6-tf

May be this is tensorflow new version bug?

I trained models before and everything was fine. The last time was 3 days ago.

**Comment by vithmel** [comment]
I tried to load my another model, and everything works fine. 
**Sorry** may be something wrong with my model.

**Comment by craigcitro** [comment]
No worries -- closing for now, but do re-open if you have a consistent and self-contained repro.
