### ISSUE TITLE
Can't connect to a premium GPU

### ISSUE THREAD

**Issue by Eitanaso** [googlecolab/colabtools#3132]
**Describe the current behavior**
Trying to connect to a premium GPU, I get a popup saying: Failed to assign a backend. No premium GPU backend available. Would you like to use a standard GPU?

It's been 3 days that this has happened.

**Describe the expected behavior**
Connect to a premium GPU to keep running my code.

**What web browser you are using**
Firefox

**Additional context**
I paid for the colab pro subscription last month (12 september), and read the FAQ. If it's something about my account or about the compute units (which I don't fully understand) I would like if I had some explanaition.

**Comment by zsaid01** [comment]
i have the same problem they allways send me this message 
![image](https://user-images.githubusercontent.com/106558023/194640208-c3080fec-20a7-4cd0-8273-b224481907bd.png)
what are the limitations ?

**Comment by hocinekaddourdrizi** [comment]
i have the same problem  since 3 last day With the colab pro + subscription

**Comment by xz-ding** [comment]
I'm having the same issue since today. Also, I can no longer check my computing credit balance anymore (this info is no longer displayed in the "resource" tab or the "choose the Colab plan" page.

**Comment by caosmagnvm** [comment]
Oh okay. I thought it was only me. Basically, I don't even have access to background elaboration anymore. I'm with Colab Pro+

**Comment by LeonardoBerti07** [comment]
I'm with colab pro+ and I can't access GPU since 3/4 days. I don't think I will renew the subscription.

**Comment by atanumandal0491** [comment]
Have anybody found the option to select Premium GPU?

**Comment by LeonardoBerti07** [comment]
Do u guys know where i can find resource monitoring, to view the calculation units used?

**Comment by Great-Bucket** [comment]
Same problem.  I have colab pro+ and get 

"Failed to assign a backend
no premium GPY backend available..."

**Comment by fernando-zalles** [comment]
I have Colab Pro subscription. This is happening to me too for a few days now. Just some days before the issue, I noticed some changes and I was even able to use a powerful GPU I was never been assigned before, thought it was a general upgrade, butnow I can't connect to a GPU

**Comment by shiro102** [comment]
I also have that issue and I have Colab Pro subscription.

**Comment by peyman-alv** [comment]
Same problem. I paid for the subscription of Colab Pro a few days ago and I get "No premium GPU backend available. Would you like to use a standard GPU?".

**Comment by 202000130132** [comment]
I paid for the Colab pro and on the first day it was ok, I got connected with an A100, and that was also the last time, I have to use Tesla T4 evertime. I feel like being played

**Comment by RubberSoul-l** [comment]
Yep, only being able to use the premium GPU on my first day, afterthat, no longer being able to select the premium GPU

**Comment by vivresursonnuage** [comment]
Have been facing the same issues for several day. I am on a Colab Pro+ subscription.

**Comment by 202000130132** [comment]
I think I found the reason... The usage was limited to 100 unit for Colab pro user, check the rest resource left.I used it up in one night... I used it for the first time and I don't know it could be used so fast. 万恶的资本家！
![image](https://user-images.githubusercontent.com/95836162/196681342-9c99f918-562f-49f0-b930-83b4ada42866.png)

**Comment by cperry-goog** [comment]
If you're having trouble accessing a runtime, check your quota by opening a notebook, clicking on the arrow dropdown next to connect, and clicking on View resources.

If no compute units are listed, you've run out of quota. We recently made a change that gives you more visibility into your quota and allows you to utilize more Colab quickly as announced [here](https://blog.tensorflow.org/2022/09/colabs-pay-as-you-go-offers-more-access-to-powerful-nvidia-compute-for-machine-learning.html)

Your option is wait until your next recurrence or [purchase more compute units](https://colab.research.google.com/signup). Closing this: if you are not able to access a runtime and you have a compute unit balance, please submit feedback in product.

**Comment by zsaid01** [comment]
Same deal here 😊😊

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zehuicao** [comment]
I paid Cloab Pro from 15/Oct to 15/Nov, however,  "You are subscribed to Colab Pro+
You currently have zero compute units available. Resources offered free of charge are not guaranteed. Purchase more units"

**Comment by ManoniLo** [comment]
I made Colab-Pro subscription more than one and half year ago.
Same message since yesterday: "You currently have zero compute units available. Resources offered free of charge are not guaranteed. Purchase more units".
That's very annoying!

**Comment by louisefz** [comment]
Ridiculous. I created two pro+ accounts to run out all units within two days. Very expensive to pay for additional cumputing units for students.

**Comment by ManoniLo** [comment]
Colab has completely changed its resources assignment policy. Since some months ago you've had good performance PCI100 GPU with Colab Pro subscription. Now you have even faster premium GPUs but you run out of Colab Pro units in about 10 hours.  This is taking advantage of people.

**Comment by Mahdi-Hasan** [comment]
Again I have also faced this trap. When I had computing units colab assigned me A100. Then my computing units finished. Now colab is offering Tesla T4. What the hell policy is this. Even they don't clearly said about this types of heinous activity.

**Comment by Mahdi-Hasan** [comment]
In colab pro:

**Comment by agusjanardana** [comment]
Lol, i just purchased collab pro today and got the same issues, idk what this policy was, i thought ill get better performance than I want. Running some of my research 4 hours, and got notifications about computing units. So basically, if my computing units go down to zero, it'll automatically make my account as a free collab? what da hell is that... very very not recommended for student....
![image](https://user-images.githubusercontent.com/62202561/228318620-4820c31e-44a5-4fd1-a945-38ab73a08e10.png)

**Comment by ManoniLo** [comment]
By using A100  I've run out of computing units in approximately 1 day of work!
That's totally unacceptable and shameful by Colab.
I recommend to switch to other tools/platforms.

**Comment by atanumandal0491** [comment]
> 

Hi, I used to work on google colab + versions. but after the issues I shifted to Paperspace Gradient. It is good. but the only issue is that it gives 6 hours of connectivity and again reconnects.  The good thing is that you can select from various GPUs. 

This is my referral code: https://console.paperspace.com/signup?R=XXUH2CC
