### ISSUE TITLE
Colab breaks when I try to load a file from a drive folder with thousands of files

### ISSUE THREAD

**Issue by DavidHarar** [googlecolab/colabtools#3133]
Hello, 
I am working with Colab (pro+ but I don't think it matters), and I try to load some data from a drive folder that contains thousands of examples (about 500K). Every time I try to do so, Colab crushes. 

I attached a screenshot of the error message that I get. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54071003/194646350-87323b26-8717-4271-b590-bd7df9573904.png">

**Comment by mco-gh** [comment]
From the [Colab FAQ](https://research.google.com/colaboratory/faq.html#resource-limits):

> Why does drive.mount() sometimes fail saying "timed out", and why do I/O operations in drive.mount()-mounted folders sometimes fail?link
> Google Drive operations can time out when the number of files or subfolders in a folder grows too large. If thousands of items are directly contained in the top-level "My Drive" folder then mounting the drive will likely time out. Repeated attempts may eventually succeed as failed attempts cache partial state locally before timing out. If you encounter this problem, try moving files and folders directly contained in "My Drive" into sub-folders. A similar problem can occur when reading from other folders after a successful drive.mount(). Accessing items in any folder containing many items can cause errors like OSError: [Errno 5] Input/output error. Again, you can fix this problem by moving directly contained items into sub-folders.
> Note that "deleting" files or subfolders by moving them to the Trash may not be enough; if that doesn't seem to help, make sure to also [Empty your Trash](https://support.google.com/drive/answer/2375102#permanent).

**Comment by DavidHarar** [comment]
Thanks for the answer, what a bummer..

**Comment by xiyichen** [comment]
@mco-gh What should I do then in case of input/output error? If I want to move some files at the top level into the sub folders, I still need to access them using commands like 'mv' or shutil library functions in python, but colab isn't allow me to do that, and mannually sub-folding them in drive is way too slow for hundreds of thousands of files...

**Comment by mco-gh** [comment]
> If I want to move some files at the top level into the sub folders, I still need to access them using commands like 'mv' or shutil library functions in python

One option would be to use [Google Drive for Desktop](https://blog.google/products/drive/drive-for-desktop/), which mirrors your Drive contents onto your local disk. Then you can rearrange your folders using local mv commands and let the built-in sync tool mirror your local changes to Drive.
