### ISSUE TITLE
resolved

### ISSUE THREAD

**Issue by conru** [googlecolab/colabtools#3137]
**Describe the current behavior**

When click "set seed", I get:

NameError                                 Traceback (most recent call last)
[<ipython-input-14-75cc44456028>](https://localhost:8080/#) in <module>
      1 #@markdown Can set random seed here for reproducibility.
----> 2 g_cuda = torch.Generator(device='cuda')
      3 seed = 52362 #@param {type:"number"}
      4 g_cuda.manual_seed(seed)

NameError: name 'torch' is not defined

=====

When click "Run for generating images", I get:

NameError                                 Traceback (most recent call last)
[<ipython-input-13-e351c3f9efae>](https://localhost:8080/#) in <module>
      9 width = 512 #@param {type:"number"}
     10 
---> 11 with autocast("cuda"), torch.inference_mode():
     12     images = pipe(
     13         prompt,

NameError: name 'autocast' is not defined

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mayankmalik-colab** [comment]
I am assuming the issue is resolved now as the title name change suggests.
