### ISSUE TITLE
Keep getting this crap

### ISSUE THREAD

**Issue by Vissceraimages** [googlecolab/colabtools#3138]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-12-55664aaf2f73> in <module>
   1481   manager.eval_settings()
   1482   # make images
-> 1483   Manager.Diffusion.Runner.run(manager.colab.settings)

4 frames
/usr/local/lib/python3.7/dist-packages/PIL/Image.py in open(fp, mode)
   2841 
   2842     if filename:
-> 2843         fp = builtins.open(filename, "rb")
   2844         exclusive_fp = True
   2845 

FileNotFoundError: [Errno 2] No such file or directory: '/content/CodeFormer/results/temp_0.8/final_results/temp.png'-
Please read the guidelines for filing an issue first.

https://github.com/googlecolab/colabtools/wiki/Bug-Reports
-->

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
You'll need to share a minimal repro notebook, or contact the notebook author if it's not your own code.
