### ISSUE TITLE
Colab Pro can not use GPU after 2 hours training

### ISSUE THREAD

**Issue by Harly-1506** [googlecolab/colabtools#3139]
I was disconnected by google colab, then I couldn't use the GPU. The detail is that during the training, the GPU disconnected after 2 hours of training and Colab informed me that the GPU usage was exhausted.

Please help me how to fix this error

**Comment by domarquez** [comment]
me too

**Comment by cperry-goog** [comment]
If you're having trouble accessing a runtime, check your quota by opening a notebook, clicking on the arrow dropdown next to connect, and clicking on View resources.

If no compute units are listed, you've run out of quota. We recently made a change that gives you more visibility into your quota and allows you to utilize more Colab quickly as announced [here](https://blog.tensorflow.org/2022/09/colabs-pay-as-you-go-offers-more-access-to-powerful-nvidia-compute-for-machine-learning.html)

Your option is wait until your next recurrence or [purchase more compute units](https://colab.research.google.com/signup). Closing this: if you are not able to access a runtime and you have a compute unit balance, please submit feedback in product.
