### ISSUE TITLE
[BUG] Colab PRO+ usage limits are DIABOLICAL after you launched PAYG ... This requires and URGENT fix please... it's been 10 days already!

### ISSUE THREAD

**Issue by lordcalder** [googlecolab/colabtools#3140]
I have been a Colab PRO+ subscriber for 3 or 4 months, and I used to get my 24 hours uninterupted usage almost every day, until you launched your PAYG service about 10 days ago. Ever since that launch, I have not been able to connect to a premium GPU, and in fact have only been allowed 3 hours usage in total over the past 10 days, on T4's, before being disconnected by Colab... What is going on?

I have subsequently cancelled my PRO+ subscription as this is actually now WORSE than the free service... 

Can you fix it please? Then I will re-subscribe, however I am already £45 out of pocket this month, paying for a service which does not exists.

**Comment by lordcalder** [comment]
![image](https://user-images.githubusercontent.com/105490895/194883264-9319190f-e8f9-4855-93c5-fd1d987e50d4.png)

Have had this issue EVERY DAY since your PAYG service launch... not once had this before that

**Comment by lordcalder** [comment]
![image](https://user-images.githubusercontent.com/105490895/194883456-20133bfa-42db-492c-99a4-359bd1f5491b.png)

I then get this after clicking Connect... I have only been 'allowed' 3 hours usage in the past 10 days, none of it on premium GPU's

**Comment by lordcalder** [comment]
![image](https://user-images.githubusercontent.com/105490895/194884732-c6135545-6430-45d8-83b3-5d8258cf03b9.png)

**Comment by lordcalder** [comment]
![image](https://user-images.githubusercontent.com/105490895/194885169-64ca05ba-d1a3-4ce0-bac2-3527e512b750.png)

**Comment by cperry-goog** [comment]
We are not planning any changes to the model at this time.

**Comment by lordcalder** [comment]
I am not asking you to change the model, I am saying that YOU HAVE CHANGED THE MODEL and subsequently I cannot connect to the premium service that I am paying for

Sent from the Galaxy
________________________________

**Comment by lordcalder** [comment]
> We are not planning any changes to the model at this time.

I am not asking you to change the model, I am saying that **I am not asking you to change the model, I am saying that YOU HAVE CHANGED THE MODEL and subsequently I cannot connect to the premium service that I am paying for** and subsequently I cannot connect to the premium service that I am paying for. 

This is a serious issue, and I would like a refund please.
