### ISSUE TITLE
Blocked GPU connection for TensorFlow versions older than 2.5

### ISSUE THREAD

**Issue by esgomezm** [googlecolab/colabtools#3141]
**Describe the current behavior**
When I use TensorFlow versions < 2.5, I cannot connect to the GPU (`tf.test.gpu_device_name()` is empty)

**Describe the expected behavior**
TensorFlow 2 is not that old and I would expect to still have the chance to work with it in Colab

**What web browser you are using**
Chrome, Firefox, Safari. It happens with all of them.

**Comment by cperry-goog** [comment]
We don't support older versions of Tensorflow sadly
