### ISSUE TITLE
gpu

### ISSUE THREAD

**Issue by domarquez** [googlecolab/colabtools#3144]
You cannot currently connect to a GPU due to usage limits in Colab. [Learn more](https://research.google.com/colaboratory/faq.html#usage-limits)

why ? i have pro , and i cant use gpu 

please ..

**Comment by Harly-1506** [comment]
SAME PROBLEMS

**Comment by cperry-goog** [comment]
If you're having trouble accessing a runtime, check your quota by opening a notebook, clicking on the arrow dropdown next to connect, and clicking on View resources.

If no compute units are listed, you've run out of quota. We recently made a change that gives you more visibility into your quota and allows you to utilize more Colab quickly as announced [here](https://blog.tensorflow.org/2022/09/colabs-pay-as-you-go-offers-more-access-to-powerful-nvidia-compute-for-machine-learning.html)

Your option is wait until your next recurrence or [purchase more compute units](https://colab.research.google.com/signup). Closing this: if you are not able to access a runtime and you have a compute unit balance, please submit feedback in product.
