### ISSUE TITLE
i want creat an video,but always this?

### ISSUE THREAD

**Issue by 2681218185** [googlecolab/colabtools#3149]
RuntimeError                              Traceback (most recent call last)
[<ipython-input-19-954efe6185e8>](https://localhost:8080/#) in <module>
     56     if process.returncode != 0:
     57         print(stderr)
---> 58         raise RuntimeError(stderr)
     59 
     60     mp4 = open(mp4_path,'rb').read()

RuntimeError: b'ffmpeg version 3.4.11-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers\n  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)\n  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared\n  libavutil      55. 78.100 / 55. 78.100\n  libavcodec     57.107.100 / 57.107.100\n  libavformat    57. 83.100 / 57. 83.100\n  libavdevice    57. 10.100 / 57. 10.100\n  libavfilter     6.107.100 /  6.107.100\n  libavresample   3.  7.  0 /  ...

**Comment by 2681218185** [comment]
![%CZL8A_QCIB75)UX2N`K8UJ](https://user-images.githubusercontent.com/115358359/195605736-27f4b857-dc47-4380-96c3-bc963989e39b.png)

**Comment by cperry-goog** [comment]
can you leave comments on #3150 and we can diagnose there
