### ISSUE TITLE
Provide IDE features via JupyterLab or shell into NB container

### ISSUE THREAD

**Issue by cwbeitel** [googlecolab/colabtools#315]
Currently colab makes it easy to launch a shareable, GPU- or TPU-backed notebook environment. The product offers numerous benefits relative to stock Jupyter notebooks.

A key part of the ML development lifecycle is the browsing, editing, and running of files and commands from the command line.

Indeed shell commands can be run from notebooks (via the !command or %%bash\ncommand syntax) but this approach feels velocity- / cognitively-limiting compared to a multi-windowed IDE environment when working on complex problems (i.e. it's fine if you're just pip installing something).

Also indeed developers could shell into their notebook VM or mount a volume or Google Drive through other means but this is of course more complicated than simply opening a browser page and can become a distraction if each of these need to be reset each time a user's connection is reset.

Proposing either (1) the more complex undertaking of making the colab environment provide the IDE features of JupyterLab or (2) to provide the means for users to connect to the instances backing their colab notebooks (such as via a dropdown that displays a command that can be copied and pasted into a terminal) whereby they can get access to vim and shells in the notebook container.

**Comment by colaboratory-team** [comment]
Thanks for the feedback. I'm going to close this issue since we aren't using GitHub to track large-scale UX feature work of this sort, but we do appreciate the value of having a more IDE-like experience and are considering many of these features as part of future work.
