### ISSUE TITLE
what should i do?

### ISSUE THREAD

**Issue by 2681218185** [googlecolab/colabtools#3150]
![5RLFY42`)(5E3W9E35SG LE](https://user-images.githubusercontent.com/115358359/195607360-382b38fa-b149-4860-8415-4c6b8e727e0a.png)

**Comment by 2681218185** [comment]
> We would need to see the error message to provide commentary; my suspicion is you'll need to contact the notebook author.

![image](https://user-images.githubusercontent.com/115358359/195993345-893f61de-5fe5-4e54-b32f-cc0f8296741a.png)

**Comment by cperry-goog** [comment]
I don't think this is unique to Colab; appears you're hitting an ffmpeg error, you might have more luck asking on StackOverflow
