### ISSUE TITLE
julia bug, initial cell allwas pops up

### ISSUE THREAD

**Issue by theodorosP** [googlecolab/colabtools#3151]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by colaboratory-team** [comment]
We'll need more information to help, can you share a public, minimal notebook that shows the issue you're having?

**Comment by theodorosP** [comment]
Every single time I try to type something in a cell, the initial cell pops up on the side, preventing me even to type something. When I try to type the cursor moves to the right. I have tried many times to close this cell (the one on the right) but whenever I click on a cell it still gives me the same issue. This is happening the last hour

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by theodorosP** [comment]
I am sharing google notebook here. Try to run the first cell and then go to the next one. I am not even able to type more that 5-6 letters before the cursor move on the side cell. I tried to close it by selecting close tabs or close all tabs. It seems that it's not working

https://colab.research.google.com/github/ageron/julia_notebooks/blob/master/Julia_Colab_Notebook_Template.ipynb#scrollTo=GIeFXS0F0zww

**Comment by corrieann** [comment]
A screenshot might help to let us know what you mean by "right cell".

If the cell that you're referring to is actually a tab that is titled "Resources" then you have a browser plugin or something else running that's issuing a click on the connect button.
