### ISSUE TITLE
Issues with shared drives, files, and Colab.

### ISSUE THREAD

**Issue by charleyjoinwaterlily** [googlecolab/colabtools#3152]
I work on a Macbook and have been using Colab to clean files on a shared drive with the company I work for. 

Issues:
1. The files I am cleaning are not reflecting the changes I make in Colab. However, these changes can be seen by the admin of the folder.
2. If the admin uploads a folder and gives me shared permissions as "content manager" in the shared drive, I have "read only" permissions in Colab for accessing the folder and files within.

Is there a solution that will allow me to view the changes I make on Colab in our files?

**Comment by cperry-goog** [comment]
1. I don't understand this -> the changes are shown to the admin, so where are they not being reflected?
2. Have you tried other permissions?

**Comment by charleyjoinwaterlily** [comment]
1. After running the code in Colab, my boss, the admin, can view the sorted and renamed files. However, I can not track the progress or download the altered folder because the files are unchanged in my view of the folder and drive. 
2. We tried different permissions on the shared drive, folder, and document to make sure it was not an issue of sharing permissions.

**Comment by mco-gh** [comment]
Can you share a sample notebook (or fragment thereof) and a list of steps required to reproduce the problem?
