### ISSUE TITLE
Deleted code in colab forms on mobile platforms

### ISSUE THREAD

**Issue by levi223** [googlecolab/colabtools#3153]
Problem:
When accessing a notebook on an mobile phone that contains a collapsed form, the code that was previously in the cell with the form gets deleted. This is only in the case when opening the form the code from the form is collapsed and is consistent through chrome, firefox and IE. I would expect this code to not dissapear. I have found that this behaviour only occurs for the owner of the notebook and not when other google accounts access it through a share link.

**Comment by ragman-google** [comment]
I was unable to reproduce this bug. Can you share a notebook that we can clone to try and repro it? Thanks!

**Comment by levi223** [comment]
> I was unable to reproduce this bug. Can you share a notebook that we can clone to try and repro it? Thanks!

I have included a colab with instructions
https://colab.research.google.com/drive/1TmDZBIJbf0GRHiH1W0ERb1FOwn__rGnx?usp=sharing

**Comment by cperry-goog** [comment]
Thank you for the report! We're tracking this internally at b/254731251

**Comment by ragman-google** [comment]
We think we've fixed the bug!

Can you give it a try, let us know if you're still running into it? Thank you!

**Comment by levi223** [comment]
The problem seems to be resolved in my tests. Thank you for your effort!

**Comment by ragman-google** [comment]
Thanks for verifying!
