### ISSUE TITLE
GPU Session resetting and deleting my current session without me doing anything.

### ISSUE THREAD

**Issue by wes-kay** [googlecolab/colabtools#3156]
**Describe the current behavior**
Unable to keep gpu session active, the session seems to delete itself and I'm unable to run my code after downloading my trained models. I'm a PRO account user as well.

**Describe the expected behavior**
This was fully working before the pay as you go model was introduced. 
I download some pre trained models and load them into the session, including all the python modules I need. I then manually edit 2 files in the folder system (tab bar) save, then the next step fails silently when I try and run my python code:

`
import os
from os import walk
import glob
from google.colab import drive
drive.mount('/content/drive')
`

Sometimes I'm able to link my drive to the session but other times it just fails and deletes my session without any warnings.

**What web browser you are using**
Chrome

**Comment by cperry-goog** [comment]
Can you submit feedback in product and refer to this issue? Hard to tell what's going on here.

**Comment by sebbov** [comment]
For posterity, in-product feedback revealed you invoked `kill` to terminate all processes in the runtime, including critical services. Disconnects and subsequent execution errors are expected in that case.

**Comment by wes-kay** [comment]
> For posterity, in-product feedback revealed you invoked `kill` to terminate all processes in the runtime, including critical services. Disconnects and subsequent execution errors are expected in that case.

```
for model in models:
  for img in glob.glob("/content/drive/MyDrive/*.png", recursive=True):
    doModel(img, model, '/content/prompts.txt')

!kill $(ps aux | awk '{print $2}')
```

Not when there's a double for loop that should be iterated over first.
