### ISSUE TITLE
Simple multiprocessing with spawn start method get stuck

### ISSUE THREAD

**Issue by tl-yang** [googlecolab/colabtools#316]
[Link To NoteBook](https://colab.research.google.com/drive/1ffzW3BD1S0HzVf0jtTLlERUiq6nAxIV8)  

The following code is extracted from the [Python documentation](https://docs.python.org/3.6/library/multiprocessing.html#contexts-and-start-methods)

``` python 
import multiprocessing as mp 
  
def foo(q):
    q.put('hello')

if __name__ == '__main__':
    ctx = mp.get_context('spawn')
    q = ctx.Queue()
    p = ctx.Process(target=foo, args=(q,))
    p.start()
    print(q.get(5))
    p.join()
```
It'll get stuck on the ```print(q.get(5))``` line. However, the **fork** start method will run without the issue.

This piece of code run normally on my local python3.6 machine. 

It looks like a bug to me. Does CoLab support multiprocessing currently? 

Here is the stack trace when forcefully stop the execution 
```
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-8-12a0f58d3db4> in <module>()
     14     p = ctx.Process(target=foo, args=(q,))
     15     p.start()
---> 16     print(q.get(5))
     17     p.join()

/usr/lib/python3.6/multiprocessing/queues.py in get(self, block, timeout)
     92         if block and timeout is None:
     93             with self._rlock:
---> 94                 res = self._recv_bytes()
     95             self._sem.release()
     96         else:

/usr/lib/python3.6/multiprocessing/connection.py in recv_bytes(self, maxlength)
    214         if maxlength is not None and maxlength < 0:
    215             raise ValueError("negative maxlength")
--> 216         buf = self._recv_bytes(maxlength)
    217         if buf is None:
    218             self._bad_message_length()

/usr/lib/python3.6/multiprocessing/connection.py in _recv_bytes(self, maxsize)
    405 
    406     def _recv_bytes(self, maxsize=None):
--> 407         buf = self._recv(4)
    408         size, = struct.unpack("!i", buf.getvalue())
    409         if maxsize is not None and size > maxsize:

/usr/lib/python3.6/multiprocessing/connection.py in _recv(self, size, read)
    377         remaining = size
    378         while remaining > 0:
--> 379             chunk = read(handle, remaining)
    380             n = len(chunk)
    381             if n == 0:

KeyboardInterrupt: 
```

**Comment by craigcitro** [comment]
The problem here is that the spawned subprocess can't find `__main__.foo`.

One (less than perfect) option is to put the code in a separate file, eg make a new directory and add it to the path:

    !mkdir mptest
    import sys
    sys.path.insert(0, 'mptest')

then write the code to a new file:

    %%writefile mptest/sample.py
    import multiprocessing as mp 
    
    def foo(q):
      q.put('hello')

Once you do, the code above (with a tweak to the import) will work fine:

    import sample
    
    ctx = mp.get_context('spawn')
    q = ctx.Queue()
    p = ctx.Process(target=sample.foo, args=(q,))
    p.start()
    print(q.get(5))
    p.join()

**Comment by goncharom** [comment]
Hi! I'm having a similar issue with ML-agents, @tl-yang were you able to fix your problem in other way or did you follow @craigcitro steps? Is there a simpler way to fix this?
Thanks in advance!
