### ISSUE TITLE
Unable to mount GDrive with custom GCE VM

### ISSUE THREAD

**Issue by CptCaptain** [googlecolab/colabtools#3163]
**Describe the current behavior**
When connected to a custom GCE VM, mounting my Google Drive fails with `KeyError: 'TBE_EPHEM_CREDS_ADDR'`.

**Describe the expected behavior**
Colab should be able to mount the drive so I can access my data.

**What web browser you are using**
Chrome

**Additional context**
This code works as expected when connected to a hosted runtime, but fails when using a custom GCE VM.
The VM in question has been created from a colab template.
```
from google.colab import drive
drive.mount('/content/datasets')
```

**Comment by cperry-goog** [comment]
This isn't supported right now unfortunately, I'd recommend looking into pydrive.
