### ISSUE TITLE
My colab project can't connect anymore

### ISSUE THREAD

**Issue by gj026621** [googlecolab/colabtools#3164]
**Describe the current behavior**
My colab project can't connect anymore, so I can't run my code.

**Describe the expected behavior**
I expect my project to connect so that I can run my code as before.

**What web browser you are using**
Chrome

**Additional context**
https://colab.research.google.com/drive/1_jor2J4qYv9Um9SnPzjoKjPZGfkOgwyy?usp=sharing

**Comment by mayankmalik-colab** [comment]
Are you still not able to connect to the runtime? I am able to connect successfully using the shared notebook. I am wondering if that was some intermittent issue.

**Comment by gj026621** [comment]
It works now... thank you.
