### ISSUE TITLE
OSError: Error no file named model_index.json found in directory 

### ISSUE THREAD

**Issue by DjTecmo** [googlecolab/colabtools#3170]
This eror occurs on the first cell of "Inference" section
If the solution to this is "accelerate config" , How do i do that? where's or how?
-I use Google chrome

**Comment by mco-gh** [comment]
I suspect the "accelerate config" is related to [this script](https://github.com/huggingface/accelerate) but this is really a notebook content issue, not a question about colab functionality.

**Comment by cperry-goog** [comment]
Closing as seems not specific to Colab

**Comment by DjTecmo** [comment]
i didn't know it wouldn't be a colab functionality, thank yu!

**Comment by DjTecmo** [comment]
> Closing as seems not specific to Colab

How is this not specific to colab if this damn fuk error just happens to me on the COLAB. You are not even helpful
