### ISSUE TITLE
Can't connect Colab to a custom GCE VM after stopping and starting the instance

### ISSUE THREAD

**Issue by NolifeM** [googlecolab/colabtools#3173]
**Describe the current behavior**
I'm using colab on GCE and need to restart the instance sometimes. Most of the time, it works fine.

I restarted it earlier today and found that I can not connect Colab to GCE.

So I connected to the instance in bash and found some info might be useful.

I found out that there were only 2 docker container running, normally there should be 3 of them. 

The datalab:baked one was down, and restart the instance won't solve the problem.

Then I tried to run the image manually, and I got these outputs:

![image](https://user-images.githubusercontent.com/10100253/197112638-578a0f29-8d83-4648-bf43-cfd075f5a5e4.png)

It seems to be a [socket](socket.error: [Errno 99] Cannot assign requested address) problem.

And I tried systemctl status k_default.service and get these:

![image](https://user-images.githubusercontent.com/10100253/197116764-2ebb128e-0735-4668-868e-ea84d9294943.png)

So it seems for some reason, restarting the VM will cause address assignment problem.

Currently I have no idea how to fix it. Please help me.

The same problem was reported by tomchify and other guys.

**What web browser you are using**
Chrome

**Comment by cperry-goog** [comment]
Thanks for doing all of this digging, we've got this tracked internally at b/255975693 and someone is looking.

**Comment by NolifeM** [comment]
> Thanks for doing all of this digging, we've got this tracked internally at b/255975693 and someone is looking.

Thanks, I'm glad to be helpful.
Is there any chance that restarting VM won't automaticlly stop docker containers, and causing images broke? Since the image for colab is a big one. Those 2 smaller containers worked fine.

**Comment by mco-gh** [comment]
Hi, I'm looking at this now. A few quick findings and questions:

1. I'm assuming you're using the [Marketplace Colab VM](https://research.google.com/colaboratory/marketplace.html), is that correct?
2. I tried rebooting via `sudo reboot` and the system recovered completely (all three containers restarted and notebook reconnected). I understand it's not easily reproducible so not too surprising. How are you restarting your VM?
3. When I try the command you used to restart the datalab:baked container I get the same error, but for me it's because this command is running a new instance and the socket is already held by the already running version. I assume you did a `docker ps` to verify the datalab container is not running?
5. Weirdly, when I run `systemctl status` I see `Active: inactive (dead)` despite my containers working as expected, but maybe that's a red herring. The error you saw from systemctl is more interesting and potentially incriminating.
6. In your `systemctl status` screenshot, I can't see the end of the `ExecStart=/usr/bin/docker` line, which should show an exit code. Can you share that? (I'm guessing it's status=125, which is aggregated later but would be nice to know)
7. What happens if you manually restart the service (`sudo systemctl start k_default.service`)?

**Comment by mco-gh** [comment]
Another thought - try `docker ps -a` to see stopped containers. I tried seeing the log from a stopped container with `docker logs <container-id>` but, sadly, that produced `Error response from daemon: configured logging driver does not support reading` - probably it's locked down for security reasons. If we can figure out how to work around that, it might reveal something useful.

**Comment by NolifeM** [comment]
> Hi, I'm looking at this now. A few quick findings and questions:
> 
> 1. I'm assuming you're using the [Marketplace Colab VM](https://research.google.com/colaboratory/marketplace.html), is that correct?
> 2. I tried rebooting via `sudo reboot` and the system recovered completely (all three containers restarted and notebook reconnected). I understand it's not easily reproducible so not too surprising. How are you restarting your VM?
> 3. When I try the command you used to restart the datalab:baked container I get the same error, but for me it's because this command is running a new instance and the socket is already held by the already running version. I assume you did a `docker ps` to verify the datalab container is not running?
> 4. Weirdly, when I run `systemctl status` I see `Active: inactive (dead)` despite my containers working as expected, but maybe that's a red herring. The error you saw from systemctl is more interesting and potentially incriminating.
> 5. In your `systemctl status` screenshot, I can't see the end of the `ExecStart=/usr/bin/docker` line, which should show an exit code. Can you share that? (I'm guessing it's status=125, which is aggregated later but would be nice to know)
> 6. What happens if you manually restart the service (`sudo systemctl start k_default.service`)?

Hi, thanks for your great work, and here's what I found yet:

1. Yes, I'm using the Makretplace Colab VM.

2. Before I met this problem, I usually restart and stop the VM via the buttons on Google Cloud VM Instances panel. And they worked fine most of the time. And yeah  it's not easily reproducible. 

Now, I'll first stop all the docker containers via Cloud Shell, and then stop the VM via panel, so far so good, no mistake.

3. I restarted the broken VM and :
![image](https://user-images.githubusercontent.com/10100253/199572694-e42404ad-3fe6-453a-b3d4-12fd270f3058.png)

then i used: `docker run -it gcr.io/colab-datalab/datalab:baked /bin/bash`
![image](https://user-images.githubusercontent.com/10100253/199572910-fd9c306c-31dc-4388-a177-270fd4cb3e93.png)

So yes, I'm sure there're only 2 containers running and datalab:baked still unrunnable.

4. I run `systemctl status`, and here're what I got: 
![image](https://user-images.githubusercontent.com/10100253/199573439-4c432aa3-f46f-4291-93f0-4745146e60ce.png)
![image](https://user-images.githubusercontent.com/10100253/199573476-4884d209-2362-4c12-9d97-373a0feae0b8.png)

5.  Yes, it's  status=125.
![image](https://user-images.githubusercontent.com/10100253/199574512-463b531a-b6cc-436f-abc3-2387c95d745e.png)

6. I got the info in 5 after running `sudo systemctl start k_default.service`

7. I got the same `Error response from daemon: configured logging driver does not support reading`
![image](https://user-images.githubusercontent.com/10100253/199575535-efa9401e-e759-4399-8838-723124484bc1.png)

**Comment by mco-gh** [comment]
I tried to use `lsof` to find out which, if any, process is hanging onto the addr/port we're failing to open but the Google Container Optimized OS doesn't have `lsof `and doesn't let you install packages. :)

So I used `netstat` to find an inuse port and then tried to open it like this:
```
$ python -m http.server --bind localhost 4000
...
OSError: [Errno 98] Address already in use
```
Note this is different from the error you are seeing, which is "Cannot assign requested address". I assume this is why the container is failing to start, as well as your manual starts.

It seems like something has changed your VM's network config such that you can't open the desired addr/port (which I think in this case is localhost/8080). Can you try this:
```
$ python -m http.server --bind localhost 8080
```

**Comment by mco-gh** [comment]
Also, `netstat -i` output might be helpful.

**Comment by NolifeM** [comment]
> I tried to use `lsof` to find out which, if any, process is hanging onto the addr/port we're failing to open but the Google Container Optimized OS doesn't have `lsof `and doesn't let you install packages. :)
> 
> So I used `netstat` to find an inuse port and then tried to open it like this:
> 
> ```
> $ python -m http.server --bind localhost 4000
> ...
> OSError: [Errno 98] Address already in use
> ```
> 
> Note this is different from the error you are seeing, which is "Cannot assign requested address". I assume this is why the container is failing to start, as well as your manual starts.
> 
> It seems like something has changed your VM's network config such that you can't open the desired addr/port (which I think in this case is localhost/8080). Can you try this:
> 
> ```
> $ python -m http.server --bind localhost 8080
> ```

It seems my 8080 port is free.

![image](https://user-images.githubusercontent.com/10100253/199888095-a0e45a06-ae22-4580-833c-85350dfc0a95.png)
![image](https://user-images.githubusercontent.com/10100253/199888137-5eebd1de-8ec6-4863-9000-83c4b6986ba3.png)

After that I tried `systemctl start k_default.service` again and got the same failed result as I done before.

Yes I have tried rebooting the VM,

Is it possible that sometimes reboot or shutdown the VM without stopping the docker containers would broken the images? I have no idea how do docker containers actually work.

**Comment by NolifeM** [comment]
Well, something new just happened minutes ago. 

I got another totally healthy VM,  I have rebooted or stopped it many times and it worked fine.

But today I started it and colab give me `Unable to connect to the runtime.` 

So I checked in Clould Shell, all 3 containers are running.

It's fine cause I have data backup, but it's still really confused.

**Comment by NolifeM** [comment]
I start a brand new VM via Marketplace Colab VM, and check the status:

![image](https://user-images.githubusercontent.com/10100253/199910813-87d3a81a-a13e-4555-a536-4149cdd62424.png)

It's working, so I guess it's something wrong with the k_default.service, but not the docker containers.

**Comment by mco-gh** [comment]
This has been resolved, please re-open if it recurs.

**Comment by NolifeM** [comment]
> This has been resolved, please re-open if it recurs.

Thx a lot ;D
