### ISSUE TITLE
Can't access to Google colab that I have created.

### ISSUE THREAD

**Issue by garraww** [googlecolab/colabtools#3178]
I write a code on Google, some days after when I come back to the file it demand my own permission to open the Google colab code. I receive a email to accept the permission but it still ask me a permission. I'm like on a loop where I can't access my code. Does someone can help me with this issues? I am on chrome. @
![Screenshot_20221021-201251_(1)](https://user-images.githubusercontent.com/106212771/197307260-53a73d35-f9a5-4f3a-93d1-fd319bbb5117.png)

**Comment by mco-gh** [comment]
Do you have multiple gmail logins, by any chance? It almost sounds like the login that's active in the browser window in which you're trying to access the notebook is different from the gmail account which is receiving the authorization requests.

If that might be the problem, I'd suggest using Chrome's incognito mode to make sure you're logged into the Google account you used to save the notebook in Drive.

**Comment by garraww** [comment]
Yes i try it but i got the same issue with a different error code  
![image](https://user-images.githubusercontent.com/106212771/197345502-37ea8a80-55e5-4b76-b3a7-0bddffadcc9d.png)

**Comment by mco-gh** [comment]
Is this correct?
- You login to colab with a gmail account.
- Save a notebook in Google Drive.
- Using the same gmail account, you can't open the notebook in Colab.

Is that it? Are you using a Google Workspace account, by any chance?

**Comment by garraww** [comment]
yes I was using a workspace that was suddenly deleted. I think the file had been delete in the same time

**Comment by mco-gh** [comment]
Ok, that would explain it then, right? I'd suggest speaking to your Workspace admin.

**Comment by garraww** [comment]
Yes, thanks you.
