### ISSUE TITLE
NOP's Basic Staple Diffusion v0.52 (1.4 Weights) - Not working

### ISSUE THREAD

**Issue by mtosc64** [googlecolab/colabtools#3179]
tried Cleanup button - does not work

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-1-802d11622d2c>](https://localhost:8080/#) in <module>
   1481   manager.eval_settings()
   1482   # make images
-> 1483   Manager.Diffusion.Runner.run(manager.colab.settings)

2 frames
[/usr/local/lib/python3.7/dist-packages/diffusers/utils/outputs.py](https://localhost:8080/#) in __getitem__(self, k)
     86         if isinstance(k, str):
     87             inner_dict = {k: v for (k, v) in self.items()}
---> 88             return inner_dict[k]
     89         else:
     90             return self.to_tuple()[k]

KeyError: 'sample'

**Comment by mayankmalik-colab** [comment]
We can have a look if you can share a minimal repro notebook.
