### ISSUE TITLE
Restarting runtime doesn't clear execution order indicator on code cells.

### ISSUE THREAD

**Issue by eikonomega** [googlecolab/colabtools#318]
Hi All,
I've noticed that when you `Restart runtime...` it doesn't clear the execution order indicator.

POST RESTART "Still has a [1] execution order indicator"
<img width="403" alt="image" src="https://user-images.githubusercontent.com/415939/47398102-8c61ed80-d700-11e8-831c-2da1ca29209c.png">

If you `Reset all runtimes...` this clears as expected, but I'd prefer not to have to restart all runtimes in various notebooks to clear the output/execution order of a single notebook.

Thank as always!

**Comment by blois** [comment]
Thanks for the report, this should be fixed in an upcoming release.

**Comment by eikonomega** [comment]
@blois Awesome! Thanks so much.
