### ISSUE TITLE
rpy2 is outdated

### ISSUE THREAD

**Issue by lgautier** [googlecolab/colabtools#3180]
**Describe the current behavior**

rpy2 installed by default is an outdated version of rpy2 (3.4.5).

```python
import rpy2
rpy2.__version__
```

**Describe the expected behavior**

The code above returns 3.5.5.

**What web browser you are using**

Firefox.

**Additional context**

https://colab.research.google.com/drive/1pepfsZT8Zak_IxbH3XYxofUAogGkUn4c?usp=sharing

**Comment by bdwaldie** [comment]
It looks like r2py has been updated to the latest version, but after the update I am unable to run any commands using cell magic. 

Running the following in a new notebook: 

%load_ext rpy2.ipython

%%R
x <- seq(0, 2*pi, length.out=50)
x

Returns this error:

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
[<ipython-input-2-cc2a3aca7f04>](https://localhost:8080/#) in <module>
----> 1 get_ipython().run_cell_magic('R', '', 'x <- seq(0, 2*pi, length.out=50)\nx\n')

8 frames
<decorator-gen-122> in R(self, line, cell, local_ns)

[/usr/local/lib/python3.7/dist-packages/rpy2/robjects/conversion.py](https://localhost:8080/#) in _py2rpy(obj)
    240     raise NotImplementedError(
    241         "Conversion 'py2rpy' not defined for objects of type '%s'" %
--> 242         str(type(obj))
    243     )
    244 

NotImplementedError: Conversion 'py2rpy' not defined for objects of type '<class 'str'>'

-------------------------------------------------------------------------------------------------------

Here is a link to a notebook with the code above that shows the error.
https://colab.research.google.com/drive/1digJ6kwHEu7192lEN15qtDz0-ccdSJXG?usp=sharing

**Comment by serjisa** [comment]
I have the same issue as @bdwaldie has

**Comment by lgautier** [comment]
This is similar to this issue report: https://github.com/rpy2/rpy2/issues/952.

The issue was fixed upstream but Colab has not updated Jupyter related dependencies:

**Comment by lgautier** [comment]
This is reported in #3206. I suggest to close this issue and continue there.

**Comment by lgautier** [comment]
I opened an issue to upgrade `ipykernel`: https://github.com/googlecolab/colabtools/issues/3212
