### ISSUE TITLE
What did happen to the output?

### ISSUE THREAD

**Issue by antonio-mastropaolo** [googlecolab/colabtools#3182]
It's a while since we have had this annoying behavior in which no progression is reported when training or testing models such as T5.  Has anyone ever managed to fix it?

<img width="1486" alt="Screenshot 2022-10-24 at 11 14 35" src="https://user-images.githubusercontent.com/77482585/197491793-0fb333d2-09f6-4da5-a9a7-d317a264d3ba.png">

**Comment by cperry-goog** [comment]
Can you share a minimal repro notebook?
