### ISSUE TITLE
Julia is not working in Colab. Nothing responds.

### ISSUE THREAD

**Issue by theodorosP** [googlecolab/colabtools#3184]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by theodorosP** [comment]
After running the first cell, I am not able to run Julia even if I update my web page.

https://colab.research.google.com/github/ageron/julia_notebooks/blob/master/Julia_Colab_Notebook_Template.ipynb#scrollTo=EEzvvzCl1i0F

**Comment by theodorosP** [comment]
![ask](https://user-images.githubusercontent.com/83337690/197638911-a53d335f-179a-493a-98e1-2490872558f5.png)

**Comment by mayankmalik-colab** [comment]
Duplicate of #3200

**Comment by metrizable** [comment]
I was able to execute the julia install cell, refresh the page, and run additional julia cells, including installing other packages (see #3391). Can you provide any additional details?

**Comment by metrizable** [comment]
I believe this is a duplicate of #3391 or #3200.
