### ISSUE TITLE
Grafic Pause

### ISSUE THREAD

**Issue by iansuzano** [googlecolab/colabtools#3185]
** venho comentar rapidamente pra dizer que o Grafico não pausa ele duplica elemento no Colab, coisa que acontece de boa em outros software, da uma ajuda ai se alguém souber resolver isso

**ele duplica o gráfico ao invés de atender gráfico dinâmico**
mesma coisa

**To usando Google Chrome **
(Chrome, Firefox, Safari, etc.)

**Tava fazendo meu Gráfico Dinâmico e não foi, não sei o motivo**

**Comment by mayankmalik-colab** [comment]
We like to plot the graph and replicate the issue first. Can you please share a repro notebook.
