### ISSUE TITLE
Nvidia Update error in FFMPEG 

### ISSUE THREAD

**Issue by GenoXu** [googlecolab/colabtools#3187]
Nvenc encoder in FFMPEG is not supported anymore by Colab!
It worked just fine 3 days ago, but now it throws this error whenever I try any FFMPEG version newer than `3.4.1.1` (Default):

```
 [hevc_nvenc @ 0x55defbb87c00] Using device cuda0 (type cuda) with hevc_nvenc encoder.
 [hevc_nvenc @ 0x55defbb87c00] Loaded Nvenc version 11.0
 [hevc_nvenc @ 0x55defbb87c00] Driver does not support the required nvenc API version. Required: 11.1 Found: 11.0
 [hevc_nvenc @ 0x55defbb87c00] The minimum required Nvidia driver for nvenc is 470.57.02 or newer
 [hevc_nvenc @ 0x55defbb87c00] Nvenc unloaded
```

I tried updating the NVIDIA driver, but it's stucked at `460.32.03`

Please consider updating the drivers..

**Comment by cperry-goog** [comment]
Can you share a minimal repro notebook?

**Comment by GenoXu** [comment]
https://colab.research.google.com/drive/1626hsamSBtU13eXiGXDwf0-75CSgEPvz?usp=sharing

**Comment by mco-gh** [comment]
Thanks, I was able to reproduce this, having a look at what happened here.

**Comment by GenoXu** [comment]
No prob, and [this](https://forums.developer.nvidia.com/t/solved-driver-does-not-support-the-required-nvenc-api-version/49948/3) is why I suggested updating the drivers..

**Comment by craigcitro** [comment]
It looks like we need an NVidia driver update on our side; we're working on it, but it's behind a few other in-flight tasks.

Internal tracking: b/246637277

**Comment by Raimund58** [comment]
It would be amazing to get updated GPU drivers. 
It would help me with Blender.
We can currently not use the A100s

**Comment by GenoXu** [comment]
Now, all FFMPEG versions before [Auto-Build 2022-11-30](https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2022-11-30-12-36) works.
Thank you.
