### ISSUE TITLE
Add a small widget to hide all notebook inputs

### ISSUE THREAD

**Issue by michaellee8** [googlecolab/colabtools#319]
Is it possible to just hide all inputs by just pressing a button. I actually made a javascript snippet for it. Just do some `style=“display:none”` things. I hope that it can be done without hassling the developer console.
Is it possible to be done by some good python api?

**Comment by metrizable** [comment]
@michaellee8 Thanks for filing the request. In the `View` menu, you can toggle "Show/hide code" and in each cell menu, under "Form" you can select "Hide form".
