### ISSUE TITLE
Support Python 3.11 by default

### ISSUE THREAD

**Issue by johnnynunez** [googlecolab/colabtools#3190]
Yeah! Python 3.11 support please. It should be the default.
Python 3.11 is between 10-60% faster than Python 3.10. On average, we measured a 1.25x speedup on the standard benchmark suite. See Faster CPython for details.
https://docs.python.org/3.11/whatsnew/3.11.html
https://www.phoronix.com/news/Python-3.11-Released

Benchmark https://www.phoronix.com/review/python-311-performance

**Comment by mayankmalik-colab** [comment]
We are working on Python upgrade, along with some other imp features. We will be more consistent with upgrades going forward.

**Comment by RyuuOujiXS** [comment]
#2615 You're so original, it's uncanny

**Comment by adamjstewart** [comment]
PyTorch doesn't even support Python 3.11 yet. 3.10 is more realistic.

**Comment by johnnynunez** [comment]
> PyTorch doesn't even support Python 3.11 yet. 3.10 is more realistic.

PyTorch is support python 3.11 partially. The problem is that torchvision among other libraries are blocked from updating because they depend on anaconda (which has already expressly said that it is working on adding python 3.11), since there are libraries like libpng that are in anaconda and torchvision makes use of them.

**Comment by adamjstewart** [comment]
Ah true, it's supported on Linux, which is all we really care about. I still think the second most recent minor version is a better default. That's what package managers like Conda/Homebrew/Spack default to.

**Comment by adamjstewart** [comment]
TensorFlow does not yet support 3.11, which Google is probably more concerned about 😆

**Comment by johnnynunez** [comment]
> Ah true, it's supported on Linux, which is all we really care about. I still think the second most recent minor version is a better default. That's what package managers like Conda/Homebrew/Spack default to.

<img width="965" alt="Screenshot 2023-01-17 at 23 45 59" src="https://user-images.githubusercontent.com/22727137/213028810-3e312c5e-d10e-4692-bfc7-4e4270792152.png">

https://pytorch.org/blog/PyTorch-1.13-release/
It's on PyTorch documentation.

**Comment by johnnynunez** [comment]
> TensorFlow does not yet support 3.11, which Google is probably more concerned about 😆

if you look at the issues the next version will already be compatible.

**Comment by johnnynunez** [comment]
@mayankmalik-colab Python 3.11 is out in anaconda
https://github.com/ContinuumIO/anaconda-issues/issues/13082#issuecomment-1386874942

```
conda create -n py311 python=3.11
```

**Comment by earlev4** [comment]
> We are working on Python upgrade, along with some other imp features. We will be more consistent with upgrades going forward.

Hi @mayankmalik-colab. Is there any status on the Python upgrade and/or other improved features. Thanks so much!

**Comment by ZetiMente** [comment]
Hi! It is now December and would love to have Python 3.11 in Colab? 
Is this in the works to be released soon or is there an easy way for me to upgrade on my own?
Thanks!

**Comment by ChristopherEeles** [comment]
Any updates on this? Python 3.10 is pretty old now.

**Comment by cameronraysmith** [comment]
Maybe we should imagine we need to help users migrate to [Project IDX](https://idx.dev/) to get this support going forward.

**Comment by ZetiMente** [comment]
wen!?

**Comment by jhamman** [comment]
@metrizable, @mayankmalik-colab, @cperry-goog - Much of the Scientific Python ecosystem (numpy, scipy, etc.) will start dropping support for Python 3.10 this quarter based on [Spec 0000](https://scientific-python.org/specs/spec-0000/). Perhaps this is the time to bump Colab to 3.11?

**Comment by EvanWiederspan** [comment]
We will be updating to Python 3.11 in early January, see https://github.com/googlecolab/colabtools/issues/4935
