### ISSUE TITLE
Can not access GPU after purchasing Colab Pro +

### ISSUE THREAD

**Issue by SantoshGuptaML** [googlecolab/colabtools#3197]
I just purchased Colab Pro +, but I am not able to access a GPU backend. It says that 

"Cannot connect to GPU backend
You cannot currently connect to a GPU due to usage limits in Colab. [Learn more](https://research.google.com/colaboratory/faq.html#usage-limits)
To get more access to GPUs, consider purchasing Colab compute units with [Pay As You Go](https://colab.research.google.com/signup?utm_source=dialog&utm_medium=link&utm_campaign=gpu_assignment_failure)."

I clicked up Pay As You Go but the page just confirms that my current plan is already Colab Pro + and that I have 500 compute units. 

I have refreshed the page, and created new notebooks, but whatever I do, it does not connect to a GPU back end. 

I also don't seem to have access to back ground execution when I select change run type.

**Comment by Randy1435** [comment]
Okay so hear me out, you won't have as much control as you think. Now k just want you to go to runtime -> runtime settings, or something similar I don't know. Then set GPU class to premium

**Comment by SantoshGuptaML** [comment]
False alarm. I had my work google account open for colab pro and when I clicked on the link to purchase colab pro, it switched to my default non-work account for the purchase. I didn't notice I wasn't using my work google account to make the purchase.

**Comment by SantoshGuptaML** [comment]
False alarm. I had my work google account open for colab pro and when I clicked on the link to purchase colab pro, it switched to my default non-work account for the purchase. I didn't notice I wasn't using my work google account to make the purchase.
