### ISSUE TITLE
cuda 10.1 missing (you broke it again)

### ISSUE THREAD

**Issue by eyaler** [googlecolab/colabtools#3198]
cuda 10.1 was once installed on colab and it is now missing from its previous location at /usr/local/cuda-10.1 thus yet again breaking all colabs relying on this feature, and yet again with no heads up, fallback or explanation. maintaining colabs is getting to be too much of a hassle.

**Comment by craigcitro** [comment]
Info about package updates has started landing in https://github.com/googlecolab/backend-info, always slightly in advance of the changes going live; https://github.com/googlecolab/backend-info/commit/408a635bf5101ca27ce55a2f0c7f2841cea41bd2 is the commit that removed some of our old CUDA versions.
