### ISSUE TITLE
Th file downloaded from the file browser is incomplete

### ISSUE THREAD

**Issue by Borrk** [googlecolab/colabtools#320]
Those days after training I tried to download the saved model(h5py) file, I always get an truncated file.
for example, the file is 150M, but the downloaded one is about 40M. 

I don't know why, I couldnot download a complete file the past week, which is really awful.

![image](https://user-images.githubusercontent.com/40885503/47493455-cf13f900-d8ab-11e8-8d14-746c6a1a08e5.png)

**Comment by blois** [comment]
How are you downloading the file?

**Comment by Borrk** [comment]
sorry for not providing the details. as the screenshot, I save files at current work folder, then right click one to download it.

![image](https://user-images.githubusercontent.com/40885503/47525228-32784800-d8f9-11e8-848f-a618adc3423a.png)

**Comment by blois** [comment]
Thanks for the report, I can also repro with a file generated as:

```
!dd if=/dev/urandom of=sample.txt bs=1M count=150
```

**Comment by colaboratory-team** [comment]
This has been fixed for a bit. Please do reopen if the issue recurs.
