### ISSUE TITLE
Julia installation problem in Colab

### ISSUE THREAD

**Issue by theodorosP** [googlecolab/colabtools#3200]
I am facing a problem installing Julia in colab. I am using the official site but it seems that everyday I get a different error. 
The problem comes when Julia packages have to be installed, in the shell script, the issue comes in this line: JULIA_PACKAGES="$JULIA_PACKAGES
I am also attaching a screenshot.

![error](https://user-images.githubusercontent.com/83337690/199163797-1878650d-96a2-4040-8c47-c2efcec4ac8f.png)

![error_1](https://user-images.githubusercontent.com/83337690/199164719-8ad8b40d-ca6e-4aa1-a36

![error2](https://user-images.githubusercontent.com/83337690/199164723-772cc150-89cd-472b-8c8a-7cc10f85f22b.png)
5-1cea91213e08.png)

Please not that I am using the official site of colab for Julia:

https://colab.research.google.com/github/ageron/julia_notebooks/blob/master/Julia_Colab_Notebook_Template.ipynb#scrollTo=GIeFXS0F0zww

It's almost 10 days now that there is an issue with Julia. Is there any way to be fixed?

**Comment by mayankmalik-colab** [comment]
It seems like there have have been a few commits 2 days back to fix the installation issue in the repo you mentioned. I just did the installation myself and it works fine. 

I also would like to mention that the above repo is not an official one and seems like a private repo.

**Comment by theodorosP** [comment]
Thanks for the reply. Please refer in this bug which is the most updated.

https://github.com/googlecolab/colabtools/issues/3204
