### ISSUE TITLE
 Cannot import name 'rank_zero_only' from 'pytorch_lightning.utilities.distributed'

### ISSUE THREAD

**Issue by inessieulle** [googlecolab/colabtools#3202]
I am using VQGAN+CLIP_(Zooming)_(z+quantize_method_with_addons).ipynb Google Repository and when I click the cell "Loading of libraries and definitions"

It sent an error :

ImportError                               Traceback (most recent call last)
<ipython-input-6-fe8fafeed45d> in <module>
     24 from omegaconf import OmegaConf
     25 from PIL import Image
---> 26 from taming.models import cond_transformer, vqgan
     27 import torch
     28 from torch import nn, optim

1 frames
/content/taming-transformers/main.py in <module>
     10 from pytorch_lightning.trainer import Trainer
     11 from pytorch_lightning.callbacks import ModelCheckpoint, Callback, LearningRateMonitor
---> 12 from pytorch_lightning.utilities.distributed import rank_zero_only
     13 
     14 from taming.data.utils import custom_collate

ImportError: cannot import name 'rank_zero_only' from 'pytorch_lightning.utilities.distributed' (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/distributed.py)

I don't know how to solve this problem. I don't know how to manually install Pytorch as it said "NOTE: If your import is failing due to a missing package, you can manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the "Open Examples" button below."

Thank you in advance if you have the solution.

Inès

I tried !pip install but I may not really know where to put this cell/line of code

**Comment by mco-gh** [comment]
Hi Inès,

You tried to import `rank_zero_only` from the `pytorch_lightning.utilities.distributed` module and the runtime is saying it can't find that symbol in that module. This doesn't appear to be a problem with Colab per se, but rather the contents of the notebook itself. It's often the case that package dependencies change (for example, `rank_zero_only` may have moved to a different module) so your best bet would be to consult with the author of this notebook, to see if they are aware of the problem and have any suggestions for fixing it.
