### ISSUE TITLE
Download Libraries for Neural Network

### ISSUE THREAD

**Issue by SpiritCrypto777** [googlecolab/colabtools#3203]
**Describe the current behavior**
Since yesterday Download Libraries for Neural Network doesn't run:
ImportError: cannot import name 'rank_zero_only' from 'pytorch_lightning.utilities.distributed' (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/distributed.py)

**Describe the expected behavior**
To run this without manual action

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mco-gh** [comment]
Someone else reported this as well (https://github.com/googlecolab/colabtools/issues/3202). Assuming you properly `pip install`'ed the required dependencies (and it sounds like you did because the notebook worked fine before) it doesn't sound like a problem with Colab itself, but more likely something changed in that module. I'd suggest checking with the pytorch_lightning maintainer.

**Comment by SpiritCrypto777** [comment]
Thank you for your prompt answer.

It's a long time I used colab without problem but in front of this problem
now I don't know what to do because I know nothing about python language or
things to do to solve it. So I don't understand how to do to check with the
pytorch_lightning maintainer. 😅

**Comment by mco-gh** [comment]
Here's the [pytorch lightning](https://www.pytorchlightning.ai/) site. You can visit that site to see what options they have for communicating questions and problem reports. I see they have a Slack channel so that might be one option. Since you're depending on that software, it's in your best interest to find out for yourself the best way to reach out to that team for help.

**Comment by SpiritCrypto777** [comment]
Thank you Marc, I'll try to do it.
When it's like that this can't be solved by the colab team directly (I say
that because it seems like I'm not the only one to have this problem)?
Anyway I will try to contact somebody in pytorch lightning.
Thanks again

**Comment by SpiritCrypto777** [comment]
Yes! I understand, the example is good!
I'm in contact with somebody pytorch on Slack. Hope he will understand ;)

**Comment by cswkim** [comment]
I'm facing this same issue. How can you force install an older version of a library in colab? If I do:
`!pip install pytorch-lightning==1.0.8` or even just `!pip install pytorch-lightning` I get a message saying that the requirement is already satisfied in `/usr/local/lib/python3.7/dist-packages`

**Comment by mco-gh** [comment]
Try pip uninstalling the package before installing the desired version.

**Comment by SpiritCrypto777** [comment]
Marc, to update a version from a colab free to a colab pro can avoid this
kind of problem or bug?

**Comment by mco-gh** [comment]
I wouldn't expect that to help. Free vs. Pro is more about the computing resources available to your notebook and I don't think it will affect the default installed package configuration.

**Comment by SpiritCrypto777** [comment]
I suppose so too. I had an answer from Pytorch:
"Seems like it is using old API. Could you restrict to use PL 1.7"
But I don't know what to do with this information. To talk again about your
analogy: I'm able to appreciate a recipe but not be a cook. ;)

**Comment by SpiritCrypto777** [comment]
The pip install I can see are all here and I don't see it:
[image: image.png]

**Comment by mco-gh** [comment]
No image showed up. If you can share a notebook, I'll take a look.

**Comment by SpiritCrypto777** [comment]
https://colab.research.google.com/drive/1lx9AGsrh7MlyJhK9UrNTK8pYpARnx457#scrollTo=EXMSuW2EQWsd
Something like that?

**Comment by mco-gh** [comment]
See the line: `!pip install ftfy regex tqdm omegaconf pytorch-lightning  &> /dev/null`
Change pytorch-lightning to pytorch-lightning==1.7 and try the whole notebook again.

If that doesn't work, I'm afraid you'll need to contact the notebook provider, the name of whom is shown in your notebook.

**Comment by SpiritCrypto777** [comment]
You're the master of Python Marc!!! The recipe is very good and it's ok
now. Thank you very much for the time you took to fix this problem!!!
