### ISSUE TITLE
Julia using Plots with GPU

### ISSUE THREAD

**Issue by theodorosP** [googlecolab/colabtools#3204]
Hello,

First of all thanks for PARTIALLY  fixing the issue with Julia. I definitely understand that you are doing your best.
 I noticed the following issues:

1)in the shell script you have JULIA_PACKAGES="IJulia BenchmarkTools", if this is substituted by JULIA_PACKAGES="IJulia BenchmarkTools Plots", then Julia can not be installed since there is an error with Plots

2) In your official Julia page (https://colab.research.google.com/github/ageron/julia_notebooks/blob/master/Julia_Colab_Notebook_Template.ipynb#scrollTo=W0UG_E8ePH1p) If I run the codewith with CPU or TPU and then do:

import Pkg; Pkg.add("Plots")

everything works perfect. However, Plots can not be installed  with GPU. I can definitely use it with TPU or just CPU.

Thanks

**Comment by cperry-goog** [comment]
That isn't our official Julia page, fwiw. You'll have better luck contacting the notebook author. We don't officially support Julia.

**Comment by theodorosP** [comment]
Thanks
