### ISSUE TITLE
Cannot retrieve the Colab notebook name

### ISSUE THREAD

**Issue by dnevo** [googlecolab/colabtools#3207]
Hi, since Nov 3, 2022, when trying to retrieve notebook name by: 
`name = requests.get('http://172.28.0.2:9000/api/sessions').json()[0]['name']`

, the following error is received:
`OSError: [Errno 113] No route to host`

The expected behavior is to receive the notebook name (it worked fine till Nov 3).

I am using Chrome.

**Comment by craigcitro** [comment]
The IP isn't stable (as you're seeing here); you should query to find out the correct IP to use.

Here's some sample code to fetch the info about the server (from [this SO answer](https://stackoverflow.com/a/41782256)): 

```
from notebook import notebookapp
servers = list(notebookapp.list_running_servers())
servers
```
