### ISSUE TITLE
cant sync to the  ***@gamil.com

### ISSUE THREAD

**Issue by maria22431** [googlecolab/colabtools#3208]
hi 
i have been working on my project in google colab
 but today i can reach or open all my file i have been saved in google colab
and make new notebook i get error cant sync to the  ***@gamil.com
but iam sing in my account
plz help me

**Comment by mco-gh** [comment]
I assume `***@gamil.com`  is a typo on your part, otherwise that would be the problem. :)

It sounds like something is wrong with your gmail account. Can you login to that account independently of colab?

**Comment by Maria2244** [comment]
yes i can and i am in my acount

**Comment by mco-gh** [comment]
Next question would be are those files you own or were they shared with you? 

Either way, can you see them via the Google Drive UI?

**Comment by Maria2244** [comment]
all file  in google Drive they are mind  . i save them in google drive
but in google colab dose not open i mean it will stay in loading..
and open notebook in colab dose not work? nothing happen .strange!

**Comment by mco-gh** [comment]
> can you see them via the Google Drive UI?

Assuming so, what happens when you try to open with Colab from the Drive UI? Like this:
<img width="805" alt="Screen Shot 2022-11-04 at 12 39 05" src="https://user-images.githubusercontent.com/658327/199974709-cd26cbe0-5636-439b-8096-88554c922c02.png">

**Comment by mco-gh** [comment]
One more thing to check - do you have two google accounts, by any chance? The account with which you use colab has to match the account you specify when you authorize drive.mount(). Can you verify that as well?

**Comment by Maria2244** [comment]
yes
i cheeked with another system i can open my file but  my laptop i cant . is any chance google colab blocked my id by mistack

**Comment by Maria2244** [comment]
or my mail

**Comment by mco-gh** [comment]
Can you reply to this question:

> Assuming so, what happens when you try to open with Colab from the Drive UI? Like this:

**Comment by Maria2244** [comment]
told u nothing happen its look like i didn't click on it.
and when i create new notebook the page will stuck on loading...

**Comment by Maria2244** [comment]
![image](https://user-images.githubusercontent.com/102213469/200636293-d4ef63d4-cb60-4b31-9f69-12742128ca34.png)

**Comment by Maria2244** [comment]
and when i open it from google drive will be like above too 
i mean stay in loading...

**Comment by mco-gh** [comment]
I'm really not sure what's going on here but if you think you may have been unfairly blocked you can submit in-product feedback to ask for verification of your account status and consideration of your case.

**Comment by Maria2244** [comment]
thanks a lot
i will do it
