### ISSUE TITLE
Unable to connect to the GCE runtime

### ISSUE THREAD

**Issue by yimingsun12138** [googlecolab/colabtools#3209]
Hey, i have some trouble here.
I deployed a GCE vm using markerplace and successfully connected to the runtime several days ago. But something went wrong while building my own environment, so i reset the vm in google cloud computer engine, but I can not connect to the vm after, so i simply delete the vm.

Today, I deploy a new GCE vm, but still, i am unable to connect to the runtime.
![Screenshot 2022-11-04 174344](https://user-images.githubusercontent.com/32930896/199945780-5653f967-7df0-4338-ba96-07351fa4105c.png)
I am not sure what is going on here, can you give me some advice? Thanks

**Comment by mco-gh** [comment]
Did you adjust your connection details (project, zone, instance name) to accommodate the new VM's details?

**Comment by yimingsun12138** [comment]
> 

yeah, i did adjust the vm detail, i also tried to connect to the colab directly from GCE marketplace, but all fails.

PS: if I give the wrong vm detail, it returns with error "VM do not exist" but not "unable to connect to the runtime"

**Comment by mco-gh** [comment]
I meant that you might have been reusing the old VM details, which would give the same "unable to connect" message. But given you're using the new details, are you able to ssh into the new VM? If so, can you login and run `docker ps -a` and share the output here?

**Comment by yimingsun12138** [comment]
> I meant that you might have been reusing the old VM details, which would give the same "unable to connect" message. But given you're using the new details, are you able to ssh into the new VM? If so, can you login and run `docker ps -a` and share the output here?

![Screenshot 2022-11-04 174344](https://user-images.githubusercontent.com/32930896/199967897-65d5a461-8feb-45d7-ad17-852310528466.png)
Here is the output. I am not familiar with docker, thank you for your assistance!

**Comment by mco-gh** [comment]
Thanks for reporting this. 

Could each of you ssh into your VM and run the following commands?
```
docker ps -a
df -a
curl -H "Metadata-Flavor: Google" "http://metadata/computeMetadata/v1/project/project-id"
curl -H "Metadata-Flavor: Google" "http://metadata/computeMetadata/v1/instance/name"
curl -H "Metadata-Flavor: Google" "http://metadata/computeMetadata/v1/instance/image"
curl -s http://ipecho.net/plain
curl -s http://icanhazip.com/
```
If you could gather the output from those commands and submit them with a product feedback item (Help->Send Feedback in Colab), that would be a huge help.

After capturing that data, you may be able to work around this problem by re-creating the Marketplace VM, but be aware that will lose any current state, like installed packages, global variables, etc.

**Comment by samsniderheld** [comment]
I've been experiencing connection issues all week. 

Unfortunately at this point, I can't connect at all, even when I create a brand new VM, with a totally different region and vm name.

Does it have to do something to with the gpu and machine types we are using?

**Comment by mco-gh** [comment]
Sorry for the inconvenience, we're working on it and will update this thread as soon as I know more.

**Comment by craigcitro** [comment]
Thanks all for the reports and the digging -- this was indeed a problem on our side. The problem should be fixed -- if you refresh your page and reconnect, everything should be OK. (Note that the page refresh is critical in that process.)

**Comment by yimingsun12138** [comment]
I can connect to the GCE vm now, without refreshing the page. Thank you for all your assistance!

By the way, If I screw up my environment on GCE vm and would like to reset the vm, how should i operate?

**Comment by mco-gh** [comment]
That's a good question. In theory, you could checkpoint images of your VM in Google Cloud Storage but there may be a more efficient mechanism. I'll research that and get back to you in this thread.

**Comment by mco-gh** [comment]
Actually, checkpointing the VM wouldn't help much because the problem in this case was in the VM to backend communication. As a general rule, any precious resource or state living on a VM should be backed up somewhere (e.g. Drive or Cloud Storage).

I'll close this issue but please re-open if this recurs.
