### ISSUE TITLE
Plots don’t show grids

### ISSUE THREAD

**Issue by natewind** [googlecolab/colabtools#321]
This:
![image](https://user-images.githubusercontent.com/30814650/47494346-1bcee400-d85a-11e8-8278-9bb6a6f7f37b.png)
![image](https://user-images.githubusercontent.com/30814650/47493768-c47c4400-d858-11e8-82c7-b453b30a2af1.png)

Shows this:
![image](https://user-images.githubusercontent.com/30814650/47493789-ce05ac00-d858-11e8-87bf-cdbc196af29d.png)

Instead of this:
![image](https://user-images.githubusercontent.com/30814650/47493890-1624ce80-d859-11e8-8d98-f783f61a3f74.png)

(Yeah, also Unicode.)
(BTW, you don’t have to suck at design just because you work for Google. Rise above it!)

**Comment by blois** [comment]
By default matplotlib is using the seaborn, to reset this:

```python
import seaborn
seaborn.reset_orig()
```

You probably want to pull ax.set() and ax.grid() out of the for loop, or explicitly enable the grid with ax.grid(True).

https://colab.research.google.com/gist/blois/4901ea2a1452577419214ae6be1ffa17/issue321.ipynb

We're always open to constructive design critique!

**Comment by natewind** [comment]
I don’t know what seaborn is but that helped, thanks!

set() and grid() were already outside the for loop though. And in the linked notebook they’re inside.

As for the design, I don’t know where to start. Basically, everything that looks different from locally installed Jupyter Notebook looks worse.
