### ISSUE TITLE
Variable names of the form _+keyword will be partially highlighted as a Python keyword

### ISSUE THREAD

**Issue by JonEsparaz** [googlecolab/colabtools#3210]
**Describe the current behavior**

A variable name of the form `_+keyword` (pseudo regex) will be partially highlighted as a Python keyword.

Examples:
- `_lambda`
- `__lambda`
- `_False`

Viewing on Colab:
![image](https://user-images.githubusercontent.com/48423418/200069029-97e49a2d-ab58-46fa-8a5b-b4d61da44a63.png)

**Describe the expected behavior**

While these are admittedly poorly named variables, they are still valid and should not include keyword syntax highlighting. For example, viewing the same notebook on GitHub:

![image](https://user-images.githubusercontent.com/48423418/200068984-583129b1-5b58-40e5-831b-9f0f8dcc4925.png)

**What web browser you are using**
Firefox 106.0.4

**Additional context**
https://colab.research.google.com/gist/JonEsparaz/4d899df57f3936ef230a1c28ed33dec9/_keyword_colab_bug.ipynb

**Comment by cperry-goog** [comment]
Thanks! Tracking b/258680955 internally.

**Comment by colaboratory-team** [comment]
Fixed, thanks for the report!
