### ISSUE TITLE
pandas DataFrame issue

### ISSUE THREAD

**Issue by Suhailpk** [googlecolab/colabtools#3213]
when I import a CSV file from pandas DataFrame it shows the output for only one second and then disappears. please fix this bug as soon as possible.

**Comment by mayankmalik-colab** [comment]
I am not really sure what you mean't by `import a CSV file from pandas DataFrame`. Do you mean saving a dataframe as a CSV (`df.to_csv()` ) or reading from csv file and creating a dataframe (`pd.read_csv()`). If possible, can you share more details ( or a minimal repro notebook ).
