### ISSUE TITLE
After TPU Node is pre-empted, Colab continues to charge compute units at the TPU cost

### ISSUE THREAD

**Issue by korneelvdbroek** [googlecolab/colabtools#3216]
**Describe the current behavior**
When a TPU Node gets pre-empted, the Colab session continues to charge compute credits at the (higher) TPU rate

**Describe the expected behavior**
When a TPU Node gets pre-empted, the Colab session should only charge for the Colab VM.

**What web browser you are using**
Chrome

**Additional context**
Can be reproduced with any Colab notebook using a TPU.

Details of the observed occurrence:
```
Colab VM IP:  34.70.155.18
TPU Node:     10.43.186.178:8470
```

Sequence of Events:
```
2022-11-07 15:47:20 UTC: Initializing the TPU system: grpc://10.43.186.178:8470
...
2022-11-07 15:48:36 UTC: tensorflow.python.framework.errors_impl.UnavailableError: Socket closed
Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 819, in get_next
    return self._next_internal()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 758, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/context.py", line 2466, in execution_mode
    executor_new.wait()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/executor.py", line 65, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.UnavailableError: Socket closed

2022-11-07 15:53:00 UTC: compute credit 39.41
2022-11-07 15:57:00 UTC: compute credit 39.24
```

Earlier occurrences of this issue was flagged in Twitter convo with @cperry-goog

**Comment by cperry-goog** [comment]
Is this reliably reproducible for you? If so, can you share a minimal repro notebook?

This _should_ be impossible/incredibly unlikely, but we can maybe tighten this up a bit more. If you submit in-product feedback and mention cperry prominently in your text then I'll grant you some compute units to compensate you.

**Comment by korneelvdbroek** [comment]
> Is this reliably reproducible for you? If so, can you share a minimal repro notebook?
> 
> This _should_ be impossible/incredibly unlikely, but we can maybe tighten this up a bit more. If you submit in-product feedback and mention cperry prominently in your text then I'll grant you some compute units to compensate you.

Thank you for your response. 

As Colab user, I am not 100% sure how to reliably trigger a TPU Node pre-emption. One potential option to reliably reproduce this, might be by intentionally crashing the TPU Node (e.g. by loading too large a dataset) such that it results in a `tensorflow.python.framework.errors_impl.UnavailableError: Socket closed` error. 

If you can confirm that, in such cases: 
1. Google restarts the crashed TPU Node and,
2. that that TPU Node, after the restart, is not linked with the Colab VM anymore (i.e. the node was pre-empted, as a consequence of the crash)

then I'd be happy to write a minimal notebook to investigate compute unit evolution on the Colab VM.

Also, what do you mean with in-product feedback?

**Comment by cperry-goog** [comment]
In-product feedback can be submitted by clicking the Help menu in Colab, then send feedback.

If you can get this to reproduce will you submit in product feedback? That'll help us dig.
