### ISSUE TITLE
Import "tensorflow.keras.datasets" could not be resolved(reportMissingImports)

### ISSUE THREAD

**Issue by Arun1542** [googlecolab/colabtools#3228]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mayankmalik-colab** [comment]
Can you share the code snippet of your import. I believe this is similar to #2637 . Let us know if this helps.

**Comment by RATIRANJAN301** [comment]
I have the same issue "[Import "tensorflow.keras.datasets" could not be resolved(reportMissingImports)](https://github.com/googlecolab/colabtools/issues/3228#top)"
