### ISSUE TITLE
Colab.new domain shortcut to create a new notebook

### ISSUE THREAD

**Issue by korakot** [googlecolab/colabtools#323]
Google documents, sheets, and slides now have their own web shortcuts.
Can we have the same for Colab notebooks as well?

**Comment by korakot** [comment]
Google is going to sell dot new domain now.
Please don't sell colab.new
Please make it a shortcut for a new colab notebook.

https://blog.google/outreach-initiatives/entrepreneurs/shortcuts-made-possible-new/

**Comment by zahrevsky** [comment]
Looks like colab.new is currently used by someone else.

Also, I've hosted [colab.run](https://colab.run) that does 302 redirect to https://colab.research.google.com/. Yes, it's not `.new`, but still a shortcut!

**Comment by mco-gh** [comment]
We've fixed this. colab.new now opens a new colab notebook for you.
