### ISSUE TITLE
Unable to connect to back end

### ISSUE THREAD

**Issue by mcxuehu** [googlecolab/colabtools#3233]
Connect, wait a moment (2s--3s) Disconnect, reconnect, disconnect. It's always been like this
![202879755-71b2ec82-6609-4751-a7d0-dfd665eccfe5](https://user-images.githubusercontent.com/106948679/202879772-a4fc764b-07e3-4ff6-bef6-8ee0182c0dcf.png)
The only Chinese language：代码执行程序已断开连接=The code executor has been disconnected
Machine translation

**Comment by cperry-goog** [comment]
Can you try in an incognito window without a proxy or vpn?
