### ISSUE TITLE
Colab consumed compute units

### ISSUE THREAD

**Issue by cevparlak** [googlecolab/colabtools#3236]
**Describe the current behavior**

Colab consumed the compute units without running a notebook in premium account.
**Describe the expected behavior**

Compute units must be spent only while running in premium account

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome and Firefox

**Comment by cperry-goog** [comment]
> Compute units must be spent only while running in premium account

This is not the expected behavior - if you have compute units, any usage of Colab will consume them.
