### ISSUE TITLE
With Colab Pro+ there is no difference bettween TPU-RAM in Standart / High-Ram mode

### ISSUE THREAD

**Issue by MaximeGrigoriev** [googlecolab/colabtools#3239]
I activated Colab Pro+, but TPU-RAM is the same in Standart / High-Ram mode — 13,6GB.

How can I increase it in High Ram mode?

**Comment by cperry-goog** [comment]
Can you submit feedback in product next time you observe this? We likely did not have enough highmem TPU machines at the time you requested an assignment.
