### ISSUE TITLE
The gpu hasn't updated for days, it always tells me it's finished even if I don't use it. Can you unlock it for me to use?

### ISSUE THREAD

**Issue by ClarissaGam** [googlecolab/colabtools#3243]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
Submit feedback in product when you encounter this.
