### ISSUE TITLE
len() function not working.. Seriously ??

### ISSUE THREAD

**Issue by harshdurugkar** [googlecolab/colabtools#3244]
strr = "Harsh"
print(len(strr)) 

This Code not running.. They show TypeError 
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

[<ipython-input-37-d03829dabfe8>](https://localhost:8080/#) in <module>
      1 strr = "Harsh"
----> 2 print(len(strr))

TypeError: 'int' objec
![Annotation 2022-11-23 232623](https://user-images.githubusercontent.com/76514358/203616457-7f5fff7e-3e42-4745-b62a-7b0dbccfe2ad.png)
t is not callable
Browser :-  Firefox

**Comment by colaboratory-team** [comment]
We usually see this issue when other code cells assign variables with the same name as built-in functions, overriding them. Did you assign a variable named "len"?

If you go to Runtime -> Restart Runtime, and just run that last cell, it should pass
