### ISSUE TITLE
Unable to connect to MS SQL Server using pyodbc in colab, getting this error OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)'). Kindly let me know if there is a fix available for this.

### ISSUE THREAD

**Issue by PoojaSalian064** [googlecolab/colabtools#3247]
Unable to connect to MS SQL Server using pyodbc in colab, getting this error OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)'). Kindly let me know if there is a fix available for this.

**Comment by cperry-goog** [comment]
Can you share a minimal repo notebook? Hard to troubleshoot without knowing what code is being invoked.

**Comment by hoang0203** [comment]
I got same as your issue
my code:
!pip install pyodbc
!pip install sqlserverport
!sudo apt-get install unixodbc-dev
!pip install pyodbc
!pip install chart_studio

%%sh
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
sudo apt-get update
sudo ACCEPT_EULA=Y apt-get -q -y install msodbcsql17

import pyodbc
import pandas as pd
import sqlserverport
import urllib
import sqlalchemy as sa

conn = pyodbc.connect(DRIVER = '{ODBC Driver 17 for SQL Server}',
                      SERVER = 'xxx.xx.xx.xxx, xxxx',
                      DATABASE = 'database_name',
                      Trusted_Connection='Yes')

cursor = conn.cursor()

error:
OperationalError                          Traceback (most recent call last)
[<ipython-input-25-66b614bec7ce>](https://localhost:8080/#) in <module>
----> 1 conn = pyodbc.connect(DRIVER = '{ODBC Driver 17 for SQL Server}',
      2                       SERVER = '172.31.40.168, 1433',
      3                       DATABASE = 'DA',
      4                       autocommit=True,
      5                       Trusted_Connection='no')

OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')

**Comment by cperry-goog** [comment]
This doesn't appear to be a Colab-specific issue as best as we can tell. You could try updating your curl to reference 18.04, that could potentially resolve, otherwise seems like a SQL Server bug.

**Comment by hoang0203** [comment]
Thanks. but I tried and it still does not work. How could I check my sql server. Note: if I use vs code or jupyter notebook even azure data studio, that code will work

**Comment by mco-gh** [comment]
I would speak with the admin of your SQL server to verify the address and port you're using and to see if there's any restriction on the ip address range of sources that are allowed to connect.

**Comment by hoang0203** [comment]
huh. Do we need to public server and use public IP instead?

**Comment by hoang0203** [comment]
for my digging, I found that we may public your ip first. I never try it before :))

**Comment by Mgajurel** [comment]
Hi, I have a similar problem. I am also thinking that this is more of an issue with the MSSQL Server that I am trying to connect rather than pyodbc's, because i can successfully connect using pymssql. Has anyone found some thing?

I will let you know if I fix my issue.
