### ISSUE TITLE
Missing dependencies in setup.py

### ISSUE THREAD

**Issue by SeraphicRav** [googlecolab/colabtools#3249]
**Describe the current behavior**
Installing locally jupyter on a clean debian and adding https://github.com/googlecolab/colabtools.git as a dependency actually also requires at least psutil and httplib2 to be installed too.

**Describe the expected behavior**
Installing from setup.py should not need additional dependencies.

**What web browser you are using**
Chrome and Firefox 100+

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Take a fresh Debian
 - Clone https://github.com/SeraphicRav/local-colab and follow the instruction of the README regarding to build and run docker
 - Go to colab and connect to the local instance
 - Run:
```python
from google.colab import drive
drive.mount('/dev/gdrive')
```

You will get dependency errors. Adding psutil and httplib2 will allow to overcome the errors but will need to another error.
![image](https://user-images.githubusercontent.com/3774520/204131160-3f8cef85-7134-480e-864f-dfa69fec8b5e.png)

**Comment by cperry-goog** [comment]
Installing https://github.com/googlecolab/colabtools.git isn't supported. It's installed by default on Colab and we don't intend to support installation anywhere else.
