### ISSUE TITLE
Slow to respond

### ISSUE THREAD

**Issue by somnathrakshit** [googlecolab/colabtools#325]
Currently, colab takes a some time in between cells. However, services like  Azure notebooks are extremely responsive and fast. Can this be corrected?

**Comment by blois** [comment]
When you say 'slow to respond', approximately how much time are you seeing between cells?

A benchmark we frequently use is:
https://colab.research.google.com/gist/blois/a3c6d3a721b5d1bb40c4d73e84c51c68/timing.ipynb

We frequently see it complete in ~7s, which is longer than we'd like (we're working on it), but I'm curious if you're seeing significantly different results.

**Comment by somnathrakshit** [comment]
I am sure that I won't even be able to fathom the insane amount of hard work that has gone into making this product better. I truly appreciate it. However, my point was the Azure notebooks does not take much time in between cells. It might very well be 10x faster than Colab wrt time taken in between cells.

The notebook in the link that you posted took 17 seconds to complete on my laptop.

**Comment by somnathrakshit** [comment]
This same code took a bit over 2 seconds on Azure notebooks. Please do something about this.

**Comment by blois** [comment]
We are working on improving the run-all time. Improving the per-cell output rendering time will take a bit more but we are keen to improve it.

**Comment by somnathrakshit** [comment]
Great!
