### ISSUE TITLE
Session stopped without entry in app.log

### ISSUE THREAD

**Issue by MuriloGarret** [googlecolab/colabtools#3254]
I'm running a CNN Deep Learning Classification model on colab pro+. However, without reason, session is interrupted, and no log is presented in the app.log file.

![image](https://user-images.githubusercontent.com/119513567/204824282-8e229d8e-04f4-4972-be7a-836038c941e0.png)
As can be seen in the image, It's 30th november and the last entry in the app.log was yesterday. The program has just stopped running without reason.

**Comment by cperry-goog** [comment]
Can you submit feedback in product the next time this happens?

Note that Pro+ runtimes will only last up to 24 hours, if you're seeing interrupts at that limit that is working as intended.
