### ISSUE TITLE
Name error

### ISSUE THREAD

**Issue by lipeffl** [googlecolab/colabtools#3257]
Hi,
i got a 'bug' today from a code that yesterday was working well. Thats in a 3d graphic using matplot. When i run the code just get the answer name 'z' is not defined. I runned the code today again to keep doing my home exercise.
If i upper 'x', 'y', and 'z', it changes and the mistakes go to the 'x'. Name error: name 'x' is not defined.
I'm using opera browser and i'm a begning in python.
Here is where the mistake is happening, in the end, 3d graphic.
https://github.com/lipeffl/MatPlot/blob/main/Atividade_Casa_Matplotlib.ipynb

**Comment by mayankmalik-colab** [comment]
I don't think lowercase z (`z`) is defined in the notebook. I can only see an uppercase Z (`Z`) defined as `Z = ColorMap(x, y).T` . I would encourage putting all the variables in lowercase.

**Comment by lipeffl** [comment]
> I don't think lowercase z (`z`) is defined in the notebook. I can only see an uppercase Z (`Z`) defined as `Z = ColorMap(x, y).T` . I would encourage putting all the variables in lowercase.

Yes, i saw it now, but it is in the code before(color map). 
I changed it for lower and it is working. I thought these cells were not linked.
Thank you.
