### ISSUE TITLE
Pandas requires version '1.2.0' or newer of 'xlrd' (version '1.1.0' currently installed).

### ISSUE THREAD

**Issue by jmalberola** [googlecolab/colabtools#3258]
Hi,

I am trying to use the read_excel function for reading a "xls" file and I find the following error:
**ImportError: Pandas requires version '1.2.0' or newer of 'xlrd' (version '1.1.0' currently installed)**

**Code:**
```
import pandas as pd
df = pd.read_excel("file.xls")
```

I am able to solve this problem by executing:
`!pip install --upgrade xlrd`

However, this solution requires to be re-executed each time the environment gets closed and need to be started again. I was wondering whether this solution could be permanent.

Best regards

**Comment by mayankmalik-colab** [comment]
`xlrd` is upgraded to '1.2.0'.

**Comment by jmalberola** [comment]
Thanks!
