### ISSUE TITLE
Delay in the cells loading

### ISSUE THREAD

**Issue by ravi160822** [googlecolab/colabtools#3259]
https://user-images.githubusercontent.com/114392296/205027073-b9c022db-85c7-46a3-9d26-26541aff9b34.mov

The cells take time to load

I have done this setup
```
from google.colab.output._publish import javascript
url = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/latest.js?config=default"
javascript(url=url)
```
to view sympy equations, could that be the reason?
or is it because of too many cells in the notebook?

**Comment by mco-gh** [comment]
I'm happy to do a little experimentation to see if I can repro this and try to understand what's going on if you're able to share a sample notebook (please expunge anything proprietary or sensitive before sharing).

**Comment by ravi160822** [comment]
it is happening on every notebook currently
Mac M1
Safari

Could it be due to many tabs being open, or some issue with too many apps open in the pc

**Comment by mco-gh** [comment]
again, a sample notebook would help

**Comment by mco-gh** [comment]
closing but reopen if you have a reproducible notebook we can try
