### ISSUE TITLE
Cannot create new file or Upload to use colab

### ISSUE THREAD

**Issue by juhonkang** [googlecolab/colabtools#3263]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
![image](https://user-images.githubusercontent.com/67153600/205285666-e86fa179-e335-440c-b119-3a85f11cf596.png)

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
Cannot create new file

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Edge

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by colaboratory-team** [comment]
Could you submit feedback within Colab at Help > Send feedback the next time this happens?
