### ISSUE TITLE
Cannot use Tensorflow 1 after upgrade to Python 3.8

### ISSUE THREAD

**Issue by veeramik** [googlecolab/colabtools#3264]
**Describe the current behavior**
Cannot use Tensorflow1 versions anymore after upgrading to Python 3.8 (I have to use TF1 because of compatibility with a software which updates are beyond my control). I tried to downgrade to Python 3.7 but an issue downloading tensorflow1.13.1 still persists. I also tried to downgrade to an older version of protobuf (see photo for the error message), but that did not fix the issue either.

**Describe the expected behavior**
Expected to be able to use TF1 by doing:
!pip uninstall -y tensorflow
!pip install tensorflow==1.13.1
import tensorflow as tf

Now can only download TF1 by
!pip uninstall -y tensorflow
!pip3 install https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.13.1-py3-none-any.whl

And the "import tensorflow as tf" command does not actually work.

**What web browser you are using**
Chrome

**Additional context**
<img width="1354" alt="Screenshot 2022-12-02 at 13 11 21" src="https://user-images.githubusercontent.com/55758979/205368523-62f8a1ea-c55e-41de-9c11-810c3da77d4f.png">

**Comment by craigcitro** [comment]
This is unfortunately outside of our control: TF1 simply does not support python 3.8: https://github.com/tensorflow/tensorflow/issues/39768
