### ISSUE TITLE
ping not working? Does it support ping?

### ISSUE THREAD

**Issue by DIKSHAAGARWAL2015** [googlecolab/colabtools#3265]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mco-gh** [comment]
Can you describe what you're trying to do?

**Comment by daveSMUS** [comment]
HTTP server works, but I can't ping the URL... Is there something I can set to allow this?

https://colab.research.google.com/drive/1cOc2f6dUGKfJoceKzzKqbtDUqyHcCPmi#scrollTo=1Leh-8tv9vzV

Thanks!

example:
>ping https://1pbqlq0ge1k-496ff2e9c6d22116-8000-colab.googleusercontent.com
Ping request could not find host https://1pbqlq0ge1k-496ff2e9c6d22116-8000-colab.googleusercontent.com. Please check the name and try again.
