### ISSUE TITLE
Tensorflow 1.15 impossible to use after update

### ISSUE THREAD

**Issue by beachboy4545** [googlecolab/colabtools#3266]
**Describe the current behavior**
Hello, my research requires that I use tensorflow 1.15. I am no longer able to use:
!pip install tensorflow==1.15
because there is no distribution for said version on Python 3.8. 

When I use :
   !sudo update-alternatives --config python3
followed by:
   !sudo apt install python3-pip
   !python3 -m pip install --user --upgrade pip

Then when I use:
   !pip3 install tensorflow==1.15

I receive the message:
  "WARNING: The following packages were previously imported in this runtime:
   [astor,google]
   You must restart the runtime in order to use newly installed versions."

When I restart my runtime, I receive a message that my session has crashed and the app.log has many warnings of:
   "| WARNING | /usr/bin/python3: No module named ipykernel_launcher"

**Describe the expected behavior**
I expect that I would be able to restart my runtime without any crashing occuring and that I would be able to run the rest of my code that involves tensorflow1.15

**What web browser you are using**
Google Chrome

**Additional context**
(https://colab.research.google.com/gist/beachboy4545/d84aa2f8202099fa6e645971ea26dd0f/runtime-crash-tf1-15.ipynb)

**Comment by mayankmalik-colab** [comment]
Unfortunately, changing Python in Colab is not supported. As you know, tensorflow 1 doesn't support Python 3.8 . That being said, you can still use fallback version (python 3.7) for a few more days. For more details on how to use the fallback version - #3246 .  However, please upgrade your notebooks to be compatible with Colab’s current runtime version.

**Comment by cperry-goog** [comment]
Sorry, nothing we can do on this, this is on Tensorflow's issue.

**Comment by Atotem** [comment]
Hey @beachboy4545 , I found a way. Apparently you can install conda in colab. But, you have to activate your environment every time you want to use it. Follow this code blocks and you will achieve it:

Before everything, set pythonpath to nothing so you don't have conflicts.
```
%env PYTHONPATH = # /env/python
```

First, you get miniconda (I'm using miniconda with python 3.8 version, but you can change it). You have to keep the path '/usr/local' to make it work. Otherwise, colab will not recognize conda.
```
!wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.12.0-Linux-x86_64.sh
!chmod +x Miniconda3-py38_4.12.0-Linux-x86_64.sh
!./Miniconda3-py38_4.12.0-Linux-x86_64.sh -b -f -p /usr/local
!conda update conda
```

Then, append this path to install packages.
```
import sys
sys.path.append('/usr/local/lib/python3.8/site-packages')
```

Create your virtual environment with python version that matches TensorFlow 1.15 (3.6)
```
!conda create -n myenv python=3.6
```

Install TensorFlow 1.15
```
%%shell
eval "$(conda shell.bash hook)"
conda activate myenv
pip install tensorflow==1.15
```

Run your python file. Remember to activate your virtual environment as suggested.
```
%%shell
eval "$(conda shell.bash hook)"
conda activate myenv
python3 /content/test.py
```

Observations: As I mentioned, you have to activate your environment every time you need TensorFlow 1.15. Also, this approach works if you want to run python files. In my case this works. I hope this can help you too. Best regards!

**Comment by licj1** [comment]
> 

Hello,
Thanks for your guidance. I have built the  virtual environment according to your instructions, and I installed the tensorflow-gpu==1.15, and set "export CUDA_VISIBLE_DEVICES="0" when running the command, but I found that the program didn't use GPU, I searched but didn't find the solution. Do you know the reason? Could you please help me solve this problem? Look forward to your reply soon. Thanks for your time!

**Comment by Atotem** [comment]
Hello @licj1,
Did you check if you're connected to GPU? (go to 'Edit'->'Notebook settings'->'Hardware accelerator'->'GPU or TPU').

**Comment by beachboy4545** [comment]
@Atotem Your method worked like a charm! 

It does seem I not only have to reactivate but also rebuild an environment to use it, however, this is a small price to pay to make Colab useful for me again.

Thank you!

**Comment by Rithvik1900** [comment]
@Atotem I have tried your method, like you said I have created new environment and installed tensorflow == 1.15, after installing it I have tried to check the version it is still showing tensorflow = 2.12.0

**Comment by Nasialink** [comment]
> Hey @beachboy4545 , I found a way. Apparently you can install conda in colab. But, you have to activate your environment every time you want to use it. Follow this code blocks and you will achieve it:
> 
> Before everything, set pythonpath to nothing so you don't have conflicts.
> 
> ```
> %env PYTHONPATH = # /env/python
> ```
> 
> First, you get miniconda (I'm using miniconda with python 3.8 version, but you can change it). You have to keep the path '/usr/local' to make it work. Otherwise, colab will not recognize conda.
> 
> ```
> !wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.12.0-Linux-x86_64.sh
> !chmod +x Miniconda3-py38_4.12.0-Linux-x86_64.sh
> !./Miniconda3-py38_4.12.0-Linux-x86_64.sh -b -f -p /usr/local
> !conda update conda
> ```
> 
> Then, append this path to install packages.
> 
> ```
> import sys
> sys.path.append('/usr/local/lib/python3.8/site-packages')
> ```
> 
> Create your virtual environment with python version that matches TensorFlow 1.15 (3.6)
> 
> ```
> !conda create -n myenv python=3.6
> ```
> 
> Install TensorFlow 1.15
> 
> ```
> %%shell
> eval "$(conda shell.bash hook)"
> conda activate myenv
> pip install tensorflow==1.15
> ```
> 
> Run your python file. Remember to activate your virtual environment as suggested.
> 
> ```
> %%shell
> eval "$(conda shell.bash hook)"
> conda activate myenv
> python3 /content/test.py
> ```
> 
> Observations: As I mentioned, you have to activate your environment every time you need TensorFlow 1.15. Also, this approach works if you want to run python files. In my case this works. I hope this can help you too. Best regards!

dude u are a miracle maker

**Comment by Ankitkumar803** [comment]
> @Atotem I have tried your method, like you said I have created new environment and installed tensorflow == 1.15, after installing it I have tried to check the version it is still showing tensorflow = 2.12.0

as mentioned by [Atotem](https://github.com/Atotem)  this only works for python files , so you can insert 
`import tensorflow as tf; print(tf.__version__)`  in test.py file and then you can see that it will show tensorflow == 1.15

**Comment by ariopri** [comment]
I cant find file test.py

**Comment by Prasantkumar987** [comment]
Tensorflow 1.15 can be used by creating seperate **conda environment** and inside it installing tensorflow with following command

`conda install tensorflow=1.15`

**Comment by MrDBC** [comment]
> conda install tensorflow=1.15



> I cant find file test.py

@ariopri 

u have to create that file, its not present by default
inside the file put this code:
>import tensorflow as tf
>print("TensorFlow version:", tf.__version__)


and then run this command in colab cell:
>%%shell
>eval "$(conda shell.bash hook)"
>conda activate myenv
>python3 /content/test.py

**Comment by MrDBC** [comment]
> Hey @beachboy4545 , I found a way. Apparently you can install conda in colab. But, you have to activate your environment every time you want to use it. Follow this code blocks and you will achieve it:
> 
> Before everything, set pythonpath to nothing so you don't have conflicts.
> 
> ```
> %env PYTHONPATH = # /env/python
> ```
> 
> First, you get miniconda (I'm using miniconda with python 3.8 version, but you can change it). You have to keep the path '/usr/local' to make it work. Otherwise, colab will not recognize conda.
> 
> ```
> !wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.12.0-Linux-x86_64.sh
> !chmod +x Miniconda3-py38_4.12.0-Linux-x86_64.sh
> !./Miniconda3-py38_4.12.0-Linux-x86_64.sh -b -f -p /usr/local
> !conda update conda
> ```
> 
> Then, append this path to install packages.
> 
> ```
> import sys
> sys.path.append('/usr/local/lib/python3.8/site-packages')
> ```
> 
> Create your virtual environment with python version that matches TensorFlow 1.15 (3.6)
> 
> ```
> !conda create -n myenv python=3.6
> ```
> 
> Install TensorFlow 1.15
> 
> ```
> %%shell
> eval "$(conda shell.bash hook)"
> conda activate myenv
> pip install tensorflow==1.15
> ```
> 
> Run your python file. Remember to activate your virtual environment as suggested.
> 
> ```
> %%shell
> eval "$(conda shell.bash hook)"
> conda activate myenv
> python3 /content/test.py
> ```
> 
> Observations: As I mentioned, you have to activate your environment every time you need TensorFlow 1.15. Also, this approach works if you want to run python files. In my case this works. I hope this can help you too. Best regards!


from what i found out, we can only run one .py file at a time.
for example  , i have 2 files: imports.py and preprocessing.py

i run the imports.py file, then when i try to run the 2nd file, it doesnt take the imports i did in the ist file into account
idk if its a problem only to me?

**Comment by IniasSomers** [comment]
> > 
> 
> Hello, Thanks for your guidance. I have built the virtual environment according to your instructions, and I installed the tensorflow-gpu==1.15, and set "export CUDA_VISIBLE_DEVICES="0" when running the command, but I found that the program didn't use GPU, I searched but didn't find the solution. Do you know the reason? Could you please help me solve this problem? Look forward to your reply soon. Thanks for your time!

Hello there! I am have the same problem that in the .py file in it can't access the gpu, did you find an solution for this? Thank you have a great day

**Comment by tosemfdk** [comment]
> Hey @beachboy4545 , I found a way. Apparently you can install conda in colab. But, you have to activate your environment every time you want to use it. Follow this code blocks and you will achieve it:
> 
> Before everything, set pythonpath to nothing so you don't have conflicts.
> 
> ```
> %env PYTHONPATH = # /env/python
> ```
> 
> First, you get miniconda (I'm using miniconda with python 3.8 version, but you can change it). You have to keep the path '/usr/local' to make it work. Otherwise, colab will not recognize conda.
> 
> ```
> !wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.12.0-Linux-x86_64.sh
> !chmod +x Miniconda3-py38_4.12.0-Linux-x86_64.sh
> !./Miniconda3-py38_4.12.0-Linux-x86_64.sh -b -f -p /usr/local
> !conda update conda
> ```
> 
> Then, append this path to install packages.
> 
> ```
> import sys
> sys.path.append('/usr/local/lib/python3.8/site-packages')
> ```
> 
> Create your virtual environment with python version that matches TensorFlow 1.15 (3.6)
> 
> ```
> !conda create -n myenv python=3.6
> ```
> 
> Install TensorFlow 1.15
> 
> ```
> %%shell
> eval "$(conda shell.bash hook)"
> conda activate myenv
> pip install tensorflow==1.15
> ```
> 
> Run your python file. Remember to activate your virtual environment as suggested.
> 
> ```
> %%shell
> eval "$(conda shell.bash hook)"
> conda activate myenv
> python3 /content/test.py
> ```
> 
> Observations: As I mentioned, you have to activate your environment every time you need TensorFlow 1.15. Also, this approach works if you want to run python files. In my case this works. I hope this can help you too. Best regards!

You saved my life bro. thanks a lot!

**Comment by dummyuser-123** [comment]
> > Hey @beachboy4545 , I found a way. Apparently you can install conda in colab. But, you have to activate your environment every time you want to use it. Follow this code blocks and you will achieve it:
> > Before everything, set pythonpath to nothing so you don't have conflicts.
> > ```
> > %env PYTHONPATH = # /env/python
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > First, you get miniconda (I'm using miniconda with python 3.8 version, but you can change it). You have to keep the path '/usr/local' to make it work. Otherwise, colab will not recognize conda.
> > ```
> > !wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.12.0-Linux-x86_64.sh
> > !chmod +x Miniconda3-py38_4.12.0-Linux-x86_64.sh
> > !./Miniconda3-py38_4.12.0-Linux-x86_64.sh -b -f -p /usr/local
> > !conda update conda
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then, append this path to install packages.
> > ```
> > import sys
> > sys.path.append('/usr/local/lib/python3.8/site-packages')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Create your virtual environment with python version that matches TensorFlow 1.15 (3.6)
> > ```
> > !conda create -n myenv python=3.6
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Install TensorFlow 1.15
> > ```
> > %%shell
> > eval "$(conda shell.bash hook)"
> > conda activate myenv
> > pip install tensorflow==1.15
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Run your python file. Remember to activate your virtual environment as suggested.
> > ```
> > %%shell
> > eval "$(conda shell.bash hook)"
> > conda activate myenv
> > python3 /content/test.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Observations: As I mentioned, you have to activate your environment every time you need TensorFlow 1.15. Also, this approach works if you want to run python files. In my case this works. I hope this can help you too. Best regards!
> 
> from what i found out, we can only run one .py file at a time. for example , i have 2 files: imports.py and preprocessing.py
> 
> i run the imports.py file, then when i try to run the 2nd file, it doesnt take the imports i did in the ist file into account idk if its a problem only to me?

True!! Did you find any solution. Actually I am running stylegan2 code in google colab and I am facing exact same error as run_training.py file contains other module files and they are not considering tf==1.15 instead they are considering as tf==2x.

**Comment by Salma1795** [comment]
> Hey @beachboy4545 , I found a way. Apparently you can install conda in colab. But, you have to activate your environment every time you want to use it. Follow this code blocks and you will achieve it:
> 
> Before everything, set pythonpath to nothing so you don't have conflicts.
> 
> ```
> %env PYTHONPATH = # /env/python
> ```
> 
> First, you get miniconda (I'm using miniconda with python 3.8 version, but you can change it). You have to keep the path '/usr/local' to make it work. Otherwise, colab will not recognize conda.
> 
> ```
> !wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.12.0-Linux-x86_64.sh
> !chmod +x Miniconda3-py38_4.12.0-Linux-x86_64.sh
> !./Miniconda3-py38_4.12.0-Linux-x86_64.sh -b -f -p /usr/local
> !conda update conda
> ```
> 
> Then, append this path to install packages.
> 
> ```
> import sys
> sys.path.append('/usr/local/lib/python3.8/site-packages')
> ```
> 
> Create your virtual environment with python version that matches TensorFlow 1.15 (3.6)
> 
> ```
> !conda create -n myenv python=3.6
> ```
> 
> Install TensorFlow 1.15
> 
> ```
> %%shell
> eval "$(conda shell.bash hook)"
> conda activate myenv
> pip install tensorflow==1.15
> ```
> 
> Run your python file. Remember to activate your virtual environment as suggested.
> 
> ```
> %%shell
> eval "$(conda shell.bash hook)"
> conda activate myenv
> python3 /content/test.py
> ```
> 
> Observations: As I mentioned, you have to activate your environment every time you need TensorFlow 1.15. Also, this approach works if you want to run python files. In my case this works. I hope this can help you too. Best regards!

I followed all these steps, but when I check the python version it doesn't show 3.6.. How can I solve this?
