### ISSUE TITLE
after pip upgrading pandas, the upgraded version is not available

### ISSUE THREAD

**Issue by moonshoes87** [googlecolab/colabtools#327]
Steps to reproduce:

- Open a new Python 3 notebook
- Reset all runtimes (if needed)
- Run the following cell: 
```
!pip install pandas --upgrade --no-deps
import pandas as pd
pd.__version__
```

- Output:
```
Collecting pandas
  Downloading https://files.pythonhosted.org/packages/e1/d8/feeb346d41f181e83fba45224ab14a8d8af019b48af742e047f3845d8cff/pandas-0.23.4-cp36-cp36m-manylinux1_x86_64.whl (8.9MB)
    100% |████████████████████████████████| 8.9MB 2.1MB/s 
Installing collected packages: pandas
  Found existing installation: pandas 0.22.0
    Uninstalling pandas-0.22.0:
      Successfully uninstalled pandas-0.22.0
Successfully installed pandas-0.23.4
'0.22.0'
```

As you can see, even though 0.23.4 has apparently been downloaded, it is not actually available.

**Comment by colaboratory-team** [comment]
If you have already imported pandas, you'll need to restart your Python process to pick up the new version. Use the 'Restart runtime' menu.

![image](https://user-images.githubusercontent.com/38081706/47824079-6ce24a80-dd28-11e8-980e-1e18aa50c32c.png)

**Comment by moonshoes87** [comment]
That is exactly what I did -- first restarted runtime, then upgraded pandas, then got the exact output I sent you.  There is a bug.

**Comment by moonshoes87** [comment]
Oh, sorry, you're saying restart the runtime after the pip install?  Perhaps that could be more clear in the documentation?
