### ISSUE TITLE
ipytree widget (+/-) toggles disappear after collapsing/expanding node

### ISSUE THREAD

**Issue by tylere** [googlecolab/colabtools#3270]
**Describe the current behavior**
After contracting and expanding a node of the ipytree widget, the subnodes no longer display their (+/-) toggles.

**Describe the expected behavior**
The subnodes should display their (+/-) toggles. This expected behavior works correctly in JupyterLab.

**What web browser you are using**
Chrome

**Additional context**
Notebook reproducing the issue:
https://colab.research.google.com/gist/tylere/572cc2a84baa4e90870a596d7f540a29/bug-ipytree-colab.ipynb#scrollTo=o89YK2wvzFsj

![bug_ipytree](https://user-images.githubusercontent.com/92862/205563673-520a3a32-6902-4516-860e-bd4ac4cf732b.gif)

**Comment by EvanWiederspan** [comment]
This should now be fixed in prod, let me know if it's not working for you
