### ISSUE TITLE
Bug when using TFLite - error message suggests sending info to colab support

### ISSUE THREAD

**Issue by FranciszekNowak** [googlecolab/colabtools#3272]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mco-gh** [comment]
Per the template, can you share a "Link to a minimal, public, self-contained notebook that reproduces this issue"?

**Comment by FranciszekNowak** [comment]
Misclick
