### ISSUE TITLE
Bug when using TFLite converter - error message suggests to send it to you

### ISSUE THREAD

**Issue by FranciszekNowak** [googlecolab/colabtools#3273]
I was trying to convert a standard model (properly defined, works just fine when trying to predict stuff) when I encountered this error:

```
WARNING:tensorflow:AutoGraph could not transform <function canonicalize_signatures.<locals>.signature_wrapper at 0x7f7981227160> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unknown node type <gast.gast.Expr object at 0x7f79811d2df0>
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

WARNING: AutoGraph could not transform <function canonicalize_signatures.<locals>.signature_wrapper at 0x7f7981227160> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unknown node type <gast.gast.Expr object at 0x7f79811d2df0>
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

```

I am using a book ,,TinyML: Machine Learning with TensorFlow on Arduino, and Ultra-Low Power Micro-Controllers ", which seems to be written by someone from TF development team.
I follow all the instructions from chapter 4.
If you are interested in my colab code, here it is:
[https://colab.research.google.com/drive/1eyqMB1POAZ9qw3lPCZkiyU7zfQ0Y1OxF#scrollTo=u26RmYUMC3Rw]
Any idea, any help?

**Comment by mco-gh** [comment]
Looks like the recommendation is to report this to the Tensorflow team, but this is the issues repo for the Colab team. I'd suggest posting this as a TF repo issue.
