### ISSUE TITLE
Python pdb.set_trace() does not work as expected in Google Colab

### ISSUE THREAD

**Issue by vtrandal** [googlecolab/colabtools#3279]
I'm attempting to use Python 3.8 built-in debugger (pdb) to single-step through Python code in a Jupyter notebook on Google Colab.

I'm expecting import pdb; pdb.set_trace() to stop program execution and show my Python source code with an arrow pointing to the next instruction to be executed without any errors or warnings of problems with the debugger or other debuggers. But instead I get this warning and only this warning (with no Source-Level debug with a pointer to the next instruction).

PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/usr/lib/python3.8/bdb.py", line 334, in set_trace
    sys.settrace(self.trace_dispatch)

> <ipython-input-2-6a33e76904da>(3)<module>()
-> print(i)

(Pdb)

Furthermore the (Pdb) prompt (or command-line) is not very useful, because if I give it the "where" command I don't get Source-Level debug with a pointer to the next instruction. Instead, I get output like this:
(Pdb) where
  /usr/lib/python3.8/runpy.py(194)_run_module_as_main()
-> return _run_code(code, main_globals, None,
  /usr/lib/python3.8/runpy.py(87)_run_code()
-> exec(code, run_globals)
  /usr/local/lib/python3.8/dist-packages/ipykernel_launcher.py(16)<module>()
...

(Chrome, Firefox, Safari, etc.)
I'm doing this work in Firefox 107.0.1.

 I have shared a small example to reproduce the problem here:
https://colab.research.google.com/gist/vtrandal/5f00abd3ebbcf61ca6c7ec719cff6095/untitled10.ipynb

**Comment by mco-gh** [comment]
I don't think pdb works in Jupyter notebooks in general, however, I  found a version called ipdb specifically made to work in a notebook. I tried it and, although  I still see those same warnings, it appears I am getting the expected debugger output, at least for a simple test. Can you try experimenting with ipdb and see if it works reasonably for you? Btw, I found [this article](https://zohaib.me/debugging-in-google-collab-notebook/) helpful.

**Comment by mco-gh** [comment]
ok, this is weird but with a bit more experimentation I found that if I quit the pdb session (respond 'q' to the pdb prompt) and re-run the cell *twice*, I stop seeing the warning. Obviously this is flaky but the two quits trick has been reproducible for me.
<img width="526" alt="Screen Shot 2022-12-09 at 09 18 34" src="https://user-images.githubusercontent.com/658327/206668247-7ffd77b9-fa00-432c-98e5-a47a1d124dba.png">

**Comment by vtrandal** [comment]
Marc,

Thank you for your suggestions. I am getting better results with ipdb
installed in Google Colab as follows:
!pip install ipdb

After the above step then the following test code works to some degree:
import ipdb
for i in range(0,5):
  ipdb.set_trace()
print(i)

If I get a warning then it does indeed help to respond with 'q' at the ipdb
prompt, and then run the cell again.

Thank you for your help,
Vincent

**Comment by mco-gh** [comment]
Cool, I'll close this for now.

**Comment by vtrandal** [comment]
Marc,

I'd like to report the source of my knowledge regarding the "pip install"
command for Jupyter notebook as coming from this link:
https://zohaib.me/debugging-in-google-collab-notebook/

They are doing the pip command as follows:
!pip install -Uqq ipdb

Again, thank you for your assistance. I am optimistic I can use this Python
debugger solution in my work on Google Colab.

Sincerely,
Vincent Randal

**Comment by mco-gh** [comment]
good to know, thanks, and glad you're able to use the debugger
