### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by larssl780** [googlecolab/colabtools#328]
Indentation is a nightmare. I know some part of this is inherited, but surely there's some way around it. I'd suggest a feature similar to sublime text, where you can backspace a row so it becomes part of the preceding row, then hit enter and the editor corrects the indentation for you.

**Comment by ericricky** [comment]
I'll also point out that Colab doesn't properly indent after one-liner if statements/for loops/functions/etc. For instance, typing
```
for i in range(10): print(i)
```
and hitting enter will open a newline with an extra level of indentation, even though it isn't syntactically valid.

**Comment by blois** [comment]
We've been working on changing the editor engine, the new one has a couple of fixes in this area. Details on enabling it are at https://colab.research.google.com/notebooks/editor_details.ipynb.

The indentation for this example looks correct, please let us know if there are other problematic ones.

```python
for i in range(10): print(i)
```
