### ISSUE TITLE
Colab should provide an alternative for Python 3.7

### ISSUE THREAD

**Issue by cloudvitamin** [googlecolab/colabtools#3280]
**Describe the current behavior**
Now that Colab has been updated to Python 3.8, it should provide an alternative for Python 3.7

**Describe the expected behavior**
Right now, the only alternative is Python 3.6 or 3.8

!sudo update-alternatives --config python3

There are 2 choices for the alternative python3 (providing /usr/bin/python3).

  Selection    Path                Priority   Status
------------------------------------------------------------
* 0            /usr/bin/python3.8   2         auto mode
  1            /usr/bin/python3.6   1         manual mode
  2            /usr/bin/python3.8   2         manual mode

**What web browser you are using**
Chrome

**Comment by Atotem** [comment]
https://github.com/googlecolab/colabtools/issues/3266#issuecomment-1348660900

**Comment by cperry-goog** [comment]
We are not able to support this, sorry.
