### ISSUE TITLE
Colab Pro+ response with GDrive is very slow

### ISSUE THREAD

**Issue by dsbyprateekg** [googlecolab/colabtools#3283]
I have bought Colab Pro+ to train a neural network model.
The first step is to mount the notebook with the drive but for the last 2 days, it has been taking too much to mount, and sometimes it gives errors like unable to connect to runtime.

If somehow it connects then it is taking 9+ hours only to scan the dataset.

The notebook ran without any issues only the first time and after that, it is creating these issues.

**Comment by michaeldoron59** [comment]
Same here.

**Comment by mco-gh** [comment]
Does [this faq](https://research.google.com/colaboratory/faq.html#drive-timeout) provide any insight?

**Comment by dsbyprateekg** [comment]
@mco-gh is anybody working on fixing this or this will be always an issue with large files?
It is only a suggestion for a paid service like colab+, there should be no such issue.

I bought this plan to train my neural network model and guess what now I am facing this notification to buy more compute-
![image](https://user-images.githubusercontent.com/30830541/207884268-a4c86482-313f-401a-8616-1e22476ee235.png)

For others, I suggest don't but pro+ service if you need to train a model which requires more memory and time because pro+ does not give you a guarantee to be in the same configuration at all time.

**Comment by cperry-goog** [comment]
No plans to update our Drive connection - if you have a large number of large files you'll want to explore other options.

**Comment by abdirahman1188** [comment]
I am facing the same problem. google colab pro+ is shit. it is not worth.
