### ISSUE TITLE
How to use Python 3.6 or 3.7 in Google Colab

### ISSUE THREAD

**Issue by hasanhut** [googlecolab/colabtools#3285]
**Describe the current behavior**
Google colab now uses python 3.8 and I want to use older versions of python. Although I tried many ways, I could not install python 3.7 or python 3.6 version.

**Describe the expected behavior**
I want to run 3.6 or 3.7 version of python on google colab as I am using old versions of tensorflow.

**What web browser you are using**
(Chrome)

**Comment by Atotem** [comment]
I propose a solution for this problem in this issue. I don't believe it's a Bug by the way.
#https://github.com/googlecolab/colabtools/issues/3266#issuecomment-1348660900
