### ISSUE TITLE
[BUG] Box-drawing characters are not rendered as monospace fonts

### ISSUE THREAD

**Issue by XuehaiPan** [googlecolab/colabtools#3289]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

Box-drawing characters are not rendered as monospace fonts. It looks around 1.7 times wider than the ASCII characters.

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/16078332/207591053-6a4c7ba8-b88c-4b03-8f76-6ca7199b143c.png">

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

Render the box-drawing characters with the same font width as other characters.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
This looks like an issue with your system font - you can change your font using your browser's fixed width font setting. I'm not able to repro with my default system fonts myself.
