### ISSUE TITLE
How to set higher shared memory to avoid RuntimeError: DataLoader worker (pid 13) is killed by signal: Bus error in PyTorch

### ISSUE THREAD

**Issue by discdiver** [googlecolab/colabtools#329]
Using pytorch 1.0 Preview with FastAI v1.0 in Colab. 

Often get `RuntimeError: DataLoader worker (pid 13) is killed by signal: Bus error. ` for more memory intensive tasks (nothing huge).

Looks like a shared memory issue:
https://github.com/pytorch/pytorch/issues/5040#issue-294274594

https://github.com/pytorch/pytorch/issues/2244#issuecomment-318864552

> Looks like the shared memory of the docker container wasn't set high enough. Setting a higher amount by adding --shm-size 8G to the docker run command seems to be the trick as mentioned here. 

Can you please set the shared memory of the docker container higher or tell me how I can do it manually?

**Comment by colaboratory-team** [comment]
Thanks for the note. Can you share a notebook that reproduces the problem? We'll take a closer look.

**Comment by colaboratory-team** [comment]
A fix should be rolling out tomorrow. We'll keep this issue updated.

**Comment by csinguva** [comment]
Is this resolved?

**Comment by zhao181** [comment]
Is this solved?

**Comment by ahmedsnoun** [comment]
Is this resolved please, I still get this error.

**Comment by snudurupati** [comment]
I got a similar error when running Colab with my local NVIDIA GeForce RTX 3080. I tried increasing Docker's shared memory size using the  `--shm-size` flag and that mitigated the error.
This is the command I used:` docker run --gpus=all --shm-size 13G -p 127.0.0.1:9000:8080 us-docker.pkg.dev/colab-images/public/runtime`
