### ISSUE TITLE
Saving is not working well over past week

### ISSUE THREAD

**Issue by larssl780** [googlecolab/colabtools#3293]
Has new code been pushed recently? A couple of times now over the last week my changes have been discarded (I use colab quite a lot and I have never seen these issues before), so when I go back to the notebook the next day, I have to rewrite the code that was already there. I now save the notebooks manually and upload them to google drive, which is quite tedious.

**Comment by cperry-goog** [comment]
No changes we're aware of, but we'll keep an eye out.
