### ISSUE TITLE
Describe the current behavior

### ISSUE THREAD

**Issue by 5560405930** [googlecolab/colabtools#3294]
@colaboratory-team 
While trying to open any colab notebook from chrome browser it does not load. Gives a blank page with message "Loading"
I have attached the error from console. I don't face with same issue on edge browser and the notebook loads without any issue.

On chrome, I face the same issue while creating a new notebook and I have tried with incognito as well but the notebooks don't load.

What web browser you are using
Chrome and fire fox

**Comment by cperry-goog** [comment]
I don't see the attached error - can you attach that?

**Comment by 5560405930** [comment]
This problem has been happening to me for several days and updating the browsers did not solve the problem
![Capture](https://user-images.githubusercontent.com/76905723/207954613-a848e1ed-fc0d-42bc-b9a4-7d615d93ee92.jpg)

**Comment by EvanWiederspan** [comment]
It's difficult to help without more data, can you attach the errors from the console that you mentioned?

**Comment by 5560405930** [comment]
It gives me this error
apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.WEPncdil2Uw.O/m=client/exm=gapi_iframes,googleapis_client/rt=j/sv=1/d=1/ed=1/rs=AHpOoo-eOecLLtOXEl3I3kIuMsKXRkDMmA/cb=gapi.loaded_1:1   
Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.WEPncdil2Uw.O/m=gapi_iframes,googleapis_client/rt=j/sv=1/d=1/ed=1/rs=AHpOoo-eOecLLtOXEl3I3kIuMsKXRkDMmA/cb=gapi.loaded_0:1          
Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

**Comment by cperry-goog** [comment]
We're guessing there's some browser extension issue here - can you reproduce in an incognito window?
