### ISSUE TITLE
Provide terminal access on custom GCE VM runtimes without Colab Pro subscription

### ISSUE THREAD

**Issue by aihgii** [googlecolab/colabtools#3295]
Colab still requires the pro subscription to use built-in terminal when running on a custom GCE VM, which just doesn't feel right.

**Comment by cperry-goog** [comment]
Hey this is a good idea, we've made some progress on this, will land when we can. Tracking this internally at b/241256395

**Comment by aihgii** [comment]
That's great, thanks!

Just in case someone's looking for a workaround:

1. Connect to your VM using [SSH](https://cloud.google.com/compute/docs/instances/ssh)
2. Connect to the container using `docker container exec -it k_default /bin/bash`
2.5. In some cases you can get a permission error, then run `sudo usermod -aG docker <username>` and go back to the second step

**Comment by blois** [comment]
This should now be working.
