### ISSUE TITLE
tf-nightly-gpu crash and restarting

### ISSUE THREAD

**Issue by tigerneil** [googlecolab/colabtools#33]
When I test tfe in colab, I came across the following problem:

```pip install tf-nightly-gpu```

`import tensorflow as tf` ===> crash and restarting

can not use latest tf... why?

**Comment by fischman** [comment]
tf-nightly-gpu is built against libcublas/libcudart/etc version 9.0, but colab's runtimes have version 8.0 to match the 1.4 tensorflow release.

**Comment by bhack** [comment]
Is this solvable now?
