### ISSUE TITLE
Collab Compute Units gone!!! suddenly from 500 to 198? what's wrong?

### ISSUE THREAD

**Issue by elkabbara** [googlecolab/colabtools#3301]
On November 15 I bought subscribed to google Collab pro with 500 units, today November 17 more than half of the points are gone. can you please help me with this issue?

**Comment by cperry-goog** [comment]
You can submit in-product feedback and reference this issue and I'll take a look when I get a chance. It is almost certainly the result of large GPU assignments in your history.
