### ISSUE TITLE
can remove entire system easily 

### ISSUE THREAD

**Issue by RIZAmohammadkhan** [googlecolab/colabtools#3303]
**using simple bash and  rm  i am able to remove and crash the program.**

**Comment by RIZAmohammadkhan** [comment]
[https://drive.google.com/file/d/1jx4ceZpHnZ7wuJDhZOXulWBZt7bIduRK/view?usp=sharing](url)

**Comment by RIZAmohammadkhan** [comment]
similarly able to do anything with the help of bash

**Comment by cperry-goog** [comment]
You probably don't want to do that. We give you extreme flexibility to get work done in Colab.
