### ISSUE TITLE
Can not import modules from Forecast SW

### ISSUE THREAD

**Issue by ssoulhi** [googlecolab/colabtools#331]
![image](https://user-images.githubusercontent.com/28113585/47954335-ae106f80-df5f-11e8-9ba7-8458443e43c0.png)

**Comment by craigcitro** [comment]
Are you sure there's a `utils` module? Looking at the github repo linked [from PyPI](https://pypi.org/project/forecast/), there's not a lot of code in [that package](https://github.com/BlackPoint-CX/forecast).

**Comment by ssoulhi** [comment]
Since this library is not documented, I Have decided not to use it anymore
