### ISSUE TITLE
syntax highlighting error in jupyter notebook when using %%writefile

### ISSUE THREAD

**Issue by jjurm003** [googlecolab/colabtools#3313]
**Describe the current behavior**
With the %%writefile magic working well,
only the script editor of jupyter notebook 
works with no syntax highlighting as below
![image](https://user-images.githubusercontent.com/43165118/209075211-6de4ef8a-66e5-42c6-a426-c0d8a7ae88b3.png)

**Comment by cperry-goog** [comment]
We don't provide syntax highlighting for %%writefile

You could also try an alternate approach:

from google.colab import files
files.view(YOUR_FILENAME)
