### ISSUE TITLE
NeMo introduction example ... (sorry if reported already, search didnt reveal)

### ISSUE THREAD

**Issue by loisl1** [googlecolab/colabtools#3315]
first cell:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.9.2 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible.
tensorflow 2.9.2 requires tensorboard<2.10,>=2.9, but you have tensorboard 2.11.0 which is incompatible.

second cell doesnot fullfill:
AttributeError                            Traceback (most recent call last)

[/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in _dep_map(self)
   3015     PKG_INFO = 'METADATA'
-> 3016     EQEQ = re.compile(r"([\(,])\s*(\d.*?)\s*([,\)])")
   3017 

25 frames

AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)

AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)

[/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in _get(self, path)
   1609     def _listdir(self, path):
   1610         return os.listdir(path)
-> 1611 
   1612     def get_resource_stream(self, manager, resource_name):
   1613         return open(self._fn(self.module_path, resource_name), 'rb')

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/Pygments-2.6.1.dist-info/METADATA'

thanks, bye

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
Looked into this a bit, it seems that the NeMo introduction has a listed dependency on [tensorboard](https://github.com/NVIDIA/NeMo/blob/v1.14.0/requirements/requirements.txt#L9) but not tensorflow, so when it installs it can end up with an unsupported version of tensorflow. I'd recommend filing an issue on their [Github component](https://github.com/NVIDIA/NeMo/issues) to update their dependencies.

**Comment by EvanWiederspan** [comment]
Dug some more, it looks like pinning some packages before installing NeMo might work. Try replacing whatever cell pip installs nemo_toolkit with the following:

```
%%shell
apt-get update && apt-get install -y libsndfile1 ffmpeg
# pip install Cython tensorflow==2.11.0 nemo_toolkit[all]==1.13.0
pip install Cython tensorflow==2.11.0 Pygments==2.6.1 nemo_toolkit[all]
```
