### ISSUE TITLE
ROBBERY FROM COLAB

### ISSUE THREAD

**Issue by Tezcan98** [googlecolab/colabtools#3317]
NO ONE CAN EXPLAIN THIS AND NOTHING IS CARE ! 

I BOUGHT COLAB PRO AND AFTER SOME USAGE IT RECOMMEND PRO+. NOW I CANNOT USE GPU !

**Comment by cperry-goog** [comment]
I can't diagnose resource issues from GitHub, you'll need to submit in product feedback.
