### ISSUE TITLE
Colab unexpectedly gets stuck and hangs after executing input() function

### ISSUE THREAD

**Issue by shanydo** [googlecolab/colabtools#3318]
**Describe the current behavior**
Colab unexpectedly gets stuck after executing input() function, e.g.: input("What is your name? "). 
I am using Colab free version.
This is inconsistent: sometimes it works well but often it gets stuck. It happens on different computers, different times of the day, different users, different networks.... I couldn't find a "rule".

When it happens, the "play" button never stops turning, and the field for typing the input *does not show*.
I can wait for many minutes and it will keep "running".

No problem with other commands at the same time *on the same code cell*, e.g. print() command - it runs well and fast.
It only happens with input command.

When it happens and Colab gets stuck, the only thing to do is to interrupt execution and re-run the cell.
Usually after 1-2 re-tries, the input command will run OK.

**What web browser you are using**
Chrome

**Comment by EvanWiederspan** [comment]
This seems like a similar issue to https://github.com/googlecolab/colabtools/issues/2889. We're tracking this internally as b/237585599, going to close this as duplicate and follow up on the other issue when we have a fix out
