### ISSUE TITLE
Midas Function

### ISSUE THREAD

**Issue by Ralph717** [googlecolab/colabtools#3319]
I have been trying for 3 days to run Disco and it always stops when it reaches some level of input, usual 32S but sometimes it is 42S,.  When I examine it and look for the error it says that the Midas function is not found or that python is not there or some other error in that string of code.  I have sent numerous bug reports and many other emails, as much as is possible given the nature of how the system works.  What can I do now.*
**What web browser you are using** Firefox, 

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by rupertchesman** [comment]
Hi,
I had the same issue, this fixed it for me:
https://www.youtube.com/watch?v=tIo0b0YJ2GA&list=PLtlQp_2-5lTLjeNvHU23NNW_OGtPtm52K&index=41

Regards,
Rupert

**Comment by Ralph717** [comment]
Thank you for that.  I had found the fix by poling at the headings on teh
top and this revealed the video with the fix.  Why do they build things
like that?  It worked for a long time then suddenly it started to give
these error messages and it took me about 4 days to get through the various
postings etc.  Thank you

Al
