### ISSUE TITLE
Unable de create new notebook with company pc

### ISSUE THREAD

**Issue by samirmebrek** [googlecolab/colabtools#3321]
**Describe the current behavior**
I'm trying to log into my college account with a company pc. When I click on a new notebook, I get an error message: Could not load coLaboratory
![colab_newfile](https://user-images.githubusercontent.com/81355315/209830836-2da182a6-f032-45ab-97a7-7662bd3737be.PNG)
![colab_upload](https://user-images.githubusercontent.com/81355315/209830838-509c30b0-fe9a-4dc9-ab3a-822424eec9cf.PNG)

**Describe the expected behavior**
A blank page for a new job

**What web browser you are using**
Chrome and Edge

**Comment by EvanWiederspan** [comment]
It's possible that either your company that owns the PC or the college that manages your account has restrictions up that are interfering with loading Colab. Are you able to access it with a different account, or with the same account on a different machine?

**Comment by EvanWiederspan** [comment]
It may also be interference from a Chrome extension, does it work for you in incognito mode?

**Comment by samirmebrek** [comment]
> It's possible that either your company that owns the PC or the college that manages your account has restrictions up that are interfering with loading Colab. Are you able to access it with a different account, or with the same account on a different machine?

Thank you for your response. Yes, colab works with my personal computer with the same account (school account)

**Comment by samirmebrek** [comment]
> It may also be interference from a Chrome extension, does it work for you in incognito mode?

It's not working with in incognito mode also.

**Comment by cperry-goog** [comment]
This looks like an admin policy on your company PC, I don't think we can resolve.
