### ISSUE TITLE
Error on Run using Deforum_Stable_Diffusion

### ISSUE THREAD

**Issue by plAItime** [googlecolab/colabtools#3322]
**Describe the current behavior**
Using Deforum and I get an error at RUN:

outdir = get_output_folder(output_path, batch_name)

**Describe the expected behavior**
I didn't expect an error and in settings there is nowhere to set output folder. I'm new to all this and hope this is the correct way to explain the issue.

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
Colab doesn't own the Deforum notebook, and don't know which one that is referring to. If you found it from Github, I would recommend filing an issue on the owner's Github page instead
