### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by cevparlak** [googlecolab/colabtools#3326]
**Describe the current behavior**
I'm a Colab pro+ subscriber. When I use standard GPU and standard runtime it still consumes my compute units.

**Describe the expected behavior**
In standard GPU and standard runtime no compute units must be spent.

**What web browser you are using**
(Chrome and Firefox)

**Comment by cperry-goog** [comment]
This is expected, your compute units are consumed first and when you've consumed all you fall back to our free of charge tier quota system.
