### ISSUE TITLE
Upgrade to Ubuntu 20.04

### ISSUE THREAD

**Issue by metrizable** [googlecolab/colabtools#3327]
### Upgrade to Ubuntu 20.04

Since Ubuntu 18.04 LTS ([Bionic Beaver](https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes)) is nearing its [support deadline](https://wiki.ubuntu.com/Releases), in order to ensure our users are on a supported distribution, Colab has upgraded to Ubuntu 20.04 LTS ([Focal Fossa](https://wiki.ubuntu.com/FocalFossa/ReleaseNotes)). Refer to the [Ubuntu lifecycle and release cadence](https://ubuntu.com/about/release-cycle) for more information. This upgrade includes a refreshed toolchain to `glibc 2.31` and `gcc 9.4.0`, and other version bumps such as `cmake 3.16.3`, `ffmpeg 4.2.7`, `gdal 3.0.4`, `graphviz 2.42.2`, `libboost 1.71.0`, and `libtesseract4 4.1.1`.

#### Colab’s fallback runtime version

Using the fallback runtime version temporarily allows access to the last version of the runtime before the upgrade described above, and is available until late-January. Its purpose is to provide a temporary mechanism for users to more smoothly upgrade their notebooks to be compatible with Colab’s current runtime version. This is available from the Command Palette via the "Use fallback runtime version" command when connected to a runtime. Of note, this setting does not persist across sessions – the command will need to be invoked on each new session.

**Comment by TonyMontana98** [comment]
It's seems like every software thingy is out of date on Colab. Hope it's going to be updated soon...

**Comment by chadbrewbaker** [comment]
There are *severe* ARM bugs in 20.04 which were cured in 22.04 that crippled those with Rust toolchains https://project-oak.github.io/rust-verification-tools/2021/08/22/rust-on-linux-1.html

I'm not aware a patch has been back ported. Wise to bump to 22.04 with older toolchain versions like gcc-9 whatever available or this will be hell for years more.

**Comment by chadbrewbaker** [comment]
@tlringer could you escalate so someone gets responsibility/opportunity of remediating Colab bitrot? Colab is the #1 marketing tool that GCP has - huge ROI by keeping it a better dev experience than competitor AWS Sagemaker.

**Comment by francesco-ballarin** [comment]
> Colab will upgrade to Ubuntu 20.04 LTS

@metrizable when will the upgrade happen? Will all runtimes be upgraded at the same time, or will it be gradual? Thanks!

**Comment by metrizable** [comment]
@francesco-ballarin The upgraded runtime based on Ubuntu 20.04 LTS should be available now for new sessions.

We have several upgrades planned in the near future to bring our ecosystem of OS distribution, Python version, drivers, libraries, and Python packages to a more contemporary set of versions. Stay tuned!

**Comment by johnnynunez** [comment]
why not 22.04 lts?
