### ISSUE TITLE
I used this account to pay for Google Colab Pro, but it didn't work

### ISSUE THREAD

**Issue by heysep** [googlecolab/colabtools#3329]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by heysep** [comment]
I used this account to pay for Google Colab Pro, but it was not applied.
I paid and the money came out, but it doesn't appear in the payment history, so I ask how to get a refund.

I ran the GPU accelerator and paid for the pro, so I wanted quick action execution.

**Comment by EvanWiederspan** [comment]
For Colab Pro refunds, you can reach out to colab-billing@google.com; we can't process refunds over Github
