### ISSUE TITLE
Cell output height is wrong

### ISSUE THREAD

**Issue by guy1ziv2** [googlecolab/colabtools#333]
After installing folium on Colab, I use this code to add a map

import folium
m = folium.Map(location=[45.5236, -122.6750],height=400)
m

However, the cell output size is inaccurate, leaving a lot of whitespace under the map and is not changing if the map height is different. 

Is this a Colab issue ? it may be a folium problem, but I could not find out...

**Comment by blois** [comment]
Here's an example of different ways to resize the output:
https://colab.research.google.com/gist/blois/864fb714422138e6d5e20ad62b7cf996/output_sizing.ipynb
