### ISSUE TITLE
The filesystem doesn't update to show the output of a command for linux command line.

### ISSUE THREAD

**Issue by shyamalschandra** [googlecolab/colabtools#3330]
I am using Yandex browser and I am expecting to have the filesystem display the updated set of files in the directory.  It doesn't.  What do I do?

**Comment by mayankmalik-colab** [comment]
Unfortunately, I couldn't replicate it. It worked just fine for me on Yandex browser as well. I just created a simple file and saved it. The filesystem displayed it correctly and I was able to read it it just fine. 

Can you provide a minimal repro notebook that explains the issue?
