### ISSUE TITLE
how to file in product feedback for google colab

### ISSUE THREAD

**Issue by karkir0003** [googlecolab/colabtools#3331]
hey, i made a suggestion as to how I think google colab could be better. the response I got from a contributor said to file "in-product feedback". What's the link for doing that? @colaboratory-team @eric-wieser @craigcitro @yilei

**Comment by craigcitro** [comment]
`Help` -> `Send feedback` 

Or: open the command palette (ctrl-shift-p), type "feedback", and hit enter.
