### ISSUE TITLE
I loose GPU device when I restart the rutime.

### ISSUE THREAD

**Issue by RituYadav92** [googlecolab/colabtools#3332]
I am using colab pro. I can connect to GPU device and it is working perfectly. But I have to do some tf installation and restart runtime after the installation. Restart runtime lose GPU device and connect to CPU device instead.
How do I solve this ?

Issue replication 

1) connect to GPU runtime
2) run : 
!pip install tensorflow==2.4.0
3) restart runtime
4) check the connected device by code:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

**Comment by mayankmalik-colab** [comment]
Actually, you don't lose the GPU runtime. Most likely when you do `!pip install tensorflow==2.4.0`, there is a dependency conflicts. You could see them in red at the bottom. Hence, the behavior is sometimes not as expected.

You can confirm the above by installing `2.7.0` version instead. It would just run fine. So, can any of the latest TF versions work for you ?

**Comment by RituYadav92** [comment]
How do I use tensorflow==2.4.0 on colab?

**Comment by cperry-goog** [comment]
TensorFlow 2.4 has conflicts with other packages so it's not possible to use that version in Colab. We don't intend to support earlier versions of TensorFlow.
