### ISSUE TITLE
Nvidia drivers are too old. Please update for Optix support

### ISSUE THREAD

**Issue by TonyMontana98** [googlecolab/colabtools#3333]
This driver is pretty old and do not support Optix, which the newer Nvidia drivers (ver. 470 and newer) for the Tesla T4 are capable of.
I tried to update the Nvidia driver with a added repository, but this failed, as i had not enough priviledges (for a reboot) to do this.

Update the drivers up-to-date

Blender require at least a ver470 (or newer) Nvidia driver for Optix support.

**Comment by mayankmalik-colab** [comment]
Thanks for the feedback. We will be upgrading Nvidia drivers in the future soon. Stay tuned!

**Comment by EvanWiederspan** [comment]
Drivers have been updated to 510
