### ISSUE TITLE
error

### ISSUE THREAD

**Issue by aarnica** [googlecolab/colabtools#3334]
AttributeError                            Traceback (most recent call last)
[<ipython-input-34-218568eaa99c>](https://localhost:8080/#) in <module>
      1 # add the image path
----> 2 test_image = image.load_img('waste1.png', target_size = (64, 64))

AttributeError: module 'keras.preprocessing.image' has no attribute 'load_img'

**Comment by mayankmalik-colab** [comment]
You can try `tf.keras.utils.load_img` instead. Check the [official page](https://www.tensorflow.org/versions/r2.9/api_docs/python/tf/keras/utils/load_img).

**Comment by aarnica** [comment]
![Annotation 2023-01-13 170859](https://user-images.githubusercontent.com/122379455/212312067-86c1cf10-da93-4bd1-9dfe-03a17048369e.png)
