### ISSUE TITLE
Picture display error

### ISSUE THREAD

**Issue by daserpey** [googlecolab/colabtools#3335]
**Describe the current behavior**
When uploading my own fits images, it say that is downsampling and the image is not displayed correctly. As a consequence I cannot enter the pixel coordinates

**Describe the expected behavior**
I expected to upload a readable image

**What web browser you are using**
Firefox

![Screenshot_20230111_182830](https://user-images.githubusercontent.com/122475013/211876657-59497b52-9c61-4cd5-a9b6-73ae5ca8aa69.png)

**Comment by cperry-goog** [comment]
I'm guessing this is the library you're using, but can you share a minimal repro notebook?
