### ISSUE TITLE
precompiled wheel no longer working

### ISSUE THREAD

**Issue by antispamtutoruser123** [googlecolab/colabtools#3336]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.14.1+cu116 requires torch==1.13.1, but you have torch 1.13.0 which is incompatible.
torchtext 0.14.1 requires torch==1.13.1, but you have torch 1.13.0 which is incompatible.
torchaudio 0.13.1+cu116 requires torch==1.13.1, but you have torch 1.13.0 which is incompatible.

**Comment by mayankmalik-colab** [comment]
We are already on torch `1.13.1` . Most likely your notebook tried installing some packages that accidentally changed the torch version to `1.13.0`. Can you confirm or share the min repro notebook.
