### ISSUE TITLE
Not able to copy images directly from output tabs 

### ISSUE THREAD

**Issue by Monk5088** [googlecolab/colabtools#3338]
Hey author, developers,
I am using colab for a long time and it was easy when i could directly copy-paste images from the output tab, but now when i copy images from the output of the cell, it doesn't get copied instead just a blank space is copied, I would request you to kindly update it back to the older setting where copying images from output of notebook was easy.
Thanks and regards,
Harshit

**Comment by cperry-goog** [comment]
Just tested: I can copy a chart in Colab and paste it into another tab. Can you test this in an incognito window? You might have a browser extension mucking with this.

**Comment by Monk5088** [comment]
Okay thanks, it's working now.
And I didn't use incognito, I think that bug was resolved.
