### ISSUE TITLE
Run cell buttons are no longer floating when scrolled

### ISSUE THREAD

**Issue by martinjbaker** [googlecolab/colabtools#3339]
**Describe the current behavior**
The Run Cell button is now stuck to the top of the cell. This means they are no longer visible when cells are scrolled. This is quite annoying compared with previous behavior. This has changed at some point in the last few weeks.

**Describe the expected behavior**
Previously the Run Cell button remained visible at the top of the screen so you could easily see if it was currently running or not.

**What web browser you are using**
Safari Version 16.1 (18614.2.9.1.12)

**Comment by blois** [comment]
This can happen as a performance improvement if the notebook has more than 100 cells. The way Chrome renders the floating run button adds performance overhead which can add milliseconds of overhead to every key press if there are too many of them.

We've made performance improvements elsewhere which may allow this number to be increased.
