### ISSUE TITLE
History view only shows latest revision

### ISSUE THREAD

**Issue by mamcgrath** [googlecolab/colabtools#334]
Although notebook history is kept, only the latest revision is viewable. The 'view' button opens a new window, but shows the latest notebook revision rather than the earlier revision. It is possible to download revisions of notebooks and view them outside of colab.

**Comment by colaboratory-team** [comment]
Thank you for the report.

Could you give more details? I've not been able to reproduce the issue as you describe it. I did the following:

1) Open a new notebook
2) Make several changes, saving along the way
3) Open the revision history pane, and click "View" on an earlier revision

The result  is a new tab that correctly displays the earlier revision.

**Comment by mamcgrath** [comment]
Thank you for the quick response.

I do the same things, but seem to be getting a different result.

1. Open a new notebook.
2. Make several changes and run code blocks, I did not explicitly save. 
3. Open revision history pane from "File" menu, and click on an earlier revision.

The result is a new tab displays the latest version. There is an icon of a stiffy disk with a line through it near the title.

**Comment by colaboratory-team** [comment]
Hi - could you share the notebook where you see this behavior?

> There is an icon of a stiffy disk with a line through it near the title.

That is intended. Revisions are opened as read-only views.
