### ISSUE TITLE
Custom GCE VM runtimes stopped working

### ISSUE THREAD

**Issue by aihgii** [googlecolab/colabtools#3340]
Colab cannot connect to custom runtimes today (after restart). Creating a new deployment from the marketplace doesn't work either.

I'm not even able to connect to a newly created VM using SSH.

**Comment by mco-gh** [comment]
> I'm not even able to connect to a newly created VM using SSH.

That part suggests an underlying problem in Compute Engine or Marketplace. I'll check and see if there's a known issue there.

**Comment by blois** [comment]
I just validated that I was able to connect to an old one as well as a newly created one.

**Comment by aihgii** [comment]
It works now. Redeployed again and successfully connected to the runtime.
