### ISSUE TITLE
Loading PyTorch Model to Device Works on Free GPU but Not Premium GPU

### ISSUE THREAD

**Issue by BananaLee** [googlecolab/colabtools#3341]
**Describe the current behavior**
Sending a PyTorch model to the Cuda Device takes forever (probably infinite loop?) on Premium GPU, but works fine on the Free GPU

**Describe the expected behavior**
I expect the Premium GPU to be at least the same speed as the Free GPU if not faster

**What web browser you are using**
Chrome

**Additional context**
[Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.](https://drive.google.com/file/d/1OFhPIFDXywBUVNP2gRhXDdyNbvikL-On/view?usp=sharing)
 - Issue occurs on the line `model = train_cnn(smoke_test=True)  # just a quick run to check everything is working`. On Free GPU time, it works very fast (as expected since it's just a smoke test), but I've burned out 6 computing units on the smoke test at Premium GPU for no movement.

**Comment by EvanWiederspan** [comment]
This will be hard to diagnose from Github, please submit feedback in product within Colab at Help > Send feedback
