### ISSUE TITLE
error

### ISSUE THREAD

**Issue by aarnica** [googlecolab/colabtools#3342]
![Annotation 2023-01-13 163500](https://user-images.githubusercontent.com/122379455/212306791-cd9003ae-df3a-47d1-a30c-8d359c9d9539.png)

**Comment by mco-gh** [comment]
I'm betting there's a cell above that one which imports tensorflow as tf and your backend has timed out or otherwise restarted. Please try rerunning the notebook from the top to make sure you have installed all required dependencies.
