### ISSUE TITLE
Unable to use file.read() command for text (byte string format) file

### ISSUE THREAD

**Issue by sqali** [googlecolab/colabtools#3352]
**Describe the current behaviour**

If we want to read a text file that is present in the byte string format, we are unable to use the file.read() function by using the below code:

path = "/document/file.txt"

f=open(path,'r')

print(f.read())  # This line throws the error, I have attached the screenshot below

However, if I use f=open(path, "rb") in the below piece of code, it works.

**Describe the expected behaviour**
 
However, in local text editors, this problem does not occur when using the below piece of code:

path = "path_of_file"

f=open(path,'r')

print(f.read())

**What web browser are you using**

I am using Chrome Browser.
![Expected Behaviour](https://user-images.githubusercontent.com/66676360/213356884-6aea494c-45ae-4781-ac1d-99f1a84f96ae.png)
![Work Around](https://user-images.githubusercontent.com/66676360/213356894-f5d625fb-6653-433f-8eb4-b622c15c41ac.png)
![Current Problem](https://user-images.githubusercontent.com/66676360/213356896-0a752618-0b89-445d-a740-78e41af0bf49.png)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by sqali** [comment]
I have figured out that it is actually throwing an error because UTF-8 cannot decode the symbol - "ÿ" at the 11597th position as mentioned in the error comment. Is there any way we could resolve it or work around this?

**Comment by sqali** [comment]
Would really appreciate if someone can guide me to resolve this issue.

**Comment by mayankmalik-colab** [comment]
I believe reading in binary mode ` f=open(path, "rb")` would be a better solution in this case. I am not sure why don't you want to use `rb` if that works?

**Comment by sqali** [comment]
Hi @mayankmalik-colab,

I need to convert the byte string format to normal string format text. But I am unable to do so even after using the function str() as it still retains the b"" in front of the string.

**Comment by mco-gh** [comment]
Try this:  https://stackoverflow.com/a/606199
