### ISSUE TITLE
htmltools can't be unloaded or updated

### ISSUE THREAD

**Issue by AbdurrahmanMN** [googlecolab/colabtools#3355]
upon using R in colab by https://colab.research.google.com/notebook#create=true&language=r
```
#Fitting our model with brms to the multiple imputed data sets
library(brms)
fit_imp1 <- brm_multiple(bmi ~ age*chl, data = imp, chains = 2)
```
as shown here: https://cran.r-project.org/web/packages/brms/vignettes/brms_missings.html
gives:
```

Error: package or namespace load failed for ‘brms’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘htmltools’ 0.5.3 is already loaded, but >= 0.5.4 is required
Traceback:

1. library(brms)

2. tryCatch({
 .     attr(package, "LibPath") <- which.lib.loc
 .     ns <- loadNamespace(package, lib.loc)
 .     env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)
 . }, error = function(e) {
 .     P <- if (!is.null(cc <- conditionCall(e))) 
 .         paste(" in", deparse(cc)[1L])
 .     else ""
 .     msg <- gettextf("package or namespace load failed for %s%s:\n %s", 
 .         sQuote(package), P, conditionMessage(e))
 .     if (logical.return && !quietly) 
 .         message(paste("Error:", msg), domain = NA)
 .     else stop(msg, call. = FALSE, domain = NA)
 . })

3. tryCatchList(expr, classes, parentenv, handlers)

4. tryCatchOne(expr, names, parentenv, handlers[[1L]])

5. value[[3L]](cond)

6. stop(msg, call. = FALSE, domain = NA)
```
I failed to unload/detach the package htmltools as other packages depend on it.
Is there a way to run this smoothly?
Thank you

**Comment by AbdurrahmanMN** [comment]
upon using R in colab by https://colab.research.google.com/notebook#create=true&language=r
```
#Fitting our model with brms to the multiple imputed data sets
library(brms)
fit_imp1 <- brm_multiple(bmi ~ age*chl, data = imp, chains = 2)
```
gives:```

Error: package or namespace load failed for ‘brms’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘htmltools’ 0.5.3 is already loaded, but >= 0.5.4 is required
Traceback:

1. library(brms)

2. tryCatch({
 .     attr(package, "LibPath") <- which.lib.loc
 .     ns <- loadNamespace(package, lib.loc)
 .     env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)
 . }, error = function(e) {
 .     P <- if (!is.null(cc <- conditionCall(e))) 
 .         paste(" in", deparse(cc)[1L])
 .     else ""
 .     msg <- gettextf("package or namespace load failed for %s%s:\n %s", 
 .         sQuote(package), P, conditionMessage(e))
 .     if (logical.return && !quietly) 
 .         message(paste("Error:", msg), domain = NA)
 .     else stop(msg, call. = FALSE, domain = NA)
 . })

3. tryCatchList(expr, classes, parentenv, handlers)

4. tryCatchOne(expr, names, parentenv, handlers[[1L]])

5. value[[3L]](cond)

6. stop(msg, call. = FALSE, domain = NA)
```
I sailed to unload/detach the package htmltools as other packages depend on it.
Is there a way to run this smoothly?
Thank you

**Comment by metrizable** [comment]
@AbdurrahmanMN Thanks for using Colab. I understand from the issue description that you are unable to load `brms` as per the [brms_missings vignette](https://cran.r-project.org/web/packages/brms/vignettes/brms_missings.html). I went ahead and tried this vignette out, but I could not reproduce your error:

![A2MeY4R8QFKfZCv](https://user-images.githubusercontent.com/65414824/214924660-49fc0eb3-dcd6-4448-b5a5-49c2b3903e41.png)

Can you provide a minimal repro notebook?

If you are trying to unload `htmltools` and still use `brms`, you may have difficulties, since `brms` has a transitive dependency on it (through `shiny`).

**Comment by AbdurrahmanMN** [comment]
> @AbdurrahmanMN Thanks for using Colab. I understand from the issue description that you are unable to load `brms` as per the [brms_missings vignette](https://cran.r-project.org/web/packages/brms/vignettes/brms_missings.html). I went ahead and tried this vignette out, but I could not reproduce your error:
> 
> ![A2MeY4R8QFKfZCv](https://user-images.githubusercontent.com/65414824/214924660-49fc0eb3-dcd6-4448-b5a5-49c2b3903e41.png)
> 
> Can you provide a minimal repro notebook?
> 
> If you are trying to unload `htmltools` and still use `brms`, you may have difficulties, since `brms` has a transitive dependency on it (through `shiny`).
Thank  you so much.
Now htmltools version  is updated on colab  ‘0.5.4’and the file ran smoothly..
