### ISSUE TITLE
не могу войти в приложение automatic 1111 через google colab, в блоке 

### ISSUE THREAD

**Issue by KoffeSoLdom** [googlecolab/colabtools#3358]
В блоке Run script выдаётся ошибка и не появляется ссылка на приложение automatic 1111. 
![ошибка](https://user-images.githubusercontent.com/123305632/213917363-4d9981b6-a058-4d1b-8095-375cb92bfebc.png)
ссылка на страницу
https://colab.research.google.com/github/ddPn08/stable-diffusion-webui-colab/blob/main/automatic1111.ipynb?hl=ru&authuser=3#scrollTo=Y4ebYsPqTrGb

**Comment by EvanWiederspan** [comment]
This seems like an issue with the notebook rather than with Colab, I would recommend reaching out to the notebook author on Github
