### ISSUE TITLE
trouble with infer speech from audio

### ISSUE THREAD

**Issue by fobbed** [googlecolab/colabtools#3359]
Whenever I run the cell for "Infer speech from audio" it will get close to the end of the execution and then fail and provide the error below.

I was playing with this yesterday and it was able to process just fine without any issues and move on to the next cell. I'm not sure what has changed or if I'm possibly missing a step, I've tried with different video url's, tokens, browsers (Opera GX and Chrome), bought more google drive storage as well as colab pro, and I still can't get past this step anymore.

Any help would be great, not sure if anyone has had this issue yet. Thanks
![image_2023-01-22_235250716](https://user-images.githubusercontent.com/123347995/213968083-ca5ea01d-bccb-44af-9f23-d2e3bbc58164.png)

**Comment by EvanWiederspan** [comment]
Could you share a minimal repro notebook?
