### ISSUE TITLE
[solved but with a follow-up]Cannot import lda when connected to a hosted runtime 

### ISSUE THREAD

**Issue by ShumzZ** [googlecolab/colabtools#336]
update: just checked issue#327 [after pip upgrading pandas, the upgraded version is not available](https://github.com/googlecolab/colabtools/issues/327) solution is similar: after installations, restart the runtime under 'runtime' tab in the header menu, then import lda

But there is a follow-up: does it mean I need to restart runtime every time after installation or update in order for the process to "pick it up"? Could this be solved somehow in the future? Thanks!

I was trying to use install and import the [lda package](https://github.com/lda-project/lda), I noticed that it requires [pbr](https://git.openstack.org/cgit/openstack-dev/pbr) version to be <4, so I used `!pip install --force-reinstall pbr==3.1.1` (done)and the then `!pip install lda` (done) which gave me back:

> Requirement already satisfied: pbr<4,>=0.6 in /usr/local/lib/python2.7/dist-packages (from lda) (3.1.1)

which seemed to be working fine, but when I tried to import `import lda`, it gave me a bunch of error messages and at the very bottom, it read:

> ContextualVersionConflict: (pbr 5.1.1 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('pbr<4,>=0.6'), set(['lda']))

So I am at a loss... didn't I just reinstall pbr 3.1.1 and the first piece of message also confirmed that I have successfully installed pbr 3.1.1? Any thoughts, thanks!

FYI the three line of codes would run perfectly if connected to a local runtime
`!pip install --force-reinstall pbr==3.1.1`
`!pip install lda` 
`import lda`

**Comment by ShumzZ** [comment]
Sorry to have created an empty issue with a meaningless title(just updated), I am quite new to Colab and Github (and honestly coding as a whole), so any suggestions or advice would be appreciated!

**Comment by craigcitro** [comment]
I'm fairly sure the problem is that you'd already imported lda and/or pbr before calling `pip install --upgrade`. This isn't particular to colab: once you've imported a package in python, another import will be a noop.

If you restart the runtime and try again, I suspect everything will work. (In general, installing new versions before loading them is the path to minimal pain.)
