### ISSUE TITLE
Selenium no longer works as usual, unexpectedly exits

### ISSUE THREAD

**Issue by Tunde4real** [googlecolab/colabtools#3362]
I'm experiencing the following error while trying to create a new chrome webdriver instance with the code line:
`driver = chrome()`

[/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py](https://wvce3hoft3n-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230120-060049-RC00_503399448#) in assert_process_still_running(self)
    115     def is_connectable(self):
    116         return utils.is_connectable(self.port)
--> 117 
    118     def send_remote_shutdown_command(self):
    119         from urllib import request as url_request

WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 1

**Comment by mco-gh** [comment]
Does [this](https://github.com/googlecolab/colabtools/issues/3347) help?

**Comment by Tunde4real** [comment]
> Does [this](https://github.com/googlecolab/colabtools/issues/3347) help?

It really was, it solved my problem.

Thanks!

**Comment by Tunde4real** [comment]
I was able to solve this problem by using a shell script copied from one of the responses to [this](https://github.com/googlecolab/colabtools/issues/3347) issue.

`%%shell
# Ubuntu no longer distributes chromium-browser outside of snap
#
# Proposed solution: https://askubuntu.com/questions/1204571/how-to-install-chromium-without-snap

# Add debian buster
cat > /etc/apt/sources.list.d/debian.list <<'EOF'
deb [arch=amd64 signed-by=/usr/share/keyrings/debian-buster.gpg] http://deb.debian.org/debian buster main
deb [arch=amd64 signed-by=/usr/share/keyrings/debian-buster-updates.gpg] http://deb.debian.org/debian buster-updates main
deb [arch=amd64 signed-by=/usr/share/keyrings/debian-security-buster.gpg] http://deb.debian.org/debian-security buster/updates main
EOF

# Add keys
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DCC9EFBF77E11517
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 112695A0E562B32A

apt-key export 77E11517 | gpg --dearmour -o /usr/share/keyrings/debian-buster.gpg
apt-key export 22F3D138 | gpg --dearmour -o /usr/share/keyrings/debian-buster-updates.gpg
apt-key export E562B32A | gpg --dearmour -o /usr/share/keyrings/debian-security-buster.gpg

# Prefer debian repo for chromium* packages only
# Note the double-blank lines between entries
cat > /etc/apt/preferences.d/chromium.pref << 'EOF'
Package: *
Pin: release a=eoan
Pin-Priority: 500


Package: *
Pin: origin "deb.debian.org"
Pin-Priority: 300


Package: chromium*
Pin: origin "deb.debian.org"
Pin-Priority: 700
EOF

# Install chromium and chromium-driver
apt-get update
apt-get install chromium chromium-driver

# Install selenium
pip install selenium`
