### ISSUE TITLE
High RAM usage when auto-saving deepfake model on Google Colab Pro after updating to Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by MedicDoesStuff** [googlecolab/colabtools#3364]
**Describe the current behavior**
As a user of Google Colab Pro, I have noticed high RAM usage when training deepfake models. This issue occurs specifically when the model auto-saves, causing my notebook to slow down and sometimes crash, disrupting my workflow. This issue started happening after they updated the colab to Ubuntu 20.04 LTS. Despite troubleshooting, the issue persists and needs to be addressed by Google Colab.

**Describe the expected behavior**
The expected behavior for training deepfake models on Google Colab Pro should be that the model saves without causing high RAM usage. Before the update to Ubuntu 20.04 LTS, I did not experience this issue and the model saved fine. However, now that this problem has surfaced after the update, it greatly hinders my workflow and productivity. I hope that Google Colab addresses this problem and restores the smooth and efficient experience of training deepfake models on their platform.

**What web browser you are using**
Chrome

**Comment by EvanWiederspan** [comment]
Thanks for the report, we're aware of some issues with higher RAM usage and are looking into it, updates will likely be posted in https://github.com/googlecolab/colabtools/issues/3363

**Comment by metrizable** [comment]
I noticed that the term "deepfake" was used in the title of the issue. Use of Colab in this case is specifically named as prohibited in our Terms-of-Service: https://research.google.com/colaboratory/faq.html#limitations-and-restrictions
