### ISSUE TITLE
UPDATE NVIDIA DRIVERs PLEASEE! :-)

### ISSUE THREAD

**Issue by Rohandud** [googlecolab/colabtools#3366]
This driver is pretty old and do not support Optix, which the newer Nvidia drivers (ver. 470 and newer) for the Tesla T4 are capable of.
I tried to update the Nvidia driver with a added repository, but this failed, as i had not enough priviledges (for a reboot) to do this.

Update the drivers up-to-date

PLEASEEEE UPDATE to nvidia-driver-470 or above Please, I want to use pro for that like i usually do but will not able to use the programs that i want with current drivers updates

**Comment by mayankmalik-colab** [comment]
Nvidia driver is upgraded to 510. I hope it helps. Also, there are more interesting upgrades coming soon.
