### ISSUE TITLE
Unusual high RAM usage

### ISSUE THREAD

**Issue by olivier59470** [googlecolab/colabtools#3368]
I ran this morning a python script I used to run previously withtout issue.

after importing libraries and mount google drive, I only read a JSON file...

I don't understand why for the same script the RAM is today insufficient.

Thanks a lot in advance.

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
Can you share a minimal repro notebook? Note that if you are trying to run Stable Diffusion and seeing issues, we are aware of RAM issues and are investigating in https://github.com/googlecolab/colabtools/issues/3363

**Comment by metrizable** [comment]
@olivier59470 Thanks for reporting this issue. I've added content to https://github.com/googlecolab/colabtools/issues/3363#issuecomment-1421405493. Assuming you had been facing the same issue, I'm going to mark this as a duplicate.
