### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by NataliaDiaz** [googlecolab/colabtools#337]
Chrome on Mac gives the following error intermittently when trying to load/run a notebook: 
Failed to fetch
TypeError: Failed to fetch
   at https://colab.research.google.com/v2/external/external_polymer_binary_l10n__fr.js?vrz=colab-20181106-085454-RC00_220290664:2277:261

The original link to the colab notebook shared with a 'anyone with the link can view' is: 
https://colab.research.google.com/drive/1B5KQvPySqYEa6XicRHdOwgv8fN1BrCgQ

**Comment by colaboratory-team** [comment]
If you discover a recipe to reproduce this reliably, please do reopen and share. A common cause of these issues is transient network issues and/or browser extensions.
