### ISSUE TITLE
hear is an issue of error line report, if some one is given indentation in the starting of the program ,then it will show an error in above line equal to the number of line indented in starting.

### ISSUE THREAD

**Issue by shubs131415** [googlecolab/colabtools#3371]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mco-gh** [comment]
Can you please share a notebook or a sample of the code you're referring to?
