### ISSUE TITLE
RAM bug, how does a 2.6GB model loaded to VRAM for inference take 11.70GB of RAM ?

### ISSUE THREAD

**Issue by TheLastBen** [googlecolab/colabtools#3372]
Right after the recent upgrade, it seems that stable diffusion is slowly becoming incompatible with google colab, what is filling 11.7GB of RAM ? I'm genuinely curious.

**Comment by EvanWiederspan** [comment]
We've been getting reports of this, updates will likely appear in https://github.com/googlecolab/colabtools/issues/3363

**Comment by TheLastBen** [comment]
Hopefully there will be updates, even people using premium are facing RAM issues.
