### ISSUE TITLE
Tensorflow training doesn't use GPU

### ISSUE THREAD

**Issue by mandanafasounaki** [googlecolab/colabtools#3376]
**Describe the current behavior**
with tf.device('/device:GPU:0'): 
does not work and GPU is not utilized.

**Describe the expected behavior**
training the model on GPU

**What web browser you are using**
Safari

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by metrizable** [comment]
@mandanafasounaki Thanks for using Colab. I understand that you are trying to use GPU with TensorFlow and are unable to. One thing to confirm is that in the "Runtime" menu, in the "Change runtime type" option, the "Hardware Accelerator" is set to GPU:

![3aPUGQzePHN3GH4](https://user-images.githubusercontent.com/65414824/215880357-c40585d5-b65f-4283-909e-c5df2bccd35b.png)

I walked through this myself and was able to execute code that uses the GPU with TensorFlow:
![92bmUmtGjU7ELRE](https://user-images.githubusercontent.com/65414824/215879227-32ecfbe1-3dcd-4b82-93a9-fe7777a0e431.png)
