### ISSUE TITLE
I have Colab Plus and cannot set the runtime to 24h or to avoid interruption when browser is closed

### ISSUE THREAD

**Issue by dimagnus** [googlecolab/colabtools#3379]
**Describe the current behavior**
 
I cannot choose in Edit -> Notebook Settings the option to run up to 24h or 
to avoid interrupting my notebook execution when I close the browser.
The feature is missing in the menu, even though I have Colab Pro Plus.

**There is no option to enable background execution** (already checked 
issue #2878 posted in Github)

**Describe the expected behavior**
Colab PRO+ should run my for 24 hours as the products description written.

**What web browser you are using**
Safari 16.2 and Chrome 109.0.5414.87
(both have the same issue)

**Already filed feedback using Help -> Send feedback and did not work**

**Comment by cperry-goog** [comment]
For Pro+ users, we try to keep your runtime live for up to 24 hours as long as you have compute units - the setting is not necessary (and we've removed it).

If your runtime gets interrupted mid-execution while you have compute units, please submit feedback in product and reference this issue.
