### ISSUE TITLE
Can't Find Most Recent Code on Colab

### ISSUE THREAD

**Issue by Mofetoluwa** [googlecolab/colabtools#3384]
Hi,

**Describe the current behavior**
Lost the changes I made for over a week now, and although I believe it was saving automatically, the notebook opens in a very old version.

**Describe the expected behavior**
Changes meant to be saved.

**What web browser you are using**
Chrome

**Additional context**
Link to current old version, not displaying latest codes:
https://colab.research.google.com/drive/1Gp6Sfda-_YndwtHKpoJDPn58umAFZ2_5?usp=sharing 

If there is an issue on this already, I'd appreciate the link. Thank you...

**Comment by cperry-goog** [comment]
If you can find a reliable way to reproduce this, that'd be helpful. If your browser ever loses connectivity, auto-saving can fail, and we show you a red error message.

**Comment by Mofetoluwa** [comment]
The work lost was work done for over a week, and auto-save worked through the week. Is it possible to lose all of the work just like that?
