### ISSUE TITLE
Google Colab missing identation.

### ISSUE THREAD

**Issue by JoskeBoi** [googlecolab/colabtools#3386]
**I** just logged back in google colab and the code was working just fine yesterday, i had made the code 'import time' and it didn't have the 'time defined'.

**It** should have the 'time defined' as it was yesterday, as the title 'time' is 'imported'.

**I** am using chrome as my browser.

**Comment by mco-gh** [comment]
Jupyter notebooks are stateful. If you run code in cell A (like import time, for example), which cell B depends upon, then the backend restarts, you'll need to rerun cell A before you can run cell B.
