### ISSUE TITLE
src/tcmalloc.cc:332] Attempt to free invalid pointer erorr

### ISSUE THREAD

**Issue by ReemaSun** [googlecolab/colabtools#3387]
Hi
I was trying to run the following on google colab 
[https://colab.research.google.com/drive/15mioeqRXUz-I7jv2Qk3-CcyqUzxU099u?usp=sharing](url)

but this error occurred
src/tcmalloc.cc:332] Attempt to free invalid pointer 0x7f5f0e0eb558 

i use google Chrome

**Comment by metrizable** [comment]
@ReemaSun Thanks for reporting this issue and thanks for using Colab. I reviewed your notebook, and I see these messages are being output by `pip` during the download of large packages, but that, ultimately, the `pip` command succeeded (although there are dependency conflicts you have installing the old versions of torch packages).

For this case, if you'd like to avoid these messages, you can include `--no-cache-dir` in the `pip install` invocation. Further, we're currently investigating our use of tcmalloc in Ubuntu 20.04.

**Comment by metrizable** [comment]
We recently released changes of our use of tcmalloc that may fix your notebook. Let us know if it resolves your issue!

**Comment by ReemaSun** [comment]
Thank you for help!
there is another problem "UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")"

**Comment by metrizable** [comment]
@ReemaSun It could be that you need to select a GPU in the "Runtime > Change runtime type" menu item as I see that the notebook you shared does not have a saved runtime as GPU: 

![7WFxMDnZonAATHp](https://user-images.githubusercontent.com/65414824/217116388-1b47a4aa-d89b-4eb1-81f1-7191b39110a0.png)

**Comment by ReemaSun** [comment]
**at training step in Starting dataset creation process this message appears**

/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py:554: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
**as a part of this**
![image](https://user-images.githubusercontent.com/124377023/218347950-923d171b-c2cf-498a-943e-49a4046346a3.png)

how to solve this to properly train the model ?

**Comment by cperry-goog** [comment]
We don't have a good way to triage training performance, you'll want to contact the notebook author.
