### ISSUE TITLE
The Selenium in colab doesn't work

### ISSUE THREAD

**Issue by YanjunTong** [googlecolab/colabtools#3389]
When I want to use selenium in colab,the programme was went wrong.I have found many ways to try to solve this problem, but it is useless.And tese are my codes.
![mmexport1675447967509](https://user-images.githubusercontent.com/114793575/216676768-5cbdb613-1dc4-4637-a9e5-00da546a78af.png)
These are the returned contents.
![mmexport1675448030743](https://user-images.githubusercontent.com/114793575/216676926-1cd2e3f2-8f87-48aa-a15f-73ab97973670.png)

Could anyone has ways to solve it?Please give me some ways.Thanks a lot!
Pleas reply me here or on my emailbox at yanjun_tong@outlook.com

**Comment by metrizable** [comment]
@YanjunTong Thanks for your report and thanks for using Colab.

In order to use `selenium`, you may want to try this: https://github.com/googlecolab/colabtools/issues/3347#issuecomment-1387453484.

**Comment by saraswathykrk** [comment]
@metrizable Does  https://github.com/googlecolab/colabtools/issues/3347#issuecomment-1387453484 solution work in colab in mac? It is somehow not working for me.

**Comment by kui6846hk** [comment]
Work for me.

```
!apt autoremove
!apt-get update
!apt install chromium-chromedriver
!pip install -U selenium
!pip install -U webdriver-manager
```

```
!wget -q -O chromedriver_linux64.zip 'https://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_linux64.zip' && unzip chromedriver_linux64.zip && rm chromedriver_linux64.zip && mv chromedriver /usr/bin/chromedriver
```

```
from selenium import webdriver
from bs4 import BeautifulSoup

options = webdriver.ChromeOptions()
options.add_argument("--no-sandbox")
options.add_argument("headless")
options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome("chromedriver", options=options) 

url = "https://www.google.com.hk"
driver.get(url)

soup = BeautifulSoup(driver.page_source, "lxml")
print(soup)
```

**Comment by YanjunTong** [comment]
Thanks and the problem has been solved

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jpjacobpadilla** [comment]
I made this thin wrapper around Selenium (ChromeDriver) which makes it easy to use Selenium in Google Colab Notebooks!

https://github.com/jpjacobpadilla/Google-Colab-Selenium

You basically just pip install the package and then can use Selenium like this:

```python
import google_colab_selenium as gs

driver = gs.ChromeDriver()
# Your code to interact with the driver here
driver.quit()
```
