### ISSUE TITLE
Improper alignment

### ISSUE THREAD

**Issue by faizihere** [googlecolab/colabtools#3390]
**Describe the current behavior**
While executing/compiling the code cell the 'loading animation' i.e. 'rotation animation'  is not centered properly around the run/play button.

**Describe the expected behavior**
The rotation has to be properly aligned at the center .

**What web browser you are using**
I'm using Chrome browser.

**Comment by EvanWiederspan** [comment]
Can you share a screenshot of this, and the exact chrome version you are using?

**Comment by blois** [comment]
This should now be fixed.

**Comment by faizihere** [comment]
perfect. Thanks

**Comment by faizihere** [comment]
If my suggestion is valuable then an official credits will be very helpful
to my professional life
