### ISSUE TITLE
julia bug

### ISSUE THREAD

**Issue by theodorosP** [googlecolab/colabtools#3391]
Hello,

Julia is not working in colab. Here is what I mean. When I run the first cell from the julia's notbook (https://colab.research.google.com/github/ageron/julia_notebooks/blob/master/Julia_Colab_Notebook_Template.ipynb), this is what I am getting.

![Julia_1](https://user-images.githubusercontent.com/83337690/216783570-ed682a9c-ab50-4cad-abf4-b2093451e071.png)

Can someone fix ti?

**Comment by theodorosP** [comment]
The above seems to work today, however whenever I try to import a package then the runtime ends. For example am unable to run the simple:

import Pkg; Pkg.add("Plots")

The runtime is terminated

**Comment by metrizable** [comment]
@theodorosP Thanks for reporting the issue and thanks for using Colab. I was able to successfully run the notebook, invoke `import Pkg; Pkg.add("Plots")`, and then use the `Plots` package with a canonical example (Wow! Julia is really expressive!)

![3QHadwjZ7QEZWgM](https://user-images.githubusercontent.com/65414824/217054793-b958c432-f5d3-4f30-a149-eaea1a6ae1a5.png)


One thing I noted: from the notebook instructions, after executing the first cell, you need to refresh the page.

**Comment by theodorosP** [comment]
> import Pkg; Pkg.add("Plots")

I just run it and it works. I was not able to run it 30 minutes ago. I am not sure what is happening with julia and colab. I face issues every now and then. Yes it is computationally expensive but it's faster compared to python for graphical data mining  projects.

**Comment by metrizable** [comment]
@theodorosP We recently released a fix for julia install failures re: https://github.com/googlecolab/colabtools/issues/3385#issuecomment-1419522299. I'm glad it's working for you now!

**Comment by theodorosP** [comment]
@metrizable I am only using colab for my Data engineering projects, so I always rephrase the page. I am glad that the issue is now fixed. Great work. Thank you very much for your prompt reply.
