### ISSUE TITLE
Upgrade CUDA to 11.6.2 and cuDNN to 8.4.0.27

### ISSUE THREAD

**Issue by mayankmalik-colab** [googlecolab/colabtools#3398]
## Upgrade CUDA to 11.6.2 and cuDNN to 8.4.0.27

This moves our CUDA ecosystem a bit closer to more contemporary version. We have several more interesting upgrades coming soon. Stay tuned. 

#### Colab’s fallback runtime version

Using the fallback runtime version temporarily allows access to the last version of the runtime before the upgrade described above, and is available until mid-February. Its purpose is to provide a temporary mechanism for users to more smoothly upgrade their notebooks to be compatible with Colab’s current runtime version. This is available from the Command Palette via the "Use fallback runtime version" command when connected to a runtime. Of note, this setting does not persist across sessions – the command will need to be invoked on each new session.

**Comment by Dan944** [comment]
Is that available now for Python 3.9?

**Comment by elahe-badali** [comment]
I do not have access to fallback runtime since last week. 

> Is that available now for Python 3.9?
