### ISSUE TITLE
red button appears

### ISSUE THREAD

**Issue by vladimir785** [googlecolab/colabtools#3400]
red button appears when i press "run the code" (Bringing Old Photo Back to Life.ipynb)

**Comment by EvanWiederspan** [comment]
Could you share a link to the notebook where you're seeing this issue?

**Comment by vladimir785** [comment]
https://colab.research.google.com/drive/1NEm6AsybIiC5TwTU_4DqDkQO0nFRB-uA?usp=sharing#scrollTo=q6lNy6jw5rjd

**Comment by EvanWiederspan** [comment]
I see the following error when running all cells, is this what you're referring to?

```
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-12-3121ae23a960>](https://localhost:8080/#) in <module>
     10     print(filename)
     11     image_original = PIL.Image.open(os.path.join(input_path, filename))
---> 12     image_restore = PIL.Image.open(os.path.join(output_path, 'final_output', filename))
     13 
     14     display(make_grid(image_original, image_restore))

[/usr/local/lib/python3.8/dist-packages/PIL/Image.py](https://localhost:8080/#) in open(fp, mode)
   2841 
   2842     if filename:
-> 2843         fp = builtins.open(filename, "rb")
   2844         exclusive_fp = True
   2845 

FileNotFoundError: [Errno 2] No such file or directory: '/content/photo_restoration/output/final_output/a.png'
```

This seems to be an issue with the notebook code missing some files, not Colab itself. I recommend reaching out to the notebook author

**Comment by vladimir785** [comment]
Hello Evan!
Maybe i’m doing something wrong )))
idk
i see this 
  
>Среда, 8 февраля 2023, 21:21 +03:00 от Evan Wiederspan ***@***.***>:
> 
> 
>I see the following error when running all cells, is this what you're referring to?
>FileNotFoundError                         Traceback (most recent call last)
>[<ipython-input-12-3121ae23a960>](https://localhost:8080/#) in <module>
>     10     print(filename)
>     11     image_original = PIL.Image.open(os.path.join(input_path, filename))
>---> 12     image_restore = PIL.Image.open(os.path.join(output_path, 'final_output', filename))
>     13 
>     14     display(make_grid(image_original, image_restore))
>
>[/usr/local/lib/python3.8/dist-packages/PIL/Image.py](https://localhost:8080/#) in open(fp, mode)
>   2841 
>   2842     if filename:
>-> 2843         fp = builtins.open(filename, "rb")
>   2844         exclusive_fp = True
>   2845 
>
>FileNotFoundError: [Errno 2] No such file or directory: '/content/photo_restoration/output/final_output/a.png'
>
>This seems to be an issue with the notebook code missing some files, not Colab itself. I recommend reaching out to the notebook author
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <googlecolab/colabtools/issues/3400/1423053508 @ github . com> 
 
 
-------------------------------
Владимир Леонидович
Телефон/Viber:  8-939-342-42-09
Skype: vmt5000

**Comment by EvanWiederspan** [comment]
I would reach out to the notebook author, this doesn't seem to be an issue with Colab itself
