### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'gpus'

### ISSUE THREAD

**Issue by Albandry209** [googlecolab/colabtools#3401]
Hey , I hope you can help me  to solve this problem .
Link;
https://colab.research.google.com/drive/1qxxjy68gtIXxSVJb9nJ6tSq3SgR3yC2e?usp=sharing

I have this error in my code (third code) :
File "/content/AttentionBasedMultiModalRNN/KNN.py", line 234, in <module>
    eval(args)
  File "/content/AttentionBasedMultiModalRNN/KNN.py", line 122, in eval
    os.environ['CUDA_VISIBLE_DEVICES'] = args.gpus
AttributeError: 'Namespace' object has no attribute 'gpus'

**Comment by EvanWiederspan** [comment]
I see on your first cell that you use `venv`. This is generally not supported in Colab. I would revise your notebook to not use that, and reach out to the notebook author if you need help with that

**Comment by Albandry209** [comment]
Thank you for your response i hope you can solve it without using venv. It has been contacted previously and no response has been received for about a week

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Albandry209** [comment]
I have used the other virtualenv and also we try without it , but the same error was raise .  https://colab.research.google.com/drive/1V9rsD7b57CbpwBbh3mP5Zyhgc3lxh8Kt?usp=sharing


Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by EvanWiederspan** [comment]
I see you're still using virtualenv in that notebook, do you have another notebook without virtualenv that shows your error?
