### ISSUE TITLE
Screen scrolls to my cursor when working with another person

### ISSUE THREAD

**Issue by JoyChopra1298** [googlecolab/colabtools#341]
So when 2 of us are working in the same code cell, whenever my friend starts coding, my screen scrolls to my cursor. I think this is unintentional and annoying, and the ideal behaviour probably should be my screen scrolling when I start to code, not others. Maybe that was the original intention and it's a bug or I am not getting why this was needed.

**Comment by corrieann** [comment]
This no longer occurs.
