### ISSUE TITLE
colab crashes when downgrade python to 3.7 

### ISSUE THREAD

**Issue by GhaidaxD** [googlecolab/colabtools#3410]
hello 
i'm trying to downgrade python on colab to 3.7 by using the following lines :

!sudo apt-get update -y
!sudo apt-get install python3.7

#change alternatives
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2

# install pip for python==3.7
!sudo apt-get install python3.7-distutils
!wget https://bootstrap.pypa.io/get-pip.py
!python get-pip.py

# install colab dependencies
!python -m pip install ipython ipython_genutils ipykernel jupyter_console prompt_toolkit httplib2 astor

# link to the old google package
!ln -s /usr/local/lib/python3.8/dist-packages/google \
       /usr/local/lib/python3.7/dist-packages/google

then after i installed tensorflow 1.14 ,  it required me to restart the runtime to use it  , but when i try to restart it the session keep crashed until it doesn't work any more !

**Comment by metrizable** [comment]
@GhaidaxD I understand that you're trying to downgrade Colab's runtime to Python 3.7 in order to use TensorFlow 1.x. This is currently an unsupported configuration.
