### ISSUE TITLE
upgrade matplotlib from version 3.2.2 to version 3.7.0

### ISSUE THREAD

**Issue by bisht-deepak** [googlecolab/colabtools#3413]
unable to use a lot of features which have been added to the latest version of matplotlib. please upgrade it soon.

**Comment by metrizable** [comment]
@bisht-deepak Thanks for the request. Of interest is this related upgrade: https://github.com/googlecolab/colabtools/issues/3428

**Comment by metrizable** [comment]
Closing as duplicate of #3498
