### ISSUE TITLE
Ctrl + C is not switching modes in vim editor

### ISSUE THREAD

**Issue by janeusz2000** [googlecolab/colabtools#3414]
**Describe the current behavior**

When we are in insert mode, Ctrl + C should switch vim mode into normal mode and when in visual vim mode, Ctrl + C should switch to normal mode as well. Coping should be handled with
Ctrl + shift + C instead of Ctrl + C.

**What web browser you are using**
Chrome, Edge

**Comment by metrizable** [comment]
@janeusz2000 Thanks for reporting the issue. We are investigating this at b/270571269.

**Comment by katlyn-edwards** [comment]
This should now be fixed
