### ISSUE TITLE
Training model

### ISSUE THREAD

**Issue by Reema1407** [googlecolab/colabtools#3415]
Hi 
I hope you can help me ,
at training step in Starting dataset creation process this message appears

/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py:554: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
warnings.warn(_create_warning_msg(
as a part of this 

![](https://user-images.githubusercontent.com/124377023/218348378-2b556380-008d-4a06-a948-bceb85f505ba.jpg)

how to solve this to properly train the model?

Notebook link https://colab.research.google.com/drive/15mioeqRXUz-I7jv2Qk3-CcyqUzxU099u?usp=sharing

**Comment by cperry-goog** [comment]
This looks like an issue with the notebook, you'll want to file an issue with them over at https://github.com/HumaticsLAB/POP-Mining-POtential-Performance

**Comment by Reema1407** [comment]
> This looks like an issue with the notebook, you'll want to file an issue with the author over at https://github.com/HumaticsLAB/POP-Mining-POtential-Performance

it isn't related to disk ? Or subscription type ?
