### ISSUE TITLE
The example in `Linear Regression with Synthetic Data.ipynb` has a bug.

### ISSUE THREAD

**Issue by shixiong-jiang** [googlecolab/colabtools#3417]
https://colab.sandbox.google.com/github/google/eng-edu/blob/main/ml/cc/exercises/linear_regression_with_synthetic_data.ipynb?utm_source=mlcc&utm_campaign=colab-external&utm_medium=referral&utm_content=linear_regression_synthetic_tf2-colab&hl=zh-cn#scrollTo=QF0BFRXTOeR3

`plt.plot([x0, x1], [y0, y1], c='r')` is wrong. 

```
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 1) + inhomogeneous part.
```

**Comment by mayankmalik-colab** [comment]
The notebook ran just fine for me. What variable values have you set (like learning_rate, epochs..)? If possible, can you share your saved notebook so that we can reproduce.

**Comment by cperry-goog** [comment]
Closing as we can reproduce, open a new bug with your own content that breaks if you can reproduce

**Comment by shixiong-jiang** [comment]
1. It deps on the vision of `matplotlib`.

2. I just verified that: notebook can run, but with an warning.
```
/usr/local/lib/python3.8/dist-packages/numpy/core/shape_base.py:65: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray. ary = asanyarray(ary)
```

3. When I ran the example, I didn't use notebook. I guess the `matplotlib`(latest version maybe?) in my local runtime has already deprecated above warning. (So, it threw an error)

4. IIUC, instead of `numpy`, func `train_model` may return float(s):
```
def train_model(model, feature, label, epochs, batch_size):
  ...
  // return trained_weight, trained_bias, epochs, rmse
  return trained_weight[0].item(), trained_bias[0].item(), epochs, rmse
```

IMHO, as a beginner practice example, we may prefer to make it runnable under all the runtime. 

Thanks,
