### ISSUE TITLE
Model does not train when using Colab Premium GPU

### ISSUE THREAD

**Issue by maxsowi** [googlecolab/colabtools#3418]
**Describe the current behavior**
I recently upgraded my google colab account to premium. But when I select the Premium GPU in runtime [screenshot attached] I encounter an issue while trying to train my model. The code runs and it does not show any error but it does not show any progress [screenshot attached]. Only when I change back to normal GPU under runtime the model trains.

Here is the code I am using to set up and train the model

```
model = ClassificationModel('roberta', 'roberta-base', num_labels=3, weight=class_weights.tolist(),
                            use_cuda=True, args={'reprocess_input_data': True, 'overwrite_output_dir': True,
                                                  "num_train_epochs": 10})

model.train_model(train)
```

**Describe the expected behavior**
When using the normal GPU the model gets trained. With the Premium GPU the model train function simply does not show any progress.

**What web browser you are using**
Chrome. 

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
![Untitled2](https://user-images.githubusercontent.com/19473544/219317646-640e5186-f503-4e7c-a161-fb6a19e75fd7.png)
![Untitled](https://user-images.githubusercontent.com/19473544/219317655-5665b6fa-0d24-484f-aec5-90aba597780e.png)

**Comment by cperry-goog** [comment]
We'll need a minimal reproducible notebook to investigate.

**Comment by maxsowi** [comment]
Sure, here is the notebook. Many thanks for the help

[notebook.zip](https://github.com/googlecolab/colabtools/files/10813097/notebook.zip)

**Comment by jonathan-telemetry** [comment]
Just want to add that I am seeing this same issue and am also using the simpletransformers module. @cperry-goog

**Comment by simonkleinfeld** [comment]
Are there any further information? I have this issue too.

**Comment by mayankmalik-colab** [comment]
@maxsowi - Thanks for the sample notebook. If possible, can you share some sample training data that you used? Also, can you confirm if this happens with `simpletransformers` only ?

**Comment by mayankmalik-colab** [comment]
It seems like the same issue as #3422. Can you check my [reply](https://github.com/googlecolab/colabtools/issues/3422#issuecomment-1460885571) there and hopefully it helps.
