### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by Albandry209** [googlecolab/colabtools#3419]
Hey, i have this problem in applying the code i hope you can help me to solve it . 

In 5th cell error:
 os.environ['CUDA_VISIBLE_DEVICES'] = args.gpus
AttributeError: 'Namespace' object has no attribute 'gpus'

in training 8 cell this error :
RuntimeError: No CUDA GPUs are available
link of code:
https://colab.research.google.com/drive/1YDIERsbtzleo5W2Acm9ZaXnYQJZq6wrq?usp=sharing
thank you .

**Comment by mco-gh** [comment]
I'll take a look to see if I can repro this but, in the meantime, I'd suggest trying to use a more recent version of pytorch and cuda.

**Comment by mco-gh** [comment]
> AttributeError: 'Namespace' object has no attribute 'gpus'

Looks like the KNN.py script expects a gpus argument, which is not being supplied by the command you invoke. I suggest taking this up with the provider of the repo you're cloning to see if you're missing an argument and/or how to run this code in colab (the source repo doesn't mention colab so you may be trying an untested usage scenario).
