### ISSUE TITLE
Classification model not trained on Colab Pro account

### ISSUE THREAD

**Issue by Ling-Ki** [googlecolab/colabtools#3422]
**Describe the current behavior**
I subscribed to Colab Pro this month. I needed the resources, esp. the GPU, to train multiple transformation models on text data and then compare the models' performance. Since last week, I noticed that the models can no longer be trained and evaluated on my account: The script of model training keeps running and suggests it is fitting the model, but the progress bar is not moving; there's also no increase of RAM usage. Eventually, the runtime connection stops, but on my screen, it still shows the code is running. 

The current behavior is shown at the end of Section 4 (**Classification D**) in the shared notebook below.

**Describe the expected behavior**
The code should run smoothly (less than an hour), as tested in my other non-premium google accounts as well as my colleague's. An output should look like the one in Section 3 (**Classification A**, included in the notebook for reference). I derive the problem lies on my account, but not the code per se, since the code can be executed perfectly on other accounts.

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
Link: [https://gist.github.com/Ling-Ki/4c2070656ccbb1ae1ab0e7292a831a08](url)
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
Here: [https://colab.research.google.com/drive/15sm8plqL-8PPE_iXVKTRuU-zFU0HwQtt?usp=sharing](url)
 - I think this issue is somewhat similar to another existing issue here: [https://github.com/googlecolab/colabtools/issues/3418](url)

**Comment by metrizable** [comment]
@Ling-Ki Thanks for reporting your issue and thanks for using Colab. We're investigating it.

**Comment by Ling-Ki** [comment]
Hi Team, has there been any update? I upgraded my account to Colab Pro+ recently, and the problem still persists. It renders my subscription worthless at the moment.

**Comment by mayankmalik-colab** [comment]
@Ling-Ki -  If possible, can you also share some sample training data that you used? It would be faster to reproduce the issue. Also, can you confirm if this happens with `simpletransformers` only ?

**Comment by Ling-Ki** [comment]
@mayankmalik-colab I attached a sample of the training data (600 rows) as requested. 

And yes, this happens when I called and trained the models inside the `simpletransformers` package. It occurs only on my account with Colab Pro(+) subscription -- if I am using a free account, it runs...

[GitHub_training_clean.xlsx](https://github.com/googlecolab/colabtools/files/10914215/GitHub_training_clean.xlsx)
