### ISSUE TITLE
Unable to see the output  of plotting just below the code 

### ISSUE THREAD

**Issue by likhith4** [googlecolab/colabtools#3423]
while I'm trying to run a simple plotting of graphs I'm unable to see the outputs 
using **Firefox** as a browser (installed from flatpak)
I'm able to see the output when I right click(the place where the output is shown) and click on the view output in fullscreen then I'm able to see the output in a fullscreen 
Can anybody help me with this issue Why I'm not able to see the output right below my code ?

'.

**Comment by metrizable** [comment]
@likhith4 Can you provide a minimal reproducible notebook? Thanks!

**Comment by likhith4** [comment]
[Screencast from 25-02-23 11:18:46 PM IST.webm](https://user-images.githubusercontent.com/78915053/221371933-3ab1cf5e-5833-4985-a394-b143cad2ad61.webm)

**Comment by likhith4** [comment]
this is a minimal code to plot a graph and it couldn't show the output

**Comment by likhith4** [comment]
@EvanWiederspan Thanks !  I tried disabling some extensions and running the notebook in the browser and it worked thanks for the hint to try it on incognito mode :) Now it works fabulous  as usual
