### ISSUE TITLE
Cursor "stuck" within cell

### ISSUE THREAD

**Issue by corgiz4lif** [googlecolab/colabtools#3425]
**Cause**
I'm uncertain as to the trigger for this issue although it may be happening after I use the CTRL+M B to create a new cell. 
**Browser**
Chrome and Opera
**Problem**
When I refresh the page it appears to work fine and I am able to click and edit a cell as normal. When I try and click into a new cell the cursor appears at the end of the 2nd cell but another cursor is still in the first cell. It continues with other cells I try and edit and I am unable to predict which cell the text may appear in.
**Solution**
The only way to fix the bug I have found has been to fully restart the browser
![chrome_SXnQg8eRRs](https://user-images.githubusercontent.com/73208066/220213027-1c8419aa-4dc6-4173-9101-f1a7785ded3f.png)

**Comment by metrizable** [comment]
@corgiz4lif Thanks for the report. Would you be able to record a screencast? I cannot reproduce your issue from the instructions provided.

**Comment by corgiz4lif** [comment]
When making the video, the issue began occurring as soon as I loaded the page.
https://user-images.githubusercontent.com/73208066/221718938-87c8467c-d3e7-4f5d-a5c2-fdcb43ea6f60.mp4

**Comment by cperry-goog** [comment]
Two questions:
1. You don't observe this anywhere else? i.e. this isn't a keyboard issue (sticky keys, etc.)
2. Can you reproduce this in an incognito window?
