### ISSUE TITLE
Add a way to remove high-memory flag on notebook for free accounts

### ISSUE THREAD

**Issue by Netruk44** [googlecolab/colabtools#3426]
**Is your feature request related to a problem? Please describe.**
I created a notebook with high-memory requirement while I had a colab subscription. The notebook works without high memory available, I just needed it at the time.

But now that my subscription has lapsed, I get a warning every time I open the notebook about the notebook requiring high memory. However, I no longer have the ability to *remove* that flag because I don't have a subscription. The option to select runtime shape is completely hidden for Free-tier users. So I just have to look at this warning every time I use this notebook.

**Describe the solution you'd like**
Possibly just a button to clear the "high memory" flag (and possibly any other runtime shape requests) in the same place that subscribers have the drop-down to select runtime shape.

**Describe alternatives you've considered**
Possibly just show the drop-down to free users, but disable the options for high-memory and whatever other options are in the dropdown.

**Additional context**
This is the menu that for subscribers has the option to select "high memory" runtime, but for free users has nothing:

<img width="421" alt="image" src="https://user-images.githubusercontent.com/1307061/220385050-4e57c8d0-4186-45fb-b99a-031bd1454115.png">

**Comment by metrizable** [comment]
@Netruk44 Thanks for the report. We're tracking this feature request internally at b/270568261.

**Comment by colaboratory-team** [comment]
We just removed the warning dialog on this case, so this issue is fixed now. Thanks again for reporting this issue to us.
