### ISSUE TITLE
Upgrade to jax 0.4.4

### ISSUE THREAD

**Issue by metrizable** [googlecolab/colabtools#3432]
### Upgrade to jax 0.4.4

The Colab runtime has been upgraded to `jax` 0.4.4. The 0.4.x series was released at the [end of 2022](https://pypi.org/project/jax/0.4.1/) and this upgrade will keep Colab's offering up-to-date with a contemporary ecosystem.

There are several improvements and some breaking changes between the version currently offered in Colab's runtime, 0.3.25, and 0.4.4. For more details, see the [jax change log](https://jax.readthedocs.io/en/latest/changelog.html).

**Comment by jecampagne** [comment]
Hi, I was developping some JAX Tutos and would like to stick for a while to 0.3.25 before switching to 0.4.x is it still possible?

**Comment by mayankmalik-colab** [comment]
We have already made the updates. If you still want to use 0.3.25, I would recommend pip installing it again in your notebook.

```
!pip install jax==0.3.25

!pip install https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.3.25+cuda11.cudnn805-cp38-cp38-manylinux2014_x86_64.whl
```

**Comment by jecampagne** [comment]
Hello
When I try  in Colab 
```
!pip install https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.3.25+cuda11.cudnn805-cp38-cp38-manylinux2014_x86_64.whl
```
I get this error 

ERROR: jaxlib-0.3.25+cuda11.cudnn805-cp38-cp38-manylinux2014_x86_64.whl is not a supported wheel on this platform.

Is there still  a way to get jax 0.3.25 I have to check a repo branch code updated on 20th Jan 23.
