### ISSUE TITLE
Recently Opened Files Not Updated Communication Error

### ISSUE THREAD

**Issue by msalaztor** [googlecolab/colabtools#3435]
**Describe the current behavior**
When I started Google Colabs, a window pops up showing all recent files, on Google Drive, however this window showed erased and deleted files, and no changes in file names. The information in Google Drive form the available files is different from the Google Colab Window.

**Describe the expected behavior**
Recent file window should show the available files on Google Drive, with the current name, not outdated names

**What web browser you are using**
Using Firefox

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
we keep a cache stored on our side, but eventually deletions and renames propagate to that menu
