### ISSUE TITLE
OutOfMemoryError despite having Colab Pro+

### ISSUE THREAD

**Issue by yanivweiss** [googlecolab/colabtools#3439]
error: message:
OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 14.75 GiB total capacity; 13.39 GiB already allocated; 46.81 MiB free; 13.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Please advise ASAP

**Comment by coreyfournier** [comment]
You are using the lower end GPU. You can change the GPU class to premium which has 40GB of memory.

**Comment by cperry-goog** [comment]
You can try altering your approach to take less memory.
