### ISSUE TITLE
Upon my Colab Pro+ not being able to use premium gpu

### ISSUE THREAD

**Issue by yanivweiss** [googlecolab/colabtools#3440]
**Describe the current behavior**
Colab Pro+ not being able to use premium gpu

**Describe the expected behavior**
Colab Pro+ being able to use premium gpu

**What web browser you are using**
Chrome

**Additional context**
**image:**
![image](https://user-images.githubusercontent.com/47185466/221373109-9caa4f7c-2e75-4f3a-a838-f6ea56e2ec33.png)

**Comment by coreyfournier** [comment]
Dude, your out of money. It says it in the error.

**Comment by cperry-goog** [comment]
Correct, you've run out of compute units. On Pro+ you'll be granted 500 more on your next recurrence.
