### ISSUE TITLE
animation flipping images 180 degrees, against my wishes

### ISSUE THREAD

**Issue by entrancedpiglet** [googlecolab/colabtools#3442]
Hi collaborators.  I've been using Deforum Stable Diffusion with images for a while, but I've recently started working with the animation,  so I wouldn't be surprised if some dumb mistake(s) on my end is messing this up.  Basically, my problem is that for some reason when animating my frames the images pulled out of the video are all flipped upside down.  This happens with every video (except, weirdest of all, one video that I rotated 180* and saved upside down).  I'm using Chrome. 

https://gist.github.com/entrancedpiglet/07c581e0e860456d1e1de5da82b6e1cc
^first time setting up a gist, so hopefully this is done correctly.

**Comment by cperry-goog** [comment]
I don't think this is a Colab-specific issue, you'll want to connect with Stable Diffusion folks.
