### ISSUE TITLE
The environment is restarting - I loose my progress 

### ISSUE THREAD

**Issue by AndrzejOlejniczak** [googlecolab/colabtools#3443]
**Describe the current behavior**

The environment is restarting during code execution. I loose the progress and ( I fear ) I pay for another unit.

**Describe the expected behavior**
I expect Colab not to reinitialize the environment during work without my prior request.
I don't want to pay for additional GPU units :C .

**What web browser you are using**
Firefox. 

**Additional context**
I am unable to reproduce it. It just happens without any record. Please help.

**Comment by DevDyrsch** [comment]
I just hade the same thing happen, I lost about 8 hours of training data and a lot of GPU Units i pay for, for nothing.

**Comment by cperry-goog** [comment]
If you have a reproducible error where Colab incorrectly restarts, please file a bug with a minimal notebook.

**Comment by AndrzejOlejniczak** [comment]
As I mentioned before. It is not a reproducible error. This just happens
regardless of the code . Please help.

czw., 2 mar 2023, 18:39 użytkownik cperry-goog ***@***.***>
napisał:
