### ISSUE TITLE
Automatic saving keeps failing

### ISSUE THREAD

**Issue by BlakeOne** [googlecolab/colabtools#3444]
I've been getting this error for the last week or so: "Automatic saving failed. This file was updated remotely or in another tab." But I only have the notebook open in one Firefox tab.

Here’s the new content I found after clicking "Show diff":

```
Execution output
0KB
  text/plain
    Output hidden; open in https://colab.research.google.com to view.
```

**Comment by blois** [comment]
Do you happen to have a simple repro of this? I just started seeing this as well but haven't been able to narrow it down.

**Comment by BlakeOne** [comment]
Not yet but if I can find a simple notebook or way to reproduce reliably, I'll post an update.

BTW my fix for now is just to do a manual save (command-S) and then it's fixed... Until it isn't.

**Comment by BlakeOne** [comment]
I haven't had this issue for a while so I'll go ahead and close it. 👍

**Comment by BlakeOne** [comment]
I haven't had this issue for a while so I'll go ahead and close it. 👍

**Comment by Nik-Kras** [comment]
I have it
There is a big Google Colab I have been working on for a while. And just today I face strange issues.

I frequently see a message `Automatic saving failed. This file was updated remotely or in another tab`

To make sure it is not caused by my collegues opening it -> I created a copy on my Google Drive, releted the original one and continued to work on the copied version. Still I got the same error... I couldn't work for an hour or more, as the code execution freezes along with this message

**Comment by D1mi3** [comment]
> I have it There is a big Google Colab I have been working on for a while. And just today I face strange issues.
> 
> I frequently see a message `Automatic saving failed. This file was updated remotely or in another tab`
> 
> To make sure it is not caused by my collegues opening it -> I created a copy on my Google Drive, releted the original one and continued to work on the copied version. Still I got the same error... I couldn't work for an hour or more, as the code execution freezes along with this message

Same here. Did you find any way to fix it?

**Comment by anuragmid457-tech** [comment]
I frequently see a message Automatic saving failed. This file was updated remotely or in another tab. the same happens with me  bro.

**Comment by ICodeDiffusion** [comment]
> I frequently see a message Automatic saving failed. This file was updated remotely or in another tab. the same happens with me bro.

Same it's really dumb, it says it was saved in another place even though it's the only tab I have of this. It's always happened to me, and never bothers to retry on it's own.
