### ISSUE TITLE
Account is blocked due to 'suspected abusive activity'

### ISSUE THREAD

**Issue by oriab** [googlecolab/colabtools#3448]
I'm blocked from using my colabpro+ account, keep seeing a message that the account is blocked due to 'suspected abusive activity'.
Please assist

**Comment by oriab** [comment]
I already did it and for a few times.
No answer from your side. 
Great experience.

**Comment by oriab** [comment]
@cperry-goog I filed dozen of feedback requests so far, opened the defect here and sent multiple emails. So far no answers and I'm still prevented from using my account. What i'm supposed to do?

**Comment by crc1200** [comment]
What great service!
