### ISSUE TITLE
AlphaFold colab fails on MSA

### ISSUE THREAD

**Issue by Drew-Thomson** [googlecolab/colabtools#3449]
The Alphafold colab notebook isn't working for me. Everything works fine till the MSA section, then it fails with:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-4-56dbdfdd10c8>](https://localhost:8080/#) in <module>
     22 import py3Dmol
     23 
---> 24 from alphafold.model import model
     25 from alphafold.model import config
     26 from alphafold.model import data

30 frames
[/opt/conda/lib/python3.8/site-packages/OpenSSL/crypto.py](https://localhost:8080/#) in <module>
   3266 # OpenSSL library (and is linked against the same one that cryptography is
   3267 # using)).
-> 3268 _lib.OpenSSL_add_all_algorithms()
   3269 
   3270 # This is similar but exercised mainly by exception_from_error_queue.  It calls

AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

**Comment by mayankmalik-colab** [comment]
It seems you need to upgrade pyopenssl. Please refer the [issue](https://github.com/deepmind/alphafold/issues/707) from deepmind's alphafold repo.

`!pip install --upgrade pyopenssl`

I hope it works.
