### ISSUE TITLE
Upgrade to Python 3.9

### ISSUE THREAD

**Issue by mayankmalik-colab** [googlecolab/colabtools#3450]
### Upgrade to Python 3.9
To provide additional [features from Python 3.9](https://docs.python.org/3/whatsnew/3.9.html) to our users, Colab has upgraded to Python 3.9 (with plans to upgrade to more modern versions in the future). Additionally, this upgrade provides benefits for the packages we pre-install in our runtime, as many can only be upgraded with a newer Python version.

#### Colab’s fallback runtime version

Using the fallback runtime version temporarily allows access to the last version of the runtime before the upgrade described above, and is available until mid-March. Its purpose is to provide a temporary mechanism for users to more smoothly upgrade their notebooks to be compatible with Colab’s current runtime version. This is available from the Command Palette via the "Use fallback runtime version" command when connected to a runtime. Of note, this setting does not persist across sessions – the command will need to be invoked on each new session.

**Comment by earlev4** [comment]
Great news, @mayankmalik-colab! Hopefully, upgrading to Python 3.10 (or 3.11) is not too far away. Thank you! 😄

**Comment by mayankmalik-colab** [comment]
It should take place in next 1-2 weeks. I am sorry I can't specify a date yet, but we are trying our best to rollout as soon as possible.

**Comment by francesco-ballarin** [comment]
Thanks @mayankmalik-colab ! For future announcements, it would be great if you could include a tentative timeline in the first post (even "in the next 1-2 weeks" would be good!), and once the upgrade rolls out reply to the issue saying that the upgrade is live, so that anyone who subscribed to the issue gets notified about that. Thanks for your understanding!

**Comment by MedicDoesStuff** [comment]
Hey, looks like this update broke my notebook once again. opencv-python==4.1.2.30 won't work and i tried updating to later versions but they don't work with my code. May anyone help me?

**Comment by mayankmalik-colab** [comment]
It seems like you must be installing `opencv-python==4.1.2.30` in the notebook because we are already on `opencv-python=4.6.0.66` by default. As per the [official pypi page](https://pypi.org/project/opencv-python/4.1.2.30/), `opencv-python==4.1.2.30` is quit old and is not compatible with python 3.9. As mentioned on top of this issue, use can use the fallback version for a few more days, which is on python 3.8.  However, I would strongly recommend upgrading the notebook so that it is compatible with the newer version of opencv-python.

**Comment by MedicDoesStuff** [comment]
Are you guys planning to add something like a Python version selector if possible? I know that for security-performance sakes you are doing updates on Colab but I'm pretty sure my code only works on versions below 3.9 (atleast before i fix it although low chance i'm not really coding-savvy).

**Comment by Valdegg** [comment]
Hey,

This updated rolled out just as I was putting the finishing touch on a prototype which uses a library that requires Python <= 3.8.

I tried changing the python version manually: "!sudo update-alternatives --config python3"
But after I install pip and all the libraries I need, it's necessary to restart the runtime.  

And restarting the runtime doesn't work (or it takes forever).

Is there any way to still use Python 3.8?

Thanks!

**Comment by anissa218** [comment]
How long will the fallback runtime version be available for?

**Comment by mayankmalik-colab** [comment]
It will be available for a few more days. I can't specify a date unfortunately.

**Comment by yyyiron** [comment]
I don't think it is a good news for me . My code only can be used in python3.8 or 3.7. When I use !sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1 to change my python version. It can be used in jupyter notebook but can't  used in python which when I use "!python install sklearn", jupyter notebook can use it but  it will show "No model name sklearn" in python internal compiler.

![image](https://user-images.githubusercontent.com/51651728/225414982-fe94db98-9258-496b-b811-cd9ede145c7c.png)


As a google colab pro, I feel so sad as what you did. It ruin my code.

**Comment by cakwok** [comment]
I am affected too.  My application run well before this change.  it spent me 2 days to fix until i reached here and able to know what has happened.

As a paid service, I think we deserve to be notified by email of any changes that could lead to disruption.

Now my issue is still stuck.  I installed Yolo8 and there are around 30 third party packages.  i reinstall everything clean it works, but after runtime is deleted and started again, some of the files inside the installed packages would be gone.

Could you pls help to fix the issue?
