### ISSUE TITLE
ModuleNotFoundError: No module named 'limesurveyrc2api.limesurvey'

### ISSUE THREAD

**Issue by AmauryVanEspen** [googlecolab/colabtools#3452]
Hello
I'm facing a bug loading a library

**Describe the current behavior**
Not able to load the limesurveyrc2api library
ModuleNotFoundError: No module named 'limesurveyrc2api.limesurvey'

**Describe the expected behavior**
Be able to use package limesurveyrc2api and the subpackage limesurvey to request API

**What web browser you are using**
Chrome

**Additional context**
Please see [https://github.com/lindsay-stevens/limesurveyrc2api/issues/14](https://github.com/lindsay-stevens/limesurveyrc2api/issues/14)

could you please provide insight ? It seems related to colab and not to the library

Thank you

**Comment by mayankmalik-colab** [comment]
It seems like other people opened the [same issue](https://github.com/lindsay-stevens/limesurveyrc2api/issues/5) on their github repo. This is what they recommended.

`!pip install https://github.com/lindsay-stevens/limesurveyrc2api/archive/master.zip`

I hope it helps. Also, You need to check with the package owner about `!pip install limesurveyrc2api` and maintenance in general . Moreover, I looks very old. Last release was in 2016 and programming language is mentioned Python 3.5. We are on Python 3.8 and moving to 3.9 very soon.
