### ISSUE TITLE
Resource exhausted error during training.

### ISSUE THREAD

**Issue by DNJ-JINI** [googlecolab/colabtools#3455]
I would like to train the deep learning task semantic segmentation. 
 Specifications: model with 31 million  parameters 
 image size ( minimum 1024x1024), batch size 256 framework -tensorflow keras 2.7 
 Total image samples 30,000, 
 Label Mask samples 30,000
 Does colab pro plus allow the training for this specification with out OOM error?
 
Issue currently facing  is even with 2000 number of images and 512x512 size for batch size 32 results in out of memory error in colab pro subscription.

**Comment by DNJ-JINI** [comment]
Hi,
Thanks for your reply,

I am using custom datagenerator using keras.utils.sequence class.

class Customgenerator(keras.utils.Sequence):
    #Helper to iterate over the data (as Numpy arrays)

    def __init__(self, batch_size, img_size, input_img_paths, target_img_paths):
        self.batch_size = batch_size
        self.img_size = img_size
        self.input_img_paths = input_img_paths
        self.target_img_paths = target_img_paths

    def __len__(self):
        return len(self.target_img_paths) // self.batch_size

    def __getitem__(self, idx):
        #Returns tuple (input, target) correspond to batch #idx.
        i = idx * self.batch_size
        batch_input_img_paths = self.input_img_paths[i : i + self.batch_size]
        batch_target_img_paths = self.target_img_paths[i : i + self.batch_size]
        x = np.zeros((self.batch_size,) + self.img_size + (3,), dtype="float32")
        for j, path in enumerate(batch_input_img_paths):
            img = load_img(path, target_size=self.img_size)
            x[j] = img
        y = np.zeros((self.batch_size,) + self.img_size + (1,), dtype="uint8")
        for j, path in enumerate(batch_target_img_paths):
            img = load_img(path, target_size=self.img_size, color_mode="grayscale")
            pixels = list(img.getdata())
            y[j] = np.expand_dims(img, 2)
        return x,y

train_gen = Customgenerator(batch_size, img_size, train_input_img_paths, train_target_img_paths)
val_gen = Customgenerator(batch_size, img_size, val_input_img_paths, val_target_img_paths)


model=model.fit(train_gen, epochs=num_epochs, validation_data=val_gen, callbacks=callbacks)


I am assuming this will load the smaller batches of images at a  time.

**Comment by cperry-goog** [comment]
Yeah, I don't think this is a Colab issue - you'll want to try to reduce the memory thrashing or upgrade to a higher memory GPU (paid plans).
