### ISSUE TITLE
Outputs disappearing

### ISSUE THREAD

**Issue by dquatrocchi** [googlecolab/colabtools#3460]
**Describe the current behavior**
When executing the code, outputs render but disappear quickly and become only accessible in full screen.

**Describe the expected behavior**
I should be able to visualize the output without full screen.

**What web browser you are using**
Chrome

**Additional context**
[Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.](https://colab.research.google.com/drive/1CE5iFhXuRxo-wbvDDpVxuMYgW9PkQS93#scrollTo=FYVlJHO04EQg)

**Comment by EvanWiederspan** [comment]
Thanks for the repro notebook. Which cells in particular are you seeing this issue for? Also, does the issue still happen for you in incognito mode?
