### ISSUE TITLE
Unrecognized arguments YAML error

### ISSUE THREAD

**Issue by SouCh305** [googlecolab/colabtools#3464]
Hello everyone!
I tried to run this part of **YOLOv7** code:

`!python train.py --device 0 --batch-size 16 --epochs 100 --img 640 640 --data data/custom_data.yaml --hyp data/hyp.scratch.custom.yaml --cgf cfg/training/yolov7x-custom.yaml --weights yolov7x.pt --name yolov7x-custom`

but unfortunatly I found an issue like this: 
`train.py: error: unrecognized arguments: --cgf cfg/training/yolov7x-custom.yaml`

How can I solve it? Is there any solution?

**Comment by mayankmalik-colab** [comment]
I think the argument should be `--cfg` instead of `--cgf`. Hope that works.

**Comment by SouCh305** [comment]
It worked. I didn't notice that error. Thank you
