### ISSUE TITLE
Upgrade httpimport from version 0.5.18 to latest version: 1.3.0

### ISSUE THREAD

**Issue by janderson2024** [googlecolab/colabtools#3469]
**Problem**
The 0.5.18 version of httpimport came out almost 4 years ago, and during that time new features have been added, and a bunch of the functions have changed. With this the documentation also updated making it difficult to try and work with this outdated 0.5.18 version.

**Solution**
Update the runtime version to 1.3.0.

**Alternative**
Update to the 1.0.0 release as that provides most of the modern features documents on the Github repository.

**Additional**
- [Current version PyPi link](https://pypi.org/project/httpimport/)
- [1.0.0 PyPi link](https://pypi.org/project/httpimport/1.0.0/)
- [Github link](https://github.com/operatorequals/httpimport)

**Comment by EvanWiederspan** [comment]
1.3 is now installed by default
