### ISSUE TITLE
Unable to type in the desired cell inspite of selecting the cell and clicking on it.

### ISSUE THREAD

**Issue by ashudhakd** [googlecolab/colabtools#3476]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
The problem is that whenever i use colab for python coding , in starting everything works properly and then after executing  3-4 cells then there becomes more than one cursor blinking in different cells at the same time. So when i want to type in particular cell then it is not being typed in the cell in which i clicked the mouse.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
I expect that whichever cell i click , it should be typed there only but as i have mentioned above that it is getting typed in another cell.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Google Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
Does this still happen for you in incognito mode, with extension disabled? Also I'm curious if you have sticky keys or something similar enabled that is keeping the alt key down, which would create multiple cursors

**Comment by ashudhakd** [comment]
Yes it still happens for me in incognito mode, with extension disabled.
I have installed Alt-C application for copy paste the content, so i don't
know whether it is only creating this issue or what.
