### ISSUE TITLE
Bokeh show_app is currently unsupported

### ISSUE THREAD

**Issue by Tirtho2000** [googlecolab/colabtools#3477]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
Can you provide a minimal repro notebook?

**Comment by joamatab** [comment]
Hi, i found the same issue

here is a colab example not working

https://colab.research.google.com/drive/1W96Re-rINGbQJ8KAhGTD1_fyP5nHpdW7?usp=sharing
