### ISSUE TITLE
Colab: allow connections to other host than localhost

### ISSUE THREAD

**Issue by matthiasamberg** [googlecolab/colabtools#3478]
**Is your feature request related to a problem? Please describe.**
I setup a custom Ubuntu VM on GCE that runs a jupyter notebook server. I cannot connect to it from a colab notebook.

**Describe the solution you'd like**
However "connect to a local runtime" seems to check whether the URL is actually localhost or not. I'd like to be able to enter any IP/Host for Google Colab to connect to, not just localhost.

**Describe alternatives you've considered**
* Using a jupyter environment instead of Google Colab

**Additional context**
* You make it hard to run a Colab backend on your own cloud. The official Colab Server Image does not allow any connection to Google Drive. Being able to setup my own jupyter backend would allow me to set up a custom Google Drive binding.

**Comment by cperry-goog** [comment]
Port forwarding will work for you right?
https://research.google.com/colaboratory/local-runtimes.html
"Connecting to a runtime on a Google Compute Engine instance"

The Drive connection requires special handling with auth + credentials we can't support anywhere other than our managed runtimes sorry.

We've got some work in flight that will make GCP connections easier/better.

**Comment by USeebi** [comment]
How about If I want to keep using the frontend kernel while forwarding udp socket connect to the backend host.  Currently I could do this by adding route at the ISP router which is not always possible. Is there any way to do the tunneling just as local-runtime connection?
