### ISSUE TITLE
Files disappearing from gdrive copied with shutil.copy

### ISSUE THREAD

**Issue by ghost** [googlecolab/colabtools#348]
Files start to slowly disappear from gdrive that I copied from one folder on my gdrive to another folder on my gdrive.

I mounted my gdrive in colab as recommended [here](https://colab.research.google.com/notebooks/io.ipynb):
```
from google.colab import drive
drive.mount('/content/gdrive')
```

How to repro:
1. Have, let's say, 512 files in `your-gdrive/folder-A`
1. Copy all 512 files in a for loop via `shutil.copy(...)` to `your-gdrive/folder-B`
1. **Delete folder `your-gdrive/folder-B` on gdrive web gui**
1. Feel free to wait a minute to make sure deletion is completed
1. Do steps 1-2 again
1. Observe that right after copying, `your-gdrive/folder-B` has 512 files
1. Wait one minute
1. Observe that `your-gdrive/folder-B` has less files, e.g. 492 files
1. Wait one minute
1. Observe that `your-gdrive/folder-B` has less files, e.g. 471 files
1. Wait one minute
1. Observe that `your-gdrive/folder-B` has less files, e.g. 439 files

I'm not sure whether all of them are going to disappear eventually and whether they keep disappearing with the same pace, but I can 100% repro this every time I redo step 2) into an empty `your-gdrive/folder-B`.

Why are the files disappearing? Who can I work around this?

**EDIT:**
Did some additional investigation and it repros only if I deleted `your-gdrive/folder-B` earlier on the gdrive web GUI. Updated the repro steps.

To me it feels like gdrive keeps deleting future files that I'll put into `your-gdrive/folder-B` even minutes after I did the "delete folder" action.

**Comment by Abanobbb** [comment]
same issue
