### ISSUE TITLE
Problem installing pytorch/xla in google colab

### ISSUE THREAD

**Issue by alekseybaev** [googlecolab/colabtools#3481]
Hi !
I am doing machine learning in Google Collab environment with pytorch/xla. 
I wanted to work at TPU. To do this, I did the installation as recommended:  
'!pip install cloud-tpu-client==0.10 torch==1.13.0 https://storage.googleapis.com/tpu-pytorch/wheels/colab/torch_xla-1.13-cp38-cp38-linux_x86_64.whl tensorboard-plugin- profile'.
It was all working properly and worked well, but some time ago (2-3 days) it stopped working and Collab told me:
'ERROR: torch_xla-1.13-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform'.
Please tell me how to solve this problem??

**Comment by sdfasfsdfasfasafd** [comment]
Bcz the colab update the python to 3.9.
It have appeared previously when the python update from 3.7 to 3.8.
you can use through this way:
First, you can click Tool → Command palette
and then, input "use fallback funtime version " 
this will solve your problem until the wheel update.

**Comment by alekseybaev** [comment]
Thanks, this is the solution. But I also want to know the solution for the new Colab environment with Python 3.9

**Comment by AlvinKimata** [comment]
The command below worked for me on a google colab runtime using python 3.10.

```bash
!pip install cloud-tpu-client==0.10 torch==2.0.0 torchvision==0.15.1 https://storage.googleapis.com/tpu-pytorch/wheels/colab/torch_xla-2.0-cp310-cp310-linux_x86_64.whl
```

**Comment by Ultracatx** [comment]
> The command below worked for me on a google colab runtime using python 3.10.
> 
> ```shell
> !pip install cloud-tpu-client==0.10 torch==2.0.0 torchvision==0.15.1 https://storage.googleapis.com/tpu-pytorch/wheels/colab/torch_xla-2.0-cp310-cp310-linux_x86_64.whl
> ```

It works for me too. Thanks for the information.

**Comment by mooniub428** [comment]
> The command below worked for me on a google colab runtime using python 3.10.
> 
> ```shell
> !pip install cloud-tpu-client==0.10 torch==2.0.0 torchvision==0.15.1 https://storage.googleapis.com/tpu-pytorch/wheels/colab/torch_xla-2.0-cp310-cp310-linux_x86_64.whl
> ```

thank you brother its working

**Comment by gametimebrizzle** [comment]
> The command below worked for me on a google colab runtime using python 3.10.
> 
> ```shell
> !pip install cloud-tpu-client==0.10 torch==2.0.0 torchvision==0.15.1 https://storage.googleapis.com/tpu-pytorch/wheels/colab/torch_xla-2.0-cp310-cp310-linux_x86_64.whl
> ```

Can confirm working, thanks @AlvinKimata
