### ISSUE TITLE
Fail to upload in both Google chrome and Safari

### ISSUE THREAD

**Issue by StatPort** [googlecolab/colabtools#3482]
**Describe the current behavior**
Fail to upload files in Chrome and Safari. It does not work to click on "upload" neither to upload with from google.colab import files
uploaded = files.upload(). 

**Describe the expected behavior**
Upload data. 

**What web browser you are using**
Chrome, Safari

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
Just tried this and it works for me, does it work for you in incognito mode? Also, which browser versions are you using?
