### ISSUE TITLE
Issue with condacolab for the installation of package xgems

### ISSUE THREAD

**Issue by gegelagaffe** [googlecolab/colabtools#3487]
Hi, i used a conda package named xgems for 6 months and from this morning i can't install it. It's seems something change in colab  recently. Could you help me to fix this problem?

Could you tell me how to solve this error :

**my script :**

!pip install -q condacolab
import condacolab
condacolab.install()

**then**
!conda install -c conda-forge xgems

**The output :**

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: done

Package Plan

environment location: /usr/local

added / updated specs:

xgems

The following packages will be downloaded:

package | build ---------------------------|----------------- brotlipy-0.7.0 |py39hb9d737c_1005 342 KB conda-forge ca-certificates-2022.12.7 | ha878542_0 143 KB conda-forge certifi-2022.12.7 | pyhd8ed1ab_0 147 KB conda-forge cffi-1.15.1 | py39he91dace_3 229 KB conda-forge chemicalfun-0.1.8 | py39h4b4f3f3_0 401 KB conda-forge colorama-0.4.6 | pyhd8ed1ab_0 25 KB conda-forge conda-23.1.0 | py39hf3d152e_0 906 KB conda-forge cryptography-38.0.4 | py39h3ccb8fc_0 1.3 MB conda-forge gems3k-4.3.3 | he78764c_3 2.0 MB conda-forge libmambapy-1.0.0 | py39h37259de_2 298 KB conda-forge libsodium-1.0.18 | h36c2ea0_1 366 KB conda-forge mamba-1.0.0 | py39hc5d2bb1_2 47 KB conda-forge nlohmann_json-3.11.2 | h27087fc_0 112 KB conda-forge openssl-3.0.8 | h0b41bf4_0 2.5 MB conda-forge pluggy-1.0.0 | pyhd8ed1ab_5 16 KB conda-forge pycosat-0.6.4 | py39hb9d737c_1 108 KB conda-forge python-3.9.16 |h2782a2a_0_cpython 23.0 MB conda-forge python_abi-3.9 | 3_cp39 6 KB conda-forge ruamel.yaml-0.17.21 | py39h72bdee0_3 184 KB conda-forge ruamel.yaml.clib-0.2.7 | py39h72bdee0_1 140 KB conda-forge ruamel_yaml-0.15.80 |py39hb9d737c_1008 255 KB conda-forge spdlog-1.11.0 | h9b3ece8_1 216 KB conda-forge thermofun-0.4.3 | py39h0069ca6_0 1.1 MB conda-forge tqdm-4.65.0 | pyhd8ed1ab_1 86 KB conda-forge tzdata-2022g | h191b570_0 106 KB conda-forge xgems-1.0.5 | py39hf939315_3 952 KB conda-forge zeromq-4.3.4 | h9c3ff4c_1 351 KB conda-forge zstandard-0.19.0 | py39h29414ee_1 373 KB conda-forge ------------------------------------------------------------ Total: 35.7 MB

The following NEW packages will be INSTALLED:

chemicalfun conda-forge/linux-64::chemicalfun-0.1.8-py39h4b4f3f3_0 None
colorama conda-forge/noarch::colorama-0.4.6-pyhd8ed1ab_0 None
gems3k conda-forge/linux-64::gems3k-4.3.3-he78764c_3 None
libsodium conda-forge/linux-64::libsodium-1.0.18-h36c2ea0_1 None
nlohmann_json conda-forge/linux-64::nlohmann_json-3.11.2-h27087fc_0 None
pluggy conda-forge/noarch::pluggy-1.0.0-pyhd8ed1ab_5 None
ruamel.yaml conda-forge/linux-64::ruamel.yaml-0.17.21-py39h72bdee0_3 None
ruamel.yaml.clib conda-forge/linux-64::ruamel.yaml.clib-0.2.7-py39h72bdee0_1 None
spdlog conda-forge/linux-64::spdlog-1.11.0-h9b3ece8_1 None
thermofun conda-forge/linux-64::thermofun-0.4.3-py39h0069ca6_0 None
tqdm conda-forge/noarch::tqdm-4.65.0-pyhd8ed1ab_1 None
tzdata conda-forge/noarch::tzdata-2022g-h191b570_0 None
xgems conda-forge/linux-64::xgems-1.0.5-py39hf939315_3 None
zeromq conda-forge/linux-64::zeromq-4.3.4-h9c3ff4c_1 None

The following packages will be UPDATED:

ca-certificates 2022.9.24-ha878542_0 --> 2022.12.7-ha878542_0 None
certifi 2022.9.24-pyhd8ed1ab_0 --> 2022.12.7-pyhd8ed1ab_0 None
cffi 1.15.1-py38h4a40e3a_2 --> 1.15.1-py39he91dace_3 None
conda 22.9.0-py38h578d9bd_2 --> 23.1.0-py39hf3d152e_0 None
openssl 3.0.7-h0b41bf4_1 --> 3.0.8-h0b41bf4_0 None
python 3.8.15-h4a9ceb5_0_cpython --> 3.9.16-h2782a2a_0_cpython None
python_abi 3.8-3_cp38 --> 3.9-3_cp39 None

The following packages will be DOWNGRADED:

brotlipy 0.7.0-py38h0a891b7_1005 --> 0.7.0-py39hb9d737c_1005 None
cryptography 38.0.4-py38h80a4ca7_0 --> 38.0.4-py39h3ccb8fc_0 None
libmambapy 1.0.0-py38h2cd2533_2 --> 1.0.0-py39h37259de_2 None
mamba 1.0.0-py38haad2881_2 --> 1.0.0-py39hc5d2bb1_2 None
pycosat 0.6.4-py38h0a891b7_1 --> 0.6.4-py39hb9d737c_1 None
ruamel_yaml 0.15.80-py38h0a891b7_1008 --> 0.15.80-py39hb9d737c_1008 None
zstandard 0.19.0-py38h5945529_1 --> 0.19.0-py39h29414ee_1 None

Downloading and Extracting Packages
spdlog-1.11.0 | 216 KB | : 100% 1.0/1 [00:00<00:00, 4.46it/s]
tqdm-4.65.0 | 86 KB | : 100% 1.0/1 [00:00<00:00, 11.83it/s]
brotlipy-0.7.0 | 342 KB | : 100% 1.0/1 [00:00<00:00, 7.69it/s]
libmambapy-1.0.0 | 298 KB | : 100% 1.0/1 [00:00<00:00, 7.52it/s]
pluggy-1.0.0 | 16 KB | : 100% 1.0/1 [00:00<00:00, 21.07it/s]
zstandard-0.19.0 | 373 KB | : 100% 1.0/1 [00:00<00:00, 16.36it/s]
tzdata-2022g | 106 KB | : 100% 1.0/1 [00:00<00:00, 5.38it/s]
pycosat-0.6.4 | 108 KB | : 100% 1.0/1 [00:00<00:00, 14.00it/s]
thermofun-0.4.3 | 1.1 MB | : 100% 1.0/1 [00:00<00:00, 6.67it/s]
zeromq-4.3.4 | 351 KB | : 100% 1.0/1 [00:00<00:00, 5.72it/s]
colorama-0.4.6 | 25 KB | : 100% 1.0/1 [00:00<00:00, 19.14it/s]
xgems-1.0.5 | 952 KB | : 100% 1.0/1 [00:00<00:00, 12.74it/s]
certifi-2022.12.7 | 147 KB | : 100% 1.0/1 [00:00<00:00, 20.96it/s]
ca-certificates-2022 | 143 KB | : 100% 1.0/1 [00:00<00:00, 19.13it/s]
ruamel.yaml-0.17.21 | 184 KB | : 100% 1.0/1 [00:00<00:00, 13.57it/s]
libsodium-1.0.18 | 366 KB | : 100% 1.0/1 [00:00<00:00, 6.29it/s]
python-3.9.16 | 23.0 MB | : 100% 1.0/1 [00:01<00:00, 1.49s/it]
ruamel_yaml-0.15.80 | 255 KB | : 100% 1.0/1 [00:00<00:00, 7.07it/s]
chemicalfun-0.1.8 | 401 KB | : 100% 1.0/1 [00:00<00:00, 13.82it/s]
gems3k-4.3.3 | 2.0 MB | : 100% 1.0/1 [00:00<00:00, 2.61it/s]
nlohmann_json-3.11.2 | 112 KB | : 100% 1.0/1 [00:00<00:00, 8.54it/s]
python_abi-3.9 | 6 KB | : 100% 1.0/1 [00:00<00:00, 22.81it/s]
cffi-1.15.1 | 229 KB | : 100% 1.0/1 [00:00<00:00, 15.00it/s]
mamba-1.0.0 | 47 KB | : 100% 1.0/1 [00:00<00:00, 12.36it/s]
cryptography-38.0.4 | 1.3 MB | : 100% 1.0/1 [00:00<00:00, 3.76it/s]
conda-23.1.0 | 906 KB | : 100% 1.0/1 [00:00<00:00, 2.76it/s]
ruamel.yaml.clib-0.2 | 140 KB | : 100% 1.0/1 [00:00<00:00, 15.90it/s]
openssl-3.0.8 | 2.5 MB | : 100% 1.0/1 [00:00<00:00, 3.09it/s]
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... failed
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/conda/exceptions.py", line 1129, in call
File "/usr/local/lib/python3.8/site-packages/conda/cli/main.py", line 86, in main_subshell
File "/usr/local/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
File "/usr/local/lib/python3.8/site-packages/conda/notices/core.py", line 75, in wrapper
File "/usr/local/lib/python3.8/site-packages/conda/notices/core.py", line 39, in display_notices
File "/usr/local/lib/python3.8/site-packages/conda/notices/http.py", line 36, in get_notice_responses
File "/usr/local/lib/python3.8/site-packages/conda/notices/http.py", line 39, in
File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result
File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
File "/usr/local/lib/python3.8/site-packages/conda/notices/http.py", line 42, in
File "/usr/local/lib/python3.8/site-packages/conda/notices/cache.py", line 37, in wrapper
File "/usr/local/lib/python3.8/site-packages/conda/notices/http.py", line 58, in get_channel_notice_response
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 460, in send
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 263, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /usr/local/lib/python3.8/site-packages/certifi/cacert.pem

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/bin/conda", line 15, in
File "/usr/local/lib/python3.8/site-packages/conda/cli/main.py", line 129, in main
File "/usr/local/lib/python3.8/site-packages/conda/exceptions.py", line 1429, in conda_exception_handler
File "/usr/local/lib/python3.8/site-packages/conda/exceptions.py", line 1132, in call
File "/usr/local/lib/python3.8/site-packages/conda/exceptions.py", line 1172, in handle_exception
File "/usr/local/lib/python3.8/site-packages/conda/exceptions.py", line 1183, in handle_unexpected_exception
File "/usr/local/lib/python3.8/site-packages/conda/exceptions.py", line 1245, in print_unexpected_error_report
ModuleNotFoundError: No module named 'conda.cli.main_info'

**I tried to import my package, it was not installed.**

**Comment by mayankmalik-colab** [comment]
Yes, we recently moved from [Python 3.8 to Python 3.9](https://github.com/googlecolab/colabtools/issues/3450). It seems like the packages invloved are not compatible with Python 3.9. I would request you to reach out to the package owners and file it upstream. I can see the references of `python3.8` paths during the installation too.

In the meanwhile, you can still use Python 3.8 for a few more days using the fallback version. Check [colab’s fallback runtime version](https://github.com/googlecolab/colabtools/issues/3450#issue-1603586822 ) section.
