### ISSUE TITLE
Cannot pip install transformers of version 2.X.X and 3.X.X

### ISSUE THREAD

**Issue by poix3** [googlecolab/colabtools#3490]
**Describe the current behavior**
Cannot pip install transformers of version 2.X.X and 3.X.X

**Describe the expected behavior**
Successfully installed

**What web browser you are using**
Chrome

**Additional context**
https://colab.research.google.com/drive/1W9iCRM9hjH0jcQ1x1TxxhbI-N6TYhbC3?usp=sharing

**Comment by mayankmalik-colab** [comment]
Thank you for reporting to us.  We migrated to from Python 3.8 to Python 3.9 last week and the older versions of transformers (version 2.X.X and 3.X.X) require older versions of `tokenizers`, which are compatible not compatible with Python 3.9. Hence, I would recommend pip installing the latest transformers, which would bring in the latest dependencies. I am sure those would work.

**Comment by poix3** [comment]
so is there any way to use the older versions in Colab?

**Comment by cperry-goog** [comment]
We don't support downgrading our Python version sorry.
