### ISSUE TITLE
Bug that prevents training from progressing

### ISSUE THREAD

**Issue by skeleton66** [googlecolab/colabtools#3491]
Sometimes a cell remains running and the training (step) does not proceed.

**Comment by skeleton66** [comment]
Specifically, it seems that after one epoch is completed, it is no longer possible to go to the steps.

**Comment by skeleton66** [comment]
If you stop the cell and run it again, it stops at the same place and you have to restart the runtime to continue.

**Comment by mco-gh** [comment]
Can you share a minimal reproducible notebook so we can investigate?

**Comment by skeleton66** [comment]
https://colab.research.google.com/drive/1eEwa5KmHrwZ06vM4CxkQyq6DAT_rSUMW?usp=sharing

**Comment by mco-gh** [comment]
Thanks for the link. Can you specify the exact sequence of events that triggers your problem?

**Comment by skeleton66** [comment]
It happens with "训练", which generates an audio file.

**Comment by skeleton66** [comment]
It is not clear exactly when this will occur.

**Comment by skeleton66** [comment]
Presumably, it seems that when saving a composite file to Google Drive, it cannot be saved forever.

**Comment by mco-gh** [comment]
Sorry, I think it's going to be difficult to debug this without a simple reproducible sequence. I'd recommend asking for support on StackOverflow.
