### ISSUE TITLE
Not able to install pysurvival

### ISSUE THREAD

**Issue by FayeqJeelani12** [googlecolab/colabtools#3493]
pysurvival is not getting installed on 3.9.

**Comment by mayankmalik-colab** [comment]
The last release from pysurvival was in 2019 and it seems to be compatible until Python 3.7. We are aready on Python 3.9. I would encourage to file it upstream so that they make it compatible with higher version sof Python.

**Comment by FayeqJeelani12** [comment]
Since pysurvival is compatible with up to python 3.7, new upgrade on Colab's python to 3.9.6 does not let it get installed. I downgraded Colab to 3.7, it still does not work. Would really appreciate any help.

**Comment by FayeqJeelani12** [comment]
I submitted for upstream updating but not sure when it happens. Is there a way to downgrade our Colab to a previous version? I changed the version to 3.7 for a particular file, but it still has problems with pysurvival.

**Comment by cperry-goog** [comment]
We don't support downgrades of our Python version, sorry.
