### ISSUE TITLE
After Installing Python 3.11.2, using @dataclass(slots=True) raises TypeError: dataclass() got an unexpected keyword argument 'slots' 

### ISSUE THREAD

**Issue by MhamedBendenia** [googlecolab/colabtools#3496]
![image](https://user-images.githubusercontent.com/32708606/224962897-16841a8b-3961-424e-96a9-08a6fdbaf4f3.png)

**Comment by mayankmalik-colab** [comment]
The python upgrade is not supported in Colab. We just [upgraded to Python 3.9](#3450) and will try to do future upgrades as soon as we can.
