### ISSUE TITLE
vpython

### ISSUE THREAD

**Issue by jonschull** [googlecolab/colabtools#35]
!pip install vpython worked
but import vpython hangs.

If I interrupt runtime we seem to be stuck in sleep

-------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-1-e4499da0af58> in <module>()
----> 1 import vpython

/usr/local/lib/python3.6/dist-packages/vpython/__init__.py in <module>()
     35     from .with_notebook import *
     36 else:
---> 37     from .no_notebook import *
     38 

/usr/local/lib/python3.6/dist-packages/vpython/no_notebook.py in <module>()
    157 
    158 while not (httpserving and websocketserving): # try to make sure setup is complete
--> 159     rate(60)
    160 
    161 GW = GlowWidget()

/usr/local/lib/python3.6/dist-packages/vpython/vpython.py in __call__(self, N)
    209         self.rval = N
    210         if self.rval < 1: raise ValueError("rate value must be greater than or equal to 1")
--> 211         super(_RateKeeper2, self).__call__(self.rval) ## calls __call__ in rate_control.py
    212 
    213 if sys.version > '3':

/usr/local/lib/python3.6/dist-packages/vpython/rate_control.py in __call__(self, maxRate)
    205             dt = self.lastSleep + self.calls*(self.userTime + self.callTime + self.delay) + \
    206                  renders*self.renderTime + sleeps*self.interactionPeriod - _clock()
--> 207             _sleep(dt)
    208             self.lastSleep = _clock()
    209             self.calls = 0

/usr/local/lib/python3.6/dist-packages/vpython/rate_control.py in _sleep(dt)
     47         dtsleep = nticks*_tick
     48         t = _clock()
---> 49         time.sleep(dtsleep)
     50         t = _clock()-t
     51         dt -= t

KeyboardInterrupt:

**Comment by jonschull** [comment]
https://drive.google.com/file/d/1D1Iv_pkrhu2n7bjV1PfTtQaBEYcpozWY/view?usp=sharing

**Comment by colaboratory-team** [comment]
I'd recommend following up with the vpython maintainers. It will likely require some knowledge of its internals to diagnose this issue.
