### ISSUE TITLE
Upgrading PyTorch to v2.0.0 and torchvision to v0.15.1 and torchaudio to v2.0.1

### ISSUE THREAD

**Issue by weiwangmeta** [googlecolab/colabtools#3503]
Hello,

We released

pytorch v2.0.0
torchvision v0.15.1
torchaudio v2.0.1
The wheel links are:

pytorch
CUDA 11.7

[download.pytorch.org/whl/cu117/torch-2.0.0%2Bcu117-cp38-cp38-linux_x86_64.whl]( https://download.pytorch.org/whl/cu117/torch-2.0.0%2Bcu117-cp38-cp38-linux_x86_64.whl)

torchvision
CUDA 11.7
[download.pytorch.org/whl/cu117/torchvision-0.15.1%2Bcu117-cp38-cp38-linux_x86_64.whl](https://download.pytorch.org/whl/cu117/torchvision-0.15.1%2Bcu117-cp38-cp38-linux_x86_64.whl)

torchaudio
CUDA 11.7
[download.pytorch.org/whl/cu117/torchaudio-2.0.1%2Bcu117-cp38-cp38-linux_x86_64.whl](https://download.pytorch.org/whl/cu117/torchaudio-2.0.1%2Bcu117-cp38-cp38-linux_x86_64.whl)

Other notes
If you require wheels for Python 3.9 / 3.10 or 3.11, you can find the links here: [download.pytorch.org/whl/torch_stable.html](https://download.pytorch.org/whl/torch_stable.html)

We're looking to having it updated in Colab.

Thanks very much.

cc'ing @colaboratory-team

Similar to https://github.com/googlecolab/colabtools/issues/3298

**Comment by mayankmalik-colab** [comment]
Hi @weiwangmeta, we will upgrade as soon as possible. Since we have moved from [Python 3.8 to 3.9](https://github.com/googlecolab/colabtools/issues/3450) last week, we would appreciate if you could mention Python 3.9 wheels directly from next time onwards. Thanks

Tracked internally at b/273877327.

**Comment by weiwangmeta** [comment]
Thanks, we will directly link Python 3.9 wheels in future requests like this. 
BTW, wheels also available on PYPI: 
https://pypi.org/project/torch/#files 
https://pypi.org/project/torchvision/#files
https://pypi.org/project/torchaudio/#files

**Comment by atalman** [comment]
Hi  @colaboratory-team and @mayankmalik-colab  could you please provide ETA for this ?

**Comment by malfet** [comment]
Since we have all packages on the PyPI, would that be reasonable to install from there, rather than from a private repo?
