### ISSUE TITLE
Syntax checker fails to recognize "!" if not at the first character of lines

### ISSUE THREAD

**Issue by tueda** [googlecolab/colabtools#3507]
**Describe the current behavior**

The Python syntax checker on Colab recognizes IPython's system command execution (`!`) if it is at the first character of lines. `!` is highlighted in blue colour:

![image](https://user-images.githubusercontent.com/1481665/225489794-3168b81d-80d6-4618-a22f-e9d5fc46543a.png)

This is OK and works well as expected.

But it fails and wrongly gives syntax error markers (red lines) when `!` is not at the first character:

![image](https://user-images.githubusercontent.com/1481665/225487661-847d98f6-2674-423d-858f-787f613e59b2.png)

In addition, only the first `!` of  `!!` is highlighted:

![image](https://user-images.githubusercontent.com/1481665/225488238-3c14b98f-2081-462c-bd63-51cedc605b5e.png)

**Describe the expected behavior**

All `!` (and both `!` of `!!`) in the above examples are expected to be highlighted in blue colour. No syntax error markers should appear. 

**What web browser you are using**

Chrome

**Additional context**
- 
See https://ipython.readthedocs.io/en/stable/interactive/reference.html#manual-capture-of-command-output-and-magic-output for `!` and `!!` in IPython.

**Comment by EvanWiederspan** [comment]
This is now fixed, thanks for the report!
