### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Radhika-Keni** [googlecolab/colabtools#3508]
Hi , 
I am using Google Colab Pro+
My runtime is at **GPU Premium class**

 I am seeing the following error :

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.75 GiB (GPU 0; 39.56 GiB total capacity; 30.61 GiB already allocated; 1.01 GiB free; 36.55 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF.

How can I opt for more memory , please advice ? I'm on premium settings

**Comment by cperry-goog** [comment]
Looks like you're running on our highest memory GPU class -- I actually don't know if it's possible to get a GPU class higher than that as an individual. You could try to launch a machine via Marketplace instead: https://research.google.com/colaboratory/marketplace.html
