### ISSUE TITLE
Error : Failed to execute cell. Could not send execute message to runtime: [object Event]

### ISSUE THREAD

**Issue by jplet** [googlecolab/colabtools#351]
Hi, 

I'm trying to run a colab notebook in Python 3, but whenever I try to run a cell, this error message comes up : 

Error : Failed to execute cell. Could not send execute message to runtime: [object Event]. 

I've made sure I'm connected to a hosted runtime and that my runtime type is either TPU or GPU. Also, the problem started when I attempted to upload a file in the following way:

```
from google.colab import files;
files_= files.upload("file name")
```

Afterwards I removed those lines and simply tried mounting my drive folder as the local repositry:

```
from google.colab import drive;
drive.mount('/content/drive')
```

Still not working.
Anybody came up with something similar? I tried restarting my computer, restarting colab, no success; I can't run a cell with google colab anymore.

**Comment by colaboratory-team** [comment]
You can verify your backend type using the runtime settings in the Runtime menu -> Change runtime type.

Please do check for errors on the [Javascript console](https://developers.google.com/web/tools/chrome-devtools/console/) and include those in your report.

A few things to try:
1. Refresh the browser tab
1. Try to reproduce the issue in an incognito window. (Extensions often cause issues of this type.)
1. Reset all runtimes using the Runtime menu -> Reset all runtimes... item.

If you can discover a reliable way to reproduce this issue, we can take a closer look.

**Comment by jplet** [comment]
Somehow, it's now working. I closed everything and re-opened my colab, and managed to run the cells. The strange part is that I had already tried that, without success.

Thank you for your help, if I get the error again I'll check for errors as you described.

JP

**Comment by shreyajain34** [comment]
@colaboratory-team  I am facing similar problems. I tried whatever you suggested, it still ain't working. I keep getting runtime errors because of the error: 
Error : Failed to execute cell. Could not send execute message to runtime:
