### ISSUE TITLE
XlaRuntimeError: INTERNAL: RET_CHECK failure      [BUG, REPLY-NEEDED]

### ISSUE THREAD

**Issue by RamiCassia** [googlecolab/colabtools#3515]
Hello,

I am getting the following error when I run a code utilising JAX's vmap() transformation: 

#########################################################################################

`UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INTERNAL: RET_CHECK failure (external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:641) dnn != nullptr

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

XlaRuntimeError                           Traceback (most recent call last)
<decorator-gen-53> in timeit(self, line, cell, local_ns)

[/usr/local/lib/python3.9/dist-packages/IPython/core/magics/execution.py](https://localhost:8080/#) in timeit(self, number)
    167         gc.disable()
    168         try:
--> 169             timing = self.inner(it, self.timer)
    170         finally:
    171             if gcold:

<magic-timeit> in inner(_it, _timer)

XlaRuntimeError: INTERNAL: RET_CHECK failure (external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:641) dnn != nullptr`

###############################################################################################

The code was running perfectly fine 4 days ago but for some reason the very same code is returning an error today - so I am assuming this could be an issue from Google's side

Any advice or support would be appreciated

**Comment by RamiCassia** [comment]
Many thanks for getting back. Here is a minimum repro code:

`import numpy as np
import jax
import jax.numpy as jnp
from jax import device_put

import torch

def compute_dots(P, K, L, Kinv, dif):

    A=jnp.dot(K,L)
    A=jnp.dot(A,Kinv)
    
    return P.at[:].set(jnp.dot(A,dif))

compute_dots_vmap = jax.vmap(compute_dots, in_axes = (1, 2, 2, 2, 1))


def func(I,nx):


    a=I[0];
    b=I[1];
    c=I[2];

    s = I.copy()
    s = s.at[1].set(s[1]*a)
    s = s.at[2].set(s[2]*a)

    P=jnp.zeros((3,nx-1))
  

 
    dif = s[:,1:]-s[:,0:-1];

    Kinv = jnp.array([[jnp.ones(nx - 1),   jnp.ones(nx - 1),    jnp.ones(nx - 1) ],
                      [jnp.ones(nx - 1),    jnp.ones(nx - 1),   jnp.ones(nx - 1) ],
                      [jnp.ones(nx - 1),    jnp.ones(nx - 1),   jnp.ones(nx - 1) ]]);
            
    K    = jnp.array([[jnp.ones(nx - 1),   jnp.ones(nx - 1),    jnp.ones(nx - 1) ],
                      [jnp.ones(nx - 1),    jnp.ones(nx - 1),   jnp.ones(nx - 1) ],
                      [jnp.ones(nx - 1),    jnp.ones(nx - 1),   jnp.ones(nx - 1) ]]);
    
    L = jnp.array([[jnp.ones(nx - 1),   jnp.ones(nx - 1),    jnp.ones(nx - 1) ],
                      [jnp.ones(nx - 1),    jnp.ones(nx - 1),   jnp.ones(nx - 1) ],
                      [jnp.ones(nx - 1),    jnp.ones(nx - 1),   jnp.ones(nx - 1) ]]);


    P = compute_dots_vmap(P, K, L, Kinv, dif)


    P = P.T
        

    PP=0.5*(P[:,0:nx-1]+P[:,0:nx-1])
    
    #ANS = (PP[:,1:-1]-PP[:,0:-2])

    return PP

func_vmap = jax.jit(jax.vmap(func, in_axes=(0, None)), static_argnums=(1))



I = np.ones((400,3,500))
nx = 500
func_vmap(jnp.array(I), nx)`

I have discovered that the error disappears when I remove 'import torch'. However I need to use pytorch later in my code so removing the import is not an option.

Best wishes
Rami

**Comment by mayankmalik-colab** [comment]
Thanks for the sample code. We were able to reproduce it.  It seems like it happens with torch 1.x versions. We just tested your code with torch 2.0.0 and it works fine. We are submitting torch upgrade to 2.0.0 changes soon and hopefully your code should work fine from early next week. In the meanwhile, we will try to investigate the issue more.

**Comment by metrizable** [comment]
Adding a reference to google/jax/issues/15084 as a possibly related issue and #3503 as one possible remedy.

**Comment by EvanWiederspan** [comment]
We are now on torch 2.0, which should fix this issue. Closing
