### ISSUE TITLE
Open in Colab from DagsHub repositories

### ISSUE THREAD

**Issue by deanp70** [googlecolab/colabtools#3517]
**Is your feature request related to a problem? Please describe.**
DagsHub has almost 20K users that heavily use notebooks for their work. One of their most common requests is the ability to open a notebook committed to DagsHub in Google Colab. Currently they need to pull the notebook, and upload it manually, which is a bad UX for them.

**Describe the solution you'd like**
An open in Colab button on `.ipynb` files committed to DagsHub, same as exists in GitHub or Hugging Face. The DagsHub team is happy to do the development necessary on our end to add support for this.

**Describe alternatives you've considered**
We currently recommend people go the manual route, but that's much less convenient.

**Additional context**
One of our blogs about the Colab API was [quoted here](https://github.com/googlecolab/colabtools/issues/2870#issuecomment-1164896957) by someone on the Colab team - so it seems like there is awareness of our work. I think this could be very useful to the community.

Thanks in advance 🙏

**Comment by cperry-goog** [comment]
Hi Dean - sadly, we're not onboarding other services right now, but we'll keep this in mind as our situation evolves.

**Comment by deanp70** [comment]
Hey @cperry-goog thanks for the response. Are there any external API endpoints that could help us implement this independently?

**Comment by EvanWiederspan** [comment]
No we don't offer any external endpoints like that. If you export your notebooks to either Github or a public Google Drive folder, then users can open the notebooks from there

**Comment by deanp70** [comment]
This is now [implemented](https://dagshub.com/blog/google-colab-integration/), so this issue can be closed
