### ISSUE TITLE
Getting 429 while trying to download google drive files

### ISSUE THREAD

**Issue by AlphaOmega1707** [googlecolab/colabtools#3518]
**Describe the current behavior**
download returns 429 and doesn't download the file at all

**Describe the expected behavior**
the file to be downloaded normally

**What web browser you are using**
Opera GX

**Additional context**
`!curl -L -o 'animeLikeTarotCardArt_v10.safetensors' 'https://drive.google.com/u/5/uc?id=1lGhzr3mCH4kLZsLMV5vElrxmqhYq6UUs&confirm=t'`

**Comment by EvanWiederspan** [comment]
That curl command works for me, are you still seeing this issue?

**Comment by AlphaOmega1707** [comment]
not anymore, i wonder why, should i close this?
