### ISSUE TITLE
taking too long to load data from google drive

### ISSUE THREAD

**Issue by HussamCheema** [googlecolab/colabtools#352]
Google Colab gets busy while executing this code block. Its been busy for last 15 mins. I'm just trying to read images from google drive. Any solution?

```
from google.colab import drive
drive.mount('/content/gdrive')
import os
import cv2
x_train = []
y_train = []

for filename in os.listdir('gdrive/My Drive/training/'):
    x = cv2.imread('gdrive/My Drive/training/'+filename,cv2.IMREAD_GRAYSCALE)
    x = cv2.resize(x, (64,64))
    x_train.append(np.array(x))
    if "cat" in filename:
        y_train.append(1)
    elif "dog" in filename:
        y_train.append(0)
```

**Comment by fischman** [comment]
Can you share a .zip file containing your training data?

**Comment by RGring** [comment]
What was the solution? For me it takes ages to load 89 MB of images (> 1hour) from my google drive.

Mounting:
from google.colab import drive
drive.mount('/content/gdrive')

Image loading:
skimage.io.image(<path_to_image>)

The dataset, that I uploaded to my google drive: https://data.broadinstitute.org/bbbc/BBBC038/ (stage1_train.zp)
