### ISSUE TITLE
Concatenate and align the trajectory Error

### ISSUE THREAD

**Issue by soul-stormer** [googlecolab/colabtools#3520]
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[<ipython-input-7-cc2c20c24c2e>](https://localhost:8080/#) in <module>
     40 ref = [template % int(1)]
     41 
---> 42 u1 = mda.Universe(pdb, flist)
     43 u2 = mda.Universe(pdb, ref)
     44 

9 frames
/usr/local/lib/python3.9/site-packages/MDAnalysis/lib/formats/libdcd.pyx in MDAnalysis.lib.formats.libdcd.DCDFile.open()

OSError: DCD file does not exist

**Comment by EvanWiederspan** [comment]
Could you provide a minimal repro notebook?
