### ISSUE TITLE
Colab Pro+ Runtime Stopping After 10 Hours.

### ISSUE THREAD

**Issue by Great-Bucket** [googlecolab/colabtools#3525]
Notebook settings
hardware: GPU
GPU Class: Premium
Runtime shape: High RAM
Chrome Version 111.0.5563.64 (Official Build) (x86_64)

I am subscribed to Colab Pro+ and started my latest session with 351 compute units.  When the most recent example of the problem described below occurred I still have 195.47 compute units after the system stopped.  I am using StyleGAN3 to train on a set of images that are stored on my Google Drive account.

I expect that the colab runtime will run for close to 24 hours, and then disconnect.

But consistently, it is stopping at close to 10:00:00 or running.  This stopping near this point has happened well over 10 times. 

I the cell output (running train.py) this is always the message when this stopping occurs:

error: Traceback (most recent call last): Exception ignored in: Exception ignored in sys.unraisablehook

Any suggestions as to how to resolve this?

Thank you.

**Comment by ioritree** [comment]
same?
https://github.com/googlecolab/colabtools/issues/3441

**Comment by cperry-goog** [comment]
Looks like you're hitting an error in code, which stops execution (due to the error), and then we'll terminate the runtime based on idle signals. As long as the code is executing and you have compute units, you'll see runtimes of up to 24 hours in length.

**Comment by Great-Bucket** [comment]
Hi cperry-goog,

I do not think you are correct, but I will test further and provide more details soon.

thanks.

**Comment by CathySunshine** [comment]
> which stops execution (due to the error)

@cperry-goog  [#3562](https://github.com/googlecolab/colabtools/issues/3562)
