### ISSUE TITLE
It doesn't save my calculation results

### ISSUE THREAD

**Issue by hanahg** [googlecolab/colabtools#3533]
hi
I have paid for as you GO type.
I have installed my programs and started to run the calculations. I am using Microsoft edge. I redid it all several times, but it seems that google behaves to me like a free-of-charge user and deletes all including software, input data, and results of calculations. 
even though, google counts all codes for me. What is the issue?

**Comment by cperry-goog** [comment]
We recycle runtimes at the end of execution for all users. If you want to save results, you'll want to add in some kind of checkpointing to an external storage solution like Drive.
