### ISSUE TITLE
Google colab 'cannot connect to GPU backend' issue. It have been 6 days already.

### ISSUE THREAD

**Issue by Trumpetsoundsmp4** [googlecolab/colabtools#3534]
Explanation of the entire situation:
Have been using Google colab for writing (with help of Kobold AI (GPU edition)) for a bit while as a hobby. Usually per session (each 1-2 days) was using it for approximately 1 hour. After some time the 'cannot connect to GPU backend' pops up for approximately rest of the day, with which I was fine (I waited and then used it again when it allowed me to).
Now it already have been 6 days (since 22th March) and still same pop up message 'cannot connect to GPU backend'. Yes, I did read FAQ about limited usage of GPU backend (it didn't help at all with figuring out about why this is happening), yes I did search through forums (I could not find anything), yes I did send feedback in colab itself (didn't get any respond/help at all). Yes, I did check daily on this and each time I see same issue. (And yes, I am kinda new to all these stuff. This problem didn't occur before for me).

Current behaviour:
Cannot use GPU backend at all, basically I am blocked from using KoboldAI at all.

Expected behaviour:
Availability to use GPU backend after waiting.

What web browser you are using?
Vivaldi

Additional info:
The account in which this issue is happening - trumpetsound.mp4@gmail.com

**Comment by cperry-goog** [comment]
It looks like you're getting throttled due to high GPU usage. You'll need to pay to upgrade or wait until the throttling calms down.
