### ISSUE TITLE
tidyquant  - R Execution Environment

### ISSUE THREAD

**Issue by jmagomez** [googlecolab/colabtools#3536]
Dear Fellows, I'm trying to install the tidyquant package in the R execution environment from google colab, but I receive this message: "Warning message:
“package ‘tidyquant’ is not available for this version of R"
Could you help me to update this R version?
Best Regards.

**Comment by metrizable** [comment]
@jmagomez Thanks for filing the issue and thanks for using Colab.

I'm able to replicate the behavior you reported. From the CRAN (https://cran.r-project.org/package=tidyquant):

```
Package ‘tidyquant’ was removed from the CRAN repository.
```

Sometimes packages do get removed from the CRAN if they don't pass checks. You may have luck filing an [issue](https://github.com/business-science/tidyquant/issues) upstream with the maintainers to get it added back.

You can also try installing the package from an archived source tarball, although YMMV.

**Comment by jmagomez** [comment]
Thanks, I will try to find tidyquant at tarball.

Best Regards.

Em qui., 30 de mar. de 2023 às 13:05, Eric Johnson ***@***.***>
escreveu:
