### ISSUE TITLE
Altair Visualizations Fail when Using JSON/CSV Data-Transformers

### ISSUE THREAD

**Issue by eikonomega** [googlecolab/colabtools#354]
Hi Friends,
So - Altair visualizations lead to notebook size bloat when interacting with anything but small datasets unless you activate their JSON/CSV data-transformers. 

* [In their documentation](https://colab.research.google.com/tun/m/m-191agqyave452/altair-data-05148a355c4ab93039b48d7e9fc03fb6.json?authuser=0) they indicate that this problem is best solved using a JSON/CSV transformer which stores data needed for the visualization outside of the notebook in temporary JSON/CSV files.

* It appears that in Colaboratory, we are able to write these temporary files, but the attempts by altair to retrieve them fail. 

Here is the code I'm attempted to run. Please note that when I do this without enabling the JSON transformer, all works as expected, but the size of the notebook becomes a major performance issue.

```
import altair as alt
import pandas as pd

# Enable the JSON data transformer
alt.data_transformers.enable('json')

# Data set from Kaggle: https://www.kaggle.com/harlfoxem/housesalesprediction
home_sales = pd.read_csv(
    'data-sets/king-county-home-sales.csv', parse_dates=['date'])
```

Now, when I actually try to generate a visualization this is all I get... 😢 
<img width="566" alt="image" src="https://user-images.githubusercontent.com/415939/48947986-0d2f2780-ef01-11e8-852a-b3dca5358ed5.png">

Additionally, I see the following errors in the JS console - which appear to be altair attempting to retrieve the JSON that it generated for the chart.
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/415939/48948138-76169f80-ef01-11e8-873a-1a4c20c338a9.png">

Finally, I'm able to confirm that the file does exist...
<img width="974" alt="image" src="https://user-images.githubusercontent.com/415939/48948187-a9592e80-ef01-11e8-8d6b-7336b7194d7b.png">

So... I'm wondering if altair is unable to retrieve the file because of a path issue or a permissions issue within the Colaboratory system.

Thanks in advance for your help!

**Comment by colaboratory-team** [comment]
I'd recommend following up with the altair maintainers at https://github.com/altair-viz/altair/issues

**Comment by forresthopkinsa** [comment]
The solution is [altair_data_server](https://colab.research.google.com/github/altair-viz/altair_data_server/blob/master/AltairDataServer.ipynb#scrollTo=z4hH7BTsjuDX)
