### ISSUE TITLE
Colab running on GCE VM with paid for GPU just stopped. 

### ISSUE THREAD

**Issue by andresmasegosa** [googlecolab/colabtools#3540]
Describe the current behavior
I started up GCE VM following these instructions: https://research.google.com/colaboratory/marketplace.html?utm_source=faq&utm_medium=link&utm_campaign=why_arent_resources_guaranteed

I then began running a colab notebook before going to bed. I woke up and found the job just stop. I did not get any error. The VM was active, I was able to connect but the training of the model just stopped during the night. It was running for almost 12 hours. 

Describe the expected behavior
As I'm paying for the VM, and I'd like to fully utilize it over a month, I would expect to be able to run a Colab notebook on my instance 24 hours a day with no interruptions. What am I paying for exactly, and how do I get full utilization of this rather expensive VM otherwise? Thanks.

What web browser you are using
Chrome

Additional context
I have a long-running notebook that is training a neural network.

**Comment by cperry-goog** [comment]
Do you have a way to introspect any error logs? We shouldn't be disconnecting you on your side, I wonder if it OOM'd or something.
