### ISSUE TITLE
portrait_generator_v001 download failed

### ISSUE THREAD

**Issue by Schweineschwarte** [googlecolab/colabtools#3545]
**Describe the current behavior**
In section "2. Diffusion and CLIP model settings" I set the option "diffusion_model" to "portrait_generator_v001". After, I click on the run button. Now, I get the following message:

`portrait_generator_v001 model download from https://huggingface.co/felipe3dartist/portrait_generator_v001/resolve/main/portrait_generator_v001_ema_0.9999_1MM.pt failed. Will try any fallback uri.`
`portrait_generator_v001 download failed.`
`secondary already downloaded. If the file is corrupt, enable check_model_SHA.`
`Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]`
`Loading model from: /usr/local/lib/python3.9/dist-packages/lpips/weights/v0.1/vgg.pth`

If I select the check box "check_model_SHA", I get the following message:
`portrait_generator_v001 model download from https://huggingface.co/felipe3dartist/portrait_generator_v001/resolve/main/portrait_generator_v001_ema_0.9999_1MM.pt failed. Will try any fallback uri.`
`portrait_generator_v001 download failed.`
`Checking secondary File`
`secondary SHA matches`
`Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]`
`Loading model from: /usr/local/lib/python3.9/dist-packages/lpips/weights/v0.1/vgg.pth`

If I run all run all other buttons with success and at the end the "Do the Run!" button, I get the following message:
`Starting Run: TimeToDisco(7) at frame 0`
`Prepping model...`

`---------------------------------------------------------------------------`

`FileNotFoundError                         Traceback (most recent call last)`

`<ipython-input-27-9183daaf5c88> in <cell line: 204>()`
`    205     model.load_state_dict(torch.load(custom_path, map_location='cpu'))`
`    206 else:`
`--> 207     model.load_state_dict(torch.load(f'{model_path}/{get_model_filename(diffusion_model)}', map_location='cpu'))`
`    208 model.requires_grad_(False).eval().to(device)`
`    209 for name, param in model.named_parameters():`

`2 frames`

`/usr/local/lib/python3.9/dist-packages/torch/serialization.py in __init__(self, name, mode)`
`    249 class _open_file(_opener):`
`    250     def __init__(self, name, mode):`
`--> 251         super(_open_file, self).__init__(open(name, mode))`
`    252 `
`    253     def __exit__(self, *args):`

`FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/AI/Disco_Diffusion/models/portrait_generator_v001_ema_0.9999_1MM.pt'`

**Describe the expected behavior**
I expected, the download of the diffusion model portrait_generator_v001 will successed.

**What web browser you are using**
Tested with Firefox and Opera

**Comment by EvanWiederspan** [comment]
This seems to be an issue with the notebook you're using, which is not owned by Colab. I would recommend reaching out to the notebook author instead
