### ISSUE TITLE
Copy paste with keyboard shortcut not working on mac

### ISSUE THREAD

**Issue by mattany** [googlecolab/colabtools#3546]
**Describe the current behavior**
Using the `cmd + c` shortcut doesn't work as expected. Instead of copying the text, it creates a link such as
https://colab.research.google.com/drive/XXXXXXXXXXX#scrollTo=XXXXXXXXXXX
However, when right clicking and then selecting "Copy", it works fine.
This issue is intermittent. Sometimes refreshing the page fixes it.

**Describe the expected behavior**
Expected the text to be copied to the clipboard.

**What web browser you are using**
Brave Browser [Version 1.49.120 Chromium: 111.0.5563.64 (Official Build) (arm64)](https://brave.com/latest/)
Using Mac M1 Pro

**Additional context**
[example](https://colab.research.google.com/drive/1QAPIvH82XAr4FTqRMd7adKUK68crgNz0#scrollTo=ztaSIe_XiBtE)

**Comment by EvanWiederspan** [comment]
Does this still happen for you when all browser extensions are disabled?

**Comment by mattany** [comment]
Will try when I get a chance and let you know
