### ISSUE TITLE
Disconnected and env deleted without any warning 1second before the "are you still here" is shown, 3h of work lost !!

### ISSUE THREAD

**Issue by jarredou** [googlecolab/colabtools#3548]
Explicit title. All my today work is gone. Can't reconnect to a GPU runtime, after only 3h of use ?! Without any warning before ?! AND THEN you ask me if "I'm still here" ?! To not loose the runtime YOU HAVE ALREADY DELETED ?! This is insane ! FY.

**Comment by EvanWiederspan** [comment]
We'll need more information to follow up on this bug report. Please submit feedback within Colab at Help > Send feedback.
