### ISSUE TITLE
Changes made by one editor no longer visible to others

### ISSUE THREAD

**Issue by Sam0ht** [googlecolab/colabtools#355]
We've been sharing Colaboratory notebooks for online coding interviews, paired with a Hangout.  Until yesterday, when I share a notebook with the candidate, when they edit the notebook then I immediately see their changes, and vice-versa.  

Yesterday and today however, the candidate has been able to open the notebook and edit it fine, but I see none of their changes on my screen.  In one interview I had the candidate share their screen over hangout, I could see that they were editing the notebook, but in my browser the notebook remained in its initial state.

Has something happened to or been changed that might have affected simultaneous editing by multiple users?  Using a regular google document still works fine in the same scenario, as expected.

**Comment by dni138** [comment]
I have been having the same issue, only for coding assignments. Thus, we are both trying to code on the document at the same time. Because of this we are getting odd save errors. Any progress to fix this yet?

**Comment by colaboratory-team** [comment]
This is unfortunate, but expected. The [realtime API is being shut down](https://developers.google.com/realtime/deprecation), and there's no replacement presently.

**Comment by Sam0ht** [comment]
Thank you for confirming this.  As you say, it's unfortunate, but I can understand why this feature is no longer available.

**Comment by rrmistry** [comment]
Hello @colaboratory-team,
Even if [realtime API is deprecated](https://developers.google.com/realtime/deprecation), is it possible to share an existing user's connected runtime if another user tries to connect to the same shared notebook (e.g. from Google Drive)?

Users can be given a warning to periodically refresh their browser when connecting to a shared runtime.

There are a lot of benefits that Colab provides for which I am grateful. It would just be really nice to collaborate in real time with colleagues with the same kernel memory state.

Especially for cases where we are collaborating on a large enough datasets (even a sub-set of our full dataset takes up several minutes to load to memory). Having a shared runtime memory state would be supremely helpful here.

My apologies if this merits creation of a separate GitHub issue.

**Comment by michaeldv-pg** [comment]
@colaboratory-team Any chance such feature can be implemented with ShareDB?

**Comment by monroews** [comment]
I use colab to teach engineering design and require team projects. Real time collaboration is what my students expect and what I would like to be able to offer them. Colab would be sooooo much better if collaboration were enabled using the same scheme Google uses for other docs.

**Comment by greydanus** [comment]
This would be amazingly helpful for my use case as well. It would be especially helpful for group coding in the time of COVID

**Comment by dinhanhx** [comment]
When we have back the real time thingy?

**Comment by zsxing99** [comment]
Looking forward to this feature coming back

**Comment by franchesoni** [comment]
+1

**Comment by AdinAck** [comment]
+1

**Comment by robertlacok** [comment]
Also was bummed by this :( building a [workaround](https://deepnote.com)

**Comment by etekweb** [comment]
Am also surprised to find this doesn't work. I thought that real-time editing was the whole point of Colab. Without real-time editing, it is hardly any better than using Jupyter notebooks in Python directly and using GitHub for shared code. In fact, it's worse: since Colab has no commit system or proper conflict management, I have to wait for my teammate to finish to do anything on the project. This really should either be fixed, or a proper commit-push-conflict resolution system needs to be implemented

**Comment by pascalelavoieINF2050** [comment]
Damm-it !! not really usefull then !
