### ISSUE TITLE
Randomly disconnected every X min for no reason

### ISSUE THREAD

**Issue by jarredou** [googlecolab/colabtools#3552]
Randomly disconnected after few minutes of not ressource angry work. The runtime say "busy" and nothing is interactive anymore. WHY ?
Why do you force user to use colab as an interactive tool and then block them to use it interactively ?!
This is insane !

**Comment by EvanWiederspan** [comment]
We'll need more information to follow up on this bug report. Please submit feedback within Colab at Help > Send feedback.
