### ISSUE TITLE
Vulkan installation

### ISSUE THREAD

**Issue by AnukritiSinghh** [googlecolab/colabtools#3556]
**Describe the current behavior**
The command `!sudo apt install -y vulkan-tools` is not working correctly anymore on colab, it is throwing error related to compatibility issue. It was working the night before but now the GPU drivers are not supporting vulkan, which is very shocking 
`Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
/build/vulkan-tools-KEbD_A/vulkan-tools-1.2.131.1+dfsg1/vulkaninfo/vulkaninfo.h:371: failed with ERROR_INCOMPATIBLE_DRIVER`

**Describe the expected behavior**
The vulkan tools should have been installed correctly

**What web browser you are using**
Chrome

**Comment by mayankmalik-colab** [comment]
!sudo apt install -y vulkan-tools is working fine on a new notebook. Can you share a sample of code that was working before and is not working anymore?

**Comment by AnukritiSinghh** [comment]
Sure, here are the two screenshots 

![image](https://user-images.githubusercontent.com/28527591/230441999-403f1fba-faed-4e80-a3f2-57aa39c12724.png)
![image](https://user-images.githubusercontent.com/28527591/230442186-e76e6830-e853-4c51-8940-ebaa54e75369.png)

**Comment by mayankmalik-colab** [comment]
Can you also install `apt-get install libnvidia-gl-525` and try. I just did and it is working now. Let me know if this works.

**Comment by AnukritiSinghh** [comment]
After installing this, it worked! Thank you so much.
