### ISSUE TITLE
numeric_column is deprecated

### ISSUE THREAD

**Issue by nealeckard** [googlecolab/colabtools#3557]
**Describe the current behavior**
This is a bug for the Feature Crosses Colab at:

https://colab.sandbox.google.com/github/google/eng-edu/blob/main/ml/cc/exercises/representation_with_a_feature_cross.ipynb

In the third executable code snippet, this warning appears:

WARNING:tensorflow:From <ipython-input-3-2283efb12c1a>:5: numeric_column (from tensorflow.python.feature_column.feature_column_v2) is deprecated and will be removed in a future version.
Instructions for updating:
Use Keras preprocessing layers instead, either directly or via the `tf.keras.utils.FeatureSpace` utility. Each of `tf.feature_column.*` has a functional equivalent in `tf.keras.layers` for feature preprocessing when training a Keras model.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

No warning.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome.

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mayankmalik-colab** [comment]
Yes, `tf.feature_column.numeric_column` `(tf.feature_columns.*)` is [deprecated in recent tf versions](https://www.tensorflow.org/api_docs/python/tf/feature_column/numeric_column) as mentioned in the warning. However, the notebook should still run just fine. You can refer [migrating_feature_columns](https://www.tensorflow.org/guide/migrate/migrating_feature_columns) for more info on making those changes.

**Comment by nealeckard** [comment]
You're correct, it works perfectly fine. I filed the bug just as a heads-up that the colab will need an update at some point.

Thanks for the links!
