### ISSUE TITLE
Redo and undo regarding 

### ISSUE THREAD

**Issue by abhiwavhal** [googlecolab/colabtools#3559]
**Describe the current behavior**
There is limitation of using redo and undo command 

**Describe the expected behavior**
We can Redo and undo as many times as we want 

**What web browser you are using**
Chrome

**Additional context**
As i was working on my project where i was writing a blog.
i made some mistakes while writing.
i used undo command.
but the i realized everything i wrote early was right. but at that time i am unable to redo it.

**Comment by EvanWiederspan** [comment]
Generally, if you undo and then edit, you won't be able to redo since those edits will have been lost. If you were working with a Google Drive notebook, you may be able to see your old state by going to File -> Revision History and recover your old content there
