### ISSUE TITLE
Editing MathJax Configuration/Enabling Nbextensions

### ISSUE THREAD

**Issue by pblitzen** [googlecolab/colabtools#3568]
Looking how to do something and possibly encountered a bug along the way. More interested in finding out how to do what I want

I have been trying to find a way to have definitions for latex/mathjax be used throughout an entire notebook. 

Here is a summary of what I posted on [stack](https://stackoverflow.com/questions/75923294/latex-definitions-in-google-colab):
The default is definitions only working within the context of a cell, even if \gdef is used. I have tried many ways around this, including nbextensions, but for the specific one I am using (enabled via ` jupyter nbextension enable load_tex_macros/main`) everything goes through but does not actually work even though I have double checked my definitions tex file is in the right place. The problem seems to stem from the fact that in jupyter notebook there is an actual interface to enable extensions (and doesn't have to be done through terminal). Also this method would require re-running lots of other lines for each session

Another possibility would be setting a custom MathJax configurations, adding macros as the documentation suggests. But after lots of searching, I was unable to find a way to do this. It appears that others have made tangential requests for this in the past, see #2822 ``

Essentially, mathjax gives the following for adding macros/definitions, and I would like to find the streamlined equivalent for colab

```
window.MathJax = {
  tex: {
    macros: {
      RR: "{\\bf R}",
      bold: ["{\\bf #1}", 1]
    },
    environments: {
      braced: ["\\left\\{", "\\right\\}"]
    }
  }
};

```

**Comment by blois** [comment]
Unfortunately for security reasons we cannot allow any customizations to MathJax running in the main frame of Colab.

A workaround may be to render the markdown in the output of a cell and use an approach such as:

https://github.com/googlecolab/colabtools/issues/322#issuecomment-633315072

(render as plain text then have your markdown configuration process the results, I believe)
