### ISSUE TITLE
No long able to write to google mounted drive

### ISSUE THREAD

**Issue by kechan** [googlecolab/colabtools#357]
I just went over 100 GB and colab started failed to save files to my google drive (via disk mount). I have increased it to 200 GB. I restarted my Colab session but it still is not saving. Saving into just /content/ seemed ok.

**Comment by kechan** [comment]
I am thinking if the disk needed to be unmounted and re-mount again. I am not sure what api to call in order to do that.

**Comment by kechan** [comment]
Things worked again on next re-mount. I think there must be a lag among diff pieces of the cloud.

**Comment by craigcitro** [comment]
For posterity, the `drive.mount()` call also has a `force_remount` arg, which forces a remount. (Picking any other mount point has the same effect.)
