### ISSUE TITLE
Add other dataframe libraries such as polars, duckdb

### ISSUE THREAD

**Issue by bingbong-sempai** [googlecolab/colabtools#3570]
**Is your feature request related to a problem? Please describe.**
Sometimes pandas can be slow / limiting when processing data.

**Describe the solution you'd like**
Inclusion of polars and/or duckdb + ibis to the default packages.

**Describe alternatives you've considered**
Polars benchmarks faster but duckdb is more mature.

**Additional context**
Both polars and duckdb are said to be significantly faster than pandas in common table operations.  
Ibis provides a pythonic API to duckdb (and also BigQuery)

**Comment by metrizable** [comment]
Tracked internally at b/278154476.

**Comment by EvanWiederspan** [comment]
Both packages are now installed by default
