### ISSUE TITLE
/usr/bin/timeout: failed to run command ‘nvidia-smi’: No such file or directory

### ISSUE THREAD

**Issue by Vierod** [googlecolab/colabtools#3581]
**Describe the current behavior**
Kernel restart out of the blue, extremely annoying.

**Describe the expected behavior**
Random kernel restarts keep happening because:
"/usr/bin/timeout: failed to run command ‘nvidia-smi’: No such file or directory"

The full error chain goes:
<html><body>

Apr 13, 2023, 6:53:42 PM | WARNING | /usr/bin/timeout: failed to run command ‘nvidia-smi’: No such file or directory
-- | -- | --
Apr 13, 2023, 6:53:25 PM | WARNING | /usr/bin/timeout: failed to run command ‘nvidia-smi’: No such file or directory
Apr 13, 2023, 6:53:09 PM | WARNING | : No such file or directory
Apr 13, 2023, 6:53:09 PM | WARNING | failed to run command ‘nvidia-smi’
Apr 13, 2023, 6:53:09 PM | WARNING | /usr/bin/timeout:

</body>
</html>

I'm not using a GPU instance or trying to run nvidia-smi.

**What web browser you are using**
Firefox

It's not notebook specific and it's a relatively new issue (last few weeks). I don't understand is something is hijacking the backend trying to use a GPU or if it's just a random bug either way it is extremely annoying.

**Comment by varunponda** [comment]
Hi @Vierod, I think The error message indicates that the nvidia-smi command, which is used to check the GPU usage and performance, is not found in your system. This error can occur if there is an issue with the GPU driver installation.
Try upgrading the nvidia GPU driver with this command:
`!pip install --upgrade nvidia-pyindex`

**Comment by mayankmalik-colab** [comment]
The warning doesn't seem like an issue for the kernel restart. Also, the `nvidia-smi`  command in the background is most probably used for other purposes and wouldn't work on a CPU runtime. Thus, we see that warning. However, this warning shouldn't restart your kernel.

Are you still having issues with the restart ? Is it possible to reproduce the issue?

**Comment by Yujin297** [comment]
I encountered the same problem and reproduced it several times, did you solve the problem?

**Comment by Yujin297** [comment]
Okay.

**Comment by kartikforcebolt** [comment]
i have solve the problem using 
!pip install --upgrade nvidia-pyindex
