### ISSUE TITLE
Random "disconnection error" alert but runtime is still running but inacessible

### ISSUE THREAD

**Issue by jarredou** [googlecolab/colabtools#3583]
Whatever I do, whatever notebook, whatever browser, Colab can't stop making these "fake" disconnection alerts. Fake because the runtime is still running, but it become not accessible, not interactive anymore, only "busy", for no reason. So unusable. And few times later, it will crashes, without any message. Because it is not interactive anymore, why ? because of your not fixed bugs.

If you ask users to use Colab interactively, don't block them to use it interactively, this is insane. This these bugs already reported since years.

**Comment by cperry-goog** [comment]
Submit feedback in product with consistent repo steps and I can take a look - I can't diagnose from GitHub.
