### ISSUE TITLE
Pandas pd.read_clipboard() not working in Colab, but code works fine in a Jupyter Notebook

### ISSUE THREAD

**Issue by flycast31** [googlecolab/colabtools#3589]
After importing pandas as pd and copying a some data from an Excel spreadsheet to my computer (running macOS Ventura 13.2.1. I keep trying to get a pandas DataFrame to load via the following code: data2 = pd.read_clipboard(). Colab returns an error each time. See attached screen shot.

![Screenshot 2023-04-19 at 6 25 50 PM](https://user-images.githubusercontent.com/36335027/233213113-8dd07a1c-0a83-497f-a4a1-ceefd79b05c4.png)
![Screenshot 2023-04-19 at 6 25 50 PM](https://user-images.githubusercontent.com/36335027/233213289-6fff41a3-5690-4fed-8ac8-8664e3e8d8ea.png)

**Comment by mayankmalik-colab** [comment]
Since the kernel is running on a virtual machine and is different from you local machine, it can't work just like that. There might be some workarounds but not recommended.

**Comment by flycast31** [comment]
Thank for your quick response. So are there directions for grabbing tabular data from websites to use in DataFrames in Pandas inside Colab?Michael GoodroeSent from my iPhoneOn Apr 20, 2023, at 2:11 AM, mayankmalik-colab ***@***.***> wrote:﻿
Since the kernel is running on a virtual machine and is different from you local machine, it can't work just like that. There might be some workarounds but not recommended.

**Comment by EvanWiederspan** [comment]
read_clipboard just reads whatever is in your clipboard, so you could also just paste it into read_csv in the notebook
