### ISSUE TITLE
Unable to Clone Private Repo

### ISSUE THREAD

**Issue by nprandall** [googlecolab/colabtools#359]
I am attempting to use the following command to clone my private repo:
**!git clone https://github.iu.edu/username/repo.git**

However, I am receiving this error message:
**fatal: could not read Username for 'https://github.iu.edu': No such device or address**

I am confused because I am able to use the above command to successfully clone the same repo when using Jupyter Notebooks on my local computer.

Anyone know what gives? I am looking for a method to clone the private repo to Colab:
a) without hardcopying my password in the link
b) that will allow anyone with access to the repo to execute the given github clone command without needing to install/alter/etc. anything else

**Comment by BhushanVasisht** [comment]
Hey! @nprandall, check out this link
https://techsupportallbugs.wordpress.com/2018/06/05/using-git-with-colab-via-ssh/

**Comment by ziatdinovmax** [comment]
This should work (perhaps not the most secure option, so make sure that the outputs are not saved when sharing a notebook). Just use your username/repo/email.

To clone a private repo
```
import os
from getpass import getpass
user = getpass('GitHub user')
password = getpass('GitHub password')
os.environ['GITHUB_AUTH'] = user + ':' + password
!git clone https://$GITHUB_AUTH@github.com/ziatdinovmax/Gnet-test.git
```

To create a new repo:
```
import os
from getpass import getpass
user = getpass('GitHub user')
password = getpass('GitHub password')
os.environ['GITHUB_AUTH'] = user + ':' + password
!git init
!git add .
!git config --global user.email "ziatdinovmax@gmail.com"
!git config --global user.name "ziatdinovmax"
!git commit -m "first commit"
# Go to GitHub and create a new repo there
!git remote add origin https://$GITHUB_AUTH@github.com/ziatdinovmax/liveSTEM.git
!git push -u origin master
```

**Comment by PhilJd** [comment]
Just stumbled upon this. For completeness: The above might store the password in logs. A better alternative is to use a token: `Settings -> Developer settings -> Personal access tokens -> Generate new token`.
Copy the token and clone the repo (replace username and token accordingly)
`!git clone https://username:token@github.com/username/repo_name.git`

**Comment by Elidor00** [comment]
An alternative, which also allows you to clone only one branch of a private repository could be:

`get_private_repo.py`

`import os
from getpass import getpass
import urllib.parse

user = input('User name: ')
password = getpass('Password: ')
password = urllib.parse.quote(password) # your password is converted into url format
repo_name = input('Repo name: ')
branch_name = input('Branch name: ')

if branch_name == "master":
	cmd_string = 'git clone https://{0}:{1}@github.com/{0}/{2}.git'.format(user, password, repo_name)
else:
	cmd_string = 'git clone -b {3} https://{0}:{1}@github.com/{0}/{2}.git'.format(user, password, repo_name, branch_name)

os.system(cmd_string)
cmd_string, password = "", "" # removing the password from the variable`


And use the command `!python get_private_repo.py`

**Comment by iantheconway** [comment]
I have a collab notebook which is part of a private repo authenticated using the steps here: 
https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb#scrollTo=Rmai0dD30XzL

I want to clone a different private repo from the same github user and install it in the private notebook. Is there a way to do that with the already authenticated notebook without adding tokens or passwords to the notebook's source?

**Comment by iantheconway** [comment]
I gather from the lack of response (except the one thumbs down emoji) that the answer is, "No, you must add either the plain text password or a new token to the already authenticated notebook".

**Comment by khizirsiddiqui** [comment]
You can look for some possible solutions here also: [Methods for using Git with Google Colab](https://stackoverflow.com/questions/48350226/methods-for-using-git-with-google-colab)

**Comment by cperry-goog** [comment]
Currently we have no mechanism to pass GitHub credentials through to the backend.
