### ISSUE TITLE
Change in TOS results in arbitrary banned string literals.

### ISSUE THREAD

**Issue by Draco18s** [googlecolab/colabtools#3593]
**Describe the current behavior**
The string `stable-diffusion-webui` anywhere in the notebook source warns about "executing code that is disallowed" even if this string is inside a comment.

**Describe the expected behavior**
`#stable-diffusion-webui` as a comment has no programmatic effect and should not interrupt execution

**What web browser you are using**
Chrome 112.0.5615.138

**Additional context**
This appears to be related to the following TOS change:
![image](https://user-images.githubusercontent.com/1750680/233696440-724e67f9-5df1-4d07-bee6-e155ecaf3a12.png)

But the implementation of this TOS change is handled in a way that makes no sense: rather than "banning web UIs" it appears to ban AUTOMATIC1111's stable-diffusion-webui ***specifically.***

![image](https://user-images.githubusercontent.com/1750680/233698020-046e39d2-5047-453a-aed2-a4e2298bfdf5.png)
![image](https://user-images.githubusercontent.com/1750680/233698135-d2286a54-ac74-4991-aa05-ce1ff6603f2e.png)

Run the following colab:
https://colab.research.google.com/drive/1odJdkdhlLgR1e2vBvSNmje9xLnxb-3CT?usp=sharing

**Comment by kieranxsomer** [comment]
Yea why are they not banning say INVOKE or "EASY DIFFUSION" why is it only ONE Web UI type?

**Comment by cperry-goog** [comment]
abuse detection is hard, I don't want to comment on any methods or possible changes in a public forum sorry.

**Comment by Draco18s** [comment]
> abuse detection is hard, I don't want to comment on any methods or possible changes in a public forum sorry.

That's perfectly acceptable.
