### ISSUE TITLE
Model Download for Fast-Dreambooth doesn't work

### ISSUE THREAD

**Issue by robaoba** [googlecolab/colabtools#3595]
When I try to download a model, it gets some error, maybe because of authentication issue with huggingface token. First time I tried to download privat model what requires some token. I made this token, put it where it says to be put - Fast-Dreambooth directory, but the error persists. Even when I want to download same model, but set it to public.

This is the text of thjs error.

> HTTPError                                 Traceback (most recent call last)
[<ipython-input-10-f102f2f8cec2>](https://localhost:8080/#) in <cell line: 114>()
    121     req=urllib.request.Request(textenc)
    122     req.add_header('Authorization', f'Basic {creds}')
--> 123     txtenc_size=urllib.request.urlopen(req).info().get('Content-Length', None)
    124   if int(txtenc_size)> 670000000 :
    125     if os.path.exists('/content/stable-diffusion-custom'):

5 frames
[/usr/lib/python3.9/urllib/request.py](https://localhost:8080/#) in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    212     else:
    213         opener = _opener
--> 214     return opener.open(url, data, timeout)
    215 
    216 def install_opener(opener):

[/usr/lib/python3.9/urllib/request.py](https://localhost:8080/#) in open(self, fullurl, data, timeout)
    521         for processor in self.process_response.get(protocol, []):
    522             meth = getattr(processor, meth_name)
--> 523             response = meth(req, response)
    524 
    525         return response

[/usr/lib/python3.9/urllib/request.py](https://localhost:8080/#) in http_response(self, request, response)
    630         # request was successfully received, understood, and accepted.
    631         if not (200 <= code < 300):
--> 632             response = self.parent.error(
    633                 'http', request, response, code, msg, hdrs)
    634 

[/usr/lib/python3.9/urllib/request.py](https://localhost:8080/#) in error(self, proto, *args)
    559         if http_err:
    560             args = (dict, 'default', 'http_error_default') + orig_args
--> 561             return self._call_chain(*args)
    562 
    563 # XXX probably also want an abstract factory that knows when it makes

[/usr/lib/python3.9/urllib/request.py](https://localhost:8080/#) in _call_chain(self, chain, kind, meth_name, *args)
    492         for handler in handlers:
    493             func = getattr(handler, meth_name)
--> 494             result = func(*args)
    495             if result is not None:
    496                 return result

[/usr/lib/python3.9/urllib/request.py](https://localhost:8080/#) in http_error_default(self, req, fp, code, msg, hdrs)
    639 class HTTPDefaultErrorHandler(BaseHandler):
    640     def http_error_default(self, req, fp, code, msg, hdrs):
--> 641         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    642 
    643 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 404: Not Found

>

**Comment by cperry-goog** [comment]
This looks like a HuggingFace issue or yeah maybe something with auth - I can take a look at a minimal reproducible notebook if you have one, but I don't think this is Colab-related.
