### ISSUE TITLE
EGL (offscreen rendering with OpenGL) stopped working

### ISSUE THREAD

**Issue by effepivi** [googlecolab/colabtools#3596]
**Describe the current behavior**
EGL was working a few weeks ago and it seems to have stopped now. It is used for offscreen rendering on a GPU with OpenGL.

**Describe the expected behavior**
When I create an EGL context, I get the error as follows: 	"Failed to retrieve EGL DRM device file."

**What web browser you are using**
Firefox

**Additional context**
https://colab.research.google.com/github/effepivi/gvxr-tutorials/blob/main/Installation-and-test.ipynb

**Comment by mayankmalik-colab** [comment]
Unfortunately we are not supporting OpenGL(EGL) for now. However, we may continue in future.
