### ISSUE TITLE
unable to open h5 file

### ISSUE THREAD

**Issue by aaryapatel007** [googlecolab/colabtools#36]
I have placed the dataset file on my drive folder but it is not able to open the files.Please help on where to place these files
``---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-43-43d8f568b8c7> in <module>()
----> 1 X_train_orig, Y_train_orig, X_test_orig, Y_test_orig, classes = load_dataset()
      2 
      3 # Normalize image vectors
      4 X_train = X_train_orig/255.
      5 X_test = X_test_orig/255.

<ipython-input-42-ac7d856f541a> in load_dataset()
      6 
      7 def load_dataset():
----> 8     train_dataset = h5py.File('train_signs.h5', "r")
      9     train_set_x_orig = np.array(train_dataset["train_set_x"][:]) # your train set features
     10     train_set_y_orig = np.array(train_dataset["train_set_y"][:]) # your train set labels

/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    267             with phil:
    268                 fapl = make_fapl(driver, libver, **kwds)
--> 269                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    270 
    271                 if swmr_support:

/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     97         if swmr and swmr_support:
     98             flags |= h5f.ACC_SWMR_READ
---> 99         fid = h5f.open(name, flags, fapl=fapl)
    100     elif mode == 'r+':
    101         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (unable to open file: name = 'train_signs.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)`

**Comment by JaveriaAkbar** [comment]
Have you changed current directory?

**Comment by aaryapatel007** [comment]
the directory is datalab.

**Comment by JaveriaAkbar** [comment]
If you are trying to access google drive files, check this.
https://stackoverflow.com/questions/47744131/colaboratory-i-can-access-to-my-google-drive-folder-and-file

**Comment by aaryapatel007** [comment]
https://colab.research.google.com/notebook#fileId=1srw_HFWQ2SMgmWIawucXfusGzrj1_U0q&scrollTo=c99EvWo1s9-x&forceEdit=true&offline=true&sandboxMode=true
After following the step in this link, do I need to change the directory?

**Comment by JaveriaAkbar** [comment]
Yes.
import os
os.chdir('drive')

**Comment by aaryapatel007** [comment]
Thank a lot!
It worked.
