### ISSUE TITLE
Run keeps crashing, says I've used all available RAM; I have 166.19 compute units and am using premium GPU

### ISSUE THREAD

**Issue by RobinGanesan** [googlecolab/colabtools#3601]
**Describe the current behavior**
Run keeps crashing.  I have I have 166.19 compute units and am using premium GPU 

**Describe the expected behavior**
I expected the run to complete

**What web browser you are using**
Chrome
**Additional context**
https://colab.research.google.com/gist/RobinGanesan/2a5a04e3564dacb2ba2eb4bd3c226360/alphafold2.ipynb

Error logs:
<html>
<body>

Timestamp | Level | Message
-- | -- | --
Apr 26, 2023, 2:08:16 PM | WARNING | WARNING:root:kernel 56cfa6db-fd98-4075-94eb-07142c6ccb29 restarted
Apr 26, 2023, 2:08:16 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Apr 26, 2023, 2:02:18 PM | WARNING | Unset property [compute/gce_metadata_read_timeout_sec].
Apr 26, 2023, 2:00:37 PM | INFO | Kernel started: 56cfa6db-fd98-4075-94eb-07142c6ccb29, name: python3
Apr 26, 2023, 1:54:50 PM | INFO | Use Control-C to stop this server and shut down all kernels (twice to skip confirmatio
![Capture](https://user-images.githubusercontent.com/108406782/234668595-cdde5722-09a6-44c0-869a-6507ff2e9470.JPG)
n).
Apr 26, 2023, 1:54:50 PM | INFO | http://172.28.0.12:9000/
Apr 26, 2023, 1:54:50 PM | INFO | Jupyter Notebook 6.4.8 is running at:

</body>
</html>

![Capture](https://user-images.githubusercontent.com/108406782/234668621-0cfbc7ba-dbaa-42da-8d1c-62f691be96c3.JPG)

**Comment by RobinGanesan** [comment]
![Capture2](https://user-images.githubusercontent.com/108406782/234672746-dc6e8e0d-3aca-48f7-9a9c-ee6546665905.JPG)

**Comment by RobinGanesan** [comment]
<html>
<body>


Timestamp | Level | Message
-- | -- | --
Apr 26, 2023, 2:43:42 PM | WARNING | WARNING:root:kernel c7dabcf8-88ab-4c0b-aae0-498d63dbe011 restarted
Apr 26, 2023, 2:43:42 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Apr 26, 2023, 2:37:34 PM | WARNING | Unset property [compute/gce_metadata_read_timeout_sec].
Apr 26, 2023, 2:33:00 PM | INFO | Kernel started: c7dabcf8-88ab-4c0b-aae0-498d63dbe011, name: python3
Apr 26, 2023, 2:30:01 PM | INFO | Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Apr 26, 2023, 2:30:01 PM | INFO | http://172.28.0.12:9000/
Apr 26, 2023, 2:30:01 PM | INFO | Jupyter Notebook 6.4.8 is running at:
Apr 26, 2023, 2:30:01 PM | INFO | Serving notebooks from local directory: /
Apr 26, 2023, 2:30:01 PM | INFO | Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Apr 26, 2023, 2:30:01 PM | INFO | http://172.28.0.2:9000/


</body>
</html>

**Comment by cperry-goog** [comment]
I think this is just using up all memory; if you're selecting premium GPU those are the biggest RAM machines we have.
