### ISSUE TITLE
Use Fallback Runtime not available1

### ISSUE THREAD

**Issue by Annabelism** [googlecolab/colabtools#3603]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by ragman-google** [comment]
Hi, the `Use Fallback Runtime` option is only available when connected to a runtime, and won't show in the command palette until then. Were you connected to a runtime?

**Comment by Annabelism** [comment]
> 
Yep that was it! Thanks so much!
