### ISSUE TITLE
Google Colab Throwing this error while connecting "This account has been blocked from accessing Colab runtimes due to suspected abusive activity."

### ISSUE THREAD

**Issue by Abhi5033** [googlecolab/colabtools#3605]
Yesterday Colab blocked access. Filed an appeal (feedback). Got access back today and again blocked. What's causing this? If any apps are prohibited, colab used to give warning while running cell in past and I stopped running the cell. But now without any warning It is blocking access. I used video trimmer app yesterday and today.

**Comment by Abhi5033** [comment]
Maybe the video trimmer app I'm using is triggering this. I'll stop using that. Please unblock my account.

**Comment by diogodh** [comment]
Same issue with me. Blocked, filed and appeal, no more news. And i am not entirely sure what i did wrong...

**Comment by cperry-goog** [comment]
You'll need to file feedback in product, I can't diagnose from GitHub unfortunately.
