### ISSUE TITLE
Model Maker Image Classification Tutorial

### ISSUE THREAD

**Issue by jlipe** [googlecolab/colabtools#3606]
**Describe the current behavior**
[This tutorial](https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/models/modify/model_maker/image_classification.ipynb) which is linked on [the tensorflow.org examples](https://www.tensorflow.org/lite/models/modify/model_maker/image_classification) doesn't work.

The step to run `pip install -q tflite-model-maker` runs out of disk space. I upgraded to Colab Pro to get more disk space but it still doesn't work. 

**Describe the expected behavior**
I expect this tutorial will be able to install tflite-model-maker without running out of disk space. If upgrading to Colab Pro+ is necessary to run this tutorial then it should say that. 

**What web browser you are using**
Chrome

**Comment by AcarFurkan** [comment]
![image](https://github.com/googlecolab/colabtools/assets/65075121/457698b2-7d02-4198-8885-fe3b75b99a52)
!sudo apt -y install libportaudio2
!pip install -q tflite-model-maker
l got exactly same error, l just run this two line and colab throws error after 10 min

**Comment by rijalmyd** [comment]
It was caused by the python version. You should use python 3.7 - 3.9. 

Check this out:
[https://discuss.tensorflow.org/t/tflite-model-maker-installation/16577/5](https://discuss.tensorflow.org/t/tflite-model-maker-installation/16577/5)

**Comment by khanhlvg** [comment]
TFLite Model Maker doesn't support Python 3.10 which is the version that Colab uses. I'd suggest you to use [MediaPipe Model Maker instead](https://developers.google.com/mediapipe/solutions/model_maker). It's the next generation of TFLite Model Maker that will offer the all capabilities as TFLite Model Maker and many new use cases. It already supports Python 3.10 and 3.11.

Here is the version of the tutorial you used above in MediaPipe Model Maker.
https://developers.google.com/mediapipe/solutions/vision/image_classifier/customize
