### ISSUE TITLE
The circle around the cell isn't centered, especially on big monitors.

### ISSUE THREAD

**Issue by Ryan3562** [googlecolab/colabtools#3609]
**Describe the current behavior**
The circle around the cell isn't centered.

![image](https://user-images.githubusercontent.com/43822686/235298032-d0e97281-b567-4205-aec0-2500ffad6f44.png)

**Describe the expected behavior**
The (loading) circle should be centered

**What web browser you are using**
Chrome

**Additional context**
Seems to happen more and more on bigger monitors.

**Comment by cperry-goog** [comment]
excellent find, thanks. tracked internally at b/280813530

**Comment by olaviinha** [comment]
It's caused by browser zoom not being at 100%.

**Comment by Ryan3562** [comment]
> It's caused by browser zoom not being at 100%. Looks like 90% zoom, that's when those little things seem most off.

It's not 90% zoom. That's 100% zoom

**Comment by olaviinha** [comment]
Oh, ok, peculiar! I've noticed the same, but found it's because my default zoom on Colab is 75-80% depending on device. At 100% it all gets centered on my Chromes on both Mac and Windows.

**Comment by blois** [comment]
This should now be fixed.
