### ISSUE TITLE
Installing Kivy

### ISSUE THREAD

**Issue by Fuskerbabs** [googlecolab/colabtools#361]
I couldn't install Kivy, as pip doesn't find some of the libraries needed to be installed.

command:   "!pip install -q pywin32"
error message: "Could not find a version that satisfies the requirement pywin32 (from versions: )
No matching distribution found for pywin32"

that goes for several libraries.

When running the commands locally on my machine then they work fine.

Any suggestions?

**Comment by Fuskerbabs** [comment]
command: "!pip install -v pywin32"
error message: "Created temporary directory: /tmp/pip-ephem-wheel-cache-xmdrtodn
Created temporary directory: /tmp/pip-req-tracker-gt3m65ti
Created requirements tracker '/tmp/pip-req-tracker-gt3m65ti'
Created temporary directory: /tmp/pip-install-xjkiwti9
Collecting pywin32
  1 location(s) to search for versions of pywin32:
  * https://pypi.org/simple/pywin32/
  Getting page https://pypi.org/simple/pywin32/
  Looking up "https://pypi.org/simple/pywin32/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/pywin32/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/pywin32/
    Skipping link https://files.pythonhosted.org/packages/36/98/581719389bef3491e982b0550ab539c25e8b2d1e9fd0695f4a05c696f061/pywin32-222-cp27-cp27m-win32.whl#sha256=7181f6aa0730caf888be592cf612cddb8987409fa4acf7393913c558da9b28d5 (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/96/4b/b52fb6f3b1648a52a3dfc422dace461a237d23ac55dfc0375b6263e86bd9/pywin32-222-cp27-cp27m-win_amd64.whl#sha256=d8a9ac7806e86b6c28be957407b50ca02144c7c0639fb125f8bd98e968ed642f (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/ed/7b/2b4ed81d83cb98721a7d1bd01a1899351a99260fe97cc51d5118ac9998f7/pywin32-222-cp35-cp35m-win32.whl#sha256=9d7e73262ca8bb8b34e7e17a29d3693e1b4b701389847bc70463adbb58b8245b (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/20/6d/ba9413b676959e49ffa990abb0f3dc4db57d2d23271859f3f76e59796e3e/pywin32-222-cp35-cp35m-win_amd64.whl#sha256=33971ade23c830f7660ad25ebf7c7625f8cd7efb635c880238bd2c5c23ee6ae8 (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/23/e3/e65b4d14c89f68bb85c24d733bcdb0b684af34970bdbb1b0892985965ce9/pywin32-222-cp36-cp36m-win32.whl#sha256=bace4824aa0242d1f3d9fd98f2116e0e1e9c8e0705ca135e5ce72960210b0c01 (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/be/25/0e0c568456b77ce144dd2b8799f915b046ffa1cd922771d214e4be05bca2/pywin32-222-cp36-cp36m-win_amd64.whl#sha256=4e27d2c9a97b0e8d538155b8804929780df9a6b3ebc31e845d16b7efa2142161 (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/91/67/59bb7d0d7623b879ce871ff82fb05da9efa63e907e1ba2e253c4cea6dcfc/pywin32-222-cp37-cp37m-win32.whl#sha256=356de1e08453e668cfe8fa892b17b46600b94373373c6b2b743730fc1d965a1c (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/a0/76/89b836562a36929bb913f9c17fca54fdd2c68b5e97ec0d626a389c087150/pywin32-223-cp27-cp27m-win32.whl#sha256=42f48567e36b787901ff3da20de5a134cd9880cc90832e2aad60951f058699f0 (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/65/83/0b14690d70bcd193a67c8b0a640129717e37a11d8e6a3e28a01e47910737/pywin32-223-cp27-cp27m-win_amd64.whl#sha256=f0f0e7c82ee334dd6e888b9b5beb05fd8947355fa7a15644c810bb4ea0079ca6 (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/32/0f/16419ffd63c60b0c197614c430eab35360a94154ac1b846b3ee69f8c8061/pywin32-223-cp35-cp35m-win32.whl#sha256=c7ea0deabcc324e5b74084b5452003109c592d1aedbe9e9289ed55b26d9b0c7f (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/73/48/42e18ab94651c28d21f626ce1b5feaf60e5fb2aae3d264138aa768532a5f/pywin32-223-cp35-cp35m-win_amd64.whl#sha256=da422d4067d98b49fbb19d851900a5fc38c61eab0ee803574c27c42309173ebe (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/d4/2d/b927e61c4a2b0aaaab72c8cb97cf748c319c399d804293164b0c43380d5f/pywin32-223-cp36-cp36m-win32.whl#sha256=fb3c85907918fd01a72ee146d323d220771dee151c0cfa5630c2f35797ffb116 (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/9f/9d/f4b2170e8ff5d825cd4398856fee88f6c70c60bce0aa8411ed17c1e1b21f/pywin32-223-cp36-cp36m-win_amd64.whl#sha256=0df9b008caef10af0d674c483316c28dcf78391332d9d5d380fab667ebf2d7d1 (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/d6/39/5c318e0b61d892861fe65a6a3150d42be4d87ae9137be2ef3e35632341c2/pywin32-223-cp37-cp37m-win32.whl#sha256=9eff897796c9d76a213134257a01b6f8a122c55e0772847fba313a8091f3ec44 (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/f4/fb/ba9e519d90b63090005bcdee900d318d895d475c627dc1bc0f77b27abad0/pywin32-223-cp37-cp37m-win_amd64.whl#sha256=249391eb924b8376826e6f84d143d1dcc0e400b238b511d5fbd3811f6ed9ad50 (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/fc/7c/25f36684ec3b8ea47d5601442950a4fa770d066f57171fbf8c905ccbfd25/pywin32-224-cp27-cp27m-win32.whl#sha256=6852ceac5fdd7a146b570655c37d9eacd520ed1eaeec051ff41c6fc94243d8bf (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/83/cc/2e39fa39b804f7b6e768a37657d75eb14cd917d1f43f376dad9f7c366ccf/pywin32-224-cp27-cp27m-win_amd64.whl#sha256=6dbc4219fe45ece6a0cc6baafe0105604fdee551b5e876dc475d3955b77190ec (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/64/5a/342e5c4552ec4c6f505c363c485f26e3828e633c55ba4888134e4d561a31/pywin32-224-cp35-cp35m-win32.whl#sha256=9bd07746ce7f2198021a9fa187fa80df7b221ec5e4c234ab6f00ea355a3baf99 (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/83/a5/960c5a714b3c975102031286121db06fe861fdd221b493dce5144d759b90/pywin32-224-cp35-cp35m-win_amd64.whl#sha256=5f265d72588806e134c8e1ede8561739071626ea4cc25c12d526aa7b82416ae5 (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/41/02/3d5014e3b70c950492ceb65785ef724d073785f02fd51401430fd5fef681/pywin32-224-cp36-cp36m-win32.whl#sha256=32b37abafbfeddb0fe718008d6aada5a71efa2874f068bee1f9e703983dcc49a (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/b2/1a/7727b406391b0178b6ccb7e447e963df5ebf1ce9e0f615fc6ce23b6f6753/pywin32-224-cp36-cp36m-win_amd64.whl#sha256=35451edb44162d2f603b5b18bd427bc88fcbc74849eaa7a7e7cfe0f507e5c0c8 (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/8a/37/917c4020e93e0e854d4cbff1cbdf14ec45a6d1cedf52f8cafdea5b22451a/pywin32-224-cp37-cp37m-win32.whl#sha256=22e218832a54ed206452c8f3ca9eff07ef327f8e597569a4c2828be5eaa09a77 (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/a3/8a/eada1e7990202cd27e58eca2a278c344fef190759bbdc8f8f0eb6abeca9c/pywin32-224-cp37-cp37m-win_amd64.whl#sha256=4eda2e1e50faa706ff8226195b84fbcbd542b08c842a9b15e303589f85bfb41c (from https://pypi.org/simple/pywin32/); it is not compatible with this Python
  Could not find a version that satisfies the requirement pywin32 (from versions: )
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-gt3m65ti'
No matching distribution found for pywin32
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 318, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 218, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 164, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/index.py", line 621, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for pywin32"

**Comment by Fuskerbabs** [comment]
It says that it is not compatible with this version of Python, but are running Python 3.

**Comment by craigcitro** [comment]
Colab VMs run Linux; I don't believe it's possible to install pywin32 on Linux.
