### ISSUE TITLE
New Python Version breaks notebook

### ISSUE THREAD

**Issue by adamgeddon1686** [googlecolab/colabtools#3610]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

After the update to python 3.10 one of the dependencies of my notebook can no longer be installed (onnxruntime-gpu 1.8). This is not compatible with python 3.10 and the rest of the dependencies aren't compatible with newer version of onnx. I tried using the fallback runtime but it appears that it doesn't have cuda libraries installed. On the fallback runtime nvcc--version says that nvcc is not defined.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

For onnxruntime-gpu 1.8 to install on the notebook like it did a few days ago. 

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

Both Chrome and Edge

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

I would be open to any solution that will get this running again. I have tried for 2 days now and haven't made any progress. I reached out to the notebook author as well as the support team for onnx and haven't gotten a response.

**Comment by metrizable** [comment]
@adamgeddon1686 Thanks for filing the issue. Would you be able to share a minimal reproducible notebook?
