### ISSUE TITLE
unable to select standard option after choose A100 

### ISSUE THREAD

**Issue by Tianjie-Wu** [googlecolab/colabtools#3611]
I think I have discovered a interest small bug in colab interface when choose runtime type.

**Describe the current behavior**

If you select GPU at this point in time (2023/04/30), you will be automatically assigned "A100" with high-ram (A100 does not have a standard option , so it will always be high-ram).
However, if you select other options, such as "None" or "TPU", you will only be able to select high-ram. as showed below:

![screen](https://vip2.loli.io/2023/04/30/sVw6Tf8KlSBYiD4.png)

**Describe the expected behavior**

It should be able to choose "standard" option. 

**What web browser you are using**
test on Chrome

**Comment by ragman-google** [comment]
Hi, @Tianjie-Wu thank you!

Tracking internally as b/280306742.

**Comment by ragman-google** [comment]
This has been fixed since May 3rd, just forgot to close the issue.
