### ISSUE TITLE
Request for Docker install Colab

### ISSUE THREAD

**Issue by tmp321hy** [googlecolab/colabtools#3614]
**I AM TRY this gist** 
https://gist.github.com/mwufi/6718b30761cd109f9aff04c5144eb885#file-install_docker_in_colab-sh-L3

**I GOT ERROR**
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Please guide me **how to docker install colab** without error

Please quickly solve this error  **Cannot connect to the Docker daemon at unix:///var/run/docker.sock.**

**Comment by cperry-goog** [comment]
Dupe with #3618 

Would be curious why you want to do this (comment on the other bug plz)
