### ISSUE TITLE
How To Install Docker Colab ?? Please guide me anyone...

### ISSUE THREAD

**Issue by tmp321hy** [googlecolab/colabtools#3618]
I AM TRY this gist but not working 
https://gist.github.com/mwufi/6718b30761cd109f9aff04c5144eb885#file-install_docker_in_colab-sh-L3

I GOT ERROR
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Please guide me how to docker install colab without error

Please quickly solve this error Cannot connect to the Docker daemon at unix:///var/run/docker.sock.

**Comment by cperry-goog** [comment]
[This answer](https://github.com/googlecolab/colabtools/issues/299#issuecomment-615308778) still applies; no plans to support.

Out of curiosity, why do you want to install Docker in Colab?
