### ISSUE TITLE
No module named 'gradio'

### ISSUE THREAD

**Issue by GothicOctopus** [googlecolab/colabtools#3620]
Everything seems to be loading fine and as normal until the very end. 
When I go to load the webui, it shows no link, only these lines

I'm using firefox with adblocks on a macbook pro.

/content/stable-diffusion
Traceback (most recent call last):
  File "scripts/webui.py", line 3, in <module>
    from frontend.frontend import draw_gradio_ui
  File "/content/stable-diffusion/frontend/frontend.py", line 1, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

Any ideas?

**Comment by cperry-goog** [comment]
Probably because gradio isn't installed on your runtime? Try `!pip install gradio`
