### ISSUE TITLE
Ipywidgets interact in Google Colab creates new plots instead of updating existing ones.

### ISSUE THREAD

**Issue by denbonte** [googlecolab/colabtools#3623]
**Describe the current behavior**

When using the Ipywidgets interact function in Google Colab, the intended behavior is to update existing plots. However, for a week or so, multiple users have reported that the function creates new plots instead of updating the existing ones (e.g., when using a slider to scroll through 3D data - i.e., given an NxMxP volume, we use widgets to interactively move through P different NxM 2D images).

Here's a screenshot at the starting point, after running the code in the cell:
![image](https://user-images.githubusercontent.com/31729248/235611040-33c83768-6156-4eea-b792-f6b08c8fd3e6.png)

Here's a screenshot after interacting with the slider/widget:
![image](https://user-images.githubusercontent.com/31729248/235611126-21d034d0-6401-447f-9144-70eae9c9194d.png)

**Describe the expected behavior**
When using the Ipywidgets interact function in Google Colab, the intended behavior is to update existing plots.

**What web browser you are using**
I've tested this on both Chrome and Safari.

**Additional context**

Google Colab is running `ipywidget==7.7.1`.

I'm using very simple custom widgets/functions that you can find here:
https://github.com/AIM-Harvard/pyplastimatch/blob/main/pyplastimatch/utils/viz.py

We have several self-contained notebooks to demo this behavior. For instance:

https://github.com/ImagingDataCommons/IDC-Tutorials/blob/master/notebooks/IDC_segmentation_primer.ipynb

(I suggest you look for cells with `viz_utils.AxialSliceSegmaskComparison` and other functions from `viz_utils`).

---

You can find a report from another user here:
https://stackoverflow.com/questions/76079118/ipywidgets-interact-function-in-google-colab-creates-new-plots-instead-of-updati

For transparency, [I first created this issue at jupyter-ipywidgets](https://github.com/jupyter-widgets/ipywidgets/issues/3766) and I've been redirected here!

**Comment by AgainstEntropy** [comment]
Maybe adding something like a `plt.show()` or `fig.show()` can be a squick olution

**Comment by metrizable** [comment]
@denbonte Thanks for filing the issue. I see some of the artifacts provided for reproducing the issue are not present, and it's been some time since the issue was filed. Is the behavior still occurring? If so, please feel free to re-open with a minimal reproducible notebook.
