### ISSUE TITLE
On installing python3.6/python3.7 using runtime GPU and clearing runtime After installing dependencies google Colab Pro session crash , 'session crashed for an unknown reason'

### ISSUE THREAD

**Issue by mujtabaAli96** [googlecolab/colabtools#3627]
**Describe the current behavior**
On installing python3.6/python3.7 using runtime GPU and clearing runtime After installing dependencies google Colab Pro session crashed, 'session crashed for an unknown reason

**Describe the expected behavior**
It shouldn't crash
**What web browser you are using**
Chrome

**Additional context**
On installing python3.6/python3.7 using runtime GPU and clearing runtime After installing dependencies google Colab Pro session crash, 'session crashed for an unknown reason, I am installing tensorflow-gpu==1.14.0 for training if I don't clear runtime it runs on CPU but it has to run on GPU

**Comment by mujtabaAli96** [comment]
![image](https://user-images.githubusercontent.com/48852703/236168260-7a4a568d-5ae3-4cce-bf88-6e211d7d564b.png)

**Comment by cperry-goog** [comment]
We don't support installing old versions of Python
