### ISSUE TITLE
Google Drive costantly disconnecting from Notebook while running Stable Diffusion 

### ISSUE THREAD

**Issue by 1111dontworryaboutit** [googlecolab/colabtools#3628]
Hello everyone, 

Browser: Google Chrome
Issue with multiple Google profiles

Yesterday, as I was using Stable Diffusion through the Colab notebook, it suddenly started to disconnect the Drive profile itself , while popping up a small bubble in the bottom left that says: An error with Google Drive occured. Then all procceses are terminated and then I find out that the drive has sort of "unmounted" itself from the notebook.

This has never happened until yesterday, and since then it constantly happens no matter which Google profile I am using.

Most of the times it doesn't even give me a code regarding the error, it just keeps disconnecting and disconnecting the drive from the notebook, sometimes before I even manage to run the cell that starts Stable Diffusion, sometimes while I am generating an image, and sometimes after.

I have tried deleting the sd folder and all files connecting it to my drive - runs for about 5 minutes and suddenly gives me an error and the Drive is disconnected. Has any one of you encountered this problem?

**Comment by RBenardi** [comment]
mine is disconnected while running the web ui

**Comment by RBenardi** [comment]
Same here, but in my case it's like after some mins it's being run, the runtime suddenly got disconnected

**Comment by IvanOrtegea** [comment]
The same thing happens to me shortly after it is running, it stops when removing the assigned GPU without the time allowed running out, and it does not give any type of error message

**Comment by RBenardi** [comment]
yea it doesn't give any type of error message, it makes me visit report bug xD

**Comment by 1111dontworryaboutit** [comment]
![image](https://user-images.githubusercontent.com/131618735/236180141-70811e59-a0b5-4a10-bf6c-12d3d0ba4dba.png)
The cell just becomes red and says that the proccess has ended and that's that...

![image](https://user-images.githubusercontent.com/131618735/236180288-67d484ed-35d0-43d9-a872-1deff2d7ad22.png)

That's while generating an image

**Comment by RBenardi** [comment]
got the same problem here

**Comment by IvanOrtegea** [comment]
yep, the same thing happens to me

**Comment by 1111dontworryaboutit** [comment]
https://github.com/TheLastBen/fast-stable-diffusion/issues/2103

**Comment by 1111dontworryaboutit** [comment]
I will close this issue here now, as obviously the issue is the free usage as the paid users don't face this problem while all of the people using it for free encounter the exact same issue.

**Comment by RBenardi** [comment]
oh so it's bcs of the free users xD ?

**Comment by 1111dontworryaboutit** [comment]
I guess so. If you want to keep using it you have to pay the 11eur / 10usd for approximately 50 hours of usage

**Comment by RBenardi** [comment]
> I guess so. If you want to keep using it you have to pay the 11eur / 10usd for approximately 50 hours of usage

damn that's a lot



> Did they warn somewhere that free users couldn't use it?

i don't know maybe i am the one who don't find it or maybe they don't (?)

**Comment by 1111dontworryaboutit** [comment]
Well I mean they don't have to...  https://github.com/TheLastBen/fast-stable-diffusion/issues/2103#issuecomment-1533699978  this answers everything

**Comment by RBenardi** [comment]
> Well I mean they don't have to... [TheLastBen/fast-stable-diffusion#2103 (comment)](https://github.com/TheLastBen/fast-stable-diffusion/issues/2103#issuecomment-1533699978) this answers everything

ya bruh also the price is kinda much for me sadly xD

**Comment by 1111dontworryaboutit** [comment]
I understand

**Comment by Kuruzavr** [comment]
> I guess so. If you want to keep using it you have to pay the 11eur / 10usd for approximately 50 hours of usage

Well, it's obvious that in terms of paid subscriptions, it makes a lot more sense to use Paperspace or RunPod than Google Colab. It looks like Google is just going to lose a huge number of customers.

**Comment by IvanOrtegea** [comment]
look at this tweet

https://twitter.com/thechrisperry/status/1649189902079381505

**Comment by AlizerUncaged** [comment]
I've moved to Kaggle, 24 hours free weekly usage there.

**Comment by JonFillip** [comment]
> I will close this issue here now, as obviously the issue is the free usage as the paid users don't face this problem while all of the people using it for free encounter the exact same issue.

It isn't though. I'm experiencing this issue using Colab Pro+, and I have over 700 compute units
![Screenshot 2023-06-23 at 4 10 57 AM](https://github.com/googlecolab/colabtools/assets/51130416/b2559639-2c5a-41c2-8dfc-b65f1c375138)

**Comment by ajunkdha** [comment]
Yes, I did a bot check and every time my exe test program finished, it restarted repeatedly. Is the colab model no longer for testing now? only for payers? I'm poor so I hope I can study well for my future lol. but yes, it's been collabed

**Comment by TMJgodofgame** [comment]
I think the solution may be with Python selenium if we program so that every x seconds, for example 10 seconds, the name of the colab window changes. I think we could trick colab and make it believe that there is activity. I have to try
