### ISSUE TITLE
Frequent disconnects while busy running in Google Colab

### ISSUE THREAD

**Issue by Leoros123** [googlecolab/colabtools#3629]
**Describe the current behavior**
After running the script (https://github.com/TheLastBen/fast-stable-diffusion) Google colab loses connection after 10 - 15 minutes of running.
It also writes the following in the browser console:
external.js:105 
 GET https://colab.research.google.com/tun/m/gpu-t4-s-22mrskdzdtvmi/socket.io/?authuser=0&EIO=3&transport=polling&t=OVce25E&sid=TbBBoQzYNqEabEfHAAAA 404
external_polymer_binary_l10n__ru.js:7224 debugger socket disconnecting due to socket.io error:  
AP {message: 'SocketIO error: /debugger: xhr poll error: 404 - TransportError', stack: 'CustomError: SocketIO error: /debugger: xhr poll e…4ed104172e515b0a00a4bbc3b92d5/external.js:86:510)'}
external_polymer_binary_l10n__ru.js:7227 lsp socket disconnecting due to socket.io error:  
AP {message: 'SocketIO error: /python-lsp/0/use_proxy: xhr poll error: 404 - TransportError', stack: 'CustomError: SocketIO error: /python-lsp/0/use_pro…4ed104172e515b0a00a4bbc3b92d5/external.js:86:510)'}
external_polymer_binary_l10n__ru.js:7227 lsp socket disconnecting due to socket.io error:  
AP {message: 'SocketIO error: /python-lsp/1/use_proxy: xhr poll error: 404 - TransportError', stack: 'CustomError: SocketIO error: /python-lsp/1/use_pro…4ed104172e515b0a00a4bbc3b92d5/external.js:86:510)'}
external_polymer_binary_l10n__ru.js:7227 lsp socket disconnecting due to socket.io error:  
AP {message: 'SocketIO error: /python-lsp/2/use_proxy: xhr poll error: 404 - TransportError', stack: 'CustomError: SocketIO error: /python-lsp/2/use_pro…4ed104172e515b0a00a4bbc3b92d5/external.js:86:510)'}
external_polymer_binary_l10n__ru.js:7227 lsp socket disconnecting due to socket.io error:  
AP {message: 'SocketIO error: /python-lsp/3/use_proxy: xhr poll error: 404 - TransportError', stack: 'CustomError: SocketIO error: /python-lsp/3/use_pro…4ed104172e515b0a00a4bbc3b92d5/external.js:86:510)'}
external_polymer_binary_l10n__ru.js:7227 lsp socket disconnecting due to socket.io error:  
AP {message: 'SocketIO error: /python-lsp/4/use_proxy: xhr poll error: 404 - TransportError', stack: 'CustomError: SocketIO error: /python-lsp/4/use_pro…4ed104172e515b0a00a4bbc3b92d5/external.js:86:510)'}

Tried the following to solve the problem:
Browser change
Change google account
Deleting the sd folder on the drive and reinstalling

**Describe the expected behavior**
Continuous work of the script for 2 - 3 hours

**What web browser you are using**
(Chrome, Brave)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
Test case notebook: https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by cperry-goog** [comment]
You must not be seeing our notices; we are restricting stable-diffusion-webui usage on free tier.

**Comment by fox1330** [comment]
why???
