### ISSUE TITLE
THE EXECUTION ENVIRONMENT GOES OFFLINE VERY SOON, DOESN'T GO LONG WITHOUT USE, WHILE WAITING FOR IT TO EXECUTE THE CELL COMPLETELY AND CORRECTLY

### ISSUE THREAD

**Issue by DjTecmo** [googlecolab/colabtools#3632]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by xhirene** [comment]
i have same problem like this

**Comment by DjTecmo** [comment]
i saw that this start to happen very recently to that many people, witth According to the [official statement](https://twitter.com/thechrisperry/status/1649189902079381505), the Colab Free of charge tier is not available for the Stable Diffusion WebUI 😭 We can only use it with [any paid plan](https://twitter.com/thechrisperry/status/1649193506957828096) Also
