### ISSUE TITLE
Google Colab has been permanently disconnected

### ISSUE THREAD

**Issue by Fatiga2023** [googlecolab/colabtools#3633]
I don't speak English, please someone explain why Google Colab has been permanently disconnected for a few days. I don't speak English, please someone explain why Google Colab has been permanently disconnected for a few days. When the Start Stable Diffusion selda is running, a pop-up message appears saying that an error occurred in Google Drive, sometimes it opens Stable Diffusion but disconnects after a few moments

**Comment by cperry-goog** [comment]
We are deleting free tier runtimes that access stable-diffusion-webui. We prioritize interactive notebook compute for free of charge tier users. We can't support web frontends that use Colab as a convenient free GPU. Users on our free of charge tier are encouraged to use Colab for interactive programming usage.

Paid users are not subject to any restrictions on web frontends, as they pay for the compute they consume.
