### ISSUE TITLE
Unable to use AV1_NVENC in Google Colab

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [googlecolab/colabtools#3634]
**Describe the current behavior**
```bash
!ffmpeg -y -strict experimental -hwaccel cuda  -i "/content/drive/myvid.mp4" -c:v av1_nvenc -async 1 -multipass 2 -tier 1 -level 24 -rc 1 -tune 2 -preset p4 -b_ref_mode 2 -spatial_aq 1 -pix_fmt yuv444p -b:v 4500k -g 15 -vf "colorspace=bt2020:iall=bt2020:trc=bt2020-12:range=pc" -c:a copy "/content/drive/MyDrive/myvidhdr.mp4" 
```

It returns this:

```verbose
[av1_nvenc @ 0x55b657630200] Provided device doesn't support required NVENC features
```

**Describe the expected behavior**
FFmpeg produces the video using AV1_NVENC

**What web browser you are using**
Chrome

**Additional context**
I have installed the latest version build of FFmpeg
I cannot install the latest version of NVIDIA drivers due to being unable to unload its models

**Comment by cperry-goog** [comment]
Can you confirm you're connected to a GPU runtime?

**Comment by MohammedMehdiTBER** [comment]
Yes, I confirm. However, seems like the NVIDIA driver version isn't
sufficient.

**Comment by metrizable** [comment]
I can confirm this is correct. FWICT, the T4, V100, and A100s that Colab makes available, for encoding, [do not support AV1](https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new). Of note, it appears the "Ada Lovelace" family does support AV1, which is provided by Google Cloud's [L4 models](https://cloud.google.com/compute/docs/gpus#nvidia_gpus_for_compute_workloads).
