### ISSUE TITLE
Random "A Google Drive error has occurred." errors, Colab unusable, once again.

### ISSUE THREAD

**Issue by jarredou** [googlecolab/colabtools#3640]
I still can't use any runtime with GPU because of the shitty bug reported earlier today.
I can't even use runtime without GPU because of this shitty error: "A Google Drive error has occurred."
No more info. Just this dumb message. Nothing in the runtime logs.
One more proof that your devs are shitdumb ?

**Comment by cperry-goog** [comment]
Duping with #3785
