### ISSUE TITLE
my google colab disconnects by itself for no apparent reason.

### ISSUE THREAD

**Issue by fox1330** [googlecolab/colabtools#3641]
**ERROR**
I currently use google colab along with Stable-diffusion but every time when I turn on WebUi, it can't stay working for 2 minutes, and it disconnects by itself, so I have to download the entire repository again to use it again for 2 minutes (or less).

before this did not happen, I could stay connected as long as I wanted, I don't know if the problem must be due to the use of the GPU or something else, but the Ram Memory is always good, and there is no apparent error, I always ran it the same way, but this problem started the day before yesterday, I think there may be an update on colab.

**browser**

Chrome

**Comment by Daaihere** [comment]
Same here Bruh !  You found any solutions ?

**Comment by pupitv** [comment]
Same issue

**Comment by fox1330** [comment]
apparently they limited the use of stable diffusion on google colab

**Comment by cperry-goog** [comment]
We delete free tier runtimes accessing stable-diffusion-webui. We prioritize interactive notebook compute for free of charge tier users. We can't support web frontends that use Colab as a convenient free GPU. Users on our free of charge tier are encouraged to use Colab for interactive programming usage.

Paid users are not subject to any restrictions on web frontends, as they pay for the compute they consume.
