### ISSUE TITLE
TPUs are depreciated and wont work for Otis' 4bit Kobold Colab. Please fix.

### ISSUE THREAD

**Issue by brunsonator3** [googlecolab/colabtools#3642]
**Describe the current behavior**
TPUs are depreciated and wont work for Otis' 4bit Kobold Colab.

https://colab.research.google.com/github/OtisAlejandro/LLMColabs/blob/main/Otis%27_4Bit_Kobold_Notebook.ipynb#scrollTo=MQvp5Ao1FL01

**Describe the expected behavior**
That the TPUs would work.

**What web browser you are using**
Chrome.

**Additional context**
Link to a public notebook:
https://colab.research.google.com/github/OtisAlejandro/LLMColabs/blob/main/Otis%27_4Bit_Kobold_Notebook.ipynb#scrollTo=MQvp5Ao1FL01

**Comment by cperry-goog** [comment]
How do they not work?
