### ISSUE TITLE
Colab Connection Errors out, no apparent cause.

### ISSUE THREAD

**Issue by Aberisque1278** [googlecolab/colabtools#3645]
Previously I was able to run webui no problems, for as long as I could conceivably need to. Now however, I'm regularly getting disconnected after only several minutes, the interface drops, and have to re-run the entire execution. Making the entire effort of using the webui kind of pointless.
As I understand it Google is limiting their GPU to pro / pay to play types, how true are those rumors just out of curiousity?

Using Google Chome

**Comment by cperry-goog** [comment]
We are deleting free tier runtimes that access stable-diffusion-webui. We prioritize interactive notebook compute for free of charge tier users. We can't support web frontends that use Colab as a convenient free GPU. Users on our free of charge tier are encouraged to use Colab for interactive programming usage.

Paid users are not subject to any restrictions on web frontends, as they pay for the compute they consume.
