### ISSUE TITLE
Disconnect and delete runtime doesnt work anymore. Nothing happens...

### ISSUE THREAD

**Issue by jarredou** [googlecolab/colabtools#3647]
"Disconnect and delete runtime" doesnt work anymore. Nothing happens. Runtime continues, I can't disconnect or do anything...

**Comment by aegonwolf** [comment]
Same here today, I couldn't turn off the runtime, the compute units were still deducted. It showed as if it was disconnected. When I opened it again it's running again.

**Comment by cperry-goog** [comment]
I can't reproduce - if you encounter this again, please file feedback in product
