### ISSUE TITLE
Unresolved issue: NotImplementedError: A UTF-8 locale is required. Got ANSI_X3.4-1968

### ISSUE THREAD

**Issue by TheWizier** [googlecolab/colabtools#3649]
#3409
This issue is not resolved

**Comment by convurt** [comment]
I get this same error and cant get past it.  All I want to do is download my files or copy them to my Google drive, I cant do either.

[usr/local/lib/python3.10/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in _run_command(cmd, clear_streamed_output)
    165   locale_encoding = locale.getpreferredencoding()
    166   if locale_encoding != _ENCODING:
--> 167     raise NotImplementedError(
    168         'A UTF-8 locale is required. Got {}'.format(locale_encoding)
    169     )

NotImplementedError: A UTF-8 locale is required. Got ANSI_X3.4-1968

**Comment by cperry-goog** [comment]
Need a reproducible notebook to investigate; we haven't been able to repo this

**Comment by convurt** [comment]
I eventually got through it with this code and it has been working

import locale
locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')

**Comment by Zaheer-10** [comment]
I had same issue:

HOW I SOLVED - 

`import locale
print(locale.getpreferredencoding())`

`import locale
def getpreferredencoding(do_setlocale = True):
    return "UTF-8"
locale.getpreferredencoding = getpreferredencoding`

**Comment by s-samadmasud** [comment]
### the following code is working for me
![a utf-8 locale is required problem solved](https://github.com/googlecolab/colabtools/assets/149870958/e56dc7df-d7db-4ea2-8e04-b6a4874738bd)
