### ISSUE TITLE
issuing a gcloud train command: %%shell  gcloud ml-engine local train --module-name trainer.task --package-path drive/findml6mug/trainer/ -- --eval-steps 5

### ISSUE THREAD

**Issue by zbenmo** [googlecolab/colabtools#365]
ERROR: (gcloud.ml-engine.local.train) /usr/local/bin/python: command not found

**Comment by craigcitro** [comment]
Can you provide a minimal notebook reproducing the problem?

**Comment by zbenmo** [comment]
Hi Craig,

The following was my first and only cell:

%%shell gcloud ml-engine local train --module-name trainer.task
--package-path drive/findml6mug/trainer/ -- --eval-steps 5

**Comment by craigcitro** [comment]
I suspect the problem is that the path you're providing (`drive/findml6mug/trainer`) doesn't exist.

Indeed, putting an empty file there (eg

    !mkdir -p drive/findml6mug/trainer
    !touch drive/findml6mug/trainer/__init__.py
    !touch drive/findml6mug/trainer/task.py

) gets no error (and, as expected, does nothing).

**Comment by zbenmo** [comment]
You're probably right. Now that I think of it, it was my mistake.
Apologises.

**Comment by craigcitro** [comment]
No problem at all!
