### ISSUE TITLE
Error in colab examples

### ISSUE THREAD

**Issue by jackreeceejini** [googlecolab/colabtools#366]
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/matplotlib/projections/__init__.py in get_projection_class(projection)
     62     try:
---> 63         return projection_registry.get_projection_class(projection)
     64     except KeyError:

/usr/local/lib/python3.6/dist-packages/matplotlib/projections/__init__.py in get_projection_class(self, name)
     28         """
---> 29         return self._all_projection_types[name]
     30 

KeyError: '3d'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-1-8dfe26ee0814> in <module>()
      3 
      4 fig = plt.figure()
----> 5 ax = fig.add_subplot(111, projection = '3d')
      6 
      7 x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

/usr/local/lib/python3.6/dist-packages/matplotlib/figure.py in add_subplot(self, *args, **kwargs)
   1054         else:
   1055             projection_class, kwargs, key = process_projection_requirements(
-> 1056                 self, *args, **kwargs)
   1057 
   1058             # try to find the axes with this key in the stack

/usr/local/lib/python3.6/dist-packages/matplotlib/projections/__init__.py in process_projection_requirements(figure, *args, **kwargs)
     89 
     90     if isinstance(projection, six.string_types) or projection is None:
---> 91         projection_class = get_projection_class(projection)
     92     elif hasattr(projection, '_as_mpl_axes'):
     93         projection_class, extra_kwargs = projection._as_mpl_axes()

/usr/local/lib/python3.6/dist-packages/matplotlib/projections/__init__.py in get_projection_class(projection)
     63         return projection_registry.get_projection_class(projection)
     64     except KeyError:
---> 65         raise ValueError("Unknown projection '%s'" % projection)
     66 
     67 

ValueError: Unknown projection '3d'

**Comment by craigcitro** [comment]
What example were you running?

**Comment by jackreeceejini** [comment]
> What example were you running?

import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111, projection = '3d')

x, y, z = axes3d.get_test_data()

ax.plot_wireframe(x, y, z, rstride = 2, cstride = 2)

plt.title("Wireframe Plot Example")
plt.tight_layout()
plt.show()

Basically anything with this line of code:
ax = fig.add_subplot(111, projection = '3d')
