### ISSUE TITLE
Compute Units Disappeared 1 Week After Purchase

### ISSUE THREAD

**Issue by smithd3887** [googlecolab/colabtools#3662]
**Describe the current behavior**
A few days ago I purchased 100 compute units for Colab and Used about 10 units for a prediction. However, when I opened Colab today, I had zero compute units left.

**Describe the expected behavior**
I expected there to be 90 units left in my "account" for use for other predictions.

**What web browser you are using**
Firefox

![no units](https://github.com/googlecolab/colabtools/assets/133139151/2a0c5c04-cb79-46a0-a217-e4ed0df22034)
![Proof of purchase](https://github.com/googlecolab/colabtools/assets/133139151/a7c575d0-6d77-4bc5-8f03-ac79d9e96e21)

**Comment by EvanWiederspan** [comment]
We won't be able to diagnose this from Github, can you file In-product feedback from Help -> Send feedback?

**Comment by ekblad** [comment]
hi - this happened to me too, but there was no answer going through Help -> Send feedback.
