### ISSUE TITLE
Sometimes the letters N and P stop working inside Collab

### ISSUE THREAD

**Issue by brunoei20** [googlecolab/colabtools#3664]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by brunoei20** [comment]
Obviously they work outside collab. Right now I am using a Collab, and neither 'n' nor 'p' work when I push the key in my keyboard, but clearly as I am writing this it works in here

**Comment by EvanWiederspan** [comment]
I see it working for me in a regular code cell, is there a specific place you're typing where it doesn't work? Also, does it work in incognito mode, with extensions turned off?

**Comment by EvanWiederspan** [comment]
We've gotten other reports of this as well, tracking internally as b/281911996. Any additional repro steps would be helpful, as I have not yet been able to reproduce. Was this after viewing a notebook diff?

**Comment by brunoei20** [comment]
Thanks,

Do you mean if this happened after a pop-up saying "Couldn't save
automatically because it was opened in another tab"? If so, yes this
happened after that pop-up.

**Comment by AurekC** [comment]
I am facing the same issue! Letters n and p not working

**Comment by ragman-google** [comment]
This is being tracked internally as b/281911996 -- we'll have a fix out soon.

In the meantime, as a workaround, refreshing the page should fix this until the next time you get the pop-up mentioned above.

Sorry for the inconvenience, we'll post here as soon as it's fixed!

**Comment by gabriellavinco** [comment]
this happened to me when trying to create a text cell just now

**Comment by ragman-google** [comment]
This has been fixed for a couple of weeks, forgot to close the issue. Please let us know if you run into this again!
