### ISSUE TITLE
Colab lags heavily after a period of time in a notebook.

### ISSUE THREAD

**Issue by MatthewCWeston** [googlecolab/colabtools#3676]
**Describe the current behavior**
Right now, after roughly 40 minutes working within a Colab notebook, I notice severe lag when attempting to scroll through the document. Syntax highlighting seems to freeze up occasionally, as well. Refreshing the page resolves the issue until it reoccurs.

**Describe the expected behavior**
The smooth workflow experienced when entering the page, or after refreshing the page, continues indefinitely.

**What web browser you are using**
Brave; I've also noticed this issue in standard Chrome and Safari.

**Additional context**
Trying to sort this out myself, I noticed a very substantial number of "analytics logging failed" messages. The rate at which they appear seems correlated with the rate at which lag occurs, and seems to increase over time. I'm not certain that this is the root cause, but adding a graceful failure mechanism after repeated failed calls to /analytics might be helpful anyways.

**Comment by recycletechno** [comment]
I am experiencing the same issue. I have been using the same notebook for a week now, and I am using the latest version of Windows 10 and Google Chrome. However, I am facing significant lag when scrolling. I have already disabled all Chrome extensions, but the problem persists. It is worth noting that a week or two ago, everything was working perfectly fine. When I scroll, the CPU usage spikes to around 30%, whereas it remains at around 1% when I am not performing any scrolling actions. Additionally, it is important to mention that I am not even connected to a Google Colab virtual machine.

**Comment by ragman-google** [comment]
Thank you both for the reports! This is being tracked internally as b/282734364.

**Comment by cperry-goog** [comment]
This should be fixed now - would love to hear if anyone is still seeing it.

**Comment by LilyShevchenko** [comment]
All good in my notebooks, it seems. Thanks!

**Comment by recycletechno** [comment]
Not very smooth but much better than it used to be. Thank you
