### ISSUE TITLE
It refused to let me change the environment from Python to Julia even though I hav worked with Julia in the past on colab

### ISSUE THREAD

**Issue by maryamelyaagoubi** [googlecolab/colabtools#3677]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by maryamelyaagoubi** [comment]
It refused to let me change the environment from Python to Julia even though I have worked with Julia in the past on colab. The parameters of the notebook do not even let me pick what language I want to be used

**Comment by cperry-goog** [comment]
We don't support Julia, sorry :(

We've seen some members of the Julia community figure out how to launch a kernel, but we don't provide support.
