### ISSUE TITLE
korean comment bugs

### ISSUE THREAD

**Issue by potatowon** [googlecolab/colabtools#3679]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

When entering comments in Korean, there is a bug where the previous ones overlap and you can't see what you are writing.

**Comment by ragman-google** [comment]
Being tracked internally as b/283266167.

**Comment by ragman-google** [comment]
This should be fixed now -- please let us know if you're still running into it!
