### ISSUE TITLE
It's driving me crazy after the update. please help

### ISSUE THREAD

**Issue by cwoonb** [googlecolab/colabtools#3685]
There was a problem with the code that worked normally after the Colab update. The same problem occurred when I tested by changing python version 3.7, 3.8, 3.9. Is there any way to use the version prior to the May 2023 update?
This update is driving me so crazy. Please help me.

**Comment by mayankmalik-colab** [comment]
Unfortunately It's not possible to use the older python versions. Can you elaborate the issue you are facing or share the min notebook?

**Comment by cperry-goog** [comment]
no plans to support versions less than python 3.10
