### ISSUE TITLE
AlphaFold crash

### ISSUE THREAD

**Issue by olibgl** [googlecolab/colabtools#3687]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
I am using AlphaFold (here: https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/beta/AlphaFold2_advanced.ipynb#scrollTo=bQe3KeyTcv0n) with exactly the same parameters for several months, changing only the protein sequence. For the first time, the program crashes systematically at the step "Run alphafold"
and issues the following error message: 
Running model_1_ptm_seed_0: 0%
0/1 [elapsed: 00:32 remaining: ?]

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

[<ipython-input-10-b8dbfbea5929>](https://localhost:8080/#) in <cell line: 67>()
     65 # run alphafold
     66 ###########################
---> 67 outs, model_rank = cf_af.run_alphafold(feature_dict, opt, runner, num_models, num_samples, subsample_msa,
     68                                        rank_by=rank_by, show_images=show_images)

47 frames

    [... skipping hidden 12 frame]

    [... skipping hidden 9 frame]

    [... skipping hidden 8 frame]

[/content/alphafold/alphafold/model/utils.py](https://localhost:8080/#) in mask_mean(mask, value, axis, drop_mask_channel, eps)
     54   elif axis is None:
     55     axis = list(range(len(mask_shape)))
---> 56   assert isinstance(axis, collections.Iterable), (
     57       'axis needs to be either an iterable, integer or "None"')
     58 

AttributeError: module 'collections' has no attribute 'Iterable'

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
--> protein structure prediction

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

--> Firefox 113.01 on MacOS Big Sur 11.7.6

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.

The crash is reproducible here:  https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/beta/AlphaFold2_advanced.ipynb#scrollTo=bQe3KeyTcv0n

using for example this sequence: YSGTARYHTQMLRVREFIRFHQIPNPLRQRLEEYFQHAWSYTNGIDMNAVLKGFPECLQADICLHLNRSLLQHCKPFRGATKGCLRALAMKFKTTHAPPGDTLVHAGDLLTALYFISRGSIEILRGDVVLAILGKNDIFGEPLNLYARPGKSNGDVRALTYCDLHKIHRDDLLEVLDMYPEFSDHFWSSLEITFNLR

 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mayankmalik-colab** [comment]
This is most probably because the notebook is not compatible with `Python 3.10`.  The error `module 'collections' has no attribute 'Iterable'`  comes for Python 3.10. The Iterable class was deprecated in 3.9 and now removed from collections in Python 3.10.

Please reach out to the notebook owner and upgrade the same.

**Comment by olibgl** [comment]
Thank for the answer. However, it is not clear for me. 
I was using AlaphaFold2 through the Colab notebook, not mine. Thus, I don't really knwo what to do when you suggest to reach out to the notebook owner.

**Comment by cperry-goog** [comment]
File an issue over at https://github.com/sokrypton/ColabFold/issues - this is maintained by a 3rd party
