### ISSUE TITLE
Connect custom VM to Colab

### ISSUE THREAD

**Issue by Cirediallo** [googlecolab/colabtools#3691]
**Description**
I would like to connect a custom VM machine from Google Cloud to Colab. I started a VM using these instructions: https://research.google.com/colaboratory/marketplace.html?utm_source=faq&utm_medium=link&utm_campaign=why_arent_resources_guaranteed
Step done: I've created a Colab instance in the Deployment Manager. In Colab I provided the project id, the Colab instance zone and the Colab instance name. Even if I try with the button "CONNECT TO VM WITH COLAB" from the the Deployment Manager
> I would like also to know if I'm connected if I'll have a given time or my colab will run untill I stop the training.

**Browser tested on**
Chrome, Firefox

**Additional context**
I've also a Colab Pro+

**Comment by cperry-goog** [comment]
Are you seeing the connected state change to green? Those steps should work to connect you to your custom VM, and then yes, that VM will run as long as you have it run, and the notebook should reconnect if you ever get disconnected.

**Comment by Cirediallo** [comment]
No it just like this picture below around 3 minutes and then print **Unable to connect to the runtime environment**
![colab](https://github.com/googlecolab/colabtools/assets/16343565/a53d4ce7-1fd7-4af2-ae28-da7f82e55a1a)

**Comment by EvanWiederspan** [comment]
I don't think we'll be able to diagnose more from Github, could you file in-product feedback at Help -> Send Feedback?

**Comment by cperry-goog** [comment]
Yeah, can you re-submit feedback in product and mention this issue? I read through all the issues, if you say something weird in there it'll flag it for me to dig deeper.
