### ISSUE TITLE
Colab crashed after running AI algorithm

### ISSUE THREAD

**Issue by clonesangram87** [googlecolab/colabtools#3693]
**Describe the current behavior**
While running my PaddleOCR library, I am getting runtime error saying my session is crashed. I ran multiple times in different GPU but getting the same erorr. I am getting error as mentioned below while running the below code:

********************************************************************************************************
img_path = os.path.join('.', r'/content/drive/MyDrive/Colab Notebooks/quotes_pic.jpeg')

result = ocr_model.ocr(img_path)
result

*********************************************************************************************************

Error message:

Timestamp,Level,Message
"May 18, 2023, 1:18:32 AM",WARNING,WARNING:root:kernel b32395dc-3814-42e4-85ec-63c82357666c restarted
"May 18, 2023, 1:18:32 AM",INFO,"KernelRestarter: restarting kernel (1/5), keep random ports"
"May 18, 2023, 1:18:30 AM",WARNING,  [SignalInfo: *** SIGSEGV (@0x0) received by PID 8299 (TID 0x7f9ef028e740) from PID 0 ***]
"May 18, 2023, 1:18:30 AM",WARNING,"  [TimeInfo: *** Aborted at 1684352910 (unix time) try ""date -d @1684352910"" if you are using GNU date ***]"
"May 18, 2023, 1:18:30 AM",WARNING,FatalError: `Segmentation fault` is detected by the operating system.
"May 18, 2023, 1:18:30 AM",WARNING,----------------------
"May 18, 2023, 1:18:30 AM",WARNING,Error Message Summary:
"May 18, 2023, 1:18:30 AM",WARNING,----------------------
"May 18, 2023, 1:18:30 AM",WARNING,"No stack trace in paddle, may be caused by external reasons."
"May 18, 2023, 1:18:30 AM",WARNING,--------------------------------------
"May 18, 2023, 1:18:30 AM",WARNING,C++ Traceback (most recent call last):
"May 18, 2023, 1:18:30 AM",WARNING,--------------------------------------
"May 18, 2023, 1:15:29 AM",WARNING,WARNING:root:kernel b32395dc-3814-42e4-85ec-63c82357666c restarted
"May 18, 2023, 1:15:29 AM",INFO,"KernelRestarter: restarting kernel (1/5), keep random ports"
"May 18, 2023, 1:15:27 AM",WARNING,  [SignalInfo: *** SIGSEGV (@0x0) received by PID 5448 (TID 0x7f35b5522740) from PID 0 ***]
"May 18, 2023, 1:15:27 AM",WARNING,"  [TimeInfo: *** Aborted at 1684352727 (unix time) try ""date -d @1684352727"" if you are using GNU date ***]"
"May 18, 2023, 1:15:27 AM",WARNING,FatalError: `Segmentation fault` is detected by the operating system.
"May 18, 2023, 1:15:27 AM",WARNING,----------------------
"May 18, 2023, 1:15:27 AM",WARNING,Error Message Summary:
"May 18, 2023, 1:15:27 AM",WARNING,----------------------
"May 18, 2023, 1:15:27 AM",WARNING,"No stack trace in paddle, may be caused by external reasons."
"May 18, 2023, 1:15:27 AM",WARNING,--------------------------------------
"May 18, 2023, 1:15:27 AM",WARNING,C++ Traceback (most recent call last):
"May 18, 2023, 1:15:27 AM",WARNING,--------------------------------------
"May 18, 2023, 1:04:17 AM",WARNING,WARNING:root:kernel b32395dc-3814-42e4-85ec-63c82357666c restarted
"May 18, 2023, 1:04:17 AM",INFO,"KernelRestarter: restarting kernel (1/5), keep random ports"
"May 18, 2023, 1:04:16 AM",WARNING,  [SignalInfo: *** SIGSEGV (@0x0) received by PID 3899 (TID 0x7f78bb576740) from PID 0 ***]
"May 18, 2023, 1:04:16 AM",WARNING,"  [TimeInfo: *** Aborted at 1684352056 (unix time) try ""date -d @1684352056"" if you are using GNU date ***]"
"May 18, 2023, 1:04:16 AM",WARNING,FatalError: `Segmentation fault` is detected by the operating system.
"May 18, 2023, 1:04:16 AM",WARNING,----------------------
"May 18, 2023, 1:04:16 AM",WARNING,Error Message Summary:
"May 18, 2023, 1:04:16 AM",WARNING,----------------------
"May 18, 2023, 1:04:16 AM",WARNING,"No stack trace in paddle, may be caused by external reasons."
"May 18, 2023, 1:04:16 AM",WARNING,--------------------------------------
"May 18, 2023, 1:04:16 AM",WARNING,C++ Traceback (most recent call last):
"May 18, 2023, 1:04:16 AM",WARNING,--------------------------------------
"May 18, 2023, 12:59:50 AM",INFO,"Kernel started: b32395dc-3814-42e4-85ec-63c82357666c, name: python3"
"May 18, 2023, 12:44:24 AM",INFO,Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
"May 18, 2023, 12:44:24 AM",INFO,http://172.28.0.12:9000/
"May 18, 2023, 12:44:24 AM",INFO,Jupyter Notebook 6.4.8 is running at:
"May 18, 2023, 12:44:24 AM",INFO,Serving notebooks from local directory: /
"May 18, 2023, 12:44:24 AM",INFO,Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
"May 18, 2023, 12:44:24 AM",INFO,http://172.28.0.2:9000/
"May 18, 2023, 12:44:24 AM",INFO,Jupyter Notebook 6.4.8 is running at:
"May 18, 2023, 12:44:24 AM",INFO,Serving notebooks from local directory: /
"May 18, 2023, 12:44:21 AM",INFO,google.colab serverextension initialized.
"May 18, 2023, 12:44:21 AM",INFO,"Authentication of /metrics is OFF, since other authentication is disabled."
"May 18, 2023, 12:44:21 AM",INFO,Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
"May 18, 2023, 12:44:21 AM",WARNING,    	/root/.jupyter/jupyter_notebook_config.json
"May 18, 2023, 12:44:21 AM",WARNING,    	/root/.local/etc/jupyter/jupyter_notebook_config.json
"May 18, 2023, 12:44:21 AM",WARNING,    	/usr/etc/jupyter/jupyter_notebook_config.json
"May 18, 2023, 12:44:21 AM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.json
"May 18, 2023, 12:44:21 AM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.d/panel-client-jupyter.json
"May 18, 2023, 12:44:21 AM",WARNING,    	/etc/jupyter/jupyter_notebook_config.json
"May 18, 2023, 12:44:21 AM",INFO,google.colab serverextension initialized.
"May 18, 2023, 12:44:21 AM",WARNING,[D 19:14:21.106 NotebookApp] Loaded config file: /root/.jupyter/jupyter_notebook_config.py
"May 18, 2023, 12:44:21 AM",WARNING,[D 19:14:21.101 NotebookApp] Looking for jupyter_notebook_config in /root/.jupyter
"May 18, 2023, 12:44:21 AM",WARNING,[D 19:14:21.101 NotebookApp] Looking for jupyter_notebook_config in /root/.local/etc/jupyter
"May 18, 2023, 12:44:21 AM",WARNING,[D 19:14:21.101 NotebookApp] Looking for jupyter_notebook_config in /usr/etc/jupyter
"May 18, 2023, 12:44:21 AM",WARNING,[D 19:14:21.101 NotebookApp] Loaded config file: /usr/local/etc/jupyter/jupyter_notebook_config.json
"May 18, 2023, 12:44:21 AM",WARNING,[D 19:14:21.100 NotebookApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
"May 18, 2023, 12:44:21 AM",WARNING,[D 19:14:21.100 NotebookApp] Loaded config file: /etc/jupyter/jupyter_notebook_config.py
"May 18, 2023, 12:44:21 AM",WARNING,[D 19:14:21.097 NotebookApp] Looking for jupyter_notebook_config in /etc/jupyter
"May 18, 2023, 12:44:21 AM",WARNING,[D 19:14:21.097 NotebookApp] Looking for jupyter_config in /root/.jupyter
"May 18, 2023, 12:44:21 AM",WARNING,[D 19:14:21.096 NotebookApp] Looking for jupyter_config in /root/.local/etc/jupyter
"May 18, 2023, 12:44:21 AM",WARNING,[D 19:14:21.096 NotebookApp] Looking for jupyter_config in /usr/etc/jupyter
"May 18, 2023, 12:44:21 AM",WARNING,[D 19:14:21.095 NotebookApp] Looking for jupyter_config in /usr/local/etc/jupyter
"May 18, 2023, 12:44:21 AM",WARNING,[D 19:14:21.092 NotebookApp] Looking for jupyter_config in /etc/jupyter
"May 18, 2023, 12:44:21 AM",WARNING,"[D 19:14:21.091 NotebookApp] Searching ['/root/.jupyter', '/root/.local/etc/jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files"
"May 18, 2023, 12:44:21 AM",INFO,"Authentication of /metrics is OFF, since other authentication is disabled."
"May 18, 2023, 12:44:21 AM",INFO,Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
"May 18, 2023, 12:44:21 AM",WARNING,    	/root/.jupyter/jupyter_notebook_config.json
"May 18, 2023, 12:44:21 AM",WARNING,    	/root/.local/etc/jupyter/jupyter_notebook_config.json
"May 18, 2023, 12:44:21 AM",WARNING,    	/usr/etc/jupyter/jupyter_notebook_config.json
"May 18, 2023, 12:44:21 AM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.json
"May 18, 2023, 12:44:21 AM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.d/panel-client-jupyter.json
"May 18, 2023, 12:44:21 AM",WARNING,    	/etc/jupyter/jupyter_notebook_config.json
"May 18, 2023, 12:44:20 AM",WARNING,[D 19:14:20.699 NotebookApp] Loaded config file: /root/.jupyter/jupyter_notebook_config.py
"May 18, 2023, 12:44:20 AM",WARNING,[D 19:14:20.695 NotebookApp] Looking for jupyter_notebook_config in /root/.jupyter
"May 18, 2023, 12:44:20 AM",WARNING,[D 19:14:20.695 NotebookApp] Looking for jupyter_notebook_config in /root/.local/etc/jupyter
"May 18, 2023, 12:44:20 AM",WARNING,[D 19:14:20.695 NotebookApp] Looking for jupyter_notebook_config in /usr/etc/jupyter
"May 18, 2023, 12:44:20 AM",WARNING,[D 19:14:20.694 NotebookApp] Loaded config file: /usr/local/etc/jupyter/jupyter_notebook_config.json
"May 18, 2023, 12:44:20 AM",WARNING,[D 19:14:20.692 NotebookApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
"May 18, 2023, 12:44:20 AM",WARNING,[D 19:14:20.692 NotebookApp] Loaded config file: /etc/jupyter/jupyter_notebook_config.py
"May 18, 2023, 12:44:20 AM",WARNING,[D 19:14:20.690 NotebookApp] Looking for jupyter_notebook_config in /etc/jupyter
"May 18, 2023, 12:44:20 AM",WARNING,[D 19:14:20.689 NotebookApp] Looking for jupyter_config in /root/.jupyter
"May 18, 2023, 12:44:20 AM",WARNING,[D 19:14:20.689 NotebookApp] Looking for jupyter_config in /root/.local/etc/jupyter
"May 18, 2023, 12:44:20 AM",WARNING,[D 19:14:20.689 NotebookApp] Looking for jupyter_config in /usr/etc/jupyter
"May 18, 2023, 12:44:20 AM",WARNING,[D 19:14:20.681 NotebookApp] Looking for jupyter_config in /usr/local/etc/jupyter
"May 18, 2023, 12:44:20 AM",WARNING,[D 19:14:20.679 NotebookApp] Looking for jupyter_config in /etc/jupyter
"May 18, 2023, 12:44:20 AM",WARNING,"[D 19:14:20.678 NotebookApp] Searching ['/root/.jupyter', '/root/.local/etc/jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files"

**Describe the expected behavior**
I should get my output without any errors

**What web browser you are using**
Microsoft Edge

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by clonesangram87** [comment]
Before running the above command I ran the following command sequentially.

Code 1:

from google.colab import drive
drive.mount('/content/drive')

Code 2:

!nvcc  --version

Code 3: 

!python -m pip install paddlepaddle-gpu==2.3.0 -i https://mirror.baidu.com/pypi/simple

Code 4:

!pip install paddleocr

Code 5:

!git clone https://github.com/PaddlePaddle/PaddleOCR

Code 6:

from paddleocr import PaddleOCR, draw_ocr # main OCR dependencies
from matplotlib import pyplot as plt # plot images
import cv2 #opencv
import os # folder directory navigation

Code 7:

ocr_model = PaddleOCR(lang='en',use_angle_cls=True)

**Comment by mayankmalik-colab** [comment]
It doesn't seem like a Colab related issue. Can you confirm with the package owner that it is compatible with python 3.10. I can see the last [Python version mentioned on pypi is 3.7](https://pypi.org/project/paddleocr/).

**Comment by cperry-goog** [comment]
This looks like a version compatibility issue, closing this out - if the package owner stands up a 3.10 compliant version that breaks specifically in Colab, please open a new issue.

**Comment by clonesangram87** [comment]
thanks for the help

cheers!
