### ISSUE TITLE
Changes are not being saved in my notebooks anymore

### ISSUE THREAD

**Issue by marv950819** [googlecolab/colabtools#3695]
I got a message saying : This file could not be saved. Please use the File menu to download the .ipynb and upload the notebook to make a copy that includes your recent changes.
![Screenshot 2023-05-18 at 14 49 44](https://github.com/googlecolab/colabtools/assets/28380103/05929538-2fa2-45a4-bfc1-3384af7d7a63)

**Comment by EvanWiederspan** [comment]
Are you still seeing this issue? Does refreshing the page fix it? If not, please share the notebook
