### ISSUE TITLE
Premium Plus not working

### ISSUE THREAD

**Issue by Rotund58** [googlecolab/colabtools#3696]
I pay for the Premium Plus deOldify video colorizer notebook.
I have been trying to use it for 2 days now. Every time I try to use it all the cells install correctly apart from the 7th "colorizer" I paste a link to my Dropbox then click the button it turns black at first but then soon changes to red and the link fails I continue click and it continues to turn red. I have tried rebooting the notebook still the same and I've even rebooted my computer nothing solves it. I use Google's Chrome browser Please help. 

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
This isn't a notebook owned by Colab, I would recommend reaching out to the notebook author for help instead
