### ISSUE TITLE
using python3+gpu runtime only first concurrent notebook gets python3, others get python2

### ISSUE THREAD

**Issue by lefant** [googlecolab/colabtools#37]
Hi,

Thanks for this awesome service. I have noticed some weird behavior around the Python 3 with GPU runtime. Whenever I open one notebook with the Python 3 with GPU runtime type the python version used is 3 as expected, however, any additional notebooks I open while the other one is still connected end up using Python 2 with GPU, ie.

```
import sys
print(sys.version)
```
returns on the first notebook:
```
3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0]
```
and on the second and other additionally opened notebooks:
```
2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0]
```

If I disconnect and wait until the VM goes away and come back after a while and start the notebooks in the reverse order it is still the notebook that is started first which has Python 3 and the second one getting Python 2, so it does not seem related to settings on the actual notebooks (I also looked at the notebook files in plain text to confirm that the runtime config is identical).
If I switch the runtime type to remove the GPU acceleration the issue seems to go away.

Also ```ps xauww``` shows two processes for the two notebooks, the first one running with /usr/bin/python3 and the second with /usr/bin/python.

Screenshot first notebook:
![image](https://user-images.githubusercontent.com/64208/35376233-6254c75a-01aa-11e8-847f-d7ab93559639.png)

Screenshot second notebook:
![image](https://user-images.githubusercontent.com/64208/35376237-68c4e0c0-01aa-11e8-9ae3-0813ffbcbdfa.png)

Let me know if there is anything else you need to know or if you want me to test anything to help resolving the issue!

Thanks and best regards,
Fabian

**Comment by craigcitro** [comment]
First off, thanks for the outstanding bug report. 👍 

I can't seem to repro this issue -- I've got two notebooks open right now that are both set to py3+gpu, and forcing a restart of my backend (*) still gets me py3+gpu with both:
  
<img width="697" alt="screen shot 2018-01-25 at 12 12 21 am" src="https://user-images.githubusercontent.com/468559/35377556-7ca269f0-0164-11e8-8836-c47ab515bb97.png">

A few questions to try and dig a little more:
* is it possible to share two notebooks that repro the issue with colaboratory-team@google.com?
* just to confirm, how are you opening the second notebook? (eg from recent, directly navigating, something else completely?)

**Comment by lefant** [comment]
So I tried reproducing it on a fresh VM with two notebooks starting from scratch and everything worked fine at first just like for you. Then I added some code I used in my full notebook to fetch dependencies and any copies I made after running that would get python version 2 again.

Basically the responsible code grabs a Pipfile and companion Pipfile.lock from https://github.com/lefant/dockerfiles-lefant/blob/master/python3-keras/ and then uses ```!pip3 install pipenv && pipenv install --three --deploy --system``` to install all the packages. I noticed now that these packages include ipython and jupyter, so that might be very relevant (originally I use that Pipfile to build a docker container that has its own jupyter server). I will try with only those / without those packages next, but first I have to wait until my VM goes away... ;)

notebook links (shared with colaboratory-team@google.com and available for public viewing):
https://colab.research.google.com/notebook#fileId=1IsB6qOqB7N18DwNYXEGzfkozKMTlRTDH
https://colab.research.google.com/notebook#fileId=1fzxvf5LP3RELfkE8cfxrRRbL2gliwCpG

**Comment by lefant** [comment]
Once I stop installing jupyter, ipython and tensorflow from Pipfile everythings works fine on a fresh VM. I am not sure how exactly installing a custom version of jupyter and ipython messes things up, but then I do not have a use case for it, so I am closing this issue. Sorry for the noise.

**Comment by craigcitro** [comment]
Thanks for digging through -- I'm betting what happened is that some step of the jupyter install overwrote the path for the python3 kernelspec.
