### ISSUE TITLE
Strange rounding error

### ISSUE THREAD

**Issue by blixten** [googlecolab/colabtools#370]
This looks like a strange rounding issue, can't figure out why this is

This code results in:
```
for i in range(1,10):
  print(i*0.1)
```
0.1
0.2
0.30000000000000004
0.4
0.5
0.6000000000000001
0.7000000000000001
0.8
0.9

While this works
```
for i in range(1,10):
  print(i/10)
```
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9

**Comment by craigcitro** [comment]
(This isn't anything specific to colab, this is just a Python question.)
