### ISSUE TITLE
The Colab notebook is not displayed correctly

### ISSUE THREAD

**Issue by jmtoral** [googlecolab/colabtools#3703]
The Colab notebook does not display complete code chunks or their results.

**
<img width="577" alt="image" src="https://github.com/googlecolab/colabtools/assets/22439582/34aa43f0-0517-4da9-ac43-a84e7eecc2da">
**

**Comment by EvanWiederspan** [comment]
Thanks for the report, can you share the repro steps for how you got to that point?

**Comment by jmtoral** [comment]
I only opened my Colab Notebook.

**Comment by EvanWiederspan** [comment]
Can you share the notebook?

**Comment by rooneycoelho** [comment]
I am with the same issue

**Comment by EvanWiederspan** [comment]
We'll need a publicly available repro notebook to diagnose more

Also, what browser are you using, and does it repro with all browser extensions disabled?

**Comment by rooneycoelho** [comment]
I removed all cookies and all user data and it worked.

Thank you
________________________________
