### ISSUE TITLE
Colab keep restart and disconect runtime ( even with pro user)

### ISSUE THREAD

**Issue by nghiagithub318** [googlecolab/colabtools#3705]
![image](https://github.com/googlecolab/colabtools/assets/96003264/a2e90a5a-8ba0-4d80-b43f-7bbf57e622fb)

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
We'll need more info to be able to help, can you share the notebook you're using? Also, are you seeing any errors pop up when your runtime restarts, specifically ones that mention running out of memory? Runtime logs would help as well
