### ISSUE TITLE
follow up #1694: "Shareddrives" does not show when I mount google drive in colab

### ISSUE THREAD

**Issue by BKFC90** [googlecolab/colabtools#3708]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
I cannot access folders "shared with me" on Google Drive in Google Colab by entering, for example, 
```
from google.colab import drive
drive.mount("/content/drive")
!ls /content/drive/Shareddrives
```
I get a "no such file or directory" error message.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
From other posts (#1694), my understanding is that one can access folders "shared with me" by a command **within** Google Colab.  I greatly prefer this, since I expect to have many students sharing a code that I will put on my own drive, and would rather not have them go through the additional process of logging into their own Google Drive and creating a shortcut.
**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
MacOS with Chrome browser.

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
I also have Google Drive desktop installed on my Mac.  The "shared with me" folders do not show up there either, unless I go through the process of creating a shortcut.

This apparently worked in 2022, but now.  If it's a 'feature' that's no longer available, that would be useful to know, though unfortunate.

 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
This just worked for me. To clarify, do you see a Shared Drive tab on the left when you view the Drive Web UI at drive.google.com?

**Comment by BKFC90** [comment]
In the left-hand panel of the web interface, I get the attached.  There is “My Drive” and “Shared with me” but no “Shared Drive,” and I found no way to share the top-level drive from another account.  I guess I don’t know what it takes to generate a “Shared Drive."

**Comment by EvanWiederspan** [comment]
If it doesn't appear in the Web UI, then it sounds like you just don't have any shared drives for us to mount in Colab. I'm not very familiar with them myself, but there's a guide [here](https://support.google.com/a/users/answer/9310351?sjid=13350302207506941093-NA) that will hopefully be helpful

**Comment by BKFC90** [comment]
Here is the issue:

Shared drives are only available for eligible work or school accounts, and you’re signed in to your personal account: ***@***.***
