### ISSUE TITLE
Conexion binance api

### ISSUE THREAD

**Issue by RenzoTenaglia** [googlecolab/colabtools#3715]
When I connect the binance api I get the following error:

Code: client=binance.Client(api_key=api_key,api_secret=api_pass)
error: APIError(code=0): Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error

I talked to binance support and we concluded that the error is from colab, because if I run the code locally in jupyter the connection works

**Comment by EvanWiederspan** [comment]
Your code in Colab will be running on a Google Cloud VM, this sounds like binance is blocking traffic from there, I would recommend reaching out to binance support again and checking if they expect traffic from Google Cloud to work

**Comment by faarese** [comment]
I have same issue brother binance through me to host , host through me to binance i dont know what i should do how can i fixed

**Comment by silvioar** [comment]
Binance API does not accept US servers...

**Comment by Zakaraya** [comment]
I'm creating tests in GitHub Action and started encountering the same error.(client=binance.Client(api_key=key,api_secret=pass)). GitHub Action prohibits the use of proxies or VPNs. How can I fix this error?
