### ISSUE TITLE
Downgrading python version and restarting the environment crashes Colab

### ISSUE THREAD

**Issue by lexmar07** [googlecolab/colabtools#3716]
**Describe the current behavior**
After trying to downgrade Python version (to 3.7 or 3.8) via  

`!sudo update-alternatives --config python3 <<< '2'`

 and restarting the environment session crashes and further connection attempts fail.

**Describe the expected behavior**
It should reconnect.

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.

https://colab.research.google.com/gist/lexmar07/81952731ddb3dc67695d603dc3a094c1/colabcrash.ipynb

**Comment by EvanWiederspan** [comment]
We don't support changing the Python version on a runtime
