### ISSUE TITLE
Error in display of tqdm Progress Bar

### ISSUE THREAD

**Issue by avinsit123** [googlecolab/colabtools#372]
tqdm is a progress bar utility specifically used to track our iteration through batches of data.However,when I use it in google colab.The progress bar does not say the same and for each iteration a new progress Bar is created.I am facing this problem when I use tqdm for the second time.
![screenshot 2018-12-12 at 8 23 14 pm](https://user-images.githubusercontent.com/33565881/49877634-dab38300-fe4b-11e8-8969-f5bf7e3d8b56.png)
I think this is an issue.Pls fix this bug.

**Comment by colaboratory-team** [comment]
Can you provide a minimal notebook that reproduces the issue?

This updates a single-line progress-bar correctly:

```
import time
from tqdm import tqdm

text = ""
for c in tqdm(range(200)):
    text = text + str(c)
    time.sleep(0.1)
```

![tqdm](https://user-images.githubusercontent.com/38081706/50033385-1f0a6480-ffad-11e8-855e-acf8902e2466.png)

**Comment by avinsit123** [comment]
Have a look at this Notebook  https://colab.research.google.com/drive/1LFqsgY8vLYbdv7oXGH6NfAQEKNIypwz7 . I am basically training a Machine learning Model on pytorch and am tracking the tracking the training progress using a tqdm loader.Whilst running the training cell for the first time .The loader is working properly but when I run the same cell again.It gives an error like this..
![screenshot 2018-12-21 at 1 03 13 pm](https://user-images.githubusercontent.com/33565881/50330359-ea545b00-0520-11e9-82eb-29a053765c4f.png)

**Comment by avinsit123** [comment]
@colaboratory-team pls do have a look at this error as I think it is an important one and would be better if rectified.

**Comment by colaboratory-team** [comment]
I'd recommend following up with the tqdm maintainers. It will likely require some knowledge of the tqdm internals to make progress on a diagnosis.
