### ISSUE TITLE
Local runtime Docker: failed to register layer error

### ISSUE THREAD

**Issue by AlexWindels** [googlecolab/colabtools#3725]
**Describe the current behavior**
I want to set-up a local runtime using Colab's Docker runtime image. When running the command as proposed on https://research.google.com/colaboratory/local-runtimes.html, I get the following error: docker: failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/8a399d1c4792111fee2656e69887c0d7fe8612bfcec7880967811de1ca96c63d/merged: too many levels of symbolic links.
See 'docker run --help'.
See the full output below.

**Describe the expected behavior**
No URL is provided to make a local runtime connection. Any suggestions how this can be resolved? Thank you!

**What web browser you are using**
Browser: Chrome
Operating system: MacOS Monterey version 12.0.1
Docker desktop version: 4.19.0

**Additional context**
winde@w028h228 ~ % docker run -p 127.0.0.1:8888:8080 us-docker.pkg.dev/colab-images/public/runtime
Unable to find image 'us-docker.pkg.dev/colab-images/public/runtime:latest' locally
latest: Pulling from colab-images/public/runtime
b549f31133a9: Already exists 
a0bad51e1731: Already exists 
f7778ea3b9cc: Already exists 
e02ba321f215: Already exists 
a9e5e49da50d: Already exists 
16a53aaedebb: Already exists 
695fbd54ccca: Already exists 
84ba795f26c8: Already exists 
fa10ccbd03d9: Already exists 
990b1b09eecb: Already exists 
371c88923b61: Already exists 
3b22ea9420c8: Already exists 
5d63b1c47a0e: Already exists 
13ea6f674637: Already exists 
64a7d213b99a: Already exists 
5b00edc6c051: Already exists 
a32a0f491b5e: Already exists 
f4207bdce876: Already exists 
2711f3be44cd: Already exists 
d32a4ff2f1b2: Already exists 
b6ea2643beb1: Already exists 
a331dfad1bc0: Already exists 
f6ec29404d52: Already exists 
db907b90085c: Already exists 
825edf07363d: Already exists 
8f5bafd58697: Already exists 
7421ac674e52: Already exists 
e8f70bf3d02d: Already exists 
29ecb7bf5376: Already exists 
543730c60f44: Already exists 
f54d4c30dff6: Already exists 
00a6d8a20eea: Already exists 
2286ba7f02ca: Already exists 
171166aa353f: Already exists 
7d1423f9c744: Already exists 
daba697fc0df: Already exists 
fb7ed669e993: Already exists 
40254a456e29: Already exists 
d759eb54fa6b: Already exists 
0091de93618b: Extracting [==================================================>]  1.917MB/1.917MB
d4a9a2da6bba: Download complete 
26999f64a4ef: Download complete 
dfb75c93382a: Download complete 
10e784064869: Download complete 
4bc9624f1884: Download complete 
4ec7a9b735df: Download complete 
058b0ae05840: Download complete 
730c4a0a0d64: Download complete 
d84dbc4ce062: Download complete 
docker: failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/8a399d1c4792111fee2656e69887c0d7fe8612bfcec7880967811de1ca96c63d/merged: too many levels of symbolic links.
See 'docker run --help'.

**Comment by sebbov** [comment]
This is an issue with your docker setup when used with large images (and ours is very large, 24G).  https://github.com/docker/for-win/issues/5763 has suggestions you might want to give a try.
