### ISSUE TITLE
Pro+ user runtime silently terminated at the background (only live less than 3 hours)

### ISSUE THREAD

**Issue by yangrunhua** [googlecolab/colabtools#3727]
Pro+ user runtime silently terminated at the background (only live less than 3 hours).
I thought the agreement is at least 24 hours are allowed?

Each time I leave my program running for a couple of hours and walked away, it is initialized to a new runtime after I came back and activate the screen again.

**Comment by EvanWiederspan** [comment]
We'll need more information to follow up on this bug report. Please submit feedback within Colab at Help > Send feedback.
