### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed

### ISSUE THREAD

**Issue by npsnu777** [googlecolab/colabtools#3728]
from pytorch_lightning.utilities.distributed import rank_zero_only
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed'
2023-06-01 17:24:22,390 ERROR config.py(9897) - Failed to load model: No module named 'pytorch_lightning.utilities.distributed'

pls fix it, Thx

**Comment by EvanWiederspan** [comment]
It looks like the newest version of pytorch-lightning doesn't include that module. Pinning to an older version before importing worked for me:
`!pip install pytorch-lightning==1.7.7`
