### ISSUE TITLE
Cannot open any of my notebooks

### ISSUE THREAD

**Issue by andrei-papou** [googlecolab/colabtools#373]
Since today I cannot open any of my notebooks from google drive, neither can I create a new one.

This is what I see:
![colab](https://user-images.githubusercontent.com/13629004/50005314-05701980-ffbb-11e8-9c26-5e93a03e2b6a.png)

**Comment by andrei-papou** [comment]
Seems like request to `apidata.googleusercontent.com/download/drive/v2beta/files/` fails with the timeout error.

**Comment by colaboratory-team** [comment]
Sorry for the trouble. Does this reproduce in an incognito window with all extensions disabled?

**Comment by andrei-papou** [comment]
Yes, I can reproduce this in incognito mode.

**Comment by easybeinggreen** [comment]
Did this problem ever find any solution? I am stuck in the same situation Thanks
