### ISSUE TITLE
IOPub data rate exceeded.

### ISSUE THREAD

**Issue by poonjijain** [googlecolab/colabtools#3731]
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

**Comment by cperry-goog** [comment]
We'll need a minimal reproducible notebook to investigate.
