### ISSUE TITLE
TFQ is broken in Colab

### ISSUE THREAD

**Issue by liv4unix** [googlecolab/colabtools#3732]
**Describe the current behavior**

I can no longer run my TFQ Colab notebooks as TF 270 is no longer found in the installation index, and TFQ is not found in any of the newer Colab/TF implementations.

this command does not work:
!pip install tensorflow==2.7.0 tensorflow_quantum -q 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement tensorflow==2.7.0 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.13.0rc0, 2.13.0rc1)
ERROR: No matching distribution found for tensorflow==2.7.0

Nor do any other commands/version like it:
!pip install tensorflow==2.8.0 #tensorflow_quantum 
!pip install tensorflow-quantum==0.8.2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: tensorflow==2.8.0 in /usr/local/lib/python3.10/dist-packages (2.8.0)
ERROR: Could not find a version that satisfies the requirement tensorflow_quantum (from versions: none)
ERROR: No matching distribution found for tensorflow_quantum

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

I expect TFQ to be found in an installation index, if not 270 then another, more recent version, so that I can create my quantum gates and continue working with my quantum noise model.

**What web browser you are using**

I have tried both Chrome & FF, this issue just started recently.

**Additional context**
I have tried nightly builds --- they too choke trying to import TFQ with Module Not Found.  This is a serious problem. I am totally stuck and  I need help resolving this quickly as I need these visualizations to finish Chapter 4 of my PhD dissertation.

**Comment by liv4unix** [comment]
It looks like the version of python that colab uses was automatically upgraded to 3.10, which no longer supports TF 2.7.0.  If I roll back to to py 3.8 then my TFQ Colab/NB works.  But what is the plan for TFQ / py 3.10 support in Colab?  Is there an upgrade path? Thank you.

**Comment by liv4unix** [comment]
This issue is identical the TFQ issues stated in #60428 #768 #762 #757 #767
Moreover, my TFQ problems persist with: colab, localhost, docker, GCP, nightly_builds ---->>>  all are nonfuncitonal for TFQ

CRITICAL PERSONAL NOTE:
I am supposed to defend my PhD dissertation in 3 months and as of right now I cannot even finish the dissertation due to an inability to get TFQ to work.  This is a time-sensitive issue.

**Comment by cperry-goog** [comment]
You'll need to file a bug upstream with TFQ - we are just following their upgrades and don't have any control over the libraries. Sorry.
