### ISSUE TITLE
After the browser is closed, when it is running in the background, after a while, the program will run at a very low efficiency until I reconnect the browser

### ISSUE THREAD

**Issue by SHAOjav** [googlecolab/colabtools#3733]
**Describe the current behavior**
After the browser is closed, when it is running in the background, after a while, the program will run at a very low efficiency until I reconnect the browser

**Describe the expected behavior**
I want programs to keep running efficiently in the background

**What web browser you are using**
![Screenshot 2023-06-05 093200](https://github.com/googlecolab/colabtools/assets/18586382/a936a299-5227-4f09-a8ab-1052a68a543b)
Chrome, 

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
I don't have any good ideas as to why this might be happening - do you have a minimal reproducible notebook? Could also be that your reporting isn't reporting correctly while disconnected.
