### ISSUE TITLE
Crashing Colab

### ISSUE THREAD

**Issue by akshaytokopedia** [googlecolab/colabtools#3738]
**Describe the current behavior**
My instance is getting crashed again and again.
I have downgraded the colab Python version from 3.10.11 to 3.8.10. And after that, I installed the dependencies.
Which then required restarting of the kernel causing it to crash.

**Describe the expected behavior**
It should start properly

**What web browser you are using**
Chrome

**Additional context**
No.

**Comment by cperry-goog** [comment]
Downgrading Python is not supported, sorry.
