### ISSUE TITLE
 a conflict between TensorBoard and “tf.config.experimental_connect_to_cluster”

### ISSUE THREAD

**Issue by cobaltyang** [googlecolab/colabtools#3740]
**Describe the current behavior**
A I did not use the TensorBoard callback at first. Later, I added the TensorBoard callback to the training function as shown in this image: [error1](https://i.stack.imgur.com/CtTWj.png) .However, I encountered this error message [error2](https://i.stack.imgur.com/erHSs.png)  .Following suggestions from other posts online like this one [blog1](https://stackoverflow.com/questions/58815710/tensor-graph-is-meaningless-when-eager-execution-is-enabled)，I added

tf.compat.v1.disable_eager_execution()
But then I got this error message:[error3](https://i.stack.imgur.com/DnUr3.png)，Based on this error, I tried to enable eager execution mode with tf.compat.v1.enable_eager_execution() before tf.config.experimental_connect_to_cluster.But then I encountered this error: [error4](https://i.stack.imgur.com/TEri9.png).😭

Tensorflow version: 2.12.0,colab,keras

It seems like there might be a conflict between TensorBoard and “tf.config.experimental_connect_to_cluster”.Can somebody help me? Thank you very much.

(edge broswer)

**Comment by cperry-goog** [comment]
can you share a minimal reproducible notebook?

**Comment by cobaltyang** [comment]
ok! the notebook link is https://colab.research.google.com/drive/1B4gcCPxgdXfI6T_xGUQAijvTPkTNMC4Y?usp=sharing @cperry-goog 😺

**Comment by cperry-goog** [comment]
Looks like I need download permissions to open that file: https://support.google.com/docs/answer/2494893?authuser=0&hl=en#zippy=%2Cprevent-people-from-downloading-printing-or-copying-your-file
