### ISSUE TITLE
Wrong version

### ISSUE THREAD

**Issue by BurpMe** [googlecolab/colabtools#3743]
SO i keep getting wrong version package and honestly don't know what Package is not updated to fix this issue 

                
17:14:44-356911 INFO     Installing package: compel                             
17:14:58-833836 WARNING  Package wrong version: requests 2.27.1 required 2.30.0 
17:14:58-835425 INFO     Installing package: requests==2.30.0                   
17:15:03-275595 INFO     Installing package: accelerate==0.18.0                 
17:15:10-549567 INFO     Installing package: diffusers==0.16.1                  
17:15:14-777123 INFO     Installing package: einops==0.4.1                      
17:15:20-664215 INFO     Installing package: gradio==3.32.0                     
17:15:35-599523 WARNING  Package wrong version: numpy 1.24.3 required 1.23.5    
17:15:35-601103 INFO     Installing package: numpy==1.23.5                      
17:15:43-681239 WARNING  Package wrong version: numba 0.56.4 required 0.57.0    
17:15:43-683152 INFO     Installing package: numba==0.57.0                      
17:15:55-555242 INFO     Installing package: pytorch_lightning==1.9.4           
17:16:04-293185 INFO     Installing package: transformers==4.26.1               
17:16:15-579106 INFO     Installing package: timm==0.6.13                       
17:16:22-215424 INFO     Installing package: tomesd==0.1.2                      
17:16:27-220675 INFO     Installing packages                                    
17:16:27-221879 INFO     Installing package:                                    
                         git+https://github.com/openai/CLIP.git

**Comment by EvanWiederspan** [comment]
Can you share a notebook that shows the error you're seeing? I thought it might just be `!pip install git+https://github.com/openai/CLIP.git` but that succeeds for me in a new notebook

**Comment by BurpMe** [comment]
https://colab.research.google.com/drive/1_woE_Fu_pYhJj_udUuvYBsm1cHqxOo47

**Comment by cperry-goog** [comment]
can you open up view privileges?
