### ISSUE TITLE
ResourceExhaustedError for old project

### ISSUE THREAD

**Issue by fairy0127** [googlecolab/colabtools#3745]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

I have made a project in may and it run well last month, for I need to shap to explain photoes. But when I run it today, it raise error of ResourceExhaustedError, the code is the same, please help me!

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

I want my code run without error, just like before. Here is the code:

_#explain the right ones
import shap 
explainer = shap.DeepExplainer(model, (my_x_train[0: 50]))
right_shap_values_list = []
for i in range(len(right_test)):
  shap_values = explainer.shap_values(right_test[[i]])
  index_names = np.array([str(x) + "\n" + '{:>7.3%}'.format(right_prob[i][x]) for x in range(5)]).reshape(1,5)
  print("Predicted label :{}\nTrue label :{}".format(right_prob[i],0))
  right_shap_values_list.append(shap_values)
  image_plot(shap_values, right_test[[i]], index_names, show = False)
  plt.show()_

And here is the error message:
_keras is no longer supported, please use tf.keras instead.
Your TensorFlow version is newer than 2.4.0 and so graph support has been removed in eager mode and some static graphs may not be supported. See PR #1483 for discussion.
`tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
[<ipython-input-21-e184c1303aa0>](https://localhost:8080/#) in <cell line: 5>()
      4 right_shap_values_list = []
      5 for i in range(len(right_test)):
----> 6   shap_values = explainer.shap_values(right_test[[i]])
      7   index_names = np.array([str(x) + "\n" + '{:>7.3%}'.format(right_prob[i][x]) for x in range(5)]).reshape(1,5)
      8   print("Predicted label :{}\nTrue label :{}".format(right_prob[i],0))_

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
We upgraded TensorFlow which looks like it caused this - you'll need to update your code per the error instructions. Sorry.

**Comment by fairy0127** [comment]
Hi Googlecolab/Colabtools,
Would you please check it again, I still got the ResourceExhaustedError,
would you please stop upgrading the product? Or let the customer to choose
the version? I want a stable environment. I am so frustrated.
Thank you so much!
Have a nice day!
Shelly
