### ISSUE TITLE
Please make a value for this

### ISSUE THREAD

**Issue by pika14pika** [googlecolab/colabtools#3746]
I tried to test its limits but it said: the IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.
Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

I copy and pasted the Current values but it said Notebook.App had no  value please fix this

It was supposed to have a value
I was using Chrome

the link to the GitHub gist: https://colab.research.google.com/gist/pika14pika/f34b5a661862fe6569f7f62f65245e2c/untitled3.ipynb

**### PLEASE FIX THIS I WANT TO TEST ITS LIMITS**

**Comment by EvanWiederspan** [comment]
You're trying to display a string with 10 million characters, that's generally too big for a Jupyter notebook. I would recommend only printing the first 100 or so characters, with `print(passwords[:100])`

**Comment by pika14pika** [comment]
> You're trying to display a string with 10 million characters, that's generally too big for a Jupyter notebook. I would recommend only printing the first 100 or so characters, with `print(passwords[:100])`

I tried 1 million and it worked
