### ISSUE TITLE
Colab Crash

### ISSUE THREAD

**Issue by Zafar577** [googlecolab/colabtools#3748]
**Describe the current behavior**
When I run my model, it crashes after excuting for 45- 55 seconds and display a message that you have used all the resources. However, I just open my colab. 

**Describe the expected behavior**
A smooth run without any crash.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Microsoft Edge

**Comment by cperry-goog** [comment]
I can't diagnose these issues from GitHub, you'll need to submit feedback in product.
