### ISSUE TITLE
Colab always become busy and then you’ll be disconnected

### ISSUE THREAD

**Issue by aorems20** [googlecolab/colabtools#3749]
https://github.com/googlecolab/colabtools/wiki/Bug-Reports
--> Busy runtime issue

**Describe the current behavior**
It progress smoothly then if the train reaches the middle part (20,000/40,000 steps) it will become busy and disconnects.

**Describe the expected behavior**
It should finish the training without problem because we are not even idle, we always interact things on colab (creating and deleting cells).

**What web browser you are using**
(Chrome)

**Additional context**
we already purchased about 3x 9.99 pay to go compute units and 1 monthly 9.99), I hope this bug will be solved soon because it only consume compute units. We uses premium A100 GPU and HIGH RAM usage.

**Comment by cperry-goog** [comment]
Again, please be civil.

I can't diagnose this issue from GitHub, please file feedback in product and reference this.

**Comment by AntonOfTheWoods** [comment]
@cperry-goog , this is not very well designed UX IMHO. "Feedback" isn't typically what I would expect to give when requesting support for a paid product. A "bug" seems more natural, and the "bug" button in Colab brings you to the GH issues.
