### ISSUE TITLE
Incompatibility with iPad 9.7” 2018 (both in mobile view and desktop view)

### ISSUE THREAD

**Issue by shyamalschandra** [googlecolab/colabtools#375]
Do you know what is causing the problem?  I am unable to execute the options with a Seedbank example using DCGAN.  Do you know what could be happening?  Thanks!

Link to example being used: 
https://research.google.com/seedbank/seed/5652786310021120

Thank you for colab!

**Comment by colaboratory-team** [comment]
What is the error that you observe?

**Comment by shyamalschandra** [comment]
Did you try to replicate the results on an iPad?

**Comment by blois** [comment]
The seed linked to is no longer available.

**Comment by shyamalschandra** [comment]
Here it is: https://research.google.com/seedbank/seed/dcgan_with_tfkeras_and_eager

**Comment by shyamalschandra** [comment]
Any takers?

**Comment by shyamalschandra** [comment]
@blois: Anyone get this to work?

**Comment by blois** [comment]
I was able to execute this on both iPhone and an iPad (iOS 12).

**Comment by shyamalschandra** [comment]
@blois: Do you have a video screenshare (a feature in iOS) of the Seedback colab notebook working on both devices, iPad and iPhone?

**Comment by blois** [comment]
@shyamalschandra perhaps a video of what is not working? An explanation of what we should be looking for when it does not work would also be helpful.

**Comment by shyamalschandra** [comment]
I'll get back to you about this when I have time.

**Comment by shyamalschandra** [comment]
Okay, it works now and I can track (due to a UI enhancement showing the RAM and Disk being used) if the process is done.
However, would it be possible to make a iPad or iPhone CSS version ( http://stephen.io/mediaqueries/#iPad ).  I would be happy to help out because many times, users would like to execute the commands inside the colabtools inside safari in an iPad or iPhone connected to an Apple TV via AirPlay 2.  This would be great for demostrations.  This would fall under feature suggestions. @blois

**Comment by shyamalschandra** [comment]
One more comment, please check this out in relation to the previous comment.
https://blisk.io/devices

**Comment by shyamalschandra** [comment]
Please check this out too. @cperry-goog 
https://css-tricks.com/snippets/css/media-queries-for-standard-devices/
