### ISSUE TITLE
 ipywidgets datepicker value not working

### ISSUE THREAD

**Issue by Amnesiac9** [googlecolab/colabtools#3751]
**Describe the current behavior**
I'm attempting to get user input by displaying a date picker and having the user select a date, I then want to pull that date as a value from the widget and use it in the rest of the program. However, this doesn't work and the date the user selects never gets assigned to the value.

**Describe the expected behavior**
When a date picker is displayed, it should accept user changes to the date and update the value of the date picker.

**What web browser you are using**
Firefox

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
https://colab.research.google.com/drive/1zGryIBLwMzXOO5BCUBL70v-QS43MaWKk?usp=sharing

**Comment by ragman-google** [comment]
Tracked internally as b/286407122.

**Comment by J-Rojas** [comment]
The values are updated if you perform the query in a follow cell, not in the same cell. The widget cannot immediately communicate to the Python session synchronously, so there must be some background processing time allotted for syncing which occurs after a cell is run.

**Comment by Amnesiac9** [comment]
It still does not work in a secondary cell unfortunately. How much time is needed? What is the usefulness of the date picker if the values cannot update at the time the user picks them? 

Update with values assigned in a separate cell: https://colab.research.google.com/drive/1zGryIBLwMzXOO5BCUBL70v-QS43MaWKk?usp=sharing#scrollTo=B-57MHR44qvS

**Comment by Amnesiac9** [comment]
It seems to only update the values after the complete program has run.
