### ISSUE TITLE
Cannot sign in to Colab

### ISSUE THREAD

**Issue by jphayward** [googlecolab/colabtools#3756]
Hello, I have two gmail accounts and cannot sign in to Google Colab using either one.
The "Sign In" button stays, and clicking it does not bring up a signin tab.

I have tried signing in using my regular gmail account as well as my Colab-specific account (which I created just for Colab, and through which I used to have a Colab pro subscription). Both accounts are fine for email, but Colab is basically frozen.

Have tried using both Chrome and Safari, both signed in and in Guest mode. No change.

Thanks for any help.

**Comment by sagprr** [comment]
I am also facing the same issue with colab on chrome.

**Comment by EvanWiederspan** [comment]
Thanks for the report, we're aware of the issue and are rolling out a fix now. We believe this to mostly be a UI-only issue, and that connecting to runtimes and executing code should still work for most users

**Comment by viditagr** [comment]
Hi @EvanWiederspan! I also wanted to point out another added thing to this problem. I was on colab pro and was able to run two sessions consecutively but after this UI problem where it shows the sign-in button on the top right of the window instead of the Google account, I am not able to run two sessions consecutively at once. Is there any troubleshooting I can do on my end to fix that? 
Thank you so much for your help!

**Comment by NewFall2021** [comment]
Same

literally as i did 5 minutes of anything it just resets

**Comment by gouthamk16** [comment]
Same here. Can't sign in

**Comment by ProTechZ** [comment]
Has this been fixed yet? Because I can't sign in either.

**Comment by hussamgn75** [comment]
same here

**Comment by WpythonW** [comment]
The same problem

**Comment by eskaviam** [comment]
same problem here

**Comment by grizzlednerd** [comment]
Bump

**Comment by chris-lorenz** [comment]
I was wondering if I'm alone with this problem but doesn't seem to be the case.

**Comment by 108mk** [comment]
seems a worldwide problem (?)

**Comment by poorni666** [comment]
same problem

**Comment by rigolitch** [comment]
Same here, they know the problem since 24 hours, the fix was rolled out 17 hours ago but still nothing is fixed.
ONCE AGAIN.

**Comment by tugberkute** [comment]
same...

**Comment by hopdebee** [comment]
bump. There seem to be related issues with storing files to the connected google drive ?

**Comment by CyberNinja600** [comment]
I found a bypass, if you are logged in, just changed the authuser=1,2,3

**Comment by LazerCuber** [comment]
Bug still exist lol

**Comment by egorserdyuk** [comment]
same, again

**Comment by Aniket-76** [comment]
same

**Comment by parrisatwork** [comment]
Noting that I too am having the same issue. Tried Edge and Chrome.

**Comment by danghoangphuong** [comment]
24 hours and this problem still exist

**Comment by sb-gravity100** [comment]
i thought i was the only one. hope this gets fixed

**Comment by cperry-goog** [comment]
Sorry about this - a fix will be live today in the next few hours. We'll update this bug when it's live.

**Comment by waleed76** [comment]
same here cant login

**Comment by cperry-goog** [comment]
The fix is live in prod. I'll keep this open for a little bit longer just in case, do let me know if you're still seeing the issue.

**Comment by cperry-goog** [comment]
Thanks for confirming!
