### ISSUE TITLE
Output File Name is wrong

### ISSUE THREAD

**Issue by Bharathkumar-Tamilarasu** [googlecolab/colabtools#3758]
Issue:
-> Using to_csv command I tried to save a dataframe in a csv format
-> Please find the code & image below
drive_path = '/content/drive/MyDrive/Colab Notebooks/Alma/Python'
df.to_csv(drive_path + 'py_output.csv')

![image](https://github.com/googlecolab/colabtools/assets/136069598/0363144d-0dc2-4c88-81d2-62964a97ae69)

-> I gave the output file name as 'py_output.csv'. But the file which saved in the location named as 'Pythonpy_output.csv'

![image](https://github.com/googlecolab/colabtools/assets/136069598/dd301167-bca8-4094-ab5a-28bb6d0a9964)

**Comment by EvanWiederspan** [comment]
You need to add another slash at the end of `drive_path`, since you're just appending the strings together you get "..../Alma/Pythonpy_output.xlsx"
