### ISSUE TITLE
I can't login in my account

### ISSUE THREAD

**Issue by IsaacMirandaCamargos** [googlecolab/colabtools#3759]
**Describe the current behavior**
When I click in sign in button it just return to the same screen that I am already.

**Describe the expected behavior**
Normally I believe that I should connect in my account.

**What web browser you are using**
Chrome and Opera

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
A fix is rolling out today in a few hours. We'll update #3756 when it's live.

**Comment by IsaacMirandaCamargos** [comment]
Thanks
