### ISSUE TITLE
Bug with the Browser : Ram and Cpu freak out

### ISSUE THREAD

**Issue by mouadriyad** [googlecolab/colabtools#376]
![screenshot from 2018-12-16 19-26-11](https://user-images.githubusercontent.com/25394225/50057603-c8478b00-0164-11e9-912a-0246be7141b6.png)
there is a bug concerning the browser:

First I somehow lost my connection then I reconnected.
The problem is that after the reconnection, It starts allocating so much RAM and CPU until the PC crush (if he doesn't find much memory) or It disconnect by himself and free the memory. It recommence when I try to reconnect or refresh the page.

I found this [https://stackoverflow.com/questions/52667987/google-colab-not-enough-memory-to-open-this-page](url)

As Attached file a screenshot

**Comment by colaboratory-team** [comment]
Can you share a notebook that reproduces the problem?

**Comment by mouadriyad** [comment]
It freaks out when the output of a cell contains a huge number of the lines.

ex: I train 20 model with 600 epochs in the same cell which lead to 12000 lines of the verbose.

I resolve the problem by using : 

`from IPython.display import clear_output
`

**Comment by tmac1997** [comment]
> `from IPython.display import clear_output `

I'm troubled by this problem for days! Thank you so much for finding the cause.
