### ISSUE TITLE
'tuple' object has no attribute 'float'

### ISSUE THREAD

**Issue by sallll** [googlecolab/colabtools#3762]
**Describe the current behavior**
I used to run the quantum deep learning code, but now it gives this error. i didnt change any single line in the code it is the same 

**Describe the expected behavior**
the code should output the training and testing result of in total 7000 images in the format .png and .jpg 

**What web browser you are using**
Chrome

**Comment by EvanWiederspan** [comment]
Can you share the notebook, including the whole error you're seeing and the line that it came from?
