### ISSUE TITLE
Copy and pasting markdown cells removes trailing spaces, eliminating line breaks

### ISSUE THREAD

**Issue by bingbong-sempai** [googlecolab/colabtools#3766]
**Describe the current behavior**
I recently noticed markdown formatting breaking in my recent notebooks.  
Trailing spaces were trimmed which removed line breaks.  
This happens when the notebook is saved and reopened.  
I can also recreate the issue by copy and pasting a markdown cell with double space line breaks.   
The new cell will have trailing spaces removed, removing the line breaks.  

**Describe the expected behavior**
Pasted cells should be identical to the original.  

**What web browser you are using**
Firefox and edge.  

**Additional context**
https://colab.research.google.com/gist/bingbong-sempai/86adb536987d7d37c9ff606f5bdf0b8d/markdown-bug.ipynb  
The spaces were lost when the notebook was copied to gist.

**Comment by EvanWiederspan** [comment]
Thanks for the report, we do intentionally trim whitespace on save, but in this case it looks like we're removing whitespace that's needed for formatting. Tracking internally in b/155917402

**Comment by bingbong-sempai** [comment]
Thanks! I use cut and paste to reposition markdown cells in my notebooks and it's a bit annoying to have to redo formatting each time.

**Comment by EvanWiederspan** [comment]
This should now be fixed, thanks for the report
