### ISSUE TITLE
Microsoft Edge Driver Failed to start

### ISSUE THREAD

**Issue by Alex4024** [googlecolab/colabtools#3767]
**I tried Automating microsoft edge in google colab using edge driver but it still give me followig error**
WebDriverException: Message: unknown error: Microsoft Edge failed to start: exited abnormally.

**Describe the expected behavior**

         import os
         from seleniumbase import BaseCase
         from selenium import webdriver
         from selenium.webdriver.common.keys import Keys
         from selenium.webdriver.common.by import By
         from selenium.webdriver.support.ui import WebDriverWait
         from selenium.webdriver.support import expected_conditions as EC
         class MyTestCase(BaseCase):
                def test_login_and_search(self):
                # Prompt the user for Microsoft Edge browser sign-in credentials
                      username = input("Enter your username: ")
                      password = input("Enter your password: ")

        # Set the path to the Microsoft Edge WebDriver executable directory
                      webdriver_directory = "/usr/local/bin/"  # Replace with the actual directory

        # Add the WebDriver directory to the PATH environment variable
                      os.environ["PATH"] += os.pathsep + webdriver_directory

        # Create a new instance of the Microsoft Edge driver
                      self.driver = webdriver.Edge()

        # Maximize the browser window (optional)
                     self.driver.maximize_window()

        # Navigate to the Microsoft sign-in page
                    self.open("https://login.live.com/")

        # Wait until the username field is visible and enter the username
                   self.wait_for_element_visible("name:loginfmt")
                   self.type("name:loginfmt", username)
                   self.press_key("name:loginfmt", Keys.RETURN)

        # Wait until the password field is visible and enter the password
                   self.wait_for_element_visible("name:passwd")
                   self.type("name:passwd", password)
                   self.press_key("name:passwd", Keys.RETURN)

        # Wait until the search box is visible and enter the search query
                  self.wait_for_element_visible("name:q")
                  self.type("name:q", "hello")
                  self.press_key("name:q", Keys.RETURN)

        # Close the browser
                 self.driver.quit()

       # Run the test case
       MyTestCase().test_login_and_search()

**What web browser you are using**
Chrome

**Additional context**
Error :
WebDriverException                        Traceback (most recent call last)
<ipython-input-20-d08ea119a1a6> in <cell line: 50>()
     48 
     49 # Run the test case
---> 50 MyTestCase().test_login_and_search()

6 frames
/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py in check_response(self, response)
    243                 alert_text = value["alert"].get("text")
    244             raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
--> 245         raise exception_class(message, screen, stacktrace)

WebDriverException: Message: unknown error: Microsoft Edge failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from msedge location /usr/bin/microsoft-edge is no longer running, so msedgedriver is assuming that msedge has crashed.)
Stacktrace:
#0 0x55d5068cb013 <unknown>
#1 0x55d5065d78c1 <unknown>
#2 0x55d506603cdf <unknown>
#3 0x55d5065ff1ed <unknown>
#4 0x55d50663fea5 <unknown>
#5 0x55d506637043 <unknown>
#6 0x55d50660a941 <unknown>
#7 0x55d50660bb5e <unknown>
#8 0x55d5068975b6 <unknown>
#9 0x55d50689b0c9 <unknown>
#10 0x55d50689abb9 <unknown>
#11 0x55d50689b585 <unknown>
#12 0x55d5068a2a5b <unknown>
#13 0x55d50689b92e <unknown>
#14 0x55d50687520c <unknown>
#15 0x55d5068b6d88 <unknown>
#16 0x55d5068b6ec4 <unknown>
#17 0x55d5068c47e6 <unknown>
#18 0x7fb58a2e4609 start_thread

NOTE :  I have used same latest version of edgedriver and same latest version microsoft edge browser and the path is also correct and the selenium version is also latest But I'm still getting Error. This code is running on my local machine , but It's not running on Google Colab.

**Comment by Alex4024** [comment]
[> Could you share the whole notebook you are using? When I run just that snippet, I see an "cannot find msedge binary" error, and I'm assuming you had code to install that](https://colab.research.google.com/drive/1svimGMvBEBxhtZ3UZ6OumXxa63O2RV4x?usp=sharing)

**Comment by cperry-goog** [comment]
There's no record of edgedrivermanager in pypy.org that I can find - I'm guessing you have the wrong package name.

**Comment by Alex4024** [comment]
Can you guide me what should I do then? Because I'm new to this automation.

**Comment by goldeneave** [comment]
> Can you guide me what should I do then? Because I'm new to this automation.

Found your post on the same issue. Have you resolved it? If so, could you share your solution or workaround?
Thanks,
