### ISSUE TITLE
Colab says it's running but it's not. it's only wasting my available compute time. FOR NOTHING.

### ISSUE THREAD

**Issue by ghost** [googlecolab/colabtools#3770]
Colab says it's running in the overall ressources widget and showing the "busy" text. The "process" cell of my notebook has its icon turning, but the cell is not executed. No other cell are executed. Nothing works. 

So, once again, I can't use Colab... The 4th time in 2 weeks ! What a reliable service !

**Comment by vijendra56** [comment]
colab says the cell are running but cell is not executed in colab notebook

**Comment by EvanWiederspan** [comment]
vijendra56, could you file a new issue instead and include a link to the notebook you are running and the cell which is not executing?
