### ISSUE TITLE
'tuple' object is not callable for no reason

### ISSUE THREAD

**Issue by JeongWonJu** [googlecolab/colabtools#3771]
I tried the following on Chrome Version 114.0.5735.133 (64bit):

import numpy as np
import pandas as pd
ar=np.array([[288,378],[10,7],[61,62]])
x=pd.DataFrame(ar,['know','dont','never'],['m','f'])

and it should make the result 

	m	f
know	288	378
dont	10	7
never	61	62
( I tried on Jupyter Notebook and succeeded.).

However, Colab gave me 

TypeError                                 Traceback (most recent call last)
[<ipython-input-166-21fcd92fd534>](https://localhost:8080/#) in <cell line: 4>()
      2 import pandas as pd
      3 ar=np.array([[288,378],[10,7],[61,62]])
----> 4 x=pd.DataFrame(ar,['know','dont','never'],['m','f'])

TypeError: 'tuple' object is not callable

although there are no typos on parentheses nor commas.

**Comment by EvanWiederspan** [comment]
That snippet worked fine for me; notebooks maintain state between cells, so I suspect that you ran other code that re-assigned some variable that is causing the error. Does it still fail for you if you `Runtime -> Restart Runtime` before running it?
