### ISSUE TITLE
Job crashed after 7 hours and 58 minutes!!

### ISSUE THREAD

**Issue by RobinGanesan** [googlecolab/colabtools#3772]
**Describe the current behavior**
Crashed for no reason!  The job was running fine for 7 hours and 58 minutes on a high RAM runtime.  It was about 45 minutes from completion.  This happens CONSTANTLY.  I have PLENTY of compute units. Bad job, Colab!
**Describe the expected behavior**
Should not crash!!
**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome

**Additional context**

https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by RobinGanesan** [comment]
![crash](https://github.com/googlecolab/colabtools/assets/108406782/b35478b3-4dd0-466a-a4a3-5d09d56e351e)

**Comment by EvanWiederspan** [comment]
This seems like your machine likely ran out of memory, which we can't diagnose from Github. Please file in-product feedback at Help -> Send Feedback
