### ISSUE TITLE
Selected GPU not Loading into the Runtime

### ISSUE THREAD

**Issue by Tallis161** [googlecolab/colabtools#3776]
Just that basically. Using Chrome, Windows 11. It won't open the A100 or V100.

**Comment by GemsFord** [comment]
Same here

**Comment by aegonwolf** [comment]
I've been experiencing this with a couple of other issues too, I think a lot of issues since the past 4 weeks that are similar.
It says A100 but actually it loads the V100 and I also can't disconnect.

**Comment by mosmos6** [comment]
I'm trying to connect to TPU on both High-RAM and standard with pro subscription but seeing this message from this morning. I think it shares the same issue. 
<Failed to assign a backend
No backend with TPU available. Would you like to use a runtime with no accelerator?>
It was totally fine until 24 hours ago.

**Comment by sebbov** [comment]
> I'm trying to connect to TPU on both High-RAM and standard with pro subscription but seeing this message from this morning. I think it shares the same issue. <Failed to assign a backend No backend with TPU available. Would you like to use a runtime with no accelerator?> It was totally fine until 24 hours ago.

Thanks for the report.  TPUs have been unusually unavailable since yesterday.   This is a separate issue and expected to be resolved in the next ~6 hours.

**Comment by mosmos6** [comment]
@sebbov 
It's back on now. Thank you.

**Comment by mayankmalik-colab** [comment]
@Tallis161 - Can you elaborate what do you mean by  "GPU not Loading into the Runtime" .  What do you get when you run `!nvidia-smi` ?

**Comment by cperry-goog** [comment]
We will fall back to an available accelerator if we stock out of a premium accelerator - I can't diagnose much more than that with this information.
