### ISSUE TITLE
Upgrade to Ubuntu 22.04

### ISSUE THREAD

**Issue by metrizable** [googlecolab/colabtools#3778]
### Upgrade to Ubuntu 22.04

The Colab runtime has been upgraded to Ubuntu 22.04 LTS (Jammy Jellyfish), the most-recent [Ubuntu LTS version](https://discourse.ubuntu.com/t/jammy-jellyfish-release-notes/24668). This upgrade includes a refreshed toolchain to `glibc 2.35` and `gcc 11.3.0`, and other version bumps such as `cmake 3.22.1`, `ffmpeg 4.4.2`, `gdal 3.4.3`, and `libboost 1.74.0`. It also brings the Colab runtime into alignment with the cadence of [Ubuntu LTS releases](https://ubuntu.com/about/release-cycle).

#### Colab’s fallback runtime version

Using the fallback runtime version temporarily allows access to the last version of the runtime before the upgrade described above, and is available until early August. Its purpose is to provide a temporary mechanism for users to more smoothly upgrade their notebooks to be compatible with Colab’s current runtime version. This will be available from the Command Palette via the "Use fallback runtime version" command when connected to a runtime. Of note, this setting does not persist across sessions – the command will need to be invoked on each new session.

**Comment by mosmos6** [comment]
I haven't been able to connect to any runtime at least since about 1 hour ago. Is it because of this? (I purchased additional computing units by mistake..)
