### ISSUE TITLE
DataFrame Display in my Google Colab is not good, it is something different

### ISSUE THREAD

**Issue by swathimys87** [googlecolab/colabtools#3779]
**Describe the current behavior**
The display of dataframe in my google colab notebook is not correct. It gets displayed like a very old HTML table with a double line border.

**Describe the expected behavior**
I am expecting that the dataframe display must be normal like how it gets displayed for anyone else.

**What web browser you are using**
Chrome

**Additional context**
![DataFrame Display Issues](https://github.com/googlecolab/colabtools/assets/137212293/98e1fcc8-69f8-440f-a14e-bb84c8bdbd7d)

**Comment by EvanWiederspan** [comment]
Can you share the notebook that created this dataframe?

**Comment by EvanWiederspan** [comment]
Also curious if this still happens in incognito mode, with all extensions disabled?

**Comment by cperry-goog** [comment]
click on the magic wand icon.
