### ISSUE TITLE
Always gets stuck at "Setting Seed"

### ISSUE THREAD

**Issue by DilucObssessed** [googlecolab/colabtools#3782]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
Everytime I try to use ColabKobold GPU, it always gets stuck, or freezes at "Setting Seed"
**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
It's supposed to get past that and then at the end create a link.
**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Bing/chrome
**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by DilucObssessed** [comment]
pls help me, i wanna use janitor ai  😭

**Comment by mayankmalik-colab** [comment]
Can you share a notebook that reproduces this issue?

**Comment by caii10** [comment]
me too
