### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Sairoxs123** [googlecolab/colabtools#3786]
[WARNING]: ERROR: /content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 failed!

# Command failed: ['/usr/bin/python3', '-m', 'pythonforandroid.toolchain', 'create', '--dist_name=mycalculator', '--bootstrap=sdl2', '--requirements=python3,kivy', '--arch=arm64-v8a', '--arch=armeabi-v7a', '--copy-libs', '--color=always', '--storage-dir=/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a', '--ndk-api=21', '--ignore-setup-py', '--debug']
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     NV_LIBCUBLAS_VERSION = '11.11.3.6-1'
#     NVIDIA_VISIBLE_DEVICES = 'all'
#     COLAB_JUPYTER_TRANSPORT = 'ipc'
#     NV_NVML_DEV_VERSION = '11.8.86-1'
#     NV_CUDNN_PACKAGE_NAME = 'libcudnn8'
#     CGROUP_MEMORY_EVENTS = '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events'
#     NV_LIBNCCL_DEV_PACKAGE = 'libnccl-dev=2.16.2-1+cuda11.8'
#     NV_LIBNCCL_DEV_PACKAGE_VERSION = '2.16.2-1'
#     VM_GCE_METADATA_HOST = '169.254.169.253'
#     HOSTNAME = 'ec79b4c9a68e'
#     TBE_RUNTIME_ADDR = '172.28.0.1:8011'
#     GCE_METADATA_TIMEOUT = '3'
#     NVIDIA_REQUIRE_CUDA = ('cuda>=11.8 brand=tesla,driver>=450,driver<451 '
 'brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 '
 'brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 '
 'brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 '
 'brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 '
 'brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 '
 'brand=tesla,driver>=510,driver<511 brand=unknown,driver>=510,driver<511 '
 'brand=nvidia,driver>=510,driver<511 brand=nvidiartx,driver>=510,driver<511 '
 'brand=geforce,driver>=510,driver<511 brand=geforcertx,driver>=510,driver<511 '
 'brand=quadro,driver>=510,driver<511 brand=quadrortx,driver>=510,driver<511 '
 'brand=titan,driver>=510,driver<511 brand=titanrtx,driver>=510,driver<511 '
 'brand=tesla,driver>=515,driver<516 brand=unknown,driver>=515,driver<516 '
 'brand=nvidia,driver>=515,driver<516 brand=nvidiartx,driver>=515,driver<516 '
 'brand=geforce,driver>=515,driver<516 brand=geforcertx,driver>=515,driver<516 '
 'brand=quadro,driver>=515,driver<516 brand=quadrortx,driver>=515,driver<516 '
 'brand=titan,driver>=515,driver<516 brand=titanrtx,driver>=515,driver<516')
#     NV_LIBCUBLAS_DEV_PACKAGE = 'libcublas-dev-11-8=11.11.3.6-1'
#     NV_NVTX_VERSION = '11.8.86-1'
#     COLAB_JUPYTER_IP = '172.28.0.12'
#     NV_CUDA_CUDART_DEV_VERSION = '11.8.89-1'
#     NV_LIBCUSPARSE_VERSION = '11.7.5.86-1'
#     COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL = 'http://172.28.0.1:8013/'
#     NV_LIBNPP_VERSION = '11.8.0.86-1'
#     NCCL_VERSION = '2.16.2-1'
#     KMP_LISTEN_PORT = '6000'
#     TF_FORCE_GPU_ALLOW_GROWTH = 'true'
#     ENV = '/root/.bashrc'
#     PWD = '/content'
#     COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT = '30s'
#     TBE_EPHEM_CREDS_ADDR = '172.28.0.1:8009'
#     TBE_CREDS_ADDR = '172.28.0.1:8008'
#     NV_CUDNN_PACKAGE = 'libcudnn8=8.9.0.131-1+cuda11.8'
#     NVIDIA_DRIVER_CAPABILITIES = 'compute,utility'
#     COLAB_JUPYTER_TOKEN = ''
#     LAST_FORCED_REBUILD = '20230608'
#     NV_NVPROF_DEV_PACKAGE = 'cuda-nvprof-11-8=11.8.87-1'
#     NV_LIBNPP_PACKAGE = 'libnpp-11-8=11.8.0.86-1'
#     NV_LIBNCCL_DEV_PACKAGE_NAME = 'libnccl-dev'
#     TCLLIBPATH = '/usr/share/tcltk/tcllib1.20'
#     NV_LIBCUBLAS_DEV_VERSION = '11.11.3.6-1'
#     COLAB_KERNEL_MANAGER_PROXY_HOST = '172.28.0.12'
#     NVIDIA_PRODUCT_NAME = 'CUDA'
#     NV_LIBCUBLAS_DEV_PACKAGE_NAME = 'libcublas-dev-11-8'
#     USE_AUTH_EPHEM = '1'
#     NV_CUDA_CUDART_VERSION = '11.8.89-1'
#     HOME = '/root'
#     LANG = 'en_US.UTF-8'
#     CUDA_VERSION = '11.8.0'
#     CLOUDSDK_CONFIG = '/content/.config'
#     NV_LIBCUBLAS_PACKAGE = 'libcublas-11-8=11.11.3.6-1'
#     NV_CUDA_NSIGHT_COMPUTE_DEV_PACKAGE = 'cuda-nsight-compute-11-8=11.8.0-1'
#     COLAB_RELEASE_TAG = 'release-colab-20230621-060108-RC02'
#     PYDEVD_USE_FRAME_EVAL = 'NO'
#     KMP_TARGET_PORT = '9000'
#     CLICOLOR = '1'
#     KMP_EXTRA_ARGS = ('--logtostderr --listen_host=172.28.0.12 --target_host=172.28.0.12 '
 '--tunnel_background_save_url=https://colab.research.google.com/tun/m/cc48301118ce562b961b3c22d803539adc1e0c19/m-s-2jpw34pb1y02s '
 '--tunnel_background_save_delay=10s '
 '--tunnel_periodic_background_save_frequency=30m0s '
 '--enable_output_coalescing=true --output_coalescing_required=true')
#     NV_LIBNPP_DEV_PACKAGE = 'libnpp-dev-11-8=11.8.0.86-1'
#     NV_LIBCUBLAS_PACKAGE_NAME = 'libcublas-11-8'
#     COLAB_KERNEL_MANAGER_PROXY_PORT = '6000'
#     CLOUDSDK_PYTHON = 'python3'
#     NV_LIBNPP_DEV_VERSION = '11.8.0.86-1'
#     ENABLE_DIRECTORYPREFETCHER = '1'
#     NO_GCE_CHECK = 'False'
#     JPY_PARENT_PID = '82'
#     PYTHONPATH = '/env/python'
#     TERM = 'xterm-color'
#     NV_LIBCUSPARSE_DEV_VERSION = '11.7.5.86-1'
#     GIT_PAGER = 'cat'
#     LIBRARY_PATH = '/usr/local/cuda/lib64/stubs'
#     NV_CUDNN_VERSION = '8.9.0.131'
#     SHLVL = '0'
#     PAGER = 'cat'
#     COLAB_LANGUAGE_SERVER_PROXY = '/usr/colab/bin/language_service'
#     NV_CUDA_LIB_VERSION = '11.8.0-1'
#     NVARCH = 'x86_64'
#     NV_CUDNN_PACKAGE_DEV = 'libcudnn8-dev=8.9.0.131-1+cuda11.8'
#     NV_CUDA_COMPAT_PACKAGE = 'cuda-compat-11-8'
#     MPLBACKEND = 'module://ipykernel.pylab.backend_inline'
#     NV_LIBNCCL_PACKAGE = 'libnccl2=2.16.2-1+cuda11.8'
#     LD_LIBRARY_PATH = '/usr/local/nvidia/lib:/usr/local/nvidia/lib64'
#     COLAB_GPU = ''
#     GCS_READ_CACHE_BLOCK_SIZE_MB = '16'
#     NV_CUDA_NSIGHT_COMPUTE_VERSION = '11.8.0-1'
#     NV_NVPROF_VERSION = '11.8.87-1'
#     COLAB_FILE_HANDLER_ADDR = 'localhost:3453'
#     PATH = '/root/.buildozer/android/platform/apache-ant-1.9.4/bin:/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-sdk/bin'
#     NV_LIBNCCL_PACKAGE_NAME = 'libnccl2'
#     COLAB_DEBUG_ADAPTER_MUX_PATH = '/usr/local/bin/dap_multiplexer'
#     NV_LIBNCCL_PACKAGE_VERSION = '2.16.2-1'
#     PYTHONWARNINGS = 'ignore:::pip._internal.cli.base_command'
#     DEBIAN_FRONTEND = 'noninteractive'
#     COLAB_BACKEND_VERSION = 'next'
#     OLDPWD = '/'
#     _ = '/usr/local/bin/buildozer'
#     PACKAGES_PATH = '/root/.buildozer/android/packages'
#     ANDROIDSDK = '/root/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/root/.buildozer/android/platform/android-ndk-r25b'
#     ANDROIDAPI = '31'
#     ANDROIDMINAPI = '21'

**Comment by cperry-goog** [comment]
we need a reproducible notebook
