### ISSUE TITLE
82 popups "are you still here" in 27 minutes

### ISSUE THREAD

**Issue by ghost** [googlecolab/colabtools#3788]
This is insane. I though Google Devs know what they are doing, but it seems not.
Seeing all the issues reported here, most of them never fixed.
Maybe it's time to retire and let competent devs do the work you're not able to do  ?

**Comment by mdxmods** [comment]
84 popups in 28 minutes now... still counting.

**Comment by mdxmods** [comment]
85

**Comment by mdxmods** [comment]
If I'm typing code INSIDE THE COLAB why do you need to ask me if I'm still here every 30 secondes ?
How someone with a minimum intelligence and coding skills can let that happen ?
