### ISSUE TITLE
Problem on %load_ext nvcc_plugin, when running CUDA

### ISSUE THREAD

**Issue by gero84** [googlecolab/colabtools#379]
I followed this tutorial to run CUDA code on COLAB:

https://medium.com/@iphoenix179/running-cuda-c-c-in-jupyter-or-how-to-run-nvcc-in-google-colab-663d33f53772

but when I give this command:

%load_ext nvcc_plugin

I get this error:

File "/usr/local/lib/python2.7/dist-packages/v1/v1.py", line 26 stmt = f"subprocess.check_output(['{file_path}.out'], stderr=subprocess.STDOUT)" ^ SyntaxError: invalid syntax

**Comment by iamshreeji-copy1** [comment]
Same issue

**Comment by cperry-goog** [comment]
You should report this with the library author at github.com/andreinechaev/nvcc4jupyter

**Comment by shewayou** [comment]
FYI It seems nvcc4jupyter is newer than nvcc_plugin, so after nvcc4jupyter is installed then %load_ext nvcc4jupyter. I found it on https://stackoverflow.com/questions/78392461/modulenotfounderror-no-module-named-nvcc-plugin
and in https://moritzstrube.substack.com/p/how-to-run-cuda-in-a-colab-notebook.
