### ISSUE TITLE
"torch drug" library showing pip index couldn't found and a python version mismatch error

### ISSUE THREAD

**Issue by sleeping4cat** [googlecolab/colabtools#3791]
**Describe Behaviour **
I was trying to install ```torchdrug``` python library on Google Colab but it couldn't find the install on ```pip``` public index and there was also a python version error. This is the first time, I am encountering this error on Google Colab. 

I have already installed ```torchdrug``` on my local computer and it perfectly installed without any error. 

**Error Message on Google Colab**

```
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.7,<3.9; 0.1.1 Requires-Python >=3.7,<3.9; 0.1.1.post1 Requires-Python >=3.7,<3.9; 0.1.2 Requires-Python >=3.7,<3.9; 0.1.2.post1 Requires-Python >=3.7,<3.9; 0.1.3 Requires-Python >=3.7,<3.10; 0.1.3.post1 Requires-Python >=3.7,<3.10; 0.2.0 Requires-Python >=3.7,<3.10; 0.2.0.post1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement torchdrug (from versions: none)
ERROR: No matching distribution found for torchdrug
```

**Browser Google Colab was accessed from: Google Chrome latest version**
**pip command used on Google Colab: ```!pip install torchdrug```**

**Local Computer Specs:**
* Python 3.8.10 (Installed Globally)

**Reference to torchdrug**
* https://torchdrug.ai/

**Comment by EvanWiederspan** [comment]
The issue is that every version of torchdrug requires a Python version less than 3.10, as seen in the error message, and Colab is now on Python 3.10. It works on your local machine because you have Python 3.8. I would reach out to the torchdrug project maintainers and see if they are planning on releasing a version compatible with 3.10 anytime soon
