### ISSUE TITLE
Colab does not taking account default python package changes to a different version

### ISSUE THREAD

**Issue by sleeping4cat** [googlecolab/colabtools#3792]
**Describe Problem**
I was trying to use ```Finetuner``` library to fine-tune OpenAI's Clip model. ```Finetuner``` required a specific version of ```typing-extensions``` library. Colab had by default the latest version installed and pip couldn't resolve the conflict by itself. Which is why, I prompted to installed the specific version of the ```typing-extensions``` library before importing ```Finetuner```. The installation to specific version of typing-extensions was successful but while I tried to import the library in the next cell, Colab was showing me the error that ```typing-extension``` was in the default latest version and I couldn't import finetuner library. Even though I checked in the next cell the version of typing extensions I have, and it was the specific version that I installed earlier. 

That means Colab wasn't able to detect the new update of the typing-extensions. I reconnected to different runtime, quite a few times and the error is persisting. 

**Browser Google Colab was accessed from: Google Chrome (latest stable version)**

**References:**
* https://finetuner.jina.ai/

**Comment by EvanWiederspan** [comment]
You may need to Runtime -> Restart Runtime after pip installing the new typing-extensions version; this doesn't give you a new VM, just restarts the Python process. Does that fix the issue for you?

**Comment by sleeping4cat** [comment]
It actually worked! thanks :)
