### ISSUE TITLE
Impossible to run 'Recommending movies: retrieval"

### ISSUE THREAD

**Issue by pksinghus** [googlecolab/colabtools#3793]
**Describe the current behavior**
Version mismatches in `tensorflow `, `tensorflow_datasets`, `tensorflow_recommenders`, `scann` and `python`. Impossible to find a combination that works.

You get error messages about something wrong with `builder.py `in `protobof`. You upgrade `protobuf` then you get errors that `tensorflow_datasets` doesn't have a method called "`load`".  Then something else, then something else.

**Describe the expected behavior**
It should be possible to run the example in the notebook.

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mayankmalik-colab** [comment]
It is tricky as `scann` still requires tf 2.11 and we are already on 2.12, along with compatible ecosystem. `scann` will downgrade tf to 2.11. Can you try the below combination. It worked for me.

```
!pip install -q tensorflow-recommenders
!pip install -q tensorflow-datasets==4.7.0
!pip install -q tensorflow-metadata==1.12.0
!pip install -q scann
```
