### ISSUE TITLE
TypeError when reassigning 'print' as an integer

### ISSUE THREAD

**Issue by sarthak1095** [googlecolab/colabtools#3794]
print = 10 
print("hi")

I am getting the below error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-15-8ba1f21ac444>](https://localhost:8080/#) in <cell line: 2>()
      1 print = 10
----> 2 print("hi")
 

TypeError: 'int' object is not callable

**Comment by EvanWiederspan** [comment]
Python allows you to override any value, including built-in functions like "print". So you are setting print to 10, then trying to call print like it's a function but it no longer is. I would avoid giving variables the same name as functions
