### ISSUE TITLE
OSError: [Errno 107] Transport endpoint is not connected (google colab pro)

### ISSUE THREAD

**Issue by Hugomer** [googlecolab/colabtools#3797]
Hello, 

I am a google colab pro+ user.
The [promise is that I can run 24 hours but after around 3 hours I get:

OSError: [Errno 107] Transport endpoint is not connected.

I don't understand what causes the error nor I don't know I can work around this error. 
I did read previous posts but I couldn't find a clear answer.

The code I did use was:

`from google.colab import drive

# Mount Google Drive to access files and folders
drive.mount('/content/drive')
`

When running my model it crashes also when I restart runtime:

**Comment by cperry-goog** [comment]
Are you hitting https://research.google.com/colaboratory/faq.html#drive-timeout ? Drive doesn't like it when you have too many files.

**Comment by olaviinha** [comment]
I am not the poster of this, but since this has been a common issue in Colab for weeks, I can respond:

No. It is not mounting timeout. Drive disconnection occurs after approximately 4 hours in session. This has been a common problem for weeks.

**Comment by olaviinha** [comment]
I am also facing this issue. As with others, Drive disconnection occurs after approximately 4 hours of active Colab notebook session. **This has happened now for weeks.** It happens also when accessing Drive folders that have only 5 files.

**Comment by Hugomer** [comment]
I did solve it by uploading the dataset directly into the notebook instead of using the drive mount. I didn't find a better solution yet (in an easy way).

**Comment by olaviinha** [comment]
Ah, so it really was the suggested too-many-files problem for you. Lucky you!

**Comment by Hugomer** [comment]
I'm not sure if it was because I had too many files. I did image classification, but often this should only be a problem if you have thousands of files, my dataset contained only a few hundred images. I thought it had more to do with time. While Google Colab Pro+ can run for 24 hours in 1 run, the drive mount feature is only consistent for the first 3 or 4 hours.

**Comment by cperry-goog** [comment]
Duping with #3785
