### ISSUE TITLE
Problema na celula de codigo

### ISSUE THREAD

**Issue by EmilioBorges** [googlecolab/colabtools#3798]
Por algum motivo a celula de codigo do google colab ficou pequena, como se estivesse minimizada, e possivel clicar no botão de play, porem não e possivel digitar nada, estou usando o google chrome.

![image](https://github.com/googlecolab/colabtools/assets/55116874/94e387df-5130-4a99-98e5-24e4ab2da719)

![erro colab](https://github.com/googlecolab/colabtools/assets/55116874/b3db9471-0d47-44ad-b753-a063f840ad86)

**Comment by cperry-goog** [comment]
Can you try this in an incognito window? There could be a browser extension that is causing this.
