### ISSUE TITLE
Deoldify Error

### ISSUE THREAD

**Issue by wangchun52799** [googlecolab/colabtools#3801]
**Describe the current behavior**
---------------------------------------------------------------------------------------------
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet101_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet101_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet101-63fe2227.pth" to /root/.cache/torch/hub/checkpoints/resnet101-63fe2227.pth
100%|██████████| 171M/171M [00:02<00:00, 77.3MB/s]
---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
[<ipython-input-7-81c07a854ecc>](https://localhost:8080/#) in <cell line: 1>()
----> 1 colorizer = get_video_colorizer()

5 frames
[/usr/local/lib/python3.10/dist-packages/torch/serialization.py](https://localhost:8080/#) in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
   1031             "functionality.")
   1032 
-> 1033     magic_number = pickle_module.load(f, **pickle_load_args)
   1034     if magic_number != MAGIC_NUMBER:
   1035         raise RuntimeError("Invalid magic number; corrupt file?")

EOFError: Ran out of input
-------------------------------------------------------------------------------------------------
in Chinese：
以上为报错内容，请查看具体是什么问题，望尽快解决。

**Comment by cperry-goog** [comment]
This doesn't look like a Colab bug - you'll want to contact the notebook or package author.
