### ISSUE TITLE
Wrong syntax highlighting when using a bang! in a f-string

### ISSUE THREAD

**Issue by Gouvernathor** [googlecolab/colabtools#3802]
**Describe the current behavior**
The syntax highlighting is off, the comments are red instead of the usual green and the string looks like it's not been ended.
![image](https://github.com/googlecolab/colabtools/assets/44340603/7af63fa3-c226-4bb1-84a4-07188bec836c)

**What web browser you are using**
Firefox

**Additional context**
https://colab.research.google.com/drive/1WRI8CrVnkZdcLgp1wl3DQQEBURfQ6x2C?usp=sharing

**Comment by cperry-goog** [comment]
This is almost certainly a Monaco bug, as we upgrade Monaco we should get this fixed when downstream fixes are available.

**Comment by EvanWiederspan** [comment]
This ended up being a bug on our end, this is now fixed. Thanks for the report
