### ISSUE TITLE
AttributeError: module 'threading' has no attribute '_Condition'

### ISSUE THREAD

**Issue by honnuanand** [googlecolab/colabtools#3807]
**Describe the current behavior**
I am having an issue importing a library. 
This notebook link : https://github.com/pinecone-io/examples/blob/master/generation/langchain/handbook/05-langchain-retrieval-augmentation.ipynb 

https://www.pinecone.io/learn/langchain-retrieval-augmentation/

Error : 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-7-645419abb9aa>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from datasets import load_dataset
      2 data = load_dataset("wikipedia", "20220301.simple", split='train[:10000]')
      3 data
      4 
      5 # from datasets import list_datasets

10 frames
[/usr/local/lib/python3.10/dist-packages/multiprocess/dummy/__init__.py](https://localhost:8080/#) in <module>
     85 #
     86 
---> 87 class Condition(threading._Condition):
     88     # XXX
     89     if sys.version_info < (3, 0):

AttributeError: module 'threading' has no attribute '_Condition'

refered in. 
**Describe the expected behavior**
I ran this on my local machine, I have no issues . 
**What web browser you are using**
I am on Chrome
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mayankmalik-colab** [comment]
This doesn't seem like Colab specific issue. It seems like the issue is from [https://github.com/apache/beam/issues/24458](https://github.com/apache/beam/issues/24458). Please follow that discussion for help.
