### ISSUE TITLE
Colab timeout so early

### ISSUE THREAD

**Issue by benrex001** [googlecolab/colabtools#3809]
Hi i have problem with runtime is timeout so early. it takes around 7 minutes and then colab timeout. this is colab notebook link https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/drive/run.ipynb#scrollTo=SaAJk33ppFw1

**Comment by mdx-mods** [comment]
> Are you using the free of charge hosted runtimes? We restrict stable-diffusion-webui on free tier; only available on paid.

So, why are you also doing that to people who never used stable diffusion and things like that ?
