### ISSUE TITLE
Help not working 

### ISSUE THREAD

**Issue by ramtz316** [googlecolab/colabtools#3812]
!git clone https://github.com/s0md3v/roop
%cd roop
#latest commit working right now 7:57 PM (UTC+3) 25 June. The below commit hash set for 10 june testing
!git checkout b41149e4a22a55198447a7accb671021b47d8bad
!pip install onnxruntime-gpu && pip install -r requirements.txt
!wget https://huggingface.co/MonsterMMORPG/SECourses/resolve/main/inswapper_128.onnx

**usualyy the above runs the project . But im getting an issue . not sure how to fix it**

 Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      Successfully uninstalled protobuf-3.20.3
  Attempting uninstall: pillow
    Found existing installation: Pillow 8.4.0
    Uninstalling Pillow-8.4.0:
      Successfully uninstalled Pillow-8.4.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.4
    Uninstalling numpy-1.22.4:
      Successfully uninstalled numpy-1.22.4
  Attempting uninstall: onnxruntime-gpu
    Found existing installation: onnxruntime-gpu 1.15.1
    Uninstalling onnxruntime-gpu-1.15.1:
      Successfully uninstalled onnxruntime-gpu-1.15.1
Successfully installed addict-2.4.0 basicsr-1.4.2 customtkinter-5.1.3 darkdetect-0.8.0 facexlib-0.3.0 filterpy-1.4.5 gfpgan-1.3.8 importlib-metadata-6.7.0 insightface-0.7.3 lmdb-1.4.1 numpy-1.23.5 onnx-1.14.0 onnxruntime-gpu-1.15.0 opennsfw2-0.10.2 pillow-9.5.0 protobuf-4.23.2 tb-nightly-2.14.0a20230702 tk-0.1.0 yapf-0.40.1
WARNING: The following packages were previously imported in this runtime:
  [PIL,numpy]
You must restart the runtime in order to use newly installed versions.
--2023-07-02 18:12:22--  https://huggingface.co/MonsterMMORPG/SECourses/resolve/main/inswapper_128.onnx
Resolving huggingface.co (huggingface.co)... 65.9.86.62, 65.9.86.57, 65.9.86.79, ...
Connecting to huggingface.co (huggingface.co)|65.9.86.62|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn-lfs.huggingface.co/repos/1b/95/1b9587c6131e50dc30fec9d8d829ec2de37d44cf22183191ea1235a5089d904f/e4a3f08c753cb72d04e10aa0f7dbe3deebbf39567d4ead6dce08e98aa49e16af?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27inswapper_128.onnx%3B+filename%3D%22inswapper_128.onnx%22%3B&Expires=1688571320&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4tbGZzLmh1Z2dpbmdmYWNlLmNvL3JlcG9zLzFiLzk1LzFiOTU4N2M2MTMxZTUwZGMzMGZlYzlkOGQ4MjllYzJkZTM3ZDQ0Y2YyMjE4MzE5MWVhMTIzNWE1MDg5ZDkwNGYvZTRhM2YwOGM3NTNjYjcyZDA0ZTEwYWEwZjdkYmUzZGVlYmJmMzk1NjdkNGVhZDZkY2UwOGU5OGFhNDllMTZhZj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2ODg1NzEzMjB9fX1dfQ__&Signature=VGEOJOl8aqicUMvb4q4MvCtVv68F9eyXLLjkF4SdQJvjp2HVAW%7EdiPY9TSdbkEDh58Vys43bPSYanlxCQfR4HImn%7EO0lVyNNmBaLQ3I5NkdvR%7EzxAN5zdoYPo-lUY3WqzGEwxYUTZc%7E4E5JbmY2qkLjcLXouebiUr1%7EYTFpdeqAjL6NMVz6BxIzYOibtC7T2PEqfIfzZn2iwSb-AHxSRSl1mG3N9c2h7XJcvueQEWdSNoXqEFtZvZTZNvoT0FzUPFh8%7EMB0t4NMDL-3Mo2PpY4WubHKUlYcb-o8bPdLq24X24ZdPaFO-hoVtO%7EWrRa88r00y12crxZwuXgQHaJ-zQg__&Key-Pair-Id=KVTP0A1DKRTAX [following]
--2023-07-02 18:12:22--  https://cdn-lfs.huggingface.co/repos/1b/95/1b9587c6131e50dc30fec9d8d829ec2de37d44cf22183191ea1235a5089d904f/e4a3f08c753cb72d04e10aa0f7dbe3deebbf39567d4ead6dce08e98aa49e16af?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27inswapper_128.onnx%3B+filename%3D%22inswapper_128.onnx%22%3B&Expires=1688571320&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4tbGZzLmh1Z2dpbmdmYWNlLmNvL3JlcG9zLzFiLzk1LzFiOTU4N2M2MTMxZTUwZGMzMGZlYzlkOGQ4MjllYzJkZTM3ZDQ0Y2YyMjE4MzE5MWVhMTIzNWE1MDg5ZDkwNGYvZTRhM2YwOGM3NTNjYjcyZDA0ZTEwYWEwZjdkYmUzZGVlYmJmMzk1NjdkNGVhZDZkY2UwOGU5OGFhNDllMTZhZj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2ODg1NzEzMjB9fX1dfQ__&Signature=VGEOJOl8aqicUMvb4q4MvCtVv68F9eyXLLjkF4SdQJvjp2HVAW%7EdiPY9TSdbkEDh58Vys43bPSYanlxCQfR4HImn%7EO0lVyNNmBaLQ3I5NkdvR%7EzxAN5zdoYPo-lUY3WqzGEwxYUTZc%7E4E5JbmY2qkLjcLXouebiUr1%7EYTFpdeqAjL6NMVz6BxIzYOibtC7T2PEqfIfzZn2iwSb-AHxSRSl1mG3N9c2h7XJcvueQEWdSNoXqEFtZvZTZNvoT0FzUPFh8%7EMB0t4NMDL-3Mo2PpY4WubHKUlYcb-o8bPdLq24X24ZdPaFO-hoVtO%7EWrRa88r00y12crxZwuXgQHaJ-zQg__&Key-Pair-Id=KVTP0A1DKRTAX
Resolving cdn-lfs.huggingface.co (cdn-lfs.huggingface.co)... 13.227.219.4, 13.227.219.41, 13.227.219.2, ...
Connecting to cdn-lfs.huggingface.co (cdn-lfs.huggingface.co)|13.227.219.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 554253681 (529M) [binary/octet-stream]
Saving to: ‘inswapper_128.onnx’

inswapper_128.onnx  100%[===================>] 528.58M  86.0MB/s    in 6.1s    

2023-07-02 18:12:28 (86.0 MB/s) - ‘inswapper_128.onnx’ saved [554253681/554253681]

https://colab.research.google.com/github/FurkanGozukara/Stable-Diffusion/blob/main/ColabNotebooks/1_click_deep_fake_for_free_by_SECourses.ipynb?authuser=2#scrollTo=_j18G_uPqc37&line=1&uniqifier=1

**and this says** 

**python3: can't open file '/content/run.py': [Errno 2] No such file or directory**

**Comment by cperry-goog** [comment]
We can't reproduce, works for us. If it keeps breaking you might want to contact the author of the repo.
