### ISSUE TITLE
How can i install Python 3.8; Pytorch 1.9.0; CUDA 10.1 in gg colab (07/2023)

### ISSUE THREAD

**Issue by ducanha2k46** [googlecolab/colabtools#3818]
Hello everyone,

I am facing some difficulties in installing the Python environment and related tools on Google Colab. Currently, I need to install Python 3.8, PyTorch 1.9.0, and CUDA 10.1 to proceed with my work.

However, it seems that Colab does not provide official support for these versions at the moment (July 2023). I have tried various methods but have been unsuccessful in installing them.

Therefore, I am seeking help from everyone. If someone has encountered a similar issue or has knowledge about how to install Python 3.8, PyTorch 1.9.0, and CUDA 10.1 on Colab at the current time, I would greatly appreciate your guidance and instructions.

Thank you sincerely for your support and contributions in helping me overcome this issue.

**Comment by cperry-goog** [comment]
We don't support downgrading Python versions unfortunately. You could try running Colab via a local runtime. https://research.google.com/colaboratory/local-runtimes.html
