### ISSUE TITLE
Copied text or code is not faithfully pasted - the middle of the copied content is replaced with one or more elipses "..."

### ISSUE THREAD

**Issue by kpkpkp** [googlecolab/colabtools#3819]
**Describe the current behavior**
Not all selected text is copied.  The middle of the text gets replaced by "..." (without the quotes)

**Describe the expected behavior**
any block of text, selected, copied, and pasted, should be identical

**What web browser you are using**
Chrome running on a Chromebook: Version 114.0.5735.205 (Official Build) (64-bit)

**Additional context**
https://colab.research.google.com/drive/1f6RlFIpM7ULlbiQxKqRB3gRab5eNVpEz?usp=sharing

**Comment by EvanWiederspan** [comment]
Does this still happen for you in incognito mode, with all extensions turned off? Also, when you paste and see the ellipses, can you paste the same text elsewhere and still see the full text?

**Comment by kpkpkp** [comment]
I Power Washed my Chromebook and then after getting things working again,
disabled all Chrome extensions except for Google Docs Offline extension.
Copying and pasting is back to normal!

I guess you can close this ticket.
I'll be checking which extension causes the issue.

Thanks!
