### ISSUE TITLE
NO FUNCIONA!!

### ISSUE THREAD

**Issue by Byronrabe** [googlecolab/colabtools#3821]
TEngoun plan mensual pero se acabó.  Todo funcionaba bien.

Compre 100 unidades y ahora no funciona.ç
Qué puedo hacer?

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
duping this with #3820
