### ISSUE TITLE
rpy2.ipython

### ISSUE THREAD

**Issue by heilandd** [googlecolab/colabtools#3825]
The problem of the rpy2.ipython was reported recently and corrected, know the following problem appeared again: 

NotImplementedError                       Traceback (most recent call last)
[<ipython-input-8-44f59b9a9fc1>](https://gyi6xynlout-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230705-060126-RC00_545627076#) in <cell line: 1>()
----> 1 get_ipython().run_cell_magic('R', '', '\na = 1+2\n')

9 frames
<decorator-gen-122> in R(self, line, cell, local_ns)

[/usr/local/lib/python3.10/dist-packages/rpy2/robjects/conversion.py](https://gyi6xynlout-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230705-060126-RC00_545627076#) in _py2rpy(obj)
    238     if isinstance(obj, _rinterface_capi.SupportsSEXP):
    239         return obj
--> 240     raise NotImplementedError(
    241         "Conversion 'py2rpy' not defined for objects of type '%s'" %
    242         str(type(obj))

NotImplementedError: Conversion 'py2rpy' not defined for objects of type '<class 'str'>'

Happy to get help to run rpy2.ipython

**Comment by mayankmalik-colab** [comment]
We are aware of it. It actually needs `ipykernel` upgrade and we are working on it. However, I think you can use `3.4.2` version of rpy2. It  works fine if you want to downgrade.
