### ISSUE TITLE
qiskit PySCF

### ISSUE THREAD

**Issue by MahmooddHasani** [googlecolab/colabtools#3826]
**Importing Liabrary**
every time I run this code i get the error:
MissingOptionalLibraryError: "The 'pyscf' library is required to use 'PySCFDriver'.  See https://pyscf.org/install.html."
but i have done every thing  that possible for solving it, moreover the code is same as the website of qiskit nature which is:

from qiskit_nature.units import DistanceUnit
from qiskit_nature.second_q.drivers import PySCFDriver
from qiskit_nature.second_q.mappers import ParityMapper
from qiskit_nature.second_q.properties import ParticleNumber
from qiskit_nature.second_q.transformers import ActiveSpaceTransformer
bond_distance = 2.5  # in Angstrom

# specify driver
driver = PySCFDriver(
    atom=f"Li 0 0 0; H 0 0 {bond_distance}",
    basis="sto3g",
    charge=0,
    spin=0,
    unit=DistanceUnit.ANGSTROM,
)
problem = driver.run()

# specify active space transformation
active_space_trafo = ActiveSpaceTransformer(
    num_electrons=problem.num_particles, num_spatial_orbitals=problem.num_spatial_orbitals
)

# transform the electronic structure problem
problem = active_space_trafo.transform(problem)

# construct the parity mapper with 2-qubit reduction
qubit_mapper = ParityMapper(num_particles=problem.num_particles)

**Comment by mayankmalik-colab** [comment]
I think you need both of the below packages. You might have missed one of them.
```
!pip install qiskit-nature
!pip install pyscf
```

The code you mentioned above worked fine after installing these packages. Hope it helps.
