### ISSUE TITLE
Issue with repeated R package installation in ColabPro

### ISSUE THREAD

**Issue by hamidghaedi** [googlecolab/colabtools#3828]
I'm facing an issue while using ColabPro for running R analysis. I need to install the "SCP" package from GitHub using the following code:
```
if (!require("devtools", quietly = TRUE)) {
  install.packages("devtools")
}
devtools::install_github("zhanghao-njmu/SCP")
```
The installation works, but the problem is that I have to reinstall the package every time I start a new kernel. This is time-consuming and causes a sharp drop in my computing unit. Is there a way to avoid reinstalling the package in every fresh session?

**Comment by cperry-goog** [comment]
We do not support custom containers in our managed runtimes, but you can use a local runtime and manage your own dependencies: https://research.google.com/colaboratory/local-runtimes.html
