### ISSUE TITLE
Stable Diffusion notebook by @pharmapsychotic NOT WORKING

### ISSUE THREAD

**Issue by meskaldiffusion** [googlecolab/colabtools#3831]
Stable Diffusion notebook by @pharmapsychotic NOT WORKING

**Describe the current behavior**
When i run the "LOAD MODEL" section i get this error.

ImportError                               Traceback (most recent call last)
[<ipython-input-4-e9577ed9b5ab>](https://localhost:8080/#) in <cell line: 17>()
     15 from omegaconf import OmegaConf
     16 from PIL import Image
---> 17 from pytorch_lightning import seed_everything
     18 from torch import autocast
     19 

3 frames
[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/__init__.py](https://localhost:8080/#) in <module>
     32     _logger.propagate = False
     33 
---> 34 from pytorch_lightning.callbacks import Callback  # noqa: E402
     35 from pytorch_lightning.core import LightningDataModule, LightningModule  # noqa: E402
     36 from pytorch_lightning.trainer import Trainer  # noqa: E402

[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/__init__.py](https://localhost:8080/#) in <module>
     23 from pytorch_lightning.callbacks.model_summary import ModelSummary
     24 from pytorch_lightning.callbacks.prediction_writer import BasePredictionWriter
---> 25 from pytorch_lightning.callbacks.progress import ProgressBarBase, RichProgressBar, TQDMProgressBar
     26 from pytorch_lightning.callbacks.pruning import ModelPruning
     27 from pytorch_lightning.callbacks.quantization import QuantizationAwareTraining

[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/progress/__init__.py](https://localhost:8080/#) in <module>
     20 """
     21 from pytorch_lightning.callbacks.progress.base import ProgressBarBase  # noqa: F401
---> 22 from pytorch_lightning.callbacks.progress.rich_progress import RichProgressBar  # noqa: F401
     23 from pytorch_lightning.callbacks.progress.tqdm_progress import TQDMProgressBar  # noqa: F401

[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/progress/rich_progress.py](https://localhost:8080/#) in <module>
     18 from typing import Any, Dict, Optional, Union
     19 
---> 20 from torchmetrics.utilities.imports import _compare_version
     21 
     22 import pytorch_lightning as pl

ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports' (/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/imports.py)

**Describe the expected behavior**
i would expect this to work as usual and dont get the error when loading the model

**What web browser you are using**
i am using Brave browser

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
Could you share the notebook you are using? As an initial guess, it seems like the torchmetrics package may be incompatible with your environment, and I would try installing a different version to see if that changes anything

**Comment by meskaldiffusion** [comment]
I am using this notebook:
pharmapsychotic_Stable_Diffusion.ipynb

https://colab.research.google.com/github/pharmapsychotic/ai-notebooks/blob/main/pharmapsychotic_Stable_Diffusion.ipynb?pli=1&authuser=1#scrollTo=bcHsbr3hblrk

I am using this since january 2023 without any problem. I have not changed computer or anything else and last week it stop working.

**Comment by cperry-goog** [comment]
You'll need to contact the notebook author - this looks like a torch or other dependency issue.
