### ISSUE TITLE
Colab gives error falsly

### ISSUE THREAD

**Issue by moahaimen** [googlecolab/colabtools#3833]
**Describe the current behavior**
hi, I'm trying to add custom module to YOLOv8.

I searched issues and follow several suggestions, but it didnt work.

Things I tried

add NewClass(nn.Module) to nn/modules/block.py
add 'NewClass' to __all__ part in block.py
add NewClass to from .block import ... part in nn/modules/ __init__.py 
add NewClass to from ..../modules import .... part in nn/tasks.py
but I continously get the same error.
I solved the issue.
it is turned out that very funny mistakes! :)

I edited my local files, but in the code, it looks like the code import modules from pip packages(ultralytics)

so here's I tryed.

In the highest folder(ultralytics), I make one .py file. (ex. Train.py)
In the .py file, add from ultralytics.yolo.engine.model import YOLO
write command. (ex. model = YOLO(WEIGHT_PATH), model.train() ....)
now the code not use pip package file but local code!
Thanks.

p.s. without this error, my YOLOv8 code is good. I trained several baseline models and it worked normally

**Describe the expected behavior**
this solution worked for my laptop but it doesn work for Google Colab , i created the file and wrote the code in it , and i excute it by this !python /content/yolov8/ultralytics/developing_blocks.py
but the same error of MDC " m = getattr(torch.nn, m[3:]) if 'nn.' in m else globals()[m] # get module
KeyError: 'MDC'"
**What web browser you are using**
Chrome

**Additional context**

**Comment by EvanWiederspan** [comment]
You may need to Runtime -> Restart Runtime after editing the file in order for Colab to pick up the changes
