### ISSUE TITLE
Failed to install third-party software

### ISSUE THREAD

**Issue by Fz903** [googlecolab/colabtools#3834]
**Describe the current behavior**
I've been using Colab Pro for more than a week without encountering this issue. However, every time I try to run the first step 'Install third-party software' today, an alert pops up and the run is stopped. 

**Describe the expected behavior**
CalledProcessError: Command 'conda install -qy conda==4.13.0            && conda install -qy -c conda-forge              python=3.10              openmm=7.7.0              pdbfixer' returned non-zero exit status 1.

**What web browser you are using**
I've tried to run it on Safari and Chrome, but the same alert appears on both browsers.

**Comment by EvanWiederspan** [comment]
Can you share the notebook you're running?

**Comment by kidless137** [comment]
I have the same problem, have you solved this?
