### ISSUE TITLE
colab notebook is not getting connected, it's getting stucked in the allocating process, I tried the feedback option but it has been two days didn't get any response

### ISSUE THREAD

**Issue by sagarbadki** [googlecolab/colabtools#3835]
Hello everyone,

I'm experiencing difficulties connecting to a Colab notebook as it gets stuck during the allocating process. It is crucial for me to use it as soon as possible. I have already attempted disabling the firewall defender, but the issue persists.

I have tried accessing the Colab notebook using Chrome, Firefox, and Edge web browsers. However, none of them have been successful in establishing a connection.

I would greatly appreciate any assistance or suggestions to resolve this problem promptly. Thank you.

**Comment by EvanWiederspan** [comment]
Does the issue still happen for you in incognito mode, with all extensions disabled?

**Comment by sagarbadki** [comment]
Hi @EvanWiederspan,
I Tried in the incognito mode with same extensions enabled and it's working fine, so there is no issue with the extensions

**Comment by MridhulClootrack** [comment]
Hi @EvanWiederspan , I tried the same on Incognito mode and it was stuck saying Allocating and wasn't working.

![Screenshot (27)_to send togithub](https://github.com/googlecolab/colabtools/assets/139528448/7c6904b9-a6c6-4c2d-8e22-9e09f6a77afc)

**Comment by aakashunnikrishnan** [comment]
HI @EvanWiederspan 
i tried in incognito window,still its loading all the time.

**Comment by cperry-goog** [comment]
Can you submit feedback in product? I don't have a good way to diagnose without that detail. Please reference this issue.
