### ISSUE TITLE
"Are you still here" popup, I click "yes", the runtime is deleted ! Why doing such a thing ?

### ISSUE THREAD

**Issue by mdx-mods** [googlecolab/colabtools#3839]
Explicit title. happended multiple times since few days.

What is the point to ask user if he's still here (while HE IS TYPING CODE INSIDE COLAB), and when he say yes, you delete all his work without any statement.
Why are you doing this ? Would you enjoy that services you use all worked liked this ?
"I had an accident, I need hostipal"
"ok, we send emergency"
and when the ambulance arrives to you and asks
"Are you still alive ?"
"yes, help me"
And then the ambulance goes away and let you die on the street without any statement.
Would you like that ?

**Comment by cperry-goog** [comment]
Can you submit feedback in product if you encounter this again.
