### ISSUE TITLE
The google collab is crashing

### ISSUE THREAD

**Issue by dnmeghana** [googlecolab/colabtools#3840]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

Iam using google collab from few years but from last 2 days the google collab is crashing for just 2 lines of codes.i rechecked with diff small code like just import things but  It says the collab crashed. Iam using Chrome web browser.

**Comment by EvanWiederspan** [comment]
Can you share the notebook you are using, and the exact error that you are seeing?

**Comment by dnmeghana** [comment]
hey,
I'll just attach the error i'm getting and the notebook link here
[image: image.png]
https://colab.research.google.com/drive/1ZUpSUZdQ4gWm5yX4rMWCB-t1Aknow8sb

**Comment by cperry-goog** [comment]
can you grant access?

**Comment by dnmeghana** [comment]
Now it's been fixed i tried to run again today . Had no issues.

**Comment by ShibuGitB** [comment]
my notebook got crashed
