### ISSUE TITLE
Third part software failing

### ISSUE THREAD

**Issue by noahqchen** [googlecolab/colabtools#3841]
**Describe the current behavior**
I have been using alphafold colab with pro for a little while now but suddenly yesterday the first step of installing third party software stopped working. I saw another bug report with a similar problem with intalling.
https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb?authuser=2#scrollTo=woIxeCPygt7K
I assume that this is an error with something updating but I don't really know.
**Describe the expected behavior**
I got the error CalledProcessError: Command 'conda install -qy conda==4.13.0 && conda install -qy -c conda-forge python=3.10 openmm=7.7.0 pdbfixer' returned non-zero exit status 1.
**What web browser you are using**
Chrome, but I've tried it on safari and it didn't work.

**Comment by kidless137** [comment]
I have the same problem, have you solved this?

**Comment by isobeld** [comment]
I've also encountered the same issue, but had recently got it working (early last week) so I think something must have updated in the code, because it says my version of python is incompatible now?

**Comment by laumiro978** [comment]
> I've also encountered the same issue, but had recently got it working (early last week) so I think something must have updated in the code, because it says my version of python is incompatible now? I can't get past the install stage now

I have the same problem during the last two days,

**Comment by cperry-goog** [comment]
The AlphaFold team pushed a fix this morning, thanks for the report.
