### ISSUE TITLE
ModuleNotFoundError: No module named 'faiss'

### ISSUE THREAD

**Issue by walidmusicman** [googlecolab/colabtools#3849]
/content/Retrieval-based-Voice-Conversion-WebUI
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 7, in <module>
    import faiss
ModuleNotFoundError: No module named 'faiss'

**Comment by mayankmalik-colab** [comment]
This doesn't seem like Colab specific issue. Please reach out to the notebook owner.
