### ISSUE TITLE
Paid products error

### ISSUE THREAD

**Issue by Ramkat12** [googlecolab/colabtools#3850]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
I was using google coolab , and then I used up all my Ram, so I wanted to make an upgrade. When I went for the upgrade a dialogue box appeared and I was asked to agree to the terms and services. When I agreed it just told me there was an error and that I should try again later ,this was around 3:00 pm (EAT) , fast forward to 9:30 PM (EAT) and I still have the same issue. I would really like to upgrade my account so that I can finalize my project which is due on Friday, kindly help.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
I expected that after agreeing to the terms and conditions , my payment options would appear and I would be able to make the relevant purchase.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome.
**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
 - https://colab.research.google.com/drive/1Bp6uVyCWSvDdQ5FFTaH4q7llQNnZ1CEw#scrollTo=hl1AeW2oQ5J7

**Comment by cperry-goog** [comment]
Can you share the error code you're seeing?
