### ISSUE TITLE
Storage Space Inaccurate 

### ISSUE THREAD

**Issue by bgonggw** [googlecolab/colabtools#3851]
Hi Colab says I am using 150G of space but in fact I am only using 18G? 

<img width="1317" alt="image" src="https://github.com/googlecolab/colabtools/assets/39283973/f097364d-42e4-43dc-b419-e0aee9789813">

For repro: https://colab.research.google.com/drive/1iwnILZ4H1okHZHBUwAVVHArgMA7-ZX2n?usp=sharing

**Comment by mayankmalik-colab** [comment]
The above notebook doesn't exist anymore.  Anyways, can you do `du`  at root and not at `/content`.  
Something like `!du -sh /` . I am wondering if other directory is using the space.
