### ISSUE TITLE
constant disconnections

### ISSUE THREAD

**Issue by swandarina** [googlecolab/colabtools#3852]
**Describe the current behavior**
I've been using the Colab Pro plan for a while, and it has been working well. But since three days ago (i am guessing), my notebook started to get disconnected. yesterday, I assumed that it was because of RAM, i added more... but it kept getting disconnected. I changed it to TPU, then to GPU... same...
and during this struggling, i have consumed more than 30 CUs

**Describe the expected behavior**
It gets disconnected and i got this error:
"Sin conexión al entorno de ejecución."

And obviously i lost everything... as i have lots of package to install and then to import... it is more than an hour waiting only in these first two steps.

is it just me? or an issue that is bothering many?

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
can you submit feedback in product and reference this github issue and we'll take a look
