### ISSUE TITLE
Colab blocked for colabcat 

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [googlecolab/colabtools#3853]
I was trying out the colabcat notebook as a student learning Cyber Security for Ethical Hacking. 

The GitHub repo is: https://github.com/someshkar/colabcat

## Current Behaviour 

I was running each cell then after a few cells I got told I was blocked from running colab runtimes for abusive activity. As I stated, I was just wanting to test this notebook out and if you check my repository you will see that I am new to Cyber Security with no real intention for breaking the law or causing harm.

<img src="https://github.com/googlecolab/colabtools/assets/55933131/d4ef1649-d6da-4dd6-8831-cbf795272133">

## Expected Behaviour

That each cell would run and try iterating hashes from hashcat using the GPUs.

<img src="https://github.com/googlecolab/colabtools/assets/55933131/b18e3f69-e534-4df3-bd2b-69c0d78fa1dd">

## Browser 

Google Chrome. Account signed in.

## Can I get my Google Colab Notebook runtime reinstated ? 
I will delete my copies of this notebook and I admit I did not know this notebook would be in violation.

**Comment by EvanWiederspan** [comment]
We can't resolve this from Github, please file an appeal as mentioned in the popup to get unbanned. We disallow [password cracking](https://research.google.com/colaboratory/faq.html#limitations-and-restrictions) regardless of the intent, and you will likely get banned again if you continue to run that notebook
