### ISSUE TITLE
Google drive mounting error on custom VM

### ISSUE THREAD

**Issue by Akshajy6** [googlecolab/colabtools#3854]
**Current Behavior**
I am trying to mount google drive to access files in my Google Colab Jupiter notebook. I am running this on a custom GCE VM and using the code below, but I am getting the below error. Every solution I have looked up has used this code, or a similar version of it, and nothing has mentioned it not working on a custom VM. The only mention of this error code is in this [GitHub issue](https://github.com/PradyumnaKrishna/Colab-Hacks/issues/51), which was supposedly fixed in 2021.
![image](https://github.com/googlecolab/colabtools/assets/65787186/03e8c333-68b4-4130-a808-cc18acd9442c)

**Expected Behavior**
When I run the same code to mount my google drive on a hosted runtime instead of my VM, it mounts correctly and I can access my files.
![image](https://github.com/googlecolab/colabtools/assets/65787186/eaf7e832-4823-44ca-991c-12ba4b952605)

I would really appreciate any help to find a solution to this error.

**Web Browser**
Google Chrome

**Comment by EvanWiederspan** [comment]
We don't currently support mounting Drive on custom GCE VMs. I would recommend using pydrive instead, https://colab.research.google.com/notebooks/io.ipynb#scrollTo=7taylj9wpsA2
