### ISSUE TITLE
Allocated issue

### ISSUE THREAD

**Issue by quintendewilde** [googlecolab/colabtools#3855]
I'm unable to get an A100 GPU.  And I'm getting other GPU's instead. 

I didn't asked for another GPU, so don't give me one. I'm losing credits by just endlessly restarting the run time to get what I want.
And losing time over it.

I'm paying more and more for the GPU and not even getting what I want. 
How does this makes sense? 

How can I approach a support/complaint case.

**Comment by cperry-goog** [comment]
If you need a specific GPU chip type, I'd recommend pursuing the Marketplace option: https://research.google.com/colaboratory/marketplace.html you can get the exact configuration you want.
