### ISSUE TITLE
I am facing this issue while using AUTOMATIC1111

### ISSUE THREAD

**Issue by naushadali6069** [googlecolab/colabtools#3856]
**Describe the current behavior**
its showing me like this
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x5bfc54ddb9d0

**Describe the expected behavior**
I dont know what happening, it was working fine.

**What web browser you are using**
Safari

**Additional context**
[Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.](https://colab.research.google.com/drive/1UHQviTrWHcsYX5UZOURr4pSgO7x4bTFS?usp=sharing)
<img width="730" alt="Screenshot 2023-07-20 at 1 21 21 AM" src="https://github.com/googlecolab/colabtools/assets/111210942/3659d725-f80f-49e3-a8b7-a5d485fc7b4a">

**Comment by agscontact** [comment]
I am running into the same issue. Looks like a bug

**Comment by naushadali6069** [comment]
> I am running into the same issue. Looks like a bug
I have resolved this, We can use the Fallback option.

**Comment by cperry-goog** [comment]
Yeah, Stable Diffusion will need to upgrade to support Ubuntu 22.04; in the meantime use the fallback option.
