### ISSUE TITLE
fast_stable_diffusion_AUTOMATIC1111.ipynb

### ISSUE THREAD

**Issue by shtinov** [googlecolab/colabtools#3860]
1. fast_stable_diffusion_AUTOMATIC1111.ipynb
https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb#scrollTo=PjzwxTkPSPHf
2. Start Stable-Diffusion
I havn't a link to run Stable Diffusion
3. I have error:
![Screenshot (34)](https://github.com/googlecolab/colabtools/assets/140036167/ff4f8972-238b-4861-bd15-9532c8d5b504)

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by ecrm77** [comment]
Google has an Ubuntu update on its system, and the Notebook should be changed to reflect that. Workaround is to go to Tools->Command Platte and activate the fallback option "Use fallback runtime version"

**Comment by cperry-goog** [comment]
@ecrm77 is correct
