### ISSUE TITLE
add-apt-repository fails in Ubuntu 22.04 but works fine with 'fallback runtime version'

### ISSUE THREAD

**Issue by soonhokong** [googlecolab/colabtools#3867]
**Describe the current behavior**

`!sudo add-apt-repository` fails. For example, `!sudo add-apt-repository ppa:ubuntu-mozilla-daily/ppa` generates the following error:

```
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 363, in <module>
    addaptrepo = AddAptRepository()
  File "/usr/bin/add-apt-repository", line 41, in __init__
    self.distro.get_sources(self.sourceslist)
  File "/usr/local/lib/python3.10/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Ubuntu/jammy
```

**Describe the expected behavior**

It should just work.

**What web browser you are using**

Google Chrome 114

**Additional context**

How to reproduce this?
- Create a new notebook.
- Run `!sudo add-apt-repository ppa:ubuntu-mozilla-daily/ppa`. In fact, any PPA should cause this error.

Note:
- I think it's caused by the recent upgrade to Ubuntu 22.04, https://github.com/googlecolab/colabtools/issues/3778.
- When I use "fallback runtime version", it just works.

**Comment by BeauGeogeo** [comment]
@soonhokong  I have exactly the same kind of bugs with library not wroking anymore whereas within the fallback runtime version I had been able to fix everything and made it work. Issue #3863

**Comment by mayankmalik-colab** [comment]
Thanks for reporting this to us. We are making the changing and you should be able to use `add-apt-repository` in a few days. Internally tracked at b/293924071 .

**Comment by EvanWiederspan** [comment]
This should be fixed now
