### ISSUE TITLE
Pillow default version needs upgrade

### ISSUE THREAD

**Issue by mayankagarwals** [googlecolab/colabtools#3868]
**Describe the current behavior**
The default pillow version available with Colab is 8.4.0. This version has a lot of known vulnerabilities. Please refer https://github.com/roboflow/supervision/issues/202
https://security.snyk.io/package/pip/Pillow/8.4.0

<img width="1114" alt="image" src="https://github.com/googlecolab/colabtools/assets/39498938/21ad71c7-93d7-4d17-8b84-1c24594d4b0a">

**Describe the expected behavior**
Default installation should be either not provided or be of the latest non-vulnerable version

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
https://colab.research.google.com/drive/18FgC-PR6uFUCySI3PQXLmXt9QifOlYXo?usp=sharing

**Comment by mayankmalik-colab** [comment]
Hi, thanks for reporting this to us. We have made the change and it will be reflected in 2 days.
