### ISSUE TITLE
 DNN library is not found. [Op:Conv3D]

### ISSUE THREAD

**Issue by brescianialberto** [googlecolab/colabtools#3870]
I get the following error when running a notebook under GPU but not CUP.
{{function_node __wrapped__Conv3D_device_/job:localhost/replica:0/task:0/device:GPU:0}} DNN library is not found. 
[Op:Conv3D]

the tensorflow version I am using is 2.12.0 (default)
I also forced the installation of the following builds according to the TF web page
https://www.tensorflow.org/install/source#gpu

!apt install --allow-change-held-packages libcudnn8=8.6.0.163-1+cuda11.8

can you please let me know what is wrong?
Thank you.

**Comment by mayankmalik-colab** [comment]
Can you share a min notebook that shows this error ? We would be happy to look into that.

**Comment by brescianialberto** [comment]
Hi Malik,

than you for your message.
I just found a workaround that is I run a fake tf.keras.Conv3D cell at the beginning and the error vanish...
