### ISSUE TITLE
Colab Pro Keeps crashing

### ISSUE THREAD

**Issue by Rofiatagboola** [googlecolab/colabtools#3871]
[

**Describe the current behavior**
A clear and concise explanation of what is currently happening.
I just subscribed to colab pro due to the size of my dataset, however whenever i set my runtime to GPU my notebook keeps crashing with an error that i have utilized all the  memory. However when i checked while managing session i still have enough memory. Kindly assist.
**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
I just subscribed to colab pro due to the size of my dataset, however whenever i set my runtime to GPU my notebook keeps crashing with an error that i have utilized all the  memory. However when i checked while managing session i still have enough memory. Kindly assist.
**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
[Chrome]()
**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mayankmalik-colab** [comment]
Can you provide feedback with the details. Thanks !

**Comment by weburnit** [comment]
hey guys... this shitty stuff costs me a lot of time...

**Comment by weburnit** [comment]
Google! you should kill yourself... damn it!

**Comment by weburnit** [comment]
I will completely move to Microsoft... I'm facking tire with your shitty stuff Google!

**Comment by weburnit** [comment]
i lost 3 days for nothing on Google Colab. Time is the damn crazy thing we can not recover!
