### ISSUE TITLE
Numpy function 

### ISSUE THREAD

**Issue by sairangasaketh** [googlecolab/colabtools#3872]
while using Numpy package and using the function numpy.itemsize we get output as 8 for int values
by defualt int size is 4 bytes
<img width="397" alt="image" src="https://github.com/googlecolab/colabtools/assets/111692919/da7a2b6d-10d6-4165-9f32-b65a56342be9">

**Comment by mayankmalik-colab** [comment]
If you check `a.dtype`, you would see `dtype('int64')` , which is `8` bytes. However, if you want 4 bytes as itemsize, you could use `int32` . Something like:
```
import numpy as np
a = np.array([1,2,3], dtype=np.int32)
```

So, it was basically difference between `int64` and `int32`. Hope it helps.
