### ISSUE TITLE
System doesn’t have a working snapd

### ISSUE THREAD

**Issue by abootorabi** [googlecolab/colabtools#3873]
**Describe the current behavior**
using selenium initializing a firefox webdriver gives an error :
"WebDriverException: Message: Process unexpectedly closed with status 1"

i trace this exception and i think that something is wrong with snapd. 
below are message i seen . and i mention all details in additional context
<< Command '/usr/bin/firefox' requires the firefox snap to be installed.>>
<<System doesn’t have a working snapd>>

**What web browser you are using**
Chrome

**Additional context**
you can check this  ( https://colab.research.google.com/gist/abootorabi/962e971c435bf7115cbe5ec5f4385b23/selenium_firefox.ipynb)
link and run it to reproduce the bug . 

using selenium i want to  initialize a firefox webdriver but it  gives this error :
"WebDriverException: Message: Process unexpectedly closed with status 1"

i checked geckodriver.log for more information and this message was logged  :
"
Command '/usr/bin/firefox' requires the firefox snap to be installed.
Please install it with:
snap install firefox 
"

and finaly with executing suggested command "!snap install firefox" it give this error :
"error: cannot communicate with server: Post “http://localhost/v2/snaps/firefox”: dial unix /run/snapd.socket: connect: no such file or directory"

i had to mention that when i install firefox for my colab (!apt install firefox) , i seen this message :
"
Preparing to unpack …/firefox_1%3a1snap1-0ubuntu2_amd64.deb …
=> Installing the firefox snap
==> Checking connectivity with the snap store
===> System doesn’t have a working snapd, skipping
"

**Comment by mayankmalik-colab** [comment]
We don't support `snap` by default. Sorry !
