### ISSUE TITLE
Transport End point not connected

### ISSUE THREAD

**Issue by RimshaShoukat** [googlecolab/colabtools#3874]
Collab Pro Plus is giving me a strange error. 
After 4 hours of training, it starts giving a 'file not found' error and a 'Transport endpoint not connected' error after 4hrs of training, even though the model has already run 6 epochs with the same data. I kindly request you to look into this issue. I am really worried about it as I have to submit my project as soon as possible. I hope you will review this problem and respond promptly.

**Comment by mayankmalik-colab** [comment]
dupe of https://github.com/googlecolab/colabtools/issues/3441

**Comment by cperry-goog** [comment]
This was an ephemeral issue from Drive which they resolved a few months back, closing - please do open a bug if you see it again.
