### ISSUE TITLE
Import paddle Bug

### ISSUE THREAD

**Issue by LeoKingzc1** [googlecolab/colabtools#3876]
it is the first time I met this issue and it did not happen before.

I have already installed the paddle library but when I import this library, the issue occurred.

thanks for any advice! 

<img width="1432" alt="截屏2023-07-26 09 56 17" src="https://github.com/googlecolab/colabtools/assets/88300284/5ad80703-2e34-4b56-8650-1ec76b7176d7">

<img width="1160" alt="截屏2023-07-26 09 56 30" src="https://github.com/googlecolab/colabtools/assets/88300284/919b484c-beba-443a-9b6f-65a15478c2ab">

**Comment by mayankmalik-colab** [comment]
Can you check the recommendation on their official github repo - https://github.com/PaddlePaddle/Paddle/issues/55597 . Hopefully it should work.

**Comment by LeoKingzc1** [comment]
> Can you check the recommendation on their official github repo - [PaddlePaddle/Paddle#55597](https://github.com/PaddlePaddle/Paddle/issues/55597) . Hopefully it should work.

Thank you so much, it worked!

**Comment by yonglee7015** [comment]
Why it happened in these days? Before One week ago, we just need to install paddelpaddle and paddelocr.
