### ISSUE TITLE
Relative link to sibling notebooks stopped working

### ISSUE THREAD

**Issue by patnr** [googlecolab/colabtools#3877]
**Describe the current behavior**
This [repo of notebooks](https://github.com/nansencenter/DA-tutorials) is used for teaching. The notebooks are interlinked with relative links, intended to work on Colab and a local Jupyter instances. Example: `[next chapter](next-chapter.ipynb)`. 

I have the distinct impression that this used to work (also on Colab). But now, as long as `.ipynb` is present in the link url, something called `corgiredirector` seems to get in the way, sending me to a page that says "leaving Colab" that contains a version of the link but without all of the relevant *parent* path.

**Describe the expected behavior**
When clicking such links, a new tab should open with Colab and the correct notebook.

**What web browser you are using**
Chrome

**Additional context**
Any of the notebooks in question in Colab.

**Comment by EvanWiederspan** [comment]
This has been fixed for a few days now, closing. Thanks for the report
