### ISSUE TITLE
cannot connect to Python 3 runtime but Python 2 is OK

### ISSUE THREAD

**Issue by davidkant** [googlecolab/colabtools#388]
When I open a new blank Python 3 notebook and try to connect it keeps saying "Runtime died. Automatically restarting." and then "Unable to connect." I can, however, connect to Python 2 runtime no problem. 

I'm migrating to Python 3 but have had many more connection errors than Python 2, so I'm reconsidering the migration... Is there any reason Python 3 would be buggier?

David

**Comment by davidkant** [comment]
resetting all runtimes fixed it!

**Comment by craigcitro** [comment]
No, there's no reason py2 and py3 should be any different in this regard.

A few quick questions:
 * if you `Runtime` -> `Reset all runtimes`, does this still happen?
 * are there any errors in the JS console?

**Comment by craigcitro** [comment]
Ah, sorry, half-completed entry was irrelevant when I came back and hit "comment". 😁
