### ISSUE TITLE
Unable to connect to service: error=2

### ISSUE THREAD

**Issue by DevilHunter98** [googlecolab/colabtools#3883]
[Initiating MEGAcmd server in background. Log: /root/.megaCmd/megacmdserver.log]
Unable to connect to service: error=2
Please ensure mega-cmd-server is running
Failed to create socket for registering for state changes

**Comment by EvanWiederspan** [comment]
We'll need more info to help, can you share the notebook you are running? Are you seeing this error in the output from a specific cell?

**Comment by DevilHunter98** [comment]
Sorry for my bad english i use translate google.

I do the steps to be able to transfer the files, but when using the mega cell, I get the error and a day before I didn't get that error, I use the google browser, it looks like this when I enter the page collab.

![Captura de pantalla 2023-08-03 193102](https://github.com/googlecolab/colabtools/assets/107583818/5c8fc980-01f4-434c-852d-598bd7ffe31c)

**Comment by cperry-goog** [comment]
can you share the notebook?

**Comment by pijano21** [comment]
> 

https://colab.research.google.com/drive/1gyHOtXNAJEMiWFYGjz5vHiZ_wGyGdC2_?authuser=1#scrollTo=XlDyLy_JZJ03
 I am facing the same problem.

**Comment by arunstop** [comment]
Got the same result on this previously working fine mega iypnb : 

[LINK](https://colab.research.google.com/github/cheems/Mega-to-Google-Drive/blob/master/Transfer_files_from_Mega_to_Google_Drive_old.ipynb)

**Comment by crushedoreos** [comment]
Same issue on the same notebook, was working fine until last month.

**Comment by cperry-goog** [comment]
This looks like a mega issue and the use case is very similar to use cases we ban. Feel free to contact the notebook author but I'm not going to troubleshoot this one sorry.
