### ISSUE TITLE
Can't concatenate string

### ISSUE THREAD

**Issue by dungcan2k5** [googlecolab/colabtools#3886]
These lines of code work fine on my computer, but when I upload them to google colab, it gives me error like this, I have tried several ways to fix it but it still doesn't work, please give me the solution. I use Win 10 with Edge browser
``` python
/content/download.py](https://localhost:8080/#) in download_all_images(url, foldername)
     45     threads = []
     46     # Vòng lặp từ 1 đến 198 để tạo các url theo mẫu
---> 47     for i in range(1, 300):
     48         url = f"{url}{i}.jpg"
     49         # Tạo một luồng mới với hàm download_image và tham số là url

TypeError: can only concatenate str (not "int") to str
```

**Comment by EvanWiederspan** [comment]
Converting the int to a string should fix this:

`url = f"{url}{str(i)}.jpg"`

**Comment by dungcan2k5** [comment]
> Converting the int to a string should fix this:
> 
> `url = f"{url}{str(i)}.jpg"`

I tried it, and it doesn't work :((((, from using `url = url + str(i)` and also f-strings,  I don't know why it crashes again, even though it's ok to run on my computer.

**Comment by KittyPark** [comment]
check the variable "url" is initially stored in the type "int".

**Comment by dungcan2k5** [comment]
> check the variable "url" is initially stored in the type "int".
the "url" variable is typed by the user from the keyboard, and I'm sure it's a "string" type instead of an "int"

**Comment by KittyPark** [comment]
<img width="965" alt="image" src="https://github.com/googlecolab/colabtools/assets/71093890/cc1436e9-15f9-472c-9481-6a7f6e0a944d">
I just checked and I'm doing fine ! Can you check my code ?

**Comment by dungcan2k5** [comment]
> <img width="965" alt="image" src="https://github.com/googlecolab/colabtools/assets/71093890/cc1436e9-15f9-472c-9481-6a7f6e0a944d">
> I just checked and I'm doing fine ! Can you check my code ? 

I have tried with simple programs and it runs perfectly right , but I don't understand why it doesn't work properly in this program

**Comment by KittyPark** [comment]
> > <img alt="image" width="965" src="https://user-images.githubusercontent.com/71093890/258013226-cc1436e9-15f9-472c-9481-6a7f6e0a944d.png">
> > I just checked and I'm doing fine ! Can you check my code ?
> 
> I have tried with simple programs and it runs perfectly right , but I don't understand why it doesn't work properly in this program

umm.. Sorry. I think I have to check your full code.

**Comment by dungcan2k5** [comment]
> > > <img alt="image" width="965" src="https://user-images.githubusercontent.com/71093890/258013226-cc1436e9-15f9-472c-9481-6a7f6e0a944d.png">
> > > I just checked and I'm doing fine ! Can you check my code ?
> > 
> > 
> > I have tried with simple programs and it runs perfectly right , but I don't understand why it doesn't work properly in this program
> 
> umm.. Sorry. I think I have to check your full code.

Thanks for your help. I have found the solution. When I change code in one file .py i uploaded. Google Colab not use this, It uses the original .py file that has been translated to pyc (i think so). And that workaround is we disconnect the runtime, then reconnect. Everything will be resolved. Thank you all <3

**Comment by KittyPark** [comment]
> > > > <img alt="image" width="965" src="https://user-images.githubusercontent.com/71093890/258013226-cc1436e9-15f9-472c-9481-6a7f6e0a944d.png">
> > > > I just checked and I'm doing fine ! Can you check my code ?
> > > 
> > > 
> > > I have tried with simple programs and it runs perfectly right , but I don't understand why it doesn't work properly in this program
> > 
> > 
> > umm.. Sorry. I think I have to check your full code.
> 
> Thanks for your help. I have found the solution. When I change code in one file .py i uploaded. Google Colab not use this, It uses the original .py file that has been translated to pyc (i think so). And that workaround is we disconnect the runtime, then reconnect. Everything will be resolved. Thank you all <3

I'm glad it went well.
