### ISSUE TITLE
letter "1" and letter "l" (small L) are indistinguishable 

### ISSUE THREAD

**Issue by FarzamD** [googlecolab/colabtools#3887]
when written in google colab 1 and l are the same and cant be distinguished

**Comment by blois** [comment]
Colab respects the browser's setting for the fixed-width font so you can use that to customize to a different one.

For example in Chrome:
![image](https://github.com/googlecolab/colabtools/assets/2152569/2971c186-35ec-41b6-b725-df5b836879de)
