### ISSUE TITLE
WARNING:root:kernel 

### ISSUE THREAD

**Issue by oussaifi-majdi** [googlecolab/colabtools#3888]
While running my training model with yolo-nas , I am getting runtime error saying my session is crashed. I ran multiple times in different GPU colab pro+ but getting the same erorr. I am getting error as mentioned below while running the below code:

Aug 1, 2023, 1:12:13 PM | WARNING | WARNING:root:kernel 64d26b43-fec6-4352-bdc2-0a820f7219c6 restarted

**Comment by EvanWiederspan** [comment]
We'll need more information to follow up on this bug report. Please submit feedback within Colab at Help > Send feedback.
