### ISSUE TITLE
Output is not Displaying even after a successful execution of the code. Particularly the images are not displaying at all

### ISSUE THREAD

**Issue by sandy89590** [googlecolab/colabtools#3890]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by ragman-google** [comment]
Can you please file in-product feedback, and include a shared notebook that we can look at it? Thank you.
