### ISSUE TITLE
Colab keeps disconnecting

### ISSUE THREAD

**Issue by Petykes** [googlecolab/colabtools#3891]
**Describe the current behavior**
Keeps disconnecting Colab Pro, and cant connect again

**Describe the expected behavior**

**What web browser you are using**
(Chrome,  Edge)

**Additional context**
I bought Coloab Pro because Im creating Warp Diffusion video, and after 5-6 minutes its disconnects and cant connect again.
And my hours drowning and I cant do anything

**Comment by EvanWiederspan** [comment]
We'll need more information to follow up on this bug report. Please submit feedback within Colab at Help > Send feedback.
