### ISSUE TITLE
i have upgraded to colab pro plus but still the ram is 12 gb

### ISSUE THREAD

**Issue by puneetvaza-star** [googlecolab/colabtools#3893]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
What runtime type are you selecting in the notebook settings?

Also note a high RAM assignment refers to *system* memory (as returned by `!grep MemTotal /proc/meminfo`), not *GPU* memory (as returned by `!nvidia-smi --query-gpu=memory.total --format=csv`). All GPU chips have the same memory profile.

**Comment by mpdx-mods** [comment]
Paid colabs are more close to a scam than a commercial product you can rely on.

**Comment by netanalytics** [comment]
> 

I AM AFRAID HE IS CORRECT. WHY DONT YOU MISLEAD PEOPLE, IF THEY PURCHASE THE UPGRADE YOU GIVE THE IMPRESSION OF GETTING A CERTAIN  PRODUCT. YET WHEN WE USE IT YOU MAKE UP SOME RATIONALIZATION THAT NO ONE BELIEVES. PLEASE BECOME GOOGLEY AND DONT BE EVIL . IN THE HUNGER FOR BONUS AND PERF OKR GOALS, YOU ARE LOOSING GOOGLYNESS.
