### ISSUE TITLE
OR_ISDRG_18 Error Unable to purchase additional compute units

### ISSUE THREAD

**Issue by daystromindustries** [googlecolab/colabtools#3895]
**Describe the current behavior**
When I attempt to purchase 100 additional compute units, I get an OR_ISDRG_18 error.

![agree_modal](https://github.com/googlecolab/colabtools/assets/141326836/d6c85250-da24-410d-bcbe-fe63d35dbd61)

![OR_ISDRG_18](https://github.com/googlecolab/colabtools/assets/141326836/d8544fd2-921f-4316-971a-992b82c6f3b3)

**Describe the expected behavior**
After clicking "agree" on the terms and conditions modal, I'm directed to some sort of payment page.

**What web browser you are using**
Chrome version 115.0.5790.110

**Comment by cperry-goog** [comment]
I can't diagnose this particular error from GitHub - can you submit feedback in product for us to investigate? Please reference this issue when you do.
