### ISSUE TITLE
auto-completeion(using tab) doesn't work any more

### ISSUE THREAD

**Issue by frhyme** [googlecolab/colabtools#390]
Auto-completion doesn't work any more in colab(python3) like below image.
Same menu is appeared in drill-down menu, always.

![colab_autocomplete_problem](https://user-images.githubusercontent.com/6789696/51164639-f85b8880-18e0-11e9-89f8-624458e64c11.png)

**Comment by frhyme** [comment]
Thanks for you comment. 
It is appeared while connected in colab.
After evaluating cell, it still show same drill-down menu.
I should memorize all function and object name of library I used now.

**Comment by craigcitro** [comment]
Just to confirm: are you saying that completions appear, but that they're not the functions available in your library?

In the example there, if you haven't evaluated `import networkx as nx`, python won't yet know the available attributes for completion. If you first evaluate the import and then try to complete, you should have more success.

**Comment by frhyme** [comment]
Thanks for your comment. 

For your better understanding, I attached new image.
the cell(include `import numpy as np`) was evaluated.
However, the available function or object name not appeared. 

![2019-01-15 5 54 08](https://user-images.githubusercontent.com/6789696/51169213-ac174500-18ee-11e9-8f52-a5f18c7d3728.png)

**Comment by craigcitro** [comment]
OK, fix should be live: if you go to `Runtime` -> `Reset all runtimes` and try again, everything should be back in working order. Please do reopen if it's not.

Sorry about the bug, and thanks for the report!
