### ISSUE TITLE
"Leaving Colab" page doesn't actually let you leave

### ISSUE THREAD

**Issue by khanson679** [googlecolab/colabtools#3902]
**Current behavior**
When clicking on a link in Colab, I am sent to this page: https://colab.research.google.com/corgiredirector. The only link on that page is to the Colab homepage. There is no way to actually proceed to the link destination.

**Expected behavior**
Clicking on the link should open a new page/tab with the target URL. If Google insists on inserting a "you are leaving Colab" then it should work like such pages usually do, proceeding automatically after a few seconds, with a link that you can click on immediately.

**What web browser you are using**
Firefox on Ubuntu

**Comment by katlyn-edwards** [comment]
Do you have an example notebook? 

Here's one where the links to the redirector seem to be working: https://colab.research.google.com/github/nansencenter/DA-tutorials/blob/Colab/notebooks/T1%20-%20DA%20%26%20EnKF.ipynb#scrollTo=x8406XM2V1xT

The first link is:
https://colab.research.google.com/corgiredirector?site=http%3A%2F%2Fwww.aics.riken.jp

Which seems alright to me. If you can create a repro notebook, please link it here.

**Comment by ragman-google** [comment]
Could you please share a repro notebook with us?

**Comment by khanson679** [comment]
Actually, when I click on the link you provided, I get exactly the same result as I described.
![image](https://github.com/googlecolab/colabtools/assets/12757278/0af7c9c1-25ef-4392-9f1e-103a3e071ec3)

**Comment by katlyn-edwards** [comment]
Do you have any extensions installed that could be stripping the query parameters? Can you try in an incognito window and see if it reproduces?

**Comment by khanson679** [comment]
Good thought. It looks like the extension ClearURLs is part of the problem. This is curious since it has never caused me trouble before. When disabled, the "leaving Colab" page displays the correct link.

I think this solves the main issue, though I question why the "leaving Colab" page is necessary at all, seeing as Colab is not banking website or anything along those lines. Thanks.

**Comment by katlyn-edwards** [comment]
It looks like this issue has already been filed against the CleanURLs team - https://gitlab.com/ClearURLs/ClearUrls/-/issues/1273

Thanks for the report, follow the above issue for more updates on this.
