### ISSUE TITLE
 NOT GETTING WHAT I PAID FOR

### ISSUE THREAD

**Issue by netanalytics** [googlecolab/colabtools#3909]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

I PAID FOR MONTHLY AND ADDITIONAL UNITS AND STILL NOT GETTING MORE SYSTEM MEMORY ?
WHY ?

THIS SEEMS TO BE CHEATING ? PLEASE ESCALATE AND INVESTIGATE 
I SHOULD BE GETTING AT LEAST 50 GB SYSTEM MEMORY NOT  12.7

Python 3 Google Compute Engine backend (GPU)
Showing resources from 8:42 PM to 8:44 PM
System RAM
1.8 / 12.7 GB
 
GPU RAM
0.0 / 15.0 GB
 
Disk
28.7 / 166.8 GB

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
See #3893
