### ISSUE TITLE
Scheduled notebooks

### ISSUE THREAD

**Issue by fpassantino** [googlecolab/colabtools#3910]
**Describe the current behavior**
I activated the pro version for this feature:
https://github.com/googlecolab/colabtools/wiki/Scheduled-notebooks
but i don't see it in my colab. 

**Describe the expected behavior**
What do I have to do to be able to use it?

**What web browser you are using**
Chrome, Firefox

Thanks
f

**Comment by cperry-goog** [comment]
scheduled notebooks are Pro+ only: are you Pro or Pro+?

**Comment by fpassantino** [comment]
Pro!
Thahk you

**Comment by dittomike** [comment]
I just signed up and this is exactly what happened to me.
I have setup notebook to run every hour and then sleep.
If I didnt have the Pro would the notebook terminate after 12hrs.
If that is the case then I dont mind the fact that I had to run a sleep function to keep it going.
