### ISSUE TITLE
Colab - Plantuml using iplantuml

### ISSUE THREAD

**Issue by egrpy** [googlecolab/colabtools#3914]
**Describe the current behavior**
Google Colab
Started with:
!pip install --upgrade iplantuml
import iplantuml
%load_ext iplantuml

Get this:
Requirement already satisfied: iplantuml in /usr/local/lib/python3.10/dist-packages (0.1.1)
Requirement already satisfied: plantweb in /usr/local/lib/python3.10/dist-packages (from iplantuml) (1.2.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from plantweb->iplantuml) (1.16.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from plantweb->iplantuml) (2.27.1)
Requirement already satisfied: docutils in /usr/local/lib/python3.10/dist-packages (from plantweb->iplantuml) (0.18.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->plantweb->iplantuml) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->plantweb->iplantuml) (2023.7.22)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->plantweb->iplantuml) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->plantweb->iplantuml) (3.4)
The iplantuml module is not an IPython extension.

**Describe the expected behavior**
Clone Github to:
/content/UUMF/uumf_classes.puml

**What web browser you are using**
Chrome

**Additional context**
Trying to execute:
%%plantuml
@startuml
!include /content/UUMF/uumf_classes.puml
@enduml

and get:
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-10-42c1987c3272>](https://localhost:8080/#) in <cell line: 1>()
----> 1 get_ipython().run_cell_magic('plantuml', '', '@startuml\n!include /content/UUMF/uumf_classes.puml\n@enduml\n')

5 frames
[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in check_call(*popenargs, **kwargs)
    367         if cmd is None:
    368             cmd = popenargs[0]
--> 369         raise CalledProcessError(retcode, cmd)
    370     return 0
    371 

CalledProcessError: Command '['plantweb', '--format', 'auto', 'a9aa3323-01cf-4f80-a761-510df552869f.uml']' returned non-zero exit status 1.

This script run ok if I used:
!include https://raw.githubusercontent.com/egrpy/UUMF/main/uumf_classes.puml?token=GHSAAAAACGCEGQ356TJMKU2ZZGXGSOQZGSMXYQ

**Comment by cperry-goog** [comment]
The last release of iplantuml was in 2017 (link: https://pypi.org/project/IPlantUML/#history), so this library is likely not compatible with the ecosystem. You'll want to contact the library maintainers.
