### ISSUE TITLE
autodisconnect after 10 mon

### ISSUE THREAD

**Issue by devdeep135468** [googlecolab/colabtools#3919]
**Describe the current behavior**
i am currently using fast_stable_diffusion_AUTOMATIC in which after 10 min the gpu automatic disconnected 
**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(brave.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
We limit stable diffusion webui usage to paid tier so we can prioritize interactive notebook compute for our free tier users.

**Comment by devdeep135468** [comment]
so sad for us like student 😞

**Comment by devdeep135468** [comment]
i have one more question it is happing only with me or others also suffering
