### ISSUE TITLE
After some time colab tries to find "client_secrets.json" and failes

### ISSUE THREAD

**Issue by edenrose** [googlecolab/colabtools#392]
I wrote a script that goes over csv files containing image URLs, downloads the images, and uploades to Google Drive.

I used the following code for authentication (took it from the code snippets in colab):
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

I tried to run it in google colab notebook and after some time (It does not feel faster than cpu by the way) it started to throw errors about "client_secrets.json" not found, and it failed with those errors.

According to google cloude documentaion :"If the environment variable isn't set, ADC uses the default service account that Compute Engine, Kubernetes Engine, App Engine, and Cloud Functions provide, for applications that run on those services." 
If I understand correctly it shouldn't need that file, Also it worked just fine for about 2 hours before that.

Will appreciate your help, it keeps happening and i can't run my script properly.
Thanks,
Eden.

**Comment by craigcitro** [comment]
Can you share a notebook that reproduces the problem (and includes the error you're seeing)?

**Comment by edenrose** [comment]
Hey, sorry it took so long
The notebook with the errors is attached

‫בתאריך יום ה׳, 17 בינו׳ 2019 ב-1:49 מאת ‪Craig Citro‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by edenrose** [comment]
If it helps I managed to workaround it so that the script will run, it
still throws errors but it does not crash.

‫בתאריך יום א׳, 27 בינו׳ 2019 ב-22:37 מאת עדן רוזנטל <‪
eden2rosenthal@gmail.com‬‏>:‬

**Comment by craigcitro** [comment]
I don't think github can handle an email attachment.

Could you share a link to a public colab notebook?

**Comment by edenrose** [comment]
with problem:
https://colab.research.google.com/drive/1dFk0PWAz_vyDs8Uyp9O5VHuqWzFb78-U

workaround:
https://colab.research.google.com/drive/1En0Bic9V395uMtSAj24RpIrBnFZXljOJ

‫בתאריך יום ב׳, 28 בינו׳ 2019 ב-1:48 מאת ‪Craig Citro‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by joker2017** [comment]
I have the same problem. Found a solution?

**Comment by mvbattan** [comment]
An update on this issue:
Seems that this piece of code works on some instances but not on others:
```
!pip install PyDrive

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

import pandas as pd
import timeit
import datetime

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
gdrive = GoogleDrive()

FILENAME = 'data_science_exercise_dataset (3) (1) (1).csv'
ID = '0B5V7cwxRp9bJemVYQy1lRkcyWkM4OWRGMFU4VEpYTWtpR2VJ'

downloaded = gdrive.CreateFile({ id: ID })
downloaded.GetContentFile(FILENAME)

df.read_csv(FILENAME)
df.sample(n=20)
```
The error I get if it fails:
```
FileNotFoundError                         Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/oauth2client/clientsecrets.py in _loadfile(filename)
    120     try:
--> 121         with open(filename, 'r') as fp:
    122             obj = json.load(fp)

FileNotFoundError: [Errno 2] No such file or directory: 'client_secrets.json'

During handling of the above exception, another exception occurred:

InvalidClientSecretsError                 Traceback (most recent call last)
10 frames
InvalidClientSecretsError: ('Error opening file', 'client_secrets.json', 'No such file or directory', 2)

During handling of the above exception, another exception occurred:

InvalidConfigError                        Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/pydrive/auth.py in LoadClientConfigFile(self, client_config_file)
    386       client_type, client_info = clientsecrets.loadfile(client_config_file)
    387     except clientsecrets.InvalidClientSecretsError as error:
--> 388       raise InvalidConfigError('Invalid client secrets file %s' % error)
    389     if not client_type in (clientsecrets.TYPE_WEB,
    390                            clientsecrets.TYPE_INSTALLED):

InvalidConfigError: Invalid client secrets file ('Error opening file', 'client_secrets.json', 'No such file or directory', 2)
```

**Comment by TA40** [comment]
Still a problem

**Comment by craigcitro** [comment]
Can someone share a self-contained repro notebook, either as a publicly readable drive notebook or as a gist?

**Comment by TA40** [comment]
Problem is that I don't know what affects it. After some time it tries to refresh the token and looks for the client_secrets.json which is not available and outputs the error above.
Maybe it will reproduce itself with this script after some time: https://colab.research.google.com/gist/TA40/5ce3d978e6d825bebc7488d1d14ed02a/client_secrets_reproduction.ipynb

What I did was writing the client_secrets.json with this data:
`{"web": {"client_id": "32555940559.apps.googleusercontent.com", "project_id": "powershell", "auth_uri": "https://accounts.google.com/o/oauth2/auth", "token_uri": "https://oauth2.googleapis.com/token", "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs", "client_secret": "ZmssLNjJy2998hD4CTg2ejr2", "redirect_uris": ["urn:ietf:wg:oauth:2.0:oob", "http://localhost"]}}`
(Taken from https://www.powershellgallery.com/packages/gOAuth/1.0.0/Content/gOAuth.psm1)
This fixed the issue for me (I hope, didn't run it long enough probably).

**Comment by guru1150** [comment]
any update on this issue, is there any solutions

**Comment by craigcitro** [comment]
I'd try reporting upstream to pydrive.
