### ISSUE TITLE
saving to google drive not working while background execution

### ISSUE THREAD

**Issue by xerxes-k** [googlecolab/colabtools#3920]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

trying to save file to google drive while drive is mounted.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

a file saved to designated google drive folder

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

* saving to google drive works when i'm online and manually click it.
* drive is mounted and kept mounted.

**Comment by xerxes-k** [comment]
using colab pro +

**Comment by cperry-goog** [comment]
Do you have a link to a minimal reproducible notebook? We've never encountered this issue.

**Comment by xerxes-k** [comment]
i'd like to give you a link but my notebook contains private data. is there any way i can show you the problem without giving the actual notebook?

it's basically like this:

cell 1 : google drive mount
cell 2 : calculation
cell 3 : save calculation result to google drive

the problem occurs in cell 3. **cell 2 calculation takes about 10 or more hours** so, i leave after running all the cells. and i expect when i comeback, cell 3 ran accordingly and saved the data. 
but when i comeback i usually find either 

1. cell 3 running for ages without saving anything, or
2. nothing is running. connection is lost. data not saved.

if it's case 1, i stop the running cell 3 and manually run the same code myself, and it saves the data right away.
if it's case 2, i have to run the whole thing again. which means computing unit wasted.

another issue is that, because i've encountered this several times now, i make cell 2 calculation to print() the gist at the end.
but oddly, after the cell 2 completed its running in the background, nothing is left to see when i come back. i tested this method with the chrome open (so, not background) and the gist got printed just below the cell as expected. but when i'm off and cells run background, the results are not there. which is doubly frustrating.

**Comment by metrizable** [comment]
@xerxes-k Thanks for providing a high-level description of your use case. I think it would speed our troubleshooting if you could provide a non-personalized example notebook if possible.

**Comment by cperry-goog** [comment]
Duping with #3785
