### ISSUE TITLE
My colab code block are cut off and i can't read

### ISSUE THREAD

**Issue by Macorte** [googlecolab/colabtools#3921]
My google colab code blocks is like this and I can't use it, I already try reset the browser cache and I see all colab customization:

<img width="640" alt="image" src="https://github.com/googlecolab/colabtools/assets/62664736/b3b24025-5b55-4717-a94f-b0b311138750">

Can anyone help me to resolve this, I tried everything and nothing works

**Comment by EvanWiederspan** [comment]
This seems similar to https://github.com/googlecolab/colabtools/issues/3798

Can you try this in an incognito window? There could be a browser extension that is causing this.

**Comment by Macorte** [comment]
i uninstalled the extensions and it worked
