### ISSUE TITLE
Something went wrong Connection errored out.

### ISSUE THREAD

**Issue by minggnim56** [googlecolab/colabtools#3923]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
We'll need a reproducible notebook that consistently demonstrates this issue, or submit in-product feedback

**Comment by minggnim56** [comment]
What's a, "reproducible notebook"?
