### ISSUE TITLE
Collab Pro+ notebook/VM keeps getting disconected

### ISSUE THREAD

**Issue by dan-lannes** [googlecolab/colabtools#3926]
**Describe the current behavior**
Everytime I try to have a notebook running in the backgroung - by shutting down my laptop, closing my browser or even closing the lid - I end up losing my progress and wasting my compute units... 
This will happen in small amounts of time for ex 5-20 minutes after, If I keep a tab open and do other things, everything will be fine.

**Describe the expected behavior**
I subscribed to a Pro+ account for the benefit of background execution, which does not seem to work for me.

**What web browser you are using**
Chrome.

**Comment by mo-nathan** [comment]
I just upgraded to Pro so I could do a real run of an image classifier with 450K images and 1200 labels.  Got them all loaded.  Did 10 epochs successfully each taking 40 minutes.  End up using 30% of my compute units.  Then it disconnected and apparently threw everything away.  Very disappointing.  Seems like a total waste of my money.

**Comment by dan-lannes** [comment]
@mo-nathan in your case I'm guessing you would need to upgrade to a Pro+ account, to be able to run it in the background, just like I did.  Too bad I can't get it to work properly....

**Comment by mo-nathan** [comment]
Thanks!  It made me a lot more paranoid and I no longer try to run a single cell at a time in my notebook, but instead submit a script that automatically exports the model results.  This got me to a good enough place that I now need to do a bunch of evaluation of the resulting model.  At this point I assume I just hit some very short timeout on the Pro account.

**Comment by metrizable** [comment]
@dan-lannes Thanks for filing the issue and thanks for using Colab. Please provide in-product feedback as we cannot troubleshoot these kinds of issues from GitHub.
