### ISSUE TITLE
Sorry, no backends is available . Please try again later 

### ISSUE THREAD

**Issue by AnjanSRG7** [googlecolab/colabtools#3930]
Hi Team,
I am unable to execute the code from colab. 
https://colab.research.google.com/github/GoogleCloudPlatform/generative-ai/blob/main/language/intro_prompt_design.ipynb#scrollTo=82ad0c445061

Below is the error .
Sorry , no backend is available . Please try again later .

Thanks

**Comment by metrizable** [comment]
Please provide in-product feedback as we cannot troubleshoot this specific issue from GitHub.
