### ISSUE TITLE
intro to fairness, numpy has no attribute 'asscalar'

### ISSUE THREAD

**Issue by tillrein** [googlecolab/colabtools#3931]
Hi, in the https://colab.research.google.com/github/google/eng-edu/blob/main/ml/cc/exercises/intro_to_ml_fairness.ipynb?utm_source=mlcc&utm_campaign=colab-external&utm_medium=referral&utm_content=fairness_tf2-colab&hl=en#scrollTo=MW-qryqs1gig colab it's not possible to execute 3-rd block 
`#@title Visualize the Data in Facets
fsg = FeatureStatisticsGenerator()
dataframes = [
    {'table': train_df, 'name': 'trainData'}]
censusProto = fsg.ProtoFromDataFrames(dataframes)
protostr = base64.b64encode(censusProto.SerializeToString()).decode("utf-8")
HTML_TEMPLATE = """<script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/1.3.3/webcomponents-lite.js"></script>
        <link rel="import" href="https://raw.githubusercontent.com/PAIR-code/facets/1.0.0/facets-dist/facets-jupyter.html">
        <facets-overview id="elem"></facets-overview>
        <script>
          document.querySelector("#elem").protoInput = "{protostr}";
        </script>"""
html = HTML_TEMPLATE.format(protostr=protostr)
display(HTML(html))`, the error is module 'numpy' has no attribute 'asscalar'

**Comment by metrizable** [comment]
@tillrein Thanks for reporting the issue and supplying the notebook. I was not able to replicate the issue you reported.

![7mpoGhYuLTcjayG](https://github.com/googlecolab/colabtools/assets/65414824/00505164-a9c8-422b-a6d0-a524ffa17349)

I would confirm that there were no other executions performed in the same session, such as installing a different version of numpy.
