### ISSUE TITLE
Bug with installation of texthero and gensim

### ISSUE THREAD

**Issue by Alimiji** [googlecolab/colabtools#3933]
Hi,
I have a bug with nstallation of texthero and gensim on google colab.

Collecting gensim==3.8.3
  Using cached gensim-3.8.3.tar.gz (23.4 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.11.3 in /usr/local/lib/python3.10/dist-packages (from gensim==3.8.3) (1.25.2)
Requirement already satisfied: scipy>=0.18.1 in /usr/local/lib/python3.10/dist-packages (from gensim==3.8.3) (1.11.1)
Requirement already satisfied: six>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from gensim==3.8.3) (1.16.0)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.10/dist-packages (from gensim==3.8.3) (6.3.0)
Building wheels for collected packages: gensim
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for gensim (setup.py) ... error
  ERROR: Failed building wheel for gensim
  Running setup.py clean for gensim
Failed to build gensim
ERROR: Could not build wheels for gensim, which is required to install pyproject.toml-based projects

**Comment by mayankmalik-colab** [comment]
`texthero` is trying to install  `gensim==3.8.3`, which was released 2 years back and is [not compatible with python 3.10](https://pypi.org/project/gensim/3.8.3/). Also, it seems like `texthero` is not maintained much. I would recommend reaching out to the package owner.
