### ISSUE TITLE
How do I install CUDA 11.1 on colab?

### ISSUE THREAD

**Issue by justinjohn0306** [googlecolab/colabtools#3939]

**Comment by mayankmalik-colab** [comment]
We are on cuda 11.8 and is compatible with current cudnn version and our ecosystem in general. Hence, I would not recommend downgrading cuda.

**Comment by justinjohn0306** [comment]
I need it for a specific project which requires cuda 11.1...

**Comment by cook-kuk** [comment]
!wget https://developer.download.nvidia.com/compute/cuda/11.1.0/local_installers/cuda-repo-ubuntu1804-11-1-local_11.1.0-455.23.05-1_amd64.deb 
!dpkg -i cuda-repo-ubuntu1804-11-1-local_11.1.0-455.23.05-1_amd64.deb 
!apt-key add /var/cuda-repo-ubuntu1804-11-1-local/7fa2af80.pub 
!apt-get update 
!apt-get install cuda-11-1 
!export CUDA_PATH=/usr/local/cuda-11.1
!nvcc --version

**Comment by AinazRafiei** [comment]
This is not a way to install cuda on colab.Its for local machine.Not helping

> !wget https://developer.download.nvidia.com/compute/cuda/11.1.0/local_installers/cuda-repo-ubuntu1804-11-1-local_11.1.0-455.23.05-1_amd64.deb !dpkg -i cuda-repo-ubuntu1804-11-1-local_11.1.0-455.23.05-1_amd64.deb !apt-key add /var/cuda-repo-ubuntu1804-11-1-local/7fa2af80.pub !apt-get update !apt-get install cuda-11-1 !export CUDA_PATH=/usr/local/cuda-11.1 !nvcc --version
