### ISSUE TITLE
Can`t create notebook

### ISSUE THREAD

**Issue by LilyZWuZz** [googlecolab/colabtools#394]
Error loading https://apis.google.com/js/client.js
Error: Error loading https://apis.google.com/js/client.js
    at HTMLScriptElement.f.onerror (https://colab.research.google.com/v2/external/gapi_loader.js:9:415)

**Comment by blois** [comment]
Can you try from an incognito browser window?

**Comment by DenisSouth** [comment]
Update your chrome browser
