### ISSUE TITLE
Transport endpoint is not connected Issue

### ISSUE THREAD

**Issue by GhadaElshamy** [googlecolab/colabtools#3940]
I have colab pro+ subscription and the notebook keeps giving me "Transport endpoint is not connected" when trying to write my training results on a file. The training time is almost 4.5 hours it did not behave like that earlier, I ran my training three time so my units have been deduced with every run and I couldn't get my results. Please help me in this I have already lost about 400 units with no output.

**Comment by metrizable** [comment]
@GhadaElshamy Thanks for reporting the issue and thanks for using Colab. Please provide in-product feedback as we cannot troubleshoot these kinds of issues from GitHub.
