### ISSUE TITLE
Flickering Colab Screen in MacBook Pro using Safari

### ISSUE THREAD

**Issue by ThisNameWasAvailable** [googlecolab/colabtools#3943]
**Describe the current behavior**
Flickering Colab Screen with python script on new MacBook Pro using Safari

Pls see Dropbox video:
https://www.dropbox.com/scl/fi/l8u0mwmjgc3vjmofek3bo/Colab-not-working-in-Safari-Browser-juddering-flashing.mov

**Describe the expected behavior**
A still screen.

**What web browser you are using**
( Safari brand new MacBook Pro)

**Comment by cperry-goog** [comment]
Can you attach the video directly? We don't have dropbox sorry.

**Comment by ThisNameWasAvailable** [comment]
You don’t need dropbox, just hit “x” in the top right of the pop up box where it says:

Get more space and powerful productivity features by upgrading your Dropbox.

and the video plays through the web browser.

https://www.dropbox.com/scl/fi/l8u0mwmjgc3vjmofek3bo/Colab-not-working-in-Safari-Browser-juddering-flashing.mov?rlkey=au47wuhqvlwl434t17sk21tgi&dl=0￼
Colab not working in Safari Browser - juddering:flashing.mov
dropbox.com

**Comment by katlyn-edwards** [comment]
Does this happen with every notebook, or a specific one? 

I can't repro, I'm using:
Safari Version 16.6 (18615.3.12.11.2)
MacOS Ventura 13.5.1 

Can you include the specifics of your Safari + macOS ?
Does it reproduce in a private window? If not, it might be a safari extension that's installed.

**Comment by Top-Gun-Maxverick** [comment]
can confirm issue still hasn't been resolved
