### ISSUE TITLE
CPU inconsistency?

### ISSUE THREAD

**Issue by azr120** [googlecolab/colabtools#3951]
Hello, I'm using Chrome with Colab Pro and trying to train a DQN agent but CPU usage is very incosistent. 

My primary concern revolves around using the maximum replay buffer size w.r.t. the CPU resources I am allocated. In previous instances, when using a runtime with 26gb, I could train the DQN with a max replay buffer of 70k, although this was not consistent:

![Screenshot 2023-08-02 222526](https://github.com/googlecolab/colabtools/assets/76614662/5ce7d146-068b-4ec7-8e3d-85c55d18b03e)

Despite zero differences in the code between these runs, apart from the 3rd run the rest spiked to max cpu very early (15k steps), while the third run reached 500k steps. Recently I am being given 51gb of cpu, so I tested 150k replay buffer size and it worked smoothly (600k steps, cpu usage plateaued at 26gb). However, since that time, every attempt I've made with 51gb ram and 150 rep buffer led to an early CPU spike to 51gb.

I believe I don't have a memory leakage issue as smaller buffer sizes do run fine (e.g. 50k or 100k). Given that some runs with the same settings ran succesfully, could this be an issue on Colab's site?

**Comment by sebbov** [comment]
Can you compare `/proc/cpuinfo` (`model name`, `cpu MHz`, etc.)?  Perhaps differences are explained by differences in CPU platform (https://cloud.google.com/compute/docs/cpu-platforms#x86_processors).  These are expected to vary between runs.  We can't provide guarantees on what you land on.
