### ISSUE TITLE
TPU deadlocks all the time

### ISSUE THREAD

**Issue by krahnikblis** [googlecolab/colabtools#3952]
**Describe the current behavior**
often a cell will take a long time to run. there's no way to replicate, other than play with my existing, working code for an hour or whatever till something takes too long. once it does, when i check Runtime > View Runtime Logs, it shows that for every 10 seconds there's a warning saying there's a deadlock, e.g.:
```
Aug 20, 2023, 5:54:14 PM | WARNING | 2023-08-20 22:54:14.269232: W external/org_tensorflow/tensorflow/compiler/xla/python/tpu_driver/client/tpu_client.cc:617] TPU Execute is taking a long time. This might be due to a deadlock between multiple TPU cores or a very slow program.
Aug 20, 2023, 5:54:04 PM | WARNING | 2023-08-20 22:54:04.269007: W external/org_tensorflow/tensorflow/compiler/xla/python/tpu_driver/client/tpu_client.cc:617] TPU Execute is taking a long time. This might be due to a deadlock between multiple TPU cores or a very slow program.
Aug 20, 2023, 5:53:54 PM | WARNING | 2023-08-20 22:53:54.268844: W external/org_tensorflow/tensorflow/compiler/xla/python/tpu_driver/client/tpu_client.cc:617] TPU Execute is taking a long time. This might be due to a deadlock between multiple TPU cores or a very slow program.
Aug 20, 2023, 5:53:44 PM | WARNING | 2023-08-20 22:53:44.268649: W external/org_tensorflow/tensorflow/compiler/xla/python/tpu_driver/client/tpu_client.cc:617] TPU Execute is taking a long time. This might be due to a deadlock between multiple TPU cores or a very slow program.
Aug 20, 2023, 5:53:34 PM | WARNING | 2023-08-20 22:53:34.268489: W external/org_tensorflow/tensorflow/compiler/xla/python/tpu_driver/client/tpu_client.cc:617] TPU Execute is taking a long time. This might be due to a deadlock between multiple TPU cores or a very slow program.
Aug 20, 2023, 5:53:24 PM | WARNING | 2023-08-20 22:53:24.268310: W external/org_tensorflow/tensorflow/compiler/xla/python/tpu_driver/client/tpu_client.cc:617] TPU Execute is taking a long time. This might be due to a deadlock between multiple TPU cores or a very slow program.
Aug 20, 2023, 5:53:14 PM | WARNING | 2023-08-20 22:53:14.268079: W external/org_tensorflow/tensorflow/compiler/xla/python/tpu_driver/client/tpu_client.cc:617] TPU Execute is taking a long time. This might be due to a deadlock between multiple TPU cores or a very slow program.
Aug 20, 2023, 5:53:04 PM | WARNING | 2023-08-20 22:53:04.267905: W external/org_tensorflow/tensorflow/compiler/xla/python/tpu_driver/client/tpu_client.cc:617] TPU Execute is taking a long time. This might be due to a deadlock between multiple TPU cores or a very slow program.
Aug 20, 2023, 5:52:54 PM | WARNING | 2023-08-20 22:52:54.267686: W external/org_tensorflow/tensorflow/compiler/xla/python/tpu_driver/client/tpu_client.cc:617] TPU Execute is taking a long time. This might be due to a deadlock between multiple TPU cores or a very slow program.
Aug 20, 2023, 5:52:44 PM | WARNING | 2023-08-20 22:52:44.267483: W external/org_tensorflow/tensorflow/compiler/xla/python/tpu_driver/client/tpu_client.cc:617] TPU Execute is taking a long time. This might be due to a deadlock between multiple TPU cores or a very slow program.
```

**NOTE: i'm not even using TensorFlow, so not sure why this error from TF is even here, i'm using JAX (and on that, it's the obsolete JAX version that comes with colab, not the latest version)**

**Describe the expected behavior**
JAX and TPUs do their jobs reliably. if something gets hung up, it should pop up a notification so i don't WASTE ALL MY PAID TIME

**What web browser you are using**
Brave

**Additional context**
can't reliably replicate. just happens all the time, but randomly. especially with bigger models that take 3-5 minutes to load parameters, meanwhile my "compute units" tick away. is there a way to get credit for all the hours that this happens???  i'm soooo sick of having to restart everything and pay double for the time to reload stuff...

**Comment by skye** [comment]
Skye from the jax team here. Colab TPU is currently still on the legacy TPU Node architecture, which is no longer supported by jax (that's why you have to use an old jax version, newer versions don't work at all). It's unfortunately very hard for us to debug this kind of issue, which is why we only support the new TPU VM architecture now. Colab is working on upgrading.

As a temporary solution until Colab switches to TPU VMs, I recommend trying Kaggle Notebooks, which do support TPU VMs and thus newer jax versions as well. You can go to https://www.kaggle.com/code and click on "New Notebook" near the top. You have to create an account and log in to get accelerator support. Once you do that, there's a "TPU VM v3-8" accelerator option. This gives you a TPU notebook environment similar to Colab, but using the newer TPU VM architecture. This should be a less buggy, more performant, and overall better experience than the older TPU Node architecture (see [this blog post](https://cloud.google.com/blog/products/compute/introducing-cloud-tpu-vms) for a brief overview of the difference).

Sorry for the less-than-optimal situation here. If you do give Kaggle Notebooks a shot, I'd be interested to hear if it works well for you or not.

**Comment by krahnikblis** [comment]
@skye thanks for the explanation, (and i'm a big fan of Jax and i'm trying hard to learn all this in my spare time and it's complex and brilliant so thanks for all you do) ... 

[deleted tirade about the Google suite of products and services i pay for and the frustrating experience of not being able to use them seamlessly together **as they are marketed to be**] 

... maybe i _would_ like the competing platform/service better, but a company that names themselves that way **clearly** didn't look around or think ahead or check with the snickering schoolkids, so i'm not interested to give them a chance at my money or my PII. just like the facehuggers. i can't take a company seriously if it names itself as a joke (unless its business is comedy)... 

anyway, what's the ETA for better google hardware to go with my google software and service?

PS to the Colab folks watching, here's one vote for getting yourselves an actual customer/technical support platform, instead of asking your customers to create an account with MS and post their technical issues in public...
