### ISSUE TITLE
All my files are gone from Colabs within 12 hours

### ISSUE THREAD

**Issue by MorsMagne** [googlecolab/colabtools#3953]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mayankmalik-colab** [comment]
Can you provide more details? Did you still have the runtime connected after 12 hours? If not, then after every reconnect, you would get a new runtime and so files won't persist.

**Comment by MorsMagne** [comment]
Don't worry about it!
