### ISSUE TITLE
Co Lab pro Not using GPU power efficiently very low resources use.  Env: v100-High RAM on chrome browser Mac OS

### ISSUE THREAD

**Issue by Lasanthasanjayasenaratharachchi** [googlecolab/colabtools#3954]
Tensorflow BERT training very slow. Note book does not use the available GPU even RAM

**Comment by cperry-goog** [comment]
I don't have a way to debug this; you'll want to contact the notebook author or if you can provide a minimal notebook that doesn't correctly utilize a GPU we'd be curious.
