### ISSUE TITLE
NansException problem and GPU limit problem

### ISSUE THREAD

**Issue by lumite1000** [googlecolab/colabtools#3959]
![image](https://github.com/googlecolab/colabtools/assets/96490287/b33ee155-9a90-468d-9aad-945ef4ac8b47)

I didn't find a solution for this. With colab I can't use the normal solution that the text says, so what can i do?

Also, I get the message that I have reached the limit of use when due to the first error I have not been able to do anything.

**Comment by cperry-goog** [comment]
I don't think this is a Colab specific issue; you might want to try StackOverflow.
