### ISSUE TITLE
Frequent connection aborted error in Google Colab

### ISSUE THREAD

**Issue by Rajsekharknath** [googlecolab/colabtools#3962]
**I am a Google Colab Pro+ user**
I have been training models on Vehicle Re-identification on Colab. Recently, however, I have noticed that the training stops after some epochs like a time out thing and the connection to the dataloader is lost. The error along with the output is given below. The error happens at around 50 epochs.
<ipython-input-3-797ef1595486>:21: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.weight.data, 1)
<ipython-input-3-797ef1595486>:22: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias.data, 0)
<ipython-input-3-797ef1595486>:28: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, std=0.001)
<ipython-input-3-797ef1595486>:29: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias.data, 0.0)
Epoch 0/59
----------
/usr/local/lib/python3.10/dist-packages/torch/optim/lr_scheduler.py:139: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
train Loss: 0.1830 Acc: 0.9991
val Loss: 0.0727 Acc: 1.0000

Epoch 1/59
----------
train Loss: 0.2673 Acc: 0.9990
val Loss: 0.1058 Acc: 1.0000

Epoch 2/59
----------
train Loss: 0.2834 Acc: 0.9992
val Loss: 0.1040 Acc: 1.0000

Epoch 3/59
----------
train Loss: 0.2804 Acc: 0.9993
val Loss: 0.1077 Acc: 1.0000

Epoch 4/59
----------
train Loss: 0.2801 Acc: 0.9996
val Loss: 0.0909 Acc: 1.0000

Epoch 5/59
----------
train Loss: 0.2791 Acc: 0.9992
val Loss: 0.0882 Acc: 1.0000

Epoch 6/59
----------
train Loss: 0.2748 Acc: 0.9993
val Loss: 0.0904 Acc: 1.0000

Epoch 7/59
----------
train Loss: 0.2723 Acc: 0.9994
val Loss: 0.0873 Acc: 1.0000

Epoch 8/59
----------
train Loss: 0.2673 Acc: 0.9994
val Loss: 0.0816 Acc: 1.0000

Epoch 9/59
----------
train Loss: 0.2623 Acc: 0.9995
val Loss: 0.0813 Acc: 1.0000

Epoch 10/59
----------
train Loss: 0.2634 Acc: 0.9994
val Loss: 0.0773 Acc: 1.0000

Epoch 11/59
----------
train Loss: 0.2605 Acc: 0.9995
val Loss: 0.0733 Acc: 1.0000

Epoch 12/59
----------
train Loss: 0.2588 Acc: 0.9993
val Loss: 0.0793 Acc: 1.0000

Epoch 13/59
----------
train Loss: 0.2600 Acc: 0.9996
val Loss: 0.0881 Acc: 1.0000

Epoch 14/59
----------
train Loss: 0.2620 Acc: 0.9994
val Loss: 0.0732 Acc: 1.0000

Epoch 15/59
----------
train Loss: 0.2551 Acc: 0.9993
val Loss: 0.0655 Acc: 1.0000

Epoch 16/59
----------
train Loss: 0.2554 Acc: 0.9994
val Loss: 0.0773 Acc: 1.0000

Epoch 17/59
----------
train Loss: 0.2545 Acc: 0.9994
val Loss: 0.0758 Acc: 1.0000

Epoch 18/59
----------
train Loss: 0.2580 Acc: 0.9997
val Loss: 0.0679 Acc: 1.0000

Epoch 19/59
----------
train Loss: 0.2594 Acc: 0.9992
val Loss: 0.0761 Acc: 1.0000

Epoch 20/59
----------
train Loss: 0.2571 Acc: 0.9994
val Loss: 0.0652 Acc: 1.0000

Epoch 21/59
----------
train Loss: 0.2630 Acc: 0.9994
val Loss: 0.0665 Acc: 1.0000

Epoch 22/59
----------
train Loss: 0.2638 Acc: 0.9994
val Loss: 0.0716 Acc: 1.0000

Epoch 23/59
----------
train Loss: 0.2660 Acc: 0.9992
val Loss: 0.0713 Acc: 1.0000

Epoch 24/59
----------
train Loss: 0.2686 Acc: 0.9989
val Loss: 0.0784 Acc: 1.0000

Epoch 25/59
----------
train Loss: 0.2706 Acc: 0.9990
val Loss: 0.0750 Acc: 1.0000

Epoch 26/59
----------
train Loss: 0.2781 Acc: 0.9988
val Loss: 0.0877 Acc: 1.0000

Epoch 27/59
----------
train Loss: 0.2834 Acc: 0.9990
val Loss: 0.0868 Acc: 0.9983

Epoch 28/59
----------
train Loss: 0.2838 Acc: 0.9988
val Loss: 0.0911 Acc: 1.0000

Epoch 29/59
----------
train Loss: 0.2958 Acc: 0.9986
val Loss: 0.0786 Acc: 1.0000

Epoch 30/59
----------
train Loss: 0.2974 Acc: 0.9983
val Loss: 0.0962 Acc: 1.0000

Epoch 31/59
----------
train Loss: 0.3073 Acc: 0.9979
val Loss: 0.1428 Acc: 0.9983

Epoch 32/59
----------
train Loss: 0.3152 Acc: 0.9980
val Loss: 0.0949 Acc: 1.0000

Epoch 33/59
----------
train Loss: 0.3108 Acc: 0.9979
val Loss: 0.1092 Acc: 1.0000

Epoch 34/59
----------
train Loss: 0.3190 Acc: 0.9976
val Loss: 0.1079 Acc: 1.0000

Epoch 35/59
----------
train Loss: 0.3304 Acc: 0.9975
val Loss: 0.1509 Acc: 0.9983

Epoch 36/59
----------
train Loss: 0.3420 Acc: 0.9963
val Loss: 0.1345 Acc: 1.0000

Epoch 37/59
----------
train Loss: 0.3357 Acc: 0.9975
val Loss: 0.1176 Acc: 1.0000

Epoch 38/59
----------
train Loss: 0.3525 Acc: 0.9965
val Loss: 0.1281 Acc: 1.0000

Epoch 39/59
----------
train Loss: 0.2259 Acc: 0.9993
val Loss: 0.0475 Acc: 1.0000

Epoch 40/59
----------
train Loss: 0.1996 Acc: 0.9998
val Loss: 0.0478 Acc: 1.0000

Epoch 41/59
----------
train Loss: 0.1946 Acc: 0.9998
val Loss: 0.0471 Acc: 1.0000

Epoch 42/59
----------
train Loss: 0.1902 Acc: 0.9999
val Loss: 0.0475 Acc: 1.0000

Epoch 43/59
----------
train Loss: 0.1913 Acc: 0.9999
val Loss: 0.0462 Acc: 1.0000

Epoch 44/59
----------
train Loss: 0.1948 Acc: 0.9998
val Loss: 0.0531 Acc: 1.0000

Epoch 45/59
----------
train Loss: 0.1917 Acc: 0.9998
val Loss: 0.0472 Acc: 1.0000

Epoch 46/59
----------
train Loss: 0.1922 Acc: 0.9998
val Loss: 0.0497 Acc: 1.0000

Epoch 47/59
----------
train Loss: 0.1933 Acc: 0.9998
val Loss: 0.0462 Acc: 1.0000

Epoch 48/59
----------
train Loss: 0.1913 Acc: 0.9998
val Loss: 0.0459 Acc: 1.0000

Epoch 49/59
----------
train Loss: 0.1926 Acc: 0.9998
val Loss: 0.0525 Acc: 1.0000

Epoch 50/59
----------
train Loss: 0.1956 Acc: 0.9998
val Loss: 0.0514 Acc: 1.0000

Epoch 51/59
----------
---------------------------------------------------------------------------
ConnectionAbortedError                    Traceback (most recent call last)
<ipython-input-24-9b6f8d4f7df2> in <cell line: 25>()
     23 criterion = nn.CrossEntropyLoss()
     24 
---> 25 model = pcb_train(model,mod_s, criterion, stage, 60)

5 frames
<ipython-input-22-7ac98a47339c> in pcb_train(model, mod_s, criterion, stage, num_epoch)
     16     # Decay LR by a factor of 0.1 every 40 epochs
     17     exp_lr_scheduler = lr_scheduler.StepLR(optimizer_ft, step_size=40, gamma=0.1)
---> 18     model = train_model(model, mod_s, criterion, optimizer_ft, exp_lr_scheduler, stage, num_epochs=num_epoch)
     19     return model

<ipython-input-18-b41491c42f79> in train_model(model, mod_s, criterion, optimizer, scheduler, stage, num_epochs)
     40             running_corrects = 0.0
     41             # Iterate over data.
---> 42             for data in dataloaders[phase]:
     43                 # get the inputs
     44                 inputs, labels = data

/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py in __next__(self)
    631                 # TODO(https://github.com/pytorch/pytorch/issues/76750)
    632                 self._reset()  # type: ignore[call-arg]
--> 633             data = self._next_data()
    634             self._num_yielded += 1
    635             if self._dataset_kind == _DatasetKind.Iterable and \

/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py in _next_data(self)
   1343             else:
   1344                 del self._task_info[idx]
-> 1345                 return self._process_data(data)
   1346 
   1347     def _try_put_index(self):

/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py in _process_data(self, data)
   1369         self._try_put_index()
   1370         if isinstance(data, ExceptionWrapper):
-> 1371             data.reraise()
   1372         return data
   1373 

/usr/local/lib/python3.10/dist-packages/torch/_utils.py in reraise(self)
    642             # instantiate since we don't know how to
    643             raise RuntimeError(msg) from None
--> 644         raise exception
    645 
    646 

**ConnectionAbortedError: Caught ConnectionAbortedError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torchvision/datasets/folder.py", line 229, in __getitem__
    sample = self.loader(path)
  File "/usr/local/lib/python3.10/dist-packages/torchvision/datasets/folder.py", line 268, in default_loader
    return pil_loader(path)
  File "/usr/local/lib/python3.10/dist-packages/torchvision/datasets/folder.py", line 246, in pil_loader
    with open(path, "rb") as f:
ConnectionAbortedError: [Errno 103] Software caused connection abort**

**Comment by cperry-goog** [comment]
We don't have any good ways to debug this; leaving it open in the event others have the same issue.

**Comment by cperry-goog** [comment]
You can also submit in product feedback and we can investigate to see if there are any logs we can view.

**Comment by jokoro** [comment]
I'm having this issue as well
<img width="739" alt="Screenshot 2023-10-03 at 8 51 32 PM" src="https://github.com/googlecolab/colabtools/assets/18509170/5db9c259-5c03-41a7-ac01-4efcb158c3c4">
