### ISSUE TITLE
Colab font not working, cursor stands at different spot when I am typing.

### ISSUE THREAD

**Issue by oMarquess** [googlecolab/colabtools#3966]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by oMarquess** [comment]
The text within colab cells (my code) looks weird and I am having difficulty copying and pasting.

**Comment by oMarquess** [comment]
The text within colab cells (my code) looks weird and I am having difficulty copying and pasting. Work on it for me. I have refreshed so many times.

**Comment by EvanWiederspan** [comment]
We'll need more info to help. Which font are you using, and which browser are you running? Also, does the problem persist in incognito mode, with all browser extensions disabled?
