### ISSUE TITLE
Add a cell button to enable a "bell" when cell has finished running

### ISSUE THREAD

**Issue by zachmoshe** [googlecolab/colabtools#3973]
**Is your feature request related to a problem? Please describe.**
In many notebooks, some of my cells are long-running processes, ranging from 1-2 minutes to a few hours. I'd like to be able to be able to work on other tasks while it's running but get alerted immediately when the cell finished running. 

**Describe the solution you'd like**
I want the Colab tab to play a sound when the cell finishes. I'm pretty sure Chrome can support playing sounds from inactive tabs (given the permissions from the user) and it would be great if this can be supported on all browsers.

It's important to mention that this should not be a default, or happen to all cells as most of the times it will be annoying. I'd add a button to the cell menu that activates the "bell" once the cell finishes (it deactivates itself upon completion). I imagine myself working, and only upon a long execution, I run it, click the button, and go to other tabs. When I get back to it and want to rerun again, I'll have to explicitly turn this on next time (if I want to).

**Describe alternatives you've considered**
I don't see any alternative to this without changing the Colab frontend. The only thing I can do is to remember to open that tab every once in a while to check...

**Comment by EvanWiederspan** [comment]
You can enable browser notifications for colab, and if you are looking at another tab when a cell completes running, you get a browser notification to take you back to the tab. This is a setting for all cells, and I understand you're asking for something you can enable per-cell, but I wanted to make sure you're aware of it as an option. It's pretty unintrusive for cells that run quickly since you don't see the popups if you're still viewing the tab when the cell completes

**Comment by zachmoshe** [comment]
1. I  wasn't aware. Thanks!
2. This doesn't seem to work... I've checked that I have both "Notifications" and "Sound" permissions enabled in "Site Settings" (for colab.research.google.com). Still, when I run "time.sleep(5)", the tab's icon changes, but no sound or any kind of an alert is shown.

Should I open a bug for that or am I missing something stupid?

**Comment by zachmoshe** [comment]
Sorry, my bad. Colab had permissions in Chrome but Chrome was disabled on my mac for notifications.

My only 2 minor points then - 
1. As a nice-to-have, allow to set the notification only for selected runs (a button on the cell itself?).
2. Not sure if possible - If you know from the Colab page that the notification won't be heard (because of site permissions or chrome permissions in the OS), alert the user when toggling the notifications settings in Colab's settings.
