### ISSUE TITLE
Unable to upgrade blinker

### ISSUE THREAD

**Issue by bilal-aamer** [googlecolab/colabtools#3976]
I want to upgrade blinker like `pip install --upgrade blinker` and it throws me the following error.

`ERROR: Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
`

**Comment by metrizable** [comment]
@bilal-aamer thanks for reporting this issue.

The error indicates that blinker is brought in by the OS platform as an [apt package](https://answers.launchpad.net/ubuntu/jammy/amd64/python3-blinker/1.4+dfsg1-0.4). If you want to install a newer version via `pip`, you'll have to remove the apt package and pip install your desired blinker version. I was able to successfully do so.

![BaMYdUKJYS4WgST](https://github.com/googlecolab/colabtools/assets/65414824/fafee72b-0553-4a7a-accf-7f1d65f1c26c)

As a call-out, removing an OS package, however, may have some unforeseen outcomes of its deps, so YMMV.

**Comment by Xh1Xxhg** [comment]
I appreciate it; it is helpful.

**Comment by Xh1Xxhg** [comment]
I appreciate it; it is helpful.
