### ISSUE TITLE
Small Code Cell Width in Chrome

### ISSUE THREAD

**Issue by rzqmhb** [googlecolab/colabtools#3978]
I was trying to use google colab in chrome, but the notebook generate an unusually small code cell width

**Comment by rzqmhb** [comment]
> do you have a screenshot?

here's a screenshot 
[](https://i.imgur.com/SE252hr.png)

**Comment by rzqmhb** [comment]
> do you have a screenshot?

here's a screenshot
[image](https://i.imgur.com/SE252hr.png)

**Comment by rzqmhb** [comment]
i don't know what's wrong, but when i used microsoft edge the code cell generated just fine.

**Comment by EvanWiederspan** [comment]
Does it still happen for you in incognito mode, with extensions turned off? We've seen a similar issue before that was caused by a browser extension

**Comment by catblue88** [comment]
I have a similar problem, take a look on my screenshot:
![image](https://github.com/googlecolab/colabtools/assets/2176465/6691b7c3-b65d-4f72-bf6c-465eb91995c4)

**Comment by catblue88** [comment]
Yeah, I found it; in my case it was caused by "pieces.app" extension..

**Comment by imparassharma** [comment]
I too faced the issue and Color picker extension was causing that problem... Reload after removing some extensions and see if it helps..
