### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by boludoz** [googlecolab/colabtools#3979]
```
ganas = False
plata = False

print("Seleccione un numero si tiene ganas de comer asado:")
print("1. Tengo ganas")
print("2. No tengo ganas")

opcion = input("Opciones: ")

if not opcion == "1" and opcion == "2":
  print("Opcion incorrecta")
  exit()
elif opcion == "1":
    ganas = True

monto = input("Ingrese su monto de dinero: ")
if monto.isdigit() == False:
  print("Ingrese un monto valido")
  exit()
else:
    plata = int(monto) >= 10000

if ganas or plata:
  print("Hoy se come asado con amigos")
else:
  print("No hay plata ni ganas, no se come asado")

```
![image](https://github.com/googlecolab/colabtools/assets/11653030/453f64f4-2c22-4513-96ee-0e98b6fedf0c)

**Comment by boludoz** [comment]
When he ran that code in Jupyter and on my computer that works.

**Comment by EvanWiederspan** [comment]
Colab and Jupyter notebooks maintain state between cells. I'm assuming what happened is that you ran some code that assigned `input =` some string value, which replaces the built-in `input()` function. Restarting your runtime and then running the code you provided should work

**Comment by boludoz** [comment]
> Colab and Jupyter notebooks maintain state between cells. I'm assuming what happened is that you ran some code that assigned `input =` some string value, which replaces the built-in `input()` function. Restarting your runtime and then running the code you provided should work

![image](https://github.com/googlecolab/colabtools/assets/11653030/0873b0c4-dc87-45b7-8343-2b31a7499c05)

This works, i dont understand what you say
