### ISSUE TITLE
!pip install tfx creates error

### ISSUE THREAD

**Issue by GeorgeMadlis** [googlecolab/colabtools#3981]
I am running the Colab notebook example:
https://colab.research.google.com/github/tensorflow/tfx/blob/master/docs/tutorials/tfx/components_keras.ipynb#scrollTo=S4SQA7Q5nej3

Running:
!pip install tfx

Creates an error:
Collecting tfx
  Using cached tfx-0.23.1-py3-none-any.whl (1.7 MB)
Collecting absl-py<0.9,>=0.7 (from tfx)
  Using cached absl-py-0.8.1.tar.gz (103 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by cperry-goog** [comment]
I can repo this, but it's not a Colab issue - you'll want to contact the tfx maintainers.

**Comment by metrizable** [comment]
@GeorgeMadlis  To add, [`tfx==1.13.0`](https://pypi.org/project/tfx/) only [supports Python 3.8 and Python 3.9](https://github.com/tensorflow/tfx/blob/v1.13.0/setup.py#L358). Colab's runtime is on Python 3.10.

**Comment by GeorgeMadlis** [comment]
Thanks! Understood.
