### ISSUE TITLE
502 Bad Gateway when trying to connect to TUNNEL for comfy UI

### ISSUE THREAD

**Issue by egambini** [googlecolab/colabtools#3984]
I am trying to connect to a vritual machine via an url https://slow-hairs-clean.loca.lt/ using a TUNNEL created by a google notebook to be able to use comfyUI.  It comes back with "502 Bad Gateway" on both my chrome browser and firefox. It was working until yesterday. Not sure if that interfere but I did share one folder of my google drive.. 

Should be taking me to the page asking me or a IP address to enter then I can start using comfyUI

Chrome and Firefox where tested. It was working until yesterday.. 

Any help would be greatly appreciated..

**Comment by EvanWiederspan** [comment]
Can you share a repro notebook that shows the setup for the comfyUI?
