### ISSUE TITLE
tflite-model-maker - actually none of examples that uses tis package does not working

### ISSUE THREAD

**Issue by stanchostanchev** [googlecolab/colabtools#3985]
colab at this link does not work:
https://developer.android.com/codelabs/recognize-flowers-with-tensorflow-on-android-beta?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-week2-machine-learning%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Frecognize-flowers-with-tensorflow-on-android-beta#1

as this is official Google collar, I am expecting it to work 

web browser does not matter

**Comment by metrizable** [comment]
@stanchostanchev Thanks for filing the issue. The current versions of TFLite (and ecosystem) do not appear to support Python 3.10. I'd follow up with those projects and file an upstream request for its support.

**Comment by gabed99** [comment]
@metrizable @cperry-goog Hi - I'm new to this workspace. When you say we should request upstreaming from the specific projects, do you mean with the TFLite developers? How do I do this? Can I run an older version of Python instead?

**Comment by gabed99** [comment]
Hi @stanchostanchev, do you know if there is an ongoing update for TFLite?

Thanks

Gabe
