### ISSUE TITLE
Cursor ahead of the text/code

### ISSUE THREAD

**Issue by matereyes00** [googlecolab/colabtools#3986]
My cursor is currently "ahead" of the text. I'm finding it uncomfortable and difficult to type properly. 

**Describe the expected behavior**
The cursor is supposed to be right beside the parenthesis where the code ends but it's a few steps ahead of it. Though, when you hit delete/backspace, it deletes the parenthesis.

Im using Firefox.

**Additional context**
![image](https://github.com/googlecolab/colabtools/assets/74333139/99ad7c22-6ad4-4e30-8879-454d4d2b26f8)

**Comment by alibekk93** [comment]
I have the same issue, it seems that the font changes for some reason, so the visual on the page and what the courses "sees" are of different width. Please help, this is super-annoying

**Comment by matereyes00** [comment]
I was able to resolve this. It was being caused by a Firefox extension called Zoom Page WE - i changed some of the settings and it reverted back to its original settings.

**Comment by alibekk93** [comment]
> I was able to resolve this. It was being caused by a Firefox extension called Zoom Page WE - i changed some of the settings and it reverted back to its original settings.

I am using Edge, but thanks anyway, I will check my extensions too
