### ISSUE TITLE
not able to upload the files

### ISSUE THREAD

**Issue by Shraven560** [googlecolab/colabtools#3987]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by Shraven560** [comment]
The import file option is not working . Tried reloading the site many times and opening a new file , but still the same things happen.

**Comment by mayankmalik-colab** [comment]
What error message are you getting? Can you try the following as well:
```
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))
```
