### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'numpy'

### ISSUE THREAD

**Issue by baqwas** [googlecolab/colabtools#3989]
https://colab.research.google.com/github/tensorflow/codelabs/blob/main/KerasNLP/io2023_workshop.ipynb#scrollTo=aNobqZ9UBJJK

**Describe the current behavior**

Attribute Error while working on LLM on Android with Keras and TensorFlow Lite
```
@tf.function
def generate(prompt, max_length):
    return gpt2_lm.generate(prompt, max_length)

concrete_func = generate.get_concrete_function(tf.TensorSpec([], tf.string), 100)
```

[/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py](https://localhost:8080/#) in __getattr__(self, name)
```
    428         np_config.enable_numpy_behavior()
    429       """)
--> 430     self.__getattribute__(name)
    431 
    432   @property

AttributeError: in user code:

    File "<ipython-input-14-d8866e8eac5d>", line 3, in generate  *
        return gpt2_lm.generate(prompt, max_length)
    File "/usr/local/lib/python3.10/dist-packages/keras_nlp/src/models/generative_task.py", line 277, in generate  *
        return self._normalize_generate_outputs(outputs, input_is_scalar)
    File "/usr/local/lib/python3.10/dist-packages/keras_nlp/src/models/generative_task.py", line 196, in normalize  *
        return tensor_to_list(outputs)
    File "/usr/local/lib/python3.10/dist-packages/keras_nlp/src/utils/tensor_utils.py", line 47, in tensor_to_list  *
        list_outputs = inputs.numpy()

    AttributeError: 'Tensor' object has no attribute 'numpy'
```

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
Should not receive _AttributeError_ message

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Firefox

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
https://colab.research.google.com/github/tensorflow/codelabs/blob/main/KerasNLP/io2023_workshop.ipynb#scrollTo=aNobqZ9UBJJK

**Comment by cperry-goog** [comment]
This is either a keras_nlp issue in which case you should ask at https://github.com/keras-team/keras-nlp/issues or you might have luck following the advice on stackoverflow: https://stackoverflow.com/questions/52357542/attributeerror-tensor-object-has-no-attribute-numpy
