### ISSUE TITLE
can i save colab project anywhere and upload and start it later?

### ISSUE THREAD

**Issue by DenisSouth** [googlecolab/colabtools#399]
I use colab.research.google.com for my research in university, but unfortunately it erasing all my files daily, yesterday i spent all day for coding, compiling, now i loose all my results:-(

I want to get some stuff for get the changes from co-laboratory machine (make dump of all file info before work and after work, then download the changes) then, when I need ma project again - i just want to upload the changes to co-laboratory and then start my project

**Comment by issa-s-ayoub** [comment]
I have the same problem; after uploading the database (round 2GB); I left my computer, and the second day, I found that all files are lost. So I am not sure if this is always the case or whether there is any solution for this problem. 
Any help is much appreciated!!

**Comment by DenisSouth** [comment]
I have got a solution. You can just write in first line of you Jupiter notebook code which may mount your Google drive as a folder. And  you can save all your files there
