### ISSUE TITLE
My сolab is blocked even though I don't break the rules

### ISSUE THREAD

**Issue by aeravel** [googlecolab/colabtools#3992]
I run my anylora freely available, for some reason it writes to me on Google colab that I am violating something, although it is not so!!

Here is the link:
https://colab.research.google.com/drive/13LeC-TUWWvVucd0xNQWbtYmmI_vUy7xg?hl=ru

Why is this happening?

**Comment by imacopypaster** [comment]
> although it is not so!!

Товарищь, не нужно лукавить. Открой файл:
https://ssl.gstatic.com/colaboratory-static/common/531c4fe6b87c8a33d030dbb3a0e641b3/external_polymer_binary.js
Там ты найдешь список всех "запрещенных" слов, на которые будет триггерится тупой скрипт Колаба.
Среди прочего ты там встретишь и свои очень "хитрые" замены webui на microsoftexcel:
![image](https://github.com/googlecolab/colabtools/assets/45368535/629aed8d-b738-49be-b10c-9ba215b321a1)
Просто используй другие слова, которые не запрещены, и которые не так популярны, можешь использовать генератор рандомных символов, например.
В общем, вот что на текущий момент использовать нельзя, но ты всегда можешь подсматривать в файле по ссылке что туда Гугл добавил нового в свои черные списки:

```
stable-diffusion-webui
stable-diffusion-$blasphemy
sd-webui
stablediffusion.vn/wp-content/uploads/Colab/
c3RhYmxlLWRpZmZ1c2lvbi13ZWJ1aQ
d2VidWk
V2ViVUk
c2Qtd2VidWk
SET UP STABLE DIFFUSION WEBUI
stable-diffusion-$
sd-webui-tunnels
-webui.
EasyGUI
EasierGUI
github.com/trivial16/testai/
aHR0cHM6Ly9odWdnaW5nZmFjZS5jby9nbWsxMjMvY29sYWIvcmF3L21haW4vY29sYWIucHk
"w"+"e"+"b"+"u"+"i"
huggingface.co/nolanaatama/colab/resolve/main/microsoftexcel
cagliostro-colab-ui
github.com/Stability-AI/StableSwarmUI
VoiceConversionWebUI
VoiceConversion{reeee}UI
Voice-Conversion-WebUI
github.com/777gt/EVC
Stable-Diffusion-Webui
nolanaatama/microsoftexcel
microsoftexcel-tunnels
a1111-microsoftexcel
SD-WebUI-TW
blasphemy=base64.b64decode
guebui = base64.b64decode
guebui2 = base64.b64decode
sdw = binascii.unhexlify
AUTOMATIC1111/{voldemort}
{sd}-{wui}
vorstcy
vcavry
zyx-webui-two-shot-main
ddPn08/automatic1111-colab
dagshub.com/camenduru/ui
github.com/camenduru/tunnels
/content/sdd-webui
github.com/DominikDoom/a1111-sd-webui-tagcomplete
blasphemy/webui
stable-diffusion-w\u0435bui
sd_web_ui
Automatic1111 обновлён до последней версии WebUI
-diffusion-webui
/content/{sdwu}/
a1111-sd-webui
github.com/comfyanonymous/ComfyUI
```
Есть множество способов обойти любые ограничения, даже если они будут на стороне сервера, а не как сейчас.

**Comment by cperry-goog** [comment]
Please submit feedback in product - we can't diagnose disconnects from Stackoverflow
