### ISSUE TITLE
resulting in most of the content being hidden

### ISSUE THREAD

**Issue by harshjoeyit** [googlecolab/colabtools#3994]
**Describe the current behavior**
The width of editor is only enabling a few characters and resulting in most of the content being hidden. A horizontal scrollbar is appearing even though I have enough space on the screen. I am seeing this issue in all of the colab notebooks I open. 

Please refer to the [screenshot in the link](https://ibb.co/pWnbfXJ)

**Describe the expected behavior**
The entire code should be visible if number of characters can fit on my screen or code should wrap to next line

**What web browser you are using**
Chrome

**Additional context**
Here's the link to one of my colab notebook.
https://colab.research.google.com/drive/1lWn4pYpKscltUsnaJmNWkIPgoUgOovBB#scrollTo=nhKd4hWx9GFt

**Comment by harshjoeyit** [comment]
This probably occuring because of this extension 

https://chrome.google.com/webstore/detail/pieces-save-code-snippets/igbgibhbfonhmjlechmeefimncpekepm

**Comment by cperry-goog** [comment]
Thanks for diagnosing the issue - we can't ensure compatibility with all Chrome extensions sadly.
