### ISSUE TITLE
Some backends have errored on the server. Check the server logs for details.

### ISSUE THREAD

**Issue by CyberWar8bit** [googlecolab/colabtools#3995]
**Describe the current behavior**
The ConfyUI backends error message: "Some backends have errored on the server. Check the server logs for details." appear each time I temporaly install ConfyUI.

In the server logs, I found this in the backend:
errored backend: (0): ComfyUI Self-Starting

In the panel I found this message that could be related:
06:04:08.235 [Info] Self-Start ComfyUI on port 7821 had errors before shutdown:
ComfyUI error: Traceback (most recent call last):
ComfyUI error:   File "/content/StableSwarmUI/dlbackend/ComfyUI/main.py", line 66, in <module>
ComfyUI error:     import comfy.utils
ComfyUI error:   File "/content/StableSwarmUI/dlbackend/ComfyUI/comfy/utils.py", line 1, in <module>
ComfyUI error:     import torch
ComfyUI error: ModuleNotFoundError: No module named 'torch' 

I found this error either with any browser and with either temporally instal or by using google drive.

This is happening for some days ago, I didn't have any problem before.

**Comment by cperry-goog** [comment]
You'll want to contact the notebook author.
