### ISSUE TITLE
Our RVC Script Keeps Disconnecting Itself After Few Minutes

### ISSUE THREAD

**Issue by owenborillo82** [googlecolab/colabtools#3996]
Our RVC Colab Script keeps disconnecting itself after 3 minutes. I'm training my new model from that Colab Notebook, which it takes hours for every epoch we're putting there.

It just keeps disconnecting itself, even the web interface keeps crashing due to the cell keeps disconnecting.

I'm using Chrome for the RVC Colab Script.

You need to change it back that limitation, since the others using it for 24 hours of AI Machine Learning. You need to remove the limitation and reverse the changes. PLEASE REMOVE THAT 3 MINUTES LIMITATION!

Run it for checking, and REMOVE THAT 3 MINUTES LIMITATION:
https://colab.research.google.com/drive/157pUQep6txJOYModYFqvz_5OJajeh7Ii

**Comment by roseyyy2022ai** [comment]
f+++++++++++++++++++ck I thought I was going insane!! Google is against RVC now huh??? AND Stable Diffusion????? tf did they do????

**Comment by cperry-goog** [comment]
We restrict webuis for both RVC and Stable Diffusion from using Colab's free backend compute with a webui - if you want to use those models you can use them in Colab on the free tier WITHOUT the webui components.

We must prioritize interactive programming sessions for our free tier users. Webuis that obscure the notebook are not a priority on free tier, but you can upgrade to paid to run those.
