### ISSUE TITLE
visualization.plot_bounding_box_gallery() : Type error 

### ISSUE THREAD

**Issue by roversi** [googlecolab/colabtools#3998]
In the "Object Detection with KerasCV" [example ](https://colab.research.google.com/github/keras-team/keras-io/blob/master/guides/ipynb/keras_cv/object_detection_keras_cv.ipynb), the visualization.plot_bounding_box_gallery() function is presenting an TypeError:

/usr/local/lib/python3.10/dist-packages/keras_cv/visualization/plot_bounding_box_gallery.py in plot_bounding_box_gallery(images, value_range, bounding_box_format, y_true, y_pred, true_color, pred_color, line_thickness, font_scale, text_thickness, class_mapping, ground_truth_mapping, prediction_mapping, legend, legend_handles, rows, cols, **kwargs)
    125     plotted_images = utils.to_numpy(images)
    126 
--> 127     draw_fn = functools.partial(
    128         draw_bounding_boxes,
    129         bounding_box_format="xyxy",

TypeError: the first argument must be callable

**It was expected to display a image and the predicted bounding boxes with classes names....**

**Comment by henrisve** [comment]
downgrade KerasCV to 0.6.2 and it will work

**Comment by roversi** [comment]
After downgrading KerasCV to 0.6.2, keras_cv.layers.Resizing() has not worked anymore...

***
/usr/local/lib/python3.10/dist-packages/keras_cv/src/layers/preprocessing/resizing.py in __init__(self, height, width, interpolation, crop_to_aspect_ratio, pad_to_aspect_ratio, bounding_box_format, **kwargs)
     92         self.crop_to_aspect_ratio = crop_to_aspect_ratio
     93         self.pad_to_aspect_ratio = pad_to_aspect_ratio
---> 94         self._interpolation_method = keras_cv.utils.get_interpolation(
     95             interpolation
     96         )

AttributeError: module 'keras_cv' has no attribute 'utils'_
***

I just tried to run everything from the beggining again using the updated keras-cv as the the original example and it worked!! 
I don't know if something was fixed in the background or whatever....

Thanks for your support!
