### ISSUE TITLE
Not able to modify time_partitioning in job.config while using Colab

### ISSUE THREAD

**Issue by romanoww** [googlecolab/colabtools#400]
Hi all,

We've been trying to create a partitioned table from scratch and load it with results from a query. We're using google Colab with the google cloud package.

When setting the job configuration, we have to specify the bigquery.TimePartitioning parameters (e.g.  type = 'DAY', field = 'DATETIME').

When running this locally (in my own Python environment), I'm able to pass these parameters. 

```
from google.cloud import bigquery

project_id = 'xyz'
dataset_id = 'xyz'
client = bigquery.Client(project=project_id)

destination_table='table1'

job_config = bigquery.QueryJobConfig()
table_ref = client.dataset(dataset_id).table(destination_table)
job_config.destination = table_ref
job_config.write_disposition = 'WRITE_TRUNCATE'

job_config.allow_large_results = True
job_config.time_partitioning = bigquery.TimePartitioning(
    type_= 'DAY',
    field='DATETIMECOLUMN')
```

Passing a query to client.query with this config, results in a newly created partitioned table (as expected).
However, running this code in Google Colab results in the following message. It seems like the import of google.cloud.bigquery in Colab misses the TimePartitioning attribute.

How can this be resolved?

```---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-defb356d4d71> in <module>()
      8 
      9 job_config.allow_large_results = True
---> 10 job_config.time_partitioning = bigquery.TimePartitioning(
     11     type_= 'DAY',
     12     field='DATETIMECOLUMN')

AttributeError: module 'google.cloud.bigquery' has no attribute 'TimePartitioning'```

**Comment by colaboratory-team** [comment]
TimePartitioning requires an updated version of the bigquery client library. 

Run: `!pip install -U google-cloud-bigquery`. Then, restart you Python runtime using the Runtime -> Restart runtime... menu.

**Comment by romanoww** [comment]
Thanks
