### ISSUE TITLE
Can't install Tensorflow Object detection API

### ISSUE THREAD

**Issue by QuanNguyenAUT** [googlecolab/colabtools#4000]
Hi there, 

This bug suddenly appeared today. Few hours ago, it had been run properly. 

Could you help to fix this bug? 

Thanks.

**Describe the current behavior**
```
Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-3-8ee57bccf1cc>](https://localhost:8080/#) in <cell line: 1>()
----> 1 get_ipython().run_cell_magic('bash', '', 'cd models/research/\nprotoc object_detection/protos/*.proto --python_out=.\ncp object_detection/packages/tf2/setup.py .\npython -m pip install .\n')

4 frames
<decorator-gen-103> in shebang(self, line, cell)

[/usr/local/lib/python3.10/dist-packages/IPython/core/magics/script.py](https://localhost:8080/#) in shebang(self, line, cell)
    243             sys.stderr.flush()
    244         if args.raise_error and p.returncode!=0:
--> 245             raise CalledProcessError(p.returncode, cell, output=out, stderr=err)
    246 
    247     def _run_script(self, p, cell, to_close):

CalledProcessError: Command 'b'cd models/research/\nprotoc object_detection/protos/*.proto --python_out=.\ncp object_detection/packages/tf2/setup.py .\npython -m pip install .\n'' returned non-zero exit status 1.
```

**Describe the expected behavior**
Compile the object detection API as usual. 

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
We can investigate if you share a reproducible notebook, but offhand it doesn't appear to be a Colab specific issue.

**Comment by ProxyAyush** [comment]
Hi, the problem can be traced to setup.py file of Tensorflow object detection api, it's not installing, some library must have changed, i am facing a similar issue as @QuanNguyenAUT

**Comment by QuanNguyenAUT** [comment]
Hi @ProxyAyush,

It came up from a version conflict.  Run this code before installing the Object detection API
`!pip uninstall Cython -y`

Hope that it can help.

**Comment by cperry-goog** [comment]
Thanks @QuanNguyenAUT closing this as it's a version conflict; appreciate the workaround.
