### ISSUE TITLE
Hola!! cuando cierro mi  seción y al otro día trato de seguir ingresando códigos me aparece este error

### ISSUE THREAD

**Issue by merce-lgtm** [googlecolab/colabtools#4007]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
Can you share a minimal reproducible notebook that generates the error you mention?

**Comment by bbb11223344556677** [comment]
stop the peoject
