### ISSUE TITLE
InvalidArgumentError: Graph execution error:

### ISSUE THREAD

**Issue by waghumbareajay** [googlecolab/colabtools#4010]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by waghumbareajay** [comment]
one day before same code was working propoerly but today it is giving "InvalidArgumentError: Graph execution error:"

**Comment by cperry-goog** [comment]
We'll need the code to investigate if you can share a minimal reproducible notebook. But if you're getting code errors, you may have more luck contacting the notebook author (if not yourself).
