### ISSUE TITLE
Code running but not printing out results 

### ISSUE THREAD

**Issue by mbova87** [googlecolab/colabtools#4013]
**Describe the current behavior**
I am running Python code and am getting the green check, but no results. See below:

**Describe the expected behavior**
I expect my code to print out my results.

**What web browser you are using**
Chrome

**Additional context**
https://colab.research.google.com/drive/1wu_lG0STOb0qsA95cSVJyVErQbGQ3BZI?usp=sharing

**Comment by EvanWiederspan** [comment]
Can you make the notebook public?
