### ISSUE TITLE
Dialog box is minimized

### ISSUE THREAD

**Issue by JohnKHancock** [googlecolab/colabtools#4018]
**Describe the current behavior**
Dialog box for changing the runtime type is minimized for some odd reason, and I cannot re-size it to set the appropriate settings.

**Describe the expected behavior**
I expected the dialog box to be in a non-minimized state and/or be able to resize it.

**What web browser you are using**
Chrome and Edge. However, it works on FIreFox.

**Additional context**
[Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link']
 (https://drive.google.com/file/d/1LUMrGlI9r9ABTh92psUZplGOfR13igEx/view?usp=sharing).
![google](https://github.com/googlecolab/colabtools/assets/22781272/68beaad1-c2fe-42cb-bdd3-1f784667ec63)
Above are screenshots for the issue.

**Comment by cperry-goog** [comment]
Does this reproduce in an incognito window?

**Comment by katlyn-edwards** [comment]
Can you also include what version of Chrome you're using? You can find it at the top of chrome://version

**Comment by JohnKHancock** [comment]
Hello,

This is the version of Chrome that I am using Version 117.0.5938.92
(Official Build) (64-bit)

Also, the error *does not* reproduce in an incognito window. Strange, but
it does solve the problem.

Thank you all.

**Comment by katlyn-edwards** [comment]
Hrm, if it doesn't reproduce in incognito, that usually points to having an extension installed that's causing the issue. You can disable and check what extensions you have installed at chrome://extensions

**Comment by JohnKHancock** [comment]
Bam! It was my Norton extensions on safe searching. Thanks. Issue resolved.
You may close the ticket.

**Comment by cperry-goog** [comment]
Amazing sleuthing, thank you!
