### ISSUE TITLE
Colab do not refresh files in Google drive

### ISSUE THREAD

**Issue by zhihaocheng** [googlecolab/colabtools#402]
I use a somename.py file in google drive to simulate the environment. Then I import it to the Colab and the run the code. Then, I modified that somename.py file in google drive the run the experiment again. However, the Colab always uses the original version. Even if I delete that somename.py file in google drive, Colab is still able to import it. Please help me.

**Comment by vehxianfish** [comment]
do you sovle it ? I meet same questions,can you tell me some solutions?

**Comment by kangzhiq** [comment]
> I meet same questions,can you tell me some solutions?

I have solved this problem by` runtime -> restart runtimes` or `Ctrl+M`.

Hope that can could be helpful! :-)

**Comment by fbbradheintz** [comment]
I'm having the same issue. Restarting the runtime does not change it.

**Comment by fbbradheintz** [comment]
Nor does resetting.

**Comment by daarong** [comment]
I think "restart runtime" helps, but it does not always work.

I have found "reset all runtimes" seems to be a good backup to make it refresh.

However for me doing a reset is a real pain because environment setup takes time, plus you have to go through the Google Drive permissions granting process again.

**Comment by shaunster0** [comment]
I'm having this as well. Doing this helped refresh python 
import importlib
importlib.reload(mymodule)

but even this doesnt work sometimes

**Comment by idhamari** [comment]
+1

**Comment by devhci** [comment]
any solution ? RI also ran into same issue

**Comment by xhain** [comment]
Why is this closed? This is an issue in my opinion.
If I pull, I can even see the diff and all - but the scripts aren't actually updated 🤷
As noted above: Reloading the modules doesn't really solve it.

**Comment by TimS-ml** [comment]
> I use a somename.py file in google drive to simulate the environment. Then I import it to the Colab and the run the code. Then, I modified that somename.py file in google drive the run the experiment again. However, the Colab always uses the original version. Even if I delete that somename.py file in google drive, Colab is still able to import it. Please help me.

Try this:
drive.mount("/content/drive", force_remount=True)

**Comment by kuzand** [comment]
Still haven't been fixed :(
Restarting the runtime to do this is very annoying and takes time.

**Comment by xhain** [comment]
```
from IPython.display import clear_output
from importlib import reload
import mymodule

def update():
  ! git pull
  reload(mymodule)
  clear_output()
```

Haven't ran experiments, but this is how I handle it right now. I didn't test and see if pullling + `reload()` actually applies the most recent changes though..

**Comment by hungdino** [comment]
It is still happening and yes, it is annoying to restart the runtime especially going through all the Google Drive authentication process.

**Comment by IDTitanium** [comment]
I had this issue, i restarted the runtime, it didn't work. I did `factory reset runtime` . It didn't work. I gave up and uploaded the files i needed directly.

**Comment by cyc115** [comment]
It's 2023 and still not addressed, it pains me to see Google builds a perfectly good product but provides little to no support for bugs like this.

**Comment by Anagabrielamantilla** [comment]
You can try this:

1. Go to the folder of the repository
`cd NameFolder`

2. !git pull

Every time I add a file in my repo I run the last code and it works

**Comment by fnacinovich** [comment]
The problem still persists. A real shame. 
@colaboratory-team

**Comment by headmetal** [comment]
You can try adding the `force_remount=True` argument to the `drive.mount()` call - this worked for me:

```
drive.mount('/content/drive', force_remount=True)
```

**Comment by gustavomirapalheta** [comment]
After some research on the web I think this is expected behavior. When you do an import python kernel loads the module and you can start using the functions to create objects. Now if the code in your .py changes and you import the updated module, this could lead to conflicts during code execution.

There is a workaround which is using the ```importlib``` ```reload``` function. But the docs advise you to do this with care, because this can lead to unpredicted behavior.
