### ISSUE TITLE
Change runtime popout window not scaled correctly

### ISSUE THREAD

**Issue by TreborDekal** [googlecolab/colabtools#4023]
**Describe the current behavior**
When selecting the "Change runtime type" popout window is not scaled correctly. Can not see the content.

![image](https://github.com/googlecolab/colabtools/assets/6201911/96cfc35f-4634-4dbf-a1a6-f275137a4b68)

**Describe the expected behavior**
I expect to be able to see clearly the different option of GPU and CPU

**What web browser you are using**
Chrome Version 116.0.5845.188 (Official Build) (64-bit)

**Additional context**
See image above

**Comment by cperry-goog** [comment]
Does this replicate in an incognito window?

**Comment by TreborDekal** [comment]
Hi, No...

[cid:dd0a0212-97b1-41d3-af29-8794b8da6442]
________________________________

**Comment by cperry-goog** [comment]
If it doesn't replicate in an incognito window it's almost certainly a browser extension you have installed that is altering our dialog popups. Find the extension and uninstall to solve.
