### ISSUE TITLE
drive is disconnecting often

### ISSUE THREAD

**Issue by hooking-software** [googlecolab/colabtools#4024]
**Describe the current behavior**
I train a machine and the drive disconnecting from the colab

**Describe the expected behavior**
since i pay for the colab, how about let the drive work?

**What web browser you are using**
Chrome

**Additional context**
This is a shame yall STEALING peoples money by promising them that all good in PRO, but i have spent around $100 now for NOTHING!
i train a model and you disconnect my drive. WTF?!?
how am i gonna save it after HOURS and HOURS of training over your damn mistake?
Wont spend a dime there no more and ill move to onedrive and microsoft.
buy my own hardware for training and stop feeding thieves.

**Comment by cperry-goog** [comment]
I think this is a dupe with #3785  if you have a notebook that reproduces your issue reliably please share.

Also helpful if you can file in-product feedback and reference this issue.

**Comment by hooking-software** [comment]
actually it is not.
I have a scanning files process on the drive, small files but lots of them. and while i scan and also when i train the model, it wont save it.
so you take the computing units, i spend time and resources and get NOTHING.

**Comment by hooking-software** [comment]
but you guys are good at evoiding good customer service, so in the end of the day, i understand. 
I will just work a little harder with someone else.
it's a shame this is what i get after being a loyal customer for years.

**Comment by cperry-goog** [comment]
I mean maybe you'd say it's a low bar but I don't know any team at Google that takes customer service as seriously as we do -- nowhere else do you have a direct line to the leadership of the product.

I can't reproduce this, I've tried. I've spun up a notebook that writes to the same Drive file for 12 hours. I've tried reading and re-reading from files. I guess I'll try writing a ton of files and and seeing if that triggers this?

**Comment by hooking-software** [comment]
you guys can access my notebooks in my account (you own it), and see the logs for yourself.
i wouldn't bother you if it wasn't very frustrating.
i feel like throwing money to the trash here.
if you can help me out to stop feeling like that by providing the high quality service i pay for, i will be okay with it.
its just i am doing it for a week now and spend 300 computing units for nothing.
please understand my feelings about it.

**Comment by hooking-software** [comment]
also, i pay for the service but for the past 3 hours i cannot have a A-100 runtime, only V-100, why?

**Comment by hooking-software** [comment]
> I mean maybe you'd say it's a low bar but I don't know any team at Google that takes customer service as seriously as we do -- nowhere else do you have a direct line to the leadership of the product.
> 
> I can't reproduce this, I've tried. I've spun up a notebook that writes to the same Drive file for 12 hours. I've tried reading and re-reading from files. I guess I'll try writing a ton of files and and seeing if that triggers this?

your (your department) specifically, do give a good service here. so i take my words back and apologize.

**Comment by cperry-goog** [comment]
We are stocking out of A100s; can't get any more out of GCP right now.

**Comment by hooking-software** [comment]
I understand. thank you for this answer. any chance you guys can look into the logs to see why i experience issues with it?
as you said, once it is mounted aint suppose to be problems. my model is 1.5GB, shouldn't be a problem.

**Comment by hooking-software** [comment]
this way or another, till i finish my credits, i have made a function to check the drive and mount it if its not before saving my model.
