### ISSUE TITLE
GOOGL COLAB 

### ISSUE THREAD

**Issue by aykut9876** [googlecolab/colabtools#4025]
**Describe the current behavior**
GPU kullanan arka uçlardan hiçbiri boşta değil. Hızlandırıcısı olmayan bir çalışma zamanı kullanmak ister misiniz? [Daha fazla bilgi](https://research.google.com/colaboratory/faq.html#gpu-availability)

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
This looks like the error we throw when you are connected to a GPU runtime but you aren't using the GPU. You'll want to utilize the GPU in order to avoid seeing these dialogs.
