### ISSUE TITLE
Drive and Runtime Disconnecting in PRO mode.

### ISSUE THREAD

**Issue by hooking-software** [googlecolab/colabtools#4026]
![image](https://github.com/googlecolab/colabtools/assets/144736064/fbe0460e-6ea6-4709-bbe9-09961dc8f9a7)

hope yall got explanation to this...

**Comment by hooking-software** [comment]
i swear to god yall is unreliable.

**Comment by hooking-software** [comment]
![image](https://github.com/googlecolab/colabtools/assets/144736064/2b7a893b-9be6-4e75-ae7e-f33d6c625939)

**Comment by cperry-goog** [comment]
Duping with #3785 if you have a minimal reproducible notebook that would be helpful
