### ISSUE TITLE
plotly fig is not displaying in google colab notebook with rpy2

### ISSUE THREAD

**Issue by DZusername** [googlecolab/colabtools#4027]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mayankmalik-colab** [comment]
Can you share a minimal repro notebook?

**Comment by DZusername** [comment]
Hi Colab Support,

Please see the requested minimal notebook and data file attached. Please
Note that in addition to the Plotly pie charts not displaying in Colab
using the rpy2 package, none of the charts and visualizations display when
the file is printed as a PDF document.

TIA,
Dan

**Comment by cperry-goog** [comment]
The attachment didn't come through on the issue, can you attach in the GitHub UI? Or link to a publicly-viewable notebook.

**Comment by cperry-goog** [comment]
I'm sorry it's not getting attached, if you share a link with public accessibility we can look

**Comment by DZusername** [comment]
Please try now.
https://github.com/DZusername/Colab/blob/main/HMEQ_Loss_Data_Preparation_for_Colab_Support.zip
