### ISSUE TITLE
Errors while using 'add-apt-repository'

### ISSUE THREAD

**Issue by DarkKaplah** [googlecolab/colabtools#4033]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

While trying to add respositories I'm getting errors.
The instructions I'm following are located here:  
https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Setting-up-ARM-manually-(Ubuntu)

Their are two add-apt-repositories in the instructions.  Both are having the following error:

> user@UbuntuARM:~$ sudo add-apt-repository ppa:heyarje/makemkv-beta
> Traceback (most recent call last):
>   File "/usr/bin/add-apt-repository", line 364, in <module>
>     sys.exit(0 if addaptrepo.main() else 1)
>   File "/usr/bin/add-apt-repository", line 347, in main
>     shortcut = handler(source, **shortcut_params)
>   File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
>     return handler(shortcut, **kwargs)
>   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 82, in __init__
>     if self.lpppa.publish_debug_symbols:
>   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 120, in lpppa
>     self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
>   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 107, in lpteam
>     self._lpteam = self.lp.people(self.teamname)
>   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 98, in lp
>     self._lp = login_func("%s.%s" % (self.__module__, self.__class__.__name__),
>   File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 494, in login_anonymously
>     return cls(
>   File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 230, in __init__
>     super(Launchpad, self).__init__(
>   File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 472, in __init__
>     self._wadl = self._browser.get_wadl_application(self._root_uri)
>   File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 447, in get_wadl_application
>     response, content = self._request(url, media_type=wadl_type)
>   File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 389, in _request
>     response, content = self._request_and_retry(
>   File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 359, in _request_and_retry
>     response, content = self._connection.request(
>   File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1725, in request
>     (response, content) = self._request(
>   File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 144, in _request
>     response, content = super(LaunchpadOAuthAwareHttp, self)._request(
>   File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 184, in _request
>     return super(RestfulHttp, self)._request(
>   File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1441, in _request
>     (response, content) = self._conn_request(conn, request_uri, method, body, headers)
>   File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1363, in _conn_request
>     conn.connect()
>   File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1153, in connect
>     sock.connect((self.host, self.port))

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

Add the repository without issue

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

Terminal.  This is a command line issue.  Posting via Mozilla

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mayankmalik-colab** [comment]
I am able to add repositories. For example, the below command works fine.
``
sudo add-apt-repository -y ppa:heyarje/makemkv-beta
```

On a side note, it doesn't seem like a notebook cell to me. Where did you execute the code exactly ?

**Comment by DarkKaplah** [comment]
In the terminal

> I am able to add repositories. For example, the below command works fine.
> 
> ```
> sudo add-apt-repository -y ppa:heyarje/makemkv-beta
> ```
> 
> On a side note, it doesn't seem like a notebook cell to me. Where did you execute the code exactly ?

**Comment by cperry-goog** [comment]
`user@UbuntuARM:~$` is not the Colab terminal? I'm confused how you got here in Colab.
