### ISSUE TITLE
wxPython installation error

### ISSUE THREAD

**Issue by Vanitha-SP** [googlecolab/colabtools#4035]
<!--Collecting wxPython
  Using cached wxPython-4.2.1.tar.gz (73.7 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from wxPython) (9.4.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from wxPython) (1.16.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from wxPython) (1.23.5)
Building wheels for collected packages: wxPython
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for wxPython (setup.py) ... error
  ERROR: Failed building wheel for wxPython
  Running setup.py clean for wxPython
Failed to build wxPython
ERROR: Could not build wheels for wxPython, which is required to install pyproject.toml-based projects

facing this erorr while trying to install wxPython

**Comment by mayankmalik-colab** [comment]
It doesn't seem like a Colab specific issue. I would request you to reach out to the repo owners.
