### ISSUE TITLE
https://www.tensorflow.org/tutorials/keras/save_and_restore_models

### ISSUE THREAD

**Issue by SinanGabel** [googlecolab/colabtools#404]
## Section: As a saved_model

Seems this does not work (which you also rightfully state in the doc.): `tf.keras.experimental.export(model, "./saved_models")` etc.

Possible fix:

```
saved_model_path = tf.keras.models.save_model(model, "./saved_models")
...
new_model = tf.keras.models.load_model("./saved_models")

```

**Comment by colaboratory-team** [comment]
Which notebook are you referring to?

**Comment by colaboratory-team** [comment]
Thanks for the report. I'd recommend opening an issue in the TensorFlow docs repo here:
https://github.com/tensorflow/docs
