### ISSUE TITLE
Unable to mount to Goole Drive

### ISSUE THREAD

**Issue by nathanielkang** [googlecolab/colabtools#4041]
Hello, 

I am using Google Colab on Chrome and trying to mount it to google drive. But it failed several times because the window is running (see screenshot below) for too long and I was not able to select which google account to mount. I waited for at least 5 minutes then the window crashed.

![image](https://github.com/googlecolab/colabtools/assets/60408260/6519c527-24c4-4bdf-8c05-f836b98e828d)

Thank you!

**Comment by cperry-goog** [comment]
Are you on a slow connection by chance?

And does this reproduce in an incognito window?
