### ISSUE TITLE
Documentation error in the description of the built-in function

### ISSUE THREAD

**Issue by Deciptikon** [googlecolab/colabtools#4044]
**Describe the current behavior**
Documentation error in the description of the built-in **range()** function in the popup hint in Google Colab. 
Here is the current description: 

range(*args, **kwargs)
range(stop) -> range object
**range(start, stop[, step])** -> range object
... 

**Describe the expected behavior**
It should be written like this:

range(*args, **kwargs)
range(stop) -> range object
**range(start, stop, [step])** -> range object
... 

**What web browser you are using**
Browser Opera One(ver: 102.0.4880.78)

**Additional context**
Link to my screenshot of this error on my Google Drive
[LINK](https://drive.google.com/file/d/1wrDr5THwfC3N-okHB9aFB4v_NdeHiZPw/view?usp=sharing)

**Comment by cperry-goog** [comment]
This docstring is owned upstream of us - we don't author or modify those.
