### ISSUE TITLE
Error 403 en app Dash

### ISSUE THREAD

**Issue by djinnxs** [googlecolab/colabtools#4048]
Cuando ejecuto el código me genera un error 403 hace una semana atrás me mostraba el dash, lo ejecute ésta semana y me aparece la imagen que pego abajo, leí en el foro que agregando el puerto podrías solucionare por lo que lo agregue pero igual no funciona. (tengo todas las librerías instaladas por si acaso dicen que falta alguna)
`import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import plotly.express as px
from google.colab import auth
auth.authenticate_user()
from google.colab import output

# Define un número de puerto, por ejemplo, 8080
port = 8080

# Utiliza output.serve_kernel_port_as_iframe para servir el puerto como un iframe
output.serve_kernel_port_as_iframe(port)
# Supongamos que tienes un DataFrame llamado "diarreas" con las columnas "ANIO", "PROVINCIA", "GRUPO" y "CANTIDAD"

# Inicializa la aplicación Dash
app = dash.Dash(__name__)

# Define el diseño de la aplicación
app.layout = html.Div([
    html.H1("Reporte de Diarreas"),
    
    # Dropdown para seleccionar el año
    dcc.Dropdown(
        id='year-dropdown',
        options=[
            {'label': str(year), 'value': year} for year in diarreas['ANIO'].unique()
        ],
        value=diarreas['ANIO'].min(),  # Valor predeterminado
        multi=False
    ),
    
    # Gráfico de barras para mostrar la cantidad por provincia y grupo de edad
    dcc.Graph(id='diarreas-bar-chart')
])

# Callback para actualizar el gráfico según el año seleccionado
@app.callback(
    Output('diarreas-bar-chart', 'figure'),
    [Input('year-dropdown', 'value')]
)
def update_chart(selected_year):
    filtered_data = diarreas[diarreas['ANIO'] == selected_year]
    
    # Utiliza Plotly Express para crear el gráfico de barras
    fig = px.bar(
        filtered_data,
        x='PROVINCIA',
        y='CANTIDAD',
        color='GRUPO',
        labels={'CANTIDAD': 'Cantidad de Diarreas'},
        title=f"Cantidad de Diarreas por Provincia y Grupo de Edad en {selected_year}"
    )
    
    return fig

if __name__ == '__main__':
    app.run_server(debug=True)`
![image](https://github.com/googlecolab/colabtools/assets/33420901/36dd1876-f12a-42c6-9c02-2fd96f5e10de)

**Comment by cperry-goog** [comment]
Sorry I missed this - we have fixed this error as of a few weeks back.
