### ISSUE TITLE
Im having trouble with my "GPU RAM" not showing its gigabits

### ISSUE THREAD

**Issue by helsdsad22** [googlecolab/colabtools#4054]
So im trying to train a AI voice model in so-vits-svc 4.0, and evertime i press "Check GPU" my "GPU RAM" shows, but doesn't show how many Gigabits it has or anything. Please help because i think this is the reason i cant train my model.

**Comment by cperry-goog** [comment]
Sorry we missed this one before - what exactly do you want to see and where?
