### ISSUE TITLE
Plotly not displaying graphs

### ISSUE THREAD

**Issue by bracaanissa** [googlecolab/colabtools#4057]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
Plotly is not not displaying the graphs when I try to run the cell an empty image box appears.

**Describe the expected behavior**
I expect plotly to display the graph resulting from the code. I was using plotly.io a week ago and it worked to display the image as for example pio.show(fig1) now even this is not working.

**What web browser you are using**
Chrome

**Comment by bracaanissa** [comment]
No, I use chrome however I’m not incognito.

**Comment by cperry-goog** [comment]
Try this in an incognito window
