### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Abdoh-Ramadan** [googlecolab/colabtools#4063]
the operation stopped with this message below 
but when I checked Google Drive the file was there.

<ipython-input-4-4fb61c2df196>:30: DeprecationWarning: is_seed() is deprecated
  if not download.is_seed():
<ipython-input-4-4fb61c2df196>:35: DeprecationWarning: name() is deprecated
  download.name(),
<ipython-input-4-4fb61c2df196>:48: DeprecationWarning: name() is deprecated
  print(download.name(), "complete")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-4fb61c2df196> in <cell line: 26>()
     46             bar.close() # Seems to be not working in Colab (see https://github.com/googlecolab/colabtools/issues/726#issue-486731758)
     47             download_bars.remove(bar)
---> 48             print(download.name(), "complete")
     49     time.sleep(1)

RuntimeError: invalid torrent handle used

**Comment by EvanWiederspan** [comment]
This doesn't seem like a Colab issue, I would reach out to the notebook author instead
