### ISSUE TITLE
UnidentifiedImageError: cannot identify image file '/content//videoFrames/2674df6393_0_0_1/000001.jpg

### ISSUE THREAD

**Issue by letlive419** [googlecolab/colabtools#4066]
**Describe the current behavior**
Im getting a error UnidentifiedImageError: cannot identify image file '/content//videoFrames/2674df6393_0_0_1/000001.jpg

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mayankmalik-colab** [comment]
This maybe be because of the corrupt image files.  I think you'll have more luck searching on Stackoverflow. One such example - [unidentifiedimageerror](https://stackoverflow.com/questions/63754311/unidentifiedimageerror-cannot-identify-image-file).
