### ISSUE TITLE
Unbuffered print output by default

### ISSUE THREAD

**Issue by jewillco** [googlecolab/colabtools#4067]
**Is your feature request related to a problem? Please describe.**
When I use `print` to write status and other output, only some of the items are typically written due to buffering. This is annoying, especially since the buffering seems to include almost all of a line of output but not all of it.

**Describe the solution you'd like**
I would like standard output in Colabs to be in unbuffered mode.

**Describe alternatives you've considered**
I currently use `flush=True` on individual `print` statements.

**Additional context**
This feature would make monitoring progress easier. Also, sometimes previous output is hidden until some long computation is done just due to items in a `print` statement being buffered.

**Comment by EvanWiederspan** [comment]
We're not going to enable that for all print statements, as there may be users who don't want that behavior by default. I believe you can use the following snippet to automatically set `flush=True` for all subsequent print calls:

```py
from functools import partial

print = partial(print, flush=True)
```

Does that work for you?
