### ISSUE TITLE
Colab saves and creates a new revision every 30 sec for no reason while running

### ISSUE THREAD

**Issue by Melanol** [googlecolab/colabtools#407]
[screenshot](https://i.postimg.cc/ty6SXGdM/colab-saves.jpg)

I have only these libraries imported:

from google.colab import drive
import numpy as np
import cPickle as pickle
import gym

So, the code itself does not do this.

**Comment by Melanol** [comment]
Tested if automatic saving of my model to Drive had something to do with this - doing this less often does not change how often Colab saves the notebook and creates a revision.

**Comment by Melanol** [comment]
Also tested if Colab is supposed to save notebooks every 30 secs - negative.

**Comment by Melanol** [comment]
This is still an issue because this destroys previous revisions while doing nothing but cloning the last revision.

**Comment by colaboratory-team** [comment]
Periodic saving is expected when the notebook or outputs change.

**Comment by Melanol** [comment]
But outputs change all the time during running. What's the point in destroying proper revisions by cloning the last one?
