### ISSUE TITLE
Add keybind to show docstring of object

### ISSUE THREAD

**Issue by geetmankar** [googlecolab/colabtools#4071]
**Is your feature request related to a problem? Please describe.**
It is frustrating sometimes to wait for docstring to appear after typing `(` to bring up hovering/floating docstring for help.

![image](https://github.com/googlecolab/colabtools/assets/27027921/f8659bbd-805b-4605-b494-1cd14757455e)

**Describe the solution you'd like**
Just a keybinding such as `Ctrl+Shift+Space` to bring that docstring up as a floating box.

**Describe alternatives you've considered**
There seem to be no solutions for this very niche problem (I presume).

**Additional context**
Nothing

**Comment by EvanWiederspan** [comment]
Tracking internally as b/306402790

**Comment by EvanWiederspan** [comment]
This should already be bound to cmd+shift+space, does that work for you?

**Comment by geetmankar** [comment]
Oh yeah it seems to, maybe the delay is just a network delay then. I mixed up this issue with a hover docstring (the docstring that comes up when you hover the mouse over a word), for e.g.:

![image](https://github.com/googlecolab/colabtools/assets/27027921/bc3c09b6-02ba-45ff-953f-90bf7bcd617c)

Is there a keybind for this to appear without using a mouse? If yes I'll just close the issue.
