### ISSUE TITLE
run time automatically disconnects in colab pro.

### ISSUE THREAD

**Issue by balams81** [googlecolab/colabtools#4073]
Runtime automatically disconnects during executing of code in google colab pro. Credits are being wasted during this process. 

https://github.com/googlecolab/colabtools/wiki/Bug-Reports

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by RuchikJani** [comment]
I am facing the same issue since 18th Oct , it is really frustrating. my notebook gets disconnection in middle of cell execution and it has become slow , really slow after the new update

**Comment by EvanWiederspan** [comment]
We'll need more information to follow up on this bug report. Please submit feedback within Colab at Help > Send feedback.
