### ISSUE TITLE
Visualisavi

### ISSUE THREAD

**Issue by joaquin92lc** [googlecolab/colabtools#4076]
En google Colab en Chrome.
Cuando ejecuto los códigos, no me quedan fijos los resultados, aparecen un momento y luego se borran.
Puede ser que la página en ese momento esté fallando o que esté mi Colab mal configurado?
Un saludo.
![image](https://github.com/googlecolab/colabtools/assets/142426020/acb7e537-b979-4f86-b2cb-736ebe1a4371)

**Comment by cperry-goog** [comment]
Can you paste the exact code that reliably triggers this behavior?
