### ISSUE TITLE
Delay problem

### ISSUE THREAD

**Issue by estudiantematematico** [googlecolab/colabtools#4079]
I have a problem with a preprocesing task and delay when I try to use the images, in a collab I create around 5,000 images and I don't have problems for the storage I use only 6 gb, so  in another collab I'm using these images, but when I access the folders they do not show me the total number of images that correspond.

**Comment by cperry-goog** [comment]
Are you using Drive for this? Or are you talking about folders on the runtime itself? Drive will die with that many images, you will have more success using another filestore or using the files locally.
