### ISSUE TITLE
Colab failing with Keras and tensorFLow backend

### ISSUE THREAD

**Issue by romisalve** [googlecolab/colabtools#408]
The same model that was ruunning with no problem, now is failing. It says "name 'os' is not defined" but I am importing os in the first cell. 
We have not changed anything in the code, literally and it just stop working.

**Comment by craigcitro** [comment]
Can you share a link to the notebook, or at least a subset including the code that leads to this error?

**Comment by romisalve** [comment]
https://colab.research.google.com/drive/1XIBXpR--3PPNPypBDfhim3qwZla7Zkwp

**Comment by craigcitro** [comment]
It looks like this is an error upstream in `keras_preprocessing` which is already fixed in https://github.com/keras-team/keras-preprocessing/pull/159. 

To confirm, if you add

    !pip install keras_preprocessing==1.0.7

and re-run, the error should disappear. (It looks like it was introduced just before 1.0.8.)

I will tweak something on our side to avoid 1.0.8, and I'll also ask upstream about the next release.

Thanks for the report, and sorry about the trouble!

**Comment by romisalve** [comment]
Ok, Thank you! I'll add that and see if it works

**Comment by romisalve** [comment]
Could not find a version that satisfies the requirement keras_preprocessing==1.0.7 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.8)
No matching distribution found for keras_preprocessing==1.0.7

Now This error appears

**Comment by craigcitro** [comment]
Note that if you've already loaded `keras_preprocessing`, you'll need to also restart your runtime (ctrl-m . or Runtime -> Restart runtime from the menu).

Just saw your second message -- it looks like 1.0.7 was removed for other reasons upstream; what about 1.0.6?

**Comment by romisalve** [comment]
Using TensorFlow backend.
Collecting keras_preprocessing==1.0.9
  Could not find a version that satisfies the requirement keras_preprocessing==1.0.9 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.8)
No matching distribution found for keras_preprocessing==1.0.9

1.0.6 also gives error. 

SHould i add : pip install git+git://github.com/keras-team/keras-preprocessing.git --upgrade --no-deps ??

**Comment by craigcitro** [comment]
`!pip install keras-preprocessing==1.0.6` works for me in a fresh notebook -- can you share the full error you're seeing?

**Comment by romisalve** [comment]
yes i have .

This appears after the first cell:

Using TensorFlow backend.
Requirement already satisfied: keras-preprocessing==1.0.6 in /usr/local/lib/python3.6/dist-packages (1.0.6)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.6/dist-packages (from keras-preprocessing==1.0.6) (1.11.0)
Requirement already satisfied: numpy>=1.9.1 in /usr/local/lib/python3.6/dist-packages (from keras-preprocessing==1.0.6) (1.14.6)

so i believe that is working, but the error does not disappear

**Comment by romisalve** [comment]
should i delete this line: 
from keras.preprocessing import image
from the first cell?

**Comment by romisalve** [comment]
my first cell should be like this:

import pandas as pd
import numpy as np
import os
from imutils import paths
from tqdm import tqdm
import keras
import random
import matplotlib.pyplot as plt
from keras.layers import Dense,GlobalAveragePooling2D,MaxPooling2D
from keras.applications import MobileNet
from keras.preprocessing import image
from keras.applications.mobilenet import preprocess_input, decode_predictions
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Model
from keras.optimizers import Adam
from keras import optimizers
from shutil import copyfile, rmtree
import time
import shutil
from shutil import copyfile
from keras.callbacks import ModelCheckpoint
from keras.callbacks import LearningRateScheduler
from keras.applications.mobilenetv2 import MobileNetV2
import math
!pip install keras-preprocessing==1.0.6 #no anda

Or how did you do it that it works??

**Comment by romisalve** [comment]
I was having 1.0.6 version.
 Now it is not letting me connect to any Notebook. It says "session has been restarted after a failure".

**Comment by romisalve** [comment]
Now i have changed to keras applications 1.0.5 and keras preprocessing 1.0.6. I believe it is working

**Comment by craigcitro** [comment]
Glad you're unblocked @romisalve, and thanks again for the report!

I've added a fix to avoid the bad version on our side, which will go live in the next few days, at which point you can safely drop your workaround. I'm going to mark this as closed.
