### ISSUE TITLE
Change Runtime Environment is always minimized

### ISSUE THREAD

**Issue by AbhiRoy96** [googlecolab/colabtools#4085]
**Describe the current behavior**
The Change Runtime Environment option when selected does not open completely it remains minimized always. It makes nearly impossible to select options.

**Describe the expected behavior**
It should be always expanded.

**What web browser you are using**
Chrome, Firefox

**Additional context**
![image](https://github.com/googlecolab/colabtools/assets/21016255/c0a8992d-1519-4a0f-9eaf-35364a59ffda)

**Comment by katlyn-edwards** [comment]
Does it repro in an incognito window? We've seen reports of this before, but it's been caused by extensions installed.

In https://github.com/googlecolab/colabtools/issues/4018 it was caused by a Norton extension, for example.
