### ISSUE TITLE
colab stop working T4 GPU 

### ISSUE THREAD

**Issue by gnajaganathan** [googlecolab/colabtools#4087]
I have rent T4 GPU for one month. My task is YOLOv5  object segment using google colab. There are 30 classes to segment. I have tested each class to segment. Now i have added one to another and test it. Till 13GB of training images colab working fine. Once i have added another class images to segment(now the training image size is 15.3GB), i stopped after some epoch.

**Comment by cperry-goog** [comment]
These types of issues are almost impossible to debug from our side, as we don't have the data or the code. The next time this happens if you can screenshot the runtime logs I'd be curious to see them.
