### ISSUE TITLE
C code runs fine but Python error is shown.

### ISSUE THREAD

**Issue by JoasLion** [googlecolab/colabtools#4088]
**Describe the current behavior**
This is a simple code in C language that runs fine but at the end it shows an error related to Python that has nothing to do with C.

**Describe the expected behavior**
Based on what I wrote in the previous sentence, that error message which does nothing shouldn't be there.

**What web browser you are using**
I'm using Firefox.

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

This is the link to the notebook:
https://colab.research.google.com/drive/1SpGrCoUjggUL4j7NiTt0rfzFQ_ivuTbp?usp=sharing

**Comment by mayankmalik-colab** [comment]
Can you try using `!` (and not `%%shell`)to execute the shell commands?

**Comment by JoasLion** [comment]
I tried what you suggested and it works fine! Thank you so much for your help!
