### ISSUE TITLE
Settings > Default page layout not giving any difference

### ISSUE THREAD

**Issue by AnuraagaNath** [googlecolab/colabtools#4089]
**Describe the current behavior**
No difference in code cell and output cells are showing after changing the values in default page layout

**Describe the expected behavior**
Horizontal: The code and output cells are displayed side-by-side, with the code cell on the left and the output cell on the right.
Vertical: The code and output cells are displayed stacked on top of each other, with the code cell on top and the output cell below.
Single tabbed view: All of the cells in the notebook are displayed in a single tab, with the code and output cells displayed below each other.

**What web browser I am using**
Google Chrome

**Comment by cperry-goog** [comment]
The default page layout applies to tabs (like resource pane, terminal, etc.) it does not impact the layout of output cells.

**Comment by AnuraagaNath** [comment]
ok thank you
