### ISSUE TITLE
CuPy has stopped working

### ISSUE THREAD

**Issue by kmaehashi** [googlecolab/colabtools#409]
Hello, I'm a maintainer of CuPy project.
It seems that Colab container is now using CUDA 10.0 by default. However, CuPy installed in the container is `cupy-cuda92`, which is for CUDA 9.2, so it is not working. Could you change it to install `cupy-cuda100`?

<img width="649" alt="screen shot 2019-02-06 at 12 59 05" src="https://user-images.githubusercontent.com/939877/52319837-15cad080-2a0f-11e9-83e2-b54153982d61.png">

**Comment by craigcitro** [comment]
Whoops -- sending out a fix right now, and a test to make sure this doesn't slip through again. (It'll make it out to all runtimes by Thursday, barring any other hiccups.) Thanks for the heads-up!

In the interim, for anyone hitting this issue and looking to get fixed up, just run

    !pip install --upgrade cupy-cuda100

and you should be back in business.

**Comment by kmaehashi** [comment]
Thanks for your quick action!

**Comment by craigcitro** [comment]
Fix is live, we should be good to go. :)
