### ISSUE TITLE
Hi, My cell (#45) to save the trained model is hung  in execution state  in notebook "https://colab.research.google.com/drive/1yxCRJNBjDxs0RoutKMQhK-iEE-2-hHa1#scrollTo=UUctmjm8RIfQ" # save the finetuned model to google drive !cp -r "/content/finetuned_model" "/content/drive/MyDrive" .  My commands to stop running the cell does not work. I am getting charged for my GPU time. 

### ISSUE THREAD

**Issue by rr62** [googlecolab/colabtools#4090]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
If the model is large, Drive may not work properly. I'd encourage you to download the model or save to GCS or another filestore.
