### ISSUE TITLE
Google Colab is disconnected. Impossible to reconnect

### ISSUE THREAD

**Issue by bvillenap7** [googlecolab/colabtools#4091]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by bvillenap7** [comment]
I was working in Google Colab when suddenly the environment was disconnected without root cause known. Currently it is impossible to reconnect.

**Comment by cperry-goog** [comment]
Can you file feedback in product and reference this issue? I wonder if you're blocked or just exceeded quota.
