### ISSUE TITLE
Native MIDI support and MIDI to audio rendering

### ISSUE THREAD

**Issue by asigalov61** [googlecolab/colabtools#4093]
Hello,

It would be great if Google Colab added native support for MIDI files.

Here is the Python module I made that works easily and natively with Google Colab (only needs fluidsynth library).

https://github.com/asigalov61/tegridy-tools/blob/main/tegridy-tools/midi_to_colab_audio.py

So I have a few questions:

Can I PR this module to colabtools ?

Can you consider adding MIDI support to Google Colab?

Can you at least add fluidsynth library to Colab so that there would not be a need to install it every time?

Thank you.

Alex

**Comment by cperry-goog** [comment]
Thanks for the request - we only take on new libraries when we see large usage - fluidsynth is below the cutoff at this point. Module looks sweet though!

**Comment by asigalov61** [comment]
@cperry-goog Ok. Thank you for your response.
