### ISSUE TITLE
colab is pointing to different project id

### ISSUE THREAD

**Issue by githubuserpk** [googlecolab/colabtools#4094]
Hi, I was trying to try a vision api sample, but Colab is pointing to a different project id 

In the beginning of the notebook, I have set the project id as below the project number is: XXXXXX126720
!gcloud config set project pkdeltaai-01

Error message is given below: 
====================
Cloud Vision API has not been used in project XXXXXX567947 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/vision.googleapis.com/overview?project=XXXXXX567947 then retry.

Can you please help.  It has not assigned the correct project id.

**Comment by EvanWiederspan** [comment]
Try setting the project ID as follows:

```py
from google.colab import auth
auth.authenticate_user(project_id=<YOUR PROJECT ID>)
```
