### ISSUE TITLE
Bug in Introduction_To_Material_Science.ipynb: AttributeError: module 'numpy.linalg._umath_linalg' has no attribute '_ilp64' 

### ISSUE THREAD

**Issue by White-Charles** [googlecolab/colabtools#4095]
When I try to run Introduction_To_Material_Science.ipynb in "Open In Colab", the code ( import deepchem as dc ) will return an error (AttributeError: module 'numpy.linalg._umath_linalg' has no attribute '_ilp64').

By the way, also in this tourist, there is another bug( 
Building wheels for collected packages: pymatgen
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for pymatgen (setup.py) ... error
  ERROR: Failed building wheel for pymatgen
  Running setup.py clean for pymatgen
Failed to build pymatgen
ERROR: Could not build wheels for pymatgen, which is required to install pyproject.toml-based projects)

**Comment by cperry-goog** [comment]
Can you report this to the author of Introduction_To_Material_Science.ipynb? I'm not sure who wrote that?

**Comment by cperry-goog** [comment]
For the errors above, I'd be interested in seeing the code that triggers them.
