### ISSUE TITLE
cannot install pyinstaller

### ISSUE THREAD

**Issue by zeki6** [googlecolab/colabtools#410]
`pip install pyinstaller`

> Collecting pyinstaller
  Using cached https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
Command "/usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp2rn5y09k" failed with error code 1 in /tmp/pip-install-uyvnqplx/pyinstaller

It was possible last month but it is impossible now.

**Comment by craigcitro** [comment]
This is an upstream issue: see https://github.com/pyinstaller/pyinstaller/issues/4003 and https://github.com/pypa/pip/issues/6163 for more details, but from the comments there, this is an easy workaround in the short term:

    !pip install --no-use-pep517 pyinstaller
