### ISSUE TITLE
Bug in `typing-extensions` library. ImportError

### ISSUE THREAD

**Issue by mcaferulker** [googlecolab/colabtools#4100]
I've run into the issue when I tried to `import gradio`. 

I'm trying to run a ML model in Colab. I tried to import gradio to publish a demo and I encountered a typing-extensions import error. I tried older typing extensions versions but it didn't work.

**Describe the current behavior**
```python
!pip install typing-extensions
```
-> Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (4.8.0)

```python
!pip -q install gradio
import gradio as gr
```
```python
ImportError                               Traceback (most recent call last)

[/usr/local/lib/python3.10/dist-packages/fastapi/exceptions.py](https://localhost:8080/#) in <module>
      4 from starlette.exceptions import HTTPException as StarletteHTTPException
      5 from starlette.exceptions import WebSocketException as StarletteWebSocketException
----> 6 from typing_extensions import Annotated, Doc  # type: ignore [attr-defined]
      7 
      8 

ImportError: cannot import name 'Doc' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)
```

**What web browser you are using**
I'm using Firefox browser.

**Comment by cperry-goog** [comment]
The commands you listed run fine - what code triggered that error?

In any event I imagine this is going to be a gradio bug.

**Comment by mcaferulker** [comment]
Yes, there is indeed a bug for `gradio v3.50.2`. Version 3.45.0 worked for me. I let them know that.
