### ISSUE TITLE
 ModuleNotFoundError: No module named 'sampling'

### ISSUE THREAD

**Issue by qiushuanglengyue** [googlecolab/colabtools#4101]
!pip install sampling.utils
Collecting sampling.utils
  Downloading sampling_utils-0.1.1-py3-none-any.whl (6.3 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from sampling.utils) (1.23.5)
Installing collected packages: sampling.utils
Successfully installed sampling.utils-0.1.1

ModuleNotFoundError: No module named 'sampling'

**Comment by mayankmalik-colab** [comment]
Where did you get that error ? I was able to install and ran a sample code:
```
!pip install sampling.utils

from sampling_utils import sample_from_list
sample_from_list([1,2,3,4,5,6,7,8], dont_pick_closest=2)
```

Please share a sample code or notebook that describes the issue.

**Comment by qiushuanglengyue** [comment]
运行以下程序：
!pip install sampling.utils

from sampling_utils import sample_from_list
sample_from_list([1,2,3,4,5,6,7,8], dont_pick_closest=2)

结果如下：
已满足要求：/usr/local/lib/python3.10/dist-packages (0.1.1)中的sampling.utils
已满足要求：/usr/local/lib/python3.10/dist-packages中的numpy（来自sampling.utils）（1.23.5）
[1, 4, 8]

但是运行以下程序：
from sampling.utils import mnist_iid, mnist_noniid, cifar_iid
结果报错如下：
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-24-e38be0aacf10>](https://localhost:8080/#) in <cell line: 16>()
     14 from tensorboardX import SummaryWriter
     15 
---> 16 from sampling.utils import mnist_iid, mnist_noniid, cifar_iid
     17 from utils.options import args_parser
     18 from models.Update import LocalUpdate

ModuleNotFoundError: No module named 'sampling'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by qiushuanglengyue** [comment]
Run the following program:
!pip install sampling.utils

from sampling_utils import sample_from_list
sample_from_list([1,2,3,4,5,6,7,8], dont_pick_closest=2)

The result is as follows:
Requirements met: sampling.utils in /usr/local/lib/python3.10/dist-packages (0.1.1)
Requirements met: numpy (from sampling.utils) in /usr/local/lib/python3.10/dist-packages (1.23.5)
[1, 4, 8]

But run the following program:
from sampling.utils import mnist_iid, mnist_noniid, cifar_iid
The error result is as follows:
-------------------------------------------------- -----------------------
ModuleNotFoundError Traceback (most recent call last)
[<ipython-input-24-e38be0aacf10>](https://localhost:8080/#) in <cell line: 16>()
      14 from tensorboardX import SummaryWriter
      15
---> 16 from sampling.utils import mnist_iid, mnist_noniid, cifar_iid
      17 from utils.options import args_parser
      18 from models.Update import LocalUpdate

ModuleNotFoundError: No module named 'sampling'

-------------------------------------------------- -----------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by cperry-goog** [comment]
That code works for us -- can you share a minimal reproducible notebook that triggers this error?
You could also submit feedback in product and we can see if there are any signals we can check there.
