### ISSUE TITLE
Unzipping files using google colab into google drive not showing up in google drive

### ISSUE THREAD

**Issue by ramacha7** [googlecolab/colabtools#4102]
I am trying to download a zipped file and then unzip it using google colab while mounted on my drive. I have not been able to see all of the files unzipped into my google drive. I tried flush and unmount but this still did not work. @colaboratory-team, can we please get some immediate help on this? It is very frustrating that the problem has not been solved yet. The google drive only has a few files unzipped but most of the files do not show up on my google drive

**Comment by cperry-goog** [comment]
Can you provide a notebook with steps? Are you doing this all in the file browser UI? Are you unzipping inside a Drive folder? Unclear if you're unzipping on the Colab runtime where you are then putting the files.

**Comment by vaduraes** [comment]
Had the same problem on my side here. The solution was to unzip the file on my computer on upload it using Google Drive desktop.

Very inefficient, but it is what it is.

**Comment by zfriedman0** [comment]
Similar issue here. Code to recreate in a notebook is as follows:

```
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

%cd /content/drive/MyDrive/PennAction/

!unzip PennAction-FramesOnly-Sorted.zip
```
`PennAction-FramesOnly-Sorted.zip` is structured like

```
├Data
    ├─train
        ├──vid1/
        |   ├──000001.jpg
        |   ├──000002.jpg
        |   ├──...
    ├──val
        ├──vid2/
        |   ├──000001.jpg
        |   ├──000002.jpg
        |   ├──...
        ├──...
```
In the Colab runtime, `unzip` yields both train and val files...
![colab-fs](https://github.com/googlecolab/colabtools/assets/43194954/3ea5d4e7-0d02-482e-b057-de104f8d0bc0)

but does not in Google Drive.
![image](https://github.com/googlecolab/colabtools/assets/43194954/dd03e6c5-37a0-48b0-a2ac-9377961b6a51)

**Comment by cperry-goog** [comment]
Tracking internally at b/309970417

**Comment by EvanWiederspan** [comment]
I ran a very simple test with the following code:

```py
for i in range(10):
    !echo {i} > /content/{i}.txt

!zip test /content/*.txt

from google.colab import drive
drive.mount('/content/drive')

!mkdir -p "/content/drive/MyDrive/zip test"
!cp /content/test.zip "/content/drive/MyDrive/zip test"

# After running this, I see the files appear in the Drive UI.
!unzip "/content/drive/MyDrive/zip test/test.zip" -d "/content/drive/MyDrive/zip test"
```

This worked fine for me, although the files are very small and upload basically instantly. I'm wondering if Drive is just taking a while due to the number or size of files; can anyone seeing this issue provide specifics of the number and size of files? Or ideally, provide a zip file with junk data that repros the issue

**Comment by codezart** [comment]
Is this fixed?

Because it is not working for me. I tried unzipping a Youtube-vos dataset 9GB size and it didn't unzip all the files. only one folder of the two folders

**Comment by Jahangeer69** [comment]
Similar Issue here. I want to use a dataset of car images. It is not letting me to unzip the files

**Comment by r73lan** [comment]
Had the same issue, but after waiting (about 20 min) unzipped files appeared in my directory

**Comment by paupaiz** [comment]
`!unzip` works for me!

**Comment by akeshmaheshwari** [comment]
I want to unzip files
