### ISSUE TITLE
python error code !pip3 install scipy==1.1.0 on google colab

### ISSUE THREAD

**Issue by Michaelsobhyhelmy** [googlecolab/colabtools#4103]
Collecting scipy==1.1.0
  Using cached scipy-1.1.0.tar.gz (15.6 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: scipy
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for scipy (setup.py) ... error
  ERROR: Failed building wheel for scipy
  Running setup.py clean for scipy
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for scipy
Failed to build scipy
ERROR: Could not build wheels for scipy, which is required to install pyproject.toml-based projects

**Comment by mayankmalik-colab** [comment]
`scipy==1.1.0` is 5 years old. I am almost sure that it would not work with python 3.10. Please use the current version installed in the container.
