### ISSUE TITLE
Can't upload 5GB file on colab manually or via files.upload()

### ISSUE THREAD

**Issue by imabansal** [googlecolab/colabtools#4104]
**Describe the current behavior**
Tried to upload the file using upload to session storage on colab notebook but got the red cross.
File link:https://huggingface.co/TheBloke/Llama-2-7B-GGML/blob/main/llama-2-7b.ggmlv3.q2_K.bin
Download the above file and uploading it manually failed.

Also tried uploading the file using following code :
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

It has been more than 10 minutes and this cell keeps on running in a never ending loop. Terminated the execution manually. Also, it is not printing the progress of the file upload.

**Describe the expected behavior**
File should uploaded in expected duration and display the progress of upload.

**What web browser you are using**
Chrome

**Additional context**
Link: https://gist.github.com/imabansal/0ead1ce0729d50287d04877205c1a6de 

**Storage**
80.59 GB disk space available

**Comment by cperry-goog** [comment]
I'd recommend `wget` to download your file directly from HuggingFace - 5GB is a little much to be sending in our web uploader.

**Comment by imabansal** [comment]
@cperry-goog  can it atleast display the message that it can't allow upload files of size greater than 500 MG etc?
as it is keep running and confusing the user
