### ISSUE TITLE
How to downgrade the colab notebook to the previous release version

### ISSUE THREAD

**Issue by thevaibhavkute** [googlecolab/colabtools#4105]
**Is your feature request related to a problem? Please describe.**
Previously I was working on one project, and it was running great but due to the recent new release of colab notebook its not working at all 

**Describe the solution you'd like**
There should be something for downgrading to the previous version of colab

**Comment by cperry-goog** [comment]
We don't always support fallback versions for every change - most updates are minor library updates. When it is available, try using Tools > Command palette > Use fallback version (iirc). If you need consistency in your dependencies, might I recommend a local runtime https://research.google.com/colaboratory/local-runtimes.html
