### ISSUE TITLE
AttributeError: '_SingleProcessDataLoaderIter' object has no attribute 'next'

### ISSUE THREAD

**Issue by qiushuanglengyue** [googlecolab/colabtools#4107]
Run the following program:
from create_MNIST_datasets import get_MNIST, plot_samples
mnist_iid_train_dls, mnist_iid_test_dls = get_MNIST("iid",

The error is reported as follows:
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to ./data/MNIST/raw/train-images-idx3-ubyte.gz
100%|██████████| 9912422/9912422 [00:00<00:00, 114200476.42it/s]
Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw

Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz to ./data/MNIST/raw/train-labels-idx1-ubyte.gz
100%|██████████| 28881/28881 [00:00<00:00, 33324812.61it/s]
Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw

Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw/t10k-images-idx3-ubyte.gz
100%|██████████| 1648877/1648877 [00:00<00:00, 28656335.68it/s]
Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw

Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz
100%|██████████| 4542/4542 [00:00<00:00, 13312738.48it/s]
Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw

-------------------------------------------------- -----------------------
AttributeError Traceback (most recent call last)
<ipython-input-3-22fabab4855a> in <cell line: 2>()
       1 from create_MNIST_datasets import get_MNIST, plot_samples
----> 2 mnist_iid_train_dls, mnist_iid_test_dls = get_MNIST("iid",
       3 n_samples_train =200, n_samples_test=100, n_clients =3,
       4 batch_size =25, shuffle =True)

1 frame
/content/create_MNIST_datasets.py in iid_split(dataset, nb_nodes, n_samples_per_node, batch_size, shuffle)
      42 data_splitted=list()
      43 for _ in range(nb_nodes):
---> 44 data_splitted.append(torch.utils.data.DataLoader(torch.utils.data.TensorDataset(*(dataiter.next())), batch_size=batch_size, shuffle=shuffle))
      45
      46 return data_splitted

AttributeError: '_SingleProcessDataLoaderIter' object has no attribute 'next'

**Comment by cperry-goog** [comment]
You'll need to reach out to the notebook author or library maintainers - we cannot fix AttributeErrors in Colab.
