### ISSUE TITLE
UI not working properly when changing runtime

### ISSUE THREAD

**Issue by jamslaugh** [googlecolab/colabtools#4109]
**Describe the current behavior**
Each time I open the "change runtime type the popup has no area to click

**Describe the expected behavior**
change runtime type popup should show all the possible choices

**What web browser you are using**
Firefox and chrome

**Additional context**
![immagine](https://github.com/googlecolab/colabtools/assets/10156618/8c2e6d0c-a951-43f2-a8a2-8d42bfcc9d0c)

**Comment by katlyn-edwards** [comment]
Hey there!

Can you try this in an incognito window? We've seen reports of this before, but it's been caused by extensions installed.

In https://github.com/googlecolab/colabtools/issues/4018 it was caused by a Norton extension, for example.
