### ISSUE TITLE
str object is not callable 

### ISSUE THREAD

**Issue by devanshusanghani** [googlecolab/colabtools#411]
[new 1.txt](https://github.com/googlecolab/colabtools/files/2835137/new.1.txt)
the above link give you my code.
some time it can call the str and some it doesnt it simply displays str is not callable.
![screenshot 57](https://user-images.githubusercontent.com/30127363/52325036-84a52b00-2a09-11e9-9fe4-9cef10739cf8.png)
this is initial screenshot i.e. 1st time i have run this code and working
![screenshot 58](https://user-images.githubusercontent.com/30127363/52325037-84a52b00-2a09-11e9-8825-02f38faedb56.png)
this is final screenshot i.e. 2nd time i have run this code.

**Comment by metrizable** [comment]
@devanshusanghani I have tried your code and am not able to reproduce your issue. Since this was filed a while ago, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
