### ISSUE TITLE
I can't download openjdk 18 (Java) correctly

### ISSUE THREAD

**Issue by Manidarean5** [googlecolab/colabtools#4110]
**Describe the current behavior**
When i try to install Java 18 say that (openjdk)

**Describe the expected behavior**
Download Java 18 and when i put !java -version say me that i'm in 18

**What web browser you are using**
Chrome

**Additional context**
![image](https://github.com/googlecolab/colabtools/assets/108998523/3cdb68cc-156f-4b17-82c4-464c40f635a6)

In will like to download Java 16 but i can't because say me E: Unable to locate package openjdk-16-jdk

**Comment by mayankmalik-colab** [comment]
We can use `!sudo apt search openjdk` to search for the available OpenJDK in the default repository
It seems like `openjdk-16-jdk` is not present there.

**Comment by Manidarean5** [comment]
But when i install another version its always 1 of java
