### ISSUE TITLE
Mardown Cells Don't Load Image from Google Drive

### ISSUE THREAD

**Issue by etdperkins** [googlecolab/colabtools#4112]
**Describe the current behavior**
Image from google drive is not in text cell when using:  

![*image name*](https://drive.google.com/uc?export=view&id= *id copied from image link with permissions set to anyone with link can view*)  

instead it just displays: *image name*

**Describe the expected behavior**
Expect that the image corresponding to the file id displays in the markdown cell when you exit editing 'mode'

**What web browser you are using**
Firefox

**Comment by cperry-goog** [comment]
I've got this working in Chrome just fine with your url pattern -- that said, Drive really hates being used as an image source for websites so I would not be surprised if they broke this intentionally after a few loads. You should use a different hosting service or attach images in the notebook itself with the image uploader.
