### ISSUE TITLE
"Range" variable

### ISSUE THREAD

**Issue by Skibowy** [googlecolab/colabtools#4119]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
I have made an variable named "range"

example:
range = 1000

then when I pressed play and there was an error:
"
TypeError                                 Traceback (most recent call last)
[<ipython-input-71-a1617d111995>](https://localhost:8080/#) in <cell line: 53>()
     51 w = np.array([0.36620631, 0.82682025, 0.59336022])
     52 
---> 53 for i in range(len(x)):
     54   xx = x[i]
     55   dd = d[i]
TypeError: 'int' object is not callable
"

The problem was when I deleted that variable, because I tried to use function "range(int)" and it still shows that error:
"
TypeError                                 Traceback (most recent call last)
[<ipython-input-71-a1617d111995>](https://localhost:8080/#) in <cell line: 53>()
     51 w = np.array([0.36620631, 0.82682025, 0.59336022])
     52 
---> 53 for i in range(len(x)):
     54   xx = x[i]
     55   dd = d[i]
TypeError: 'int' object is not callable
"

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
I expected that variable disapears

**What web browser you are using**
Opera GX

**Comment by mayankmalik-colab** [comment]
There is some confusion what you are running exactly. Can you share a reproducible notebook that could us help test it ?

**Comment by cperry-goog** [comment]
You reassigned a built-in function (range). Pick a new name for your variable `not_range = 1000`
