### ISSUE TITLE
new pytorch release v1.0.1

### ISSUE THREAD

**Issue by soumith** [googlecolab/colabtools#412]
Hi folks,

We released a new PyTorch version v1.0.1.
I believe it might even fix https://github.com/googlecolab/colabtools/issues/312

The wheel links are:

CUDA 9.0

- https://download.pytorch.org/whl/cu90/torch-1.0.1-cp27-cp27m-linux_x86_64.whl
- https://download.pytorch.org/whl/cu90/torch-1.0.1-cp27-cp27mu-linux_x86_64.whl
- https://download.pytorch.org/whl/cu90/torch-1.0.1-cp36-cp36m-linux_x86_64.whl

CUDA 10.0

- https://download.pytorch.org/whl/cu100/torch-1.0.1-cp27-cp27m-linux_x86_64.whl
- https://download.pytorch.org/whl/cu100/torch-1.0.1-cp27-cp27mu-linux_x86_64.whl
- https://download.pytorch.org/whl/cu100/torch-1.0.1-cp36-cp36m-linux_x86_64.whl

We're looking to having it updated in Colab.

Thanks very much.

cc'ing @colaboratory-team on the suggestion of Ami

**Comment by colaboratory-team** [comment]
Thanks, we'll start on the update and keep this issue updated.
b/123988922

**Comment by soumith** [comment]
I'm so sorry, it looks like we botched certain things in the binaries. I'm rebuilding them, will ping back over here once ready.

**Comment by colaboratory-team** [comment]
Thanks for the information. We'll hold off on any updates until we get confirmation to continue.

**Comment by soumith** [comment]
Sorry about that. Though the issues wouldn'tve affected the colab experience, I wanted to be extra conservative.

The new links are

CUDA 9.0

- https://download.pytorch.org/whl/cu90/torch-1.0.1.post2-cp27-cp27m-linux_x86_64.whl
- https://download.pytorch.org/whl/cu90/torch-1.0.1.post2-cp27-cp27mu-linux_x86_64.whl
- https://download.pytorch.org/whl/cu90/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl
- https://download.pytorch.org/whl/cu90/torch-1.0.1.post2-cp37-cp37m-linux_x86_64.whl

CUDA 10.0

- https://download.pytorch.org/whl/cu100/torch-1.0.1.post2-cp27-cp27m-linux_x86_64.whl
- https://download.pytorch.org/whl/cu100/torch-1.0.1.post2-cp27-cp27mu-linux_x86_64.whl
- https://download.pytorch.org/whl/cu100/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl
- https://download.pytorch.org/whl/cu100/torch-1.0.1.post2-cp37-cp37m-linux_x86_64.whl

Thanks a lot for waiting.

**Comment by colaboratory-team** [comment]
Pytorch has now been updated to 1.0.1.post2 in Colab.
