### ISSUE TITLE
Cell magic `%%python` is not highlighted

### ISSUE THREAD

**Issue by slitvinov** [googlecolab/colabtools#4123]
Cell magic `%%python` works, but is not highlighted (appearing the same as regular text).
```
%%python
import os; print(os.getpid())
```
(prints a new process ID every time I run the cell).

**Comment by cperry-goog** [comment]
gotta be honest I didn't know `%%python` was a magic until this moment. it's highlighting for me right now? but we'll look.

**Comment by slitvinov** [comment]
It appears like this in Firefox 119.0 (64-bit) on Ubuntu."
![image](https://github.com/googlecolab/colabtools/assets/115638/4cc39086-0a05-46ff-9a99-2527e974a922)

**Comment by EvanWiederspan** [comment]
This should be fixed now, thanks for the report!
