### ISSUE TITLE
pro plus runtime error

### ISSUE THREAD

**Issue by reuissir** [googlecolab/colabtools#4125]
So I've reported this one month ago

### Expected behavior
Google colab pro plus was advertised with a much longer runtime. This was the reason I chose to purchase it so I could train my YOLO v5m6 model without any distractions.

### Current Behavior
Continuous disconnections with google gdrive and frequent runtime errors have stopped training, hurting the learning process and overall mAP of my model. As a result, I have not been able to complete one training without multiple disconnections. 

### Web Browser
Chrome

### Request
I requested this a month ago and I received refund for only my additional purchases of computational resources. I am requesting a full refund for my google colab pro + purchase as I did not meet what was advertised while I also wasted too much time trying to train my model through colab pro +. If you check my notebook runs, you can find that not a single training exceeded 100 epochs.

**Comment by cperry-goog** [comment]
contact colab-billing@google.com for refund.
