### ISSUE TITLE
Loading data while using `R` runtime, results in an error

### ISSUE THREAD

**Issue by narayanivedam** [googlecolab/colabtools#4127]
I am using colab pro with R runtime on Google Chrome. Whenever I try to upload data (.RData) of size 250MB, using ```load("FILENAME.RData")```, I get the following error. 

<img width="522" alt="Screenshot 2023-11-03 at 5 20 56 PM" src="https://github.com/googlecolab/colabtools/assets/6894540/ead7f55f-9358-471b-bd32-c6b819e666f7">

An additional observation is that, it runs just fine while using colab without a subscription!

**Comment by craigcitro** [comment]
To confirm: you're saying you uploaded the file, and in the same session, couldn't read it? That's ... weird. :)

Can you still repro?
