### ISSUE TITLE
Not connected to a TPU runtime

### ISSUE THREAD

**Issue by rozanaljaber** [googlecolab/colabtools#4129]
i cant connect with tpu ,although i have colab pro plus subscription 

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
submit feedback internally - but oftentimes we stock out of TPUs due to heavy demand and low chip supply.
