### ISSUE TITLE
UI problem when running my code

### ISSUE THREAD

**Issue by DavidChou23** [googlecolab/colabtools#4131]
When I use GPU to run code, UI says it is connecting to backend, but my code is running, so that I can't observe the ram, gpu vram usage when running my code.
screenshot:
![image](https://github.com/googlecolab/colabtools/assets/127016703/4a5db261-2846-4d3f-9589-c91a81abe724)

**Describe the expected behavior**
When running my code, I expected that UI shows it is connected to backend gpu, so that I can observe the resource usage.

**What web browser you are using**
Edge(version 118.0.2088.76 (64 bits))

**Comment by mosmos6** [comment]
I encountered the same issue with TPU runtime about an hour ago (TPU runtime was unconnectable yesterday.).
My code was hanging forever. I refreshed the tab to know the notebook was attempting to connect to the runtime again, which means, it was quietly disconnected. I reset the runtime, reran, and it was ok.

**Comment by cperry-goog** [comment]
When you encounter this can you submit feedback internally? Resetting the runtime should work as I believe these errors are ephemeral.
