### ISSUE TITLE
Interruption in operation when training a model!

### ISSUE THREAD

**Issue by Bekzod25** [googlecolab/colabtools#4133]
I've bought many hours of TPU, but I've had to restart my session 5 times because of session interruptions. I have never logged out of google colab. The duration of my training is 2 days. But after 17 hours the training stopped! I ask you to fix this situation and add hours for me. My email that is used for work: info.rfid24@gmail.com

![image](https://github.com/googlecolab/colabtools/assets/110373695/fba32b54-dbd9-43cd-a773-66e778802650)

**Comment by cperry-goog** [comment]
Pro+ users get access to runtimes up to 24 hours (we do our best to get 24 hours, sometimes we may fall short?) If you need to train for 2 days, I'd recommend spinning up your own VM on GCP marketplace: https://research.google.com/colaboratory/marketplace.html

You will not face runtime length restrictions.
