### ISSUE TITLE
Colab Pro not using GPU RAM

### ISSUE THREAD

**Issue by grithub1** [googlecolab/colabtools#4134]
I have the colab pro membership but it is using 12.7 GB of System RAM instead of 32 GB.

This is seriously limilting my work and stalling it every few minutes.

**Comment by cperry-goog** [comment]
Are you referring to GPU RAM or System RAM? All our T4s have 16GB of RAM if memory serves. You'll want to reduce the memory footprint for the GPU or access an A100, OR you can configure your own machine on marketplace to your own specifications: https://research.google.com/colaboratory/marketplace.html
