### ISSUE TITLE
 Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install accelerate`

### ISSUE THREAD

**Issue by AlketaR** [googlecolab/colabtools#4136]
Since a couple of weeks running the code below fails with the error of the title of this issue 

```
"from transformers import MistralForCausalLM
model = MistralForCausalLM.from_pretrained("mistralai/Mistral-7B-v0.1",
    #load_in_8bit_fp32_cpu_offload=True, #needed to reduce the bits (which means less precission for the weights), to overcame RAM constraints
    device_map='auto',
    load_in_4bit=True,
)"
```

accelerate is installed:
```
accelerate                       0.24.1
bitsandbytes                     0.39.0
```

uninstalling/updating the packages above does not fix anything. The same code/notebook was working 1 month ago.

**Comment by irudnyts** [comment]
I found this [thread](https://stackoverflow.com/questions/76902752/importerror-using-low-cpu-mem-usage-true-or-a-device-map-requires-accelerat) with the solution to write `!pip -qqq install bitsandbytes accelerate`. For some reason, it works from time to time.

**Comment by cperry-goog** [comment]
This looks like a `transformers` bug; try contacting the maintainers
