### ISSUE TITLE
The Version Update Failed my code. Roll Back to old version missing

### ISSUE THREAD

**Issue by Gelesh** [googlecolab/colabtools#4137]
**Describe the current behavior**
[Issue Reported in StakcOverflow ](https://stackoverflow.com/questions/77433354/google-colab-roll-back)
The Code which worked failed. This is due to a version upgrade

**Describe the expected behavior**
Existing notebook must not be pushed to a new version, or a roll back option must be there.

**What web browser you are using**
Chrome

**Additional context**
Some Keras Package of my old code , Of Sept 2023 stopped working in Nov 6 2023. I am not remembering what all were those package by default by then.

Is there any way I can have the Google Colab roll back to a previous veriosn.

Below is the Error Message from my current code while complied a couple of months before

**Comment by mayankmalik-colab** [comment]
We upgraded keras from 2.13.1 to 2.14.0  and tf from 2.13.0 to 2.14.0 in mid Oct. Can you try downgrading and run your notebook:

```
!pip install tensorflow==2.13.0
!pip install keras==2.13.1
```

Otherwise, you might want to change your notebook to be compatible with upgraded versions.

**Comment by Gelesh** [comment]
I happened to figure out, `!pip install tensorflow==2.12.1 ` alone and _restart the Kernal_ does solves.Every time I open I have to do this.  However, if I had a couple of other package , it would have been trouble. Thanks @mayankmalik-colab .
However, I would still consider this as defect that, the version changed without user consent, and no option to revert back
