### ISSUE TITLE
Colab always restart when running kernel PCA on my dataset

### ISSUE THREAD

**Issue by goldboy225** [googlecolab/colabtools#4140]
**Describe the current behavior**

when running the code using kernel PCA to fit data, colab repeated restart, with following prompts:

Timestamp | Level | Message
-- | -- | --
Nov 7, 2023, 11:51:29 PM | WARNING | WARNING:root:kernel 8bcec051-2f17-43fa-9893-8031d3587b3d restarted
Nov 7, 2023, 11:51:29 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports

Nov 7, 2023, 11:43:20 PM | WARNING | WARNING:root:kernel 8bcec051-2f17-43fa-9893-8031d3587b3d restarted
-- | -- | --
Nov 7, 2023, 11:43:20 PM | WARNING | WARNING:root:kernel 8bcec051-2f17-43fa-9893-8031d3587b3d restarted
Nov 7, 2023, 11:43:20 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Nov 7, 2023, 11:41:20 PM | WARNING | WARNING:root:kernel 8bcec051-2f17-43fa-9893-8031d3587b3d restarted
Nov 7, 2023, 11:41:20 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Nov 7, 2023, 11:40:02 PM | WARNING | WARNING:root:kernel 8bcec051-2f17-43fa-9893-8031d3587b3d restarted
Nov 7, 2023, 11:40:02 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports

**Describe the expected behavior.
Running following code, colab always restart when running "X_3D = rbf_pca.fit_transform(X_scaled)".
Repeated for many times...

#Apply Kernal PCA to reduce data to 3 dimensions
from sklearn.decomposition import KernelPCA

rbf_pca = KernelPCA(n_components = 3, kernel="rbf", gamma=0.04)
X_3D = rbf_pca.fit_transform(X_scaled)

**What web browser you are using**
Chrome 116.0.5845.187 (x86_64)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
I can't diagnose from GitHub - can you submit feedback internally and reference this issue? We can see if there are any clues in our logs.

**Comment by Gainward777** [comment]
Same problem. Did you manage to find any solution?

**Comment by tybaltcapulett** [comment]
Exact same problem happening to me as well!!
