### ISSUE TITLE
from pandas_profiling import ProfileReport not available on colab notebook

### ISSUE THREAD

**Issue by AMisra18** [googlecolab/colabtools#4147]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
This appears to be a bug with pandas_profiling: even after I install and import pandas_profiling I get this error:

`PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.5/migration/#basesettings-has-moved-to-pydantic-settings for more details.`

Can you report it to Pandas?
