### ISSUE TITLE
Google Colabotary Change Runtime Box Bug

### ISSUE THREAD

**Issue by fatehfaez** [googlecolab/colabtools#4149]
**Describe the current behavior**
When I wanted to change the runtime type, the box showing up is jammed and doesn't show me the options, there is a very narrow window which i can only see the top of the written options. 

**Describe the expected behavior**
The options box should have allowed a clear view to the options. 

**What web browser you are using**
(Chrome on windows 11 home edition)

**Additional context**
I am sorry I dont know how to do all of the mentioned instructions, I thought to upload a screenshot to demonstrate the bug. 
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by katlyn-edwards** [comment]
So far, we've only seen this bug when you have an extension installed -- please disable your extensions to identify what extension is problemmatic.

See https://github.com/googlecolab/colabtools/issues/4018

**Comment by joshuafajardo** [comment]
Ran into the same issue. For me, it was the Norton Safe Web extension. Thanks Katlyn!
