### ISSUE TITLE
Unable to move cursor with bluetooth keyboard on iOS device's browser

### ISSUE THREAD

**Issue by may22es** [googlecolab/colabtools#415]
I recently using google colab on iPad with bluetooth keyboard.
But when I entered code block at google colab, I can not move cursor with bluetooth keyboard cursor key.

I triend on safary and chrome browser, all browser is same.

Google colab on pc browser with same keyboard, It does work well.

**Comment by blois** [comment]
I'm also seeing that Colab disconnects any time the escape key is pressed.

**Comment by blois** [comment]
Appears to be https://bugs.webkit.org/show_bug.cgi?id=149054

**Comment by mehmetoguzderin** [comment]
@blois Similar problem with monaco-editor is solved in CodeSandbox (which uses monaco-editor) with workarounds for iOS, adding proper arrow key support for Smart Keyboard and other external keyboards. Is it possible to have a workaround implementation for iOS until a proper WebKit fix comes?
