### ISSUE TITLE
error during model training at google colab

### ISSUE THREAD

**Issue by Abhiramisp1996** [googlecolab/colabtools#4154]
![image](https://github.com/googlecolab/colabtools/assets/151518381/6811dc5b-6be5-41e6-8ad6-ac4dda73a5ff)

**Comment by sineeli** [comment]
Hi @Abhiramisp1996,

Please install tf-keras

```
pip install tf-keras
```
this should resolve your issue

**Comment by Abhiramisp1996** [comment]
Thanks for replying..

Stuck with new error

[image: image.png]
