### ISSUE TITLE
Change runtime type Dialog Box - Selection Scroll Box Vertical Size Constrained

### ISSUE THREAD

**Issue by apprichm** [googlecolab/colabtools#4155]
**Describe the current behavior**
When selecting "Change Runtime Type" Dialog Box appears but the option scroll window is vertical size 16 and locked, rendering the scroll options not visible.

**Describe the expected behavior**
Selection window should be scrollable allowing selection of CPU/GPU options.

**What web browser you are using**
Chrome

![Screenshot 2023-11-20 184943](https://github.com/googlecolab/colabtools/assets/22620091/41c739b7-4c2f-4139-acaa-3ecbb9606f73)
![Screenshot 2023-11-20 210721](https://github.com/googlecolab/colabtools/assets/22620091/d73bfb25-86aa-4503-841f-30a176bccf51)

**Comment by cperry-goog** [comment]
Thanks @joshuafajardo  -- yeah, in general UI issues like this are caused by rogue browser extensions - for anyone reading this in the future try replicating the behavior in an incognito window to check.
