### ISSUE TITLE
ipycanvas doesn't render in colab

### ISSUE THREAD

**Issue by dhruvbird** [googlecolab/colabtools#4157]
**Describe the current behavior**
I expect ipycanvas to work in Colab since it works in Jupyter notebooks in general.

It also results in the following error in Chrome inspector.

```
manager.min.js:1867 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'constructor')
    at e (manager.min.js:1867:241234)
    at ct.switchCanvas (widget.ts:1581:38)
    at ct.processCommand (widget.ts:1581:38)
    at ct.onCommand (widget.ts:1581:38)
    at eval (widget.ts:1581:38)
```

**Describe the expected behavior**
Repro colab: https://colab.research.google.com/drive/1nrSz81QbvX164PBQ9Thl-aQZ-ZTkPTez#scrollTo=yKQdVnT8_ln7

After running all the cells, I expect a red box to be drawn, but it is not.

**What web browser you are using**
Chrome (Version 117.0.5938.88 (Official Build) (arm64)) on MacOS.

**Additional context**
https://colab.research.google.com/drive/1nrSz81QbvX164PBQ9Thl-aQZ-ZTkPTez#scrollTo=yKQdVnT8_ln7

**Comment by cperry-goog** [comment]
Tracking internally at b/315328773
