### ISSUE TITLE
Google Colab outputs disappears right after is shown 

### ISSUE THREAD

**Issue by MariamGamal12** [googlecolab/colabtools#4160]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by MariamGamal12** [comment]
I haven't been able to solve this problem. Since a few days ago my colab notebooks outputs have been malfunctioning: the outputs appear after the execution of the cell but disappear immediately. If I click on the fullscreen output I can see it, but it's very counterproductive
i'm using chrome

**Comment by cperry-goog** [comment]
Usually this is caused by a chrome browser extension - does this replicate in an incognito window for you?

**Comment by katyalrajat** [comment]
Hey, I am facing a similar issue.
It seems that the 'Next Steps' bar at the bottom loads (AI feature) and overrides the output of the cell in some cases (example df.head()). I tried to disable the AI features in settings, but it still continues to show. I haven't added any new extensions on chrome. If i click on view output fullscreen then the result shows.
