### ISSUE TITLE
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/colabtools/dist/google-colab-1.0.0.tar.gz'

### ISSUE THREAD

**Issue by Abhiramisp1996** [googlecolab/colabtools#4161]
![image](https://github.com/googlecolab/colabtools/assets/151518381/2f213c99-5d34-4c48-87eb-a1ba349f1081)

**Comment by cperry-goog** [comment]
what code triggered this error?

**Comment by qeFLilyum** [comment]
How did you solve it may i ask?
