### ISSUE TITLE
Bad Link: Notebooks > Data Visualization > Explore patent database with ml

### ISSUE THREAD

**Issue by clarkdever** [googlecolab/colabtools#4168]
**Describe the current behavior**
Given: I visit https://colab.google/notebooks/ and scroll down to the Data Vizualization[sic] header
When: I click on the card titled  Explore patent database with ml
Then: I am sent to the Colab for mediapy

**Describe the expected behavior**
I should be sent to the Colab for Exploring the Patent Database with ML

**What web browser you are using**
Firefox

**Additional context**
![image](https://github.com/googlecolab/colabtools/assets/416106/438725d9-d924-484e-b8e5-66152e219e30)

1. Additionally, you should consider changing the spelling from Vizualization to Visualization in the header.

**Comment by cperry-goog** [comment]
this is now fixed, thanks for reporting
