### ISSUE TITLE
Add a ipython command to push the notebook to a repo

### ISSUE THREAD

**Issue by intotecho** [googlecolab/colabtools#417]
We can [now ](https://github.com/googlecolab/colabtools/issues/124) integrate with github and private gith repo but it requires pushing the save UI button. 

We can push content to the repo but not the notebook to the repo as we don't know the path to the notebook - and it is not in the repo.

Can the notebook reference itself (notebook.ipynb)? I expect the path depends on the runtime. 
A command could return the path to notebook.ipynb.
Then we could push a version of it to the repo.

This would be great for building a ML training workflow that records the parameters of many experiments.

**Comment by blois** [comment]
Currently the notebook JSON file only exists in the browser client. A rough overview of the flow is https://jupyter.readthedocs.io/en/latest/architecture/how_jupyter_ipython_work.html#notebooks (though this is slightly different for Colab)
