### ISSUE TITLE
Output is not getting displayed.

### ISSUE THREAD

**Issue by bimal-gajera** [googlecolab/colabtools#4170]
The output is colab notebook is not working properly. If faced issues while printing plots, dataframe, and other kinds of output. The output gets displayed for a second after cell running is complete and then it disappears.
![image](https://github.com/googlecolab/colabtools/assets/90305421/578eeb7f-4cc7-4aba-91aa-7cbcedd72d11)
In this image the plot was displayed for a second then it disappeared.

**Comment by cperry-goog** [comment]
Does this reproduce in an incognito window? UI bugs like these are usually the result of conflicting browser extensions.

**Comment by bimal-gajera** [comment]
It's working in incognito, Thanks!!
Any suggestion about what browser extension might be conflicting? I'm using Chrome.

**Comment by cperry-goog** [comment]
I'm so sorry, no idea! Closing this for now - if you see this again in an incognito window please do open a new bug.

**Comment by NastiiaKoval** [comment]
Thanks! In my case I have conflict with browser extensions "scrnli" for record screen

**Comment by Mariahameed89** [comment]
cant open in incognito am mount my drive 😥
