### ISSUE TITLE
Output not being displayed

### ISSUE THREAD

**Issue by tadiwamark** [googlecolab/colabtools#4175]
Output is not being displayed. It's just appearing for a few seconds, then disappearing. Expected behaviour is output and error being displayed when I run a cell. I'm using Chrome

![image](https://github.com/googlecolab/colabtools/assets/64325379/f8186f46-d488-44ff-889d-0de373fabab3)

**Comment by cperry-goog** [comment]
Does this reproduce in an incognito window? Usually these types of bugs are due to browser extensions.
