### ISSUE TITLE
numba 0.58.1 metadata not found

### ISSUE THREAD

**Issue by xerxes-k** [googlecolab/colabtools#4176]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

[/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in _get()
   1724 
   1725     def _get(self, path):
-> 1726         with open(path, 'rb') as stream:
   1727             return stream.read()
   1728 

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/numba-0.58.1.dist-info/METADATA'

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

I DON'T EVEN NEED NUMBA 0.58.1
my requirements are numba 0.56.x

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
Do you have the code that triggered this?

**Comment by xerxes-k** [comment]
the code involves prop package ... i've checked with them and they don't specify numba version too
