### ISSUE TITLE
Notebook is not running with GPU

### ISSUE THREAD

**Issue by Arwa-97** [googlecolab/colabtools#4179]
I subscribed to Colab Pro+ and set the notebook runtime type to A100
but it is using the system ram not the gpu ram when running the code !
(using chrome)

what is the issue how to run the code with gpu ?

<img width="524" alt="Screenshot 2023-11-28 at 9 44 23 PM" src="https://github.com/googlecolab/colabtools/assets/60826257/fdb023f7-c69e-4b3a-8839-b167c7823d8f">

**Comment by cperry-goog** [comment]
I don't think this is a Colab issue - you'll want to ensure your code is properly accessing GPU RAM
