### ISSUE TITLE
colab auto disconnect

### ISSUE THREAD

**Issue by jaideep11061982** [googlecolab/colabtools#418]
Google colab getting auto disconnected even there are no internet issues. This is happening due to inability to allocate the GPU. This is happening since last 3 to 4 days. I have been using colab since 3-4 months.

**Comment by jaideep11061982** [comment]
any update... connectivity to colab is getting limited ds days...

**Comment by colaboratory-team** [comment]
Please share a self-contained notebook that reproduces the problem and we'll take a look.
