### ISSUE TITLE
Allow `drive.mount()` with Secrets

### ISSUE THREAD

**Issue by recycletechno** [googlecolab/colabtools#4182]
**Is your feature request related to a problem? Please describe.**
Each time after restarting the notebook, it is necessary to run a separate cell containing the code to connect to Google Drive, and several actions need to be performed to connect it in a separate window.

**Describe the solution you'd like**
After adding Google Secrets, it became possible to store sensitive information managed by a Google account and connect the necessary variables by calling the `userdata.get('<secretName>')` function. Some time ago, users were asked to enter the code that appears in an additional window for authorization on Google Drive. Later, the code input was replaced by confirming consent simply by using the mouse. 
If it were possible to save and automatically input the code that was requested earlier through Google Secrets, the authorization on Google Drive would be much faster and would not require additional user interactions, as they have already given their consent to save the Google Drive key in the Secrets section.

Maybe provide an additional argument to `drive.mount()` like `secret_key=12345` which will be stored in Google Secrets only. So the final call would look like:

```
from google.colab import drive, userdata
drive.mount('/content/drive', secret_key=userdata.get('secretName'))
```

**Comment by cperry-goog** [comment]
thanks for the request!

**Comment by colaboratory-team** [comment]
This is an interesting request, but we're unfortunately likely not going to be able to do it. For one, the authorization code that used to be pasted in does not last indefinitely, so you would still need to paste in a new one whenever the old one expired. Secondly, in our new flow that you've seen, the consent dialog is required for security reasons, so there's not a good way to bypass it
