### ISSUE TITLE
emacs keybindings support in colab

### ISSUE THREAD

**Issue by kpe** [googlecolab/colabtools#419]
It would be great if I could use **emacs keybindings** in google colab!

As CodeMirror already have builtin support for both emacs and vim keybindngs, it might be already sufficient to add a keybindings option in the preferences menu. And by the way - JupyterLab already has a "**Settings->Text Editor Key Map**" menu entry (it doesn't quite work yet for cells, but... it seems to be intentional - see https://github.com/jupyterlab/jupyterlab/issues/3885#issuecomment-412294469 ).

*N.B.* I have a simple labextension for jupyterlab (s. [kpe/jupyterlab-emacskeys](https://github.com/kpe/jupyterlab-emacskeys)), but it would be great if one could also use some of the essential emacs style keybindings in colab.

**Comment by ihowell** [comment]
Hey @kpe . Can we close this? I just checked out if Google Colab has this, settings -> editor -> editor key bindings -> emacs, and it seemed to have the bindings. Could you confirm you see these?

**Comment by jramapuram** [comment]
I don't see this as supported? 

![Image](https://github.com/user-attachments/assets/8ee0b6c5-38b6-45b7-8a79-c395c8cd8d8d)
