### ISSUE TITLE
[Emergency] Can't access my a100 and keep switching to v100 gpu for my colab pro account

### ISSUE THREAD

**Issue by PrimordialCoder** [googlecolab/colabtools#4205]
Whenever i try to select a100 gpu in change runtime i am keep getiing switched to v100 instead. I have a project to work on and deadline is approaching. Here are some screenshots
![Screenshot 2023-12-09 185251](https://github.com/googlecolab/colabtools/assets/114156951/3edc7953-0e89-402a-9ccd-93fc84d1fd8e)
![Screenshot 2023-12-09 185154](https://github.com/googlecolab/colabtools/assets/114156951/f1b2dd47-012a-4480-8f61-6152f5d51d59)

**Comment by AfnanTurky** [comment]
I've been facing the same problem for a week. 
please Help

**Comment by sahil301290** [comment]
Facing same problem. Is Google using A100 for their own use and not giving to Colab Pro users?
Are we being scammed?

**Comment by cperry-goog** [comment]
We can't guarantee a specific accelerator - A100s have been stocking out and I can't get more capacity from GCS. Doing our best. We fall back to V100 if it doesn't exist.

Alternative is you can sign up for GCP Marketplace or Vertex and request an A100 through them, or use a local runtime with a GPU you acquire elsewhere. Sorry.

**Comment by CharmingSteve** [comment]
I joined the colab pro so that I can run some good models, but they don't run as it needs a100 with memory and stuff. The towards the end of the run with an a100, Once I get assigned one, the a100 is taken from me beforfe the end. really sucks!
