### ISSUE TITLE
Poor translation in the menu

### ISSUE THREAD

**Issue by tueda** [googlecolab/colabtools#4206]
**Describe the current behavior**

I do not know if this is the right place to post it, but there is a misleading translation in the menu of [Google Colab in Japanese](https://colab.research.google.com/?hl=ja).

English:
- Runtime
    - Restart session
    - Restart session and run all

Japanese:
- ランタイム
    - セッションを**再開する**
    - セッションを**再開して**すべて実行する
 
I know this translation may be obtained by Google Translate or DeepL Translator, but unfortunately, they usually mean
- Runtime
    - **Resume** session
    - **Resume** session and run all
  
So, Japanese users may wonder what will be resumed.

Some screenshots, which may be helpful:

<img src="https://github.com/googlecolab/colabtools/assets/1481665/40a7b67e-fbe2-4e05-a5e0-6dcbc93db073" height="350"/>
<img src="https://github.com/googlecolab/colabtools/assets/1481665/38de78cc-0609-4354-bd28-55dfba11b6c8" height="340"/>

<img src="https://github.com/googlecolab/colabtools/assets/1481665/a48f69cc-a401-4cc9-b2a2-72740be5d368" height="280"/>

**Describe the expected behavior**

"再起動する" is the proper verb corresponding to "restart" (or "reboot").

- ランタイム
    - セッションを**再起動する**
    - セッションを**再起動して**すべて実行する

**What web browser you are using**

Chrome

**Additional context**

 
I believe this mistranslation has been introduced recently; before that, I think it was fine ("再起動する" was used, as far as I remember).

**Comment by cperry-goog** [comment]
thanks, we'll take a look

**Comment by katlyn-edwards** [comment]
We requested a re-translation, it should be live now! Thanks for the report!
