### ISSUE TITLE
Downgrade CUDA to 9.2

### ISSUE THREAD

**Issue by noblakit01** [googlecolab/colabtools#421]
Hi Colab team,

I need to use [Torch](http://torch.ch) in my notebooks but it can't be installed on CUDA 10.0.  

So I'm trying to downgrade CUDA in Google Colab to version 9.2.

Does it possible to do this on Colab now?

**Comment by craigcitro** [comment]
No, there's no way to change the cuda version inside colab. 

It looks like https://github.com/torch/cutorch/issues/834 has some folks trying to build from source with cuda10, with mixed success.

**Comment by noblakit01** [comment]
Thanks for quick response. I will give a try
