### ISSUE TITLE
Upgrade to CUDA 12.2,  tensorflow 2.15.0, keras 2.15.0, and Nvidia driver 535.104.05

### ISSUE THREAD

**Issue by mayankmalik-colab** [googlecolab/colabtools#4214]
### Upgrade to CUDA 12.2,  tensorflow 2.15.0, keras 2.15.0, and Nvidia driver 535.104.05
The Colab runtime is going to be upgraded to `CUDA 12.2`,  `tensorflow 2.15.0`, `keras 2.15.0`, and Nvidia driver `535.104.05` this week or early next week. Please upgrade your notebooks to be compatible with the changes.

#### Colab’s fallback runtime version

Using the fallback runtime version temporarily allows access to the last version of the runtime before the upgrade described above, and is available until early Jan. Its purpose is to provide a temporary mechanism for users to more smoothly upgrade their notebooks to be compatible with Colab’s current runtime version. This will be available from the Command Palette via the "Use fallback runtime version" command when connected to a runtime. Of note, this setting does not persist across sessions – the command will need to be invoked on each new session.

**Comment by F10JM** [comment]
is there a way to go back to the previous version of cuda?

**Comment by mayankmalik-colab** [comment]
Yes, you can follow the steps mentioned under the heading `Colab’s fallback runtime version` on the top.

**Comment by AkshayAbraham** [comment]
is there any chance do you know about the exact date of this USE FALLBACK RUNTIME VERSION becoming unavailable. I just wanted to finish my project before it is getting unavailable. 
Thankyou

**Comment by dking21** [comment]
Hi, I don't see "Colab's fallback runtime version". can you share me the screenshot where I can see it?

**Comment by AkshayAbraham** [comment]
> Hi, I don't see "Colab's fallback runtime version". can you share me the screenshot where I can see it?

Connect to your GPU and go to tools -> command palette -> search for use fallback runtime version

**Comment by m1337v** [comment]
@mayankmalik-colab onnxruntime is still incompatible with cuda 12.2. This is something that can't be fixed by updating the workbook. Please keep the option to use the fallback version available for a longer time or at least until a cuda 12.2 onnxruntime update is released

**Comment by mayankmalik-colab** [comment]
> @mayankmalik-colab onnxruntime is still incompatible with cuda 12.2. This is something that can't be fixed by updating the workbook. Please keep the option to use the fallback version available for a longer time or at least until a cuda 12.2 onnxruntime update is released

Yes, we understand updating CUDA was a big jump. We will try to keep the option to use fallback version available for as long as we can.

**Comment by m1337v** [comment]
@mayankmalik-colab 
Looks like the fallback runtime is not available anymore.
Whenever i select it i get an error that it's not available.
This is happening for some days already

**Comment by RahmatBudiarsa09** [comment]
Yes me too
the fallback runtime is not available anymore

**Comment by mayankmalik-colab** [comment]
If you are already on fallback, then it would tell you that message. Try creating a new notebook and then try "Use fallback runtime version" command from command palette.

**Comment by beveradb** [comment]
For anyone else who just wants to be able to use `onnxruntime-gpu` from python on Colab again and doesn't want to go through the hassle of compiling from source or waiting for the official 1.17 release;

You can uninstall the release version and install this wheel I built from the latest `onnxruntime` source earlier today (on a colab instance):

`pip uninstall onnxruntime-gpu`
`pip install https://github.com/karaokenerds/python-audio-separator/releases/download/v0.12.1/onnxruntime_gpu-1.17.0-cp310-cp310-linux_x86_64.whl`

**Comment by G-force78** [comment]
> For anyone else who just wants to be able to use `onnxruntime-gpu` from python on Colab again and doesn't want to go through the hassle of compiling from source or waiting for the official 1.17 release;
> 
> You can install this wheel I built from the latest `onnxruntime` source earlier today (on a colab instance):
> 
> `pip install https://github.com/karaokenerds/python-audio-separator/releases/download/v0.12.1/onnxruntime_gpu-1.17.0-cp310-cp310-linux_x86_64.whl`

Legend, thank you!

**Comment by Rakeshkumar-7** [comment]
> For anyone else who just wants to be able to use `onnxruntime-gpu` from python on Colab again and doesn't want to go through the hassle of compiling from source or waiting for the official 1.17 release;
> 
> You can install this wheel I built from the latest `onnxruntime` source earlier today (on a colab instance):
> 
> `pip install https://github.com/karaokenerds/python-audio-separator/releases/download/v0.12.1/onnxruntime_gpu-1.17.0-cp310-cp310-linux_x86_64.whl`

This worked. Thank you so much for the help and saving me a bunch of time! <3

**Comment by mayankmalik-colab** [comment]
We are planning to remove `Colab’s fallback runtime version` sometime middle/end of this week.

**Comment by mithras666** [comment]
Noo :(

**Comment by fastcode99** [comment]
@mayankmalik-colab can we keep the fallback runtime longer? we still don't have time to adapt to the new CUDA
