### ISSUE TITLE
shrunk screen to change runtime type

### ISSUE THREAD

**Issue by Darol23** [googlecolab/colabtools#4215]
Hello Everyone,

When I want to change the runtime type of any google collab, in the runtime section, the screen get shrunk. It is hard to adjust the parameters.

![change runtime type](https://github.com/googlecolab/colabtools/assets/153650971/93ee2679-0f10-4198-a45d-b705052ffa26)

**Describe the expected behavior**
 I would like to have the same screen as in the edit section, in notebook settings, where it is understandable.
![notebook settings](https://github.com/googlecolab/colabtools/assets/153650971/5a9707a2-246d-4a94-852d-9d1b57cd19a1)

**What web browser you are using**

Chrome

Thank you in advance for your attention

**Comment by cperry-goog** [comment]
We've had a bunch of reports of this - they're all due to a browser extension conflicting with our UI. If you try it in an incognito window it should appear normally. Uninstall the offending browser extension and you're good to go.

If you find this repos in an incognito window open a new bug.
