### ISSUE TITLE
Impain or Outpain of image does not work already for 3 days

### ISSUE THREAD

**Issue by AhojAhoj145** [googlecolab/colabtools#4216]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
We'll need a minimal reproducible notebook shared publicly to investigate. Though this does not appear to be a Colab issue - my suspicion is you'll have more luck contacting the notebook author.
