### ISSUE TITLE
fooocus_colab.ipynb gives errors

### ISSUE THREAD

**Issue by hwovirtualmodels** [googlecolab/colabtools#4218]
Colab gives an error message on all type of requests, text or image, even after several restart.
Using Chrome.

**Comment by cperry-goog** [comment]
What errors are you seeing? I think we might have started restricting fooocus on the free of charge tier due the webui working around our notebook ui.

**Comment by hwovirtualmodels** [comment]
Very helpful. It's working now. I think I'm going to upgrade to pro+ as I can see the page getting more popular. The results are amazing and I haven't seen anything as good anywhere else. I really love it. If you're looking for customer feedback etc I'd be interested to take part. Thanks again

**Comment by cperry-goog** [comment]
Great thanks!
