### ISSUE TITLE
input()

### ISSUE THREAD

**Issue by MiniSkoot32** [googlecolab/colabtools#4219]
My input() when i change the code, he first time it will not show it. I run my code again and it works. I am on a chromebook s330 using chrome.

**Comment by cperry-goog** [comment]
We'll need a minimal reproducible notebook shared publicly to investigate

**Comment by MiniSkoot32** [comment]
Don;t take the rest of my code, it is copyrighted.

**Comment by EvanWiederspan** [comment]
We just need the minimal amount of code that shows the issue you're seeing
