### ISSUE TITLE
After the google colab update, cuda updated to 12.2 but i absolutely need cuda 12 for my model to work like it did 2 days ago

### ISSUE THREAD

**Issue by F10JM** [googlecolab/colabtools#4227]
**Describe the current behavior**
2 days ago before the update of google colab, my model was training on gpu acceleration just fine with cuda 12 and tensorflow 2.13 but now with cuda 12.2 im forced to use tensorflow 2.15 but my model only works with version of tensorflow <12.13. When i check the google colab files in  /usr/local/ there are 2 folders cuda-12 and cuda-12.2 so i assume there should be a way to make the version of cuda utilized 12 instead of 12.2

**Describe the expected behavior**
I really need to find a way to change the cuda version back to what it was 2 days ago

**What web browser you are using**
chrome

**Comment by mayankmalik-colab** [comment]
We were on CUDA 11.8 before upgrading to 12.2. Anyways, we are aware of the fact that  tf<2.15 may not work with CUDA 12.2, so I would recommend either using tf2.15 or If you still want to use tf<2.15, you can use fallback version of Colab for a few more days as mentioned [here]( https://github.com/googlecolab/colabtools/issues/4214.).

**Comment by mayankmalik-colab** [comment]
Follow updates on #4214

**Comment by jchucAD** [comment]
For me, the upgrade to cuda 12.2 has totally changed the performance of my FT2.8 model, in the bad way :( 
Did someone experience the same thing?
So, now I try to install cuda 11.8.x to verify if I can come back to a best result as it was begin of december!
