### ISSUE TITLE
Issues with GEE API, api is enabled but it's saying it isn't - URGENT FOR UNIVERSITY PROJECT

### ISSUE THREAD

**Issue by NaoCipherCS** [googlecolab/colabtools#4228]
385     raise _translate_cloud_exception(e)  # pylint: disable=raise-missing-from
    386 
    387 

EEException: Google Earth Engine API has not been used in project 522309567947 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/earthengine.googleapis.com/overview?project=522309567947 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry._

**Describe the expected behavior**

I've run this project for 2 months and never had any issues with authentication until now. Nothing has changed and I am the sole owner and the API is enabled.

I am using Chrome.

I'm using this for my final year project due in a few weeks and I need this working yesterday, please help me! Is the API down?

**Comment by EvanWiederspan** [comment]
That looks like it's trying to authenticate with the default cloud project instead of your own. Does running the following before calling EE fix it?

```
from google.colab import auth
auth.authenticate_user(project_id=YOUR_CLOUD_PROJECT_ID)
```

**Comment by NaoCipherCS** [comment]
Hi Evan,
<img width="908" alt="githubimage" src="https://github.com/googlecolab/colabtools/assets/30591044/94f471bb-d582-4d2b-ba3b-49746ab32dd8">


I've just added that before everything else. Now it's having a problem with ee.Initialize().

**Comment by NaoCipherCS** [comment]
<img width="364" alt="image" src="https://github.com/googlecolab/colabtools/assets/30591044/828c5ca3-99b2-48ba-abee-73cb3c94cc8e">
I literally am the owner and have these permissions.....

**Comment by MottaD2** [comment]
Hi, @NaoCipherCS. I also encountered this issue with the Google Earth Engine API while running my code. It seems that the project ID they gave me is the same ID they gave to you. So far, I haven't been able to solve this problem.
![bug](https://github.com/googlecolab/colabtools/assets/110045249/a9ba48ec-11a6-404b-889f-819095df75b9)

**Comment by NaoCipherCS** [comment]
Whoa confusing...do we think this is a new GEE problem?

**Comment by MottaD2** [comment]
Probably yes, notice that the ID is the same. We are in the same situation, because my project is also for the university. I have already authorized the API at the link they provided and the error persists.

**Comment by NaoCipherCS** [comment]
Ugh, what a mess!

I've posted this on Linkedin with a few hashtags and have emailed a few other people on G Colab projects I know to see if they're also having issues. Also contacted Goog so if I get any answers, i'll let you know...

Needed things working yesterday, hope you're not in the same situation?

**Comment by MottaD2** [comment]
Well, I need it to be working at least until Monday... But I'll wait for your news and hope it starts working again!

**Comment by NaoCipherCS** [comment]
Wow it actually worked!!!!! Thank you so much!!!

**Comment by mbayad33** [comment]
Hello, 

Could you please help me resolve this, I have been stuck with this issue for many days now. 
I have got the same issue even by doing those steps:

step1:
from google.colab import auth
auth.authenticate_user(project_id='ee-carbon') 
#ee-carbon is the my project-ID
import ee
step: 2
#Initilize with project
ee.Initialize(project='ee-carbon')

GEE API is enables in my GCS project.
Alo I'am owner of the specified project and I have added service Usage Consumer role. 
The I've got this error: 
WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "PERMISSION_DENIED"
---------------------------------------------------------------------------
HttpError                                 Traceback (most recent call last)
[<ipython-input-3-f0315e159e1e>](https://localhost:8080/#) in <cell line: 5>()
      3 
      4 #Initilize with project
----> 5 ee.Initialize(project='ee-carbon')

11 frames
[/usr/local/lib/python3.10/dist-packages/ee/_utils.py](https://localhost:8080/#) in wrapper(*args, **kwargs)
     37           if new_key not in kwargs:
     38             kwargs[new_key] = old_key_val
---> 39       return func(*args, **kwargs)
     40 
     41     return wrapper

[/usr/local/lib/python3.10/dist-packages/ee/__init__.py](https://localhost:8080/#) in Initialize(credentials, url, cloud_api_key, http_transport, project)
    138     credentials = data.get_persistent_credentials()
    139 
--> 140   data.initialize(
    141       credentials=credentials,
    142       api_base_url=(url + '/api' if url else None),

[/usr/local/lib/python3.10/dist-packages/ee/data.py](https://localhost:8080/#) in initialize(credentials, api_base_url, tile_base_url, cloud_api_base_url, cloud_api_key, project, http_transport)
    223     _requests_session = requests.Session()
    224 
--> 225   _install_cloud_api_resource()
    226 
    227   if project is not None:

[/usr/local/lib/python3.10/dist-packages/ee/data.py](https://localhost:8080/#) in _install_cloud_api_resource()
    298   timeout = (_deadline_ms / 1000.0) or None
    299   assert _requests_session is not None
--> 300   _cloud_api_resource = _cloud_api_utils.build_cloud_resource(
    301       _cloud_api_base_url,
    302       _requests_session,

[/usr/local/lib/python3.10/dist-packages/ee/_cloud_api_utils.py](https://localhost:8080/#) in build_cloud_resource(api_base_url, session, api_key, credentials, timeout, headers_supplier, response_inspector, http_transport, raw)
    193     # but it's not backward-compatible. There's no reliable way to check the
    194     # package version, either.
--> 195     resource = build(static_discovery=False)
    196   except TypeError:
    197     pass  # Handle fallback case outside except block, for cleaner stack traces.

[/usr/local/lib/python3.10/dist-packages/ee/_cloud_api_utils.py](https://localhost:8080/#) in build(**kwargs)
    177 
    178   def build(**kwargs):
--> 179     return discovery.build(
    180         'earthengine',
    181         VERSION,

[/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py](https://localhost:8080/#) in positional_wrapper(*args, **kwargs)
    128                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    129                     logger.warning(message)
--> 130             return wrapped(*args, **kwargs)
    131 
    132         return positional_wrapper

[/usr/local/lib/python3.10/dist-packages/googleapiclient/discovery.py](https://localhost:8080/#) in build(serviceName, version, http, discoveryServiceUrl, developerKey, model, requestBuilder, credentials, cache_discovery, cache, client_options, adc_cert_path, adc_key_path, num_retries, static_discovery, always_use_jwt_access)
    314                 continue
    315             else:
--> 316                 raise e
    317 
    318     # If discovery_http was created by this function, we are done with it

[/usr/local/lib/python3.10/dist-packages/googleapiclient/discovery.py](https://localhost:8080/#) in build(serviceName, version, http, discoveryServiceUrl, developerKey, model, requestBuilder, credentials, cache_discovery, cache, client_options, adc_cert_path, adc_key_path, num_retries, static_discovery, always_use_jwt_access)
    285 
    286         try:
--> 287             content = _retrieve_discovery_doc(
    288                 requested_url,
    289                 discovery_http,

[/usr/local/lib/python3.10/dist-packages/googleapiclient/discovery.py](https://localhost:8080/#) in _retrieve_discovery_doc(url, http, cache_discovery, serviceName, version, cache, developerKey, num_retries, static_discovery)
    420     # Note that it will already raise an error if we don't get a 2xx response
    421     req = HttpRequest(http, HttpRequest.null_postproc, actual_url)
--> 422     resp, content = req.execute(num_retries=num_retries)
    423 
    424     try:

[/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py](https://localhost:8080/#) in positional_wrapper(*args, **kwargs)
    128                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    129                     logger.warning(message)
--> 130             return wrapped(*args, **kwargs)
    131 
    132         return positional_wrapper

[/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py](https://localhost:8080/#) in execute(self, http, num_retries)
    936             callback(resp)
    937         if resp.status >= 300:
--> 938             raise HttpError(resp, content, uri=self.uri)
    939         return self.postproc(resp, content)
    940 

HttpError: <HttpError 403 when requesting https://earthengine.googleapis.com/$discovery/rest?version=v1&prettyPrint=false returned "Caller does not have required permission to use project ee-carbon. Grant the caller the roles/serviceusage.serviceUsageConsumer role, or a custom role with the serviceusage.services.use permission, by visiting https://console.developers.google.com/iam-admin/iam/project?project=ee-carbon and then retry. Propagation of the new permission may take a few minutes.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developer console IAM admin', 'url': 'https://console.developers.google.com/iam-admin/iam/project?project=ee-carbon'}]}, {'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'USER_PROJECT_DENIED', 'domain': 'googleapis.com', 'metadata': {'service': 'earthengine.googleapis.com', 'consumer': 'projects/ee-carbon'}}]">

**Comment by NaoCipherCS** [comment]
instead of from google.colab import auth
auth.authenticate_user(project_id='ee-carbon')

try just ee.Authenticate()

keep ee.Initialize(project='ee-carbon') as is.

Let us know if that works!

**Comment by mbayad33** [comment]
Good news!
I run the same code in jupyter notebook and it woked just fine. I think the problem is in Colab.

I uploded the .tif files from bucket to assest using this code:

!pip install earthengine-api --upgrade

import ee
ee.Authenticate()
ee.Initialize(project='my_project_id')

file_name = 'C:/Users/Downloads/manifest.json' # path to manifest json file...

Upload....
!earthengine upload image --manifest {file_name}

many thanks for yoyr feedback!

**Comment by hafez-ahmad** [comment]
I tried every possible way, not working , access denied 
---------------------------------------------------------------------------
HttpError                                 Traceback (most recent call last)
[<ipython-input-16-99e03d56abd3>](https://localhost:8080/#) in <cell line: 1>()
----> 1 ee.Initialize()

11 frames
[/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py](https://localhost:8080/#) in execute(self, http, num_retries)
    936             callback(resp)
    937         if resp.status >= 300:
--> 938             raise HttpError(resp, content, uri=self.uri)
    939         return self.postproc(resp, content)
    940 

HttpError: <HttpError 403 when requesting https://earthengine.googleapis.com/$discovery/rest?version=v1&prettyPrint=false returned "Caller does not have required permission to use project studenthafez100. Grant the caller the roles/serviceusage.serviceUsageConsumer role, or a custom role with the serviceusage.services.use permission, by visiting https://console.developers.google.com/iam-admin/iam/project?project=studenthafez100 and then retry. Propagation of the new permission may take a few minutes.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developer console IAM admin', 'url': 'https://console.developers.google.com/iam-admin/iam/project?project=studenthafez100'}]}, {'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'USER_PROJECT_DENIED', 'domain': 'googleapis.com', 'metadata': {'service': 'earthengine.googleapis.com', 'consumer': 'projects/studenthafez100'}}]">

**Comment by zhuang-hao-ming** [comment]
> Good news! I run the same code in jupyter notebook and it woked just fine. I think the problem is in Colab.
> 
> I uploded the .tif files from bucket to assest using this code:
> 
> !pip install earthengine-api --upgrade
> 
> import ee ee.Authenticate() ee.Initialize(project='my_project_id')
> 
> file_name = 'C:/Users/Downloads/manifest.json' # path to manifest json file...
> 
> Upload.... !earthengine upload image --manifest {file_name}
> 
> many thanks for your feedback!


hello @mbayad33  I think you are right. Using jupyter notebook in local computer work. this is a very strange problem.

**Comment by Vk0z** [comment]
> ee.Initialize(project='add here') Step 1: Goto cloud console --> API and services ![image](https://private-user-images.githubusercontent.com/34327057/291045932-f02a9d2f-42ec-490d-bd02-95881000e565.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzMwNzMsIm5iZiI6MTcwNTA3Mjc3MywicGF0aCI6Ii8zNDMyNzA1Ny8yOTEwNDU5MzItZjAyYTlkMmYtNDJlYy00OTBkLWJkMDItOTU4ODEwMDBlNTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkOGM1YzU3MzI1M2M3YzgyNmY2NjA0YzY2MTRlZWFlMjQ3NmRiZjI0NWVlZWUxMjg3MzhjNTZkM2U1YjljMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S5JKgfPtHgxSCO2Y2ftRl01QsUPnyBrDcblIlW6wIMw)
> 
> Step 2: Enable API and Services ![image](https://private-user-images.githubusercontent.com/34327057/291044817-028b108e-00f5-4532-bd63-b60b10ba81c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzMwNzMsIm5iZiI6MTcwNTA3Mjc3MywicGF0aCI6Ii8zNDMyNzA1Ny8yOTEwNDQ4MTctMDI4YjEwOGUtMDBmNS00NTMyLWJkNjMtYjYwYjEwYmE4MWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0OWY2MGRiYTNkMDkzYTQzOTBkY2E3NjJmYjI2YWE0YjI1ODE4OGU0MzRhMTM2NGNiYmYwNWQzNjZkYzU2OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aFO3AyH7X5xJnQJTCvXVrDUYpXdHQrVPC_D1Gjy6CK0)
> 
> Step 3: Search for 'Google Earth Engine API' ![image](https://private-user-images.githubusercontent.com/34327057/291044973-d9fe6fcd-212e-43a3-a6e5-e95d39a150e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzMwNzMsIm5iZiI6MTcwNTA3Mjc3MywicGF0aCI6Ii8zNDMyNzA1Ny8yOTEwNDQ5NzMtZDlmZTZmY2QtMjEyZS00M2EzLWE2ZTUtZTk1ZDM5YTE1MGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiODYzY2M1MmM2NGUyYWE4NzNhYmI5NmY4MDJjMzJmYmUyZTA4YTU3Zjg1YWQ1YTJhMTdiNTZlMzBjYzE5M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f71M0ZcnJ0rI8KiwwH_msjHca_NLpxTvXRmuin5zgLA)
> 
> Step 4: Make sure 'Google Earth Engine API' is enabled ![image](https://private-user-images.githubusercontent.com/34327057/291045122-2ddd9e76-5c15-4a60-9395-18af41a0441f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzMwNzMsIm5iZiI6MTcwNTA3Mjc3MywicGF0aCI6Ii8zNDMyNzA1Ny8yOTEwNDUxMjItMmRkZDllNzYtNWMxNS00YTYwLTkzOTUtMThhZjQxYTA0NDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NzllYTdmNzdkMDQ4MmRhM2JkOThlNzlmMzM4M2NkZDJlYTZmOTJiNmE4ZmIyNjliZmFlZWNlNDNhMjJhY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZV-GnK5iEdMPicQL-76kBUBlvZg5KO0NuM8_V1NQHRQ)
> 
> Step 5: Instead of ee.Initialize() use ee.Initialize(project='project_id') ![image](https://private-user-images.githubusercontent.com/34327057/291045386-4c201148-d47b-416f-a36a-6ea9935b5fab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzMwNzMsIm5iZiI6MTcwNTA3Mjc3MywicGF0aCI6Ii8zNDMyNzA1Ny8yOTEwNDUzODYtNGMyMDExNDgtZDQ3Yi00MTZmLWEzNmEtNmVhOTkzNWI1ZmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMTgzYTg0OGQzOTQwYTRjYjU0YzQ2ZjI0Nzg1MzhjZjY5YWQxMjZkNGIyNjI4MmFlODU0Y2YyYmUyOWZhZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dXPvwt6wr08g81XZ13iKqCY8VAiQRVysjYw_nPUJlCg)
> 
> Hope this works

Thank you very much for this. In my case the GEE API was enabled, so I disabled and re-enabled t and did what you said with ee.Initialize(project='add here') and it worked.

**Comment by shanan11** [comment]
![QQ截图20240120215356](https://github.com/googlecolab/colabtools/assets/131270282/01211e0e-45cd-4d90-88de-43effa865653)
I entered the newly set up Google Cloud project, but it shows that I have no access permissions, and I still cannot use geemap. How can I open permissions in the Google Cloud project?

**Comment by shanan11** [comment]
![1111111111](https://github.com/googlecolab/colabtools/assets/131270282/1607cb68-8609-4aec-a5e2-1144485bde67)

very strange

**Comment by SafaaHadi1980** [comment]
hello every one .. my problem is



![Untitled](https://github.com/googlecolab/colabtools/assets/169070580/295a3f13-fbd7-4014-9d83-a5e4ff662e66)

**Comment by MohibShaikh** [comment]
You can pass the product-id from the google earth engine and verify if it is working
![image](https://github.com/googlecolab/colabtools/assets/120479082/0b22ed2a-19fe-4d79-b8b2-8ca6a891c0fe)

**Comment by NaoCipherCS** [comment]
Hi yes,

The above solution should work. In general, it's no longer enough to just have ee.Initialize(). You now have to use ee.Initialize(project='project_id') going forward. Happened to me a few months back. Also just ensure all your GEE APIs are on for the future....

Best,

Naomi
