### ISSUE TITLE
File upload doesn't work in Firefox

### ISSUE THREAD

**Issue by esemeniuc** [googlecolab/colabtools#423]
When using the "Files" tab of the sidebar, the upload spinner just loops endlessly. Fails on Firefox 65.0 on Arch Linux. Works perfectly in Google Chrome

**Comment by colaboratory-team** [comment]
Thanks for the report, and sorry for the trouble. We'll take a look and keep this issue updated.

**Comment by colaboratory-team** [comment]
While we're fixing the file browser upload, an immediately usable work-around is to run the following in a code cell to upload files:

```
from google.colab import files
files.upload()
```

**Comment by esemeniuc** [comment]
That works! Thanks

**Comment by blois** [comment]
This issue should now be fixed in the current version of Colab.

**Comment by 5560405930** [comment]
Hello, unfortunately, it has been several days that colab does not load for me in Chrome and Firefox

**Comment by zhiyun-deng** [comment]
Google Colab file upload also did not work for us when we were using Firefox 104.0.2.

**Comment by youdontneedtoknow22** [comment]
Doesn't work on Firefox 111, but does work on edge
