### ISSUE TITLE
cannot use GPU with tensorflow version 2.12.0 

### ISSUE THREAD

**Issue by dking21** [googlecolab/colabtools#4230]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

I use Google Colab for my personal project.
I need to use tensorflow 2.12.0 version specifically as other libraries I need to use are based on tensorflow 2.12.0.  so I install with !pip install tensorflow == 2.12.0
However, when I try to work on modeling, it says that I cannot use GPU on a colab notebook. it works fine with regularly installed tensorflow version (2.15). It says GPU not found / tensorflow cannot configure GPU message. 

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
I want to use tensorflow 2.12.0 version with GPU without issue.
Is this an issue that can be mitigated if I purchase pro / GPU computing unit? Or bug which cannot be fixed no matter I purchase subscription?

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome 

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

https://colab.research.google.com/drive/1-Ty4Q2-JbJHqS09w0Ub6rPSSQfXrFqgq?usp=sharing

**Comment by Tetra-quark** [comment]
I am experiencing a similar problem trying to pip install tensorflow 2.10 and 2.11. Previously I had no problem using the GPU but now whenever I install version of tensorflow that is different from the pre-installed version (2.15.0) tensorflow can't see the GPU device, although it still manages to find the CPU.

**Comment by loewenm** [comment]
[+1] I am also experiencing this issue. It's likely due to the CUDA upgrade to 12.2 from 11.8.

**Comment by mayankmalik-colab** [comment]
Follow updates on #4214

**Comment by Amit30swgoh** [comment]
!pip install tensorflow[and-cuda]

**Comment by thagstrom123** [comment]
any workaround to get GPUs for TF 2.14 or less. The temporary fallback environment in colab is now gone

**Comment by luvwinnie** [comment]
same here, any way to do so?

**Comment by MehdiBedja** [comment]
im using tensorflow 2.13.1 , the gpu is not detected why is that , ( im using it in a tensorflow object detection api ) 
any ideas?
