### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by blackmore29** [googlecolab/colabtools#4231]
<

!Hello, I have a problem when trying to generate a video with Google Colab, I didn't have this problem recently, I attach the photos so you can help me how to solve it

![error 1](https://github.com/googlecolab/colabtools/assets/154088733/3d8b9859-d50f-4312-92f6-114ba7527bf5)

![error 2](https://github.com/googlecolab/colabtools/assets/154088733/6adc112d-f784-4cf7-9102-caddb98be093)

![error 3](https://github.com/googlecolab/colabtools/assets/154088733/c54401df-af23-45b5-96a1-2faf7e6eda94)

**Comment by cperry-goog** [comment]
I'd contact the notebook author - I have limited ability to debug others' code.

**Comment by cperry-goog** [comment]
You might have luck using the fallback version: Tools > Command Palette > Use fallback runtime version
