### ISSUE TITLE
Need Help, GPU not working.

### ISSUE THREAD

**Issue by rickychaka** [googlecolab/colabtools#4233]
![Uploading Screenshot 2023-12-18 171742.png…]()

**Comment by mayankmalik-colab** [comment]
We are aware of the fact that tf < 2.15 might not be compatible with CUDA 2,12. I would recommend using tf 2.15. However, if you still want to use tf<2.15, you can use fallback version of Colab for a few more days as mentioned [here](https://github.com/googlecolab/colabtools/issues/4214.)

**Comment by mayankmalik-colab** [comment]
Follow updates on #4214
