### ISSUE TITLE
Questions ?

### ISSUE THREAD

**Issue by VeryUselessKid** [googlecolab/colabtools#4237]
1) Can I use multiple Google accounts to run different Colab Pro on the same computer ? For example, I use the first email to run Colab in Chrome, the second email to run Colab in a second browser, and so on ?

2) Why does Google Colab Pro only offer the V100 16GB ? Do they also provide the V100 32GB ?

3) Can I run Colab Pro continuously for more than 2 days ?

Thanks

**Comment by cperry-goog** [comment]
1. is against our terms: https://research.google.com/colaboratory/faq.html#limitations-and-restrictions
2. we get whatever inventory we can from Google Cloud
3. no. you can try a local or remote runtime: https://research.google.com/colaboratory/local-runtimes.html
