### ISSUE TITLE
VRAM not running

### ISSUE THREAD

**Issue by Amudhesh-KT** [googlecolab/colabtools#4243]
**Describe the current behavior**
I am using a colab notebook with runtime type V4-GPU. When I execute a particular cell, it is not using the GPU RAM and only using CPU RAM

**Describe the expected behavior**
When I execute the cell, the runtime should use GPU RAM

**What web browser you are using**
Chrome

**Comment by loewenm** [comment]
You've likely downgraded some library (e.g. Tensorflow, etc.) to something not compatible with CUDA 12.2.
Reference: https://github.com/googlecolab/colabtools/issues/4214

**Comment by mayankmalik-colab** [comment]
Can you use tf `2.15` as older versions might not be comoatible with upgraded CUDA, or if you want to use the older versions, you can use fallback version of Colab for a few more days as mentioned [here](https://github.com/googlecolab/colabtools/issues/4214)
