### ISSUE TITLE
when we write a multiline comments then it prints in output,but comments meaning not prints in output.so please correct the error 

### ISSUE THREAD

**Issue by Vrundavan-Raj** [googlecolab/colabtools#4244]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by katlyn-edwards** [comment]
Can you provide a minimal repro notebook?
