### ISSUE TITLE
GPU not utilizing

### ISSUE THREAD

**Issue by SUNNY11286** [googlecolab/colabtools#4248]
GPU is connect in my colab but it is not being used and taking computation time similar as CPU. The same code was working fine till 2 to 4 days back, but not today. I was using tensorflow. Any one can help me with this?

**Comment by mayankmalik-colab** [comment]
What tf version are you using? I would recommend using tf `2.15` as we recently [upgraded CUDA and TF](https://github.com/googlecolab/colabtools/issues/4214). Also, you can use fallback version of Colab for a few more days as mentioned in the same github issue mentioned.

**Comment by SUNNY11286** [comment]
> What tf version are you using? I would recommend using tf `2.15` as we recently [upgraded CUDA and TF](https://github.com/googlecolab/colabtools/issues/4214). Also, you can use fallback version of Colab for a few more days as mentioned in the same github issue mentioned.

I was using 2.12 version due to other modules or packages compatibility issues, can't use 2.15. But also for 2.15 the issue remains open.

**Comment by mayankmalik-colab** [comment]
Please use Colab’s fallback runtime version as mentioned [here](https://github.com/googlecolab/colabtools/issues/4214)

**Comment by SUNNY11286** [comment]
Thanks, with fallback runtime its working.
