### ISSUE TITLE
Cannot connect to the A100 Hardware accelerator

### ISSUE THREAD

**Issue by SisypheGeek** [googlecolab/colabtools#4253]
Hi there 

**Describe the current behavior**
I want to use A100. When I click on this option in notebook settings, it changes on the settings tab, but doesn't change in the actual notebook.  I'm stuck on V100 in the notebook even when I change to A100 in settings. 

**Describe the expected behavior**
Expect A100 to be the GPU used to run the code in the notebook. 

**What web browser you are using**
Chrome 

Thanks!

**Comment by JhonDan1999** [comment]
the same here 

As a subscriber to Pro Colab, I expected access to the A100 GPU. BUT, I have been repeatedly allocated a V100 GPU instead!!!


The A100 GPU has not been made available since I suscribed and there is a lack of clarity on when and if it will be provided!!!

**Comment by cperry-goog** [comment]
GCE has very limited A100 stock - we continue to try to increase our supply.

**Comment by JhonDan1999** [comment]
> GCE has very limited A100 stock - we continue to try to increase our supply.

The main selling point of the Pro Colab subscription for many of us is access A100. 
I want to know when subscribers like myself, who have been waiting for more than two weeks, can expect access to the A100 GPU?
