### ISSUE TITLE
shared memory is only 64M on my custom GCE colab VM

### ISSUE THREAD

**Issue by ruuttt** [googlecolab/colabtools#4254]
**Describe the current behavior**
I rent a instance in the google cloud, which I deployed a few days ago from the market place by clicking on the link provided in the colab FAQ. When I connect to the instance from the colab web-interface and run the command:
`!df -h
`
This give as output
```
Filesystem      Size  Used Avail Use% Mounted on
overlay         193G   41G  152G  22% /
tmpfs            64M     0   64M   0% /dev
shm              64M   14M   51M  22% /dev/shm
/dev/sda1       193G   41G  152G  22% /opt/bin
tmpfs           6.4G  340K  6.4G   1% /var/colab
```
Note that the shm (shared memory) value is only 64MB. 

When I run the same command on a standard (free of charge) instance, I get:
```
Filesystem      Size  Used Avail Use% Mounted on
overlay         108G   41G   68G  38% /
tmpfs            64M     0   64M   0% /dev
shm             5.8G     0  5.8G   0% /dev/shm
/dev/root       2.0G  1.1G  849M  57% /usr/sbin/docker-init
tmpfs           6.4G   56K  6.4G   1% /var/colab
/dev/sda1        71G   54G   17G  77% /etc/hosts
tmpfs           6.4G     0  6.4G   0% /proc/acpi
tmpfs           6.4G     0  6.4G   0% /proc/scsi
tmpfs           6.4G     0  6.4G   0% /sys/firmware
```
As you can see in this case the shm is almost 6G.

The problem with this low amount of shared memory is that multithreading of PyTorch gives the error as is described [here](https://github.com/pytorch/pytorch/issues/7181). The work around is to disabled multithreading , but this not ideal since this will increase calculation time. 

Could you please update the colab instance on the market place

**Comment by mayankmalik-colab** [comment]
Thanks for reporting this to us. We will get that fixed in the next MP release. Tracked internally at b/317991003.

**Comment by EvanWiederspan** [comment]
This should be fixed now, thanks for the report
