### ISSUE TITLE
Not Allocating Runtime

### ISSUE THREAD

**Issue by Amit1110** [googlecolab/colabtools#426]
The notebook is not able to connect to a runtime and it just shows allocating. I have checked my internet connection and it is working as usual, but I am not able to connect to notebook.

**Comment by rizavelioglu** [comment]
Having the same problem here. I tried 'reset all runtimes' but still doesn't work.

**Comment by DavisTownsend** [comment]
same issue here

**Comment by deepak121993** [comment]
same issue here

**Comment by rizavelioglu** [comment]
> Having the same problem here. I tried 'reset all runtimes' but still doesn't work.

Just connected now

**Comment by colaboratory-team** [comment]
Sorry for the trouble, all. Colab should again be working for all users. Do let us know if the issue recurs.

**Comment by jaideep11061982** [comment]
hi i keep facing this issue every now n then.... one or two time if due to internet it disconnects there after it takes long time for notebook to get connected
