### ISSUE TITLE
Cannot access my GEE asset after authorization

### ISSUE THREAD

**Issue by LauraChow77** [googlecolab/colabtools#4260]
**Describe the current behavior**
I want to upload my asset from GCS to GEE Asset. I have authorized GEE and GCS using the code below and at least no bugs popped up.

```
import ee

# Trigger the authentication flow.
ee.Authenticate()
# Initialize the library.
ee.Initialize(project='mixpointsextracion')

!gcloud config set project mixpointsextracion
!gcloud auth login

```
then I tried to access my asset with the code below:

```
# Asset path in GEE
gee_asset_dir = "projects/mixpointsextracion/assets/gum_val_final"

# Acquire file names in asset, and stored in the variable: target_asset_files
gee_asset_info = !earthengine ls {gee_asset_dir}
gee_asset_files = []
for i in range(0, len(gee_asset_info)):
  print(gee_asset_info[i])
  gee_asset_files.append(gee_asset_info[i].split(os.sep)[-1])
print('Number of files in GEE asset: ' + str(len(gee_asset_files)))
```
the error was:
`W1226 07:34:08.939983 139076975796224 http.py:140] Encountered 403 Forbidden with reason "PERMISSION_DENIED"
Traceback (most recent call last):
  File "/usr/local/bin/earthengine", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/ee/cli/eecli.py", line 85, in main
    tf_module.app.run(_run_command, argv=sys.argv[:1])
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.10/dist-packages/ee/cli/eecli.py", line 61, in _run_command
    dispatcher.run(args, config)
  File "/usr/local/lib/python3.10/dist-packages/ee/cli/commands.py", line 361, in run
    self.command_dict[vars(args)[self.dest]].run(args, config)
  File "/usr/local/lib/python3.10/dist-packages/ee/cli/commands.py", line 870, in run
    config.ee_init()
  File "/usr/local/lib/python3.10/dist-packages/ee/cli/utils.py", line 148, in ee_init
    ee.Initialize(
  File "/usr/local/lib/python3.10/dist-packages/ee/_utils.py", line 39, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ee/__init__.py", line 140, in Initialize
    data.initialize(
  File "/usr/local/lib/python3.10/dist-packages/ee/data.py", line 225, in initialize
    _install_cloud_api_resource()
  File "/usr/local/lib/python3.10/dist-packages/ee/data.py", line 300, in _install_cloud_api_resource
    _cloud_api_resource = _cloud_api_utils.build_cloud_resource(
  File "/usr/local/lib/python3.10/dist-packages/ee/_cloud_api_utils.py", line 195, in build_cloud_resource
    resource = build(static_discovery=False)
  File "/usr/local/lib/python3.10/dist-packages/ee/_cloud_api_utils.py", line 179, in build
    return discovery.build(
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/discovery.py", line 316, in build
    raise e
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/discovery.py", line 287, in build
    content = _retrieve_discovery_doc(
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/discovery.py", line 422, in _retrieve_discovery_doc
    resp, content = req.execute(num_retries=num_retries)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://earthengine.googleapis.com/$discovery/rest?version=v1&prettyPrint=false returned "Caller does not have required permission to use project mixpointsextracion. Grant the caller the roles/serviceusage.serviceUsageConsumer role, or a custom role with the serviceusage.services.use permission, by visiting https://console.developers.google.com/iam-admin/iam/project?project=mixpointsextracion and then retry. Propagation of the new permission may take a few minutes.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developer console IAM admin', 'url': 'https://console.developers.google.com/iam-admin/iam/project?project=mixpointsextracion'}]}, {'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'USER_PROJECT_DENIED', 'domain': 'googleapis.com', 'metadata': {'service': 'earthengine.googleapis.com', 'consumer': 'projects/mixpointsextracion'}}]">
Number of files in GEE asset: 45`

why it happened? First, I am the owner of the cloud project and also the owner of the asset owner. I also made sure I have the permission (i.e., Service Usage Consumer) allowed. Why I was denied from my own asset?

**Describe the expected behavior**
I want to access my assets successfully so that I could upload my data from GCS to this asset.

**What web browser you are using**
Chrome

**Additional context**
I was using Google Colab.

**Comment by mbayad33** [comment]
Hello, 

have been able to solve this problem? I stumbled upon the same proble and still stack for several days now.

**Comment by LauraChow77** [comment]
Dear mbayad33,

Hello! I haven't been able to solve this problem yet. I'll reach out to you again if I find the solution.

Best regards,
Yuhan ZHOU
________________________________

**Comment by mbayad33** [comment]
Dear Yuhan, 
thanks for yoyr feedback.

I think the problem is with  ee.Initialize(project='project-id') command itself, but still cannot figure out what is the problem: 

I saw in another post that they solved this by starting the script by : 
from google.colab import auth
auth.authenticate_user(project_id='project-id'). this prevented the error in the ee.initialize(), but when I wanted to sent files from bucket to ee assets I got the error exactly like yours. 

best,
Bayad

**Comment by mbayad33** [comment]
Good new! 

I run the same code in jupyter notebook and it woked just fine. I think the problem is in Colab. 

I uploded the .tif files from bucket to assest using this code: 

!pip install earthengine-api --upgrade

import ee
ee.Authenticate()
ee.Initialize(project='my_project_id')

file_name = 'C:/Users/Downloads/manifest.json' # path to manifest json file...

# Do the upload.
!earthengine upload image --manifest {file_name}

If it works you get somthing like:
Started upload task with ID: UBAJ4QNHCD.......

Cheers!

**Comment by LauraChow77** [comment]
Dear Bayad,

Apologies for the delayed response; I was engaged in a group meeting.

I am truly grateful for your guidance! Following your shared method, I have now successfully uploaded images using Jupyter Notebook as well.

Best regards,
Yuhan ZHOU
________________________________

**Comment by jdbcode** [comment]
Recent Earth Engine authentication and initialization [changes](https://developers.google.com/earth-engine/changelog#python_api_v01383) and bugs may have caused these issues. If you're using the Earth Engine CLI in Colab, you can use these methods while additional fixes are being rolled out: https://gist.github.com/jdbcode/5961cbbed9187e24775df4d279fcbc26

In the future use https://developers.google.com/earth-engine/guides/auth and https://developers.google.com/earth-engine/guides/command_line for reference.

**Comment by LauraChow77** [comment]
Dear jdbcode,

Thank you so much for your solution. It worked.

Best regards,
Yuhan ZHOU

**Comment by jdbcode** [comment]
The previously mentioned fixes to auth and project settings while using the Earth Engine CLI in Colab have been resolved. Please follow instructions in the [Earth Engine CLI use in Colab docs](https://developers.google.com/earth-engine/guides/command_line#usage_in_colab).
