### ISSUE TITLE
Cant install fbprophet on my google colab 

### ISSUE THREAD

**Issue by muhand4u** [googlecolab/colabtools#4265]
Building wheels for collected packages: fbprophet
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for fbprophet (setup.py) ... error
  ERROR: Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
ERROR: Could not build wheels for fbprophet, which is required to install pyproject.toml-based projects

**Comment by mayankmalik-colab** [comment]
`fbprophet` supports <=Python 3.7. It seems it was last updated in 2020. It won't work with our ecosystem. The alternative seems to be prophet, which is already installed in our ecosystem. Try using that.
