### ISSUE TITLE
My app stops running if I close me browser

### ISSUE THREAD

**Issue by Temepest74** [googlecolab/colabtools#4268]
I paid for pro+, and it worked as expected last time (1-2 weeks ago). I was able to just leave my program running while I close my browser, but now, it suddenly stops if I do so. 
I get no errors, it just pauses my execution. My session still stays connected (it will disconnect eventually).

**Comment by cperry-goog** [comment]
Can you submit feedback in product and reference this issue? I can take a look - hard to diagnose this from GitHub.
