### ISSUE TITLE
conda install -c pykaldi pykaldi

### ISSUE THREAD

**Issue by Hamahmi** [googlecolab/colabtools#427]
I want to use Pykaldi on Colab, yet the installation using conda is not available.

**Comment by metrizable** [comment]
@Hamahmi Correct. Conda installs are not supported at this time. You may be interested in following feature request #496.

**Comment by Hamahmi** [comment]
> 

Phew that took only less than 5 years to solve 😂
Great work you guys, I personally moved on ever since but I hope this will be a great help for other people.
