### ISSUE TITLE
Package built from GitHub source not importing properly

### ISSUE THREAD

**Issue by darshansarojini** [googlecolab/colabtools#4274]
**Describe the current behavior**
1. I have cloned repositories from GitHub and pip-installed them. 
2. I run the notebook and it works as expected. 
3. After a few runs of the same notebook changing the inputs to the code, it unexpectedly stops correctly importing the pip-installed package, csdl. I am unable to call any function or class in the package

**Describe the expected behavior**
Once pip-installed, when I import the package csdl I should be able to call functions or classes in the package. Access to the methods should be independent of which runtime resource (CPU, GPU, TPU) I use. 

**What web browser you are using**
Firefox

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
- [GitHub Gist link](https://colab.research.google.com/gist/darshansarojini/fed7ad4147abb6ca505ce6aed2b76898/comparingautogradpackages.ipynb)

**Comment by EvanWiederspan** [comment]
"Access to the methods should be independent of which runtime resource (CPU, GPU, TPU) I use."

Does this mean that you are switching the Runtime type after running the notebook? Switching runtime type will get you a brand new machine, and any packages will have to be re-installed to be used

**Comment by darshansarojini** [comment]
Hello Evan,
The first few cells install the repositories from GitHub. 

Running the notebook works. I re-run multiple times changing some inputs. It still works. But then, unexpectedly, it throws the error seen in the GitHub gist. 
After that, it does not work: 1) "disconnect and delete runtime" -> "run all" (which will install the packages again), 2) "change runtime" (which as you pointed out gives a new machine) -> "run all"

I came back to this a few days later. It worked! But then, again, after running the same notebook a few times, it throws the error.

**Comment by cperry-goog** [comment]
Does this happen for all packages? Or just this specific one?

**Comment by darshansarojini** [comment]
The error is only for the CSDL package. Other packages, such as CasADi and python_csdl_backend, that I pip install in the same notebook work without errors.

**Comment by cperry-goog** [comment]
I'd check with the package owner, we build from source in Colab regularly and this appears to be the only case where it fails.
