### ISSUE TITLE
Error on input image  

### ISSUE THREAD

**Issue by lostman77** [googlecolab/colabtools#4276]
Hello, i have a weird issue with image prompt options, i getting an error message when i beginning try to do something with image prompt, faceswap,  etc. It's happens mostly image processing or downloading models/ Other things are working properly.

I'm using Chrome browser
Hope for your help.
Thanks
https://colab.research.google.com/github/lllyasviel/Fooocus/blob/main/fooocus_colab.ipynb#scrollTo=VjYy0F2gZIPR&line=1&uniqifier=1

**Comment by EvanWiederspan** [comment]
I would file an issue with the Github repo that you are downloading code from instead
