### ISSUE TITLE
Why does my program still get interrupted when running the fooocus program even though I have already paid to upgrade to Colab Pro?

### ISSUE THREAD

**Issue by amostsai** [googlecolab/colabtools#4278]
Why does my program still get interrupted when running the fooocus program even though I have already paid to upgrade to Colab Pro?

**Comment by u173Tsholo** [comment]
I have been getting the same issue for 2 days now. It just hangs on Connecting as below:

<img width="254" alt="colabpro" src="https://github.com/googlecolab/colabtools/assets/55790389/8c924a1b-d0fc-4896-9b74-c22825ec1baa">

Is there a fix for this?

**Comment by atin4210** [comment]
I am having the same issue and I am subscribed to Colab Pro+. Running in Firefox on MacOS.

**Comment by EvanWiederspan** [comment]
We'll need more information to follow up on this bug report. Please submit feedback within Colab at Help > Send feedback.

**Comment by nrrm1** [comment]
[](url)
