### ISSUE TITLE
x/y values for 'mouse over' for a matplotlib plot

### ISSUE THREAD

**Issue by haimivan** [googlecolab/colabtools#428]
Hi,

I would like to be able to move and zoom an inline matplotlib plot and also have a x/y variable display when hovering over the plot canvas with the mouse.

With 

```
!pip install mpld3
import mpld3 
mpld3.enable_notebook()
import matplotlib.pyplot as plt
plt.plot([[0,0],[1,1]],linewidth=4, label='random diagonal')
plt.show()
```

I am able to get move and zoom. 

Is there any other way to get also the x/y values when hovering over the canvas with the mouse?

If this is presently not possible: could you perhaps take this as a feature request?

Thanks in advance!

**Comment by metrizable** [comment]
@haimivan This can be done several ways. For example, with the `bokeh` `HoverTool`:

```
import numpy as np
import bokeh.plotting as plt
import bokeh.models as pltm

x = np.arange(100)
y = x ** 4

fig = plt.figure()
fig.add_tools(pltm.HoverTool())
fig.line(x, y)
plt.show(fig)
```

![Screenshot from 2023-02-27 14-46-27](https://user-images.githubusercontent.com/65414824/221704501-d6eeb490-9220-4ffa-a6fd-98275e8324c6.png)
