### ISSUE TITLE
Every time I attempt to Upscale a picture it disconnects...

### ISSUE THREAD

**Issue by IronPuft** [googlecolab/colabtools#4282]
I'm using Safari, I have been able to upscale photos, but now each time I set it up, It gives me connection errors. However it works when I'm faceswaping or generating a new image. It only does not work when I'm upscaling the image I import.

**Comment by EvanWiederspan** [comment]
This sounds like an issue with the notebook you're using, not Colab itself. I would reach out to the notebook author instead
