### ISSUE TITLE
Runtime doesn't time out and disconnect when on the `Connect to Google Drive` modal

### ISSUE THREAD

**Issue by ArchieLuxton** [googlecolab/colabtools#4284]
**Describe the current behavior**
Typically, a runtime will disconnect after a period of inactivity. However when left on the 'Connect to Google Drive' modal, activated when mounting a drive, it does not. This results in lots of credits being used unintentionally. 

**Describe the expected behavior**
The runtime disconnects after the same period of inactivity, regardless of the state of the session.

**What web browser you are using**
Chrome

**Additional context**
Appears to happen with any cell that runs `drive.mount('/content/drive')` or similar, but is then left on the modal.

**Comment by EvanWiederspan** [comment]
Filed internally as b/319655511

**Comment by colaboratory-team** [comment]
A fix for this issue has been submitted and will be available in a few days, so closing this.
