### ISSUE TITLE
get_dataset_names() is not working

### ISSUE THREAD

**Issue by TimJo21** [googlecolab/colabtools#4285]
![seaborn](https://github.com/googlecolab/colabtools/assets/93178218/3583afb1-8311-47e1-92d5-b12f0bcb689a)

**Comment by mayankmalik-colab** [comment]
This seems like  an upstream issue - [3613](https://github.com/mwaskom/seaborn/issues/3613) .

You can do the following:
- `!pip install seaborn==0.13.1`
- Runtime -> restart session

It should work.
