### ISSUE TITLE
A100 availability 

### ISSUE THREAD

**Issue by JhonDan1999** [googlecolab/colabtools#4286]
**Describe the current behavior**
I'm encountering a problem with my Pro Colab subscription. Although I've selected the A100 GPU in the notebook settings, it doesn't actually activate in the notebook itself. Instead, I keep running on the V100 GPU. I am facing this issue for more than 20 days.

**Describe the expected behavior**
As a Pro Colab subscriber, I anticipate the A100 GPU to be available. The unavailability of the A100 GPU, despite my subscription is disappointing, especially since accessing the A100 is benefit of the Pro Colab. I am seeking information on when the A100 GPU will be accessible for subscribers like me who have been waiting for over 20 days.

**What web browser you are using**
Chrome

**Comment by EvanWiederspan** [comment]
GCE has very limited A100 stock - we continue to try to increase our supply.
