### ISSUE TITLE
Earth Engine task listing in colab

### ISSUE THREAD

**Issue by PCdurham** [googlecolab/colabtools#4287]
Returned to using the GEE python API after the holidays.  I hit the bug described [here](https://github.com/googlecolab/colabtools/issues/4228), and solved the problem as per instructions in that issue.  But later in my code it seems that ee is not using the project-ID I authenticated.  I use this command to list my active tasks:

`command = 'earthengine task list' with Popen(command, stdout=PIPE, stderr=None, shell=True) as process:
    output = process.communicate()[0].decode("utf-8")
    print(output)`

And it now returns: 

Google Earth Engine API has not been used in project 522309567947 before or it is disabled.

this is the same project ID the issue above reports.  It's not my project ID.  Is there a flag to specify a project ID when lsiting tasks?  Or an alternative method to list active tasks?

**Comment by jdbcode** [comment]
Recent Earth Engine authentication and initialization [changes](https://developers.google.com/earth-engine/changelog#python_api_v01383) and bugs may have caused these issues. If you're using the Earth Engine CLI in Colab, you can use these methods while additional fixes are being rolled out: https://gist.github.com/jdbcode/5961cbbed9187e24775df4d279fcbc26

In the future use https://developers.google.com/earth-engine/guides/auth and https://developers.google.com/earth-engine/guides/command_line for reference.

**Comment by jdbcode** [comment]
The previously mentioned fixes to auth and project settings while using the Earth Engine CLI in Colab have been resolved. Please follow instructions in the [Earth Engine CLI use in Colab docs](https://developers.google.com/earth-engine/guides/command_line#usage_in_colab).
