### ISSUE TITLE
Unable to load Colaboratory - too much recursion

### ISSUE THREAD

**Issue by danielacojocaru07** [googlecolab/colabtools#4291]
**Describe the current behavior**
Cannot load a Colaboratory file. The message "Unable to load Colaboratory. too much recursion" appears. 

**Describe the expected behavior**
To open the file.

**What web browser you are using**
Firefox

**Additional context**
.
.
.
Before the error occurred, I tried to edit the file multiple times, and then the error appeared.
.
.
. 
Additional message:
too much recursion
Please report this to https://github.com/markedjs/marked.
qM.prototype.output@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:2473:266
vM@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:2484:283
nM.prototype.parse@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:2480:237
uM@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:2480:36
oM@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:2487:311
LOa@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:2536:53
KOa@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:2524:52
g.updateSectionHeader@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:5084:125
j0@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:5081:793
v0@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:5122:499
g.enterDocument@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:6836:480
g.enterDocument@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:8028:66
Ln@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:597:379
g.render@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:597:93
i9a/<@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:4336:99
va@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:16:57
ta.prototype.next_@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:14:195
laa/this.next@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:17:48
b@https://ssl.gstatic.com/colaboratory-static/common/4c9a47c5fb96c88d4d37ae495e285eab/external_polymer_binary.js:17:309

Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by katlyn-edwards** [comment]
It looks like you have a large data image inlined into your markdown that's breaking our markdown parser.

You can modify the JSON of the file directly to remove that and it should be OK again.
