### ISSUE TITLE
WARNING: [GoogleDrive] Unable to request confirmed source file: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by coloreando9999** [googlecolab/colabtools#4293]
[GoogleDrive] Extracting URL: https://drive.google.com/file/d/1WLRnRc0VQMcaPyi5wrPdcd7UcOsaDdkq/view?usp=sharing
[GoogleDrive] 1WLRnRc0VQMcaPyi5wrPdcd7UcOsaDdkq: Downloading video webpage
[GoogleDrive] 1WLRnRc0VQMcaPyi5wrPdcd7UcOsaDdkq: Requesting source file
[GoogleDrive] 1WLRnRc0VQMcaPyi5wrPdcd7UcOsaDdkq: Requesting confirmed source file
WARNING: [GoogleDrive] Unable to request confirmed source file: HTTP Error 400: Bad Request
[info] 1WLRnRc0VQMcaPyi5wrPdcd7UcOsaDdkq: Downloading 1 format(s): 18
[download] Destination: video/source/video.mp4
[download] 100% of   43.50MiB in 00:06:07 at 121.27KiB/s 
the piece of the movie to be colored weighs 218 mb in mp4 format and when downloading it converts it into only 43.50 mb because it loses a lot of image quality, I don't understand why it does it, any solution for this?

**Comment by cperry-goog** [comment]
duping with #4294
