### ISSUE TITLE
WARNING: [GoogleDrive] Unable to request confirmed source file: HTTP Error 400: Bad Request #4293

### ISSUE THREAD

**Issue by coloreando9999** [googlecolab/colabtools#4294]
[GoogleDrive] Extracting URL: https://drive.google.com/file/d/1WLRnRc0VQMcaPyi5wrPdcd7UcOsaDdkq/view?usp=sharing
[GoogleDrive] 1WLRnRc0VQMcaPyi5wrPdcd7UcOsaDdkq: Downloading video webpage
[GoogleDrive] 1WLRnRc0VQMcaPyi5wrPdcd7UcOsaDdkq: Requesting source file
[GoogleDrive] 1WLRnRc0VQMcaPyi5wrPdcd7UcOsaDdkq: Requesting confirmed source file
WARNING: [GoogleDrive] Unable to request confirmed source file: HTTP Error 400: Bad Request
[info] 1WLRnRc0VQMcaPyi5wrPdcd7UcOsaDdkq: Downloading 1 format(s): 18
[download] Destination: video/source/video.mp4
[download] 100% of   43.50MiB in 00:06:07 at 121.27KiB/s 

WARNING: [GoogleDrive] Unable to request confirmed source file: HTTP Error 400: Bad Request
[info] 1WLRnRc0VQMcaPyi5wrPdcd7UcOsaDdkq: Downloading 1 format(s): 18
any solution please to be able to fix this that has not been able to confirm the source file if it is in mp4 because when downloading it reduces the size of it any solution for this thanks greetings

**Comment by cperry-goog** [comment]
can you please share a minimal reproducible notebook, not sure how you're getting this error
