### ISSUE TITLE
displays runtime connecting and do nothing. then displays connection lost

### ISSUE THREAD

**Issue by kariakushscan** [googlecolab/colabtools#4297]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by FranciscoAlves00** [comment]
I am getting the same issue with Colab Pro+. I can't run any notebook since seconds after it keeps connecting and disconnecting.

**Comment by cperry-goog** [comment]
can you file feedback in product and mention this and I can take a look.
