### ISSUE TITLE
   assert any(os.path.exists(os.path.join(path, 'libcuda.so')) for path in dirs), msg AssertionError: libcuda.so cannot found!

### ISSUE THREAD

**Issue by sunlove99** [googlecolab/colabtools#4300]
assert any(os.path.exists(os.path.join(path, 'libcuda.so')) for path in dirs), msg
AssertionError: libcuda.so cannot found!

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by bmox** [comment]
It works for me on Google Colab
`!echo /usr/lib64-nvidia/ >/etc/ld.so.conf.d/libcuda.conf; ldconfig`
