### ISSUE TITLE
error in the Search against genetic databases step

### ISSUE THREAD

**Issue by joellllllllllll** [googlecolab/colabtools#4301]
I am using alphafold as I usually do but I keep getting this error during the Search against genetic databases step of alpha fold. All the previous steps are completed. Does anyone know what is going on?

SymbolAlreadyExposedError                 Traceback (most recent call last)
[<ipython-input-8-f1fdee26350e>](https://localhost:8080/#) in <cell line: 27>()
     25 import py3Dmol
     26 
---> 27 from alphafold.model import model
     28 from alphafold.model import config
     29 from alphafold.model import data

22 frames
[/opt/conda/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py](https://localhost:8080/#) in set_attr(self, func, api_names_attr, names)
    362     if api_names_attr in func.__dict__:
    363       if not self._allow_multiple_exports:
--> 364         raise SymbolAlreadyExposedError(
    365             'Symbol %s is already exposed as %s.' %
    366             (func.__name__, getattr(func, api_names_attr)))  # pylint: disable=protected-access

SymbolAlreadyExposedError: Symbol Zeros is already exposed as ().

**Comment by cperry-goog** [comment]
can you share a minimal reproducible notebook? this is almost certainly an issue with the code, not Colab, though, so you may have more luck contacting the notebook author.
