### ISSUE TITLE
Text-over-button issue: Google Colab

### ISSUE THREAD

**Issue by clarson14** [googlecolab/colabtools#4302]
![image](https://github.com/googlecolab/colabtools/assets/156637746/b02d54e5-a188-470c-b167-fd4e499ec10f)

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

"There is incomplete text where buttons should be when opening google colab."

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

"I expected there to be a clean page."

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by katlyn-edwards** [comment]
Hrm looks like the Material Symbols font isn't loading for you?

Can you verify that there aren't any errors in the Chrome console when you load the page? Can you also try in an incognito window?
