### ISSUE TITLE
Training File/Folder missing in Google Colab directory

### ISSUE THREAD

**Issue by Harix143** [googlecolab/colabtools#4309]
I was training an AI model on Google Colab and when its execuation is completed, it should save the model checkpoints in the colab directory (as previously) but, No files or folder there in the colab directory and the colab is disconneced. I have lost all the training files, how can I recover it or find it??

P.S: It happend two times in 2 days. Previously there is no issue like that.

Training code/Command:

```
python finetune/finetune.py \
  --model_path="bigcode/starcoder"\
  --dataset_name="ArmelR/stack-exchange-instruction"\
  --subset="data/finetune"\
  --split="train"\
  --size_valid_set 10000\
  --streaming\
  --seq_length 2048\
  --max_steps 1000\
  --batch_size 1\
  --input_column_name="question"\
  --output_column_name="response"\ 
  --gradient_accumulation_steps 16\
  --learning_rate 1e-4\
  --lr_scheduler_type="cosine"\
  --num_warmup_steps 100\
  --weight_decay 0.05\
  --output_dir="./checkpoints" \
```
I want to recover my training files as there is some way to recover or not to lost it again?

**Comment by cperry-goog** [comment]
If I'm reading correctly, the files are being deleted at the end of your session because the runtime is recycled. Can you write these files to an external data source? Colab runtimes are deleted at the end of a session.
