### ISSUE TITLE
No code color highlight after uploading a notebook

### ISSUE THREAD

**Issue by ogenev** [googlecolab/colabtools#431]
Hello, when I upload a notebook, the python code is with no color highlight as supposed to be

![screenshot from 2019-02-16 15-11-43](https://user-images.githubusercontent.com/39865181/52900341-5e4b7080-31fd-11e9-9ab8-14e6f26dc3a0.png)

**Comment by colaboratory-team** [comment]
If you're able to share the notebook, please do and we'll take a closer look.
b/124541665

**Comment by craigcitro** [comment]
We would definitely like to see the notebook (in particular the kernelspec in the top-level metadata).

Just to confirm: if you open `Edit` -> `Notebook settings` and explicitly choose python3 (or python2) and hit "save", does the syntax highlighting go back to normal?

**Comment by ogenev** [comment]
> Just to confirm: if you open `Edit` -> `Notebook settings` and explicitly choose python3 (or python2) and hit "save", does the syntax highlighting go back to normal?

Yes, highlighting go back to normal. Here is a link to the notebook:
https://colab.research.google.com/drive/14KoUyuBYeASkiG-2CYbOOtGJjVL8cLoO

**Comment by craigcitro** [comment]
@ogenev do you still have a copy from before you tweaked the notebook settings? (Or, alternately, can you find a still-unhighlighted version in `File` -> `Revision history`?)

**Comment by ogenev** [comment]
> @ogenev do you still have a copy from before you tweaked the notebook settings? (Or, alternately, can you find a still-unhighlighted version in `File` -> `Revision history`?)

Updated to unhighlighted version.

**Comment by craigcitro** [comment]
Perfect -- it is indeed an unknown kernelspec. I'll work on getting this fixed on our side, and will update the bug.

**Comment by domoritz** [comment]
I've seen the same issue when I load notebooks from GitHub. When I switch to dark mode and back, syntax highlighting works again.

**Comment by nkaenzig** [comment]
> I've seen the same issue when I load notebooks from GitHub. When I switch to dark mode and back, syntax highlighting works again.

Same for me. Thanks for the tip.

**Comment by domoritz** [comment]
@craigcitro is this being worked on?

**Comment by blois** [comment]
The fix for this should now be live.

The workaround mentioned in https://github.com/googlecolab/colabtools/issues/431#issuecomment-464386616 is still needed to fix existing notebooks which do not have coloring but newly imported notebooks should now be correct.
