### ISSUE TITLE
Couldn't find the option for background execution in collab Pro+ account

### ISSUE THREAD

**Issue by vinothini0806** [googlecolab/colabtools#4310]
I am currently encountering an issue with the activation of background execution in Collab Pro +. Unfortunately, I am unable to locate the option to enable background execution within Collab Pro +.In some places, they mentioned it will automatically enable the background execution. But i have tried to run one notebook as the default setting, but onnce i have closed the window it crashed. How can I enable the background execution in collab pro +?

PS: 
![image](https://github.com/googlecolab/colabtools/assets/62206610/f605a79d-acb9-4d5b-b899-4ec29b1c3853)
![image](https://github.com/googlecolab/colabtools/assets/62206610/d5611154-faf4-4d82-b647-7b12dac936ce)

**Comment by cperry-goog** [comment]
Background execution is enabled by default for all Pro+ accounts. (We changed this about a year ago). No need to explicitly set it.

If you're seeing crashes when you close, please submit in-product feedback and mention this issue and I'll take a look. A code snippet would be useful when you do that, and don't forget to opt into receiving email so I can get back to you.
