### ISSUE TITLE
xr-text-repr-fallback always shown when displaying xarray datasets instead of only HTML representation

### ISSUE THREAD

**Issue by maxiimilian** [googlecolab/colabtools#4311]
**Describe the current behavior**
xarray Datasets and Dataarrays are displayed as pretty HTML representations in interactive environments such as Colab and Jupyter. As a fallback or for text-based environments such as CLIs, xarray also has a "text" mode, which prints the array/dataset as a text-only representation. Currently, Colab shows **both** representations on top of each other, which becomes especially problematic for very large arrays:

![xarray_colab_issue](https://github.com/googlecolab/colabtools/assets/27306285/d224f238-b2ae-4281-bc3e-7229c036bfdc)

**Describe the expected behavior**
I would only expect the HTML representation to show (dashed box), not the text representation (solid box). The display mode of xarray is set accordingly. Different versions of xarray showed the same error. Jupyter lab (locally run) did not show this problem. Thus, I believe it is an issue with Colab. It might be similar #1145.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome

**Comment by cperry-goog** [comment]
this is a great bug report. thank you.

tracked internally at b/321052132

**Comment by EvanWiederspan** [comment]
Fix went in today, should be live early next week. Thanks for the report

**Comment by maxiimilian** [comment]
Thanks for the fix!
