### ISSUE TITLE
Colab Pro+ disconnecting almost always when I leave it idle

### ISSUE THREAD

**Issue by Taikakim** [googlecolab/colabtools#4314]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
Lately practically always when I leave my Pro+ running a Kohya XL training script on an A100 unattended, it cuts me off. Sometimes the instance is deleted instantly as I put my computer to sleep, sometimes it runs for an hour or maybe two at most and then kills the instance. This is infuriating, I'm losing money  all the time here... 

Like yesterday after using two days in the first place to find good settings for the script, I finally left it running an around 2-3hrs job, it had actually finished training, but apparently cut off while the local file was transferred to my Drive. 
I don't want to have a desktop running and wasting electricity that I'm partly trying to save by doing my training on efficient servers. It's kind of crazy to need to have a laptop on in my backpack when going around town just to keep the instances running. This happens so much that I don't even mostly try to use the background excecution. It's kind of a bummer since I've paid for it for a few months now already :( There was one single instance a few days ago when I managed to run a long 10+hrs run while having my computer either shut down or asleep.

**Describe the expected behavior**
Run for 24hrs like for what I paid for.

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
This is not the settings I'm using on my private copy of the notebook, but I didn't modify the code: 
https://github.com/Linaqruf/kohya-trainer/blob/main/kohya-trainer-XL.ipynb
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
OS info: Linux kim-HP-EliteDesk-800-G2-DM-65W 6.5.0-14-lowlatency #14.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 13:01:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by EvanWiederspan** [comment]
We can't diagnose this from Github, please file in-product feedback at Help -> Send Feedback
