### ISSUE TITLE
Unexpected runtime error scheduled jobs

### ISSUE THREAD

**Issue by Joachim1000** [googlecolab/colabtools#4317]
**Describe the current behavior**
I have a job that is getting unexpected runtime error when doing scheduled in colab. No error messages is printed?

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
This is difficult to diagnose from Github, can you file in-product feedback at Help -> Send Feedback? That should help us dig up the exact error
