### ISSUE TITLE
Flowise on colab error: Failed to save chatflow: Not allowed.

### ISSUE THREAD

**Issue by nnWhisperer** [googlecolab/colabtools#4323]
**Describe the current behavior**
I'm trying to use flowise on a colab notebook. The web UI opens but cannot save a chatflow to be able to work with it. Either using the serve_kernel_port_as_iframe or serve_kernel_port_as_tab functions give the same error.

**Describe the expected behavior**
I expect no error message and save the chatflow so that user can use the drap & drop UI to create circuits.

**What web browser you are using**
Chrome, probably not related to the browser as the same setting works with a tailscale node setup (as a safer alternative to ngrok etc).

**Additional context**
The following code to reproduce:
```
!mkdir -p ~/miniconda3
!wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
!bash ~/miniconda3/miniconda.sh -b -f -p /usr/local
!rm -rf ~/miniconda3/miniconda.sh

! conda config --add channels conda-forge
! conda install -y mamba
! mamba update -qy --all
! mamba clean -qafy

!mamba install nodejs -y

!sudo apt-get update

!npm i -g npm@latest

!npm --version

!npm install -g flowise

from threading import Thread
import portpicker

port = portpicker.pick_unused_port()

def run_app():
    !export PORT={port}; npx flowise start

thread = Thread(target=run_app)
thread.start()

from google.colab import output

output.serve_kernel_port_as_iframe(port)
```
In the code there is npm update to the latest version that doesn't work and doesn't need to work anyway. The node version is updated to be able to use flowise, using mamba / miniconda. I tried to trace the issue myself but the code refers to google.colab.kernel.proxyPort which doesn't seem to be open source. Thank you

**Comment by EvanWiederspan** [comment]
I was able to run that code and both create and save a chatflow. I would reach out to the flowise maintainers if you see further issues

**Comment by nnWhisperer** [comment]
When I check the console log, the problem is triggered upon a POST request to a google colab address: https://[machineID]colab.googleusercontent.com/api/v1/chatflows . Colab returns "not allowed", just [like a similar previous colab issue](https://github.com/googlecolab/colabtools/issues/3925), I see [this one with a comment that this feature (which feature? I assume it is post requests on colab kernel ports) is not supported but is being tracked to improve](https://github.com/googlecolab/colabtools/issues/3925#issuecomment-1674236919).
I doubt how you manage to create and save a chatflow is in a dev environment not reflecting the product environment problems.

**Comment by macsunmood** [comment]
Hi! Any updates on this ?

**Comment by nnWhisperer** [comment]
I don't have the permission to reopen the issue. Since another user reports it, it means that the issue persists. I am not using this setup anymore, hence you could open another issue if you need @macsunmood .
