### ISSUE TITLE
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by electroliz** [googlecolab/colabtools#4326]
Try to run Segformer training on gpu get:
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Describe the expected behavior**
Six months ago I trained the same model on gpu and everything worked fine.

**What web browser you are using**
Chrome

**Additional context**
Link to notebook https://colab.research.google.com/drive/1K3NHj4ESj3Yt3Eq7xejP5-FnPNigADSJ?usp=sharing

**Comment by mayankmalik-colab** [comment]
We did a lot of upgrades in the last six month. Can you also try the same on the fallback runtime? You can check [this](https://github.com/googlecolab/colabtools/issues/4214#issue-2037844472) on how to use fallback version.

**Comment by deanp70** [comment]
Hey @mayankmalik-colab – I'm getting this error when trying to train with Ultralytics YOLO now. Tried the fallback runtime but it says it's no longer available. Anything else I can do?
