### ISSUE TITLE
Colab Pro+ stops performing the task if I turn off my laptop

### ISSUE THREAD

**Issue by maxefanov** [googlecolab/colabtools#4327]
Colab Pro+ stops performing the task if I turn off my laptop. I had a long-running task running, last night I remembered its progress, in the morning I logged into colab - and the progress has not changed, although resources are decreasing

**Comment by EvanWiederspan** [comment]
This is difficult to diagnose from Github, can you file in-product feedback at Help -> Send Feedback and mention this issue?
