### ISSUE TITLE
unusable after 2 days, error on phone and imac

### ISSUE THREAD

**Issue by lgwjames** [googlecolab/colabtools#4329]
**Describe the current behavior**
made 4 images great
went to the a face swap and error after a few mins saying my Nvidia GPU found

this was on my pixel 6 phone

at home same thing, for 2 days. I have a rx580 pro in my iMac. tested on iMac and bootcamp windows. same thing 

**Describe the expected behavior**
URL to be usable for 72 hours and to make images 

**What web browser you are using**
Chrome, Firefox

**Comment by EvanWiederspan** [comment]
Are you sure you're reconnecting to a GPU runtime? You can change the runtime type in the menu, Runtime -> Change Runtime Type

**Comment by lgwjames** [comment]
after a few plays and tries, still a few warnings, but getting 32.45 it but still 20-45mins a image

**Comment by cperry-goog** [comment]
Can you provide a minimal reproducible notebook?
