### ISSUE TITLE
OutofMemory Error even when the memory is abundant.

### ISSUE THREAD

**Issue by PineappleTech1213** [googlecolab/colabtools#4331]
**Describe the current behavior**
I am trying to fine tune an LLM on colab, and keep hitting the out of memory error even when the memory is enough.
![image](https://github.com/googlecolab/colabtools/assets/125321926/9a5e385a-3ef3-4211-a586-684ae576db7e)

**Describe the expected behavior**
I expected the trainer to run smoothly.
**What web browser you are using**
Chrome

**Additional context**
I tried to set the memory split and such and cleaned the cache but nothing helps.
![image](https://github.com/googlecolab/colabtools/assets/125321926/45287c69-6b63-423d-8a85-fadba3d428d1)

**Comment by mayankmalik-colab** [comment]
Can you confirm that you still have enough memory? You can check resources while the code is executed : `Runtime` -> `View resources`
