### ISSUE TITLE
My 2 days of work disappeared after a refresh on colab

### ISSUE THREAD

**Issue by manolya** [googlecolab/colabtools#4333]
I need immediate help. 

https://colab.research.google.com/gist/manolya/c1afc6fc78d86b717aa0e9534a2fd6c3/dfnn.ipynb

I had lines of codes. I don't have time to fix it. I don't see any updates. I'm really worried. 

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by manisha-cell** [comment]
my tomorrow work is disappeared

**Comment by cperry-goog** [comment]
If you submit feedback in product we can investigate, but it's likely unrecoverable if you cannot find the data by viewing history of the file. Sorry.
