### ISSUE TITLE
Colab AI has disappeared from my Gmail account.

### ISSUE THREAD

**Issue by rejoicekumah** [googlecolab/colabtools#4334]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

Colab AI is no longer showing in my notebooks.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

Normally, when I go into my notebooks, Colab AI will be at the top right to help me fix errors in my code. 

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

Using Edge browser 

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
<img width="236" alt="image" src="https://github.com/googlecolab/colabtools/assets/68454583/e776201d-fb58-43c6-8292-94be0f208e62">

**Comment by blois** [comment]
Can you submit feedback using the Help -> Send Feedback menu to help us diagnose?

**Comment by rejoicekumah** [comment]
> Can you submit feedback using the Help -> Send Feedback menu to help us diagnose?

Just did.

**Comment by blois** [comment]
This feature has not been launched in all regions. We are working to enable this for as many users as possible.

**Comment by rejoicekumah** [comment]
I had Colab AI last week did they unlaunched it in America?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cperry-goog** [comment]
It's available in the US, not available in the EU.

Sending feedback via Help -> Send Feedback is the best way to help us diagnose.
