### ISSUE TITLE
JAX is not able to work with TPU

### ISSUE THREAD

**Issue by RogerJL** [googlecolab/colabtools#4336]
Selecting TPU as device for my JAX program (only CPU, T4 GPU and TPU are available to select)
Resulting in.

WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)

```
WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
devices [CpuDevice(id=0)]

```
setting the environment variable
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = 0

```
gives an error, that it should be a string not an int. Any other setting gives no WARNING output.
But the print still says CpuDevice

**Describe the expected behavior**
If TPU is not available (have no execution units), it should not be selectable.

With no execution units T4 GPU is possible to select and it looks like it works.
`devices [cuda(id=0)]
`

With TPU it looks like TPU is selected, but execution falls back to CPU

To me this looks like new JAX and TPUs are not compatible, or the UI is bad.

**What web browser you are using**
Chrome

**Additional context**
```
#import os
#os.environ['TF_CPP_MIN_LOG_LEVEL'] = 0
import jax

print("devices", jax.devices())

```
https://colab.research.google.com/gist/RogerJL/8af079d4a5dea667126a803365500e93/untitled0.ipynb?authuser=2#scrollTo=plECK22_jnXo&line=1&uniqifier=1

**Comment by RogerJL** [comment]
Looks like this has improved, now you get a popup telling that there are no TPUs available.

**Comment by cperry-goog** [comment]
This is a known issue; our TPU architecture is out of date, but we're actively working on this now.

**Comment by sagelywizard** [comment]
This is fixed with the "TPU v2" runtime.
