### ISSUE TITLE
Incorrect Compute Units

### ISSUE THREAD

**Issue by cevparlak** [googlecolab/colabtools#4338]
**Describe the current behavior**
Hi
I recently purchased Colab Pro with 100 compute units
but in my Colab resources it says You don't have any available processing units.
In my Colab account it shows that message:
"you have -300 (minus 300) computing units."
It looks like I'm indebted to Colab.
I know the usage limits and I don't think I have ever exceeded them.
There is something wrong here.
Regards
Order number
COL.7240-4386-9163-34268
 Payments profile ID: 6772-5032-3023

**Describe the expected behavior**
+100 Compute Units upon purchase
**What web browser you are using**
Chrome, Edge

**Additional context**
![a](https://github.com/googlecolab/colabtools/assets/45640286/d27e8ecc-b12b-4f39-8651-1910f5c7dabe)

**Comment by colaboratory-team** [comment]
Thank you for reporting this issue especially with the order ID. We identified the issue and corrected your balance, so your Compute Units balance should be 100 now. This issue is also being investigated internally with b/323181200.
