### ISSUE TITLE
Erro: Processador de quadro face_enhancer não encontrado. - /usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.   _torch_pytree._register_pytree_node( Frame processor face_enhancer not found.

### ISSUE THREAD

**Issue by Ferbeca1972** [googlecolab/colabtools#4339]
Esta ocorrendo um erro na aba Deepfake, não realizando a troca de rosto - Erro: /usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Frame processor face_enhancer not found.

**Comment by cperry-goog** [comment]
Using Colab to create Deepfakes is not permitted: https://research.google.com/colaboratory/faq.html#disallowed-activities
