### ISSUE TITLE
Synchronising data with Google Drive doesn't work

### ISSUE THREAD

**Issue by ParikhKadam** [googlecolab/colabtools#434]
I ran a code on colab today.. starting from the noon it took me midnight to get its output. But what I found was, my google drive wasn't updated with the latest contents saved by colab. All those files where shown in colab but not on drive. I don't know why but it's very frustrating waiting a long time for your output, getting all things working correctly but having such problems so that you can't download the files or have it saved to use whenever necessary..

Please solve this issue.. I am looking forward to run the same code to get the same output in future after you solve this problem.

Here are some images which might make you understand the problem:

![screenshot 51](https://user-images.githubusercontent.com/39589393/53044492-2ec48e80-34b1-11e9-9136-b8a8d4beb4aa.png)

![screenshot 61](https://user-images.githubusercontent.com/39589393/53044497-31bf7f00-34b1-11e9-829e-f7a756509a2b.png)

Please solve this as soon as possible.. Thank you!

**Comment by RamoxCode** [comment]
Have the same problem.
even downloading the files manually wasn't possible as colab takes 2h to prosses 1.8 gb (one file) just to raise a download Error
