### ISSUE TITLE
Can't pay for Colab Pro

### ISSUE THREAD

**Issue by colton-lapp** [googlecolab/colabtools#4340]
**Describe the current behavior**
When I go to pay for Google Colab pro, it asks me to add a payment method. When I click add, it shows 3 credit cards I've added but they are all greyed out with the comment "verify on payment methods page". So I can't select any of the cards I've added, and can't buy colab pro as a result. 

**Describe the expected behavior**
I should be able to select a card and pay for it. 

**What web browser you are using**
Chrome.

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by katlyn-edwards** [comment]
Have you tried verifying your payment methods here? https://pay.google.com/pay/u/0/paymentmethods It sounds like maybe something is wrong with them (maybe the expiration date needs to be updated?)

**Comment by colton-lapp** [comment]
I just tried to add my credit card there and it looked like it went through and said "payment method added" but then the list of payments was still blank... as if there was something wrong saving the processed information or something. I put the info in wrong at first and it alerted me to that, but when I fixed the info this happened... so I don't think it's a problem with incorrect info

**Comment by cperry-goog** [comment]
+1 follow up with payments, sorry

**Comment by pabrcno** [comment]
+1

**Comment by kjin2020** [comment]
+1. It keeps insisting that my credit card is invalid and that I need to replace it with a new one. When I attempt to access my Google Wallet, it notifies me that I recently—meaning three years ago—changed my recovery phone number. Now, I am required to receive a verification code on my old number, which I have been unable to access for the past three years!
