### ISSUE TITLE
SyntaxError: Unexpected token 'e', "eyJuYmZvcm"... is not valid JSON

### ISSUE THREAD

**Issue by Arjun20398** [googlecolab/colabtools#4342]
**I am not able to open new notebooks in any of my google account**
If I open older notebooks then also I'm getting the same error. I deleted notebook folders from the drive but I still get the same error.

I have been having this issue for some months, I remember once I mounted my drive to google-colab after that it started to come.

There was an error loading this notebook. Ensure that the file is accessible and try again.
Unexpected token 'e', "eyJuYmZvcm"... is not valid JSON

https://drive.google.com/drive/?action=locate&id=1cxQ4H_9J3PFKM8Urs9-xGe4wZZeTOg&authuser=0

Unexpected token 'e', "eyJuYmZvcm"... is not valid JSON
SyntaxError: Unexpected token 'e', "eyJuYmZvcm"... is not valid JSON

**Comment by cperry-goog** [comment]
Can you share that drive file publicly? You can share through the Drive UI so no need to open up Colab. When I try to access it says it doesn't exist.

**Comment by gmolinav20052013** [comment]
The same problem. I can't loading a notebook.

**Comment by ctxwing** [comment]
i got just same as @Arjun20398 . it is simple "Create New" colab notebook. even error meassage was the same

**Comment by cperry-goog** [comment]
Can you file feedback in product when you encounter this? Or share a link to a Colab notebook that won't load for you and we can look?

@ctxwing I've got no good ideas of what might be happening, getting feedback report might help.

**Comment by gmolinav20052013** [comment]
[image: image.png]

**Comment by gmolinav20052013** [comment]
[image: image.png]

**Comment by gmolinav20052013** [comment]
[image: image.png]

**Comment by EvanWiederspan** [comment]
None of those images are loading on Github, we'll need a link to the notebook, or better, in-product feedback as mentioned above

**Comment by gmolinav20052013** [comment]
It works, was fixed. Thanks for your support.

**Comment by GrzegorzDuzynski** [comment]
You have problem with CORS ?

**Comment by gmolinav20052013** [comment]
No. Was solved. Maybe they fixed something.

Thanks

**Comment by ZionPi** [comment]
fixed by turn CORS Unblock extension off in chrome.

**Comment by sodaMelon** [comment]
oh it really from  CORS Unblock extension lol. i forgot it 
thanks everybody
