### ISSUE TITLE
FileNotFoundError: [Errno 2] Unable to open file

### ISSUE THREAD

**Issue by romulobsilva** [googlecolab/colabtools#4349]
Tutorial 2 Part II:
Physics inspired Machine Learning

Partial Differential Equation (PDE) Solvers 

Resolution Invariance

The Fourier layers are discretization-invariant, because they can learn from and evaluate functions which are discretized in an arbitrary way. Since parameters are learned directly in Fourier space, resolving the functions in physical space simply amounts to projecting on the basis of wave functions which are well-defined everywhere on the space. This allows us to transfer among discretization.
Time to code a Neural PDE Solver

FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/content/KdV_train_10_1_3_512_easy.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

################################################################
# read data
################################################################
train_loader = create_dataloader(r"/content/KdV_train_10_1_3_512_easy.h5", mode="train", nt=nt, nx=nx, batch_size=batch_size, num_workers=num_workers)
valid_loader = create_dataloader(r"/content/KdV_valid_10_1_3_easy.h5", mode="valid", nt=nt, nx=nx, batch_size=batch_size, num_workers=num_workers)
test_loader = create_dataloader(r"/content/KdV_test_10_1_3_easy.h5", mode = "test", nt=nt, nx=nx, batch_size=batch_size, num_workers=num_workers)

**Comment by EvanWiederspan** [comment]
I would reach out to the notebook author instead, this does not seem to be an issue with Colab itself
