### ISSUE TITLE
Documentation on downloading from Drive is confusing

### ISSUE THREAD

**Issue by bcli4d** [googlecolab/colabtools#435]
The 'Downloading data from a Drive file into Python' cell of the '[Loading and saving data: Local files, Drive, Sheets, Google Cloud Storage](https://colab.research.google.com/notebooks/io.ipynb#scrollTo=P3KX0Sm0E2sF)' documentation page has the following:

"# Download the file we just uploaded."
"#"
"# Replace the assignment below with your file ID"
"# to download a different file."
"#"
"# A file ID looks like: 1uBtlaggVyWshwcyP6kEI-y_W3P8D26sz"
"file_id = 'target_file_id'"

The comment suggests that no change is needed if the user only wants to download the file just uploaded, however target_file_id must always be replaced by some valid file ID. Perhaps :

"# Download a the file we just uploaded or a different file from Drive'"
"#"
"# Replace 'target_file_id' in the assignment below with the the file ID of"
"# either the file we just uploaded or a different file to be downloaded."

**Comment by bcli4d** [comment]
Sorry about the poor styling. The bold lines were meant to be comments beginning with '#'.

**Comment by metrizable** [comment]
The io.ipynb notebook has been updated.
