### ISSUE TITLE
Frame processor face_enhancer not found.

### ISSUE THREAD

**Issue by nastaranir** [googlecolab/colabtools#4351]
![Screenshot 2024-02-02 at 22-25-59 Google Colaboratory](https://github.com/googlecolab/colabtools/assets/158611436/87130055-314b-40b2-b014-eaa1d3266930)
<!--

Hello
Does not work
please check it
thank you.

![Screenshot 2024-02-02 at 22-25-59 Google Colaboratory](https://github.com/googlecolab/colabtools/assets/158611436/f897da1b-5ef6-4f23-b7ba-c816d41fb28e)

**What web browser you are using**
(Firefox)

**Comment by explore2024** [comment]
I am having the same issue.

**Comment by EvanWiederspan** [comment]
I would reach out to the notebook author instead, this does not seem to be an issue with Colab itself

**Comment by Dan3344** [comment]
I have the same bug. How to fix it?
