### ISSUE TITLE
Colab Pro Free for Students

### ISSUE THREAD

**Issue by karkir0003** [googlecolab/colabtools#4354]
**Is your feature request related to a problem? Please describe.**
Colab Pro free for students to get their hands dirty with GPU, TPU for ML/DL use cases
**Describe the solution you'd like**
Colab Pro free for students

**Describe alternatives you've considered**
Not having Colab pro as a student

**Additional context**
I didn't get a concrete response from my request [here](https://github.com/googlecolab/colabtools/issues/3325). Can someone from the colab team please address my followup and/or provide a timeline/ETA if this feature is on the team's roadmap

**Comment by cperry-goog** [comment]
Duping in with #2367
