### ISSUE TITLE
Colab pro+ consistently killing process after 2-4 hours.

### ISSUE THREAD

**Issue by geordw** [googlecolab/colabtools#4356]
**Describe the current behavior**
I start a high RAM CPU-only computation from the terminal. Despite using only 10-30GB of RAM and minimal disc the process is consistently killed after 2-4 hours of execution. (I got 2* 24 hr executions, and since then have had 6-7 processes killed, all around the 2-4 hour mark.)

**Describe the expected behavior**
When I signed up for colab pro+, I expected reasonably consistent 24h execution.

**What web browser you are using**
Chrome.

**Additional context**
Perhaps this is just false expectations, but it would be good to understand what I can and cannot do on colab pro+. I am an academic ML researcher, and these interruptions are severely hampering my ability to work. Would it help if I ran the computations through a notebook? Is my use of terminal causing the computations to be killed?

**Comment by EvanWiederspan** [comment]
Can you file in-product feedback at Help -> Send Feedback instead? This is difficult to diagnose from Github
