### ISSUE TITLE
504 gateway time out

### ISSUE THREAD

**Issue by shevaree** [googlecolab/colabtools#4360]
**Describe the current behavior**
when i try to open colab i have this type of error, and until yesterday it worked

**Describe the expected behavior**

**What web browser you are using**
Chrome

**Comment by Jon4141411** [comment]
I am having the same issue. It produces the gradio IP address, but won't connect upon clicking it.

**Comment by GabriBOAT** [comment]
I have the exact same problem I tried both normal and incognito on Chorme and Edge's

**Comment by katlyn-edwards** [comment]
Can you include a HAR file of your network activity? We aren't seeing any issues on our side :/ 

To generate a HAR - open the chrome dev tools, go to the network tab, and then make sure the record button is enabled.  Trigger the action that causes the 504 (reloading the page?) and then download the har and upload it here.
