### ISSUE TITLE
File uploads are only saving partial file contents

### ISSUE THREAD

**Issue by nick-nagaraj** [googlecolab/colabtools#437]
When I upload a csv file to collab, it only shows 4306 rows out of the actual 24000. I have tried reading it on my local pc and have confirmed that it does indeed contain 24000 rows. This issue seems to be specific to collab, and reading it using pandas also returns only 4306 rows. What could be the issue?
My notebook:
![error_1](https://user-images.githubusercontent.com/37271004/53144687-4db34580-35c3-11e9-94ba-45fa5df79f43.png)
My local pc:
![screenshot from 2019-02-21 10-28-38](https://user-images.githubusercontent.com/37271004/53144746-82270180-35c3-11e9-9a63-197e838c1a53.png)

**Comment by nanselmo** [comment]
I'm having a similar issue. When I upload [census.csv](https://github.com/udacity/DSND_Term1/blob/master/projects/p1_charityml/census.csv),  it's as though the dataframe is starting midway through at a random point (in this case the first full row is 44239).

The "header" just says "ates" and ">50k" - so it's using a partial row of 44239 as a header.

![screenshot 2019-02-21 at 7 52 10 am](https://user-images.githubusercontent.com/10697941/53173634-b2fc3c00-35ad-11e9-93ff-968b1eeb15c9.png)

**Comment by Llvve** [comment]
Same issue here with xls file. When I downloaded back from colab it look like this

![image](https://user-images.githubusercontent.com/4600820/53187823-87716400-3636-11e9-9ecb-65992ed12c6e.png)

I have noticed if file size is less than 1mb it works fine.

**Comment by blois** [comment]
We are working on an urgent fix for this.

@Llvve is correct that files <1MB should complete normally.

A temporary workaround for larger files is to use:

```python
from google.colab import files
files.upload();
```

**Comment by colaboratory-team** [comment]
Sorry for the trouble. We're working on a service change now to fix.

An immediately usable work-around is to upload the file to Google Drive, and then to copy the file after mounting your Drive using [the recipe here](https://colab.research.google.com/notebooks/io.ipynb#scrollTo=u22w3BFiOveA)

```
from google.colab import drive
drive.mount('/content/gdrive')
```

**Comment by nick-nagaraj** [comment]
> Sorry for the trouble. We're working on a service change now to fix.
> 
> An immediately usable work-around is to upload the file to Google Drive, and then to copy the file after mounting your Drive using [the recipe here](https://colab.research.google.com/notebooks/io.ipynb#scrollTo=u22w3BFiOveA)
> 
> ```
> from google.colab import drive
> drive.mount('/content/gdrive')
> ```

Thanks for the response. Unfortunately, this doesn't work for me as I am also currently encountering another error at the moment where I am unable to enter the authorization code to mount google drive. (However, I believe this issue is currently being addressed)

**Comment by nanselmo** [comment]
Does a local upload work for you Nick? 
from google.colab import files
uploaded = files.upload()

**Comment by colaboratory-team** [comment]
This issue should be mitigated in new VMs.
If you have an old VM, please click "Reset all runtimes" in the Runtime menu to get a fresh one.
If you still see issues after that, please chime in here.
If you previously saw issues and no longer do, feel free to thumbs-up this update to avoid spamming the history.

**Comment by githubbla** [comment]
may be it's not related, colab now lost connectivity to my gdrive

Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.

**Comment by colaboratory-team** [comment]
@githubbla please open a new issue with as much reproduction information as you can include.
