### ISSUE TITLE
CPU instances stuck in loop of allocating runtime, connecting to runtime, initializing runtime, allocating runtime 

### ISSUE THREAD

**Issue by ProGamerGov** [googlecolab/colabtools#4379]
**Describe the current behavior**

Upon running code or even opening the resources tab the notebook will disconnect within seconds and end up in a loop of: "allocating runtime -> connecting to runtime -> initializing runtime -> disconnected -> allocating -> connecting". Despite these messages it seems to be the same runtime each time as the changes as code cells keep running and downloaded files remain.

**Describe the expected behavior**

It should have stable connection.

**What web browser you are using**

Firefox

**Additional context**

My internet connection is fine and there appears to be no connectivity issues between connecting with Colab on my end. Its also happened across multiple days.

Link to a minimal, public, self-contained notebook that reproduces this issue.
I don't believe there's a way I can reproduce it code-wise on other notebooks as it happens for any code cell I run.

**Comment by EvanWiederspan** [comment]
This will be difficult to diagnose from Github, can you instead send in-product feedback at Help -> Send Feedback and mention this issue?
