### ISSUE TITLE
Editing "collapsed_sections" from within Colab editor

### ISSUE THREAD

**Issue by ericricky** [googlecolab/colabtools#438]
Can we get a way of choosing which sections are hidden on startup? Right now I can get sections to start collapsed by editing the "collapsed_sections" metadata in the raw ipynb file, but I can't get that metadata to change just by editing the notebook in Colab.

**Comment by blois** [comment]
The section state should be saved as part of notebook save. Can you try an explicit ctrl-S save?

**Comment by ericricky** [comment]
@blois Yeah, it works after saving. I noticed this the other day and meant to close the issue but forgot!
