### ISSUE TITLE
GRU and LSTM cells not using cuDNN kernel

### ISSUE THREAD

**Issue by ethanm123** [googlecolab/colabtools#4385]
**Describe the current behavior**
My GRU and LSTM cells are not using cuDNN kernels, resulting in incredibly slow training speed:
WARNING:tensorflow:Layer gru_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.

Definition of GRU layer (LSTM is using same arguments):
bidirectional_1 = keras.layers.Bidirectional(keras.layers.GRU(64, return_sequences=True), name="gru1")

This exact model definition worked less than 2 weeks ago and built without this issue on colab. I am also currently able to build the model on my local machine without this issue, leading me to believe its an issue with the colab environment. 

I have tried this on the T4 GPU and the V100 (high ram). It persists on both. 

Edit: This issue seems to only occur after loading a model? If I build a model with fresh layers with the same parameters it builds without this issue. Then if I try loading a model this issue begins, and even if I try and build the fresh model again as before, the issue happens here too. Again, everything works without issue on my local machine. 

**Describe the expected behavior**
This warning doesn't appear and GRU and LSTM use cuDNN kernel optimisations, my training time 2 weeks ago was 1/8th of what it is now, the model definition hasn't changed I am literally rerunning the same cell. 

**What web browser you are using**
Firefox and Chrome, both Windows and MacOS. 

**Additional context**
I have followed the docs to ensure the parameters that allow for the optimisation are correct (https://keras.io/api/layers/recurrent_layers/gru/). I tried specified them manually, although the default values should suffice. Neither worked. This is costing me an unbelievable amount of compute units, and my runtime is likely to timeout before training finishes. This is incredibly frustrating.

**Comment by ethanm123** [comment]
> The document you shared is for keras 3 and there is a [new version release on 14th Feb for keras 3](https://screenshot.googleplex.com/Xj823x3LxjzdsmR) I am not sure which version do you use ot it's possible that you used something like `pip install --upgrade keras` that uses `3.0.5` after 14th Feb but used `3.0.4` before that. Can you also check other dependencies too.

I didn't run any dependency updates on my end, I only ran copy and 7zip commands in my notebook. I can see that colab is still using Keras 2.15 and as I didn't update Keras myself this shouldn't be the issue? I am also confused why the issue only happens after loading a model. If I compile a model from scratch without loading it compiles without this issue, even if the parameters are the same? After trying to load a model the problems begin. 
I checked Tensorflow when I opened the issue and they hadn't released a new version either. 
The issue is still persisting. I managed to train my models in the end but it used a lot of compute credits

**Comment by mayankmalik-colab** [comment]
Can you share a small reproducible notebook, along with some sample data you are training on. It is difficult to debug like this. If you can provide a repro notebook, I can give it a try.

**Comment by ethanm123** [comment]
Running the exact same code in a new notebook fixed the issue. I have no idea why since the issue still persists in my original notebook and all the copies I made of it, but the notebook works fine on my local machine and the same code works in a new Colab notebook? Feel a bit thick for not trying it in another notebook though. Thanks for your help :)
