### ISSUE TITLE
Question about Google Colab Pro Plus ?

### ISSUE THREAD

**Issue by VeryUselessKid** [googlecolab/colabtools#4386]
I'm running a program using Google Colab Pro Plus. For each epoch, I print out details such as the epoch number and iteration on the WebUI to keep track. I also save this information to Google Drive. I want to ask, if I shut down my PC, will the background execution print the output to the WebUI on Colab, or will it only save the output to Google Drive?

Thanks

**Comment by EvanWiederspan** [comment]
Background execution will keep running the notebook when you close the tab, including any writes to Google Drive in the background, as well as updating your notebook so that you will see any changes in the WebUI when you come back to it
