### ISSUE TITLE
The webpage freezes when this command is run in vim

### ISSUE THREAD

**Issue by ajay-vishnu** [googlecolab/colabtools#4387]
# The colab webpage freezes when this command is used
**Describe the current behavior**
Whenever I type this command in command mode while using vim editor, the entire webpage freezes and I've close and reopen.
```vim
:%s/<string1>/<string>/g
```

**Describe the expected behavior**
This command is supposed to replace `string1` with `string2` in the active cell.

**What web browser you are using**
Chrome

**Comment by yumemio** [comment]
Not OP, but I experienced a similar issue when a specific pattern is involved. 

For example, let's say you have a cell with the code like this:

```python
prompt = (
    "You are Gemini, an AI assistant created by Google."
    "Today is March 21, 2024."
    "You respond to the user's questions or instructions politely."
)
```

And you want to put the newline to the end of each string, so you run `:%s/"$/\\n"/g`. This command will freeze the browser tab, forcing me to reload the page. My env is Firefox/Ubuntu 20.04.

I *guess* what's happening is an infinite loop, like this:

* `"...by Google."` -> `"...by Google.\n"`
* `"...by Google.\n"` -> `"...by Google.\n\n"`
* and so on...

I also found that a workaround is to remove the `g` flag from the command. Note that this workaround may be specific to the above example, and depending of what you're trying to substitute this may not be an option.

Also, this kind of pattern works fine in Neovim (and possibly Vim too).

@ajay-vishnu, can you comment on whether this applies to your case too?

**Comment by ajay-vishnu** [comment]
Yup, this is what I faced as well. The webpage would freeze whenever the `g` tag is used.

**Comment by yumemio** [comment]
Thanks. The upstream issue is https://github.com/brijeshb42/monaco-vim/issues/87, which is already fixed (no longer reproducible in [their demo](https://editor.bitwiser.in/)). Hopefully the Colab team will update the library soon!

**Comment by cperry-goog** [comment]
Thanks @yumemio - tracking the monaco vim upgrade internally at b/330730012 - we'll get to it.

**Comment by cperry-goog** [comment]
This is fixed in prod. Thanks again.
