### ISSUE TITLE
Change Runtime Type UI Issue

### ISSUE THREAD

**Issue by Nitin-Mane** [googlecolab/colabtools#4389]
There is an issue with the UI for the change runtime type setting to select from the front-end interface. 

**Describe the current behavior**
Currently, when attempting to change the runtime type setting from the front-end interface, users encounter issues with the user interface. Specifically, the options for selecting a different runtime type are either missing, unresponsive, or displaying incorrectly.

**Describe the expected behavior**
The expected behaviour is that when users navigate to the change runtime type setting in the front-end interface, they should be presented with a clear and functional dropdown or selection menu that allows them to choose from available runtime types. This selection process should be intuitive and responsive, ensuring users can easily switch between different runtime types without encountering any UI issues.

### Steps to Reproduce

1. Log in to the colab application.
2. Navigate to the runtime section where the runtime type can be changed.
3. Attempt to change the runtime type.
4. Observe any issues with the user interface, such as missing options, unresponsive dropdown menus, or incorrect display of available runtime types.

**What web browser you are using**
The issue has been observed across multiple web browsers including Chrome, Brave, and Edge.

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
 
 
![Screenshot 2024-02-18 131449](https://github.com/googlecolab/colabtools/assets/15194333/69df02b3-a048-40a0-9073-e3314a435e25)

![Screenshot 2024-02-18 132013](https://github.com/googlecolab/colabtools/assets/15194333/6b67cb62-e785-498a-b961-935d71349332)

**Comment by katlyn-edwards** [comment]
Hey there!

Can you try this in an incognito window? We've seen reports of this before, but it's been caused by extensions installed.

In https://github.com/googlecolab/colabtools/issues/4018 it was caused by a Norton extension, for example.

**Comment by CL-VO** [comment]
Oh. Colab staff is too dumb to code CSS once again.
