### ISSUE TITLE
Regression: predict fuel efficiency tutorial seems to be outdated

### ISSUE THREAD

**Issue by lukbebalduke** [googlecolab/colabtools#439]
Under the list of tutorials in the TensorFlow website, this [particular one](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/keras/basic_regression.ipynb?hl=pt-br) is outdated. If you Run all code you can see that under the section **Inspect the model** the second snippet shall crash and the execution is aborted.

I would heavily appreciate the revision of that particular code.

**Comment by craigcitro** [comment]
What error are you seeing? (That notebook executes with no errors for me.)
