### ISSUE TITLE
Try implementing the ‘exit’ statement

### ISSUE THREAD

**Issue by ItheaChtholly** [googlecolab/colabtools#4390]
**Is your feature request related to a problem? Please describe.**
I tried terminating the entire notebook using `exit`, but the kernel always restarted after crashed. And closing the browser directly does not seem to interrupt the notebook.

**Describe the solution you'd like**
When using `exit` or `exit()`, a dialog box will pop up asking whether to terminate the core. 'Yes' to shut down the kernel and exit, 'No' to nothing.

**Comment by EvanWiederspan** [comment]
`runtime.unassign` should do what you want:

```python
from google.colab import runtime
runtime.unassign()
```
This immediately unassigns your runtime and disconnects you

**Comment by ItheaChtholly** [comment]
Sorry to view this comment after really long time.
It seems to work, Thanks!
