### ISSUE TITLE
Float not Callable

### ISSUE THREAD

**Issue by remartins75** [googlecolab/colabtools#4393]
**Describe the current behavior**
not recognize "float"
Code: 
'''Como sugestão de prática, indicamos você a criar um novo script python seguindo as orientações a seguir:

Crie três inputs que receba os três dados abaixo:
Nome do tipo string
Altura do tipo Float
CPF do tipo inteiro  
      2. Exiba através de um único print as três informações para o usuário.'''

nome = input("escreva seu nome: ") #string
altura = float (input("qual a sua altura: "))  #float
CPF = int(input("qual seu CPF: "))  #inteiro
print("nome digitado é: ", nome, ", altura: ", altura, ", CPF: ", CPF, ".")

Error: escreva seu nome: regina
qual a sua altura: 1.60
qual seu CPF: 123456
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-42-0f8470f7dd83>](https://localhost:8080/#) in <cell line: 12>()
     10 altura = float (input("qual a sua altura: "))  #float
     11 CPF = int(input("qual seu CPF: "))  #inteiro
---> 12 print("nome digitado é: ", nome, ", altura: ", altura, ", CPF: ", CPF, ".")
     13 
     14 

TypeError: 'float' object is not callable

**Describe the expected behavior**
Necessita trazer as informacoes digitadas em uma unica linha. Testado no VsCode e funcionou normalmente.  
​
104 / 5.000
Resultados de tradução
Resultado da tradução
You need to bring the information entered on a single line. Tested in VsCode and it worked normally.

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
 - nome = input("escreva seu nome: ") #string
altura = float (input("qual a sua altura: "))  #float
CPF = int(input("qual seu CPF: "))  #inteiro
print("nome digitado é: ", nome, ", altura: ", altura, ", CPF: ", CPF, ".")

escreva seu nome: regina
qual a sua altura: 1.60
qual seu CPF: 123456
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-42-0f8470f7dd83>](https://localhost:8080/#) in <cell line: 12>()
     10 altura = float (input("qual a sua altura: "))  #float
     11 CPF = int(input("qual seu CPF: "))  #inteiro
---> 12 print("nome digitado é: ", nome, ", altura: ", altura, ", CPF: ", CPF, ".")
     13 
     14 

TypeError: 'float' object is not callable

**Comment by EvanWiederspan** [comment]
You likely re-assigned `print` to be a number, overriding the print function. Restarting your session and removing the code that does this should fix the issue
