### ISSUE TITLE
I subscribed to PRO but cannot use T4 And the daily usage time is less than 4 hours

### ISSUE THREAD

**Issue by roxas1212** [googlecolab/colabtools#4395]
**Describe the current behavior**
I subscribed to PRO but cannot use T4 And the daily usage time is less than 4 hours

**Describe the expected behavior**
Can run on T4 and be used for at least 4 hours a day
I can only use it for 1 hours now and can't even use it

**What web browser you are using**
Chrome.

**Comment by colaboratory-team** [comment]
If you submit an in-product feedback (`Help` > `Send feedback` on https://colab.research.google.com/), we can take a look at your usage history to see if there are any issues. However, please note that once your monthly compute units (100 for a Pro subscriber) is exhausted, your compute usages are considered free of charge and not guaranteed (as stated in `Runtime` > `View Resources` as `You currently have zero compute units available. Resources offered free of charge are not guaranteed.`). Please submit an in-product feedback if you'd still like us to investigate.

**Comment by roxas1212** [comment]
I have subscribed to you for a long time. 
In the past, even if you used up all the compute units, you could still use T4 for at least 4 hours a day, but now can't.
I think it would be better for me to subscribe to paperspace.

**Comment by colaboratory-team** [comment]
As noted above, once you're out of compute units, your account acts the same as a free user, where GPU resources are not guaranteed.

**Comment by roxas1212** [comment]
However, you were not like this before. You obviously cut corners.
