### ISSUE TITLE
Code error cuase the colab cell to crash

### ISSUE THREAD

**Issue by BIGdeadLock** [googlecolab/colabtools#4396]
**Describe the current behavior**
When there is some error in my colab notebook code the cell which run the buggy code will just stuck. The error stack is not displayed and it keep on running. After some time an error message pop up about JS code. I need to delete the cell and paste the code to a new cell to try and run the code again. The most painful point is there is no error stack message, meaning I don't know where is the bug in my code.

**Describe the expected behavior**
Code crash and the error stack printed.

**What web browser you are using**
Firefox (Happen on Chrome as well)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
https://colab.research.google.com/gist/BIGdeadLock/19396ae70a03dd25fcc323a913ec9410/untitled0.ipynb

![Screenshot 2024-02-22 at 16 57 55](https://github.com/googlecolab/colabtools/assets/64005996/77ecd697-747a-4778-a70b-37bf291d0add)

**Comment by EvanWiederspan** [comment]
Does this only happen for you in this notebook? Also, does this still happen for you in incognito mode, with all extensions disabled?

**Comment by colaboratory-team** [comment]
@CanisDirusPrime that doesn't look like the same issue, can you file a new issue instead and include the notebook you are running?
