### ISSUE TITLE
Colab didn't keep my save history and because of that, I lost 5 hours of work

### ISSUE THREAD

**Issue by E-crls** [googlecolab/colabtools#4397]
**Describe the current behavior**
Google colab simply lost all the progress I had made in the last 5 hours of work. The browser closed, I went to open it again, all the progress saved was lost, along with my trust in the platform.

**Describe the expected behavior**
Colab should do what it told me it would do, that is, keep the progress history saved.

**What web browser you are using**
Opera.

**Additional context**
I no longer trust your platform. Whenever I have to use it I will download my entire file with each progress I make. I hated the stress and anger I went through because of this. I wont trust the plataform anymore. Never.

**Comment by colaboratory-team** [comment]
This will be difficult to diagnose from Github, can you file in-product feedback at Help -> Send Feedback instead?

**Comment by loganvaz** [comment]
Going to second this - also lost a ridiculous amount of work bc of this. Is there any way to recover?

**Comment by dashrath-chauhan** [comment]
Happened with me today as well, lost a few hours or work because it didn't saved the progress.
