### ISSUE TITLE
Dropdowns no longer show defined options

### ISSUE THREAD

**Issue by henk717** [googlecolab/colabtools#4399]
**Describe the current behavior**
The dropdowns have a new look with a better looking drop-down UI that makes it clearer that they can be expanded, but only the default option is populated in the menu.

**Describe the expected behavior**
The colab has a new look with better looking drop-downs, but they actually contain the defined options.

**What web browser you are using**
Latest Firefox, Edge

**Additional context**
Version = "Official" #@param ["Official", "Beta"] {allow-input: true}

**Comment by katlyn-edwards** [comment]
Thanks for the report. We're tracking this internally at b/326628715

If you delete the pre-populated text from the drop down, all options will re-appear, it's filtering the results based on the pre-populated text.

**Comment by henk717** [comment]
Ah, I understand now. This is causing mass confusion for my users because they do not understand where the options went. We populate sane defaults, but as a result they have no idea what other options they can pick.

**Comment by LostRuins** [comment]
Just bumping this thread as it is quite a significant issue - the auto-filter aspect means that any editable dropdown cannot be pre-populated, otherwise they would simply become a textbox. 

Perhaps this filter behavior could be disabled by setting a property of the dropdown.

**Comment by colaboratory-team** [comment]
Thanks for the feedback, this should be improved now. Filtered options are not shown until the user changes the input box text
