### ISSUE TITLE
Red line doesn't plot on Machine Learning Crash Course Simple Linear Regression with Synthetic Data exercise

### ISSUE THREAD

**Issue by bmarieg** [googlecolab/colabtools#4408]
**Describe the current behavior**

In the "Specify the paramaters" portion of the tutorial, a plot is generated. This plot should have a red line that shows the output of the model. It does not. Running the code produces an error:

ValueError                                Traceback (most recent call last)
[<ipython-input-30-f9468caf965a>](https://localhost:8080/#) in <cell line: 9>()
      7                                                          my_label, epochs,
      8                                                          my_batch_size)
----> 9 plot_the_model(trained_weight, trained_bias, my_feature, my_label)
     10 plot_the_loss_curve(epochs, rmse)

6 frames
[/usr/local/lib/python3.10/dist-packages/numpy/core/shape_base.py](https://localhost:8080/#) in atleast_1d(*arys)
     63     res = []
     64     for ary in arys:
---> 65         ary = asanyarray(ary)
     66         if ary.ndim == 0:
     67             result = ary.reshape(1)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 1) + inhomogeneous part.

**Describe the expected behavior**

The plot should have a red line that shows the output of the model.

**What web browser you are using**

Chrome

**Additional context**

Here is the link to the exercise:
(https://colab.research.google.com/github/google/eng-edu/blob/main/ml/cc/exercises/linear_regression_with_synthetic_data.ipynb?utm_source=mlcc&utm_campaign=colab-external&utm_medium=referral&utm_content=linear_regression_synthetic_tf2-colab&hl=en#scrollTo=QF0BFRXTOeR3)

I believe the error occurs because the portion of the code that generates the red line (in the section "Defining plotting functions") tries to plot a mixture of integers/floats and lists. The code works if you make y0 and y1 floats instead of lists like this:

  # Create a red line representing the model. The red line starts
  # at coordinates (x0, y0) and ends at coordinates (x1, y1).
  x0 = 0
  y0 = trained_bias[0]
  x1 = feature[-1]
  y1 = trained_bias[0] + (trained_weight[0][0] * x1)
  plt.plot([x0, x1], [y0, y1], c='r')

**Comment by bmarieg** [comment]
The "Linear Regression with a Real Dataset" exercise in the same course has the same problem and can be fixed the same way.

**Comment by sandersk** [comment]
Thanks very much for the bug report, @bmarieg! We've merged in a [PR](https://github.com/google/eng-edu/pull/95) that fixes this error, so the Colabs should work as expected now. Please let me know if you encounter any further issues.

**Comment by colaboratory-team** [comment]
Thanks @sandersk!
