### ISSUE TITLE
cannot install package "pyenchant"

### ISSUE THREAD

**Issue by YuhuiNi** [googlecolab/colabtools#441]
I try to install the package "pyenchant" but failed.
<img width="1212" alt="screen shot 2019-02-22 at 18 44 15" src="https://user-images.githubusercontent.com/40183327/53278926-2303e280-36d2-11e9-80fd-68e177a2ad1e.png">

**Comment by craigcitro** [comment]
Running with `pip install -v` reveals the problem -- `pyenchant` requires the `enchant` library.

    !apt install -qq enchant
    !pip install pyenchant

should have you good to go.

**Comment by YuhuiNi** [comment]
Thanks, it works

**Comment by AtrikGit6174** [comment]
@craigcitro I had used your method and it used to work about one year ago too, but now it shows and "ImportError: The 'enchant' C library was not found and maybe needs to be installed."

I have raised a issue on the developers' GitHub repo @ https://github.com/pyenchant/pyenchant/issues/253
Looking forward to your advice.

**Comment by blois** [comment]
```python
!apt update
!apt install -qq enchant
!pip install pyenchant
```

**Comment by dmerejkowsky** [comment]
Yup - that should work. You may also need to install a dictionary for the language you intend to use PyEnchant with. More information here : https://pyenchant.github.io/pyenchant/install.html#installing-a-dictionary

Cheers!

**Comment by M4MURARI** [comment]
> ```python
> !apt update
> !apt install -qq enchant
> !pip install pyenchant
> ```
After successfully running the above code, when I run `import enchant` in google colab then following error comes
```
NameError: name 'enchant_lib_path' is not defined
```

**Comment by dmerejkowsky** [comment]
Is this the entire error message ? It would be really helpful to have the whole back trace here.

**Comment by M4MURARI** [comment]
Thanks, everyone for your expert help, Now no error and enchant is working fine in Google Colab. Below code  worked for me -
```
!apt update
!apt install enchant --fix-missing
!apt install -qq enchant
!pip install pyenchant
```
