### ISSUE TITLE
I have a PRO subscription and it only has 12gb of RAM, why?

### ISSUE THREAD

**Issue by sucioyarrastrado** [googlecolab/colabtools#4410]
I have a PRO subscription and it only has 12gb of RAM, why?

Chrome - Win10 PC

**Comment by mayankmalik-colab** [comment]
You can select high ram machines. Select `Runtime->Change runtime type->High-Ram`

**Comment by sucioyarrastrado** [comment]
> You can select high ram machines. Select `Runtime->Change runtime type->High-Ram`

It doesn't work, I've been trying for more than 24 hours and it won't let me, to make matters worse it says that I have exceeded the usage limit

**Comment by colaboratory-team** [comment]
Once a subscriber's purchased compute units are depleted, their ongoing usage will be treated & restricted the same way as free of charge users, which is as stated in the Runtime - View Resources pane ("You currently have zero compute units available. Resources offered free of charge are not guaranteed. Purchase more units [here](https://colab.research.google.com/signup?utm_source=resource_tab&utm_medium=link&utm_campaign=payg_learn_more)."). Once a user's (subscriber or not) free of charge allowance is exhausted (that is, when the user "exceeded the usage limit"), then Colab allows only 1 CPU Standard runtime (no High-RAM). Thus this appears to be all working as expected. Free usage allowance will refill (to a daily maximum) in at most 24 hours, at which point you may be able to get a High-RAM runtime, but again, that'll also be restricted with the free of charge resource usage policy and not guaranteed.
