### ISSUE TITLE
I want to hide popups.

### ISSUE THREAD

**Issue by skeleton66** [googlecolab/colabtools#4413]
**Describe the current behavior**
The message used to be displayed only as a message, but since yesterday it has been popping up.

**Describe the expected behavior**
I would like the pop-up to stop as it is depressing.

**What web browser you are using**
Chrome

[ - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.](https://colab.research.google.com/github/litagin02/Style-Bert-VITS2/blob/master/colab.ipynb)
![スクリーンショット 2024-03-01 120414](https://github.com/googlecolab/colabtools/assets/127566572/c6f1d6e9-1ec5-4fec-86c6-d86460cf9054)

**Comment by cperry-goog** [comment]
Sorry popups like these are necessary to instruct users!

**Comment by skeleton66** [comment]
However, it was once not displayed.
