### ISSUE TITLE
Don't ending process collab video

### ISSUE THREAD

**Issue by leadbit1** [googlecolab/colabtools#4416]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
If your runtime is terminating unexpectedly, you can file feedback in product with a clear description of what caused the termination and we'll take a look.
