### ISSUE TITLE
Google colab tensorflow-gpu stuck with importerror: libcublas.so.9.0

### ISSUE THREAD

**Issue by welcomesorrow** [googlecolab/colabtools#442]
Google colab has CUDA 10, whereas tensorflow-gpu remains version 1.12.0 which is built against CUDA 9, causing an import error as in the title.

One can compile tensorflow-gpu against CUDA 10, but i wonder why Google colab did not do it when they updated CUDA driver.

**Comment by craigcitro** [comment]
TF with GPU support is already installed by default in GPU runtimes; there's no need to install your own.

(If you've installed another and want to undo, you can just go to `Runtime` -> `Reset all runtimes` and you'll get a fresh runtime.)

**Comment by welcomesorrow** [comment]
Thank you and you are right, craigcitro, that I should not have installed "tensorflow-gpu" by myself. Just running the code with pre-installed "tensorflow" worked fine.

**Comment by nmfzone** [comment]
@craigcitro However colab uses tensorflow 1.15. If I need to use tensorflow 1.8 and tensorflow-gpu 1.8, how to do it?
