### ISSUE TITLE
Cant connect to custom VM ion Colab

### ISSUE THREAD

**Issue by mariusz6100** [googlecolab/colabtools#4421]
**Describe the current behavior**
I am trying to connect to Custom VM from Colab: I press the 'Connect to Custom VM' in Deployment manager
<img width="1109" alt="image" src="https://github.com/googlecolab/colabtools/assets/67412572/c0b71d99-236b-419f-85a4-c1872b63aaf3">

After that, a window with my notebooks comes up:
<img width="830" alt="image" src="https://github.com/googlecolab/colabtools/assets/67412572/51f6b39e-8cd2-4f3e-9900-f2c6180c4bd1">
 and I select the notebook, it starts to connect but defaults to the already prvided resources rather than a custom VM (RAM or T4, etc.):
 
<img width="1346" alt="image" src="https://github.com/googlecolab/colabtools/assets/67412572/6475055b-36be-4b34-98f9-ef62236f585f">

Then, I try another way.  I go to Custom GCP VM using project, zone and instance name:
<img width="478" alt="image" src="https://github.com/googlecolab/colabtools/assets/67412572/2207da80-3f86-4fb9-9356-0259ebc9fdc3">

and Colab tries to connect
[colab-3-vm](https://console.cloud.google.com/compute/instancesDetail/zones/us-central1-a/instances/colab-3-vm?hl=en&project=gleaming-city-374119)

The deployment is running:
<img width="1155" alt="image" src="https://github.com/googlecolab/colabtools/assets/67412572/b5644a54-7507-44dd-bf34-481e429378ec">

Colab notebook tries to connect:
<img width="550" alt="image" src="https://github.com/googlecolab/colabtools/assets/67412572/ce0bc7f2-2b1c-47c8-b000-dd3217720594">

but it fails to connect this way also and it says that the resource does not exist:
<img width="527" alt="image" src="https://github.com/googlecolab/colabtools/assets/67412572/a98fe4c8-fc53-47aa-b462-6951485eebaa">

**Describe the expected behavior**
I would expect to be able to use the custom GCP VM instance that was set up for Colab specifically

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - notebook link: https://colab.research.google.com/drive/1fL3y0pQoo0L7mqedcfVw10G8D9GcEZ7X?usp=sharing
 - I also wanted to get larger instances but they do not launch despite trying in several regions. Am I too low on quotas, I tried to request an increase but it keeps getting denied despite using a paid account. Here is an example
 
<img width="1155" alt="image" src="https://github.com/googlecolab/colabtools/assets/67412572/a55a57b6-0aac-4dc1-bf80-47207653f1c9">

**Comment by mariusz6100** [comment]
Solved the issue, the project name should be the the project ID not the project name, it would help to make that clear in the connection pop up box

**Comment by cperry-goog** [comment]
We'll update the title to say Project ID - we might be able to list projects someday. Closing this as solved though.
