### ISSUE TITLE
Calling exit() right after calling google.colab.files.download() will crash the session.

### ISSUE THREAD

**Issue by Epicminer256** [googlecolab/colabtools#4423]
**Describe the current behavior**
Calling a file download with `google.colab.files.download` and exiting right after will crash the session. It will not download the file either.

**Describe the expected behavior**
Was expecting to be able to download data before aborting/exiting the program.

**What web browser you are using**
Brave Browser.

**Additional context**
Here is a small code sample that triggers it.
```
from google.colab import files

f=open('users.txt', 'w')
f.write("test")
f.close()
files.download('users.txt')
exit() # <-- Adding this will crash the session
```

Users can just leave out the `exit()`, but

**Comment by colaboratory-team** [comment]
This is mostly expected. files.download is asynchronous, and it doesn't have a good way to know when the download completes, since that is handled by the browser. I would recommend just deleting your runtime when the file download ends, if your goal is to reduce VM usage as much as possible

**Comment by Epicminer256** [comment]
Yeah, its most expected and I can code around it (especially because using `exit()` is not the best practice). Gonna close because it is expected to happen.
