### ISSUE TITLE
не загружается

### ISSUE THREAD

**Issue by IrinaSHU** [googlecolab/colabtools#4425]
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver...

**Comment by mayankmalik-colab** [comment]
Can you confirm that you are using a GPU machine? if not, you can select a GPU machine by `Runtime` -> `Change runtime type` -> select a gpu accelerator

**Comment by IrinaSHU** [comment]
Значит зависит от скорости? Происходят большие помехи, это может повлиять на загрузку? Но, в таком случае, возникает вопрос, почему пишут о драйвере в видео, когда всё до этого момента загружалось, эта запись путает.

**Comment by cperry-goog** [comment]
`RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver` can be solved by following the steps above - you must have a GPU runtime to use NVIDIA drivers.
