### ISSUE TITLE
The TensorFlow contrib module will not be included in TensorFlow 2.0

### ISSUE THREAD

**Issue by naffan2014** [googlecolab/colabtools#443]
[first_steps_with_tensor_flow.ipynb](https://colab.research.google.com/notebooks/mlcc/first_steps_with_tensor_flow.ipynb?utm_source=mlcc&utm_campaign=colab-external&utm_medium=referral&utm_content=firststeps-colab&hl=zh-cn#scrollTo=ubhtW-NGU802)

```
# Use gradient descent as the optimizer for training the model.
my_optimizer=tf.train.GradientDescentOptimizer(learning_rate=0.0000001)
my_optimizer = tf.contrib.estimator.clip_gradients_by_norm(my_optimizer, 5.0)

# Configure the linear regression model with our feature columns and optimizer.
# Set a learning rate of 0.0000001 for Gradient Descent.
linear_regressor = tf.estimator.LinearRegressor(
    feature_columns=feature_columns,
    optimizer=my_optimizer
)
```
when run these code ,  tf will show error.

```

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.
```

how to fix this problem?

**Comment by letuantam96** [comment]
i am facing the same problem. anyone have a solution for this? :(

**Comment by qiamaiwa** [comment]
i am facing the same problem. anyone have a solution for this? :(

**Comment by craigcitro** [comment]
This is just a deprecation warning, not an actual error.

**Comment by CorazonG** [comment]
> This is just a deprecation warning, not an actual error.

But my code couldn't run after the warning emmm
