### ISSUE TITLE
regarding installation of tensorflow-gpu

### ISSUE THREAD

**Issue by sanjayshet08** [googlecolab/colabtools#4431]
i'm unable to install tensorflow-gpu. As soon as i run the following command which is: *!pip install tensorflow-gpu*.
im getting the following error:
Collecting tensorflow-gpu
  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

i ran all the commands that i knew and somewhere i read that we should install depedencies like CUDA cuDNN and while checking for CUDA version i ran the following command which is: *!nvcc --version* and the results i got is:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0

and while checking for cuDNN, i ran the following command:
!ls /usr/local/cuda/include/cudnn.h
the output i got was:
ls: cannot access '/usr/local/cuda/include/cudnn.h': No such file or directory
i have tried all the methods that i know so i kindly request to resolve this issue.

**Comment by mayankmalik-colab** [comment]
`tensorflow-gpu` has been discontinued and it is encouraged to use `tensorflow`, which ofcourse provide GPU support via CUDA.

For more details, check [this](https://pypi.org/project/tensorflow-gpu/).

Also, `tensorflow` is already pre-installed, so you don't need to install manually.
