### ISSUE TITLE
The fallback runtime version is unavailable at this time.

### ISSUE THREAD

**Issue by jjeroam** [googlecolab/colabtools#4432]
why when I tried to use fallback runtime version it always says that "The fallback runtime version is unavailable at this time.". Is it on maintenance or bug or what?

**Comment by mayankmalik-colab** [comment]
The fallback version is not available always. We enable it only when there is some possible breaking changes coming in, so that people can use the stable older runtime in case of any issue.

**Comment by jjeroam** [comment]
Thank you for answering but how can I install tflite-model-maker successfuly since they said that I need to change back to older version of phyton to make it work in google colab?

**Comment by mayankmalik-colab** [comment]
Unfortunately, changing the Python version is very tricky and is not recommended to do in Colab.
