### ISSUE TITLE
I loaded up my pro membership and purchased compute nodes on colab, but gpuram is not displayed on the gpu option in the resource option bar on the right.

### ISSUE THREAD

**Issue by jthwxxzyt** [googlecolab/colabtools#4437]
As I said above, although I reloaded the por member, purchased the compute node, and set the operation type to gpu run, the gpu run is not shown on the right side, and the gpu is not available.
![image](https://github.com/googlecolab/colabtools/assets/163423667/910f1c62-0396-49ec-be46-1bf7448a23e0)
![image](https://github.com/googlecolab/colabtools/assets/163423667/bf3ab213-e13f-4d84-966c-0acae5e6fd13)

**Comment by jthwxxzyt** [comment]
I found that it seems that only the ram of the display gpu has a problem, and it does not affect other operations.

**Comment by mayankmalik-colab** [comment]
We have made the fix and you should start seeing GPU ram by Friday morning.
