### ISSUE TITLE
Save authorization to drive & sheets across runs of same notebook owned and controlled by me.

### ISSUE THREAD

**Issue by davies-w** [googlecolab/colabtools#4440]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I start running one of my colabs for the Nth time this week, tab out, and then come back to find out it's been waiting for me to OK, my own colab, that I've run dozens of times before, to grant it access to my drive, and with not one, but three seperate Oauth screens.

**Describe the solution you'd like**
Offer the chance to save authorization for drive & sheets for *ME* running my *OWN* colab, assuming that I am the only editor allowed.

**Describe alternatives you've considered**
Running Jupyter and stop using Gdrive and Colab.

**Additional context**
Add any other context, screenshots or notebooks about the feature request here.

**Comment by cperry-goog** [comment]
It *should* be the case that your own owned and authored notebooks don't require this OAuth flow - can you create a blank new notebook and try this? These checks are in place to address potential abuse as users granting Drive creds to unsavory actors is really bad.
