### ISSUE TITLE
I can't select the A100 gpu. I want it. Please provide it. You guys are always care about money, the colab pro is not worthy without the A100. Please give me

### ISSUE THREAD

**Issue by abhinav-pm** [googlecolab/colabtools#4442]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
I'd love nothing more than to give you A100s - we can't procure any more capacity from GCP due to system-wide demand. Sorry, I continue to work on this. We're adding L4s soon with a bigger memory footprint which I think will help.
