### ISSUE TITLE
A100 not available

### ISSUE THREAD

**Issue by Josekomodo** [googlecolab/colabtools#4445]
**Describe the current behavior**
It is impossible to connect to the A100 GPU. I have tried for 3 days now

**Describe the expected behavior**
A100 GPU should connect

**What web browser you are using**
Chrome

**Additional context**
None

**Comment by cperry-goog** [comment]
A100s are in high demand, and we're unable to secure more from GCP (I've tried many times). We're introducing L4s soon to help improve our machine footprint.
