### ISSUE TITLE
Cannot display images hosted on my Google Drive in my Colab notebooks

### ISSUE THREAD

**Issue by nick-secur** [googlecolab/colabtools#4447]
**Describe the current behavior**

I am a *Colab Jupyter Notebook user*. As such, I need to display images that I've created and uploaded to Google Drive in my notebooks. I have researched and followed instructions to do so using the following procedure:

1. Upload image to Google Drive,
2. Make the image publicly viewable
3. Obtain a sharable URL
4. use markdown syntax to display the image in a markdown cell in the notebook. For example:
```
![INSERT IMAGE](https:/sharable_url)
```

**Describe the expected behavior**
The image should display inline in my Jupyter Notebooks

**What web browser you are using**
Chrome

**Additional context**

The following URL links to [my minimal, public, self-contained notebook that reproduces this issue...](https://colab.research.google.com/drive/1ScqHlC_ENxZ_5cmihc3xqFX0x0TzmifG?usp=sharing)

https://colab.research.google.com/drive/1ScqHlC_ENxZ_5cmihc3xqFX0x0TzmifG?usp=sharing

**Comment by EvanWiederspan** [comment]
I don't think we can make it work with that specific link; Drive restricts how that link can be used to show the image. You'll need to change the URL you're using, the guide here worked for me, https://www.intodeeplearning.com/embedding-images-in-google-drive-to-markdown/

**Comment by nick-secur** [comment]
Wow, thank you for your speedy attention to the issue. I've been hunting for an answer to this for days now but didn't come across the resource you provided. I updated the minimal notbook with the recommended URL and it seems to be a viable workaround (though it seems to me that Drive ought to provide links that can be embedded out of the box). I'll summarize the solution here in case others faced with the same problem discover this issue.

### Solution

#### To link to an image hosted on Google Drive from Google Colab:

1. Make sure the image is made publically accessable.

2. Obtain a sharable link (which will encode the image ID):
```
https://drive.google.com/file/d/<IMAGE_ID_HASH>/view?usp=sharing
```
3. Embed the image id in a url of the following form:
```
https://drive.google.com/uc?id=<IMAGE_ID_HASH>
```
