### ISSUE TITLE
numpy has no expand_dims

### ISSUE THREAD

**Issue by chennanli** [googlecolab/colabtools#445]
AttributeErrorTraceback (most recent call last)
<ipython-input-11-5877644b6e9e> in <module>()
      2 x = np.random.random(10)
      3 #help(np.expand_dims)
----> 4 x = x.expand_dims(10,0)

AttributeError: 'numpy.ndarray' object has no attribute 'expand_dims'

i think this is available in desktop Jupyter notebook, right?

**Comment by craigcitro** [comment]
You want `np.expand_dims` on the right, not `x.expand_dims`.
