### ISSUE TITLE
collab pro won't allow High-RAM

### ISSUE THREAD

**Issue by zstankow** [googlecolab/colabtools#4450]
**Describe the current behavior**
I subscribed to collab pro. I choose Change Runtime -> High-RAM. The runtime shows 'Connecting...' and then returns to the default RAM (only 12.7 GB). Yesterday it was working normally. 

**Describe the expected behavior**
I should have 51 GB of RAM as part of collab pro after selecting High-RAM

**What web browser you are using**
Chrome

**Additional context**
I am unable to run any of my models without being able to use High-RAM option. My subscription to collab pro is ACTIVE. Yesterday I was able to use High-RAM until last night, when it randomly disconnected and reconnected to the default options. When I click 'Change runtime', it shows that High-RAM is turned ON, but then when I click save, it returns to the default and shows that only 12.7 GB is available.

**Comment by cperry-goog** [comment]
We sometimes stock out of high-RAM, if you still encounter this, please file feedback in product and reference this issue and we can take a look. Sorry. Working on increasing our footprint right now.
