### ISSUE TITLE
No swapped file

### ISSUE THREAD

**Issue by DZone1** [googlecolab/colabtools#4455]
**Describe the current behavior**
There is no swapped file for me to download after the process is finished.

**Describe the expected behavior**
A swapped file should appear after the process finishes.

**What web browser you are using**
Chrome

**Comment by FabioOtake** [comment]
i had the same problem!

**Comment by DZone1** [comment]
> i had the same problem!

did you find a fix for it because i'm still having the problem and can't make videos

**Comment by leadbit1** [comment]
i have same problem

**Comment by cperry-goog** [comment]
Please post a minimal reproducible notebook with your issue; this does not contain enough information to help.

**Comment by windsweaver** [comment]
The same issue

**Comment by DZone1** [comment]
> Please post a minimal reproducible notebook with your issue; this does not contain enough information to help.

how do I do that? the only thing I know how to do is run the files so I don't know how to post that

**Comment by cperry-goog** [comment]
How are you running the files?

**Comment by DZone1** [comment]
I insert them into the files section on the left then copy and paste them in place of the code they have to replace. Replace /content/NSF.mp4 with the video file first then replace /content/AS.jpg with the face image then run. 
![Screenshot (8)](https://github.com/googlecolab/colabtools/assets/164454437/eb73cdd2-a170-4d5f-ac5b-366e030c5349)

**Comment by DZone1** [comment]
Usually it finishes everything with "Processing to video succeed!" at the bottom of everything but lately it doesn't show that anymore. Everything stops at the top 100% progress mark and it still doesn't give me the "swapped" file like normally. I've restarted the notebook multiple times but still have the same issue. 
![Uploading Screenshot (9).png…]()

**Comment by DZone1** [comment]
> How are you running the files?

Usually it finishes everything with "Processing to video succeed!" at the bottom of everything but lately it doesn't show that anymore. Everything stops at the top 100% progress mark and it still doesn't give me the "swapped" file like normally. I've restarted the notebook multiple times but still have the same issue.
![Screenshot (9)](https://github.com/googlecolab/colabtools/assets/164454437/8adbf2df-f695-4cd6-a17e-f9116264793b)

**Comment by DZone1** [comment]
> What is the link to the notebook?

https://colab.research.google.com/drive/1o2LG8e_kg174vPjI_OQ9Xs1r8U4BSk-w#scrollTo=D3L8Lkyj-5gl

**Comment by DZone1** [comment]
That's it. It doesn't have the problem because I bookmarked it before the problem started but I would usually start from there and just add new video and face image files into the code and run everything from the top starting from Clone Roop

**Comment by cperry-goog** [comment]
This appears to be issues with a notebook generating deepfakes - generating deepfakes is not permitted in Colab per our terms, so closing this.

**Comment by yew-hub** [comment]
any solution to solve this problem too?
