### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by colessa** [googlecolab/colabtools#4458]
Hello! I'm using Google Chrome and I'm having a problem, when I use colab IA ( GFPGAN Inference Demo, GFPGAN - Towards Real-World Blind Face Restoration with Generative Facial Prior) to restore face photos, it gives an error in part 3, ´´inference``:
 File "/usr/local/lib/python3.10/dist-packages/basicsr/data/degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'
ls: cannot access 'results/cmp': No such file or directory

**Comment by cperry-goog** [comment]
Please reach out to the notebook author for this type of error - it looks like the correct version of a dependency may not have been installed in the notebook.

**Comment by bigeye-studios** [comment]
I have the exact same issue and am not clear where or how to resolve this???

**Comment by colessa** [comment]
I also have no knowledge about it, I used it a few months ago to restore photo images but suddenly I can't do it anymore, I get this error and I don't know what to do
