### ISSUE TITLE
Notebook loading error

### ISSUE THREAD

**Issue by Ali-Abdelkhalek** [googlecolab/colabtools#446]
While trying to create or load any notebook from drive, the following error appears:
Notebook loading error
There was an error loading this notebook. Ensure that the file is accessible and try again.
Could not fetch resource at https://00e9e64bacc6587341ef2858bc5f18102b0fe76663f1f997a2-apidata.googleusercontent.com/download/drive/v2beta/files/1chPiBTZAK5unSYiUAXj33s7JPI70XU8x?qk=AD5uMEueg7kfKtDsyQe18BavqOV44ZOB0XApxqH-sqRrvpDboBHEWDIDvfVZUyEWPq4vdar1RkJ6OqfnS7kBwE_Yhq5ImkrrbR_03VI3L9IxWW5RTMspVD6Fa4QtTuyxzyYKfUTsvMNLJXBbIofV8xykKJeJbFpEyuYjdGDcgKkmGjVS8TvB8O7tqyMF03lrhkSlxWZpHxMbeS0WkBNMhrfDRB0AmcuEbpiqJK5IsaeiWEoy_2ovGRrzctj6R1O8kvDmzKy2BxIMomDKqTtNWobvxR18Xc7ykmIbWZG0E21ZBYeb8EklSvWYKuPodnUXDPdYaSF2SCs8_1e4I09lYop5kHzKK03JkCgVN0cgQUyjzOOVmDAIeBZXClgmrYTQ8SCxDQDEEaqVD-Hf_GRbYXGAcPzAAIPykVAGiOii7KAE1NjRXzTfPVNfpTacmvdnZXDh_EnXOqxqWVSOGvoNrB7FC6RqwY4B_27zptQNuATiAvBN18NzpkfwzCJdNRE9GGZpPo3snURh6hL3YJ4QWtknZIqSzHxPIwPEPzc2ST8ptureoRS3P0_oYjcvsrRPSV0smrDscZ2OaLggtgDu9UHphzm-KMAGXW2CO1Y6YWcelNPU7vgrfSnyMVrsbBp3OdHISqoARgeFWK8dPYZ9mCI5VRrrPSNikrnK0F2myd3WzdOix4GqxIBQ6dfIt6z1Af20yBylp4hQ3UTU-Ov4D5zWGkCNlcOqMIv8JqOq35Yqik5FrTvWKy3AOWWIOIgdDlwY3NyfeA4yTn5v5h0DUvfJBylBTrfLYw: 403 The download quota for this file has been exceeded.

I tried to access my drive with google colab from another account. It creates notebooks  but another error happens when i try to read data from my drive:
Input/output error

i think the problem is with my drive but i can't solve.

any help?

**Comment by blois** [comment]
Does the above issue occur for all Drive notebook loads, or just that file?

The error when reading data from Drive- how are you reading the data?

**Comment by Ali-Abdelkhalek** [comment]
the notebook problem doesn't happen any more. it looks like my driver was stuck for a while or something like however it still can't read files. I'm trying to read a tar file using tarfile.open. This has been for about 7 hours.

**Comment by Ali-Abdelkhalek** [comment]
surprisingly, every thing is working well now. just waited for a while and the problem no longer exists.
thank you for your reply @blois

**Comment by Ali-Abdelkhalek** [comment]
surprisingly, everything is working well now. I just waited for a while and the problem no longer exists.
thank you for your reply @blois

**Comment by easybeinggreen** [comment]
I am having a similar problem, unable to open new python notebook in colab, unable to open any files from gdrive (I have mounted and gdrive visible). I have tried disabling popups, adblocker, using incognito and nothing will work. I can, however, access the colab welcoming documents and notebooks in github. This has left colab unusable for me so any advice would be very welcome. Using chrome browser. The following error message

Notebook loading error
There was an error loading this notebook. Ensure that the file is accessible and try again.
Failed to fetch

https://drive.google.com/drive/?action=locate&id=1cofhWOS7AEea5sdrO9w0Zhsz-OIA3jgV&authuser=0
Failed to fetch
TypeError: Failed to fetch

**Comment by blois** [comment]
@easybeinggreen - Are there additional details in the error dialog? Do you happen to know if there are additional errors in the Chrome developer console?

**Comment by easybeinggreen** [comment]
Hi when I  try to open a new notebook or a pre-existing I get the following error, no more details. Clicking on the link takes me to the Colab Notebooks file in Google drive - where it should be:

Sorry, no detailed knowledge of Chrome developer console but when I open developer tools panel, no obvious errors

Notebook loading error
There was an error loading this notebook. Ensure that the file is accessible and try again.
Failed to fetch

https://drive.google.com/drive/?action=locate&id=1qlNjp6FXK7xC0CxVHb17PrAyYTG_I0jx&authuser=0
Failed to fetch
TypeError: Failed to fetch

Is it possilbe that there might be some issue with my ISP, I have run out of ideas since I can open it in some locations and not others?

Many thanks

**Comment by blois** [comment]
From Chrome devtools, if you open the 'Network' tab then reload the page I would expect to see some items appear in red indicating that they failed. 

For the items that failed, I'd be curious about the name being requested and the status. From what you're describing and the error message this seems like the error is either originating from your browser or your network. Possibly try a different browser such as Firefox?

**Comment by easybeinggreen** [comment]
Thanks again @blois , so iI did as you suggested, it does indeed show up in red as follows

name: https://00e9e64bac7450b25e3fd9b0cf8027dca61846f464b75aba89-apidata.googleusercontent.com/download/drive/v2beta/files/1K9L1NqxDRt4JfuRQ2NZ1QxQqy9_BgDYBqmRlVIiWhXAweE167LU?qk=AD5uMEtEdpjQKh_6KF8Lkr1uxrqr-MFwOF6dNgIcK9Qzs_TEZyRqdRk_kjVRr5JX4pG1xIXBMgIPDuUkdsQsXLdgbEJ0qg4LuN6eDgUXp3Rf8egbXGG_aOqFzmi0Hu_jZGFVlfxVoLKJ6d6gH834SjfrORMWfi4q5fh-iF43uvWRMq9rjWUu7sUC6K7EH8gL7NH8PIPxkMGamRAZ0LBBm_gCYOSNBkeqy6gI4Wqz6_OYM-k9NkTFCKVW2kjALq_cTsBJ9ko350FlnoeKi8MUUkibOExJ16W25AjVKn1nuxxFzxBcrmrkUXST9LC1A8Ab3K7SW3i9RPSCDPk0I5C9qibVXOwdxYlfF3Cki855sl3KZBjrQE5kBRe-Lo0D0z0LlmiswYejc-qO_eGvTT0q_FPuXNNUnip5Otoo0ObHOxctKmS0Fi1O2A2nrz8C8WUMfyxfjEv8a_KN42ecQ3s4KvRvRmNcMhcudTjgRxCpnnq_fYv_pc7NHwkfvjSMKGBWbZ4N1gQZ4BGhL6WpJHaGYd2hxZp8Vvt0MTGd0VYNAOrFJE7Bv2JL7BomnYh9SFeGSrp7g6XEIA8OveOvKrDOyp-cIv9glQQifi_OyDR00Ljj8uuAld3vnp-x-OqqotC5E5JWfx_Ehx65Z1n4xtgVIH3C0XoOErdRJh_mgFFB859N6BySSTzT3Wh75AJefr1zqEbu2SROBQteFa2LN-vgxX9fyXdPxghC5TPih7ir0sLadT4smL0UDGEfiIU7w6HXMCtDJaAJwb6Q62fO1IkhEAHydNmT-nzmHbEPOJO8w8iKqar3Sbl-P2w
status: failed
type: fetch
initiator: https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20190426-085300-RC00_245428438

I then tried on Firefox and got a similar but different error: Network wrror this time, looking at the network in developer tools the same codes were appearing

Notebook loading error
There was an error loading this notebook. Ensure that the file is accessible and try again.

NetworkError when attempting to fetch resource.
https://drive.google.com/drive/?action=locate&id=1PYvsyF3HDwUWz7WQf11YHft6MmHnGPrf&authuser=0

NetworkError when attempting to fetch resource.

Not sure what this all means, any further thoughts. Thanks so much for your input on this, very much appreciated

**Comment by blois** [comment]
Are you able to download the file from the file browser at https://drive.google.com?

I'm a little surprised that API is failing so reliably.

**Comment by easybeinggreen** [comment]
So yes, when I choose 'open a new python 3 notebook' in colab it does indeed create an untitled document in the colab notebooks folder in Google Drive. I am able to download and open that as a regular Jupyter notebook. But cannot open that or any other document in colab (unless it is through github, or a google created doc)

**Comment by easybeinggreen** [comment]
Actually, edit that, when I attempt to create a new python 3 document it does so but it does NOT create a new ipynb document and this cannot be downloaded and opened it just deserves file type as 'File' and will not open. THe image it creates has the 4 squares of windows 10 against a hard drive which I am unfamiliar with. It is only colab docs or previously created docs that can be downloaded. Sorry its not clearer
![image](https://user-images.githubusercontent.com/35714807/56981613-f5329280-6b87-11e9-8095-746495d36ad4.png)

**Comment by blois** [comment]
Do you happen to have another Google account to try with that?

**Comment by easybeinggreen** [comment]
Apologies for the delayed reply, I have been investigating the problem further and my Internet Service Provider has advised there is a fault with my modem. They did not say what that was and in over 12 months I have had no other internet issues until this one. They have replaced modem and new and old notebooks now open fine. I remain baffled but hopefully this may help others if the problem arises again. Many thanks @blois for your assistance.

**Comment by blois** [comment]
I am baffled by that resolution as well, but thanks for letting us know!

**Comment by betty35** [comment]
Wow, this actually worked. But I guess I'm a bit luckier? Restart the modem, and that's all it took to get everything working again. 

And some other symptoms if it is your modem's fault: 

- Can open text files in google drive.
- Not able to download anything from google drive (get an error page that says doc-<something>-<some number>-docs.googleusercontent.com took too long to respond.).
- Change a browser, not working. 
- Plug in a network cable, not working.
- Cannot open the file in colab with smart phone and its browser with WIFI.
- Switch to 3G/4G, can open the file with smart phone and its browser in colab.

**Comment by trombitasgeza** [comment]
I tried to colorize video segmentd with videocolorizeColab.ipynb as I did it quite a several times with succes, but now I could start downloading from google drive video files if I made a copy of them. The copy's started to download and the colorization ptocess finished. But after it finished came the message: 

Download failed
Could not fetch resource at https://colab.research.google.com/tun/m/gpu-p100-s-1nsim9mlahjyh/files/content/DeOldify/video/result/video.mp4?authuser=5: 504 
FetchError: Could not fetch resource at https://colab.research.google.com/tun/m/gpu-p100-s-1nsim9mlahjyh/files/content/DeOldify/video/result/video.mp4?authuser=5: 504 
    at Lz.Kz [as constructor] (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20191219-082400-RC00_286397102:911:76)
    at new Lz (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20191219-082400-RC00_286397102:911:293)
    at ya.program_ (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20191219-082400-RC00_286397102:4031:357)
    at Aa (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20191219-082400-RC00_286397102:17:336)
    at ya.next_ (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20191219-082400-RC00_286397102:15:474)
    at Ca.next (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20191219-082400-RC00_286397102:18:206)
    at b (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20191219-082400-RC00_286397102:27:43)

The whole session lost. I tried it with several google accounts,but the same happened with all of them. Should I be worried, or it's just a temporal problem with google collab?

**Comment by bhavuk0909** [comment]
I tried to run (https://github.com/keithito/tacotron/blob/master/demo_server.py) but it shows following error : 
**Unexpected token i in JSON at position 0
SyntaxError: Unexpected token i in JSON at position 0
    at JSON.parse (<anonymous>)
    at Ba.program_ (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200116-082400-RC00_290071694:1613:377)
    at Da (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200116-082400-RC00_290071694:17:336)
    at Ba.next_ (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200116-082400-RC00_290071694:15:474)
    at Fa.next (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200116-082400-RC00_290071694:18:206)
    at b (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200116-082400-RC00_290071694:26:268)**

Why is it showing this error?

**Comment by ZHANGWEILIN1** [comment]
Could not fetch resource at https://colab.research.google.com/tun/m/gpu-p100-hm-28z2bk5mw3x5g/files/content/drive/My%20Drive/OneDrive_b/UnLiteFlowNet-PIV/src/train/train_functions.py?authuser=0: 504 
FetchError: Could not fetch resource at https://colab.research.google.com/tun/m/gpu-p100-hm-28z2bk5mw3x5g/files/content/drive/My%20Drive/OneDrive_b/UnLiteFlowNet-PIV/src/train/train_functions.py?authuser=0: 504 
    at mv.lv [as constructor] (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20200721-085603-RC00_322362549:719:741)
    at new mv (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20200721-085603-RC00_322362549:719:958)
    at Ca.program_ (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20200721-085603-RC00_322362549:4192:357)
    at Ea (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20200721-085603-RC00_322362549:19:336)
    at Ca.next_ (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20200721-085603-RC00_322362549:17:474)
    at Ga.next (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20200721-085603-RC00_322362549:20:206)
    at b (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__zh_cn.js?vrz=colab-20200721-085603-RC00_322362549:20:466)

i can not get the files in google drive and can not download it. This problem confusing me for one day. could you give me some advice to solve this problem ?

**Comment by tooHotSpot** [comment]
Consider just downloading the file with permanent link and gdown preinstalled like [here](https://stackoverflow.com/questions/48735600/file-download-from-google-drive-to-colaboratory)

**Comment by dragonshill** [comment]
Hi there,

Notebook loading error -

try restarting your browser.

I get this every now and then.  I don't know what triggers it, but once it starts it gets stuck, and won't open any file at all.   Closing the Colab tab doesn't change it, but restarting Firefox works.
