### ISSUE TITLE
Can we bump the duckdb version to 0.10.1?

### ISSUE THREAD

**Issue by guenp** [googlecolab/colabtools#4466]
**Is your feature request related to a problem? Please describe.**
Right now, `duckdb` is installed by default, but fixed to version 0.9.2. A new version 0.10.1 just came out, and databases created with newer versions of DuckDB are no longer readable by 0.9.2. However, 0.10.x should be backward compatible with reading databases created with 0.9.x.

**Describe the solution you'd like**
It would be great if Colab could install the latest version, 0.10.1

**Describe alternatives you've considered**
We could run `pip install --upgrade duckdb` at the start of the notebook.

**Additional context**
Related issue: https://github.com/googlecolab/colabtools/issues/3570
DuckDB releases: https://github.com/duckdb/duckdb/releases

**Comment by cperry-goog** [comment]
We are doing this now.

**Comment by EvanWiederspan** [comment]
Upgrade is done!
