### ISSUE TITLE
collab section isnt working it run on my computer for while and then all the sudden when tried to run it again is asking for Nvidia driver which i had updated for the purpose of use of foocus i dont know what else to do 

### ISSUE THREAD

**Issue by Dary5143** [googlecolab/colabtools#4467]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
You'll need to ensure you've set the runtime type to GPU in order to have access to NVIDIA drivers.
