### ISSUE TITLE
Ada yang bisa bantu saya 

### ISSUE THREAD

**Issue by d1d1ts** [googlecolab/colabtools#4468]
Kenapa accunt coleb saya bisa di bekukan padahal saya pengen mencoba mining verus dengan vasilitas CPU google colab saya 
 berikut masalahnya 
![Accunt colab saya di bekukan](https://github.com/googlecolab/colabtools/assets/86543323/988b8875-c4a5-4894-b9a7-9eb23fca45cc)

teman teman yang alamin mohon solusinya

**Comment by cperry-goog** [comment]
Cryptocurrency mining is against our terms of service, we will ban accounts who attempt to mine.
