### ISSUE TITLE
Lost code from 3 days ago

### ISSUE THREAD

**Issue by Jinjingggg** [googlecolab/colabtools#4477]
**Describe the current behavior**
3 days of code disappered from the notebook. Revision history shows no revisions since 3 days ago but google drive shows activity logged from today at 5pm

**Describe the expected behavior**
The code should not disappear. Wifi and connectivity had no issues.

**What web browser you are using**
Using Chrome

**Comment by Tttthea** [comment]
Same issue here. Have u got the codes back?

**Comment by cperry-goog** [comment]
There are sporadic drive issues that may cause this, we give warnings in the UI if we get out of sync. We have some ongoing work to make this less likely.
