### ISSUE TITLE
Couldn't even complete first step

### ISSUE THREAD

**Issue by judhistir88** [googlecolab/colabtools#4478]
Collecting youtube_dl
  Downloading youtube_dl-2021.12.17-py2.py3-none-any.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 19.8 MB/s eta 0:00:00
Installing collected packages: youtube_dl
Successfully installed youtube_dl-2021.12.17
Collecting ffmpeg
  Downloading ffmpeg-1.4.tar.gz (5.1 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: ffmpeg
  Building wheel for ffmpeg (setup.py) ... done
  Created wheel for ffmpeg: filename=ffmpeg-1.4-py3-none-any.whl size=6082 sha256=5a10365bda772baca021d1c626eba23367acbf904bba66085de6729106d5af1d
  Stored in directory: /root/.cache/pip/wheels/8e/7a/69/cd6aeb83b126a7f04cbe7c9d929028dc52a6e7d525ff56003a
Successfully built ffmpeg
Installing collected packages: ffmpeg
Successfully installed ffmpeg-1.4
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-1-2d8c3cbbfd43>](https://localhost:8080/#) in <cell line: 17>()
     15 get_ipython().run_line_magic('matplotlib', 'inline')
     16 
---> 17 get_ipython().run_line_magic('tensorflow_version', '1.x')
     18 get_ipython().system('git clone  https://github.com/TachibanaYoshino/AnimeGAN.git')
     19 get_ipython().run_line_magic('cd', 'AnimeGAN')

1 frames
[/usr/local/lib/python3.10/dist-packages/google/colab/_tensorflow_magics.py](https://localhost:8080/#) in _tensorflow_version(line)
     33 
     34   if line.startswith("1"):
---> 35     raise ValueError(
     36         # pylint: disable=line-too-long
     37         textwrap.dedent(

ValueError: Tensorflow 1 is unsupported in Colab.

Your notebook should be updated to use Tensorflow 2.
See the guide at https://www.tensorflow.org/guide/migrate#migrate-from-tensorflow-1x-to-tensorflow-2.

**Comment by cperry-goog** [comment]
Tensorflow 1 is unsupported in Colab; we've upgraded to 2.15. You'll need to update your code.

**Comment by judhistir88** [comment]
Microsoft Windows [Version 10.0.22631.3374]
(c) Microsoft Corporation. All rights reserved.

C:\Users\judhi>git clone --recursive git@github.com:gustavorayo/video-to-cartoon.git
Cloning into 'video-to-cartoon'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

How to solve this?
