### ISSUE TITLE
Colab connected to custom VM  stops when idle for some time 

### ISSUE THREAD

**Issue by dis-is-pj** [googlecolab/colabtools#4480]
**Describe the current behavior**
I've created the VM from Colab Marketplace on GCP and connected it to several notebooks. My notebooks sometimes get idle (it's in the time.sleep()). But it automatically shuts down that thread whenever it goes idle for a little more time. 

**Describe the expected behavior**
I opted for the paid VM and colab so that it doesn't stop and keep running. Colab is convenient since I can literally run these notebooks from my mobile (making some change in parameters). I don't want my colab to stop even if it's idle for long time. How to disable this setting?

**What web browser you are using**
Chrome

**Additional context**
I'm running some algo trading code that keeps checking the status of my order in a few minutes (I wait by using time.sleep()) by making a few api calls, but it doesn't consume CPU most of the time. But it's important for me to continue the process.

**Comment by mayankmalik-colab** [comment]
I couldn't repro it. I tried to do `time.sleep(3600)` and it never got diconnected. Perhaps, there might be something else in your notebook that did the dosconnect. Is it still a problem ?
