### ISSUE TITLE
TPU Node to TPU VM Migration

### ISSUE THREAD

**Issue by sagelywizard** [googlecolab/colabtools#4481]
We recently released TPU VM accelerators for Colab (backed by TPU v2-8)! This deprecates the legacy TPU Node accelerators (see [this documentation](https://cloud.google.com/tpu/docs/system-architecture-tpu-vm#tpu-arch) for the technical details). This improves usability, reliability, and debuggability, as well as enables support for modern JAX on TPU! Between April and June 2024, we'll begin migrating existing legacy TPU notebooks to modern TPU VM machines. This may require some action from Colab TPU notebook owners.

## Limited capacity

As with legacy TPUs, we have limited free tier capacity. Use of "TPU v2" accelerators is subject to availability.

## Migration plan

We'll gradually switch legacy TPU notebooks to be backed by TPU VM runtimes. No user action is required to initiate the migration, but some action may be required to update legacy TPU notebooks.

As we migrate legacy TPU notebooks, we'll update this Github ticket with the current migration status.

You can also manually migrate your legacy TPU notebooks by changing the accelerator type from "TPU (deprecated)" to "TPU v2".

#### Default installed packages

TPU v2 runtimes have different packages installed by default than our other runtimes. The set of packages installed on the TPU v2 runtime is smaller and focused on deep learning/AI applications. We've verified that the most commonly installed packages will still be included in the new TPU v2 runtime, but some uncommon packages may be removed. You may need to manually install these packages using `pip install`, e.g.:

```bash
!pip install <my-uncommon-package>
```

#### JAX will undergo a significant upgrade

JAX will undergo a very significant upgrade, i.e. (0.3.25 to 0.4.x). There may be some API changes during this upgrade. You can manually downgrade to the previous version using `pip install`, i.e.

```bash
!pip install 'jax[tpu]==0.3.25' -f https://storage.googleapis.com/jax-releases/libtpu_releases.html -f https://storage.googleapis.com/jax-releases/jax_releases.html
```

#### Tensorflow TPU Initialization Changes Slightly

The arguments for TPU instantiation in Tensorflow change slightly, now that TPU v2 notebooks will connect to a local TPU.

You can direct Tensorflow to connect to the local runtime by setting `tpu="local"` for `TPUClusterResolver`. For example:

```python
tf.contrib.cluster_resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
```

Changes to:

```python
tf.contrib.cluster_resolver.TPUClusterResolver(tpu='local')
```

**Comment by Ryukijano** [comment]
Are there going to be support for tpu 3-8 vms in the future? Also does this mean the tpu v1 accelerators are not available at all in collab?

**Comment by sagelywizard** [comment]
@Ryukijano Nothing to announce as far as new accelerators. As far as the old accelerators: yes, the `TPU (deprecated)` runtimes will no longer be available in the coming weeks. (A technical note: `TPU (deprecated)` was backed by v2-8 too, but they used the old-style TPU Node architecture. `TPU v2` uses the same v2-8 accelerator, but it uses the new-style TPU VM architecture. They were not backed by TPU v1 chips.)

**Comment by shakthiman** [comment]
Will the TPU VM machines support TF v2.16.1?

**Comment by JersonGB22** [comment]
@sagelywizard I've been trying to use the 'TPU v2' on Colab for several days, but I keep getting the following message:
Failed to assign a backend
There are no TPUs available. Would you like to use a runtime without an accelerator?

**Comment by sagelywizard** [comment]
@JersonGB22 TPU availability is subject to our available resource capacity, which varies throughout the day. However, Pro and Pro+ subscribers get priority access. Subscribe to Pro or Pro+ if you'd like more consistent access to TPU runtimes.

**Comment by sagelywizard** [comment]
Migration status update: We're in the process of disabling the creation of new `TPU (deprecated)` notebooks. In the coming weeks, we'll migrate the remaining legacy `TPU (deprecated)` notebooks to `TPU v2` runtimes.

**Comment by BenKlee** [comment]
Is this only supported on `tensorflow>=2.15.0`? I am using 2.13.0 (and tested 2.14.0) and changing to `TPUClusterResolver(tpu='local')` results in the resolver not recognizing any TPUs (`resolver.num_accelerators()['TPU'] == 0`)

**Comment by h4ck4l1** [comment]
How do I upgrade tensorflow to 2.16 on tpu? my code is tested on local cpu 64gb i9 cpu. I get some errors which take me to previous keras versions.

**Comment by sagelywizard** [comment]
@BenKlee We don't explicitly support tensorflow 2.13.x, though it may work. It's possible you're not installing tensorflow correctly.

**Comment by sagelywizard** [comment]
@Emrhdgr Are you sure you're connected to a TPU runtime? Please file a separate Github issue.

**Comment by agbruno-git** [comment]
> @sagelywizard I've been trying to use the 'TPU v2' on Colab for several days, but I keep getting the following message: `Failed to assign a backend There are no TPUs available. Would you like to use a runtime without an accelerator?`

I am having the same message.

**Comment by sagelywizard** [comment]
Hi @agbruno-git! That means there were no TPUs available at that time. GPU and TPU notebooks are subject to availability. Colab Pro and Pro+ subscribers get priority access to accelerators, so you can subscribe if you'd like more reliable access to accelerators such as TPUs.

**Comment by sagelywizard** [comment]
Hi folks! The TPU Node to TPU VM migration has completed, so we're closing out this ticket. If you have any new issues with TPUs, please file a new issue in Github or send feedback in the Colab UI (in the Help dropdown menu, under "Help > Send feedback").
