### ISSUE TITLE
In Google colab correct python code is throwing an error

### ISSUE THREAD

**Issue by yoganandpaluru** [googlecolab/colabtools#4483]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by yoganandpaluru** [comment]
**This is the python code**

arr = [12, 3, 4, 15]
ans = sum(arr)
print('Sum of the array is ', and)

**This code is throwing the following error**

TypeError                                 Traceback (most recent call last)
[<ipython-input-19-1752674c5d09>](https://localhost:8080/#) in <cell line: 3>()
      1 arr = [12, 3, 4, 15]
      2 
----> 3 ans = sum(arr)
      4 
      5 print('Sum of the array is ', ans)

TypeError: 'int' object is not callable

**Comment by katlyn-edwards** [comment]
This isn't a bug in colab. It sounds like you have a variable name `sum` somewhere else in your code.
