### ISSUE TITLE
Syntax highlighting unavailable when using %%writefile filename.py

### ISSUE THREAD

**Issue by kundetiA** [googlecolab/colabtools#4485]
while creating python scripts in google colab using %%writefile filename.py, there is no syntax highlighting for the rest of the code.
It world be very useful if syntax highlighting feature available.

**Comment by EvanWiederspan** [comment]
Tracking internally as b/333895664

**Comment by cperry-goog** [comment]
this is fixed, thanks for the report.

**Comment by kundetiA** [comment]
Thankyou!!
