### ISSUE TITLE
custom_widget on local runtime

### ISSUE THREAD

**Issue by MehmetTopsakal** [googlecolab/colabtools#4487]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

```
%matplotlib widget
import matplotlib.pyplot as plt
plt.figure()
```
 on "local runtime" is complaining and want me to do

```
from google.colab import output
output.enable_custom_widget_manager()
```

But I am on local environment. I have an old Linux OS (CentOS Stream 8) and 
I cannot install google-colab
```
!pip install google-colab
```

**Describe the expected behavior**
```
from google.colab import output
output.enable_custom_widget_manager()
```
shouldn't be needed on local environment

**What web browser you are using**
Chrome on Linux OS

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
What instructions are you following for connecting to the local runtime? https://research.google.com/colaboratory/local-runtimes.html has instructions including our docker image which should address this?

**Comment by mayankmalik-colab** [comment]
You would need to use option 1 from https://research.google.com/colaboratory/local-runtimes.html if you want to use google-colab package. We don't publish it on pypi anymore. So, you would get super old version if you do pip install it. I would recommend using option 1.
