### ISSUE TITLE
Google Cola x Python x Pynetlogo

### ISSUE THREAD

**Issue by Robhyson** [googlecolab/colabtools#4488]
I use a model in netlogo in version 6.3.0. I use the code below and I have never had an error, but on the Google Colab platform it is giving this error. Could anyone help me resolve this error?

Code:

![image](https://github.com/googlecolab/colabtools/assets/32375862/acd0c0fe-badc-4ad0-b4c7-b19c398b9d21)

Error:

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/_jpype.cpython-310-x86_64-linux-gnu.so in netLogoLink.NetLogoLink.loadModel()

Exception: Java Exception

The above exception was the direct cause of the following exception:

java.lang.NoSuchMethodError               Traceback (most recent call last)
2 frames
java.lang.NoSuchMethodError: java.lang.NoSuchMethodError: 'void org.objectweb.asm.MethodVisitor.visitMethodInsn(int, java.lang.String, java.lang.String, java.lang.String, boolean)'

During handling of the above exception, another exception occurred:

NetLogoException                          Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/pynetlogo/core.py in load_model(self, path)
    247         except jpype.JException as ex:
    248             print(ex.stacktrace())
--> 249             raise NetLogoException(str(ex))
    250 
    251     def kill_workspace(self):

NetLogoException: java.lang.NoSuchMethodError: 'void org.objectweb.asm.MethodVisitor.visitMethodInsn(int, java.lang.String, java.lang.String, java.lang.String, boolean)'

**Comment by EvanWiederspan** [comment]
It's not clear to me that this is a Colab issue specifically, I would reach out to the pynetlogo package maintainers instead
