### ISSUE TITLE
tortoise-tts notebook gives errors when installing packages

### ISSUE THREAD

**Issue by PacoH** [googlecolab/colabtools#4489]
I tried to install the packages and got the following error:

`ERROR: Could not build wheels for numba, llvmlite, which is required to install pyproject.toml-based projects`

Is there any way to fix this error or to get the notebook's creator to look into it?

Additional information:

Colab Notebook:

[clone-your-own-voice-tortoise-tts.ipynb - Colaboratory](https://colab.research.google.com/drive/1N8lXviiwfmrS9vYzuFdQnLHlddXMMMvU#scrollTo=vF1d-My9IXXt)

Repository:

[neonbjb/tortoise-tts: A multi-voice TTS system trained with an emphasis on quality](https://github.com/neonbjb/tortoise-tts)

```
AssertionError                            Traceback (most recent call last)
<ipython-input-3-98147deeb26d> in <cell line: 2>()
      1 # Generate speech
----> 2 voice_samples, conditioning_latents = load_voice(CUSTOM_VOICE_NAME)
      3 gen = tts.tts_with_preset(text, voice_samples=voice_samples, conditioning_latents=conditioning_latents, 
      4                           preset=preset)
      5 torchaudio.save(f'generated-{CUSTOM_VOICE_NAME}.wav', gen.squeeze(0).cpu(), 24000

/content/tortoise-tts/tortoise/utils/audio.py in load_voice(voice)
    104         conds = []
    105         for cond_path in paths:
--> 106             c = load_audio(cond_path, 22050)
    107             conds.append(c)
    108         return conds, None

/content/tortoise-tts/tortoise/utils/audio.py in load_audio(audiopath, sampling_rate)
     38             audio = audio[0]
     39         else:
---> 40             assert audio.shape[1] < 5
     41             audio = audio[:, 0]
     42 
```

Next steps: Explain error

Please explain the error:

AssertionError: 
Colab AI
Install the required module:

```
!pip install torchaudio
Use code with caution
Import the required modules:
 
import torchaudio
Use code with caution
Change the assertion:
 
assert audio.shape[1] <= 5
Use code with caution
Execute the code:
 
# Generate speech
voice_samples, conditioning_latents = load_voice(CUSTOM_VOICE_NAME)
gen = tts.tts_with_preset(text, voice_samples=voice_samples, conditioning_latents=conditioning_latents, 
                          preset=preset)
torchaudio.save(f'generated-{CUSTOM_VOICE_NAME}.wav', gen.squeeze(0).cpu(), 24000)
IPython.display.Audio(f'generated-{CUSTOM_VOICE_NAME}.wav')
Use code with caution
Sources
medium.com/mlearning-ai/voice-cloning-for-beginners-in-8-minutes-db046e009a70
Rate this answer
```

**Comment by mayankmalik-colab** [comment]
I can see tha numba version `0.48.0` requirement mentioned in the [requirements file](https://github.com/jnordberg/tortoise-tts/blob/main/requirements.txt) is very old and may not work on Colab. Also, you will have better luck reaching out to the notebook authors.

**Comment by PacoH** [comment]
I found that others had this problem in 'Issues' but got no reply. Is there any way I can edit the source code and include a later version?

**Comment by mayankmalik-colab** [comment]
I think you will have to work with [tortoise-tts](https://github.com/jnordberg/tortoise-tts) them on this.
