### ISSUE TITLE
problem with the new dark theme and latex equations

### ISSUE THREAD

**Issue by vincentvigon** [googlecolab/colabtools#449]
The latex equation are almost invisible when we use the dark theme.

**Comment by vincentvigon** [comment]
The latex equation are almost invisible when we use the dark theme.

**Comment by vincentvigon** [comment]
(sorry, it is not closed)

**Comment by metrizable** [comment]
Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem and service since then, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook/screencast.
