### ISSUE TITLE
All of my work of 10 days worth are gone and have become non-existent

### ISSUE THREAD

**Issue by cheskamo** [googlecolab/colabtools#4493]
I had been working on a colab notebook from March 26 until April 6. Everyday, I just "run all" my code, assuming it will just be there everyday -- the whole reason we use colab and other google drive applications (because it saves and records all history revisions). But, all of a sudden, I opened my notebook and all the work was gone apart from the three starting lines and when I look to the revisions, it said: "Last Update on March 26," which is just not true..... Yes, I'm looking at the same file. Yes, I tried opening it from my drive. Yes, I tried signing out and in again. Please tell me this is an easy fix.

**Comment by EvanWiederspan** [comment]
We won't be able to help from Github, can you file in-product feedback at Help -> Send Feedback and mention this issue?
