### ISSUE TITLE
gdrive inconsistency when used with pip install

### ISSUE THREAD

**Issue by dbwrangler** [googlecolab/colabtools#4495]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

I followed these steps in colab:

cell 1
from google.colab import drive
drive.mount("/content/drive")

2
!pip install virtualenv
!virtualenv /content/drive/MyDrive/venv_MASTER06042024

3
!source /content/drive/MyDrive/venv_MASTER06042024/bin/activate; pip install -U langchain==0.1.14 \
einops==0.6.1 \
accelerate==0.21.0

4
import sys
sys.path.append("/content/drive/MyDrive/venv_MASTER06042024/lib/python3.10/site-packages")

5
import einops

6
from accelerate import Accelerator

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

The above works. When I disconnect and delete the runtime and then restart, I expect cells 4-6 to work, however only 4 and 5 work, 6 gives error:
ImportError: cannot import name 'Accelerator' from 'accelerate' (unknown location) .

On closer inspection, before deleting the kernel, the chrome gdrive browser and colab file browser both show a directory for einops with contents. For accelerator only colab file browser shows contents but gdrive browser shows directory called accelerator with no contents. The path is: /content/drive/MyDrive/venv_MASTER06042024/lib/python3.10/site-packages

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

minimum public notebook to replicate issue
https://colab.research.google.com/drive/1BTsrBCyIg4iU5CqCnZJsRn9tPmVMRVYi?usp=sharing

**Comment by wwwillchen** [comment]
Is there a particular reason you're using `virtualenv`? You could try directly pip installing the packages that you need, i.e. `!pip install -U langchain==0.1.14`

Typically virtualenv is used for a local development environment when you have multiple projects with different dependency requirements but because Colab provides its own isolated Python environment there's less need to use virtualenv.

**Comment by dbwrangler** [comment]
hey there @wwwillchen  do you know of another way to persist installed python packages in colab? I'm only doing this since I have to reinstall all packages about 3-4 times a day due to colab idle timeouts and it takes about 10-15 minutes each time. Seems hugely wasteful in cpu cycles and time. This is why I'm using virtualenv.

**Comment by wwwillchen** [comment]
I see. You could try storing the pip packages directly on Drive without using virtualenv (e.g. https://stackoverflow.com/a/55253499). note: this is not an official recommendation

**Comment by dbwrangler** [comment]
Thanks for the suggestion. Good new is that it worked! Bad news is importing is super slow and unstable. I repeated the pip install of accelerate twice and once it worked and second time a torch file was missing in gdrive. Also, when it did work, on kernel restart it took 16 mins to run 'from accelerate import Accelerator'! Anyway, I don't see an easy way to do this , so will try a local set up for non-gpu development. 

I look forward to the day that pip runs quickly quickly on colab!

**Comment by mayankmalik-colab** [comment]
> hey there @wwwillchen do you know of another way to persist installed python packages in colab? I'm only doing this since I have to reinstall all packages about 3-4 times a day due to colab idle timeouts and it takes about 10-15 minutes each time. Seems hugely wasteful in cpu cycles and time. This is why I'm using virtualenv.

You can use [local runtimes](https://research.google.com/colaboratory/local-runtimes.html) or [Colab marketplace](https://research.google.com/colaboratory/marketplace.html) if you want to persist the packages.

**Comment by dbwrangler** [comment]
thanks for your time!
