### ISSUE TITLE
INSTALLATION & IMPORTING OF PPSCORE LIBRARY IN GOOGLE COLAB

### ISSUE THREAD

**Issue by fpsomad** [googlecolab/colabtools#4499]
[PPSCORE.ipynb - Colab.pdf](https://github.com/googlecolab/colabtools/files/14948611/PPSCORE.ipynb.-.Colab.pdf)

As depicted in the attached .pdf file, it is not possible to import the ppscore library into the current google colab environment due to incompatibility of the pandas library versions. Google colab requires pandas 2.0.3, whilst ppscore library deploys pandas 1.5.3. Is there any way to circumvent this issue and be able to run the ppscore library in a Jupyter notebook of the current colab environment ?

**Comment by EvanWiederspan** [comment]
The output indicates that the package installed just fine - it's just pointing out an incompatible version. This may sometimes affect you if it's incompatible with a package that you care about, but in this case it shouldn't cause any issues

**Comment by fpsomad** [comment]
Thank you for your reply. The package may have installed, but due to the incompatibility it cannot be imported, hence it cannot be deployed! Can you suggest any workaround for this issue ?

I would appreciate your help in this.

Fotis Psomadellis
