### ISSUE TITLE
While installing caffe-cpu it asks for continue Y/N but how to give input as Y

### ISSUE THREAD

**Issue by saifhassan** [googlecolab/colabtools#45]
While installing caffe-cpu it asks for continue Y/N but how to give input as Y

using this command
**!apt install caffe-cpu**

Need to get 79.2 MB of archives.
After this operation, 298 MB of additional disk space will be used.
**Do you want to continue? [Y/n]**

**Comment by craigcitro** [comment]
Just add `-y` to your command -- so

    !apt install -y caffe-cpu

will do the trick.

**Comment by saifhassan** [comment]
Thanks, It worked.

**Comment by colaboratory-team** [comment]
We've just rolled out support for input prompts. You should now be able to answer this prompt without needing `-y`. See #258 for a similar issue.
