### ISSUE TITLE
code not working

### ISSUE THREAD

**Issue by Haricharan108** [googlecolab/colabtools#4502]
n=input() 
a=False 
if len(n)==10 and int(n[0])>5 and n.isdigit(): 
    for i in range(10): 
        if n.count(n[i])<8: 
            a=True 
            if n[i]*6 in n: 
                a=False 
                break
            else: 
                break
if a: 
    print('valid')
else:
    print('invalid')

this code is working in other platforms but not in colab so fix it and please give me something in reward

**Comment by cperry-goog** [comment]
Your reward is a fuzzy feeling from a job well done. Can you instead submit this as a GitHub gist or a notebook and identify how this code is not working?
