### ISSUE TITLE
joblib error in memory.py

### ISSUE THREAD

**Issue by goporto20** [googlecolab/colabtools#4503]
I hope you find very well

By using the following lines of code:
!pip install pycaret
from pycaret.regression import *

I get this error:
mportError: cannot import name '_format_load_msg' from 'joblib.memory' (/usr/local/lib/python3.10/dist-packages/joblib/memory.py)

I temporarily solved it by removing this parameter _format_load_msg from memory.py.

However, when I want to execute the following code:
reg = setup(data = data,
              target = 'sale exchange rate',
              ignore_features = ['purchase exchange rate', 'date'],
              numeric_imputation = 'mean',
              categorical_features = ['year','month','week year','day month','day year','quarter year'] ,
              transformation = True,
              transform_target = True,
              remove_multicollinearity = True,
              multicollinearity_threshold = 0.95)

I'm getting this other error:

AttributeError: 'FastMemorizedFunc' object has no attribute '_get_output_identifiers'.

I have tried restarting the execution environment and running it again and the same thing happens to me, I have even tried selecting another environment and the same error continues.

Your help please.

**Comment by goporto20** [comment]
The browser used is Firefox and Microsoft Edge

**Comment by krishnagenomics** [comment]
Same issue for me too

**Comment by MahdiAll99** [comment]
I encountered the same error while using pycaret=3.3.0 and python=3.10.0, I downgraded pycaret to 3.0.4 but I still got the same error. However when I downgraded to python=3.9.13 and pycaret=3.0.4 the error was gone! So I recommend downgrading your Python version, also, I think this issue should be open in pycaret repo.

**Comment by goporto20** [comment]
> I encountered the same error while using pycaret=3.3.0 and python=3.10.0, I downgraded pycaret to 3.0.4 but I still got the same error. However when I downgraded to python=3.9.13 and pycaret=3.0.4 the error was gone! So I recommend downgrading your Python version, also, I think this issue should be open in pycaret repo.

**Comment by goporto20** [comment]
I managed to install the version of python that you mention, however not in pycaret.

I don't know if I'm doing something wrong, I did it like this: !pip install pycaret = 3.0.4

That way it gives me the same error.

**Comment by MahdiAll99** [comment]
Can you try it on a new conda environnement: You can create one as follows (with the python version i mentionned) `conda create --name myenv python=3.9.13` and to install a specific version of pycaret run `pip install pycaret==3.0.4`, then install other requirements and test again.

**Comment by sorenwacker** [comment]
What version of `joblib` do you have installed?

**Comment by goporto20** [comment]
The installed version is the one that Google Colab installs by default, I do not do a manual installation of joblib.

However, for now it is working again.

**Comment by hikmetc** [comment]
same error, I tried everything mentioned above

**Comment by zankai-dcap** [comment]
Facing the same issue with joblib=1.4.0 . Using joblib=1.3.2 solves the issue.

**Comment by Manthata** [comment]
@zankai-dcap thank you for sharing! your solution worked for me too: joblib=1.3.2

**Comment by thiernmad** [comment]
Faced the same issue on Snowpark, downgrade to joblib=1.2.0 works ! Thanks for sharing.
