### ISSUE TITLE
Google Colab Pro+  not access A100 GPU

### ISSUE THREAD

**Issue by JhonDan1999** [googlecolab/colabtools#4505]
**Describe the current behavior**
I subscribed to Google Colab Pro+ expecting access to premium GPUs (including A100) and 500 compute units for 90 days.
After canceling my subscription with the intention of not renewing automatically, I lost access to the A100 GPU. This has persisted for over a week, despite my ongoing Pro+ status.

**Describe the expected behavior**
My understanding is that Colab Pro+ subscribers should have access to premium GPUs like the A100 throughout their active subscription period, regardless of whether auto-renewal is enabled.

**What web browser you are using**
Chrome

**Additional context**
I want to say this is not the first time when I cancel my subscription even though my subscription period is not ended but once I cancel my subscription I am unable to connect or used A100

As you can see here is what I got 
![Screenshot 2024-04-15 at 12 18 28 AM](https://github.com/googlecolab/colabtools/assets/145554661/5b651eb1-29b6-405e-86d5-0d96d492ba0d)

And here is my computer unit

![Screenshot 2024-04-15 at 12 18 34 AM](https://github.com/googlecolab/colabtools/assets/145554661/bef2a1a9-78d7-4ee7-83dc-058c11357298)

**Comment by cperry-goog** [comment]
We're trying to get more A100s but they're frequently stocked out by Pro+ users though I'll note this is a common complaint here - we added L4s in the interim as an option with a larger memory footprint than V100s. I cannot secure more A100s right now, but looking to get H100s as well.

**Comment by JhonDan1999** [comment]
@cperry-goog but I am Pro+ user and still not able to get A100 can I know why?

**Comment by mahsumozer** [comment]
> @cperry-goog but I am Pro+ user and still not able to get A100 can I know why?

i am getting the same problem rn. after few run time changes and try i was able to get a100 but after i disconnect now i am getting same problem again. maybe it can work for you.

**Comment by JhonDan1999** [comment]
> > @cperry-goog but I am Pro+ user and still not able to get A100 can I know why?
> 
> i am getting the same problem rn. after few run time changes and try i was able to get a100 but after i disconnect now i am getting same problem again. maybe it can work for you.

I tried it it worked one time may be after 5 times of connecting and disconnecting 
Thanks
