### ISSUE TITLE
Google Colab is so laggy when I using Google Chrome

### ISSUE THREAD

**Issue by K2O7I** [googlecolab/colabtools#4507]
**Describe the current behavior**
I use my Google Colab in Chrome browser, but when I update Chrome's new version, Google Colab is frozen when I scroll up and down my web page, and it is still frozen when I reload the page.
I already tried another browser and found this issue only occurs in Chrome

**What web browser you are using**
My Chrome version is 123.0.6312.123

**Comment by EvanWiederspan** [comment]
Is this just for a specific notebook, or all notebooks, even scratchpad? Also, does this happen for you in incognito mode, with all extensions disabled?

**Comment by K2O7I** [comment]
Yes, it happens even in incognito mode and all notebook has this problem.

**Comment by alexanderhe88** [comment]
It happens to me as well. Colab is extremely sluggish with Chrome, and switching to other browsers like Edge seems to solve the issue.

My chrome version:
Version 123.0.6312.123 (Official Build) (64-bit)

**Comment by ArnaudFERRY** [comment]
Bonjour,
j'ai exactement le même problème sur Google Chrome depuis le 15/04/24 lorsque j'ouvre un notebook colab : au bout de une ou deux minutes, ça devient très très lent puis le note book se fige et plus aucune action n'est possible !
Version Google Chrome : 123.0.6312.123
Je précise que je suis en version gratuite de colab mais avant le 15/04 tout fonctionnait parfaitement bien.
J'ai essayé de modifier les paramètres de Chrome et Colab sans succès (le passage de CPU à T4 GPU apporte une légère amélioration mais le note book finit toujours par être lent).
En revanche pas de problème de lenteur si j'ouvre le même note book sous Edge ou JupiterLab dans Chrome donc ce qui me fait penser qu'il s'agit d'un problème lié à Google Colab.

**Comment by alexanderhe88** [comment]
UPDATE: the new Chrome update (Version 124.0.6367.61 (Official Build) (64-bit)) seems to solve this issue.
