### ISSUE TITLE
Incorrect link for Gemini quickstart in "Welcome to Colab" notebook  

### ISSUE THREAD

**Issue by jtbg** [googlecolab/colabtools#4513]
**Describe the current behavior**
The default `Welcome to Colab` notebook [contains several newly-added links to examples using the Gemini API](https://colab.research.google.com/notebooks/welcome.ipynb#scrollTo=Wf5KrEb6vrkR&line=11&uniqifier=1)

Included in this list is
```html
<a href="https://colab.research.google.com/github/google/generative-ai-docs/blob/main/site/en/tutorials/python_quickstart.ipynb?utm_medium=link&utm_campaign=gemini">
Gemini API: Quickstart with Python
</a>
```

This is not the correct path for the quickstart, so clicking it results in a `Notebook note found` error

**Describe the expected behavior**

The correct link should be:

```html
<a href="https://github.com/google/generative-ai-docs/blob/main/site/en/tutorials/quickstart_colab.ipynb">
Gemini API: Quickstart with Python
</a>
```

**Comment by EvanWiederspan** [comment]
Thanks for pointing this out, I just sent the fix so the correct link should start appearing early next week
