### ISSUE TITLE
Variables are not being exchanged for their values ​​when used as an argument in a script

### ISSUE THREAD

**Issue by shirounanashi** [googlecolab/colabtools#4515]
**Describe the current behavior**
Variables are not being changed to their value when used as arguments in a Python script, instead the variable name is used as the value.

**Describe the expected behavior**
The variable value will be used as the value, not the variable name.

**What web browser you are using**
Chrome and Firefox

**Additional context**
[Notebook](https://colab.research.google.com/drive/1Pyud6bWtUAic_xdE2TGVHAmfk6OAMwKS?usp=sharing)
Output:
```
usage: main.py infer [-h]
                     [--f0up_key {-24,-23,-22,-21,-20,-19,-18,-17,-16,-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24}]
                     [--filter_radius {0,1,2,3,4,5,6,7,8,9,10}]
                     [--index_rate {0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0}]
                     [--rms_mix_rate {0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0}]
                     [--protect {0.0,0.1,0.2,0.3,0.4,0.5}]
                     [--hop_length {too much numbers}]
                     [--f0method {pm,harvest,dio,crepe,crepe-tiny,rmvpe,fcpe,hybrid[crepe+rmvpe],hybrid[crepe+fcpe],hybrid[rmvpe+fcpe],hybrid[crepe+rmvpe+fcpe]}]
                     [--input_path INPUT_PATH] [--output_path OUTPUT_PATH] [--pth_path PTH_PATH]
                     [--index_path INDEX_PATH] [--split_audio {True,False}]
                     [--f0autotune {True,False}] [--clean_audio {True,False}]
                     [--clean_strength {0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0}]
                     [--export_format {WAV,MP3,FLAC,OGG,M4A}]
main.py infer: error: argument --f0up_key: invalid choice: '{pitch}' (choose from '-24', '-23', '-22', '-21', '-20', '-19', '-18', '-17', '-16', '-15', '-14', '-13', '-12', '-11', '-10', '-9', '-8', '-7', '-6', '-5', '-4', '-3', '-2', '-1', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24')
```
The "pitch" variable is not being exchanged for its value, instead, the name "{pitch}" is being used as the value
**This doesn't just happen on this notebook, I've had several notebooks with this same problem.**

**Comment by EvanWiederspan** [comment]
I'm not able to repro with a simple case, are you able to provide a repro that doesn't require reading files from Drive?

**Comment by shirounanashi** [comment]
Hi @EvanWiederspan , I tested the code today to make the change you requested and, to my surprise, it worked as it should...

**Comment by EvanWiederspan** [comment]
Ah, it's possible you're running into https://github.com/ipython/ipython/issues/8492

It looks like in a ! statement, if any of the curly brace-wrapped variables do not exist, then none of them will be substituted. This is somewhat intentional by IPython, and I don't think there's much we could do to fix it

You can repro pretty easily with:

```
a = 1
!echo {a} {a}
!echo {a} {b}
!echo {b} {a}
```

Where the first one prints a just fine, but the next print literal {a} and {b}, even though a is defined and b is not

Closing as I don't believe we can do much here, since it happens at the IPython level
