### ISSUE TITLE
Cannot update to latest ggplot2 version in colab R kernel

### ISSUE THREAD

**Issue by silasbergen** [googlecolab/colabtools#4517]
It appears that within the past week (I write this on 4/20/2024), the default `ggplot2` package version pre-installed with the R kernel in Google colab is 3.3.5, a very old version. I have lots of code for a forecasting class using the `forecast` package that, when run a week ago, loaded `ggplot2` version 3.4.4 and worked fine. This code no longer works with 3.3.5. I have tried to update to the latest version of `ggplot2`, but am running into problems with the `rlang` package: the latest versions of `ggplot2` depend on rlang >= 1.1.0, whereas the default is `rlang` 1.0.1. Trying to update the `rlang` package seems to violate the R kernel itself!

I am using a Chrome browser; problem persists in Firefox.

Here is my notebook where I try to update ggplot to latest version and follow a rabbit trail that depends on the IRkernel package behind the whole notebook:

https://colab.research.google.com/drive/171EZU5Qyar-a768EUxlm1pyVXbh9TE1v?usp=sharing

Two questions,

1. why is the "new" default ggplot2 package pre-installed on the R kernels so old;
2. why can I not update it??

**Comment by U-R-dev** [comment]
I am also suffering from the same 'rlang' version problem: I cannot load the 'furrr' package that depends on rlang >= 1.0.2.
As a temporary workaround, I could update the 'rlang' package after unloading all dependent packages, and was able to run the 'furrr' package without problems:

```r
packageVersion('rlang')
[1] ‘1.0.1’

unloadNamespace('IRkernel')
unloadNamespace('IRdisplay')
unloadNamespace('repr')
unloadNamespace('pillar')
unloadNamespace('ellipsis')
unloadNamespace('vctrs')
unloadNamespace('lifecycle')
unloadNamespace('htmltools')
unloadNamespace('rlang')

install.packages('rlang')
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

library(rlang)

packageVersion('rlang')
[1] ‘1.1.3’
```

**Comment by JanNehyba** [comment]
Same problem: 
```
options(repos = c(CRAN = "https://cloud.r-project.org/"))
install.packages("rlang")
library(rlang)
packageVersion("rlang")
```

Output:
`Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Error in value[[3L]](cond): Package ‘rlang’ version 1.0.1 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘rlang’ is imported by ‘ellipsis’, ‘pillar’, ‘vctrs’, ‘lifecycle’, ‘htmltools’ so cannot be unloaded

Traceback:

1. library(rlang)
2. tryCatch(unloadNamespace(package), error = function(e) {
 .     P <- if (!is.null(cc <- conditionCall(e))) 
 .         paste("Error in", deparse(cc)[1L], ": ")
 .     else "Error : "
 .     stop(gettextf("Package %s version %s cannot be unloaded:\n %s", 
 .         sQuote(package), oldversion, paste0(P, conditionMessage(e), 
 .             "\n")), domain = NA)
 . })
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. value[[3L]](cond)
6. stop(gettextf("Package %s version %s cannot be unloaded:\n %s", 
 .     sQuote(package), oldversion, paste0(P, conditionMessage(e), 
 .         "\n")), domain = NA)`

**Comment by silasbergen** [comment]
Well, within the past hour, the kernel seems to have updated to the point that rlang version 1.1.3 is the default installed version, and ggplot2 version 3.4.4 (2nd-to-last most recent version) is installed.  Don't know what happened to cause the kernel to revert back to an ancient version of rlang/tidyverse, but it seems to be okay now?
