### ISSUE TITLE
Google Colab consumed the compute units without running a notebook in premium account.

### ISSUE THREAD

**Issue by Aman-Kitaz** [googlecolab/colabtools#4519]
**Describe the current behavior**
Google Colab consumed the compute units without running a notebook in a pro account.

**Describe the expected behavior**
Compute units must be spent only while running a notebook
**What web browser you are using**
Chrome
<img width="258" alt="Screenshot 2024-04-22 at 1 51 14 PM" src="https://github.com/googlecolab/colabtools/assets/167759580/cad577f8-9008-445a-bf80-03863e5ac730">

**Comment by EvanWiederspan** [comment]
We won't be able to help from Github, can you file in-product feedback at Help -> Send feedback? Then we can look and see what was using your compute units
