### ISSUE TITLE
whisper-webui.ipynb   error  

### ISSUE THREAD

**Issue by 2019232** [googlecolab/colabtools#4523]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

/

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformers 4.40.0 requires tokenizers<0.20,>=0.19, but you have tokenizers 0.15.2 which is incompatible.

**Comment by mayankmalik-colab** [comment]
We are already on tokenizers `0.19.1`. I don't see your notebook but my guess is that your notebook may have downgraded the tokenizers package, which caused the conflict.
