### ISSUE TITLE
Your session crashed for an unknown reason

### ISSUE THREAD

**Issue by chrislalk** [googlecolab/colabtools#4528]
**Describe the current behavior**
When I run the following command
import torch
the session crashes: "Your session crashed for an unknown reason."
WARNING:root:kernel b533f34b-cbe8-4c8e-9ba4-fd538b02864a restarted

**Describe the expected behavior**
It should be able to import torch
**What web browser you are using**
Chrome
I use a A100 with extra GPU

**Comment by EvanWiederspan** [comment]
Can you share a repro notebook that shows this issue?
