### ISSUE TITLE
Add DuckDB backend for Ibis

### ISSUE THREAD

**Issue by bingbong-sempai** [googlecolab/colabtools#4529]
**Is your feature request related to a problem? Please describe.**
Both Ibis and DuckDB are already included in the default packages.  
But the installation of Ibis has no backend to use DuckDB with Ibis.  

**Describe the solution you'd like**
Include `ibis-framework[duckdb]` in the default packages.

**Describe alternatives you've considered**
Running `pip install 'ibis-framework[duckdb]'` at the start of notebooks.

**Additional context**
Ibis integration with DuckDB: https://duckdb.org/docs/guides/python/ibis.html

**Comment by EvanWiederspan** [comment]
Thanks for the suggestion, we will consider it
