### ISSUE TITLE
Error Installing Dependencies on Google Colab (Wheel)

### ISSUE THREAD

**Issue by RoenTh** [googlecolab/colabtools#4531]
**Describe the current behavior**
I am trying to run the code of [stable-dreamfusion](https://github.com/ashawkey/stable-dreamfusion) in a Google Colab notebook, which as I see its working for others, but I am encountering installation errors for several packages (raymarching, shencoder, freqencoder, and gridencoder). The installation fails during the execution of install.sh, with the following error for each package

```
Installing collected packages: raymarching
error: subprocess-exited-with-error

× Running setup.py install for raymarching did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Running setup.py install for raymarching ... error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> raymarching

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure."
```

**Describe the expected behavior**
Successfully install cuda extensions

**What web browser you are using**
Chrome

**Additional context**
1.Go to [https://colab.research.google.com/drive/1MXT3yfOFvO0ooKEfiUUvTKwUkrrlCHpF?usp=sharing](https://github.com/ashawkey/stable-dreamfusion/issues/url)
2. Run install dependencies

**Comment by cperry-goog** [comment]
raymarching is no longer maintained - the last release was 3 years back. You'll want to contact the library maintainer or notebook author, sorry.
