### ISSUE TITLE
[BUG]Colab，Could not create share link. 

### ISSUE THREAD

**Issue by jthwxxzyt** [googlecolab/colabtools#4533]
As the title indicates, when I used colab in the last few days, I was prompted：

Could not create share link. Missing file: /usr/local/lib/python3.10/dist-packages/gradio/frpc_linux_amd64_v0.2. 

Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps: 
![image](https://github.com/googlecolab/colabtools/assets/163423667/2e32b59a-fc64-49a5-b32f-f97a6f0a1e61)

**Comment by jthwxxzyt** [comment]
What happened?
Unable to create a shared link

Steps to reproduce the problem
Execute the cells and wait until it finishes loading

What should have happened?
It should have shown the link of the gradio

What browsers do you use to access Fooocus?
Google Chrome

Where are you running Fooocus?
Cloud (Google Colab)

What operating system are you using?
No response

**Comment by campilu** [comment]
This happens to me as well, and yesterday it was working fine for me.

**Comment by cperry-goog** [comment]
Can you share a minimal reproducible notebook? I can't figure out what is breaking from this error.
