### ISSUE TITLE
My colab file is not saving, I tried cache cleaning, changed browser, other colab file 

### ISSUE THREAD

**Issue by Souviksamanta34** [googlecolab/colabtools#4538]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
Can you submit feedback in product, or if you have reproducible steps that reliably trigger this that would be lovely.
