### ISSUE TITLE
Can't Connect to A100

### ISSUE THREAD

**Issue by yukiarimo** [googlecolab/colabtools#4539]
How do I get an A100 GPU if I'm a Pro subscriber? I tried to connect to it, but it dropped me to the L4 or V100. Is there a perfect time of day when fewer people are using it? How does it work?

**Comment by cperry-goog** [comment]
We have low capacity of A100s at Google generally; we're running at our max. Sorry. Lots of L4s though.

**Comment by MaxKho** [comment]
I think, for ML, it's A100>V100>P100>L4>T4

**Comment by yukiarimo** [comment]
Thanks, got it! Also, how appropriately they relate to M1-M4 Basic,Pro,Max versions?
