### ISSUE TITLE
ipyLeaflet maps do not display in Colab notebooks (possible regression on 2024-04-30)

### ISSUE THREAD

**Issue by antiraza** [googlecolab/colabtools#4540]
**Describe the current behavior**
Within roughly the last 24 hours of this bug report, a change in behavior is seen running ipyLeaflet on colab.

Yesterday, code executed would display a map.

Today, the same code will not.

A GIST containing a basic implementation of a map to show the error is included below.

This code, executed on a Jupyter notebook, WAI.
Executed on Colab, nothing is seen -- today. Yesterday, this likely would have WAI.

**Describe the expected behavior**

An interactive leaflet map should appear displayed in the cell output.

**What web browser you are using**
Chrome Version 124.0.6367.92 (Official Build) (arm64) (OSX)

**Additional context**
https://gist.github.com/antiraza/38ecadf6e9d31d9635d586461b1306ba#file-ipyleaflet-bug-report-2024-04-30-ipynb

**Comment by antiraza** [comment]
Looks like this is actually related to the new release of iPyleaflet.

See:  https://github.com/jupyter-widgets/ipyleaflet/issues/1192

I will close this bug as it doesn't seem this is related to anything related to Colab.

**Comment by antiraza** [comment]
Having said that, it looks like forcing a prior version (eg. 18.2) -- will get things working on Colab in the interim -- if that is desired. Reopening in case that's of interest to this crew.

**Comment by antiraza** [comment]
A workaround is described here.

https://github.com/gee-community/geemap/issues/2001

`Run the following command in your Colab notebooks:

!pip install ipyleaflet==0.18.2`

Given that this workaround is simple to execute, I'll close this ticket (again).

**Comment by giswqs** [comment]
I would highly suggest forcing ipyleaflet v0.18.2 in Colab until ipyleaflet resolves the issue. There are many packages built on top of ipyleaflet, and v0.19.0 breaks many downstream packages, making them unusable on Colab.

@jdbcode  @naschmitz

**Comment by EvanWiederspan** [comment]
Thanks for the suggestion, I sent the change to pin ipyleaflets to 0.18.2 for the time being, that'll take effect in the next few days

**Comment by maartenbreddels** [comment]
Hi, this is fixed in ipyleaflet 0.19.1 https://github.com/jupyter-widgets/ipyleaflet/issues/1192#issuecomment-2109534676
