### ISSUE TITLE
from pytorch_forecasting.trainer import Trainer

### ISSUE THREAD

**Issue by brettgolden2424** [googlecolab/colabtools#4543]
Does anyone know why Colab cannot find Pytourch forecasting? 

ModuleNotFoundError: No module named 'pytorch_forecasting.trainer'

**Comment by mayankmalik-colab** [comment]
I don't see `pytorch_forecasting.trainer` atleast in the latest version of `pytorch_forecasting`. Can you refer the sample example mentioned [here](https://github.com/jdb78/pytorch-forecasting/tree/v0.9.0?tab=readme-ov-file#usage-example).
