### ISSUE TITLE
Can not connect to A100 GPU. i'm new subscribe to colab pro

### ISSUE THREAD

**Issue by Jorge-ux** [googlecolab/colabtools#4544]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by JhonDan1999** [comment]
Unfortunately I being pro subscriber does not guarantee the availability of A100
