### ISSUE TITLE
Colab is not connecting to GCE backend

### ISSUE THREAD

**Issue by sokol11** [googlecolab/colabtools#4546]
This is the first time I've encountered this: Colab is stuck trying to connect to a VM. It seems to affect all VM types on both Chrome and Safari. For reference, I'm in the US, in the Northeast. It just says "Connecting" indefinitely...

**Comment by cperry-goog** [comment]
please confirm the details of the connection you're making, confirm your account has access to the VM, confirm the VM is running, and if those are all true, submit feedback in product and reference this issue.

**Comment by sokol11** [comment]
I'm doing what I've been doing for years, trying to connect to the GCE backend via browser, and it's just stuck trying to do so. I'm a Pro subscriber. 

"submit feedback in product and reference this issue." - how do I do that?

Thank you!
