### ISSUE TITLE
Install failed using MySQL - Error: chatflowsService.getAllChatflows - Error: getRunningExpressApp failed!

### ISSUE THREAD

**Issue by phongtnit** [googlecolab/colabtools#4548]
**Describe the current behavior**
Hi, I installed Flowise on Docker using new files in https://github.com/FlowiseAI/Flowise/tree/main/docker and using MySQL in .env. And failed installation with the following error: 

```Status: 500
Error: chatflowsService.getAllChatflows - Error: getRunningExpressApp failed!
```

Error image: 
<img width="1208" alt="Screenshot 2024-05-05 at 12 59 03" src="https://github.com/googlecolab/colabtools/assets/5652784/485fe588-a12c-488e-8119-2189a76e9958">

**My .env setting**
```PORT=3000
DATABASE_PATH=/root/.flowise
APIKEY_PATH=/root/.flowise
SECRETKEY_PATH=/root/.flowise
LOG_PATH=/root/.flowise/logs
BLOB_STORAGE_PATH=/root/.flowise/storage

# NUMBER_OF_PROXIES= 1
# CORS_ORIGINS="*"
# IFRAME_ORIGINS="*"

DATABASE_TYPE=mysql
DATABASE_PORT=3306
DATABASE_HOST=172.17.0.1
DATABASE_NAME=abc
DATABASE_USER=abc
DATABASE_PASSWORD=abc
```

**Describe the expected behavior**
I am sure that MySQL account information is correct. I checked the MySQL database, it was empty after running the Flowise using `sudo docker compose up -d`.

If I don't use MySQL as my DB backend, the installation is successful and the script worked fine.

What I should do to install Flowise using MySQL? Thanks for your support,

**Additional context**
- OS: Ubuntu 24.04
- Docker version: Docker version 26.1.1, build 4cf5afa
- MySQL version: mysql  Ver 8.0.36-2ubuntu3 for Linux on x86_64 ((Ubuntu))
- My ufw firewall:
```
sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
22/tcp                     ALLOW       Anywhere                  
80/tcp                     ALLOW       Anywhere                  
443                        ALLOW       Anywhere                  
3306 on docker0            ALLOW       172.17.0.0/16             
22/tcp (v6)                ALLOW       Anywhere (v6)             
80/tcp (v6)                ALLOW       Anywhere (v6)             
443 (v6)                   ALLOW       Anywhere (v6)
```
- My `mysqld.cnf`:
```
bind-address = 0.0.0.0
```
- I tested access the MySQL remotely using `mysql -u <mysql_user> -h <remote_ip> -p` and it worked.

**Comment by phongtnit** [comment]
Hix, I had a mistake to post the issue here

**Comment by cperry-goog** [comment]
Closing given your last comment.
