### ISSUE TITLE
IPython.display.display_javascript not working?

### ISSUE THREAD

**Issue by intuitivetextmining** [googlecolab/colabtools#455]
It looks like `IPython.display.javascript` objects are not rendered by `IPython.display.display_javascript`

This example notebook works in a locally installed Jupyter notebook (anaconda) and also a mybinder instance, which suggests the issue is with colab.

[https://github.com/intuitivetextmining/d3fdgraph/blob/master/examples/d3fdgraph_simple_test.ipynb](https://github.com/intuitivetextmining/d3fdgraph/blob/master/examples/d3fdgraph_simple_test.ipynb)

The d3fdgraph module simply loads some html and javascript from a packaged file and renders them .. the html element woks in colab but the javascript appears not to run.

**Comment by blois** [comment]
The issue is that the Javascript that d3fdgraph is generating uses require.js which is not available by default. Jupyter Lab has similar behavior.

The workaround is to explicitly load require.js:
https://colab.research.google.com/gist/blois/f11d8827f8d0d78ced494bd51abcdd68/d3fdgraph.ipynb

**Comment by intuitivetextmining** [comment]
is there a case for enabling require.js by default - given that the main Jupyter notebook and the mybinder service does include it?

**Comment by blois** [comment]
Colab tries to minimize the public APIs which are provided by default for backwards compatibility reasons and to minimize output loading time. 

An example of using `pre_run_cell` to configure it in every outputframe is:
https://colab.sandbox.google.com/notebooks/charts.ipynb#scrollTo=yrkTy0G1O4xq

 - JupyterLab: https://github.com/jupyterlab/jupyterlab/issues/1188
 - nteract: https://github.com/nteract/nteract/issues/2743
