### ISSUE TITLE
Why L4 GPU on Google Colab trains model same time as my GTX 1650 SUPER? 

### ISSUE THREAD

**Issue by Jerrody** [googlecolab/colabtools#4552]
Data is directly uploaded to the Colab's Workspace and I don't use GDrive. Also, I can provide my Net if it's necessary.

In summery, both GPUs (my and on the Google Colab L4 GPUs train model in 20 secs per epoch).

**Comment by cperry-goog** [comment]
We cannot benchmark L4 performance against other GPU types, sorry.
