### ISSUE TITLE
not printing list of directory while using os.listdir in for loop

### ISSUE THREAD

**Issue by fulwaa** [googlecolab/colabtools#4553]
list of sub directory is not showing while i tried to use os.listdir in for loop to iterate over sub directory. it taking subdirectory but printing name  
for cati in os.listdir(dataset_root_path):
  print(cati)

**Comment by mayankmalik-colab** [comment]
I am not sure if I understood the problem. `os.listdir` gives you the list of files and directories for the path specified ( `dataset_root_path` in your case). If you want to list the full path, you can do something like:

```
path=""
for file in os.listdir(path):
  full_path = os.path.join(path, file)
  if os.path.isdir(full_path):
    print(full_path) 
```
