### ISSUE TITLE
ModuleNotFoundError: No module named 'fpdf2'

### ISSUE THREAD

**Issue by xlipesousa** [googlecolab/colabtools#4557]
In Google Colab i try to execute this cod but this error is printed:

!pip install fpdf2
from fpdf2 import FPDF

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-a38fe0be4699>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from fpdf2 import FPDF

ModuleNotFoundError: No module named 'fpdf2'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by katlyn-edwards** [comment]
You want the following code:
```
!pip install fpdf2
from fpdf import FPDF
```

It's installed as fpdf 

Here's their website which shows this as an example:
https://pypi.org/project/fpdf2/

https://colab.research.google.com/github/py-pdf/fpdf2/blob/master/tutorial/notebook.ipynb
