### ISSUE TITLE
Error When using dark theme can't read plot's values

### ISSUE THREAD

**Issue by lmadhuranga** [googlecolab/colabtools#456]
![error colab](https://user-images.githubusercontent.com/3930563/53717145-3efb4700-3e7d-11e9-93ea-8daba0642f42.JPG)

there is a huge problem to work with plot images
Alternative
1. Change the colors using matplot parameters  if it has so many plots (more than 10 each file) it's not a practical solution.
2.Override css using some chrome extention

**Comment by katlyn-edwards** [comment]
Hey there! Do you have a minimal repro notebook we could use to debug? 
I was playing around with  https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/04.02-Simple-Scatter-Plots.ipynb

And this one seems alright in dark mode: 
![download](https://user-images.githubusercontent.com/2673487/54705944-15881f80-4afb-11e9-95d1-321edcd5a4cc.png)

**Comment by lmadhuranga** [comment]
hi Katlyn Edwards,
Thanks for quick response and I reported this one 

![image](https://user-images.githubusercontent.com/3930563/54706953-1a35ed80-4b66-11e9-88cb-8e64e3c216b8.png)

there was a solution for it, Did you see in the above
This is the solution for it =>  **plt.style.use('seaborn-whitegrid')**
![image](https://user-images.githubusercontent.com/3930563/54707017-376abc00-4b66-11e9-97bd-1914f2e88739.png)

Is it a problem or feature now, or do we need to add this line (**plt.style.use('seaborn-whitegrid')**)
in our code ..?
Thanks

**Comment by Molkree** [comment]
Hi, @katlyn-edwards, repro can be found here [Google Intro to fairness](https://colab.research.google.com/github/google/eng-edu/blob/master/ml/cc/exercises/intro_to_fairness.ipynb). Facets visual overview produces unreadable plot values in dark theme.
![image](https://user-images.githubusercontent.com/12860284/55760813-e6affa00-5a65-11e9-8ddf-1164d07d0e76.png)

**Comment by bthodla** [comment]
plt.style.use('seaborn-whitegrid') works like a charm! Thank you!

**Comment by craigcitro** [comment]
FWIW, I've also tweaked things to make the labels for the default matplotlib theme readable in dark mode.
