### ISSUE TITLE
Colab Pro.  Account has been blocked  from accessing Colab 

### ISSUE THREAD

**Issue by Stylenazar** [googlecolab/colabtools#4561]
Hello. Could you help unlock the Colab Pro account. I use it to work with Comfyui ( ui for "stable diffusion" run). But yesterday, I was blocked. I did not make any changes to the notebook, it has been working correctly for a long time.

I have enough units and I have Colab Pro . Here are the screenshots.

![61c26k5njqzc1](https://github.com/googlecolab/colabtools/assets/126091008/70166ee5-0370-491e-ac61-2cf00313a73e)
![nr3ogegnjqzc1](https://github.com/googlecolab/colabtools/assets/126091008/906a01b0-3ae9-4a75-9faf-7da11b5b8180)
![zwvhuopnjqzc1](https://github.com/googlecolab/colabtools/assets/126091008/b2b7d0fb-409d-49bc-b892-e6c6c8752ac4)

**Comment by Stylenazar** [comment]
Thank you very much Colab team.  My problem is solved.

**Comment by Sarfaraz-CPU** [comment]
hello i am also facing the same problem i  took subscription today at 1pm and now at 6 pm iam banned please helpme solve
![image](https://github.com/user-attachments/assets/483c6a3d-743d-4c7a-acab-4b0cfccf31b7)
