### ISSUE TITLE
AI tools not working

### ISSUE THREAD

**Issue by stansokol** [googlecolab/colabtools#4563]
**Describe the current behavior**
Not seeing AI suggestions, despite being Collab Pro subsriber
**Describe the expected behavior**
Would expect code prompts to appear

**What web browser you are using**
Safari

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
Can you submit in product feedback and we can look. My suspicion is you are in a locale where AI tools are not yet launched, or you are using a workspace accounts. We are in the progress of both expanding locales for AI assistance and launching to Workspace users.
