### ISSUE TITLE
HELLO

### ISSUE THREAD

**Issue by Kotamanistan** [googlecolab/colabtools#4564]
I am a Google Colab pro member. While making a transaction, I received a warning that you exceeded the limit after 3 hours and 56 minutes and I was not allowed to make a transaction. What kind of job is this? Did we buy Pro for nothing? I want this resolved.
Didn't Google Colab pro have 24 hours extra time? denemelikhsp32@gmail.com
https://colab.research.google.com/drive/10bOVAaVM7DozgCY1UcMxqVoucx-V9552#scrollTo=E4W8p1ZLLXLy

**Comment by cperry-goog** [comment]
Can you submit in-product feedback and reference this issue? We can take a look. My suspicion is you exhausted your compute unit balance.
