### ISSUE TITLE
bokeh show_app is currently unsupported.

### ISSUE THREAD

**Issue by gillams1** [googlecolab/colabtools#4566]
When I run the following code below, I get the message "bokeh show_app is currently unsupported".
"FFI = lk.search_tesscut(Target_ID, sector=sec).download(cutout_size=(l,l), quality_bitmask=None)
FFI.interact_sky(notebook_url=url)"

This code is from the python package lightKurve used for analyzing data from the Transiting Exoplanet Survey Satellite (TESS).
URL=https://docs.lightkurve.org/

I expect an interactive astronomical image to be displayed of a region of the sky viewed by the TESS satellite.

I am using MicroSoft Edge.

The notebook AperturesSelect.ipnyb is saved as a GitHub gist.

Thank you,

Steve Gillam

**Comment by cperry-goog** [comment]
duplicate with #1800
