### ISSUE TITLE
Should the default CPU runtime have Python packages that depend on CUDA?

### ISSUE THREAD

**Issue by atmorling** [googlecolab/colabtools#4569]
**Describe the current behavior**
In a default Python Notebook (no GPU) environment, packages such as `cuda-python` and `cudf-cu12` are installed.

**Describe the expected behavior**
Very happy to be wrong here but I would expect that these packages are excluded from a CPU only runtime.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
https://gist.github.com/atmorling/584478dc0160ee2e09824181105f900d

A concrete example of why this might not be desirable is a package like `datashader`, which has an optional dependency on `cudf`. If one runs `import datashader` on CPU runtime it results in the below warning:
```
/usr/local/lib/python3.10/dist-packages/cudf/utils/_ptxcompiler.py:61: UserWarning: Error getting driver and runtime versions:

stdout:



stderr:

Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/usr/local/lib/python3.10/dist-packages/numba/cuda/cudadrv/driver.py", line 295, in __getattr__
    raise CudaSupportError("Error at driver init: \n%s:" %
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: 

CUDA driver library cannot be found.
If you are sure that a CUDA driver is installed,
try setting environment variable NUMBA_CUDA_DRIVER
with the file path of the CUDA driver shared library.
:


Not patching Numba
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.10/dist-packages/cudf/utils/gpu_utils.py:62: UserWarning: Failed to dlopen libcuda.so.1
  warnings.warn(str(e))
/usr/local/lib/python3.10/dist-packages/cudf/utils/gpu_utils.py:62: UserWarning: Function "cuInit" not found
  warnings.warn(str(e))
```
Like I said, I'm happy to be wrong here, and maybe this is on datashader to make their check for a valid GPU environment smarter, but to me these packages shouldn't be default without a GPU.

**Comment by mayankmalik-colab** [comment]
Unfortunately, we can't have different packages for a CPU and a GPU machines for now. However, we will keep this mind as a new feature request.
