### ISSUE TITLE
Could not able to connect the GPU> It is showing no backend !

### ISSUE THREAD

**Issue by Tirth1403** [googlecolab/colabtools#4570]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by chandcalnaido** [comment]
I am seeing the same issue.

**Comment by Crisha86** [comment]
I have tried with two accounts, one of which I am paying for Colab Pro and one just using regular runtime, then had a friend try ton connect on their gmail, and the Colab Pro gets the with GPU message back when trying to connect to T4 GPU runtime, and the CPU runtime gets this error:

![2024-05-16_19-33-28](https://github.com/googlecolab/colabtools/assets/170055386/49a3c359-acea-452f-85b8-c6e0f41de249)

**Comment by mayankmalik-colab** [comment]
Follow https://github.com/googlecolab/colabtools/issues/4574 for the updates.

**Comment by cperry-goog** [comment]
This was resolved last week
