### ISSUE TITLE
Cannot connect to my Google Drive

### ISSUE THREAD

**Issue by chrisyxue** [googlecolab/colabtools#4571]
**Describe the current behavior**
Cannot connect to my Google Drive using
"""
from google.colab import auth
auth.authenticate_user()
"""

**Describe the expected behavior**
Connect to my drive

**What web browser you are using**
Chrome

**Additional context**
Here is the error feedback
<img width="371" alt="Screenshot 2024-05-16 at 4 17 15 PM" src="https://github.com/googlecolab/colabtools/assets/41327917/59b034b2-0ab9-4d29-9196-5ae018bbe1a4">

**Comment by mayankmalik-colab** [comment]
We are aware of the issue. Please follow [link](https://status.cloud.google.com/incidents/xVSEV3kVaJBmS7SZbnre#Dh3y8L8YSyVY8gnSdWiZ) for the updates.

**Comment by chrisyxue** [comment]
Thank you for taking care of this. BTW, the GUI of Colab looks wired (photo attached). 

I tried to reload it several times, but it still did not change. Also, I logged into the Colab by my other Google account using the same browser (Chrome), and the GUI looks good.


![Screenshot 2024-05-16 at 5 10 58 PM](https://github.com/googlecolab/colabtools/assets/41327917/b30e0f1f-537a-488a-9675-388323d03cc4)

**Comment by EvanWiederspan** [comment]
The issue with not being able to receive a runtime should be resolved now, thank you for your patience on that. The UI issue looks like an extension interfering, do you see the issue when loading the page in Incognito mode with all extensions disabled?
