### ISSUE TITLE
Issue with colab pro+

### ISSUE THREAD

**Issue by Tirth1403** [googlecolab/colabtools#4572]
Failed to assign a backend
No backend with GPU available. Would you like to use a runtime with no accelerator? [More info](https://research.google.com/colaboratory/faq.html#gpu-availability)

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by Crisha86** [comment]
I have tried with two accounts, one of which I am paying for Colab Pro and one just using regular runtime, then had a friend try ton connect on their gmail, and the Colab Pro gets the with GPU message back when trying to connect to T4 GPU runtime, and the CPU runtime gets this error:

![2024-05-16_19-33-28](https://github.com/googlecolab/colabtools/assets/170055386/64fe7cfe-8fe4-4075-b854-120f437e4e91)

**Comment by mayankmalik-colab** [comment]
We are aware of the issue. Please follow [link](https://status.cloud.google.com/incidents/xVSEV3kVaJBmS7SZbnre#Dh3y8L8YSyVY8gnSdWiZ) for the updates.

**Comment by cperry-goog** [comment]
this was resolved last week
