### ISSUE TITLE
Stuck on connecting to even a CPU.

### ISSUE THREAD

**Issue by Psyga315** [googlecolab/colabtools#4573]
**Describe the current behavior**
I'm trying to connecting to a CPU and it's just stuck on "Connecting..."

**Describe the expected behavior**
To connect to a CPU.

**What web browser you are using**
Firefox

**Additional context**
It doesn't matter the notebook, it doesn't connect.

**Comment by cperry-goog** [comment]
[This link](https://status.cloud.google.com/incidents/xVSEV3kVaJBmS7SZbnre#Dh3y8L8YSyVY8gnSdWiZ) has details on the ongoing incident.

**Comment by EvanWiederspan** [comment]
This should be resolved now, thank you for your patience
