### ISSUE TITLE
I can't use gpu to run tf(tensorflow) library, can you help me run it using gpu?

### ISSUE THREAD

**Issue by khoa3** [googlecolab/colabtools#4575]
I can't use gpu to run tf(tensorflow) library, can you help me run it using gpu?

**Comment by khoa3** [comment]
if my computer has a gpu (nvida gtx 1660 super)

**Comment by katlyn-edwards** [comment]
If you want to connect to your computer, you'll want to connect Colab using a "local runtime" - https://research.google.com/colaboratory/local-runtimes.html

**Comment by khoa3** [comment]
> Nếu muốn kết nối với máy tính của mình, bạn sẽ muốn kết nối Colab bằng "thời gian chạy cục bộ" - https://research.google.com/colaboratory/local-runtimes.html

please check my email

**Comment by khoa3** [comment]
So now I just need to run the commands in the link you provided and use it
in my default, right?

Vào Th 2, 20 thg 5, 2024 vào lúc 11:44 Katlyn Edwards <
***@***.***> đã viết:

**Comment by cperry-goog** [comment]
You'll need to select connect to a local runtime every time.
