### ISSUE TITLE
Program not running 

### ISSUE THREAD

**Issue by SilentKiller30** [googlecolab/colabtools#4576]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by SilentKiller30** [comment]
I’ve encountered an issue where my code doesn’t execute properly, and no error messages are displayed.”

**Comment by katlyn-edwards** [comment]
Without a screenshot, a repro notebook or something more concrete, we're unable to help.
