### ISSUE TITLE
i am not getting  inside of the tab lines like this: start coding or generate with AI

### ISSUE THREAD

**Issue by sivakotimohankumar** [googlecolab/colabtools#4583]
![Untitled2 ipynb - Colab](https://github.com/googlecolab/colabtools/assets/169905423/192dfee9-5212-426c-b2bc-af09ab2a6765)

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
See #4584
