### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by sivakotimohankumar** [googlecolab/colabtools#4584]
I AM not getting option of this inside of the new tab: start coding or generate with AI
![Untitled2 ipynb - Colab](https://github.com/googlecolab/colabtools/assets/169905423/d3afce44-78a0-444f-af82-8144ad2177ab)

**Comment by cperry-goog** [comment]
If you submit feedback in product we can say for sure, but this option is only available for gmail accounts of users who are 18+ in select countries (starting EU expansion soon fwiw). If you're on a workspace account or in a country we haven't launched yet it won't show, sorry.
