### ISSUE TITLE
[BUG]Questions regarding the display or settlement of colab computing units

### ISSUE THREAD

**Issue by jthwxxzyt** [googlecolab/colabtools#4585]
I purchased 100 computing units and the colab pro package on the 11th and 19th of this month respectively.
So I have 200 compute units here. And I have always used T4GPU.
On the afternoon of May 21,When I close colab, disconnect the link and delete the runtime, it shows that there are still about 140 computing units. But on the evening of May 21, when I opened colab again, it showed that there were only 39 computing units left.
There are 100 computational units missing.
I made sure that I disconnected the link and deleted the runtime after using colab. Moreover, even if I forget to do this, when t4gpu deducts 1.84 computing units per hour, it will not be deducted from 140 computing units to the remaining 39 computing units in about 6 hours.
I don't know if this is a display error or a system calculation failure...
![image](https://github.com/googlecolab/colabtools/assets/163423667/665c44d7-0f3c-4551-b87e-f8171cc6caf8)

**Comment by jthwxxzyt** [comment]
I used it again for a few hours yesterday, and it still doesn't show normally...
![image](https://github.com/googlecolab/colabtools/assets/163423667/bb3111d5-aa58-4c1c-bbaf-1eac62838eab)

**Comment by cperry-goog** [comment]
Can you file this feedback in product so we can investigate your account? Reference this issue. Thank you.
