### ISSUE TITLE
Colab pro+ not connecting to runtime

### ISSUE THREAD

**Issue by AntonioTannoury** [googlecolab/colabtools#4586]
**Describe the current behavior**
I have a pro+ colab account, that is not connecting to any of the configuration of the runtime (with GPU, with CPU,  with High RAM, without High RAM). If I use my other standard account it works, so it's not a connection problem from my side.

**Describe the expected behavior**
I expext to be connected to whatever runtime I need.

**What web browser you are using**
Chrome

**Aditional context**
By not connecting I mean, that I can press connect to runtime, but it will keep pending the connection until it says "Unable to connect to runtime"

I'm paying for such service so I expect at least to work better than the standard non-payed one

**Comment by seriodor** [comment]
I'm getting this exact same error, with the addition that it sometimes says
 ```
await connected: disconnected
Error: await connected: disconnected
    at https://ssl.gstatic.com/colaboratory-static/common/f78d3c46c7be89bc2afe86f025e3f824/external_binary.js:7025:426
```
glad its not just me.

**Comment by AntonioTannoury** [comment]
@seriodor thanks for confirming my frustration😄

**Comment by recycletechno** [comment]
The same with me on Colab Pro - it is "Connecting..." all the time. Tried to run on cpu, gpu, tpu - the same result. Also tested several internet connections and laptops. I happened just today. Maybe with today's update in Colab

**Comment by recycletechno** [comment]
In Google Chrome console I get 502 error:
![image](https://github.com/googlecolab/colabtools/assets/30195061/6096b281-70c2-4836-928d-9bddef3fb0a7)

following the link (https://colab.research.google.com/tun/m/m-hm-1rbbilaj2n6q8/api/sessions?backend_version=next&authuser=0) I get:
![image](https://github.com/googlecolab/colabtools/assets/30195061/445e350f-8193-4edf-883a-40aba9742aac)

**Comment by AidaRostamza** [comment]
How long will it take to be fixed? I have a deadline in the next few hours.

**Comment by Luca-Melop** [comment]
Same Problem here (on Firefox, Chrome, and Brave).

`ailed to load resource: net::ERR_BLOCKED_BY_CLIENT
play.google.com/log?format=json&hasfast=true&authuser=0:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
play.google.com/log?format=json&hasfast=true&authuser=0:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
play.google.com/log?format=json&hasfast=true&authuser=0:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
rs=AA2YrTstZieUcIRJsHgW4g1D6WRCneCt9Q:197 
        
        
       POST https://play.google.com/log?format=json&hasfast=true&authuser=0 net::ERR_BLOCKED_BY_CLIENT`

On a new account (without pro) it works.

**Comment by sorinbrindusescu** [comment]
I have the same error.

**Comment by AntonioTannoury** [comment]
I think for now, for those having deadlines, standard colab accounts are working fine.
So you might think about using it although having limited resources.

**Comment by ssyigitarslan** [comment]
I have the same error.

**Comment by MrcBalla** [comment]
same error with colab pro

**Comment by uestcrbx** [comment]
the same error
I want to kown how to solve it.

**Comment by Windy0Star** [comment]
> How long will it take to be fixed? I have a deadline in the next few hours.

me too! my DDL is last Monday, but I just started to use Colab and uploaded the data yesterday night, It's very urgent. I just paid to upgrade to pro+ yesterday and didn't expect to run into this today, terrible experience.

**Comment by wolfassi123** [comment]
> @AidaRostamza I think for now, for those having deadlines, standard colab accounts are working fine. So you might think about using it although having limited resources.

No it's not working on the regular colab. This is frustrating tbh.

**Comment by AidaRostamza** [comment]
@wolfassi123 By using another Gmail account you can have access to the standard colab resources

**Comment by cperry-goog** [comment]
Thanks for flagging this, we had a partial outage that is now resolved. Appreciate everyone jumping on this thread.
