### ISSUE TITLE
Colab can't connect to runtime

### ISSUE THREAD

**Issue by FloFive** [googlecolab/colabtools#4588]
Hi everyone,

I am in a bit of a trouble this morning. I need to run some code on google colab, and usually it goes nicely. Except that since this morning, I find it impossible to connect to the runtime. regardless of whether I want to run on CPU, GPU etc.

I get no real error message, but it's just stuck on connecting.

I really can't figure out what's up. And google services seem to be up.

I deleted cookies, added colab to third party cookies, and disabled my chrome ext. Everything is usually running okay on chrome. I tried other browser, but same problem. I've asked colleagues to try running some code on their colab, but from the same kind of office computer as me, and it went well.

Help ?

**Comment by ssyigitarslan** [comment]
I have same error.

**Comment by sorinbrindusescu** [comment]
I have the same error.

**Comment by MrcBalla** [comment]
same issue here

**Comment by Windy0Star** [comment]
same issue here, unfortunately, today I need to use colab to solve my course work and last week is DDL. I try my best to connect the CPU or GPU but it not useful, I had just pay for the pro+ server yesterday.

**Comment by Windy0Star** [comment]
the error message is "await connected: disconnected
Error: await connected: disconnected"

**Comment by recycletechno** [comment]
Its strange that free accounts with small RAM work fine, but I need more resources to run my thesis experiments - that's why I paid for Colab Pro and it does not work starting from today

**Comment by uestcrbx** [comment]
The same error. How to slove this problem

**Comment by cmdaniels** [comment]
I have the same problem. It was working fine earlier today but then stopped working around the time of your first posting. My network connection is fine. I've tried different browsers, different devices, different notebooks but nothing changes. I'm not using a VPN or firewall. Sometimes I can see in the browser console that it successfully connects, but the UI does not reflect that.

**Comment by cperry-goog** [comment]
Thanks for flagging - we had a partial outage earlier this morning that is now resolved. Apologies.

**Comment by woshidongzhe** [comment]
The same error. How to slove this problem

**Comment by AshmanP12** [comment]
I am having the same error now... ugh

**Comment by prajwal9773** [comment]
same issue , I am stuck in the middle and it is  not connecting to runtime

**Comment by mtmatt** [comment]
same issue
