### ISSUE TITLE
Failed to execute cell. Could not send execute message to runtime: Error: await connected: disconnected await connected: disconnected Error: await connect

### ISSUE THREAD

**Issue by rozanhamzeh9821** [googlecolab/colabtools#4591]
await connected: disconnected
Error: await connected: disconnected
    at https://ssl.gstatic.com/colaboratory-static/common/f78d3c46c7be89bc2afe86f025e3f824/external_binary.js:7025:426

**Comment by cperry-goog** [comment]
Thanks for flagging, we had a partial outage earlier this morning which is now resolved.
