### ISSUE TITLE
"Pay As You Go" not working

### ISSUE THREAD

**Issue by mr-palesleazywind** [googlecolab/colabtools#4592]
I've been charged for "Pay As You Go" plan but I can see "You are not subscribed" and also on the "Choose the Colab plan that's right for you" I can see "You currently have 0 compute units."

**Comment by cperry-goog** [comment]
Can you submit feedback in product and we can take a look.

**Comment by katlyn-edwards** [comment]
For what it's worth - pay as you go is a one time charge, not a recurring subscription, so "you are not subscribed" is correct. Do file in product feedback so we can look into the "0 compute units" issue.

**Comment by mr-palesleazywind** [comment]
Hi,If this is the way you provide the service then please cancel my payment. I am not interested in anymoreRegards, PrzemekW dniu 2024-05-23 20:42:11 użytkownik Katlyn Edwards  napisał:For what it's worth - pay as you go is a one time charge, not a recurring subscription, so "you are not subscribed" is correct. Do file in product feedback so we can look into the "0 compute units" issue.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
