### ISSUE TITLE
Run time crashes during execution

### ISSUE THREAD

**Issue by pacificoceanmist** [googlecolab/colabtools#4593]
Describe the current behavior
I'm using colab for a network analysis on a large gap (26GB file size, 46 Million edges). I was running the Edmonds algorithm using RAPID cuGraph NetworkX, and it crashed upon execution (11th cell on my colab notebook) and gave this message `Your session crashed for an unknown reason.`. I'm using A100 GPU to run my Colab.

Describe the expected behavior
I expect to use GPU accelerated network analysis generating minimum spanning arborescence (MSA) tree via Edmonds algorithm.

What web browser you are using
Safari. MacOS is all updated to current versions.

Additional context
Runtime log
![Screenshot 2024-05-22 at 8 46 03 PM](https://github.com/googlecolab/colabtools/assets/64761042/3833c785-189c-4ce6-9b3f-ec2e84843edb) 
https://colab.research.google.com/drive/17DT5z0INqSMg__KPm-oYuyqH-TSSKS2G?usp=sharing

View of Resource
![Screenshot 2024-05-22 at 9 09 26 PM](https://github.com/googlecolab/colabtools/assets/64761042/bfe64a7a-5f93-4b7b-90d0-f2b5e187d38e)

**Comment by cperry-goog** [comment]
Can you open up access to that notebook?

**Comment by pacificoceanmist** [comment]
> Can you open up access to that notebook?

Updated access, sorry about that

**Comment by cperry-goog** [comment]
notebook appears to be deleted
