### ISSUE TITLE
Google Colab Pro Runtime Disconnection Issue

### ISSUE THREAD

**Issue by ssyigitarslan** [googlecolab/colabtools#4594]
Yesterday, my connection to the Google Colab Pro runtime was interrupted. It had been resolved about 11-12 hours ago, but now I am experiencing issues connecting to the runtime again. The notebook remains stuck at the cell where the Google Drive is being mounted. It also gets stuck when trying to execute any other command.

I have tried both Microsoft Edge and Chrome.

**Comment by cperry-goog** [comment]
Can you submit feedback internally and reference this issue and we can take a look.
