### ISSUE TITLE
colab scroll and hanging issue 

### ISSUE THREAD

**Issue by Maheshushir** [googlecolab/colabtools#4596]
current behavior 
while opening any file in colab i am unable to scroll up or down with my mouse or touchpad. the tool becomes useless while reading through a document 

expected behavior 
i want to use it normally. there is no hardware issue with my laptop or anything. i am able to use everything properly but this problem is same 

i am using chrome browser

**Comment by DustanGiles** [comment]
Same issue here

**Comment by Maheshushir** [comment]
:( please update me if you found any solution to this

**Comment by EvanWiederspan** [comment]
Are you still seeing this issue in incognito mode with all extensions disabled?

**Comment by DustanGiles** [comment]
Yes I am seeing the issue in incognito mode with all extensions disabled.

**Comment by Maheshushir** [comment]
not yet solved too. i am somehow managing by manual scrolling

**Comment by DustanGiles** [comment]
I just use microsoft edge lol

**Comment by Maheshushir** [comment]
is it working on that ?

**Comment by DustanGiles** [comment]
Yes it is

**Comment by cperry-goog** [comment]
When you say "while opening any file in colab" do you mean any notebook file in Colab, or are you referring to the file viewer in Colab?

**Comment by Maheshushir** [comment]
while using new notebook and also while reading existing file.

**Comment by cperry-goog** [comment]
How big are these files? I use Colab every day and have never seen this behavior, so confused as to how to reproduce it.

**Comment by Maheshushir** [comment]
these files are pretty small , even less than 10 mb. its issue on chrome only.
