### ISSUE TITLE
I think my first-order-model-demo is not listening to me

### ISSUE THREAD

**Issue by Matti763** [googlecolab/colabtools#4597]
**Describe the current behavior**
When i tried to put any deepfake video on first-order-model-demo, it doesn't send me the video

**Describe the expected behavior**
I was expecting my first-order-model-demo to give me any deepfake template i wanted.

**What web browser you are using**
Microsoft Edge

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -

**Comment by Matti763** [comment]
Um, hello? AliaksandrSiarohin? Are you here?

**Comment by EvanWiederspan** [comment]
This doesn't seem like a Colab issue, I would reach out to the notebook author instead
