### ISSUE TITLE
The colab suggestions feature is not working while writing code

### ISSUE THREAD

**Issue by sohamghewari** [googlecolab/colabtools#4599]
The suggestions feature of the google colab is not working even after pressing ctrl plus space while writing the code. 

When I press ctrl and space, the tab shows, "no suggestions.". I want to resolve this bug as suggestions help a lot while writing a code especially for beginners like me.

**Comment by EvanWiederspan** [comment]
You do have to be connected to a runtime in order to get suggestions, are you still never seeing them when you're connected?

**Comment by danielfoerster2** [comment]
I have the same issue. It worked fine until a couple of weeks ago, and then stopped working. I don't remember having changed any setting. In any case, it also doesn't work when connected to a runtime.
