### ISSUE TITLE
Runtime won't connect

### ISSUE THREAD

**Issue by ArEnSc** [googlecolab/colabtools#46]
^

**Comment by blois** [comment]
Any information such as error message or browser console errors?

**Comment by blois** [comment]
Also Help -> Send Feedback with a screen of what error appears may help us investigate.

**Comment by ArEnSc** [comment]
![screen shot 2018-02-02 at 5 38 29 pm](https://user-images.githubusercontent.com/6252325/35758096-28d3e94c-0840-11e8-91ea-e04dfcb049b2.png)

**Comment by blois** [comment]
If it continues to fail, can you try loading from an incognito window?

**Comment by ArEnSc** [comment]
Hey that works! I think its because I accidentally used a session from a link I found on kaggle, and it expired. Thanks!
