### ISSUE TITLE
Runtime keep crashing when large file is loaded

### ISSUE THREAD

**Issue by rajans** [googlecolab/colabtools#460]
Runtime dies whenever I load large file before training. This is not happening all the time and when I logout and log back in it works some times. I tried with gc.collect() etc. but no luck and I can't keep logging out and back in and run all the steps all over again. This is frustrating.

Memory Allocation Error:

Timestamp	Level	Message
Mar 5, 2019, 10:42:37 AM	WARNING	WARNING:root:kernel e6de7a89-0274-4141-90bc-1ea7f400b97d restarted
Mar 5, 2019, 10:42:37 AM	INFO	KernelRestarter: restarting kernel (1/5), keep random ports
Mar 5, 2019, 10:42:32 AM	WARNING	tcmalloc: large alloc 2847006720 bytes == 0x7f1595f0e000 @

**Comment by metrizable** [comment]
Since this issue was filed a while ago, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
