### ISSUE TITLE
Disconected with colab pro+

### ISSUE THREAD

**Issue by mcatalin99** [googlecolab/colabtools#4600]
I want to train more time consuming model (8-9h) so I bought colab pro+ so I can do that. After about 5 hours I am disconnected from the host, but the code is still running, and after another 3-4 hours the session is completely stopped. This shows that the platform is very bad considering that you pay 50 euros and it says that it can run 24 hours when the browser is closed (I didn't close the browser at all and I use Brave).

**Comment by EvanWiederspan** [comment]
I don't think we'll be able to look into this from GitHub, can you file in-product feedback instead at Help -> Send Feedback?
