### ISSUE TITLE
Figshare download forbidden

### ISSUE THREAD

**Issue by knc6** [googlecolab/colabtools#4601]
Hi,

Often but not always I cannot download files from from Figshare in colab

e.g. ```!wget https://ndownloader.figshare.com/files/38522315 -O id_prop.json.zip```

![image](https://github.com/googlecolab/colabtools/assets/16902896/e2486a82-77c1-42db-bd6d-54c0ba62e282)

About a couple months ago, such commands worked fine.

**Comment by mayankmalik-colab** [comment]
I don't think it is Colab specific issue. `403` is the response from their server. Maybe save the file in google drive and mount in the runtime.

**Comment by ogrisel** [comment]
I think those 403 errors are specific to HTTP requests coming from a Google Colab node. Several people reported the same problem at scikit-learn/scikit-learn#28297 while those cannot be easily reproduced outside of Google Colab.
