### ISSUE TITLE
504 Gateway Time-out error when trying to use defooocus in colab

### ISSUE THREAD

**Issue by stanz80** [googlecolab/colabtools#4603]
**Describe the current behavior**
I launch the interface defocus in colab, it loads than I click public url - gradio.live link and I get the above 504 error

**Describe the expected behavior**
I expect defooocus to launch correctly on colab like it used to run till today

**What web browser you are using**
Chrome

**Comment by EvanWiederspan** [comment]
Can you include the notebook you're running, and the error that you're seeing?
