### ISSUE TITLE
I can't upgrade colab i still have git version 2.34.1

### ISSUE THREAD

**Issue by Felipecl22** [googlecolab/colabtools#4607]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

I can't upgrade to the latest version of colab.

**Comment by mayankmalik-colab** [comment]
I am assuming you want to upgrade git. Can you try the following:
```
%%shell
sudo add-apt-repository -y ppa:git-core/ppa
sudo apt-get update
sudo apt-get install git -y
```
