### ISSUE TITLE
require.js enabled by default?

### ISSUE THREAD

**Issue by intuitivetextmining** [googlecolab/colabtools#461]
Should require.js be enabled by default?

The main jupyter notebook and the mybinder service does enable it.

Not having it enabled means we get issues like this: [issue 455](https://github.com/googlecolab/colabtools/issues/455)

Not only are there benefits to having it enabled, it also brings colab into parity with the wider jupyter notebook ecosystem.

**Comment by blois** [comment]
Colab tries to minimize the public APIs which are provided by default for backwards compatibility reasons and to minimize output loading time. Once something like this is added then it must be maintained for all time.

An example of using pre_run_cell to configure it in every outputframe is:
```python
from IPython.display import HTML

def add_require_js():
  display(HTML('<script src="/static/components/requirejs/require.js"></script>'))

get_ipython().events.register('pre_run_cell', add_require_js)
```

Classic Jupyter Notebooks does include require.js by default but newer environments are avoiding it:
 - JupyterLab: jupyterlab/jupyterlab#1188
 - nteract: nteract/nteract#2743
