### ISSUE TITLE
The option of AI assist doesn't appear in my Colab pro

### ISSUE THREAD

**Issue by hulamo** [googlecolab/colabtools#4612]
**Is your feature request related to a problem? Please describe.**
The option of AI assist doesn't appear in my Colab pro

**Comment by katlyn-edwards** [comment]
Hey there! Can you file in-product feedback (Help -> Send Feedback) and then reference this GitHub issue? It's a bit easier for us to debug from there.

Thanks!

**Comment by cperry-goog** [comment]
It's likely you're using a Workspace account (launching to those in the next couple weeks) or you're in a country where we haven't launched AI features, or your account is <18.
