### ISSUE TITLE
open json file to view on click in the JSON file it disappears!

### ISSUE THREAD

**Issue by pleabargain** [googlecolab/colabtools#4614]
**Describe the current behavior**
click on json file left side to open. right side json file appears. on click on the JSON file on the right, the JSON disappears
https://www.youtube.com/watch?v=L1zIkyCr7aI

**Describe the expected behavior**
I should be able to view and edit the json

**What web browser you are using**
chromebook
Version 125.0.6422.140 (Official Build) (64-bit)

**Additional context**
[Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.]
 - 
 - (https://colab.research.google.com/drive/1WvIKoRomN9ROupiRRbrU6QwGBe4uL5mE?usp=sharing)

**Comment by EvanWiederspan** [comment]
Forgot to update this issue, but this should have been fixed a while ago now. Thanks for reporting!
