### ISSUE TITLE
Windows incopability

### ISSUE THREAD

**Issue by alex-ber** [googlecolab/colabtools#462]
On Windows with google-colab installed the following code failes:

`from google.colab import files`
`uploaded = files.upload()`

**Comment by alex-ber** [comment]
[_system_commands.zip](https://github.com/googlecolab/colabtools/files/2939943/_system_commands.zip)

Attached fixed file.

The fixes are the following:

1. On Windows there in no pty, so

`try:`
`    import pty`
`except ImportError:`
`    # Failed to import experimental pty support`
`    pass`


2.  On Windows there in no termios, so
`try:`
`    import termios`
`except ImportError:`
`    # Failed to import experimental termios support`
`    pass`

3. Windows does not provide SIGKILL, so il lin 251(function _monitor_process)
`if p.poll() is None:		    `
`		    # Windows does not provide SIGKILL, go with SIGTERM then`
`		    _SIGKILL = getattr(signal, 'SIGKILL', signal.SIGTERM)`
`		    p.send_signal(_SIGKILL)`

4. And with the same reasone on line 380 _INTERRUPTED_SIGNALS definition should be changed to

`_INTERRUPTED_SIGNALS = (`
`    signal.SIGINT,`
`    signal.SIGTERM,`
`    signal.SIGKILL,`
`) if hasattr(signal, 'SIGKILL') else (`
`    signal.SIGINT,`
`    signal.SIGTERM,`
`)`

**Comment by craigcitro** [comment]
Unfortunately, we don't really have bandwidth to support installing or using colabtools outside of Colab itself.
