### ISSUE TITLE
Output doesn't get rendered, Issue is not fixed even after session is cleared.

### ISSUE THREAD

**Issue by SominZex** [googlecolab/colabtools#4622]
![Screenshot (84)](https://github.com/googlecolab/colabtools/assets/69101676/2db3a83d-dfe7-4220-abd3-4f51093b3915)

Having a bug. When I run the code, it doesn't show any output. Even If I clear the session & cache its not fixed

**Comment by EvanWiederspan** [comment]
Can you share the notebook, and what you expect the output to be? Do you get output when you run it in a different notebook product like Jupyterlab?

**Comment by SominZex** [comment]
Yes, everything works fine in Jupyterlab. Issue is in Colab, but I found a solution somebody suggested, It works in Incognito mode.

**Comment by SominZex** [comment]
> Can you share the notebook, and what you expect the output to be? Do you get output when you run it in a different notebook product like Jupyterlab?

Yes. It's resolved now. Thank you.

**Comment by cperry-goog** [comment]
For the future, just noting that sometimes browser extensions can conflict with Colab which can be removed by working in incognito mode.
