### ISSUE TITLE
Stoping session without any problem

### ISSUE THREAD

**Issue by leo83** [googlecolab/colabtools#4624]
**Describe the current behavior**
After 20 hours of working session stoped to execute without any error. This was payed account and of course the was positive balance.
This behaviour repeated several times.

**Describe the expected behavior**
A session works until it gets error in code or no money left.

**What web browser you are using**
Chrome

**Additional context**

**Comment by EvanWiederspan** [comment]
Can you file in-product feedback instead at Help -> Send Feedback? This will give us the info needed to investigate what happened to your session.
