### ISSUE TITLE
ERROR: Unknown command line flag 'xla_latency_hiding_scheduler_rerun'

### ISSUE THREAD

**Issue by byczysmaster** [googlecolab/colabtools#4628]
When I tried runing automatic1111 with sd then i've got some "chardet" error which i fixed by typing "!pip install chardet", after I got this error problem

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1718112270.002079   12593 pjrt_api.cc:100] GetPjrtApi was found for tpu at /usr/local/lib/python3.10/dist-packages/torch_xla/lib/libtpu.so
I0000 00:00:1718112270.002200   12593 pjrt_api.cc:79] PJRT_Api is set for device type tpu
I0000 00:00:1718112270.002207   12593 pjrt_api.cc:146] The PJRT plugin has PJRT API version 0.46. The framework PJRT API version is 0.46.
E0611 13:24:30.113886980   12730 oauth2_credentials.cc:176]            Call to http server ended with error 404 [].
ERROR: Unknown command line flag 'xla_latency_hiding_scheduler_rerun'

**Comment by mahmoudhantash** [comment]
the below code is facing same issue on TPUv2 env ,  it's working well on CPU and GPU but colab session crash with ERROR: Unknown command line flag 'xla_latency_hiding_scheduler_rerun'

from langchain_huggingface import HuggingFaceEmbeddings
em =  HuggingFaceEmbeddings()

**Comment by brand17** [comment]
have the same issue here https://colab.research.google.com/drive/1bEySvl3HagayCXQPxHE53Z-fM5UyKuaV?usp=sharing

**Comment by Samia1117** [comment]
Why was this closed? Have the same issue on TPU (but not on GPU)
