### ISSUE TITLE
Typo in the "Setup the layers"

### ISSUE THREAD

**Issue by sjagat** [googlecolab/colabtools#463]
Original 
"hidden" tf.keras.layers.Dense— A densely connected layer of 126 neurons. Each neuron (or node) takes input from all 784 nodes in the previous layer, weighting that input according to hidden parameters which will be learned during training, and outputs a single value to the next layer.

Number of neurons should be 128.

**Comment by craigcitro** [comment]
Thanks for the report! I've sent a fix upstream.
