### ISSUE TITLE
Multiproceesing not working after switching to Pro

### ISSUE THREAD

**Issue by pawelSoftware** [googlecolab/colabtools#4632]
**Describe the current behavior**
Torch Multiprocessing python programs are not working anymore. Simple program: 

`import torch.multiprocessing as mp

mp.set_start_method('spawn', force=True)

def worker(rank):
    print(f"Proces {rank}: Witam z procesu!")

num_processes = 4

processes = []
for rank in range(num_processes):
    p = mp.Process(target=worker, args=(rank,))
    p.start()
    processes.append(p)

for p in processes:
    p.join()
print('program ends')
`

Prints only last log "Program ends". Problem was not occuring on free version

**Describe the expected behavior**

multiprocessing works. Program will print log for every working thread

**What web browser you are using**
Chrome

**Comment by mayankmalik-colab** [comment]
Can you tell us what runtime did you use - CPU, GPU, TPU and  and more details? . I can't reproduce it unfortunately.
