### ISSUE TITLE
this code doesn't work now-----cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver()

### ISSUE THREAD

**Issue by Barooni-saeede** [googlecolab/colabtools#4637]
cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver()

last days I worked with this code but since last day it doesn't work

ValueError: Please provide a TPU Name to connect to.

why?

**Comment by cperry-goog** [comment]
We'll need a minimal reproducible notebook to investigate, impossible to know what's happening with just the code snippet, though if you're calling an external TPU cluster this would not be a Colab issue.

**Comment by Barooni-saeede** [comment]
this is my code with error but some days ago I didn't have this error with
this code

**Comment by cperry-goog** [comment]
I need a reproducible notebook to investigate

**Comment by Barooni-saeede** [comment]
So, what do I do for this

**Comment by sagelywizard** [comment]
Please write a Colab notebook that demonstrates the issue, make it public, and share a link here.
