### ISSUE TITLE
Unable to download created files in colab

### ISSUE THREAD

**Issue by DevinRShaw** [googlecolab/colabtools#4638]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by Fortune-zita** [comment]
went i click on upload file, the command drag your file here doesn't execute

**Comment by cperry-goog** [comment]
Can you verify this doesn't work in an incognito window? You could have browser extensions conflicting?

Else, please report your OS and browser version.
