### ISSUE TITLE
Icons not visible

### ISSUE THREAD

**Issue by bivas015** [googlecolab/colabtools#4642]
**current behavior**
for the past 2 months icons have not loaded whenever I opened colab in Chrome. signed in with this account (bivas015@gmail.com).

**Describe the expected behavior**
Icons should be visible as normally.

**web browser I am using**
Chrome

**Additional context**
This issue is not happening when I open colab using same account in other browser. This is only happening in chrome. Again when I sign in chrome with different account this issue is not there.
![Screenshot from 2024-05-26 21-57-41](https://github.com/googlecolab/colabtools/assets/82586713/749a9e88-2fb0-48ea-99ac-78b8fe2e97f8)

**Comment by katlyn-edwards** [comment]
Can you try "hard refreshing" ?

* Hold down Ctrl
* Click the Reload button
* Or, press F5

Alternatively it seems like something is incorrectly cached, you could try clearing your cookies/cache in Chrome and see if that fixes it?

**Comment by yumemio** [comment]
HI @bivas015,

My guess is that font-related add-ons may be causing the issue. The icons are provided as a custom font, so add-ons or browser settings can prevent the browser from rendering them properly. (By the way, Firefox natively supports overriding site-provided fonts with a local style, which is how I came across this issue😁)
Disabling the add-ons may help!

**Comment by cperry-goog** [comment]
Thanks @yumemio !

**Comment by bivas015** [comment]
@yumemio Thanks.
my issue is resolved.
