### ISSUE TITLE
Google Colan will not connect to a runtime

### ISSUE THREAD

**Issue by aavideora** [googlecolab/colabtools#4643]
**Describe the current behavior**
My google colab will not connect to a runtime. I even have a monthly subscription for google colab pro. This has been going on for a few days. When I open any of my notebooks with a different gmail, which is not subscribed to the monthly subscription, it connects.

**Describe the expected behavior**
My google colab notebooks should connect to a GPU. Especially since I am a paying customer. 

**What web browser you are using**
Chrom

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
Please submit feedback in product and reference this issue, thanks.
