### ISSUE TITLE
 Issue with Runtime Termination in Colab Pro and Pro+

### ISSUE THREAD

**Issue by bahcecimuhammed** [googlecolab/colabtools#4646]
Dear Colab Support Team,

I hope this message finds you well. I am writing to report an issue I have encountered with the Colab Pro and Pro+ services, which has caused significant inconvenience and disruption to my work.

Yesterday, I upgraded to Colab Pro and initiated my work. However, after 16 hours of continuous operation, the runtime was abruptly terminated, resulting in the loss of my progress and causing considerable frustration. Hoping for a more reliable experience, I further upgraded to Colab Pro+. Unfortunately, I encountered the same issue with the runtime being terminated again, leading to another instance of inconvenience and disruption.

As a paying customer, I expected a more stable and uninterrupted service. The recurrent termination of the runtime has not only disrupted my workflow but also led to a loss of valuable time and resources. I am seeking support and a resolution to this issue to ensure that I can fully utilize the services for which I have paid.

I would greatly appreciate your prompt attention to this matter and any assistance you can provide to prevent such issues in the future.

Thank you for your understanding and support.

Best regards,

Muhammed Bahçeci

**Comment by cperry-goog** [comment]
Runtimes last up to 24 hours in Colab Pro, and if you have enough compute units, will last 24 hours in Colab Pro+. If you encounter interruptions prior to 24 hours, please submit feedback in product (Help > Submit feedback) and we can investigate further. We cannot diagnose from GitHub.
