### ISSUE TITLE
I'm on Colab pro and my runtime keeps on disconnecting

### ISSUE THREAD

**Issue by mikmikthemimic** [googlecolab/colabtools#4648]
**Describe the current behavior**
I am training my model but after a few hours over the 24th hour mark of training, my runtime abruptly disconnects. This forces me to have to start retraining again. This has happened twice already, each time time, it happens a few hours (around 2) after the 24 hours of training.

**Describe the expected behavior**
I don't really expect the runtime to disconnect as I do have a cell that is running as it disconnects.

**What web browser you are using**
I'm currently using brave browser

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
Here is the link to the notebook: 
https://colab.research.google.com/drive/1uH91QvlczNdavBA_pApjd7weANxf4DqB?usp=sharing

**Comment by cperry-goog** [comment]
Runtimes last up to 24 hours. If you want a runtime that lasts indefinitely, you can manage your own custom GCE VM: https://research.google.com/colaboratory/marketplace.html
