### ISSUE TITLE
cant mount drive on colab

### ISSUE THREAD

**Issue by yacinedexter** [googlecolab/colabtools#465]
When i enter my authorization code and i hit enter it doesn't work it keeps running. It was working for me before and then it stopped since 2 or 3 weeks ago
![screenshot from 2019-03-07 09-51-46](https://user-images.githubusercontent.com/25806178/53964997-5e34e700-40be-11e9-985e-9ed79221241f.png)

**Comment by craigcitro** [comment]
I believe this is a dupe of #424 -- if you can provide any of the info we're looking for there to help debug, please do!
