### ISSUE TITLE
Colab Pro runtime randomly disconnects and can't reconnect automatically

### ISSUE THREAD

**Issue by hasanakg** [googlecolab/colabtools#4654]
**Describe the current behavior**
I'm using Colab Pro and my runtime randomly disconnects after 10-15 minutes and cannot reconnect, therefore it's impossible to run analysis, and it keeps wasting my compute units.

**Describe the expected behavior**
Colab Pro runtime shouldn't disconnect after 10-15 minutes.

**What web browser you are using**
Chrome

**Additional context**
Screenshot of infinite "connecting" status:
<img width="363" alt="Screenshot 2024-06-23 at 22 36 51" src="https://github.com/googlecolab/colabtools/assets/2556801/cf5c0a46-f724-4723-9680-c24e23877533">

**Comment by juliocesardaxavante** [comment]
Same problem here...

**Comment by cperry-goog** [comment]
Can you submit feedback in product? I can't diagnose this issue from GitHub.
