### ISSUE TITLE
Lost 2 days of work in colab notebook

### ISSUE THREAD

**Issue by CY-dev** [googlecolab/colabtools#4655]
**Describe the current behavior**
I added multiple cells with class definitions and test codes and executed them on Friday and Saturday. Now when I reopen the notebook today, they are all gone with no trace in revision history or notebook versions. https://colab.research.google.com/drive/1H_xk6aR-qpYfWTcvWoYAgHC2GV8N48FN#scrollTo=hlu7H-W-KYPT. 

**Describe the expected behavior**
The notebook should contain all my changes up to today.

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
If auto-saving ever gets interrupted, you should see a red error message "Saving failed" - please do watch out for that error and manually trigger a save event at that time. We are working to reduce the probability of occurrence of these types of errors in the future.

You can submit feedback in product if this happens again.
