### ISSUE TITLE
colab could not install 1.2.4 pandas

### ISSUE THREAD

**Issue by my-shaoyang** [googlecolab/colabtools#4657]
**Describe the current behavior**
My steps are as follows
The first step is to uninstall the current pandas !pip uninstall pandas
The second step is to run the command !pip install pandas==1.2.4
The following error occurs：
Building wheels for collected packages: pandas
  error: subprocess-exited-with-error
  
  × Building wheel for pandas (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for pandas (pyproject.toml) ... error
  ERROR: Failed building wheel for pandas
Failed to build pandas
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects

**Describe the expected behavior**

**What web browser you are using**
I use Firefox 

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mayankmalik-colab** [comment]
Pandas 1.2.4 was launched in 2021 and it looks work on python 3.10. Check the `Programming Language` section on left  in https://pypi.org/project/pandas/1.2.4/ .
