### ISSUE TITLE
Unable to save notebooks to Github.

### ISSUE THREAD

**Issue by chopadeabhishek** [googlecolab/colabtools#4658]
**Describe the current behavior**
Unable to save my colab notebooks to Github using the 'Save a copy in Github' option in the File menu.

**Describe the expected behavior**
Once done with my notebook, I want to save a copy of the Notebook in my public Github repo. Upon using the 'Save a copy in Github' option, I got  a pop-up to authorise colab to access my Github. Despite providing the said access, when I hit the save option, there are no files in my repo. I also get no feedback from colab, whether the save was successful or not. No warnings, no errors, no alerts, nothing!
There are no files in my Github repo as well. 

**What web browser you are using**
Google Chrome - Version 126.0.6478.114 (Official Build) (64-bit) on Ubuntu.
Also tried it on Google Chrome - Version 125.0.6422.76 (Official Build) (arm64) on MacOS.

**Comment by panda667** [comment]
I'm using Colab (and Github) in Mozilla Firefox 127.0.2 (64-bit) and the upload-to-Github function works fine. I've used the function several times in the past few weeks and have had no problems.
