### ISSUE TITLE
Unknown white line across lines of code

### ISSUE THREAD

**Issue by lukkwen** [googlecolab/colabtools#4660]
![Screenshot 2024-06-26 at 2 26 27 PM](https://github.com/googlecolab/colabtools/assets/97434155/bed3d304-aa67-4c36-ba98-fe66416885f3)

As shown in the image above, there exists this white block that is covering lines of codes.

Currently using Chrom.

**Comment by cperry-goog** [comment]
Can you confirm this happens in an incognito window?

**Comment by lukkwen** [comment]
@cperry-goog has been resolved on its own thanks
