### ISSUE TITLE
Could we bump duckdb to 1.0.0?

### ISSUE THREAD

**Issue by guenp** [googlecolab/colabtools#4661]
**Is your feature request related to a problem? Please describe.**
The latest version of `duckdb` is 1.0.0! It just came out at the beginning of this month. See https://duckdb.org/2024/06/03/announcing-duckdb-100.html

**Describe the solution you'd like**
It would be great if Google Colab could have `duckdb` 1.0.0 installed by default. Right now it's on 0.10.3.

**Describe alternatives you've considered**
`pip install --upgrade duckdb` at the start of the notebook is a good workaround.

**Additional context**
The next version, 1.1.0, is planned for September: https://duckdb.org/docs/dev/release_calendar.html

**Comment by mayankmalik-colab** [comment]
Tracked internally at b/349747964

**Comment by guenp** [comment]
@cperry-goog Just wanted to check in on this, should we wait and bump to 1.1.0 in September?

**Comment by mayankmalik-colab** [comment]
@guenp - you can see the updated version - 1.0.0- on Wednesday.

**Comment by Hasena386** [comment]
Any plans to fix this soon…?
