### ISSUE TITLE
payment failed!

### ISSUE THREAD

**Issue by mnoorchenarboo** [googlecolab/colabtools#4664]
Error
One or more dependencies could not be loaded.
payments is not defined
ReferenceError: payments is not defined

**Comment by katlyn-edwards** [comment]
Does this happen in an incognito window? Do you happen to have an ad blocker or extension installed that might interfere with Google Payments loading?

**Comment by mnoorchenarboo** [comment]
I tried with other browser and still not working but I tried with other Gmail account and it works. can you please let me know if you have any idea how can I solve this error?

**Comment by EvanWiederspan** [comment]
Can you instead file in-product feedback at Help -> Send feedback? And include a link to this issue so that we can investigate further
