### ISSUE TITLE
Pro+ Runtime immediately stops executing, Message: "Waiting to finish the current execution", Runtime: "Connecting", whenever browser closes.

### ISSUE THREAD

**Issue by MichaelShawJ** [googlecolab/colabtools#4666]
**Describe the current behavior**
I can delete and start a new runtime. It will run fine, executions happening twice per second. As soon as I exit the browser or the computer goes to sleep, the code snags and says Message at bottom of screen: "Waiting to finish the current execution", and the Runtime message in the top right says: "Connecting", whenever browser closes. The code, which should take 2 hours to run, is stalled an unrecoverable. It does not finish execution. All the data is lost. 

**Describe the expected behavior**
Because I am a Pro+ subscriber/user, I would expect the Runtime to continue even when I close the browser, for up to 24 hours.  

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
https://colab.research.google.com/drive/1yzCA91IgLgFBvpDMKgLvY78z2oiuHYZ4?usp=sharing

**Comment by juliocesardaxavante** [comment]
Yes, this problem is happening to me too and other users. Please Colab team: we need feedback on the normalization of this service. I'm wasting a lot of time restarting my project several times a day.

**Comment by Mitali-N** [comment]
did this get resolved? I just bought Pro+ for background execution, and I, too, am facing runtime getting disconnected as soon as the computer goes to sleep.

**Comment by cperry-goog** [comment]
Can you file feedback in product and reference this issue and we can take a look?
