### ISSUE TITLE
Pay-As-You-Go Compute Units Not Reflecting in Google Colab Account

### ISSUE THREAD

**Issue by MahmudAbdullah55** [googlecolab/colabtools#4668]
Describe the current behavior:
A few days ago, I purchased Google Colab Pro and received 100 compute units. After using these units, I purchased additional units using the Pay-As-You-Go option. The charge was successfully processed and deducted from my card. However, the additional compute units are not showing up in my account, and my balance has not been updated. When trying to connect to the GPU, it still reflects the previous balance.

Describe the expected behavior:
After purchasing the additional compute units, they should immediately reflect in my Google Colab account, allowing me to use the GPU without any issues.

What web browser are you using:
Google Chrome

Additional context:
I have attached a screenshot of my transaction history showing the successful charge for the additional compute units. Despite this, the units are not reflecting in my account. I have tried refreshing the page and logging out and back in, but the issue persists.

Any assistance in resolving this issue would be greatly appreciated.

![Colab Pay as you go charge deduction transaction](https://github.com/googlecolab/colabtools/assets/174274107/7bd18af7-3aef-44ce-a9f1-4da157628bca)

**Comment by EvanWiederspan** [comment]
We won't be able to diagnose this from Github, please file in-product feedback at Help -> Send Feedback, including a link to this issue. That will give us the information to look at what happened to your CCUs
