### ISSUE TITLE
Files Not Uploading on Colab

### ISSUE THREAD

**Issue by Sebbvl** [googlecolab/colabtools#4669]
I am using Google Chrome. I am a beginner trying to upload a .txt file as an environment variable on Google Colab. Every time the file is being uploaded it disappears and the code does not work without that file. How can I fix this situation?

**Comment by EvanWiederspan** [comment]
To clarify, whenever your VM is deleted and you get a new one, the file system will be reset. Are you saying the file disappears eventually, after getting a new VM, or it disappears right away? If the latter, can you share more detailed repro steps?
