### ISSUE TITLE
Whenever I am running a code, the output is not showing below. I have tried ctrl+m+o too but its not working. Please tell me the other way?

### ISSUE THREAD

**Issue by aanchalsharma07** [googlecolab/colabtools#4670]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
Can you provide a repro notebook that shows the issue? Make sure it is publicly shared so we can view it
