### ISSUE TITLE
Output when executed, it fades away.

### ISSUE THREAD

**Issue by lobnahegazyy** [googlecolab/colabtools#4679]
**Describe the current behavior**
When i press the output button, it runs but it doesn't show any output. the ouput part shows and then a second later it fades away.
![image](https://github.com/googlecolab/colabtools/assets/132402737/83517515-b8e5-45c9-82dc-4b83eb579a78)

**Describe the expected behavior**
what i expect is the output to be shown when its executed.

**What web browser you are using**
Microsoft Edge

**Comment by EvanWiederspan** [comment]
Does this repro for you in incognito mode, with all browser extensions disabled?
