### ISSUE TITLE
Output is not working

### ISSUE THREAD

**Issue by Aira-alice** [googlecolab/colabtools#4680]
![Screenshot (29)](https://github.com/googlecolab/colabtools/assets/174866847/927e4dca-ee8a-42bb-b0d3-8ef9fa73cf1d)

Output is not working

**Comment by EvanWiederspan** [comment]
Can you share the notebook and the specific cell where you're seeing this issue? Make sure it's publicly visible.

Also, does this repro for you in incognito mode, with all browser extensions disabled?
