### ISSUE TITLE
Click event bug

### ISSUE THREAD

**Issue by scriptax** [googlecolab/colabtools#4681]
Click down outside buttons and releasing inside a button behaves as if I clicked the button intentionally. This causes unwanted running of a cell or opening side menus, which is annoying.

Browser: Chrome, Firefox.

**Comment by EvanWiederspan** [comment]
I can't repro this for any button on Chrome (I'm on ChromeOS). Is there a specific button in the UI that you're seeing this for?

**Comment by scriptax** [comment]
> I can't repro this for any button on Chrome (I'm on ChromeOS). Is there a specific button in the UI that you're seeing this for?

![Screenshot 2024-07-14 142202](https://github.com/user-attachments/assets/a2d71b7d-60e4-46ff-89e3-7f81cda987fa)
These are the buttons I'm talking about. Click down somewhere inside a code cell and release with mouse pointer on one of the buttons shown above.

And you're right. I see it's fixed on Chrome.  But it's still there on Firefox.

**Comment by zelliott** [comment]
This is a bug in monaco editor, tracked by https://github.com/microsoft/monaco-editor/issues/4379.
