### ISSUE TITLE
Compute unit disappeared

### ISSUE THREAD

**Issue by troybvo** [googlecolab/colabtools#4684]
my compute unit was at ~500 when I last logged on. Now it's at 200. Somehow 300 computing units just disappeared

**Comment by colaboratory-team** [comment]
Please submit a feedback in product (`https://colab.research.google.com`, then `Help` > `Send feedback`), and then reply here confirming your feedback submission. We'll need to look into your account specifics, and follow up there.

**Comment by troybvo** [comment]
> Please submit a feedback in product (`https://colab.research.google.com`, then `Help` > `Send feedback`), and then reply here confirming your feedback submission. We'll need to look into your account specifics, and follow up there.

I submitted my feedback. Thanks for looking into this.

**Comment by colaboratory-team** [comment]
Thank you @troybvo for submitting an in-product feedback. We'll look into your account, see what happened and respond to your account by email.
