### ISSUE TITLE
Xarray import is broken

### ISSUE THREAD

**Issue by tulsaweathercoder** [googlecolab/colabtools#4685]
**The issue:** I can't import xarray.

**How to reproduce:**
In any colab session (using google chrome) if I type "import xarray" I get a module not found error as follows:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-3-45e55b6321f5>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import xarray

5 frames
[/usr/local/lib/python3.10/site-packages/xarray/core/nputils.py](https://localhost:8080/#) in <module>
     13 # remove once numpy 2.0 is the oldest supported version
     14 if module_available("numpy", minversion="2.0.0.dev0"):
---> 15     from numpy.lib.array_utils import (  # type: ignore[import-not-found,unused-ignore]
     16         normalize_axis_index,
     17     )

ModuleNotFoundError: No module named 'numpy.lib.array_utils'

**Additional Details:**
The default version of xarray is xarray==2023.2.0
Since it seems to be related to the numpy version, we have: numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1718615061894/work/dist/numpy-2.0.0-cp310-cp310-linux_x86_64.whl#sha256=91843c84a6c7fb01afed16468f942dfe32b48184a79039847a16b4459e5735c4 

Ultimately it comes down to numpy.lib.array_utils being missing. 

**What I expect to happen:** Xarray should be able to import without errors. I am not including a link to a colab document because it's just a stock import statement.

**Comment by tulsaweathercoder** [comment]
I don't know why, but even though I am doing the same import it is now working. So I am just going to assume it was a weird local problem. I'll close the issue.

**Comment by EvanWiederspan** [comment]
I do see that it looks like you've installed a different numpy version, that may lead to issues as many libraries require a certain version. xarray imports just fine in a fresh runtime
