### ISSUE TITLE
files.download() failing if run in the same code section where the file was saved

### ISSUE THREAD

**Issue by eyaler** [googlecolab/colabtools#469]
trying to do files.download() on files that were saved in the same code section can result in MessageError: TypeError: NetworkError when attempting to fetch resource (firefox) or MessageError: TypeError: Failed to fetch (chrome). download works fine if run from a subsequent code section

**Comment by metrizable** [comment]
@eyaler Thanks for filing the issue. Unfortunately, I am not able to reproduce it.

Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem since then, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
