### ISSUE TITLE
Fooocus on google colab extremely slow

### ISSUE THREAD

**Issue by pixlgen** [googlecolab/colabtools#4691]
fooocus takes a long time to open then fooocus gui loads even longer, specially the default image takes 15/20 mins, colab was renewed recently.

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
Can you share a repro notebook that shows the issue?
