### ISSUE TITLE
Access of files on google drive too slow

### ISSUE THREAD

**Issue by swaminathanrahul** [googlecolab/colabtools#4692]
Status Before : Running training of models on GPU accessing image data on google drive was fine before. 

Status Now :  Since last 2 days the disk access has given multiple OS error messages and has become very slow! Really very slow! 
This means datasets defined as files on gdrive get very slow and painful to load and many times the code is stuck and times out seemingly in error. 

I have lost hours waiting for computing to end for it just to fail - loosing also my compute credits I bought. 

Browser isnt the issue here -- but its Chrome if you need to know.

**Comment by EvanWiederspan** [comment]
This can sometimes be caused by having too many files in a single folder in your Drive, does https://research.google.com/colaboratory/faq.html#drive-timeout help?
