### ISSUE TITLE
Error in applying Manim

### ISSUE THREAD

**Issue by Matheus071** [googlecolab/colabtools#4693]
Error in applying Manim

Even though there is no error report from the system, the video is produced with 0s of duration. I've already checked the library documentation and the phyton version of colab.

The strangest thing is that the image formation occurs perfectly, only the video production has a problem.

Browser: Chrome

**Comment by mayankmalik-colab** [comment]
Does that work on other platforms/machines? I doubt if this is Colab specific issue.
