### ISSUE TITLE
Unable to connect to google drive

### ISSUE THREAD

**Issue by Jo-Ang** [googlecolab/colabtools#4697]
**Describe the current behavior**
Ran the following code in Google Colab:
from google.colab import drive  
drive.mount('/content/gdrive')  
%cd gdrive/  
%cd MyDrive/ 

I didn't receive an URL as per the expected behaviour but got pop up window with prompts which I followed to give access. And received the following error:
MessageError                              Traceback (most recent call last)
[<ipython-input-1-14edf674a16b>](https://localhost:8080/#) in <cell line: 2>()
      1 from google.colab import drive
----> 2 drive.mount('/content/gdrive')
      3 get_ipython().run_line_magic('cd', 'gdrive/')
      4 get_ipython().run_line_magic('cd', 'MyDrive/')

3 frames
[/usr/local/lib/python3.10/dist-packages/google/colab/_message.py](https://localhost:8080/#) in read_reply_from_input(message_id, timeout_sec)
    101     ):
    102       if 'error' in reply:
--> 103         raise MessageError(reply['error'])
    104       return reply.get('data', None)
    105 

MessageError: Error: credential propagation was unsuccessful

**Describe the expected behavior**
The system will ask for an authorised code which you can find by following the URL link in the message that will be displayed upon running the code 

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
Can you file in-product feedback at Help -> Send Feedback? That will give us more information to be able to debug further
