### ISSUE TITLE
Hosted runtime disconnecting on active Diffusion run.

### ISSUE THREAD

**Issue by ThornsOfire** [googlecolab/colabtools#4698]
**Describe the current behavior**
I am building Disco Diffusion v5.7 on a L4 hosted runtime (Pro+ subscription).  It is in a running state processing iterations, and batches with images being generated and saved to my google drive (drive still has plenty of space). No issues running the notebook. After 30-60 minutes the connection to the runtime is lost with no errors, just the yellow "connecting" dot(s). I have tired using both Firefox and Chrome, cleared cache and cookies, removed all browser extensions, tried adding both a JS element clicker and console print loop on a timer inside a code cell to prevent timeout. I have even physically clicked notebook elements every few minutes instead of using scripts. None of these solutions have worked.

**Describe the expected behavior**
I expect the runtime to stay live for the 24 hour maximum on the Pro+ package without disconnecting (unless I'm doing something wrong which is always possible).

**What web browser you are using**
Chrome Version 126.0.6478.127 (Official Build) (64-bit)
Firefox  Version 128.0 (64-bit)

**Additional context**
Notebook project being used.
https://colab.research.google.com/github/alembics/disco-diffusion/blob/main/Disco_Diffusion.ipynb
All setting are run as default. With the odd issue of the sys path not being appended to AdaBins (pretty sure this is caused by a slow download of AdaBins_nyu.pt. This issue is resolved by running:
#import sys
#sys.path.append('./AdaBins')
Then re-running:
1.3 Install, import dependencies and set up runtime devices

app.log as follows:

Timestamp,Level,Message
"Jul 15, 2024, 9:40:12 PM",INFO,Discarding 5 buffered messages for 559af406-0386-4626-89f7-1b724be64469:87309e0e-619f-4ff7-f8fe-892607155379
"Jul 15, 2024, 9:40:09 PM",INFO,Starting buffering for 559af406-0386-4626-89f7-1b724be64469:87309e0e-619f-4ff7-f8fe-892607155379
"Jul 15, 2024, 8:12:33 PM",WARNING,WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
"Jul 15, 2024, 8:12:21 PM",INFO,Kernel interrupted: 559af406-0386-4626-89f7-1b724be64469
"Jul 15, 2024, 8:12:16 PM",WARNING,"HTTP request sent, awaiting response... "
"Jul 15, 2024, 8:12:16 PM",WARNING,connected.
"Jul 15, 2024, 8:12:16 PM",WARNING,"209.94.90.1, 2602:fea2:2::1"
"Jul 15, 2024, 8:12:16 PM",WARNING,Resolving ipfs.io (ipfs.io)... 
"Jul 15, 2024, 8:12:16 PM",WARNING,--2024-07-16 02:12:16--  https://ipfs.io/ipfs/Qmd2mMnDLWePKmgfS8m6ntAg4nhV5VkUyAydYBp8cWWeB7/AdaBins_nyu.pt
"Jul 15, 2024, 8:12:16 PM",WARNING,Location: https://ipfs.io/ipfs/Qmd2mMnDLWePKmgfS8m6ntAg4nhV5VkUyAydYBp8cWWeB7/AdaBins_nyu.pt [following]
"Jul 15, 2024, 8:12:16 PM",WARNING,301 Moved Permanently
"Jul 15, 2024, 8:12:16 PM",WARNING,"HTTP request sent, awaiting response... "
"Jul 15, 2024, 8:12:16 PM",WARNING,connected.
"Jul 15, 2024, 8:12:16 PM",WARNING,"104.17.64.14, 104.17.96.13, 2606:4700::6811:400e, ..."
"Jul 15, 2024, 8:12:16 PM",WARNING,Resolving cloudflare-ipfs.com (cloudflare-ipfs.com)... 
"Jul 15, 2024, 8:12:16 PM",WARNING,--2024-07-16 02:12:16--  https://cloudflare-ipfs.com/ipfs/Qmd2mMnDLWePKmgfS8m6ntAg4nhV5VkUyAydYBp8cWWeB7/AdaBins_nyu.pt
"Jul 15, 2024, 8:12:14 PM",WARNING,WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
"Jul 15, 2024, 8:12:06 PM",INFO,Kernel interrupted: 559af406-0386-4626-89f7-1b724be64469
"Jul 15, 2024, 8:10:06 PM",WARNING,"HTTP request sent, awaiting response... "
"Jul 15, 2024, 8:10:06 PM",WARNING,connected.
"Jul 15, 2024, 8:10:06 PM",WARNING,"209.94.90.1, 2602:fea2:2::1"
"Jul 15, 2024, 8:10:06 PM",WARNING,Resolving ipfs.io (ipfs.io)... 
"Jul 15, 2024, 8:10:06 PM",WARNING,--2024-07-16 02:10:06--  https://ipfs.io/ipfs/Qmd2mMnDLWePKmgfS8m6ntAg4nhV5VkUyAydYBp8cWWeB7/AdaBins_nyu.pt
"Jul 15, 2024, 8:10:06 PM",WARNING,Location: https://ipfs.io/ipfs/Qmd2mMnDLWePKmgfS8m6ntAg4nhV5VkUyAydYBp8cWWeB7/AdaBins_nyu.pt [following]
"Jul 15, 2024, 8:10:06 PM",WARNING,301 Moved Permanently
"Jul 15, 2024, 8:10:06 PM",WARNING,"HTTP request sent, awaiting response... "
"Jul 15, 2024, 8:10:06 PM",WARNING,connected.
"Jul 15, 2024, 8:10:06 PM",WARNING,"104.17.64.14, 104.17.96.13, 2606:4700::6811:600d, ..."
"Jul 15, 2024, 8:10:06 PM",WARNING,Resolving cloudflare-ipfs.com (cloudflare-ipfs.com)... 
"Jul 15, 2024, 8:10:06 PM",WARNING,--2024-07-16 02:10:06--  https://cloudflare-ipfs.com/ipfs/Qmd2mMnDLWePKmgfS8m6ntAg4nhV5VkUyAydYBp8cWWeB7/AdaBins_nyu.pt
"Jul 15, 2024, 8:10:05 PM",WARNING,Cloning into 'AdaBins'...
"Jul 15, 2024, 8:10:03 PM",WARNING,Cloning into 'disco-diffusion'...
"Jul 15, 2024, 8:10:03 PM",WARNING,Turn off this advice by setting config variable advice.detachedHead to false
"Jul 15, 2024, 8:10:03 PM",WARNING,  git switch -
"Jul 15, 2024, 8:10:03 PM",WARNING,Or undo this operation with:
"Jul 15, 2024, 8:10:03 PM",WARNING,  git switch -c <new-branch-name>
"Jul 15, 2024, 8:10:03 PM",WARNING,do so (now or later) by using -c with the switch command. Example:
"Jul 15, 2024, 8:10:03 PM",WARNING,"If you want to create a new branch to retain commits you create, you may"
"Jul 15, 2024, 8:10:03 PM",WARNING,state without impacting any branches by switching back to a branch.
"Jul 15, 2024, 8:10:03 PM",WARNING,"changes and commit them, and you can discard any commits you make in this"
"Jul 15, 2024, 8:10:03 PM",WARNING,"You are in 'detached HEAD' state. You can look around, make experimental"
"Jul 15, 2024, 8:10:03 PM",WARNING,Note: switching to 'f28885afc4c6c8907e0555b00e28b299ba2e5a16'.
"Jul 15, 2024, 8:10:02 PM",WARNING,Cloning into 'MiDaS'...
"Jul 15, 2024, 8:10:02 PM",WARNING,Cloning into 'pytorch3d-lite'...
"Jul 15, 2024, 8:10:00 PM",WARNING,Cloning into 'ResizeRight'...
"Jul 15, 2024, 8:10:00 PM",WARNING,Cloning into 'guided-diffusion'...
"Jul 15, 2024, 8:09:53 PM",WARNING,Cloning into 'open_clip'...
"Jul 15, 2024, 8:09:52 PM",WARNING,Cloning into 'CLIP'...
"Jul 15, 2024, 8:09:38 PM",WARNING,WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
"Jul 15, 2024, 8:07:00 PM",INFO,"Kernel started: 559af406-0386-4626-89f7-1b724be64469, name: python3"
"Jul 15, 2024, 8:00:51 PM",INFO,Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
"Jul 15, 2024, 8:00:51 PM",INFO,http://172.28.0.12:9000/
"Jul 15, 2024, 8:00:51 PM",INFO,Jupyter Notebook 6.5.5 is running at:
"Jul 15, 2024, 8:00:51 PM",INFO,Serving notebooks from local directory: /
"Jul 15, 2024, 8:00:50 PM",INFO,Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
"Jul 15, 2024, 8:00:50 PM",INFO,http://172.28.0.2:9000/
"Jul 15, 2024, 8:00:50 PM",INFO,Jupyter Notebook 6.5.5 is running at:
"Jul 15, 2024, 8:00:50 PM",INFO,Serving notebooks from local directory: /
"Jul 15, 2024, 8:00:49 PM",INFO,Loading IPython parallel extension
"Jul 15, 2024, 8:00:49 PM",INFO,google.colab serverextension initialized.
"Jul 15, 2024, 8:00:49 PM",INFO,"Authentication of /metrics is OFF, since other authentication is disabled."
"Jul 15, 2024, 8:00:49 PM",INFO,Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
"Jul 15, 2024, 8:00:49 PM",WARNING,    	/root/.jupyter/jupyter_notebook_config.json
"Jul 15, 2024, 8:00:49 PM",WARNING,    	/root/.local/etc/jupyter/jupyter_notebook_config.json
"Jul 15, 2024, 8:00:49 PM",WARNING,    	/usr/etc/jupyter/jupyter_notebook_config.json
"Jul 15, 2024, 8:00:49 PM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.json
"Jul 15, 2024, 8:00:49 PM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.d/panel-client-jupyter.json
"Jul 15, 2024, 8:00:49 PM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.d/ipyparallel.json
"Jul 15, 2024, 8:00:49 PM",WARNING,    	/etc/jupyter/jupyter_notebook_config.json
"Jul 15, 2024, 8:00:49 PM",INFO,google.colab serverextension initialized.
"Jul 15, 2024, 8:00:49 PM",INFO,"Authentication of /metrics is OFF, since other authentication is disabled."
"Jul 15, 2024, 8:00:49 PM",INFO,Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
"Jul 15, 2024, 8:00:49 PM",WARNING,    	/root/.jupyter/jupyter_notebook_config.json
"Jul 15, 2024, 8:00:49 PM",WARNING,    	/root/.local/etc/jupyter/jupyter_notebook_config.json
"Jul 15, 2024, 8:00:49 PM",WARNING,    	/usr/etc/jupyter/jupyter_notebook_config.json
"Jul 15, 2024, 8:00:49 PM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.json
"Jul 15, 2024, 8:00:49 PM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.d/panel-client-jupyter.json
"Jul 15, 2024, 8:00:49 PM",WARNING,    	/etc/jupyter/jupyter_notebook_config.json
"Jul 15, 2024, 8:00:49 PM",WARNING,[D 02:00:49.239 NotebookApp] Loaded config file: /root/.jupyter/jupyter_notebook_config.py
"Jul 15, 2024, 8:00:49 PM",WARNING,[D 02:00:49.235 NotebookApp] Looking for jupyter_notebook_config in /root/.jupyter
"Jul 15, 2024, 8:00:49 PM",WARNING,[D 02:00:49.235 NotebookApp] Looking for jupyter_notebook_config in /root/.local/etc/jupyter
"Jul 15, 2024, 8:00:49 PM",WARNING,[D 02:00:49.235 NotebookApp] Looking for jupyter_notebook_config in /usr/etc/jupyter
"Jul 15, 2024, 8:00:49 PM",WARNING,[D 02:00:49.234 NotebookApp] Loaded config file: /usr/local/etc/jupyter/jupyter_notebook_config.json
"Jul 15, 2024, 8:00:49 PM",WARNING,[D 02:00:49.232 NotebookApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
"Jul 15, 2024, 8:00:49 PM",WARNING,[D 02:00:49.232 NotebookApp] Loaded config file: /etc/jupyter/jupyter_notebook_config.py
"Jul 15, 2024, 8:00:49 PM",WARNING,[D 02:00:49.230 NotebookApp] Looking for jupyter_notebook_config in /etc/jupyter
"Jul 15, 2024, 8:00:49 PM",WARNING,[D 02:00:49.229 NotebookApp] Looking for jupyter_config in /root/.jupyter
"Jul 15, 2024, 8:00:49 PM",WARNING,[D 02:00:49.229 NotebookApp] Looking for jupyter_config in /root/.local/etc/jupyter
"Jul 15, 2024, 8:00:49 PM",WARNING,[D 02:00:49.229 NotebookApp] Looking for jupyter_config in /usr/etc/jupyter
"Jul 15, 2024, 8:00:49 PM",WARNING,[D 02:00:49.225 NotebookApp] Looking for jupyter_config in /usr/local/etc/jupyter
"Jul 15, 2024, 8:00:49 PM",WARNING,[D 02:00:49.225 NotebookApp] Looking for jupyter_config in /etc/jupyter
"Jul 15, 2024, 8:00:49 PM",WARNING,"[D 02:00:49.224 NotebookApp] Searching ['/root/.jupyter', '/root/.local/etc/jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files"
"Jul 15, 2024, 8:00:48 PM",WARNING,[D 02:00:48.955 NotebookApp] Loaded config file: /root/.jupyter/jupyter_notebook_config.py
"Jul 15, 2024, 8:00:48 PM",WARNING,[D 02:00:48.952 NotebookApp] Looking for jupyter_notebook_config in /root/.jupyter
"Jul 15, 2024, 8:00:48 PM",WARNING,[D 02:00:48.952 NotebookApp] Looking for jupyter_notebook_config in /root/.local/etc/jupyter
"Jul 15, 2024, 8:00:48 PM",WARNING,[D 02:00:48.952 NotebookApp] Looking for jupyter_notebook_config in /usr/etc/jupyter
"Jul 15, 2024, 8:00:48 PM",WARNING,[D 02:00:48.952 NotebookApp] Loaded config file: /usr/local/etc/jupyter/jupyter_notebook_config.json
"Jul 15, 2024, 8:00:48 PM",WARNING,[D 02:00:48.950 NotebookApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
"Jul 15, 2024, 8:00:48 PM",WARNING,[D 02:00:48.950 NotebookApp] Loaded config file: /etc/jupyter/jupyter_notebook_config.py
"Jul 15, 2024, 8:00:48 PM",WARNING,[D 02:00:48.948 NotebookApp] Looking for jupyter_notebook_config in /etc/jupyter
"Jul 15, 2024, 8:00:48 PM",WARNING,[D 02:00:48.948 NotebookApp] Looking for jupyter_config in /root/.jupyter
"Jul 15, 2024, 8:00:48 PM",WARNING,[D 02:00:48.948 NotebookApp] Looking for jupyter_config in /root/.local/etc/jupyter
"Jul 15, 2024, 8:00:48 PM",WARNING,[D 02:00:48.947 NotebookApp] Looking for jupyter_config in /usr/etc/jupyter
"Jul 15, 2024, 8:00:48 PM",WARNING,[D 02:00:48.943 NotebookApp] Looking for jupyter_config in /usr/local/etc/jupyter
"Jul 15, 2024, 8:00:48 PM",WARNING,[D 02:00:48.941 NotebookApp] Looking for jupyter_config in /etc/jupyter
"Jul 15, 2024, 8:00:48 PM",WARNING,"[D 02:00:48.941 NotebookApp] Searching ['/root/.jupyter', '/root/.local/etc/jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files"

**Comment by EvanWiederspan** [comment]
Can you file in-product feedback instead at Help -> Send feedback? That will give us more data to be able to look at your VM and see what could be causing disconnects

**Comment by ThornsOfire** [comment]
Will do!
