### ISSUE TITLE
Notebook taking long time to connect

### ISSUE THREAD

**Issue by jaideep11061982** [googlecolab/colabtools#470]
hi i keep facing this issue every now n then.... one or two time if due to internet it disconnects there after it takes long time for notebook to get connected with gpu. 
why do we have connectivity issue. I dont think this should be related to the contents of the notebook.

**Comment by metrizable** [comment]
Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem since then, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
