### ISSUE TITLE
error in ModuleName pinecone.client 

### ISSUE THREAD

**Issue by Ramareddy2111** [googlecolab/colabtools#4700]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
I'm trying to Import Client from pinecone.client but it's showing modlenameerror even after installation of pinecone-client.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
 - ---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-5-312ba20bab47>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from pinecone.client import Client

ModuleNotFoundError: No module named 'pinecone.client'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
------------------------------------

**Comment by mayankmalik-colab** [comment]
I think the syntax mentioned above is for older pinecone versions. For the latest versions, you can refer the code from their [official pypi page](https://pypi.org/project/pinecone-client/4.1.2/#description). Let me know if that works.
