### ISSUE TITLE
Pharokka + Phold + Phynteny

### ISSUE THREAD

**Issue by JonathanWinther** [googlecolab/colabtools#4703]
Using Pharokka, Phold, Syntheny on Chrome i get the following error after correctly installing modules 1,2 and running Pharokka on module 3. The phold module gives the following output:

Error occurred: Command 'phold run -i output_pharokka/pharokka.gbk -t 4 -o output_phold -p  -f' returned non-zero exit status 1.
Please advice

**Comment by cperry-goog** [comment]
We'll need a minimal reproducible notebook to investigate.
