### ISSUE TITLE
Notebook getting disconnected while plotting large datasets with plotly

### ISSUE THREAD

**Issue by patilpushkarp** [googlecolab/colabtools#471]
I am using a dataset with 102175 rows vs 32 columns. I want to plot a box plot with values from 17 columns. I am looping over columns and appending the trace of plotly to a data varibale. When I try to execute the cell I am getting "Runtime Disconnected" prompt and my notebook is getting disconnected. The connection is established again but plot is not getting displayed and the colab is the showing the cell status to executed. I tried to limit the number of rows and the plot is getting displayed. But I want to plot box plot with complete dataset.
![Screenshot from 2019-03-09 12-31-44](https://user-images.githubusercontent.com/16013308/54067545-4a78b480-4267-11e9-9182-43e7833063fe.png)

**Comment by blois** [comment]
You'll probably want to find a way to subset that data- 102175 x 17 is a fairly large amount of data. My guess is that it's taking too long to transfer and is disconnecting.

Repro: https://colab.research.google.com/gist/blois/6b85f45f9bf57e68319de6d6c5822252/large-data.ipynb
