### ISSUE TITLE
Upgrade CVXPY

### ISSUE THREAD

**Issue by alexshtf** [googlecolab/colabtools#4710]
The current default version of CVXPY on Colab is 1.3.4, which uses a deprecated solver that sometimes fails due to numerical issues, especially with the exponential cone, which is used to model the well-known logistic regression problem.

I'd like to upgrade CVXPY to the latest version, 1.5.2, which uses Clarabel open source solver instead of ECOS. I found it much more robust on problems. It's main drawback is that it's a bit slower, but I believe it CVXPY isn't supposed to be extremely fast in the first place. Just a convenient and very robust tool tool with an acceptable speed.

**Comment by metrizable** [comment]
@alexshtf Thanks for filing the request. We're currently working on getting this upgrade in.

**Comment by metrizable** [comment]
We've upgraded to `cvxpy==1.5.2` and this should be available now.
