### ISSUE TITLE
There is a Vertical Line in the google colab  . please fix this 

### ISSUE THREAD

**Issue by TARUN1354** [googlecolab/colabtools#4712]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by katlyn-edwards** [comment]
Is this the vertical column setting in the editor?

![image](https://github.com/user-attachments/assets/94102aa2-0d25-4782-96d1-bea6b243613e)


Can you include a screenshot?
