### ISSUE TITLE
Paid for Colab Pro but I don't have access to Terminal

### ISSUE THREAD

**Issue by nicoaira** [googlecolab/colabtools#4713]
I have suscribed for Colab Pro. At the beggining I had access to the terminal. I decided to cancel my automatic suscription because I only need to use the Colab Pro for this month. I should still have more than two weeks of Colab Pro. I have access to the GPUs but I can not access to the terminal anymore. Also, I don't see the option to get more RAM either.

![image](https://github.com/user-attachments/assets/456d80c8-9c11-46da-b042-01ccad317f14)

![image](https://github.com/user-attachments/assets/10fbd4c7-457c-4069-bafb-7aacb0a0f728)

**Comment by katlyn-edwards** [comment]
Hey there! Thanks for the report -- we'd love to look into this further, can you file in-product feedback, and reference this github issue? (We need in product feedback to gather account details and information). 

Thanks!

**Comment by data-88** [comment]
Hi, how did you fix it in the end?
