### ISSUE TITLE
My Runtime keeps disconnecting !!!

### ISSUE THREAD

**Issue by Sumeshan29** [googlecolab/colabtools#4715]
https://colab.research.google.com/drive/1kqKK4ODM7A82EHIbuxxahB-B3aMhyb57 this is the link to my runtime , 

I am currently paying for Colab pro , i do not understand why my runtime is disconnecting after 1hour into my training loop , thius has happened to me multiple times and has cost me already half of the compute units that i have purchased for this month , and this is just this months worth of compute units , i currently have an auto clicker that keeps clicking on the notebook every 60 seconds to show activity yet my runtime still disconnects! Please you need to help me address this issue as this is now costing me !

Regards

**Comment by Afefa** [comment]
I have the same problem! I subscribed to Colab Pro+ and purchased more computing units, but I'm still facing the same issue. My code was working well two days ago, but about 20 hours ago, I started encountering this problem. My work has already consumed more than 120 computing units without any benefit.

**Comment by Sumeshan29** [comment]
Its abit unfair that we have to keep paying for a service that has a time base currency ...yet it fails to complete the time based task.......

**Comment by cperry-goog** [comment]
`i currently have an auto clicker that keeps clicking on the notebook every 60 seconds to show activity yet my runtime still disconnects`

You are attempting to circumvent our checks on interactivity - we support background execution for Pro+ users only. Closing this as it's not clear this is an issue.

If you encounter unexpected terminations you can file feedback in product and reference this issue and we can take a look.

**Comment by Sumeshan29** [comment]
Sigh .....so you expect your users to sit infront of a training loop for 9 hours ???? This is ridiculous....sigh ...subscription cancelled ......

**Comment by Sumeshan29** [comment]
Also you need to realise that some of us here in South Africa cant afford the 50usd for pro+ ....thanks for supporting low income individuals !
