### ISSUE TITLE
TypeError: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by madiiiih** [googlecolab/colabtools#4719]
I can't run any cell in Google Colab. I got this error 
Failed to execute cell. Could not send execute message to runtime: TypeError: NetworkError when attempting to fetch resource.

NetworkError when attempting to fetch resource.

I'm sure that I connect to the Inretnet correctly. I restarted the computer and made a new notebook but it didn't work

**Comment by d-rovito** [comment]
Did you figure anything out? 
Same thing is happening to me except mine just says `TypeError: Failed to fetch`

**Comment by FFYICE** [comment]
> Did you figure anything out? Same thing is happening to me except mine just says `TypeError: Failed to fetch`

Did you check if the runtime is connecting as it should? Or it says unable to connect?

**Comment by d-rovito** [comment]
> > Did you figure anything out? Same thing is happening to me except mine just says `TypeError: Failed to fetch`
> 
> Did you check if the runtime is connecting as it should? Or it says unable to connect?

Unable to connect. Tried different browser, different computer, different notebook, clearing cookies and I have no extensions. Still same issue

**Comment by FFYICE** [comment]
> > > Did you figure anything out? Same thing is happening to me except mine just says `TypeError: Failed to fetch`
> > 
> > 
> > Did you check if the runtime is connecting as it should? Or it says unable to connect?
> 
> Unable to connect. Tried different browser, different computer, different notebook, clearing cookies and I have no extensions. Still same issue

Same here.... I think its their server issue... But I can't find any notes about them fixing it and when it will be fixed..LOL

**Comment by shaswatidash8** [comment]
I am getting the same error since morning.

Failed to execute cell. Could not send execute message to runtime: TypeError: Failed to fetch

![error_message](https://github.com/user-attachments/assets/ae5593d0-fc76-4491-be77-3f3f19fa148a)

**Comment by fangyeh** [comment]
same issue still

**Comment by hamidniko** [comment]
same issue for me.I guess this is a server problem.

**Comment by cperry-goog** [comment]
Hi folks, thanks for commenting. A recent update caused an issue connecting for a small number of our users. This has now been resolved. We have not changed any geo availability of Colab. Please open a new bug if you encounter new connection issues.
