### ISSUE TITLE
Unable to connect to the runtime.

### ISSUE THREAD

**Issue by nouri-muhammad** [googlecolab/colabtools#4727]
Colab have been acting strangely since yesterday! When I want to run code in google colab, it can't connect to runtime.
It give "Unable to connect to the runtime" error. It fails no matter the runtime type; thus I can't run any code anymore. 
I don't know if it is related or not, but from file option on the left bar in colab page, I don't have access to browse the files in google drive, with the message "Connecting to a runtime to enable file browsing"
I tried with both Firefox and Brave browsers and it didn't work on any of them.

**Comment by Hamedeng64** [comment]
I have same problem, are you from Iran?

**Comment by nouri-muhammad** [comment]
> I have same problem, are you from Iran?

yeah, but the issue doesn't seem to be related to Iran, many people have faced the same issue from different countries.

**Comment by Hamedeng64** [comment]
Dear Muhammad
thank you i share my code with my friend in other country and it didn't any
see problem

**Comment by toufikshit** [comment]
From Morocco , and I am facing the same problem

**Comment by cperry-goog** [comment]
Hi folks, thanks for commenting. A recent update caused an issue connecting for a small number of our users. This has now been resolved. We have not changed any geo availability of Colab. Please open a new bug if you encounter new connection issues.

**Comment by nouri-muhammad** [comment]
> Hi folks, thanks for commenting. A recent update caused an issue connecting for a small number of our users. This has now been resolved. We have not changed any geo availability of Colab. Please open a new bug if you encounter new connection issues.

Thanks, the issue is resolved and it runs smoothly. Thanks again for the support.
