### ISSUE TITLE
Writing to Google Drive not working

### ISSUE THREAD

**Issue by renedlog** [googlecolab/colabtools#473]
The example script "Mounting Google Drive in your VM" is not working.
Also if I check via !ls /gdrive/ none of my files are shown

![image](https://user-images.githubusercontent.com/14824710/54083524-dc92c280-4324-11e9-8542-86484ba3c632.png)

**Comment by colaboratory-team** [comment]
You'll need to use a path like `/gdrive/My\ Drive/foo.txt`. 

If you run `!ls /gdrive`, I suspect you'll see `My Drive`, which is used to disambiguate Team Drives. You won't be able to write to the base directory `/gdrive` for this reason.
