### ISSUE TITLE
Runtime error - not connect to runtime - any email - any files

### ISSUE THREAD

**Issue by Hamedeng64** [googlecolab/colabtools#4731]
**Describe the current behavior**
Runtime error in Iran country

**Describe the expected behavior**
Connect to runtime for running the code
**What web browser you are using**
(Chrome

**Comment by cperry-goog** [comment]
Hi folks, thanks for commenting. A recent update caused an issue connecting for a small number of our users. This has now been resolved. We have not changed any geo availability of Colab. Please open a new bug if you encounter new connection issues.
