### ISSUE TITLE
Unable to transfer  Colab Subscription

### ISSUE THREAD

**Issue by Annapurnasolutions** [googlecolab/colabtools#4735]
Hi folks, 
I would like to transfer my  Colab Subscription to a peer using a different Gmail /google account. 
Please inform me how to get this done as we are unable to use the  Colab Subscription currently. 

Thanks, 
Jan

**Comment by EvanWiederspan** [comment]
This is not currently supported. You can reach out to colab-billing@google.com if you want to cancel your subscription and activate a separate one on the other account
