### ISSUE TITLE
ProxyPort URL is broken as July 23rd

### ISSUE THREAD

**Issue by jlopatec** [googlecolab/colabtools#4738]
As of July 23rd / 24th the proxy approach for a URL is broken from Colab with a 403. This is used to launch Tensorboard tools in a full URL.

from google.colab import output
def open_window_to_port(port):
  print(output.eval_js(f'google.colab.kernel.proxyPort({port})'))

print('Must execute this cell first for the URL to work.')
# The generated URL will only be valid while this notebook file is open.
open_window_to_port(port)

Example:
https://colab.research.google.com/gist/blois/240fab81110daa9bbdb513c5b7b717cb/proxyport-examples.ipynb#scrollTo=gjqweJ0lUwWA

<img width="1192" alt="Screenshot 2024-07-27 at 1 41 23 PM" src="https://github.com/user-attachments/assets/67cbf6b3-96fa-48db-a142-4c77b7c020cc">

**Comment by EvanWiederspan** [comment]
Does `serve_kernel_port_as_iframe` work for you instead?

**Comment by arizedatngo** [comment]
Running into the same issue. I can get it into an iframe in the notebook cell myself, but it's a much worser experience to interact that way. I was personally hoping for the proxy approach for a URL to be working again

@EvanWiederspan do we know why this proxy approach for a URL broke?

**Comment by jlopatec** [comment]
Slightly suspicious this is related to secure cookie propagation in chrome browser, maybe a chrome browser change that affects the feature between colab server serving up a URL to the chrome browser.

**Comment by arizedatngo** [comment]
@EvanWiederspan the issue some got fixed. if that was you, thanks a ton!
