### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sateeshambesange** [googlecolab/colabtools#474]
Error loading https://apis.google.com/js/client.js
Error: Error loading https://apis.google.com/js/client.js
    at HTMLScriptElement.f.onerror (https://colab.research.google.com/v2/external/gapi_loader.js:9:415)

**Comment by blois** [comment]
Errors loading that script are indicative of something between you and Colab's servers blocking the script- most commonly a Chrome extension. Can you try using an incognito window?
