### ISSUE TITLE
List-type markdowns are not appied in text cell

### ISSUE THREAD

**Issue by woolist** [googlecolab/colabtools#4741]
List-type markdowns such as _, *, and 1. are not applied to text cells. 
However, horizontal lines, bold, italics, and H1(#) work well. Wh
at's the problem?

![스크린샷 2024-07-29 104200](https://github.com/user-attachments/assets/e04907eb-2d39-4294-8309-aa7a70b69e6e)

**Comment by EvanWiederspan** [comment]
I'm not able to reproduce this, I see your exact text display the lists as expected

Does this repro for you in incognito mode with all extensions disabled?

If it still happens, can you share the notebook that shows this issue?

**Comment by woolist** [comment]
@EvanWiederspan Although I’m not sure of the exact cause, it seems that a Chrome extension was the issue. Deleting all the extensions resolved the problem.
