### ISSUE TITLE
Android Chrome web interface looks weird

### ISSUE THREAD

**Issue by ionutgrigorescu** [googlecolab/colabtools#4742]
![Screenshot_20240729-095237_Chrome](https://github.com/user-attachments/assets/9a1542c6-4ad9-49db-9c10-ceed5c2c4e94)

I am using colab on my Android phone, through Chrome. Today, it started looking looking like in the attached image.

**Comment by ionutgrigorescu** [comment]
![Uploading Screenshot_20240729-095730_Chrome.jpg…]()

**Comment by ionutgrigorescu** [comment]
![Screenshot_20240729-095730_Chrome](https://github.com/user-attachments/assets/5d0ee8a0-b5c9-42ca-a44c-5301c8242876)

**Comment by EvanWiederspan** [comment]
This can happen sometimes when specific CSS files fail to load. Does it happen for you consistently?

**Comment by ionutgrigorescu** [comment]
![Screenshot_20240802-062245_Chrome](https://github.com/user-attachments/assets/5ff1b734-cf37-41da-8d60-ff29b7623ead)

It is working fine now, I will keep monitoring it.
