### ISSUE TITLE
`p.circle()` not rendering in bokeh figures

### ISSUE THREAD

**Issue by tiagonj** [googlecolab/colabtools#4743]
**Describe the current behavior**
A bokeh figure containing multiple types of glyphs will get rendered correctly **except for** data plotted using the `circle()` method. Others may also be broken, I know that `p.line()` is working :+1: 

**Describe the expected behavior**
Data added to the bokeh figure using the `circle()` method should get displayed.

**What web browser you are using**
Chrome

**Additional context**
https://colab.research.google.com/github/bebi103a/bebi103a.github.io/blob/master/lessons/06/intro_to_plotting_with_bokeh.ipynb

In the above Colab, when execution reaches the cell containing

```
bokeh.io.show(p)
```

the resulting plot is empty, no data is shown.

![image](https://github.com/user-attachments/assets/b602fa7a-7572-4329-a1e4-eae884cef451)

I originally spotted this in a work-related Colab sheet where the bokek version is `3.4.2`. That Colab had been working until around 26 ~ 27 July, but I'm not sure what has changed since then, and I'd not been keeping track of the bokeh version prior to this.

**Comment by metrizable** [comment]
@tiagonj Thanks for reporting the issue and thanks for using Colab.

For your example notebook, I believe if you pass some positive `radius` argument, the plot will resolve:

![8N5brLd8MXN8c2C](https://github.com/user-attachments/assets/17e0ffc9-58c3-411d-abd1-48af8d115c45)

**Comment by tiagonj** [comment]
Thank you @metrizable this was useful :pray: 

I had also noticed the `radius` argument from the bokeh API, but initially in my work Colab this wasn't enough to fix it, so I thought it must be something else (again, everything had been working fine for many weeks prior).

I've now circled back and found that the `p.circle()` rendering failure (additionally to needing `radius` :+1:) comes from passing an iterable (list or pd.Series, no difference) of pandas `Timestamp`s as the `x` argument . For example `p.line()` renders correctly with the exact same inputs :shrug: This failure to render occurs regardless of the use of `p = bokeh.plotting.figure(... , x_axis_type='datetime)`.

**Example to reproduce the failure (tested on [the same Colab](https://colab.research.google.com/github/bebi103a/bebi103a.github.io/blob/master/lessons/06/intro_to_plotting_with_bokeh.ipynb))**:

```
# Create the figure, stored in variable `p`
p = bokeh.plotting.figure(
    width=400,
    height=300,
    x_axis_label="The X axis",
    y_axis_label="The Y axis",
    x_axis_type='datetime'
)

t1 = pd.Timestamp('2017-01-01T12')
t2 = pd.Timestamp('2017-01-01T13')
t3 = pd.Timestamp('2017-01-01T14')

p.circle(x=[t1, t2, t3],  y=[1, 2, 3], radius=1)
bokeh.io.show(p)
```

I've also tested locally in a venv with bokeh 3.5.1 same result, empty plot.

I'm guessing this is a regression in bokeh, so I'll look to raise a ticket there instead. Thank you again! :pray:
