### ISSUE TITLE
The site sends a request to no longer existing URL

### ISSUE THREAD

**Issue by nkosephayo777** [googlecolab/colabtools#4745]
During packaging kivy app with Buildozer, the following URL is accessed but it no long exist in that way. Thus the command return a request failed error: https://[download.savannah.gnu.org](https://download.savannah.gnu.org/releases/freetype/freetype-2.10.1.tar.gz)/releases/freetype/freetype-2.10.1.tar.gz

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
This isn't an issue with Colab itself, I recommend reaching out to the notebook or library author instead
