### ISSUE TITLE
Drive notebook loads are failing

### ISSUE THREAD

**Issue by NguyenDucTuong** [googlecolab/colabtools#476]
Hi,

I have this problem: While my code is running, I accidentally refresh the page and then, I cannot open any Notebook. The error message is below:
![Capture](https://user-images.githubusercontent.com/18389393/54252084-dae11e80-451f-11e9-8f24-523b5187565d.PNG)

Here is the link to the Notebook that causes error:

https://colab.research.google.com/drive/1npUbIRsrMWFYp0_F2HAyPU3sF1yqvEI-

I would be very appreciated for any help or suggestion for a solution. Thank you in advance.

**Comment by colaboratory-team** [comment]
Sorry for the trouble. Drive notebooks are currently unavailable for many users. We're aware of the problem and are working with Drive to resolve the issue. 

Updates at https://www.google.com/appsstatus

**Comment by colaboratory-team** [comment]
Drive error rates are moderating. Sorry for the trouble, all. Further updates will be posted at https://www.google.com/appsstatus
