### ISSUE TITLE
Unable to download necessary software in Alphafold 2 Advanced

### ISSUE THREAD

**Issue by astatffdod** [googlecolab/colabtools#4762]
I am unable to complete the 'install software' step of using Alphafold 2 advanced due to error codes included in photos:

<img width="960" alt="Screenshot 2024-08-06 154016" src="https://github.com/user-attachments/assets/352a7d3b-3d83-406f-9d99-477de863327c">
<img width="284" alt="Screenshot 2024-08-06 154106" src="https://github.com/user-attachments/assets/a3fc9a33-d007-4214-8665-5617d76a1119">

**Comment by cperry-goog** [comment]
We don't own that library, you'll want to contact the maintainer (offhand I think you can reach them at https://github.com/sokrypton/ColabFold/issues)
