### ISSUE TITLE
Paid colab pro but it is not activated

### ISSUE THREAD

**Issue by fatemehnikan** [googlecolab/colabtools#4763]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by fatemehnikan** [comment]
It is paid for colab pro but my account is not activated after 3 hours. what should I do?

**Comment by katlyn-edwards** [comment]
Hey there, we can't diagnose billing issues on GitHub, unfortunately. Your best bet is to reach out to colab-billing@google.com with your purchase order number.

**Comment by cperry-goog** [comment]
Yes, if it takes longer than an hour to activate, please contact support at the email address above.
