### ISSUE TITLE
The tutorials at https://firebase.google.com/ are not available

### ISSUE THREAD

**Issue by QualityS** [googlecolab/colabtools#4764]
**Describe the current behavior**
IN：https://firebase.google.cn/codelabs/textclassification-android?hl=zh_cn#7
https://colab.research.google.com/github/FirebaseExtended/codelab-textclassification-android/blob/master/train_tflite_model.ipynb?hl=zh-cn#scrollTo=60bgUw9CHrLg
are not available

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by katlyn-edwards** [comment]
Hey there! I seems to load for me:
https://colab.research.google.com/github/FirebaseExtended/codelab-textclassification-android/blob/master/train_tflite_model.ipynb?hl=zh-cn

Do you get something different? Does that page not load for you? Maybe you could include a screenshot or a HAR file?
