### ISSUE TITLE
Error: FetchError: Could not fetch resource at https://colab.research.google.com/language-services/converse?authuser=0: 400

### ISSUE THREAD

**Issue by danielacbgp** [googlecolab/colabtools#4765]
**Describe the current behavior**
Any question I ask in Gemini within Colab is returning an error message:
Error: FetchError: Could not fetch resource at https://colab.research.google.com/language-services/converse?authuser=0: 400
I am a Colab Pro subscriber, and until 2 weeks ago, I normally used Gemini within Colab. What happened?

**What web browser you are using**
Chrome

**Additional context**
https://drive.google.com/file/d/1uOg2P4okJBsqeJpmBKwSl8hvkiQDH_7R/view?usp=sharing

**Comment by judemars** [comment]
Hi there! Thanks for reporting. We temporarily had an issue with gemini interacting with long notebooks (like yours! - thanks for the link that was very helpful). I'm now seeing gemini work correctly with your notebook - can you try?

**Comment by danielacbgp** [comment]
Thanks so much! The problem was fixed!
Sincerely,
Daniela

Em qui., 8 de ago. de 2024 às 14:22, Julianne DeMars <
***@***.***> escreveu:

**Comment by randomboy720** [comment]
I have the same error.
I don't know much about coding, so I created a subtitle file using someone else's coding...
Uploading the file works fine, but when you click submit, an error appears a few seconds later, and the percentage doesn't progress and an error appears.
I would really appreciate it if you could tell me how to solve it.

**Comment by CH860** [comment]
Hello, it seems that I have pretty same problem FetchError: Could not fetch resource at https://colab.research.google.com/language-services/generateCode?authuser=0: 403. How can I manage it?

**Comment by Sofi967** [comment]
Hello, I have the same error. I would appreciate also if you can tell me how to solve it.

**Comment by Sofi967** [comment]
> Hello, I have the same error. I would appreciate also if you can tell me how to solve it.
Do I need to share the notebook to facilitate the way to solve it?

**Comment by colaboratory-team** [comment]
Tracking internally at b/372007516, thank you for reporting!

**Comment by Sofi967** [comment]
OK, thank you, Do you know when the incident will be corrected?

**Comment by dirkpaessler** [comment]
A workaround is to create a code block with some garbage text in it, runs it, throws an error, then click on "explain error",

**Comment by AntonSant** [comment]
> A workaround is to create a code block with some garbage text in it, runs it, throws an error, then click on "explain error",

That doesn't work for me

**Comment by 106AbdulBasit** [comment]
How do i cancel my colab subscription ?
I am getting error

**Comment by Vortex21-X** [comment]
I have a blank file and am trying to use Gemini to generate the basic code but am getting the same error: FetchError: Could not fetch resource at https://colab.research.google.com/language-services/generateCode?authuser=0: 403

**Comment by Aises-neitzen** [comment]
> Hi there! Thanks for reporting. We temporarily had an issue with gemini interacting with long notebooks (like yours! - thanks for the link that was very helpful). I'm now seeing gemini work correctly with your notebook - can you try?

Hi there, it may appear this issue is back because I am experiencing the same issue.
