### ISSUE TITLE
ctrl-[ multiple selected lines causes SyntaxError: Unexpected token S in JSON at position 0

### ISSUE THREAD

**Issue by am717171** [googlecolab/colabtools#477]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by colaboratory-team** [comment]
Duplicate of #476
