### ISSUE TITLE
Colab Pro subscription, I don't have any available compute units to access premium GPUs.

### ISSUE THREAD

**Issue by Graciela-ia** [googlecolab/colabtools#4770]
I recently activated my Colab Pro subscription but I'm encountering an issue. The platform is informing me that despite my subscription, I don't have any available compute units to access premium GPUs. I'm unable to proceed.

**Comment by cperry-goog** [comment]
If you file feedback internally we can investigate, but it's likely the case that you have exhausted your compute unit balance and it will be refreshed the next time your subscription recurs.
