### ISSUE TITLE
Colab AI coding assistant suddenly disappear 

### ISSUE THREAD

**Issue by ppduck01** [googlecolab/colabtools#4777]
**Describe the current behavior**
Colab AI coding assistant suddenly disappear. It shows up for an hour, and it suddenly appears when I want to debug again.

**Describe the expected behavior**
I would like to have the AI coding debug fucntion always on. 

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
Can you say more about what you're seeing? And by debug, do you mean code completions? Or the chat window?
