### ISSUE TITLE
hola, estoy sufriendo cortes continuos en mi entorno, lo cual me genera un gran perjuicio debido a la interrupcion de los modelos en pleno testing, teniendo que empezar una y otra vez, de no solucionarse iniciare las acciones judiciales pertinentes. 

### ISSUE THREAD

**Issue by tinchoman79** [googlecolab/colabtools#4779]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
We'll need more information to follow up on this bug report. Please submit feedback within Colab at Help > Send feedback.

**Comment by tinchoman79** [comment]
Ni nombre es Angerami Carlos Martin, usuario ***@***.*** abonando suscripción a Google colab pro ,el entorno de ejecución del codigo en  tpv2 sufre continúos cortes o caídas del entorno interrumpiendo el entrenamiento del modelo constantemente haciendo que pierda todos los epoch corridos El 15 ago 2024 13:45, Evan Wiederspan ***@***.***> escribió:
We'll need more information to follow up on this bug report. Please submit feedback within Colab at Help > Send feedback.
