### ISSUE TITLE
ifcopenshell

### ISSUE THREAD

**Issue by gregoriosaura** [googlecolab/colabtools#478]
I've tried in differents ways to install the "ifcopenshell" package, but I can't:

_```

> import ifcopenshell
> ImportErrorTraceback (most recent call last)
> <ipython-input-4-f191a03739d0> in <module>()
> ----> 1 import ifcopenshell
> 
> ImportError: No module named ifcopenshell
> 
> ---------------------------------------------------------------------------
> NOTE: If your import is failing due to a missing package, you can
> manually install dependencies using either !pip or !apt.
> 
> To view examples of installing some common dependencies, click the
> "Open Examples" button below.
> ```_

!apt-get install ifcopenshell
!pip install ifcopenshell
import ifcopenshell

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ifcopenshell
Collecting ifcopenshell
  Could not find a version that satisfies the requirement ifcopenshell (from versions: )
No matching distribution found for ifcopenshell
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-af11590b4647> in <module>()
      1 get_ipython().system('apt-get install ifcopenshell')
      2 get_ipython().system('pip install ifcopenshell')
----> 3 import ifcopenshell

ModuleNotFoundError: No module named 'ifcopenshell'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

- Describe the current behavior: 

- Describe the expected behavior: I'd like to install an external package "ifcopenshell"

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

**Comment by metrizable** [comment]
I am not able to reproduce and was able to successfully install: `!pip install ifcopenshell`.

Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem since then, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.

**Comment by Tsovak** [comment]
@metrizable  I can reproduce it. please reopen it

```

➜  ~ docker run -it python:3.11 bash
Unable to find image 'python:3.11' locally
3.11: Pulling from library/python
df2021ddb7d6: Already exists
8d647f1dd7e7: Already exists
5cdd9a70365f: Already exists
95089c600b36: Already exists
031bfcddba4a: Already exists
7a2f0d5b0b05: Already exists
b0f1034fa6a0: Already exists
3bf98da35d8a: Already exists
Digest: sha256:2a725c9721f737a2944244c98c714d24f8bcfaddd9f5c15083cbaa024f7fce54
Status: Downloaded newer image for python:3.11
root@e908219a4024:/#
root@e908219a4024:/# pip3 install ifcopenshell==0.7.0.231127
ERROR: Could not find a version that satisfies the requirement ifcopenshell==0.7.0.231127 (from versions: none)
ERROR: No matching distribution found for ifcopenshell==0.7.0.231127

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
root@e908219a4024:/# pip install ifcopenshell==0.7.0.231127
ERROR: Could not find a version that satisfies the requirement ifcopenshell==0.7.0.231127 (from versions: none)
ERROR: No matching distribution found for ifcopenshell==0.7.0.231127

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
root@e908219a4024:/# pip install --upgrade pip
Requirement already satisfied: pip in /usr/local/lib/python3.11/site-packages (23.2.1)
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/47/6a/453160888fab7c6a432a6e25f8afe6256d0d9f2cbd25971021da6491d899/pip-23.3.1-py3-none-any.whl.metadata
  Downloading pip-23.3.1-py3-none-any.whl.metadata (3.5 kB)
Downloading pip-23.3.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 7.7 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.2.1
    Uninstalling pip-23.2.1:
      Successfully uninstalled pip-23.2.1
Successfully installed pip-23.3.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@e908219a4024:/# pip install ifcopenshell==0.7.0.231127
ERROR: Could not find a version that satisfies the requirement ifcopenshell==0.7.0.231127 (from versions: none)
ERROR: No matching distribution found for ifcopenshell==0.7.0.231127
root@e908219a4024:/# pip install ifcopenshell==0.7.0
ERROR: Could not find a version that satisfies the requirement ifcopenshell==0.7.0 (from versions: none)
ERROR: No matching distribution found for ifcopenshell==0.7.0
root@e908219a4024:/# pip install ifcopenshell
ERROR: Could not find a version that satisfies the requirement ifcopenshell (from versions: none)
ERROR: No matching distribution found for ifcopenshell
root@e908219a4024:/#
```

**Comment by ozzzzz** [comment]
For me the problem was that I've tried to build docker image on the Arm-based macbook. On macos it is goes fine, because ifcopenshell has for the macos arm64. But when you move inside the docker, it requires `manylinux-...-aarch64`, and ifcopenshell doesn't have build for it. See this [page](https://pypi.org/project/ifcopenshell/#files):
<img width="658" alt="image" src="https://github.com/googlecolab/colabtools/assets/5720160/1d9640df-9a98-418e-b5bc-c689cdbd12c7">

Solution was ugly: moving to another x64 build machine.

**Comment by Tsovak** [comment]
@ozzzzz  you have to build a docker image with a platform-specific `docker build --platform linux/amd64`
