### ISSUE TITLE
Ai assistance vs tab suggestions

### ISSUE THREAD

**Issue by xemeriusss** [googlecolab/colabtools#4780]
Hello,

In Google Colab, I don't want to use auto complete code feature. I close it from tools->ai assistance. But when I close it, it also doesn't give me any tab suggestions. Like I want to see the available functions, but it says "no suggestions". I think they are not relevant and I didn't understand why the suggestions also closes when I close the ai assistance. Thank you in advance.

![image](https://github.com/user-attachments/assets/7492f42c-7aa2-4f8b-9bbc-bc5a3c79087f)

**Comment by EvanWiederspan** [comment]
You won't get suggestions unless you're connected to a runtime, are you still seeing No Suggestions when connected?

**Comment by xemeriusss** [comment]
> You won't get suggestions unless you're connected to a runtime, are you still seeing No Suggestions when connected?

Oh yes I guess my connection was dropped when I was trying. Thank you!
