### ISSUE TITLE
401 AUTH_KEY_UNREGISTERED

### ISSUE THREAD

**Issue by Johnny3951** [googlecolab/colabtools#4783]
Telegram says: [401 AUTH_KEY_UNREGISTERED] - The key is not registered in the system. Delete your session file and login again (caused by "updates.GetState")

My browser is Firefox.

This error is from Clonechat.

![Clonagem](https://github.com/user-attachments/assets/84f3f087-a007-40be-a7a5-1ce32d94602e)

**Comment by katlyn-edwards** [comment]
This isn't an issue with Colab, either there's an issue with the notebook you're running (if so, reach out to the notebook author), or based on your screenshot, you didn't provide a valid token -- your screenshot still has the placeholder token.

**Comment by Johnny3951** [comment]
Thanks Katlyn, but I've never had any value for Bot Token and it always worked fine.

**Comment by Johnny3951** [comment]
Thanks Katlyn, but I've never had any value for Bot Token and it's always worked fine.
