### ISSUE TITLE
Only facial expression change

### ISSUE THREAD

**Issue by itellmytale** [googlecolab/colabtools#4789]
**Describe the current behavior**
I have create a comic character using Stable Image core. Now I like to create sequence of images for my comics book of same character with different action but same surrounding.

**Describe the expected behavior**
There is no such option avaiable in stable diffusion 

**What web browser you are using**
Chrome

**Additional context**
No comics / book image generate option is there

**Comment by cperry-goog** [comment]
You'll want to contact the notebook author of the notebook you're using to request this feature.
