### ISSUE TITLE
google drive timeout all the time

### ISSUE THREAD

**Issue by edenrose** [googlecolab/colabtools#479]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I have a training and test datasets on my google drive that i used to train and test my models for weeks using "drive.mount()" and everything was fine.
But this week nothing works. I get "google drive timeout" when i'm creating an image generator, training, predicting, basicly every thing that includes reading images from google drive.
I'm getting the error every minute.

- Describe the expected behavior:
That it would work like before

- The web browser you are using (Chrome, Firefox, Safari, etc.): chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*): It's nothing special, it happens to a lot of people using drive.mount

**Comment by dalip98** [comment]
I think, it can be a bug in your code, for e.g. some parameter must be sit to a very large number, so the memory got filled and the system restarts (timeouts).

**Comment by colaboratory-team** [comment]
Please see https://research.google.com/colaboratory/faq.html#drive-timeout for an explanation for why this happens and suggested remedies.
The fact that the code used to work and stopped working strongly suggests that accumulated outputs have crossed the too-many-direct-descendants in a single folder limits.

**Comment by SalMeza** [comment]
I'm having the same issue.  I have emptied my trash and tried resetting the runtimes, neither worked.  My my drive directory is pretty small, maybe 6 files.  Any ideas?

**Comment by SalMeza** [comment]
FYI, I'm in the process of starting a project, so I don't have any files loaded yet, I'm using chrome.

**Comment by colaboratory-team** [comment]
@SalMeza if your Google Drive is almost empty it's likely you're having a different underlying issue to this one. Please open a new issue with the information the template prompts for.
