### ISSUE TITLE
Like to have  several pic of same character in different expression and same background

### ISSUE THREAD

**Issue by itellmytale** [googlecolab/colabtools#4790]
**Is your feature request related to a problem? Please describe.**
For my comics book i like to have same character in several pictures with different action

**Describe the solution you'd like**
I need a comics feature which can generate source character in different actions

**Describe alternatives you've considered**
Nothing

**Additional context**

**Comment by cperry-goog** [comment]
I think you'll want to contact the notebook author for the notebook you're using for this functionality.
