### ISSUE TITLE
im working with colab pro.runtime disconnected. 

### ISSUE THREAD

**Issue by mfh1988** [googlecolab/colabtools#4792]
Hello colab team,
I'm using colab pro. but i usually have runtime disconnected error also i; not robot window.

I have to run my colab notebook for 6, 7 hours to get the result. but unfortunately i lost lot of unit point (about 200) due to this problem.
i'm using chrome as web browser.

i hope you can fix this  as soon as possible. im wasting time and unit point.
thnkx.

**Comment by mfh1988** [comment]
runtime disconnected.  im not rebot window.

**Comment by Shreejan-git** [comment]
Same issue. Just wasting the unit points!!!!!

**Comment by cperry-goog** [comment]
I'll need a minimal reproducible notebook to investigate.

**Comment by deliamoreno2295** [comment]
> Same issue. Just wasting the unit points!!!!!

Me too :(
