### ISSUE TITLE
AuthorizationError: Failed to fetch user credentials

### ISSUE THREAD

**Issue by BorjaDiago** [googlecolab/colabtools#4794]
When I execute the following statement the script brakes with this exception:

```shell
from google.colab import auth

auth.authenticate_user()

```
```
AuthorizationError                        Traceback (most recent call last)
[<ipython-input-112-d71ef1e6e939>](https://localhost:8080/#) in <cell line: 6>()
      4 from google.colab import auth
      5 
----> 6 auth.authenticate_user()
      7 
      8 def get_secret(secret_id: str, version: str = "latest"):

[/usr/local/lib/python3.10/dist-packages/google/colab/auth.py](https://localhost:8080/#) in authenticate_user(clear_output, project_id)
    306   if _check_adc(_CredentialType.USER):
    307     return
--> 308   raise _errors.AuthorizationError('Failed to fetch user credentials')
    309 
    310 

AuthorizationError: Failed to fetch user credentials
```

**Describe the expected behavior**
The normal behavior of this method.

**What web browser you are using**
Chrome

**Additional context**
This behavior has been occurring for a couple of hours, since up to this point the colab was working correctly. I have tried rebooting and running the following commands in case they could help, but nope.

`!gcloud auth login --no-launch-browser`
`!gcloud auth application-default login`

And of course, i set the project in my current configuration:

`!gcloud config set project my-project`

**Comment by cperry-goog** [comment]
We're not sure what might be causing this - can you submit in-product feedback and mention this issue? We can look into this further. We're wondering if you're on a Workspace account where some permissions have been disabled by your administrator.

**Comment by BorjaDiago** [comment]
Hello, 
Yes, I use Colab with my company's workspace account. It may be that the error is due to a recent change in company policies for using Google Colab. I will try to gather more info if this is the problem.

In the meantime, any help is welcome. Thank you very much!

**Comment by BorjaDiago** [comment]
Hello, 

This morning I tried to run the colab again and it worked without error. I have run it because my company has assured me that they have not implemented any restriction policy on this product.

It seems that it must have been a punctual error in the google.colab.auth library in its authenticate_user() method.

We can consider the issue closed, but it would be nice if users would be notified if there are occasional errors due to updates. Thank you very much for your time.

Best regards.

Translated with DeepL.com (free version)

**Comment by EvanWiederspan** [comment]
Glad it's working now!
