### ISSUE TITLE
Add ability to resume work from previous session

### ISSUE THREAD

**Issue by BrazilForever11** [googlecolab/colabtools#48]
This is a feature request. It would be nice to be able to resume work from where I left (when launching colab next day), so I would not need to reinstall all my libraries and re-map access to my google drive folder. 

I am guessing one can try to store image of VM on google drive

**Comment by colaboratory-team** [comment]
We're exploring ways to extend backend duration. For now, an immediately applicable work-around is to use a local runtime with either a local or cloud-hosted persistent backend. See: http://research.google.com/colaboratory/local-runtimes.html
