### ISSUE TITLE
Service /usr/local/bin/chromedriver unexpectedly exited. Status code was: -9

### ISSUE THREAD

**Issue by AbdulWahabCH** [googlecolab/colabtools#4807]
**Chrome version 128.0.6613.85 and driver latest and stable version is this 128.0.6613.84**
I'm getting the above error, every thing works correctly before chrome update.

**Comment by nitishjhavats** [comment]
Check Chrome Version in Colab:

First, let's confirm the exact Chrome version Colab is running. Execute the following code in a Colab cell:
Python

!google-chrome --version


This will output the Chrome version installed in the Colab runtime.

Install the Matching ChromeDriver:

Colab provides a convenient way to install specific ChromeDriver versions. Use the following code, replacing 

YOUR_CHROME_VERSION with the output from the previous step (e.g., 114.0.5735.199):

Bash
!wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - 
!echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list
!apt-get   
 -y update 
!apt-get install -y google-chrome-stable

# Install the matching ChromeDriver

!apt-get install -yqq unzip
!wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/YOUR_CHROME_VERSION/chromedriver_linux64.zip
!unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
Use code [with caution.](https://github.com/faq#coding)

This will:

Add the necessary Google Chrome repository to Colab's package manager.
Update the package list.
Install the stable version of Google Chrome.
Download the ChromeDriver zip file matching your Chrome version.
Unzip and install it in the appropriate location.
Verify the Installation:
Run the following to check if ChromeDriver is installed correctly and its version:
Bash
!chromedriver --version

The output should show the ChromeDriver version, which should now match your Chrome version.

Restart Runtime (if necessary):
In some cases, you might need to restart the Colab runtime for the changes to take effect. Go to the "Runtime" menu and select "Restart runtime".
Important Considerations

Colab Updates: Colab environments are regularly updated. It's possible that by the time you try this, the ChromeDriver version might have been updated to match the latest Chrome. So, always check the Chrome version first before installing ChromeDriver.
Alternative Approach (WebDriver Manager): If you're using Selenium in your Colab notebook, consider using a WebDriver manager library like webdriver_manager. It automatically handles downloading and managing the correct ChromeDriver version for you, simplifying the process.

Example using WebDriver Manager

Python
!pip install webdriver_manager

from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))   
  


# ... rest of your Selenium code

**Comment by EvanWiederspan** [comment]
A different version of chromedriver may fix your issue. Otherwise I would recommend asking on a forum such as StackOverflow instead, this doesn't seem like a Colab-specific issue
