### ISSUE TITLE
Quotation auto-close doesn't work with f-strings

### ISSUE THREAD

**Issue by ericricky** [googlecolab/colabtools#481]
Quotation auto-close does not seem to play well with f-strings. Here is the current behavior:

* Typing `f"` will not insert a closing quotation mark after the cursor
* Typing `f"text without curly braces"` will correctly only insert one quotation mark at the end
* Typing `f"text with {} curly braces"` will insert an extra quotation mark after the cursor at the end, so that there are three quotation marks in total

Can we improve the behavior in this area, particularly with regard to the last point?

**Comment by blois** [comment]
We have a fix in progress for the final point, though it may take a bit more time to land than normal. 

Will investigate the handling of the formatting strings otherwise.

**Comment by ericricky** [comment]
Awesome, thanks @blois

**Comment by colaboratory-team** [comment]
b/128634556

**Comment by blois** [comment]
We've been working on switching to a new editor engine, this bug has been fixed there. Details are at https://colab.research.google.com/notebooks/editor_details.ipynb.
