### ISSUE TITLE
Cannot print all the pages 

### ISSUE THREAD

**Issue by SanjayaGrg** [googlecolab/colabtools#4815]
only 1/1 is printed I need to print all the pages but it is not giving me all the pages

**Comment by ankitav-0205** [comment]
yes even mine

**Comment by pkirtan2** [comment]
even my also

**Comment by HailinRen** [comment]
Has anyone figured out any workaround?

**Comment by anacarolRicciardi** [comment]
the same here

**Comment by MartinStoermer** [comment]
Same here. I need the full document to append to my lab notebook and am just gatting one partial page

**Comment by cperry-goog** [comment]
So sorry. We're tracking this at b/364612873 and should have a fix out tomorrow or early next week.

**Comment by hazardouspilot** [comment]
+1

**Comment by hazardouspilot** [comment]
I found this work around in case it helps someone - https://onlineconvertfree.com/convert-format/ipynb-to-pdf/
It puts the name of the file at the start of the first page, if that's an issue you can probably find an ipynb to pdf converter free online which doesn't

**Comment by katlyn-edwards** [comment]
This should be fixed now! Sorry for the trouble, and thanks for the reports!

**Comment by arusso1105** [comment]
Confirming it’s fixedRegards,Andrew Russo1966 SE Gaskins CirclePort St Lucie, FL 34952-6639M: 954-292-7062On Sep 9, 2024, at 7:25 PM, Katlyn Edwards ***@***.***> wrote:﻿
This should be fixed now! Sorry for the trouble, and thanks for the reports!

**Comment by HiraFatima006** [comment]
Still facing the same issue

**Comment by FernandaPsihas** [comment]
Yes, this is not fixed. I get the same issue also.

**Comment by spencershumwaygoogle** [comment]
See related open threads with some workarounds:
https://github.com/googlecolab/colabtools/issues/4357

**Comment by ChristineHarvey** [comment]
> I found this work around in case it helps someone - https://onlineconvertfree.com/convert-format/ipynb-to-pdf/ It puts the name of the file at the start of the first page, if that's an issue you can probably find an ipynb to pdf converter free online which doesn't

this worked for me too, thanks so much
