### ISSUE TITLE
AssertionError: CUDA is not available

### ISSUE THREAD

**Issue by alisatwat** [googlecolab/colabtools#482]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:

**> assert torch.cuda.is_available() is returning False**

- Describe the expected behavior:

**> assert torch.cuda.is_available() should return True**

- The web browser you are using (Chrome, Firefox, Safari, etc.):
**FireFox**

- Link to self-contained notebook that reproduces this issue

[https://github.com/cypw/PyTorch-MFNet] 

Error occurred while evaluating the pre-trained model of PyTorch-MFNet.

```
cd test
# the default setting is to test trained model on ucf-101 (split1)
python evaluate_video.py
```

**Comment by kav** [comment]
Apologies if this is a dumb question but have you confirmed your runtime type is set to GPU?

**Comment by soumith** [comment]
@alisatwat indeed, the problem is what @kav suggested. Make sure your runtime type is set to GPU.

**Comment by metrizable** [comment]
Since this issue was filed a while ago, if you are still experiencing the issue, please file a new issue with steps to reproduce/screen cast or file in-product feedback.
