### ISSUE TITLE
coco package install fails on colab

### ISSUE THREAD

**Issue by mohammed-fakruddin** [googlecolab/colabtools#483]
Hi There,

On Google Colab, when I try to install the "coco" package it fails with the following error.

The command used to install the package is - 

!pip install coco

and the error message is - 

_Collecting coco
  Using cached https://files.pythonhosted.org/packages/88/3f/01432b8e521e59693f02db6eed24fc45601efe3308d96bb46ed5546c1913/coco-0.4.0.tar.gz
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-x5k8410m/coco/_

**Comment by craigcitro** [comment]
Running `!pip install -v coco` will get you more info -- it looks like the package has an undeclared dependency.

**Comment by mohammed-fakruddin** [comment]
Hi Craig, thanks for the super fast response.
I ran the "pip install -v coco" and the following is the output. But couldn't find the clues in the verbose log.

_Created temporary directory: /tmp/pip-ephem-wheel-cache-1757vesf
Created temporary directory: /tmp/pip-req-tracker-c83uu9r4
Created requirements tracker '/tmp/pip-req-tracker-c83uu9r4'
Created temporary directory: /tmp/pip-install-8ozlgkoq
Collecting coco
  1 location(s) to search for versions of coco:
  * https://pypi.org/simple/coco/
  Getting page https://pypi.org/simple/coco/
  Looking up "https://pypi.org/simple/coco/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/coco/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/coco/
    Found link https://files.pythonhosted.org/packages/29/c9/9876ea58e504002ebbd99dbae7d329adbb63526a5cd5834febb81cb523da/coco-0.0.1.tar.gz#sha256=2bd4bee18c60f67be8a7a702add4ce4783b11577cb6ccb0d7ed694bb1e1878c2 (from https://pypi.org/simple/coco/), version: 0.0.1
    Found link https://files.pythonhosted.org/packages/4d/cf/db8c6bf480dffdf78485e04b82566f03e90aace31f58f162cb392e306a9c/coco-0.0.2.tar.gz#sha256=982eabf2aa0965dd47b5985c1030967819f7ae2b7af3ef228ee18f7a00c6b8a7 (from https://pypi.org/simple/coco/), version: 0.0.2
    Found link https://files.pythonhosted.org/packages/04/d3/ccf6a37f91cd9421a70a797da0266262d6e890b78e1d46717c09242188b5/coco-0.1.0.tar.gz#sha256=e6dc01b73dcde2b1abaf6a92445350e4e9b88bfe2dcdd954bbe26205adeab423 (from https://pypi.org/simple/coco/), version: 0.1.0
    Found link https://files.pythonhosted.org/packages/87/31/389104e002e1336451b40b0f7d2fd81b13b0826950337e4fc9fa55924ff4/coco-0.1.2.tar.gz#sha256=470469853f9f7f4c54699f9bfae59d559d4042c94153ece4a2edd5efacd8d801 (from https://pypi.org/simple/coco/), version: 0.1.2
    Found link https://files.pythonhosted.org/packages/93/f0/089eb8debe1f8adaa2ed68f09553403e6498ce8af905c65e275986350237/coco-0.1.2.1.tar.gz#sha256=640971c7f2f43db14853dc9ff904827442672362ea506f592e1be30c2c5dc62d (from https://pypi.org/simple/coco/), version: 0.1.2.1
    Found link https://files.pythonhosted.org/packages/a5/e0/39f04bb7a686c09500c0d69a0032a1347d6743306366385923c9a1fe00ec/coco-0.1.2.2.tar.gz#sha256=2d206d0b398925fc56c3df6e64e619a7d589e4de193230a910b71ea0a5148aa6 (from https://pypi.org/simple/coco/), version: 0.1.2.2
    Found link https://files.pythonhosted.org/packages/eb/90/dc494163ed56db8171c11bf9b5e59596f7d40f084cf5bb014af5be1c54a7/coco-0.3.tar.gz#sha256=ee14382123c1400658a8abf9cc373e866774716e1c71d941340763a1e092a552 (from https://pypi.org/simple/coco/), version: 0.3
    Found link https://files.pythonhosted.org/packages/c4/0a/cb23bd49e6badb93fa830f0447e88ea5ffb6698aec83f814a7025bbb52c7/coco-0.3.1.tar.gz#sha256=8af7e8498bb6df60d881995cb5aff5f4ef4f9d0296ba6cad21172b79bd0b9201 (from https://pypi.org/simple/coco/), version: 0.3.1
    Found link https://files.pythonhosted.org/packages/88/3f/01432b8e521e59693f02db6eed24fc45601efe3308d96bb46ed5546c1913/coco-0.4.0.tar.gz#sha256=7612d6c57c26e0d34babe6ea2d5e2280f0738bad7e7606fead89b9af2570c7a3 (from https://pypi.org/simple/coco/), version: 0.4.0
  Using version 0.4.0 (newest of versions: 0.0.1, 0.0.2, 0.1.0, 0.1.2, 0.1.2.1, 0.1.2.2, 0.3, 0.3.1, 0.4.0)
  Created temporary directory: /tmp/pip-unpack-3w9eb162
  Looking up "https://files.pythonhosted.org/packages/88/3f/01432b8e521e59693f02db6eed24fc45601efe3308d96bb46ed5546c1913/coco-0.4.0.tar.gz" in the cache
  Current age based on date: 1897
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 1897
  Using cached https://files.pythonhosted.org/packages/88/3f/01432b8e521e59693f02db6eed24fc45601efe3308d96bb46ed5546c1913/coco-0.4.0.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/88/3f/01432b8e521e59693f02db6eed24fc45601efe3308d96bb46ed5546c1913/coco-0.4.0.tar.gz#sha256=7612d6c57c26e0d34babe6ea2d5e2280f0738bad7e7606fead89b9af2570c7a3 (from https://pypi.org/simple/coco/)
  Added coco from https://files.pythonhosted.org/packages/88/3f/01432b8e521e59693f02db6eed24fc45601efe3308d96bb46ed5546c1913/coco-0.4.0.tar.gz#sha256=7612d6c57c26e0d34babe6ea2d5e2280f0738bad7e7606fead89b9af2570c7a3 to build tracker '/tmp/pip-req-tracker-c83uu9r4'
    Running setup.py (path:/tmp/pip-install-8ozlgkoq/coco/setup.py) egg_info for package coco
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8ozlgkoq/coco/setup.py", line 9, in <module>
        import coco
      File "/tmp/pip-install-8ozlgkoq/coco/coco.py", line 28, in <module>
        from clint.textui import puts, indent, colored
    ModuleNotFoundError: No module named 'clint'
Cleaning up...
  Removing source in /tmp/pip-install-8ozlgkoq/coco
Removed coco from https://files.pythonhosted.org/packages/88/3f/01432b8e521e59693f02db6eed24fc45601efe3308d96bb46ed5546c1913/coco-0.4.0.tar.gz#sha256=7612d6c57c26e0d34babe6ea2d5e2280f0738bad7e7606fead89b9af2570c7a3 from build tracker '/tmp/pip-req-tracker-c83uu9r4'
Removed build tracker '/tmp/pip-req-tracker-c83uu9r4'
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-8ozlgkoq/coco/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 349, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 158, in prep_for_dist
    self.req.prepare_metadata()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 530, in prepare_metadata
    self.run_egg_info()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 609, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-8ozlgkoq/coco/_

**Comment by craigcitro** [comment]
I think the key lines are these:

    from clint.textui import puts, indent, colored
    ModuleNotFoundError: No module named 'clint'

In general, we don't have bandwidth to fix library issues -- if installing `clint` doesn't do the trick, I'd ask the `coco` folks.

**Comment by mohammed-fakruddin** [comment]
installing the following packages helped. Thank you very much CraigCitro! I really appreciate your pointers.

!pip install clint
!pip install crontab
!pip install tablib

**Comment by EslamHosney** [comment]
I have the same problem and installing clint, crontab, tablib doesn't do the trick

**Comment by HermesMG** [comment]
Netiher for me
