### ISSUE TITLE
Download of CIFAR10 fails

### ISSUE THREAD

**Issue by Poul-Andersson** [googlecolab/colabtools#4833]
Attempts to download CIFAR10 dataset using torchvision.datasets.CIFAR10(...) fail. Error message: " <urlopen error [Errno 110] Connection timed out>"

Running Colab in Edge browser.

File used: "https://colab.research.google.com/github/pytorch/tutorials/blob/gh-pages/_downloads/cifar10_tutorial.ipynb" 

Would greatly appreciate some help. Best, Poul

**Comment by mayankmalik-colab** [comment]
I am able to download the dataset just fine. Do you still see an issue ?
