### ISSUE TITLE
Insane security flaw

### ISSUE THREAD

**Issue by Programmer2011bird** [googlecolab/colabtools#4835]
** Note : IDK if this is the place i should report this bug but I hope it is **
so the `%%bash` command lets you do anything you want , literally !
for example I was able to install neovim just by typing `sudo apt install neovim`...
this doesn't stop anyone else from installing any other dangerous executables and running them.

**Comment by cperry-goog** [comment]
Forgot to reply to this, made me happy. We give you root access, enjoy :)
