### ISSUE TITLE
HTML Outputs for Malloy Queries are not showing in Colab!

### ISSUE THREAD

**Issue by Hasena386** [googlecolab/colabtools#4839]
I submitted a Malloy query in colab. It should place query results in HTML, JSON and the SQL query columns respectively.

The HTML output is not showing though both the Jason and SQL output is intact.  I can also save the results in a dataframe and view it with no problem.  

But can’t see the results it in the HTML output column even when I switched to different browsers(tried both Chrome and Firefox).

Wld appreciate if this is fixed :

You can try to simulate the problem using this sample below. Just run any of the queries to simulate the problem.

https://colab.research.google.com/drive/1eo1fe3878DfUvo1RcyhFUKcFhjdaSlzp?usp=sharing

Thanks
…

**Comment by metrizable** [comment]
With https://github.com/malloydata/malloy-py/pull/140, this was fixed and published in `malloy==2024.1096`.
