### ISSUE TITLE
Session disconnections without any apparent reason

### ISSUE THREAD

**Issue by adrejia** [googlecolab/colabtools#4844]
Hi Google,

I’m a Google Colab Pro user, and I’ve been experiencing frequent session disconnections without any apparent reason. Like others have mentioned, I’m training a Convolutional Neural Network (CNN) using images stored in my Google Drive. Sometimes, the session gets disconnected without showing a captcha, and this is wasting my running time credits, which is frustrating since I’m paying for this service.

I would really appreciate a solution to this issue, as I’m losing valuable time and execution credits. Thank you in advance for your help.

Best regards.

Browser: Chrome

- Notebook link: https://colab.research.google.com/drive/1BsscKZVP5i27OMuDAp4idjaU3RCjYYHR?usp=sharing

**Comment by cperry-goog** [comment]
¿Puedes enviar comentarios sobre el producto desde el menú de ayuda?

**Comment by cperry-goog** [comment]
tracking this internally at b/368464596
