### ISSUE TITLE
RAM Exhaustion and Session Crash in Google Colab

### ISSUE THREAD

**Issue by CsMukhesh** [googlecolab/colabtools#4851]
I encountered a critical issue while working on an image processing task in a Google Colab notebook. The notebook, titled "Untitled15.ipynb," was running on a Google Colab instance.
During the execution of the code, the notebook consumed all available RAM, leading to a session crash. 

Expected behavior
The code should run successfully without causing any memory-related errors or session crashes.

**What web browser you are using**
Chrome

I faced this issue within few seconds of execution.
![Screenshot_20240919-164340](https://github.com/user-attachments/assets/e5d93a9f-f5c3-4de4-a0bc-bb590d6e0216)
![Screenshot_20240919-164320](https://github.com/user-attachments/assets/83457495-46a3-4d41-aa87-88627d65f331)

**Comment by abhisharma9876** [comment]
download
https://bit.ly/4gx42eQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by cperry-goog** [comment]
If you use too much memory, the VM will crash. We provide the warnings in the UI when you are running high, you should get a higher RAM runtime or reduce the size of your data. Sorry.
