### ISSUE TITLE
hello i am also facing the same problem i  took subscription today at 1pm and now at 6 pm iam banned please helpme solve

### ISSUE THREAD

**Issue by Sarfaraz-CPU** [googlecolab/colabtools#4852]
hello i am also facing the same problem i  took subscription today at 1pm and now at 6 pm iam banned please helpme solve
![image](https://github.com/user-attachments/assets/483c6a3d-743d-4c7a-acab-4b0cfccf31b7)

_Originally posted by @Sarfaraz-CPU in https://github.com/googlecolab/colabtools/issues/4561#issuecomment-2363616945_

**Comment by Sarfaraz-CPU** [comment]
@eric-wieser @fischman @sagelywizard @hawkinsp

**Comment by Sarfaraz-CPU** [comment]
@fischman @sagelywizard @hawkinsp @eric-wieser

**Comment by katlyn-edwards** [comment]
Please file in-product feedback and reference this GitHub issue - we cannot debug account specific issues through GitHub.

**Comment by Sarfaraz-CPU** [comment]
There is no comment from their end  can you make this a priority

**Comment by katlyn-edwards** [comment]
Tracking internally with b/368644490

**Comment by Sarfaraz-CPU** [comment]
This is not resolved still , i mailed .anything from your  side
