### ISSUE TITLE
Dataset Description - California Housing

### ISSUE THREAD

**Issue by s2t2** [googlecolab/colabtools#4862]
**Describe the current behavior**
There is a "README.md" file in the "sample_data" directory in the Colab filesystem that attempts to provide a link to more information about the california housing CSV files in the "sample_data" directory. However that link is broken:

> `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at: https://developers.google.com/machine-learning/crash-course/california-housing-data-description

**Describe the expected behavior**
Expect a written description of the dataset to be in the README file, or a working link to where to find this information.

**What web browser you are using**
Chrome

**Additional context**
There is a lot of information about a similar california housing dataset from sklearn and tensorflow. However that dataset is slightly different (contains column about occupants, also expresses bedrooms and bathrooms as averages instead of totals). 

Given the nature of these differences between the datasets, it isn't totally apparent if these datasets are meant to be the same, or if they are from the same source, what transformation operations were taken on the original dataset. Any transformations should be documented.

```python
from sklearn.datasets import fetch_california_housing

dataset = fetch_california_housing()
print(type(dataset))
print(dataset.DESCR)
```

Alternatively, there is this [kaggle dataset](https://www.kaggle.com/datasets/camnugent/california-housing-prices) which more closely resembles the Colab dataset, and says:

> This data was initially featured in the following paper:
Pace, R. Kelley, and Ronald Barry. "Sparse spatial autoregressions." Statistics & Probability Letters 33.3 (1997): 291-297.
>
> and I encountered it in 'Hands-On Machine learning with Scikit-Learn and TensorFlow' by Aurélien Géron.
> Aurélien Géron wrote:
> This dataset is a modified version of the California Housing dataset > available from: [Luís Torgo's page](http://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html) (University of Porto)

**Comment by mayankmalik-colab** [comment]
Thanks for letting us know. Tracking internally at b/369843963.

**Comment by EvanWiederspan** [comment]
This has been fixed for a bit now, thanks for the report!

**Comment by paulzikopoulos** [comment]
With this fix is there anything I need to do to run the notebook, because it wasn't working for me today ... do I have to get the dataset from somewhere and mount it? I opened a ticket, hope I'm not wasting people's time.
