### ISSUE TITLE
[Connecting to a runtime to enable file browsing.]

### ISSUE THREAD

**Issue by duongtd** [googlecolab/colabtools#4863]
**Describe the current behavior**
When I open a notebook and navigate to the Files section, I constantly see the message "Connecting to a runtime to enable file browsing." This message persists and does not resolve, preventing me from accessing or browsing files in the notebook.

**Describe the expected behavior**
The expected behavior is that after opening a notebook, I should be able to access the Files section without any persistent connection issues. The "Connecting to a runtime" message should disappear quickly, allowing me to browse and manage files within the Colab environment.

**What web browser you are using**
Chrome

**Additional context**
This issue occurs consistently across all new and existing notebooks. I am using Colab Pro+.

Unfortunately, due to the nature of this issue, I cannot provide a link to a specific notebook that reproduces the problem, as it affects all notebooks I try to open.

Steps to reproduce:
1. Open any Colab notebook (new or existing).
2. Click on the "Files" icon in the left sidebar.
3. Observe the persistent "Connecting to a runtime to enable file browsing" message.

I have already tried clearing my browser cache, using different browsers, and restarting my computer, but the issue persists.

<img width="1366" alt="loi" src="https://github.com/user-attachments/assets/e021cd52-e4fb-482d-9eb2-bc033151ad35">

**Comment by katlyn-edwards** [comment]
How long have you waited? It shows in the top right that it's connecting to a runtime - this can take a little time. If you're able to reproduce this issue consistently, can you capture a HAR and upload it here? Here's a support article that explains how to capture a HAR file - https://support.google.com/admanager/answer/10358597?hl=en
