### ISSUE TITLE
html (<img src />) not displaying the image present in Gdrive

### ISSUE THREAD

**Issue by samuelard7** [googlecolab/colabtools#4864]
![Screenshot from 2024-09-25 12-37-41](https://github.com/user-attachments/assets/a146ff69-216d-4724-a94b-3d7d20f075e6)

**Describe the current behavior**
Image is not displaying even with the correct path.
But it displayed when provided with https. 
e.g: https://i.imgur.com/49FNOHj.jpg

**Describe the expected behavior**
Image should be displayed .

**What web browser you are using**
Google Chrome

**Comment by EvanWiederspan** [comment]
This isn't supported - the markdown in that text cell is running your browser, which is not running on your VM and has no access to the file system. You can instead display the image using a code cell that runs `IPython.display.Image('PATH_TO_YOUR_IMAGE')`

**Comment by samuelard7** [comment]
Okay.

> This isn't supported - the markdown in that text cell is running your browser, which is not running on your VM and has no access to the file system. You can instead display the image using a code cell that runs `IPython.display.Image('PATH_TO_YOUR_IMAGE')`
