### ISSUE TITLE
Could not load the JavaScript files

### ISSUE THREAD

**Issue by dengvol** [googlecolab/colabtools#4867]
why do I keep getting this error in colab: Error
Could not load the JavaScript files needed to display output. This is probably because your Google Account login access has expired or because third-party cookies are not allowed by your browser. Please reload this page.

Also my outputs are not showing up and I keep getting an error saying do you want to wait or quit page. This has been going on for weeks.

**Comment by dengvol** [comment]
Yes it is still super slow.



Kind Regards,



Ahmad Mitoubsi, MPH


Big Orange. Big Ideas.






________________________________

**Comment by dukes101** [comment]
I get this error repeatedly when I try to run plotly dash code. It's fixable once I restart/refresh/close out, but this is so time-consuming. Does anyone have a solution?

**Comment by dengvol** [comment]
What’s run plotly dash code?

Kind Regards,
Ahmad Mitoubsi

On Oct 4, 2024, at 5:18 PM, dukes101 ***@***.***> wrote:

﻿
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

I get this error repeatedly when I try to run plotly dash code. It's fixable once I restart/refresh/close out, but this is so time-consuming. Does anyone have a solution?

**Comment by dukes101** [comment]
*Run my dash app in colab. It buffers/stalls then this error pops up

**Comment by dengvol** [comment]
So how will this get fixed?

Kind Regards,
Ahmad Mitoubsi

On Oct 4, 2024, at 5:26 PM, dukes101 ***@***.***> wrote:

﻿
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

*Run my dash app in colab. It buffers/stalls then this error pops up

**Comment by EvanWiederspan** [comment]
We will need a repro notebook to investigate further, please share a link to one that shows this issue and make sure that it is publicly visible
