### ISSUE TITLE
No running environment, but I still pay for the GPU ? 

### ISSUE THREAD

**Issue by JustineBoutry** [googlecolab/colabtools#4868]
Hi!

Since yesterday, I'm training a network, I tried diverse GPU, I paid for even more powerful, I changed the batch number many times, but I never found a way to have access to more than 2% of the GPU, which was not really usefull. Then I started the calculation without a GPU environment, however I still pay the unit as it would be connected, why ? I feel scammed :'(

<img width="930" alt="image" src="https://github.com/user-attachments/assets/609b96c5-431b-479f-8f43-109c6e5ae595">

**Comment by cperry-goog** [comment]
Compute units are deducted based on your machine type - in this case it appears you're connected to an A100 GPU, so you're being charged 11.77 per hour. CPU runtimes will charge much much less. To disconnect and delete your A100 runtime immediately to stop being charged, please use the functionality at "Runtime > Disconnect and delete runtime", if you leave the notebook running the GPU will continue to run for a few minutes until we detect you are idle and delete it automatically.

My suspicion is the A100 runtime is still running during this screenshot.

Please submit in product feedback if you observe behavior that is different from what I described, and we can refund you.
