### ISSUE TITLE
New option: fast Drive integration

### ISSUE THREAD

**Issue by Taikakim** [googlecolab/colabtools#4869]
Many times now when I do training of AI models, I start by dumping a lot of data from my Drive to the local VM. This slows down experiments.

It would be nice to have a checboc on the runtime type for "Fast Drive", which essentially would try to choose a geographically close server to the location of my Drive data to make the downloading as fast as possible.

Other than paying megabucks for dedicated VM storage on another service, I can't think of a way to make this faster.

**Comment by EvanWiederspan** [comment]
To be clear, are you mounting Drive to get access to your files that way? Or manually uploading your files to your VM on each run. We would expect mounting Drive to be faster

Alternatively, if you always need a certain set of files, a Marketplace VM may work for you

**Comment by Taikakim** [comment]
I mount my Drive, and then download the data. Yes, I have tried the marketplace in the past, but setting them up are very cumbersome, and files have to be separately managed with buckets, etc. I've just noticed that depending on my luck the download speed from my Drive to Colab VM changes a lot right now.

**Comment by cperry-goog** [comment]
This would be lovely but not supported by the Drive team (I've tried). I'd recommend a Marketplace VM or Colab Enterprise for consistent zonal assignment and then use GCS. Sorry. Could also explore local runtimes (remote VM you control with port forwarding).
