### ISSUE TITLE
CPU runtime 

### ISSUE THREAD

**Issue by ehsankhaligh** [googlecolab/colabtools#4872]
Despite having ~23 units available, selection of CPU runtime with a higher memory option is not available as show in the screenshot.  
![Screenshot 2024-09-27 at 7 50 19 PM](https://github.com/user-attachments/assets/2f7068ff-347d-4cef-bc3d-ab68b713e212)

**Comment by cperry-goog** [comment]
High-mem is reserved for current subscribers colab.research.google.com/signup
