### ISSUE TITLE
Colab Pro+ does not give me an option for "Background Execution"

### ISSUE THREAD

**Issue by smosharof** [googlecolab/colabtools#4874]
**Describe the current behavior**
I have a Colab Pro+ subscription but I do not see an option for "Background Execution".

**Describe the expected behavior**
I need to be able to run jobs unattended (aka Background Execution).

**What web browser you are using**
Chrome

**Additional context**
See attachment

**Comment by katlyn-edwards** [comment]
I think this is just enabled by default. 

Note - from https://colab.research.google.com/signup it says:

Background execution
With compute units, your actively running notebook will continue running for up to 24hrs, even if you close your browser.



Reading https://colab.research.google.com/notebooks/pro.ipynb
Colab Pro+ users have access to background execution, where notebooks will continue executing even after you've closed a browser tab. This is always enabled in Pro+ runtimes as long as you have compute units available.

If you're not getting background execution by default, do let us know.
