### ISSUE TITLE
Typing overwrites existing, non-selected text, regardless of Insert key on keyboard.

### ISSUE THREAD

**Issue by pr3sidentspence** [googlecolab/colabtools#488]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: 
Sometimes when typing in a cell and there is existing text after the cursor on that line the text is overwritten instead of new characters being inserted. Must save notebook and reload page to make it stop.

- Describe the expected behavior:
This should not happen, or it should only happen if I toggle the insert key on my keyboard.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome Version 72.0.3626.121 (Official Build) (64-bit)

- Link to self-contained notebook that reproduces this issue
Happens randomly.

**Comment by metrizable** [comment]
@pr3sidentspence Are you able to reproduce this with all add-ons disabled in incognito mode?

Also, since this issue was filed a while ago, if you are still experiencing the issue, please reopen with a set of reproducible steps.
