### ISSUE TITLE
White mid-line in fraction in dark mode, please.

### ISSUE THREAD

**Issue by YijiaoCao** [googlecolab/colabtools#4881]
The mid-line is always black in \frac{}{} , even in dark mode. A white one is preferred.

**Comment by cperry-goog** [comment]
thanks - tracking internally at b/372757905

**Comment by EvanWiederspan** [comment]
What browser / OS are you using? I see it render fine on ChromeOS in a text cell

**Comment by katlyn-edwards** [comment]
![BBdBaimLntpswEQ](https://github.com/user-attachments/assets/fa815bc2-f24a-4407-b7d2-91047f42f85b)


Is there something else we should be doing to repro this issue?

**Comment by cperry-goog** [comment]
We are unable to reproduce this - please open an issue with reproducible steps.
