### ISSUE TITLE
!pip install cirq 

### ISSUE THREAD

**Issue by peterbabulik** [googlecolab/colabtools#4888]
!!! Use this: 

pip install cirq==0.15.0

Instead of this:

pip install cirq

------------------------------------------------

Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by mayankmalik-colab** [comment]
This is not Colab specific issue. You will get more information if you try `!pip install -v cirq` . This is an ongoing issue - https://github.com/quantumlib/Cirq/issues/6754 .

**Comment by pavoljuhas** [comment]
You can also use
```
pip install cirq~=1.0.dev
```
to install the latest development which should get a working quil dependency.
