### ISSUE TITLE
Python version upgrade

### ISSUE THREAD

**Issue by nadirdbit** [googlecolab/colabtools#4890]
Hi,

Current version of Python is 3.10.12 which is now 15 months old - kindly arrange for upgrade to a newer release like 3.12.x so that we may avail the newer improvements:

https://docs.python.org/3.12/whatsnew/3.12.html
https://docs.python.org/3.11/whatsnew/3.11.html

Thank you.

**Comment by mayankmalik-colab** [comment]
Hi, we are working on upgrading Python to 3.11. We anticipate the upgrade will be done in the next few months.

**Comment by nadirdbit** [comment]
Hi Mayank,

Are estimated dates available for when the Python 3.11 and Python 3.12 upgrades will be kindly provided?

Thank you.

**Comment by EvanWiederspan** [comment]
We will be updating to Python 3.11 in early January, see https://github.com/googlecolab/colabtools/issues/4935

**Comment by benlai1130** [comment]
How about Python 3.12? when will the Python 3.12 upgrades be kindly provided?

**Comment by KenOcheltree** [comment]
I am running code that requires Python 3.12. Is there any way to run that on Colab?
