### ISSUE TITLE
Celsius to Fahrenheit Print Model Error

### ISSUE THREAD

**Issue by NwekeGoddy** [googlecolab/colabtools#4891]
**Describe the current behavior**
On this Notebook on Colab used to practice - l02c01_celsius_to_fahrenheit.ipynb
This part of the code throws an error
- print(model.predict([100.0]))

ValueError                                Traceback (most recent call last)
[<ipython-input-18-5f23ede71fd3>](https://localhost:8080/#) in <cell line: 1>()
----> 1 print(model.predict([100.0]))

**Describe the expected behavior**
-print(model.predict(np.array([[100.0]])))
if replaced with this works 

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
 -

**Comment by cperry-goog** [comment]
Looks like you're talking about this notebook which our team does not maintain: https://github.com/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l02c01_celsius_to_fahrenheit.ipynb

Can you file an issue on the Tensorflow repo instead? Thanks.
