### ISSUE TITLE
GPU is so slow

### ISSUE THREAD

**Issue by ahmedabdelhameed** [googlecolab/colabtools#49]
I am training an RNN model.  My laptop CPU is much faster than The GPU. Is that normal?

**Comment by fischman** [comment]
That's very unexpected.  Can you share a complete/minimal reproduction notebook either publicly or just with colaboratory-team@google.com ?

Are you perhaps doing a lot of checkpointing?  Disk bandwidth is likely to be the main aspect in which a modern laptop is significantly faster than the VMs being used.
