### ISSUE TITLE
Dropdown text is not visible

### ISSUE THREAD

**Issue by sorydi3** [googlecolab/colabtools#4901]
**Describe the current behavior**
When attempting to save a copy of a notebook to GitHub, the text in the dropdown menu is not visible.
Steps to Reproduce:
1. Go to settings
2. Enable GitHub sharing
![image](https://github.com/user-attachments/assets/fd33ee68-648e-47a2-b2de-ec280b440400)
5. Go to "Save a copy to GitHub"
7. Click the dropdown menu
![image](https://github.com/user-attachments/assets/a2242f21-f662-4ace-ae2c-7b9e56713571)

**Describe the expected behavior**

The background color of the dropdown menu should match the host theme, ensuring text visibility.

**What web browser you are using**

Chrome

**Additional context**
This issue appears to be related to a mismatch between the dropdown menu's background color and the text color, likely caused by inconsistent theme application.

**Comment by EvanWiederspan** [comment]
Thanks for the report, tracking internally as b/https://b.corp.google.com/issues/374104271

**Comment by EvanWiederspan** [comment]
This should be fixed now, thanks for the report!
