### ISSUE TITLE
connecting sql on google colab

### ISSUE THREAD

**Issue by Monamuruganandham** [googlecolab/colabtools#4906]
### I want to connect sql in google colab.but that shows local host can't be connected.

connection = connector.connect(
    host = "localhost",
    user = "root",
    password = "*********"
)
connection

MySQLInterfaceError                       Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py in _open_connection(self)
    334         try:
--> 335             self._cmysql.connect(**cnx_kwargs)
    336             self._cmysql.converter_str_fallback = self._converter_str_fallback

MySQLInterfaceError: Can't connect to MySQL server on 'localhost:3306' (99)

The above exception was the direct cause of the following exception:

DatabaseError                             Traceback (most recent call last)
4 frames
/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py in _open_connection(self)
    338                 self.converter.str_fallback = self._converter_str_fallback
    339         except MySQLInterfaceError as err:
--> 340             raise get_mysql_exception(
    341                 msg=err.msg, errno=err.errno, sqlstate=err.sqlstate
    342             ) from err

DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (99)

kindly help me with this.

**Comment by cperry-goog** [comment]
I think you'll have more luck on Stackoverflow, this looks like not a Colab issue.
