### ISSUE TITLE
Generative AI feature will, even if explicitly asked not to, continue to output incorrect code scraped from the internet rather than trying to solve a problem itself.

### ISSUE THREAD

**Issue by MatthewCWeston** [googlecolab/colabtools#4908]
**Describe the current behavior**
In many cases, the new generative AI will attempt to look up a solution rather than writing one. Often, this code is incorrect or irrelevant. Unfortunately, the pipeline used to do this appears to override the interpretation of the request itself, meaning that explicitly telling the AI not to use this feature does not work.

**Describe the expected behavior**
If I explicitly state in the prompt that the system is not to look up code on the internet, search should not be used. Ideally, a toggle in the prompt to hard-set whether the search pipeline is called in the first place would be the most reliable solution, but at minimum it should not countermand a user request.

**What web browser you are using**
Chrome

**Comment by colaboratory-team** [comment]
Thanks for reporting! Could you share a minimum reproducible notebook and/or the prompt you asked in Gemini chat?
