### ISSUE TITLE
I encountered a bug in the TensorFlow tutorial of overfit_and_underfit.ipynb

### ISSUE THREAD

**Issue by liaojiaxin97** [googlecolab/colabtools#4909]
**Describe the current behavior**
https://tensorflow.google.cn/tutorials/keras/overfit_and_underfit?hl=zh-cn
I am new to TensorFlow and am learning the overFitting chapter, but I have a bug when I run the fitting chapter cloab(https://tensorflow.google.cn/tutorials/keras/overfit_and_underfit?hl=zh-cn)
![image](https://github.com/user-attachments/assets/a2939bf8-4bea-4f4a-9e74-9cb285fe5b2a)

**Describe the expected behavior**
Expect it to work

**What web browser you are using**
edge
**Additional context**

**Comment by liaojiaxin97** [comment]
![image](https://github.com/user-attachments/assets/85fcc4ab-9a8e-43ef-96d4-74f05fc78495)
When I run the file "save_and_load.ipynb", it returns an error with no changes

**Comment by liaojiaxin97** [comment]
Why there are so many errors in the code in the tutorial, is it because it is the new TensorFlow version, but the code is the old version?

**Comment by cperry-goog** [comment]
Please refer Tensorflow issues to Tensorflow: https://www.tensorflow.org/community
