### ISSUE TITLE
Gradio GUI issue in Colab. ModuleNotFoundError: No module named 'multipart.multipart'; 'multipart' is not a package

### ISSUE THREAD

**Issue by jsteward2930** [googlecolab/colabtools#4910]
I have been using Gradio in Google Colab the past few weeks to create a prototype application. Today an error started to occur when I try to 'import gradio as gr'.  I was wondering if this may be caused by an update to Gradio or Google Colab that is now causing compatibility issues between the package and the Colab environment.  Trying to install multipart and python-multipart did not help.

!pip install gradio

...
Downloading websockets-12.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (130 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 9.2 MB/s eta 0:00:00
Installing collected packages: pydub, websockets, tomlkit, semantic-version, ruff, python-multipart, orjson, markupsafe, h11, ffmpy, aiofiles, uvicorn, starlette, huggingface-hub, httpcore, httpx, fastapi, gradio-client, gradio
  Attempting uninstall: markupsafe
    Found existing installation: MarkupSafe 3.0.1
    Uninstalling MarkupSafe-3.0.1:
      Successfully uninstalled MarkupSafe-3.0.1
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.24.7
    Uninstalling huggingface-hub-0.24.7:
      Successfully uninstalled huggingface-hub-0.24.7
Successfully installed aiofiles-23.2.1 fastapi-0.115.2 ffmpy-0.4.0 gradio-5.1.0 gradio-client-1.4.0 h11-0.14.0 httpcore-1.0.6 httpx-0.27.2 huggingface-hub-0.26.0 markupsafe-2.1.5 orjson-3.10.9 pydub-0.25.1 python-multipart-0.0.13 ruff-0.7.0 semantic-version-2.10.0 starlette-0.40.0 tomlkit-0.12.0 uvicorn-0.32.0 websockets-12.0

import gradio as gr

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-43eca54f7d45>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import gradio as gr

6 frames
[/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py](https://localhost:8080/#) in <module>
     32 import gradio_client.utils as client_utils
     33 import httpx
---> 34 import multipart
     35 from gradio_client.documentation import document
     36 from multipart.multipart import parse_options_header

ModuleNotFoundError: No module named 'multipart'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by cperry-goog** [comment]
I think you'll need to contact Gradio for this, or the notebook author.
