### ISSUE TITLE
Select runtime type menue is squashed.

### ISSUE THREAD

**Issue by palmcorp** [googlecolab/colabtools#4912]
**Describe the current behavior**
Want to select GPU configuration.  Select <Runtime> <change runtime type>  
the menu is squeezed into a couple of lines so cant see selections.  Image provided

**Describe the expected behavior**
Expect to see a window with visible selections.

**What web browser you are using**
Chrome ( 239.0.6668.101) , FireFox.  

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
![chrom_change_runtme_display](https://github.com/user-attachments/assets/9d010bc5-b1dc-45b8-be07-70cea643d076)

**Comment by katlyn-edwards** [comment]
This looks like https://github.com/googlecolab/colabtools/issues/4389 

Specifically this is caused by Chrome extensions -- please try disabling extensions one by one to see which one is causing the issue.
