### ISSUE TITLE
Unexpected Runtime Error for Scheduled Executions with Colab Pro

### ISSUE THREAD

**Issue by epie-godfred** [googlecolab/colabtools#4917]
**Describe the current behavior**
Scheduled Notebook  executions with a Colab Pro Account somestimes exit with an Error "Unexpected Runtime Error". 

**Describe the expected behavior**
Expect the scheduled runs of the Notebook, to run smoothly without errors, exactly like when I manually run the Notebooks.

**What web browser you are using**
Firefox

**Additional context**
I have already reported this issue using the Help -> Send Feedback with snapshots describing the problem more than two week now. The Colab Pro Account is ramcolabpro@gmail.com. I still have not received any feedback regarding this error.

**Comment by momonc-glitch** [comment]
Same thing

**Comment by cperry-goog** [comment]
duplicate with #4887
