### ISSUE TITLE
CUDA Kernel error when running ultralytics v8 training.

### ISSUE THREAD

**Issue by kvkamal** [googlecolab/colabtools#4919]
**Describe the current behavior**
Model Training stops after 2 epochs with the following error: I'm starting to see this now. 

Trying to run ultralytics YOLOV8 training from. Has there been any updates to Cuda/Ultralytics?

[/usr/local/lib/python3.10/dist-packages/ultralytics/utils/tal.py](https://localhost:8080/#) in get_box_metrics(self, pd_scores, pd_bboxes, gt_labels, gt_bboxes, mask_gt)
111 ind[1] = gt_labels.squeeze(-1) # b, max_num_obj
112 # Get the scores of each grid for each gt cls
--> 113 bbox_scores[mask_gt] = pd_scores[ind[0], :, ind[1]][mask_gt] # b, max_num_obj, hw
114
115 # (b, max_num_obj, 1, 4), (b, 1, hw, 4)

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

**Describe the expected behavior**
MOdel training to continue.

**What web browser you are using**
(Chrome)

**Comment by cperry-goog** [comment]
We haven't updated CUDA recently no, and we don't pre-install Ultralytics - I'd contact the notebook author for help.
