### ISSUE TITLE
Unable to save to a public GitHub repo (not displayed in dropdown)

### ISSUE THREAD

**Issue by willingc** [googlecolab/colabtools#492]
- Describe the current behavior:

Save to GitHub dropdown does not list all of my public repos. I am unable to select a repo beyond the letter P.  
![image](https://user-images.githubusercontent.com/2680980/54850560-a64e2f00-4ca4-11e9-817b-5376ab6fee18.png)

- Describe the expected behavior:

I would expect to be able to select any public repo for my GitHub account.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/drive/19HbsJxt_04rI3Dy_twTPJ7FJ3uWLZ1cv

**Comment by craigcitro** [comment]
Hi @willingc -- this is an unfortunate known bug: we only load 500 repos from github. 😞

Unfortunately, I don't have an easy workaround offhand for saving.

b/115572230

**Comment by willingc** [comment]
Thanks @craigcitro. I figured it was something like that. I'll just use a different github org for saving. I'll go ahead and close since you are aware of the bug.

**Comment by craigcitro** [comment]
Sorry about the trouble, and thanks for the bug report!
