### ISSUE TITLE
Primesieve installment error

### ISSUE THREAD

**Issue by jddeoro20** [googlecolab/colabtools#4924]
**Describe the current behavior**
i'm trying to install primesieve but it givees me this error

Collecting primesieve
  Using cached primesieve-2.3.4.tar.gz (146 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: primesieve
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for primesieve (setup.py) ... error
  ERROR: Failed building wheel for primesieve
  Running setup.py clean for primesieve
Failed to build primesieve
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (primesieve)

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
Brave

**Comment by metrizable** [comment]
@jddeoro20 Thanks for filing the issue and thanks for using Colab.

I tried installing `primesieve==2.3.4` from PyPI and from source and both installations failed. Adding `--verbose` to `pip install`, it fails when trying to build the `primesieve._primesieve` extension with `No module named 'distutils.msvccompiler'`.

One work-around I found was to downgrade to `setuptools<74`, restart the session, then install `primesieve<=2.3.0` (newer versions of `primesieve` fail for other reasons):

![59qWEg4ziAw3Zqe](https://github.com/user-attachments/assets/9a5f59b1-f12f-4f30-a7cc-0781552f72c1)

I'd recommend reaching out to the [package maintainers](https://pypi.org/project/primesieve/), referencing this issue.
