### ISSUE TITLE
Inserting ` and pressing right arrow deletes text

### ISSUE THREAD

**Issue by axelsparr** [googlecolab/colabtools#4926]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

When a \` character is typed and right arrow key is pressed another \` is inserted removing the adjacent character. This doesn't happen if \` is copy pasted. It's present both inside and outside of comments. In code cells if no other character is next to the \` it creates a new line and a new \`. It's present both in code and markdown cells but in markdown cells it doesn't add another \` unless there is a character already next to the initial \`.

**Describe the expected behavior**
For the cursor to simply move without removing text.

**What web browser you are using**
Firefox
**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
What language is your keyboard out of curiosity? And what OS?

Can you try this in incognito mode? Could be an extension impacting you.
