### ISSUE TITLE
Can not open files in google drive!

### ISSUE THREAD

**Issue by zc8340311** [googlecolab/colabtools#4927]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
Do you mean mounting your Drive on your VM? Or opening Drive notebooks? We haven't seen widespread issues with either, so we'll need more info to be able to diagnose. 

If the issue is in a notebook that you're running, please share the notebook so that we can take a look

**Comment by zc8340311** [comment]
I understand what is going on. The issue is related to the multiple account management.
