### ISSUE TITLE
A line in the middle of each cell

### ISSUE THREAD

**Issue by ryan-sam-daniel** [googlecolab/colabtools#4933]
![Screenshot (19)](https://github.com/user-attachments/assets/e24c5d11-f8f2-444a-8205-565cf558a9c7)

**Comment by ryan-sam-daniel** [comment]
remove the center in the cell

**Comment by katlyn-edwards** [comment]
![image](https://github.com/user-attachments/assets/905e0803-cb9f-4eb4-b9cc-f440a7e8df92)


This is from the vertical ruler setting. I believe you can set it to 0 to remove it.
