### ISSUE TITLE
Line number and column number can be provided in the googlecolab

### ISSUE THREAD

**Issue by SenthilKumarMCH** [googlecolab/colabtools#4938]
**Is your feature request related to a problem? Please describe.**
The content of the "for" loop and "if" condition should be aligned with the appropriate space from the start of the line.  when we have lengthy content in the for loop or if condition, it is very difficult to check the alignment between starting and ending. Since the space is not maintained properly, the for loop/if condition ends over there. It may lead to errors in terms. 
Also, Generally, the error message is given with a line number. However, no line number is given on the left side of the editor. The user finds a difficult to trace the place to the corresponding error message.

**Describe the solution you'd like**
The line number can be given on the left side of the editor. Also, the column number in each line can be displayed somewhere in the editor window while placing the cursor anywhere in the place.

**Describe alternatives you've considered**
The line and column numbers can be given on the left side of the editor window.

**Additional context**
The well-known problem of all users

**Comment by katlyn-edwards** [comment]
Can you provide a minimal reproducible notebook? I'm not quite sure what you're describing. 

Note that "show line numbers" is a configurable setting under "Editor" -- you might have to enable it.
<img width="739" alt="Screenshot 2024-11-11 at 2 08 18 PM" src="https://github.com/user-attachments/assets/8f550c38-dabb-4357-9c23-5526a0939965">
