### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by mikpusch** [googlecolab/colabtools#4940]
Colabfold gives the following error:

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-6-b1110d0a69bd>](https://localhost:8080/#) in <cell line: 7>()
      5 from colabfold.download import download_alphafold_params, default_data_dir
      6 from colabfold.utils import setup_logging
----> 7 from colabfold.batch import get_queries, run
      8 
      9 from pathlib import Path

**Comment by cperry-goog** [comment]
Please contact the notebook author for help on this.
