### ISSUE TITLE
Cannot Authenticate with Google, Google feedback Bad request but my colleages all can do it

### ISSUE THREAD

**Issue by PhanAnh3001** [googlecolab/colabtools#4942]
Step1:
![image](https://github.com/user-attachments/assets/9fcc5df1-0764-4a49-9ffa-f86c81857eb1)

Step2:
![image](https://github.com/user-attachments/assets/bfac1c7e-6775-4647-a028-9f782daf4c8b)

Step3:
![image](https://github.com/user-attachments/assets/a2ea215f-a8b1-4b07-ab7c-a62b6ea2fbba)

My colleages able to connect, but I cannot

**Comment by cperry-goog** [comment]
This is outside of our scope - I'd contact your organization's admin to see what differences exist with your account. Sorry.
