### ISSUE TITLE
Cannot import scanpy

### ISSUE THREAD

**Issue by Sonali513** [googlecolab/colabtools#4943]
**Describe the current behavior**
The scanpy package is being imported as sc after !pip install

**Describe the expected behavior**
The following command fails with an error described below:
import scanpy as sc

--------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/cupy/__init__.py](https://localhost:8080/#) in <module>
     16 try:
---> 17     from cupy import _core  # NOQA
     18 except ImportError as exc:

10 frames
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/cupy/__init__.py](https://localhost:8080/#) in <module>
     17     from cupy import _core  # NOQA
     18 except ImportError as exc:
---> 19     raise ImportError(f'''
     20 ================================================================
     21 {_environment._diagnose_import_error()}

ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
================================================================

**What web browser you are using**
Chrome

**Additional context**
https://colab.research.google.com/drive/15bp2VCjUGDnkvQbe2P-sdy4bFJGtRAb7?usp=sharing

**Comment by metrizable** [comment]
@Sonali513 Thanks for reporting the issue and thanks for using Colab.

When running on a CPU runtime, I got a similar error that you've reported when installing and importing `scanpy` and `squidpy` (as in the notebook you shared). However, I was able to successfully install and import `scanpy` and `squidpy` when I selected and ran on a GPU runtime (a T4, for example).

You can run your notebook in a GPU runtime by selecting, say, a T4 GPU accelerator via the "Runtime > Change runtime type" menu option.
