### ISSUE TITLE
Cannot see the content when open a modal, such as to "change runtime type" modal

### ISSUE THREAD

**Issue by xuanswe** [googlecolab/colabtools#4944]
**Describe the current behavior**

![image](https://github.com/user-attachments/assets/ad2c09bf-9497-4bd4-a534-fed9be01cfe1)

![image](https://github.com/user-attachments/assets/d590e699-ac31-4116-97fd-dabe85b9b8b1)

**Describe the expected behavior**

![image](https://github.com/user-attachments/assets/b146d934-4603-4f20-ac72-41fc23e76d6c)

**What web browser you are using**
Microsoft Edge Version 130.0.2849.80 (Official build) (64-bit)
Windows 11 Pro 23H2 (OS Build 22631.4317)

**Comment by katlyn-edwards** [comment]
Please see https://github.com/googlecolab/colabtools/issues/4266#issue-2057960191
