### ISSUE TITLE
Collab access blocked

### ISSUE THREAD

**Issue by VamuveTV** [googlecolab/colabtools#4946]
I already filled the report error at stackoverflow as suggested by the collabs error message, but so far, couldn´t had a proper response on what just happened and how it can be fixed.

The problem is while i was trying to access my collabs account, i was suddenly surprised to see that the access was blocked with this msg "count has been blocked from accessing Colab runtimes due to suspected abusive activity. This does not impact access to other Google products. If you believe this has been done in error, review the usage limitations and file an appeal. "

I have no idea what kind of "suspected abusive activity" is this. I had never have this problem before. I always use colab for my professional area only, related to sound editing.

Can someone help and explain why it was suddenly blocked ? Was it a error ? How to unblock the access ? I need the access for my job

Best Regards

Guga

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by jaesong-colab** [comment]
It should be unblocked now. Let me know if you see any more problems.
