### ISSUE TITLE
Colab Access Blocked

### ISSUE THREAD

**Issue by jjschwab** [googlecolab/colabtools#4947]
My Colab access was suddenly blocked for no clear reason while I was using it for my job. 

**Describe the current behavior**
I am having the same issue reported by [VamuveTV](https://github.com/VamuveTV) referenced here: https://github.com/googlecolab/colabtools/issues/4946
When I try to connect to a colab runtime, I get the message "This account has been blocked from accessing Colab runtimes due to suspected abusive activity. This does not impact access to other Google products. If you believe this has been done in error, review the [usage limitations](https://research.google.com/colaboratory/faq.html#limitations-and-restrictions) and [file an appeal](https://colab.research.google.com/drive/1pDfDpMK2GZDYExwA4r4ZVet_2_-QldLK#)." despite not performing any out-of-the ordinary actions in my colab environment. 

**Describe the expected behavior**
I expected to connect to my colab runtime to continue working on my code.
**What web browser you are using**
Chrome
**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by jjschwab** [comment]
My account was unblocked after a short amount of time, but I didn't learn anything about what caused this problem.

**Comment by jaesong-colab** [comment]
It was an error on our end. The accounts that were banned have been unbanned

**Comment by jjschwab** [comment]
> It was an error on our end. The accounts that were banned have been unbanned

Thank you. It seems that my account was unblocked for a short time, but when I try it right now it says it is blocked again. Should I just wait a while for this to be resolved?

**Comment by jaesong-colab** [comment]
It should not have been blocked again. Are you still blocked?

**Comment by jjschwab** [comment]
Now it seems to be blocked again. I am not sure if it is a result of my code or not.

**Comment by jjschwab** [comment]
Now I am unblocked again. It seems that the fix to this issue may not be stable.

**Comment by veronica-hoffman** [comment]
I am having exactly the same issue. Not sure if that helps resolve anything, but it's not just you having this problem.

**Comment by jaesong-colab** [comment]
It should be unblocked now. Let me know if it happens again
