### ISSUE TITLE
[Feature Request]: Run Gazebo simulation likewise tensorboard

### ISSUE THREAD

**Issue by talregev** [googlecolab/colabtools#495]
I want to run and view Gazebo simulator In google colab like you do in TensorFlow.
I don't have all the knowledge how to do it.
I want it for  Reinforcement Learning, to train a robot in deep neural net. 
I try partial with gazebo, gazebo web and ngrok. but most of the time it not work.
Can you help? 
Can you make a general case like in tensorboard, that the code block will listen to localhost with some port and display it as an html page?
I already have some partial success - most of the time it does not work:
[Gazebo in cloab][1]

[1]:https://colab.research.google.com/drive/1A-miW8cTRKzs7B0m1m4enfiFySzBhsgN

**Comment by dineshresearch** [comment]
Anyupdate?

**Comment by blois** [comment]
`!hg clone https://bitbucket.org/osrf/gzweb` is a 404.

For port generation, maybe use:

```python
import portpicker
PORT_NUMBER = portpicker.pick_unused_port()
```

Then as an alternative to ngrok possibly try:
```python
from google.colab import output
output.serve_kernel_port_as_iframe(PORT_NUMBER)
```

**Comment by talregev** [comment]
gazebo switch to GitHub: 
https://github.com/osrf/gazebo

Also they planing to switch to new library: 
https://github.com/ignitionrobotics/ign-gazebo

**Comment by talregev** [comment]
@blois Can you update my colab and share it with us?

**Comment by blois** [comment]
The gazebo setup and install steps seem to be fairly outdated- if someone more familiar with Gazebo can update those I can take a look at getting it to work in Colab.

**Comment by talregev** [comment]
>  !hg clone https://bitbucket.org/osrf/gzweb is a 404.

@blois I fix this line. replace with the github. should work. Can you check and see if it work?

**Comment by blois** [comment]
@talregev I'm seeing a bunch of build errors compiling gzweb/gzbridge.

https://colab.research.google.com/gist/blois/076fa35d5268f4b2e465d4e7dcc6fea2/copy-of-gazebo.ipynb#scrollTo=KHVrPCNDELL7

**Comment by talregev** [comment]
Just a sec, I update on the way.

**Comment by talregev** [comment]
@blois Try Now. It should be a lot of warning in gzweb, it always like that.

**Comment by blois** [comment]
@talregev I'm still seeing errors:

```
gzbridge.target.mk:127: recipe for target 'Debug/obj.target/gzbridge/GZNode.o' failed
make: *** [Debug/obj.target/gzbridge/GZNode.o] Error 1
make: Leaving directory '/content/gzweb/gzbridge/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/content/gzweb/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.19.112+
gyp ERR! command "/tools/node/bin/node" "/content/gzweb/node_modules/.bin/node-gyp" "build" "-d"
gyp ERR! cwd /content/gzweb/gzbridge
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v7.1.0
```

Then later:

```

> gzweb@1.3.0 start /content/gzweb
> if [ $npm_config_port ]; then port=$npm_config_port; fi; cd gzbridge && ./server.js $port "17579"

module.js:549
    throw err;
    ^

Error: Cannot find module './build/Debug/gzbridge'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/content/gzweb/gzbridge/server.js:9:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by talregev** [comment]
Yes. Sorry. I am not sure I will able to compile gazebo web with the new gazeb 11. 
The instruction for install gazebo web is for gazebo 7. I am not sure I want that. 
I am still trying.

**Comment by talregev** [comment]
@blois How to tell gcc to compile with -std=c++14 by default?

**Comment by talregev** [comment]
@blois I also get a gcc errors when compile gzweb. I don't know how to solve it.

**Comment by talregev** [comment]
@blois I have another example how to use webots in google colab.
There is an errors there too, but it it is in python and tensorflow. It will be interesting for you to try to fix it?
