### ISSUE TITLE
Operation is not working.

### ISSUE THREAD

**Issue by seoyeon76** [googlecolab/colabtools#4955]
Why not?
![스크린샷 2024-11-18 153355](https://github.com/user-attachments/assets/9cb1dd47-d571-479f-8d2e-d017d848028f)
![스크린샷 2024-11-19 171535](https://github.com/user-attachments/assets/f792f99c-d142-45b3-9743-aac76209e4fa)

**Comment by colaboratory-team** [comment]
I would reach out to the notebook author instead
