### ISSUE TITLE
L4 GPU is not working

### ISSUE THREAD

**Issue by pixelpathologist** [googlecolab/colabtools#4957]
**Describe the current behavior**
I´m trying to use the GPU using detectron2 and when I try to use de L4 GPU doesn´t connects. 

**Describe the expected behavior**

Upload and see images and use Detectron2 por image analysis 

**What web browser you are using**
Chrome

**Additional context**
![image](https://github.com/user-attachments/assets/85f51275-768a-4446-943c-562104091824)

**Comment by colaboratory-team** [comment]
This seems to be an issue with installing the 5.1 version of pyyaml - Colab already include version 6, are you able to skip that pip install step and use that version?
