### ISSUE TITLE
Unable to see output of image in colab

### ISSUE THREAD

**Issue by LCKZCM** [googlecolab/colabtools#4958]
**Describe the current behavior**
When I'm using plt.show(), the image pops up and then all the content below the cell disappeared. I tried to use incognito, disabling all the extensions and even tried on the other computer, but the thing is still happening.

**What web browser you are using**
Google Chrome
![image](https://github.com/user-attachments/assets/bd6a7fe3-5ce1-4478-8ce5-2aeda7bbd3b1)
![image](https://github.com/user-attachments/assets/72deb184-08e7-424f-87b3-55bd631c2b86)

**Comment by colaboratory-team** [comment]
I'm not able to reproduce this, can you share a minimal repro notebook that shows this error?
