### ISSUE TITLE
Tengo un problema al ejecutar un codigo, los script aparecen y desaparecen

### ISSUE THREAD

**Issue by BalkiTena** [googlecolab/colabtools#4965]
El problema que estoy teniendo al ejecutar mi codigo en el script aparece y desaparece y no hay formar de visualizarlo. Pensé que era un problema con mi navegador, elimine el caché y cookies pero el problema persiste. Además entrando a este foro veo que no soy el único que tiene este problema.

**Comment by cperry-goog** [comment]
duplicate of #4964
