### ISSUE TITLE
Unable to edit the existing Text/Comment section (showing Blue) & leading to auto populate while creating the new text tab 

### ISSUE THREAD

**Issue by thakur028** [googlecolab/colabtools#4968]
The current behavior
Unable to edit the existing text/comment sections in Google Colab. When selecting a text cell (highlighted in blue), editing is disabled. Additionally, creating a new text cell results in auto-populated of a blank cell which we can't edit as well.

The expected behavior
The existing text/comment cells should be editable directly when selected. New text cells should open as blank for the user to input content without auto-populated new Text section.

What web browser you are using
(Example: Chrome, Version 118.0.5993.117)

Additional context

This issue occurs even when attempting to edit or create new text cells in both saved and unsaved notebooks.

Steps to reproduce:
Open an existing Google Colab notebook.
Attempt to edit a text cell.
Create a new text cell and observe auto-populated new boxes.

![{EC9E3564-B489-41C4-A1C4-E5DA2E4A884F}](https://github.com/user-attachments/assets/03e92892-c5bc-4ff7-bff3-71cbae65d3b6)

**Comment by cperry-goog** [comment]
When selected, the cells are not editable, that is working as intended. You'll need to double click to edit. We're exploring adding an explicit icon as well.
