### ISSUE TITLE
Colab Runtime Crash - Herbie Package during cfgrib call

### ISSUE THREAD

**Issue by fleegs79** [googlecolab/colabtools#4969]
**Describe the current behavior**
I have several scripts that use the [Herbie package](https://github.com/blaylockbk/Herbie) to grab weather model grib data and convert them to an xarray dataset.  These scripts have been working fine over the last 1.5 years and all the way through Saturday.  Then on Monday morning when running an unchanged script (or any of my other scripts that use Herbie), the Colab runtime quickly crashes after grabbing the data.  I've tracked it down within the Herbie core.py xarray method and where it calles cfgrid to open the downloaded dataset.  From what I can tell, none of the packages have updated recently (I even tried downgrading a few of them with no help), so I was curious if there was a change on the Google Colab side of things.  

Thank you in advance for the assistance. 

**Describe the expected behavior**
The xarray.Dataset would be outputted and not a crash of the runtime. 

**What web browser you are using**
Chrome or Edge

**Additional context**
This issue can be seen in [this notebook](https://colab.research.google.com/gist/fleegs79/c423d154fb19650a9252d70f29e651aa/model-data-herbie-crash.ipynb). If I run this same script in a Jupyter Notebook, I'll get an output like this: 
<img width="804" alt="Colab-Crash-Herbie" src="https://github.com/user-attachments/assets/98c6259f-18a1-4677-ae5d-c4b805579da2">

**Comment by cperry-goog** [comment]
I think you're right, it must be a dependency change in our base container which we publish at https://github.com/googlecolab/backend-info -- I'd recommend looking over that and investigating which dependency changed and installing a previous version explicitly in code (which you may want to do in general for relying on a notebook over a long time)

**Comment by jp2nyy** [comment]
I also am having the issue with Herbie in Google Colab.

**Comment by fleegs79** [comment]
Thank you for the assistance!  I've tracked it down to the ecCodes module and rolled it back to the previous version.  

Thanks again,

fleegs79
