### ISSUE TITLE
Extend GDrive mount/auth timeout

### ISSUE THREAD

**Issue by olaviinha** [googlecolab/colabtools#4970]
**Is your feature request related to a problem? Please describe.**
Usually when any of my notebooks is "finished", I clean it up and try to make it a user-friendly UI, by minimizing the number of cells, making them forms, trying to do all the necessary installations, Drive mounting, etc. in the first cell. Basically I aim to pack it in two form-cells: 1) Clone, install, setup, configure, 2) Do stuff.

This being the case, the first cell may take several minutes to execute, so, in practice, you may leave it running and return in a few minutes. This approach no longer works if there is Google Drive mounting in the same cell, because that will timeout within a couple of minutes, resulting in cell execution failure. No matter what you do next (even if you use the Drive mount button to skip the Drive mount code), you have to re-execute the first cell with all the installation and preparation stuff due to previous failure.

**Describe the solution you'd like**
Extend Google Drive mounting (authentication) timeout to some 10-15 minutes.

**Describe alternatives you've considered**
Extend Google Drive mounting (authentication) timeout to some 5-10 minutes.

**Additional context**
I think there used to be no timeout in GDrive mounting at all. It's totally understandable that there is one, but it just kicks in too soon imo. Constantly bump to interruptions with "Drive mounting failed" now.

**Comment by peap** [comment]
Can you try setting [`timeout_ms`](https://github.com/googlecolab/colabtools/blob/b11ec1f7146b88bc2fc500cdd5b0d231c18df041/google/colab/drive.py#L98) in your `drive.mount()` call to a value larger than the 2-minute default? Also worth considering the notes in [the FAQ](https://research.google.com/colaboratory/faq.html#drive-timeout) about Drive taking a long time to mount.

**Comment by olaviinha** [comment]
Yeah, `timeout_ms` seems to do the trick, thanks!
