### ISSUE TITLE
Fooocus running very slowly on A100 High Ram. Please fix.

### ISSUE THREAD

**Issue by mlf-crypto** [googlecolab/colabtools#4972]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
We have no dedicated support for fooocus, I'd contact the notebook author about A100 optimizations.
