### ISSUE TITLE
Colab Account Access Blocked due to "suspected abusive activity"

### ISSUE THREAD

**Issue by pmantramurti** [googlecolab/colabtools#4979]
For the last few days, I've been running two different machine learning tasks, for two projects I have due in the next few days. One was a notebook fine tuning a reinforcement learning agent I've been training on the game 2048, and the other was a notebook that loaded and ran a YOLO image detection model from ultralytics. The latter program also loads a dataset of images from the Places2 challenge website, which is about 20gb of images. However, since I was using Colab paid units, and as of today I still have over 100 of them, I was under the impression that this was okay.

Today, about 10 minutes into running the program, I was suddenly cutoff from the runtime and received the following message:

Connection failed
This account has been blocked from accessing Colab runtimes due to suspected abusive activity. This does not impact access to other Google products. If you believe this has been done in error, review the [usage limitations](https://research.google.com/colaboratory/faq.html#limitations-and-restrictions) and [file an appeal](https://colab.research.google.com/drive/10JBT_98rq0BQNpgqIBRQ97ZZ67ncSIio?authuser=1#).

I've submitted an appeal, but haven't received any confirmation of it having been received or acknowledged, and I need to be able to access Colab runtimes for my schoolwork. Is there any way of finding out more about this issue, and how I can get it fixed?

**Comment by head-iie-vnr** [comment]
+1 Same here

**Comment by Mabedallah** [comment]
Same issue here. Just started Yolo and getting :

> Connection failed
> This account has been blocked from accessing Colab runtimes due to suspected abusive activity. This does not impact access to other Google products. If you believe this has been done in error, review the [usage limitations](https://research.google.com/colaboratory/faq.html#limitations-and-restrictions) and [file an appeal](https://colab.research.google.com/drive/1vpZMH2V92eUFWrzckahqJ87MtiGelJMj#).

**Comment by kirkwoodmc** [comment]
Same issue here. YOLO model.tune run...

**Comment by KarthikKatakam2312** [comment]
Same issue here I was running Yolov8 and all of the sudden I had this issue.Just 10 mins before I have subscribed to Google Colab Pro for the utilisation of GPU and this what happened

**Comment by throughthetrees** [comment]
Same issue. Model training. Unacceptable.

**Comment by madisonlong1** [comment]
Same issue here! Basic model training is suspected abusive activity

**Comment by DanielHV** [comment]
Same issue, running YOLO11,  not even five minutes after I started working on it.

**Comment by airin421** [comment]
same issue here

**Comment by mo-advidan** [comment]
Same issue happened here in the middle of doing a run that uses YOLOv8 on 4th December 21:00 UTC

**Comment by coco1718** [comment]
same issue here

**Comment by JahirMendez** [comment]
The same problem

**Comment by HOn5** [comment]
same issue here

**Comment by chynggi** [comment]
Same issue here

**Comment by truong04** [comment]
same here

**Comment by Kagi217** [comment]
same issue here

**Comment by Aman78600** [comment]
same issue here

**Comment by music991758** [comment]
same issue here

**Comment by Ananth-Joshi** [comment]
Same issure here.. can someone help me understand whats happening... because u just got banned from both Kaggle and colab...

**Comment by chynggi** [comment]
> Same issure here.. can someone help me understand whats happening... because u just got banned from both Kaggle and colab...

Me too. i got banned both too

**Comment by Ananth-Joshi** [comment]
> > Same issure here.. can someone help me understand whats happening... because u just got banned from both Kaggle and colab...
> 
> Me too. i got banned both too
i was training a model to detect guns in footage... is the ban due to that or something

**Comment by music991758** [comment]
> Same issure here.. can someone help me understand whats happening... because i just got banned from both Kaggle and colab...

Me too.  I was using a dataset from Roboflow and training a YOLOv11 model for car damage detection.

**Comment by Tw0bit** [comment]
I just started testing the platform and within a few moments got that same message

**Comment by CM9RE** [comment]
저도 방금 yolov8n 모델 학습을 시작하려 하는데 계정이 차단되었다는 메세지를 받았습니다.

**Comment by eggtgg** [comment]
When I work with the .yaml file in the data downloaded from Roboflow, my account is immediately blocked.

**Comment by izyuan** [comment]
Same here, account banned for trying to do a simple prediction model on

**Comment by v4681d** [comment]
same here, I was trying to load the YOLO11 model. (Colab Pro sub)

**Comment by crc1200** [comment]
Same for me! very frustrating. any solution? Trying to just load pretrained yolov8 model.

**Comment by pangniuniu95** [comment]
Same here, I'm also using the YOLOV8 model.

**Comment by Romziii** [comment]
me too! I was training using **yolov8** and a custom dataset from **roboflow**, suddenly the runtime was interrupted at the moment “Overriding model.yaml nc=80 with nc=54”. 
and when I want to reconnect I get a message like this :

> Connection failed This account has been blocked from accessing Colab runtimes due to suspected abusive activity. This does not impact access to other Google products. If you believe this has been done in error, review the [usage limitations](https://research.google.com/colaboratory/faq.html#limitations-and-restrictions) and [file an appeal](https://colab.research.google.com/drive/10JBT_98rq0BQNpgqIBRQ97ZZ67ncSIio?authuser=1#).

even though last night I ran the same notebook without any problems

**Comment by coolhartman** [comment]
Same here, anyone resolved?

**Comment by mo-advidan** [comment]
> Same here, anyone resolved?

No luck yet for me

**Comment by SDPDVADER** [comment]
My Account is also blocked.  What is going on is it a bug it started this afternoon around 5pm.

**Comment by trschnrangga** [comment]
my account just got blocked aswell 10 seconds into training the yolov11 model

**Comment by amleshthakur00** [comment]
for the thesis  I started my  colab project. I uploaded 1800 training image data using YOLO8.
Today when I viewed for the files they were not found and it showed someone else files.

I started my Jyputernotebook instructions from the beginning. In few minutes I got the above error that account is blocked.

**Comment by MelodyYu1006** [comment]
Same here—I’m using a custom dataset for YOLOv11 from Roboflow.

**Comment by SDPDVADER** [comment]
Both of my accounts are blocked trying to run stable diffusion ForgeUI.  It was working fine this morning and up to this afternoon.

**Comment by LockerUp** [comment]
+1 Same here

**Comment by cperry-goog** [comment]
Thanks for all the reports, we've been digging into this, still investigating

**Comment by SDPDVADER** [comment]
Can you let us know if it is a bug or a false positive check or something that is causing this?

**Comment by nd1902** [comment]
it's ridiculous and frustrating, no notice or remedy, my work has been affected because I can't get anything done all day, it's ridiculous

**Comment by findinggeels** [comment]
HELPPP ME TOOOO. I GOT BANNED. I'M IN A RUSSS HELP

**Comment by nd1902** [comment]
What the hell are the developers doing???

**Comment by Ananth-Joshi** [comment]
![image](https://github.com/user-attachments/assets/63ec13ea-a6a3-47e2-b60f-a33967786b29)
Second account also banned🥲

**Comment by Ananth-Joshi** [comment]
> Thanks for all the reports, we've been digging into this, still investigating


hey can you tell me if it is because of words like "gun" in the dataset... had my 2 accounts blocked

**Comment by Amit-IITM** [comment]
Same issue here. I was aslo working on YOLO 10n model and got banned.

**Comment by praths71018** [comment]
I was working with YOLOv8 in ultralytics and got banned , it was working fine for 3 months

**Comment by Aizad-Khan** [comment]
Exactly the same issue here. Also just when it finally ran error free.

YOLO isnt YOLOing

**Comment by cperry-goog** [comment]
We hit an issue where our abuse detection was picking up false positives. We've unbanned all affected accounts and updated our abuse rules which should address this - new runtimes will be fixed; you may need to delete an existing runtime if you still see this. Sorry.

Let me know if you still see issues getting banned on new runtimes.

**Comment by madisonlong1** [comment]
It is fixed for me!

**Comment by Ananth-Joshi** [comment]
its fixed

**Comment by Ananth-Joshi** [comment]
hey whats up with kaggle though... does anybdody have any info.. ive heard kaggle uses google cloud in the backend.. im still banned there... is this related?

**Comment by pangniuniu95** [comment]
It happens again...

**Comment by cperry-goog** [comment]
@pangniuniu95 is this on a new runtime?

**Comment by pangniuniu95** [comment]
> We hit an issue where our abuse detection was picking up false positives. We've unbanned all affected accounts and updated our abuse rules which should address this - new runtimes will be fixed; you may need to delete an existing runtime if you still see this. Sorry.
> 
> Let me know if you still see issues getting banned on new runtimes.

It happened again... I connected successfully and started running and happed again.

**Comment by pangniuniu95** [comment]
> @pangniuniu95 is this on a new runtime?

Yes. I connected successfully when I received the fixed message.

**Comment by Ananth-Joshi** [comment]
@cperry-goog please check on kaggle...

**Comment by truong04** [comment]
i still having the issue in kaggle

**Comment by LockerUp** [comment]
The bug appeared again in a new environment

**Comment by Aizad-Khan** [comment]
It was fixed and now its back

**Comment by Ananth-Joshi** [comment]
now its back... and kaggle was never fixed

**Comment by Aizad-Khan** [comment]
Yep it's officially back after 10 minutes of being fixed

**Comment by Romziii** [comment]
after running 19 minutes, and back again

**Comment by v4681d** [comment]
fixed and blocked again.

**Comment by Manjitj** [comment]
Connection failed
This account has been blocked from accessing Colab runtimes due to suspected abusive activity. This does not impact access to other Google products. If you believe this has been done in error, review the [usage limitations]. how to fix it kindly suggest

**Comment by HARSHEREX-ACX** [comment]
same issue
![Screenshot 2024-12-05 121108](https://github.com/user-attachments/assets/270ef8f2-2612-486d-a19a-1ad122a49881)
i have deadlines. please fix this ASAP.

**Comment by Vineet061** [comment]
![colab_issue](https://github.com/user-attachments/assets/48507261-3956-49c6-9846-52f3a4a72f28)

Me too getting same error while running trained YOLO (v8) model.

**Comment by truong04** [comment]
oh my god, it happened again, especially with yolov8

**Comment by AJ-JAISWAL** [comment]
![image](https://github.com/user-attachments/assets/9b23bd8d-604c-4831-b465-0a5a113eed1d)
same again using YOLOv8

**Comment by sunny-pidata** [comment]
The same issue occurred again.
Please resolve this quickly

**Comment by sreepr123** [comment]
![issue](https://github.com/user-attachments/assets/01be3e9c-fd40-4ca4-89ed-204f84e4c305)
Getting the same error while training yolov8 model , please fix it as soon as possible

**Comment by SDPDVADER** [comment]
Like Brittany Spears, it did it again.

**Comment by findinggeels** [comment]
OMGGG WHAT HAPPENNNN

**Comment by Ananth-Joshi** [comment]
kaggle came back then died again

**Comment by nd1902** [comment]
1 account running for 15 minutes
1 account still running for 30 minutes without interruption
It's difficult

**Comment by martvelge** [comment]
Same issue

**Comment by JongSinister** [comment]
same here

**Comment by williamsaung** [comment]
Same, i'm training a yolo model. How long will it take to unbanned?

**Comment by kglmcodes** [comment]
Same! i'm training a yolo model for a friend. How long will it take to unbanned?

**Comment by SDPDVADER** [comment]
So it appears that anything with Yolo will cause the block.  I use
Adetailer which use Yolo and in doing so it blocked me

**Comment by kiminya-raphael** [comment]
+1

**Comment by pmantramurti** [comment]
Mine has been blocked again, I really needed this to work, so I have to say I'm rather disappointed to be having to go through this again.

**Comment by hex37672910** [comment]
I'm using yolov11 and I've been blocked 4 times within the past few hours.

**Comment by Skillnoob** [comment]
Please uninstall Ultralytics `v8.3.41`, the package on PyPi is compromised, we are working on resolving the issue. `v8.3.40` is safe to use.
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/843

To uninstall ultralytics:
```
pip uninstall ultralytics
```
You can safely install Ultralytics through the following commands:
```
pip install git+https://github.com/ultralytics/ultralytics.git
```
or:
```
pip install ultralytics==8.3.40
```
Just fyi, I'm from Ultralytics, we just recently found out about this issue.

**Comment by williamsaung** [comment]
thank you but my colab account is still banned.

> Please uninstall Ultralytics `v8.3.41`, the package on PyPi is compromised, we are working on resolving the issue. `v8.3.40` is safe to use. [ltdrdata/ComfyUI-Impact-Pack#843](https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/843)
> 
> To uninstall ultralytics:
> 
> ```
> pip uninstall ultralytics
> ```
> 
> You can safely install Ultralytics through the following commands:
> 
> ```
> pip install git+https://github.com/ultralytics/ultralytics.git
> ```
> 
> or:
> 
> ```
> pip install ultralytics==8.3.40
> ```
> 
> Just fyi, I'm from Ultralytics, we just recently found out about this issue.

**Comment by chiflmas** [comment]
> thank you but my colab account is still banned.
> 
> > Please uninstall Ultralytics `v8.3.41`, the package on PyPi is compromised, we are working on resolving the issue. `v8.3.40` is safe to use. [ltdrdata/ComfyUI-Impact-Pack#843](https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/843)
> > To uninstall ultralytics:
> > ```
> > pip uninstall ultralytics
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can safely install Ultralytics through the following commands:
> > ```
> > pip install git+https://github.com/ultralytics/ultralytics.git
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or:
> > ```
> > pip install ultralytics==8.3.40
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Just fyi, I'm from Ultralytics, we just recently found out about this issue.

Same here, my account is still banned...

**Comment by praths71018** [comment]
again banned after an hour

**Comment by Skillnoob** [comment]
@praths71018 Please see my comment here: https://github.com/googlecolab/colabtools/issues/4979#issuecomment-2519668219

**Comment by williamsaung** [comment]
> @williamsaung I am not from google colab, I sadly can't do anything about your account being banned.

anyways , it works after i tested again with my alt account. Thanks

**Comment by GiperKot007** [comment]
How to get an account unblocked due to this annoying error? Or is the account blocked forever?

**Comment by mo-advidan** [comment]
I'm able to run notebooks on Colab Pro+ again. Thanks @Skillnoob for the updates and transparency on the situation.

**Comment by AErdemmm** [comment]
How to get an account unblocked due to this annoying error? Or is the account blocked forever?

**Comment by Vineet061** [comment]
@cperry-goog How to unblock the account which got banned cause of this error?

**Comment by mo-advidan** [comment]
> > I'm able to run notebooks on Colab Pro+ again. Thanks @Skillnoob for the updates and transparency on the situation.
> 
> why my account is not unblocked then?

I submitted an appeal yesterday at 20:00 UTC. Did you submit an appeal and when?

I also didn't try to run anymore notebooks on Colab since 00:00 UTC, so it's been 9 hours without activity on Colab for me.

**Comment by sreepr123** [comment]
How can I get my account unblocked? I recently purchased computing units and would like to regain access to use them.

**Comment by HARSHEREX-ACX** [comment]
> > > I'm able to run notebooks on Colab Pro+ again. Thanks @Skillnoob for the updates and transparency on the situation.
> > 
> > 
> > why my account is not unblocked then?
> 
> I submitted an appeal yesterday at 20:00 UTC. Did you submit an appeal and when?
> 
> I also didn't try to run anymore notebooks on Colab since 00:00 UTC, so it's been 9 hours without activity on Colab for me.

yes i did file an appeal. its been 4 hours

**Comment by Fikri645** [comment]
Same issue. I was running tuner.fit() and model.train() for YOLO11 model at the same time.

**Comment by Fikri645** [comment]
My account is still blocked

**Comment by SDPDVADER** [comment]
Just got to have patience it will be resolved, unfortunately someone put malicious code into something for some mining.

**Comment by Skol600ml** [comment]
Thanks to Ultralytics, you all just tried to run a crypto mining through Colab, it's not like you be magically unbanned

**Comment by Skillnoob** [comment]
The current package on PyPi is safe, more informatio can be found here:
https://github.com/ultralytics/ultralytics/issues/18027#issuecomment-2520462686

**Comment by RalFingerLP** [comment]
> The compromised Ultralytics package version has been removed from PyPi, it should be safe to install Ultralytics again.

Do we also get a public response what the f happend? Still, great problemsolving!

**Comment by pmantramurti** [comment]
Considering I've been banned twice now, you're absolutely sure that the current package is safe, right?

**Comment by Y-T-G** [comment]
If you want to be extra sure, you can install ultralytics from git instead:

```bash
!pip install git+https://github.com/ultralytics/ultralytics
```

**Comment by RalFingerLP** [comment]
IMPORTANT: Delete any ultralytics==8.3.41 and ultrlaytics==8.3.42 versions that may be installed locally as these are both affected. ultralytics<=8.3.40 is safe.

Source: https://github.com/ultralytics/ultralytics/issues/18027#issuecomment-2520462686

**Comment by cperry-goog** [comment]
Yesterday ultralytics released 8.3.41, which contained malicious code that could be used for cryptocurrency mining. Automated Colab abuse detection picked this up and began banning unsuspecting ultralytics users who installed 8.3.41 and started training with that version.

We noticed this uptick in bans, but we had made no recent changes to our configs, so were unable to immediately diagnose the issue. Late in the day our Backend TL hopped on while on vacation and root-caused the issue and reported it upstream: https://github.com/ultralytics/ultralytics/issues/18027 - ultralytics subsequently removed 8.3.41 (and briefly, 8.3.42) from PyPI.

We have unbanned all users impacted yesterday, and this issue should be resolved. A big thank you to all users who reported this. We'll have an internal post-mortem to see if we can better avoid these types of attacks in the future.

**Comment by cperry-goog** [comment]
I'll keep this issue open for another day or two just in case we see a repeat, please do comment if you see issues.

**Comment by airin421** [comment]
my account is still being blocked, please assists

**Comment by HenrikPetersen** [comment]
Im still not able to connect to a Colab runtime. I filed two appeals yesterday. Is there anything else I can do to get my account unblocked?

**Comment by colaboratory-team** [comment]
We unblocked more users on the 9th that we believe were hit by this issue. If you are still blocked from this event, please file in-product feedback at Help -> Send Feedback and we will get you unblocked

**Comment by jose-solorzano** [comment]
@cperry-goog I need to be unblocked too. I was running a standard Pytorch pipeline, but apparently the system didn't like something in the cached arrow files of a large Huggingface dataset. Kaggle is troubleshooting this as well.

**Comment by gigacoursesdrive** [comment]
My access to google colab also got blocked for the same reason. Could i get my issue get unblocked?

**Comment by gigacoursesdrive** [comment]
@cperry-goog  Could you please check my account. I have been using it without any problems.

**Comment by kevinkaiwang** [comment]
yesterday my colab account was blocked, Warning of abuse。 how could i unblock it？

**Comment by abhijit869** [comment]
Please Unblock my Colab account, my account show This account has been blocked from accessing Colab runtimes due to suspected abusive activity.  Why!

**Comment by thefirst632student** [comment]
Same issue here
