### ISSUE TITLE
Same issure here... i just got banned from both Kaggle and colab..

### ISSUE THREAD

**Issue by shashankgowda7892** [googlecolab/colabtools#4980]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
We hit an issue where our abuse detection was picking up false positives. We've unbanned all affected accounts and updated our abuse rules which should address this. Sorry.
