### ISSUE TITLE
Colab access blocked!

### ISSUE THREAD

**Issue by tushark01** [googlecolab/colabtools#4984]
Dont know why i got blocked ,... i was just training a yolo 11 model

**Comment by jonghoIm** [comment]
me too.. 
What actions can I take to resolve this issue? I need to test with the YOLO11 model for my work, and my deadline is tomorrow. I subscribed to Pro+ because I wanted to use Colab properly and efficiently. Please lift the ban as soon as possible. I sincerely ask for your help.

**Comment by cperry-goog** [comment]
Yesterday ultralytics released 8.3.41, which contained malicious code that could be used for cryptocurrency mining. Automated Colab abuse detection picked this up and began banning unsuspecting ultralytics users who installed 8.3.41 and started training with that version.

We noticed this uptick in bans, but we had made no recent changes to our configs, so were unable to immediately diagnose the issue. Late in the day our Backend TL hopped on while on vacation and root-caused the issue and reported it upstream: https://github.com/ultralytics/ultralytics/issues/18027 - ultralytics subsequently removed 8.3.41 (and briefly, 8.3.42) from PyPI.

We have unbanned all users impacted yesterday, and this issue should be resolved. A big thank you to all users who reported this. We'll have an internal post-mortem to see if we can better avoid these types of attacks in the future.

**Comment by glenn-jocher** [comment]
Thank you @tushark01 @jonghoIm @cperry-goog for bringing this to our attention. We confirm that Ultralytics versions 8.3.41 and 8.3.42 were compromised by a malicious code injection targeting cryptocurrency mining. Both versions have been immediately removed from PyPI.

We have released 8.3.43 which addresses this security issue. Our team is conducting a full security audit and implementing additional safeguards to prevent similar incidents.

We apologize to all affected users and appreciate Google Colab's swift detection of this security breach. We are committed to ensuring the safety and integrity of our package.
