### ISSUE TITLE
This account has been blocked from accessing Colab runtimes due to suspected abusive activity

### ISSUE THREAD

**Issue by HARSHEREX-ACX** [googlecolab/colabtools#4987]
![Screenshot 2024-12-05 121108](https://github.com/user-attachments/assets/a9a7aaab-1a25-4c9a-917a-31f9a2aed907)

why? i was just training yolo v8. need immidiate resolution.

**Comment by lalekosucu** [comment]
Same here, I was just training yolov8 and I got the same notification?

**Comment by r00sh1** [comment]
same issue while training YOLOv8 Model

**Comment by r00sh1** [comment]
how to appeal on it? to get unblock?

**Comment by Druidot** [comment]
Got message trying to run yolov5 model.   How to get unblocked?

**Comment by ahmednoorx** [comment]
same problem just happened to me as well, how to  get unblocked plz any immediate solution

**Comment by GenWise** [comment]
Same issue. When will @colaboratory-team  1) respond, and 2) fix the issue? Thank you.

**Comment by NoodlesStamps** [comment]
It appears that PypI's ultralytics package has been compromised.
[https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/843](url)

**Comment by glenn-jocher** [comment]
Thank you @HARSHEREX-ACX @GenWise @NoodlesStamps @r00sh1 @Druidot @cperry-goog for bringing this to our attention. We confirm that Ultralytics versions 8.3.41 and 8.3.42 were compromised by a malicious code injection targeting cryptocurrency mining. Both versions have been immediately removed from PyPI.

We have released 8.3.43 which addresses this security issue. Our team is conducting a full security audit and implementing additional safeguards to prevent similar incidents.

We apologize to all affected users and appreciate Google Colab's swift detection of this security breach. We are committed to ensuring the safety and integrity of our package.

**Comment by r00sh1** [comment]
> Thank you @HARSHEREX-ACX @GenWise @NoodlesStamps @r00sh1 @Druidot @cperry-goog for bringing this to our attention. We confirm that Ultralytics versions 8.3.41 and 8.3.42 were compromised by a malicious code injection targeting cryptocurrency mining. Both versions have been immediately removed from PyPI.
> 
> We have released 8.3.43 which addresses this security issue. Our team is conducting a full security audit and implementing additional safeguards to prevent similar incidents.
> 
> We apologize to all affected users and appreciate Google Colab's swift detection of this security breach. We are committed to ensuring the safety and integrity of our package.

Thanks for fast Response!
