### ISSUE TITLE
Failed to assign a backend (in a specific gdrive - others fine)

### ISSUE THREAD

**Issue by joefriel** [googlecolab/colabtools#499]
From a specific google account, I am suddenly consistently unable to assign a GPU backend. This happens on any existing colab notebook or when I create a new colab notebook from the gdrive.  This account has worked fine for some time.  I know that GPUs are not always available, but if I try from another google account (different gdrive), I can easily create a new colab notebook with a GPU - it never fails.  The failing google account seems somehow "stuck" in a bad mode.  Any suggestions?

**Comment by joefriel** [comment]
I waited (19 hours) and tried again and it now works fine.  I assume there was a VM associated with that gdrive account that was in a bad state and unable to be cleared by "reset all runtimes?"

**Comment by joefriel** [comment]
This happened again today to my research partner. He can not get a GPU backend in his primary gmail account, but if he uses another gmail account it works fine.  There is nothing suspicious-looking in the JS console, just a 503 error.  "Reset all runtimes" does not clear this issue.

**Comment by reiinakano** [comment]
I noticed the same thing. Are you running long running jobs? I think they just throttle resource usage. Colab is not meant to be.a long running research environment so it's up to them how they want to throttle it. If you're going to use it for that purpose anyway make sure to periodically back checkpoints up somewhere

**Comment by joefriel** [comment]
We do save checkpoints and there have been times the jobs are cut off after 12 hours (which is as-advertised and as we expect), but this doesn't seem to be connected to that.  It happens randomly while working on the code and experimenting.

**Comment by metrizable** [comment]
Thanks for the reports, we'll look into it but it's difficult to diagnose from Github. Please file in-product feedback at Help -> Send Feedback and include a link to this issue
