### ISSUE TITLE
When will the Colab issue be fixed?

### ISSUE THREAD

**Issue by mrortach** [googlecolab/colabtools#4990]
I was working on Colab and I need to do some testing. I have some work to do but I'm having this problem.

Connection failed
This account has been blocked from accessing Colab runtimes due to suspected abusive activity. This does not impact access to other Google products. If you believe this has been done in error, review the [usage limitations](https://research.google.com/colaboratory/faq.html#limitations-and-restrictions) and [file an appeal](https://colab.research.google.com/drive/1gabDpi8Y2anqgkjiCW9iyyHxa_6VCQam#).

![image](https://github.com/user-attachments/assets/0f50d351-e4a0-4b2b-8b4c-0dc4a47c0b50)

**Comment by GoldenVadim** [comment]
bro its not a bug. file an appeal

**Comment by cperry-goog** [comment]
Yesterday ultralytics released 8.3.41, which contained malicious code that could be used for cryptocurrency mining. Automated Colab abuse detection picked this up and began banning unsuspecting ultralytics users who installed 8.3.41 and started training with that version.

We noticed this uptick in bans, but we had made no recent changes to our configs, so were unable to immediately diagnose the issue. Late in the day our Backend TL hopped on while on vacation and root-caused the issue and reported it upstream: https://github.com/ultralytics/ultralytics/issues/18027 - ultralytics subsequently removed 8.3.41 (and briefly, 8.3.42) from PyPI.

We have unbanned all users impacted yesterday, and this issue should be resolved. A big thank you to all users who reported this. We'll have an internal post-mortem to see if we can better avoid these types of attacks in the future.

**Comment by glenn-jocher** [comment]
Thank you @cperry-goog for bringing this to our attention. We confirm that Ultralytics versions 8.3.41 and 8.3.42 were compromised by a malicious code injection targeting cryptocurrency mining. Both versions have been immediately removed from PyPI.

We have released 8.3.43 which addresses this security issue. Our team is conducting a full security audit and implementing additional safeguards to prevent similar incidents.

We apologize to all affected users and appreciate Google Colab's swift detection of this security breach. We are committed to ensuring the safety and integrity of our package.
