### ISSUE TITLE
No Deoldify folder on completion

### ISSUE THREAD

**Issue by kennt66** [googlecolab/colabtools#4993]
Hi
Ive been trying all week but this about the fourth time now that on completion the Deoldiify folder with the video result folder doesnt appear.
ive tried refrreshing and using the shortcut link but nothing seems to work.Very frustrating with this now<!--

im using safari/tried chrome

https://colab.research.google.com/github/jantic/DeOldify/blob/master/VideoColorizerColab.ipynb

**Comment by colaboratory-team** [comment]
This doesn't seem like an issue with Colab itself, I would reach out to the notebook author through Github instead
