### ISSUE TITLE
from ultralytics import YOLO

### ISSUE THREAD

**Issue by alejoherrera** [googlecolab/colabtools#4994]
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-a9db4b00351d>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from ultralytics import YOLO
      2 
      3 # 1. Cargar el modelo (nano, el más pequeño)
      4 model = YOLO("/content/drive/MyDrive/proyecto_promidat/vagoneta/dIAra_vagoneta/entrenamiento_yolo_vagoneta_2/weights/best.pt")
      5 

[/usr/local/lib/python3.10/dist-packages/ultralytics/__init__.py](https://localhost:8080/#) in <module>
      4 
      5 import os
----> 6 import package
      7 
      8 # Set ENV variables (place before imports)

ModuleNotFoundError: No module named 'package'

**Comment by alejoherrera** [comment]
!pip install package

![image](https://github.com/user-attachments/assets/bca54ff3-e4ad-4bbf-8a12-1013d2771ff5)

**Comment by baypogiMD** [comment]
Collecting package
  Downloading package-0.1.1.tar.gz (13 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Y-T-G** [comment]
The versions.8.3.45 and 8.3.46 are compromised. Use .8.3.44.

**Comment by colaboratory-team** [comment]
See https://github.com/googlecolab/colabtools/issues/4979 - this should be resolved now
