### ISSUE TITLE
from ultralytics import YOLO

### ISSUE THREAD

**Issue by baypogiMD** [googlecolab/colabtools#4996]
**Describe the current behavior**
Unable to import Yolo after installation of ultralytics

**Describe the expected behavior**
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-5-0bf2fd45f7d1>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from ultralytics import YOLO

[/usr/local/lib/python3.10/dist-packages/ultralytics/__init__.py](https://localhost:8080/#) in <module>
      4 
      5 import os
----> 6 import package
      7 
      8 # Set ENV variables (place before imports)

ModuleNotFoundError: No module named 'package'

**What web browser you are using**
Brave

**Comment by colaboratory-team** [comment]
See https://github.com/googlecolab/colabtools/issues/4979 - this should be resolved now
