### ISSUE TITLE
pymongo not working

### ISSUE THREAD

**Issue by marcost21** [googlecolab/colabtools#50]
I am trying to connect to a MongoDB, but am receiving this error:
ConfigurationError: Server at c604.candidate.12.mongolayer.com:10604 reports wire version 0, but this version of PyMongo requires at least 2 (MongoDB 2.6).

I believe it is some server configuration because the same script works fine in Jupiter Notebook within my computer.

**Comment by craigcitro** [comment]
I'm guessing you've got different versions of the pymongo package installed locally vs. in Colab. Can you use `pip list` to compare the versions?

**Comment by marcost21** [comment]
The version I'm using is pymongo (3.5.1).

-------

Marcos Masanobu Takahashi

2018-02-12 21:11 GMT-02:00 Craig Citro <notifications@github.com>:

**Comment by craigcitro** [comment]
I don't know anything about pymongo -- I'm just guessing from the error message about wire version mismatches that there are multiple versions in play here.

Is there a "hello world" for pymongo you can use to confirm whether or not it's working from Colab?
