### ISSUE TITLE
Colab is repeatedly crashing for any model 

### ISSUE THREAD

**Issue by pankysdomain** [googlecolab/colabtools#500]
Bug report for Colab: http://colab.research.google.com/.

Colab log shows

WARNING:root:kernel 1fe0be22-c98a-4519-a16a-69c9fb4be1da restarted
KernelRestarter: restarting kernel (1/5), keep random ports 
tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10754 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)

Here is my colab link
https://colab.research.google.com/drive/1QG1mg1zOn6gZaaSv4rrI4F6erdxsxQ8V

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
My Google colab crashes immediately as soon as it starts training on tiny-imagenet with 0.1 million images and 200 classes of size 64*64

I am using model.fit_generator with batch size (tried from 32 till 1024) and size of image ( tried from 16 till 64) but nothing works.

I tried resnet-18 architecture with (1.8*10^9 params) as well as custom model too with 0.8 million params but in vain.

- Describe the expected behavior:
Google colab  shouldn't crash
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link to self-contained notebook that reproduces this issue
  https://colab.research.google.com/drive/1QG1mg1zOn6gZaaSv4rrI4F6erdxsxQ8V

**Comment by DerekGloudemans** [comment]
Did you ever make progress on this issue? I'm running into a similar issue using Pytorch models in google colab

**Comment by MojammelHossain** [comment]
@DerekGloudemans thanks, buddy you saved me. I faced the same issue and after spent several hours to debug it I find out that I didn't transfer my hidden states tensor in GPU. It should raise an exception or give an error message which may save lots of time.

**Comment by kivilcimco** [comment]
Hi I am having the similar issue using a python script that has VTK module.
Could you show me a snippet of code on how I need to transer it to GPU?

**Comment by MojammelHossain** [comment]
I am not sure for which reason you are getting this error as it does not explicitly show the reason. For me, it was the hidden state of my encoder, as by mistake I forget to move it in GPU after initializing. In PyTorch, you can easily move tensor in GPU by tensor. to("cuda").

Cuda Docs
PyTorch -> [https://pytorch.org/docs/stable/notes/cuda.html]
TensorFlow -> [https://www.tensorflow.org/guide/gpu]

**Comment by kivilcimco** [comment]
thank you  MojammelHossain. I will look if I can find the solution.
