### ISSUE TITLE
All code submitted is taking too long. Just upgraded to paid version and still stalling. 

### ISSUE THREAD

**Issue by anchormuse** [googlecolab/colabtools#5004]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by colaboratory-team** [comment]
We won't be able to diagnose this from Github, can you file in-product feedback at Help -> Send feedback instead?
