### ISSUE TITLE
Multiple terminals in Colab?

### ISSUE THREAD

**Issue by b8zhong** [googlecolab/colabtools#5010]
# Feature Request: Multiple Terminal Support

## **Is your feature request related to a problem? Please describe.**

When users need to manage processes on Google Colab but cannot do so efficiently - since they can't use multiple terminal instances.

## **Describe the solution you'd like**

Support multiple terminal instances within the same runtime environment. Each terminal would operate independently, allowing users to:
- Run multiple commands or processes simultaneously.
- Monitor log outputs in one terminal while interacting with another.

## **Describe alternatives you've considered**

1. **Opening multiple browser tabs to monitor a single terminal instance**  
   - Gets difficult to manage, not independent instances either.

## **Additional context**

- Would just be really happy to see this brought in one day!

**Comment by katlyn-edwards** [comment]
Hey! We use "tmux" on our terminal to allow for multiple tabs/windows. The default keybinding is Ctrl+B then C to create a new window.

Check out https://github.com/tmux/tmux/wiki to learn more!

**Comment by b8zhong** [comment]
Oh - thank you so much! Honestly had no idea that was a thing lol
