### ISSUE TITLE
Feature request: Automatically connect to a GCP instance

### ISSUE THREAD

**Issue by reiinakano** [googlecolab/colabtools#502]
I really like how easy it is to set up Colab (open a link), but the free GPU is kinda slow. Will you be working on a feature to directly set up a connection to a GCP instance so I can use a proper GPU with all the ease of Colab? Obviously I will pay for time used.

**Comment by ak9250** [comment]
this would be great, also kaggle now has p100 instances by default is colab looking to upgrade the k80 in the future?

**Comment by metrizable** [comment]
@reiinakano We offer both free-tier (T4) and premium-tier (A100, V100) accelerators. You can update your notebook settings by going to the "Runtime" menu, selecting "Change runtime type" and selecting the appropriate "Hardware accelerator".
