### ISSUE TITLE
No Deoldify folder on completion

### ISSUE THREAD

**Issue by kennt66** [googlecolab/colabtools#5020]
Ive been using this nearly 2 years but recently on completion the De-oldify folder with finish vdeo doesnt appear.Can anyone suggest anything to resolve this.Im using safari.If you try going to the click video result here it just says cannot fetch from backend

**Comment by kennt66** [comment]
Anyone here?

**Comment by katlyn-edwards** [comment]
This doesn't sound like a Colab specific problem. If it's with a specific notebook, contact the notebook author.
