### ISSUE TITLE
Showing "Prediction failed" since today

### ISSUE THREAD

**Issue by msandy1013** [googlecolab/colabtools#5022]
**Describe the current behavior**
Since today when I logged in to compute CatPred colab notebook, it throws that "Prediction failed". Earlier it was working without any issue.

**Describe the expected behavior**
It should compute and give the value after the completion of the cell run.

**What web browser you are using**
Chrome

**Comment by katlyn-edwards** [comment]
It's possible that maybe an underlying dependency changed and the notebook needs to be updated. I would contact the notebook author instead.
