### ISSUE TITLE
tf version error 

### ISSUE THREAD

**Issue by huatangzhi** [googlecolab/colabtools#503]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:  I have installed tensorflow==2.0.0-alpha0 
!pip install -q tensorflow==2.0.0-alpha0
import tensorflow as tf
- Describe the expected behavior:
when I run print(__tf.version__)
it shows 1.13.1
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue

**Comment by huatangzhi** [comment]
I use !pip list it shows :
tensor2tensor            1.11.0               
tensorboard              1.13.1               
tensorboardcolab         0.0.22               
tensorflow               2.0.0a0              
tensorflow-estimator     1.13.0               
tensorflow-hub           0.3.0

**Comment by craigcitro** [comment]
You need to restart your runtime (Runtime -> Restart runtime) after installing if you've already imported TF.

(Confirmed this works in a fresh runtime.)
