### ISSUE TITLE
New versions of Chainer and CuPy have been released

### ISSUE THREAD

**Issue by mitmul** [googlecolab/colabtools#504]
Hi, I'm a maintainer of Chainer and CuPy projects.
Thank you very much for making Chainer and CuPy available on Colab by default.
Yesterday, we released new versions v5.4.0 of Chainer and CuPy.
Those are the last stable release of v5 (the next release will be the first stable version of v6).
But the current versions of Chainer and CuPy on Colab are v5.0.0 and v5.2.0, so could you upgrade the versions of both packages to v5.4.0? Then users can immediately start working with the latest Chainer and CuPy on Colab! and actually, it's better to use the same version numbers of Chainer and CuPy because we are not testing the combinations of different version numbers of Chainer and CuPy.

Thanks.

**Comment by craigcitro** [comment]
Thanks for the note -- we'll try and take a look soon.

b/130026040

**Comment by mitmul** [comment]
@craigcitro Hi, is there any problem to upgrade them on Colab? I'm more than happy to help.

**Comment by craigcitro** [comment]
@mitmul New versions should be rolling out in the next few days. (Should be Wednesday afternoon, barring any other issues.)

**Comment by craigcitro** [comment]
Chainer and CuPy should both be at 5.4.0. Thanks for the report!
