### ISSUE TITLE
Keyboard shortcuts stop working in a cell after autocompleting within it.

### ISSUE THREAD

**Issue by zetaqubit** [googlecolab/colabtools#506]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Autocomplete in a code cell using TAB. Afterwards, keyboard shortcuts (e.g. CTLR+Enter) no longer work in that cell, but they work in other cells. Refreshing the notebook fixes the problem until the next autocomplete.

- Describe the expected behavior:
Keyboard shortcuts keep working.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome, Linux

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1MZ18q_smgiLpYIFtTsNjExKeY4c53xm1

**Comment by blois** [comment]
This has been fixed.
