### ISSUE TITLE
'Restart Runtime' causes the VM instance to crash.

### ISSUE THREAD

**Issue by 2ndMessiah** [googlecolab/colabtools#507]
I was intended to restart the runtime to reload several newly installed packages, but the vm instance crashes and I couldnt reconnect again. All I could do is to request to assign a new VM.

This seems to happen merely after installing certain packages after I tried installing several libraries.
Here's the code:

`!pip install -U https://github.com/nilmtk/nilmtk/archive/master.zip#egg=nilmtk`
`!pip install -U https://github.com/nilmtk/nilm_metadata/archive/master.zip#egg=nilm_metadata`
`!apt-get -qq install -y graphviz && pip install -q pydot`
`from google.colab import drive`
`import nilmtk as nt`
`import numpy as np`
`import pylab as pl`
`import pandas  as pd`
`import requests `
`import time`
`drive.mount('/gdrive')`
`!pip install autokeras`

The notebook is [here](https://colab.research.google.com/drive/1hMS7eNDvc-jlAZCOvMn_YlIduShpNXfJ). With python3 and GPU.

Since it's impossible to restart the IDE properly, the dependency version conficts have prevented me from carrying on my work. So 'restarting runtime' functionality itself is worth noting.

ps I dont think it's related to my web browser tho, I put down my environment here:
windows 10 ltsc 2019 march update
firefox66.0.3

Thank you.

**Comment by blois** [comment]
Does this issue persist if you do not do the `drive.mount()` step?

**Comment by blois** [comment]
Ok, I can repro with https://colab.research.google.com/gist/blois/efb7dd16836ba49de7c190a20daf3c1f/issue-507.ipynb

When it crashes there's additional data in the logs which are accessible from the toast message which appears in the bottom-left corner after it fails to connect.

**Comment by blois** [comment]
You'll want to upgrade ipython and ipykernel as well:
```
!pip install -q --upgrade ipython
!pip install -q --upgrade ipykernel
```

**Comment by 2ndMessiah** [comment]
@blois Working fine now. Thanks for your instant reply.
