### ISSUE TITLE
Tensorflow Keras Dense layer object initialization error

### ISSUE THREAD

**Issue by subc69** [googlecolab/colabtools#508]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Defined a dense layer as below in one colab cell:
import tensorflow as tf
layer = tf.keras.layers.Dense(10)

In the subsequent cell, when running the following code for first time, an error named FailedPreconditionError occurs for line 4 below. However, no error is reported when the same cell is run subsequently.
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  print(sess.run(layer.variables))
  print(sess.run([layer(tf.zeros([15, 5])), layer.variables]))

- Describe the expected behavior:
The error/output should be consistent as nothing was changed after first run.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by metrizable** [comment]
Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem including TensorFlow and Keras since then, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
