### ISSUE TITLE
The connection to the runtime has timed out

### ISSUE THREAD

**Issue by ghosh-inspire** [googlecolab/colabtools#509]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
The session times out in about 50 mins. This is hapenning everytime, even if I am using the notebook for reviewing the code.
- Describe the expected behavior:
The session should run for 12 Hrs.
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
![Capture](https://user-images.githubusercontent.com/42549255/56085841-b8099900-5e42-11e9-82f3-a82c6bf52c53.JPG)

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by Dylan-H-Wang** [comment]
Same issue here. But this is a possible solution: when I met this issue, I didn't click any button and tried to search for solutions. After couple of minutes, it continues, Maybe you can leave this message there and wait for some time.
