### ISSUE TITLE
Loading MRPC in bert_finetuning_with_cloud_tpus.ipynb fails due to Firebase hosting going over limit

### ISSUE THREAD

**Issue by sedelnik** [googlecolab/colabtools#514]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

Following line fails, since the data was NOT downloaded from Firebase
train_examples = processor.get_train_examples(TASK_DATA_DIR) 

- Describe the expected behavior:

I would expect this code to run smoothly, but this requires
"train.tsv" to be downloaded from somewhere

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/github/tensorflow/tpu/blob/master/tools/colab/bert_finetuning_with_cloud_tpus.ipynb

**Comment by colaboratory-team** [comment]
As this isn't a Colab-specific issue, I'd recommend filing an issue in the [BERT repo](https://github.com/google-research/bert/issues) directly.
