### ISSUE TITLE
AuthorizationError: Error fetching credentials

### ISSUE THREAD

**Issue by skysunsun** [googlecolab/colabtools#518]
E: Package 'python-software-properties' has no installation candidate
Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/auth?redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&prompt=select_account&response_type=code&client_id=32555940559.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&access_type=offline

Enter verification code: ··········
---------------------------------------------------------------------------
AuthorizationError                        Traceback (most recent call last)
<ipython-input-10-75a4d519ca25> in <module>()
      4 get_ipython().system('apt-get -y install -qq google-drive-ocamlfuse fuse')
      5 from google.colab import auth
----> 6 auth.authenticate_user()
      7 from oauth2client.client import GoogleCredentials
      8 creds = GoogleCredentials.get_application_default()

1 frames
/usr/local/lib/python3.6/dist-packages/google/colab/auth.py in _gcloud_login()
     95     _os.remove(name)
     96   if gcloud_process.returncode:
---> 97     raise _errors.AuthorizationError('Error fetching credentials')
     98 
     99 

AuthorizationError: Error fetching credentials

**Comment by ntakouris** [comment]
Try copying the link manually, instead of using the icon.
