### ISSUE TITLE
Is a single GPU shared among several users?

### ISSUE THREAD

**Issue by Rhuax** [googlecolab/colabtools#52]
I almost always get assigned a GPU which has the 95% of the RAM already full, and I cannot run my scripts. I wanted to know if this is related to the sharing of a single GPU between several users or it is a bug/my fault.

**Comment by CSEMike** [comment]
By default, TensorFlow will consume all memory on a GPU, inhibiting sharing. There's a config option to prevent this. See:
https://www.tensorflow.org/tutorials/using_gpu#allowing_gpu_memory_growth

Concretely, configure your TensorFlow session using the following option:

```
config = tf.ConfigProto()
config.gpu_options.allow_growth = True

```

**Comment by colaboratory-team** [comment]
To explicitly answer a question in the original report: GPUs are not shared among users.

**Comment by dheerajmpai** [comment]
I think this might be a bug as the previous user might not have terminated the process and google might have asssigned the VM without clearing it
