### ISSUE TITLE
Tensorflow text classification erroneous execution

### ISSUE THREAD

**Issue by AdityaOli** [googlecolab/colabtools#523]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
When you to go to :
https://www.tensorflow.org/tutorials/keras/basic_text_classification
and try executing the ode on google colab, the execution gives and error
```
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/imdb.npz
17465344/17464789 [==============================] - 0s 0us/step
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-35f9740dbe66> in <module>()
      1 imdb = keras.datasets.imdb
      2 
----> 3 (train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

2 frames
/usr/local/lib/python3.6/dist-packages/numpy/lib/format.py in read_array(fp, allow_pickle, pickle_kwargs)
    690         # The array contained Python objects. We need to unpickle the data.
    691         if not allow_pickle:
--> 692             raise ValueError("Object arrays cannot be loaded when "
    693                              "allow_pickle=False")
    694         if pickle_kwargs is None:

ValueError: Object arrays cannot be loaded when allow_pickle=False
```
- Describe the expected behavior:
Whereas the execution should have proceeded normally and not produced any errors.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
```
https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/keras/basic_text_classification.ipynb
```

**Comment by craigcitro** [comment]
Thanks for the report! This is due to an upstream numpy change, but the notebook has already been fixed.
