### ISSUE TITLE
Cannot load colaboratory

### ISSUE THREAD

**Issue by acmilannesta** [googlecolab/colabtools#525]
When I tried to create a new Python3 notebook on colab, it failed to load and returned the following error messages:

Error loading https://apis.google.com/js/client.js
Error: Error loading https://apis.google.com/js/client.js
    at HTMLScriptElement.k.onerror (https://colab.research.google.com/v2/external/gapi_loader.js:9:415)

Any suggestions are appreciated.

Thanks,
Jaosn

**Comment by colaboratory-team** [comment]
A common cause of this error is Chrome extensions which block access to the `https://apis.google.com/js/client.js` library.

I'd recommend trying to load the page in an incognito window with all extensions disabled. If the problem vanishes, it's likely that you'll need to whitelist the `colab.research.google.com` hostname in one of your extensions which blocks resource fetches.

**Comment by Mahe-git2hub** [comment]
I tried even in incognito where none of my extensions are enabled. I even tried it in 2 browsers (Firefox and Chrome). I am still getting the same message

**Comment by besley** [comment]
When I meet this issue, it seemed that after I added the url:https://apis.google.com ino trusted website from security tab in IE explorer seeting. It will work fine, although there isnt any chrome or mine extensions in my computer.
