### ISSUE TITLE
Keras dataset load_model

### ISSUE THREAD

**Issue by rakshithjk** [googlecolab/colabtools#527]
```
from keras.datasets import imdb
(X_train, y_train), (X_test, y_test) = imdb.load_data()
```

Executing the above code results in the following error

![image](https://user-images.githubusercontent.com/31753793/56845756-c72d2400-68e3-11e9-98ea-2dba8443f0cd.png)

It works perfectly on my local system.  Is it an issue with format.py? How do i rectify it?

This is the link to my notebook - 
[](url)(https://colab.research.google.com/drive/1Qx47kIRwmW0a4zcAqRz9Kq6ekteonxLS)

**Comment by metrizable** [comment]
Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem including Keras since then, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook (the reproducible notebook supplied in the OP doesn't appear to exist).
