### ISSUE TITLE
One of text feature is not working

### ISSUE THREAD

**Issue by Shwetago** [googlecolab/colabtools#529]
Format as code feature of the Text block is not working.
When I use back-ticks (```), Block of code should be highlighted
I am using Chrome.

**Comment by blois** [comment]
We should probably default to the notebook language for markdown syntax highlighting, currently you need to explicitly annotate the language for the syntax highlighting:

```markdown
```python
def something():
    pass
```
```

https://colab.research.google.com/gist/blois/0b612cd99f7a574ccb32a66c6707b3a2/markdown-code.ipynb?monaco=0
