### ISSUE TITLE
Same code works on CPU but not GPU

### ISSUE THREAD

**Issue by RParedesPalacios** [googlecolab/colabtools#53]
Check file attached below

**Comment by RParedesPalacios** [comment]
It appears:

Using TensorFlow backend.

(50000, 32, 32, 3)
(10000, 32, 32, 3)

---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
<ipython-input-1-9a1783308f6c> in <module>()
     76 model = Sequential()
     77 
---> 78 model=CBGN(model,32,x_train.shape[1:])
     79 model=CBGN(model,64)
     80 model=CBGN(model,128)

....

**Comment by RParedesPalacios** [comment]
[2_cifar_DA.py.zip](https://github.com/googlecolab/colabtools/files/1711470/2_cifar_DA.py.zip)

**Comment by fischman** [comment]
I don't get the same error you do; the code from the .zip file when pasted into a code cell works just fine.
(at least it's gotten as far as epoch 122/150 while I was not looking).

This is probably down to having pip install'd some incompatible package. You can reset your VM by executing `!kill -9 -1` and waiting 15-30s to reconnect.  If you can repro the problem after that please share a notebook that includes any prep/import/installs you've done.

**Comment by fischman** [comment]
...and eventually it completed training: https://colab.research.google.com/drive/1os0fHG6dr4p5ku0ZXijTrNMMlbZX1cMX#scrollTo=DSaO7CAv2zkf

**Comment by RParedesPalacios** [comment]
Hi Fischman, thanks for the reply, now its working, i don't thinkg there is any difference w.r.t yesterday...
anyway this is the link to the notebook

https://drive.google.com/file/d/1GnPVXGar0L1K5Mz1sjUPLcbWkYyltFnM/view?usp=sharing

Mmmm i am pretty sure that yesterday i did the same. Moreover, it is not the first time that the same code works on CPU but not GPU even when i re-start the VM and so...

**Comment by fischman** [comment]
Restarting the runtime (using cmd/ctrl-m-period) only restarts the python process but doesn't reinitialize the VM, so any packages you'd re-installed that would cause the sort of InternalError in the original report would persist on disk.  The `!kill -9 -1` trick will get your VM re-initialized with a fresh disk image so should be robust to this failure mode.

If you can repro starting from a fresh VM please follow up with details and reopen.

**Comment by RParedesPalacios** [comment]
Ok, next time i will try the !kill -9 -1 trick
Thanks!
