### ISSUE TITLE
Conflict of Tab operation

### ISSUE THREAD

**Issue by girishkuniyal** [googlecolab/colabtools#530]
Bug report for Colab: http://colab.research.google.com/.

- When i am typing a function of library like torch.nn.RNN() ,when put cursor inside bracket and press tab, sometimes shows docs and sometimes not.

- Please make Tab behavior inside colab consistent. do one operation completely well.
 dont want unexpected behaviour.
- The web browser I am using Firefox 66.0.3 (64-bit) on window 10

- Link to self-contained notebook that reproduces this issue
  https://colab.research.google.com/drive/1-5pQVFrzyRpV0bY-2MfRb22lGVSjCV7l

**Comment by blois** [comment]
Thanks for reporting- this was a regression and the fix should hopefully be available tomorrow.

The workaround is to execute a cell to reset the completion state.
