### ISSUE TITLE
Upgrade PyTorch to v1.1.0

### ISSUE THREAD

**Issue by soumith** [googlecolab/colabtools#531]
Hi folks,

We released a new PyTorch version v1.1.
The wheel links are:

CUDA 9.0

- https://download.pytorch.org/whl/cu90/torch-1.1.0-cp27-cp27m-linux_x86_64.whl
- https://download.pytorch.org/whl/cu90/torch-1.1.0-cp27-cp27mu-linux_x86_64.whl
- https://download.pytorch.org/whl/cu90/torch-1.1.0-cp36-cp36m-linux_x86_64.whl

CUDA 10.0

- https://download.pytorch.org/whl/cu100/torch-1.1.0-cp27-cp27m-linux_x86_64.whl
- https://download.pytorch.org/whl/cu100/torch-1.1.0-cp27-cp27mu-linux_x86_64.whl
- https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl

We're looking to having it updated in Colab.

Thanks very much.

cc'ing @colaboratory-team on the suggestion of Ami

**Comment by colaboratory-team** [comment]
b/131727249

**Comment by colaboratory-team** [comment]
pytorch 1.1 is now available in the standard Colab environment:
![AJOcQQzrG6V](https://user-images.githubusercontent.com/38081706/57255694-80d57480-7009-11e9-8d0d-bbaf4c3cdf35.png)

**Comment by soumith** [comment]
thank you very much!
