### ISSUE TITLE
Object arrays cannot be loaded when allow_pickle=False

### ISSUE THREAD

**Issue by BhargavB05** [googlecolab/colabtools#532]
Object arrays cannot be loaded when allow_pickle=False

- Describe the current behavior: I have been using google collab for the past few months and i had no issues loading imdb data, but from the past few days the execution was interrupted with the error "Object arrays cannot be loaded when allow_pickle=False"

- Describe the expected behavior: Before i had no issues when loading imdb data the execution was good and within short time i used to get the results for my code.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Firefox

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1XhDz4b9R6fjU5MwlpluRGkxui7vCzA5s

**Comment by craigcitro** [comment]
I believe this is the same root issue as #523, which is ultimately https://github.com/keras-team/keras/pull/12714. The only obvious workaround for now is to use `tf-nightly`.
