### ISSUE TITLE
Allow changing font size and picking font type inside the code cell

### ISSUE THREAD

**Issue by reddragon** [googlecolab/colabtools#533]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: The current Colab version as of (05/01) does not allow increasing either the font size, or picking the font inside the code cells. While this can be somewhat remedied by zooming in, that increases the size of _all_ the other elements on the page.

- Describe the expected behavior: Allow increasing font size, picking font etc. within the code cell.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*): N/A

**Comment by alext234** [comment]
+1 for this
the font size is too small for code cell.

**Comment by blois** [comment]
The new editor does have a slightly larger font size: https://colab.research.google.com/notebooks/editor_details.ipynb

Are the other font sizes within Colab sufficient? Typically browser zoom is used to increase all fonts together.

**Comment by theroyakash** [comment]
I use a 4k monitor With out 200% Zoom it's very difficult for the eyes

**Comment by katlyn-edwards** [comment]
Hi there! Thanks for the feedback:

You can specify what font is being used by the editor (lear more here --  https://research.google.com/colaboratory/faq.html#editor-font-family)

You can now also specify the font size via Tools -> Settings -> Editor
![font_size](https://user-images.githubusercontent.com/2673487/80127925-db811c80-8549-11ea-8477-c5b4618cf27b.png)

**Comment by kenqcl** [comment]
Is it possible to change the font type?

**Comment by o4dev** [comment]
@kenqcl This still doesn't seem to be possible from the UI. However (in case you still need to or if anyone else comes across this) the CSS selector for the editor text is `.view-line`  (for output text its `.output_text`, for rendered markdown its `.markdown`).

So you could just add a user script to your browser like this:
```
// @include https://colab.research.google.com/drive/*
.view-line {
    /* Change editor text to FiraCode Nerd Font. */
    font-family: "FiraCode Nerd Font";
}
```

Obviously changing "FiraCode Nerd Font" for whatever you need.

**Comment by blois** [comment]
@kenqcl @o4dev - Colab uses the browser's default `monospace` font, as mentioned in https://github.com/googlecolab/colabtools/issues/533#issuecomment-618521276. 

If you do switch to Fira Code or something similar you'll probably want to enable ligatures under Colab's editor settings.
