### ISSUE TITLE
Help window text doesn't scroll

### ISSUE THREAD

**Issue by skepticalsports** [googlecolab/colabtools#534]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
When entering ?whatever into a card and running it, a bar on the bottom pops up with a "Help" tab and the help documentation for whatever. If that text happens to be longer than the box, it doesn't scroll and you can only see more by making the box bigger (and isn't even easy to copy).
![image](https://user-images.githubusercontent.com/7376078/57031697-3f099000-6bfd-11e9-96bf-772929c9e205.png)

- Describe the expected behavior:
In regular Jupyter notebooks, running ?whatever pops up a frame on the bottom of the page that has a scroll bar on the right and a button to pop those results out into their own window. This would be reasonably acceptable normal behavior over no scroll bar at all, of course. Preferably, however, for a number of reasons it would be nice to be able to run help commands and have the help results pin to the bottom of the card like any other results/texts/charts etc. 
![image](https://user-images.githubusercontent.com/7376078/57031764-72e4b580-6bfd-11e9-9fa7-e01f6e685cc3.png)

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Tested in Chrome and Firefox

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1sxUCyCdGrprBr8Etj_u2lpvt1GA5ydUp

**Comment by colaboratory-team** [comment]
Thanks for the report. We'll take a look.
b/131772334

**Comment by corrieann** [comment]
This has been fixed.
