### ISSUE TITLE
Colab hangs if "Omit code cell output when saving this notebook" is not set and a cell is busy for a long time.

### ISSUE THREAD

**Issue by wflorin** [googlecolab/colabtools#535]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
If "Omit code cell output when saving this notebook" is not set and a cell is busy for a long time, a warning pops up saying that it couldn't auto save the outputs. After this warning  it hangs. Also, if I close the browser and reopen the notebook it hangs again after reconnecting to the runtime if it's still busy.

The only way to reopen the notebook is to wait till the session ends.

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1FByveN6oWu9YLPzMezciGmW5Zi2uB0zL

**Comment by wflorin** [comment]
Now it works. It does't hang anymore.
Thanks

**Comment by blois** [comment]
The 'Omit code cell output...' option _should_  be independent of the saving frequency, which _should_ also be independent of the reconnecting state. But if you have another window open for the same notebook which is executing the code, then that could be writing the Drive document which would cause save conflicts from the other window, and the kernel would be busy from that tab.
