### ISSUE TITLE
Fairness excercise is not working

### ISSUE THREAD

**Issue by TE-JoakimElvander** [googlecolab/colabtools#536]
Describe the current behavior:
The intro_to_fairness.ipynb is not working properly.

During setup the following error is described (related to previous reported bug that PyTorch is updated.)
```
Collecting seaborn==0.8.1
Downloading https://files.pythonhosted.org/packages/10/01/dd1c7838cde3b69b247aaeb61016e238cafd8188a276e366d36aa6bcdab4/seaborn-0.8.1.tar.gz (178kB)
     |████████████████████████████████| 184kB 2.9MB/s 
Building wheels for collected packages: seaborn
  Building wheel for seaborn (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/26/0a/44/53ddd89769e62f7c6691976375b86c6492e7dd20a2d3970e32

Successfully built seaborn
ERROR: fastai 0.7.0 has requirement torch<0.4, but you'll have torch 1.0.1.post2 which isincompatible.
Installing collected packages: seaborn
  Found existing installation: seaborn 0.9.0
    Uninstalling seaborn-0.9.0:
      Successfully uninstalled seaborn-0.9.0
Successfully installed seaborn-0.8.1
Modules are imported."
```

Secondly, all the executions of Facets and Facets and Facets Dive fail to produce any output in the window.

- Describe the expected behavior:
No errors while importing modules
Expected output is displayed for the Facets exercises

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Firefox 66.0.3 (64 bit)

Link to failing page:
https://colab.research.google.com/github/google/eng-edu/blob/master/ml/cc/exercises/intro_to_fairness.ipynb

**Comment by craigcitro** [comment]
b/132081012

**Comment by sandersk** [comment]
This is now fixed. Added handling to polyfill web components for support in Firefox.
