### ISSUE TITLE
Cannot upgrade pyzmq on Google Colaboratory

### ISSUE THREAD

**Issue by johnnykost** [googlecolab/colabtools#537]
I want to upgrade pyzmq in Google Colaboratory. I used the command `!pip install pyzmq`, but after restarting the runtime, it cannot reconnect.

**Comment by craigcitro** [comment]
(This also appears as https://stackoverflow.com/questions/55969773/cannot-upgrade-pyzmq-on-google-colaboratory)

As noted on SO, this is expected: upgrading `pyzmq` may affect the communcation libraries used by colab, which can wreak all sorts of havoc.
