### ISSUE TITLE
i cant delete notebook in colab

### ISSUE THREAD

**Issue by haseebi** [googlecolab/colabtools#538]
Bug report for Colab: http://colab.research.google.com/.
why i seee nonsense when i open colab
how get rid of these
i cant delete notebook 
no clear structure of cloab file storage 

![screencapture-colab-research-google-notebooks-welcome-ipynb-2019-05-04-21_33_09](https://user-images.githubusercontent.com/35608338/57182080-ac931600-6eb4-11e9-903c-a21115815553.png)

![screencapture-colab-research-google-notebooks-welcome-ipynb-2019-05-04-21_33_09](https://user-images.githubusercontent.com/35608338/57182073-9e44fa00-6eb4-11e9-90ca-c7a1006bb609.png)

- The web browser  i am using (Chrome)

**Comment by prabhat-123** [comment]
go to google drive and delete it bro

**Comment by frainmaster** [comment]
for anyone who is seeing this problem, you must filter first the notebook you are deleting at the search input.

![image](https://user-images.githubusercontent.com/32104766/97067284-696bbc00-15ee-11eb-9ea6-1485527f805b.png)

When only one notebook is shown (which is the one you wanted to delete), click the delete button.

![image](https://user-images.githubusercontent.com/32104766/97067300-94eea680-15ee-11eb-96ff-8dc7f040163a.png)

Note that the delete button will delete all notebooks appearing in the filtered list.

**Comment by wtfhafsa** [comment]
It was helpful. Thanks
