### ISSUE TITLE
files.upload() in python3 should return bytes

### ISSUE THREAD

**Issue by blois** [googlecolab/colabtools#54]
files.upload() returns string data, this should probably be bytes.

**Comment by Androbin** [comment]
`files.upload` uses `base64.b64decode` which returns `bytes`.
https://github.com/googlecolab/colabtools/blob/fca93e7dc826302fa3072430c35f11afed514ab1/google/colab/files.py#L75
Docs: https://docs.python.org/3/library/base64.html#base64.b64decode
