### ISSUE TITLE
invalid literal for int() with base 10: '<!DOCTYPE' from the google w2vec

### ISSUE THREAD

**Issue by Hayor** [googlecolab/colabtools#540]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I am currently trying to implement a neural network architecture on colab, I ran the code last week but then this morning, the code failed to run.
- Describe the expected behavior:
The code is meant to embed my sentences from the quora pair data set into vectors using the google word2vec news.
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://drive.google.com/open?id=1kuNejwYINFhblMPIWoFrt3HizHrJLExG

**Comment by blois** [comment]
It looks like you're passing the URL of a Drive file to load_word2vec_format and that it doesn't handle those. The actualy URL which is being used (https://drive.google.com/file/d/XXXX/edit?usp=sharing) is for the preview, not the file contents.

I would recommend downloading the file locally first, then passing a local path to load_word2vec_format.
