### ISSUE TITLE
Disabling auto-scroll of outputs

### ISSUE THREAD

**Issue by blois** [googlecolab/colabtools#541]
Repeating a user question here: 
Is it possible to disable auto-scrolling of large outputs to allow the entire output to be visible?

Answer:
Yes- the maximum height is 1000px but this can be overriden by executing the Javascript:
```javascript
google.colab.output.setIframeHeight(0, true, {
  maxHeight: 5000,
})
```

An example in Python:
```python
from IPython.display import Javascript
display(Javascript('''google.colab.output.setIframeHeight(0, true, {maxHeight: 5000})'''))

for i in range(200):
  print(i)
```

**Comment by JakobLS** [comment]
If I want to shrink the width of the output then? To keep it within the width of the window for example. 

I've tried various variants of below code but without success. 

` 
from IPython.display import Javascript
display(Javascript('''google.colab.output.setIframeWidth(0, true, {maxWidth: 500})''')) 
`


Is there an alternative for this?

**Comment by blois** [comment]
The iframe itself should always be limited to the width of the window, I'm guessing you're looking to wrap text within the iframe rather than horizontally scroll?

An example of that is:
https://colab.sandbox.google.com/gist/blois/a1e3918fe80487c8d539190eee220028/pre-wrapping.ipynb

Otherwise you should be able to use HTML styling within the outputframe to further constrain the rendering sizes.

**Comment by JakobLS** [comment]
You're correct. I apologise my rather ambiguous explanation. In either way, the approach in the link worked. Thank you very much @blois!

**Comment by bonryu** [comment]
Is there a solution for text wrapping of output that can be applied once at top of the notebook (i.e. to avoid a horizontal scroll bar)? As far as I can tell, the solution in pre-wrapping.ipynb example must be used in every cell that prints horizontally long outputs.

For example, this solution ( [https://stackoverflow.com/questions/36419342/how-to-wrap-code-text-in-jupyter-notebooks](https://stackoverflow.com/questions/36419342/how-to-wrap-code-text-in-jupyter-notebooks) ) edits the local file ~/.jupyter/nbconfig/notbook.json.

Is there an equivalent method that can be done for colab?  Thank you.

**Comment by bonryu** [comment]
Inspired by numerous stackoverflow posts, I have come to a solution, which I have also shared on stackoverflow: https://stackoverflow.com/questions/58890109/line-wrapping-in-collaboratory-google-results/61401455#61401455

The solution I have come to is to put the following in the first cell of the notebook. Then every cell afterwards will execute the css snippet inside the `set_css()` function.
```
from IPython.display import HTML, display

def set_css():
  display(HTML('''
  <style>
    pre {
        white-space: pre-wrap;
    }
  </style>
  '''))
get_ipython().events.register('pre_run_cell', set_css)
```

**Comment by Sol1986** [comment]
just to further bonryu's post:

For thinking models like DeepSeek R1, I'd say use this because it makes it easier to read the output.

 ```
   from IPython.core.display import display, HTML
    
    display(HTML('''
    <style>
      pre {
        white-space: pre-wrap !important;  /* Wrap text */
        word-break: break-word !important; /* Prevent long words from overflowing */
      }
      .output_result {
        max-height: none !important; /* Remove scroll */
      }
      .output_area {
        overflow-y: visible !important; /* Prevent vertical scrolling */
      }
    </style>
    '''))
```
