### ISSUE TITLE
latex rendering became much slower

### ISSUE THREAD

**Issue by yotamgi** [googlecolab/colabtools#542]
Some recent change made the latex rendering engine work much slower, especially in notebooks that have a lot of latex cells. This is a major setback, where for me, working with many of my colab notebooks is currently impossible.

**Comment by blois** [comment]
Do you happen to have an example notebook and do you have an approximate estimate of when the slowdown may have occurred?

**Comment by yotamgi** [comment]
Yes, I do have an example notebook:
https://colab.research.google.com/drive/1UyuInGdSNSc2aNy3CNZGFYUJSmtzA0zd

It does have a lot of latex cells, but until about two weeks ago, after it
finished loading once all the latex cells (which took no more than 2
minutes), I could edit the notebook with no delay, where only the edited
notes were re-rendered. Currently, it seems like every edit of a cell
triggers re-rendering of all the latex cells, which makes it pretty
difficult to work with.

Thanks!

**Comment by blois** [comment]
We're working on some performance improvements which should improve this notebook a bit, but looking at it there's just a *lot* of math in there which is really causing a lot of browser layout issues. The best and most immediate workaround at this time would be to split the notebook into more manageable pieces.

**Comment by yotamgi** [comment]
I agree that this notebook has a lot of latex cells, but up until now I
could have worked with such notebooks. There has been some change in the
past month that made it work much slower.

Anyway, thanks for the quick response and I am looking forward to see the
new features in colab :)

**Comment by colaboratory-team** [comment]
b/132196272
