### ISSUE TITLE
DOWNLOAD FAILED Cannot read property 'size' of undefined

### ISSUE THREAD

**Issue by utsavg** [googlecolab/colabtools#543]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: Unable to download save model and weights

- Describe the expected behavior:download save model and weights

- The web browser you are using (Chrome, Firefox, Safari, etc.):chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):https://colab.research.google.com/drive/1yc9a-yRgDJ15Q_7M878sGLWkALVEUB7H

**Comment by craigcitro** [comment]
The error in the title doesn't appear in your notebook; was this when trying to download from the files pane? Can you copy-paste the error you see from chrome devtools?

**Comment by craigcitro** [comment]
The error in the title doesn't appear in your notebook; was this when trying to download from the files pane? Can you copy-paste the error you see from chrome devtools?

**Comment by utsavg** [comment]
After restarting my system its working fine.Now I am not able to see that error.
