### ISSUE TITLE
Image resize function in Open CV not working

### ISSUE THREAD

**Issue by ramakanthn1** [googlecolab/colabtools#544]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: While performing the resize operation of a frame/image using cv2 results in the following:

_MODEL_SIZE = (416, 416)
resized_frame = cv2.resize(frame, dsize=_MODEL_SIZE[::-1])

When trying to resize video frame by frame which currently is in a native resolution of 1280*720 i am encountering the following error:

error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

One verified answer mentions that there is a possible bug in Open Cv that can be circumvented by commenting out a line from the "imgwarp.cpp" file in the modules. 

The above fix is possible only on local machines but not over this platform as i assume.  

- Describe the expected behavior:

Ideally this function should resize the image/frame so that further processing can occur.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome

- Link to self-contained notebook that reproduces this issue:

https://colab.research.google.com/drive/19ojde30ZS1K8ylD35qhkPd5H4iH_Zp8V

  (click the *Share* button, then *Get Shareable Link*):

**Comment by metrizable** [comment]
Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem including OpenCV since then, if you are still experiencing the issue, please file a new issue and provide a new, minimal reproducible notebook.
