### ISSUE TITLE
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown   len(cache))

### ISSUE THREAD

**Issue by aas1070** [googlecolab/colabtools#546]

**Comment by metrizable** [comment]
Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem including Python since then, if you are still experiencing the issue, please file a new issue and provide a minimal reproducible notebook.
