### ISSUE TITLE
Cant scroll the page the way I want.

### ISSUE THREAD

**Issue by paulgureghian** [googlecolab/colabtools#547]
I used to be able to hit the escape key and the three dots in the cell would go away and lock the page so I could scroll up and down with the arrow keys. now It just doesn't respond when I hit the escape key, and I can only scroll from cell to cell.  I tried it with both current chrome and firefox.
![Capture15](https://user-images.githubusercontent.com/8146561/57576453-e1532000-7414-11e9-8da6-7b4fe7d3b201.PNG)

**Comment by katlyn-edwards** [comment]
Thanks for the report, we'll take a look - b/132516361

**Comment by katlyn-edwards** [comment]
Thanks for flagging this, we've fixed it internally and hope to see it live before the end of the week. I'll post here again once I've confirmed it's live.

**Comment by paulgureghian** [comment]
Thanks. I guess that means it still will be the same on my end until it goes live ?

**Comment by katlyn-edwards** [comment]
This should be live now! Sorry about the delay, please let me know if you're still seeing this.

**Comment by paulgureghian** [comment]
Looks good. It works again. thanks

**Comment by paulgureghian** [comment]
It works now. thanks
