### ISSUE TITLE
Has anybody successfully embedded a bokeh server in a google colab notebook?

### ISSUE THREAD

**Issue by juanpac96** [googlecolab/colabtools#549]
I'm trying to run a copy of bokeh/notebook_embed.ipynb in google colab. All cells execute fine but show(modify_doc) produces no output. What value should I pass as notebook_url? when I run in jupyterlab this work perfectly, but when I try use colab this didn't work.  

I have looked at the console in chrome devtools and it's pretty clear that default values don't apply to this environment (I see some localhost:8080 all over the place).
- Link to self-contained notebook that reproduces this issue
https://colab.research.google.com/drive/1zWRB-tZsnE-ORgXGV0fI1qZOjnRonpuk#scrollTo=VoewznOajt9S&line=11&uniqifier=1

**Comment by blois** [comment]
I wasn't able to access your notebook, but an example one is: https://colab.sandbox.google.com/gist/blois/f2bcc3d420aea95f09f6eebe711cf82c/bokeh-server.ipynb

When navigating to the running server it is currently failing because it's attempting to connect with a websocket.

**Comment by firmai** [comment]
Have any of you succeeded my dear friends. If you have could you help me out.
