### ISSUE TITLE
There isn't any backend. Try it later.

### ISSUE THREAD

**Issue by RodrigoTomeES** [googlecolab/colabtools#550]
Hi,

I am a student from La Rioja University. I used colab for IA subject, but since a few days I am receiving this error from colab, _There isn't any backend. Try it later._.

Some colleagues are also experiencing this problem.

Does anyone know why this error occurs?

Thanks

**Comment by WaterKnight1998** [comment]
Same to me!

**Comment by blois** [comment]
If you are encountering this please send feedback using the 'Help -> Send feedback...' menu and we may be able to investigate.
