### ISSUE TITLE
Can't change Python interpreter version

### ISSUE THREAD

**Issue by 2ndMessiah** [googlecolab/colabtools#551]
UPDATE: Found that python3+GPU leads it to python2 while python3+None acc leads it to python3.

Original post:
I always use python3 in my projects. And I started to notice that the jupyter is using python2 from the time that I saw some messages like "/usr/local/lib/python2.7/distpackages/sklearn/svm/base.py..." even if I have set it to python3..

Then I used sys,six,platform packages to verify this and it seems as it is..

Demo notebook:
https://drive.google.com/open?id=1c8X66IQH7rYaJhqwRwhCC5MMnywtYHST

Thanks.

**Comment by blois** [comment]
I'm seeing it use Python3 in both cases- it could be something where the version was changed but wasn't propagated correctly. If this happens then using the Runtime -> Reset all runtimes... command should get it back on track.

**Comment by 2ndMessiah** [comment]
Indeed it's been all fine since yesterday.. But that's what I encountered as a matter of a fact..So weird.

**Comment by blois** [comment]
I don't doubt that it occurred- the way Python versions are changed is a bit odd. Please let us know if you figure out a way to reproduce it.
