### ISSUE TITLE
No backends available

### ISSUE THREAD

**Issue by joheras** [googlecolab/colabtools#552]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior: When trying to connect to any backend, it shows the message "Sorry, no backends available. Please try again later." This only happens with one of my accounts but not the other. I am currently using Google Colaboratory for teaching an Artificial Intelligence course.

- Describe the expected behavior: Connection with any backend.

- The web browser you are using (Chrome, Firefox, Safari, etc.): It happens with any web browser.

**Comment by blois** [comment]
If you are encountering this please send feedback using the 'Help -> Send feedback...' menu and we may be able to investigate.
