### ISSUE TITLE
Cython annotations tangled

### ISSUE THREAD

**Issue by hexchain** [googlecolab/colabtools#554]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
A cell starting with `%%cython -a` should output a cython report. In Colab, the report looks tangled:
![image](https://user-images.githubusercontent.com/529520/57807867-58b0e880-7762-11e9-919e-7b2f720419b6.png)

- Describe the expected behavior:
In a local jupyter notebook, the report looks like this:
![image](https://user-images.githubusercontent.com/529520/57807901-75e5b700-7762-11e9-9ea5-e99dbb4a6d7b.png)

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chromium 74.0.3729.157 (Official Build) Arch Linux (64-bit)

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1_cpwj-zNd8kvY_ml0t0s_ragdwBRQsoa

**Comment by blois** [comment]
Interesting- Colab is styling all <pre> elements as inline- this is probably something that should not be done.

Thanks for the report!

**Comment by hexchain** [comment]
It seems to me that this issue has been fixed.

**Comment by blois** [comment]
Yep- the fix went out yesterday.
