### ISSUE TITLE
"Open in Colab" shield.io badge has the wrong link

### ISSUE THREAD

**Issue by robincrlee** [googlecolab/colabtools#557]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
I created a colab notebook in a development branch. After I merge the branch into master branch, the link to the "open in colab"  (button that looks like this thing below) points to the file in the development branch. This becomes problematic when the dev branch gets deleted. 

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb)

- Describe the expected behavior:

The link should point to the master/updated location.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome
- Link to repo that reproduces this issue
https://github.com/robincrlee/Colab-bug-example/blob/master/example.ipynb

When I hover over the badge, the links point to the dev file.

**Comment by ziatdinovmax** [comment]
You probably need to modify the href here (now it points to
.../blob/dev/...):

"cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/robincrlee/Colab-bug-example/blob/dev/example.ipynb\"
target=\"_parent\"><img
src=\"https://colab.research.google.com/assets/colab-badge.svg\"
alt=\"Open In Colab\"/></a>"

**Comment by robincrlee** [comment]
Looks like this is the only way to modify the link since the colab badge is part of the JSON file.
