### ISSUE TITLE
%%bigquery <destination var> does not hide output

### ISSUE THREAD

**Issue by stdlibh** [googlecolab/colabtools#558]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
According to the documentation, adding a variable to store the query results should prevent the results from displaying.  However, after adding a variable, query results are still displayed.  At least the contents of the query are also held in dataframe, so the functionality is not completely broken.

- Describe the expected behavior:
The results should not be displayed but should be contained in the dataframe as per the documentation found here: https://googleapis.github.io/google-cloud-python/latest/bigquery/magics.html

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link to self-contained notebook that reproduces this issue
https://colab.research.google.com/drive/1fJh7D32FuQg7mRs8VRdsYFtEnqgYcfRG

**Comment by craigcitro** [comment]
It looks like we're due for an upgrade of `google-cloud-bigquery`.

If you run

    !pip install --upgrade google-cloud-bigquery

(and restart your runtime if prompted), you'll see the expected behavior.

**Comment by colaboratory-team** [comment]
b/133201605

**Comment by stdlibh** [comment]
Hey Craig - Yep - that fixed it.  Appreciate the tip.

---FSR
