### ISSUE TITLE
GPU is not working. (It was working perfectly on Sunday with the same program)

### ISSUE THREAD

**Issue by stevessschen** [googlecolab/colabtools#56]
GPU is not working with the following message; the program just crashed!! (It was working perfectly on Sunday with the same program). It was working fine without GPU.

Training...
Epoch 1/150
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1322     try:
-> 1323       return fn(*args)
   1324     except errors.OpError as e:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _run_fn(session, feed_dict, fetch_list, target_list, options, run_metadata)
   1301                                    feed_dict, fetch_list, target_list,
-> 1302                                    status, run_metadata)
   1303

**Comment by fischman** [comment]
ResourceExhaustedError most likely indicates running out of GPU memory.
The easiest way for this to happen is using TF with GPU but not using the allow_growth config option as demonstrated in https://colab.research.google.com/notebooks/gpu.ipynb
Without that option, the first GPU notebook you use will allocate all GPU RAM and leave none for subsequent notebooks.

You can reset your runtime by executing
!kill -9 -1
which will disconnect all your notebook and refresh your runtime from scratch (losing any local files or state), and clear anything using GPU RAM.  Wait 30-45s and then click the CONNECT button to reconnect.

If you can reproduce a ResourceExhaustionError that isn't simply running out of GPU RAM, please do share the notebook with colaboratory-team@google.com and reopen this bug.
