### ISSUE TITLE
cv2.VideoCapture().open() not working and always returns FALSE

### ISSUE THREAD

**Issue by surya-palaniswamy** [googlecolab/colabtools#560]
The function does not open the webcam. But on using Google Colab's code snippet for image capture it accesses the webcam
I am currently running this on Chrome
The notebook containing only the error:
https://colab.research.google.com/drive/1uQkkF7KSnjLAiQGjTKmx-kVMX3RuYuYP

**Comment by colaboratory-team** [comment]
You'll need to use web APIs to interact with the camera in Colab. (Colab codes executes on a VM that doesn't have a webcam attached, so APIs that presume direct hardware access won't work.)

The advanced output example notebook has an example showing how to access the camera using web APIs:
https://colab.research.google.com/notebooks/snippets/advanced_outputs.ipynb#scrollTo=2viqYx97hPMi

**Comment by vighc** [comment]
Step1 Go to Google Colaboratory

Step2 Create a new notebook

Step3 Click snippet panel

Step4 Click Camera Capture
Click insert

Step5 Run script
Shit + Enter

**Comment by YoniChechik** [comment]
Here is an example of working with video capturing in google colab: https://gist.github.com/YoniChechik/f01c73558c865f2ef931162e2a0872de
