### ISSUE TITLE
Upgrade TorchVision to v0.3.0

### ISSUE THREAD

**Issue by soumith** [googlecolab/colabtools#564]
Hi folks,

We released a new TorchVision version v0.3.0.
The wheel links are:

CUDA 9.0

https://download.pytorch.org/whl/cu90/torchvision-0.3.0-cp27-cp27m-linux_x86_64.whl
https://download.pytorch.org/whl/cu90/torchvision-0.3.0-cp27-cp27mu-linux_x86_64.whl
https://download.pytorch.org/whl/cu90/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
CUDA 10.0

https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp27-cp27m-linux_x86_64.whl
https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp27-cp27mu-linux_x86_64.whl
https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl

We're looking to having it updated in Colab.

Thanks very much.

cc'ing @colaboratory-team on the suggestion of Ami

**Comment by colaboratory-team** [comment]
b/133420808

**Comment by colaboratory-team** [comment]
The rollout is complete.

**Comment by soumith** [comment]
thank you very much!
