### ISSUE TITLE
Attached files not included when shared

### ISSUE THREAD

**Issue by pbeens** [googlecolab/colabtools#566]
I'm a teacher using Colab in my high school CS class. 

When I ask a student to share a notebook with me that reads in a data file as in...
`open('DATA10.txt', 'r')`

...the data file is not included in the shared copy of the Colab document even though it is present in the student's own notebook.

**Comment by ziatdinovmax** [comment]
In my experience, the best way to work with files needed to run a notebook
is to store them in Google Drive and then download with a 'gdown' command
into the notebook. So the first cell in your notebook will be: !gdown
<shareable link>. Alternatively, you can make a Team Drive for your project
to which both you and your students will have an access via a shared colab
notebook and store the files on that drive.

**Comment by pbeens** [comment]
Thanks so much, Maxim!

It took some playing around but I eventually got it working once I discovered I need to use the download link for the file, not the shared link.

Here's the test I created:
https://colab.research.google.com/drive/17nP39iS2wqrab_RMUvvO9ZHjflpRgaOK
