### ISSUE TITLE
Caffe train: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by daothingoclan** [googlecolab/colabtools#568]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
1. Notebook is setup as Python3 and GPU
2. Installed caffe-cuda and set gpu mode
3. Run Caffe train command:
!caffe train -solver '/content/drive/My Drive/quick-solver.prototxt' -weights '/content/drive/My Drive/model.caffemodel' -gpu all

4. Then got below error:
Check failed: error == cudaSuccess (48 vs. 0)  no kernel image is available for execution on the device
*** Check failure stack trace: ***
    @     0x7fd4c082f0cd  google::LogMessage::Fail()
    @     0x7fd4c0830f33  google::LogMessage::SendToLog()
    @     0x7fd4c082ec28  google::LogMessage::Flush()
    @     0x7fd4c0831999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd4c0f60e61  caffe::im2col_gpu<>()
    @     0x7fd4c0d9bbd9  caffe::BaseConvolutionLayer<>::conv_im2col_gpu()
    @     0x7fd4c0d9bcd6  caffe::BaseConvolutionLayer<>::forward_gpu_gemm()
    @     0x7fd4c0f25d66  caffe::ConvolutionLayer<>::Forward_gpu()
    @     0x7fd4c0e9ef11  caffe::Net<>::ForwardFromTo()
    @     0x7fd4c0e9f017  caffe::Net<>::Forward()
    @     0x7fd4c0ebdb38  caffe::Solver<>::Step()
    @     0x7fd4c0ebe92a  caffe::Solver<>::Solve()
    @     0x55ae8d00207c  train()
    @     0x55ae8cffe37b  main
    @     0x7fd4bf5c6b97  __libc_start_main
    @     0x55ae8cffed6a  _start

- Describe the expected behavior:
Should execute train command without error.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome and Safari.

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/15NbDON7sTbRHokdR9cdkiK_XaIvzTsio

@colaboratory-team

**Comment by daothingoclan** [comment]
I found out the reason. It happened cuz Colab had been upgraded to CUDA 10 and built-in cafe-cuda library is not support arch for CUDA 10.

Currently I need to build caffe from source with latest version on github. So pain to install from source, slow building. But it might be only solution atm.

**Comment by colaboratory-team** [comment]
b/134015668
