### ISSUE TITLE
ENH: toc2 Table of Contents extension

### ISSUE THREAD

**Issue by westurner** [googlecolab/colabtools#57]
https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html

-- https://twitter.com/mathcass/status/962785704899002368

> I'll also have to add both Scratchpad  https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/scratchpad/README.html  and Collapsible headings  https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/collapsible_headings/readme.html  as other must-have extensions for #Jupyter

**Comment by westurner** [comment]
```bash
conda install -c conda-forge jupyter_contrib_nbextensions

# conda install -c conda-forge jupyter_nbextensions_configurator
```

https://github.com/ipython-contrib/jupyter_contrib_nbextensions

https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/

**Comment by craigcitro** [comment]
Just to confirm: did you discover the Colab equivalents of all these?

* ctrl-alt-n: open scratch cell
* View -> Table of Contents
* zippies for collapsing sections

(ctrl-alt-p opens the command palette, which is useful here.)

**Comment by westurner** [comment]
Yup. Thanks!
