### ISSUE TITLE
Upload not working on firefox

### ISSUE THREAD

**Issue by Hafman08** [googlecolab/colabtools#572]
Upload seems to not work again on FIrefox version 67.0. I press upload and in console appears :
![image](https://user-images.githubusercontent.com/9305899/58650121-8a0ae600-8316-11e9-81f3-980bcf79083c.png)

**Comment by craigcitro** [comment]
Yep, this is a bug -- fix is already in, should go live tomorrow. Sorry about the inconvenience!
