### ISSUE TITLE
500 - Internal Server Error

### ISSUE THREAD

**Issue by PN12** [googlecolab/colabtools#574]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by PN12** [comment]
Hi, 

While running the below command - 
"!kaggle datasets download -d kazanova/sentiment140 -p /content"

I m facing the below error - 500 - Internal Server Error

Please advise the resolution.

Thanks

**Comment by blois** [comment]
This could be related to https://github.com/googlecolab/colabtools/issues/526, we're investigating.
