### ISSUE TITLE
runtime disconnects

### ISSUE THREAD

**Issue by wasaga** [googlecolab/colabtools#58]
Please clarify disconnect policy. 

I frequently find frontend disconnected from runtime while executing long-running snippet (i.e. which reads DB, processes data and pushes back to DB). I can see that runtime is alive (as new data is being pushed to DB) but I can't reconnect to that runtime anymore - will always get a new instance.

**Comment by colaboratory-team** [comment]
Please share a self-contained notebook that reproduces the issue and we'll take a closer look.

**Comment by ShivamRawat0l** [comment]
@wasaga
https://medium.com/@shivamrawat_756/how-to-prevent-google-colab-from-disconnecting-717b88a128c0 Maybe this could prevent it from disconnecting. But internet should be connected.
My Q learning notebook disconnects too

**Comment by kunakl07** [comment]
My colab notebook is getting continuously disconnected, it would connect for a second or two and would automatically get disconnected.
https://colab.research.google.com/drive/1Y7msFg_FI78mPaUouiuozJoWJscqRRbo?usp=sharing
Could you please help me out on solving this issue
