### ISSUE TITLE
pyTorch tutorial fails with Exactly one of "prediction_class" and "framework" may be provided

### ISSUE THREAD

**Issue by sanealytics** [googlecolab/colabtools#580]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

Deploy model cell fails with 

```
Exactly one of "prediction_class" and "framework" may be provided. In order to use a custom prediction class, "framework" should be left unspecified.
```

- Describe the expected behavior:

Should not fail

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/github/GoogleCloudPlatform/cloudml-samples/blob/master/notebooks/pytorch/Text%20Classification%20Using%20PyTorch%20and%20CMLE.ipynb

**Comment by metrizable** [comment]
Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem including pyTorch since then, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook (as aside, the notebook you shared is no longer available).
