### ISSUE TITLE
Colab misses some cells from notebook created with Jupyter

### ISSUE THREAD

**Issue by subhacom** [googlecolab/colabtools#581]
When a notebook created with local Jupyter (v4.4.0) is opened in Colab, some cells are missing. 

This has been reported before on Jupyter notebook issue tracker: https://github.com/jupyter/notebook/issues/4307 and StackOverflow: https://stackoverflow.com/questions/53973334/versions-of-jupyter-compatible-with-colab

- Using firefox 67.0.1 (64 bit)

- Public notebook to reproduce this problem: https://gist.github.com/subhacom/ec5233708e7bb1cd73c2e4e4a7f23156
  The notebook above was originally created in Colab, then downloaded locally and edited in Jupyter notebook.

**Comment by subhacom** [comment]
It looks like the `id` field in metadata for the cell gets duplicated when I split a cell in Jupyter notebook.

**Comment by blois** [comment]
Colab was doing this as a workaround for some long-past issue- it should really be changed to give the cells a unique ID instead.

**Comment by blois** [comment]
b/134832954

**Comment by subhacom** [comment]
Possible workaround: deleting the `id` field from cell metadata before uploading the notebook avoids this issue.

**Comment by blois** [comment]
Yes, and the fix should be live in a few days.

**Comment by blois** [comment]
The fix is now live.
