### ISSUE TITLE
Deprecated library package( scipy.misc.factorial ) causing error

### ISSUE THREAD

**Issue by Gurubux** [googlecolab/colabtools#582]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

**ISSUE**
On the import of `import statsmodels.formula.api as sm`
Reports following error in Read-Only file _edgeworth.py_
```
While /usr/local/lib/python3.6/dist-packages/statsmodels/distributions/edgeworth.py in <module>()
      5 import numpy as np
      6 from numpy.polynomial.hermite_e import HermiteE
----> 7 from scipy.misc import factorial
      8 from scipy.stats import rv_continuous
      9 import scipy.special as special

ImportError: cannot import name 'factorial'
```

The **Solution** as per https://stackoverflow.com/a/56284155/5653568 is to import `scipy.special.factorial` instead of `scipy.misc.factorial`, since `scipy.misc.factorial` is deprecated.

Web browser used : Chrome

Link to colab file : https://colab.research.google.com/drive/1JCi5qVE349ienBeryVPllRTYyswRaRLn

**Comment by craigcitro** [comment]
It looks like our versions of statsmodels and scipy are incompatible: https://github.com/statsmodels/statsmodels/issues/5759

Until that's fixed, you should be able to `pip install scipy==1.2` to get unblocked.

**Comment by Gurubux** [comment]
@craigcitro 
That resolved my current code issue 
Appreciate instant reply 👍 
I am not sure whether this issue is to be closed or be left open until incompatibility is managed.
https://colab.research.google.com/drive/1JCi5qVE349ienBeryVPllRTYyswRaRLn

**Comment by craigcitro** [comment]
Yes, let's leave this open for tracking the fix on our side.

**Comment by jakevdp** [comment]
I think the fix will be to upgrade our installation of statsmodels to version 0.10, which should be released some time this month: https://github.com/statsmodels/statsmodels/issues/5759

**Comment by jakevdp** [comment]
statsmodels is now updated in colab
