### ISSUE TITLE
error loading notebooks

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#585]
Could not fetch resource at https://00e9e64bac6f947324a0324db4e74880646e43baa6c90152fb-apidata.googleusercontent.com/download/drive/v2beta/files/1szW-I-EkjHHI6aDoNZYaAMtrdjsjUb2w?qk=AD5uMEvd0MMPIqlrXzpXlVjoAWYFvNekl_roy9QpfBW7wfSmBkBZa8zxAcVOdOsYvJDHqHjfX7W9mB9e3_S4_dhFDpBtGDw0JpiTJGImmSU1T_9yv52GhKW_nFO_AusPBphNoCHRYHqK5eI9V10N6KEuJ1fe365FAONG7AYFLrRXymiIj00lvkuBxPfrf503pImBKcQ53dYQog22Eh-BeMOMgPDROJkjth-yN7E7C7nqv6Vp61aNYsGAuoRMi3fAr3CcKTK0KFX0-M9BF8ImSai8AgO5_Qq79i-2rxe2j-smIxF3PaBYlHn9stIjZx3RvWOj3801OvLnIASmTv0DF5r2uFDEFdF32jADKv1EOZsrk56-n83HiGOYNDrLvxoFORvxxRf9-EftI-nj33jnec8JkLzyXjfHLtCaHlQ3zT6ncJlX0j_nFv4uPYFgsdfhzwZ1mOH-f0LAO9bdtW07IvLQj8uzpkfyYOoy3ZG0TUfsgrHwrUX-yc9oxV_7vmdI9VeoGhGxkejDDP7QdSV3CtKCCDqLS_ex4qQI-UIWN6P1mcsxwmihbEKFRQzbUipSvpTsJ5u-d-X7haV7weiOOLOy7ht-DsUzp-VNTq78wnf1qtrc3yo5JT4SdcF_AU36Whw9bZUdkYHMXoUDTgLnv4qIOwG6El-tFWvpO6SMBeILTSnosGxH8oNw9AQgfikStI1O6S5ywdNY_hiI7Hi0DNkg7M60CAq0ZH7S0P8mMEg1gnCrBG3HHdrRr4nIvvDWa5ijfaTCjMChegle_2E20zPQWYR7OdIpHg: 403 The download quota for this file has been exceeded

**Comment by metrizable** [comment]
@vainaixr Since this issue was filed a while ago, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
