### ISSUE TITLE
git lfs is not working

### ISSUE THREAD

**Issue by mainak555** [googlecolab/colabtools#586]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
!git lfs clone
!git lfs install

are not working
- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
![image](https://user-images.githubusercontent.com/26775546/59209703-94a46580-8bc9-11e9-97d0-6480b8bcf38d.png)

**Comment by arjitkatare** [comment]
Run 
Try updating your git version -
```
apt-get update && apt-get upgrade
```
and then use - 
```
git clone ...
```
