### ISSUE TITLE
Image widget causes disconnect

### ISSUE THREAD

**Issue by blois** [googlecolab/colabtools#587]
See minimal repro in https://github.com/googlecolab/colabtools/issues/60#issuecomment-500236316

Image uses binary comm messages which Colab does not currently support. The binary format does not appear to be documented in https://jupyter-client.readthedocs.io/en/latest/messaging.html#messages-on-the-iopub-pub-sub-channel.

The original Jupyter PR which added support for this is https://github.com/jupyter/notebook/commit/3693ac83aece47f402ddbcc279814e74df09fda9.

b/123539401

**Comment by filmackay** [comment]
@blois any view on how this might be viewed priority-wise? I think `ipywidgets` are hard to use without this support..

**Comment by blois** [comment]
It's currently relatively low priority- this is currently the only feature which is using the binary wire format.

Can you explain how you are running into this? Is it just trying to display an image?

**Comment by filmackay** [comment]
> Can you explain how you are running into this? Is it just trying to display an image?

Yeah, it's as simple as that. If you're building up `ipywidgets` in any kind of structure - you really want to include `ipywidgets.Image` in the structure, usually. In my case, generated from `pygraphviz` - which I only recently got to work in colab.

**Comment by jasongrout** [comment]
The binary messages use the `buffers` attribute of comm messages: https://jupyter-client.readthedocs.io/en/stable/messaging.html#general-message-format

I think you are right that the notebook websocket binary message format is not documented (but should be!). The jlab code for deserializing these messages is at https://github.com/jupyterlab/jupyterlab/blob/master/packages/services/src/kernel/serialize.ts

**Comment by jasongrout** [comment]
Note that a workaround for using the image widget is using an output widget with a display command to display the image.

**Comment by jasongrout** [comment]
> Image uses binary comm messages which Colab does not currently support. The binary format does not appear to be documented in https://jupyter-client.readthedocs.io/en/latest/messaging.html#messages-on-the-iopub-pub-sub-channel.

Note that the serialization we are talking about here is not the wire format from the kernel (which those docs are documenting), but instead the wire format of websocket messages from the notebook server. So the docs that we need to write for the websocket binary format would be in the notebook documentation.

**Comment by blois** [comment]
Thanks Jason- Colab uses the standard wire format but it passes through a couple of layers. I don't think the docs are a blocker, we just have a number of places that need to be updated for this.

An example of Jason's IPython.display.Image workaround- https://colab.research.google.com/gist/blois/7054e1a8b4ac05d6c45ae0687b9f3c45/image-widgets.ipynb

**Comment by jasongrout** [comment]
Nice work on getting output widgets working!
