### ISSUE TITLE
autoscroll output

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#589]
is it possible to add autoscroll to the bottom of output by default, just like in terminal?

currently, it needs to be done manually in google colab by using the scroll bar.

**Comment by blois** [comment]
Thanks for the request- outputs should now be auto-scrolling to the end.

**Comment by mkolodny** [comment]
@blois Auto-scrolling to the end out the output is usually what I want, but sometimes it's not. How can I disable auto-scrolling?

**Comment by blois** [comment]
Do you not want auto-scrolling, or no scrollbars at all?

Here's an example of disabling scrolling:
```python
from IPython.display import HTML, Javascript
# Disable vertical scrolling by setting a massive max-height
display(Javascript('google.colab.output.setIframeHeight(-1, true, {maxHeight: 100000})'))

# Display some large content
display(HTML('''
<style>
  .placeholder {
    height: 2000px;
    background: repeating-linear-gradient(45deg, #606dbc, #606dbc 10px, #465298 10px, #465298 20px);
  }
</style>
<div class="placeholder">Some content</div>
'''))
```
