### ISSUE TITLE
Add vim plugin support

### ISSUE THREAD

**Issue by sirotenko** [googlecolab/colabtools#59]
This is a feature request following [this SO question](https://stackoverflow.com/questions/48674326/is-there-a-way-to-use-vim-plugin-in-colaboratory/).
A significant part of jupyter notebook users prefer [vim bindings](https://github.com/lambdalisue/jupyter-vim-binding) inside cells. Both jupyter notebook and jupyter lab has such plugins.
Would be great to have one for colab.

**Comment by captainvera** [comment]
Yes please, this is the one thing preventing me from using colab full-time instead of Jupyter

**Comment by sirotenko** [comment]
Note that there is a nice hack to enable vim support suggested: https://stackoverflow.com/a/48913909/460436
Given that its one line thing hopefully it won't be that hard to integrate it eventually

**Comment by thomcom** [comment]
I want to use colab exclusively, but if Jupyter supports vim and colab never gets it I'll have to switch. :(

**Comment by thomcom** [comment]
Brain storming my own comments. Surely there's an event emitted whenever a user clicks on a Jupyter code window? The script from the above SO question can be modified instead to just add a listener for that event and enable vimMode any time the cell is clicked. Sounds like a good job for a Chrome plugin.

**Comment by thomcom** [comment]
I created autovim to solve this problem: https://chrome.google.com/webstore/detail/licohjbphilmljmjonhiifkldfahnmja/publish-accepted?authUser=0&hl=en-US

**Comment by reddragon** [comment]
It will be great to have native support in the Colab code cell editor for this.

**Comment by colaboratory-team** [comment]
b/111772024

**Comment by WorksWellWithOthers** [comment]
Dropped by to say I'm really loving Colaboratory.
Vim support would be great!

**Comment by katlyn-edwards** [comment]
You should now be able to enable Vim keybindings by opting into the new editor.
Some more information: 
https://colab.research.google.com/notebooks/editor_details.ipynb 

We'll be updating that notebook soon to mention Vim keybindings, but it should be an option along with "Classic" under Preferences.

**Comment by WorksWellWithOthers** [comment]
This is great!
