### ISSUE TITLE
Google Drive timeout

### ISSUE THREAD

**Issue by VomDorfe** [googlecolab/colabtools#595]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

Description:
As the titel discribes, I got a timeout Error. My code was running fine yesterday and I haven't change anything since then. Just got crashed over night.

I searched all topics with the same problem and tried all solutions:
- i reseted all runtimes
- i have only one folder in "My Drive", the last folder is pretty large with around 80.000 (Image)-files
- my trash is completly empty

- The web browser you are using (Chrome, Firefox, Safari, etc.):
 Chrom Version: 75.0.3770.80

**Comment by vibhusehra** [comment]
I'm facing the same problem
