### ISSUE TITLE
multiple ngork sessions listening / tunneling on same port

### ISSUE THREAD

**Issue by sathish297** [googlecolab/colabtools#596]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Running a python3 note in colab 
Running below creates multiple although port 6006 can be tunnelled only once!!!

_`!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip ngrok-stable-linux-amd64.zip

LOG_DIR = '/tmp/retrain_logs/train'
get_ipython().system_raw(
    'tensorboard --logdir {} --host 0.0.0.0 --port 6006 &'
    .format(LOG_DIR)
)
get_ipython().system_raw('./ngrok http 6006 &')
`

`root        3963       1  0 22:15 ?        00:00:02 /usr/bin/python2 /usr/local/bin/tensorboard --logdir /tmp/retrain_logs/train --host 0.0.0.0 --port 6006
root        3973       1  0 22:15 ?        00:00:02 ./ngrok http 6006
root        5237       1  0 22:25 ?        00:00:00 ./ngrok http 6006
`

- Describe the expected behavior:

It should only be possible to create one process. It is not possible to listen on port by more than one process (pid).

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome
Version 74.0.3729.169 (Official Build) (64-bit)

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1ESUPfaOijssPrKAiYE_74ATYwW_BaN3Q

**Comment by wchargin** [comment]
TensorBoard has built-in support for running in Colab; you don’t need to
use ngrok at all anymore. You can just write:

```
%load_ext tensorboard  # only needed once per notebook
%tensorboard --logdir {LOG_DIR}
```

to see the TensorBoard instance inline in the notebook.

This functionality is included in TensorFlow 1.14 and later.

For details, please see:
<https://www.tensorflow.org/tensorboard/r2/tensorboard_in_notebooks>

(Disclaimer: I work on TensorBoard.)
