### ISSUE TITLE
tpu suspected of causing excessive storage (gcs) billing

### ISSUE THREAD

**Issue by ekim38** [googlecolab/colabtools#597]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
free access to tpu is great, but i think its causing excessive billing inadvertently. i have hundreds of dollars of billing charges because my bucket which resides in US was accessed from EU and APAC. i wonder if it is because i ended up getting a tpu in those regions which accessed my US bucket.

- Describe the expected behavior:
any way of preventing this would work. it would be nice if i can specify multiple buckets one per each region (or gcs starts offering global buckets that spans all regions). alternatively, i would like to limit my tpu placement within one region of choice.

- The web browser you are using (Chrome, Firefox, Safari, etc.): N/A

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by colaboratory-team** [comment]
All Colab TPU instances in 2019 have been in US zones so any EU/APAC accesses must be coming from something else.
(note non-TPU colab instances do indeed exist in other geographies)

**Comment by ekim38** [comment]
thank you for quick response. is there a way to find out if my non-tpu instance is in other region? I'm currently trying to use ip to find out.

**Comment by colaboratory-team** [comment]
Colab VMs don't expose their location information, sorry.

**Comment by Mistobaan** [comment]
@colaboratory-team Is this still the case one year later? also with the PRO version? TPUs data retrieval can suffer a bit from non-same-zone bucket.

**Comment by kento-kobayashi** [comment]
@colaboratory-team Is this still the case two year later? also with the PRO version? TPUs data retrieval can suffer a bit from non-same-zone bucket.

**Comment by chavinlo** [comment]
@colaboratory-team Is this still the case four years later? also with the PRO version? TPUs data retrieval can suffer a bit from non-same-zone bucket.

**Comment by eselimnl** [comment]
@colaboratory-team Is this still the case five years later? also with the PRO version? TPUs data retrieval can suffer a bit from non-same-zone bucket.
