### ISSUE TITLE
Add support for comms messages

### ISSUE THREAD

**Issue by korakot** [googlecolab/colabtools#6]
Some tasks need interactions between JS frontend and python backend.
Please add support for IPython.notebook.kernel.execute(python_code)

Also, some modules like ipyleaflet, bqplot, and other Jupyter Widgets don't work without them.

**Comment by blois** [comment]
There are a couple of separate issues here-

**IPython.notebook.kernel.execute**: for security concerns, Colab does not allow execution of aritrary python code from Javascript. Rather, Javascript will be able to invoke specific Python callbacks. The callback must be registered from Python using the google.colab.output.register_callback method: https://github.com/googlecolab/colabtools/blob/master/google/colab/output/_js.py#L45. This has not yet rolled out into production:

```python
import google.colab.output

def DoSomething(a, b, c=0):
  return "a=%d b=%d c=%d" % (a, b, c)

google.colab.output.register_callback('DoSomething', DoSomething)
```

Once the python callback is registered, Javascript from an output which has executed within the current session can call google.colab.kernel.invokeFunction:

```javascript
const result = await google.colab.kernel.invokeFunction('DoSomething', [1, 2], {c: 3})
```

**Comms**: currently as you noted Comms are not supported in Colab. One important distinction is that in Colab, each cell's output is in it's own iframe and all user-controlled code is executed in those iframes. We could broadcast these messages to each iframe, but in the case of something like Jupyter Widgets, it's not typically expecting multiple instances of the widget manager running on the page.

I'd still like to see what level of trickery we could add to get some level of compatibility here, but I'm pretty sure it's going to involve a good deal more work than just plumbing through the comms messages.

**Comment by korakot** [comment]
I’m satisfied with google.colab.kernel.invokeFunction

I only need a way to interact with output cell and make change to python variables. This suffices for my need. Thanks.

So, it will roll out to production sometime soon, right? At that time, please make a simple example, e.g. click a button to do something, or allow drawing on canvas and send the image to python.

Really appriciate Colab.

**Comment by blois** [comment]
Yes, it should roll out shortly after the holidays.

FWIW, the frontend code is already available and you can patch in the Python code via:

```python
from google.colab.output import _js as __js_239
import json

functions = {}

def register_callback(name, function):
  functions[name] = function

def invoke_function(name, args_json, kwargs_json):
  args = json.loads(args_json)
  kwargs = json.loads(kwargs_json)
  return functions[name](*args, **kwargs)
 
__js_239.register_callback = register_callback
__js_239._invoke_function = invoke_function
```

**Comment by blois** [comment]
`google.colab.kernel.invokeFunction` is now available, a notebook showing how to use it (and a bit more):
https://colab.research.google.com/notebook#fileId=1sYg2maTOT3GrCGS7R7WSxJcM3RsHjHAH

**Comment by korakot** [comment]
The last example "Persisting Updates" does not work with Python 3.

BTW, how do I change the output of other cells? The last example show how to use `output.redirect_to_element` to change an element within the current cell. But I may want to call many python codes from different cells but want all the output to redirect to the first output cell. Maybe something like a dashboard where you try different python commands, but on the same output.

**Comment by korakot** [comment]
I try to create a simple button example, but it's not working.
`HTML('''
<script>
function update(){
  result = google.colab.kernel.invokeFunction('hello',[],{});
  return result.data['application/json'].result
}
</script>
<button onclick="this.innerText=update()">update</button>
''')`

I may use promise incorrectly. Can you explain more? Do I need to use async and await?

**Comment by blois** [comment]
I opened https://github.com/googlecolab/colabtools/issues/18 for the Python 3 issue in the last cell.

Also opened https://github.com/googlecolab/colabtools/issues/19 to track allowing communication between outputframes. The technique with this API would be to send a message from one output to another output then invokeFunction from the output which is to be modified by the kernel.

**Comment by oeway** [comment]
@blois 
Would it be possible to support invoking functions defined in JS from Python? I know that we can do `eval_js` to get around, however, I think for real-time communication (as supported by comms message) there is a big overhead. 

I think it would be great if the same API can be supported the other way around. What do you think?

**Comment by blois** [comment]
@oeway 
`eval_js` has a second argument- `ignore_result` that when set to true will not block the Python code waiting for the result. Otherwise there should not be significant overhead between `eval_js` and comms messages- they are all JSON messages delivered over the same IPython iopub channel.

**Comment by oeway** [comment]
hi, thanks for the quick response. Good to know that the waiting can be
disabled with ignore_results.

Can IPython iopub support binary data? I think there are still overheads on
the encoding data to string, parsing the js code, decoding the string etc.
imagine sending binary data, for example a high resolution image, we will
need base64 etc. Don’t you think it will be more straightforward if support
invokeFunction in Python?

**Comment by blois** [comment]
IPython iopub does support it but Colab does not at this time- https://github.com/googlecolab/colabtools/issues/587.
