### ISSUE TITLE
Add Ipywidgets support 

### ISSUE THREAD

**Issue by joseFranciscoDiez** [googlecolab/colabtools#60]
Widgets are the most widespread way to provide interactivity with the user in Jupyter notebooks.

Google Colab should support ipywidgets or provide an alternative.

Ref https://stackoverflow.com/questions/47269168/ipywidgets-with-google-colaboratory

**Comment by blois** [comment]
Also see https://github.com/googlecolab/colabtools/issues/6

**Comment by KelSolaar** [comment]
Hi,

As many I'm super interested by that feature support and wanted to know if there was any news about it?

Cheers,

Thomas

**Comment by KelSolaar** [comment]
@blois : Yes absolutely :)

Here is a typical example I would be keen on running in Google Colab:

![image](https://user-images.githubusercontent.com/99779/40678204-fb29308e-63d3-11e8-8b21-7ed1a470006c.png)

Widgets used: `Box, Dropdown, HBox, IntSlider, Label, Textarea, VBox`

You can play live with it in Binder if you can bear with the slow startup time (just need to execute the cells): https://mybinder.org/v2/gh/colour-science/colour-playground/master?filepath=playground%2Fcolour.ipynb

**Comment by chengs** [comment]
@blois, also, some ``tqdm`` (a progress bar) users need to run the tqdm on CoLab, which needs ipywidgets to work.
REF https://github.com/tqdm/tqdm/issues/558

**Comment by mdmadhu** [comment]
@blois, [ipyleaflet](https://github.com/jupyter-widgets/ipyleaflet) is another widget that would be very useful to see in Colab. Colab notebooks would be a great way forward for Python users of Google Earth Engine to collaborate, and here, ipyleaflet in Jupyter notebooks is currently among the recommended/favoured options for visualising tiled maps created from analyses. There are workarounds, but support for ipywidgets would be great. Thanks.

**Comment by KelSolaar** [comment]
Adding [pythreejs](https://github.com/jupyter-widgets/pythreejs) to the bunch!

**Comment by maartenbreddels** [comment]
As a core jupyter-widgets / ipywidget dev I want to let you know we are interested in support on colab. Feel free to reach out to us for help or discussion in care you need help:
 * https://github.com/jupyter-widgets/ipywidgets/
 * https://gitter.im/jupyter-widgets/Lobby

cc @jasongrout @SylvainCorlay @vidartf @mwcraig

**Comment by Yomguithereal** [comment]
Adding [ipysigma](https://github.com/Yomguithereal/ipysigma) to the bunch.

**Comment by tovrstra** [comment]
Some more:
- https://github.com/arose/nglview
- https://github.com/Autodesk/notebook-molecular-visualization

**Comment by mwcraig** [comment]
I'd also like to see [ipyevents](https://github.com/mwcraig/ipyevents) in the mix...I am a little biased, though, since I wrote it. But including ipyevents would also allow [astrowidgets](https://github.com/astropy/astrowidgets).

**Comment by thewtex** [comment]
Adding [`itk-jupyter-widgets`](https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets), interactive Jupyter widgets to visualize images in 2D and 3D, as another example in the vibrant ipywidgets ecosystem that would be helpful for colab adoption.

**Comment by perez1987** [comment]
+1

**Comment by maallen3** [comment]
I need this too!

**Comment by DuaneNielsen** [comment]
I'd just like tqdm progress bars to work nicely, that would be good...

**Comment by d13g0** [comment]
Me too!

**Comment by diego898** [comment]
Another vote for supporting tqdm!

**Comment by chengs** [comment]
@diego888
See this https://github.com/tqdm/tqdm/pull/640

If need to use tqdm on colab

**Comment by smilinrobin** [comment]
+1
Need this :)

**Comment by wesleyugang** [comment]
+1

**Comment by chrisbol** [comment]
+1, would be great if Slider, Checkbox, Combo, Select widgets will become available

**Comment by aleksas** [comment]
+1

**Comment by nathanmargaglio** [comment]
+1

**Comment by blois** [comment]
@chrisbol - the basic slider/checkbox/combo widgets should now be working. There are a couple of limitations and rough edges but it's worth a try.

We appreciate all of the interest and will continue to work on improvements in this area.

Please feel free to open bugs on issues and we'll see what we can do to unblock.

**Comment by treygreer** [comment]
@blois Super happy you folks are working on ipywidgets!  How do I try it out?

**Comment by treygreer** [comment]
@blois Oh, I just had to close and re-open my notebook.

**Comment by sibyjackgrove** [comment]
I tried Ipywidgets and I am able to get the slider. But no output is displayed when I move the slider. Please see my screenshot below. Do I need to do anything other than import the module?

![image](https://user-images.githubusercontent.com/25213730/52595282-22866480-2e13-11e9-8142-e7d259398305.png)

**Comment by blois** [comment]
Right now the contents of output widgets are not being displayed. It's being used by `@interact`.

The output widget itself is fairly complicated in how it routes messages, we're evaluating how best to handle it.

**Comment by pnlph** [comment]
This is still not working:
```
import ipywidgets as w
w.Button()
```
IPKernelApp] WARNING | Widget Javascript not detected. It may not be installed or enabled properly

**Comment by pnlph** [comment]
Another scenario would be [visualizing a list of 2D images with Menpo](https://www.menpo.org/menpo/visualization.html#images). It keeps showing the IPKernelApp error with Colab:
```
%matplotlib inline
import menpo.io as mio
from menpowidgets import visualize_images
images = list(mio.import_images('/path/to/images/'))
visualize_images(images)
```

**Comment by blois** [comment]
Currently Colab only supports the ipywidgets widgets, see https://github.com/googlecolab/colabtools/issues/498.

The warning 'Widget Javascript not detected'- do you know what version of ipywidgets is installed?

https://colab.sandbox.google.com/gist/blois/249a58c98f8f3a2ce672dc9a1c03228c/widgets.ipynb

**Comment by pnlph** [comment]
OK, it works now, thank you. Any suggestion on how to preview a list of images in an usable way?

**Comment by cornhundred** [comment]
On a related note, widgets are supported on kaggle, but cannot be embedded into HTML notebooks currently. https://github.com/jupyter-widgets/ipywidgets/issues/2360#issuecomment-480401010

**Comment by blois** [comment]
I'm working on rendering output widgets right now, otherwise there are two other open widgets issues:
Support custom widgets: https://github.com/googlecolab/colabtools/issues/498
Persist widgets during notebook save: https://github.com/googlecolab/colabtools/issues/516

**Comment by mforbes** [comment]
There is an issue with the `Image()` widget which hangs when the comm is opened.

Minimal non-working example:

```python
import ipywidgets
ipywidgets.Image()
```

(No data is provided, so a broken image icon should be shown.  Instead, the runtime just hangs.)

More complete non-working example:

```python
import ipywidgets
import numpy as np
from matplotlib import cm
import PIL.Image
data = cm.viridis(np.random.random((32,32)), bytes=True)
img = PIL.Image.fromarray(data)
ipywidgets.Image(value=img._repr_png_(), format='png')
```

Images do work - they can be captured for example with the `Output()` widget:

```python
import ipywidgets
import numpy as np
from matplotlib import cm
import PIL.Image
data = cm.viridis(np.random.random((32,32)), bytes=True)
img = PIL.Image.fromarray(data)
out = ipywidgets.Output()
display(out)
with out:
    display(img)
```

**Comment by mforbes** [comment]
Also, the `Label` widget does not display values properly:

```python
import ipywidgets
ipywidgets.Label(value="Hi")
```

**Comment by blois** [comment]
The fix for the Label widget not displaying is now live. Thanks for the report.

**Comment by thwee-alchemist** [comment]
Since noone has mentioned it yet, could we get pythreejs support?

**Comment by zirlman** [comment]
[Variable inspector](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/varInspector) would be really useful to have in Colab. Please add support for it

**Comment by caladd** [comment]
Supporting `ipyturtle` would be a great for school classrooms and parents (like me) teaching their kids python.

I got the module installed via pip with no issues, but enabling it fails:
```
!jupyter nbextension enable /usr/local/lib/python3.6/dist-packages/ipyturtle
```
Output:
```
Enabling notebook extension /usr/local/lib/python3.6/dist-packages/ipyturtle...
      - Validating: problems found:
        - require?  X /usr/local/lib/python3.6/dist-packages/ipyturtle
```

**Comment by DrSosh** [comment]
Support for <keplergl> would be great: 

https://github.com/keplergl/kepler.gl/blob/master/docs/keplergl-jupyter/user-guide.md

The widget installs fine with <pip install>, but the map doesn't render, and no error is generated.

**Comment by babash** [comment]
There are anyway to use FigureWidget on collab ? 
A support for it would be great.
From my side the widget is never display but no error appear the notebook is just disconnected momentarily.

https://plot.ly/python/figurewidget/

**Comment by Cerebrock** [comment]
+1

**Comment by korakot** [comment]
[Qgrid](https://github.com/quantopian/qgrid) is very useful for editing a dataframe.

DataTable is already helpful for exploring and filtering. But dataframe manipulation will be even better.

**Comment by yingxiaoGuo** [comment]
pls add jupyter-notify
it's very very useful to monitor the running status of cells
https://github.com/ShopRunner/jupyter-notify

**Comment by sriyogesh94** [comment]
Please support nbgrader, as that would make my job as a teacher so much more easier!

**Comment by gingertosser** [comment]
There is an issue when trying to use the "SelectMultiple" widget on Colab because any ctrl-click event selects the entire cell and blocks the interact control.  Options are highlighted but not passed through.
Single selection and shift-select works, just not ctrl-select.

**Comment by cornhundred** [comment]
Hi @blois, would we be able to get support for our widget Clustergrammer2 (https://github.com/ismms-himc/clustergrammer2) ? It is primarily designed for single-cell high-dimensional data exploration, but also works as a general purpose WebGL Pandas DataFrame explorer 

see https://clustergrammer.readthedocs.io/

Pip installation works but I'm seeing the following error in the console 
<img width="538" alt="Screen Shot 2020-02-06 at 1 56 32 PM" src="https://user-images.githubusercontent.com/8352840/73969268-17142f00-48e9-11ea-82c7-f5dfa28213a4.png">

**Comment by giswqs** [comment]
> @blois, [ipyleaflet](https://github.com/jupyter-widgets/ipyleaflet) is another widget that would be very useful to see in Colab. Colab notebooks would be a great way forward for Python users of Google Earth Engine to collaborate, and here, ipyleaflet in Jupyter notebooks is currently among the recommended/favoured options for visualising tiled maps created from analyses. There are workarounds, but support for ipywidgets would be great. Thanks.

@blois Please add support for  [ipyleaflet](https://github.com/jupyter-widgets/ipyleaflet), which would make visualizing and interacting Google Earth Engine tile layers much easier with the [earthengine-api](https://github.com/google/earthengine-api). @tylere  @davidbrochart @chrieke

**Comment by Thomseeen** [comment]
Is it possible to add support for `open3d` [JVisualizer](http://www.open3d.org/docs/release/tutorial/Basic/jupyter.html)? Would be quiet useful to easily show 3d-data although `JVisualizer` is still in the experimental phase. At the moment Firefox's dev-tools console just shows  `Error has occurred while trying to update output. Error: "Widgets module open3d is not supported"` while the cell's output stays empty when trying to use it.

**Comment by ybressler** [comment]
Icons for buttons are not rendered in colab. I'd love to see this supported.

**An empty button is showed for the following code:**
```
my_button = widgets.Button(icon="home")
display(my_button)
```

**Comment by blois** [comment]
Opened https://github.com/googlecolab/colabtools/issues/1302

**Comment by barissayil** [comment]
I'd like to be able to use tqdm on colab as well.

**Comment by blois** [comment]
@barissayil tqdm notebook should work in Colab: https://colab.research.google.com/gist/blois/0edb04e592c16cbab8f0f9b1cff3595e/tqdm_notebook.ipynb

**Comment by adriangb** [comment]
It would be amazing to get support for third party widgets!

**Comment by omar-3** [comment]
is there any hope for ipyleaflet to be included?

**Comment by jph00** [comment]
@blois it appears this has been implemented now - should this issue be closed?

**Comment by blois** [comment]
@jph00 yes, most of the issues now fall under https://github.com/googlecolab/colabtools/issues/498.

**Comment by Erhannis** [comment]
I'm having trouble with the Play widget.  The buttons don't show their icons, and button presses do not trigger any notable reaction.
Test case: https://colab.research.google.com/drive/1WE2pV0UfgRb0cfOVdCkgo7MzwCkLBdDV#scrollTo=Y8eS_TugFa6i
Note that the same code on a local Jupyter instance works properly; the four buttons have icons, and pressing the play button causes the slider to advance and the output to output, every 2 seconds.

**Comment by AJAX6255** [comment]
Erhannis:
Yes, I ran your code in colab and had the same (poor) results. I then ran
the same code cell in Kaggle and it worked!
Same version of ipywidgets 7.5.1. Perhaps a dependency issue?
🤔

**Comment by Erhannis** [comment]
Maybe so; not sure how I'd know, really.

**Comment by AJAX6255** [comment]
If you type the following command in both environments (working and not
working), you will get a list of the installed software and its version
number.

!pip list

Then you compare (yes it is tedious) the differences in the software
release numbers.
Lastly if there is a software package in the working environment that is
NOT present in the non-working environment, then that MAY likely be the
issue.
I will try this too but I encourage you to try it.
Then I may save it and run a "diff" to try and make it easier.
(more automatic).
It may turn out to be an older version of ipython being run in colab?

**Comment by AJAX6255** [comment]
Here is an interesting reference that may help.
https://colab.research.google.com/notebooks/widgets.ipynb

**Comment by blois** [comment]
@Erhannis this sounds like https://github.com/googlecolab/colabtools/issues/1302

**Comment by Erhannis** [comment]
@blois That does appear to account for the icon problem, at least; thanks.  Unfortunately, while the workaround fixes the icons, the widget remains non-functional.

@AJAX6255 Well, I've gotten a `!pip list` from colab and from a jupyter labs workspace, now:
[colab_pip.txt](https://github.com/googlecolab/colabtools/files/5300771/colab_pip.txt)
[jupyter_pip.txt](https://github.com/googlecolab/colabtools/files/5300772/jupyter_pip.txt)

As per your note, I see that the ipython version for colab is 5.5.0, vs. jupyter labs' 7.16.1.
I also note ipykernel v 4.10.1 vs 5.1.4, though I don't really know what is and isn't relevant.
The jupyter-client versions are different, and there are a few differences in exactly which jupyter-related packages are installed.
The versions of ipywidgets appear to be the same.

**Comment by AJAX6255** [comment]
@Erhannis I updated my colab ipython to 7.16.1 (not recommended by colab)
from 5.5.0 and it did not resolve the issue. Hmm..

**Comment by blois** [comment]
@Erhannis this looks like it may be an issue with jslink- I just opened https://github.com/googlecolab/colabtools/is.

**Comment by Erhannis** [comment]
Oh! @blois , you were right!  jslink doesn't work - but the play widget does, actually!  This means that while you can't bind two `value`s together like in the docs, you _can_ do the following:

```
def value_changed(change):
  print(change.new)
play.observe(value_changed,'value')
```

It's probably tricky to keep two objects in sync like this, without getting e.g. infinite recursion, but for what I wanted to do I only needed a unidirectional link, anyway.  Thanks!

**Comment by maartenbreddels** [comment]
A good workaround might be link or dlink instead, that goes via the kernel, similar to observe.

**Comment by Erhannis** [comment]
@maartenbreddels Oh, you mean when observe fires it triggers/requires communication with the server?  That might explain why using a different computer in my house causes my hacky "animation" to run much slower than when it's localhost, haha

**Comment by maartenbreddels** [comment]
Yes, since it executes Python code, which lives at the server. That's why jslink (which is handled in the browser) usually gives smoother results (but it cannot execute code).
