### ISSUE TITLE
Colab authentication is not compatible with tensorflow 2.0.0

### ISSUE THREAD

**Issue by ssable** [googlecolab/colabtools#602]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Following code to authenticate in notebook with tensorflow is crashing:
!pip install -q tensorflow==2.0.0-beta1
from google.colab import auth
auth.authenticate_user()

AttributeError Traceback (most recent call last)
in ()
25
26 from google.colab import auth
---> 27 auth.authenticate_user()
28
29 prepared_record_paths = tf.io.gfile.glob(training_data)

/usr/local/lib/python3.6/dist-packages/google/colab/auth.py in authenticate_user(clear_output)
154 with tf.compat.v1.Session('grpc://{}'.format(colab_tpu_addr)) as sess:
155 with open(_get_adc_path()) as auth_info:
--> 156 tf.contrib.cloud.configure_gcs(
157 sess, credentials=_json.load(auth_info))
158 if _check_adc():

AttributeError: module 'tensorflow' has no attribute 'contrib'

- Describe the expected behavior:
I expect previous code not to crash.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

!pip install -q tensorflow==2.0.0-beta1
from google.colab import auth
auth.authenticate_user()

**Comment by craigcitro** [comment]
Thanks for the report!

You can set `os.environ['COLAB_SKIP_TPU_AUTH'] = '1'` to skip the failing code. However, note that you're still likely to hit trouble with TPUs + TF2.

**Comment by craigcitro** [comment]
b/135524562

**Comment by ssable** [comment]
Thanks for your feedback.
I tried to use tf2 because I had troubles with TPUs and tensorflow 1.14.1-rc1 that was deployed recently in Colab.
So apparently there is no stable TPU solution in Colab at the moment :(

**Comment by yongtang** [comment]
Some background about the above mentioned error:

1) As part of tensorflow modularization, `tf.contrib` has been removed from tensorflow core repo.
2) `tf.contrib.cloud.configure_gcs` (called from  `google/colab/auth.py`)  now lives in tensorflow/io, from the PR https://github.com/tensorflow/io/pull/339 by @rjpower

/cc @rjpower

**Comment by suresh88** [comment]
How to run the BERT [notebook](https://colab.research.google.com/github/tensorflow/tpu/blob/master/tools/colab/bert_finetuning_with_cloud_tpus.ipynb) if we cannot authenticate with google storage using TF2.X in colab. Is there any work around for this? 

I am facing module 'tensorflow' has no attribute 'contrib' error.

**Comment by rjpower** [comment]
This functionality is now part of a separate library: https://pypi.org/project/tensorflow-gcs-config/ . It should work for TF 2.1, though it may need to be rebuilt for TF 2.2. There seems to be an example for this here:

https://github.com/googlecolab/colabtools/issues/934

@craigcitro can we ping the Cloud TPU team about updating the notebook in question?

**Comment by knightperfectionist** [comment]
> How to run the BERT [notebook](https://colab.research.google.com/github/tensorflow/tpu/blob/master/tools/colab/bert_finetuning_with_cloud_tpus.ipynb) if we cannot authenticate with google storage using TF2.X in colab. Is there any work around for this?
> 
> I am facing module 'tensorflow' has no attribute 'contrib' error.

What's the progress? Did you resolve it?

**Comment by rjpower** [comment]
That notebook itself needs to be updated (tf.contrib doesn't exist anymore).

**Comment by knightperfectionist** [comment]
Please let me know what are the necessary chages in order to run the notebook.
@rjpower
