### ISSUE TITLE
Change Directory command not working.

### ISSUE THREAD

**Issue by Nibba2018** [googlecolab/colabtools#603]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Stuck at a particular directory. Unable to change directories.

- Describe the expected behavior:
Supposed to change directory

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Firefox

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment]
I'm guessing you're using `!cd somedirname` -- note that `!` starts a subshell, where you're changing directory, and then ... closing the subshell, only to start over next time.

Use `%cd` to persistently change directories. See [this SO question](https://stackoverflow.com/questions/36512527/cd-vs-cd-vs-cd-in-ipython) for more info.
