### ISSUE TITLE
cannot create a new Python notebook

### ISSUE THREAD

**Issue by pedroveloso13** [googlecolab/colabtools#61]
I cannot create a new notebook. Here is the error: 
![screen](https://user-images.githubusercontent.com/10541007/36266030-919531ae-123e-11e8-90dd-fa8b0599d081.jpg)

**Comment by blois** [comment]
Can you try using an incognito window? From the error, it looks like a Chrome extension is causing errors, specifically the StayFocused extension: https://chrome.google.com/webstore/detail/stayfocusd/laankejkbhbdhmipfmgcngdelahlfoji.

Or try disabling this extension.

**Comment by pedroveloso13** [comment]
I deactivated StayFocused and used an incognito window. Now I have another error:
![screen_incognito](https://user-images.githubusercontent.com/10541007/36278520-1fc336b0-1262-11e8-9788-91461dbb3fd6.jpg)

**Comment by pedroveloso13** [comment]
I deactivated StayFocused and used an incognito window. Now I have another error:

![screen_incognito](https://user-images.githubusercontent.com/10541007/36278885-2d20001c-1263-11e8-99d7-ca544498812d.jpg)

**Comment by blois** [comment]
Is it possible that you have cookies disabled? See chrome://settings/content/cookies

**Comment by pedroveloso13** [comment]
No.
"Allow sites to save and read cookie data" is on 
"Block third-party cookies" is off

**Comment by blois** [comment]
The only other things I can think of are to disable all extensions and possibly try a different Google sign-in, if you have one.

The network tab may have a more specific reason for the 403 error from Drive.

**Comment by pedroveloso13** [comment]
I have two Google accounts, a regular gmail account and an account from the university that is integrated with Google. It only works If am **exclusively** logged in to my account from the university.

**Comment by pedroveloso13** [comment]
By the way, thanks for your quick replies, blois.

**Comment by blois** [comment]
We are working on multi-login support. Stay tuned!
