### ISSUE TITLE
SpaCy not working in Colab

### ISSUE THREAD

**Issue by Ayush-agar** [googlecolab/colabtools#612]
Bug report for Colab: http://colab.research.google.com/.

I'm getting this error:
OSError: [E050] Can't find model 'en_core_web_lg'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

Even though it says:
**Requirement already satisfied: en_core_web_lg==2.1.0 from https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-2.1.0/en_core_web_lg-2.1.0.tar.gz#egg=en_core_web_lg==2.1.0 in /usr/local/lib/python3.6/dist-packages (2.1.0)
✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_lg')***

When I downloaded en_core_web_lg in a cell just above that.

**Comment by alex000kim** [comment]
Don't run `!python -m spacy download en_core_web_lg` from inside jupyter.
Do this instead:
```
import spacy.cli
spacy.cli.download("en_core_web_lg")
```

**Comment by metrizable** [comment]
@Ayush-agar  Since this issue was filed a while ago, and we have had multiple package and ecosystem upgrades, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
