### ISSUE TITLE
simple %matplotlib fails in Google Colab

### ISSUE THREAD

**Issue by mg64ve** [googlecolab/colabtools#616]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

Just opened a new Python 3 notebook in Google Collab GPU and typed %matplotlib. At the execution I have got:

ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

- Describe the expected behavior:

As in this document:

https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/04.00-Introduction-To-Matplotlib.ipynb#scrollTo=sb30xayjaaWY

I should get:

Using matplotlib backend: TkAgg

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome Version 75.0.3770.100 (Official Build) (64-bit)

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

It is very reproducable, just create a new Python 3 notebook and type %matplotlib

**Comment by jakevdp** [comment]
Hello - Colab does not support non-inline backends for matplotlib (Brief explanation: your Python code runs on a remote VM, so calling tkagg-based display hooks on the remote server would not cause tkagg-based windows to open on your own computer)

To view matplotlib plots in colab, you can use ``%%matplotlib inline`` if you like, or leave it out completely, as inline matplotlib figure display is the default at startup.

**Comment by abhilashmathewsvow** [comment]
Is there any method to either zoom or have a cursor (for a matplotlib plot) in Google Colab today?
