### ISSUE TITLE
Tabbing (or ctrl+space) to auto complete path after dot-slash results in duplicate dot

### ISSUE THREAD

**Issue by arunsubk** [googlecolab/colabtools#617]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
The image below shows, how after performing a dot-dot-slash (or for that matter dot-slash) and tabbing (or ctrl+space), and then selecting the resulting auto path by pressing "Enter" results in duplicate appearance, thus turning it into dot-dot-dot-dot-slash.
![image](https://user-images.githubusercontent.com/41122193/60388216-d68b4200-9acb-11e9-9d92-e467efbb5d40.png)

- Describe the expected behavior:
After pressing Enter to select the path suggested by auto-complete, the auto-complete suggestion should "replace" and not "append" to the path entered "before" tabbing.

- The web browser you are using (Chrome, Firefox, Safari, etc.):l.
Al

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by arunsubk** [comment]
A note:
On rare occasions this issue is "not" reproducible. No logical inference can be drawn about when that is. Otherwise, most times this issue is reproducible. Furthermore, to the best of my knowledge, this behavior wasn't seen some months ago. I have been getting used to that nagging feeling of not conveniently being able to use auto-complete of paths. I hope select "Enter" is the right method? Because that is how it is in most linux based auto-complete systems.

Thanks,

**Comment by blois** [comment]
We're working on updating the editor engine and have fixed a couple of issues around path completions. Details can be found at https://colab.research.google.com/notebooks/editor_details.ipynb.
