### ISSUE TITLE
Update NVIDIA driver, mount driver libraries: optix and rtcore

### ISSUE THREAD

**Issue by robertsulej** [googlecolab/colabtools#620]
- Describe the current behavior:

OptiX 6 is a ray tracing framework capable of using RT cores for the ray tracing itself and AI-based image denoisng as well. I am working on the [Python package](https://plotoptix.rnd.team) for data visualization based on this framework. It would be great to share Colab notebooks demonstrating visualization features.

In order to have OptiX 6 running, NVIDIA driver 418.30 is required, with properly mounted new libraries libnvoptix.so.X and libnvidia-rtcore.so.X.

- Describe the expected behavior:

Driver 418 with libnvoptix.so.X and libnvidia-rtcore.so.X available in the virtual machine running the notebook. If you are using dockers then solution is straight-forward, please, see [this issue](https://github.com/NVIDIA/nvidia-docker/issues/990#issuecomment-507794935) and [discussion here](https://devtalk.nvidia.com/default/topic/1050039/optix/optix-6-0-0-inside-nvidia-docker/post/5357336/#5357336).

Hope I am not asking too much!
Robert

**Comment by craigcitro** [comment]
This is likely to happen as part of another change; we'll update this issue when it lands.

b/130182705

**Comment by robertsulej** [comment]
Hi again,

I noticed the updated drivers! And eagerly tested my ray tracing package. :)

But... it happens that OptiX 6 has an issue with Tesla T4 that can be cured with OptiX 6.5/7 and the driver updated to 435 (see discussion [here](https://devtalk.nvidia.com/default/topic/1062573/optix/optix-6-ptx-parse-error-internal-error-while-parsing-builtin-declarations/)). I know.. things are moving fast. Can I ask how often you are making such updates? What could be the timescale for 435?

Thanks!

**Comment by boulos** [comment]
Now that the newer drivers are live in prod, I've verified that I can run plotoptix (albeit a little painfully to get mono installed):

 https://colab.research.google.com/drive/1UivjLRdiUV0_ZRyAUHByvKJo1UIbxdfa#scrollTo=v0tL2j_nSz34

I'm no colab expert, so I didn't bother much with getting the "on frame end" imgplot updating thing to work correctly.

**Comment by robertsulej** [comment]
@boulos Thanks for testing! I'll have look at colab too next week.
