### ISSUE TITLE
Any folder named "checkpoints" in /content/foo folder have its contents hidden

### ISSUE THREAD

**Issue by Mr-DDDAlKilanny** [googlecolab/colabtools#621]
When I create any folder in /content, such as executing
```
!wget -q -O src.zip https://github.com/mvoelk/ssd_detectors/archive/master.zip
!unzip -q src.zip
import os
os.chdir("ssd_detectors-master")
!mkdir checkpoints
!cp ../src.zip checkpoints/
```
The file src.zip should now be copied to checkpoints. Confirm using:
`!ls checkpoints`
Shows:
`src.zip`

Now using the file explorer, Click Refresh, the folder checkpoints is now visible. Try to open it, the arrow is shown as expanded but nothing is shown inside it.

![image](https://user-images.githubusercontent.com/5459919/60583966-ab874380-9d94-11e9-806c-76d2b183c319.png)

Using:
Windows 10, Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by craigcitro** [comment]
Yep, this looks like a bad interaction with jupyter's checkpoint mechanism:
  https://github.com/ipython/ipython/wiki/IPEP-15:-Autosaving-the-IPython-Notebook

I don't have a quick answer for you beyond "use a different directory name". 😞 

b/136659627

**Comment by atmaranto** [comment]
I've been using a workaround other than renaming when it would be inconvenient (such as a git repository that has the "checkpoints" directory). Using a `symlink` typically seems to be sufficient to get around the bug, both for the "checkpoints" directory itself and for subdirectories. I just thought I'd put this here for anyone looking for an alternative fix to renaming the directory.

```python
if not os.path.exists("proxy"):
  os.symlink("checkpoints", "proxy")
```

**Comment by josephrocca** [comment]
@craigcitro Surely it would at least be worth adding a line of code that warns users when they create a folder called "checkpoint", since that folder name is so common in ML?

**Comment by craigcitro** [comment]
This should be fixed!
