### ISSUE TITLE
tf.enable_eager_execution must be called at program startup.

### ISSUE THREAD

**Issue by AND2797** [googlecolab/colabtools#622]
Running `tf.enable_eager_execution()` with or without GPU produces the error `tf.enable_eager_execution must be called at program startup.` 
I have seen that this issue has also been highlighted before, but from what I understood if we use a 
`None` or `TPU` runtime type then this error should not pop, but it is still occurring.  Tried applying the fixes mentioned in other issues but they did not work.

reproducible code -
`import tensorflow as tf`
`tf.enable_eager_execution()`

https://colab.research.google.com/drive/17UUwoqv3Npjz8hMbfcPfhREXkim2B5vo

Link to the notebook where I am using `tf.enable_eager_execution()`

tf  version `1.14.0`

**Comment by craigcitro** [comment]
As suggested by the error message, this must happen before any TF code is executed. In the attached notebook, there's a whole cell of keras model fitting before calling `enable_eager_execution`.
