### ISSUE TITLE
holoviews / bokeh combination for dynamic map doesnt produce results

### ISSUE THREAD

**Issue by harsshal** [googlecolab/colabtools#623]
I am able to get Bokeh working. I can also plot interactive graphs.

When using DynamicMap in Cell 3, I am expecting second window (Under Title 'No Selection') to show selection from first window. I am able to get that to work in local notebook, but not in Google Colab.

I am using chrome, Version 72.0.3626.119 (Official Build) (64-bit).

https://colab.research.google.com/drive/1dlH-wvT2LhaXUZbcGQfXRpvHcxofAJxk

**Comment by korakot** [comment]
You need to set

    %env HV_DOC_HTML=true

And call this in every cell you want display

    hv.extension('bokeh')

**Comment by rchurt** [comment]
Still having this issue with displaying DynamicMaps in Colab--for example [this](http://holoviews.org/reference/streams/bokeh/BoundsY.html#streams-bokeh-gallery-boundsy) example from the docs will render, but values from the selection don't get updated in the table.

**Comment by blois** [comment]
I'm seeing a number of different errors occurring, not sure exactly what the flow is expected to be- occasionally I see it actually work, but often I get an error:

`Expected text fragment but received binary fragment` from https://github.com/bokeh/bokeh/blob/130b5eb8b3f1a8715fb3f9ab6d6b33dc3f716531/bokehjs/src/lib/protocol/receiver.ts#L59

Where it's getting an ArrayBuffer rather than text.

Also seeing an error because `apply_json_patch` (https://github.com/bokeh/bokeh/blob/branch-2.1/bokehjs/src/lib/document/document.ts#L668) is being called with `{id: "6260"}`, so `references` is undefined and fails to iterate at https://github.com/bokeh/bokeh/blob/130b5eb8b3f1a8715fb3f9ab6d6b33dc3f716531/bokehjs/src/lib/document/document.ts#L358.

**Comment by rchurt** [comment]
Hi @blois,
Just wanted to check in to see if you'd managed to get DynamicMaps to work reliably in Colab based on the above, or if you'd run into any other issues. Thanks!

**Comment by ka-steve** [comment]
Hi @blois, 
I'm wondering too if you managed to get DynamicMaps working.
I'm trying to run the first example from http://holoviews.org/user_guide/Dashboards.html and it renders at first, but does not update and I get the same "Expected text fragment but received binary fragment" error in the console you mentioned.

**Comment by bryevdv** [comment]
cc @ajaythorve who mentioned using HV to me earlier today

**Comment by AjayThorve** [comment]
this notebook- https://colab.research.google.com/drive/1pv6VETRiTE_XlnmaROwWSHW9R6xbfbye?usp=sharing - has the example using interactive shade in hv (has the type dynamic map). Thanks to @gregory1506 for the work on this.

**Comment by ka-steve** [comment]
Thanks @bryevdv, @AjayThorve, I will check it out!

Meanwhile here is my example:
https://colab.research.google.com/drive/1s7zVjWeUsXP5Dsm-L8F1steiOuYNgZVe?usp=sharing

As I mentioned, it is the Dashboards notebook downloaded from the Holoviews website, so I assumed it should work. I've only added the bokeh sample download at the beginning and the extension lines in each cell.  I've tried installing various versions and even pyviz-comms, but they didn't change anything.

And the mighty weird thing that sometimes it doesn't work at all, other times it starts to work after a few clicks, with no change in the code whatsoever, starting with Factory reset etc.

This is how it usually doesn't work:
![mDstO376Bc](https://user-images.githubusercontent.com/4239832/114744341-dfefa800-9d4d-11eb-8550-8ed839e787a9.gif)
And this is how it sometimes starts to work, but note how it doesn't react to the first change of the select, even if it works from the second change:
![Xj8jDACXx5](https://user-images.githubusercontent.com/4239832/114744626-2e9d4200-9d4e-11eb-9fde-a398a0660e26.gif)

While creating these gifs, I've noticed a reproducible pattern:
 - Factory reset
 - Run cell with the imports and sample download
 - Run first example cell: it doesn't work, it gives the "binary fragment" error
 - Run the same cell again: it works from the second change.

If I duplicate the example cell, run the original then run the copy, none of them work. Whatever happens and lets it almost work at the second run, affects only the scope of the cell. 

Scratch that. While further experimenting, this stopped working. Now I get the binary error every time with no way to reproduce the almost-working result. I assume after some time it would return again. Or not.

And this is only the first example. I tried the next example with the panel integration a few times, with similar results (mostly not working, sometimes something works but no clear way to reproduce), but right now can't experiment with that either as I only get the binary error...

**Comment by ka-steve** [comment]
> this notebook- https://colab.research.google.com/drive/1pv6VETRiTE_XlnmaROwWSHW9R6xbfbye?usp=sharing - has the example using interactive `shade` in hv (has the type dynamic map). Thanks to @gregory1506 for the work on this.

For me the 2nd cell crashes the kernel. Commenting out `condacolab.check()` helped, then everything ran correctly. But I'm not sure if this is a good example. 

As far as I understand, all of the examples are willing to run for the first time and create a displayable output. The datashader functions (shade, regrid) also work allowing an interactive rescaling. But as soon as `hv.DynamicMap(some_func)` comes into play either through `.redim.values(..)` or through `@pn.depends`, something breaks.

**Comment by ka-steve** [comment]
This issue just keeps fascinating me. I tried the same example again, and got the same factory-reset/not-working/almost-working result. So I though I make a recording just to make sure it's not me going crazy. However this time I got 3 not-working results before I got one almost-working result. 
![dP2joXE3k8](https://user-images.githubusercontent.com/4239832/114792542-db94b080-9d88-11eb-8e15-64058ff16ad6.gif)

**Comment by blois** [comment]
It looks like there's a race condition somewhere. We try to ensure deterministic event ordering from Colab though there can always be a case where something was missed.

**Comment by bryevdv** [comment]
I don't really know anything about the customizations that collab makes to the standard notebook, or the Bokeh adapter that was mentioned. Is there some proxy or other go-between that relays websocket messages?

**Comment by blois** [comment]
I think I have a handle on the issue, will be following up shortly.

**Comment by blois** [comment]
@ka-steve Do you want to give that a try again? Some tweaks should have just rolled out.

**Comment by ka-steve** [comment]
@blois I tested the original official Holoviews Dashboards example I linked above and can confirm that it worked perfectly every time I tried. I will get back to you if it ever reappears but it seems to be solved now, thanks!
