### ISSUE TITLE
Missing proper language field

### ISSUE THREAD

**Issue by silversillu** [googlecolab/colabtools#625]
Bug report for Colab: http://colab.research.google.com/.

When I save a notebook in my local Jupyter Notebooks interface and explore the source, it has the following section:

    "kernelspec": {
       "display_name": "Python 3",
       "language": "python",
       "name": "python3"
    }

On the other hand, when I download the `.ipynb` file from Colaboratory, this sections looks like this:

    "kernelspec": { 
        "name": "python3", 
        "display_name": "Python 3" 
    }

The problem with the latter is that many tools (such as [notebook.js][1]) rely on the `language` field to properly render the HTML which is needed for code highlighting etc.

For example, when I use [nbpreview][2] to preview my notebook saved from Colab,it will look like this:

    <code class="lang-undefined" data-language="undefined">

Whereas, one saved from my local Jupyter Notebook will look like this:

    <code class=" language-python" data-language="python">

 

  [1]: https://github.com/jsvine/notebookjs
  [2]: https://github.com/jsvine/nbpreviewions

**Comment by craigcitro** [comment]
Thanks for the report!

I'm a little wary about adding a language field, since it's not part of the notebook format:
  https://github.com/jupyter/nbformat/blob/11903688167d21af96c92f7f5bf0634ab51819f1/nbformat/v4/nbformat.v4.schema.json#L13-L27

Do you know if the tools you're looking to use also respect the `language_info` field? It looks like we're *also* failing to fill that one in, but I'd be much happier adding the info there.

Also adding @rgbkrk as knower of all things nbformat, in case `language` in the kernelspec is a de-facto standard.

**Comment by silversillu** [comment]
Thank you for your answer @craigcitro 

Yes, `language_info` field would work fine as well. (if it's set as `language_info.name`)

Just checked notebook.js source code and found this:

`var lang = this.cell.raw.language || m.language || (m.kernelspec && m.kernelspec.language) || (m.language_info && m.language_info.name);`

**Comment by maciejkula** [comment]
To revive this: this field is used for tools like `nbconvert` to correctly tag code fences: [code](https://github.com/jupyter/nbconvert/blob/7b535027d6b6323aea05d619d13ef4e52c89e5de/share/jupyter/nbconvert/templates/markdown/index.md.j2#L14).

This seems worth supporting.

**Comment by MSeal** [comment]
FYI there have been a couple reported issues trying to use papermill recently with colab notebooks that are missing this field (e.g. https://github.com/nteract/papermill/issues/584). The `language_info.name` field should be the one to target for 4.x notebooks. You may also want to bump the minor version from 0 to 4 or 5, depending on if you have cell id support yet, to keep the spec versions closer to the more recent minor releases.

**Comment by blois** [comment]
I'll take a look into this. 

Cell ID support is in if you upload a notebook w/ v4.5, per https://github.com/jupyter/nbformat/pull/189#issuecomment-736917847. An example if you want to give it a try is https://colab.research.google.com/gist/blois/161ecb9e8bc9ca8e9d1c277a0f6925fb/nbformat-4-5.ipynb - please let us know if there's anything unexpected.

I don't imagine we'll switch to 4.5 until at least JLab and possibly classic gain support (https://github.com/jupyterlab/jupyterlab/issues/9729).

**Comment by MSeal** [comment]
Thanks for taking a look!

Classic and nteract have 4.5 support now, with lab still having partial support (id's save but get replaced on each save). I'll poke on that issue to see if we can get that prioritized.

**Comment by blois** [comment]
The fix for this should be live now.
