### ISSUE TITLE
Files do not appear in Drive

### ISSUE THREAD

**Issue by eliezerfb** [googlecolab/colabtools#63]
I tried to use !wget and !git, however the files and directories are not visible in Drive. But the files downloaded, because I can see using !ls

**Comment by eliezerfb** [comment]
Maybe it's not a bug, let me test it better.

**Comment by eliezerfb** [comment]
I was following the https://medium.com/deep-learning-turkey/google-colab-free-gpu-tutorial-e113627b9f5d tutorial and could not clone the repository and link to Drive. I could not make it work, but today it worked first. I believe that yesterday I was with some instability, because what I did today was what I had done yesterday.

**Comment by fischman** [comment]
If you can reproduce the problem with a self-contained notebook please share it with colaboratory-team@google.com and reopen this bug.  Thanks.
