### ISSUE TITLE
"Copy path" from gdrive sidebar does not include initial slash

### ISSUE THREAD

**Issue by ikazos** [googlecolab/colabtools#630]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

Say we want to write code to load a file from gdrive. We mount gdrive, navigate to our desired file in the sidebar on the left, in the "Files" tab. We right-click on the file to reveal the context menu, and click "Copy path" to copy the path. We then paste this into our code.

The copied path does not have a slash `/` at the beginning, but it is required:

```
with open("/content/drive/myfile.txt") as f1:
    pass    # success!
with open("content/drive/myfile.txt") as f1:
    pass    # error!
```

- Describe the expected behavior:

The initial slash should be included.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Firefox Quantum 67.0.4 (64-bit)

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment]
Thanks for the report!

tracking info for our side:
b/137547753

**Comment by blois** [comment]
The fix for this should now be live.
