### ISSUE TITLE
 XhrHttpError: Request Failed, status=500

### ISSUE THREAD

**Issue by ghost** [googlecolab/colabtools#631]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

I can't connect to runtime GPU, there is `"unable to connect to the runtime"` in the bottom-left corner, and when running a cell, I get this error

```
Error
Failed to execute cell. Could not send execute message to runtime: XhrHttpError: Request Failed, status=500, url=https://colab.research.google.com/tun/m/gpu-k80-s-2u7v4uhjye607/api/sessions?authuser=0
```

- Describe the expected behavior:

Well it's supposed to work ! It works with TPUs

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Using firefox, but tried it on chrome and it failed too.
![Screenshot from 2019-07-11 17-22-08](https://user-images.githubusercontent.com/44257632/61063617-8a5fcc00-a400-11e9-9f62-f6897bbaf97b.png)

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/drive/1bh2cMkWum_8Ip4QUeionDwb3Y6I30vkM

**Comment by VincentMatter** [comment]
So it wasn't working yesterday, even after rebooting, clearing cache, changing browser. Today it worked without a problem. Should I close the issue ? I'm not sure

**Comment by codermine29** [comment]
Facing same issue

**Comment by cperry-goog** [comment]
We'll need a more minimal repro notebook to investigate
