### ISSUE TITLE
Typo: rwo should be row

### ISSUE THREAD

**Issue by djbarrettg** [googlecolab/colabtools#633]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
In the Recommendation Systems colab, under "II. Preliminaries", the word "rwo" should be "row".

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://drive.google.com/file/d/1fxJPkY7RMTdQTD3azYh4Yvtx-7EpqI7T/view?usp=sharing

**Comment by metrizable** [comment]
@djbarrettg Thanks for the report. The [notebook](https://colab.research.google.com/github/google/eng-edu/blob/main/ml/recommendation-systems/recommendation-systems.ipynb) has since been updated.
