### ISSUE TITLE
Feature Request: Show blank spaces, or vertical lines, or any other visualizer of indentations

### ISSUE THREAD

**Issue by Santosh-Gupta** [googlecolab/colabtools#636]
I would love to have some sort of visualization of the indentations in Google colab, to more easily  comprehend what code belongs to what functions and classes. 

Vertical lines are a classic way to do this. 

https://snag.gy/R02NzM.jpg

Showing/highlighting the spaces/tabs are also something I've seen in IDEs. 

My favorite is different column highlights for each tab, which I haven't seen in a while so I don't have an exact pic of this. But the first left tabs will always be one color , next tab will be another, etc. I made a quick mock up of what I'm trying to describe

https://snag.gy/8GNXs2.jpg

**Comment by blois** [comment]
We're working on changing the code editor engine, details can be found at https://colab.research.google.com/notebooks/editor_details.ipynb.

If you enable the new editor then there will be a preference in the Editor section 'Show indentation guides' which will display the indentation.

![image](https://user-images.githubusercontent.com/2152569/61968479-00316f00-af8d-11e9-9330-f7407f519400.png)


![image](https://user-images.githubusercontent.com/2152569/61968445-eb54db80-af8c-11e9-96c4-cdb32549ac65.png)
