### ISSUE TITLE
tensorflow can't handle a numpy array object to placehoder's variable

### ISSUE THREAD

**Issue by hayoungishere** [googlecolab/colabtools#638]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
[
![캡처](https://user-images.githubusercontent.com/48154977/61290669-65f05f00-a807-11e9-8480-dd3171c8eae1.PNG)
](url)

**Comment by metrizable** [comment]
@hayoungishere Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem including NumPy and TensorFlow since then, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
