### ISSUE TITLE
correction not reflecting

### ISSUE THREAD

**Issue by debadityamandal** [googlecolab/colabtools#639]
After correcting error in a particular cell or module, the correction is not reflecting into the program during re-execution. Same error is displaying as before. After click on "restart and run all", correct code is executing. This is not acceptable because it deletes all the local variables and models created by previous execution.Please check this. I am accessing colab through google chrome.

Thank you

**Comment by blois** [comment]
Can you explain where the code is that you are correcting?

If the code is in a cell then the cell will have to be re-executed to get the differences. If the code is in a separate python file then the module will need to be reloaded.

**Comment by debadityamandal** [comment]
It is not happening every time.Sometimes it is happening.Suppose one  cell is containing a function and I have changed something to fix an error.After that I re-execute the cell.When i am calling that function from another cell same error is coming which was coming before but after click on 'restart and run all' button every cell is working fine.
