### ISSUE TITLE
Problem with downloading big files

### ISSUE THREAD

**Issue by alla-levina** [googlecolab/colabtools#64]
I use google colaboratory for neural network's training and want to save files with computated models on my local system. But I faced problem when I tried to do it. I download small files without any problems but for every really big file (~200Mb) I see this error.
Can you give me an advice for solving this problem?

<img width="408" alt="connectionreseterror" src="https://user-images.githubusercontent.com/25111542/36374715-674273ac-157d-11e8-968f-7df0a959d296.PNG">

**Comment by fischman** [comment]
As a workaround you might consider saving to Google Drive or GCS as demonstrated in https://colab.research.google.com/notebooks/io.ipynb

**Comment by blois** [comment]
There is a new file download UI in the notebook sidebar, alongside the table of contents.
