### ISSUE TITLE
Dark theme: inline code color scheme—UX issues

### ISSUE THREAD

**Issue by 8bitmp3** [googlecolab/colabtools#640]
Hi @corrieann @craigcitro @CSEMike Thanks for Colab, it's wonderful and indispensable. Just wanted to share this issue:

- **Describe the current behavior (Dark theme, text cells, Markdown):**

Since code cells have a black background vs text cells, which have a dark grey one, some of the inline code colors for modules, functions, etc render/appear barely visible/comprehesible:

- **Example for reproducibility:**

While in Colab with the Dark theme enabled
`import`, `as`, `class`, `def`, `return` are purple in Markdown—barely visible
class name (e.g. `MyModel`), `super`, `call` are dark blue against a dark grey background...—barely visible

The same stuff looks ok against a default black background in code cells.

![image_dark_theme](https://github.com/8bitmp3/temp_image_repo/blob/master/google-colab-dark-theme-inline-code-colors.png?raw=true)

Try this sample code in Markdown to reproduce the issue:

```python
import tensorflow as tf

# A simple `tf.keras` model
class MyModel(tf.keras.Model):
    def __init__(self):
        super(MyModel, self).__init__()
        self.conv1 = tf.keras.layers.Conv2D(32, 3, activation='relu')
        self.flatten = tf.keras.Flatten()
        self.dense1 = tf.keras.Dense(128, activation='relu')
        self.dense2 = tf.keras.Dense(10, activation='softmax')
        
    def call(self, x):
        x = self.conv1(x)
        x = self.flatten(x)
        x = self.dense1(x)
        return self.dense2(x)

model = MyModel()
```

- **Suggested solution—change the color scheme:**

Potentially changing the default code text colors scheme to accomodate for the dark grey background.

Lighter colors such as those in Atom's Dark Theme https://atom.io/themes/one-dark-ui or PyCharm's dark theme https://plugins.jetbrains.com/plugin/11938-one-dark-theme should be adopted in line with the common standards:

Atom:
![example_atom_dark_theme](https://i.github-camo.com/af4a063b48fb691fb25e664ca8e0680a31f6f1e4/68747470733a2f2f636c6f75642e67697468756275736572636f6e74656e742e636f6d2f6173736574732f3337383032332f32363234363831382f30383235356237362d336364362d313165372d396636642d3661653365313661383961392e706e67)

PyCharm:
![example_pycharm_dark_theme](https://plugins.jetbrains.com/files/11938/screenshot_19494.png)

**Comment by blois** [comment]
We're working on switching to a different code editing engine which has updated dark mode highlights. Details to enable it can be found at https://colab.research.google.com/notebooks/editor_details.ipynb. 

![image](https://user-images.githubusercontent.com/2152569/61968269-68cc1c00-af8c-11e9-9f4f-146bb46c2147.png)

**Comment by 8bitmp3** [comment]
@blois autocomplete, dark mode, etc totally rock 👍 Great job team
