### ISSUE TITLE
Can't cd into a specific directory

### ISSUE THREAD

**Issue by CSP197** [googlecolab/colabtools#641]
- Describe the current behavior:

```jupyter
%%bash
date_dir=`date +"%y-%m-%d"` # Use linux date command to get today's date and initialize to the `date_dir` variable
mkdir -p $date_dir          # Make a new directory (if it doesn't already exist) and assign the name as the value of the `date_dir` variable
cd "`ls -t | head -1`"      # This is supposed to list all elements in the current directory, sorted newest first, 
                            # only take the newest element and change directory into the newest element
```

- Describe the expected behavior:

**The cd command isn't working on Google Colab, but this command works on my local linux machine.**

- The web browser you are using (Chrome, Firefox, Safari, etc.):

**This behavior has been seen on Google Chrome and Firefox.**

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Copy/Paste the aforementioned Jupyter code in a notebook to reproduce this issue**

**Comment by craigcitro** [comment]
I believe this is all WAI.

I suspect the issue you're hitting is that after executing that cell, further shell commands aren't executed in the date subdir; this is expected: you're starting a subshell, changing directory, and then closing the subshell. The directory you changed to isn't remembered anywhere.

If you want further python & shell commands to be in a different directory, use `%cd`.

If I'm misunderstanding, feel free to reopen. 😁

**Comment by CSP197** [comment]
I've tried the same commands using `%` with the same outcome. 
If this is the expected behavior, is there any way to persist the state of the sub-shell after closing it?

**Comment by craigcitro** [comment]
In general, `os.chdir()` is the best way to change directories: https://docs.python.org/3/library/os.html#os.chdir

`%cd` is a shortcut for this.

**Comment by CSP197** [comment]
So I'm currently using the following:
```python
date_dir = datetime.date.today().strftime("%y-%m-%d")
os.makedirs(date_dir, exist_ok=True)
os.chdir(date_dir)
```
and wanted to implement the same concept using the `%` cell magic, but am unable to do so as of writing...

Any advice?

**Comment by craigcitro** [comment]
No, there's no reasonable way for the child (bash) process to affect the state of the parent process.
