### ISSUE TITLE
regarding pip list outdated

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#642]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
too many outdated packages

- Describe the expected behavior:
updated packages

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/14UhBTAkmQBT0kv1qZNyAgllUHpWNsBeg

**Comment by metrizable** [comment]
@vainaixr Thanks for filing the issue. Since you reported it, we've made many package upgrades and are continuing to do so. Several packages are currently out-of-date and we're working to get the Colab runtime ecosystem of packages to a contemporary set of versions.
