### ISSUE TITLE
Issue importing MNIST in colab CNN tutorial

### ISSUE THREAD

**Issue by manasi-sharma** [googlecolab/colabtools#643]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: Whenever I try to run cell 4 (from mnist import MNIST
data = MNIST(data_dir="data/MNIST/")), I get an error saying that:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-f3175b8855ff> in <module>()
----> 1 from mnist import MNIST
      2 data = MNIST(data_dir="data/MNIST/")

ModuleNotFoundError: No module named 'mnist'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

I tried pip installing both mnist and python-mnist but neither fixed the issue, which then said that there is an error importing MNIST. Two days ago, the entire notebook was working as intended (no issues), so I am unsure about what suddenly changed.

- Describe the expected behavior: The expected behavior is that MNIST loads without issue and the rest of the code runs smoothly from there.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome, although the issue also shows up in Firefox as well. I tried running the notebook from another laptop and the issue still persisted.

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/github/Hvass-Labs/TensorFlow-Tutorials/blob/master/02_Convolutional_Neural_Network.ipynb

**Comment by agneevguin** [comment]
This is still an open issue after more than 2 years.

**Comment by craigcitro** [comment]
I'd try reporting upstream to the repo that owns that notebook (Hvass-Labs/TensorFlow-Tutorials).
