### ISSUE TITLE
how to do code folding?

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#646]
- Describe the current behavior:
no shortcut available for code folding

- Describe the expected behavior:
shortcut for code folding

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

**Comment by blois** [comment]
We're working on switching to a new editor engine, details can be found at https://colab.research.google.com/notebooks/editor_details.ipynb.

If you enable this editor then there is an option in the Preferences under the Editor section to enable Code Folding. Once this is enabled use Ctrl+Shift+[ and Ctrl+Shift+] to expand/collapse.

**Comment by vainaijr** [comment]
yes I was able to do it, thanks
