### ISSUE TITLE
Recurring 'module' object has no attribute 'X'

### ISSUE THREAD

**Issue by GrahamboJangles** [googlecolab/colabtools#648]
I keep getting this error in Google Colab when I try to use an attribute of a module. Here's the error I get in [this notebook](https://colab.research.google.com/drive/1Dnwz5mkymI6GKaW9mt92TDOoQqAFA6TH#scrollTo=7EHplbNW_PyJ&forceEdit=true&offline=true&sandboxMode=true) for example (this has happened with multiple different modules in multiple notebooks):
```
AttributeErrorTraceback (most recent call last)
<ipython-input-2-7d82ed158dda> in <module>()
     12 
     13 # define the submission/grader object for this exercise
---> 14 grader = utils.Grader()
     15 
     16 # tells matplotlib to embed plots within the notebook

AttributeError: 'module' object has no attribute 'Grader'
```
Importing modules is successful, but using attributes is often not. I'm not 100% sure if this is a Colab issue or something else but since this has happened across many different projects I'm starting to think it has something to do with Colab.

This is in Chrome.

EDIT: I seem to kind of get by this by using `!wget` then extracting it rather than using `!git clone`

**Comment by craigcitro** [comment]
That notebook isn't public, which will make it harder to diagnose.

There's nothing colab-specific here; my hunch is that all the problems you're seeing would be resolved by a kernel restart (ctrl-m . or Runtime -> Restart).

(In particular, I'm guessing that you've got a situation where you're importing modules that were installed in this session, and python's import idempotency is causing grief.)

**Comment by GrahamboJangles** [comment]
@craigcitro The notebook is now public. My bad, I thought I did it correctly the first time. I think you will find that even restarting the runtime/kernel will not fix the issue in the notebook.

**Comment by craigcitro** [comment]
The utils library you're installing is this one: https://pypi.org/project/utils/

Neither that nor the library you install in the first cell have a `grader` anywhere, which is why the import is failing.

This isn't really a colab issue, so would be a better fit for StackOverflow.
