### ISSUE TITLE
Cell getting "stuck" when scrolling.

### ISSUE THREAD

**Issue by joseivanchechen** [googlecolab/colabtools#651]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
When I select a cell which the one above is waiting to be executed, it gets "stuck" in the screen while I'm scrolling.

- Describe the expected behavior:
The cell should be following the scroll of the page.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chromium 75.0.3770.142.

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1rNTysfChrPq9rEGGyfR3UCSnOVyqpM-K
Execute the first cell (the one with `while 1: pass`), select to run the `def func_big1()` cell, then select the cell below it and start scrolling.
Also, try running the cell above the `def func_big1()` and select the one below it (which is `def func_big1()`). The "stuck" area isn't so big as it is with `def func_big2()`.

**Comment by blois** [comment]
This is being tracked internally as b/138130676. It appears to be a recent regression, but not clear if it was a change in Colab or a recent upgrade of Chrome.

**Comment by blois** [comment]
And thanks for the great repro!

**Comment by joseivanchechen** [comment]
Tested using Vivaldi (built upon Chromium), while using the "classic editor" the problem didn't occur, only when I switched to the "new editor" this issue started happening.
No problems while using the "new editor" on Firefox.

Hope it helps.

**Comment by blois** [comment]
This issue should now be fixed.
