### ISSUE TITLE
New Editor Bug: text might disappear when it is selected

### ISSUE THREAD

**Issue by liyxi** [googlecolab/colabtools#653]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
In the new code editor, selected text is not shown properly occasionally. Part of the text might disappear when they are selected.

- Describe the expected behavior:
They should be shown on the screen.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome - Version 75.0.3770.142 (Official Build) (64-bit), on OS X Mojave 10.14.6, with the dark theme (for both Colab and the OS).

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
I don't think there is any specific occasion when the bug can be triggered. But I believe any notebook can reproduces this, as long as you tried enough times.

Thank you.

Attachment: some screenshots
![ScreenShot1](https://user-images.githubusercontent.com/19374612/62029666-98965080-b226-11e9-8583-8f157d36bc11.png)
![ScreenShot2](https://user-images.githubusercontent.com/19374612/62029668-992ee700-b226-11e9-9caa-93456138f5fe.png)

**Comment by blois** [comment]
I'm working on a fix for https://github.com/googlecolab/colabtools/issues/651 which I'm hoping will help out with this issue as well. Will update the bug when the changes are live.

**Comment by blois** [comment]
The fix for https://github.com/googlecolab/colabtools/issues/651 is now live, please let us know if this is still repro'ing.

**Comment by liyxi** [comment]
> The fix for #651 is now live, please let us know if this is still repro'ing.

Thank you so much. #651 is absolutely fixed. I tried it. But unfortunately, this issue is still there. 

![Screen Shot 2019-08-02 at 1 09 04 pm](https://user-images.githubusercontent.com/19374612/62341520-0e503400-b527-11e9-978a-1b3ddf8bc554.png)

**Comment by blois** [comment]
Does this reproduce in light theme as well?

**Comment by liyxi** [comment]
@blois I'm not sure about that. But I can try it today.
