### ISSUE TITLE
problem with tpu and cudnnlstm

### ISSUE THREAD

**Issue by vahidajalluian** [googlecolab/colabtools#654]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Opkernel problem, while using CuDNNLSTM on TPU of google Colab
- Describe the expected behavior:
Working like a clock!
- The web browser you are using (Chrome, Firefox, Safari, etc.):
All of them no difference
- Link to self-contained notebook that reproduces this issue

**Comment by metrizable** [comment]
@vahidajalluian Since this issue was filed a while ago, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
