### ISSUE TITLE
Can't connect to Tesla T4 GPU

### ISSUE THREAD

**Issue by hongtaijing** [googlecolab/colabtools#655]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

GPU is always Tesla K80 since yesterday

- Describe the expected behavior:

reset the runtime GPU should change to Tesla T4 

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by hongtaijing** [comment]
BTW, other's account can still use T4. So I guess this is the problem only for me.

**Comment by ManzarIMalik** [comment]
@hongtaijing,

Similar issue! I was able to use Tesla T4 before but now it only shows Tesla K80. A little research on this issue showed me that probably use of Tesla T4 is limited/account.

**Comment by hongtaijing** [comment]
@ManzarIMalik Yeah, but i didn't find any document or Q&A post some explanation about its limitation.  So I just wonder it is a bug or a normal phenomenon for a personal account.

cheers,
Hongtai

**Comment by ManzarIMalik** [comment]
@hongtaijing,

FAQ's [here](https://research.google.com/colaboratory/faq.html#gpu-availability) states:
**How may I use GPUs and why are they sometimes unavailable?
**

> Colaboratory is intended for interactive use. Long-running background computations, particularly on GPUs, may be stopped. Please do not use Colaboratory for cryptocurrency mining. Doing so is unsupported and may result in service unavailability. We encourage users who wish to run continuous or long-running computations through Colaboratory’s UI to use a local runtime.

So I assumed this is the case, if you are prolonging training on Colab, they rollback gpu version avalable to you. 

But @googlecolab doesn't say anything about this. Hope they will clarify this.

Best Regards,
@ManzarIMalik

**Comment by hongtaijing** [comment]
@ManzarIMalik It might work like this as you said.  Because I was training my model for long times these days. :) Thank you so much for your help!

Regards,
Hongtai
