### ISSUE TITLE
New editor: sometimes caret does Not appear where I can click

### ISSUE THREAD

**Issue by Santosh-Gupta** [googlecolab/colabtools#656]
Bug report for Colab: http://colab.research.google.com/.

Sometimes I click where I want the caret to be placed, but instead a whole block of text is selected. Here's picture

https://snag.gy/63N0cl.jpg

Whereever  I click, the caret does not appear there, and if I type something, it deleted the whole block of code.

**Comment by blois** [comment]
We've been unable to reproduce this- do you know what browser and OS you are using?

It almost seems like a triple-click gesture, but normally in that case the cursor would go to the start of the next line.

**Comment by Santosh-Gupta** [comment]
I am using Google chrome, windows 10. I am also using a font changer extension, I wonder if this has an effect. I am unable to reproduce this error at will. I'll try to note what steps require reproduction of the issue. After triple clicking, I can still place the caret whereever I click.

**Comment by blois** [comment]
Using a Chrome incognito window is an easy way to experiment with no extensions- if it does not repro there then it's frequently an extension.

A font changer could definitely cause problems as it could invalidate the font size calculations.

**Comment by blois** [comment]
You mentioned that you're using a font changer extension- the new editor is using the browser's default 'monospace' font, you can change which font the browser uses to render that in Chrome settings:
![image](https://user-images.githubusercontent.com/2152569/62226349-f1710080-b36e-11e9-8113-24b07f7c4f76.png)
