### ISSUE TITLE
Drive files save bug

### ISSUE THREAD

**Issue by Kotzly** [googlecolab/colabtools#659]
I am using Google Colab for research purposes and i've encoutered a bug. Sometimes when I am writing files to my drive mounted directory thhe notebook shows that I am using the VM disk space, and soon becomes full and crashes. I can see the files in my drive directory, but when I shutdown the notebook the files get deleted.

I am using Google Chrome Version 75.0.3770.142, in a notebook with a python3 kernel and no Hardware Acceleration.

**Comment by colaboratory-team** [comment]
Data written to Google Drive is first written to the disk attached to the VM, so the maximum size is limited by that.
The `google.colab.drive` module has a recently-added `flush_and_unmount()` function that you can use to sync data written to the local VM's disk cache of your Drive-mounted folder back to Google Drive, after which a "Reset all runtimes" (from the Runtime menu) will get you a fresh VM.
We're working on making all this more transparent.
