### ISSUE TITLE
weird codefolding behaviour

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#660]
First Scenario
1) I folded code
2) I went to the end of the current line, using end key on my keyboard
3) I want to go to the next cell, but it does not go
4) So, I have to press shortcut command for going to the next cell
5) In cells that do not have code folding, I am able to press the down arrow twice at the last line and move to the next cell, but when code is folded, then I have to press shortcut.

Second Scenario
1) I folded code
2) I went to the next cell by pressing shortcut command
3) I pressed up to go to the previous cell, which contains folded code.
4) Code automatically unfolds, why does this happen, shouldn't it only unfold when I press ctrl + shift + ]

**Comment by blois** [comment]
Yes, cell navigation appears to be using source lines rather than visible lines.
