### ISSUE TITLE
GPU not available when using TF 2.0.0-beta1

### ISSUE THREAD

**Issue by jbgh2** [googlecolab/colabtools#662]
- Describe the current behavior:

GPU is not visible to tensorflow 2.0.0-beta1 even when notebook is set to use it.

- Describe the expected behavior:

GPU is available

- The web browser you are using (Chrome, Firefox, Safari, etc.):

It doesn't matter.

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/drive/1vgMWH8im_p6gRN60Nnawzn7jTL5P5UNd

**Comment by MarkDaoust** [comment]
We have a separate package for the GPU build.
Please try again with:

```
!pip install tensorflow-gpu==2.0.0-beta1
```

**Comment by jbgh2** [comment]
That's it. Thank you!
