### ISSUE TITLE
Regarding dunder methods autocomplete

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#667]
- Describe the current behavior:
dunder methods do not autocomplete, for example, `__set__`, `__get__`

- Describe the expected behavior:
dunder methods autocomplete, with expected arguments, return type

**Comment by blois** [comment]
You should see these appear after the second underscore is typed.

**Comment by vainaijr** [comment]
but it does not suggest `__init__` in a class, only a few methods are suggested.
![Screenshot (299)](https://user-images.githubusercontent.com/43755000/62483392-7a19f180-b7f2-11e9-9a43-2b48acfaf8b9.png)

**Comment by blois** [comment]
Ah, this is a request for completions for declaring dunder methods.

The completions which are appearing are for the global scope.

**Comment by vainaijr** [comment]
also, for string, when I write, `hello world`. and then press control space, it only gives config/ as autocomplete, I think it should have autocomplete according to dir.
