### ISSUE TITLE
bug #2

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#668]
output does not get displayed
[bug_2.zip](https://github.com/googlecolab/colabtools/files/3465179/bug_2.zip)

**Comment by blois** [comment]
Trying to dig into this one- if it occurs again, can you try resizing your browser window?

**Comment by vainaijr** [comment]
it has occurred multiple times within the past couple of days

**Comment by blois** [comment]
A fix for this should now be live.
