### ISSUE TITLE
next cell goes below screen after cell execution 

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#672]
after executing a cell, next cell goes below screen, I think cell execution results should appear, and then next cell should appear on the screen, rather than going below.

[below_cursor.zip](https://github.com/googlecolab/colabtools/files/3469654/below_cursor.zip)

**Comment by vainaijr** [comment]
also, right click options go below screen
also, file menu options go below screen

![Screenshot (304)](https://user-images.githubusercontent.com/43755000/62579005-8fb81580-b8dd-11e9-966b-ab29e5d4ec1c.png)
[bug_right_click.zip](https://github.com/googlecolab/colabtools/files/3474265/bug_right_click.zip)
