### ISSUE TITLE
crash after pip install object_detection

### ISSUE THREAD

**Issue by woodwolfzhu** [googlecolab/colabtools#673]
after I use this code "pip install object_detection" and restart the remote machine,
then it tells me "your session is crashed" again and again.
I refresh the page but it still not work

**Comment by JojoReikun** [comment]
I have the same problem: 
I used the same code 1 week ago and it worked fine several times, but since I tried it today: When I run the cell 'pip install deeplabcut' it will crash after I hit 'Restart Runtime'.

**Comment by GS756** [comment]
Hi, same problem here after switching to python 3.8 and installing the explabox package, which required python>=3.8. The installation is succesful, but the kernel always crashes after hitting the "restart runtime" button, and there is no way to restart it without deleting the session.

**Comment by cperry-goog** [comment]
upgrading python is not supported, it will do weird things

if the base bug is still a problem please share a minimal repro notebook

**Comment by GS756** [comment]
Oh alright, thanks for the quick answer. There is no way to use an upper python version on colab then ?
