### ISSUE TITLE
enable ctrl + click in definition file

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#674]
- Describe the current behavior:
after clicking on ctrl + click to go to the definition of a module, I want to go to definition of another module which is in that definition file, but ctrl + click does not work, that is it does not work again and again.

- Describe the expected behavior:
ctrl + click works on definition file also.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

**Comment by blois** [comment]
Right now we're using the runtime objects to discover the source location, support for this would require additional static analysis on the viewing files (LSP or Jedi). Fully agree that this would be a significant improvement.
