### ISSUE TITLE
Google drive crashing

### ISSUE THREAD

**Issue by rbk1988** [googlecolab/colabtools#675]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: I have mounted google drive with my colab notebook. I got an error message that google drive crashed/timeout occurred. This occurred multiple times.

- Describe the expected behavior: No crash from google drive.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment]
There's not enough information here for us to do anything; please include a minimal self-contained notebook that either repros the problem or (at least) includes the full error you're seeing.
