### ISSUE TITLE
Files on Google Drive loaded using template do not refresh

### ISSUE THREAD

**Issue by combobulate** [googlecolab/colabtools#677]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

I am using the code snippet "Downloading files or importing data from Google Drive". I have modified this to include the file id, as well as a . Then I run this cell and another cell which imports that file and produces an output reflecting the content of that file.

Next I update the file on Google Drive and verify that the ID hasn't changed, and then rerun both this code snippet cell and the cell which imports the file. The output reflects the content of the original file, not the update.

Next I delete the file in the directory where Colab is loading these files (observed when I click the "files" tab); perhaps the upload process is not able to overwrite existing files. I rerun both cells again. Again, the output reflects the content of the original file, not the update.

Total time between file upload and final (after many repeats) rerun of cells is around fifteen minutes. After a significant amount of time, these seem to get synced; something I loaded yesterday finally updated before I ran it today.

- Describe the expected behavior:

The updated file should be used, or there should be some clear indicator of what file is being used instead.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

Issue is apparently time-based so no link is useful

**Comment by craigcitro** [comment]
This sounds like #287, but it's hard to know for sure without a repro notebook. Is it possible to share a minimal notebook that repros the error you're seeing?

**Comment by combobulate** [comment]
Let's see if this works. I've staged https://colab.research.google.com/drive/1it9XLyAAL4Q7a9IiM9XzRg3_p4ShY-6I

To support this notebook, I've initially uploaded to my drive addexample.py with the single function:

def add_numbers(a, b):
    return a+b

After importing the file and running the two cells in the notebook, I uploaded an updated version of addexample.py with a modified version of this (now incorrectly named) function:

def add_numbers(a, b):
    return a*b

However, rerunning all cells in the notebook does not reflect the updated function.

Note that I have found something that *is* working to make the file update for me, but I'm not sure if it is a workaround or if it actually is the correct solution to the problem I am experiencing. After the file is already imported, if I update it and then run the following:

import importlib
importlib.reload(addexample)

Then the file is updated correctly.

**Comment by craigcitro** [comment]
Ah -- what you're seeing is expected behavior; in Python, imports are idempotent. That is, if you do `import foo`, change the underlying file, and `import foo` again -- you won't see the updates.

You have two options:
 * reload, as you're doing
 * restart the kernel between updates (ctrl-m . in colab)

The latter is way more heavyweight, but is probably simpler if you're importing a whole collection of modules (eg `a` imports `a.b` and `a.c`, etc).

**Comment by combobulate** [comment]
Ah, gotcha. Great, thanks!
