### ISSUE TITLE
Unexpected kernel name in notebook metadata silently prevents connection to runtime

### ISSUE THREAD

**Issue by domoritz** [googlecolab/colabtools#68]
Somehow I cannot connect to a kernel when I run https://colab.research.google.com/github/domoritz/draco/blob/master/notebooks/Process%20effectiveness.ipynb. Other notebooks work fine. 

<img width="170" alt="screen shot 2018-02-21 at 20 00 45" src="https://user-images.githubusercontent.com/589034/36519724-f6c858dc-1741-11e8-9aa0-35a256abe678.png">

**Comment by craigcitro** [comment]
I suspect it's getting confused by the kernel name in the notebook metadata. Do you see any errors on the JS console?

**Comment by domoritz** [comment]
Yep, there is a 501

<img width="634" alt="screen shot 2018-02-21 at 21 07 59" src="https://user-images.githubusercontent.com/589034/36521396-76c78b44-174b-11e8-96f1-6a1dd48596a8.png">

**Comment by domoritz** [comment]
It works when I switch to a Python 3 kernel manually. Does this override the kernel name?

Here is the working notebook: https://colab.research.google.com/drive/19dPh_GC3QgYBlzP6Js0w4nWmcyoxfo_N

**Comment by blois** [comment]
The fix for this is now live.
