### ISSUE TITLE
save as snippet

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#680]
hello,

is it possible to give an option to save a section as a snippet, like I press a shortcut command and a section gets saved as a snippet (maybe a default snippet storing file could be asked to the user, where it would get appended at the bottom), and in any another notebook, I would be able to access the saved snippet from code snippets.

thanks

**Comment by blois** [comment]
Custom snippets notebooks can be added in the preferences.

**Comment by vainaijr** [comment]
yes I know that, is it possible to save a section as snippet, so I do not need to copy and paste code in snippets file, it instead happens by a shortcut command, and I can stay in my current notebook, to save a section as a snippet.
