### ISSUE TITLE
regarding imports

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#681]
hello,

suggestion for one more import that would make life easy, and we will not have to pip install it again and again

funcy
https://github.com/Suor/funcy

thanks

**Comment by metrizable** [comment]
@vainaixr Thanks for the request. We pre-install packages based on a number of factors -- among them time to install (in this case, about 8s), [popularity](https://packaging.python.org/en/latest/guides/analyzing-pypi-package-downloads/#additional-tools) in the community, and demand for pre-installation. We can revisit the request if these and other factors change in the future.
