### ISSUE TITLE
pprint bug

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#682]
pprint("") 
is toggling pretty printing.

**Comment by craigcitro** [comment]
This isn't a colab-specific bug; you're hitting IPython automagic: https://stackoverflow.com/questions/19411312/what-is-ipython-automagic

**Comment by vainaijr** [comment]
but how to use pretty printing, %pprint and pprint(“”) both toggle it

**Comment by craigcitro** [comment]
`from pprint import pprint` and you'll avoid the automagic.
