### ISSUE TITLE
ram bag in google colab

### ISSUE THREAD

**Issue by Dvir1992** [googlecolab/colabtools#686]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
hi my ram used to crash after i ran a simulation and then the google colab gave me the option to increase to 25 G ram.  for some reason i deleted my last notebook and now in the new notebook when i get to the end of the ram, google colab doesnt give me this option anymore. what should i do?

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by jsnydes** [comment]
You should see the option in the "toast"-style notification that pops up on an out-of-memory crash.

![ram](https://user-images.githubusercontent.com/1389678/62813165-2ba07780-babe-11e9-8150-4c3d81162086.png)

side note: if the notebook already uses a high-memory runtime (it is a per-notebook) setting, you won't see the offer
