### ISSUE TITLE
Different train speed at different google accounts with same code

### ISSUE THREAD

**Issue by KillerStrike17** [googlecolab/colabtools#687]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: The same code i ran in two of my gmail account i got different training speed. The difference is around 40 seconds

- Describe the expected behavior: Similar training speed for both id.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by tmabraham** [comment]
Check which GPU is being used using !nvidia-smi. I think some accounts are getting K80 and some are getting T4.

**Comment by KillerStrike17** [comment]
It is tesla k80 in one and T4 in other..? how to get t4 in both?

**Comment by tmabraham** [comment]
@KillerStrike17 only way is to use a different google account.

**Comment by donmahallem** [comment]
@KillerStrike17 thats pure luck if you do get a K80 or a T4. Very few times I had luck terminating the VM and creating a new one with a different GPU
