### ISSUE TITLE
TPU problem with nvidia-smi

### ISSUE THREAD

**Issue by vahidajalluian** [googlecolab/colabtools#688]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
When TPU is selected, not only CuDNNLSTM of Keras doesn't work, but also nvidia-smi can't find any graphical processing unit(GPU).
- Describe the expected behavior:
Both of them should work when selected. 
- The web browser you are using (Chrome, Firefox, Safari, etc.):
No difference, it doesn't work tested by chrome or firefox.
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://drive.google.com/file/d/1rpUzzHv8jYC-_dJb_HYE35NcXqjU0P-R/view?usp=sharing

**Comment by craigcitro** [comment]
TPUs are not GPUs, and aren't visible to `nvidia-smi`.

**Comment by vahidajalluian** [comment]
what about cudnnlstm problem with tpu?

**Comment by RahulBhalley** [comment]
> TPUs are not GPUs, and aren't visible to nvidia-smi.

@craigcitro how to visualize TPUs then?

**Comment by sagelywizard** [comment]
There's new CLI for checking TPU utilization metrics called `tpu-info`. It's preinstalled on Colab's TPU runtimes!
