### ISSUE TITLE
[Feature Request] Bar to keep track of GPU memory

### ISSUE THREAD

**Issue by Santosh-Gupta** [googlecolab/colabtools#689]
There are bars to keep track of disk space and CPU memory, but not GPU memory. I would love to have one for GPU memory to aid in optimizing parameters for training.

**Comment by metrizable** [comment]
@Santosh-Gupta This has been implemented and is available from the Resources menu

![7xmrtdK5HXdVaSn](https://user-images.githubusercontent.com/65414824/222488413-94d67e6b-93ae-40c6-9c75-abeec3d6c401.png)
