### ISSUE TITLE
Error: "Failed to execute cell. Could not send execute message to runtime: TypeError: Cannot read property 'emailAddress' of undefined"

### ISSUE THREAD

**Issue by laeremansM** [googlecolab/colabtools#69]
We receive the error "Failed to execute cell. Could not send execute message to runtime: TypeError: Cannot read property 'emailAddress' of undefined" in all notebooks.

**Comment by craigcitro** [comment]
When you say "in all notebooks" -- does this happen in (eg) https://colab.research.google.com/notebooks/welcome.ipynb, or just some other set of notebooks you're viewing?

**Comment by craigcitro** [comment]
One more note: "fix is in" means that we've fixed it on our side; barring any disaster, the fix should be live on https://colab.research.google.com/ on Monday.

**Comment by craigcitro** [comment]
Fix is live -- let us know if you see similar issues!

**Comment by maatkara** [comment]
Failed to execute cell. Could not send execute message to runtime: CustomError: Timed out waiting for promise
 DETAILS
Timed out waiting for promise
CustomError: Timed out waiting for promise
    at an [as constructor] (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab_20180222_085323-RC02_186836021:795:959)
    at new lr (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab_20180222_085323-RC02_186836021:890:978)
    at https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab_20180222_085323-RC02_186836021:890:619

**Comment by maatkara** [comment]
Failed to execute cell. Could not send execute message to runtime: CustomError: Timed out waiting for promise
 DETAILS
Timed out waiting for promise
CustomError: Timed out waiting for promise

**Comment by bii9** [comment]
Keep displaying this message even running a Hello World program:

Error
Failed to execute cell. Could not send execute message to runtime: CustomError: timed out waiting for iframe configuration URL https://localhost:8080/

timed out waiting for iframe configuration URL https://localhost:8080/
CustomError: timed out waiting for iframe configuration URL https://localhost:8080/
    at ro [as constructor] (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab_20180530_085322-RC00_198567274:817:540)
    at new Xs (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab_20180530_085322-RC00_198567274:920:979)
    at https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab_20180530_085322-RC00_198567274:920:620

**Comment by bii9** [comment]
@blois - Thanks for your question. I used Chrome for two of my computers (one in window XP and one in window Vista), both of which version are 49.0.2623.112. I have tried incognito window for both computers in three different networks (six trials in total), but still did not work, indicating that the problem was not due to extensions or plugins. I have tried in a third computer with the most updated Chrome update in window 10 and it works. Do not know if Chrome version 49.0.2623.112 will cause time out error relating to port 8080 leading to the failure of using Google Colaboratory. Thank you ahead of time of your comment. Thanks.

**Comment by blois** [comment]
Unfortunately Chrome 49 is quite out of date right now and is not supported.

**Comment by The-Gupta** [comment]
Error
Failed to execute cell. Could not send execute message to runtime: [object CloseEvent]
[object CloseEvent]

@craigcitro I get this error often. I've been using Colab for 2 weeks.
And, session disconnects after uploading a file from a local drive.

**Comment by The-Gupta** [comment]
I happens while using 

```
from google.colab import files
uploaded = files.upload()
```

but **surprisingly** not while printing some properties after upload completion, like-

```
from google.colab import files
uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))
```
