### ISSUE TITLE
regarding cpython files

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#691]
any way to access cpython files?

I did this

`inspect.getabsfile(torch._C)`

and got this

`'/usr/local/lib/python3.6/dist-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so'`

how to access cpython files in colab without going to github?

**Comment by craigcitro** [comment]
No, there's no way to get directly to the source in this case.

In particular, for a `.so`, it could be a cython file, or it could be another kind of C extension (built via vanilla C/C++ code, or SWIG'd in, or something else completely). All we have is the installed package -- there's no way for us to trace that back to source, and in cases like this (torch is distributed as a .whl file) the source isn't included.
