### ISSUE TITLE
cudnn version is not correct

### ISSUE THREAD

**Issue by world2vec** [googlecolab/colabtools#692]
Bug report for Colab: http://colab.research.google.com/.
I encounter this error:
`019-08-13 06:41:47.282624: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.3.1 but source was compiled with: 7.4.2.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library. `
Looks Cudnn version is not correct in the environment.

**Comment by craigcitro** [comment]
Can you share a self-contained notebook reproducing that error?

**Comment by world2vec** [comment]
Finally find the problem. Looks Spacy conflicts with tensorflow. 
Here is the [notebook](https://drive.google.com/open?id=1XEDAZpXzRHKtErYmW7VqQKU69uiARhVq)

**Comment by craigcitro** [comment]
Yes, that's an excellent repro. 

However, I don't think it's colab-specific -- putting that code in a file and executing gives the same error. I suspect you want to file an issue on spacy or TF.

**Comment by nguaki** [comment]
hello world2vec,

Getting similar problem.

How did you resolve the conflict with spacy?

Did you downgrade or upgrade spacy?

Thanks
