### ISSUE TITLE
search option in ctrl+click opened window

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#693]
- Describe the current behavior:
after ctrl+click on a method, a new window opens, but it is difficult to search for a keyword
in that window, and I have to scroll up and down, to look for a keyword

- Describe the expected behavior:
a search option in the window opened after ctrl+click

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

**Comment by craigcitro** [comment]
b/139424825
