### ISSUE TITLE
using chromedriver to exceed the limit of downloading 100 images gives false error log in Google Colab.

### ISSUE THREAD

**Issue by sparshrestha** [googlecolab/colabtools#694]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:

Google Colab allows only 100 images at a time to download. So basically when developer tries to exceed the `limit > 100` or unknowingly sets `limit = 101` for instance, developer expects a sensible and reasonable error log that would indicate the limit has been wrong or not expected. But the error log says the location of the `chromedriver` couldn't be found. Moreover hints you to use argument to fix the path. Even though the location path is completely working fine.

```
Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to
specify the path to the executable.) or google chrome browser is not installed on your machine
An exception has occurred, use %tb to see the full traceback.
```
Instantly changing the limit back to 100 makes it working again.
- Describe the expected behavior:
Exceeding the allowed limit of downloading 100 images should provide Colab developers with accurate error message that the limit has been exceeded or the limit is prohibited.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
https://colab.research.google.com/drive/1dfdOeK4CPRoUypXl79t9lqUCEbELiDOT

**Comment by blois** [comment]
This looks to be an issue in the google_images_download package- https://github.com/hardikvasa/google-images-download/issues/257.
