### ISSUE TITLE
[Feature Request] Colored brackets , or some sort of indicated for start and end brackets

### ISSUE THREAD

**Issue by Santosh-Gupta** [googlecolab/colabtools#697]
- Describe the current behavior:

brackets ( [ { < > } ] )are all the same color. Sometimes when there's several in a row it's tricky to see which start bracket belongs to which end bracket. 

It would be great to have them a specific color. For example, the first [ would be dark red, second [ would be dark blue, etc. 

Since colors may be limited, I came up with a few alternative solutions:
-keep track of star and end brackets would be a direct line
-textures for the text itself. 

These other solutions may also interfere with the elegantness of the code. So, you could just have these visuals only occur when there mouse hovers over the line. If the caret is clicked on within the line.

**Comment by blois** [comment]
We're working on a new editor engine which has more visual differentiation showing the matched bracket from the cursor position.

Additionally, in the new editor ctrl+shift+\ can be used to jump to the matched bracket.

Info on enabling the new editor: https://colab.research.google.com/notebooks/editor_details.ipynb
