### ISSUE TITLE
Colab notebook close the job with no  logs whatsoever

### ISSUE THREAD

**Issue by MaximBazarov** [googlecolab/colabtools#698]
Trying to run a long job (apple turicreate)
- Describe the current behavior:
No logs after starting GPU on full power, after night the notebook is just not running and creates a new instance with no jobs running.

- Describe the expected behavior:

Some logs during work, keep it alive or at least give some feedback on what went wrong.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1GaJLOhdrN-OG8zsL4vgo-wBcqJh6CPYv#scrollTo=6Q6YYscrpqmw

**Comment by craigcitro** [comment]
Colab backends aren't long-lived; see [the FAQ](https://research.google.com/colaboratory/faq.html), in particular:

> **Where is my code executed? What happens to my execution state if I close the browser window?**
> Code is executed in a virtual machine dedicated to your account. Virtual machines are recycled when idle for a while, and have a maximum lifetime enforced by the system.

**Comment by MaximBazarov** [comment]
@craigcitro thank you for the answer. The issue here is not that it gets terminated, no question here.

The issue is that it gives no output, so I can't tell where's the problem and what is it.

**Comment by craigcitro** [comment]
Can you mount your google drive (`from google.colab import drive; drive.mount()`) and arrange for whatever you're running to write your logs there?
