### ISSUE TITLE
High ram

### ISSUE THREAD

**Issue by letanloc1998** [googlecolab/colabtools#699]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: I can't choose High-ram

- Describe the expected behavior: Could choose High-ram

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by jsnydes** [comment]
we'll need more context to help you. what do you mean by "choose high-ram"?

**Comment by sanjay235** [comment]
![image](https://user-images.githubusercontent.com/25169996/63948052-a6452d00-ca95-11e9-9516-826e7cd1c887.png)

The above kind of option is not available for me too. What I've is as below,

![image](https://user-images.githubusercontent.com/25169996/63948191-dee50680-ca95-11e9-97fc-f0566c4c9155.png)

**Comment by jsnydes** [comment]
this was an experiment we were running that we couldn't launch due to capacity constraints. sorry! we're exploring ways for those who need more RAM to get access to it.

**Comment by letanloc1998** [comment]
Thank you
