### ISSUE TITLE
feature request: connect through SSH from an external console

### ISSUE THREAD

**Issue by davidpham87** [googlecolab/colabtools#70]
Hello,

I think many of us are using external tools to write and edit our code (I personally use Emacs).
Is there any possibility that we connect to the colaboratory through SSH to the running kernel?

Thanks a lot for your help!

Kind regards,
David

**Comment by captainvera** [comment]
This would be an extremely good alternative to adding bindings on the editor! 👍

**Comment by thomcom** [comment]
This would be super great.

**Comment by amundv** [comment]
+1

**Comment by davidpham87** [comment]
At least can we have the emacs shortcut?
