### ISSUE TITLE
can't  authenticate myself anymore with google drive, "unknown error" 

### ISSUE THREAD

**Issue by jandevries123** [googlecolab/colabtools#703]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

When i click on the auth link, login with my account, it "freeze" loads and then says: 

"Something went wrong, try again"  i tried several times and methods and none of them worked

from google.colab import drive
drive.mount('/content/drive')

i use this code all the time, for 4 months now and now suddenly i can't log in anymore

- Describe the expected behavior:

Auth my drive to connect with my google collab code

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Google Chrome, cleared cache already

**Comment by craigcitro** [comment]
We believe this is https://status.cloud.google.com/incident/developers-console/19008.

**Comment by jandevries123** [comment]
> We believe this is https://status.cloud.google.com/incident/developers-console/19008.

Thank you! I forgot to check uptime sites

**Comment by craigcitro** [comment]
This issue should be resolved.
