### ISSUE TITLE
%matplotlib notebook does not turn on interactive mode in Colab.

### ISSUE THREAD

**Issue by qo4on** [googlecolab/colabtools#706]
https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/04.12-Three-Dimensional-Plotting.ipynb

**Comment by drscotthawley** [comment]
See https://github.com/googlecolab/colabtools/issues/616 and 
https://github.com/googlecolab/colabtools/issues/86#issuecomment-377027265

**Comment by agentydragon** [comment]
I'd also be interested in the `notebook` backend. For me the use-case would be updating plots.

(I'm training a TensorFlow model whose output I visualize in a matplotlib figure, and I want to update the plot as the model is being trained. My use-case is not covered by TensorBoard. It's similar to if I trained a GAN and wanted to see outputs of model so I can see it making progress.)

**Comment by blois** [comment]
See https://github.com/googlecolab/colabtools/issues/498#issuecomment-916996133

Opting into custom widget support should enable matplotlib notebook support:
```python
from google.colab import output
output.enable_custom_widget_manager()
```

**Comment by abhilashmathewsvow** [comment]
@blois Unfortunately that fix still does not enable "%matplotlib notebook"

Is there any recommended way to get interactive plots with matplotlib on Colab?
