### ISSUE TITLE
variables are not recognised globally

### ISSUE THREAD

**Issue by 1605810** [googlecolab/colabtools#708]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I have defined a few variables in the beginning in a code cell. A few blocks down creating a list uisng these varaibles. Errror is issued saying variable undefined.
- Describe the expected behavior:
list should be craeted with previously declared variables.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):https://colab.research.google.com/drive/1vAEg6rEro2nUj4WMw8aoU_mqxQCQ384M#scrollTo=GYoOrgpxn5vp

**Comment by craigcitro** [comment]
(notebook is private)
