### ISSUE TITLE
InvalidArgumentError: ValueError: `generator` yielded an element of shape

### ISSUE THREAD

**Issue by Raju-567** [googlecolab/colabtools#709]
Running step2 of the below url is leading to compilation error in train model step(colab tool)
https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android/#1

code lab compilation url :
https://colab.research.google.com/github/tensorflow/examples/blob/master/community/en/flowers_tf_lite.ipynb#scrollTo=JsaRFlZ9B6WK&uniqifier=1

error stacktrace
InvalidArgumentError: ValueError: generator yielded an element of shape (59, 224, 224, 3) where an element of shape (64, 224, 224, 3) was expected.
Traceback (most recent call last):

File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/script_ops.py", line 235, in call
ret = func(*args)

File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 630, in generator_py_func
"of shape %s was expected." % (ret_array.shape, expected_shape))

ValueError: generator yielded an element of shape (59, 224, 224, 3) where an element of shape (64, 224, 224, 3) was expected.

 [[{{node PyFunc}}]] [Op:IteratorGetNextSync]

Error snapshot is also attached 
<img width="1440" alt="error_snapshot" src="https://user-images.githubusercontent.com/45848219/63487849-6fd24580-c4ca-11e9-8978-a84aa573c59f.png">

**Comment by Raju-567** [comment]
Running step2 of the page mentioned in below url is leading to compilation error in train model step
https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android/#1

code lab compilation url : 
https://colab.research.google.com/github/tensorflow/examples/blob/master/community/en/flowers_tf_lite.ipynb#scrollTo=JsaRFlZ9B6WK&uniqifier=1

error stacktrace 
InvalidArgumentError: ValueError: `generator` yielded an element of shape (59, 224, 224, 3) where an element of shape (64, 224, 224, 3) was expected.
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/script_ops.py", line 235, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 630, in generator_py_func
    "of shape %s was expected." % (ret_array.shape, expected_shape))

ValueError: `generator` yielded an element of shape (59, 224, 224, 3) where an element of shape (64, 224, 224, 3) was expected.


	 [[{{node PyFunc}}]] [Op:IteratorGetNextSync]

<img width="1440" alt="error_snapshot" src="https://user-images.githubusercontent.com/45848219/63449065-ee909980-c45c-11e9-84bd-d3235b74100e.png">

**Comment by craigcitro** [comment]
@yashk2810 or @markdaoust do either of you happen to know who owns this tutorial?

**Comment by yashk2810** [comment]
There is a fix in-flight. Should be submitted by monday (waiting on approval).

**Comment by SomethingFromNothing** [comment]
a temporary solution for me..
Steps:
1. BATCH_SIZE = **10** (_or 5_)
2. comment out lines: 
 #rescale=1./255, 
 #validation_split=0.2

**Comment by MarioDeAraujoCarvalho** [comment]
Think that it could be a bug from tf-nightly(-gpu)-2.0 since I installed with standard tensorflow 1.14 and it works. It worked here, I just had to keep an eye on the variables of history.

**Comment by KostyaBakay** [comment]
So currently is it impossible to complete "Recognize Flowers with TensorFlow on Android" codelab?

**Comment by yashk2810** [comment]
The fix is submitted. Can you try it out now?

**Comment by MarkDaoust** [comment]
Actually, it looks like it was not updated.

I'll fix it right now.

**Comment by KostyaBakay** [comment]
@yashk2810 I tried again it right now - it is not working.
<img width="1438" alt="Screen Shot 2019-09-04 at 7 05 08 PM" src="https://user-images.githubusercontent.com/9611539/64271956-01b86480-cf47-11e9-998c-6b00aed314d0.png">

**Comment by MarkDaoust** [comment]
This should be fixed now, sorry about the delay.

**Comment by KostyaBakay** [comment]
@MarkDaoust everything works. Thank you! I suppose this issue can be closed.

**Comment by craigcitro** [comment]
thanks all!
