### ISSUE TITLE
Problems executing cells across several notebooks

### ISSUE THREAD

**Issue by rbuchmann** [googlecolab/colabtools#71]
We have several notebooks stored in our team drive which stopped being able to execute cells altogether. The error message reads:

```
Failed to execute cell. Could not send execute message to runtime: TypeError: y[0] is undefined
```
Restarting or changing the runtime doesn't fix it, in some cases we were able to run the notebooks again by creating a copy of it (in our own respective drives).
Might be related to #69 , since this is a message we also saw in some of them.

**Comment by craigcitro** [comment]
Yes, this should be a duplicate of #69.
