### ISSUE TITLE
Safari: Can't print ipynb file

### ISSUE THREAD

**Issue by captainvera** [googlecolab/colabtools#72]
Nothing happens when I click the print button. Also, there is no "export to pdf" option. 

This means that in order to export the notebook to any other format I have to download the .ipynb file, open it in Jupyter and **then** print it.

Edit: There are no javascript errors when clicking the print box

**Comment by captainvera** [comment]
@jiamicu Hey, Thanks for the help but I think you misunderstood me. 

I didn't mean that I couldn't print in Python, everything works great there. I meant that I can't print to a pdf file (or to a printer). Nothing happens when I click here: 
![screen shot](https://user-images.githubusercontent.com/5597178/36851832-27b218e0-1d62-11e8-819e-972781b2ace3.png)

**Comment by blois** [comment]
Some basic questions-
Browser version? Can you try incognito mode? Are there any errors in the browser's dev console?

**Comment by captainvera** [comment]
Safari 11.0.3.
Doesn't work on incognito mode, and there are no errors on the dev console (caused by the print). 

In a weird note, I came back to a notebook that had been disconnected from the backend and I could print it without issues. 

Works on Chrome without issue.

**Comment by blois** [comment]
I do see the issue in Safari, thank you for filing.

**Comment by captainvera** [comment]
Follow up: 
After being AFK for a while, notebook had the following errors:
![image](https://user-images.githubusercontent.com/5597178/36872244-84b6ca74-1d9c-11e8-8614-2bb85cf6a899.png)

The print now works...

**Comment by captainvera** [comment]
Follow up - 2:
I can't print when I disconnect from Colab. If I open a new notebook and then turn off Wifi I can print 100%.

**Comment by blois** [comment]
I'm also seeing that after invoking `window.print()`, Safari delays a long time before bringing up the print dialog (for me, 20+ seconds).

For the time being, I'd recommend using the browser's native print.

Colab's print is provided because we restyle the page while printing to drop scrolling elements and drop shadows and such. But this relies on a synchronous window.print() and it's not clear that Safari is allowing that.

**Comment by eyehol3** [comment]
sadly, this issue haven't disappeared

**Comment by joshua-goldstein** [comment]
Still an issue on Mac, running Safari

**Comment by lashu333** [comment]
same issue

**Comment by ghost** [comment]
same issue
