### ISSUE TITLE
Wrong drive mounted when using different Google account [cont.]

### ISSUE THREAD

**Issue by meifish** [googlecolab/colabtools#721]
This is a continuation of bug #720. 

- Describe the current behavior:
I have two Google accounts for different use purpose.
I used account B for writing code on CoLab platform, and my data for coding all stored in my Google Drive under this account. It used to work fine when I mount my Google Drive on Colab, however today I discovered when I executed the mount commands as follows, it mounted my drive from account A, and I couldn't retrieve my drive in account B.
```
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
```

- Describe the expected behavior:
While using CoLab with account B, the 'mount drive' behavior should trigger the authentication page for the user to select which account to use. However, it stopped showing that page. I tried using Incognito Windows, clear the cookies and history, and also restart the runtime kernel, but none of the above work. (It used to be fine 1 month ago.)

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

**Comment by databaaz** [comment]
The option is now called **Factory reset runtime**

**Comment by krishnaraj-sr** [comment]
Same problem.
Tried 
1. Factory reset runtime
2. Closing sessions 
3. Cleared browser history
4. Opened auth URL in incognito.
5. Browser Chromium on Raspberri Pi
