### ISSUE TITLE
Closing widgets not working

### ISSUE THREAD

**Issue by FKLC** [googlecolab/colabtools#726]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: Closing an ipywidgets not working

- Describe the expected behavior: When I call widget.close() it should disappear

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome Version 76.0.3809.100

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/drive/1FABSKvIgVay40XCy-p_y3l-RrXpQwSxU

**Comment by blois** [comment]
Thank you for reporting, the fix for this is now live.

**Comment by PERFECT047** [comment]
Thank You.

**Comment by adanyal46** [comment]
the speed is to slow on download

**Comment by FKLC** [comment]
Torrenting is prohibited on Google Cloud. Please don't use it. Also don't send new comments in other random repositories. I'm sorry for the notifications. Someone privileged can lock this issue.

**Comment by temmyg123** [comment]
sometimes stop download , stuck, and no download at all
