### ISSUE TITLE
google drive mount same tab

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#729]
- Describe the current behavior:
google drive mount opens in new tab
- Describe the expected behavior:
google drive mount go to url opens in colab itself
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

**Comment by craigcitro** [comment]
Why do you want it to open in the same tab?

**Comment by vainaijr** [comment]
just like tensorboard access below cell, google drive mount sign in option also below cell.

**Comment by craigcitro** [comment]
I don't think there's any plan to make that possible.
