### ISSUE TITLE
Same Notebook different backend

### ISSUE THREAD

**Issue by captainvera** [googlecolab/colabtools#73]
When working in a shared collab notebook me and my colleagues normally connect to the same backend. This means that, for example, you can't run all cells at once **but** when someone installs a package and runs the cell I can use it in another cell without issue. 

Right now, me and another colleague are on the same notebook, we can see each other's code and text changing in real time.  However, we each need to execute all cells because we seem to be connected to different backends. This means, installing packages twice, downloading datasets twice, etc. 

Is this an intended change, or unexpected behaviour?

**Comment by craigcitro** [comment]
Yes, this is WAI: there's no way to share a Python kernel process with Colaboratory.
