### ISSUE TITLE
Personal file is lost during model training

### ISSUE THREAD

**Issue by ye-yu** [googlecolab/colabtools#732]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
The kernel was disconnected during in the middle of a neural network model training. After reconnecting to the kernel, my saved model does not exist in the disk anymore. (i.e. running `!ls -lah /contents` returned no personal files either uploaded or saved)

- Describe the expected behavior:
I have never run a remove file command, and my files should be there. I could not recreate this issue, but I have uploaded a lot of files there and now I have to regenerate the files, and this would be troublesome in the future.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Firefox

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1OcHS1MMT07-4QISqVPjaex-Oi42pgyr5

**Comment by craigcitro** [comment]
Colab backends don't provide persistent storage; if you'd like files to be persisted between sessions, we recommend using Google Drive: https://colab.research.google.com/notebooks/io.ipynb#scrollTo=u22w3BFiOveA
