### ISSUE TITLE
Colab slow download

### ISSUE THREAD

**Issue by AlexGagne10** [googlecolab/colabtools#735]
I don't know why but I get a very poor downloading speed. 20 minutes to download cifar-10. That's crazy. Somebody know why on Colab I can't download a 220MB under 20 minutes and it take approx 30sec on my laptop

I use GPU and CUDA 
cifar.tgz           100%[===================>] 160.77M   254KB/s    in 15m 54s
I download the file from here: https://pjreddie.com/media/files/cifar.tgz

**Comment by Jarmos-san** [comment]
Another instance of slow download speed.

![image](https://user-images.githubusercontent.com/31373860/81170632-a4ceeb80-8fb8-11ea-93f5-01491c9cabf4.png)

**Comment by maazullah96** [comment]
I am getting the same kind of issue.
![Screenshot from 2020-10-15 15-57-37](https://user-images.githubusercontent.com/30190807/96114561-31ce8700-0eff-11eb-8861-c1420a8dab8d.png).
Can you share any solution How to  avoid this issue.

**Comment by ivallesp** [comment]
Same in my case, download starts fast but decreases over time, making impossible to download imagenet test and validation sets

**Comment by maazullah96** [comment]
I think downloading images from any site is very slow because the size of images varies from 1-10 MB based on image quality.

**Comment by maazullah96** [comment]
I ha

> Same in my case, download starts fast but decreases over time, making impossible to download imagenet test and validation sets
I have tried to download image net on my own pc and it has taken one day to download 2 lac files.Try to download zip files and then extract it.

**Comment by ivallesp** [comment]
Well I am trying to download a 10gb tarball. In an AWS instance this takes less than 5 minutes

**Comment by sven-nm** [comment]
Same issue here using Colab Pro. Downloading a ~2gb model suddenly started to take mode than 15 minutes. Any idea ?

**Comment by Sentero-esp12** [comment]
Not only couldn't I download the file, the connection timed out because I was away waiting for the file to download. Now the file is gone in the middle of the download.

**Comment by cperry-goog** [comment]
Download speeds can be affected by a number of factors that are difficult to assess. If you have a consistently slow example, please open a new bug with a minimal reproducible notebook.

**Comment by nahuelmontesino** [comment]
Try changing the runtime environment, disconnect from the current one and connect again so it assigns you another
