### ISSUE TITLE
Is Tesla T4 usage shut down for all users?

### ISSUE THREAD

**Issue by tmabraham** [googlecolab/colabtools#736]
I tried accessing GPU on my account and asked others to check as well and we are all getting K80 GPU. Is Google Colaboratory not providing anymore Tesla T4 access or is this temporary?

**Comment by sebbov** [comment]
T4s are still provided on Colaboratory but are sometimes limited in availability.  Additional restrictions may apply per our FAQ (https://research.google.com/colaboratory/faq.html, "Why are hardware resources such as T4 GPUs not available to me?").
