### ISSUE TITLE
Mount Drive Lost between colab runtimes

### ISSUE THREAD

**Issue by andhdo** [googlecolab/colabtools#737]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

I should mount google drive per notebook that i run; 

- Describe the expected behavior:

Mount drive in one notebook, and let available this dive unit to be readed in another notebooks durign the same user session; 
Previously i created just one notebook with the mount instructions, and then i execute the code block. So the authorization step just happened only once, and then i can go to every notebook to run the logic without any impediment to read the files in drive.

In recent changes of colab this does not happen: you need to include lines per notebook to mount drive, then ask for the token and then run the resto of your logic. 

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome 

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

first execute the initial notebook and run the mount cell, and then run the test on other notebook to verify the access to files in drive:
* [00_MountDatasets_gdrive.ipynb](https://colab.research.google.com/drive/1Gnxpbp6xBf2jViOdMrxZwQD0-QdGc456)
* [00_TestAccessToDrive.ipynb](https://colab.research.google.com/drive/1C-cwFLjxXPZpwkXvb3HZrYL-8qI5xxpC)

**Comment by craigcitro** [comment]
The new behavior you're seeing is the intended behavior: you shouldn't assume that two notebooks you're running concurrently will be on the same backend.
