### ISSUE TITLE
recycle after about 12hour

### ISSUE THREAD

**Issue by Roundtree-Larry** [googlecolab/colabtools#738]
Hello,
i start using Colab GPU for training my data, but after about 12hour all my data deleted for non reason.
![er](https://user-images.githubusercontent.com/54907197/64460018-42ec7800-d0f1-11e9-86bc-55d95cb8d70a.png)

**Comment by craigcitro** [comment]
This is WAI; per the [FAQ](https://research.google.com/colaboratory/faq.html):

> **Where is my code executed? What happens to my execution state if I close the browser window?**
> Code is executed in a virtual machine dedicated to your account. Virtual machines are recycled when idle for a while, and have a maximum lifetime enforced by the system.

If you'd like to persist files between runs, I'd recommend using Google Drive: https://colab.research.google.com/notebooks/io.ipynb#scrollTo=c2W5A2px3doP
