### ISSUE TITLE
TensorBoard does not scale to a proper size

### ISSUE THREAD

**Issue by lc0** [googlecolab/colabtools#747]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
![image](https://user-images.githubusercontent.com/775466/65076209-d39c4100-d998-11e9-953b-a46c2babdd9a.png)

- Describe the expected behavior:
Expect it to scale to a proper size

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome (Version 76.0.3809.132 (Official Build) (64-bit))

Yesterday I was able to reproduce on a couple accounts. Reseting environment or refreshing window did not help

Sometimes re-zooming window size helps. Ideally it shows up properly without additional actions. It used to work without any additional steps

**Comment by craigcitro** [comment]
Internal tracking:
b/140936104

**Comment by blois** [comment]
Working on a proper fix now. A workaround is to force it to resize with something like:

from IPython.display import Javascript
%tensorboard --logdir logs
display(Javascript('setTimeout(() => google.colab.output.resizeIframeToContent(), 3000)'))

You may need to tweak that number a bit.

**Comment by lc0** [comment]
@blois just resizing browser window helps as a temporary solution, at least for now :)

**Comment by lc0** [comment]
I guess this should be closed already, have not seen any issues lately. What do you think?

**Comment by blois** [comment]
Thanks for the reminder- the fix should have been live a few days after the original bug report.
