### ISSUE TITLE
CUDA_ERROR_NO_DEVICE

### ISSUE THREAD

**Issue by ramrahu** [googlecolab/colabtools#748]
Hi,
I get the following error with **tensorflow-gpu 1.0.0**. I set CUDA_VISIBLE_DEVICES to 0 as suggested in some places but that didn't help.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
E tensorflow/stream_executor/cuda/cuda_driver.cc:509] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: ea01eeb693f2
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: ea01eeb693f2
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 430.40.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:363] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  418.67  Sat Apr  6 03:07:24 CDT 2019
GCC version:  gcc version 4.9.x 20150123 (prerelease) (4.9.2_cos_gg_4.9.2-r200-ac6128e0a17a52f011797f33ac3e7d6273a9368d_4.9.2-r200) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 418.67.0
E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:303] kernel version 418.67.0 does not match DSO version 430.40.0 -- cannot find working devices in this configuration

**Comment by tnovikoff** [comment]
For tracking by colab team: b/141646271

**Comment by tnovikoff** [comment]
Unfortunately cannot pip install any version of TensorFlow you want, due to compatibility issues with CUDA versions. (The same issue applies to other libraries besides TensorFlow incidentally.) 

Colab currently comes with two versions of Colab installed, a 1.x version and a 2.x version. You can specify which of these using the following magic before you import TensorFlow:
%tensorflow_version 1.x
or 
%tensorflow_version 2.x

At any time you can see what version of TF you have imported with:
print(tensorflow.__version__)

Hope this helps!
