### ISSUE TITLE
Disconnection within a minute or two

### ISSUE THREAD

**Issue by puffgit** [googlecolab/colabtools#752]
It keeps disconnecting itself when I choose GPU and Python 3 , connection lasts till a minute or two and then it just disconnects and keeps disconnecting even after several tries. It wasn't happening a week ago, don't know what's causing it.

**Comment by 2000222** [comment]
I have the same issue and can not connect the backend of GPU in colab.....
I am so sad for my projects ----------

**Comment by JojoReikun** [comment]
Same for me. 
I am using the deeplabcut toolbox and it worked last week, but when I try to run the same code now, the session crashes repeatedly and I can't reconnect.

**Comment by Karansaluja** [comment]
Same issue. I have been paying for Colab Pro for the last two months, even then, there is not a single instance that I've been able to train a model. It is so unpredictable. Disconnection happens at any moment.
