### ISSUE TITLE
Parameter Hint Box

### ISSUE THREAD

**Issue by subhajitmajumder** [googlecolab/colabtools#753]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Parameter Hint Box is sometimes getting very frustrating.During typing it floats through out the screen and I cant see whatever I am typing.It needs to get fix immediately.
- Describe the expected behavior:
Fix this problem and make the box smaller and scrollable.
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
![Screenshot (24)](https://user-images.githubusercontent.com/47553180/65371186-9f699e80-dc7e-11e9-9da3-2d7002baea1a.png)

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment]
You can hit ESC to dismiss the box if it's annoying you.

If you'd prefer not to have the popup, `Tools` -> `Preferences` -> `Editor` -> disable `Automatically trigger code completions` and you'll have something similar to the previous behavior (no completion/parameter popups until you hit a key to bring them up).
