### ISSUE TITLE
[often] some files are not mounting from google drive even the file is present

### ISSUE THREAD

**Issue by santhoshBjeeffy** [googlecolab/colabtools#754]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by rahul-t-p** [comment]
It happened to me as well. I was training a model using catalyst and saved some checkpoints in the drive. Then when I tried to load those checkpoints I couldn't. But the files are present in drive.google.com. I use Firefox.

**Comment by santhoshBjeeffy** [comment]
Hi @rahul-t-p ,

The issue got fixed for me after moving the files to another folder in a drive...
