### ISSUE TITLE
shortcut to insert code cell not working

### ISSUE THREAD

**Issue by j-donahue** [googlecolab/colabtools#756]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
Recently, Colab asked me if I wanted to try a new version of Colab with additional features, so I accepted. Several shortcuts that I created worked on the old Colab version but not this one (the shortcuts are still defined, I checked). Namely: "Insert Code Cell Above", "Insert Code Cell Below", "Add Code Cell".

- Describe the expected behavior:
In the past, I've used "Ctrl+Shift+Up" to insert code cell above, and "Ctrl+Shift+Down" to insert code cell below. I've tried redefining the shortcut to a few variants like "Ctrl+Up", "Ctrl+Down", but the issue persists. 

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

**Comment by blois** [comment]
Editor keyboard preferences are taking precedence when the focus is in the editor- in this case ctrl-shift-up is the shortcut for extending multi-cursor lines.

You should be able to press escape once to exit cell edit mode then use ctrl-shift-up/down to insert a new cell.
