### ISSUE TITLE
JavaScript not working on Colab

### ISSUE THREAD

**Issue by cbrionesr** [googlecolab/colabtools#757]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior: I've been using Colab for a while now and never had issues, but suddenly today it started throwing an error. It says:

**Error**
Could not load the JavaScript files needed to display output. 
This is probably because your Google account login access has expired or because third-party cookies are not allowed by your browser. 

Please reload this page. 

(Uploaded a picture of error...) None of the two possible problems that says it's true.. my google account access has not expired and I have 3rd paty cookie enabled.. I restarted chrome, disabled/enables 3rd party cookies and login again.. nothing works. 

- Describe the expected behavior: It should read the script perfectly (Using a notebook in Python 3)... it has done it several times and i don't understand why 

- The web browser you are using (Chrome, Firefox, Safari, etc.): Google Chrome latest version

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/drive/1-8KpjrPLoZ6Bhvip6LcIBGSsk0adATNl

![Error_Colab](https://user-images.githubusercontent.com/42191393/65472207-b825b000-de48-11e9-97dd-6407f0a0b036.PNG)

**Comment by mouadriyad** [comment]
Same problem + it uses all my laptop ram => crash

**Comment by blois** [comment]
Looking at that notebook it looks like many of the plotly graphs are consuming large amounts of CPU and memory. The outputs will only be rendered when they are scrolled into view, so I can open Chrome's task manager and watch the CPU and memory increase while scrolling through. In a fresh browser session I'm seeing it get up to 2GB of RAM for that renderer process. 

The error dialog you're seeing is because the frames are going unresponsive because of how much CPU they are using (the memory pressure isn't helping).

The workarounds for this would be to either break the single notebook up into separate notebooks with fewer outputs or see if you can reduce the complexity of the plotly graphs (they appear to be the primary source of the issue).

**Comment by Alexyjones** [comment]
I do get a similar error, when running a cell in my colab. Even loading just some library results in this error. I tried to log in and out, using a private tab and also other browsers. Even uninstalling all extensions did not change this behavior. 
I am using Safari 13 now. 
This error just appeared about 2 weeks ago and has persisted since. 

Any help how I can trace this error would be greatly appreciated!

Thanks!

**Comment by blois** [comment]
@Alexyjones - I'm unable to repro issues with Safari 13, but about 2 weeks ago did make some changes specifically to fix some Safari issues specifically in this area. 

Can you try using a Private window? Also I'm curious if you can think of any other extensions or settings which may cause problems.

**Comment by Alexyjones** [comment]
@blois Thank you for the quick response. I have tried a private window and reproduced the error. I could share the colab if it helps (just not publicly). I got the "feeling" that it is tied to my google account...

![Prvt_Win_error](https://user-images.githubusercontent.com/45836874/66617133-616cf400-ec06-11e9-8d86-a374e6e915db.png)

**Comment by Keramatfar** [comment]
I have the same problem.

**Comment by Alexyjones** [comment]
I just observed that it might be a network issue - The error appears only in my company network (which is restrictive, many ports blocked), but is resolved, when I use my mobile network.

**Comment by QuantumNinja92** [comment]
It only started occurring recently, and more frequent on GPU environment.
so network, cookies, OS restart ? Any actual cause cause its troublesome with long running models.

**Comment by Alexyjones** [comment]
Sometimes using an unfiltered access to the internet helped. Check if there
are port restrictions.

Am Mo., 6. Juli 2020 um 11:07 Uhr schrieb Ramzy Karam <
notifications@github.com>:

**Comment by QuantumNinja92** [comment]
Hi Alex,
I am using Incognito mode and it hasn't got the error so far.

**Comment by Ahmad-noborders** [comment]
hey @blois i had the same error but the cell is still running. i am expecting that the cell will complete execution even after error and i should wait. or should i cancel it because it?

**Comment by blois** [comment]
If the code is still running and you get this error then you can try moving the cell up/down using the arrows on the cell toolbar-this will cause the output to re-render itself. If the error is caused by a spinning output then you may need to first kill the task using Chrome's Task Manager, then move the cell up/down to re-render it.

If you have something which consistently repro's this then I'd be interested in diving into what is causing it.

**Comment by QuantumNinja92** [comment]
My scenario is an 8-10 hours training, after the training the model is saved and sent to google drive.
The below solution works perfectly for me as long as you didn't exceed the 12 hours, used incognito mode, and before the session connects allow cookies.
https://stackoverflow.com/a/60388275/2791816

**Comment by Ahmad-noborders** [comment]
thank you @blois for our reply actually my drive space was full and it was unable to write data on drive i thin this caused the problem. i freed up space and it is all good now,

**Comment by Ahmad-noborders** [comment]
@QuantumNinja92 ye in my case it was around 6 hours training

**Comment by KimYonghyun94** [comment]
I goto a same error on colab, but colab is working on ipad even same googleID.
Only Windows and Linux got this error on colab, also my google profile and googledrive icon(?) image(?) were broken..... how can i solve the problem?

**Comment by JonathanSum** [comment]
Here is my guess. Every time I train something that is GANs, this always happens. Is it possible that Google does not want you to keep using their GPU? TBH.

**Comment by Ceceu** [comment]
> Bug report for Colab: http://colab.research.google.com/.
> 
> * Describe the current behavior: I've been using Colab for a while now and never had issues, but suddenly today it started throwing an error. It says:
> 
> **Error**
> Could not load the JavaScript files needed to display output.
> This is probably because your Google account login access has expired or because third-party cookies are not allowed by your browser.
> 
> Please reload this page.
> 
> (Uploaded a picture of error...) None of the two possible problems that says it's true.. my google account access has not expired and I have 3rd paty cookie enabled.. I restarted chrome, disabled/enables 3rd party cookies and login again.. nothing works.
> 
> * Describe the expected behavior: It should read the script perfectly (Using a notebook in Python 3)... it has done it several times and i don't understand why
> * The web browser you are using (Chrome, Firefox, Safari, etc.): Google Chrome latest version
> * Link to self-contained notebook that reproduces this issue
>   (click the _Share_ button, then _Get Shareable Link_): https://colab.research.google.com/drive/1-8KpjrPLoZ6Bhvip6LcIBGSsk0adATNl
> 
> ![Error_Colab](https://user-images.githubusercontent.com/42191393/65472207-b825b000-de48-11e9-97dd-6407f0a0b036.PNG)

Any solution?

**Comment by Echo9k** [comment]
None of these worked for me.
- I tried terminating the environment,
- Doing a factory reset, 
- Restarting chrome,
- Restarting my laptop,
- Cleaning cookies for Colab, nor for everything in the last 24 hours.
- A different browser (Google Chrome beta, Brave browser)
- Using a local environment and it's not working.
- Coincidently I started using a VPN in between, and yet it wasn't working.

It was working yesterday before my environment ran out of RAM. Perhaps it's something wrong with Colab?

**Comment by brianferrell787** [comment]
> “None of these worked for me.
> 
> * I tried terminating the environment,
> * Doing a factory reset,
> * Restarting chrome,
> * Restarting my laptop,
> * Cleaning cookies for Colab, and for everything in the last 24 hours.
> * Using a different browser (Google Chrome beta, Brave browser)
> * Using Colab with a Local Host.
> * Coincidently I started using a VPN in between and yet it wasn't working.
> 
> It was working yesterday before my environment ran out of RAM. Perhaps it's something wrong with Colab?”


Do you have too many cells open on your Colab that aren’t needed? Start a new notebook with just the cells you need or get rid of them.

**Comment by Echo9k** [comment]
None of these worked for me.
- I tried terminating the environment,
- Doing a factory reset, 
- Restarting chrome,
- Restarting my laptop,
- Cleaning cookies for Colab, nor for everything in the last 24 hours.
- A different browser (Google Chrome beta, Brave browser)
- Using a local environment and it's not working.
- Coincidently I started using a VPN in between, and yet it wasn't working.

It was working yesterday before my environment ran out of RAM. Perhaps it's something wrong with Colab?

> > “None of these worked for me.
> > 
> > * I tried terminating the environment,
> > * Doing a factory reset,
> > * Restarting chrome,
> > * Restarting my laptop,
> > * Cleaning cookies for Colab, and for everything in the last 24 hours.
> > * Using a different browser (Google Chrome beta, Brave browser)
> > * Using Colab with a Local Host.
> > * Coincidently I started using a VPN in between and yet it wasn't working.
> > 
> > It was working yesterday before my environment ran out of RAM. Perhaps it's something wrong with Colab?”
> 
> Do you have too many cells open on your Colab that aren’t needed? Start a new notebook with just the cells you need or get rid of them.

I'd not say so, you can check it here.
https://colab.research.google.com/drive/1YMKWa2so2AESmQth77Kd8pJbd1TfTzxs?usp=sharing
While I was making a few changes to share it with you I got the error and it's not even running.

**Comment by xtshanlei** [comment]
I happened to meet the issue today.
**Deleting the coding block and its output worked for me.** 
I tried to predict using a trained model and the error occurred. I've tried everything and nothing can help. At last, I deleted the coding block for the prediction and everything went back to normal.

**Comment by nollied** [comment]
can this be bumped?

**Comment by SidSensei** [comment]
Try disabling pop-up block or adblock extension, if you have any. 
It worked for me.

**Comment by AkshayAshok2** [comment]
I am having a similar issue in 2023. Was working fine until a couple of days ago then started throwing that same error. @cbrionesr has this been resolved for you?

**Comment by ramah-madi** [comment]
I was having the same issue and the fix number " 9 " on this site worked for me : 
https://helpdeskgeek.com/help-desk/9-fixes-when-images-not-loading-in-chrome/

**Comment by AkshayAshok2** [comment]
@ramah-madi This worked! Thank you!!

**Comment by cperry-goog** [comment]
Consolidating javascript errors to #4427
