### ISSUE TITLE
Python memory consumption issue.

### ISSUE THREAD

**Issue by niranjan-sa** [googlecolab/colabtools#758]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: I can see that for same data set, Scikit-learn's LabelEncoder is using far more resources than Kaggle kernels. It's also taking too long to execute. Can you please look into this? Thanks.

- Describe the expected behavior: I think that memory consumption for a particular task (for same input and same algorithm) should be fairly similar/consistent in similar environments. I can see a piece of code run in much less RAM on Kaggle Kernels than Colab. I would find similar memory consumption as ideal case. Thanks.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*): Will share in a while. Thanks.

**Comment by tnovikoff** [comment]
The notebook will be most helpful. Thanks!

**Comment by metrizable** [comment]
@niranjan-sa Since this issue was filed a while ago, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
