### ISSUE TITLE
I get error message No GPU available of any type...

### ISSUE THREAD

**Issue by jaideep11061982** [googlecolab/colabtools#759]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Suddenly my notebook got disconnected and couldnt reconnect with error message No GPU available.
- Describe the expected behavior:
I read in FAQ that high end gpu can get temporarily unavailable but atleast k80 should always be available.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1sChU8cwCNegfR9ZYk6W-1DjFKV1eEp-k

**Comment by sebbov** [comment]
The FAQ entry you are referring to does not state that k80s should always be available.  It talks about different types of hardware (GPU in this case) in general.  When this happens, try a CPU instance instead; or a GPU one a day later.
