### ISSUE TITLE
Connection Problem with Multiple Google Accounts

### ISSUE THREAD

**Issue by akuzubasli** [googlecolab/colabtools#76]
Hi, 

I have two google accounts, one of them is a personal/free google account and the other is a G-Suite for my startup.

I cannot connect a CoLab session. However, if I open a incognito tab and login with my personal account, then I can connect and work on my project.

Best regards.

**Comment by blois** [comment]
We are working on multi-login support right now, recommendation is to use an incognito tab in the meantime.

**Comment by blois** [comment]
Multi-login support has rolled out.
