### ISSUE TITLE
Copy Matplotlib Figure Plot Output to Clipboard (MacOS/Chrome)

### ISSUE THREAD

**Issue by gaitskell** [googlecolab/colabtools#760]
Bug report for Colab: http://colab.research.google.com/.

A "Right-Click" or Ctl-Click on a figure output from Matplotlib (graphic) does not allow the copying (via menu) of the plot to the clipboard. There is also no way to select the figure output and then (Cmd-C) copy the figure.

I would expect to be able to copy (and then paste elsewhere) the figures from my Colab session. (At present I have to rely on screenshots which is a very crude way of achieving this.) I would like to have the option to copy the figure image as either a bitmap or as vector. The standard container would be a PDF. 

Using MacOS Chrome with Colab Beta
Example noteboook:
https://colab.research.google.com/drive/1NOZlpVeffKutq6nnnxvcAsawwPGVBYzk

**Comment by gaitskell** [comment]
I should clarify that I am using the Colab New Code Editor. 

Also, the CTL-Click > Copy Image works occasionally (placing the figure in the clipboard) but not reliably. I cannot work out what the correct procedure is to make it work reproducibly.

**Comment by tnovikoff** [comment]
For what it's worth, I find that if I CTL-Click an image in your notebook, and then select Save Image As, I can save the image to the desktop. That's not exactly what you're asking about, but it gets the job done and is less crude than screenshots. :-) I find it works every time, although while the menu is showing I often find that more than the image looks like it's "selected" – but still only the output image I CTL-Clicked on actually gets saved.

**Comment by tnovikoff** [comment]
(Once I've saved the image then I can do whatever I need with it, including copying it to the clipboard by CTL-clicking on the file on my desktop.)
