### ISSUE TITLE
Upgrade PyTorch to v1.2.0 and TorchVision to v0.4.0

### ISSUE THREAD

**Issue by soumith** [googlecolab/colabtools#762]
Hi folks,

We released a new PyTorch version v1.2. We'd released it a few weeks ago but forgot to open an issue, sorry about that.

The wheel links are:

**PyTorch**

CUDA 9.2

https://download.pytorch.org/whl/cu92/torch-1.2.0%2Bcu92-cp27-cp27m-manylinux1_x86_64.whl
https://download.pytorch.org/whl/cu92/torch-1.2.0%2Bcu92-cp27-cp27mu-manylinux1_x86_64.whl
https://download.pytorch.org/whl/cu92/torch-1.2.0%2Bcu92-cp36-cp36m-manylinux1_x86_64.whl

CUDA 10.0

https://download.pytorch.org/whl/cu100/torch-1.2.0-cp27-cp27m-manylinux1_x86_64.whl
https://download.pytorch.org/whl/cu100/torch-1.2.0-cp27-cp27mu-manylinux1_x86_64.whl
https://download.pytorch.org/whl/cu100/torch-1.2.0-cp36-cp36m-manylinux1_x86_64.whl

**TorchVision**

CUDA 9.2

https://download.pytorch.org/whl/cu92/torchvision-0.4.0%2Bcu92-cp27-cp27m-manylinux1_x86_64.whl
https://download.pytorch.org/whl/cu92/torchvision-0.4.0%2Bcu92-cp27-cp27mu-manylinux1_x86_64.whl
https://download.pytorch.org/whl/cu92/torchvision-0.4.0%2Bcu92-cp36-cp36m-manylinux1_x86_64.whl

CUDA 10.0

https://download.pytorch.org/whl/cu100/torchvision-0.4.0-cp27-cp27m-manylinux1_x86_64.whl
https://download.pytorch.org/whl/cu100/torchvision-0.4.0-cp27-cp27mu-manylinux1_x86_64.whl
https://download.pytorch.org/whl/cu100/torchvision-0.4.0-cp36-cp36m-manylinux1_x86_64.whl

We're looking to having it updated in Colab.

Thanks very much.

cc'ing @colaboratory-team on the suggestion of Ami

**Comment by colaboratory-team** [comment]
b/141656482

**Comment by colaboratory-team** [comment]
Pre-installed PyTorch and TorchVision versions in colab are now updated.
(if you're still seeing old versions in the next day or so it's probably because you still have a VM assigned from before the update; "Reset all runtimes" to get assigned a post-update VM)

**Comment by soumith** [comment]
thanks so much!
