### ISSUE TITLE
Unable to read content of file with view permissions

### ISSUE THREAD

**Issue by jakepezaro** [googlecolab/colabtools#763]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:  When trying to read the content of a file for which I have view permissions I get the error:  FileNotFoundError: [Errno 2] No such file or directory: '/content/gdrive/My Drive/test.txt'.  Note that os.path.isfile('/content/gdrive/My Drive/test.txt') returns true, so the file _should_ be available

- Describe the expected behavior:  I expect that I am able to read the contents of the file

- The web browser you are using (Chrome, Firefox, Safari, etc.):  Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):  https://colab.research.google.com/drive/1Ax1yKjAUJnXK4V3IDbVg1txbtdteBQy-

![image](https://user-images.githubusercontent.com/8840200/65657287-571ef780-e055-11e9-80a2-aff0a9abb498.png)

**Comment by colaboratory-team** [comment]
Thanks for the report. Are you able to download the file from drive.google.com ?
Are you the owner of the file, or was it shared with you?
If shared with you, are both you and the owner using @gmail.com accounts?

**Comment by jakepezaro** [comment]
The file was shared with "disable copying and downloading", so I cannot download it from drive.  

The owner of the file is my work account @indeed.com, and the recipient is my personal account (@gmail.com).

**Comment by jakepezaro** [comment]
I think this might be a difference in assumptions.  

My assumption is that if I can `view` in drive but not copy or download then I should also be able to `read` in colab because colab read is like drive view.

Perhaps the colab assumption is that colab read is like drive copy/download, not like drive view?

**Comment by colaboratory-team** [comment]
Right; reading in colab is equivalent to download in terms of permissions.
Thanks for clarifying.
