### ISSUE TITLE
Google Drive Time out issue for parsing files from Drive

### ISSUE THREAD

**Issue by achyuta26** [googlecolab/colabtools#766]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I'm trying to run a GitHub project and I have mounted the data files on Drive. While running the instructions for preprocessing the data, I'm getting the time out.
- Describe the expected behavior:
Even though it creates the pickle files as expected, the files are empty.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1etmzgAZzjzSVourEQpNZaFZqkgDRVw21

**Comment by vk1996** [comment]
Issues in unzipping files from google drive to colab. But I'm able write files from colab to Google drive.

**Comment by achyuta26** [comment]
I'm too able to write to Google Drive using Colab but the files that get written onto it are empty.
