### ISSUE TITLE
pytest defaults to python 2.7 in python 3 notebook

### ISSUE THREAD

**Issue by beli** [googlecolab/colabtools#767]
When I run 
```
pytest --version
```
in a cell in a python 3 notebook, it returns
```
This is pytest version 3.6.4, imported from /usr/local/lib/python2.7/dist-packages/pytest.pyc
```
Some python 3 features are missing from this - it raises an error for type annotations in the code, for example.

See notebook : https://colab.research.google.com/drive/1gZQCJEhPNXmZHmffQXxYcknpbHmSxhPX

I'm using Google Chrome Version 78.0.3904.35 (Official Build) dev (64-bit).

**Comment by craigcitro** [comment]
This is WAI (though it will flip soonish).

You can run

    !python -m pytest --version

and you'll get the py3 version.
