### ISSUE TITLE
Tab completion for insertion of Unicode math from LaTeX names only partially replaces name

### ISSUE THREAD

**Issue by jmbejara** [googlecolab/colabtools#77]
In the colab notebook, when I try to insert a Unicode character from its LaTeX name using the code suggestion, the notebook enters the character incorrectly, overwriting only partially over the LaTeX name. For example, when I type `\psi` into the notebook and press tab, the notebook suggest the Unicode character. This is shown here: 

![image](https://user-images.githubusercontent.com/3770323/37072896-45ddb43e-2189-11e8-8038-a4370af39827.png)

When I then press tab again (or return), the Unicode character is inserted. However, it only partially replaces the previous code, as shown here: 
![image](https://user-images.githubusercontent.com/3770323/37072782-ce42fd4e-2188-11e8-8afc-a91ca549a01b.png)

My expectation is that this would be fully replaced, like so:

![image](https://user-images.githubusercontent.com/3770323/37072881-2f943bbc-2189-11e8-9c36-08dbd6725d36.png)

I'm using Chrome Version 64.0.3282.186 (Official Build) (64-bit) on Windows 10.

Thanks!

**Comment by colaboratory-team** [comment]
b/124757378

**Comment by metrizable** [comment]
I just tested this and it's been fixed. Closing.
