### ISSUE TITLE
vim

### ISSUE THREAD

**Issue by khaliunch** [googlecolab/colabtools#770]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by katlyn-edwards** [comment]
Vim support is already present for the new editor: https://twitter.com/GoogleColab/status/1156980030276161537
