### ISSUE TITLE
Unable to create file on Drive using Google Colaboratory

### ISSUE THREAD

**Issue by gabrielcustodio** [googlecolab/colabtools#771]
Bug report for Colab: http://colab.research.google.com/.

Why? Is there a quota for save directly on Drive?
It is a correct path. 
I was not getting this error. But it started from nothing.

```
from google.colab import drive
import os
drive.mount('/content/drive')
```
```
Epoch 00001: val_loss improved from inf to 9.17905, saving model to /content/drive/My Drive/model.h5
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-44-7f3664bdd269> in <module>()
      5     validation_steps=(val_gen.samples / BATCH_SIZE) * 0.2,
      6     callbacks=[checkpoint, rle, el],
----> 7     epochs=50
      8 )

10 frames
/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    146         fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
    147     elif mode == 'w':
--> 148         fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
    149     elif mode == 'a':
    150         # Open in append mode (read/write).

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.create()

OSError: Unable to create file (unable to open file: name = '/content/drive/My Drive/model.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)
```

I am using Chrome browser.

**Comment by gabrielcustodio** [comment]
After, I solved this re-run drive.mount('/content/drive')

**Comment by Talluripavan** [comment]
### Sir please tell me how to solve this problem!

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
h5py/h5f.pyx in h5py.h5f.create()
OSError: Unable to create file (unable to open file: name = '/content/drive/My Drive/model.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)**

**Comment by Talluripavan** [comment]
> After, I solved this re-run drive.mount('/content/drive')

sir please tell me how to solve this issue?

**Comment by kkb786** [comment]
@Talluripavan remount the drive, I didn't understand this in the beginning, but remounting the drive fixed my error
