### ISSUE TITLE
Running two notebooks in the same runtime environment.

### ISSUE THREAD

**Issue by manojneuro** [googlecolab/colabtools#773]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Currently, the run time environment gets reset for every notebook that we open (see screenshot):
![image](https://user-images.githubusercontent.com/26097457/66213829-886b7900-e68e-11e9-8974-7d156ffaca16.png)

- Describe the expected behavior:
Earlier, there was a check box that allowed us to choose if the runtime environment needs to be reset (see screenshot below). This allowed us to open and run a second notebook based on the installation of the first notebook, without having to reinstall packages.

![image](https://user-images.githubusercontent.com/26097457/66214040-ec8e3d00-e68e-11e9-934c-720e03cc6d51.png)

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/github/brainiak/brainiak-tutorials/blob/master/tutorials/colab-env-setup.ipynb

**Comment by craigcitro** [comment]
This is no longer possible.
