### ISSUE TITLE
Normal tables can't be loaded.

### ISSUE THREAD

**Issue by luochonghai** [googlecolab/colabtools#78]
I run the following codes:
#########################
import math  
import pandas as pd
import numpy as np
import tensorflow as tf

from IPython import display  
from matplotlib import cm  
from matplotlib import gridspec
from matplotlib import pyplot as plt
from sklearn import metrics
from tensorflow.python.data import Dataset

tf.logging.set_verbosity(tf.logging.ERROR)
pd.options.display.max_rows = 10
pd.options.display.float_format = '{:.lf}'.format

chds = pd.read_csv("https://storage.googleapis.com/mledu-datasets/california_housing_train.csv", sep=",")
chds.describe()
######################################
and got error:
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    697                 type_pprinters=self.type_printers,
    698                 deferred_pprinters=self.deferred_printers)
--> 699             printer.pretty(obj)
    700             printer.flush()
    701             return stream.getvalue()

/usr/local/lib/python3.6/dist-packages/IPython/lib/pretty.py in pretty(self, obj)
    396                             if callable(meth):
    397                                 return meth(obj, self, cycle)
--> 398             return _default_pprint(obj, self, cycle)
    399         finally:
    400             self.end_group()

/usr/local/lib/python3.6/dist-packages/IPython/lib/pretty.py in _default_pprint(obj, p, cycle)
    516     if _safe_getattr(klass, '__repr__', None) not in _baseclass_reprs:
    517         # A user-provided repr. Find newlines and replace them with p.break_()
--> 518         _repr_pprint(obj, p, cycle)
    519         return
    520     p.begin_group(1, '<')

/usr/local/lib/python3.6/dist-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    707     """A pprint that just redirects to the normal repr function."""
    708     # Find newlines and replace them with p.break_()
--> 709     output = repr(obj)
    710     for idx,output_line in enumerate(output.splitlines()):
    711         if idx:

/usr/local/lib/python3.6/dist-packages/pandas/core/base.py in __repr__(self)
     78         Yields Bytestring in Py2, Unicode String in py3.
     79         """
---> 80         return str(self)
     81 
     82 

/usr/local/lib/python3.6/dist-packages/pandas/core/base.py in __str__(self)
     57 
     58         if compat.PY3:
---> 59             return self.__unicode__()
     60         return self.__bytes__()
     61 

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py in __unicode__(self)
    634             width = None
    635         self.to_string(buf=buf, max_rows=max_rows, max_cols=max_cols,
--> 636                        line_width=width, show_dimensions=show_dimensions)
    637 
    638         return buf.getvalue()

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py in to_string(self, buf, columns, col_space, header, index, na_rep, formatters, float_format, sparsify, index_names, justify, line_width, max_rows, max_cols, show_dimensions)
   1673                                            max_cols=max_cols,
   1674                                            show_dimensions=show_dimensions)
-> 1675         formatter.to_string()
   1676 
   1677         if buf is None:

/usr/local/lib/python3.6/dist-packages/pandas/io/formats/format.py in to_string(self)
    595         else:
    596 
--> 597             strcols = self._to_str_columns()
    598             if self.line_width is None:  # no need to wrap around just print
    599                 # the whole frame

/usr/local/lib/python3.6/dist-packages/pandas/io/formats/format.py in _to_str_columns(self)
    530                 header_colwidth = max(self.col_space or 0,
    531                                       *(self.adj.len(x) for x in cheader))
--> 532                 fmt_values = self._format_col(i)
    533                 fmt_values = _make_fixed_width(fmt_values, self.justify,
    534                                                minimum=header_colwidth,

/usr/local/lib/python3.6/dist-packages/pandas/io/formats/format.py in _format_col(self, i)
    706         return format_array(values_to_format, formatter,
    707                             float_format=self.float_format, na_rep=self.na_rep,
--> 708                             space=self.col_space, decimal=self.decimal)
    709 
    710     def to_html(self, classes=None, notebook=False, border=None):

/usr/local/lib/python3.6/dist-packages/pandas/io/formats/format.py in format_array(values, formatter, float_format, na_rep, digits, space, justify, decimal)
   1820                         space=space, justify=justify, decimal=decimal)
   1821 
-> 1822     return fmt_obj.get_result()
   1823 
   1824 

/usr/local/lib/python3.6/dist-packages/pandas/io/formats/format.py in get_result(self)
   1840 
   1841     def get_result(self):
-> 1842         fmt_values = self._format_strings()
   1843         return _make_fixed_width(fmt_values, self.justify)
   1844 

/usr/local/lib/python3.6/dist-packages/pandas/io/formats/format.py in _format_strings(self)
   2026         # shortcut
   2027         if self.formatter is not None:
-> 2028             return [self.formatter(x) for x in self.values]
   2029 
   2030         return list(self.get_result_as_array())

/usr/local/lib/python3.6/dist-packages/pandas/io/formats/format.py in <listcomp>(.0)
   2026         # shortcut
   2027         if self.formatter is not None:
-> 2028             return [self.formatter(x) for x in self.values]
   2029 
   2030         return list(self.get_result_as_array())

ValueError: Format specifier missing precision
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    336             method = get_real_method(obj, self.print_method)
    337             if method is not None:
--> 338                 return method()
    339             return None
    340         else:

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py in _repr_html_(self)
    667 
    668             return self.to_html(max_rows=max_rows, max_cols=max_cols,
--> 669                                 show_dimensions=show_dimensions, notebook=True)
    670         else:
    671             return None

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py in to_html(self, buf, columns, col_space, header, index, na_rep, formatters, float_format, sparsify, index_names, justify, bold_rows, classes, escape, max_rows, max_cols, show_dimensions, notebook, decimal, border)
   1732                                            decimal=decimal)
   1733         # TODO: a generic formatter wld b in DataFrameFormatter
-> 1734         formatter.to_html(classes=classes, notebook=notebook, border=border)
   1735 
   1736         if buf is None:

/usr/local/lib/python3.6/dist-packages/pandas/io/formats/format.py in to_html(self, classes, notebook, border)
    731                                       border=border)
    732         if hasattr(self.buf, 'write'):
--> 733             html_renderer.write_result(self.buf)
    734         elif isinstance(self.buf, compat.string_types):
    735             with open(self.buf, 'w') as f:

/usr/local/lib/python3.6/dist-packages/pandas/io/formats/format.py in write_result(self, buf)
   1214         indent += self.indent_delta
   1215         indent = self._write_header(indent)
-> 1216         indent = self._write_body(indent)
   1217 
   1218         self.write('</table>', indent)

/usr/local/lib/python3.6/dist-packages/pandas/io/formats/format.py in _write_body(self, indent)
   1370         fmt_values = {}
   1371         for i in range(min(len(self.columns), self.max_cols)):
-> 1372             fmt_values[i] = self.fmt._format_col(i)
   1373 
   1374         # write values

/usr/local/lib/python3.6/dist-packages/pandas/io/formats/format.py in _format_col(self, i)
    706         return format_array(values_to_format, formatter,
    707                             float_format=self.float_format, na_rep=self.na_rep,
--> 708                             space=self.col_space, decimal=self.decimal)
    709 
    710     def to_html(self, classes=None, notebook=False, border=None):

/usr/local/lib/python3.6/dist-packages/pandas/io/formats/format.py in format_array(values, formatter, float_format, na_rep, digits, space, justify, decimal)
   1820                         space=space, justify=justify, decimal=decimal)
   1821 
-> 1822     return fmt_obj.get_result()
   1823 
   1824 

/usr/local/lib/python3.6/dist-packages/pandas/io/formats/format.py in get_result(self)
   1840 
   1841     def get_result(self):
-> 1842         fmt_values = self._format_strings()
   1843         return _make_fixed_width(fmt_values, self.justify)
   1844 

/usr/local/lib/python3.6/dist-packages/pandas/io/formats/format.py in _format_strings(self)
   2026         # shortcut
   2027         if self.formatter is not None:
-> 2028             return [self.formatter(x) for x in self.values]
   2029 
   2030         return list(self.get_result_as_array())

/usr/local/lib/python3.6/dist-packages/pandas/io/formats/format.py in <listcomp>(.0)
   2026         # shortcut
   2027         if self.formatter is not None:
-> 2028             return [self.formatter(x) for x in self.values]
   2029 
   2030         return list(self.get_result_as_array())

ValueError: Format specifier missing precision

**Comment by craigcitro** [comment]
You've got a typo in your format specifier: you should have `1` instead of `l`, so 

    pd.options.display.float_format = '{:.1f}'.format
