### ISSUE TITLE
google.colab.files.upload kills Chrome

### ISSUE THREAD

**Issue by smith-kyle** [googlecolab/colabtools#79]
Runtime: Python 3 with GPU

Executing the following line locks up Chrome:
```python
from google.colab import files
uploaded = files.upload()
```
 I'm prompted by Chrome to either wait for the page to become responsive or to kill the tab.

After killing the tab then reopening the notebook it's stuck in a permanent "Initializing" state.

**Comment by smith-kyle** [comment]
I created a copy of the notebook and the problem has fixed itself.

This might be unrelated to google.colab.files. Maybe just instability of Colaboratory?

I'll just close this out.

**Comment by blois** [comment]
Chrome version? May also be worth trying out incognito tabs- sometimes extensions can cause issues as well.

**Comment by smith-kyle** [comment]
64.0.3282.167 (Official Build) (64-bit)
