### ISSUE TITLE
shortcuts for snippets

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#792]
Consider this scenario,

1) I created a snippet for something that I use often, it could be, something like 
`from IPython.core.debugger import set_trace`
or
a neural network architecture and so on
2) now in order to access this, I need to 
    a) press one shortcut for seeing all snippets
    b) search for particular snippet I want to use
    c) select that snippet

what could have been done,

give a custom shortcut creation option, for saved snippets, so that I press one shortcut for
a snippet that I use often, and do not need to see all snippets, then search, then select.

so I could set a shortcut for a particular snippet, for example, assume I have saved

`from IPython.core.debugger import set_trace` as a snippet, with title debug,

so an option to create a shortcut for this particular snippet based on its title, and then I would press that shortcut, and this snippet would appear in the current notebook I am using.

**Comment by tnovikoff** [comment]
Tracking feature request internally at b/143781845
