### ISSUE TITLE
Problem loading notebook code from github: $arg1$arg2 

### ISSUE THREAD

**Issue by jaderabbit** [googlecolab/colabtools#793]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:

A paragraph which has a bash command: `! echo $arg1$arg2` on loading, will take $arg1$ as a formatting command, so _arg1_ will be boldened and italic, and the dollar signs will disappear - It is the same as when using $arg1$ in the "Text" cells. 

![image](https://user-images.githubusercontent.com/5547095/66254765-597f0100-e77b-11e9-8c44-8e5ab0765988.png)

- Describe the expected behavior:

The code cells should not interpret the $arg1$ as a formatting instruction, when loading from github

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
Load the following notebook from github into colab: https://github.com/jaderabbit/colab-bug-example

**Comment by craigcitro** [comment]
I don't see the behavior you're seeing:

![image](https://user-images.githubusercontent.com/468559/66257747-c41b4700-e751-11e9-82e1-0c33bddd99c9.png)

Can you confirm this repros in an incognito window?

**Comment by jaderabbit** [comment]
This doesn't happen in incognito window, 
I tried to confirm with a different arround and was still able to replicate it. That's strange

**Comment by craigcitro** [comment]
If you're seeing this in chrome, but *not* in an incognito window, that almost surely means you've got an extension in play that's causing the problem. I'd try selectively disabling extensions to track it down.
