### ISSUE TITLE
Unable to load Colaboratory. Error loading https://apis.google.com/js/client.js Error: Error loading https://apis.google.com/js/client.js     at HTMLScriptElement.k.onerror (https://colab.research.google.com/v2/external/gapi_loader.js:9:415)

### ISSUE THREAD

**Issue by ankit-patel-1404** [googlecolab/colabtools#795]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by blois** [comment]
See https://github.com/googlecolab/colabtools/issues/981
