### ISSUE TITLE
Do you know why Google Colab is not plotting the charts today? I've been using it all these days and the graphics looked, but not now...  matplotlib.pyplot

### ISSUE THREAD

**Issue by Wittline** [googlecolab/colabtools#798]

**Comment by Wittline** [comment]
> Do you have an example notebook?
> 
> Does this example work? https://colab.research.google.com/notebooks/charts.ipynb#scrollTo=08RTGn_xE3MP&line=11&uniqifier=1

I changed the python execution environment from 2 to 3 and it worked, and then I went back to 3 again. After that, all the charts appeared again. :)

**Comment by blois** [comment]
Typically 'Reset runtime' will fix issues where the kernel gets into an odd state.
