### ISSUE TITLE
Restore the python environment

### ISSUE THREAD

**Issue by tonyyeung99** [googlecolab/colabtools#80]
I have uninstalled the default tensorflow library. After reinstall it with pip, I could not active the gpu. 

Could I restore the python environment and get the default tensorflow lib coming with colab? 

https://colab.research.google.com/drive/1KP2O9UzKXCUVFg7FKUXzHJFla7KgR2QR

**Comment by craigcitro** [comment]
You have two options:

1. If you `!kill -9 -1` and wait about 30 seconds, you can reconnect to a completely fresh setup.
1. We recollect idle VMs after ~90m, so if you (say) go to sleep and get an answer from us the next morning (😀) you'll have a brand-new VM.
