### ISSUE TITLE
how to stop animation 

### ISSUE THREAD

**Issue by shubham-ai** [googlecolab/colabtools#803]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

Please guide how to stop firework animation and the moving dog animation it's so irritating while working

**Comment by craigcitro** [comment]
If you go to `Tools` -> `Preferences` -> `Miscellaneous`, you can disable both of these there:
 * uncheck "Corgi mode"
 * set "Power level" to "No power"

**Comment by jhlingle** [comment]
When I go into Tools>Miscellaneous I see both the Cogi Mode and Kitty Mode. Both are already unchecked, but the fireworks are still displaying. How do I get rid of these irritating firworks?

**Comment by katlyn-edwards** [comment]
The fireworks are from the Power Level setting. You should set it to "No power" as Craig mentioned above.

**Comment by jhlingle** [comment]
Thanks Katlyn!! I'll give it a try. Sure hope this works. They are making
me nuts!!

That seems to have worked!! You've made my day! It was a hard answer to
find. I'd been googling on and off for a week looking for a solution.

John

John Lingle
704-237-0844 (Phone)

**Comment by NiksanJP** [comment]
> If you go to `Tools` -> `Preferences` -> `Miscellaneous`, you can disable both of these there:
> 
> * uncheck "Corgi mode"
> * set "Power level" to "No power"

I had a hard time typing with a dog and firework shaking my screen THANK YOU!!!!!!!!!!!!!

**Comment by freealise** [comment]
I thought the power mode was about access levels or something. How stupid :(

**Comment by thecatfix** [comment]
I am trying colab for training models with TPUs to see if i would use for google cloud account. I thought this was a hidden setting for more power. Your documentation of colab is not what i expected when clicking on Help menu. Your team designed the UI as if it was a toy.
