### ISSUE TITLE
Quandl is installed but is not found

### ISSUE THREAD

**Issue by svemu** [googlecolab/colabtools#804]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Have installed quandl in my collab notebook and when I do a !pip show quandl it shows me the following details

Name: Quandl
Version: 3.4.8
Summary: Package for quandl API access
Home-page: https://github.com/quandl/quandl-python
Author: Quandl
Author-email: connect@quandl.com
License: MIT
Location: /usr/local/lib/python3.6/site-packages
Requires: more-itertools, requests, six, pyOpenSSL, numpy, pyasn1, ndg-httpsclient, inflection, pandas, python-dateutil
Required-by: 

However when I do an import quandl or import Quandl , it throws me a 

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-9b0ae57416bb> in <module>()
----> 1 import Quandl

ModuleNotFoundError: No module named 'Quandl'

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-8-c982d674eccd> in <module>()
----> 1 import quandl

ModuleNotFoundError: No module named 'quandl'

I have confirmed that all the dependencies are installed as well 

- Describe the expected behavior:

import quandl shouldnt show the error
- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/drive/1rMhNwpNn_2gmzrVYlFhxnTUb8ij1fTAx

**Comment by craigcitro** [comment]
Doing

    !pip install quandl
    import quandl

works for me in a fresh runtime; does the problem persist if you `Runtime` -> `Reset all runtimes`?

**Comment by svemu** [comment]
Yes , it does , tried refresh, restart

**Comment by svemu** [comment]
This refresh and restart worked now , closing the issue , Thank you !
