### ISSUE TITLE
tab takes to next cell instead of tab

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#805]
when I press tab, it takes cursor to next cell, instead of using tab for spaces.

[tab.zip](https://github.com/googlecolab/colabtools/files/3730028/tab.zip)

**Comment by blois** [comment]
Are there any particular keyboard bindings you're using? Do you know if this just started happening?

I'm unable to reproduce this behavior.

**Comment by vainaijr** [comment]
key bindings default only.
yes it just started happening, tab used to give tab earlier, but now it takes cursor to next cell.

**Comment by blois** [comment]
I'm just brainstorming at this point- could be a Chrome version upgrade, or perhaps a new browser extension (try incognito mode for that).

I'm pretty sure that there have not been any changes in Colab in the past 3 days which would have affected this.

**Comment by vainaijr** [comment]
I reloaded, tab started working as expected.
someway got resolved on its own.
