### ISSUE TITLE
No T4 Instances [BUG]

### ISSUE THREAD

**Issue by gumdropsteve** [googlecolab/colabtools#806]
Bug report for Colab: http://colab.research.google.com/

- Describe the current behavior:
  - Over the past 6+ weeks a number other users and myself have been unable to access T4 instances despite numerous attempts to reconnect and some accounts having not used any T4 instances before. 

- Describe the expected behavior:
  - There seemed to be some sort of limit to T4 instances over the past few months, e.g. if I were using T4 instances for a number of days there would be a prohibition period of sorts where I wouldn't be able to connect to a T4 instance for the next week or so. 
    - As it seemed fair and made enough sense, the above is the expected behavior. 

- The web browser you are using (Chrome, Firefox, Safari, etc.):
  - Firefox and Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/drive/1r7S15Ie33yRw8cmET7_bjCpvjJiDOdub

**Comment by tnovikoff** [comment]
Availability of T4s depends on many factors including demand, available capacity, and recent usage history. Some more details can be found on the [Colab FAQ](https://research.google.com/colaboratory/faq.html). There is currently no way to guarantee connection to a T4 in Colab.

**Comment by gumdropsteve** [comment]
It appears they have been brought back into the mix. Thank you.
