### ISSUE TITLE
Upgrading PyTorch to v1.3.0 and TorchVision to v0.4.1

### ISSUE THREAD

**Issue by soumith** [googlecolab/colabtools#809]
Hi folks,

We released a new PyTorch version v1.3.

The wheel links are:

PyTorch

CUDA 9.2

https://download.pytorch.org/whl/cu92/torch-1.3.0%2Bcu92-cp27-cp27m-linux_x86_64.whl
https://download.pytorch.org/whl/cu92/torch-1.3.0%2Bcu92-cp27-cp27mu-linux_x86_64.whl
https://download.pytorch.org/whl/cu92/torch-1.3.0%2Bcu92-cp36-cp36m-linux_x86_64.whl

CUDA 10.1

https://download.pytorch.org/whl/cu101/torch-1.3.0-cp27-cp27m-manylinux1_x86_64.whl
https://download.pytorch.org/whl/cu101/torch-1.3.0-cp27-cp27mu-manylinux1_x86_64.whl
https://download.pytorch.org/whl/cu101/torch-1.3.0-cp36-cp36m-manylinux1_x86_64.whl

TorchVision

CUDA 9.2

https://download.pytorch.org/whl/cu92/torchvision-0.4.1%2Bcu92-cp27-cp27m-linux_x86_64.whl
https://download.pytorch.org/whl/cu92/torchvision-0.4.1%2Bcu92-cp27-cp27mu-linux_x86_64.whl
https://download.pytorch.org/whl/cu92/torchvision-0.4.1%2Bcu92-cp36-cp36m-linux_x86_64.whl

CUDA 10.1

https://download.pytorch.org/whl/cu101/torchvision-0.4.1-cp27-cp27m-linux_x86_64.whl
https://download.pytorch.org/whl/cu101/torchvision-0.4.1-cp27-cp27mu-linux_x86_64.whl
https://download.pytorch.org/whl/cu101/torchvision-0.4.1-cp36-cp36m-linux_x86_64.whl

We're looking to having it updated in Colab.

Thanks very much.

cc'ing @colaboratory-team on the suggestion of Ami

**Comment by colaboratory-team** [comment]
b/142797419

**Comment by colaboratory-team** [comment]
FYI we're still using CUDA 10.0 (and for 2.7 it's the mu variant we want), so:
https://download.pytorch.org/whl/cu100/torch-1.3.0%2Bcu100-cp27-cp27mu-linux_x86_64.whl
https://download.pytorch.org/whl/cu100/torch-1.3.0%2Bcu100-cp36-cp36m-linux_x86_64.whl
https://download.pytorch.org/whl/cu100/torchvision-0.4.1%2Bcu100-cp27-cp27mu-linux_x86_64.whl
https://download.pytorch.org/whl/cu100/torchvision-0.4.1%2Bcu100-cp36-cp36m-linux_x86_64.whl

**Comment by soumith** [comment]
thanks, yes those links are correct :)

**Comment by colaboratory-team** [comment]
Note that this makes
```
import torch
torch.__version__
```
be `'1.3.0+cu100'` instead of `'1.2.0'`. Is the addition of `+cu100` to the version string ok?

**Comment by soumith** [comment]
that is okay. It follows PEP conventions and so should be fine.

**Comment by colaboratory-team** [comment]
Done now in new VMs. If you already have an assigned VM that predates the update please "Reset all runtimes" from the Runtime menu or command palette (note this unassign all existing VM assignments for all your notebooks, so save you work / temporary files / etc first).
