### ISSUE TITLE
Date form input keyboard arrow inverted

### ISSUE THREAD

**Issue by metal3d** [googlecolab/colabtools#81]
Hi
I've created a form and a date field. After typing year, I need to hit "left" arrow instead of right to go on month... and same for day.

Actually, arrows usage is inverted

**Comment by colaboratory-team** [comment]
I wasn't able to reproduce this particular error. Please reopen if you can reproduce, and include the browser and version number you're using. An immediately applicable work-around is to use tab and shift tab to cycle between date form fields.
