### ISSUE TITLE
Runtime local, not able to import files using google.colab packages (windows)

### ISSUE THREAD

**Issue by hdecamp** [googlecolab/colabtools#810]
I could manage to get the colab connected to my local machine but can not run:

from google.colab import files

It stops here:

c:\users\....\appdata\local\programs\python\python37\lib\tty.py in <module>()
      3 # Author: Steen Lumholt.
      4 
----> 5 from termios import *
      6 
      7 __all__ = ["setraw", "setcbreak"]

ModuleNotFoundError: No module named 'termios'

My O.S. is windows and termios is exclusively Unix.

**Comment by craigcitro** [comment]
We don't support installing and using this repo locally.
