### ISSUE TITLE
Cannot import Jupyter notebooks from google drive

### ISSUE THREAD

**Issue by cwripley1** [googlecolab/colabtools#811]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Even if I drag Jupyter notebooks into the Colab Notebooks folder, Colab cannot see the Jupyter notebooks.  I have to download them to my computer and reupload them into Colab

- Describe the expected behavior:
Users should be able to import Jupyter notebooks from drive into Colab

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by blois** [comment]
When you view the file in Drive (https://drive.google.com), can you right-click on it and choose Open with Google Colaboratory?

**Comment by cwripley1** [comment]
Yes actually this works.  Thanks! I had to also click "view" -> table of contents from the menu to see that there is a mount google drive button.  This allowed me to open drive files from already within colab.
