### ISSUE TITLE
Unable to quit inside loop while using %debug

### ISSUE THREAD

**Issue by skunkworker** [googlecolab/colabtools#812]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
When using the magic `%debug` inside of a for loop. Entering `quit()` does not pull you out of running the execution completely, but just iterates to the next run of the for loop. In order to stop execution you need to restart the runtime or enter `import os; os._exit(0)` but the latter causes the runtime to crash.

- Describe the expected behavior:
Entering `quit()` inside a for loop should exit from the loop and not require the runtime to crash or need a restart.
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome 77 on Mac OS 10.13.6.
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1hkVW3HMdV9QBi6G4icP9fbpCgJ5z6eCb

**Comment by craigcitro** [comment]
This isn't a bug: you're asking to invoke the debugger on every iteration of the loop, so the runtime invokes the debugger on every iteration of the loop. `quit()` just terminates the *current* debugger iteration.
