### ISSUE TITLE
copying from set_trace

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#814]
- Describe the current behavior:
If I want to see the shape of a tensor, then I have to set_trace, then print its shape, then copy it and then paste the shape next to line of code, so that I do not forget it the next time I check code.

- Describe the expected behavior:
is it possible to make changes to notebook cell while debugging, so that I do not need to go up and down again and again.
[copy_from_set_trace.zip](https://github.com/googlecolab/colabtools/files/3747922/copy_from_set_trace.zip)

**Comment by tnovikoff** [comment]
Feature request tracked internally at b/143783319

**Comment by metrizable** [comment]
This has been implemented. Functionality available via the `Insert > Scratch code cell` menu. Also, top-level variable information available in the Variables pane on the left:

![A4QdiYf9daY8Dpg](https://user-images.githubusercontent.com/65414824/228994570-74c442b0-c83f-4a6d-ac09-c2acff1864e5.png)
