### ISSUE TITLE
Need some features

### ISSUE THREAD

**Issue by subhajitmajumder** [googlecolab/colabtools#819]
Feature 1: Multiple comment line at a time.Now I can only create comment line using # in a single line.If it is possible to create multiple comment lines at a time by selecting multiple lines.(If there is any availability of this feature please let me know.)

Feature 2: Disable a code or text block.Now I have to delete an unused code block.But I need to keep that unused code block which is not required to be executed.(Again if this feature is available please let me know.

Feature 3: Increase or decrease font size. Cant increase font size and it is hard to read or write for me.(If this feature is available please let me know.) 

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
-

**Comment by blois** [comment]
Feature 1: ctrl-/ will comment the current line. Select multiple lines to comment all of them.
Feature 2: Does this mean disabling execution of a code cell? Two techniques: comment out the code or add the code as a python block in a markdown cell.
Feature 3: This is tracked in https://github.com/googlecolab/colabtools/issues/533.

**Comment by subhajitmajumder** [comment]
#feature 2: Actually want to keep the code cell but disabling execution.if
a cell gets comment feature like a code line,it would be great at least for
me.

**Comment by metrizable** [comment]
The recommendations for 1 and 3 from [#819 comment](https://github.com/googlecolab/colabtools/issues/819#issuecomment-544685633) seem to provide solution for your requests. The recommendations in 2 may also provide options for your request. Closing this issue. Please open a new feature request for any missing functionality.
