### ISSUE TITLE
FR: Autorun current cell on form change

### ISSUE THREAD

**Issue by korakot** [googlecolab/colabtools#82]
The new form feature is useful: you can change a variable value by just dragging a slider.
Now to change the result, you just type Ctrl+Enter to rerun the current cell.
Please add the feature to run it automatically upon value change, no need for Ctrl+Enter.

This will be very useful for fast interaction: e.g. you have a graph of `y=mx+c`, you can drag a slider for `m` or a slider for `c`. Then you see the graph is updated automatically. Then there will be no need to implement complex jupyter widgets.

**Comment by blois** [comment]
Click the pencil icon beside the title to edit, then select 'Auto-execute cell when fields change'.
