### ISSUE TITLE
# No backends available, and I'm not mining any cryptocurrency just doing coursera assignment.

### ISSUE THREAD

**Issue by yash04singh** [googlecolab/colabtools#820]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
  **no backends**
- Describe the expected behavior:
  **able to connect with hosted runtime**
- The web browser you are using (Chrome, Firefox, Safari, etc.):
 **chrome**

- Link to a self-contained notebook that reproduces this issue

https://colab.research.google.com/drive/1Ftkq2eqvrJN8rrKUCtCb9LPaVsurVwyG

**Comment by tnovikoff** [comment]
You may be running into usage limits if you use Colab very heavily. To avoid usage limits, consider closing your tabs when you are done with your work, and avoid using GPU/TPU-accelerated runtimes if they aren’t necessary for your work.

**Comment by colaboratory-team** [comment]
Likely b/144214181, now fixed.
