### ISSUE TITLE
Colab is no working 

### ISSUE THREAD

**Issue by jdquintero** [googlecolab/colabtools#823]
everytime that i try to run a cell it shows me this message:

Error
Could not load the JavaScript files needed to display output.
This is probably because your Google account login access has expired or because third-party cookies are not allowed by your browser.

Please reload this page.

**Comment by blois** [comment]
The most common cause of this right now is that there is some code executing in the outputframe which is using 100% CPU. To see if this is the case you can use Chrome's task manager to see if there are any processes at 100% and if so, to kill that process and try again.
