### ISSUE TITLE
Saving a notebook when Google Drive is full needs a clearer error message

### ISSUE THREAD

**Issue by fareshan** [googlecolab/colabtools#824]
- Describe the current behavior:
When I add Plotly figures to a notebook, it becomes impossible to save it.
When I remove them, the notebook becomes savable again.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome and Safari

**Comment by fareshan** [comment]
I found the issue :)
My google drive is full
I lost too much time trying to solve this issue. Google should make an alert for this.

**Comment by jsnydes** [comment]
fix with a specific message should roll out tomo or the next day.
