### ISSUE TITLE
The Python tab setting should default to 4 spaces to respect PEP8 and the Google style guide

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [googlecolab/colabtools#827]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

Currently, when opening a Python notebook, the default tab size is 2. It can be changed with a setting (tools -> preference -> editor -> use 4 spaces), but the default should represent the most widely used workflow.

PEP8 recommends using 4 spaces: [source](https://www.python.org/dev/peps/pep-0008/#indentation)
The Google Python style guide recommend using 4 spaces: [source](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#34-indentation)
The Python formatter Black indents with 4 spaces: [source](https://github.com/psf/black)
In the TensorFlow documentation, we'd like to start using 4 spaces to indent the code and since we use Colab, having the default at 4 spaces would make it much easier to migrate: [thread here](https://groups.google.com/a/tensorflow.org/forum/#!topic/docs/P-JeBVnNT_c) 

- Describe the expected behavior:

When opening a Python notebook, the default tab size is 4. It can be changed to 2 in the settings like before.

- The web browser you are using (Chrome, Firefox, Safari, etc.): 

Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

[self-contained notebook](https://colab.research.google.com/drive/1z3IUyzqsg9tJ-dZYFgSwCDmmN8dW6yMG)

Thank you for looking into it, and thanks for this awesome tool :)

**Comment by thomashirtz** [comment]
An auto formatting tool would be also nice, since imported notebook are kind of weird with the spaces

**Comment by blois** [comment]
Agree that 4 spaces as the default is probably the correct behavior. This would probably need to be paired with some auto-detection to minimize the impact of the change.

**Comment by gabrieldemarmiesse** [comment]
A very good idea, I didn't think about that. Auto-detection should help to transition smoothly. Some simple auto-detection would be enough maybe? Like for example looking for the number of spaces after a `def ...(...):` or the spaces after a `class ...(...):` ?

**Comment by gabrieldemarmiesse** [comment]
Any news on this?
