### ISSUE TITLE
Incomplete plots

### ISSUE THREAD

**Issue by Javiersuing** [googlecolab/colabtools#828]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

The y axis of the pyplot and sns figures are incomplete at the beginning and at the end of the plot, as shown on the following pictures

![image](https://user-images.githubusercontent.com/47925495/67612867-874cd980-f76c-11e9-809c-e964aa3102a6.png)

![image](https://user-images.githubusercontent.com/47925495/67612887-c8dd8480-f76c-11e9-9988-e1c02db12d5f.png)

- Describe the expected behavior:

A complete graph as it was 2 week ago with the same code. The complete figure is shown on the following picture:

![image](https://user-images.githubusercontent.com/47925495/67612943-3a1d3780-f76d-11e9-9aa1-e4764aae44c9.png)

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*): It happens in any notebook, I try a new one put this piece of code and the graph was not comeplete:

https://drive.google.com/open?id=1My18DBfbTLsmeN2TxKYeFMkezXMGeb5W

```python
import seaborn as sn
import pandas as pd
import matplotlib.pyplot as plt
array = [[33,2,0,0,0,0,0,0,0,1,3], 
        [3,31,0,0,0,0,0,0,0,0,0], 
        [0,4,41,0,0,0,0,0,0,0,1], 
        [0,1,0,30,0,6,0,0,0,0,1], 
        [0,0,0,0,38,10,0,0,0,0,0], 
        [0,0,0,3,1,39,0,0,0,0,4], 
        [0,2,2,0,4,1,31,0,0,0,2],
        [0,1,0,0,0,0,0,36,0,2,0], 
        [0,0,0,0,0,0,1,5,37,5,1], 
        [3,0,0,0,0,0,0,0,0,39,0], 
        [0,0,0,0,0,0,0,0,0,0,38]]
df_cm = pd.DataFrame(array, index = [i for i in "ABCDEFGHIJK"],
                  columns = [i for i in "ABCDEFGHIJK"])
plt.figure(figsize = (10,7))
sn.heatmap(df_cm, annot=True)
```

**Comment by tnovikoff** [comment]
Tracking internally at b/143778520

**Comment by jakevdp** [comment]
Hi - This isn't specific to Colab – it appears to be an issue with matplotlib version 3.1.X; downgrading to matplotlib 3.0.X fixes the issue.

The question is whether this is enough of an impetus to downgrade matplotlib in our default container until they fix it... I'm not sure. In any case, it should be reported upstream to the matplotlib and/or seaborn developers.

**Comment by jakevdp** [comment]
Reported in Seaborn's issue tracker: https://github.com/googlecolab/colabtools/issues/828

**Comment by tnovikoff** [comment]
Looks like this is a known issue, and will be fixed in the next matplotlib release (which currently has a release candidate.)

**Comment by colaboratory-team** [comment]
Hello, Colab is now updated to matplotlib 3.1.2 by default, which contains the fix for this issue. Thanks for the report!
