### ISSUE TITLE
Unexpected NameError in Solution.

### ISSUE THREAD

**Issue by JoshuaOakland** [googlecolab/colabtools#830]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
 The Run Cell Code execution unexpectedly halts with name errors.

- Describe the expected behavior:
   Code execution should not halt on expected names in execution environment. Alternatively the exercise should be more explicit when detailing the exercise outline. 

- The web browser you are using (Chrome, Firefox, Safari, etc.):
        77.0.3865.120 (Official Build) (64-bit)

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/notebooks/mlcc/intro_to_pandas.ipynb

/*
If this is unintended this first trace below from the solution is your most objective example.
*/

NameError                                 Traceback (most recent call last)
<ipython-input-2-085193edc804> in <module>()
----> 1 cities['Is wide and has saint name'] = (cities['Area square miles'] > 50) & cities['City name'].apply(lambda name: name.startswith('San'))
      2 cities

NameError: name 'cities' is not defined

/*
While I expected an exception on this brilliant piece below, I do not think the description of the exercise suits this outcome.
*/

NameError                                 Traceback (most recent call last)
<ipython-input-1-668d8a6d2016> in <module>()
----> 1 for city in cities:
      2   if("San" in city):
      3     city['Is a saint'] = True
      4   else:
      5     city['Is a saint'] = False

NameError: name 'cities' is not defined

/*
I also just wanted to say thank you for providing these lessons and this material, it has been invaluable.
*/

**Comment by craigcitro** [comment]
The error you're getting means that you haven't executed the cells above the one you're executing (in particular, the one that defined `cities`).
