### ISSUE TITLE
saves failed

### ISSUE THREAD

**Issue by elizabethswkim** [googlecolab/colabtools#832]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Missing a day's history of revisions on a colab notebook.

- Describe the expected behavior:
Usually colab's great about autosaving.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome.

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by Lucia508** [comment]
can not paste in + Code, nothing!
