### ISSUE TITLE
issue on invoke

### ISSUE THREAD

**Issue by vijayscsa** [googlecolab/colabtools#834]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Invoking is not easy

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by tnovikoff** [comment]
Can you provide more information?
