### ISSUE TITLE
Reconnect a local runtime after disconnection

### ISSUE THREAD

**Issue by MI-LA01** [googlecolab/colabtools#836]
- Describe the current behavior:

Google colab is not reconnecting an existing and running session opened through a local runtime when a disconnection from network occurred. 

The tab connect appear w/ "connecting..." ; no timeout occur  I confirm the local Jupyter is still running. 

- Describe the expected behavior:

If a disconnection from network occurred (wifi turned/off/on, lan turned/off/on or computer turned off/on) google colab should be able to re-open/connect an existing and opened session on the local Jupyter runtime as  the same way it does on hosted runtime. 

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome latest macos. - The connection is made through a web-socket proxy installed on my workstation ; that is ; handling the routing from ws://localhost:8888 to an internal server in my lan (ws://192.168.1.x:8888) - pls note, a pattern matching is implemented to catch the uri from colab request and append it on the requested lan server. 

This method work like a charm - no pb to connect and use colab that way. As mentioned above, the issue raise when a network reconnection attempt occur. 

Feedbacks are welcome.

**Comment by craigcitro** [comment]
Thanks for the report! I can confirm I see the behavior; we'll take a look.

Internal tracking:
b/143647794

**Comment by madson812** [comment]
Is there an update on this? I am running into the same issue.

**Comment by VladMurgoci** [comment]
Same issue here, I have found no fix for this and it's incredibly annoying.

**Comment by 7C7M5KQG1Y2ORDJ8VM2Q1D92N5RVGPQTT6D1** [comment]
Also running into the same issue
