### ISSUE TITLE
Google Drive gets unmounted when interrupting a running cell

### ISSUE THREAD

**Issue by mitalbert** [googlecolab/colabtools#837]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
After mounting the gdrive using:
from google.colab import drive
drive.mount('/gdrive')

the mounted drive gets unmounted when interrupting a running cell, even if the cell neither writes on nor reads from mounted drive

- Describe the expected behavior:
It would be useful if the mounted drive stays mounted

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link to self-contained notebook that reproduces this issue
[Link](https://colab.research.google.com/drive/1JgE7wT1zt0c1q7vQ1pnM2s_kz7KYq7BY)

**Comment by colaboratory-team** [comment]
Fix is rolled out. You may need to "Reset all runtimes" (from the Runtime menu or the command palette) to observe this if you have a VM assigned already (this will lose all your current VM's state so save your work off-VM first).
Thanks again for the report and sorry for the inconvenience.

**Comment by mitalbert** [comment]
Thanks for fixing it so quickly.
