### ISSUE TITLE
copying files do not display

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#838]
I have an account 'X' in which I have colab notebooks
I have an account 'Y' in which I do not have those colab notebooks

I copy my colab notebooks, from google drive of account 'X' to google drive of account 'Y', inside colab notebooks folder

But still colab notebooks do not appear with yellow icon, and do not appear in google drive search results in colab also.

![Screenshot (72)](https://user-images.githubusercontent.com/43755000/67914510-b384b200-fbd3-11e9-906b-b7a0083c7341.png)

I downloaded files from google drive of account 'X' and then uploaded them to google drive of account 'Y', is there a way to directly copy?

**Comment by craigcitro** [comment]
Can you say more about how you did the upload/download? (Was it via the Drive UI, or using a tool like drive sync, or something else?)

Colab's Drive integration works via MIME types, which are generally preserved when copying via Drive.

**Comment by vainaijr** [comment]
I selected all files inside colab notebooks folder of account 'X', then right click, then select download, then it downloaded a zip file, then extracted the zip file, then uploaded those files, to account 'Y', by file upload.

**Comment by craigcitro** [comment]
b/144544526
