### ISSUE TITLE
avoid zebra stripes when possible

### ISSUE THREAD

**Issue by fhoffa** [googlecolab/colabtools#841]
Looking at the new Data Table extension and generally at how tables are presented: Please avoid using the zebra stripes design to color each other row with a different background.

If possible, only use a different background color for a row when there's a meaning for it. For example "is this row selected? is this row more important that the others? is this row an outlier?"

Edward Tufte agrees:

> Again, this is a solved problem, with examples in Envisioning Information, chapter 3. Strips are merely bureaucratic or designer chartjunk; good typography can always organize a table, no stripes needed.

> -- Edward Tufte https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0001IV

- https://twitter.com/felipehoffa/status/1190376736766087168
- https://ux.stackexchange.com/a/121430/33122

**Comment by craigcitro** [comment]
FWIW, one big complication here is that our tables are always as wide as the browser, making the alternation pretty helpful for looking across the table.

**Comment by blois** [comment]
This also highlights that the header alignments should match the column data alignment.

**Comment by fhoffa** [comment]
Yes! I understand there's a user preference issue too. But GMail and Spreadsheets in general do really well at any width.

FWIW, my favorite related gif:

![](https://i.stack.imgur.com/Dic42.gif)

**Comment by pjmartel** [comment]
Make zebra stripes optional if you must, but please don't remove them. They are very useful for looking across wide tables, particularly for people with vision problems like myself.
