### ISSUE TITLE
Error changing to a directory in Google Drive

### ISSUE THREAD

**Issue by eda-ricercatore** [googlecolab/colabtools#842]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

After I listed the contents of a directory in my Google Drive using the "ls -al" Linux/UNIX command in my Jupyter notebook on Google Colab/Colaboratory, I changed directories to this aforementioned directory using the "cd" Linux/UNIX command.

When I listed the contents of this directory again in my Google Drive after the "cd" Linux/UNIX command, the output of this Linux/UNIX command is different from the initial "ls -al" Linux/UNIX command.

- Describe the expected behavior:

The output of the two instances of the "ls" Linux/UNIX command should be the same, since I am listing the contents of the same directory.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Google Chrome on macOS Catalina 10.15.1.

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

See https://github.com/eda-ricercatore/scienza_dei_dati/blob/master/error_with_importing_packages_and_modules.ipynb for the Jupyter notebook with the Linux/UNIX commands in the Python "script" and the output results of executing such commands on Google Colab/Colaboratory.

**Comment by tnovikoff** [comment]
Tracked at b/144190831

**Comment by colaboratory-team** [comment]
When you run a subprocess under `!` its current working directory ("cwd") is independent of the calling process' cwd. So running
```
!cd foo
```
has no effect, since the `cd` only changes the cwd of the subprocess, not of the python runtime itself.
To change the cwd of the python runtime use the `%cd` magic instead of where you're currently doing `!cd`.

**Comment by jakevdp** [comment]
If you use the ``%cd`` magic command rather than the ``!cd`` shell command, it will work as you expect.
