### ISSUE TITLE
Cannot open a notebook

### ISSUE THREAD

**Issue by 11Alexei11** [googlecolab/colabtools#844]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by jakevdp** [comment]
Hello - we'll need more information in order to help with this. How did you attempt to open the notebook (following a URL? choosing new notebook from a menu?) What happened when you did? Was there an error message? Thanks.
