### ISSUE TITLE
Upgrading PyTorch to v1.3.1 and TorchVision to v0.4.2

### ISSUE THREAD

**Issue by soumith** [googlecolab/colabtools#845]
Hi folks,

We released a new PyTorch version v1.3.1 and torchvision v0.4.2.

The wheel links are:

PyTorch

CUDA 10.0

https://download.pytorch.org/whl/cu100/torch-1.3.1%2Bcu100-cp27-cp27m-linux_x86_64.whl
https://download.pytorch.org/whl/cu100/torch-1.3.1%2Bcu100-cp27-cp27mu-linux_x86_64.whl
https://download.pytorch.org/whl/cu100/torch-1.3.1%2Bcu100-cp36-cp36m-linux_x86_64.whl

TorchVision

CUDA 10.0

https://download.pytorch.org/whl/cu100/torchvision-0.4.2%2Bcu100-cp27-cp27m-linux_x86_64.whl
https://download.pytorch.org/whl/cu100/torchvision-0.4.2%2Bcu100-cp27-cp27mu-linux_x86_64.whl
https://download.pytorch.org/whl/cu100/torchvision-0.4.2%2Bcu100-cp36-cp36m-linux_x86_64.whl

We're looking to having it updated in Colab.

Thanks very much.

cc'ing @colaboratory-team

**Comment by colaboratory-team** [comment]
b/144098602

**Comment by jakevdp** [comment]
updated package versions now available in http://colab.research.google.com runtimes!

**Comment by soumith** [comment]
thank you!
