### ISSUE TITLE
BigQuery snippet broken; uses out of date syntax for Pandas GBQ

### ISSUE THREAD

**Issue by riordan** [googlecolab/colabtools#846]
# Describe the current behavior:
When using the snippet [Using BigQuery with Pandas API](https://colab.research.google.com/notebooks/snippets/bigquery.ipynb#scrollTo=KcAZ2RHCg_Ze), the code provided in the snippet won't complete execution, even when the user fills out the variables for their GCP project ID, leaving them to debug a BigQuery syntax issue on their own.

# Describe the expected behavior:
When the snippet is inserted, a user following the snippets conventions (e.g. replacing the blockquoted text in `project_id = '[your Cloud Platform project ID]'`), the code should execute successfully giving a working illustrative example for the user to iterate from, not have to debug.

# The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

# Link to self-contained notebook that reproduces this issue
[Notebook with updated syntax](https://colab.research.google.com/drive/1WfCjfKyg_xr3iq4uze5IBxBS2kDg7SFA#scrollTo=nFF9Wz1CAyVI)

This notebook resolves the issue by:
- Updating the syntax within the query to use StandardSQL for the tablename (backticks around tablename, change `:` to `.` for separator between GCP Project and Dataset
- Removing deprecated `verbose` argument from `pd.io.gbq.read_gbq()`

**Comment by jakevdp** [comment]
Thanks for the report. It looks like pandas-gbq switched from legacy SQL to standard SQL at some point along the way; we'll get that updated.

**Comment by riordan** [comment]
Thank you, @jakevdp. There's a lot of really thoughtful design decisions that went into Colab and the way the Snippets is built to shortcut the process of moving from discovery -> use + iteration is really remarkable.
