### ISSUE TITLE
Typo In TF-agents Colab notebook

### ISSUE THREAD

**Issue by lacvapps** [googlecolab/colabtools#847]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
Network is misspelled "neetwork"
- Describe the expected behavior:
Network should be spelled correctly

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
https://colab.research.google.com/github/tensorflow/agents/blob/master/tf_agents/colabs/5_replay_buffers_tutorial.ipynb#scrollTo=9V7DEcB8IeiQ

**Comment by craigcitro** [comment]
Thanks for the report!

**Comment by lacvapps** [comment]
No Problem!

**Comment by metrizable** [comment]
This has been fixed at: https://github.com/tensorflow/agents/blob/master/docs/tutorials/5_replay_buffers_tutorial.ipynb
