### ISSUE TITLE
Tesla P100 GPU shown instead of Tesla K80 or T4

### ISSUE THREAD

**Issue by wakame1367** [googlecolab/colabtools#848]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
`!nvidia-smi`
![colab_p100](https://user-images.githubusercontent.com/7046610/68542425-c7a88a80-03ef-11ea-8a1b-d3fab433b4c8.PNG)

Tesla P100 GPU shown instead of Tesla T4 or K80 now.

- Describe the expected behavior:
I expect to use Tesla P100 GPU instead of Tesla T4 or K80.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1KDVPeoum-w7AwEkx-BUZIlK19071bpeZ

**Comment by akashdeepjassal** [comment]
That is same as when T4 was first introduced in colab.
I am also using P100 right now.

**Comment by maulvi** [comment]
P100 is currently the fastest gpu available on colab, how is this a "bug" ?
