### ISSUE TITLE
Error in import Attribute in module

### ISSUE THREAD

**Issue by Mohammed-Towfiq** [googlecolab/colabtools#850]
### Error in import Attribute in module

> in "telegram" module have "ext"
> colab cant read "ext" inside "telegram" module
> Fix it please

**My Code**
```
import telegram
from telegram.ext import Updater,CommandHandler,CallbackQueryHandler
```
 **Error Is:**
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-b78ef8df0cfc> in <module>()
      1 import telegram
----> 2 from telegram.ext import Updater,CommandHandler,CallbackQueryHandler

ModuleNotFoundError: No module named 'telegram.ext'
```

**Comment by jakevdp** [comment]
Hello,
telegram is a third-party package that is not installed by default in Colab. If you are having trouble using it, I would suggest referring to the package documentation or issue tracker.
