### ISSUE TITLE
Not able to download .py file from colab

### ISSUE THREAD

**Issue by ShivaniBurad** [googlecolab/colabtools#852]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by blois** [comment]
Can you explain the error that you are seeing? By default Chrome will display a special warning for these since it considers .py files to be executables.

**Comment by metrizable** [comment]
@ShivaniBurad  Since this issue was filed a while ago, if you are still experiencing the issue, please re-open and provide a screencast of the behavior you are seeing.
