### ISSUE TITLE
Continuous Disconnect

### ISSUE THREAD

**Issue by luizapozzobon** [googlecolab/colabtools#854]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
Every notebook I have tried using since yesterday is continuously disconnecting after 1 minute. I've tried three different notebooks, tried changing computers, tried changing the runtime to CPU, but all of them, after about 1min running, gets disconnected and everything is lost.
I've also not exhausted my 12h running time since it first got disconnected when I was with about 7~8h usage. I've spent the last 12h not using it and the problem is still here.

- Describe the expected behavior:
The expected behavior would be for the notebook to not disconnect so quickly. I understand it disconnects after a period of about 30~1h with no usage, besides the 12h limit, but I'm getting disconnected so quickly I can't even load my drive into colab most of the times.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link to self-contained notebook that reproduces this issue
It's really any notebook at all. It happens with this one from fast ai also.
https://colab.research.google.com/github/fastai/course-v3/blob/master/nbs/dl1/lesson1-pets.ipynb

** Update:
I've tested running the colab notebooks with Firefox instead of Chrome and it seems to be working. However, the Chrome bug is still happening and I'd deeply appreciate a feedback on this topic.

**Comment by polakowo** [comment]
I have the same issue with Chrome, while Safari seems to work fine. In Chrome, after running a couple of cells, the GPU runtime gets disconnected and keeps reconnecting indefinitely. The CPU-only runtime seems not to be affected by this issue.

**Comment by craigcitro** [comment]
We had some issues with assignments earlier this week that _could_ explain what you were seeing, but it's hard to be sure.

If you can still repro (esp. in an incognito window, or with inconsistent behavior between browsers), let us know.
