### ISSUE TITLE
ctrl + cell number to go to a cell

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#857]
- Describe the current behavior:
If I am in cell number 'X' and I want cursor to be at cell number 'Y', then the only way is to scroll up/down, and click on cell 'Y' or navigate one cell up/down till I reach cell 'Y'
 
- Describe the expected behavior:
ctrl + cell number to move to another cell, for example if I am at cell number 5, and want to go to cell number 10, then ctrl+10 takes to cell 10, or a better way to navigate between two cells that are not next to each other.

**Comment by jakevdp** [comment]
Colab doesn't really have a concept of cell numbers, so I don't think this would work.

I would suggest using the "Next Cell" and "Previous Cell" keyboard shortcuts to navigate between cells, which in the default key mapping are Ctrl-m-n and Ctrl-m-p, respectively. You can choose  Tools-Keyboard Shortcuts if you would like to remap these.
