### ISSUE TITLE
Keyboard shortcut not working since yesterday

### ISSUE THREAD

**Issue by WenshanLiang** [googlecolab/colabtools#859]
- Describe the current behavior: all shortcuts (eg. Shift+Enter) are not working. I have tried to reset default shortcuts, and restart the colab. None of them worked. 

- Describe the expected behavior: 

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment]
duplicate of #858
