### ISSUE TITLE
Unable to delete empty directory via Files pane GUI

### ISSUE THREAD

**Issue by lukereichold** [googlecolab/colabtools#862]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- **Describe the current behavior**: When attempting to delete a directory in the "Files" pane via Right Click > "Delete Folder", I receive `"Deletion failed Directory "full" is not empty. Only empty directories can be deleted." Visually, and confirmed via `ls`, this directory is completely empty.`

I was indeed able to later delete the directory via a shell command. I am opted in to using the "new code editor" in Colab.

- **Describe the expected behavior**: The directory is deleted.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome 78

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by katlyn-edwards** [comment]
Hidden files aren't rendered in the UI it seems. `ls` also won't return them. Can you verify via `ls -la` that there's nothing there? For me, I'm only able to reproduce this if I create a dot-file (something named .hiddenfile).

**Comment by lukereichold** [comment]
Ah yes, I did have an unexpected hidden file in there, which was definitely the cause. Thanks!
