### ISSUE TITLE
Safari: LaTeX \hat not displaying correctly 

### ISSUE THREAD

**Issue by captainvera** [googlecolab/colabtools#87]
The \hat symbol in LaTeX mathematical expressions is not working correctly in Safari 11.0.3

The math renders like this: 
![screen shot 2018-03-13 at 15 18 35](https://user-images.githubusercontent.com/5597178/37351045-19f03560-26d2-11e8-9efb-de3361ff123d.png)

It works on other browsers (e.g Firefox 59.0). But not in Safari. 
No specific errors happen in dev console. 
Also doesn't work in incognito mode.

**Comment by blois** [comment]
This is https://github.com/mathjax/MathJax/issues/1737, looks like we need to do an update.
