### ISSUE TITLE
SMOTE fails to run on colab from imblearn

### ISSUE THREAD

**Issue by qboy21** [googlecolab/colabtools#870]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
from sklearn.utils import resample
from imblearn import under_sampling, over_sampling
from imblearn.over_sampling import SMOTE

# SMOTE
sm = SMOTE()
X_train_sam, y_train_sam = sm.fit_resample(X_train, y_train)

Just runs forver without any output for completion
- Describe the expected behavior:
completion with the ability to view the value counts
# view class balance
y_train.value_counts() 
- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://drive.google.com/file/d/1SJL-pfk27I4zXl43ZrkeZPbnu97reUX4/view?usp=sharing

**Comment by tnovikoff** [comment]
I think this is a SMOTE issue, not a Colab issue. 

The SMOTE sample code seems to work (not hanging) in this notebook:
https://colab.research.google.com/drive/1LXcFk8wWEK6P_W8vi2oxpxUGszT5YaUe

(SMOTE sample code taken from from https://imbalanced-learn.readthedocs.io/en/stable/generated/imblearn.over_sampling.SMOTE.html)

**Comment by qboy21** [comment]
Sorry I should have stated it does not work in Colab when the sample size is 10,000. No problem, I used undersampling and reshape. The example is provided is a tiny sample dataset.
