### ISSUE TITLE
Bug: Widget (Ipywidget) with plot does not show up where it's supposed to using GridspecLayout

### ISSUE THREAD

**Issue by KristianLN** [googlecolab/colabtools#873]
Hi,

I'm trying to place two graphs in individual cells of the grid, created using GridspecLayout from Ipywidgets. However, the plots appears to the left of the interactive controls, instead of below as supposed to.

I initially raised this issue [here](https://github.com/jupyter-widgets/ipywidgets/issues/2624).

I'm working on Colaboratory and Jupyter Notebook via Anaconda, both via Chrome on Windows 10. This has been tested on JupyterLab via Firefox on Mac as well, which is why I suspect it to be an issue with Colaboratory.

Link to reproducible notebook: https://drive.google.com/open?id=1EBYD8dVc8BnlL2dD7qApGNGpI1xZf8f3

**Comment by blois** [comment]
This should be fixed now.
