### ISSUE TITLE
New editor's Ctrl + Shift + Space and Ctrl + Space not working on Pixelbook / ChromeOS

### ISSUE THREAD

**Issue by ziatdinovmax** [googlecolab/colabtools#874]
Hello,

I'm really enjoying the new Colab editor. One small issue is that when working on my Pixelbook with ChromeOS, I cannot use Ctrl + Shift + Space and Ctrl + Space shortcuts for parameter hints and code completion since they are reserved for [switching between keyboard languages](https://support.google.com/chromebook/answer/1059492?hl=en&ref_topic=9145745).* So far I couldn't find an option to change a shortcut for switching between languages on the Pixelbook. Nor I was able to find an option to change these particular shortcuts in Colab. Hence, I'm hoping that you can help with this.

Thanks in advance!

*It seems that if there is only one language then everything works fine.

**Comment by craigcitro** [comment]
Interesting! (And unfortunate.)

The only solution I've found so far: 
* visit https://colab.research.google.com
* three dot menu -> More tools -> Create shortcut
* when you create the shortcut, click "open as window"

According to [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=123856) (which I found via [this one](https://bugs.chromium.org/p/chromium/issues/detail?id=211906)), this *should* no longer capture shortcuts.

Let me know if that works?

**Comment by ziatdinovmax** [comment]
It works! Thanks! Well, as long as I don't open another notebook in a "new tab" :)
