### ISSUE TITLE
Colab form's "dropdown" element is displaying default element in form, even when value is removed. 

### ISSUE THREAD

**Issue by arunks123** [googlecolab/colabtools#875]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
When we delete the value corresponding to the dropdown variable the User Interface is displaying the first value by default. This is misleading

- Describe the expected behavior:
This is misleading because it gives an impression to the user that the value has already been filled by him. If the value for a dropdown element is empty (i..e '') then it should honor that and no show any value by default in the User Interface ont eh drop down.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by arunks123** [comment]
Browser being used is chrome.

Please see in the following notebook, how though I have removed the value of "Dropdown" , the first value is appearing as a default. https://colab.research.google.com/drive/1CuzvzabBWAZ6qBfh_KGgijeDlBB3jujK 

Thanks,

**Comment by tnovikoff** [comment]
Tracking at b/145823350

**Comment by corrieann** [comment]
Thanks for the bug report.  This has been fixed.
