### ISSUE TITLE
Colab usage with GCP bucket costs more than 100$ a day. Is it normal?

### ISSUE THREAD

**Issue by muxgt** [googlecolab/colabtools#880]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I trained a model in Colab accessing data from Google Cloud bucket for 1 day and it calculated me the cost around 110$ mostly for "GCP Storage egress between NA and EU ". I wonder if there is a way to use Colab and bucket in the same region so that egress is free? How do I know in what region Colab is running?
- Describe the expected behavior:
I expected the price to be reasonable

- The web browser you are using (Chrome, Firefox, Safari, etc.):
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment]
Colab doesn't have a way to control which region your backend is in.

I'd recommend using a local runtime: https://research.google.com/colaboratory/local-runtimes.html

**Comment by world2vec** [comment]
@craigcitro 
Could you kindly explain why connect to local-runtime will not trigger the egress fee?

**Comment by craigcitro** [comment]
If you use a local runtime, you know what continent your backend is in, and you can choose a bucket in the same continent.
