### ISSUE TITLE
Embed image from Google Drive

### ISSUE THREAD

**Issue by beli** [googlecolab/colabtools#882]
I'm trying to embed an explanatory image in a markdown cell. 
At the top of the cell there's an 'Insert image' button that puts the code `![alt text](https://)` into the cell.
It works for images hosted on the web, like for example from Wikimedia Commons.
On Google Drive you can right-click on a file and select 'Get shareable link' which gives you a link using which anyone can view the file (like say an image file).
But this link can't be used to display an image in a Colab markdown cell.
I'm using Google Chrome.

Example notebook: https://colab.research.google.com/drive/19Qe70fDD2XUP8LdWYnUQuUko5oT98Euy

**Comment by craigcitro** [comment]
I don't think there's anything colab-specific here; it looks like you got it figured out based on your notebook. (Your solution also seems to match [this SO question](https://stackoverflow.com/a/11855448).)

**Comment by colaboratory-team** [comment]
If an image is on your clipboard you can also use ‘paste’ to paste the
base64 data into the markdown.

**Comment by beli** [comment]
> I don't think there's anything colab-specific here; it looks like you got it figured out based on your notebook. 

The notebook has three attempts at inserting images. The one hosted on wiki commons works, the ones on Google Drive don't. That's sort of the problem :-)

> (Your solution also seems to match [this SO question](https://stackoverflow.com/a/11855448).)

That and many others, but none of their solutions work for images on Google Drive. This could be an issue on GDrive's side though.

> If an image is on your clipboard you can also use ‘paste’ to paste the base64 data into the markdown.

That works, thanks! Though it puts a wall of text in my markdown cell. Still, I understand this is a low priority issue (or working as intended?) so won't press any further. Appreciate the work y'all're doing.

**Comment by blois** [comment]
I was able to get a photo from Drive working by:

1. Upload the image to Drive.
2. Right-click on the file in Drive, choose 'Get sharable link'.

The URL should look like: https://drive.google.com/open?id=XXXXXX

Then grab the ID from that URL then for the URL in the notebook, use:
http://drive.google.com/uc?export=view&id=XXXXXX

**Comment by craigcitro** [comment]
Just to confirm: the embedded `uc` link in that notebook works when I open it. 

Is that not the case for everyone else?

**Comment by beli** [comment]
Un-blocking third party cookies made the images appear for me - those with 'open?id' replaced with 'uc?id' and with 'uc?export=view&id'. The change is immediate, without having to reload. I'm on Google Chrome.

Apologies. Thanks again for the patience.

**Comment by xiebruce** [comment]
> I was able to get a photo from Drive working by:
> 
> 1. Upload the image to Drive.
> 2. Right-click on the file in Drive, choose 'Get sharable link'.
> 
> The URL should look like: https://drive.google.com/open?id=XXXXXX
> 
> Then grab the ID from that URL then for the URL in the notebook, use:
> http://drive.google.com/uc?export=view&id=XXXXXX

This really help me a lot, well I'll mention one more point here(in case someone need it), if you are embedding an non-image file to markdown, you can use: 
```
http://drive.google.com/uc?export=download&id=XXXXXX
```
