### ISSUE TITLE
Colab Getting unresponsive

### ISSUE THREAD

**Issue by abdallah197** [googlecolab/colabtools#883]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
All colab notebooks are getting unresponsive out of the sudden for me. created ones and uploaded ones. I use GPU and reset all runtimes, but it gets unresponsive and crashes right away
- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
https://colab.research.google.com/drive/1_avkyI5o5a69OkoAQP19D2-1hrFREtjN
  (click the *Share* button, then *Get Shareable Link*):

**Comment by tnovikoff** [comment]
What exactly do you mean by "gets unresponsive and crashes"? Can you copy/paste the contents of any error messages you might be seeing?

**Comment by layjain** [comment]
Same problem, view freezes and the page becomes unresponsive; Google chrome "You can wait for them to become responsive or kill them" message.

**Comment by blois** [comment]
Can you try an incognito browser window?

**Comment by AhmedAyman0** [comment]
@blois I've been facing this recently , suddenly it goes laggy and not responding on chrome macos and tried the incognito window gives same problem

**Comment by MHRosenberg** [comment]
Same behavior as above across both macOS 10 and windows machines. Reopening the page/browser does not resolve the issue. If this can't be resolved soon, I'll have to switch to running everything locally which would be a bummer...

**Comment by Arpitrf** [comment]
I have been facing this same issue recently as well.

**Comment by abdallah197** [comment]
I had to re install chrome

**Comment by murthax** [comment]
same problem. I disabled autosave (saw that was one resolution). Also tried "from IPython.display import clear_output" and same behavior on both Chrome and Firefox.

**Comment by SimKico** [comment]
Still the problem. 
I'm using Google Chrome and Colab becomes unresponsive very often, especially when I leave the site for some time, like for a minute or two.

**Comment by Anirban166** [comment]
I'm facing the same issue (specific to the use of Colab on chrome in MacOS) at the moment, being stuck after clicking the 'Share' button for a notebook am working on.

**Comment by Anirban166** [comment]
I'm facing the same issue (specific to the use of Colab on Chrome in MacOS) at the moment, being stuck after clicking the 'Share' button for a notebook am working on.

**Comment by ecolleran** [comment]
same issue here where the page is simply unresponsive and I cannot select text or even navigate the page to stop executing the code. any help or recommendations would be highly appreciated. I have used Chrome and Safari on MacOS.

**Comment by blois** [comment]
Common causes which may lead to slow pages:
 - Browser extensions misbehaving. Often opening in an incognito browser window drops extensions and may resolve the issue.
 - Excessively large notebooks. We're continuously optimizing Colab, previously things would start slowing down at around 100 cells, now it can be usable at over 1000 cells.
 - Excessively large outputs- we try to trim and limit outputs to avoid performance issues, there may be edge cases where particularly large or verbose outputs may cause sluggishness.
 -  Other tabs- the browser rendering process may be shared across multiple browser tabs. This can lead to performance issues in one tab affecting another tab.

**Comment by Karlheinzniebuhr** [comment]
Getting same error when doing some slight machine learning that takes a few minutes in a notebook. Besides that now captchas become increasingly annoying despite paying the pro version of colab

**Comment by blackPantherOS** [comment]
Getting same error when running long build command...

**Comment by seasighter** [comment]
![Screenshot 2024-01-18 120952](https://github.com/googlecolab/colabtools/assets/71922190/dcf85900-97ac-4403-a325-b78670477ae4)
  
Getting same error while using google  collab on brave browser

**Comment by thijsi123** [comment]
Still happening on both edge and chrome...

**Comment by mycoalchen** [comment]
Same here, I've been closing and reopening the tab/browser but Colab becomes unresponsive ~1 sec after opening every time.

**Comment by thijsi123** [comment]
For me it happens when the output of a cell gets too large so I have to clear it every 10 seconds.

**Comment by keyapi** [comment]
since this week, on chrome 131.0.6778.205 (windows 11), all google colab tabs,  often suddenly loss of response or crash.

**Comment by akhil4674** [comment]
![Screenshot 2024-12-26 at 12 10 50 PM](https://github.com/user-attachments/assets/b0a6c6fc-9124-4c90-9a2b-c259b42ce123)
![Screenshot 2024-12-26 at 12 14 07 PM](https://github.com/user-attachments/assets/81b52293-579f-4b8f-a334-70035b9539c7)
Same for me
