### ISSUE TITLE
[Feature Request] side by side code cells

### ISSUE THREAD

**Issue by dyl4nm4rsh4ll** [googlecolab/colabtools#886]
This would allow some pretty serious improvement in my productivity, personally. I am already a big fan of the ability to intermix markdown and code with the "form" cells, they have allowed me to navigate a complicated CoLab document quickly. Allowing multiple code cells to be placed side by side vertically would be awesome...

**Comment by tnovikoff** [comment]
Tracking at b/145817927

**Comment by colaboratory-team** [comment]
Execution output can be rendered side-by-side with the cell's source using:
```
#@title Something { vertical-output: true }
```
(requires a title, which can be empty)
