### ISSUE TITLE
Debug mode in Colabtools or even Jupyter to step into and out of code inside of code blocks.

### ISSUE THREAD

**Issue by shyamalschandra** [googlecolab/colabtools#887]
This is a feature suggestion or request.  Would it be possible to add a debug mode inside of colabtools or even jupyter in general to make it so one can query the state of each variable in question in the set of statements?

**Comment by shyamalschandra** [comment]
I found this StackOverflow [article](https://stackoverflow.com/questions/32409629/what-is-the-right-way-to-debug-in-ipython-notebook).

**Comment by shyamalschandra** [comment]
Basically, I found what I am looking for but I have to try it [first](https://github.com/pixiedust/pixiedust).

**Comment by shyamalschandra** [comment]
However, [PixieDust](https://pixiedust.github.io/pixiedust/install.html) visual debugger has some compatibility issues with colabtools AFAIK (as far as I know). 

![image](https://user-images.githubusercontent.com/9545735/69902606-6708cf80-1355-11ea-9810-0266f678f7ab.png)

**Comment by tnovikoff** [comment]
https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/01.06-Errors-and-Debugging.ipynb

**Comment by shyamalschandra** [comment]
Thanks, @tnovikoff!  I am reading the notes.
