### ISSUE TITLE
Google Colab won't run any cell and it gives javascript error

### ISSUE THREAD

**Issue by ReemAwadh** [googlecolab/colabtools#889]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
all Google Colab notebooks that I have won't run any cell and gives below error:

Error
Could not load the JavaScript files needed to display output.
This is probably because your Google account login access has expired or because third-party cookies are not allowed by your browser.

Please reload this page.
 DETAILS

tried restarting chrome browser, checked if third party cookies are enabled, checked if javascript are enabled in browser setting and even tried to run google colab in incognito mode and on Firefox but it does not work there either.

another thing noticed is when I log into drive to open google colab notebook the icons are not showing it shows a broken image instead.

- Describe the expected behavior:
should run without issues

- The web browser you are using (Chrome, Firefox, Safari, etc.):
chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by craigcitro** [comment]
Could I ask you to file feedback from within colab when this happens, so we can look at the corresponding backend logs?

**Comment by cperry-goog** [comment]
Consolidating javascript errors to #4427
