### ISSUE TITLE
WIT Jupyter Extention Error

### ISSUE THREAD

**Issue by ksaurav-ds** [googlecolab/colabtools#890]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Age Demo from WIT [From here](: https://colab.research.google.com/github/pair-code/what-if-tool/blob/master/WIT_Age_Regression.ipynb)
- Describe the current behavior:

On executing the command- `WitWidget(config_builder, height=tool_height_in_px)`
I encountered the below error above the WIT extention dashboard:

        Cannot set tensorflow.serving.Regression.value to array([21.733267], dtype=float32): array([21.733267], dtype=float32) has type <class 'numpy.ndarray'>, but expected one of: numbers.Real

- Describe the expected behavior:
Performance Tab is not working. It should be populated with data.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
![WITIssue](https://user-images.githubusercontent.com/51818390/70150626-4d0e1a80-16d0-11ea-99f4-8bdd2b57048b.PNG)

**Comment by blois** [comment]
This should probably be filed against the what-if-tool directly at https://github.com/pair-code/what-if-tool/issues.

**Comment by ksaurav-ds** [comment]
Ok...Thanks.
