### ISSUE TITLE
faceswap error

### ISSUE THREAD

**Issue by Alkatraz91** [googlecolab/colabtools#893]
i got this error using chrome with faceswap tool:

NameError                                 Traceback (most recent call last)
<ipython-input-21-76b10e973f9b> in <module>()
----> 1 model = FaceswapGANModel(**arch_config)

2 frames
/content/faceswap-GAN/networks/nn_blocks.py in conv_block(input_tensor, f, use_norm, strides, w_l2, norm)
    126 def conv_block(input_tensor, f, use_norm=False, strides=2, w_l2=w_l2, norm='none'):
    127     x = input_tensor
--> 128     x = Conv2D(f, kernel_size=3, strides=strides, kernel_regularizer=regularizers.l2(w_l2),  
    129                kernel_initializer=conv_init, use_bias=False, padding="same")(x)
    130     x = Activation("relu")(x)

NameError: name 'regularizers' is not defined

**Comment by colaboratory-team** [comment]
Hello - it appears you are running code from a third-party library on Colab (perhaps https://github.com/shaoanlu/faceswap-GAN?). If you are having issues running their code, please seek support at that repository.
