### ISSUE TITLE
BUG for user input

### ISSUE THREAD

**Issue by temp-mail1** [googlecolab/colabtools#897]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
stop running for a while
- Describe the expected behavior:
the program tell the me to a reason for "why am I sad"
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

Game:
AI Dungeon 2 will save and use your actions and game to continually improve AI
 Dungeon. If you would like to disable this enter 'nosaving' for any action.
 This will also turn off the ability to save games.

Initializing AI Dungeon! (This might take a few minutes)

 ▄▄▄       ██▓   ▓█████▄  █    ██  ███▄    █   ▄████ ▓█████  ▒█████   ███▄    █    
▒████▄    ▓██▒   ▒██▀ ██▌ ██  ▓██▒ ██ ▀█   █  ██▒ ▀█▒▓█   ▀ ▒██▒  ██▒ ██ ▀█   █    
▒██  ▀█▄  ▒██▒   ░██   █▌▓██  ▒██░▓██  ▀█ ██▒▒██░▄▄▄░▒███   ▒██░  ██▒▓██  ▀█ ██▒   
░██▄▄▄▄██ ░██░   ░▓█▄   ▌▓▓█  ░██░▓██▒  ▐▌██▒░▓█  ██▓▒▓█  ▄ ▒██   ██░▓██▒  ▐▌██▒   
 ▓█   ▓██▒░██░   ░▒████▓ ▒▒█████▓ ▒██░   ▓██░░▒▓███▀▒░▒████▒░ ████▓▒░▒██░   ▓██░   
 ▒▒   ▓▒█░░▓      ▒▒▓  ▒ ░▒▓▒ ▒ ▒ ░ ▒░   ▒ ▒  ░▒   ▒ ░░ ▒░ ░░ ▒░▒░▒░ ░ ▒░   ▒ ▒    
  ▒   ▒▒ ░ ▒ ░    ░ ▒  ▒ ░░▒░ ░ ░ ░ ░░   ░ ▒░  ░   ░  ░ ░  ░  ░ ▒ ▒░ ░ ░░   ░ ▒░   
  ░   ▒    ▒ ░    ░ ░  ░  ░░░ ░ ░    ░   ░ ░ ░ ░   ░    ░   ░ ░ ░ ▒     ░   ░ ░    
      ░  ░ ░        ░       ░              ░       ░    ░  ░    ░ ░           ░    
                  ░                                                                

Pick a setting.
0) fantasy (recommended)
1) mystery
2) apocalyptic
3) zombies
4) custom
Enter the number of your choice: 0

Pick a character
0) noble
1) knight
2) squire
3) wizard
4) ranger
5) peasant
6) rogue
Enter the number of your choice: 
Error invalid choice. 
Enter the number of your choice: 1

What is your name? Ben

AI Dungeon 2 Instructions:
 Enter actions starting with a verb ex. "go to the tavern" or "attack the orc."
 To speak enter 'say "(thing you want to say)"' or just "(thing you want to say)"
 

The following commands can be entered for any action: 
  "revert"   Reverts the last action allowing you to pick a different action.
  "quit"     Quits the game and saves
  "restart"  Starts a new game and saves your current one
  "save"     Makes a new save of your game and gives you the save ID
  "load"     Asks for a save ID and loads the game if the ID is valid
  "print"    Prints a transcript of your adventure (without extra newline formatting)
  "help"     Prints these instructions again

Generating story...

You are Ben, a knight living in the kingdom of Larion. You have a steel longsword
 and a wooden shield. You are on a quest to defeat the evil dragon of Larion.
 You've heard he lives up at the north of the kingdom. You set on the path to
 defeat him and walk into a dark forest. As you enter the forest you see an old
 man sitting by a fire. He looks like he is about to fall asleep but keeps looking
 around as if something might be lurking nearby.

"Hello," says the old man. "I am called Ben"
> help

AI Dungeon 2 Instructions:
 Enter actions starting with a verb ex. "go to the tavern" or "attack the orc."
 To speak enter 'say "(thing you want to say)"' or just "(thing you want to say)"
 

The following commands can be entered for any action: 
  "revert"   Reverts the last action allowing you to pick a different action.
  "quit"     Quits the game and saves
  "restart"  Starts a new game and saves your current one
  "save"     Makes a new save of your game and gives you the save ID
  "load"     Asks for a save ID and loads the game if the ID is valid
  "print"    Prints a transcript of your adventure (without extra newline formatting)
  "help"     Prints these instructions again
> ask where is the evil dragon

"The evil dragon?" asks Ben. "What do you mean? I don't understand".
> go in front of the old man

"That's what I'm trying to tell you!" shouts Ben. "The dragon lives in the north
 east part of the kingdom".
> go to the north east part of the kingdom

"I see", says the old man. "So, you want me to take you there?".
> say yes

"Very good, now let's get going. The journey will be quite dangerous for you,
 but we'll make it through it together".
> say okay

"Goodbye, my friend".
> say what do you mean, I through you were coming with me on the journey to the evil dragon

"Oh no, I was not going to come with you on this journey. This journey is too
 dangerous for you. I am sorry, but I can't allow you to accompany me on this
 journey. Goodbye".
> say if that's so, can you give me some tips to defeat the dragon?

"No, I won't help you. Goodbye".
> say okay, I'll go to the north east part of the kingdom

"Thank you for your time, goodbye".
> go to the north east part of the kingdom

"Goodbye, my friend".
> find the dragon

Ben looks at you with his eyes wide open. He didn't expect you to say something
 like that.
> say who am I

"My name is Ben, I live in the northern part of the kingdom of Larion".
> say go defeat the evil dragon in the kingdom

"Okay, I'll try to help you. Good luck, bye".
> good bye

You leave the old man and head towards the north east part of the kingdom. You
 walk along the road and then suddenly you hear a loud noise. A huge black cloud
 appears from nowhere and starts to rain down. It seems like the sky has turned
 dark. Suddenly, you feel very cold
> hide in a cave

A cave is nearby, so you run inside it. You crawl around under the bed and finally
 you find yourself in a small room. There is a table and chairs made out of wood
 and a fireplace. On top of the table sits a young girl dressed in a white dress
> ask the young girl about the evil dragon

"Hello, how are you?", she asks.
> hi, it's raining outside 

"Yes, it is raining outside. What did you want to talk about?", you answer.
> Emmm... I was looking for a way to defeat the dragon

"Well, it's difficult to explain, but I think you should just follow the dragon.
 The dragon is always there, he's not really smart or anything, he just follows
 his instincts. Just wait until night and then attack him".
> say thank you so much, I will do my best for defeating the dragon

"It's been a pleasure talking to you, I hope you succeed".
> Oh, can I have your name?

"My name is Ben, I live in the northern part of the kingdom of Larion".
> ask the young girl what is her name

"Her name is Lina, she's a little girl and she wants to be a knight one day".
> say I hope your dream will come true one day, to be a knight

"Yeah, I wish I could become a knight one day. Thanks for listening to me, bye".
> say goodbye and wait for the rain to end

The rain stops and the sun comes up. You decide to stay here for the night. You
 don't know why, but you feel a bit sad. You look at the fire and the table and
 wonder where the **** you left them all. You also notice that the door is closed
> ask myself why am I feeling sad

After I inputted ask myself why am I felling sad, the program took a minute or so with no response while running the game.

**Comment by colaboratory-team** [comment]
Hello - AI dungeon is a third-party project, not supported by the colab team. If you find issues with the code, please report them at https://github.com/nickwalton/AIDungeon/
