### ISSUE TITLE
Reproducible out of memory crash

### ISSUE THREAD

**Issue by uramer** [googlecolab/colabtools#899]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Out of memory crash. To reproduce: load 95c2fb00-1906-11ea-a04f-0242ac1c0002 and type "Try to cast the spell written on the wall"

- Describe the expected behavior:
No crash.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Desktop Chrome Version 79.0.3945.74 (Official Build) beta (64-bit)
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/github/nickwalton/AIDungeon/blob/master/AIDungeon_2.ipynb

**Comment by colaboratory-team** [comment]
Hello - AI dungeon is a third-party project, not supported by the colab team. If you find issues with the code, please report them at https://github.com/nickwalton/AIDungeon/
