### ISSUE TITLE
Feature Request: Dark Theme

### ISSUE THREAD

**Issue by ghost** [googlecolab/colabtools#90]
It would be very useful to have a dark theme for longer coding sessions. Would this be possible to implement?

**Comment by NikolasBielski** [comment]
[
![tenor](https://user-images.githubusercontent.com/20161742/43178840-9d678000-9023-11e8-8d8c-2ddfec4c6775.gif)
](url)

**Comment by qubix12** [comment]
Any idea if this request is considered?

**Comment by pjmartel** [comment]
Another vote for this. It is really needed,

**Comment by XinyueZ** [comment]
+1

**Comment by seanag0234** [comment]
+1

**Comment by GM223** [comment]
+1

**Comment by AhmetHamzaEmra** [comment]
+1

**Comment by l3r4nd** [comment]
+1

**Comment by UndecidedBoy** [comment]
A Dark Theme would be super nice!
In the meantime, for people who are looking for a work around, the Dark Reader extension is very nice!

**Comment by MihaTomsic** [comment]
In the meantime I have been working on a workaround using Chrome Stylus Extension https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne.

I have put the first semi usable JSON export for the Stylus on the github:
https://github.com/MihaTomsic/DarkGoogleColabStylusTheme

It's far from perfect but it is getting useful.

![image](https://user-images.githubusercontent.com/5785564/48739609-cddcae80-ec54-11e8-9bd5-1e609d07a744.png)

Take care,
M.

**Comment by saicodes** [comment]
Does colab support *jupyter-themes* https://github.com/dunovank/jupyter-themes ?
If anyone has any idea on how this could be done on google colab (looking for a work-around) please do share
Is it possible to upload and apply our custom themes to colab and make it more presentable??

**Comment by tycho01** [comment]
@MihaTomsic any chance of putting the theme on e.g. userstyles.org? (I know that one says Stylish, but I've taken it one was forked from the other.)

**Comment by puraminy** [comment]
I put a dark theme on userstyles.org. To install it you need to first install stylish add-on for Chrome:

https://userstyles.org/styles/168225/dark-theme-for-google-colab-development

![image](https://user-images.githubusercontent.com/5293185/52123201-9ae26e00-263a-11e9-9cde-c41fc054c70b.png)

**Comment by pjmartel** [comment]
@puraminy Thanks Ahmad, I'm using your theme and it looks great! 

P.

**Comment by puraminy** [comment]
> @puraminy Thanks Ahmad, I'm using your theme and it looks great!
> 
> P.

Thanks, I am glad that you find it useful! I may update it in future if I found it lacks something.

**Comment by katlyn-edwards** [comment]
Hey there! Built-in support for dark theme should now be live in the preferences dialog. Please give it a try! There are still a few minor pieces of the UI lacking theme support but those should be fixed shortly. 

Thanks for all the feedback here!

**Comment by puraminy** [comment]
Thanks, 
You just waited till I write a user style.

**Comment by ericricky** [comment]
Is there any chance you can make editable text brighter? [This](http://i.imgur.com/nPSVLqM.png) is what it looks like for me now.

**Comment by puraminy** [comment]
> Is there any chance you can make editable text brighter? [This](http://i.imgur.com/nPSVLqM.png) is what it looks like for me now.

You probably mean the built-in dark theme provided by @katlyn-edwards. Otherwise, if you use the theme I provided, the text in editing mode is yellow.

**Comment by ericricky** [comment]
@puraminy Yeah you're right, I forgot to tag @katlyn-edwards
