### ISSUE TITLE
KeyboardInterrupt

### ISSUE THREAD

**Issue by shiningskyy** [googlecolab/colabtools#900]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
The game won't start. Even if I can't do anything
![sdx](https://user-images.githubusercontent.com/40699129/70380530-1f79d900-193d-11ea-9f74-08ad2ce4c498.PNG)

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome (clear, without any extension)

- Link to self-contained notebook that reproduces this issue
  https://colab.research.google.com/github/nickwalton/AIDungeon/blob/master/AIDungeon_2

**Comment by craigcitro** [comment]
AI dungeon is a third-party project, not supported by the colab team. If you find issues with the code, please report them at https://github.com/nickwalton/AIDungeon/
