### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by cytotechnologist** [googlecolab/colabtools#904]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: Doesn't do anything at all, just error codes.

- Describe the expected behavior:

Initializing AI Dungeon! (This might take a few minutes)

Traceback (most recent call last):
  File "play.py", line 211, in <module>
    play_aidungeon_2()
  File "play.py", line 74, in play_aidungeon_2
    generator = GPT2Generator()
  File "/content/AIDungeon/generator/gpt2/gpt2_generator.py", line 27, in __init__
    self.enc = encoder.get_encoder(self.model_name, models_dir)
  File "/content/AIDungeon/generator/gpt2/src/encoder.py", line 111, in get_encoder
    with open(os.path.join(models_dir, model_name, 'vocab.bpe'), 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'generator/gpt2/models/model_v5/vocab.bpe'

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/github/nickwalton/AIDungeon/blob/master/AIDungeon_2.ipynb

**Comment by attbon** [comment]
Got an extremely similar error.  It worked yesterday however today I got:

Traceback (most recent call last):
  File "play.py", line 211, in <module>
    play_aidungeon_2()
  File "play.py", line 74, in play_aidungeon_2
    generator = GPT2Generator()
  File "/content/AIDungeon/generator/gpt2/gpt2_generator.py", line 29, in __init__
    with open(os.path.join(models_dir, self.model_name, 'hparams.json')) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'generator/gpt2/models/model_v5/hparams.json'

**Comment by craigcitro** [comment]
AI dungeon is a third-party project, not supported by the colab team. If you find issues with the code, please report them at https://github.com/nickwalton/AIDungeon/
