### ISSUE TITLE
1. Download progress 2. short operating time

### ISSUE THREAD

**Issue by Tofu-96** [googlecolab/colabtools#905]
Every time I turn on the game I have to wait a few hours until something loads and when it loads
the game only works for 10-15 minutes then the game lose connection to the host at the very beginning I didn't have this first problem

 *** Download Progress Summary as of Sun Dec  8 13:31:20 2019 *** 
[#f903b9 0B/5.8GiB(0%) CN:0 SD:0 DL:0B]
FILE: /content/AIDungeon/generator/gpt2/models/model_v5/checkpoint (6more)

 *** Download Progress Summary as of Sun Dec  8 14:07:39 2019 *** 
[#f903b9 1.8GiB/5.8GiB(32%) CN:44 SD:4 DL:1.0MiB UL:0B(2.4MiB) ETA:1h4m32s]
FILE: /content/AIDungeon/generator/gpt2/models/model_v5/checkpoint (6more)

my browsers Chrome and Opera

**Comment by colaboratory-team** [comment]
AI dungeon is a third-party project, not supported by the colab team. If you find issues with the code, please report them at https://github.com/nickwalton/AIDungeon/
