### ISSUE TITLE
Drive mounts as root ... and user cannot run apps from root directory

### ISSUE THREAD

**Issue by rayanfer32** [googlecolab/colabtools#906]
Bug report for Colab: 

- I'm trying to run an app directly from the mounted drive FS ,and it is giving me permission denied error

- i should be able to run app as user from drive 

- The web browser i'am  using is chrome

**Comment by tnovikoff** [comment]
Tracking at b/146234889

**Comment by tnovikoff** [comment]
Execution in a mounted directory should be possible. Perhaps you are trying to run a file that is not chmod'd u+x, or e.g. trying to run a windows program on a linux VM. Without a repro notebook with and repro instructions it's hard to say more.

**Comment by Rayanfer32** [comment]
yea right i didnt notice that either.... gonna try it
