### ISSUE TITLE
GPU device not found on my notebooks...only works on demos

### ISSUE THREAD

**Issue by JohnTheLearner** [googlecolab/colabtools#91]
My notebook didn't work w/ GPU, so I created new Python 2 (&3) notebooks and pasted the below sample code to check GPU status:

`import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))
`

What I initially get is:

`InternalError: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 11995578368
`

After this initial error, I get the below when re-executing the cell:

`
SystemErrorTraceback (most recent call last)
<ipython-input-2-d1680108c58e> in <module>()
      2 device_name = tf.test.gpu_device_name()
      3 if device_name != '/device:GPU:0':
----> 4   raise SystemError('GPU device not found')
      5 print('Found GPU at: {}'.format(device_name))

SystemError: GPU device not found
`

I tried this with no other notebooks open, tried saving the notebook, interrupting/restarting, etc., but still getting the above.

Please advise.

**Comment by fischman** [comment]
This reads a lot like #56. Please see the advice there and reopen with repro notebook if the advice there doesn't work for you (note in particular the reset advice).
