### ISSUE TITLE
javac and java have different alternatives set

### ISSUE THREAD

**Issue by cmacdonald** [googlecolab/colabtools#915]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: /etc/alternatives/javac and /etc/alternatives/java link to java 8 and java 11 respectively

- Describe the expected behavior: I thought we would see the same version? Is this intentional?

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome, but not relevant

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/drive/1PozK8gr3kaHMat2TZbcsyHeioodoAhtl

**Comment by cmacdonald** [comment]
Bump?

**Comment by colaboratory-team** [comment]
Sorry for radio silence, and thanks for reporting this issue. 
Bundling both 8 and 11 was unintentional and we'll drop 8, adding JDK 11. 
Will update this bug when that change is released.

**Comment by colaboratory-team** [comment]
This change is now released. If you still see both 8 & 11 you probably have a VM that started before the latest release; use [Runtime -> Factory reset runtime] to get a fresh one.

Thanks again for the report.

**Comment by cmacdonald** [comment]
looks good to me, thanks!
