### ISSUE TITLE
Link to create a new Swift notebook doesn't work.

### ISSUE THREAD

**Issue by korakot** [googlecolab/colabtools#917]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

I can create a new notebook that specify python2, python3, and r. 

For example, with R it is:

https://colab.research.google.com/notebook#create=true&language=r

However, this doesn't work with Swift

https://colab.research.google.com/notebook#create=true&language=swift

- Describe the expected behavior:

https://colab.research.google.com/notebook#create=true&language=swift should create a new Swift notebook.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome.

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by BradLarson** [comment]
If it helps, the following link will start you with a new blank Swift notebook in Colab:

https://colab.research.google.com/github/tensorflow/swift/blob/master/notebooks/blank_swift.ipynb

**Comment by blois** [comment]
This is now fixed.
