### ISSUE TITLE
KeyError: 'CLOUDSDK_CONFIG' when drive.mount('/content/drive', force_remount=True)

### ISSUE THREAD

**Issue by xyzPrimeTV** [googlecolab/colabtools#922]
When I am mounting drive I am getting the error on local Jupyter notebook...

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Output===>
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-36dbed4a69ff> in <module>
      1 from google.colab import drive
      2 
----> 3 drive.mount('/content/drive', force_remount=True)

/usr/lib/python3.8/site-packages/google_colab-1.0.0-py3.8.egg/google/colab/drive.py in mount(mountpoint, force_remount, timeout_ms, use_metadata_server)
    104     return
    105 
--> 106   env = _env()
    107   home = env.home
    108   root_dir = env.root_dir

/usr/lib/python3.8/site-packages/google_colab-1.0.0-py3.8.egg/google/colab/drive.py in _env()
     42   home = _os.environ['HOME']
     43   root_dir = _os.path.realpath(
---> 44       _os.path.join(_os.environ['CLOUDSDK_CONFIG'], '../..'))
     45   inet_family = 'IPV4_ONLY'
     46   dev = '/dev/fuse'

/usr/lib/python3.8/os.py in __getitem__(self, key)
    671         except KeyError:
    672             # raise KeyError with the original key value
--> 673             raise KeyError(key) from None
    674         return self.decodevalue(value)
    675 

KeyError: 'CLOUDSDK_CONFIG'
------------------------------------------------------------------------------

How can I solve this issue ?

Thanks in advance.

**Comment by craigcitro** [comment]
We don't support using `google.colab` with local runtimes.

**Comment by parisak916** [comment]
Hi,

Can you elaborate how I can create an environment not locally?

**Comment by pradeeps147** [comment]
File "/home/pradeep/.virtualenvs/ai/lib/python3.6/site-packages/google/colab/drive.py", line 43, in _env
    _os.path.join(_os.environ['CLOUDSDK_CONFIG'], '../..'))
  File "/home/pradeep/.virtualenvs/ai/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'CLOUDSDK_CONFIG'

**Comment by Brandy0k** [comment]
> File "/home/pradeep/.virtualenvs/ai/lib/python3.6/site-packages/google/colab/drive.py", line 43, in _env _os.path.join(_os.environ['CLOUDSDK_CONFIG'], '../..')) File "/home/pradeep/.virtualenvs/ai/lib/python3.6/os.py", line 669, in **getitem** raise KeyError(key) from None KeyError: 'CLOUDSDK_CONFIG'

how to solve this problem?
