### ISSUE TITLE
Pytorch CUDA Error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by adtabia** [googlecolab/colabtools#923]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
When i try to define a model to a device 'cuda:0' it brokes with the error *CUDA error: an illegal memory access was encountered*. This use to work a few days ago.

- Describe the expected behavior:
It should compile and work without any error

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
![colab_error](https://user-images.githubusercontent.com/40809017/71366271-4f052400-2580-11ea-96d1-3fa66d7e0786.PNG)

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by KhoomeiK** [comment]
How did you solve this? I've opened #1493 which seems to be similar to your issue, but I was able to narrow the bug down a lot. Seems to be some problem with handling CUDA internal state.
