### ISSUE TITLE
Colab GPU unavailable for torch 1.3.1 or tensorflow 1.15.0

### ISSUE THREAD

**Issue by junwen-austin** [googlecolab/colabtools#930]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
The default tensorflow and torch on Colab do not appear to be able to use GPU with GPU as runtime:

import tensorflow as tf
print(tf.__version\_\_)
tf.test.is_gpu_available()

returns:

1.15.0
False

Same with the torch:

import torch
print(torch.__version\_\_)
torch.cuda.is_available()

returns:

1.3.1
False

- Describe the expected behavior:
GPU should be available for use with runtime=GPU
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by colaboratory-team** [comment]
To use a GPU, you need to switch to a GPU runtime. Choose *Runtime*->*Change Runtime Type* and then select *Hardware Accelerators*->*GPU* and click Save, then rerun your cells.

If you are already using a GPU runtime and you cannot connect to a GPU, it may indicate that you've modified the VM environment in a way that makes it unable to connect. Choose *Runtime*->*Factory Reset Runtime* to get a clean VM, and then try again.
