### ISSUE TITLE
Monaco editor in a bad state

### ISSUE THREAD

**Issue by rtatgit** [googlecolab/colabtools#932]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Opening a .py file in the editor throws a notification at the bottom left saying monaco editor is in a bad state.
- Describe the expected behavior:
Editor must open without any such notification of bugs.
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Observed in Chrome.
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1p7tKYGDJqhfGM3uMGuywjYhLKGQE6O7l

**Comment by katlyn-edwards** [comment]
Hey there, 
I'm not able to reproduce this issue. Note that files like "setup.py" aren't shared via your notebook. I created a new file by right clicking in the file pane, and saved it as setup.py, and added "print(hi)", saved and re-opened it, and didn't experience any errors in the console (I'm assuming you're seeing this in the console?).

Is it possible that the setup.py file is maybe malformed and causing the error?

**Comment by rtatgit** [comment]
Hey @katlyn-edwards. 
There is no issue opening the python files, it seems the pop-up (In the notebook and not in the console) randomly prompted me to report a bug for "monaco editor being in a bad state" . The issue is not recurring and I am not observing it as of this time. Wish I had taken a screenshot!. Anyone really having issues with the editor can reopen this issue.
