### ISSUE TITLE
Can not interupr Kernel

### ISSUE THREAD

**Issue by kotinigor** [googlecolab/colabtools#933]
I can not interupt kernel. When I press Interupt Execusion kernel continue to work.
- The web browser you are using (Chrome):
- Link to self-contained notebook that reproduces this issue
I can not share because "Sorry, sharing is unavailable at this time. Please try again later."

**Comment by craigcitro** [comment]
This is almost surely an indicator that you're stuck in C/C++ code that isn't respecting your interrupt; this is unfortunately WAI.

Is the sharing error still there? Is it reproducible?
