### ISSUE TITLE
tf.config.experimental_connect_to_cluster report error code 12 with tf2.1 use tpu

### ISSUE THREAD

**Issue by ofpppppppdbfjs** [googlecolab/colabtools#934]
if '2.1' in tf.__version__:
        if 'COLAB_TPU_ADDR' in os.environ:
            tpu = tf.distribute.cluster_resolver.TPUClusterResolver()
            print('Running on TPU ', tpu.cluster_spec().as_dict())
            tf.config.experimental_connect_to_cluster(tpu)
            tf.tpu.experimental.initialize_tpu_system(tpu)
            strategy = tf.distribute.experimental.TPUStrategy(tpu)

**Comment by jsnydes** [comment]
try:
```
!pip install -U tensorflow-gcs-config==2.1.3
import os
tf.config.experimental_connect_to_host('grpc://' + os.environ['COLAB_TPU_ADDR'])
from google.colab import auth
auth.authenticate_user()
import tensorflow_gcs_config
tensorflow_gcs_config.configure_gcs_from_colab_auth()
```
