### ISSUE TITLE
Colab dark mode: flashes of white

### ISSUE THREAD

**Issue by MentalGear** [googlecolab/colabtools#936]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
When opening colab in a new tab, or while loading outputs in a notebook, there are flashes of white as the page is loading, which are very irritating when working in dark/focused mode.

- Describe the expected behavior:
Smooth dark mode, no white flashes.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Safari,, Chrome, Firefox.

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
Any notebook.

- How to fix ?
Set the default background color for new pages/outputs to a dark color. It won't matter in light mode, but makes a huge difference in dark mode (white is much more luminance intensive than dark, e.g. more annoying to get flashed by it, whereas the opposite has no effect)

**Comment by techtide** [comment]
Do you perhaps have power mode turned on without enough suitable resources (toggle via Tools/Settings/Miscellaneous)? The lower power modes do have some white flashes by design when using it. Also, are you using the new editor version? I just can't seem to replicate it on the latest version of Chrome (79.0.3945.88).
![Power Mode](https://user-images.githubusercontent.com/8594707/71834411-13ea1100-30a7-11ea-8505-c5462459402b.png)

**Comment by katlyn-edwards** [comment]
I've seen this with outputs before, but we've worked on the "opening a new tab" portion extensively to make that as smooth as possible.

We do store preferences in two places -- localstorage in your browser and in Google Drive. Drive is a bit slower to get the preferences from, so it's possible to see a flash if say your local storage says "light theme" and Google Drive says "dark theme". Note that we sync up both once drive loads, so this should only happen once. 

Created b/147229665 internally to track output frames.

**Comment by MentalGear** [comment]
Thanks for your replies !

@katlyn-edwards Mh, since google drive doesn't provide a dark theme yet, it probably says always "light theme". A quick way for a better UX / fix, would be to give the console outputs by default a dark background, and switch it to light only if the light theme is enabled. Why is a default dark better? Light is much more intense (higher luminance) than dark, therefore way more annoying to get flashed by it, than encountering a dark BG flash in a light theme.


#techtide: no, I don't use a power mode.
