### ISSUE TITLE
Opening notebooks from Github doesn't clone all the required files

### ISSUE THREAD

**Issue by tlemo** [googlecolab/colabtools#937]
When opening a notebook from Github, the notebook container seems to clone only the .ipynb file. 

This is a problem if the notebook depends on other files in the repository (ex. modules or data files) and severely limits the ability to use colab + github. In contrast, mybinder will clone the whole repository, making it easier to add a "launch in binder" badge to the Github repository.

**Comment by korakot** [comment]
You can do it yourself with

    !npx degit user/projectname -f

**Comment by tlemo** [comment]
Thanks @korakot, but why not doing this automatically? Or at very least prompt the user?
