### ISSUE TITLE
can't load and save colab notebook

### ISSUE THREAD

**Issue by please-nooo-overfit** [googlecolab/colabtools#942]
I can't save my colab notebook.
I've run it on chrome, firefox, safari,
I guess this is a problem with my account.

**Comment by specht-luccas** [comment]
I too can't load my colab notebook. 
I'm using python 3 actually but i can't open it.
when i press 'new python 3 notebook' . it show the follwing error:  Unable to load Colaboratory.
does somebody with the same error?
it's my frist time using google colab

**Comment by blois** [comment]
Are there any errors in the Chrome developer tools console?
