### ISSUE TITLE
Error in library(randomForest): there is no package called ‘randomForest’ Traceback:  1. library(randomForest)

### ISSUE THREAD

**Issue by wiccaswati** [googlecolab/colabtools#944]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment]
This is WAI: if you'd like to use another package, you can install it.
