### ISSUE TITLE
notebook name does not get saved

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#945]
I renamed a notebook and then saved the notebook, then restarted my computer, but after restart, the name of notebook changes back to Untitled, and the name that I gave did not get saved.

**Comment by ahariri13** [comment]
@vainaijr how did you solve this this issue ?

**Comment by vainaijr** [comment]
I do not exactly remember, but maybe I just reloaded my notebook, and the name started displaying.
