### ISSUE TITLE
'Your session crashed for an unknow reason'  when run cell 'set_session(...'

### ISSUE THREAD

**Issue by MK2345** [googlecolab/colabtools#946]
Bug report for Colab: http://colab.research.google.com/.

Timestamp | Level | Message
-- | -- | --
Jan 12, 2020, 3:46:13 PM | WARNING | WARNING:root:kernel 351e3411-a04c-4198-96df-0cf7e3106605 restarted
Jan 12, 2020, 3:46:13 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Jan 12, 2020, 3:46:13 PM | WARNING | 2020-01-12 14:46:13.355670: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Not found: no CUDA devices found
Jan 12, 2020, 3:46:01 PM | WARNING | 2020-01-12 14:46:01.537574: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (cfafab0770c5): /proc/driver/nvidia/version does not exist
Jan 12, 2020, 3:46:01 PM | WARNING | 2020-01-12 14:46:01.536588: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Jan 12, 2020, 3:46:01 PM | WARNING | 2020-01-12 14:46:01.450757: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
Jan 12, 2020, 3:46:01 PM | WARNING | 2020-01-12 14:46:01.419454: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (0): Host, Default Version
Jan 12, 2020, 3:46:01 PM | WARNING | 2020-01-12 14:46:01.419389: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x17c3100 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
Jan 12, 2020, 3:46:01 PM | WARNING | 2020-01-12 14:46:01.415809: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
Jan 12, 2020, 3:45:54 PM | INFO | Adapting to protocol v5.1 for kernel 351e3411-a04c-4198-96df-0cf7e3106605

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

When trying to run the cell with following code, then the session crashed:

`from keras import backend as K

if 'tensorflow' == K.backend():
  import tensorflow as tf
  from keras.backend.tensorflow_backend import set_session
  config = tf.ConfigProto()
  config.gpu_options.allow_growth = True
  config.gpu_options.visible_device_list = "0"
  #session = tf.Session(config=config)
  set_session(tf.Session(config=config))`

I had recently loaded data set into GoogleDrive. In order to exclude that there is no connection between the crashes and this data set, I removed the data set from GoogleDrive. 
But the sessions are still crashing.

- Describe the expected behavior:
I want to use GoogleColab again without session crash

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Opera

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
All my notebooks in googleColab crashing since a few hours
https://colab.research.google.com/drive/1aKy0o33ej8FSHQlyLc5dvVRqgj11-7YV#scrollTo=V1n934sU82p0
![colabCrash](https://user-images.githubusercontent.com/24621381/72220714-daf0e700-3553-11ea-86e3-32205bcd062e.PNG)

**Comment by colaboratory-team** [comment]
The tensorflow FATAL error is triggered by specifying
`config.gpu_options.visible_device_list = "0"`
on a VM with no GPU. Omit that line if you're not trying to use a GPU (in which case also `config.gpu_options.allow_growth = True` isn't adding value and you can drop it), or select "GPU" from the [Hardware accelerators] drop-down in the Notebook Settings dialog.
