### ISSUE TITLE
Sign-in spins forever when trying to mount Drive

### ISSUE THREAD

**Issue by dsaff** [googlecolab/colabtools#947]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: When I try to mount drive, using the exact code from the snippet, it prompts me to sign in and authorize, and then it spins forever on a screen saying "Success!", without ever actually giving me an authorization code 

- Describe the expected behavior: OAuth sign-in eventually results in an authorization code

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/drive/1dLddSSgX_Xz7hCFnzTuPfbWFtadGtouE

Note:

This was working fine, in all notebooks, for this account, until sometime in late December.  Since then, all notebooks for this account exhibit this same behavior, but the same code will mount just fine with other accounts.

Based on other advice, I have reduced the number of files in my Google Drive root to less than 20, and emptied the trash.

This is the spinner I get forever in my sign-in tab:

<img width="480" alt="Screen Shot 2020-01-14 at 4 29 00 PM" src="https://user-images.githubusercontent.com/46155/72384249-04904680-36eb-11ea-8ce3-005a79152373.png">

**Comment by colaboratory-team** [comment]
Per off-bug convo this resolved itself.

If anyone else sees this behavior, please:
- see if it repros in an Incognito window (to rule out interference from extensions)
- "send feedback" in colab referencing this github issue and copy/paste the contents of the chrome devtools JS console for the team to be able to correlate google account information without posting private information on this public tracker.
