### ISSUE TITLE
GPU out of memory error - memory already allocated before code starts to run

### ISSUE THREAD

**Issue by PaulBrook** [googlecolab/colabtools#950]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

I'm using a GPU on Google Colab to run some deep learning code.

I have got 70% of the way through the training, but now I keep getting the following error:

`RuntimeError: CUDA out of memory. Tried to allocate 2.56 GiB (GPU 0; 15.90 GiB total capacity; 10.38 GiB already allocated; 1.83 GiB free; 2.99 GiB cached)`

When I try to restart it, the memory message appears immediately.

- Describe the expected behavior:

The notebook has been running the same script fine and I have restarted the code many times on previous days. I've never had a RAM issue.

Could someone explain why the error message says `10.38 GiB already allocated` - how can there be memory already allocated when I start to run something. Could that be being used by someone else? Do I just need to wait and try again later?

I have also tried to reset the runtime but the same thing happens.

https://colab.research.google.com/drive/1p_2kQmKSM2lkkJ_16p8NEAJeUJ0cw_pB

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

[https://colab.research.google.com/drive/1p_2kQmKSM2lkkJ_16p8NEAJeUJ0cw_pB](https://colab.research.google.com/drive/1p_2kQmKSM2lkkJ_16p8NEAJeUJ0cw_pB
![gpu](https://user-images.githubusercontent.com/9338709/72625124-1585c580-3940-11ea-97e6-3b35a2e1eb3a.png)
)

**Comment by blois** [comment]
We just backed out a recent change, would it be possible to try again?

You can request a new runtime with the 'Runtime->Factory reset runtime' menu item.

**Comment by PaulBrook** [comment]
Thank you for the reply. I just tried again after a Factory reset runtime but unfortunately I I still got: 

`RuntimeError: CUDA out of memory. Tried to allocate 2.56 GiB (GPU 0; 15.90 GiB total capacity; 10.37 GiB already allocated; 1.44 GiB free; 3.38 GiB cached)`

**Comment by colaboratory-team** [comment]
> how can there be memory already allocated when I start to run something"

That's not what's happening - nvidia-smi's output in your notebook shows nothing is using the GPU to start with. Memory is allocated as part of your computation, when then fails part-way through, having already allocated >10GiB and failing to allocate more.

> Could that be being used by someone else?

No, GPUs are not shared among users.

You could try reducing your data/batch/epoch sizes to try and fit into RAM. 
Note that colab offers a variety of different GPU types with different architectures and capacities, so a model that trains ok on one may fail on another.

**Comment by PaulBrook** [comment]
That makes sense, thank you. I don't understand though, why my screenshot shows `RAM: 2.22 GB` just before the error. It never gets much above 2 GB before it runs out of memory. Certainly never seems to get anywhere near 10 GB.

**Comment by colaboratory-team** [comment]
The `RAM: 2.22 GB` in the hover info is talking about "main" memory (alternately known as "CPU", "general purpose", or "system" memory), but the `CUDA out of memory` error is referring to "GPU" memory; the two types of memory are distinct pools that can't generally be used interchangeably.

**Comment by PaulBrook** [comment]
That's great - it's good to learn something when one posts on a forum. Cutting my batch sizes fixed the problem as you suggested. Thank you for replying and clearing things up.
