### ISSUE TITLE
Please check the colab tf2.x1`s environment, since yestoday TPU can not work

### ISSUE THREAD

**Issue by ofpppppppdbfjs** [googlecolab/colabtools#952]
Bug report for Colab: http://colab.research.google.com/.

in tf 2.x  TPU  mode ,  run  model.fit()  func , get crashed, 

Jan 18, 2020, 5:00:48 PM | WARNING | WARNING:root:kernel be8688bc-f368-4a35-83b4-f51e049f21e2 restarted
-- | -- | --
Jan 18, 2020, 5:00:48 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Jan 18, 2020, 5:00:46 PM | WARNING | 2020-01-18 09:00:46.168597: E tensorflow/core/framework/dataset.cc:86] The Encode() method is not implemented for DatasetVariantWrapper objects.
Jan 18, 2020, 4:59:39 PM | WARNING | 2020-01-18 08:59:39.141626: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Jan 18, 2020, 4:58:45 PM | INFO | Kernel restarted: be8688bc-f368-4a35-83b4-f51e049f21e2
Jan 18, 2020, 4:58:42 PM | WARNING | warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
Jan 18, 2020, 4:58:42 PM | WARNING | /usr/local/lib/python3.6/dist-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
Jan 18, 2020, 4:57:21 PM | WARNING | 2020-01-18 08:57:21.627846: W tensorflow/core/distributed_runtime/rpc/grpc_session.cc:370] GrpcSession::ListDevices will initialize the session with an empty graph and other defaults because the session has not yet been created.
Jan 18, 2020, 4:43:30 PM | WARNING | 2020-01-18 08:43:30.075329: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (181e09943b9f): /proc/driver/nvidia/version does not exist
Jan 18, 2020, 4:43:30 PM | WARNING | 2020-01-18 08:43:30.075281: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

**Comment by jsnydes** [comment]
Hi, could you add a publicly-shared notebook that reproduces this problem?

**Comment by jonashaag** [comment]
Have this problem too, can give you private access to Colab notebook that reproduces the issue.

**Comment by jonashaag** [comment]
The crash also happens when simply doing a `next(iter(mydataset))`

**Comment by jonashaag** [comment]
It happens when there's an exception in a `.map` function.

**Comment by jonashaag** [comment]
Now have an example where there is no exception in the dataset generation, at least not when no TPU is connected. When a TPU is connected, `next(iter(mydataset))` crashes the runtime (not sure due to exception or something else).

**Comment by jonashaag** [comment]
The error probably comes from this issue that is only shown when _defining_ the dataset _after_ TPU has been initialized:

```
---------------------------------------------------------------------------

UnavailableError                          Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py in execution_mode(mode)
   1985       ctx.executor = executor_new
-> 1986       yield
   1987     finally:

13 frames

UnavailableError: failed to connect to all addresses
Additional GRPC error information:
{"created":"@1589984004.316700793","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3959,"referenced_errors":[{"created":"@1589984004.316698995","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}


During handling of the above exception, another exception occurred:

UnavailableError                          Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/executor.py in wait(self)
     65   def wait(self):
     66     """Waits for ops dispatched in this executor to finish."""
---> 67     pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
     68 
     69   def clear_error(self):

UnavailableError: failed to connect to all addresses
Additional GRPC error information:
{"created":"@1589984004.316700793","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3959,"referenced_errors":[{"created":"@1589984004.316698995","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}

```
