### ISSUE TITLE
entire section for %%R

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#955]
- Describe the current behavior:
if i want to run R, then I need to specify %%R in multiple code cells, for example

code cell 1
```
%load_ext rpy2.ipython
```
code cell 2
```
%%R 
library(datasets)
head(iris)
```
code cell 3
```
%%R
summary(iris)
```

- Describe the expected behavior:
specify %%R once for a section, and all cells within that section run R.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

**Comment by lgautier** [comment]
This is working as intended. The "R magic" is made to allow calling R from a Python notebook when needed, and the scope of jupyter magics is limited to its cell.

If wanting to have an R notebook, an R kernel should be used instead of a Python kernel.

I think that the issue can be closed.
