### ISSUE TITLE
A py file uploaded to google drive but not seen by Colab python

### ISSUE THREAD

**Issue by junwen-austin** [googlecolab/colabtools#957]
- Describe the current behavior:
I have a small .py file that is uploaded to Google Drive but cannot be seen on Colab. I've tried to force remount the google drive, restart run time, reset to the factory runtime, and still does not work. What is even more interesting is by using !more command line on the Colab, the Colab shows the latest .py file but when executing it with python, it stills only saw old version. 

- Describe the expected behavior:
The Colab should see latest version of files from Google Drive

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Tried Chrome and Safari

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment]
This isn't anything to do with colab -- in python, once you've imported a module, any further imports are no-ops until you restart python or use `importlib.reload`; see the docs for more info: https://docs.python.org/3/library/importlib.html#importlib.reload

**Comment by junwen-austin** [comment]
Thanks for getting back to me! Actually I was not importing a py file in the notebook and I understand the changes on the py file will not be automatically reflected in the notebook unless reloading the module.

What I was doing is run the py file directly in the notebook by involving
!python -m my_module

and my_module is in the py file. I edit the py file and verified it was updated in the google drive. However, when running !python -m my_module in the notebook, it appears the Colab still saw the old version.
