### ISSUE TITLE
Monaco editor is in a bad state

### ISSUE THREAD

**Issue by asaf-kali** [googlecolab/colabtools#959]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
Using `np.random.uniform` gave `ValueError: low >= high`. Since that happened, changes made to the file that raised this excpetions have no effect. When opening the file, the "Monaco editor is in a bad state" sign pops at the bottom of the screen. The file is editable and can be saved, but changes to the file (including removing it entierly) do not effect the run, and the same ValueError raises...
- Describe the expected behavior:
Changes to the file need to effect the run (adding prints, changing code lines).
The "Monaco editor is in a bad state" sign should not pop.
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome 79.0.3945.130 (64-bit).
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://drive.google.com/file/u/0/d/1YdPU5gFnEN850S3x_Gd_sQdi5JM-tFve/edit

**Comment by craigcitro** [comment]
Can you share the notebook you linked?

**Comment by asaf-kali** [comment]
I know it's not convenient, but as this is a school project, I don't want to publicly share it. Please request access and i'll grant it.

**Comment by craigcitro** [comment]
Can you make a minimal repro notebook and share that?

**Comment by asaf-kali** [comment]
The session is has retarted and I can't seem to reproduce it now.
