### ISSUE TITLE
on the colab notebook 

### ISSUE THREAD

**Issue by JAYBIRD97** [googlecolab/colabtools#96]
i can not access my files in it and it is really frustrating me cause i like using that format instead of the others please how do i fix it

**Comment by craigcitro** [comment]
I'm not quite sure what you're asking here; I suspect you're saying that you can't see your Google Drive files directly from Colab. This is expected: Colab doesn't automatically make your Drive files visible; some recipes for fetching these files are at https://colab.research.google.com/notebooks/io.ipynb.

Feel free to reopen if I've misunderstood your issue.
