### ISSUE TITLE
Driver to mount Google Drive in the file system has a cache that is not a cache

### ISSUE THREAD

**Issue by bsolano** [googlecolab/colabtools#960]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:

In December, disk sizes have changed.  The disk on the GPU backend went to a minimal size, and it does not permit the use of large datasets.  One proposed solution at Sourceforge (the site you are recommending for questions) is to mount Google Drive. Therefore I bought 200 GB of Google Drive. However, the disk size is still an issue. The driver to mount Google Drive has a cache that is not a cache, it is a copy. Therefore any file you read will be copied on the disk and that will fill the disk. Apparently once Google Drive is mounted it starts to cache files in /root/.config/Google/DriveFS/[uniqueid]/content_cache. The cache has no control over its size, it does not delete or replace anything, it just accumulates data, and it takes all the disk making the code crash.

- Describe the expected behavior:

Mounting Google Drive and not filling the disk with a full copy of what is on Google Drive.  The copy should be partial, that is a cache.

**Comment by OleAd** [comment]
Did you figure out a workaround for this? Running into the same issue.

**Comment by dorukkarinca** [comment]
Is it safe to delete that directory periodically?

**Comment by colaboratory-team** [comment]
Deleting that directory while Drive is unmounted (e.g. after running `drive.flush_and_unmount()`) is safe, but doing so while Drive is mounted is likely to lead to problems.
The cache should limit itself to a sensible amount of the disk. If you can share a minimal notebook that reproduces an issue starting from "Factory reset runtime" (in the Runtime menu or the command palette) then please do share it either publicly or just with colaboratory-team@google.com as Viewer and paste the link here.

**Comment by DanielMarchand** [comment]
It is certainly not a minimal example but this notebook shows that this problems prevents following along to a popular book on deep learning "Deep Learning with Pytorch". https://colab.research.google.com/drive/1yr0w9f6ijHC8P18FSxEKvCyuDlHQsHNs?usp=sharing

Actually, you can see that /root become needlessly bloated just by downloading the files into gdrive (but it gets worse and worse as the exercises go on.

**Comment by colaboratory-team** [comment]
@DanielMarchand thanks for the repro. Tracked internally as b/182073735.

**Comment by colaboratory-team** [comment]
The cache will limit itself to a sensible amount of disk when reading, but this issue revolves around writing.
The cache does not delete local data while it is still being uploaded. You can avoid the issue while downloading the subset zip files in @DanielMarchand's notebook by interleaving calls to 
```
drive.flush_and_unmount()
drive.mount('/content/gdrive')
```
between the `wget`s to make one upload complete before the next download starts.

Note that that notebook also extracts archives to Google Drive, so you'll probably want to account for this during extraction as well.
