### ISSUE TITLE
apt updgrade results in crash loop

### ISSUE THREAD

**Issue by chlorophyll-zz** [googlecolab/colabtools#962]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
```
!apt update
!apt upgrade -y
!apt-get dselect-upgrade -y
```
results in disconnection loop and crash loop

- Describe the expected behavior:

upgrading the packages, restarting, kexec in the upgraded kernel, reconnecting

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/drive/1qC4plmXPnrkDOLtdZ9wBJbKCx0vdH69_

**Comment by craigcitro** [comment]
Colab runtimes don't support kernel upgrades.
