### ISSUE TITLE
Sorry, no backends available. Please try again later.

### ISSUE THREAD

**Issue by sasagr** [googlecolab/colabtools#968]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
On a specific account I m recently getting always this message when trying to connect:
Sorry, no backends available. Please try again later.
On other account, same browser I have no issues. I sent also a feedback
- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome and Safari
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by tnovikoff** [comment]
You can learn more about the resource limits in Colab at the Colab FAQ:
https://research.google.com/colaboratory/faq.html#resource-limits

**Comment by martinetmayank** [comment]
I'm also having the same problem.

**Comment by pratikbits** [comment]
I am also having the same problem. It works with other account with same browser but not with same account with different browser.

**Comment by hayupadhyaya** [comment]
I have this problem after 12 hours I still can't use it.
any solutions?

**Comment by pratikbits** [comment]
The backend issue is solved. Cells are running.

**Comment by pratikbits** [comment]
The same problem again appeared today, just now.

**Comment by mxt8380** [comment]
I have had the same problem for at least a month? Do you guys block certain accounts for some reason?

**Comment by ChuaCheowHuan** [comment]
Hi, I'm having the same issue with Colab (default settings) on Chrome. I'm not using Colab's GPU or TPU.

**Comment by pratikbits** [comment]
try changing the account

**Comment by abdimk** [comment]
am having this problem like for a month

**Comment by testonamonaco** [comment]
It's happening again! Colab says "Sorry, no backends available. Please try again later."

**Comment by rcanand** [comment]
Just happened again.

**Comment by TranHuuNhatHuy** [comment]
@annidamf same for me, seems something's broken on Colab's side

**Comment by annidamf** [comment]
I hope they fix it as soon as possible :)

**Comment by aditikilledar** [comment]
I’m facing the same issue. Using colab’s default settings.

**Comment by craigcitro** [comment]
For all the commenters in the last 3h: We had an availability issue on our side, which led to failed GPU assignments; we believe we've found the root cause and the issue should resolve shortly.

**Comment by olusegunajibola** [comment]
Yes, I thought I was the only one.

Hoping the system gets back up ASAP.

**Comment by annidamf** [comment]
amazing, thank you!! :) @craigcitro and the team

> For all the commenters in the last 3h: We had an availability issue on our side, which led to failed GPU assignments; we believe we've found the root cause and the issue should resolve shortly.

**Comment by leduy99** [comment]
Hi, I'm also having this though I didn't train much last week :( Please fix :(

**Comment by radames** [comment]
thanks @craigcitro it would be great to have Google Colab on the Google services status https://status.cloud.google.com/

**Comment by aritraMandal02** [comment]
Hi, I am getting this issue right now. My colab is not connecting to runtime, Only showing Allocating and after a long time it says 'No backend available. Please try again later.' Tried with different accounts not fixing.

**Comment by Onyoursix** [comment]
Also getting no back end issue, good to know it isn't just me!

**Comment by aritraMandal02** [comment]
Thanks. It is working now.

**Comment by NomaanMalick** [comment]
I have been getting this error message for the last few days. Is there any solution?

**Comment by 786unknown420** [comment]
Facing same issue

**Comment by danielpm307** [comment]
I think to check your running code before executing it. I have this problem and i read rules and there is a section for that. I hope its nor be permanent because we are just tinkering with our code for learning.

file hosting, media serving, or other web service offerings not related to interactive compute with Colab
downloading torrents or engaging in peer-to-peer file-sharing
using a remote desktop or SSH
connecting to remote proxies
mining cryptocurrency
running denial-of-service attacks
password cracking
using multiple accounts to work around access or resource usage restrictions
creating deepfakes

**Comment by danielpm307** [comment]
creating deepfakes :)

**Comment by joram5** [comment]
I have the same problem

**Comment by duythuc0201** [comment]
Also getting no back end issue, good to know it isn't just me!

**Comment by duythuc0201** [comment]
I have the same problem
