### ISSUE TITLE
No backend with GPU/TPU available. 

### ISSUE THREAD

**Issue by Tenoke** [googlecolab/colabtools#969]
I find myself unable to start a GPU or TPU runtime today from my account. The error looks like 
[this](https://usercontent.irccloud-cdn.com/file/zYqvQf45/image.png).

I'm not sure if Colab is silently flagging people for over-usage - I wrote a popular blog post on training GPT2-1.5b days ago, so maybe someone flagged me, or maybe they saw my recent usage, while prototyping with Jax and TPUs - I am not sure.

Possibly related to https://github.com/googlecolab/colabtools/issues/968

**Comment by koshian2** [comment]
I am facing a similar problem.
Even though TPU training, the runtime is dropped in about 3 hours and training does not progress at all. I know that even TPU training have restrictions on long-term use, but this is too severe.

**Comment by sayradley** [comment]
I can also confirm this issue became intense. Obviously I appreciate TPUs public availability greatly - thank you Google, but I'm no longer able to experiment with GANs easily with only 2-3h of TPU a day.

**Comment by Tenoke** [comment]
I now believe this is just an extension of their rate-limiting, which seems to have been getting harsher, rather than a bug. I don't expect anyone to respond, so I'm closing the issue.
