### ISSUE TITLE
New Notebook is not opening. 

### ISSUE THREAD

**Issue by gauravchandra7** [googlecolab/colabtools#97]
After clicking on "create a new Python 3 notebook", the notebook doesn't load, it has been 30 minutes.

**Comment by blois** [comment]
We are investigating some issues here, should be able to try again.

**Comment by blois** [comment]
This should be resolved now.

**Comment by blois** [comment]
Expected notebook creation time is under 10 seconds. If it takes much longer than that then please open an issue.
