### ISSUE TITLE
At

### ISSUE THREAD

**Issue by sreeragrnandan** [googlecolab/colabtools#972]
At https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/images/transfer_learning.ipynb#scrollTo=ro4oYaEmxe4r

(raw_train, raw_validation, raw_test), metadata = tfds.load(
    'cats_vs_dogs',
    split=['train[:80%]', 'train[80%:90%]', 'train[90%:]'],
    with_info=True,
    as_supervised=True,
)

why there is an error

KeyError: "Invalid split train[:80%]. Available splits are: ['train']"

**Comment by craigcitro** [comment]
You should report this on the TF repo where that notebook lives.
