### ISSUE TITLE
Upgrading PyTorch to v1.4.0 and torchvision to v0.5.0

### ISSUE THREAD

**Issue by soumith** [googlecolab/colabtools#973]
Hi folks,

We released a new PyTorch version v1.4.0 and torchvision v0.5.0.

The wheel links are:

PyTorch

CUDA 10.0

https://download.pytorch.org/whl/cu100/torch-1.4.0%2Bcu100-cp27-cp27m-linux_x86_64.whl
https://download.pytorch.org/whl/cu100/torch-1.4.0%2Bcu100-cp27-cp27mu-linux_x86_64.whl
https://download.pytorch.org/whl/cu100/torch-1.4.0%2Bcu100-cp36-cp36m-linux_x86_64.whl

CUDA 10.1

https://download.pytorch.org/whl/cu101/torch-1.4.0-cp27-cp27m-linux_x86_64.whl
https://download.pytorch.org/whl/cu101/torch-1.4.0-cp27-cp27mu-linux_x86_64.whl
https://download.pytorch.org/whl/cu101/torch-1.4.0-cp36-cp36m-linux_x86_64.whl

TorchVision

CUDA 10.0

https://download.pytorch.org/whl/cu100/torchvision-0.5.0%2Bcu100-cp27-cp27m-linux_x86_64.whl
https://download.pytorch.org/whl/cu100/torchvision-0.5.0%2Bcu100-cp27-cp27mu-linux_x86_64.whl
https://download.pytorch.org/whl/cu100/torchvision-0.5.0%2Bcu100-cp36-cp36m-linux_x86_64.whl

CUDA 10.1

https://download.pytorch.org/whl/cu101/torchvision-0.5.0-cp27-cp27m-linux_x86_64.whl
https://download.pytorch.org/whl/cu101/torchvision-0.5.0-cp27-cp27mu-linux_x86_64.whl
https://download.pytorch.org/whl/cu101/torchvision-0.5.0-cp36-cp36m-linux_x86_64.whl

If you require wheels for Python 3.7 / 3.8, you can find the links here: https://download.pytorch.org/whl/torch_stable.html

We're looking to having it updated in Colab.

Thanks very much.

cc'ing @colaboratory-team

**Comment by colaboratory-team** [comment]
b/148534149

**Comment by colaboratory-team** [comment]
Versions are now updated.
