### ISSUE TITLE
plt.show(), issue run through command line and through python command in google colab

### ISSUE THREAD

**Issue by CBD88** [googlecolab/colabtools#974]
plt.show() works perfectly fine and show image when run through command line of google colab, But when i run it through "!python run_file.py" it shows "<Figure size 600x1100 with 64 Axes>" instead. 

I tried "%matplotlib inline" command above "!python run_file.py". No change.

**Comment by colaboratory-team** [comment]
Within Colab's main Python process, matplotlib is configured to display inline in your browser. When you run ``!python run_file.py``, it starts a new python process that lacks this configuration. Showing matplotlib plots in this way is not supported.

**Comment by CBD88** [comment]
OK. Thanks.

**Comment by 0hex7** [comment]
> plt.show() works perfectly fine and show image when run through command line of google colab, But when i run it through "!python run_file.py" it shows "<Figure size 600x1100 with 64 Axes>" instead.
> 
> I tried "%matplotlib inline" command above "!python run_file.py". No change.

so whats the solution to this issue??
