### ISSUE TITLE
sympy sometimes renders, sometimes does not render

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#975]
- Describe the current behavior:
I use snippet render sympy in colab, but sympy sometimes does not render.

- Describe the expected behavior:
sympy renders always

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

**Comment by tnovikoff** [comment]
Is it an intermittent problem, or is it that for some cells it reliably renders and for other cells it reliably does not? If you can provide a repro notebook that would help enormously.

**Comment by vainaijr** [comment]
here is one example, this happens often
[sympy_.zip](https://github.com/googlecolab/colabtools/files/4173550/sympy_.zip)

**Comment by blois** [comment]
Does it work more reliably if you load MathJax on `post_run_cell` instead of `pre_run_cell`?

```python
from IPython.display import Math, HTML

def load_mathjax_in_cell_output():
  display(HTML("<script src='https://www.gstatic.com/external_hosted/"
               "mathjax/latest/MathJax.js?config=default'></script>"))
get_ipython().events.register('post_run_cell', load_mathjax_in_cell_output)
```

**Comment by vainaijr** [comment]
I think it works reliably with 'post_run_cell', I am seeing correct output now always, and 

'Loading [MathJax]/extensions/MathMenu.js
 Loading [MathJax]/extensions/MathZoom.js' 

appears after output displays correctly.

**Comment by blois** [comment]
Thanks, we'll have to update the sample.

**Comment by blois** [comment]
This should now be working without the explicit loading of MathJax.
