### ISSUE TITLE
'Intro to neural nets' colab notebook missing an optimizer

### ISSUE THREAD

**Issue by HarshaLaxman** [googlecolab/colabtools#98]
https://colab.research.google.com/notebooks/mlcc/intro_to_neural_nets.ipynb?hl=en

def train_nn_regression_model(

.....

# Create a linear regressor object.
  my_optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
  my_optimizer = tf.contrib.estimator.clip_gradients_by_norm(my_optimizer, 5.0)
  dnn_regressor = tf.estimator.DNNRegressor(
      feature_columns=construct_feature_columns(training_examples),
      hidden_units=hidden_units
  )

#This should be added as a dnn_regressor parameter
optimizer = my_optimizer

**Comment by craigcitro** [comment]
Good eye! Fixed upstream, should roll out within the next few days.
