### ISSUE TITLE
Can't load ipynbs from Google Drive as well as not being able to open a new python 3 notebook

### ISSUE THREAD

**Issue by rowebyrowe** [googlecolab/colabtools#981]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: Saved ipynbs that were previously created and/or used in colab are no longer listed in the open notebook pop-up list. When I tried going to google drive to access the file directly and open in colaboratory, I receive a network loading error: 
`Error loading https://apis.google.com/js/client.js
H/G</k.onerror@https://colab.research.google.com/v2/external/gapi_loader.js:14:415`

I get the same error code when I try to start a new python 2 or python 3 notebook, although the heading says Error instead of Network Loading Error.

- Describe the expected behavior: My ipynbs that are saved on drive would appear in the "open notebook" pop-up list. I would open a notebook from that list.

Colab should open a new python 3 notebook when I press "New Python 3 Notebook"

- The web browser you are using (Chrome, Firefox, Safari, etc.): Firefox

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by chrzzrd** [comment]
I'm having the exact same issue.

Currently on FireFox

**Comment by blois** [comment]
Errors loading `https://apis.google.com/js/client.js` usually indicate either a network error, extension or ad blocker. Can you try an incognito window?

**Comment by rowebyrowe** [comment]
I tried it on firefox incognito and it worked when I opened google drive and selected the notebook and "opened with" colaboratory. It was not there initially when I tried to load the file from colaboratory. After opening the file from drive, I opened a separate tab and was able to load a file directly from drive. Thank you blois. 

I'll look more into what is blocking it.

**Comment by chrzzrd** [comment]
I do use Ad Blockers & other extensions; however with them enabled prior to this instance it worked just fine. Now that I go back to colab everything works as normal, without me modifying any of my extension. I hypothesize it was either a problem with my network or possibly an update that created a bug which caused this temporarily?

**Comment by blois** [comment]
`https://apis.google.com/js/client.js` is the standard client library for accessing Google services (https://cloud.google.com/compute/docs/tutorials/javascript-guide). If that cannot be loaded then there's not much that can be done.

**Comment by chrzzrd** [comment]
I appreciate you explaining it thoroughly @blois.
