### ISSUE TITLE
(Minor issue) Scratch code cell covering/blocking the parameters hint window

### ISSUE THREAD

**Issue by ziatdinovmax** [googlecolab/colabtools#982]
Hi, I'm really enjoying the new Colab interface, with the scratch code cells being super-useful (person who came up with this idea is a genius, in my opinion). One minor thing that I noticed is that a scratch cell (or any other extra tab opened, like .py files) covers/blocks part of the parameter hints box. See the screenshot below. This can be a problem when working on a regular laptop (Pixelbook Go in this particular case) and not on a desktop with a sufficiently wide screen. I think that it would make sense to have the parameter hints in the "foreground" all the time. Anyway, hope this can be useful feedback. Thanks for reading.

![image](https://user-images.githubusercontent.com/34245227/73798123-f1b7e180-477f-11ea-9914-e32c26d68090.png)

**Comment by blois** [comment]
Thanks for the great feedback! We're taking a look at it.

**Comment by blois** [comment]
This issue should now be fixed.
