### ISSUE TITLE
Cannot retrieve current directory of mounted drive after reconnection

### ISSUE THREAD

**Issue by chiefpi** [googlecolab/colabtools#989]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: colab cannot retrieve current directory (e.g. %ls or %cd) of mounted drive after reconnection. Remounting is a solution.

Error:
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
ls: cannot open directory '.': Transport endpoint is not connected
```

- Describe the expected behavior: directory related commands should work after reconnection.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by tnovikoff** [comment]
Please note whether you are using the new Mount Drive UI or the old authentication flow: https://twitter.com/GoogleColab/status/1226929213560610818
