### ISSUE TITLE
Typo in 'Production ML Systems'

### ISSUE THREAD

**Issue by HarshaLaxman** [googlecolab/colabtools#99]
https://developers.google.com/machine-learning/crash-course/production-ml-systems

"Fortunately, many of the components in the preceding figure are reusable. Furthermore, you don't have to build all the components in Figure 2 yourself."

There is no figure 2, just figure 1.

**Comment by craigcitro** [comment]
Thanks! I sent a fix upstream, but I'm not sure how long the fix will take to percolate out.

(FWIW, the "Send Feedback" widget on that page is probably a better option for things that aren't strictly in Colab.)
