### ISSUE TITLE
Feature Request: Colab Pro to increase storage as well.

### ISSUE THREAD

**Issue by korakot** [googlecolab/colabtools#990]
- Describe the current behavior:

    Colab has **reduced** the storage from 350GB in GPU instance to just 64GB and increased storage for CPU instance to 100GB. This makes some storage-heavy use cases unable to run on Colab. 

    Now, Colab Pro is launched with **double** almost everything: GPU usage, time to run (12->24h), RAM (13->26GB). **EXCEPT** Storage is kept at 100GB/64GB (same as before).

- Describe the expected behavior:

    For Colab Pro, **increase** the storage to 200GB (doubling as well). Or 350GB (the same as before). Or even 700GB (doubling of before).

- The web browser you are using (Chrome, Firefox, Safari, etc.):

    Firefox.

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

    Any notebooks can show the storage limit.

**Comment by amarsinghen** [comment]
I agree as well. There should be more storage. I basically use colab pro for practicing with Kaggle competitions. Some of the datasets are very big. We have this extra RAM and GPU but can't do much with it if don't have enough storage to process the data.

**Comment by lamhoangtung** [comment]
Strongly agree

**Comment by mahmoodabed** [comment]
Yes. Please fix the storage issue.

**Comment by btomtom5** [comment]
Agreed! I'm willing to pay more if necessary to off-set the cost!

**Comment by Raavada** [comment]
please increase the stroage for gpu

**Comment by AntonSakharovAE** [comment]
Agree. Please fix it. 27Gb dataset I can download but can not unzip it. Google drive not an option because it works too slow for many files. Around 114 thousand images one epoch work more than 24 hours, for example the same amount of images the same code process one epochs for less then one hour.

**Comment by Andreas-Atanasiu** [comment]
Just adding my two cents in:

my tf.records data is aprox 16 gb, stored in Google Drive. After training for 2 hours the "quota" of the file is exceeded in Google Drive and I can't access it from Colab. (Can't download it either from G Drive)

Therfore, i'm on the same boat and would like to see a sensible storage increase for Colab Pro at 150 - 200 GB.

**Comment by cibic89** [comment]
Same problem here; went for google colab pro and found out very quickly I can't use it to for deep learning for kaggle competitions. Google drive, although it has tightly knit support, is not a good option at all as it throttles frequent resource access.

**Comment by BradSegal** [comment]
Same issue as well and using a drive mount eventually runs into an IO error and significantly slows training. Even if it was an option like with high ram in runtime settings, so if it's not needed the default won't waste resources

**Comment by ShivanshuPurohit** [comment]
Agreed. Even with MSCOCO dataset I faced storage issues when using all 400k images. 64 gb is way too less for any serious work. I  would rather pay $12 a month and have more storage than be stuck with a tiny disc.

**Comment by khursani8** [comment]
Yes, I feel more comfortable work with Colab, the only problem is it space is too small for me even for Colab Pro

**Comment by 7thstorm** [comment]
I have 25 million images around 500 GB. How can I use?

**Comment by korakot** [comment]
Colab Pro now has twice the storage just like I requested. Thank you.

**Comment by jonykarki** [comment]
@korakot is this really solved?

**Comment by cibic89** [comment]
> 
> 
> @korakot is this really solved?

Should be, for colab pro one gets 225 GB in total

**Comment by a-akram-98** [comment]
So if I paid for Colab pro I will get more than 200 GB of GPU runtime storage !?, I don't want to pay for nothing :D.

**Comment by cibic89** [comment]
Found that currently, the standard runtime (in active pro) gives you 225 GB, the GPU gives your 147 GB, and the TPU gives you 107 GB.

**Comment by jonykarki** [comment]
I've been using the GPU on the pro version frequently and the 147GB is sometimes still not enough. @a-akram-98 the total will be 147GB (like @cibic89 mentioned above) giving you about 110GB left after the system files.

**Comment by a-akram-98** [comment]
@jonykarki I saw some tutorials on the web saying if I have data set that exceeds the disk space I can save the data set on PAID google drive and train the model directly from the drive

**Comment by cibic89** [comment]
> 
> 
> @jonykarki I saw some tutorials on the web saying if I have data set that exceeds the disk space I can save the data set on PAID google drive and train the model directly from the drive

That's what I thought. Gdrive will severely throttle access for small files very quickly crippling deep learning using GPUs. This is even worse with TPUs but then again one should be loading all data in ram to fully utilise benefits of the technology.

**Comment by jonykarki** [comment]
> > @jonykarki I saw some tutorials on the web saying if I have data set that exceeds the disk space I can save the data set on PAID google drive and train the model directly from the drive
> 
> That's what I thought. Gdrive will severely throttle access for small files very quickly crippling deep learning using GPUs. This is even worse with TPUs but then again one should be loading all data in ram to fully utilise benefits of the technology.

Exactly! Using GDrive slows things down.

**Comment by a-akram-98** [comment]
So actually there is no solution till google increase it or add extra paid service.

**Comment by cibic89** [comment]
> 
> 
> @jonykarki I saw some tutorials on the web saying if I have data set that exceeds the disk space I can save the data set on PAID google drive and train the model directly from the drive

That's what I thought. Gdrive will severely throttle access for small files very quickly crippling deep learning using GPUs. This is even worse with TPUs but then again one should be loading all data in ram to fully utilise benefits of the technology.

> 
> 
> So actually there is no solution till google increase it or add extra paid service.

It's probably engineered that way. Fast.ai with GPU instances such as nvidia 1080 Ti/2080 Ti (12 GB) or Titan RTX (24 GB) are the next cost effective infrastructure approaches. If you are doing transfer learning then you might get away with 1070/1080/2070/2080 having 8 GB of VRAM but this trend is fading fast for cutting edge models in competitive situations such as Kaggle competitions. See a GPU deep learning training performance comparison here: https://i0.wp.com/timdettmers.com/wp-content/uploads/2018/08/performance_TPU_RTX_GPUs.png, more details with batch sizes here: https://lambdalabs.com/blog/choosing-a-gpu-for-deep-learning/

**Comment by pratt3000** [comment]
any updates? how much storage does it provide now?

**Comment by giangdip2410** [comment]
Colab Pro current supports 225G disk space for TPU & 147G disk space for GPU.

**Comment by xinxin8816** [comment]
> Colab Pro current supports 225G disk space for TPU & 147G disk space for GPU.

Hi, giangdip2410. Does pro user still have 225G disk space for TPU & 147G disk space for GPU now?  It is said that only pro plus users can get it.

**Comment by stefangrotz** [comment]
Alternately, a better Google Drive integration would work for me as well. When you mount Drive and copy to many files to it, the process stops working at some point.

**Comment by SaeedArisha** [comment]
Can someone guide me about disk space of colab pro plus? With GPU I only get 128 GB, my data is around 200GB, any guidance?

**Comment by FahadGhaffar** [comment]
Recently, I bought a Colab Pro and mounted my drive (2 TB allowed) with it, but it gave me an error when it reached 188 GB [Errno 28] No space left on the device.

**Comment by zaynabmu** [comment]
> Same issue as well and using a drive mount eventually runs into an IO error and significantly slows tr

the same issue with me ,  did you try colab pro + ? if yes it is solve the problem ? thank you in advance

**Comment by srikanteswartalluri** [comment]
Even I have the same question, will colab pro plus give more than 300GB disk space ?

**Comment by srikanteswartalluri** [comment]
Tried collab pro + , disk space is still 226 GB max.

**Comment by imrnh** [comment]
> Alternately, a better Google Drive integration would work for me as well. When you mount Drive and copy to many files to it, the process stops working at some point. I understand that you don't want too many i/o operations on drive, but please give us a way to copy big folders out of the workspace.
> 
> Often it is impossible to create a tar.gz of a folder because the disk space is already full. A option like "save folder as zip/tar on Drive" would be great.

@googlecolab please add this feature.

**Comment by maxall41** [comment]
Bump

**Comment by kbre93** [comment]
I also think more space would help a lot for large datasets. Currently have mounted a google drive and paid for extra space but the load time is too slow and there's not enough storage to bring the data into the VM.
