### ISSUE TITLE
Install Solaris library  

### ISSUE THREAD

**Issue by manishsharma28** [googlecolab/colabtools#992]
Colab is having some issues with 'gdal=3.0.2' which is required for 'Solaris' library.
Upon installing 'Solaris' it starts collecting 'gdal=3.0.2' and gives the following error. 

Collecting gdal>=3.0.2
  Using cached https://files.pythonhosted.org/packages/ae/09/cac5021db34f5c95c6a660b90e5d27062a520fe32a0493f68d07a7055d30/GDAL-3.0.4.tar.gz
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

The pre-installed version of 'gdal' on colab is 2.2.2

**Comment by tnovikoff** [comment]
Please provide a minimal notebook to reproduce

**Comment by manishsharma28** [comment]
Follow the link for colab notebook:

https://colab.research.google.com/drive/1DNphb2xvz2_Ajnzx8t7HxUWG8nN-fqS7

**Comment by mananeau** [comment]
Using:
```!add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
!apt-get update
!apt-get install python-numpy gdal-bin libgdal-dev python3-rtree
```
and 
```
!pip install torch==1.3.1
!pip install torchvision==0.4.2
```
solved the problem for me :)

**Comment by manishsharma28** [comment]
Thanks @mananeau

**Comment by ramkumarperumal** [comment]
While installing solaris in colab gdal issue is solved using,

```
!add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
!apt-get update
!apt-get install python-numpy gdal-bin libgdal-dev python3-rtree
```
and

```
!pip install torch==1.3.1
!pip install torchvision==0.4.2

```
But i have issue with shapely,`

> ERROR: Could not find a version that satisfies the requirement shapely>=1.7.1dev (from solaris) (from versions: 1.0a7, 1.0b1, 1.0b2, 1.0b3, 1.0b4, 1.0rc1, 1.0rc2, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.15, 1.2b1, 1.2b2, 1.2b3, 1.2b4, 1.2b5, 1.2b6, 1.2b7, 1.2rc1, 1.2rc2, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9, 1.2.10, 1.2.12, 1.2.13, 1.2.14, 1.2.15, 1.2.16, 1.2.17, 1.2.18, 1.2.19, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.5.13, 1.5.14, 1.5.15, 1.5.16, 1.5.17, 1.6a1, 1.6a2, 1.6b1, 1.6b2, 1.6b3, 1.6b4, 1.6b5, 1.6.0, 1.6.1, 1.6.2, 1.6.2.post1, 1.6.3, 1.6.4, 1.6.4.post1, 1.6.4.post2, 1.7a1, 1.7a2, 1.7a3, 1.7b1, 1.7.0)
> ERROR: No matching distribution found for shapely>=1.7.1dev (from solaris)

I am getting above error but max available version shapely is 1.7.0.

**Comment by bartek2101** [comment]
@ramkumarperumal 
try:
pip install git+git://github.com/toblerity/shapely.git@master
that worked for me

**Comment by AnupamaRajkumar** [comment]
Hi,

I have been trying to install gdal on google colab. I have tried all the steps mentioned above but to no avail. I still keep getting this error. Any help/pointers would be highly appreciated.

Building wheel for gdal (setup.py) ... error
  ERROR: Failed building wheel for gdal
  Running setup.py clean for gdal
Failed to build gdal
Installing collected packages: imgaug, albumentations, gdal, solaris
  Found existing installation: imgaug 0.2.9
    Uninstalling imgaug-0.2.9:
      Successfully uninstalled imgaug-0.2.9
  Found existing installation: albumentations 0.1.12
    Uninstalling albumentations-0.1.12:
      Successfully uninstalled albumentations-0.1.12
  Found existing installation: GDAL 2.2.2
    Uninstalling GDAL-2.2.2:
      Successfully uninstalled GDAL-2.2.2
    Running setup.py install for gdal ... error
  Rolling back uninstall of GDAL
  Moving to /usr/local/lib/python3.7/dist-packages/GDAL-2.2.2.dist-info/
   from /usr/local/lib/python3.7/dist-packages/~DAL-2.2.2.dist-info
  Moving to /usr/local/lib/python3.7/dist-packages/__pycache__/gdal.cpython-37.pyc
   from /tmp/pip-uninstall-ambl0xme/gdal.cpython-37.pyc
  Moving to /usr/local/lib/python3.7/dist-packages/__pycache__/gdalconst.cpython-37.pyc
   from /tmp/pip-uninstall-ambl0xme/gdalconst.cpython-37.pyc
  Moving to /usr/local/lib/python3.7/dist-packages/__pycache__/gdalnumeric.cpython-37.pyc
   from /tmp/pip-uninstall-ambl0xme/gdalnumeric.cpython-37.pyc
  Moving to /usr/local/lib/python3.7/dist-packages/__pycache__/gnm.cpython-37.pyc
   from /tmp/pip-uninstall-ambl0xme/gnm.cpython-37.pyc
  Moving to /usr/local/lib/python3.7/dist-packages/__pycache__/ogr.cpython-37.pyc
   from /tmp/pip-uninstall-ambl0xme/ogr.cpython-37.pyc
  Moving to /usr/local/lib/python3.7/dist-packages/__pycache__/osr.cpython-37.pyc
   from /tmp/pip-uninstall-ambl0xme/osr.cpython-37.pyc
  Moving to /usr/local/lib/python3.7/dist-packages/gdal.py
   from /tmp/pip-uninstall-bsko554w/gdal.py
  Moving to /usr/local/lib/python3.7/dist-packages/gdalconst.py
   from /tmp/pip-uninstall-bsko554w/gdalconst.py
  Moving to /usr/local/lib/python3.7/dist-packages/gdalnumeric.py
   from /tmp/pip-uninstall-bsko554w/gdalnumeric.py
  Moving to /usr/local/lib/python3.7/dist-packages/gnm.py
   from /tmp/pip-uninstall-bsko554w/gnm.py
  Moving to /usr/local/lib/python3.7/dist-packages/ogr.py
   from /tmp/pip-uninstall-bsko554w/ogr.py
  Moving to /usr/local/lib/python3.7/dist-packages/osgeo/
   from /usr/local/lib/python3.7/dist-packages/~sgeo
  Moving to /usr/local/lib/python3.7/dist-packages/osr.py
   from /tmp/pip-uninstall-bsko554w/osr.py
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tng6h7da/gdal/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tng6h7da/gdal/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-djdtwdus/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
Requirement already satisfied: rio-tiler in /usr/local/lib/python3.7/dist-packages (2.0.5)

I figured that whatever I try, gdal version is always 2.2.2 and I have tried everything to upgrade the version to >=3.0.2 but to no avail.
