### ISSUE TITLE
Tensorflow Data Validation workshop notebook fails by default

### ISSUE THREAD

**Issue by lassehh** [googlecolab/colabtools#996]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: **The TFDV chicago_taxi notebook fails to fetch the data it needs from storage.googleapis.com.**

- Describe the expected behavior: **It shouldn't fail.**

- The web browser you are using (Chrome, Firefox, Safari, etc.): **Chrome/Firefox.**

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*): **https://colab.research.google.com/github/tensorflow/tfx/blob/master/docs/tutorials/data_validation/tfdv_basic.ipynb (Step 2 fails. This is the default notebook with no changes to it.)**

**Comment by colaboratory-team** [comment]
Hello, thanks for the report.

That notebook is not owned by colaboratory; it can be found here: http://github.com/tensorflow/tfx/blob/master/docs/tutorials/data_validation/tfdv_basic.ipynb

The best place to raise this issue would be in that repository.
