### ISSUE TITLE
Ipywidgets not showing on iPad 7 Google colab

### ISSUE THREAD

**Issue by Blaizzy** [googlecolab/colabtools#997]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
   Ipywidgets are not showing on iPad output 

- Describe the expected behavior:
   I would if the widgets appeared when I execute the line of code 

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Both chrome and safari 

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1xO6sGHpVyLr4Q4aESJWhwwZfGCinU89F

**Comment by tnovikoff** [comment]
Tracking at b/150028340

FWIW some general information about widgets in Colab can be found at:
https://colab.research.google.com/notebooks/widgets.ipynb
and
https://stackoverflow.com/questions/47269168/ipywidgets-with-google-colaboratory

**Comment by Blaizzy** [comment]
Thank you @tnovikoff  I just saw the progress it is promising. It works tho still some parts it doesn't render properly. If you could solve this one problem it would mean the world to me. I desperately want to use ipywidgets in colab on my iPad.

**Comment by blois** [comment]
This should now be working.

**Comment by Blaizzy** [comment]
It is working now, thank you very much for your help.
You don’t know but you just changed my life.

**Comment by blois** [comment]
Glad to hear :)
